### ISSUE TITLE
Contributions for translations to launchpad are not synced

### ISSUE THREAD

**Issue by hanklank** [transmission/transmission#100]
The translations done in launchpad doesn't sync to transmission, at least not for the latest years, and at least not for Swedish. I did update and correct the Swedish translation to 100% for trunk in launchpad in 2014, and it's still not included here (as an updated sv.po). Others seem have the same problem - see for example. https://github.com/transmission/transmission/pull/25.  So, please tell us, what can we translators do if we would like to get our work included?? I think just doing a pull request here would be a fair way until (sync issues) are fixed, but at the moment, I see that those pull requests are closed (ex. https://github.com/transmission/transmission/pull/93) and refereed to launchpad (which doesn't seem to work - moment 22).

Swedish translation in launchpad: https://translations.launchpad.net/transmission/trunk/+pots/transmission/sv/+translate

**Comment by mikedld** [comment]
Would it be okay to move .po translations to Transifex? I'd love to keep it all in one place, and hope to move Mac client translations there sometime soon... I don't really know what the downsides would be (apart from people learning to go to new location), but I could see some upsides from where I stand (but I'm a developer, so...).

**Comment by hanklank** [comment]
@mikedld  Anything that suits the project better - if Transifex is what works best for future development for you, by all means go for it. I can't imagine anyone would have any strong opinion against it - a lot of well known project use that platform, ( I often translate stuff there too).

**Comment by piotrdrag** [comment]
As a translator, I prefer Transifex over Launchpad, but I would be OK with anything as long as you regularly push/pull translations.
