### ISSUE TITLE
A Gui interface to the daemon, which keeps running as a different user than the interface user.  

### ISSUE THREAD

**Issue by MaharishiCanada** [transmission/transmission#1000]
I know that the daemon can run as the user of our choice. If we use a browser to interface with the daemon, this is the user that iptables (on Ubuntu) sees, which is what I want.   However, if I use the transmission-gtk interface, the iptables sees the transmission-gtk user (i.e. , me as the system user) as the user, which is not what I want.  I would like to have an interface to the daemon that is identified as a bit torrent client (which is not the case for the browser) so that, when I use this interface, the iptables sees the daemon user, and, when I click on a torrent in my browser, this interface is called.

**Comment by mikedld** [comment]
I'm not sure what "qtk" means. We have GTK+ client (transmission-gtk) which doesn't support remote sessions. If you want to connect to your deamon with a GUI, we have a Qt client (transmission-qt) which does support that, and a web client.

**Comment by MaharishiCanada** [comment]
I have to check again what is transmission-qt, but I think it is a command line interface. Yes, I need an interface to the daemon. This is a first requirement, but have  a second and a third requirement. The second is that  it must offers a user interface similar to what is offered by transmission-gtk or a web-client.  The third requirement is that it must be associated with the mime type of a torrent, just like transmission-gtk is, so that when I click on a torrent on my desktop or on any page in a browser, say Firefox,  it is called by the system. Your web client does not meet this third requirement. I think transmission-qt does not meet the second and the third. Finally, transmission-gtk, satisfies the second and the third requirement, but it does not use the daemon as a backend, the first requirement.   This first requirement is important because I want the transmission application to run as a different user, for security reason. The second requirement is important for obvious reason. The third is important because most of the times we click on a link  in a web page, say using Firefox, to get a torrent.

**Comment by MaharishiCanada** [comment]
Oh Well ! I don't know why I had in mind that transmission-qt was a command line interface !  I can believe this.  Anyway, thank you. Yes, transmission-qt is exactly what I need!  It is a gui interface to the daemon and well, I have not checked, but I think it will be called when I click on a torrent.

**Comment by MaharishiCanada** [comment]
I will close the issue, because the GUI interface to the daemon officially exists as transmission-qt. The issue is that, for some reason, this GUI interface becomes more than an interface. It becomes the actual system user that manages the torrent.  This does not happen when we use the web client as an interface.
