### ISSUE TITLE
Port is closed when connected to IPsec service

### ISSUE THREAD

**Issue by TomHsiung** [transmission/transmission#1002]
I think the software use automatic method to make the server reachable from outside (such that other peers could find my machine). Interestingly, on my NAT gateway, I don't set up any port-forwarding iptables rules (to let outside initiators able to connect my client behind the NAT gateway). I only set up NAT rules (so that my client initiators behind the NAT gate could connect Internet).

I also set up NAT rules for my remote strongSwan servers. But I don't know why this issue happened.

I think something is wrong with the NAT-PMP / UPnP technology. Some thing must broken after I turn on the strongSwan, which makes the NAT-PMP / UPnP of the software on clients behind NAT gateway not working.

So, manual NAT port forwarding iptables rule(s) is plausible. But, my clients connected to strongSwan server don't have fixed virtual IP addresses. How to deal with this issue?

Thank you

PS: I initially created issue on the IPsec support website here, https://wiki.strongswan.org/issues/3168

**Comment by vlcty** [comment]
I think this is not a transmission problem. The UPnP port forwarding request is dropped before it's routed inside the VPN tunnel or at the VPN server.

In the short the NAT punching feature of the mTP protocol may help you being able to seed. The real goal is to get IPv6 working/adopted.

**Comment by ckerr** [comment]
Closing based on previous comment about the root of the problem.
