### ISSUE TITLE
GUI is duplicated when adding torrents

### ISSUE THREAD

**Issue by sklprogs** [transmission/transmission#1004]
Hello! I'm using Transmission 2.94 (d8e60ee44f) (GTK version), which is default in Debian Buster (32-bit). I have a very annoying issue: each time I add a new torrent from a browser, should it be from a magnetic link or a torrent file, Transmission window and tray icon are literally duplicated. One window shows torrent titles like 26fdc332... before metadata were fetched, and another one - content titles after fetching the metadata. The "newer" window continues to function properly, however, this bug if pretty frustrating since I can't instantly tell which window is "newer".

I have the following output in a terminal:
`(transmission:8774): Gdk-CRITICAL **: 22:31:49.287: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[11841:11841:0914/223405.676972:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

(transmission-gtk:9710): GLib-CRITICAL **: 22:35:05.249: g_file_test: assertion 'filename != NULL' failed
Error creating proxy: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:» (g-io-error-quark, 13)
Error creating proxy: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:» (g-io-error-quark, 13)
Error creating proxy: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:» (g-io-error-quark, 13)
Error creating proxy: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:» (g-io-error-quark, 13)
Error creating proxy: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:» (g-io-error-quark, 13)

** (transmission-gtk:9710): WARNING **: 22:35:06.777: Failed to create proxy for org.freedesktop.Notifications

(transmission-gtk:9710): libayatana-appindicator-WARNING **: 22:35:06.782: Unable to get the session bus: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:»

(transmission-gtk:9710): LIBDBUSMENU-GLIB-WARNING **: 22:35:06.785: Unable to get session bus: Неизвестный или неподдерживаемый транспорт «disabled» для адреса «disabled:»

(transmission-gtk:9710): Gdk-CRITICAL **: 22:35:07.124: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

** (transmission-gtk:9710): CRITICAL **: 22:35:09.077: gtr_file_trash_or_remove: assertion 'filename && *filename' failed`

**Comment by mikedld** [comment]
This doesn't look like it has anything to do with Transmission. You need to fix DBus on your system.
