### ISSUE TITLE
Saving a .resume file fails on Windows due to the created file having an incomplete name

### ISSUE THREAD

**Issue by AntonPetrochenko** [transmission/transmission#1009]
Upon adding a torrent with the symbol : in it, the target file name for the .resume for the torrent is abruptly cut off, containing all the letters up to that symbol and even lacking an extension. 

Issue walkthrough from observation:
- Metadata is downloaded properly
- File created and opened with incomplete name
- Writing to _a file_ fails
- Torrent is aborted with an error, all attempts at downloading it and related procedures are ceased
- Strangely enough, the broken file is never closed and it's impossible to rename or delete it. Referenced by filename, perhaps?
![image](https://user-images.githubusercontent.com/52828796/65622580-c5c56c00-dfe7-11e9-8fc5-8dd33b7d33c0.png)
![image](https://user-images.githubusercontent.com/52828796/65622646-e7beee80-dfe7-11e9-9d40-628ca8a1687d.png)

**Comment by AntonPetrochenko** [comment]
Cause:
tfter some research (that admittedly should have come from the top of the head), the : symbol turned out to be a special symbol in Windows and is not allowed in filenames. A fix would be to escape/replace them, or to stop using filenames that come from arbitrary sources.

**Comment by mikedld** [comment]
See #122.
