### ISSUE TITLE
[FEATURE] Add "Transferring" filter

### ISSUE THREAD

**Issue by 1000hz** [transmission/transmission#101]
Something I've always wished Transmission had is a filter to see which torrents are currently transferring data. I'm often seeding hundreds of torrents and will see that data is being transferred via the macOS dock, but can't easily tell which torrent(s) is active.

**Comment by Moorre** [comment]
Try View --> Sorted order --> Active

Sorry, I cant tell you, what is native names of this. I have RU localization active.

**Comment by 1000hz** [comment]
Nice! That certainly helps. I still think this feature would be a nice addition though.

**Comment by gvigner** [comment]
I reported similar problem here :
https://github.com/transmission/transmission/issues/114

But I was answered that it's correct to have torrents with DL or UL at speed 0.0 KB/s in "Active" and "Seeding" tabs, while they are actually inactive. It's pretty confusing and when we have many torrents, the really active ones are lost in a sea of inactive torrents.

At least, the Active tab should not contain torrents which UL or DL speed is at 0.0 KB/s.

Also, the Seeding tab is a bit confusing to me, does it only contain completed torrents or does it contain completed torrents and torrents which are being downloaded and  seeding at the same time ?

In my opinion, uTorrent tabs arrangement is more convenient, I would appreciate to have the same arrangement in Transmission.

**Comment by ckerr** [comment]
The GTK, Qt, and web clients have this via setting the drop-down state filter to 'Active'

**Comment by Harm133** [comment]
@ckerr This one can be closed :)
