### ISSUE TITLE
using pi4, transmission cache memory leak occur.

### ISSUE THREAD

**Issue by adamzchmbr** [transmission/transmission#1011]
hi guys.
I have a pi4 (memory 4g) with raspbian buster.
When using transmission-daemon, cache memory is increased more and more.
To be specific, i installed transmission-daemon (ver. 2.94 on raspbian buster) and edited some setting. (like rpc connect, watching seed folder)
in idle state, memory is stable.
But add some torrent and it is download state, cache memory is increased.
when i using pi3B+ on raspbian jessie and stretch, it was not happen. (Of course it is not the 2.94 version.)
does anyone have a solution?

thank you.

**Comment by ben-ba** [comment]
Maybe still the same issue; #313

**Comment by LorisAlbanese** [comment]
Same issue here. Raspberry Pi4 (2G) , Raspbian 10.2, transmission-daemon ver 2.94-2, Out Of Memory issue occur:

Out of memory: Kill process 5296 (transmission-da) score 835 or sacrifice child
Killed process 5296 (transmission-da) total-vm:1809052kB, anon-rss:1651472kB, file-rss:9808kB, shmem-rss:0kB

**Comment by ShredderWalnut** [comment]
I assume my issue is the same:

```
raspberrypi kernel: [17280.564738] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=transmission-da,pid=8499,uid=1000
raspberrypi kernel: [17280.564835] Out of memory: Killed process 8499 (transmission-da) total-vm:165008kB, anon-rss:78744kB, file-rss:7368kB, shmem-rss:0kB, UID:1000 pgtables:288kB oom_score_adj:0
raspberrypi kernel: [17282.673068] oom_reaper: reaped process 8499 (transmission-da), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
raspberrypi systemd[1]: transmission-daemon.service: Main process exited, code=killed, status=9/KILL
raspberrypi systemd[1]: transmission-daemon.service: Failed with result 'signal'.
```

**Comment by LorisAlbanese** [comment]
make (more) swap available. this solved my problem.

**Comment by ckerr** [comment]
Is this still an issue in Transmission 4?

**Comment by LorisAlbanese** [comment]
adding swap problem vanish.
