### ISSUE TITLE
Why the system user when we use transmission-qt is not the daemon user? Could we have that?

### ISSUE THREAD

**Issue by Dominic-Mayers** [transmission/transmission#1019]
In Ubuntu with systemd, we can choose under which system user a daemon runs  by adding 
```
[Service]
User=systemuserofmychoice
```
in the systemd configuration for that daemon. In my case, I added this configuration code in the file `/etc/systemd/system/transmission-daemon.service.d/newuser`. When I use the web client to the transmission-daemon, as expected, `systemuserofmychoice` is the user that is seen in the firewall of Ubuntu. However, when I use transmission-qt, which is supposed to be simply an interface to the daemon, but with the same features as transmission-gtk,  the firewall does not see the daemon user `systemuserofmychoice`. It sees the transmission-qt user.  Why is that? Can we have the daemon user `systemuserofmychoice`, as we have with the web client? 

In case one would ask why I don't use the web client then. The problem with the web client is that it's not called when I click on a torrent. I must open the web client and then open the torrent from there. In fact, in my case, perhaps because of some configuration issue, I have to save the torrent first and then open the torrent file with the web client.   

It might be a constraint with Ubuntu, but then it's strange that it does not apply to the web  client.

**Comment by ckerr** [comment]
TBH I don't understand this bug report. This feels more like a configuration issue than a bug in Transmission?

You can run transmission-daemon and transmission-qt under whichever user you choose, depending on how you set up your system and how you set up Transmission. You can even run different sessions with different configuration files at the same time.

**Comment by Dominic-Mayers** [comment]
This was a long time ago. So, the problem might  not be there anymore. I have not checked, because I do not use transmission anymore. However, it's important to realize that the issue is the user seen in the firewall of Ubuntu. The configuration of Ubuntu might obviously have a role to play, but it remains that  `systemuserofmychoice` was seen in the firewall with the web client, but not with  transmission-qt. It could be that the issue was in the configuration of transmission-qt, but at the time, I could not find anyway to change the configuration of transmission-qt to choose the user that will be seen in the firewall. If I remember well, there was a way to formally choose the user under which transmission-qt, but at the time, that was not the user seen in the firewall. I remember that my thought back then was that the firewall was not properly  informed of the user chosen in the configuration of transmission-qt.
