### ISSUE TITLE
crash in 2.94 in transmission-qt when preallocation is enabled

### ISSUE THREAD

**Issue by YahelF19** [transmission/transmission#1020]
Torrent starts to load and stops with an error
after removing the torrent and trying to add it, transmission again falls.
Whatever torrents I add, it behaves like this with everyone, downloads a little and stops.

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	transmission-qt.exe
  Версия приложения:	2.94.0.0
  Отметка времени приложения:	5ae8a6b1
  Имя модуля с ошибкой:	transmission-qt.exe
  Версия модуля с ошибкой:	2.94.0.0
  Отметка времени модуля с ошибкой:	5ae8a6b1
  Код исключения:	c0000005
  Смещение исключения:	00000000000ab237
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	2878
  Дополнительные сведения 2:	28785b374044a5ec616c215505628397
  Дополнительные сведения 3:	2419
  Дополнительные сведения 4:	2419de77cf321bc2036a566ebe3ddd8b

![Uploading Безымянный.jpg…]()

**Comment by YahelF19** [comment]
![Безымянный](https://user-images.githubusercontent.com/56619276/66887349-62759b00-efe3-11e9-8ed5-0fcb60f92c32.jpg)

**Comment by sergey-s-betke** [comment]
Transmission crashed when `preallocation` is set to non-zero. Disable `preallocation` (set to zero)...
