### ISSUE TITLE
Dead donation link

### ISSUE THREAD

**Issue by LeopoldTal** [transmission/transmission#1023]
On the [donations page](https://transmissionbt.com/donate/), there is a link to the [`trac.transmissionbt.com` wiki](https://trac.transmissionbt.com/). On *that* page, there is a link to `https://transmissionbt.com/donate.html`, which 404s.

Suggested fixes:

1. The donations page should probably point to [the github wiki `https://github.com/transmission/transmission/wiki`](https://github.com/transmission/transmission/wiki) instead.
2. The `trac.transmissionbt.com` wiki should point to [the current donations page `https://transmissionbt.com/donate/`](https://transmissionbt.com/donate/).
3. `https://transmissionbt.com/donate.html` should redirect to `https://transmissionbt.com/donate/` because URL stability is nice.

**Comment by mikedld** [comment]
Please open an issue against [transmission/transmission.github.io](/transmission/transmission.github.io) instead.
