### ISSUE TITLE
lot of log : (errno 22 - Invalid argument) (net.c:290)

### ISSUE THREAD

**Issue by kifeo** [transmission/transmission#1031]
Hello,

It look to run fine, but in the logs I have :

> Couldn't connect socket 20 to 80.98.38.235, port 58237 (errno 22 - Invalid argument) (net.c:290)

my version is with the package  2.92-2+deb9u1

**Comment by ckerr** [comment]
Sounds like [this might be the problem](https://stackoverflow.com/a/4200797):

> I figured out what the issue was, I was first getting a ECONNREFUSED, which on Linux I can just retry the connect() after a short pause and all is well, but on FreeBSD, the following retry of connect() fails with EINVAL.

`tr_netOpenPeerSocket()` could solve this by being more selective about which errors it logs and/or adding special handling for `ECONNREFUSED`.
