### ISSUE TITLE
Android Server?

### ISSUE THREAD

**Issue by ddogishere** [transmission/transmission#1035]
Is it possible to make transmission in my android TV into a server to be access remotely?
Thanks.

**Comment by ckerr** [comment]
There aren't any plans for making Android binaries. This is a small project with few maintainers, so it's unlikely that this will happen in the future either.

**However** the project has accepted Android-specific pull requests, so I know there _are_ people out there optimizing Transmission to run on Android. If there's anything that can be done in `transmission/transmission` to make life easier for those people, I'm supportive of that. I just don't want to commit the main project to maintaining another binary release series.

**Comment by depler** [comment]
@ckerr @ddogishere actually, there is a way to run transmission on android as native binary (kind of). There is project called Termux: https://github.com/termux/termux-app. It is an extremely powerful linux environment emulator. For example, it allows to install clang (and other development stuff) and compile binaries right within your android device. Moreover, it is already contains transmission as single package, which can be installed as `pkg install transmission`. Some more actions required to make run as service and autostart on boot, but it works just fine.

**Comment by ddogishere** [comment]
Thanks will look into it.

Kind regards
