### ISSUE TITLE
Seeding ratio not honoured while still downloading

### ISSUE THREAD

**Issue by ljgww** [transmission/transmission#105]
It is available for user to set seeding 'goal' in Transmission preferences (tab 'Seeding', section 'Limits') by enabling 'Stop seeding at ratio [value box]' 

Indeed, Transmission will stop at user defined ratio, only if user has 100% of the torrent and torrent is in 'seeding' state.  

But, If user has not completed download and torrent is still in 'downloading' state, seeding of local chunks may go over 'seeding ratio' limit. [Observed that seeding works as soon as there is some content to seed, that is expected even during download]

On slow downloading torrents (over a week, month...) seeding ratio may be arbitrary and typically will go over limit, sometimes, way over limit depending on conditions.

IMHO Stop seeding (based on ratio) shall be honoured in all active torrent modes.

**Comment by cfpp2p** [comment]
Transmission out of the box does not allow zero speed upload, (nor does it consistently allow download zero speed).
https://github.com/cfpp2p/transmission/commit/2ae211dd57ae19a0423e7fd33e552c643460eae9
https://forum.transmissionbt.com/viewtopic.php?f=1&t=17757#p72913
https://forum.transmissionbt.com/viewtopic.php?f=4&t=17832#p73024

**Comment by ckerr** [comment]
You're asking for an upload cap, not a seeding ratio -- a torrent isn't a seed until it finishes downloading.

I'd personally be opposed to upload caps (as opposed to seeding ratios) for the same reason that Transmission doesn't allow zero upload speeds out-of-the-box; it tries to encourage sharing while downloading.
