### ISSUE TITLE
[Feature request] Better rounding of ratio

### ISSUE THREAD

**Issue by deejam** [transmission/transmission#1053]
I suggest a better rounding of the ratio depending on its value. When the ratio is low, higher precision than what is currently implemented would be beneficial. Higher ratios requires less precision.

Examples:
Low ratios would benefit from higher precision (two decimals): 0.14, 1.05, 4.93.
Medium ratios need less precision (one decimal): 5.1, 9.7, 51.7.
High ratios needs no precision (no decimal): 100, 152.

**Comment by ckerr** [comment]
Sounds good to me. If someone wants to patch [tr_strratio()](https://github.com/transmission/transmission/blob/main/libtransmission/utils.cc#L1153) this would probably be a good first issue. There is already a place in tests/libtransmission/utils-test to add tests for the changes, too.

**Comment by ckerr** [comment]
Fixed by #2508
