### ISSUE TITLE
[bug] The site is down

### ISSUE THREAD

**Issue by neverov** [transmission/transmission#1058]
Can't access https://transmissionbt.com/.
<img width="1552" alt="transmissionbt com 2019-11-19 09-31-20" src="https://user-images.githubusercontent.com/57802/69170690-60ee3580-0aaf-11ea-9ed7-ca3d07c2763a.png">

**Comment by dausruddin** [comment]
Currently it is working fine.

**Comment by neverov** [comment]
Yup, seems to be working fine for me too, thanks!
