### ISSUE TITLE
Torrents with web seeds cause transmission-daemon to eat 100% CPU

### ISSUE THREAD

**Issue by patrakov** [transmission/transmission#1061]
This is reproducible both on Arch Linux and on OpenWRT, with any torrent that includes a web seed.

To reproduce:

```
wget https://torrents.endlessm.com/torrents/eos-amd64-amd64-base-3.7.4-iso.torrent
transmission-daemon
transmission-remote 127.0.0.1 --download-dir /home/myuser --downlimit 200
transmission-remote 127.0.0.1 --add eos-amd64-amd64-base-3.7.4-iso.torrent
top
```

Result: even though instructed to obey an absurdly low speed limit, transmission-daemon eats 100% CPU.

**Comment by Mikaela** [comment]
I am able to reproduce this on transmission-daemon 2.94 (d8e60ee44f) on Debian Testing.

I was attempting to download two archive.org torrents and am not surprised if this affects all of them.

**Comment by daftaupe** [comment]
Hello,

I can reproduce this bug on DragonFlyBSD also, using 2.94 as well.

I'm using [the latest ArchLinux image](https://www.archlinux.org/releng/releases/2020.01.01/torrent/) available as it uses webseeds.
Once I add it, the transmission-daemon process goes 100%+ and don't come back under a reasonnable CPU load until I remove the torrent (pausing it not enough).

I can see messages such as : ` transmission-daemon[259549]: Couldn't create socket: Too many open files (/construction/net-p2p/transmission-daemon/transmission-2.94/libtransmission/fdlimit.c:524)` repeating in /var/log/messages

**Comment by zootboy** [comment]
This is still an issue, and I think I've managed to narrow down the trigger. It seems that the high CPU usage only happens if a download speed limit is applied to the torrent currently downloading with a web seed.

I did an operf scan during a high-cpu event and this was the output:
```
279388   38.5344  libc-2.31.so             _IO_default_setbuf
273595   37.7354  libc-2.31.so             _IO_default_xsgetn
76627    10.5687  libcurl.so.4.6.0         /usr/lib/libcurl.so.4.6.0
34399     4.7445  libc-2.31.so             __vfwscanf_internal
18270     2.5199  transmission-gtk         /usr/bin/transmission-gtk
15292     2.1091  [vdso] (tgid:95548 range:0x7ffe77bce000-0x7ffe77bcefff) [vdso] (tgid:95548 range:0x7ffe77bce000-0x7ffe77bcefff)
...
```

I'm not familiar enough with the codebase to say what the bug is, but it seems like there's some odd interaction going on between the cURL code and the bandwidth limiting code.

**Comment by daftaupe** [comment]
> This is still an issue, and I think I've managed to narrow down the trigger. It seems that the high CPU usage only happens if a download speed limit is applied to the torrent currently downloading with a web seed.
> 
> Edit: tested with 2.94 on Arch Linux x64.

I can confirm with ArchLinux torrent that there's no issue when not setting a download limit, whereas with one the CPU usage skyrockets.
Tested on 2.94 under DragonFlyBSD.

**Comment by ckerr** [comment]
If this is still happening, I'd love to see a `perf` recording of where Transmission is spending its cycles for you all

**Comment by zootboy** [comment]
Here's what I got from a brief perf record:

```
Samples: 47K of event 'cycles', Event count (approx.): 37104145884
Overhead  Command          Shared Object               Symbol
  60.19%  transmission-gt  libc-2.31.so                [.] __memmove_avx_unaligned_erms                               ◆
   4.88%  transmission-gt  transmission-gtk            [.] tr_torrentFindFromId                                       ▒
   4.17%  transmission-gt  [kernel.vmlinux]            [k] do_syscall_64                                              ▒
   2.28%  transmission-gt  [vdso]                      [.] __vdso_clock_gettime                                       ▒
   1.49%  transmission-gt  [kernel.vmlinux]            [k] entry_SYSCALL_64                                           ▒
   1.34%  transmission-gt  [kernel.vmlinux]            [k] syscall_return_via_sysret                                  ▒
   1.18%  transmission-gt  [kernel.vmlinux]            [k] do_sys_poll                                                ▒
   1.11%  transmission-gt  libc-2.31.so                [.] _int_malloc                                                ▒
   0.87%  transmission-gt  libc-2.31.so                [.] _int_free                                                  ▒
   0.78%  transmission-gt  libc-2.31.so                [.] malloc                                                     ▒
   0.78%  transmission-gt  libcurl.so.4.6.0            [.] 0x000000000004337a                                         ▒
   0.70%  transmission-gt  libpthread-2.31.so          [.] __pthread_mutex_lock                                       ▒
   0.62%  transmission-gt  [kernel.vmlinux]            [k] __fget_files                                               ▒
   0.57%  transmission-gt  [kernel.vmlinux]            [k] sock_poll                                                  ▒
   0.53%  transmission-gt  libcurl.so.4.6.0            [.] curl_multi_perform  
```

I'm not super familiar with perf, so if there's more info that you'd like to see, let me know.

**Comment by 4llan** [comment]
There's at least two issues described here:

1. High CPU usage when bandwidth limit is set
2. "Too many open files" when add torrent with multiple webseeds (like Arch Linux torrent)

About the first, when I have a high speed bandwidth and set a low download limit, the CPU usage goes high.

About the second, I just stumbled upon this issue last week and the only propable cause to this is described here: https://github.com/transmission/transmission/pull/893

How to reproduce:

- Debian stable, transmission-daemon 2.94
- Open web interface, try to add Arch Linux 2021.07.01 torrent (https://archlinux.org/download/)
- Instantly the daemon freezes, the systemd service stales, the torrent don't finish

**Comment by zopieux** [comment]
Can reproduce the issue with Arch ISOs torrents. Instant freeze, 100% CPU on two cores. Same symptoms as @4llan.

**Comment by zopieux** [comment]
There are a bunch of patches on the internet to address this, but for now I'm simply disabling webseed entirely with a one line diff (against 3.00) which removes the entrypoint for webseed peer logic:

```patch
diff --git a/libtransmission/peer-mgr.c b/libtransmission/peer-mgr.c
index d1239cc..73f8e77 100644
--- a/libtransmission/peer-mgr.c
+++ b/libtransmission/peer-mgr.c
@@ -508,8 +508,6 @@ static tr_swarm* swarmNew(tr_peerMgr* manager, tr_torrent* tor)
     s->webseeds = TR_PTR_ARRAY_INIT;
     s->outgoingHandshakes = TR_PTR_ARRAY_INIT;
 
-    rebuildWebseedArray(s, tor);
-
     return s;
 }
```
