### ISSUE TITLE
Done script called even for initial seed hash checking

### ISSUE THREAD

**Issue by devilopa** [transmission/transmission#1082]
I have the opinion that the done script should not be called when starting to seed a torrent with

`transmission-remote -a file.torrent -S --find /dir` # to make sure it does not download accidentally
`transmission-remote -t $X -v `# verify 
`transmission-remote -t $X -s `# start ( if above verify was successfull ..)

this can easily be fixed in the code by doing something like
`            if ( wasRunning && wasLeeching ) `

around the `torrentCallScript(tor, tr_sessionGetTorrentDoneScript(tor->session));`

in file torrent.c lines 2336 and following.

regards

**Comment by devilopa** [comment]
Example fix in pull request #1083

**Comment by ckerr** [comment]
My concern with this change is that it could break other people’s scripts.

One alternative is we could set an env var to help distinguish how the torrent became complete, e.g. bytesDownloaded which would be 0 for a torrent that was added as a seed…
