### ISSUE TITLE
[Feature Request] UI Scaling

### ISSUE THREAD

**Issue by qwedas** [transmission/transmission#1087]
UI is way too small on higher resolution monitors (I just recently got a 1440p monitor).

OS: Arch
WM: dwm
Transmission 2.94

**Comment by andrasg** [comment]
Same on Windows 10 1903:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/10730249/71441418-ad0d4500-2701-11ea-9084-1251ffbe5e56.png">

Pretty much all UI elements except the menu are rendered too small on a high-DPI setting.

**Comment by qwedas** [comment]
I also checked out transmission-qt and it also does not have an option for UI scaling

**Comment by qwedas** [comment]
Images for context
GTK
![pic-window-191225-1150-38](https://user-images.githubusercontent.com/32962637/71448703-40984300-270d-11ea-9ae3-da52f6572e33.png)

QT
![pic-window-191225-1152-41](https://user-images.githubusercontent.com/32962637/71448704-40984300-270d-11ea-9ff8-a6dfc1581e69.png)

**Comment by ckerr** [comment]
It's unlikely that there will be any in-app setting for this, but there are some platform-level answers.

For example Qt has [environment variables](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt) that let you change scaling if you launch transmission-qt with the environment variable set
