### ISSUE TITLE
error url in wiki?

### ISSUE THREAD

**Issue by xux1217** [transmission/transmission#109]
hi,

I really like it and now I want to understand how it to work.

But when I click the url that is red in wiki, the url is "https://github.com/transmission/transmission/wiki/EditConfigFiles", and then, it would jump to "https://github.com/transmission/transmission/wiki".

Then I search "transmission Editing Configuration Files" by Google, it tell me the right url is "https://github.com/transmission/transmission/wiki/Editing-Configuration-Files"， and I can open it.

So, is these errors?

**Comment by ccckblaze** [comment]
so do i, that's annoying!

**Comment by ccckblaze** [comment]
@JohnClay can you help us out, please

**Comment by JohnClay** [comment]
I've adjusted the index page accordingly.

Thanks for the reminder.
