### ISSUE TITLE
wiki has documentation for removed environment variable `TR_DEBUG`

### ISSUE THREAD

**Issue by ishehadeh** [transmission/transmission#1090]
TR_DEBUG is listed on the Environment Variables wiki, but it just has (undocumented) as a description. I searched commits for the variable and the last mention of it was 599c5a8cc4f26ed9235a09559a5bb2e93afadc6c, which allegedly removed the variable. When searching google and DuckDuckGo I didn't find anything either.

The documentation should probably be updated to remove the reference to TR_DEBUG or add some sort of explanation.

**Comment by jtojnar** [comment]
Looking at the [relevant ticket](https://web.archive.org/web/20151110192900/https://trac.transmissionbt.com/ticket/3511), it has been replaced by a CLI flag.

**Comment by IanS5** [comment]
Ok, that's good to know, I guess it is an old version of `--log-debug`. Can someone update the wiki? I would but I don't think I can.
