### ISSUE TITLE
Magnet torrents are not preserved if no metadata downloaded

### ISSUE THREAD

**Issue by PF4Public** [transmission/transmission#1102]
If there was no complete metadata downloaded for a Magnet torrent upon closing Transmission, it will be removed from the list.

Could be related to #89, but I'm not certain as it is worded in a very vague way.

**Comment by danfiscus** [comment]
I have this issue also, very problematic with an unreliable internet connection like mine

**Comment by PF4Public** [comment]
@ckerr Is it fixed?
