### ISSUE TITLE
Feature Request: Allow two torrents with same hash

### ISSUE THREAD

**Issue by JustMyGithub** [transmission/transmission#1104]
It is nasty that transmission cannot do what other clients like utorrent or rtorrent can. It is nice to have a warning when adding the torrent, but it is annoying that it is not possible. I really like transmission for many reasons, but this is one of the few downsides.

**Comment by JustMyGithub** [comment]
No. It should only be merged if the .torrent allows so and the user agrees. Otherwise they should be treated seperately.
No, talking about the same content on different trackers.

**Comment by valcomm** [comment]
I think he's talking about merging trackers list, not creating a different torrent.

**Comment by ckerr** [comment]
Merging the torrent lists (at least for public torrents) is a request I understand,  but [this comment](https://github.com/transmission/transmission/issues/1104#issuecomment-1040171181) about treating them separately makes me think that's not the request?

**Comment by valcomm** [comment]
I'm not sure that it was about treating them separately.  Cannot say about utorrent or rtorrent, but QBittorrent in case of adding .torrent with different trackers list shows a message that lists were merged.
Currently transmission only returns 'torrent-duplicate' and no any merging happens/possible - I think that was described as 

> It is nasty that transmission cannot do what other clients like utorrent or rtorrent can.

I might be wrong though and maybe topic starter might explain his/her issue clearer.

**Comment by JustMyGithub** [comment]
The perfect solution would be to ask the user wheter he wants 2 seperate downloads in transmission from two torrents with the same hash or (if allowed by both torrents) he wants to merge the tracker announce urls of both into one download in transmission.

**Comment by valcomm** [comment]
Why is this a perfect solution?  What's the reason to download exactly the same content twice?  And where to store it?  It cannot be the same common download directory - that would cause collisions.
Not saying that hash in transmission (and protocol) is a primary key.
And RPC and daemon logic for such request would need to be twisted in such a weird and confusing way...

Can you explain how your request works/dealt with in other torrent clients?  Both with .torrent files and magnet links.

**Comment by JustMyGithub** [comment]
It is not about downloading twice. It is about seeding on more than one non-public tracker. Afaik one of the issues is that upload/download statistics need to be separated for non-public torrents. Being a user, I do not know the source code and cannot tell you how it is handled in other clients. Practically the hash alone cannot be the primary key in the local torrent database of the client. If that is how it is implemented, an additional primary key needs to be added (e.g. an index number).

In fact, the hash may be a primary key *for the specific tracker*, but not necessarily globaly. That it is possible is proven by other clients as mentioned before

**Comment by valcomm** [comment]
@JustMyGithub, can you explain how it is handled in other clients (like utorrent or rtorrent - the ones you mentioned) not from the source code point of view, but from the user experience?  I mean can you describe an example where you have some .torrent from one non-public tracker added to your torrent client.  And what happens when you add .torrent from another non-public tracker (presumably with the same hash) to the same torrent client.  All details starting from adding the second .torrent are very interesting and important.  For example, do you see two torrents in the queue of the client or just one?  Are Info Hashes really the same in the former case?  Are DHT/PeX/LSD enabled or disabled?  The more information you provide, the better

**Comment by ckerr** [comment]
@JustMyGithub so when you try to add the same torrent twice in another client, it opens a second copy of it? Can you tell me what client to test this out on?

**Comment by ckerr** [comment]
Closing due to lack of response and of actionable info

**Comment by JustMyGithub** [comment]
Sorry for missing to followup on this. DHT/PeX/LSD are disabled, as mentioned earlier this is about private .torrents that can (or should) not be merged.
like a_example.org.torrent and a_example.com.torrent.
As i also mentionend utorrent or rtorrent allowed to do this in 2020. Not sure about today.
