### ISSUE TITLE
[Feature Request] Download episodes one by one

### ISSUE THREAD

**Issue by ohld** [transmission/transmission#1111]
hi. I just come up with the idea to have a "Download episode one by one" mode for all series fans with a not-so-great internet connection.

It would be awesome if Transmission starts to download the next episode after the previous one was finished downloading.

The problem I have right not is a really poor internet connection and I stop downloading all episodes except one - to watch it first. Then I would need to start to download the next one while I've been watching already downloaded one. So it would be awesome if this can be automated somehow.

P.S. Sorry, I couldn't find any other way to propose my feature request.

**Comment by sio** [comment]
I'm not sure what is the position of developers on this matter, but sequential downloading goes against the ideas of bittorrent and is ethically questionable because it harms the health of the swarm.

**Comment by ohld** [comment]
@sio Agreed. Maybe more granular priorities might help there? Not just high/medium/low priority.

**Comment by ckerr** [comment]
Closing as `wontfix`.

There is a transmission fork out there on GitHub somewhere that does sequential downloading if you **really** want it. IMO stock Transmission should keep its current piece-choosing algorithm for better overall swarm health
