### ISSUE TITLE
Commit #abac811 breaks the build (Qt translations macro in cmake)

### ISSUE THREAD

**Issue by sio** [transmission/transmission#1117]
I was unable to build the latest master (commit 20119f006ca0f3a13245b379c74254c92f372910) because of errors related to Qt translations engine.

Bisecting led me to the commit abac811dd24fd188681116f8964d17075d2c83db which is the first one where the breakage occurs. It seems that `-silent` is meant to be an option but somehow it gets interpreted as a filename.

```
<...lines skipped...>
[ 74%] Built target transmission-gtk
Scanning dependencies of target transmission-qt_autogen
[ 75%] Automatic MOC for target transmission-qt
[ 75%] Built target transmission-qt_autogen
make[2]: *** No rule to make target '../qt/-silent', needed by 'qt/-silent.qm'.  Stop.
CMakeFiles/Makefile2:1556: recipe for target 'qt/CMakeFiles/transmission-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/transmission-qt.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

Full build logs are attached: [`cmake ..`][cmake.log], [`make`][make.log]

https://github.com/transmission/transmission/blob/abac811dd24fd188681116f8964d17075d2c83db/cmake/TrMacros.cmake#L197

Removing `OPTIONS -silent` from that line allows to finish the build without errors. Unfortunately I'm not familiar with [Qt-cmake integration](https://doc.qt.io/qt-5/qtlinguist-cmake-qt5-add-translation.html) enough to suggest the proper fix.

[cmake.log]: https://github.com/transmission/transmission/files/4113532/cmake.log
[make.log]: https://github.com/transmission/transmission/files/4113533/make.log

**Comment by ckerr** [comment]
Is this still an issue? I see the `-silent` call is still in CMakeLists.txt I'm not able to reproduce this problem.
