### ISSUE TITLE
Verifying local data for a long time before starting downloading 

### ISSUE THREAD

**Issue by melenxyz** [transmission/transmission#1118]
Hi, I’m having this issue on Transmission for Mac 2.94 but also on the latest builds.
When I add a new torrent, never downloaded before, it starts verifying for local data for a really long time before realizing it’s a completely unknown torrent and start downloading it.

When going into the informations panel of that torrent, it shows a "Last Activity: 18288 days ago" which appears to be the 1970’s, when the day zero for computers counting dates is.

I’ve provided a screenshot of the information panel.
I’m sorry in advance if this issue has been brought up before, I didn’t find it anywhere.

Thanks again for making such a great software!

![5FECD035-BF74-4993-B158-D4AE27D49E3C](https://user-images.githubusercontent.com/59291854/73204936-391aee00-4140-11ea-8183-e8492b946597.jpeg)

**Comment by Username-Climax** [comment]
Anyone having the same issue ?

**Comment by crocodile2u** [comment]
Me. Super annoying

**Comment by ckerr** [comment]
> When going into the informations panel of that torrent, it shows a "Last Activity: 18288 days ago" which appears to be the 1970’s, when the day zero for computers counting dates is.

This side-issue is [fixed](https://github.com/transmission/transmission/blame/main/web/src/inspector.js#L411) by #1476.

**Comment by ckerr** [comment]
Could someone who was experiencing this test out a [nightly build](https://transmissionbt.com/download) and see if the slow-verify issue is still present in the new web client?

**Comment by aniqueta** [comment]
> Could someone who was experiencing this test out a [nightly build](https://transmissionbt.com/download) and see if the slow-verify issue is still present in the new web client?

Issue seems resolved for me.

**Comment by aniqueta** [comment]
To clarify, I'm using Transmission Remote GUI, which uses the API endpoint, and that seems to be working. When I try to load the web endpoint (hosted on macOS Catalina), I receive the following error. Thanks.

```
404: Not Found

Couldn't find Transmission's web interface files!

Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.

Package Builders: to set a custom default at compile time, #define PACKAGE_DATA_DIR in libtransmission/platform.c or tweak tr_getClutchDir() by hand.
```
