### ISSUE TITLE
[Feature Request] Show total seeding time in torrent properies page.

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#112]
I need to know exactly how long a torrent has been seeding and Transmission doesn't currently show that. Please add that info to the properties page.

**Comment by Coeur** [comment]
![Capture d’écran 2022-05-05 à 19 51 59](https://user-images.githubusercontent.com/839992/166917865-27b52042-6543-4e14-a7c5-e59e7ed3070e.png)

As a 5.5 years old issue, I'll assume the property page was different before.
If that information isn't the one you expect, kindly reopen a new issue and explain how your expected value would defer from the displayed value in my screenshot. Thanks.
