### ISSUE TITLE
Allow configuring where torrent files are stored

### ISSUE THREAD

**Issue by PhiloEpisteme** [transmission/transmission#1124]
If this option already exists, I apologize. In some installations of transmission it is useful to define an alternate location for the downloads folder. This feature is well supported with the `download-dir` option per this [wiki](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files).

This same functionality would be extremely useful for the `Torrents` directory as well.

**Comment by stockHuman** [comment]
Those features are the first and fifth options in the _Downloading_ tab within the app's preferences window.

**Comment by ckerr** [comment]
The torrents directory is currently hardcoded to be a child folder in the config directory and TBH I don't see what the use case would be for making this configurable. Even if there *is* a use case; if it's something that only one or two people would use, maybe the use case would be better solved by symlinks outside of Transmission's codebase.

@PhiloEpisteme what are you trying to do with your torrents directory?

**Comment by ckerr** [comment]
Closing due to lack of response.
