### ISSUE TITLE
 Destination Transmission kill own performance and Source Transmission performance and loose excellent peer for big (from 1TB) torrents

### ISSUE THREAD

**Issue by axvpast** [transmission/transmission#1126]
**Pre condition**
Used: https://gitlab.com/AxVPast/recracker.local
Data transfer between Transmission works as: Transmission 1 <==> switch 1Gbit <==> Transmission 2
Transmission 1 use powerful 8x1.8GGz CPU, 2GB ram, not less than 160MB/s HDD 
Transmission 2 use 2x1.8GGz CPU, 2GB ram, not less than 160MB/s 10 TB Helium HDD 
1.5TB torrent with 32M pieces (90% complete)
Transmission 1 connected to local tracker
Transmission 2 connected to local and global trackers

**Behavior**:
- Sometime your Transmission 1/2 loose in peer list another Transmission addresses
- Network performance near 2MB/s, but for other torrents I can see performance not less than 10MB/s (for Transmission 2).

*Looks like exists few reason why it happens*
- Pice to download choice strategy is looks like wrong for big torrents. Idea - change strategy if block size near 32MB. For smaller files "default" strategy works fine, because files is small, directory sizes is small and most of all files pices fit OS cache and Transmission cache. But in case big torrents we face to big folders, where even fopen call takes long (f.e. `ls -la` takes 3 sec), files can have sizes from 1GB, so it is does not fit any cache (or you need to work with 2TB torrent 1TB RAM and 2TB SSD drive... that's now cost a lot of money). And this is a reason why src & dst transmissions always have OS/Transmission cache miss. If dst transmission CPU is not so powerful, we face to additional delay for completed block SHA1 check. So jumping between files and read/write random HDD areas is not good idea for it.

- If you not only peer but also you seed something - transmission have more random behavior for files access. So it is increase delays between last pice get from dst transmission and ask for next pice. If delay between interaction with src transmission is longer that 60sec, both transmission remove each other from peers list. So dst transmission loose excellent peer (IT LOCATED IN THE SAME SWITCH!). Situation is really poor if it happens when dst transmission - announce to trackers at this moment. Situation be even worst if we in this moment receive last data chunk for file and begin rename file (working with a big folders takes a while). 

*How to ensure that it is true*
- You can set upload limit for dst transmission to 0, so it is remove some chaotic impact from up-loaders - now may be dst transmission not loose excellent peer, but you can see jumping traffic for dst transmission jump to 2-3MB/s and fall to 0 each 30 sec(looks like block sha1 check boundary)
- You can change priorities for files (manually), and if you set to some one (exec one, not all) file priority to High, network speed increased to 5-8MB/s, but still pulse

So main idea - for big torrent change pice choice strategy and operates (For Download and for Upload), not using pices, not using block, but using superblocks with size like 1/1000 of (big) torrent size, for 2TB torrent it is 1GB size, so we probably fit to caches and operate inside few files.

Second idea - increase timeout regarding seed/peers communication and add re-connection logic if our src close connection because we are so slow process data.

"On the fly" sha1 check. So usually sha1 calls looks like x = createSha1Chiper(); x.update(dataChunk), x.digest(); So idea is - keep in memory this 'x' and if next from prev data chunk arrive - immediately do x.update(). Because we usually ask data blocks from beginning so most of all it is arrive in the same order what we are ask, so in most off all cases we at the last chunk do x.update only for last data chunk, so we have minimal delay between blocks processing.

**Comment by ckerr** [comment]
To be honest I don't understand a lot of this bug report. It's a very long description, some of it makes sense, and some of it is confusing.

In particular the proposal:

> So main idea - for big torrent change pice choice strategy and operates (For Download and for Upload), not using pices, not using block, but using superblocks with size like 1/1000 of (big) torrent size, for 2TB torrent it is 1GB size, so we probably fit to caches and operate inside few files.

Are you suggesting that Transmission prefetch 1GB of block data when seeding a 2TB torrent? How do we know in advance what block data the peer will request?

**Comment by ckerr** [comment]
To followup: I've added the `pr welcome` label because performance PRs are _always_ welcomed. Please be aware that there are a lot of people running Transmission on Raspberry PIs too though. The PR would need to behave well both on very powerful machines and on smaller Pis too.

**Comment by axvpast** [comment]
> To be honest I don't understand a lot of this bug report. It's a very long description, some of it makes sense, and some of it is confusing.
> 
> In particular the proposal:
> 
> > So main idea - for big torrent change pice choice strategy and operates (For Download and for Upload), not using pices, not using block, but using superblocks with size like 1/1000 of (big) torrent size, for 2TB torrent it is 1GB size, so we probably fit to caches and operate inside few files.
> 
> Are you suggesting that Transmission prefetch 1GB of block data when seeding a 2TB torrent? How do we know in advance what block data the peer will request?

I know my scenario is little bit complicated and not easy to reproduce, but in general it shows unexpected behavior.
Main question - large torrent files, which did not fit to RAM, like 1TiB upload/download speed is bad, comparing with small files.
Small torrents can utilize all network bandwidth, but big - not. I try to understand the cause of this problem and I have some (may be wrong) ideas how to fix it.

First - loosing excellent peer. In my example I use retracker which tells to download transmission constant IP of upload transmission (which connected to the same 1GiBit switch). But download transmission sometimes decide, that upload transmission disperses and download stuck. I observe download transmission behavior and think that it happens, when download transmission takes full chunk (may be few), it begin recalculate chunk checksum (in 1TiB torrent usually used 16MiB chunks) and it takes a while. In this period of time some of sides (looks like download transmission) decide that another side is dead and remove it form alive peers list or something else. So at the end I see that network activity is absent, download transmission peers list is empty.
Possible solution recalculate chunk checksum on the fly (we hope that UDP packets arrive in good order and at the end we calculate checksum only for last packet, so without loooong full chunk recalculation at the end). In current situation I see network activity as waves - downloading - high, calculation checksum - low.
Another solutions - change peers list cleaning logic (for download side), adjust inactivity timeouts using chunk checksum recalculation duration (means that is not peer is not responding time, it our process hangs ant it is not the reason for remove this peer from our peers list). 

Second - caching and random access issue with hard drive. If in big file you allays choice random block of data from file your performance will be significant killed (especially in really large mechanical HDD) for both sides. In this case sequential reading and writing have better performance than random read/write operations, but sequential (from beginning) reading from source is not in torrents transfers ideology. Main idea of torrents (may be I wrong) - read less distributed blocks at first. Idea is not prefetch, idea like split something super-big to some big parts. F.e. we have 1TiB torrent. We split it (logically) to 1024 super-chunks, each with size like 1GiB, choice one of this 1GiB super-chunk for download and download all chunks inside this super-chunk till the end without switching to another super-chunk (ok, may be here select less popular chunks, but only in this super-chunk). Even here we can IGNORE better peers which offers data from another super-chunks. In this case we work with hard drive only inside one 1GiB HDD area on both sides (src & dst), so it can improve performance from both sides (even if another side is not Transmission).

**Comment by ckerr** [comment]
I don't think this is feasible under either BitTorrent v1 or v2, since no bittorrent client honors block requests larger than 16KB.

I'm always happy to consider performance improvements and appreciate the thought that went into this proposal but I think it's out-of-scope for Transmission. Something like this would need to be proposed "upstream" at https://bittorrent.org where it could be considered for the BitTorrent spec.
