### ISSUE TITLE
The setting "Accept magnet links" can't be undone.

### ISSUE THREAD

**Issue by Liferme** [transmission/transmission#1127]
1. After setting Transmission the default application to accept magnet links, I seem to have trouble finding a way to undo it, I want to set another app the default app but I don't know how.
    2. And that is all because when I use Transmission to accept magnet links, the mission always says "torrent meta data needed", I am new to this, please tell me what to do...
    System: MacOS 10.15.3

**Comment by Coeur** [comment]
I'll leave this kind of questions to AskDifferent or similar forums:
https://apple.stackexchange.com/questions/354949/how-to-change-default-app-to-open-magnet-link-without-using-a-third-party-ui
