### ISSUE TITLE
Wrong error message when incomplete folder permissions are wrong

### ISSUE THREAD

**Issue by nitnelave** [transmission/transmission#1130]
Setup:

- download folder in /downloads
- incomplete folder in /incomplete
- Transmission user has RW access to /downloads, but not /incomplete.

When downloading a new torrent, after getting a MB or so, it will try to create the file in /incomplete, and fail with "Permission error: could not create /downloads/My.New.Torrent" (or something similar). Note that the error is about the downloads folder, and not the incomplete one.

Debugging this cost me ~5h :D Can we get the right error message there?

**Comment by neilbags** [comment]
Just hit this bug and wasted time too
