### ISSUE TITLE
[feature requests] And [Bug]

### ISSUE THREAD

**Issue by refriedfood** [transmission/transmission#1134]
Currently tested 2.94 x64 on windows and receiving the following when I drag and drop a torrent onto the window:
https://i.imgur.com/yDU7SHS.png
Regardless of what is put in the "source" field, it gives an error.

[Suggestions]

1. I would like to see a copy or move .torrent file to directory option, this is useful for backing up the torrent file in case something horrible goes wrong.
2. Adding trackers in bulk instead one-by-one.
3. More columns for details about the torrent in compact mode. Example: Total Size/Downloaded/Down Speed/Done/Seeds/Peers/Up Speed/Uploaded/Last Active/UpLimit/Time Active/Tracker/Etc
4. Visible fonts: https://i.imgur.com/0lqT7sa.png
5. Remove and Delete Torrent file right click option (this coincides with 1. and doesn't remove the data, just deletes the .torrent and removes the entry from the client (doesn't delete copy of .torrent file if one was made)
6. The Maximum Downloads should be overhauled so it's split to maximum active downloads AND maximum active torrents, so you can limit the amount of torrents active all together--i.e. all in client or only some. All torrent alive and active -1 (for all), 5 for only 5 active total. This also goes for upload, if there is a download limit active, there needs to be an upload active limit. All/some/none
7. Create Directory for file. If it's a single file torrent, an option to create a directory under its name and place it in it would be nice for organization reasons.
8. a pre-allocate disk space option.
9. Option for torrent's properties to be displayed and modified in a bottom panel instead of individually clicking on each one.

Interesting client, just has a ways to go before I can transfer to it. Keep up the good work!

**Comment by ckerr** [comment]
Handling this ticket would require fixing ten separate items.

I'm going to close this ticket as a tracking issue. Please open separate issues for each item you'd like to be considered.

**Comment by refriedfood** [comment]
You just want to ignore them, I'm not opening up ten different tickets. Get a clue.
