### ISSUE TITLE
What is the difference between rpc-whitelist and rpc-host-whitelist?

### ISSUE THREAD

**Issue by 1471765122** [transmission/transmission#1137]
I'm confusing about these two options. What is the difference between them?

**Comment by ckerr** [comment]
It's understandable. It's probably bad design; the difference is based on an implementation detail and the two keys do overlap.

`rpc-host-whitelist` filters based on the HTTP `Host` header

`rpc-whitelist`filters based on what libevent thinks the request's address is.

**Comment by StudioEtrange** [comment]
So they must be setted with same values if enabled or not ?
