### ISSUE TITLE
[Feature Request] Implement larger piece sizes on torrent creation

### ISSUE THREAD

**Issue by sserdda-liamE** [transmission/transmission#1139]
Transmission's torrent creation currently seems to max out at a 2MB piece size.  (at least it was still at 2MB on a 100GB torrent which was the largest I tried.)  This small a piece size is can cause a disk I/O bottleneck  at gigabit speeds.  Large torrents with less than a 4MB piece size are banned on at least one major private tracker for this reason.  

If it could switch over to a 4MB piece size at around a 8GB torrent size, that would be nice.

**Comment by ckerr** [comment]
You might want to refer that tracker's admins to this:

https://wiki.theory.org/index.php/BitTorrentSpecification

> Current best-practice is to keep the piece size to 512KB or less, for torrents around 8-10GB, even if that results in a larger .torrent file. This results in a more efficient swarm for sharing files. The most common sizes are 256 kB, 512 kB, and 1 MB.

**Comment by Pentaphon** [comment]
> Current best-practice is to keep the piece size to 512KB or less, for torrents around 8-10GB, even if that results in a larger .torrent file.

Why? That wiki doesn't even give a reason. It doesn't make sense to use 512kb for a 10 gb torrent because that just results in way more pieces and a higher likelihood of a swarm not having all the pieces when some seeders leave, as well as more pieces to thrash the hard drive.
