### ISSUE TITLE
Torrents not seeding are still in the "Active" tab

### ISSUE THREAD

**Issue by gvigner** [transmission/transmission#114]
Torrents displaying "UL: 0.0 KB/s" are listed in the "Seeding" tab while they are not seeding.
I'm using Transmission 2.92 (14714) on OSX.

**Comment by mikedld** [comment]
So is it "Active" or "Seeding" tab after all? Title says one thing, description another...

**Comment by gvigner** [comment]
Torrents not seeding are still in the "Active" tab as you can see on the screenshot attached, sorry for my mistake.

<img width="780" alt="transmission_active_tab" src="https://cloud.githubusercontent.com/assets/612946/21307548/e0b6d29a-c610-11e6-9e65-cb2de44cf29b.png">

**Comment by mikedld** [comment]
Well, I think this behavior is correct, as torrents are either "active" or "paused". "Active" doesn't mean that the data is being exchanged at this very moment, but instead that if another peer willing to exchange data will come along the exchange will happen; contrary to "paused" which means that we're not actively searching for exchange opportunity.

**Comment by mikedld** [comment]
See also: #101

**Comment by gvigner** [comment]
My suggestion is that the "Active" tab should be divided in two tabs "Active" and "Inactive". Otherwise, really active torrents are melt a growing list of old torrents not seeding.
