### ISSUE TITLE
remove torrent , closed and reopen transmission, remove torrent it's in torrent list

### ISSUE THREAD

**Issue by fjqingyou** [transmission/transmission#1143]
remove torrent , closed and reopen transmission, remove torrent it's in torrent list

os : win10_x64
version transmission 2.94 (d8e60ee44f)
this's screen Video file:
[ScreenVideoFile.zip](https://github.com/transmission/transmission/files/4297349/ScreenVideoFile.zip)

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/2433

**Comment by fjqingyou** [comment]
@ckerr 

Because my English is very poor, the following content comes from online translation

The new task does not immediately generate the corresponding folder. It's likely that you haven't downloaded anything for more than half a year after you created a new task. The progress is 0.00%.

One day, however, it suddenly has a speed, changing from the name specified by the DN parameter to the name of the folder.

However, this half a year. Hundreds or even thousands of new tasks may be added.

It is likely that the task of no speed has long been forgotten.

At this time, you can't find the original task by searching the DN keyword in your memory. Because its name has changed. And when it changes, it is not notified that its name has changed!

If the downloaded content is not native language content, you may need to manually traverse to find the original task. When you don't know a language, you may even need the help of translation!

So. It is expected that an option can be provided. The display name can take precedence over the DN parameter or the folder name, and the priority display name can be specified according to user habits
