### ISSUE TITLE
hope add note information support

### ISSUE THREAD

**Issue by fjqingyou** [transmission/transmission#1145]
Sorry, my English is very poor. The following is from the Internet Translation

Some of the items downloaded by the magnetic link belong to the zip package. They may have passwords, or for other reasons, they are expected to make a note of the local task.

It is expected to add a function of local custom remark information

thanks!

**Comment by ckerr** [comment]
I'm sorry but I don't understand this request.

**Comment by fjqingyou** [comment]
When there are many tasks at the same time. For example, hundreds of tasks to be downloaded.

However, the initial added tasks may not be downloaded for months. It's easy to forget what happened when you added a task. Maybe there is a zip file in this download task. Extracting it may require a password or other information related to the task. I had to open another file to record information about a task.

If you can have a comment field for custom download task, you don't need additional file records!

**Comment by ckerr** [comment]
'
