### ISSUE TITLE
In-App Update not working since years

### ISSUE THREAD

**Issue by MacyEleanorMay** [transmission/transmission#1149]
As the header says...

The app says it has an update and goes ahead and downloads it after which an error occurs.
This is happening on 4 diff. computers running High Sierra, Mojave and Catalina. So the issue is macOS agnostic

**Comment by DevilDimon** [comment]
This was fixed in the latest release. Unfortunately, there is no way to update to this release as auto-update is broken, and .dmg files for 2.93 & 2.94 are not supplied. Building from source seems like the only option unless devs upload dmgs for releases after 2.92

**Comment by ckerr** [comment]
IIUC this will be fixed when 3.00 is released; however, just as @DevilDimon says people will need to manually update to it. :slightly_frowning_face:
