### ISSUE TITLE
systemd[1]: transmission-daemon.service: Main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by Hello-Moeka** [transmission/transmission#1153]
systemd[1]: transmission-daemon.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: transmission-daemon.service: Failed with result 'signal'.

System:Ununtu 18.04 LTS
RAM:4GB
Transmission Version:2.94
Install from apt install

Thanks.

**Comment by ProdanAndrei** [comment]
The log should have more details. I was getting transmission-daemon killed when I was still running 2.92 and I was running out of memory.

**Comment by ckerr** [comment]
Closing due to age + lack of actionable info.

If this is still happening in Transmission 4.0.0 or higher, please file a new issue. Thanks!
