### ISSUE TITLE
Notebook tabs mouse scroll with gtk3

### ISSUE THREAD

**Issue by luigifab** [transmission/transmission#1155]
For the preferences window, I think for [gtk/tr-prefs.c](https://github.com/transmission/transmission/blob/master/gtk/tr-prefs.c), can you add this to "restore" tabs mouse scroll.

```c
#include <gdk/gdk.h>
#if GTK_CHECK_VERSION (3,4,0) && !GTK_CHECK_VERSION (4,0,0)
// gtk-scroll-tabs for GTK 3.4 to 3.24
gtk_widget_add_events (GTK_WIDGET (n), GDK_SCROLL_MASK);
g_signal_connect (GTK_WIDGET (n), "scroll-event",
				G_CALLBACK (capplet_dialog_page_scroll_event_cb),
				GTK_WINDOW (window));
#endif
```

[source](https://github.com/mate-desktop/mate-control-center/blob/master/capplets/appearance/appearance-main.c#L208) + [capplet_dialog_page_scroll_event_cb function](https://github.com/mate-desktop/mate-control-center/blob/master/capplets/common/capplet-util.c#L173)

**Comment by ckerr** [comment]
Copying `capplet_dialog_page_scroll_event_cb()` seems like overkill for this feature... does mouse scrolling work on tabs in other GTK apps and Transmission is doing something that breaks that, or is Transmission behaving as other GTK apps do?

**Comment by luigifab** [comment]
The tab mouse scroll has been removed by GTK 3. So it is impossible to scroll tabs in all applications without a custom implementation. Some mate apps have this custom implementation.
