### ISSUE TITLE
Device not configured

### ISSUE THREAD

**Issue by ekko20six** [transmission/transmission#1160]
So my external hdd had issues so I moved everything off it, erased it fresh, moved everything back (same name same folders etc) and now transmission keeps telling me error: Device not configured

any hints on what I should be looking for?
Cheers

**Comment by ckerr** [comment]
That string doesn't come from Transmission; it appears to be a Mac error. 

https://www.finetunedmac.com/forums/ubbthreads.php?ubb=showflat&Number=33257 has some information that might be helpful. Since isn't a Transmission-specific error I'm going to close this bug report.
