### ISSUE TITLE
OSX Dark theme

### ISSUE THREAD

**Issue by ddavidebor** [transmission/transmission#1162]
Hello guys,
Just a dumb feature request, but if somebody wanted to implement the dark theme on transmission on macOS, it would be really cool.

**Comment by codesforacookie** [comment]
Dark mode is already in the nightly build client for macOS. [Download It Here!](https://build.transmissionbt.com/job/trunk-mac/)

**Comment by ddavidebor** [comment]
Just tried dark mode love it!
