### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by RenaKunisaki** [transmission/transmission#1163]
[This page](https://github.com/transmission/transmission/wiki/Configuration-Files) has two broken links: Editing Configuration Files and Environment Variables. It doesn't seem possible to create a pull request for wikis, so I'll just report it here.

**Comment by Sylvain303** [comment]
There seems to have some PR mechanism on github wiki, but not obvious actually https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

I encourage you to vote, for the [related bug report](https://github.com/isaacs/github/issues/333).

The transmission wiki seems to have migrated from [trac](https://trac.transmissionbt.com/wiki/Blocklists) at a certain moment and the content is not reworked.

**Comment by ckerr** [comment]
Fixed in https://github.com/transmission/transmission/wiki/Configuration-Files/a12ce5994cd2c2c64c161160afd882ea1771af61
