### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by canine-afficionado** [transmission/transmission#1164]
Firstly, thanks to those of you that continue to develop Transmission - still my favourite BitTorrent client.

My seedbox provider have agreed to let me run a new build of transmission-daemon on my seedbox (currently running 2.94) but obviously they won't support it so I've got a couple of questions:
1. Is it stable?
2. Are the .resume files compatible ie if I upgrade will all my existing settings be compatible?

Thanks

**Comment by ckerr** [comment]
Pretty stable AFAIK. I use `master` for my torrenting and so do a lot of testers.

There may be issues with .resume files if you try to downgrade; I haven't tested it.
