### ISSUE TITLE
Screen support for Pinephone/Librem 5

### ISSUE THREAD

**Issue by SimonSchubert** [transmission/transmission#1165]
Some screens like Statistics, About and the file picker already work perfectly. But I wasn't able to actually hit the "Add" button to start the download after picking a torrent file from my file system. I don't know how much work it is but libhandy might come in handy. What do you think?

![transmission_1](https://user-images.githubusercontent.com/1833337/78663931-4dfbc680-78d3-11ea-97b5-500df9d21dad.png) ![transmission_2](https://user-images.githubusercontent.com/1833337/78664011-71267600-78d3-11ea-9a25-ec5381e260c3.png) ![transmission_3](https://user-images.githubusercontent.com/1833337/78664013-71bf0c80-78d3-11ea-8b9b-dcb23588b5d5.png) ![transmission_4](https://user-images.githubusercontent.com/1833337/78664015-71bf0c80-78d3-11ea-9a21-7d3eead71c4e.png) ![transmission_5](https://user-images.githubusercontent.com/1833337/78664016-7257a300-78d3-11ea-8203-19becaccfc01.png) ![transmission_6](https://user-images.githubusercontent.com/1833337/78664017-72f03980-78d3-11ea-8ed3-a30102bca354.png)

**Comment by okias** [comment]
While it would be great for Transmission to support phones layout directly ( :wink: ), there is project building a top of `libtransmission` named [Fragments](https://gitlab.gnome.org/World/Fragments). It's optimized from begging to run on mobile and tablet screens.

**Comment by ckerr** [comment]
If people want to write code that makes the existing client play better with mobile environments, I'm all for it and would be willing to review.

One concern -- I don't have any familiarity with libhandy and would wonder about the tradeoff of adding a new dependency that older systems might not have prepackaged.

**Comment by mikedld** [comment]
I'm actually thinking of maybe working on this, but it requires more changes to GTK 4 version (at least the way I see it) and thus more time. Don't think it makes sense for the GTK 3 version. I'm okay with this ticket staying closed until I happen to be anywhere close, or until someone else comes along and shows interest.
