### ISSUE TITLE
I would like to offer you a Russian version of the web interface

### ISSUE THREAD

**Issue by blbulyandavbulyan** [transmission/transmission#1166]
Hey. I really liked your program. I decided to change its interface, I slightly changed its appearance and added a Russian translation. The Russian translation is not completely finished, in some places the translation is completely wrong, but the process would not have advanced if I had not suggested. I do not have the experience of a translator, I translated everything by machine translation, adjusting the translation where I could understand the meaning of this or that interface element. Some things are left in English. Perhaps you do not need this at all, it is up to you to decide, besides, someone will have to support the translation. I am writing this here because I cannot create a Pull Request, due to the fact that I did not clone your repository, at the time of creating a modified version of the web interface, if you do not need a non-perfect translation, then at least look at the stylesheet the designer of me is not very, but I like the look I made.
[Here is a link to my modified version repository](https://github.com/blbulyandavbulyan/TransmissionWebUIRussian)
There are two versions, one is made under a dark theme, the second is plain white.
I apologize for my English, this is a machine translation.

**Comment by ValZapod** [comment]
Almost everything is translated except Rating field in statistics.

**Comment by ckerr** [comment]
It looks like this repo would need some significant work to resync with the current codebase after the  #1476 refactor / de-jQuery-ization.

If someone wants to do that work and add in a translation module, that would be great!

**Comment by mikedld** [comment]
The translation appears to be way outdated now. Closing in favor of #1942.
