### ISSUE TITLE
[2.94] How to troubleshoot "UDP Couldn't parse UDP tracker packet. (tr-udp.c:231)"

### ISSUE THREAD

**Issue by jringoot** [transmission/transmission#1168]
Context: I am trying to use transmission and [opentracker](https://erdgeist.org/arts/software/opentracker/) in a closed network. (with vpn connections to it)
The intention is to redistribute large (gigs) datafiles
It doesn't appear to work.
firewall is shut down
nmap shows tracker is up

I enabled debug logging to see more
And the log fills with lines like this

"UDP Couldn't parse UDP tracker packet. (tr-udp.c:231)"

Where to start with troubleshooting this?

Suggestions on how to set up public/private redistribution of local created files are welcome.

**Comment by russkel** [comment]
https://github.com/transmission/transmission/blob/master/libtransmission/tr-udp.c#L231

The line number doesn't correspond with the latest version, although I'm not sure if that's because of C compiler behaviour. What version are you running?

**Comment by jringoot** [comment]
transmission-daemon -V
transmission-daemon 2.94 (d8e60ee44f)

**Comment by jringoot** [comment]
I see the version in git is 3.00, I will compile it tomorrow and do tests. I'll post the result here.

**Comment by jringoot** [comment]
I am currently stuck here with building transmission 3

make ..
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/Transmission/build
[root@shambler build]# make
[  5%] Built target miniupnpc
[ 10%] Built target dht
[ 15%] Built target utp
[ 20%] Built target natpmp
[ 24%] Built target b64
[ 64%] Built target transmission
[ 66%] Built target transmission-test
make[2]: *** No rule to make target 'third-party/event/lib/libevent.a', needed by 'libtransmission/transmission-test-watchdir'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:320: libtransmission/CMakeFiles/transmission-test-watchdir.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
