### ISSUE TITLE
TOS/DSCP is not set for uTP

### ISSUE THREAD

**Issue by TapuGithub** [transmission/transmission#1171]
I've done some tcpdumping and found out that transmission 2.94-rc3 from  alpine linux 3.11 is not setting TOS/DSCP header to UDP packets(uTP protocol probably).
I don't think this is intended.

**Comment by TapuGithub** [comment]
Anyone?

**Comment by ValZapod** [comment]
> not setting TOS

There is no such thing as TOS anymore, it is only DSCP now. What it should be for uTP? I mean...

**Comment by TapuGithub** [comment]
I'm using current configuration terminology.
`peer-socket-tos: String (default = "default") Set the Type-Of-Service (TOS) parameter for outgoing TCP packets. Possible values are "default", "lowcost", "throughput", "lowdelay" and "reliability". The value "lowcost" is recommended if you're using a smart router, and shouldn't harm in any case.`
Just want to do QoS on my router. Standart way is to use DSCP in header. I can do it using peer-socket-tos for TCP streams, but cannot for UDP(uTP). I would be nice to have another option in config file or to use current value to uTP.

**Comment by pataquets** [comment]
@TapuGithub: you might be interested in #1043

**Comment by TapuGithub** [comment]
@pataquets Thanks - this is really what I need.

**Comment by TapuGithub** [comment]
Closing for #1043
