### ISSUE TITLE
transmission-qt menus blur and global-menu

### ISSUE THREAD

**Issue by RaitaroH** [transmission/transmission#1172]
Transmission-qt does not respect the blur setting set in Plasma 5 desktop. It also doesn't make its menu appear in the global menu, or window decoration menu embed thing either.

**Comment by ckerr** [comment]
It's been awhile since I looked at that code, but I don't recall the menu code doing anything unusual.

Any idea what a Qt app needs to do to respect these settings? Should it just happen by virtue of being a Qt app?

**Comment by RaitaroH** [comment]
I am unaware sorry. I think it may not be enough just to be QT though.
According to the bug I opened [here](https://bugs.kde.org/show_bug.cgi?id=419905):

> This is a bug in the app itself; it needs to set a flag that marks its menu as able to handle transparency properly.

**Comment by RaitaroH** [comment]
🤔 Except since last month it seems that blur works for some reason now.
![image](https://user-images.githubusercontent.com/19552720/82204196-1e49d080-990d-11ea-9a07-4ea7e19d131c.png)
Now I had a few updates which may be the culprit:
``` 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
```
Still, the global menu is not respected yet. One can set the menu to be global instead so it works with the global menu panel, or with the button inside window decorations. Alternatively I use it with [plasma-hud](https://github.com/Zren/plasma-hud) and transmission is the only application this doesn't work with because it doesn't work with global menus.

**Comment by RaitaroH** [comment]
Seems as of `transmission-qt 3.00 (bb6b5a062e)` this has been fixed. Thank you!
