### ISSUE TITLE
Remove torrent&Delete data button next to remove torrent button

### ISSUE THREAD

**Issue by siyia2** [transmission/transmission#1175]
Would this be possible? way better than right click delete torrent&data and shift+delete.

**Comment by ckerr** [comment]
Do you mean, a "Remove & Delete" button on the toolbar right next to "Remove"? That seems like it would cause more pain than benefit when people start clicking the wrong button by accident.

"Remove & Delete" is already near "Remove" on the context menu though.

**Comment by siyia2** [comment]
Most old people when they remove torrents,  believe that the contents of the torrents are removed, which of course isnt happening by removing a torrent, i believe at least a checkbox in the preferences
about the action of the remove button could help.
