### ISSUE TITLE
Crash on Win 10, Transmission 2.94 (d8e60ee44f)

### ISSUE THREAD

**Issue by pinchies** [transmission/transmission#1182]
I recently had a crash on windows after opening a torrent. Peers would connect, after about 60-70 peers it would hang and crash.

Torrent below for testing: https://www.dropbox.com/s/fongo8bhuh2b2mb/test.zip?dl=0

**Comment by flaviomauro** [comment]
> I recently had a crash on windows after opening a torrent. Peers would connect, after about 60-70 peers it would hang and crash.
> 
> Torrent below for testing: https://www.dropbox.com/s/fongo8bhuh2b2mb/test.zip?dl=0

Hello Team,

Same here, I'm running Windows 10 Pro. 
Please find attached the details of the error.
[Report.zip](https://github.com/transmission/transmission/files/4524880/Report.zip)

**Comment by RCoeurjoly** [comment]
I had the same issue.
It was solved installing the 32 bit (x86) version, even if my computer is 64 bit

**Comment by ckerr** [comment]
Is this still happening in the 4.0.0 betas?

**Comment by ckerr** [comment]
Closing stale bug. If this is still happening in 4.0.0 or higher please file a new bug. Thank you!
