### ISSUE TITLE
Might be potential null pointer dereference in webseed.c

### ISSUE THREAD

**Issue by viennadd** [transmission/transmission#119]
In function `task_request_next_chunk (struct tr_webseed_task * t) `at webseed.c,

[line 475](https://github.com/transmission/transmission/blob/master/libtransmission/webseed.c#L475)  obtains a` tr_info*` from function `tr_torrentInfo` that might returns null, and the returned pointer is used in next few lines.

Is that the [line 470](https://github.com/transmission/transmission/blob/master/libtransmission/webseed.c#L470) could actually be` if (tr_istorrent(tor)) `to ensure function `tr_torrentInfo` returns valid pointer.

thx.

**Comment by mikedld** [comment]
My understanding is that `tr_isTorrent` should be used in assertion context only, to avoid programming errors where one passes around a pointer to something other than torrent as a pointer to torrent. Other than that, and the case where one might pass/return a pointer to freed torrent, we should just trust what we get.

In this particular case, non-`NULL` pointer *is* a valid pointer. Adding an assertion is fine by me, but I would prefer it to be inside `tr_torrentFindFromId` as a search post-condition.

**Comment by viennadd** [comment]
Thanks Mike, and yes, I think so, the validation as a search post-condition is better,

I found that the implementation of [tr_torrentInfo](https://github.com/transmission/transmission/blob/4c00df9463ea4fd70b73c620e439f5c3ee5efa60/libtransmission/torrent.c#L1146) might returns NULL (if tr_isTorrent returns false), `tr_isTorrent` is not in assertion this case? I can see most of usage of `tr_isTorrent` are in assertion as you said.

**Comment by mikedld** [comment]
Noticed this too. I think those places where it's being used outside of `assert()` should be "fixed", one way or another.
