### ISSUE TITLE
Fresh install - immediately connects to 60+ servers across the world

### ISSUE THREAD

**Issue by JustTom2** [transmission/transmission#1196]
Upon a clean installation of transmission-daemon, I am seeing numerous outgoing connections to over 60 different IP addresses.

This is before any torrents are added or default configuration is changed. All incoming connections are blocked by my firewall so the Daemon is actively contacting these servers

Checked on Ubuntu server 20.04 (pulled from ubuntu repo) and from the latest transmission docker container provided by linuxserver.io

Is this normal behaviour?

Here is a sample:
Type                source destination ip/port
udp	ubuntu	51413	62.210.81.215	51413	
udp	ubuntu	51413	219.79.69.147	6881	
udp	ubuntu	51413	79.161.66.164	44558	
udp	ubuntu	51413	175.213.251.5	32205	
udp	ubuntu	51413	187.39.253.3	40952	
udp	ubuntu	51413	109.120.8.208	6881	
udp	ubuntu	51413	87.149.245.172	6881	
udp	ubuntu	51413	5.39.226.188	59777	
udp	ubuntu	51413	89.103.9.107	49643	
udp	ubuntu	51413	107.242.124.37	32992	
udp	ubuntu	51413	121.165.57.113	61098

**Comment by JustTom2** [comment]
The only thing I can think of is that these servers have something to do with time/date/region synchronization.

**Comment by sio** [comment]
If I recall correctly, 6881 is the default port for the DHT bootstrapping node. Transmission is most likely just connecting to DHT network to be ready when you need it

**Comment by JustTom2** [comment]
Cheers. That clears things up, I just didn't expect transmission to connect to the DHT network unless there was an active torrent.
