### ISSUE TITLE
No PPA for Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by flying-sausages** [transmission/transmission#1197]
Hey guys, not sure how the PPA system works but there are no builds for 20.04 right now it seems. Would it be possible to make the builds for the new LTS release please?

**Comment by flying-sausages** [comment]
Turns it out it's not maintained by you guys, my bad

**Comment by anoteng** [comment]
I'll update the PPA when there's a new release. I don't see a point to updating it with the same version that's allready in Ubuntu.

**Comment by flying-sausages** [comment]
Fair enough, understood.
My concern comes from the fact that all online tutorials come up with the repo, and it will 404 if people change their `xenial`s to `focal`s in their apt sources. Not sure how the update managers handle that either. In the event there ever will be a new release, it would be nice to have the version available from the PPA and have it installed during upgrades.

**Comment by anoteng** [comment]
An upgrade of Ubuntu would disable any PPA, and it would have to be
re-added.
With the increased activity here lately, I hope the next release is not far
away, so I might as well prepare by updating the PPA.

tor. 30. apr. 2020 kl. 22:52 skrev flying-sausages <notifications@github.com

**Comment by anoteng** [comment]
I've uploaded packages for eoan and focal now, but they are versioned older than the ones currently in Debian and Ubuntu, so they won't replace anything in if added to a system.

**Comment by flying-sausages** [comment]
3.0 is out

**Comment by ckerr** [comment]
FWIW the releases will be more frequent :smile_cat:

**Comment by anoteng** [comment]
I'm working on it. Ran into a few problems, which I'll hopefully have time
to fix tonight after work.
Will look into automation if releases starts to become frequent.

tor. 23. feb. 2023 kl. 23:18 skrev B. Roland ***@***.***>:

**Comment by antivirtel** [comment]
Thanks @anoteng ,any update on this please? Do you need any help (also with automation)?
