### ISSUE TITLE
Transmission interaction with a FUSE filesystem.

### ISSUE THREAD

**Issue by Bad-ptr** [transmission/transmission#120]
Hello, I'm trying to use transmission to download a torrent onto custom FUSE filesystem(I use fusepy) which actually save data on a real filesystem but with different path.

It works in general, but I get a high number of 'corrupt' data statistics(a half or more of the downloaded data is 'corrupt') 
![img](https://my.mixtape.moe/xmlwyx.jpg)

I have tried a number of 'passthrough' filesystem examples and get the same results
https://github.com/terencehonles/fusepy/blob/master/examples/loopback.py
https://github.com/libfuse/python-fuse/blob/master/example/xmp.py
https://github.com/dpavlin/perl-fuse/blob/master/examples/loopback.pl
https://github.com/skorokithakis/python-fuse-sample/blob/master/fuse.py

What can I do about that?
I guess that python + fuse is rather slow may it be the cause of this?

I will also ask in fuse-devel about it of course, but I want to know how the transmission checks that data is corrupt?

**Comment by mikedld** [comment]
Number one question is do you get the same corruption ratio when not using your FUSE filesystem?

**Comment by Bad-ptr** [comment]
> do you get the same corruption ratio when not using your FUSE filesystem?

No. I have no or very low corruption ratio when I do not use FUSE fs. I also tried another harddrive and it still the same -- corruption with FUSE and no corruption if I use a harddrive's fs (ext4) directly.

**Comment by Bad-ptr** [comment]
Well, looks like I found the cause of the problem -- sometimes a bad file handle is given to read/write FUSE callbacks.
So it seems like transmission has nothing to do with it).
Closing this and will continue discussion at fuse-devel http://fuse.996288.n3.nabble.com/Transmission-bittorrent-client-interaction-with-a-FUSE-filesystem-td14431.html
