### ISSUE TITLE
LPD not public torrent on LAN

### ISSUE THREAD

**Issue by Juniorsnet** [transmission/transmission#1209]
I have a transmission 2.94 running on a server with local peer discovery enabled.
in another computer on the same LAN the other transmission never get the server has a peer (with lpd enable too).
I try to listen de broadcast messages with netcat (nc -vv -l -p 6771 -u), but the message never appears.

**Comment by Mlocik97-issues** [comment]
have same problem,...

**Comment by PRESFIL** [comment]
Same problem. I tried distributing a torrent on a local network between two clients on the same host.
`transmission-cli==3.00-2` & `transmission-qt==3.00-2` on Manjaro. LPD does not works. Without firewall restrictions.

**Comment by ihatetoregister** [comment]
Same issue here with two 4.0.3 clients
