### ISSUE TITLE
Use Sparkle framework from new maintainers

### ISSUE THREAD

**Issue by livings124** [transmission/transmission#121]
https://sparkle-project.org

We use a custom version because we need support for multiple versions (dropped OSes), but it looks like the mainline supports this now.

Besides not having to support a tweaked implementation, the newest version has some additional developer verification checks.

We'd have to figure out how to support betas, but I think that's the only thing missing.

**Comment by mikedld** [comment]
Closing in preparation of 3.00 (see #600 and 1b36e34d9bcfd8ea28f2c6ff4085a294e4cf0f71).
