### ISSUE TITLE
Windows 10, t2.94 - Couldn't find Transmission's web interface files!

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1212]
On Windows 10 with Transmission 2.94 when i open in web browser
http://localhost:9091/transmission/web/

i see:
> 404: Not Found
> 
> Couldn't find Transmission's web interface files!

The [TransmissionGUI](https://github.com/transmission-remote-gui/transgui/releases) can connect without problem

**Comment by mikedld** [comment]
You need to select "Web interface" on components page during installation/modification (it's off by default).

**Comment by slrslr** [comment]
Thanks, that was it. I ran installer again and now it works.

The process in more detail: i backed up application data (Win.+R, %appdata%, and in Local and Roaming backed up directories), downloaded new installer of the Transmission 3.00 and ran it leaving default app and components ticked to be installed and also ticked the Web interface component.
It completed and then i am in new app version with my old torrents and working web interface - so all good.
