### ISSUE TITLE
3.00 gui is blank when i close it (to Windows 10 tray) and reopen

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1214]
Transmission 3.00+ (20119f006c) gui shows correct after startup, but the interface gets empty/blank (white), not show even File, Edit, Torrent menu tabs when:

1) i close window (to Windows 10 tray) and then click tray to restore it.

2) when i minimize the window to Windows taskbar for more than like 3 seconds

The content again show up when i resize the window by mouse click and move or by clicking window button for maximizing or returning from maximize.

Focusing other windows over Transmission does not cause the empty interface problem.

**Comment by mikedld** [comment]
Also reported on the forum: https://forum.transmissionbt.com/viewtopic.php?f=17&t=20401

**Comment by slrslr** [comment]
I am no longer using that OS, so maybe closing?
