### ISSUE TITLE
Dark mode on Catalina

### ISSUE THREAD

**Issue by MassimoClementi** [transmission/transmission#1216]
It would be **amazing** if you could add both dark and adaptive themes to the application. Please let me know if it is work in progress or there is no hope.

**Comment by NekoFever** [comment]
It's in the [nightly builds](https://build.transmissionbt.com/job/trunk-mac/) so presumably will be in whatever ends up being the next release (3.0?). I've been running the latest nightly for some time and it's quite stable, so try that if you can't wait.

**Comment by MassimoClementi** [comment]
Makes sense, thank you for the info!
