### ISSUE TITLE
Portable version for Windows

### ISSUE THREAD

**Issue by stdedos** [transmission/transmission#1218]
Hello there,

Is there a portable version for Windows?

**Comment by ckerr** [comment]
I believe transmission-qt works on Windows?

**Comment by stdedos** [comment]
There is a big **Portable** word, first on the title.

Fine if you choose to ignore it like that.

**Comment by timkrenz** [comment]
https://portableapps.com/apps/internet/transmission-portable

**Comment by stdedos** [comment]
Is that considered/condoned official?
