### ISSUE TITLE
Torrent downloaded 100% cannot be force-verified

### ISSUE THREAD

**Issue by stdedos** [transmission/transmission#1219]
_Note that I am using https://portableapps.com/apps/internet/transmission-portable, since I am not fancy installing things_

I have a torrent downloaded by qbt at 100%.

* Transmission 2.9.4 on Win10 says it's at 99.8% (missing a piece I am guessing), even after forcing to re-check.
* Starting to download crashes Transmission.

Any ideas?

**Comment by ckerr** [comment]
Can you provide a backtrace or crash report?

**Comment by stdedos** [comment]
How does that work in Windows? Can I send you a link to a Windows dump file? Otherwise, I haven't seen any backtrace anywhere

**Comment by ValZapod** [comment]
What is the torrent?

**Comment by stdedos** [comment]
I am sorry - this is closing up on 6 months of inactivity.
I don't have anything anymore, nor will I waste the time to put something back together given the inactivity.

**Comment by ValZapod** [comment]
Just give the torrent hash.

**Comment by stdedos** [comment]
> Just give the torrent hash.

As I said:

> I don't have anything anymore

I resolved my problem with qbt, did what I had to do with that torrent, and removed metadata and Transmission (the benefit of using portable apps is that a Shift+Del fixes everything)

**Comment by ValZapod** [comment]
Okay, so close the issue.

**Comment by ckerr** [comment]
Closing based on above feedback and inability  to reproduce the issue.

If anyone is still seeing this issue in 3.00 or in [the nightly builds](https://transmissionbt.com/download), please file a new issue with information from that release. Thank you!

**Comment by ValZapod** [comment]
I actually had same problem.

**Comment by ckerr** [comment]
@ValZapod if you're still seeing this behavior in a [nightly build](https://transmissionbt.com/download) then please open a new ticket with full information. If it is a public torrent, please send me a .torrent or magnet link to the email I have in the git commit logs.

**Comment by ValZapod** [comment]
It is right here. #1504
