### ISSUE TITLE
[Feature Request] Add/Remove Tier in Web GUI

### ISSUE THREAD

**Issue by lucebert** [transmission/transmission#1220]
Hey folks,

It would be nice Transmission offers the possibility to add or remove Tier in Web GUI
This functionality is available in the client :

<img width="551" alt="Capture d’écran 2020-05-11 à 12 55 47" src="https://user-images.githubusercontent.com/39068991/81555285-9d2c8f80-9388-11ea-8e08-376561124642.png">

**Comment by ckerr** [comment]
Related: #2642

**Comment by ckerr** [comment]
Closing as a subset of https://github.com/transmission/transmission/issues/5234
