### ISSUE TITLE
Scrollbar overlaps "Show" button

### ISSUE THREAD

**Issue by fedorpashin** [transmission/transmission#1224]
If I scroll the list of torrents, I can't immediately open a torrent directory, because the scrollbar overlaps "Show" button.

<img width="47" alt="Снимок экрана 2020-05-12 в 08 16 18" src="https://user-images.githubusercontent.com/19939537/81641253-3ad79b80-9429-11ea-991b-c9fd3c35e536.png">

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #261, #1.
