### ISSUE TITLE
build wiki: buildingTransmissionQtWindows  mingw.repo url homes.merjis.com not found host

### ISSUE THREAD

**Issue by fjqingyou** [transmission/transmission#1226]
Fail according to wiki: buildingtransmissionqtwindows process

now yum install mingw component fail

i try use chrome open url:
http://homes.merjis.com/~rich/mingw/fedora-rawhide/x86_64/

i geting this error
```
无法访问此网站
找不到 homes.merjis.com 的服务器 IP 地址。
DNS_PROBE_FINISHED_NXDOMAIN
```

Any help, thank you

**Comment by ckerr** [comment]
I'm not seeing that in our documentation. Is still an issue?

**Comment by fjqingyou** [comment]
it's at this url

https://trac.transmissionbt.com/wiki/BuildingTransmissionQtWindows

but, now i using ubuntu build this git master branch success
