### ISSUE TITLE
[WEB UI] Login page instead of Sign in popup

### ISSUE THREAD

**Issue by ZimGil** [transmission/transmission#1232]
How about switching to a proper Login page instead of the sign in popup?
Couple of reasons IMO:
1. Better look and feel
2. Will be easy to use with services like [LastPass](https://www.lastpass.com/)
3. Can add a `Remember Me` option, maybe

**Comment by madcowGit** [comment]
same as #823

**Comment by normanr** [comment]
same as https://github.com/transmission/transmission/issues/716

**Comment by ckerr** [comment]
Duplicate of #466 716
