### ISSUE TITLE
Reveal In Finder opens parent folder not selected file (Mac)

### ISSUE THREAD

**Issue by pedroconejo** [transmission/transmission#1233]
At some point in recent updates, the Reveal In Finder contextual menu option and the Reveal 🔍 icon has been opening and selecting the torrent's parent folder rather than selecting the actual file. 

Previously, choosing those options would open and select the downloaded file itself.
So for example clicking Reveal for the download of "Transmission.app" now opens Finder to
_~/Downloads_  rather than _~/Downloads/Transmission.app_

Not a huge deal but it is lost functionality.

EDIT: This appears to only occur when the Finder default view is Columns. When in Icon, List or Gallery Views, the item is correctly selected.

**Comment by vraithe** [comment]
I updated today to Transmission 3.00 and am using Catalina 10.15.5 but don't have the issue you describe, neither now nor in the past. My view is set to columns and when clicking on 🔍 the correct file is selected...

**Comment by Atecub3000** [comment]
I have updated to Transmission 3.00 and using Catalina 10.15.5.
Still have the same issue described above.

**Comment by ldexterldesign** [comment]
👋 https://github.com/transmission/transmission/issues/1300

**Comment by ldexterldesign** [comment]
🙏

**Comment by Coeur** [comment]
I cannot reproduce this issue with Transmission 4.0 on macOS Ventura.

Since you're saying it's working in Icon, List or Gallery, I'll assume it's purely a Finder bug in older versions of macOS.
