### ISSUE TITLE
Move from TeamCity to GitHub Actions for post-commit checks

### ISSUE THREAD

**Issue by alimony** [transmission/transmission#1235]
Post-commit checks are currently run on a private instance of TeamCity, which means contributors cannot inspect what checks were run, their progress, etc. Now that GitHub has a very competent actions system, maybe that would be a better choice for running checks.

**Comment by mikedld** [comment]
The moment GitHub will allow running the systems that I have set up on TeamCity that would be an option. Anyone is able to login as guest there, so the build progress and logs are quite available.

**Comment by mikedld** [comment]
I myself find it a bit confusing that with guest login enabled TeamCity would still direct you to the login page, and the guest login option there is not clearly indicated. Looks like [it's going to be fixed in v2020.2](https://youtrack.jetbrains.com/issue/TW-55891) which is nice.
