### ISSUE TITLE
3.00 release tarball doesn't have all submodules

### ISSUE THREAD

**Issue by i0ntempest** [transmission/transmission#1246]
I'm trying to use macports to automate the build (with Xcode), but the build fails because not all submodules are in the tarball. There's no easy way to get submodule with macports, so could you please kindly provide a complete release tarball of this and the future versions?

**Comment by danechitoaie** [comment]
Trying to compile 3.00 and getting the following error:
```
CMake Error: The source directory "/tmp/build/third-party/b64/src/b64" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [CMakeFiles/b64.dir/build.make:109: third-party/b64/src/b64-stamp/b64-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/b64.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
I assume it's because of this?

**Comment by i0ntempest** [comment]
@danechitoaie You prolly used GitHub generated tarball which contains no submodules at all. The release tarball (.xz one) does have lib64 and some other and is enough for the gtk build, but not for the native macOS build using Xcode.
