### ISSUE TITLE
Unable to build version 3.0 on debian 9

### ISSUE THREAD

**Issue by xxhjkl** [transmission/transmission#1253]
[ 73%] Built target transmission-qt_automoc
make[2]: *** No rule to make target '../qt/-silent', needed by 'qt/-silent.qm'.  Stop.
CMakeFiles/Makefile2:1495: recipe for target 'qt/CMakeFiles/transmission-qt.dir/all' failed
make[1]: *** [qt/CMakeFiles/transmission-qt.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by p506738532** [comment]
i have a similar trouble with you when i use the commond "make". however, i did get this trouble when i refer this page https://github.com/transmission/transmission/wiki/Building-Transmission
the commond part is
`$ git clone https://github.com/transmission/transmission.git
$ cd Transmission
$ ./autogen.sh && make -s
$ su # if necessary for the next line
$ make install`
also, i got a trouble about libiconv, finally, i succeed after visiting this page https://blog.whsir.com/post-1275.html
best wishes.

**Comment by mikedld** [comment]
Fixed by #1377.
