### ISSUE TITLE
OS X - Dark mode / Light mode choice ?

### ISSUE THREAD

**Issue by misanthropish** [transmission/transmission#1255]
Please, if possible, let it be possible to choose between dark mode and light mode in the preferences, without having to change the entire OS to one or the other.

**Comment by harpalassi** [comment]
+1. Dark mode is not enabled on Mojave. I still want to run 32-bit apps & iTunes, so I don't want to update to Catalina at this time. 

Thanks!

**Comment by XYZeb** [comment]
Not keen on dark mode in it's current form - the grey text in dark background is really hard to read on a non-retina display.
As a workaround to force light mode:
1. Quit Transmission
2. Paste this in Terminal: `defaults write org.m0k.transmission NSRequiresAquaSystemAppearance 1`
3. Restart Transmission

Similarly `defaults write org.m0k.transmission NSRequiresAquaSystemAppearance 0` for the reverse and `defaults delete org.m0k.transmission NSRequiresAquaSystemAppearance` to remove this change (if dark mode is improved 😉)
