### ISSUE TITLE
Qt Client: directory empty if it contains only symlinks

### ISSUE THREAD

**Issue by patlefort** [transmission/transmission#1257]
When selecting a directory for a torrent, in the directory selection dialog, if the directory contains only symbolic link directories, the dialog will not show its sub-directories. It will load them only if I manually start typing a sub-directory in the location text box. This is on arch linux, running transmission v3.00.

**Comment by ckerr** [comment]
Transmission's not doing anything special in that file selection dialog; this is apparently a Qt issue.
