### ISSUE TITLE
Sparkle framework is broken in 3.00 release tarball

### ISSUE THREAD

**Issue by i0ntempest** [transmission/transmission#1258]
All symlinks inside the Sparkle framework are followed and become the actual files/folders, and codesign program doesn't like that:
```
$ sudo codesign --force --deep --sign - /Applications/MacPorts/Transmission.app/
/Applications/MacPorts/Transmission.app/: replacing existing signature
/Applications/MacPorts/Transmission.app/: bundle format is ambiguous (could be app or framework)
In subcomponent: /Applications/MacPorts/Transmission.app/Contents/Frameworks/Sparkle.framework
```

**Comment by mikedld** [comment]
Last time I see Sparkle symlinks being preserved in a tarball is in v0.82, so long time ago. Then they started to get converted to hardlinks in v2.32, a long time ago as well. This (using `-h` tar option) seems to be the default automake behavior dating back to 1996 (http://git.savannah.gnu.org/cgit/automake.git/commit/?id=7930983ab1c620) which is possible to change but is a bit tricky and I'm not sure if we want to...

On a side note, switching to CPack and its `package_source` make target doesn't help much. It preserves some of the symlinks but not the others.

**Comment by i0ntempest** [comment]
Would it be possible to zip/gz the framework and only extract it when needed? This could preserve the symlinks

**Comment by Coeur** [comment]
This issue is from May 2020, and the framework has been updated twice since then by @livings124. Assigning the issue to him.

**Comment by ckerr** [comment]
Is this still broken in Transmission 4?

**Comment by ankanpratik** [comment]
I just checked mine again and it always shows a 'Update Error' since 3.0

**Comment by i0ntempest** [comment]
Haven’t got to it yet, manipulating Xcode builds in MacPorts is pretty complicated so I’ve been putting it off. Will get back to this once confirmed.

**Comment by i0ntempest** [comment]
This is fixed in 4.x, closing. Thanks to the devs.
