### ISSUE TITLE
Mac update doesn't work for the new v3.0.0

### ISSUE THREAD

**Issue by Motti-Shneor** [transmission/transmission#1261]
Env: iMac 27" 2015, MacOS 10.14.6, Transmission 2.9.4 was running continuously for about a week.

Transmission popped its usual update dialog window, suggesting I installed the new v3.0.0. I read the news, and hit the "Update" button. It showed a brief progress dialog, downloading about 5.4 MB, and then presented an error failure dialog - reporting failure to install the update. I tried this 2 times with the same results. 

I'm sorry I didn't take a screenshot at this moment, but rather went to your home page, downloaded and installed the new version manually over the original app... but surely you can reproduce this. It was quite stubborn. 

I then opened Console, and looked for **Transmission** related log messages in system.log, and found the following:
```
May 24 07:41:47 Mottis-Big-iMac Transmission[4419]: Sparkle Error: An error occurred while extracting the archive. Please try again later.
May 24 07:42:03 Mottis-Big-iMac Transmission[4419]: Sparkle Error: An error occurred while extracting the archive. Please try again later.
May 24 07:47:04 Mottis-Big-iMac ExternalQuickLookSatellite[5115]: No file data for file:///Volumes/Transmission/Transmission.app
May 24 07:50:08 Mottis-Big-iMac ExternalQuickLookSatellite[5146]: No file data for file:///Applications/Old%20Transmission.app

```
It seems that one of the needed files is empty or missing on the downloaded update archive. 

If there is any more information I can provide to help resolve the issue - let me know.

**Comment by earthsound** [comment]
As mentioned in [Issue 600](https://github.com/transmission/transmission/issues/600#issuecomment-393298555), the next update (this one) will have to be manual on macOS. 

It wouldn't hurt to add a note about this in the Release Notes.

**Comment by Motti-Shneor** [comment]
But how is one to see release notes before installing the update? it's a little catch-22 for most users. Also - it's Transmission who pushed that update to me... if you know Transmission 2.5.4 cannot autoupdate itself - why place this update on your server?

**Comment by rjhancock** [comment]
I just did the update. The update window had a note about needing to download from the site if the update fails.

**Comment by livings124** [comment]
Closing out. The update notes say that you need to manually update. The version of Sparkle in the older version doesn't work with newer versions of macOS, and the version in 3.00 does.
