### ISSUE TITLE
3.00 Windows x64 installer prompts you to close Firefox when installing

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#1265]
No other torrent client installer prompts you to close your browser or require a require a reboot unless you close your browser. Can we get a fix for this or use another installer? This is quite obtrusive and is bound to annoy new users.

**Comment by DevilGeek** [comment]
Yea wtf.. it ask me to close :
- Firefox
- NVIDIA Container
- NVIDIA LocalSystem Container
- NVIDIA Share
- nvsphelper64.exe

**Comment by JiraiyaTheSage** [comment]
Same for me.... needs update.

**Comment by Pentaphon** [comment]
@livings124 @ckerr please look at this because it is causing issues for people who install Transmission on Windows and it would be nice if new users didn't have problems upon installing this great torrent client.

**Comment by Pentaphon** [comment]
I recently installed transmission-3.00+-rf8b3514c0e and the installer no longer asks to close Firefox.

Did a new version of the installer fix this issue?

**Comment by Pentaphon** [comment]
Tried another clean install of the latest nightly and again, this issue seems to have resolved itself by unknown means. It no longer asks you to close Firefox when installing. Closing!

**Comment by Pentaphon** [comment]
Never mind! It looks like Windows 11 still has this issue on the latest nightly as of this post I just clean installed this on my only Windows 11 machine. 
![ff](https://user-images.githubusercontent.com/49374058/186728220-6f0dbf11-6133-4ac4-8b29-0d9d5800e8bd.png)
! Screenshot below! I just tested this on my only Windows 11 machine.

**Comment by Pentaphon** [comment]
@mikedld @ckerr 

When I uninstalled Transmission Nightly just to see what would happen I noticed that it can adversely affect a person's Firefox installation. As soon as I uninstalled Transmission, I re-opened Firefox, and I got this error:

>"The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem."

https://support.mozilla.org/en-US/questions/1290656

The solution for this was to simply find another copy of VCRUNTIME140_1.dll on my system from another program and put it back into the Mozilla Firefox folder but this shouldn't happen to Transmission users and I expect a lot of people to complain about this issue when the beta comes out. 

Can you guys let whoever is in charge of packaging the Transmission installer for Windows about this? Perhaps the installer script needs to be upgraded to a new version? Or use another installer script entirely?

**Comment by Pentaphon** [comment]
This is still happening on 4.0.0-Beta 2 and I imagine a lot of people are seeing it during the install.

**Comment by mikedld** [comment]
Based on comments in https://bugzilla.mozilla.org/show_bug.cgi?id=1624546, I'd say this is an issue with Firefox (and NVIDIA?), not us. Transmission uses a documented approach to install the redistributable[^1] while Firefox seems to be doing some black magic.

[^1]: https://wixtoolset.org/docs/v3/howtos/redistributables_and_install_checks/install_vcredist/

**Comment by mikedld** [comment]
Ugh... [Redistributing Visual C++ Files](https://learn.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files) says that
> Merge modules (`.msm` files) for Visual C++ Redistributable files are deprecated. We don't recommend you use them for application deployment.

IIUC, fixing this would then mean either
* switching from `.msi` to `.exe` to be able to install the `.exe` version of vcredist automatically, or
* sticking with `.msi` and refusing to install before user installs vcredist on their own.

I'm leaning towards the second option because it's seemingly easier to implement.
