### ISSUE TITLE
IPv6 address in tracker URL

### ISSUE THREAD

**Issue by santost12** [transmission/transmission#1266]
Version: Transmission 3.00
Issue: Transmission is unable to connect to a tracker using its IPv6 address unless the tracker URL is a domain name. The tracker URL is typed correctly. Example:  "udp://[fd12:7777:9a76::1]:6969/announce"

![1](https://user-images.githubusercontent.com/45154554/82763909-7e9fad00-9dfa-11ea-95c0-16f55b206740.jpg)
![2](https://user-images.githubusercontent.com/45154554/82763908-7d6e8000-9dfa-11ea-9b4d-39face1f2af1.jpg)

**Comment by mtheophy** [comment]
Is the address reachable from the machine? Can you ping the IPv6 address? The address you showed is a ULA which is not routable over the public internet.

**Comment by santost12** [comment]
@mtheophy Yes. I can ping the address. It's part of my private network. I can confirm that the address works for other BitTorrent clients.

**Comment by ValZapod** [comment]
> I can ping the address

That is not enough. For link local and ULA you usually provide a network interface (scope ID) using %wlan0 notation (name or number). 

udp://[fd12:7777:9a76::1pe%15]:6969/announce
