### ISSUE TITLE
Request official ARM/ARM64/MIPS Release

### ISSUE THREAD

**Issue by samondlee** [transmission/transmission#1267]
Request official ARM/ARM64/MIPS Release

Nowadays,we have more low cost devices running in our houses.......

especially, ARM/ARM64(armbian),Mips (router)......

and we really need to download via them.........

so could transmission support ARM/ARM64/MIPS release officially?

**Comment by fcastilloec** [comment]
Usually, you can just add the Ubuntu repository to your Raspberry Pi (or other Debian OS using `armhf` or `arm64`). For v3.0, the Ubuntu repositories are not complete/working.

I usually add the Bionic repo because it's the closest to the Raspbian version I have. The Bionic repo still has v2.94 even though the Release file was updated when v3.0 was released.
Trying to add the Focal or Eoan repository just broke my installation. I only use `transmission-daemon` and it was not part of the updated packages. Only `transmission` and `transmission-common` have been updated for `armhf` and `arm64`. After checking their PPA page, it seems that they had some build errors for v3.0 packages on Bionic

So, if you only use the package `transmission` then adding the Focal repository might work if you want v3.0. If you rely on other packages like `transmission-daemon`, `transmission-gtk`, `transmission-qt` or `transmission-cli`, you're stuck on v2.94 for the moment.

**Comment by samondlee** [comment]
> Usually, you can just add the Ubuntu repository to your Raspberry Pi (or other Debian OS using `armhf` or `arm64`). For v3.0, the Ubuntu repositories are not complete/working.
> 
> I usually add the Bionic repo because it's the closest to the Raspbian version I have. The Bionic repo still has v2.94 even though the Release file was updated when v3.0 was released.
> Trying to add the Focal or Eoan repository just broke my installation. I only use `transmission-daemon` and it was not part of the updated packages. Only `transmission` and `transmission-common` have been updated for `armhf` and `arm64`. After checking their PPA page, it seems that they had some build errors for v3.0 packages on Bionic
> 
> So, if you only use the package `transmission` then adding the Focal repository might work if you want v3.0. If you rely on other packages like `transmission-daemon`, `transmission-gtk`, `transmission-qt` or `transmission-cli`, you're stuck on v2.94 for the moment.




sad..... i use transmission-daemon...thanks for your reply

**Comment by fcastilloec** [comment]
Just and FYI, the Bionic repo has been updated with v3.0 but it has the same problem as Focal, no updated version for `transmission-daemon`.
I hope one of the developers can address this and provide an updated PPA that includes all packages for `armhf` and `arm64`

**Comment by anoteng** [comment]
The PPA only have i386 and amd64 builds, AFAIK there is no support for arm
build on launchpad yet.

You could download the source package from the ppa and build it yourself:
dget url.to.source.package.dcs && cd transmission-3.00 && debuild
Probably needs an apt install devscripts and apt build-dep transmission
first.
This should generate a .deb for the arch you're currently on.


ons. 27. mai 2020, 23:47 skrev Felipe Castillo <notifications@github.com>:

**Comment by fcastilloec** [comment]
@anoteng I'm confused, if there's no support then why does this exist http://ppa.launchpad.net/transmissionbt/ppa/ubuntu/dists/bionic/main/binary-armhf/Packages.gz

You can add that repo to any `armhf` and install transmission without a problem, but it seems that what we need is `transmission-daemon` also to be included there.

**Comment by anoteng** [comment]
Have you tested that it actually works?
Two of the packages are arch independent transmission and
transmission-common. All of the client packages and the daemon package ar
built for the target arch, currently only i386 and amd64.

Last I read only the core ubuntu teams could enable arm supoort on PPAs,
but while looking for a link to give you I found out that it can now be
enabled by anyone. I have now enabled the three supported arm archs, and
will try to start builds soon.

P. S. The Ubuntu PPA on Launchpad is not part of the transmission project,
and really don't belong in this bugtracker. I am not part of the
transmission dev team, but i do maintain the transmissionbt ppa on
launchpad.

Andreas

tor. 28. mai 2020, 06:48 skrev Felipe Castillo <notifications@github.com>:

**Comment by anoteng** [comment]
The PPA now contains binaries for arm64 and armhf

**Comment by fcastilloec** [comment]
Thanks so much @anoteng!!! For any future problems, I'll make sure to contact you from Launchpad.

For everybody that's trying to install this PPA on a Raspberry Pi 4 (Debian Buster), use the `eoan` Ubuntu version. Bionic it's too old and the dependencies won't work. Bionic needs `libminiupnpc10` while Eoan uses `libminiupnpc17` which is also found on the Raspberry Pi repositories.

@samondlee this issue should be close now

**Comment by samondlee** [comment]
@fcastilloec @anoteng 
Thanks! issue closed
