### ISSUE TITLE
Setting Limit Download to 0 KB/s prevents uploading

### ISSUE THREAD

**Issue by julian-wolf** [transmission/transmission#127]
Setting the Limit Download field of a single transfer to 0 KB/s seems to stop any data from being uploaded on the transfer. Peers still appear in the peer list, but no data are sent.

I'm running Transmission 2.92 on OS X El Capitan (10.11.6).

**Comment by cfpp2p** [comment]
> It's not too difficult to patch so that per-torrent behavior is
> consistent with the global speed limit behavior.

and to fix it all to function as you'd expect.

Analysis here for both download zero and upload zero.
https://forum.transmissionbt.com/viewtopic.php?f=1&t=17757#p72913

**Comment by tearfur** [comment]
Fixed by #5821.
