### ISSUE TITLE
Clicking group delta in list view doesn't properly expand/collapse

### ISSUE THREAD

**Issue by cylott** [transmission/transmission#1270]
I just upgraded to Mac client 3.0 and noticed an ol' bug is still there. If you're looking at your list of torrents, and click the delta next to a group, occasionally it will not expand/collapse as expected. I find this happens if I expand a group and then very quickly click the delta again.

**Comment by Coeur** [comment]
Can you try the macOS Transmission 4.0 client?

**Comment by ckerr** [comment]
> Can you try the macOS Transmission 4.0 client?
> If you reproduce, can you provide a screenshot for clarity?

**Comment by Coeur** [comment]
The request for clarification has been there for 3 months, so I'll close the issue, as I've never experienced it and it may have been fixed already.

Feel free to reply to this issue or reopen a new one if you have a reproduction and screenshot in Transmission 4. Thanks.
