### ISSUE TITLE
Pre-Update torrents don't download anymore

### ISSUE THREAD

**Issue by Phenix-Feedback** [transmission/transmission#1271]
Step to reproduce:

- Have torrents _not finished_
- Update Transmission
- Restart Windows
- Start Transmission and try to continue downloading

Result: nothing happen. 
Seeding is working. I tried to delete the torrent and reput the torrent (keeping the .part file), but it's not working too. I've a bunch of partly downloaded torrent which are quite lively (check with someone else and with another torrent) so it's not a lack of seeders. Ask me anything you need.

Windows 10 1903 18362.836
Transmission 3.00 bb6b5a062e
 
Edit: btw I need to alt+enter the previous torrent to make it "recognised" (I don't have a better term) for them to work.

**Comment by revolter** [comment]
What does alt+enter do?

**Comment by Phenix-Feedback** [comment]
It opens the Properties of the torrent. By doing that the torrent is "recognised" again.
Picture below will show you. Top is after opening properties, bottom is after starting Transmission. It happens at every start-up.

https://i.imgur.com/6v7GTSU.png

**Comment by Phenix-Feedback** [comment]
I'm closing the issue it seems resolved for me.
