### ISSUE TITLE
mixes unix and windows paths

### ISSUE THREAD

**Issue by trgswe** [transmission/transmission#1273]
there seems to be a error in the filepath handling
if you put S:\Arcade in the download location and try to dowload  for instance
fix-it-felix and it contains fix-it-felix/fix-it-felix.d64
then transmissionbt Qt interface tries to open/create S:\Arcade/fix-it-felix/...

might not be related to another bug where transmission does not see network url's/UNC's

**Comment by mikedld** [comment]
Is there a particular error you're seeing? You didn't specify your operating system, but forward slashes are supported on Windows for the most part, and obviously on *NIX, so the look of the path is not an issue in itself and I don't see a problem in the behavior you're describing.

If you're saying that you're on Windows and S: is a network drive, you will have to mount it with the same user Transmission is running as which appears to be a known limitation.
