### ISSUE TITLE
Menus on the Web interface are overlapped

### ISSUE THREAD

**Issue by S-Aarab** [transmission/transmission#1275]
the **#torrent_inspector** gets on top of **#torrent_context_menu** and  **#footer_super_menu**

<img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/32977495/83107161-a8382d00-a0b5-11ea-8127-2d10d91f6814.png"> <img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/32977495/83107171-ae2e0e00-a0b5-11ea-9189-46fb92e5cfe8.png">

firefox  76.0.1
transmission 3.00

**Comment by ckerr** [comment]
This is fixed by #1476
