### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by richbee0** [transmission/transmission#1276]
The previous Transmission application is unable to update to latest version. When trying to update from Transmission 2.94 (MacOS 10.15.5) to Transmission 3.00 using the application's internal updating function, the application fails and reports an "Update Error! An error occurred while extracting the archive. Please try again later".

(This problem also existed when trying the same operation in MacOS 10.15.4)

**Comment by DevilDimon** [comment]
Duplicates #1261
