### ISSUE TITLE
Torrents are not downloaded after updating to 3.0.0 on macOS

### ISSUE THREAD

**Issue by revolter** [transmission/transmission#1277]
After updating to 3.0.0, no torrent is downloading anymore. Regardless of when I added it (before or after the update). They're stuck in this state:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/5748627/83114175-4f768d80-a0d1-11ea-9715-c4683ede6293.png">

I tested the same torrent on another PC with a different client, and it started downloading.

**Comment by x-Felix** [comment]
probably because Nexusphp based site is not allowing transmission 3.0 as for now.

**Comment by Aniverse** [comment]
I run transmission-daemon on my Linux server and use Transmission Remote GUI on my PC. You can check a torrent's tracker status with remote gui.

If you were downloading torrents from private tracker, this means that tracker hasn't added Transmission 3.0 to client whitelist.
Typically when there is a major version update, it would take more time for sysop to check the new client.

**Comment by revolter** [comment]
Oh, wow, didn't know about this. Indeed, the latest version was not added to the whitelist. Thank you!
