### ISSUE TITLE
3.00 doesn't connect to any peers

### ISSUE THREAD

**Issue by Mlocik97-issues** [transmission/transmission#1278]
Hello,

I have updated to 3.00 on Ubuntu 18.04 LTS, and now I can't connect to any peers. I'm activ, other peers are activ too. Client correctly download list of peers from tracker. But after that, torrent is freezed at "Downloading from 0 from total 0 peers". I tried reinstall `sudo apt-get purge transmission-gtk transmission-common transmission-daemon transmission-cli `and then do this commands:

`sudo add-apt-repository ppa:transmissionbt/ppa`
`sudo apt-get update`
`sudo apt-get install transmission-gtk transmission-common transmission-daemon transmission-cli` 

but didn't help.

Tracker see me as activ, and seeding these torrents.

![Snímka obrazovky z 2020-05-28 21-24-59](https://user-images.githubusercontent.com/31345346/83184663-0ef72e00-a12a-11ea-9595-ef6f666a3954.png)

After 2 hours, it's still the same.

**Comment by Mlocik97** [comment]
OK, I solved it...
first I changed rpc-authentication-required on false then restart and then back to true. And then deleted: var/libs/transmission-daemon/info/resume a var/libs/transmission-daemon/info/dht.dat
