### ISSUE TITLE
net.c: tr_netSetTOS() attempts to set `IP_TOS` on IPv6 sockets using `IPPROTO_IP`.

### ISSUE THREAD

**Issue by villavic** [transmission/transmission#128]
Which fails with `EINVAL`.

For IPv6 sockets the appropriate flags would be: `IPPROTO_IPV6`, and `IPV6_TCLASS`.

**Comment by mikedld** [comment]
Thanks for reporting this. I don't have an IPv6 network at hand and I would hate to fix it blindly (I don't really like network programming that much). I'm okay with merging a PR though from someone who knows what he's doing and who's capable of testing the change.

**Comment by mikedld** [comment]
Closing by #360 and #737.
