### ISSUE TITLE
Cannot downgrade, all active torrents lose their download location

### ISSUE THREAD

**Issue by Endemoniada** [transmission/transmission#1280]
I'm trying to downgrade to 2.94 on Arch Linux, but when I do the old resume files no longer have the correct download path in them. They've all been set to the default download location, which means they can't resume properly.

Is there a way to safely downgrade from 3.0 to 2.94 and keep all the current resume information?

**Comment by ckerr** [comment]
Probably not? The file naming scheme for .resume and .torrent files changed to fix https://github.com/transmission/transmission/issues/122.

You might be able to go in and rename the files back to the old names by hand, but there's no way inside of the Transmission application to downgrade the files. 2.94 doesn't have any knowledge of the changes that 3.00 made.
