### ISSUE TITLE
missing icon on close

### ISSUE THREAD

**Issue by mattia-b89** [transmission/transmission#1288]
Starting with new 3.00 version,  
icon on shutdown is missing, replaced by fallback one.

I attach the screenshot below:
![screen](https://user-images.githubusercontent.com/545463/83338990-cd04ee00-a2c9-11ea-855b-8a7558bf6647.png)

---

Transmission 3.00 on Arch Linux w/ GNOME 3.36.1

**Comment by mikedld** [comment]
@mattia-b89, could you check if this is fixed in current `main`, after a fixup as part of #3916.

**Comment by mattia-b89** [comment]
> @mattia-b89, could you check if this is fixed in current `main`, after a fixup as part of #3916.

unfortunately I can't test it now;

**Comment by Harm133** [comment]
Looks good to me :) 

On [4b65c4f](https://github.com/transmission/transmission/commit/4b65c4fa2814a71a571700928ae9457b04270eb9)


![IconNotMissing](https://user-images.githubusercontent.com/1971429/195450575-4e8a3891-4f27-4ba9-a1a1-1ec793dc210e.png)

**Comment by mikedld** [comment]
Thanks @Harm133, closing.

**Comment by asoymos** [comment]
Hi, I have the same situation. It is a missing icon in the icon theme, as I have it in another computer with another theme. Can you please tell me what is the icon name?

**Comment by asoymos** [comment]
If anyone is having this issue, manually add `gtk-network` icon in `apps` folder in icon theme.
