### ISSUE TITLE
transmission 3.0, ubuntu web interface - stopped downloading

### ISSUE THREAD

**Issue by ageekhere** [transmission/transmission#1291]
Hi, just updated to transmission 3.0 on ubuntu and now in the web interface downloads are not running and new downloads are stuck on retrieving metadata.

**Comment by S-Aarab** [comment]
maybe 3.0 was not added to the whitelist yet  #1277

**Comment by anoteng** [comment]
I'm experiencing the same. Public trackers work, but private don't. I have confirmed that it is not a whitelist issue, and I've tried with both resuming old torrents and starting new ones.

**Comment by ageekhere** [comment]
i think this is the case

**Comment by ageekhere** [comment]
issue is still there for me

**Comment by ageekhere** [comment]
I think the problem at the time was it was not added to the whitelist yet so for a time it had this issue. Maybe something to keep in mind for new updates.
