### ISSUE TITLE
torrent-done script uses unnecessary memory because it uses fork()

### ISSUE THREAD

**Issue by BrainSlayer** [transmission/transmission#1299]
the torrent done exec script will fail in alot of cases. the reason is simple. transmission will usually allocate alot of memory while its running and the script is called from a processfork of transmission by itself. this will double the memory consumption since the whole process is cloned. the result is 
(12): Call to fork() failed: Out of memory (torrent.c:2276)
the script execution should be changed. a shell call can be used for instance to fork it outside of transmission to avoid cloning of the whole main process

**Comment by SyntrophicConsortium** [comment]
Is this new? Transmission was just updated to 3.0 on my system, and the script no longer executes. It worked fine before. Nothing has changed aside from upgrading from 2.94 to 3.

**Comment by BrainSlayer** [comment]
@SyntrophicConsortium it happend also before, but only frequencly. the new updated version was runnng straight into this problem. it is easy to fix. forking a process which takes several hundert megabytes of memory is never a good idea.  especially if you run it on embedded systems

**Comment by mikedld** [comment]
I think you're misinformed on how `fork()` works. Linux man page states in its NOTES section:
> Under Linux, `fork()` is implemented using copy-on-write pages, so the only penalty that it incurs is the time and memory required to duplicate the parent's page tables, and to create a unique task structure for the child.

The same/similar is usually true for non-Linux systems too. This means that no memory use "doubling" occurs as the pages are shared unless one modifies them. Think about it: duplicating all the pages' content on `fork()` would make this call quite expensive/slow.

Executing via a shell (e.g. using `system()`) uses `fork()` as well, so there will be no difference.

**Comment by BrainSlayer** [comment]
okay. then tell me why the fork call fails with out of memory, even if 300 mb ram is free and no system doesnt use fork. it uses standard spawn which uses vfork (which has a different behaviour than fork since it doesnt copy all page tables) and is executing the commit using /bin/sh
anyway. "fork" fails with out of memory. "system" works and the only reason can be that fork does indeen requires too much memory. vfork could be worth a try of course. but the use of fork here is wrong. its not working since it requires the doubled size of memory even if not used due cow. 
in any way. a fork with duplicated pages is not required since its only used for command execution but dos not require any access to local data

**Comment by BrainSlayer** [comment]
replacing fork with vfork works perfect btw

**Comment by cmcasanova** [comment]
> Is this new? Transmission was just updated to 3.0 on my system, and my script no longer executes when a torrent has completed downloading. It worked fine before. Nothing has changed aside from upgrading from 2.94 to 3.

Ran into this issue myself.  To troubleshoot my script, I configured it to do a touch on a file, and found that it worked.  If I called it with sudo the script does not work, while in previous versions using sudo in my script did work.  Enabling log-info will display if the script is executed successfully (or fails due to permissions or missing file).

**Comment by BrainSlayer** [comment]
@cmcasanova if the script has the same rights as transmission it should work. so both must have the same user rights. but the problem i discovered has nothing todo with user rights. it has something todo how the script is executed and will simply cause a out of memory on smaller embedded systems. i made also a internal patch for it. (simply replace fork with vfork) and this fixes the problem immediatly

**Comment by SyntrophicConsortium** [comment]
I'm not running it on a smaller embedded system, and it's not a permission error, as far as I can tell. Permissions haven't changed. The only change in my case is transmission was updated.

**Comment by ckerr** [comment]
https://stackoverflow.com/questions/4259629/what-is-the-difference-between-fork-and-vfork says that vfork is likely to be marked as deprecated, so I'm doubtful that we'd get any advantage from switching from fork to vfork.

Also this comment sticks out:

> With most current kernels, however, including Linux, the primary benefit of vfork has disappeared because of the way fork is implemented. Rather than copying the whole image when fork is executed, copy-on-write techniques are used.

This is very similar to what @mikedld mentioned previously at https://github.com/transmission/transmission/issues/1299#issuecomment-640190686.

If this is still a problem, could you describe what kind of system you're running on? I wonder if it's an issue with fork on that version of that system, rather than a problem with fork in general.

**Comment by ckerr** [comment]
Closing due to lack of clarification and because it looks like this is not the problem it was originally suggested to be

**Comment by BrainSlayer** [comment]
it seems more you closed it due the lack of understanding how fork works. fork clones the whole process with all memory. so on embedded systems it eats up all memory and crashes. bug is still persistent. (i fixed in in my own version of course, otherwise transmission is not usable for embedded systems)
