### ISSUE TITLE
Allow to change the language in UI

### ISSUE THREAD

**Issue by ulrichb** [transmission/transmission#130]
... so that the workaround described [here](http://trqtw.sourceforge.net/blog/transmission-qt-for-windows/known-problems/) isn't needed anymore. Note that on Windows the second workaround doesn't even work because the MSI installer restores deleted language files when starting Transmission.

**Comment by mikedld** [comment]
Since the link points to trqtw.sf.net (which is currently gone, not sure if forever), I'm guessing you're talking about Qt client. I'll also guessing (from memory) that one of workarounds involved setting LANG or LC_ALL environment variable, and the other was about removing the uneeded .qm translation files.

Which language is your operating system using? Which language do you want Transmission to be displayed in? If those differ and automatically detected language matches your operating system, could you explain why do you not want Transmission to use the language it detects?

**Comment by ulrichb** [comment]
@mikedld: I have an English Windows with a German "locale" ("Region settings").

I think the problem is that you use [`QLocale().name()`](https://github.com/transmission/transmission/blob/5e18ddbca8bd23640c0722b50aca3c46b202c410/qt/Application.cc#L314) (which is "de_AT" on my machine) to load the translation files instead of [`QLocale::uiLanguages()`](https://doc.qt.io/qt-4.8/qlocale.html#uiLanguages) (which is "en-US" on my machine).

**Comment by mikedld** [comment]
Thanks for the hint @ulrichb, I've made some changes. Would be great if you could try latest [x86](http://trtc.mikedld.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Transmission_WindowsX86&tab=artifacts) or [x64](http://trtc.mikedld.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Transmission_WindowsX64&tab=artifacts) build to see if it helped.

**Comment by ulrichb** [comment]
Hi @mikedld,

Thanks for taking a look at this issue. 

Why did you choose [`QLocale::system()`](https://doc.qt.io/qt-4.8/qlocale.html#system) instead of `QLocale::uiLanguages()`? This still returns "de_AT" on my system. Note that `QLocale::system()` is the same as the previously used [`QLocale()`](https://doc.qt.io/qt-4.8/qlocale.html#QLocale) constructor, the only difference is that its result can be overridden by using `setDefaultLocale()`.

**Comment by mikedld** [comment]
@ulrichb, `QLocale::uiLanguages()`, as you mention it, is not a thing. The method is not static and should be called on a `QLocale` object which I need to get from somewhere, and without knowing the exact locale to construct there aren't that many options: `QLocale::c()` (which isn't what we want for sure), `QLocale::system()` (which gets locale settings from the system and is most probably what we need), and `QLocale()` (which as you mention is the same as `QLocale::system()` unless `QLocale::setDefault()` is called which we don't do as we don't know what to set it to). Unless you clarify how exactly you're getting `uiLanguages()` to return "en-US" (i.e., where do you get `QLocale` object to call this method on) I'm unsure how to proceed.

**Comment by ulrichb** [comment]
OK. Here my sample program ...

```C++
qDebug() << "QLocale():" << QLocale().name();
qDebug() << "QLocale::system()" << QLocale::system().name();
qDebug() << "QLocale().uiLanguages() length:" << QLocale().uiLanguages().length();
qDebug() << "QLocale().uiLanguages() [0]:" << QLocale().uiLanguages().at(0);
```
... prints ...
```plain
QLocale(): "de_AT"
QLocale::system() "de_AT"
QLocale().uiLanguages() length: 1
QLocale().uiLanguages() [0]: "en-US"
```

**Comment by mikedld** [comment]
I presume this:

```c++
qDebug() << QLocale::system().uiLanguages().at(0);
```

also prints "en-US" then, doesn't it? In any case, using `QLocale()` instead of `QLocale::system()` might still be beneficial...

**Comment by ulrichb** [comment]
Ahh the [QLocale::uiLanguages() docs](https://doc.qt.io/qt-4.8/qlocale.html#uiLanguages) state _"Most like you do not need to use this function directly, but just pass the QLocale object to the QTranslator::load() function"_.

=> Your change in [line 78](https://github.com/transmission/transmission/commit/6c9fa2913b368f2cd1e06a59176396576644c934#diff-9bb3d88c46a9f8249c07bff26a8a6e1dR78) already fixes my issue.

Thanks!

**Comment by mikedld** [comment]
Yeah, I'm not calling `name()` on locale object anywhere myself. Still changed to `QLocale()` in 13e111a89aa98f92b6e7a151e59ca79cde5e4edf ;) Thanks for testing!

**Comment by ulrichb** [comment]
Thanks again. BTW: Great Torrent client!

**Comment by dangpzanco** [comment]
This bug is only fixed on the nightly builds (if anyone came here via google "transmission change language").

Also, I'd like to suggest a drop-down menu for language selection, so the user can change the language at will.

**Comment by Fawers** [comment]
I second @dangpzanco 's suggestion about the drop-down list. Came from qBitTorrent, and I'm loving Transmission so far. Using it on Android, Linux and Windows.
