### ISSUE TITLE
Export /metrics to Prometheus

### ISSUE THREAD

**Issue by yegle** [transmission/transmission#1304]
It would be great if Transmission daemon can export a /metrics HTTP handler so Prometheus can scrape and collect metrics from Transmission.

Right now there's a third party exporter that communicate with Transmission and export the /metrics handler, but it would be great if Transmission can natively support this.

**Comment by james7132** [comment]
Commenting just to show my support for this feature and also highlight that access to this endpoint should have a config-established bearer token or mirror the same basic auth requirements as the rest of the web interface.

**Comment by ckerr** [comment]
This sounds like a great idea.

Unfortunately, none of the maintainers have expertise with Prometheus. More importantly, this would be scope creep to Transmission when the developer team is spread extremely thin. IMO it just doesn't make sense to commit to new things like this if we don't have the time and expertise to properly maintain it.

If the third-party tool is well-maintained, please open a PR to add it to the `electron/electron` [docs](https://github.com/transmission/transmission/blob/main/docs/README.md). Thanks!

**Comment by raspbeguy** [comment]
Quick update for the next user looking for that feature:

Here is the [prometheus exporter for Transmission](https://github.com/metalmatze/transmission-exporter). Sadly the project is stalled and looking for new maintainers. There is a [fork](https://github.com/leijurv/transmission-exporter) that fixes some performances issues.

I post it there to add more visibility to this great project that just needs a bit more maintainers and love.

I fully understand the argument of not wanting to maintain a feature that can be assumed by third-party tools.
