### ISSUE TITLE
Can multithreading be supported？

### ISSUE THREAD

**Issue by mjyhj** [transmission/transmission#1305]
Some CPUs have low single frequency, which will cause webui to jam when downloading large files

**Comment by alaa13212** [comment]
I think this is supported but no enabled. Enabling it require compiling your own version.

Explanation [here](https://github.com/transmission/transmission/wiki/Can-I-sequence-the-files-I-download)

**Comment by antivirtel** [comment]
Same happens to me, allocating files should be a separate thread in the background, so the GUI still stays responsive

**Comment by ckerr** [comment]
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.
