### ISSUE TITLE
Adding duplicate torrent   

### ISSUE THREAD

**Issue by Anan5a** [transmission/transmission#1309]
Is there any way to add or force add a duplicate torrent in transmission? 
Let's say a torrent with hash ```abcd...``` is downloading in  ```/home/user/abcd``` now is it possible to add the same torrent to download under a different directory? eg. ```/home/user/another/abcd```

**Comment by Mlocik97-issues** [comment]
I don't know why you would want something like this,... but You can just create script to autocopy that or use symlinks...

**Comment by Anan5a** [comment]
@Mlocik97-issues yes, i am planning to do exactly that
