### ISSUE TITLE
tr_fdFileCheckout failed 

### ISSUE THREAD

**Issue by mengyyy** [transmission/transmission#1311]
Hello:
   Since i had upgrade to 3.0 but the same file name too log issue exists.
   This time it cause `tr_fdFileCheckout failed ` and `Main process exited`.
   I download this magnet link `magnet:?xt=urn:btih:4d58e813920883ce52a581a951190035ce03339b`
Thank you

**Comment by ckerr** [comment]
Same issue as https://github.com/transmission/transmission/issues/2311
