### ISSUE TITLE
Feature Request: make the settings menu available in mobile web

### ISSUE THREAD

**Issue by Endemoniada** [transmission/transmission#1316]
I would like to request that the settings menu be made available when browsing the web GUI on a mobile device, specifically (in my case) to be able to change the sorting to "age". I have hundreds of torrents and would like to se my most recent ones at the top of the page, but with the mobile CSS that's impossible due to the entire settings menu being disabled.

It would also be helpful if the Transmission web GUI respected the "request desktop version" option in modern mobile browsers, which would also enable use of the settings menu.

**Comment by readstead** [comment]
Both of these would be great improvements. It’s so hard to manage this from mobile.

**Comment by ckerr** [comment]
This was fixed a long time ago and I forgot to close this issue. It was fixed by the web client rewrite.
