### ISSUE TITLE
Focus should change to filter bar when invoked.

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#132]
When a user hits "Show Filter Bar" the focus should switch to the filter bar so that it may be used immediately instead of having to manually click on it.

**Comment by Harm133** [comment]
I dont think this change is required anymore; Seems to have been fixed somewhere along the line :)
On f1f55cc3df1105d03549251c6023726829179838 :

https://user-images.githubusercontent.com/1971429/195209363-637bed18-1890-48d7-b59f-895dd2b88d01.mov

**Comment by ckerr** [comment]
Closing based on previous comment by @Harm133
