### ISSUE TITLE
Transmission 3.00+ crashing every other day on Windows 10

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1324]
Transmission 3.00+ (somenumber: what is it? is it privacy risk to disclose?)
Windows 10 64bit

Windows says program crashed (no details) and offer to close it.
Is there anyone who is able and willing to fix this?
If yes, please reply and let me know what to do exactly to supply required data. I prefer if i can provide it in private.

**Comment by ckerr** [comment]
Easiest thing to try first is to download a nightly build and report back if it's still crashing. There's been a ton of work on the Qt client since June 2020

**Comment by slrslr** [comment]
Thank You. Unfortunately i am no longer using that operating system.
