### ISSUE TITLE
Sleep time per second is hard coded

### ISSUE THREAD

**Issue by lps-rocks** [transmission/transmission#1331]
https://github.com/transmission/transmission/blob/2ef07517b65e98c0c68bbff0ca2467434a1835d2/libtransmission/verify.c#L30

This value is hard coded and wastes at least 10% of time. This should be a user configurable option with sensible defaults. The other option is to implement a system that detects read latency and once it's over a certain point, begins to back off.

**Comment by ckerr** [comment]
The problem with user-configurable options is that we have a macOS, Qt, GTK, and Web client -- every little feature that gets added requires a *lot* of extra work to expose in the GUI.

Possibly more importantly, most users would be confused by an option that read something like "sleep interval during verify (msec): 100" and so all that work would go to a feature that only a couple of people would use.

I'm more in agreement with the idea that latency could be detected and throttled back. Looks like that interval was added specifically as a heuristic for not overwhelming IO:

```c
  /* sleeping even just a few msec per second goes a long
   * way towards reducing IO load... */
  if (lastSleptAt != now)
  {
      lastSleptAt = now;
      tr_wait_msec(MSEC_TO_SLEEP_PER_SECOND_DURING_VERIFY);
 }
```

If someone wants to work up a better version of this code, and it's simple and cross-platform, I'd be happy to review it.

**Comment by andreygursky** [comment]
> The problem with user-configurable options is that we have a macOS, Qt, GTK, and Web client -- every little feature that gets added requires a lot of extra work to expose in the GUI.

One approach is to put all highly customizable properties into a unified GUI (with comments where needed). Perhaps the best-known implementation is the Firefox's 'about:config'. This approach is also adopted by smaller projects like Gajim ([Advanced Configuration Editor](https://dev.gajim.org/gajim/gajim/-/wikis/help/ACE)).

**Comment by ckerr** [comment]
The approach that's worked in Transmission for this is exposing the feature in `settings.json` where power users can find it without cluttering up the GUI. (Since Transmission has multiple GUIs, this is also a work-saver in that the change can be made once instead of once per GUI.)

To the original report of not hardcoding the sleep time, if someone makes a patch for this in settings I'll be happy to review it
