### ISSUE TITLE
Add window still appears when option boxes are unchecked

### ISSUE THREAD

**Issue by listingpro** [transmission/transmission#1332]
Unsure if this is an issue or how it works.
I recently started using groups and criteria to assign custom locations. When I click a torrent or magnet link I'm always presented with the add window even if there are no "add window" check boxes checked.
Add window appears even if torrent file doesn't match any group criteria filters, which should be the default location

**Comment by ckerr** [comment]
What version of Transmission are you using? And on what platform?

**Comment by ckerr** [comment]
Closing due to lack of response + lack of actionable info.
