### ISSUE TITLE
[BUG] libtransmission cannot parse hybrid torrent files

### ISSUE THREAD

**Issue by uno20001** [transmission/transmission#1339]
BEP 52 sets out the upgrade path towards BitTorrent v2, and this describes so-called "hybrid" torrents, which contain both BitTorrent v1 and v2 keys. Unfortunately libtransmission, as of yet, is unable to parse hybrid torrents. The reason for that is that empty strings are handled specially, and - as far as I can see - used to indicate invalid strings / errors. BitTorrent v2 heavily utilizes empty strings as directory keys, and that prevents libtransmission from parsing hybrid torrents.

One problematic line is [`variant-benc.c:161`](https://github.com/transmission/transmission/blob/master/libtransmission/variant-benc.c#L161), which causes parsing to fail if the quark id is zero, which happens when an empty string is encountered. 

A solution I see is a new value for `TR_KEY_NONE`, that is not the empty string. It could be `NULL`, however, then I think [`quark.c:compareKey()`](https://github.com/transmission/transmission/blob/master/libtransmission/quark.c#L416) should be prepared to handle `NULL`. I don't know how much of the code base relies on `TR_KEY_NONE` being and empty string, so this is just speculation.

I would appreciate if a fix could be implemented, since, hopefully, more and more BitTorrent clients will start to move away from BitTorrent v1 to BitTorrent v2.

**Comment by sbrudenell** [comment]
This creates a chicken-and-egg problem for adopting v2.

Clients don't support v2 because publishers aren't creating v2 torrents; publishers aren't creating v2 torrents because they break existing clients...

**Comment by MaddTheSane** [comment]
I'd say at least add support for hybrid torrents, even if BT2 support isn't planned.

**Comment by bagobones** [comment]
libtorrent based clients have started being released that create their torrents by default in hybrid mode. Transmission could quickly become a dead client without at least hybrid support.

The point of hybrid torrents was supposed to be backward compatibility so I suspect a fix to ignore the extra metadata would not be that hard.

**Comment by ludwig-v** [comment]
@uno20001 gave a good hint on where to search. Just remove from line 161:

    *key != 0 && 

tr_bencParseStr() must also be modified to handle 0 length string without triggering an error by adding:

    if (end == 0) {
    	*setme_end = (uint8_t const*)end + 1;
    	*setme_str = (uint8_t const*)end + 1;
    	*setme_strlen = 0;
    	return 0;
    }

Right after:

    end = memchr(buf, ':', bufend - buf);

And hybrid bencoded torrents will work 😄

**Comment by ckerr** [comment]
Fixed by #1964

**Comment by uno20001** [comment]
Thanks!
