### ISSUE TITLE
The program “transmission” does not display an application window.

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#1340]
I try to start programs (according to the version “3.00-151.2”) for the handling of torrent files on my Linux system once more.

```
elfring@Sonne:~> transmission-gtk

(transmission-gtk:5561): Gtk-WARNING **: 07:50:38.337: Theme parsing error: gtk.css:1:34: Invalid name of pseudo-class
[warn] Unable to parse nameserver address fe80::1%br0
…
elfring@Sonne:~> transmission-qt
qt5ct: using qt5ct plugin
…
[warn] Unable to parse nameserver address fe80::1%br0
```

Now I wonder again why the corresponding application windows are not displayed for my XFCE session at the moment.

**Comment by ckerr** [comment]
Transmission doesn’t touch gtk.css; likely this is caused by a system configuration issue. Googling for that error message shows similar reports for Firefox and Evolution.

If this is repeatable on a fresh system, please open a new ticket. Thank you!
