### ISSUE TITLE
Text visibility issue in v3

### ISSUE THREAD

**Issue by unknown--** [transmission/transmission#1341]
OS: Mac OSX 10.11

After upgrading to version 3 I've noticed that the smaller text used for file size, transfer speed and such is a lot harder to read.
The attached image shows the difference with the top torrent taken from version 2.94 and the bottom from version 3.
![Screen Shot 2020-06-28 at 10 46 13 PM](https://user-images.githubusercontent.com/7199527/85936206-a32bff00-b93b-11ea-9124-1be5db92bf9c.jpg)

**Comment by bart-kneepkens** [comment]
Do you have a proposal for a solution? Could use another color for the 'status' label, but I'm not sure it'd improve readability. I'm also not sure what changed it between versions, as in both versions it seems to be `NSColor.secondaryLabelColor`

**Comment by GaryElshaw** [comment]
I had a similar problem and made this hack. https://github.com/GaryElshaw/Ocular

**Comment by ckerr** [comment]
Fixed by #3571?

**Comment by GaryElshaw** [comment]
Fixed!
