### ISSUE TITLE
Open Folder not working

### ISSUE THREAD

**Issue by andradadad** [transmission/transmission#1342]
3.00 (7e1da2d), firefox78-win764bit

Constant bug since many versions, also works randomly.
In some previous versions, single files, unlike folders, would open /mydocuments/ folder even that the default location download was never set there.

**Comment by vjayer** [comment]
I also get this. I can verify that single files never had open folder work correctly, as it would always open the user's documents dir instead. As for a torrent with directory, I found a workaround for to make Open Folder work reliably: Always view the torrent's Properties first, then Open Folder works afterwards for that torrent.

**Comment by andradadad** [comment]
> 
> 
> Always view the torrent's Properties first, then Open Folder works afterwards for that torrent.

Wow! Thank you for the tip, I created the same issue years ago but developers never showed any care for replying. Not then, now neither.
Great advice for those with the same problem.

Will start using it from now on!

**Comment by EvanK** [comment]
Transmission 3.00 (bb6b5a062e) on Win10 Pro x64

Similar issue for me, the "Open Folder" option only works sporadically, most of the time doing nothing.

Does not appear to make a difference whether the torrent creates a file or folder.

**Comment by mikedld** [comment]
Please don't combine multiple issues in one report. See #1095, #325.

**Comment by syddel** [comment]
I'm using Arch Linux. This problem only occurs on `transmission-qt` (version 3.00), not with `transmission-gtk`. On another laptop running Kubuntu 18.04 with `transmission-qt` 2.6, this issue does not occur.
