### ISSUE TITLE
Helm chart for transmission-daemon

### ISSUE THREAD

**Issue by kurczynski** [transmission/transmission#1348]
I'm setting up Transmission as a dedicated service for my network and would love to be able to deploy it using Helm. It should be pretty straight forward to create a Helm chart and automate the build to push it up to Helm Hub for distribution.

**Comment by ckerr** [comment]
I'd group this into the same category as other requests to make Docker or flatpak images of Transmission -- things that are nice-to-have, but which would require the maintainers to take on new maintenance responsibilities for these new components.

If some third party wants to create this and maintain it, e.g. in a github repo, and then submit a PR to link to it in the `transmission/transmission` [docs](https://github.com/transmission/transmission/blob/main/docs/README.md), I'd be happy for that. But the Transmission team is already very small and spread very thin, so it doesn't make sense to commit to new maintenance responsibilities.

**Comment by GScottElshaw** [comment]
>transmission/transmission [docs](https://github.com/transmission/transmission/blob/main/docs/README.md), I'd be happy for that

Or the new website!
