### ISSUE TITLE
[Feature Request] set down-/upload limit per day (or other time unit)

### ISSUE THREAD

**Issue by cmdtstof** [transmission/transmission#1349]
debian: transmission (-gtk) 2.92 (14714)

when having an internet data package for a daily limited amount of GB, it would be very helpfull beeing able to set a download limit per day (or other time units).

for example set „1GB / d“ and transmission is keeping track of the downloaded amount from 00:00 till 23:59 of that day, even when the app is closed and started again later.
if limit is reached, down/upload is stopped with a message indicating it.

thanks for the greath tool

**Comment by fateslayer** [comment]
Yes I agree, we should have such a feature

**Comment by ckerr** [comment]
This is exactly the kind of use case that scripting is good at. It's a feature that would be very useful for a handful of people but not to anyone else, so it doesn't make sense to put it into Transmission itself. Solution, write a script to connect to Transmission, watch the transfer stats, zero out the download speed, and reinstate it at 23:59.
