### ISSUE TITLE
[Feature] "Alias" location when using a remote client

### ISSUE THREAD

**Issue by COLAMAroro** [transmission/transmission#1352]
Hello !

I've started using Transmission as my BT Client, with a server serving as a "seedbox"

My setup is as follow:
I have a Windows Server with Transmission installed, with remote gestion
I have a SMB Share on this server pointing to a directory on the server, which I'm hooked on with my laptop
Transmission is set to download in said directory

The issue is that the option "Open Folder" (understandably) doesn't work.
It could be nice if it was possible to "bind" or "alias" a location when using remoting.
I could just say that "my torrents are in `\\server\torrents\`", so I could just access it easily
It could also work with HTTP, which could allow to download in HTTP from your own seedbox (while transmission still seeds)

**Comment by xavery** [comment]
[Transmission Remote GUI](https://github.com/transmission-remote-gui/transgui/) contains the exact functionality you're describing.
