### ISSUE TITLE
Updated icon for macOS Big Sur

### ISSUE THREAD

**Issue by godly-devotion** [transmission/transmission#1360]
macOS Big Sur is updating all the system icons with a rounded-rectangle shape and a front-facing perspective. Some 3rd party developers including Adobe are converting their app icons to match up with these system icons.

Transmission's current app icon will stick out pretty badly on Big Sur. Are there any plans to update the macOS icon?

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/mail-photos-preferences-big-sur.png)

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/preview-xcode-text-edit-big-sur.png)

![](https://avatars3.githubusercontent.com/u/223312?s=200&v=4)

**Comment by sylrs** [comment]
@vagena Just tagging you for this

**Comment by revblaze** [comment]
Now that Big Sur is only a few days away, there are a number of app icon concepts [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements) (4 to be exact).

**Comment by mjbaldwin** [comment]
I also love the one on Dribble the most, but I do want to highlight a problem with it, that with a dock with reduced transparency in light mode, there isn't enough contrast of the light gray against the light gray:

![image](https://user-images.githubusercontent.com/160959/99263700-8eb6a900-27ed-11eb-9802-99cda35da250.png)

I would suggest that adding a dark gray border to it -- similar to the one it currently has -- but with the same width as Terminal and Activity monitor (shown to the right) would be helpful.

**Comment by alexraikos** [comment]
> I also love the one on Dribble the most

Yes! This one's awesome.

**Comment by ifeign** [comment]
There's some great options at macosicons.com this one is my favorite as it stays consistent with the current logo
![image](https://user-images.githubusercontent.com/32289760/100034702-9fe55400-2db1-11eb-8d87-59e37065702d.png)

**Comment by fre123ber** [comment]
I agree that the one on Dribbble by "yw4z" is special. If there isn't enough contrast, just make it darker.

**Comment by hazarek** [comment]
these icons are too detailed for small sizes. I use this icon. I made for macOS Big Sur;
![simge](https://user-images.githubusercontent.com/36481442/106371799-c14a5980-6379-11eb-9986-4e6511ed4d8d.png)

All available icons, 

- Number 1 has a weird perspective. the gear is too high, doesn't look good at small sizes.
- Number 2 doesn't even look like a gear.
- 3 and 4 has wrong gear positions.
- Number 5 has artificial shadows. Air brush strokes stand out,  doesn't look good at small sizes.
- Number 6 my choice. Looks good in small sizes, has good contrast and is not too different from the original.

<img width="1498" alt="transmission_icons" src="https://user-images.githubusercontent.com/36481442/106371821-138b7a80-637a-11eb-8fec-b38dab18ecba.png">

**Comment by fre123ber** [comment]
I think number 5 is also not too different from the original. The original one has a weird perspective too. The artificial shadows add character and are in tune with the new Big Sur icons (look at messages, for example). Maybe it can be simplified a little. For me, number 6 is a bit simple and doesn't share any characteristic with big sur icons, especially the handle is too plain. I think that number 2 is better than 6.

**Comment by spectralsky** [comment]
My votes personally would be for 5 and 1 as they feel the most right to me. I think 5 could be simplified a bit, and I'd prefer the stick poking out some more. I like the border on 1 a lot. Really not a fan of 2, 3, 4 and 6 as they just aren't really recognisable or are oddly rendered.

**Comment by mjbaldwin** [comment]
Agreed on both 5 and 1, if the border from 1 got added to 5. No strong feeling on whether the handle should stick out above the top of the frame or not.

I'm also not sure how much we have to worry about small sizes? I virtually never see app icons in their small sizes -- I see them large in my dock, in clicking on the applications folder menu, in Cmd+Tab, in launchpad... the only time I can think of where someone regularly sees a small icon is if they set their Applications folder in the dock to show applications as a list... in which case you're primarily going by the alphabetized title rather than distinguishing between icons, no? But maybe there's some common scenario I'm forgetting?

**Comment by hazarek** [comment]
> the only time I can think of where someone regularly sees a small icon is if they set their Applications folder in the dock to show applications as a list... in which case you're primarily going by the alphabetized title rather than distinguishing between icons, no? But maybe there's some common scenario I'm forgetting?

Actually ICNS files contain separate image files for each size. The Apple guidelines say that the small icons should be simple. Look carefully at the Safari icon, 7, 8, 9 and 10 are different. Dock icon, Spotlight search, Application folder these are considered small icons. macbook users in particular often use the size of the dock small.

<img width="668" alt="Ekran Resmi 2021-01-31 18 06 07" src="https://user-images.githubusercontent.com/36481442/106388334-0e1c4780-63ef-11eb-85ae-7050188f5d4c.png">


 I also disagree with any of the above comments, all of them are amateur comments.

**Comment by 1lias** [comment]
Let's keep this topic moving forward, it seems like most people prefer options 1 and 5. Objectively looking and comparing option 5 seems to fit the closest to the aesthetic of Big Sur. The concern of smaller icon sizes can be handled with the use of more simplified variations of the same icon (just like it happens in Safari and other macOS icons). 

@mjbaldwin do you have a link to the person who designed the dribbble option?

**Comment by godly-devotion** [comment]
Personally I've been using option 5, and its been great.
![image](https://user-images.githubusercontent.com/1341760/107886066-8c86e800-6ecb-11eb-9db9-40fd76366a63.png)

**Comment by hazarek** [comment]
> Personally I've been using option 5, and its been great.
> ![image](https://user-images.githubusercontent.com/1341760/107886066-8c86e800-6ecb-11eb-9db9-40fd76366a63.png)

unnatural airbrush strokes look very ugly.

**Comment by mjbaldwin** [comment]
> @mjbaldwin do you have a link to the person who designed the dribbble option?

Unfortunately I don't. And their profile page on dribbble doesn't provide any contact info, nor is there a way to message them, and the same for their account on gumroad, and can't find anything on Google either.

So no idea whatsoever, sorry.

I think the icon's great, but I do want to reiterate the importance of a dark gray border around it -- it's very sharp in the screenshot by @godly-devotion but in the screenshot I pasted up above, it blends in too much with a light gray dock.

**Comment by hazarek** [comment]
Can you open the Github Discussion feature? Icons are discussed on the old fashioned forum.transmissionbt.com. Icon files should be shared as open source. everyone should be able to change it. In the end, there should be a vote.

**Comment by hazarek** [comment]
> I'm also not sure how much we have to worry about small sizes? I virtually never see app icons in their small sizes -- I see them large in my dock, in clicking on the applications folder menu, in Cmd+Tab, in launchpad... the only time I can think of where someone regularly sees a small icon is if they set their Applications folder in the dock to show applications as a list... in which case you're primarily going by the alphabetized title rather than distinguishing between icons, no? But maybe there's some common scenario I'm forgetting?

notifications;
<img width="381" alt="Ekran Resmi 2021-02-15 03 54 49" src="https://user-images.githubusercontent.com/36481442/107894787-e0341880-6f41-11eb-9c8a-2fd065dff2e0.png">

**Comment by alexandrosraikos** [comment]
> Personally I've been using option 5, and its been great.
> ![image](https://user-images.githubusercontent.com/1341760/107886066-8c86e800-6ecb-11eb-9db9-40fd76366a63.png)

Me too, it's so polished!

**Comment by hazarek** [comment]
> > Personally I've been using option 5, and its been great.

> 
> Me too, it's so polished!

This repo cannot use it without permission from yw4z. I'm thinking of designing its slightly improved version. (multiple design per resolution and better background) but I need to be sure about the license.
<img width="927" alt="Ekran Resmi 2021-02-15 22 04 20" src="https://user-images.githubusercontent.com/36481442/107984981-3a80b800-6fda-11eb-85a6-283849f09985.png">

**Comment by yw4z** [comment]
hello all, thanks for all comments on my design, send me an email to yw4z@outlook.com if developers interested, i can finish design with last touches ( adding border etc. ) , creating document icon and various icon sizes

**Comment by godly-devotion** [comment]
@yw4z For starters, many here would be interested in using your icon for our local copy of Transmission with the improvements!

**Comment by hazarek** [comment]
@yw4z türksün galiba, simgeyi hangi yazılımla ile yaptıysan onun dosyasını CC lisansı ile paylaşır mısın. herkes değişiklikl yapmakta özgür olsun.

**Comment by yw4z** [comment]
@godly-devotion thanks for your interest, like i said if developers interested with embedding my icon to app, they can contact me from here or with an email

@hazarek  maalesef, işin çorbaya dönüşmemesi için çizim dosyasını paylaşmamayı tercih ederim

**Comment by hazarek** [comment]
@yw4z simgeyi  hangi lisans ile vermeyi düşünüyorsun? sonuçta hakları sende saklı olmayacak ve istersem aynısını tersine müzendislik ile yapıp değiştirebilirim. Transmission özgür ve açık kaynak bir projedir.
