### ISSUE TITLE
the private value field is not correctly displayed

### ISSUE THREAD

**Issue by nanardtetard** [transmission/transmission#1362]
Transmission 3.00
Mac OS 10.15.5

In the general informations of a private torrent, the private value field is displayed on top of the hash value field.
So it is not clearly visible.
See the screenshot below :
<img width="698" alt="Capture d’écran 2020-07-15 à 01 54 51" src="https://user-images.githubusercontent.com/48246249/87487521-2dfc4180-c63e-11ea-9538-724a71258ebf.png">

**Comment by nanardtetard** [comment]
I've found this in transmission/macosx/fr.lproj/Localizable.strings :
`/* Inspector -> private torrent */`
`"Private Torrent, non-tracker peer discovery disabled" = "Torrent privé, utilisation des pairs du traqueur uniquement\n";`

I think the '/n' character is the reason why this field is bad displayed.

**Comment by ckerr** [comment]
Please see https://www.transifex.com/transmissionbt/transmissionbt/ for information on how to contribute to Transmission localizations / translations. Thank you!
