### ISSUE TITLE
Transmission 3.00, Unknown Client Names

### ISSUE THREAD

**Issue by pmarsden** [transmission/transmission#1363]
3.00 does not seem to recognise a couple of clients (peer-ids).

-UW110Q- 
This is uTorrent Web.

-FW6830-
This is FrostWire.

**Comment by pmarsden** [comment]
Another I came across ;

-BI2300-
This is BiglyBT  (2.3.0.0)

**Comment by pmarsden** [comment]
Another I came across today ;

-BL24632
This is BitLord (2.4.6-32)

**Comment by reeyon** [comment]
I have these on my 3.0.0 client, but not sure what is it exactly.

-WW0007-
-UW1145-
-UW113P-

**Comment by pmarsden** [comment]
-UWxxxx- are previously listed above, they are uTorrent Web.

-WW0007- is one I've seen as well, its apparently WebTorrent ( https://webtorrent.io/ ).

Three others I have come across, that I cannot find information on are ;

-WS1000-
-BI2600-
--DE203s

The last one may be some form of Deluge 2.x, but thats purely a guess.
