### ISSUE TITLE
Scroll Bar Issue 

### ISSUE THREAD

**Issue by prinze77** [transmission/transmission#1365]
On mac os Catalina 10.15.6 i cant click on open file location because the vertical scroll bar is in front of the button open file location
<img width="51" alt="Снимок экрана 2020-07-19 в 10 52 13 PM" src="https://user-images.githubusercontent.com/33203521/87883839-d9c4d900-ca12-11ea-8ac4-4964c17abef7.png">
.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #1224, #261, #1.
