### ISSUE TITLE
Why were the proxy settings removed?

### ISSUE THREAD

**Issue by Festeazy** [transmission/transmission#1375]
Why were the proxy settings removed?

**Comment by mikedld** [comment]
See #344, [TRAC-5625](https://trac.transmissionbt.com/ticket/5625), [TRAC-3688](https://trac.transmissionbt.com/ticket/3688).

**Comment by frankli0324** [comment]
all the above discussions suggests that proxy support NOT be removed
I don't understand why did it happen

**Comment by erdoukki** [comment]
So I must leave Transmission, because of missing proxy !

**Comment by TurnOffNOD** [comment]
> See #344, [TRAC-5625](https://trac.transmissionbt.com/ticket/5625), [TRAC-3688](https://trac.transmissionbt.com/ticket/3688).

Since proxy is still support, why does proxy settings removed?
