### ISSUE TITLE
Memory leaks in macOS 10.15.x with 3.0.0

### ISSUE THREAD

**Issue by scolson** [transmission/transmission#1379]
I have two hosts set up for helping seed common linux isos we use on our proxmox hosts (I know, I know, but really). On one of these seedboxes, it was updated to 3.0.0. The other was left on 2.9.4. Both are running the latest Catalina (10.15.x).

The 3.x seedbox is running in to an issue where the transmission process, which normally runs 24/7, starts to ballon in memory footprint after about 14-18 hours, give or take. Normally it only consumes around 60-70M. After most of a day, it is up to 6-8 GB. At about 24 hours, it hits 10-12 GB. If left alone, it will keep leaking and will easily hit 40+GB on a machine that just doesn't have that much RAM available. We have taken to restarting the process every 24 hours just to restart the "counter."

The 2.9.4 system, which is identical in software and configuration otherwise, never needs to be manually restarted.

**Comment by fortinmike** [comment]
This happens on my Mac too:

- Transmission 3.00 (f4489c982e)
- macOS Catalina 10.15.6 (19G2021)

**Comment by ckerr** [comment]
Please try a nightly build and report back if the problem persists? There's been a lot of work on the backend since 3.00.

**Comment by Coeur** [comment]
I do not have any memory leak on master branch.
I recommend closing this issue when a new release is made. @ckerr can you publish some 3.01 version to mark this as resolved?

**Comment by Coeur** [comment]
4.0 beta is available. Closing.
