### ISSUE TITLE
Tray icon doesn't toggle window

### ISSUE THREAD

**Issue by JpegXguy** [transmission/transmission#1387]
Arch Linux x86_64, Transmission 3.00

In 2.94, it used to be that clicking on the tray icon would toggle showing the transmission window. A right click would give you the menu with the checkbox for alternate speed limits and the like.

Now on 3.00 both left and right clicking the tray icon show the menu, and you have to tick a checkbox in the menu to show the transmission window...

I think that's unintuitive and just unnecessary

**Comment by k3lt** [comment]
Same thing happens on Windows 10 unfortunately.

**Comment by areographe** [comment]
Agreed, I have this issue on Manjaro Cinnamon and Transmission 3.00, GTK client. I feel like it doesn't make sense to have left-click and right-click perform the exact same function.

**Comment by JpegXguy** [comment]
So, After some time of research, bisects that were'nt needed e.t.c.
The reason for this is actually outside transmission-gtk itself.
for my distro (Arch) it has to do with [this bug report](https://bugs.archlinux.org/task/67346), leading to [this change](https://github.com/archlinux/svntogit-packages/commit/44f7fa91d6c5a6aedb78fa50acc59ecd62e71bae#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) whereby transmission is built with `libappindicator-gtk3`. According to the bug report, this is for better support under Wayland.

That said, building with this "new?" API causes this unwanted behaviour. For now, using 3.00-1 instead of 3.00-2 in Arch, solves this for me. But for the future, what to do?

**Comment by JpegXguy** [comment]
UPDATE: I hadn't noticed it before when looking at the file, but I believe the difference in behaviour stems from the divergent code paths at the end of the file: https://github.com/transmission/transmission/blob/9c5e6f7ea61ad4e7708756b7a9b7c299936117f4/gtk/tr-icon.c#L157-L178

When not using libappindicator, this call happens `g_signal_connect(icon, "activate", G_CALLBACK(activated), NULL);`, which to my mind, binds the click to the toggle of the window, through the function `activate()`. The question is: Is there a way to get this using the LibAppindicator API or are we limited to showing menus?

**Comment by ckerr** [comment]
The current behavior is consistent with every other icon in my tray. As evidenced by the issue @JpegXguy linked, this is the behavior that the desktop maintainers are going for, so it makes sense for Transmission to play nicely with the desktop.

**Comment by JpegXguy** [comment]
It doesn't seem weird to you, having to click twice in order to bring up the transmission window? (the second time is harder because you have to find the target checkbox)

**Comment by mnalis** [comment]
> The current behavior is consistent with every other icon in my tray. 

This is _exactly the opposite of my tray_, where ***none*** of the apps display the menu on left-click, yet all of them do display menu on right-click. (for reference, it is currently icewm clock, cpu/mem/swap monitor, network interface monitor, pidgin, telegram, vlc, and transmission-gtk (built without libayatana-appindicator3-dev, as referenced in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901081)

Anyway, I've never even seen the app (except transmission-gtk) which shows same menu on right and left click on the tray. Do you?

> this is the behavior that the desktop maintainers are going for, 

Which "desktop maintainers" do you mean exactly here? It only seems to be appindicator stance; if you read all the links @JpegXguy linked, you'd see that this stance is _far from consensus_...

> so it makes sense for Transmission to play nicely with the desktop.

Well, Transmission used to play nicely with desktop, now it no longer does (unless manually worked around as shown in that Debian bug). All of the bigger apps I use that have tray icon (pidgin, telegram, vlc - i.e. not small applets) work the same way as transmission used to - menu on right click, show/hide main window on left click.

Also, see https://github.com/transmission/transmission/issues/403
