### ISSUE TITLE
Request New Feature: Block an cilent/IP on the fly (As Dynamic Leecher Protection  is not powerful)

### ISSUE THREAD

**Issue by songsammy** [transmission/transmission#1397]
In our country, only Dynamic Leecher Protection is not enough. I mean, some user agent download at 1 mbps and upload at 1 kbps.  You can check wikipedia for more example.
So here's the feature I request:
1. Block Certain IP for X minutes (Maybe with a * in the address)
2. Block a useragent via regexp (For example , ^x blocks UA "xyz")
3. Contribute to a database, as a public service.

**Comment by ckerr** [comment]
You can already add IP addresses and ranges to a local blocklist, and Transmission will honor that.

Transmission is **absolutely** not getting into the business of contributing to IP databases. Not only does the project not have resources to do that work on an ongoing basis, but maintaining an IP address blocklist would come with legal risks for a BitTorrent application.

So for both practical and legal reasons, dynamic leecher blocklists will need to be maintained by someone else.
