### ISSUE TITLE
Add user trackers in preferences (that will be added automatically for each new torrent download)

### ISSUE THREAD

**Issue by startpagina808** [transmission/transmission#1399]
Like qBit torrent, there should be an option to add a default torrent tracker list that will be added (by default) for each new torrent.

**Comment by pataquets** [comment]
Adding my +1, plus a suggestion added to a list, maybe a "tracker list URL" which would be fetched and later added always might come handy. There are several working tracker lists downloadable around.
In the meantime, check out https://github.com/AndrewMarchukov/tracker-add. It might come handy.

**Comment by pataquets** [comment]
Linking PR #299, which (partly) addresses this.

**Comment by ckerr** [comment]
Fixed by #2668
