### ISSUE TITLE
:-1: error: error: ../libtransmission/libtransmission.a: No such file or directory

### ISSUE THREAD

**Issue by thiagomota456** [transmission/transmission#1401]
I tryed build the qt project and recive t6he message ": - 1: error: error: ../libtransmission/libtransmission.a: No such file or directory".
I can't find the file libtransmission too.

**Comment by mikedld** [comment]
Building Qt client with qmake requires you to configure/build the top-level autotools project first. Note that this is no longer the preferred way and you should switch to CMake ASAP.

**Comment by thiagomota456** [comment]
How do I do this? Do you have documentation that I can consult? (I did not find)

**Comment by thiagomota456** [comment]
How do I do this? Do you have documentation that I can consult? (I did not find)
