### ISSUE TITLE
Download Size /  Total Size / Remaining Size

### ISSUE THREAD

**Issue by ralphee** [transmission/transmission#1403]
on the web interface one can see the size of the torrent ie XXGB of XXGB. Can one have total size of torrent and or remaining size of torrent being download in the terminal as headers. Currently the headers which I have in the terminal are:

ID   Done       Have  ETA           Up    Down  Ratio  Status       Name
 
would like to have 

ID   Done       Total   Have      Remaining         ETA           Up    Down  Ratio  Status       Name

**Comment by ckerr** [comment]
I'm not sure that I  understand this feature request correctly. Could you try rephrasing it to help me understand?

**Comment by ralphee** [comment]
![tsm_gui](https://user-images.githubusercontent.com/8269794/150637287-cb2f549a-1731-42ae-a8bf-245113c96660.jpg)

With the browser  I can see the "total size" of torrent file and "actual download size" of torrent ( ie 6.54GB of 25.1GB )

![2022-01-22_12-53](https://user-images.githubusercontent.com/8269794/150637476-ae7c6219-4acd-4ca3-9154-88a558ded8f8.jpg)

In the terminal I can only see the % of completed file and the actual downloaded size (Not the total size of the file)

Hope its a more clear now

**Comment by ckerr** [comment]
when you say "in the terminal" are you talking about transmission-remote?

**Comment by ralphee** [comment]
> when you say "in the terminal" are you talking about transmission-remote?

( [transmission-cli](https://wiki.archlinux.org/title/Transmission#Installation) albeit I just noticed transmission-cli is now deprecated

**Comment by ckerr** [comment]
closing issue as per previous comment
