### ISSUE TITLE
Daemon run as root and drop privileges

### ISSUE THREAD

**Issue by johnlane** [transmission/transmission#1413]
I don't think the transmission daemon can do this but it would be good to be able to start it as root and have it drop privileges to a given uid (a "transmission" user) after binding to the port. This would allow binding to port 80 and make it easier to start directly from a busybox init in an embedded / tiny container scenario.

**Comment by mikedld** [comment]
Not seeing any reason to bind on 80, or any issue with binding on non-80. Transmission is not a HTTP server, this limitation is not that critical.

**Comment by johnlane** [comment]
bit quick on the close-down there!

It would be nice to be able to have (non-tech) users type "http://transmission-server" into their browser rather than "http://transmission-server:9091".

Forgetting the port 80 thing though, starting as root and dropping privileges would make it easier to start where there isn't much of an init environment. That's the main point of this question.
