### ISSUE TITLE
Add Configurable brute force options

### ISSUE THREAD

**Issue by Chrool** [transmission/transmission#1415]
As of version 3 a brute force feature was added to transmission. https://github.com/transmission/transmission/issues/365
PR: https://github.com/transmission/transmission/pull/371

If 100 consecutive failed login attempts are made then the frontend and api are locked out until a restart.  I would like for both the brute force feature to be configurable (enabled true/false) and the amount of login attempts to be set by configuration too, rather than and arbitrary 100.

**Comment by ckerr** [comment]
This is probably too niche an option to be configurable in the GUI, but it might make sense in `settings.json`

**Comment by Chrool** [comment]
https://github.com/transmission/transmission/pull/1447
Not a C programmer so this is more of a monkey see, monkey do.

**Comment by antivirtel** [comment]
Since I've updated to v3.0 I regularly get the inaccessible issue on the daemon, but since it's not logging what are the incorrect requests, I don't know where does it come from. I don't have the RPC port exposed to the Internet, and all my clients have the correct password, but it still gets inaccessible after a few minutes. Can also logging added before this PR is merged, so I don't need to disable it completely?

**Comment by stlaurentc** [comment]
> Since I've updated to v3.0 I regularly get the inaccessible issue on the daemon, but since it's not logging what are the incorrect requests, I don't know where does it come from. I don't have the RPC port exposed to the Internet, and all my clients have the correct password, but it still gets inaccessible after a few minutes. Can also logging added before this PR is merged, so I don't need to disable it completely?

I have the exact same problem. Can't figure out where these requests come from...

**Comment by Chrool** [comment]
> > Since I've updated to v3.0 I regularly get the inaccessible issue on the daemon, but since it's not logging what are the incorrect requests, I don't know where does it come from. I don't have the RPC port exposed to the Internet, and all my clients have the correct password, but it still gets inaccessible after a few minutes. Can also logging added before this PR is merged, so I don't need to disable it completely?
> 
> I have the exact same problem. Can't figure out where these requests come from...

lol this is the exact reason that i raised this request. Im using linuxserver docker image on ubuntu server 18, am constantly getting locked out. Looks like adding the ip address of the host that is trying to login to the logs should be easy enough. Not sure how much that'll help.

**Comment by antivirtel** [comment]
It didn't help at all, I've tried to add any possible combination, no luck. Disabling the whitelists didn't make a difference. This anti-bruteforce should be configurable

**Comment by ckerr** [comment]
Fixed by #1447

**Comment by PavelNiedoba** [comment]
Please remove this completely. It does not make anything safer. Nobody asked for this. It's pain for years.

**Comment by ckerr** [comment]
> Please remove this completely. It does not make anything safer. Nobody asked for this.

Quite obviously someone did, since they wrote a patch for it in #365.
