### ISSUE TITLE
NULL pointer checking problem

### ISSUE THREAD

**Issue by viennadd** [transmission/transmission#142]
In function [tr_fdFileCheckout](https://github.com/transmission/transmission/blob/02e6f1cd33a1ad75fbced1be8240817a466dda94/libtransmission/fdlimit.c#L468),

```cpp

// if NULL returned from function getfileset
  struct tr_fileset * set = get_fileset (session);       

// there is null checking inside fileset_lookup for variable set, if it is null, then null will return to variable o.
  struct tr_cached_file * o = fileset_lookup (set, torrent_id, i);    

// o == NULL, will take the second block
  if (o && writable && !o->is_writable)                     
    cached_file_close (o); /* close it so we can reopen in rw mode */
  else if (!o)
// <== there is no null checking for variable set inside function fileset_get_empty_slot
    o = fileset_get_empty_slot (set);                    
```
I think a similar null check should be added into [fileset_get_empty_slot](https://github.com/transmission/transmission/blob/02e6f1cd33a1ad75fbced1be8240817a466dda94/libtransmission/fdlimit.c#L321) too.

shortcuts:
[fileset_lookup](https://github.com/transmission/transmission/blob/02e6f1cd33a1ad75fbced1be8240817a466dda94/libtransmission/fdlimit.c#L308)
```cpp
static struct tr_cached_file *
fileset_lookup (struct tr_fileset * set, int torrent_id, tr_file_index_t i)
{
  struct tr_cached_file * o;

  if (set != NULL)                 // with null check
    for (o=set->begin; o!=set->end; ++o)
      if ((torrent_id == o->torrent_id) && (i == o->file_index) && cached_file_is_open (o))
        return o;

  return NULL;
}
```

[fileset_get_empty_slot](https://github.com/transmission/transmission/blob/02e6f1cd33a1ad75fbced1be8240817a466dda94/libtransmission/fdlimit.c#L321)
```cpp
static struct tr_cached_file *
fileset_get_empty_slot (struct tr_fileset * set)
{
  struct tr_cached_file * cull = NULL;

  if (set->begin != NULL)         // without null check for variable set
    {
      struct tr_cached_file * o;

      /* try to find an unused slot */
      for (o=set->begin; o!=set->end; ++o)
        if (!cached_file_is_open (o))
```

**Comment by viennadd** [comment]
anyone?

**Comment by buhtz** [comment]
I suggest you should create a PR for this.

**Comment by viennadd** [comment]
@buhtz seems it is a duplicated issue with #202 , I must had forgotten I was already opened this issue.
and seems it is a known/intentional implementation according to the reply of @mikedld at #202 , I should probably close this issue first. Thank you for your concern.
