### ISSUE TITLE
Error: 'Unable to save resume file. File exists'

### ISSUE THREAD

**Issue by ahmar20** [transmission/transmission#1422]
I am experiencing an error where the resume file of any torrent does not save after saving it the first time. I can delete the resume file manually and then transmission saves the file again successfully but if the file is there already it will not save it in any way and this impacts on the pause and resume because in case of restarting the router or restarting transmission, transmission thinks it has not downloaded the torrent since the last save of resume file, which was either at the start or when I manually deleted the file.

I have also created an issue [here](https://github.com/openwrt/packages/issues/13243) because I am using transmission on OpenWrt and I think the issue could be related to saving the file through `file-posix.c` or `variant.c` but this is just a wild guess. :)

Please take a look. Thanks

**Comment by legendtang** [comment]
same here. the permission is correct

**Comment by ahmar20** [comment]
I am able to run v2.94 on latest OpenWrt by editing the MakeFile. The only needed changes are, to replace the version with 2.94 and edit the PKG_HASH to `35442cc849f91f8df982c3d0d479d650c6ca19310a994eccdaa79a4af3916b7d`. Then you need to remove the `web_seeding` patch from patches folder and you are done.

**Comment by ckerr** [comment]
Is this still happening in Transmission 4?

**Comment by ckerr** [comment]
Closing due to lack of response and lack of actionable info.

If this is still happening for anyone in Transmission 4 please open a new issue with updated info. Thank you! :bowing_man:
