### ISSUE TITLE
Issue when starting a new torrent

### ISSUE THREAD

**Issue by yakiaa** [transmission/transmission#1424]
Hi. When I open a .torrent file with transmission, instead of showing me the torrent I want to download, it shows me all of my previous torrent files, check out [the video](https://streamable.com/1q4su8). I am using build 2.94.

**Comment by yakiaa** [comment]
UPDATE : Same issue occurs in build 3.00

**Comment by ckerr** [comment]
Closing this issue due to lack of actionable information. If this is still occurring in the [nightly builds](https://transmissionbt.com/download), please file a new bug report with updated information. Thank you!
