### ISSUE TITLE
Error:Permission denied [Path location]

### ISSUE THREAD

**Issue by TinyRick32** [transmission/transmission#1426]
Hello, I am new to linux and transmission

I'm running a headless install on a raspberry pi 4
everything was running fine a few months ago. today i tried adding a magnet link to the web interface and received an error
Error:Permission Denied [Path location]

i am completely lost as i have tried giving debian-transmission rw and multiple other things. 

i am also new to github so i am not sure what command lines to post or how to post them.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
