### ISSUE TITLE
Update file icon if rename changes file type

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#143]
If a renamed file in a torrent changes the file type, the icon in the transmission UI is not updated to the new type. The expected behavior is for the application to use the icon of the current file type.

macOS 10.12.2, Transmission 2.92.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. Even more so if existing issue (#37) was created by youself...

**Comment by CyberSkull** [comment]
Sorry! 😖
