### ISSUE TITLE
Open Folder doesn't do anything on Haiku

### ISSUE THREAD

**Issue by extrowerk** [transmission/transmission#1434]
Transmission 3 built with Qt GUI on Haiku, and while it is works very well, the "Open folder" item in the torrent right click menu doesn't do anything. I assume, this platform case (__HAIKU__) is not handled yet in the respective function, probably some adjustment would be required, but i can't seem to find the location, where this handled. Is it handled by Transmission or Qt? Can somebody give me some hint?
Thank you!

**Comment by mikedld** [comment]
https://github.com/transmission/transmission/blob/b3c3168f16a54bc0bff4b09f0f645e8664829e9e/qt/MainWindow.cc#L649-L659

**Comment by extrowerk** [comment]
Thanks, i see here case for WIN and MAC. Isn't it falls back somewhere for Linux or ist that case also unhandled?

I think i can implement something along the mac and win examples, we don't need anything else just 'open $PATH' to spawn a Tracker window with the provided path, so it should be easy.

**Comment by mikedld** [comment]
Special cases for Windows and Mac are there to support opening a folder for single-file torrents and focusing a specific file. Non-single-file torrents and systems other than Windows and Mac are using `QDesktopServices::openUrl()` to open a folder in the most suitable system application and thus support for this is provided by Qt itself, not us.

**Comment by extrowerk** [comment]
> this is provided by Qt itself, not us.

Ok, that's why i haven't found anything. Will notify the Haiku Qt porter team. Thanks, we can close this issue.
