### ISSUE TITLE
transmission-create creates broken torrents with empty files

### ISSUE THREAD

**Issue by fauno** [transmission/transmission#1453]
while seeding folders with torrents created with transmission-create, transmission-gtk was expecting to download some pieces (torrent seed started at 96%). we later tried with deluge to confirm the torrent was broken: creating a new torrent from the same folder the seed started at 100% for both clients. then we noticed the folder contained some empty files and apparently they're making transmission-create generate broken torrents.

```bash
>_ touch empty_file
>_ transmission-create empty_file
WARNING: no trackers specified
Creating torrent "empty_file.torrent" .... error reading "": No such file or directory
>_ mkdir empty_dir
>_ touch empty_dir/empty_file
>_ transmission-create empty_dir
WARNING: no trackers specified
Creating torrent "empty_dir.torrent" .... error reading "": No such file or directory
>_ echo something > empty_dir/something
>_ transmission-create empty_dir
WARNING: no trackers specified
Creating torrent "empty_dir.torrent" .... done!
```

**Comment by ckerr** [comment]
The choice to skip 0-byte files when creating new torrents was added because of https://trac.transmissionbt.com/ticket/1267 but this seems to be an obsolete choice. Every other torrent client I tested _did_ include 0-byte files when I created a .torrent with them.
