### ISSUE TITLE
Lost connexion when i change torrent localisation

### ISSUE THREAD

**Issue by DidierMasse** [transmission/transmission#1462]
Hello ! 

i'm on raspbian os ( debian buster ) and i'm using Transmission 2.94

I've some issues with transmission. When i want change torrent localisation i loose connexion with server...

Some idéa for fix it ? 

Thanks

**Comment by xavery** [comment]
This is a known issue. Network traffic - including the RPC - is not processed when moving large amounts of data around.

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/2462
