### ISSUE TITLE
[FEATUE] Daemon listening on unix sockets only.

### ISSUE THREAD

**Issue by luqasz** [transmission/transmission#1470]
Hi

Use case:
Transmission daemon used only with RPC access e.g. on a server with nginx reverse proxy. Using unix sockets will enable server admins to restrict access for a group of users. Listening only on unix sockets will block users which don't have rw permission on unix socket.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #441.

**Comment by luqasz** [comment]
Ok. Will do next time. thx
