### ISSUE TITLE
Pause and resume "Checking existing data" interrupts process

### ISSUE THREAD

**Issue by magamig** [transmission/transmission#1479]
If you remove and add a torrent to Transmission it will start to check the existing data in order to restart from the point it had previously stopped. However, if you pause while it is "Checking existing data", when you resume the process, it will start the download from the point it was paused instead of finishing the check for existing data.

**System:** mac OS Catalina 10.15.7 & Transmission 3.00

**Comment by pradorocchi** [comment]
How was the behavior before? I mean, on other MacOS/Catalina versions, or older Transmission versions?

I am interested on this situation, but I don't have any information ( about IF was it different ) on other versions, neither I don't know if you have the answer for my question, but it could help me to track the error, or at least know it was always there un-noticed.

Thanks in advance

**Comment by magamig** [comment]
I have no clue what happened in the previous versions.

**Comment by ckerr** [comment]
It's intentional that "Verify local data" always starts from scratch.

**Comment by magamig** [comment]
That was not the issue, but the fact that it would lose "download progress". Anyway, I've just checked and this is not an issue in the most recent version, so it can be considered as fixed.

**Comment by ckerr** [comment]
Thanks for the clarification, and also for testing a recent version! :green_heart:
