### ISSUE TITLE
Remote UI showing two double entries on v 3.0 macOS

### ISSUE THREAD

**Issue by kimfucious** [transmission/transmission#1486]
While running a single torrent in the Transmission app, two entries appear in the remote / web UI.

The app is running macOS Catalina, and the remote machine is running Windows 10 with Chrome (Version 86.0.4240.75) as the browser.
![image](https://user-images.githubusercontent.com/26792769/97427562-51c26980-1947-11eb-9e08-280f1a46eb10.png)
![image](https://user-images.githubusercontent.com/26792769/97427630-6acb1a80-1947-11eb-83d3-7a28b34335f7.png)

**Comment by desdic** [comment]
Did you ever find the problem ? I have the same but on Linux after a upgrade of Debian

**Comment by kimfucious** [comment]
Hi @desdic,

I never looked much further into this.

As I mainly let stuff run in the background, I haven't really paid much attention to it.

I think the key thing is that viewing status on the actual machine where the download is happening shows a single download, so the dupe in the remote must be some sort of bug/anomoly rather than a double download.

**Comment by ckerr** [comment]
The web client has been rewritten in `main`. If this problem persists in the nightly builds, please lmk

**Comment by ckerr** [comment]
Closing due to lack of actionable info. If this is still happening in Transmission 4 please open a new bug. Thanks!
