### ISSUE TITLE
Different application data for different ways the app is opened

### ISSUE THREAD

**Issue by echaskaris** [transmission/transmission#1488]
1. Start Tor browser (No i dont download the files of the torrents through tor)
2. download a torrent file
3. select "open with transmission"
4. The app that opens through tor browser has different data than the one that opens when you open it through the app menu, I cant see torrents i downloaded with app opened through the app menu when app is opened through tor and vice versa

Ubuntu 20.04
Transmission 2.94 (d8e60ee44f)

**Comment by echaskaris** [comment]
For example it says in the log "Saved /home/user/Desktop/tor browser folder/.config/transmission/settings.json"

**Comment by varesa** [comment]
It seems that the Tor browser might be modifying the `$HOME` or other environment variables, which Transmission end up inheriting. 

Some mentions of this "modified HOME": https://blog.torproject.org/comment/284420#comment-284420

**Comment by ckerr** [comment]
This is not solvable by Transmission.

Transmission (and other well-behaved Linux apps) follows [the XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which uses paths whose default values derive from `$HOME`.

You could set these environment variables yourself before launching Transmission if you want to force another directory, but Transmission is correctly using the environment it inherits, even if that environment is altered by Tor.
