### ISSUE TITLE
Transmission doesn't respect autostart "Hide" flag

### ISSUE THREAD

**Issue by generator85** [transmission/transmission#149]
I've set up Transmission to autostart in OSX (System Preferences -> Users & Groups), and checked the "Hide" flag to prevent the app window from showing up. But Transmission ignores this flag and shows the UI anyway when starting after a reboot.

I've got OSX El Capitan installed, but this also occurs on the latest OSX version (sierra).

See forum post for more info:
https://forum.transmissionbt.com/viewtopic.php?f=4&t=18305

**Comment by Coeur** [comment]
For context, we're talking about this option:
https://support.apple.com/guide/mac-help/mtusr003/mac

**Comment by Coeur** [comment]
After many restart attempts, it seems to work completely as expected on macOS Monterey:
- if app was opened before restarting the session, and you set to "reopen all windows at session startup", then the app state will be identical as before.
- if app was closed or you don't set "reopen all windows at session startup", then the app state will be minimised.

If there is a scenario that isn't behaving as expected, please reopen an issue and clarify:
a. How was the state of the app before (closed, opened, minimised)
b. Did you check "reopen all windows at session startup" or not.
c. Did you restart session, restart computer or crash computer.
d. Which OS version.
