### ISSUE TITLE
error "request lost files" is not clear and requests deleted ,although they "UnСheckMark" from the downloads menu downloads

### ISSUE THREAD

**Issue by GrayRats** [transmission/transmission#1494]
when you delete files and _UnСheckMark_ from the download's file's , still the error "**request for lost files**" and shakes the new when you change/add files in the menu downloads.
will have to remove the torrent and add (for example, via magnetic link) torrent,instruct on new download.

**Comment by GreyRats** [comment]
- [ ]

**Comment by ckerr** [comment]
I don't understand what this bug report is saying. I think there may be a translation issue. Could you please restate the bug so that I can try to understand it?

**Comment by ckerr** [comment]
Closing due to lack of response.
