### ISSUE TITLE
transmission compile  failed in Lede

### ISSUE THREAD

**Issue by jack338c** [transmission/transmission#150]
Sir,Can you help me ?

checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating transmission-gtk.spec
config.status: creating cli/Makefile
config.status: creating daemon/Makefile
config.status: creating extras/Makefile
config.status: creating libtransmission/Makefile
config.status: creating utils/Makefile
config.status: creating third-party/Makefile
config.status: creating third-party/dht/Makefile
config.status: creating third-party/libb64/Makefile
config.status: creating third-party/libutp/Makefile
config.status: creating third-party/libnatpmp/Makefile
config.status: creating third-party/miniupnpc/Makefile
config.status: creating macosx/Makefile
config.status: creating gtk/Makefile
config.status: creating gtk/icons/Makefile
config.status: creating qt/config.pri
config.status: creating web/Makefile
config.status: creating web/images/Makefile
config.status: creating web/style/Makefile
config.status: creating web/style/jqueryui/Makefile
config.status: creating web/style/jqueryui/images/Makefile
config.status: creating web/style/transmission/Makefile
config.status: creating web/style/transmission/images/Makefile
config.status: creating web/style/transmission/images/buttons/Makefile
config.status: creating web/javascript/Makefile
config.status: creating web/javascript/jquery/Makefile
config.status: error: cannot find input file: `po/Makefile.in.in'
Makefile:198: recipe for target '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/transmission-openssl/transmission-2.92+git/.configured_yyyyyyyy' failed
make[3]: *** [/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/transmission-openssl/transmission-2.92+git/.configured_yyyyyyyy] Error 1
make[3]: Leaving directory '/home/jack/source/feeds/packages/net/transmission'
package/Makefile:133: recipe for target 'package/feeds/packages/transmission/compile' failed
make[2]: *** [package/feeds/packages/transmission/compile] Error 2
make[2]: Leaving directory '/home/jack/source'
package/Makefile:129: recipe for target '/home/jack/source/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/jack/source/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jack/source'
/home/jack/source/include/toplevel.mk:197: recipe for target 'world' failed

**Comment by mikedld** [comment]
Since you seem to be building for an embedded device, pass `--disable-nls` to `configure` as you most probably don't need NLS support anyway.

**Comment by jack338c** [comment]
ok,thank you mike !
Remark: about 1 month agao,I could build  it successfully in lede

**Comment by jack338c** [comment]
Hi Mike,I do search on google for how to pass  pass --disable-nls,but I can not make it
Could you tell me which file I need edit in my lede folder. I did not find it in rules.mk and makefile in transmission folder of my lede folder

**Comment by mikedld** [comment]
Hmm, I fiddled with it a bit and it looks like the error is there even with `--disable-nls`. What you are missing is the `glib-gettextize` tool which comes with `glib` package (at least in my distribution). Maybe you had it installed before but removed since?..

**Comment by jack338c** [comment]
I'm not sure,but I will try it as your said,thanks

On Jan 20, 2017 6:09 PM, "Mike Gelfand" <notifications@github.com> wrote:

Hmm, I fiddled with it a bit and it looks like the error is there even with
--disable-nls. What you are missing is the glib-gettextize tool which comes
with glib package (at least in my distribution). Maybe you had it installed
before but removed since?..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/transmission/transmission/issues/150#issuecomment-274032686>,
or mute the thread

**Comment by jack338c** [comment]
It works !Mike,you are awesome ! it's a beautiful day to me !
