### ISSUE TITLE
Allow adding a webseed after torrent has started

### ISSUE THREAD

**Issue by riking** [transmission/transmission#1500]
When a file is available both over a slow web download and a torrent, frequently the torrent file authors forget to add the web download location as a webseed.

If all fully-downloaded peers go away, the webseed is necessary to restore full content to the live swarm. This may be a belated realization.

Support adding a webseed URL per file after a torrent has already started.

**Comment by ckerr** [comment]
This is a subset of https://github.com/transmission/transmission/issues/65, so I'm closing this one as a duplicate.
