### ISSUE TITLE
Wiki link to RPC specification is broken

### ISSUE THREAD

**Issue by robgmills** [transmission/transmission#151]
[The link to the RPC specification](https://github.com/transmission/transmission/wiki/rpc) on the [main page of the wiki](https://github.com/transmission/transmission/wiki) is broken.  It should resolve to [the `rpc-spec.txt` file](https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt) in the `extras` directory.

I'd love to fix this, and other wiki issues, but I'm not sure how to edit the wiki as an outside contributor.

**Comment by Sylvain303** [comment]
Also related to: https://github.com/transmission/transmission/issues/435
