### ISSUE TITLE
Unable to save resume file: No file descriptors available Transmission 3.00 (bb6b5a062e)

### ISSUE THREAD

**Issue by Sloth-on-meth** [transmission/transmission#1513]
Hi there.i keep getting this error when having many torrents open. how do i fix

**Comment by Sloth-on-meth** [comment]
OS: UBUNTU
transmission running in docker

**Comment by za3k** [comment]
This means you are trying to open more files at once than Linux allows. It's not a problem with transmissions per se.
Docker (by default) uses the host system limits, so unless you changed options, this is a problem with your Linux setup, and docker is not involved either.

To learn more about limits on open files and how to increase them, use Google. 'ulimits' is the name of the OS limit system.
