### ISSUE TITLE
Transmission Qt 3.00 (bb6b5a062e) does not show content type

### ISSUE THREAD

**Issue by ViBE-HU** [transmission/transmission#1517]
Transmission only show icons only if the selected torrent is a file and not a subfolder. Folder icons appears if I open up the selected torrent's properties.

![tm](https://user-images.githubusercontent.com/640109/98943110-4b0f2700-24ef-11eb-8af0-24c0f9c300ac.jpg)

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #1289.
