### ISSUE TITLE
Feature request: allow disabling TCP in favour of UDP/uTP (as much as possible)

### ISSUE THREAD

**Issue by pataquets** [transmission/transmission#1519]
I'm using Transmission as my torrent service and it works awesomely. I also try to leave it always up and running and with unlimited seed ratio to take advantage of otherwise idle bandwidth.
However, I experience frequent slowdowns and some freezes with my ISP home router. I've troubleshooted it and the culprit seems to be the router not able to cope with that many TCP connections. It might not be always the case, but my guess is that most home users are stuck with their ISP-provided router, hence "cheapness" is not an easy thing to workaround for most users (ISPs only guarantee QoS with their equipment).
Also, when I'm actively using my PC, network performance decreases if Transmission is sharing.
I'm aware that I can tune max connections and such, but I think that having a `--no-tcp` switch or similar would give another tool for maximizing usage, especially if fully using [uTP](https://www.bittorrent.org/beps/bep_0029.html). 

Advantages to implement "uTP/UDP only" as much as possible:
* Nowadays, every major Torrent software/library more or less provides this, since UDP/uTP has numerous advantages in network performance 'per se', such as automatic congestion control and others (see corresponding [BEP-19](https://www.bittorrent.org/beps/bep_0029.html) for details). The BEP rationale even acknowledges the ISP router's shortcomings, and most users have those, as opposed to a select few having high-end routing hardware.
* Less skilled users would not be able to easily apply the "lower your connections" solution and will have to stop sharing as soon as they get their files. Availability suffers badly, since I guess this will be the most common scenario.
* Reducing number of connections requires some configuration and testing cycles, which might be time consuming. Not that difficult, but annoying, except if the above is also true.
* Lowering connections too much would unnecessarily decrease network performance and sharing again, which would impact on ratios. It might end up being a waste of otherwise idle bandwidth and would allow fully utilize connection without getting in the way.

Adding such a possibility would avoid users having to make compromises and benefit sharing. True story: happened recently to me while wanting to contribute excess unused bandwidth to recent Debian Bullseye torrents. I had to configure sharing to be disabled while actively using my PC and resume while not. Even using scheduling, it requires some effort. In my case, I would like an 'always on, set-it-and-forget-it' operation.

It would be great to run Transmission "24/7, always sharing" with it using all the excess/idle available bandwidth without it being noticed, network-wise.

**Comment by Pentaphon** [comment]
Just lower the number of connections. Your router's shortcomings are not the issue of the client. Disabling TCP just reduces connection quality. Only uTP should be disabled since it slows down torrent speeds.

**Comment by ckerr** [comment]
My gut feeling is that this is too esoteric for a UI preferences feature, e.g. if we were to add this as a settings option, most people wouldn't understand what to choose.

I can't speak for any specific PR until I read the code, but if someone wanted to make a PR to prefer initiating uTP connections and only resorted to TCP as a fallback, I'm fine with that idea in principle

**Comment by Pentaphon** [comment]
>if someone wanted to make a PR to prefer initiating uTP connections and only resorted to TCP as a fallback, I'm fine with that idea in principle

We can do without that. No other client does this. The option is typically just the ability to disable uTP because some people don't like how it slows down their torrent speeds and that's really enough for everybody. The OP is just misunderstanding how connections can overwhelm a low-spec router and he needs to just lower his number of connections until his specific router stops being overwhelmed but I suspect the OP is one of those people that stubbornly doesn't want to lower his number of connections because that would slow down his speeds on public torrents. 

The extra coding work just isn't worth what the settings can already alleviate for the user.

**Comment by ckerr** [comment]
Closing issue based on @Pentaphon's comment
