### ISSUE TITLE
Purely advisory name results in invalid/corrupt .torrent 

### ISSUE THREAD

**Issue by ZinnDesLebens** [transmission/transmission#152]
In the single-file mode the name of the file is checked with the function [path_component_is_suspicious](https://github.com/transmission/transmission/blob/master/libtransmission/metainfo.c#L71) in [parseFiles](https://github.com/transmission/transmission/blob/master/libtransmission/metainfo.c#L135). If the name is suspicious the result is an error message: "Error: invalid or corrupt torrent file". According to the [BitTorrent specification](http://www.bittorrent.org/beps/bep_0003.html) the name is "purely advisory". Although the specification does not limit the name in any way, the checks are sensible, but they should not result in the rejection of a valid torrent
Edit: The bug exists at least until commit [4160743](https://github.com/transmission/transmission/commit/4160743738bbfe4c4ed9087dbef6acac8365034e)

**Comment by lps-rocks** [comment]
This is still a stupid problem. Transmission won't load torrent files without the 'files' dictionary even though its purely optional.

**Comment by mrchief** [comment]
I'm seeing this error on some of the torrents and every other client is able to load them without issues. Not sure if it's the same root cause.

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/pull/2695 fixes the issue in the original description, that Transmission won't parse a .torrent file that has a "suspicious" (non-portable) name.

The [followup comment](https://github.com/transmission/transmission/issues/152#issuecomment-524055409) that Transmission "won't load torrent files without the 'files' dictionary" is inaccurate.  -- there must be either a 'file' string _or_ a 'files' dictionary. I _think_ this meant to say "won't load torrent file", which is true and is not a bug.

The **contents** of the "file" are advisory -- they are the recommended name to use when saving the torrent to disk -- but the **presence** of the "file" entry  is not advisory. Look a few paragraphs further down in the spec: "In the single file case, the name key is the name of a file, in the multiple file case, it's the name of a directory."
