### ISSUE TITLE
iOS ans upload button

### ISSUE THREAD

**Issue by Nierusan** [transmission/transmission#1524]
Hi!

I have a big issue on transmission installed on my local raspberry pi. When I click on the upload button, nothing happens. Normally a menu should come to choose between photos or file app to choose. 

This issue came with iOS 14.

![5C419A91-0D01-4CC8-AAA3-CC0F6416B118](https://user-images.githubusercontent.com/17992977/99198477-1cb47480-2799-11eb-8da9-7f6fdc663a5f.jpeg)

The new iOS 14’s menu

![08ECF901-9F73-4F4D-AAFF-6F9C65ECB181](https://user-images.githubusercontent.com/17992977/99198533-964c6280-2799-11eb-8219-56546b01180c.jpeg)

**Comment by mikedld** [comment]
@Nierusan, is this still an issue with 4.0.0-beta.1?

**Comment by ckerr** [comment]
> @Nierusan, is this still an issue with 4.0.0-beta.1?

**Comment by Nierusan** [comment]
Downloaded latest version, works fine now
