### ISSUE TITLE
Remove selected torrent by pressing delete button in search box

### ISSUE THREAD

**Issue by pudovmaxim** [transmission/transmission#153]
This happens if select some torrent in list, and then focus in search box and press del button.

Version 2.84 (14307) on Ubuntu 16.04

**Comment by mikedld** [comment]
Related to [TRAC-5758](https://trac.transmissionbt.com/ticket/5758). PR is welcome.

**Comment by pudovmaxim** [comment]
I checked it. Trouble in gtk's accelerator keys for menu actions. Accelerators intercept keypress and handle it first. I'm not found right way to change order of event execution or work correctly with focus in text field.
