### ISSUE TITLE
Firefox opens every new magnet as a new 'transmission.exe' process

### ISSUE THREAD

**Issue by andradadad** [transmission/transmission#1536]
Reproduction: click on any magnet with firefox, and transmission will open a new window of transmission.exe with the other still running.
Very dangerous for data, since it could download both at the same time or corrupt profile with list of downloads.

Windows 7 64bits
Firefox 84

**Comment by andradadad** [comment]
Anyone?

**Comment by ckerr** [comment]
This is a duplicate of https://github.com/transmission/transmission/issues/255
