### ISSUE TITLE
webgui老是卡死，能不能在代码上独立出一个工作线程给界面用？防止卡顿

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#1541]
webgui老是卡死，能不能在代码上独立出一个工作线程给界面用？防止卡顿

**Comment by urain39** [comment]
你是想说webui？旧版transmission的webui还算稳定吧？新版好像重构了，没试过。

translate: You mean webui? Is the old version of transmission webui stable? The new version seems to be refactored, and I haven't tried it.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. I have no idea if I understood you correctly (see below), but see e.g. #1314.

Also, please respect others and use English. I don't know how many times I've told you this @1265578519, and I'll ban you again, this time indefinitely, if this continues to happen. If you don't know the language, at least use [Google Translate](https://translate.google.com/) as a courtesy to others.

**Comment by 1265578519** [comment]
@mikedld 如果你不愿意使用谷歌翻译，那请你永久禁止我

**Comment by Aloento** [comment]
圣地巡礼，笑死我了
Shame on you @1265578519
