### ISSUE TITLE
now master build fail on mac 10.15.4, commit id is  b83d8e483

### ISSUE THREAD

**Issue by fjqingyou** [transmission/transmission#1547]
macOS Catalina 10.15.4
error output log:

git/transmission/macosx/PrefsWindow.m:31:13: error: property 'toolbarStyle' not found on object of type 'PrefsWindow *'
       self.toolbarStyle = NSWindowToolbarStylePreference;
            ^
git/transmission/macosx/PrefsWindow.m:31:28: error: use of undeclared identifier 'NSWindowToolbarStylePreference'
       self.toolbarStyle = NSWindowToolbarStylePreference;

**Comment by livings124** [comment]
Xcode 12 on mac 11 is now required to build.
