### ISSUE TITLE
How to change username/password transmission remote gui

### ISSUE THREAD

**Issue by TongTC** [transmission/transmission#1551]
Dear All

Now I am finding method to change password and username by not need to change parameter by open terminal and typing " sudo nano settings.json "

**For my idea:**
I would like to make web interface and change username/ password for accessing transmission -GUI

**My question:**
How to prepare setting up before making web interface for changing username/password ?

(Now I am preparing run PHP and execute bash file for execute stop service --> change password/username --> reload -- > start service but It still not work )

Best Regard

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
