### ISSUE TITLE
update-version-h.sh still relies on user_agent_prefix and peer_id_prefix from configure.ac which no longer exists

### ISSUE THREAD

**Issue by kuglee** [transmission/transmission#1553]
I'm running macOS 11 Big Sur.

A certain tracker works well up to this commit:
**Add new translations from Transifex (95% and higher)**(32add75f0e48ca4dd2c4182424ca546ff7001a98)

However with the next commit (**Remove autotools-based build system** (4c7153fa4)) there's an error: `Tracker returned error: Tracker gave HTTP response code 0 (No Response)`.

I'm unable to find the what's causing the issue. There were no source code changes between the two commits.

**Comment by kuglee** [comment]
I've found the problem.

The `configure.ac` file was removed, but `update-version-h.sh` still relies on it to define `USERAGENT_PREFIX` and `PEERID_PREFIX`.
https://github.com/transmission/transmission/blob/b83d8e48325d5a5b5d790a3fd5be2fe551205c12/update-version-h.sh#L15

I'm not sure how this issue should be handled.

**Comment by mikedld** [comment]
Thanks for reporting!
