### ISSUE TITLE
[Feature Request] Option to start with the system (minimized)

### ISSUE THREAD

**Issue by arthurflor23** [transmission/transmission#1561]
Hello,

I know there is a command line for this:
```
echo -e "
[Desktop Entry]
Type=Application
Name=transmission-gtk
Exec=transmission-gtk -m" > ~/.config/autostart/transmission-gtk.desktop
```

However, would it be interesting to have this option in the application itself?
Perhaps to complement the Preferences > Desktop tab.

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/366
