### ISSUE TITLE
Transmission defult 51413 port bug at asustor as10 series

### ISSUE THREAD

**Issue by undgang** [transmission/transmission#1564]
https://www.asustor.com/app_central/app_detail?id=875&type=6&model=10xx
Hi.
I'm a user of tr client on asustor 1004t v2 (version 3.00)

I found a issue that this version in asustor 1004t v2, when I tried to open the defult 51413 port in defalt web ui ,(of course I set the port forwarding on my router and nas's ez-router no-doubtly correct) the port is CLOSED.

Then i installed advanced web ui via ssh and try to test the port,there are no response.
So,I download the transgui remote, test the port AGAIN, the result is not closed or open , is "porttested:http error 0 no response".

I tried to change port to 51414 etc, not work as same.

I even download tr windows client to check port status, my port forwarding is fine:)
So I think this is a bug for asustor version(not upgrade to v3.00-18 yet! ), so I reported it to asustor official support,  if someone also have the same problem , please let the developer know, fix it as quick as possible, thanks all of their work!

**Comment by ckerr** [comment]
If I'm reading this correctly, this is an asustor issue rather than a bug that needs to be fixed in `transmission/transmission` so I'm closing this ticket. If this is incorrect, please file a new ticket describing the Transmission bug. Thank you!
