### ISSUE TITLE
Having crashes with a .zst crashdump that seem reproducible (happen when i rename payload file name)

### ISSUE THREAD

**Issue by slrslr** [transmission/transmission#1566]
Hello, having crashes on Arch/Manjaro Linux with Transmission 3.00 (bb6b5a062e).
When i rename certain torrent (b0rn2ra) payload file, it crash. (after re-adding torrent one day later, i can no longer reproduce it though)

But i am not willing to share the crashdump .zst file (located in /var/lib/systemd/coredump) publicly for privacy reasons. If anyone is capable to fix crashes and willing to help with this and let me know how to send it in private, link to a private contact, please let me know.

**Comment by ckerr** [comment]
I know how long this issue has been in limbo and am going through the issue backlog to resolve older unaddressed issues.

Are you still able to make this crash in a build from `master` or a nightly build from https://transmissionbt.com/download/ ?

**Comment by slrslr** [comment]
@ckerr i think that i am runing my OS latest Transmission version: 3.00 (bb6b5a062e) and i am no longer able to reproduce this issue with same torrent file that crashed 1 year back. So this may likely be closed. Thank You
