### ISSUE TITLE
Port Forwarding guide

### ISSUE THREAD

**Issue by ediowar** [transmission/transmission#1569]
Where is the Port Forwarding guide linked on https://github.com/transmission/transmission/wiki/Why-is-my-port-closed%3F

**Comment by TheWug** [comment]
you can clone it at https://github.com/transmission/transmission.wiki.git

**Comment by ediowar** [comment]
> you can clone it at https://github.com/transmission/transmission.wiki.git

**404**

**Comment by TheWug** [comment]
it's a git repository, clone it from a git client.

**Comment by ediowar** [comment]
Cloned, but the manual is not there. Found an old manual on the Transmission support forum, is it still up to date? https://trac.transmissionbt.com/wiki/PortForwardingGuide

**Comment by ediowar** [comment]
Cloned, but the guide is not there. Found an old guide on the Transmission support forum, is it still up to date? https://trac.transmissionbt.com/wiki/PortForwardingGuide

**Comment by TheWug** [comment]
I'm sorry, I misunderstood your question. I thought you were asking where the source for the wiki page you linked to was, and how to edit it.

Port forwarding is a fairly eternal process, and the method of doing this for transmission has not changed significantly, so the guide you linked, though outdated, is still applicable. The broken link should probably be removed from the wiki page though.
