### ISSUE TITLE
[Feature Request] Option to stop downloading when disk space is running low

### ISSUE THREAD

**Issue by daogan** [transmission/transmission#1571]
On my 128GB MacBook, free space is around 50GB, when downloading a 80GB full 4K BluRay movie overnight, it drains up the disk space, leaving out about ~20MB, some programs cannot be functioning properly under such low disk space, and some of other programs will crash due to low available space.

Improvement suggestions: Add a setting option with a reasonable default value to specify when to stop all downloading when disk space is running low.

**Comment by mohkale** [comment]
Have you considered having a different program monitor diskspace and then have that tell transmission to shut down or pause? For example you can have a cronjob checking every hour how much disk space is free and then if it's below a certain threshold to stop downloading.

**Comment by daogan** [comment]
That's a possible solution, thank you for the suggestion.

**Comment by philliplongman** [comment]
That's a fairly technical solution. It seems like an option to pause all downloads when 10GB (or whatever) of free space remain would be fairly simple to implement. In my experience, Transmission has had problems with queue behavior after running out of space for years—so it seems like it would be a useful addition!

**Comment by ckerr** [comment]
If Transmission said "yes" to every feature request like this, the preferences dialog would be 50 pages long :smile: I agree this could be useful to some people, but there's some threshold of "how many people would use this feature" that I don't think is met here.

**Comment by dballing** [comment]
I seek not to re-open this declined request, but only to note that "I'd use this feature, too" :-)
