### ISSUE TITLE
Is there a dark mode for transmission on W10?

### ISSUE THREAD

**Issue by pogoooooo** [transmission/transmission#1576]
I looked online and didn't find an answer for this question so I thought about asking here, I hope it's the right place. I love transmission but I would love to get a dark mode for it. Is there a trick for this or is it on development maybe? Thanks.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #920.

**Comment by pogoooooo** [comment]
@mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.

**Comment by PaulMEdwards** [comment]
> @mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.

Run this command for a dark UI on Windows:

`"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`

You can also append `-style fusion` for a slightly different theme, which I think looks better:

`"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

**Comment by Damians0** [comment]
> > @mikedldgrazie per il link!  Ho cercato in quel sito e non vedo alcuna soluzione per questo, potresti aiutarmi?  Ho abilitato la modalità oscura nel mio W10 e vedo qualcosa come "darkmode=n" nei commenti del problema ma non capisco cosa o come usarlo.
> 
> Esegui questo comando per un'interfaccia utente oscura su Windows:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`
> 
> Puoi anche aggiungere `-style fusion`per un tema leggermente diverso, che penso abbia un aspetto migliore:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

A thousand thanks.  But do I have to write every time I open transmission?  Is there no way to save the setting?

**Comment by Damians0** [comment]
> > @mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.
> 
> Run this command for a dark UI on Windows:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`
> 
> You can also append `-style fusion` for a slightly different theme, which I think looks better:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

A thousand thanks. But do I have to write this command every time I open transmission? Is there no way to save the setting?

**Comment by Gersonzao** [comment]
> > > @mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.
> > 
> > 
> > Run this command for a dark UI on Windows:
> > `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`
> > You can also append `-style fusion` for a slightly different theme, which I think looks better:
> > `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`
> 
> A thousand thanks. But do I have to write this command every time I open transmission? Is there no way to save the setting?

Make a shortcut for it.

**Comment by maplefujian** [comment]
> > @mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.
> 
> Run this command for a dark UI on Windows:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`
> 
> You can also append `-style fusion` for a slightly different theme, which I think looks better:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

I'm going to try this!

**Comment by maplefujian** [comment]
> > > > @mikedld thanks for the link! I searched in that site and I don't see any solution for this, could you help me? I have dark mode enabled in my W10 and I see something like "darkmode=n" in the comments of the issue but I don't understand what or how to use it.
> > > 
> > > 
> > > Run this command for a dark UI on Windows:
> > > `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`
> > > You can also append `-style fusion` for a slightly different theme, which I think looks better:
> > > `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`
> > 
> > 
> > A thousand thanks. But do I have to write this command every time I open transmission? Is there no way to save the setting?
> 
> Make a shortcut for it.

If you prefer to have Transmission open in dark mode with the Fusion style every time without manually entering the command each time, you can create a shortcut that includes these parameters. Here's how you can do it:

Right-click on your Desktop (or in any directory where you want the shortcut to be) and choose New > Shortcut.

In the location field of the shortcut, enter the command:

sql
Copy code
"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion
Make sure to adjust the path if your Transmission installation is in a different folder.

Click Next, give your shortcut a name (like "Transmission Dark Mode"), and then click Finish.

Now, whenever you want to open Transmission in dark mode with the Fusion style, you can simply double-click this shortcut. This method saves you from having to manually enter the command every time.

**Comment by maplefujian** [comment]
would the above work ? Going to try when I get home.

**Comment by dav-aguilera** [comment]
> would the above work ? Going to try when I get home.

Worked for me. Thanks @maplefujian.

**Comment by maplefujian** [comment]
> > would the above work ? Going to try when I get home.
> 
> Worked for me. Thanks @maplefujian.

Can you share screenshots ? Would love to see how it looks now.

**Comment by dav-aguilera** [comment]
![Captura de pantalla 2024-12-10 191534](https://github.com/user-attachments/assets/7609dd6c-d7b1-4751-904b-a12f2ea5321d)
![Captura de pantalla 2024-12-10 191754](https://github.com/user-attachments/assets/ce882e4f-989e-449f-a4c3-289a42129a74)
