### ISSUE TITLE
cmake cannot find GoogleTest

### ISSUE THREAD

**Issue by Vla8islav** [transmission/transmission#1596]
I copied the repository and I'm trying to build using the instruction provided. When I do

`➜  transmission git:(master) cd build && cmake ..`
it fails with the 
>CMake Error at tests/CMakeLists.txt:3 (include):
>  include could not find load file:
>
>    GoogleTest
>
>
>-- Looking for uncrustify
>-- Configuring incomplete, errors occurred!
>See also "/root/repos/transmission/build/CMakeFiles/CMakeOutput.log".
>See also "/root/repos/transmission/build/CMakeFiles/CMakeError.log".

error.
I'm not quite sure, but I think it's supposed to be one of submodules, which were successfully installed with the 
`git submodule update --init`
command.
What do I miss?

My system: 

>No LSB modules are available.
>Distributor ID: Debian
>Description:    Debian GNU/Linux 9.13 (stretch)
>Release:        9.13
>Codename:       stretch
`cmake --version`
>cmake version 3.7.2

**Comment by dbkeys** [comment]
Same issue ....

**Comment by LETIshNick** [comment]
Same issue trying to build on osx 11.2 with m1 chip

**Comment by mikedld** [comment]
`GoogleTest` module was added in CMake 3.9. Your version (3.7.2) is lower than that, which causes the error. I don't see anything from this module being used, so it's safe to comment out / remove this line (`include(GoogleTest)`) from tests/CMakeLists.txt.

**Comment by mikedld** [comment]
Fixed in 28b0e53006563624e510c81dd080c9ac4be85d53.
