### ISSUE TITLE
'Image not recognized' error – MacBook Pro M1 Big Sur

### ISSUE THREAD

**Issue by NumFive55** [transmission/transmission#1598]
I tried downloading and installing the latest Transmission build (3.0) on my new MacbookPro M1 with Big Sur and am getting the prompt below when trying to open the DMG

![image](https://user-images.githubusercontent.com/37964923/105560214-34e8c880-5ce1-11eb-9865-e8d4f8f4fa81.png)

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #1528.

**Comment by Mask3dMan** [comment]
Not duplicate, completely unrelated problem with architecture. The dmg probably got corrupted during download.

**Comment by mikedld** [comment]
M1 is not officially supported yet, so it doesn't really matter why it failed. Keeping this issue around makes no sense.

**Comment by livings124** [comment]
The app should be able to run in Rosetta.

**Comment by cpollo01** [comment]
This issue should be closed and is a duplicate. The link @mikedld shared did the trick – I downloaded the DMG from that thread and it installed correctly.

Thanks!

**Comment by mikedld** [comment]
> The app should be able to run in Rosetta.

Oh, didn't know they resurrected that :)

**Comment by livings124** [comment]
What’s old is new.

**Comment by Mask3dMan** [comment]
> M1 is not officially supported yet, so it doesn't really matter why it failed. Keeping this issue around makes no sense.

Just redownloading the dmg would've solved it. Dmg images are not architecture dependent. Transmission runs fine on rosetta, with no apparent issues.
