### ISSUE TITLE
Where are preferences stored? (Wiki link on this is dead, and it's not easy to find)

### ISSUE THREAD

**Issue by magicgoose** [transmission/transmission#160]
This wiki page says they are in JSON format.
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

This part
>For the location of these files, look at the Configuration Files page

has a broken link, it doesn't actually lead anywhere.

I tried to find it myself:

```console
$ find ~ -iname "*transmission*"
~/Applications/Transmission.app
~/Applications/Transmission.app/Contents/MacOS/Transmission
~/Applications/Transmission.app/Contents/Resources/Transmission.icns
~/Applications/Transmission.app/Contents/Resources/TransmissionDocument.icns
~/Applications/Transmission.app/Contents/Resources/TransmissionHelp
~/Applications/Transmission.app/Contents/Resources/TransmissionHelp/gfx/TransmissionIcon.png
~/Applications/Transmission.app/Contents/Resources/TransmissionHelp/TransmissionHelp.helpindex
~/Applications/Transmission.app/Contents/Resources/web/javascript/transmission.js
~/Applications/Transmission.app/Contents/Resources/web/style/transmission
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.m0k.transmission.sfl
~/Library/Application Support/Transmission
~/Library/Caches/org.m0k.transmission
~/Library/Cookies/org.m0k.transmission.binarycookies
~/Library/Preferences/org.m0k.transmission.plist
~/Library/Saved Application State/org.m0k.transmission.savedState
```

None of that looks like a JSON config file.

So, how can I change some settings which are absent in GUI?

**Comment by slokhorst** [comment]
`settings.json` is only used by the GTK, daemon, cli, and Qt(?) clients, it's at `$XDG_CONFIG_HOME/transmission/settings.json` or `~/.config/transmission/settings.json`.

The native macOS client uses another method of storing settings. See https://trac.transmissionbt.com/wiki/MovedToGitHub/EditConfigFiles#MacOSX

**Comment by magicgoose** [comment]
Okay, thank you
