### ISSUE TITLE
Changing per-file download priorities using web client currently broken on master

### ISSUE THREAD

**Issue by TheWug** [transmission/transmission#1605]
![priorities](https://user-images.githubusercontent.com/3932619/105702322-7edbd500-5ec0-11eb-8f2e-d29958d897ef.png)

Attempting to change the priorities of a downloading file cause the buttons to become "stuck down" as shown. When the page is refreshed, they remain at their previous values. A little bit of chrome debugging indicates that, as far as i can tell, the correct set-torrent RPC calls are being generated, and those calls is succeeding, but for some reason the priority values are not sticking.

Running a torrent for a short period of time confirms that the priority changes are being ignored, and not applied invisibly.

**Comment by TheWug** [comment]
Looks like it's still broken as of 16ec15d.

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/4610.
