### ISSUE TITLE
transmission keep downloading all files even if i uncheck some in task creation dialog

### ISSUE THREAD

**Issue by mega-optimus** [transmission/transmission#1610]
I'm using the latest version (3.00), running on windows 7.

**Comment by amcgregor** [comment]
It's important to note that Bittorrent itself does not structure itself around the concept of "files". Instead, it utilizes "chunks", so if you select a file that is partially across several, other files may be partially, or completely downloaded even if de-selected. They just happened to be within a chunk needed for a file you did have selected.
