### ISSUE TITLE
Transmission BTC stops on Shield

### ISSUE THREAD

**Issue by Charlyiii** [transmission/transmission#1614]
Until yesterday I was perfect, since yesterday just put it in the background or when the Shield falls asleep, the server stops ... someone who can guide me on what happens? I was tried remove and reinstall de app, but no solution. Thank you.

**Comment by avivmu** [comment]
What is shield?

**Comment by Charlyiii** [comment]
> What is shield?

Nvidia SHIELD, a Android TV Box
