### ISSUE TITLE
What’s the definition of incomplete-dir config variable? 

### ISSUE THREAD

**Issue by Anan5a** [transmission/transmission#1615]
I want to know how exactly the `incomplete-dir` variable  is used. From docs, it is supposed to keep incomplete downloads, temporarily 
I have few questions :

When a torrent is marked complete in this context? 
 Is it possible to use a global configuration for this when torrents are added via rpc? For example,
`settings.json` containing 
```json
{

"incomplete-dir":"/var/spool/disk2"

}
```
Then a torrent is added via rpc with download destination `/var/spool/disk0`
How will transmission-daemon handle this?

**Comment by EdwinKM** [comment]
Not a developer. Just my experience. Found it also a bit confusing. But you enter for a torrent a  (default) "download-dir", but if "incomplete-dir-enabled" it will be actually first placed in this "incomplete" folder. If the torrent is completed it will be moved to the "download-dir". The confusing part is that the web-gui is only showing the final destination folder.

**Comment by Anan5a** [comment]
i figured it, somehow.
`Download is marked complete when Transmission finishes receiving all the pieces and then file is moved to destination location and is seeded from there afterward`
