### ISSUE TITLE
error on http redirect in magnet link

### ISSUE THREAD

**Issue by diegargon** [transmission/transmission#1616]
If i paste a  link  to magnet in the navigator or click in click in the link , firefox give me the option to open the magnet with transmission and works fine.
But if i add directly the link (link to a magnet) to web interface or using transmission-remote got this error:

gotMetadataFromURL: http error 404: Not Found

Here the log using transmission-remote:
https://pastebin.com/1Am2A0uB

That seems a problem with the redirect perhaps?
https://github.com/qbittorrent/qBittorrent/issues/11877

Checked with
transmission-daemon 2.94 
transmission-daemon 3.00

**Comment by diegargon** [comment]
#1618 perhaps related?

**Comment by ckerr** [comment]
The error message sounds like #88.

Hmm, maybe try running with  the environment variable `TR_CURL_VERBOSE=1` to see what curl is doing?

**Comment by ckerr** [comment]
Closed due to lack of response + lack of actionable info.

If this is still happening in Transmission 4, please open a new ticket with info on how to repro. Thanks!
