### ISSUE TITLE
Please delete “Spanish (Latin America)” from Transifex and from the application

### ISSUE THREAD

**Issue by fitojb** [transmission/transmission#1617]
It unnecessarily complicates volunteer maintenance of the Spanish localization. Besides, in the base Spanish translation there are NO terms that are exclusive to Spain, or any other region for that matter.

**Comment by ckerr** [comment]
@mikedld did this get done -- can this issue be closed?

**Comment by mikedld** [comment]
Done. Was never in the repository AFAICT.
