### ISSUE TITLE
transmission-cli man page lists option not recognized by transmission-cli

### ISSUE THREAD

**Issue by esraiak** [transmission/transmission#1621]
These commands
  >> transmission-cli -n
  >> transmission-cli --new
say that the respective options are not recognized.

However
  >> man transmission-cli
lists the option:
"
    -n, --new sourcefile
           Create torrent from the specified file or directory
".

**Comment by sidml** [comment]
@ckerr 
Since the cli doesn't support this, should i make a PR with updated man page ?
