### ISSUE TITLE
Sequential download

### ISSUE THREAD

**Issue by XITRIX** [transmission/transmission#1622]
How could I modify library to enable sequential download?
I found [this Wiki article](https://github.com/transmission/transmission/wiki/Can-I-sequence-the-files-I-download), but it's outdated and there is no method "compareRefillPiece" in peer-mgr.c.

**Comment by AndreyPavlenko** [comment]
> How could I modify library to enable sequential download?
> I found [this Wiki article](https://github.com/transmission/transmission/wiki/Can-I-sequence-the-files-I-download), but it's outdated and there is no method "compareRefillPiece" in peer-mgr.c.

https://github.com/AndreyPavlenko/transmission/commit/6d347636dffdd3d309805c6509ad2b69cef9059e

**Comment by XITRIX** [comment]
Thanks a lot!
