### ISSUE TITLE
Error: No such process

### ISSUE THREAD

**Issue by mcandre** [transmission/transmission#1626]
When renaming your Windows home directory, Transmission gets confused about the configured download and partial directories. From the GUI view everything looks fine. But when you try to download a magnet, the resulting torrent gets a few KB into the download and borks with the message `Error: No such process`...

As a workaround, temporarily set both download directories to other values, such as your home folder and Documents folder. Then go back and configure the directories to the desired values.

I suppose that some part of the configuration system is using a dead file directory pointer, instead of ordinary string paths. That's why everything looks okay in the GUI but the downloads can fail.

I tried a few different torrents and got the same behavior with each one. Flat torrents with no crazy filenames or any deep directory hierarchies. The problem appears to be the underlying configuration persistence system (Windows registry)?

Transmission 3.00

Windows 10

**Comment by amilios** [comment]
Hello, a solution is to delete the AppData directory that corresponds to Transmission. The issue is that the settings.json saves the default path as a string, so after renaming your user account/home directory this path doesn't correspond to anything anymore. Hope that helps!

**Comment by Phoenix616** [comment]
Doesn't work. After deleting it the program even crashes on trying to add the torrent again.
