### ISSUE TITLE
feature request: provide statistics on number of passive-mode peers

### ISSUE THREAD

**Issue by archenemies** [transmission/transmission#1629]
According to my meager understanding, if I want to use Transmission without port forwarding configured, then as a Torrent client it will be operating in "passive mode" and can only connect to "active" peers.

In other words, without port forwarding, all the peers that I connect to will be in the same mode - active.

Conversely, with port forwarding, the peers for each torrent are going to fall into two categories - true? Is there an interface which outputs a count of how many peers are active and how many are passive, for each torrent? Would it be a good idea to provide such an interface?

**Comment by ckerr** [comment]
I'm not familiar with the phrasing you're using here, e.g. 'passive mode', but I think I understand what you mean.

Between two peers -- your own and someone else's -- one of the two has to initiate the connection, and the other has to receive it, like one person phoning another. If the incoming peer connection port is closed on your system, then you won't be able to receive incoming calls, only make outgoing ones. If the port is open, then you can both receive incoming & make outgoing calls. Port forwarding is one way to open that port.

The torrent details / inspector will show you which peers are incoming and which are outgoing. That should give you the information that you're looking for!
