### ISSUE TITLE
feature to see public ip address in webUI

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#1634]
Hello, Thanks for great project. 

Please include also to view public ip address which can be check from checking external website "what is my ip-address" and display that in the webUI, and update every 1 minutes when webUI is active. this will help to check which public ip address transmission is running. thanks.

**Comment by killemov** [comment]
Sounds paradoxical to me. How can you see the public IP in the web-UI if you don't know the public IP already?

**Comment by louwe** [comment]
> Sounds paradoxical to me. How can you see the public IP in the web-UI if you don't know the public IP already?

Because you are usually accessing the web UI from an internal network through a private IP.

**Comment by alexg-k** [comment]
+1 This is especially useful when transmission and the VPN client are running in containers, which gets more and more common (especially when making use of the web ui).

**Comment by xiruizhao** [comment]
The user should use a dynamic DNS client or write his own bash script. Asking transmission to query public IP address is not the appropriate solution.

**Comment by ckerr** [comment]
superceded by #5785.
