### ISSUE TITLE
Collect unwanted but received blocks as invisible files within torrent root folder

### ISSUE THREAD

**Issue by porg** [transmission/transmission#1635]
**Foreword**
- The nature of this request is old and comes again and again
  - originally 2013 https://trac.transmissionbt.com/ticket/532
  - also more recently Jan 2020 in #1105 
  - There is a [patched Mac build available](https://trac.transmissionbt.com/ticket/532#comment:221), but from Oct 2015.
    - Would love something contemporary.

**Reproduction:**
- Start a bittorrent download which contains various files and folders.
- Only select certain files or folders for download.

**Expected:**
- In my download folder I only get what I wanted.
- What is necessary technically (due to the BitTorrent protocol and its pieces) is kept away from me as a user while still ensuring:
  - network stability (pieces are kept intact)
  - flexibility (external disk usage)
  - portability (easy moving of a torrent download folder)

**Actual:**
1. You get a lot of additional unwanted files.
2. and even folders from the download folder root path until each unwanted file.
3. The best convenience option currently offered:
  a. Incomplete files can have a .part suffix, unwanted files will stay with this suffix forever, at least you can distinguish them.
  b. You can decide to keep incomplete files in a dedicated "Incomplete" folder.

**Negativ consequences:**
I. On systems without sparse file support unwanted files waste a lot of storage space:
 - Ad 1: not only the overlapping piece, but takes the full size that unwanted file needs (the sparse parts get really filled with zeros on disk instead of just metadata which says "there's a gap here")
  - Luckily since APFS on macOS 10.13 High Sierra this huge downside is mitigated.
    - I checked that with Transmission 3.0.0 on macOS 11 Big Sur, the file info in Finder shows a large file size but in brackets the "on disk" usage is much less, accounting just for the overlap.

II. Visual clutter
  - Ad 3a: Still given with the convenience option of a ".part" suffix
    - You can distinguish them but not so easily filter them out, they disturb in file listings.
    - Also sorting is no workaround. Neither ".part" nor "Document" (shown as type under macOS) will make it sort at the very start or beginning.
  - Ad 2: Unwanted folders needed to created to hold unwanted files, if the torrent specifies such path structures.

III. Limited portability
   - Ad 3c: If you keep pieces somewhere else, you have limited portability.
   - Having it on the boot volume at a central location allows you portability between storage devices/volumes
   - But cross device moving will break the pieces, as they to not travel along
   
**Proposal**
Hence I come up with a solution for macOS with APFS (and will work the same for all other Unices with sparse file support)
1. Unwanted files get a "." (dot) prefix which by default makes them invisible on Unix*es and a ".part" suffix.
  -  Also possible on Windows to hide files starting with a dot.
2. Unwanted folders necessary along the path to unwanted files get a "." prefix as well.
3. Wanted files are normally named, never get a "." prefix or invisible flag
 - If the user opts in for a ".part" suffix, gets them.
 - What I as the user requested is always a visible file.
 - If I want a crude differentiating I get that .part suffix
- Advantage of an unchanged suffix is that file type is already correct during download, for correct sorting by filetype, preview by QuickView (SPACE on selected file), etc.

**Advantages**
1. You can move the entire torrent root folder and move it freely from Mac to Mac which runs Transmission (with a version that feature gets introduced or newwer).
  - No need to also migrate your "Incomplete" folder or AppSupport "pieces" folder
2. The burden of invisible files taking space is neglectable on sparse file OSes
  - Anyway if you do not plan to use the folder for torrenting anymore, just move out the wanted files to your desired location, and trash the entire folder including all invisible unwanted files.

**Comment by fr500** [comment]
+1

**Comment by fr500** [comment]
@porg have you managed to patch a modern transmission with those patches?

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #290.

**Comment by porg** [comment]
@fr500 I did not attempt to patch modern Transmission versions.

**Comment by porg** [comment]
@mikedld I always search for existing issues, I even referenced 2 related issues in my "Foreword" section.

I do not know by what criteria you closed my issue and kept #290 open. But as it is now I feel a bit unappreciated. I took the effort to file a standalone issue with a fully articulated reproduction & proposal supplied with design rationales.

My issue-tracker practice as a UX designer inside a development company: If I find duplicates, I do not operate by "keep the oldest and close all newer ones as duplicates" but keep the "most useful issue" alive and close the ones as dupes which are narrow/outdated or less applicable. What's useful would take lengths to describe here, but roughly: "as descriptive as necessary", "short as possible", with more/better material attached (screenshots, logs, sketches, links to guideline/standard, etc), many crosslinks to/from other issues, wiki, code-commits, etc.

#290 seems pretty thin in that regard. May you reconsider?
