### ISSUE TITLE
transmission cannot find symlinks to files

### ISSUE THREAD

**Issue by alethiophile** [transmission/transmission#1636]
I'm currently trying to use git-annex to organize my torrents. git-annex works by (by default) replacing files with symlinks to those files in a central location, while the symlinks are committed to git.

When trying to make transmission see downloaded data, it shows "no data" when pointed to a default git-annex directory (with each file replaced by a symlink to that file stored elsewhere). Ideally, for already-downloaded torrents transmission would be able to traverse symlinks and use the targets of those symlinks for seeding.

**Comment by pmarsden** [comment]
I use symlinks all the time, and it works fine.

**Comment by alethiophile** [comment]
Hmm. A few days ago when I tried to start it up it wasn't finding any of the symlinks, but now it seems to work fine.

Put it down to gremlins, I guess.
