### ISSUE TITLE
Download location is set but when adding a torrent the path is modified

### ISSUE THREAD

**Issue by Fenrir88** [transmission/transmission#1637]
Using the windows qt client and connecting to a Linux backend. In preferences, downloading, Save to Location, the value follows a pattern such as "/media/myDownloads".  But when adding a new torrent the suggested location is "C:/media/myDownloads" which is not the set value, nor a valid path.

**Comment by ckerr** [comment]
Closing as a duplicate of https://github.com/transmission/transmission/issues/1490
