### ISSUE TITLE
Set incomplete dir to temp folder

### ISSUE THREAD

**Issue by binarykitchen** [transmission/transmission#1641]
Don't want to store incomplete chunks in the same download folder (which seems to be the default on MacOS). And is messing with some video servers like Plex to serve them to any home TVs when incomplete.

That said, would be good to store them into the default $TMPDIR or something similar. Or at least add an option for that in the preferences screen, see attachment.
<img width="547" alt="Screen Shot 2021-03-18 at 21 46 54" src="https://user-images.githubusercontent.com/177641/111598103-b8cbb680-8833-11eb-87cf-b24c2b1bba6f.png">

How about a sub-option under "Keep incomplete files" and point that to the temp folder?

Agree, it's too sophisticated for mortal users but for some nerds like you and me, it's a huge plus. 

Hope this helps. Sorry for not checking if this ever has been raised before. Thanks for the hard work, cheers!

**Comment by ckerr** [comment]
Since this isn't something that most people will ever use, I don't think it makes sense as a GUI option.

`settings.json` has an `incomplete-dir` entry where you can set the location of incomplete files. I _think_ that is what you're looking for here.
