### ISSUE TITLE
[Arch Linux] 3.00 transmission-daemon crashes occasionally

### ISSUE THREAD

**Issue by ArchieMeng** [transmission/transmission#1645]
## Crash Log: 
https://paste.ubuntu.com/p/H5yxyySyTt/

## Descriptions:
It sometimes just crash without clear direct cause. From its error log, the last operations are always some "Could not connect to tracker " and "Retrying announce in XXXX seconds" messages. However, sometimes it didn't crash immediately after the last log, so I am not confident to link the trackers connection errors to the crash.
Since the (std) error log is too large, I have to find some websites that supports log file uploads to show you guys here. So, in this report, there is no transmission-daemon error log available.

BTW, my curl version is 7.75.0 and 4.7.0 for curl4. libevent version is 2.1.12 .

## Update:
I downgraded to version 2.94 and problems still exist. However, the error log is a bit different.
crash log for version 2.94: https://paste.ubuntu.com/p/vfs6kngGZQ/

**Comment by astrotee** [comment]
Same here on manjaro, it's been happening for months now!

**Comment by ArchieMeng** [comment]
> Same here on manjaro, it's been happening for months now!

In fact, after days of using transmission, I found it really stable recently. Only 2 crashes in a month.
Anyway, I recommend you to add a periodical task (Usually, cronie) to keep transmission-daemon running.

The script can be:
```Bash
#!/bin/bash
#Filename: start_transmission.sh

pidof transmission-daemon >/dev/null
if [ $? -ne 0 ]; then
        setsid transmission-daemon
fi
```
And run script per minute:
```bash
*/1 * * * * bash start_transmission.sh
```

**Comment by astrotee** [comment]
> In fact, after a month of using transmission, I found it really stable recently. Only 2 crashes in a month.

Well, it happens randomly in my experience, but it seems to occur more often than that, at least to me, I might have it running for days!
But still it needs to be looked into.
> Anyway, I recommend you to add a periodical task (Usually, cronie) to keep transmission-daemon running as a temporary solution.
> 
> The script can be:
> 
> ```shell
> #!/bin/bash
> #Filename: start_transmission.sh
> 
> pidof transmission-daemon >/dev/null
> if [ $? -ne 0 ]; then
>         setsid transmission-daemon
> fi
> ```
> 
> And run script per minute (in cronie):
> 
> ```shell
> */1 * * * * bash start_transmission.sh
> ```

That won't exactly work for me because I have it managed by systemd, but thanks anyway

**Comment by ckerr** [comment]
The paste from the original bug report has expired…

if this is still happening in the nightly builds, please update the ticket with a new crash report or stacktrace. Thank you!

**Comment by ArchieMeng** [comment]
I will check it later these days, since I don't have my server with me right now.

**Comment by ArchieMeng** [comment]
After I check my log, there is no transmission crash log at all for a week now. I guess it might be caused by some other packages. Because the transmission package on Arch hasn't been updated since 26 Jul 2020, and I am still using the same version of transmission which is this issue related to.
