### ISSUE TITLE
Client announcing itself twice to the tracker with differents id

### ISSUE THREAD

**Issue by damcav35** [transmission/transmission#1646]
#### Description
When adding a torrent via a magnet link with a tracker, to a transmission client, the client announces itself twice to an HTTP tracker.
It uses the same key, but not the same id.

When the download is finished on the client, if 'timeout_downloaders_interval' did not expires on tracker side, a ghost peer is present.

In the meantime, if removing / adding the same torrent on the client, the tracker will return the ghost peer to the client.
The client will try to connect to itself, requesting for the wrong peer id.

Constated on versions:
- 2.92
- 2.94
- 3.00

#### logs

situation: 1 peer seeding for the torrent ux-web

- adding the torrent via magnet link to a client 

Logs from client:

ux-web Announcing to tracker (announcer.c:1554)
ux-web Got 1 peers from tracker (torrent.c:565)

-> got the peer seeding from the tracker

Saved "/etc/transmission-daemon/torrents/ux-web.c28eb888a801f1bc.torrent" (variant.c:1274)
ux-web Pausing (torrent.c:1856)
Saved "/etc/transmission-daemon/resume/ux-web.c28eb888a801f1bc.resume" (variant.c:1274)
ux-web Magnet Verify (torrent.c:1879)
ux-web Queued for verification (verify.c:269)
ux-web Verifying torrent (verify.c:224)
ux-web verifying torrent... (verify.c:62)
ux-web Verification is done. It took 0 seconds to verify 209732268 bytes (209732268 bytes per second) (verify.c:167)

ux-web Announcing to tracker (announcer.c:1554)
ux-web Announcing to tracker (announcer.c:1554)

-> announcing twice

ux-web Got 2 peers from tracker (torrent.c:565)

-> the peer seeding, and the first announce

When requesting the tracker at this time :

[
  {
    "ip": "172.16.0.2",
    "peer id": "-TR2940-svvhqpc2zds4",
    "port": 51413,
    "key": "57760b54"
  },
  {
    "ip": "172.16.0.1",
    "peer id": "-TR2940-e8v1k4xcsakz",
    "port": 51413,
    "key": "4bdcf30b"
  }
]

The client starts downloading the torrent, and if requesting the tracker we got 3 peers :

[
  {
    "ip": "172.16.0.2",
    "peer id": "-TR2940-svvhqpc2zds4",
    "port": 51413,
    "key": "57760b54"
  },
  {
    "ip": "172.16.0.1",
    "peer id": "-TR2940-e8v1k4xcsakz",
    "port": 51413,
    "key": "4bdcf30b"
  },
  {
    "ip": "172.16.0.2",
    "peer id": "-TR2940-h1u78xmzmmf4",
    "port": 51413,
    "key": "57760b54"
  }
]

-> the seeding peer, the peer from first announce, the peer from the second announce, which is the one downloadling
-> same ip, same key, but different peer id

- When the client is finished downloading:

ux-web State changed from "Incomplete" to "Complete" (torrent.c:2218)
ux-web Announcing to tracker (announcer.c:1554)
ux-web Got 3 peers from tracker (torrent.c:565)

-> The peer from the first announce is still there

#### To Reproduce
- setup an http tracker
- setup 2 transmission client
- create a torrent with a magnet link on the first client, with the files on the transmission's download dir
Using transmission's watch dir, it will be added automatically and the client is seeding (it already got all the files in the download dir)
- add the torrent to the second client using rpc commands

**Comment by cfpp2p** [comment]
`    /* corresponds to the peer_id sent as a tracker request parameter.
     * one tracker admin says: "When the same torrent is opened and
     * closed and opened again without quitting Transmission ...
     * change the peerid. It would help sometimes if a stopped event
     * was missed to ensure that we didn't think someone was cheating. */
tr_torrentUnsetPeerId(tor);`

https://github.com/transmission/transmission/blob/9c5e6f7ea61ad4e7708756b7a9b7c299936117f4/libtransmission/torrent.c#L1837

**Comment by damcav35** [comment]
It would be nice to have an option to disable this behaviour, very annoying on private tracker / torrents

**Comment by ckerr** [comment]
This is intended behavior as described correctly by @cfpp2p
