### ISSUE TITLE
Compound Transfer Window

### ISSUE THREAD

**Issue by davidavdavid** [transmission/transmission#1648]
At one point when numerous transfers (more than one) were in play, instead of opening separate windows for each download where one would ADD a torrent to be downloaded, all of those windows would be contained in one window.  

I am guessing that at some point with one of the updates this feature was removed/deprecated.

Please let me know.

**Comment by UltimateByte** [comment]
That looks loke an issue for Transmission-GUI, not for Transmission-daemon.
https://github.com/transmission-remote-gui/transgui/issues

I guess you can close this issue and open a new one in the appropriate repo to leverage some room for transmission-daemon to focus on their own issues.

Best regards
