### ISSUE TITLE
Transmission-gtk UX and private trackers

### ISSUE THREAD

**Issue by lvella** [transmission/transmission#1649]
Private trackers take very seriously statistics reports. And some (by that I mean at least one I know) take offense with Transmission, because the Gtk version allows for the user to "quit now" right after the download is complete, without giving the opportunity for the download statistics to be reported back.

The "quit now" button is shown right after the user clicks to quit, which is prone to be clicked by users who don't know any better. Then, next time Transmission is opened, it triggers the anti-cheat for the tracker using [this software](https://github.com/HDInnovations/UNIT3D-Community-Edition), because the user is now a seeder for a download that was never completed in the eyes of the tracker.

What is the solution for the trackers? They ban Transmission.

If I were to make a PR to make Transmission more appealing to such trackers, what solution would be more likely to be accepted? I can think of two:
- Remove the "Quit Now" button. I don't know how transmission-qt does it, but obviously such solution means reporting back the statistics to the tracker before closing the process.
- Add the Transmission variant (Qt, Gtk, Cli or Daemon) to the User-Agent of the HTTP request to the tracker. This will allow the trackers to just ban the versions that offends their anti-cheat system.

**Comment by ckerr** [comment]
Hmm... that feature has been in the GTK client for literally [13 years](https://github.com/transmission/transmission/commit/0fa3fb0d67c443aadf52d5660faba01c8daac351) now... surely if this was really an issue it would have surfaced before now?

Still, IMO the answer is not to limit the damage s.t. trackers can ban only the GTK client. I distinctly remember the intent of the feature was to allow the app to exit in cases where the tracker was slow to process the 'stop' requests. Maybe if the "Quit Now" button was insensitive for the first five seconds, and then was enabled? That should allow responsive trackers to get the stop requests, yet still leave users with the ability to force-quit when trackers are not responding.

**Comment by ckerr** [comment]
Closing due to lack of a response.
