### ISSUE TITLE
Feature request: Option to use labels in rpc api 

### ISSUE THREAD

**Issue by NO-ob** [transmission/transmission#1656]
Requesting the ability to use labels instead of ids when making post requests to the api an example for torrent-get

```
{
"arguments": 
     {
        "fields": ["name","status","percentDone","rateDownload"],
        "labels": ["uwu"]
     },
    "method": "torrent-get"
}
```

This would return results for torrents with the label "uwu" I think this would be quite useful if you have a program adding torrents via the api as all the torrents could be given a label the program knows and then it could just make requests using the label instead of needing a list of ids

**Comment by ckerr** [comment]
That's kind of a neat idea. What would you use it for?

**Comment by LaserEyess** [comment]
Sample use case: You're using labels to keep track of the type of content, e.g. Linux ISOs. These ISOs may come from many different trackers and be in different directories. You'd like to do a `torrent-set`, say `trackerAdd` or `location` on only torrents with those labels. Right now you'd have to pull all torrents with `torrent-get`, then filter by labels locally to get the IDs, then send the `torrent-set`. 

This could be further extended if the session was aware of all current labels.

**Comment by killemov** [comment]
Actually a slightly broader query option could go a long way to optimize the data sent from Transmission. Currently only a "recently-active" option is available.

 ```
 {
 "arguments": 
      {
         "fields": ["name","status","percentDone","rateDownload"],
         "query": [
           {
             "field": "labels",
             "operator": "contains",
             "operand" : ["uwu"]
           },
           {
             "field": "status",
             "operator": "equals",
             "operand" : "4" // Downloading
           },
         ]
      },
     "method": "torrent-get"
 }
 ```

**Comment by ckerr** [comment]
Superseded by https://github.com/transmission/transmission/pull/3125 (I think?)

**Comment by killemov** [comment]
> Superseded by #3125 (I think?)

For the simplest case: kinda sorta. @NO-ob made a very specific case for labels. I think we could do better.
