### ISSUE TITLE
IPv6+IPv4 support is not good.

### ISSUE THREAD

**Issue by lvella** [transmission/transmission#1659]
I noticed I was getting no incoming peer connections from IPv4 addresses from private trackers. After monitoring the traffic to one private tracker with Wireshark for a few minutes, it was clear that only IPv6 requests were being made to that tracker without the `&ipv4=` GET parameter, so there was no way for the tracker to know my IPv4 address.

I tested it with using the branch of my unrelated PR #1654, which is based on a very recent master.

I think the solution to this problem is to implement the 2020-01-03 version of [bep_0007](https://www.bittorrent.org/beps/bep_0007.html), where one simply sends the announce through every address you want to use. Possibly also implement the `&ipv4=` solution to be backwards compatible with trackers who support it.

**Comment by howl** [comment]
@lvella, i upper l lower, is a pain to mention you xD.

I have just open, and then close a feature request, my bad to search after opening a issue.

I wish that this issue and your contribution gets all the attention it needs.

**Comment by howl** [comment]
This need also to be implemented in trackers, peer_id key when multiple reports are send from the same peer, etc...

**Comment by lvella** [comment]
@howl Trackers who don't will see two independent peers. I don't understand the protocol enough to see what kind of problems this can cause, but I am hoping it is harmless.

**Comment by howl** [comment]
If the peer_id is the same, there are trackers that substitute the previous ip, as this is a factible way to track dynamic ip changes. Not 100% sure when one ip is 4 and the other 6.

**Comment by bormay** [comment]
Has this issue been resolved yet? When my transmission client downloads a torrent it only downloads from ipv6 peers. The downloads are extremely slow because of it. My transmission client is on a box that has native ipv4 and ipv6...
