### ISSUE TITLE
[Language][macOS]  adding zh_TW.lproj and zh_CN.lproj to macosx?

### ISSUE THREAD

**Issue by yangjian226200** [transmission/transmission#167]
Hi, the developers.
I found the Chinese version of Linux and win, but not mac.
I can find zh_CN.lproj in the Chinese forum，what can I do?

**Comment by mikedld** [comment]
I'm hesitant to accept any new translations until there is a PR for #140. Nothing stops you from adding these translations to [Transifex project](https://www.transifex.com/transmissionbt/transmissionbt/), although it doesn't contain all the phrases right now and will need additional work once things settle.

**Comment by yangjian226200** [comment]
thank you. i will close the issues.
