### ISSUE TITLE
Dedicated Delete Torrent + Data button for Web UI

### ISSUE THREAD

**Issue by mcandre** [transmission/transmission#1674]
The Web UI uses a lot of context menus for important actions. This prevents the Web UI from integrating well with mobile browsers, where the context menu is often unavailable or difficult to trigger and hold open.

Long term, it would be better to move all the context menu elements to left-click elements inside a basic hamburger menu. Also, providing dedicated mobile apps would be useful.

For now, simply adding a new Delete Torrent + Data button would be really helpful. That way, users can free up disk space without resorting to SSH commands.

**Comment by ckerr** [comment]
This is something that's been discussed in the past, and the conclusion then (which I mostly agree with) is that it would make it too easy for users to accidentally delete downloaded content. That's why the 'delete torrent + data' button is intentionally missing.

**Comment by mcandre** [comment]
You would:

* Prevent iOS and iPad users from enjoying basic functions

in order to:

* Protect users from themselves
