### ISSUE TITLE
Font size (Help wanted)

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#1676]
I would love Transmission to have the ability to adjust font size in the main window, to more easily register upload and download values for torrents. They're currently tiny. This is the current squint-state on my MacBook Air. ![Screenshot 2021-08-28 at 3 57 41 PM](https://user-images.githubusercontent.com/69029666/131205610-2e2bd1ab-e579-4e1c-9286-d631bafa1cc5.png)

**Comment by GScottElshaw** [comment]
I am not a coder.
I'm fluent in HTML and some CSS, but that is where my current career lies, and until I finally get my A into G, it is probably where any talent I have will remain. But! I do have a desire to learn, always. So.

My go-to music player is [Cog](https://github.com/losnoco/Cog), it aesthetically appeals, it is tiny code-wise, and it seems complete to me. On MacOS it shares a resemblance to Transmission with its dual panels, and features a clean means of adjusting the font size of the panels. I asked Chris about the code he uses for this and he kindly got back to me a few days ago.

> It's quite simple. Check out the configuration value `fontSize`. And the transformer, `FontSizeToLineHeightTransformer`, which is applied to that value to control the PlaylistView (NSTableView) 's Row Height property.
<

Did i mention i'm not a coder?

Poking around the code, I now have the info that should be in the  Pbxproj file and the libraries for `PlaylistView` and `FontSizetoLineHeightTransformer`.

Where to from here? Aside from my, did i mention not being a coder(?) my limitations are that i'm on a MacBook Air with no room for XCode (sadly XCode still can't be installed on an external volume). I do have time and advanced degrees in literature and French film which means, i guess, i'm litera (what's that word again?) I can read and watch good.

I know @nevack has contributed to Cog, but can anyone else help me wip this into shape for a PR? @fxcoudert @ckerr ?

**Comment by ckerr** [comment]
> I know @nevack has contributed to Cog, but can anyone else help me whip this into shape for a PR? @ckerr ?

Responding as a courtesy, but I'm not really the first person to ask about macOS PRs.

**Comment by GScottElshaw** [comment]
> Responding as a courtesy, but I'm not really the first person to ask about macOS PRs.

Anyone else help me whip this into some kind of shape? @DevilDimon @LaserEyess @Oleg-Chashko

**Comment by DevilDimon** [comment]
Supporting something like this on a long-term basis would require moving away from manual layout. We haven't got that yet, sadly

**Comment by LaserEyess** [comment]
Sorry, I don't use macOS.

**Comment by GScottElshaw** [comment]
> moving away from manual layout

Is this something on the cards? @mikedld @livings124

**Comment by livings124** [comment]
Unfortunately this isn't something planned currently. I'd recommend system-level magnification options in the meantime. Would be neat for Apple to bring Dynamic Type to the Mac and for us to adopt that at some point.

**Comment by GScottElshaw** [comment]
If i understand correctly, there is something that can be done in the interim to allow those two libraries? The unfortunate thing about the system level magnification changes are that they are system wide. I don't require that for any other application, it is just Transmission, alone. I have the peer window open all the time because the font size is larger (i'm using a macbook air).

**Comment by GaryElshaw** [comment]
I was wondering if this is something i could now work on with recent auto-layout changes being made? On a scale of 1 to 10, how feasible is this to do now @DevilDimon @sweetppro?

**Comment by GaryElshaw** [comment]
I can get these to compile fine in cmake by adjusting the lists file. I'm not sure if we just need something as simple as a change in the edit or view menu to include a + and - function or not. It feels a little like progress...

[Font-Size.zip](https://github.com/transmission/transmission/files/9228156/Font-Size.zip)

**Comment by GaryElshaw** [comment]
@DevilDimon Dmitri, is this something we can please look at again before 4.00?

**Comment by ckerr** [comment]
> I would love Transmission to have the ability to adjust font size in the main window, to more easily register upload and download values for torrents. They're currently tiny. This is the current squint-state on my MacBook Air.

Fixed by #4557 :tada:
