### ISSUE TITLE
Icons are blurry on a HiDPI screen for the GTK app

### ISSUE THREAD

**Issue by flipflop97** [transmission/transmission#1684]
When using the GTK 3.0 app on a HiDPI screen with 200% scaling, some icons are blurry and upscaled, instead of sharper bigger versions of the image. This applies to torrent mimetype icons, as well as the bottom bar. See the screenshot for a visual explanation.

![Schermafdruk van 2021-04-29 12-56-40](https://user-images.githubusercontent.com/13943260/116540782-e6a02280-a8ea-11eb-8a2d-ad1d46861d91.png)

**Comment by ckerr** [comment]
Yeap we probably need to move to svgs to make this better.

**Comment by mikedld** [comment]
@flipflop97, please confirm if this is still an issue in current `main`, after switching from `Gdk::Pixbuf` to `Gio::Icon` as part of #3916.

**Comment by flipflop97** [comment]
@mikedld All icons are now sharp in the latest `main` version, thanks!
