### ISSUE TITLE
Remove quitting badge on the macOS icon

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [transmission/transmission#1690]
When one quits Transmission, the dock icon shows a black badge displaying "Quitting". This is standard is no longer used on macOS, no other app I've seen announces its state of quitting like this. It's should be removed.

**Comment by fxcoudert** [comment]
First attempt:

```
diff --git a/macosx/BadgeView.h b/macosx/BadgeView.h
index a0d4fa980..1b6ddb5bf 100644
--- a/macosx/BadgeView.h
+++ b/macosx/BadgeView.h
@@ -14,12 +14,10 @@
 
     CGFloat fDownloadRate;
     CGFloat fUploadRate;
-    BOOL fQuitting;
 }
 
 - (instancetype)initWithLib:(tr_session*)lib;
 
 - (BOOL)setRatesWithDownload:(CGFloat)downloadRate upload:(CGFloat)uploadRate;
-- (void)setQuitting;
 
 @end
diff --git a/macosx/BadgeView.mm b/macosx/BadgeView.mm
index e9746e5b9..b3c00567f 100644
--- a/macosx/BadgeView.mm
+++ b/macosx/BadgeView.mm
@@ -9,7 +9,7 @@
 
 @interface BadgeView (Private)
 
-- (void)badge:(NSImage*)badge string:(NSString*)string atHeight:(CGFloat)height adjustForQuit:(BOOL)quit;
+- (void)badge:(NSImage*)badge string:(NSString*)string atHeight:(CGFloat)height;
 
 @end
 
@@ -23,7 +23,6 @@ - (instancetype)initWithLib:(tr_session*)lib
 
         fDownloadRate = 0.0;
         fUploadRate = 0.0;
-        fQuitting = NO;
     }
     return self;
 }
@@ -41,31 +40,17 @@ - (BOOL)setRatesWithDownload:(CGFloat)downloadRate upload:(CGFloat)uploadRate
     return YES;
 }
 
-- (void)setQuitting
-{
-    fQuitting = YES;
-}
-
 - (void)drawRect:(NSRect)rect
 {
     [NSApp.applicationIconImage drawInRect:rect fromRect:NSZeroRect operation:NSCompositingOperationSourceOver fraction:1.0];
 
-    if (fQuitting)
-    {
-        NSImage* quitBadge = [NSImage imageNamed:@"QuitBadge"];
-        [self badge:quitBadge string:NSLocalizedString(@"Quitting", "Dock Badger -> quit")
-                 atHeight:(NSHeight(rect) - quitBadge.size.height) * 0.5
-            adjustForQuit:YES];
-        return;
-    }
-
     BOOL const upload = fUploadRate >= 0.1;
     BOOL const download = fDownloadRate >= 0.1;
     CGFloat bottom = 0.0;
     if (upload)
     {
         NSImage* uploadBadge = [NSImage imageNamed:@"UploadBadge"];
-        [self badge:uploadBadge string:[NSString stringForSpeedAbbrev:fUploadRate] atHeight:bottom adjustForQuit:NO];
+        [self badge:uploadBadge string:[NSString stringForSpeedAbbrev:fUploadRate] atHeight:bottom];
         if (download)
         {
             bottom += uploadBadge.size.height + BETWEEN_PADDING; //download rate above upload rate
@@ -73,8 +58,7 @@ - (void)drawRect:(NSRect)rect
     }
     if (download)
     {
-        [self badge:[NSImage imageNamed:@"DownloadBadge"] string:[NSString stringForSpeedAbbrev:fDownloadRate] atHeight:bottom
-            adjustForQuit:NO];
+        [self badge:[NSImage imageNamed:@"DownloadBadge"] string:[NSString stringForSpeedAbbrev:fDownloadRate] atHeight:bottom];
     }
 }
 
@@ -82,7 +66,7 @@ - (void)drawRect:(NSRect)rect
 
 @implementation BadgeView (Private)
 
-- (void)badge:(NSImage*)badge string:(NSString*)string atHeight:(CGFloat)height adjustForQuit:(BOOL)quit
+- (void)badge:(NSImage*)badge string:(NSString*)string atHeight:(CGFloat)height
 {
     if (!fAttributes)
     {
@@ -115,7 +99,7 @@ - (void)badge:(NSImage*)badge string:(NSString*)string atHeight:(CGFloat)height
     //string is in center of image
     NSRect stringRect;
     stringRect.origin.x = NSMidX(badgeRect) - stringSize.width * 0.5;
-    stringRect.origin.y = NSMidY(badgeRect) - stringSize.height * 0.5 + (quit ? 2.0 : 1.0); //adjust for shadow, extra for quit
+    stringRect.origin.y = NSMidY(badgeRect) - stringSize.height * 0.5 + 1.0; //adjust for shadow
     stringRect.size = stringSize;
 
     [string drawInRect:stringRect withAttributes:fAttributes];
diff --git a/macosx/Badger.h b/macosx/Badger.h
index b2d63aa67..17752a237 100644
--- a/macosx/Badger.h
+++ b/macosx/Badger.h
@@ -21,6 +21,5 @@
 - (void)addCompletedTorrent:(Torrent*)torrent;
 - (void)removeTorrent:(Torrent*)torrent;
 - (void)clearCompleted;
-- (void)setQuitting;
 
 @end
diff --git a/macosx/Badger.mm b/macosx/Badger.mm
index d934a8590..6c533f2e5 100644
--- a/macosx/Badger.mm
+++ b/macosx/Badger.mm
@@ -69,11 +69,4 @@ - (void)clearCompleted
     }
 }
 
-- (void)setQuitting
-{
-    [self clearCompleted];
-    [(BadgeView*)NSApp.dockTile.contentView setQuitting];
-    [NSApp.dockTile display];
-}
-
 @end
diff --git a/macosx/Controller.mm b/macosx/Controller.mm
index fb5913db9..a0b93d745 100644
--- a/macosx/Controller.mm
+++ b/macosx/Controller.mm
@@ -882,8 +882,6 @@ - (void)applicationWillTerminate:(NSNotification*)notification
         }
     }
 
-    [fBadger setQuitting];
-
     //remove all torrent downloads
     if (fPendingTorrentDownloads)
     {
```

**Comment by ckerr** [comment]
@fxcoudert PR that baby

**Comment by fxcoudert** [comment]
I'll try, but I'm still stuck with the Sparkle issue, which means it's hard to make a clean PR without unrelated Xcode changes.

**Comment by RobFog** [comment]
> Why not make an option to disable the "Quitting" badge? Transmission already gives you options to disable badges for download and upload rates. Leaving a preference option for those who would like the "Quitting" badge is a win-win for people who want it gone and people who don't.

Because adding options for a lot of features makes preferences harder to navigate for users and the code harder to maintain for developers. And this is not a feature that many users will miss, in all likelihood.

**Comment by kakuhen** [comment]
>adding options for a lot of features makes preferences harder to navigate for users
This is adding a single checkbox.

>this is not a feature that many users will miss
Well, the badge is the only thing that makes clear the program is actually quitting as opposed to staying frozen. And with the same logic, we can argue to remove dock badges *in general* as they're all a "thing of the past" and not really present in any "modern" macOS program.

**Comment by fxcoudert** [comment]
> remove dock badges in general as they're all a "thing of the past" and not really present in any "modern" macOS program

<img width="113" alt="Capture d’écran 2022-01-26 à 09 10 37" src="https://user-images.githubusercontent.com/1980544/151126087-d926b934-4605-4bee-aa12-7dd8d8022251.png">

**Comment by GScottElshaw** [comment]
Agreed. The dock has an excellent indicator of whether an application is active or not, and usability suggests, even if you are one of those people who have the dock permanently in place, there are a number of indicators whether an application is unresponsive. Or not.

**Comment by RobFog** [comment]
> > adding options for a lot of features makes preferences harder to navigate for users
> 
> This is adding a single checkbox.

Note that I am not one of Transmission's developers.

I have been following the project for a long time. And if Transmission's maintainers had in fact added "a single checkbox" every time they it was requested we'd probably have 50 or so more checkboxes in Transmission's preferences.

**Comment by GScottElshaw** [comment]
I'm not adverse to 50 preferences, but they should always be in a plist or config file. Having said that? As I said before, _unless_ you have the dock permanently in place, when would you see it?

**Comment by kakuhen** [comment]
> > remove dock badges in general as they're all a "thing of the past" and not really present in any "modern" macOS program
> 
> <img alt="Capture d’écran 2022-01-26 à 09 10 37" width="113" src="https://user-images.githubusercontent.com/1980544/151126087-d926b934-4605-4bee-aa12-7dd8d8022251.png">

I suppose I should have been more clear on my wording. **Custom** dock badges like what Transmission does are highly non-standard. I can only think of the Downloads folder showing a progress bar as the only non-notification-badge dock icon used in modern macOS. If there is an Apple software that uses custom dock badges, then I'm willing to admit I am wrong. But as of now, it seems pretty unusual to make any custom badge, and I'm not sure if the Human Interface Guidelines recommend developers to do this at all.




> And if Transmission's maintainers had in fact added "a single checkbox" every time they it was requested we'd probably have 50 or so more checkboxes in Transmission's preferences.

I agree that feature creep is a real issue, especially for big projects like Transmission. But this only convinces me that now is a perfect opportunity to rethink the custom dock badges Transmission is currently using. For instance, one could argue that you can always open the Transmission window to see your active download/upload rates, so the icon badges that still exist are only a maintenance cost on the developers.
