### ISSUE TITLE
Segfaults in libcurl crashes

### ISSUE THREAD

**Issue by PowerCoder** [transmission/transmission#1695]
Since about two days my Transmission started crashing pretty much every 10 to 20 minutes with the error:
    
`transmission-da: segfault at 18 ip sp error 4 in libcurl.so.4.7.0`

(I took out the memory addresses since they change every time)

It appears to be doing this mostly while at rest. There are no recorded log entries of anything happening before it crashes.

It doesn't appear to happen when there's many active torrents. For example, last night it was online for 3 hours while it was downloading, but crashed soon after. A single torrent downloading at a few kb/s won't stop it though. Nor will clicking on different torrents every few minutes to force it to list the contents.

I'm running Transmission 3.00, Python 3.9.5 and Curl 7.76.1 if it matters.

When it started crashing, the system had been running stable for about two months without being updated, so nothing had changed except the torrents it was offered. I only updated it after thinking that maybe that would be the solution. I also checked my SSD for filesystem errors and it is fine.

It's quite annoying to have to restart it every 20 or so minutes, especially since my knowledge of Linux is limited to certain areas. I can install and maintain my system, but can't write a cron-job to check if Transmission is running and if it isn't to restart it.

**Comment by ckerr** [comment]
Is this still happening in `main`?
