### ISSUE TITLE
Transmission 3.00: torrents with colon in name can not be renamed

### ISSUE THREAD

**Issue by nrebl** [transmission/transmission#1700]
OS: Ubuntu 20.04
Transmission: transmission-daemon 3.00 (bb6b5a062e)

When torrent have ":" symbol in its name - Transmission can download it (with automatic replacement colon -> underscore in real path). But there is no way to rename such torrent name through API. Method "torrent-rename-path" always return "Invalid argument" for such torrents, no matter what to specify in the new name.

This is very annoying.

**Comment by killemov** [comment]
To be clear the replacement of ":" to "_" is done where? (In the interface and propagated throughout or only on the filesystem?)

**Comment by Coeur** [comment]
There is some characters sanitation in a present pull request: #3823
Could that solve the issue?

**Comment by tearfur** [comment]
> There is some characters sanitation in a present pull request: #3823 Could that solve the issue?

Can confirm this is fixed.
