### ISSUE TITLE
Alternative Speed status bar icon is low contrast with dark GTK theme (ex. adwaita-dark)

### ISSUE THREAD

**Issue by nevack** [transmission/transmission#1705]
![image](https://user-images.githubusercontent.com/8330119/119126003-27e3a800-ba3b-11eb-848a-031d0e79fa97.png)

**Comment by bexnoss** [comment]
This was fixed in https://github.com/transmission/transmission/pull/3655 so this issue can be closed.

**Comment by nevack** [comment]
Done! Thanks!
