### ISSUE TITLE
Are torrent ids persistant between runs ?

### ISSUE THREAD

**Issue by stuaxo** [transmission/transmission#171]
Hi,
   Sorry if this is the wrong place to ask this.    I'm using transmission to download assets in a project, and access transmission via its rpc interface (in python via transmissionrpc).

If I store torrent ids then, will they refer to the same files if I run my program later (ie after a reboot / restarting my program / restarting transmission).

?

**Comment by mikedld** [comment]
Please use https://forum.transmissionbt.com/ for support.

To answer your question: no, torrent IDs returned from RPC are not guaranteed to be the same after session restart. You could cache them but only for as long as current `X-Transmission-Session-Id` you use is valid (it expires in [one hour](https://github.com/transmission/transmission/blob/b82f6009dd28e0c93f0380967604183c5629d55d/libtransmission/session-id.c#L27) by default).

**Comment by aannenko** [comment]
Is there any permanent field that could be used as a torrent identifier? Hash probably?

**Comment by ckerr** [comment]
@aannenko yes, the torrent's infohash string is used as a persistent unique key
