### ISSUE TITLE
JSON encoding issue with unicode

### ISSUE THREAD

**Issue by lTimeLordl** [transmission/transmission#1718]
I think the json encoding for unicode is broken on the RPC. For example with the emoji 👊 is encoded as `\u1f44a` instead of `\ud83d\udc4a`. The Surrogate seem to not be used.

When a client decode the json with this unicode, it will decode `\u1f44` instead of `\u1f44a`, so it return `ὄa` instead of `👊`. Tested with Javascript and PHP.

```javascript
JSON.parse('["\u1f44a"]');
> Array [ "ὄa" ]

JSON.parse('["\ud83d\udc4a"]');
> Array [ "👊" ]
```

Transmission 2.94

**Comment by xavery** [comment]
Probably related to https://github.com/transmission/transmission/issues/612

**Comment by ckerr** [comment]
Transmission recently changed to https://github.com/nemtrif/utfcpp for its utf8 encoding/decoding. Since @xavery mentioned above that this issue might've been related to the ConvertUTF code, this may have fixed this issue as a side-effect.

Does this problem persist in the [nightly builds](https://transmissionbt.com/download/)?

**Comment by killemov** [comment]
Is this a recent issue? I have seen Unicode characters being displayed correctly for a long time.

**Comment by lTimeLordl** [comment]
I haven't tested the [nightly builds](https://transmissionbt.com/download/) or 3.0 yet but this issue was confirmed in version 2.94

I will try to make test with weekend on the nightly build.

**Comment by killemov** [comment]
And you are sure it worked before 2.94? (That's what I meant before.)

**Comment by lTimeLordl** [comment]
Sorry, I read your message to fastly, I don't know the behavior before 2.94

**Comment by ckerr** [comment]
> Does this problem persist in the [nightly builds](https://transmissionbt.com/download/)?

**Comment by msg7086** [comment]
I didn't try nightly builds, but I added a test case to json-test and it failed the test with emoji.

```C
in = R"({ "key": "\ud83c\udf65" })"sv;
EXPECT_TRUE(tr_variantFromBuf(&top, TR_VARIANT_PARSE_JSON | TR_VARIANT_PARSE_INPLACE, in));
EXPECT_TRUE(tr_variantIsDict(&top));
EXPECT_TRUE(tr_variantDictFindStrView(&top, key, &sv));
EXPECT_EQ("🍥"sv, sv);
json = tr_variantToStr(&top, TR_VARIANT_FMT_JSON);
tr_variantClear(&top);

EXPECT_FALSE(std::empty(json));
EXPECT_NE(std::string::npos, json.find("\\ud83c"));
EXPECT_NE(std::string::npos, json.find("\\udf65"));
EXPECT_TRUE(tr_variantFromBuf(&top, TR_VARIANT_PARSE_JSON | TR_VARIANT_PARSE_INPLACE, json));
EXPECT_TRUE(tr_variantIsDict(&top));
EXPECT_TRUE(tr_variantDictFindStrView(&top, key, &sv));
EXPECT_EQ("🍥"sv, sv);
tr_variantClear(&top);
```

Sample emoji took from https://www.compart.com/en/unicode/U+1F365.

**Comment by BoringCat** [comment]
Try nightly builds transmission-4.0.0-beta.3.dev+r3c11b36bc3. Problem persisted.

![image](https://user-images.githubusercontent.com/25497484/216651905-aa1b203d-63df-4ebf-8c94-77e44060071e.png)

build cmd:
```sh
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_DAEMON=ON -DENABLE_GTK=OFF -DENABLE_QT=OFF -DENABLE_MAC=OFF -DENABLE_WEB=ON -DENABLE_CLI=ON ..
make -j12
```

run cmd:
```sh
env TRANSMISSION_WEB_HOME=$PWD/web/public_html ./daemon/transmission-daemon -g config -f
```

<details><summary>system infomation</summary><pre>OS: Debian
Kernel: x86_64 Linux 5.15.79.1-microsoft-standard-WSL2
Uptime: 2h 28m
Packages: 873
Shell: zsh 5.7.1
WM: Not Found
###########
npm version
{
  npm: '8.19.3',
  node: '14.21.2',
  v8: '8.4.371.23-node.88',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.6',
  openssl: '1.1.1s',
  cldr: '40.0',
  icu: '70.1',
  tz: '2022f',
  unicode: '14.0'
}
###########
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)</pre></details>

**Comment by killemov** [comment]
I vaguely recall something about UTF-16 and something in [a Star Overflow answer](https://stackoverflow.com/a/27415982). Maybe this helps.

**Comment by lTimeLordl** [comment]
Just tested and this issue has been fixed, thanks @xavery!
