### ISSUE TITLE
transmission-cli is excessively verbose and chatty

### ISSUE THREAD

**Issue by gnarlin** [transmission/transmission#1719]
Can we please get a --verbose 0-5 setting (with 0 being no output) for transmission-cli?
There is frankly an excessive level of verbosity and technical output that's usually not needed.

**Comment by xavery** [comment]
`transmission-cli` is in total maintenance mode and its functionality has been almost entirely replaced by `transmission-remote`, so I wouldn't get my hopes up.

**Comment by gnarlin** [comment]
But doesn't transmission-remote serve a different purpose? Isn't it only a command line remote for the full GUI suit? What I really need is a wget like program but for bittorrent, preferably one that isn't so endlessly forthcoming with it's verbiage.

**Comment by xavery** [comment]
Sounds like [aria2](https://github.com/aria2/aria2) is something you'd find more suitable.

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/issues/1992 is a superset of this bug; would fix it for both transmission-cli and transmission-daemon
