### ISSUE TITLE
[Feature request] Show when a torrent was added in "Torrent Properties" window

### ISSUE THREAD

**Issue by rybak** [transmission/transmission#1729]
As of Transmission 2.94, the "Information" tab of the "Torrent Properties" window shows the following:

- Activity
  - Have: bytes/%
  - Availability: %
  - Uploaded: bytes
  - Downloaded: bytes
  - State
  - Running time: n days, m hours
  - Last activity
  - Error
- Details
  - Size
  - Location
  - Hash
  - Privacy
  - Origin
  - Comment

It would be nice, if the "Information" tab of the "Torrent Properties" window also showed _when_ a particular torrent was added to Transmission. Since there is "View > Sort by Age", I assume that Transmission stores some kind of information regarding when a torrent was added.

Thanks.

**Comment by sewe2000** [comment]
I've added this feature in my fork of transmission in the qt version. I'll create a pull request
