### ISSUE TITLE
Transmission on Apple Silicon Chip

### ISSUE THREAD

**Issue by Zeroscl** [transmission/transmission#1738]
Is there a possibility that there is an ARM version to be native in the Apple Silicon Chip?  and you don't have to use rosseta 2 for your "translation"?  Thanks

**Comment by Arnav-arw** [comment]
I made a M1 optimized version a while back. Here you go: https://we.tl/t-MClFmsspCN

**Comment by Zeroscl** [comment]
Thank you very much, how weird, I couldn't find it on the GitHUB page. 

Thanks again

**Comment by rstolpe** [comment]
> I made a M1 optimized version a while back. Here you go: https://we.tl/t-MClFmsspCN

The link don't work can you give it again?

Are you keeping your m1 version updated?

**Comment by Arnav-arw** [comment]
> The link don't work can you give it again?

Here you go: https://drive.google.com/file/d/15dtZjG-MbqB5dpYn19fpMd5T7Vym1Bz8/view?usp=sharing

> Are you keeping your m1 version updated?

No sorry right now I have my exam. I will definitely do that after it.

**Comment by rstolpe** [comment]
> > The link don't work can you give it again?
> 
> Here you go: https://drive.google.com/file/d/15dtZjG-MbqB5dpYn19fpMd5T7Vym1Bz8/view?usp=sharing
> 
> > Are you keeping your m1 version updated?
> 
> No sorry right now I have my exam. I will definitely do that after it.
> 
> Edit: I just checked Transmission hasn't been updated since May 2020 so I have the latest version only.

Perfect, you can open a new GIT repo for it also if you want so people can help you with it :)
