### ISSUE TITLE
Bad behaviour when transmission-remote authentication fails

### ISSUE THREAD

**Issue by sebastian-king** [transmission/transmission#174]
When `transmission-remote`'s authentication fails its output is very peculiar, it looks to me like something is being interpreted as a carriage return or a strange encoding type.

Example behaviour which can be replicated easily:
The bytes following `Unauthorized User` cause problems.

```console
% transmission-remote 127.0.0.1:9091 --auth=a:b -t 000000000000000000000000000000000000000 --stop
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userion: Basic YTpi
User-Agent: transmission-remote/2.84 (14307)
Accept: */*
Accept-Encoding: deflate, gzip

% transmission-remote 127.0.0.1:9091 --auth=aa:bb -t 000000000000000000000000000000000000000 --stop
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userion: Basic YWE6YmI=
User-Agent: transmission-remote/2.84 (14307)
Accept: */*
Accept-Encoding: deflate, gzip

% transmission-remote 127.0.0.1:9091 --auth=aaa:bbb -t 000000000000000000000000000000000000000 --stop
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userion: Basic YWFhOmJiYg==
User-Agent: transmission-remote/2.84 (14307)
Accept: */*
Accept-Encoding: deflate, gzip
```

This causes problems when programataically working with Transmission and it outputs these bytes as it interferes with my terminal, especially if `head -n 1` is used then it sometimes overwrites my newlines.

**Comment by cfpp2p** [comment]
> The bytes following Unauthorized User cause problems.

This was reproducible for me.
https://github.com/transmission/transmission/pull/500 fixed it.

The extra characters appear to be buffer leftovers from the previous http post commands.
