### ISSUE TITLE
Open in file manager starts VSCode

### ISSUE THREAD

**Issue by lil5** [transmission/transmission#1741]
### Steps 

- I right click on a torrent
- Click on the option "open folder"

### Expected 

Opens my default file manager using defaults set by xdg mime: "inode/directory"

### Actual result 

Opens vscode.

---

I know I should be confer with vscode devs but this only happens to me with Transmission. Other applications open my default file manager fine.

**Comment by lil5** [comment]
https://github.com/transmission/transmission/blob/143c5f538113bba2649b3052e0a5d77946a47278/gtk/Application.cc#L1466-L1469

**Comment by lil5** [comment]
I fixed this by;
1. Right clicking a folder in my file manager (Thunar)
2. Enter the `Open With` sub-menu
3. Click on `Open With Other Application...`
4. A window pops up asking you to choose from a list of applications
5. Select your file manager
6. Check `Use as default for this kind of file`
7. Click `Open`

**Comment by andresti** [comment]
@lil5 thanks, your fix worked for me
