### ISSUE TITLE
Transmission ignores edited settings.json

### ISSUE THREAD

**Issue by MSS00** [transmission/transmission#1752]
I wanted to disable whitelist, so I

1. Stopped transmission-daemon via `systemctl stop transmission-daemon`
2. Went to `/etc/transmission-daemon`
3. Edited settings.json
4. Saved changes
5. Started daemon

But I still get 403, when I'm trying to access client with browser.
What do I do?
Also, even on local machine, where transmission is running I can't start downloading getting error `Couldn't connect to server`.

Transmission is running at Debian 10 server.

**Comment by pmarsden** [comment]
Transmission rather obviously doesnt ignore settings.json.
Since you have provided no actual details its impossible to know what the issue might be.
Perhaps you are editing the wrong file, or perhaps what you are editing isnt doing what you expect/want.

**Comment by MSS00** [comment]
So I wanted to disable `rpc-whitelist`. I disabled transmission-daemon with `systemctl stop transmission-daemon`. I've went to `/etc/transmission-daemon/` and opened `settings.json` in nano.
I've found `rpc-whitelist` and set it's value to false. I've saved all changes and enabled transmission-daemon again with `systemctl start transmission-daemon`. All of those commands were issued with root privilegies. And I still get HTTP 403 error.
Transmission-daemon is running on Debian 10 Buster.
And I've tried to access it from Windows machine from Chromium browser.
Maybe there's problem with Pi-hole running on the same server as Transmission.
If not, what details I need to provide?

**Comment by pmarsden** [comment]
I have no idea what Pi-Hole is, so I cannot comment on that.
While Transmission is running, edit the value of rpc-whitelist to '0' and save it.
Then stop Transmission and check the file. If its still '0' (i.e. not overwritten) then its not using that settings file.
(Its using one somewhere else, so search your system for settings.json).

**Comment by MSS00** [comment]
I changed value of `rpc-whitelist` to 0, saved it and stopped `transmission-daemon`. Settings file got overwritten to `rpc-whitelish = false;`. Then I started it and tried to connect to it. Now I get 401 error Unauthorized User. It asks me login and password. I entered root login and password and it didn't worked.

**Comment by MSS00** [comment]
Nevermind, I resolved issue by entering `transmission` to both login and password. I don't know why it didn't worked earlier.
