### ISSUE TITLE
More of one year without releases

### ISSUE THREAD

**Issue by Ahton89** [transmission/transmission#1766]
I'm sorry, but there have been no releases for over a year. During this time, for example, the same Apple Silicon is used by the peoples in all and in general for a year and a sea of new dependencies and bug fixes in libraries, fixing vulnerabilities, etc. It's not funny anymore, I can understand being busy, business, problems - but a year, a YEAR without a single release is epic. When new release?

**Comment by mikedld** [comment]
See #1711.
