### ISSUE TITLE
WebTorrent Peer ID not recognized

### ISSUE THREAD

**Issue by duramato** [transmission/transmission#1767]
The Peer ID for webtorrent is not recognized. 
For example: `-WW0088-`, this should be `WebTorrent 0.98`

Transmission 3.00

![image](https://user-images.githubusercontent.com/10121067/130962085-cc69c34a-70ee-4c38-b688-b48fbc322139.png)

**Comment by polarathene** [comment]
AFAIK Transmission doesn't support WebTorrent yet.

The `libtorrent` backend has support for it in 2.x but this has yet to be released (_no mention of WebTorrent in any 2.x changelog yet_), there's a relevant [tracking issue for Transmission here](https://github.com/transmission/transmission/issues/47).

**Comment by ckerr** [comment]
Fixed in 02897f7397c791e39ed9c06a922066dd6ce64bf6
