### ISSUE TITLE
Enable external access?

### ISSUE THREAD

**Issue by chascos69** [transmission/transmission#1768]
Hello

How i can enable external  access? Y put my  host in :
#- HOST_WHITELIST=XXXX.duckdns.org #optional
but have 403 forbidden

Internal works with: - WHITELIST=127.0.0.1,192.168.*.* #optional
I open/forward 9091 port in router

Somewhere i read: "connect to my server and run this command : transmission-daemon -p 9091 -f -T -a 192.168.2.4". How i can connect to server?
Thx

**Comment by ckerr** [comment]
Please use https://forum.transmissionbt.com/ or other forums for support questions. This issue tracker is for tracking bug reports and feature requests. Thank you!
