### ISSUE TITLE
Bump Website (C) marking to 2017

### ISSUE THREAD

**Issue by 927589452** [transmission/transmission#177]
That should be updated shouldn't it ?
Could probably do it wanted.

**Comment by 927589452** [comment]
Could not find Website Source here, so not relevant

**Comment by mikedld** [comment]
Changes to transmissionbt.com site could be made in [transmission/transmission.github.io](/transmission/transmission.github.io) repository. This specific change should go into [includes/html/footer.html](/transmission/transmission.github.io/blob/master/includes/html/footer.html).
