### ISSUE TITLE
Quitting Transmission does not send announce to tracker

### ISSUE THREAD

**Issue by dominikh** [transmission/transmission#1772]
When quitting Transmission with active torrents, no event=stopped announce is being sent to the tracker.

Steps to reproduce:
- Capture network traffic
- Run Transmission
- Have an active torrent
- Quit transmission – either via File->Quit or via ^C
- Notice no final announce being sent

When quitting, Transmission does display the "Closing connections" dialog, but no announce seems to make it across the wire.

I've attached a packet capture of opening Transmission, waiting for the event=started announce, then closing Transmission: [transmission.pcapng.gz](https://github.com/transmission/transmission/files/7081331/transmission.pcapng.gz)

I'm not 100% confident in my Wireshark skills, but I've also observed that various trackers would keep my client around as a peer after closing it.

System information:
```
OS: Linux, NixOS unstable

$ transmission-gtk --version
transmission-gtk 3.00 (0)

$ uname -a    
Linux chulak 5.10.57 #1-NixOS SMP Sun Aug 8 07:05:24 UTC 2021 x86_64 GNU/Linux
```

**Comment by andreygursky** [comment]
Looks like a dup of #196.

**Comment by dominikh** [comment]
You're right.
