### ISSUE TITLE
transmission-daemon does not launch correctly when using systemd

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#178]
Hello,
as reported in Debian as http://bugs.debian.org/854856:

> it appears the systemd service file for transmission-daemon does not pass a configuration directory when launching the daemon, which will try to use its home directory /home/transmission-daemon, which doesn't exist and cannot be created.
>
> The old init.d file sourced /etc/default/transmission-daemon which defaulted the configuration directory to /var/lib/transmission-daemon/info

could you have a look at this? thanks!

**Comment by mikedld** [comment]
I'm a bit confused. Looking into [transmission_2.92-2.debian.tar.xz](http://http.debian.net/debian/pool/main/t/transmission/transmission_2.92-2.debian.tar.xz), and transmission-daemon.postinst in particular, debian-transmission user should have a home directory of "/var/lib/transmission-daemon", not "/home/transmission-daemon".

And then, different distributions use different default configuration directories for the daemon (e.g. Gentoo uses "/var/lib/transmission/config"). How do you propose we fix this?..

**Comment by mikedld** [comment]
Closing for the lack of response.

**Comment by Scondo** [comment]
transmission-daemon.postinst have no way to fix already present ` transmission-daemon` user.

So this will be common bug with update from 2.84 when homedir changed.
