### ISSUE TITLE
cmake ENABLE_WEB is not used

### ISSUE THREAD

**Issue by Bluewind** [transmission/transmission#1790]
```
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_WEB
```

This appears to be only mentioned in the option list, but nowhere else. https://github.com/transmission/transmission/blob/a459e5e11b2d2524b649f7487368de30c8d2af21/CMakeLists.txt#L24

Should this variable even exist or has it simply not been implemented yet?

**Comment by mikedld** [comment]
Looks like a false-positive, it's used here: https://github.com/transmission/transmission/blob/a459e5e11b2d2524b649f7487368de30c8d2af21/CMakeLists.txt#L647-L655

**Comment by Bluewind** [comment]
I'm sorry, my bad. I'm actually building version 3.00 and it looks like that code is not yet present there. It was added by https://github.com/transmission/transmission/commit/cd453764b15ee77caaa88867e33b46269bb8b314.

Guess I'll have to wait for the next release. Thank you!
