### ISSUE TITLE
Error downloading torrent with extra backslash in path on Windows

### ISSUE THREAD

**Issue by depler** [transmission/transmission#1791]
Transmission for windows has a bug with folders path ending with backslash. If you put download into folder like `C:\Torrents` it will run ok, but path `C:\Torrents\` (with ending backslash) will fail. The error looks like:

`Couldn't create "C:\Torrents\/Subfolder": The filename, directory name, or volume label syntax is incorrect. (c:\Data\Sources\transmission\code\fdlimit.c:174)
`

This is what happens inside, error code 123 after calling `SHCreateDirectoryExW`:
![image](https://user-images.githubusercontent.com/13541699/132984361-bd1cff79-e590-49d8-82a6-90627f411c05.png)

**Comment by depler** [comment]
Better approach: https://github.com/depler/transmission/commit/0d4b43901bef1b04213dbe6a3aa1d804dfd566aa

**Comment by depler** [comment]
Better approach: https://github.com/depler/transmission/commit/0d4b43901bef1b04213dbe6a3aa1d804dfd566aa

**Comment by depler** [comment]
Better approach: https://github.com/depler/transmission/commit/a36e21bd4c97c36516fc154a1ebb573bf4df9529

**Comment by Pentaphon** [comment]
Transmission for Windows is still just an early preview and has a lot of bugs that have yet to be acknowledged. Even the installer is asking for Firefox to be closed before proceeding which is scaring some users off.

**Comment by depler** [comment]
@ckerr, there is cross platform implementanon of `std:: filesystem' implemented as couple of header files: https://github.com/gulrak/filesystem

It seems suitable replace obsolete platform-dependent code in `file-xx.cc` files. What do you think?

**Comment by Pentaphon** [comment]
I think you should just do what transmission-daemon-cygwin does which is just put a download folder in the transmission folder when it first runs to make it totally portable and keep everything in one folder by default while still letting people change it in the ini file if they want to.
