### ISSUE TITLE
Compiling libtransmission separately, plus problematic building procedure report

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#1795]
Greetings everyone,

I hope you are doing well.

I've just read the HN article and got thrilled as I'm using transmission (QT) as my client of choice.

~~My question is: which C++ standard do you use?~~ Nevermind; I have found it's C++17, at least that is what is included in CMake files and XCode configuration settings.

Also, can I compile libtransmission separately from the entire project? I'm under GNU / Linux Debian testing 64-bit.

I would be interested in playing locally for fun.

P.S.: which parts do you plan to refactor exactly, the entire C code base or specific parts of it so the code can be compatible with C++ and the rest will remain as is? Please advice.

**Comment by stefanos82** [comment]
It seems it assumes I use Clang and it breaks upon `make` command.

![image](https://user-images.githubusercontent.com/1777466/133006931-0eea5d56-fe6d-40b9-aae5-51e684ec299f.png)

**Comment by stefanos82** [comment]
OK, I have managed to get some progress.

I had to export `CC` and `CXX` to `clang` and `clang++` respectively; then I had to pass the C++ flag `-stdlib=libc++` as it's necessary for Clang to work (under Linux): 

```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebIno -DCMAKE_CXX_FLAGS="-stdlib=libc++" ..
```

Unfortunately it breaks right before the end...

![image](https://user-images.githubusercontent.com/1777466/133011498-3ce520ca-aaed-41c9-bc84-8acb71eb6b1a.png)

**Comment by stefanos82** [comment]
OK, further progress.

I have managed to build transmission with `ninja transmission` but when I run `ninja libtransmission-test` I get the following error:

![image](https://user-images.githubusercontent.com/1777466/133122032-efefb37a-b8d5-42ab-bb1d-e37f5f3bbdc2.png)

**Comment by mikedld** [comment]
I don't know what version of it you have, but enabling clang-tidy (which is happening by default) doesn't seem to work for you, so pull the latest master if you don't have changes from #1792 yet and configure with `-DRUN_CLANG_TIDY=OFF`. You should also be able to use GCC, there's no requirement for Clang (apart from clang-tidy which is optional since a few PRs ago). Hope it works out.

**Comment by stefanos82** [comment]
It was indeed the clang-tidy the issue; with the flag you have suggested it builds just fine, thank you for the help with this issue.

Now about the parts of refactoring, is there anything I should know before I start experimenting locally?

**Comment by stefanos82** [comment]
> I don't know what version of it you have, but enabling clang-tidy (which is happening by default) doesn't seem to work for you, so pull the latest master if you don't have changes from #1792 yet and configure with `-DRUN_CLANG_TIDY=OFF`. You should also be able to use GCC, there's no requirement for Clang (apart from clang-tidy which is optional since a few PRs ago). Hope it works out.

Also, can you let the users know that a hook is placed within their `.git/hooks/pre-commit` that executes `clang tidy` with every commit of theirs?

I had a local branch and would break my commit every time I attempt to push; I had to comment it out to be able to work.

**Comment by stefanos82** [comment]
> I don't know what version of it you have, but enabling clang-tidy (which is happening by default) doesn't seem to work for you, so pull the latest master if you don't have changes from #1792 yet and configure with `-DRUN_CLANG_TIDY=OFF`.

```
stefanos@debian:~/development/Transmission/build [master]$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 11.0.1
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell
```

Is it considered an outdated version? I would like to make the building process to work right out of the box, so to speak, if possible.

Any advice @mikedld ?

**Comment by mikedld** [comment]
The version we're using at the moment is 12.x (12.0.1), which is also the latest stable and latest one available at https://releases.llvm.org/download.html. When 13.x gets released, we're likely to switch to it, with [potentially] a slight delay but still ASAP. If for some reason you cannot keep up and install this version (using your package manager, including via PPAs and the like), using Docker image is probably the easiest next option.

**Comment by stefanos82** [comment]
> The version we're using at the moment is 12.x (12.0.1), which is also the latest stable and latest one available at https://releases.llvm.org/download.html. When 13.x gets released, we're likely to switch to it, with [potentially] a slight delay but still ASAP. If for some reason you cannot keep up and install this version (using your package manager, including via PPAs and the like), using Docker image is probably the easiest next option.

Ah I see...bummer, I'm using GNU / Linux Debian testing 64-bit and it delays with bleeding edge stuff, which is good from a security perspective; it gives them time to test and patch insecure code.

On the other hand, I could go with Docker, but I have tried it and it's not my thing...

I will just keep the clang-tidy disabled with the flag you have suggested in the first place.

Thanks again.
