### ISSUE TITLE
unreachable default case

### ISSUE THREAD

**Issue by viennadd** [transmission/transmission#181]
the default case in function `tr_variant_string_get_string` [variant.c#L160](https://github.com/transmission/transmission/blob/master/libtransmission/variant.c#L160) seems unreachable, since str->type only will be assigned in `tr_variant_string_set_quark` and `tr_variant_string_set_string`. 

Regards,
Alex

**Comment by mikedld** [comment]
Defaults cases are there to protect against destructive future modifications. You either have it, or you initialize `ret` with default `NULL` value on declaration, the latter being suboptimal as it leads to two assignments in most cases. But you never leave `ret` uninitialized ;)
