### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by JacquesLG** [transmission/transmission#182]
Hello,

I was wondering if you could support the WebRTC protocol. On the web torrent.io FAQ (https://webtorrent.io/faq) it says:

> This should make it easy for existing popular torrent clients like Transmission, and uTorrent to add support for WebTorrent.

So yeah if you could add WebRTC you would be the best ;)

Thanks have a nice day,
Jacques

**Comment by mikedld** [comment]
Please search for existing issues before opening new ones. See #47.
