### ISSUE TITLE
strip trailing whitespace from magnet links

### ISSUE THREAD

**Issue by cmyr** [transmission/transmission#1820]
I generally add magnet links via copy/paste, and I often accidentally copy trailing whitespace, which fails with the following fairly unhelpful error:

<img width="532" alt="Screen Shot 2021-09-18 at 7 05 55 PM" src="https://user-images.githubusercontent.com/3330916/133910705-c6350694-51ee-456d-802c-b9eab394ae4f.png">

Unless there is some rationale I'm overlooking, it should be easy enough to just strip any leading/trailing whitespace before attempting to parse the link?

If this is desirable I would be happy to try and put a patch together, although if an existing contributor or maintainer wanted to make this fix that would be welcome!

thanks for the useful software!

**Comment by killemov** [comment]
A simple regular expression should be used to sanitize any URL. See torrentRegexp in https://github.com/killemov/Shift/blob/e32e0f9883d8443aaf90be94efbdf1c84b0d8681/shift.js#L532

**Comment by cmyr** [comment]
I'm running transmission `3.00 (f4489c982e)` on macos `12.3.1 (21E258)`, and pasting a magnet link that includes a trailing newline does not trim the newline.

I'm curious as to why you think the system should be trimming the newline for me? I would not expect this behaviour, and I am able to select & copy trailing newlines in a variety of contexts (although it's important to extend the selection down to the start of the next line, the newline is not included if you just select to the *end* of a line)

**Comment by Coeur** [comment]
OK, I'm exactly on macos 12.3.1 (21E258) too. I put the link you gave in your screenshot in the pasteboard, with a newline at the end:
```
echo "magnet:?xt=urn:btih:a2b806846cd5c638e609ca665a764db153bb63bf\n" | pbcopy
```
When I paste it in Transmission, the newline is removed here:
https://github.com/transmission/transmission/blob/70fbce71ec0d5511a2588b0fe438ffba59be12cb/macosx/TorrentTableView.mm#L643

So such issue was already resolved by 8392476 6.5 years ago.

You'd need to be clearer on how you reproduce your issue precisely. Maybe a video?

**Comment by cmyr** [comment]
@Coeur just to be clear, when you paste this into transmission (<kbd>cmd</kbd>+<kbd>U</kbd> to bring up the 'Open torrent address' window, then paste) do you not see an error dialog?

**Comment by Coeur** [comment]
I didn't know about cmd+U, I was doing cmd+V directly.
Let me investigate it.
