### ISSUE TITLE
high cpu usage when setting a download limit rate on webseed torrents

### ISSUE THREAD

**Issue by bmorel** [transmission/transmission#1829]
Running Debian 11, amd64 arch, no DE, no dbus, no systemd (those infos are for some context, it is very likely unrelated, but I've seen situations in which that kind of setup triggers performance bugs, and it's also a rather uncommon configuration).
Using either of: transmission-qt (3.00 (bb6b5a062e)), same version of transmission-gtk, tried to downgrade both to debian 10's packages: 2.94-2+deb10u2

When setting download limits, transmission maxes the usage of a single core, as can be seen with e.g. xosview or top.

I have a google-perftools4 analysis of transmission-qt 3.00 here: [transmission-qt.profile.pdf](https://github.com/transmission/transmission/files/7218069/transmission-qt.profile.pdf)

In practice, this makes transmission unusable since when not limited, it makes it very uncomfortable to use any other internet related application.

**Comment by bmorel** [comment]
Considering the in-progress port to C++, this is likely this issue will be ignored and close (see #1840, #701), so I'm unsubscribing, since any further discussion on that kind of topic will likely be only for the next, rewrote, version (thus, unrelated to this). I'll just search for a client which works and is not a resource burner in the meantime.

**Comment by ckerr** [comment]
confirmed for webseeds -- the code that we use to pause and then resume curl tasks appears to be putting a lot of load on curl's internals.

`CURLOPT_MAX_RECV_SPEED_LARGE` may be a better way to do this

**Comment by bmorel** [comment]
Heh... wow thanks I was a bad mouth on this (upstream rewriting, thus not caring), sorry and thanks for the work!
