### ISSUE TITLE
add the ability to set max # of active torrents in web client

### ISSUE THREAD

**Issue by skydoy** [transmission/transmission#185]
Hello, I´m new here

I would like to purpose to have some features in web interface like controlling the number of transfers limit to a number on my choosing would it be possible?

I´m using a jail in freenas with transmission, i would like to have more control

Thanks

**Comment by ckerr** [comment]
The web client in the [nightly builds](https://transmissionbt.com/) has the ability to set how many torrents can be downloaded concurrently, in Prefs > Download queue size
