### ISSUE TITLE
Update broke transmisson daemon

### ISSUE THREAD

**Issue by mariothiel** [transmission/transmission#187]
I just ran apt upgrade today and the latest transmission update broke at install.

```
Setting up transmission-daemon (2.92-1ubuntu1~16.10.1) ...
Job for transmission-daemon.service failed because the control process exited with error code. See "systemctl status transmission-daemon.service" and "journalctl -xe" for details.
invoke-rc.d: initscript transmission-daemon, action "start" failed.
dpkg: error processing package transmission-daemon (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 transmission-daemon
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any idea what I can do to fix that?

**Comment by erikjoens** [comment]
set your correct transmission user in /lib/systemd/system/transmission-daemon.service

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. When you do, provide more information, in particular the output of `systemctl status transmission-daemon.service` and `journalctl -xe` as the error message suggests. You might also get more help on Ubuntu-related internet resources.

**Comment by yuriw** [comment]
was any solution recommended ?
