### ISSUE TITLE
Possible UAF under multi-threading

### ISSUE THREAD

**Issue by viennadd** [transmission/transmission#188]
In [platform.c#L127](https://github.com/transmission/transmission/blob/master/libtransmission/platform.c#L127) 
 ```c
  pthread_create (&t->thread, NULL, (void* (*)(void*))ThreadFunc, t);
  pthread_detach (t->thread);
```

and the implementation of ThreadFunc
```c
ThreadFunc (void * _t)
{
  tr_thread * t = _t;

  t->func (t->arg);

  tr_free (t);
  .....
}
```

Could `t` be freed in `ThreadFunc` before `t`  passed into `pthread_detach` ? (don't sure it is possible in reality)
Would it be safer if  `pthread_detach` called inside the new created routine:
```c
ThreadFunc (void * _t)
{
   pthread_detach(pthread_self());
   ......
```

**Comment by cfpp2p** [comment]
it's just to make sure all the thread resources are released

**Comment by mikedld** [comment]
Fixed, thanks!

**Comment by cfpp2p** [comment]
> Could `t` be freed in `ThreadFunc` before `t` passed into `pthread_detach` ?

In `ThreadFunc` `t` is correctly freed. `tr_free (t)` deallocates just the structure `t` (`tr_thread * t = _t`). Not any of `t` members (and not `_t` or indirectly `_t` members either) are freed. see  [TRAC-2756](https://trac.transmissionbt.com/ticket/2756#comment:2)

**Comment by viennadd** [comment]
@cfpp2p if structure `t` is deallocated, then we couldn't assure what data  that address `t` would points to (freed block might be allocated to other usage in other threads, still, that execution path might be impossible, just to be safe)

**Comment by cfpp2p** [comment]
@viennadd    Thanks!, got it.
