### ISSUE TITLE
Artifacts, the upper frame of the selection window is not visible

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#1891]
- macOS Big Sur: v.11.6 (20G165)
- Transmission: 3.00+6b7f2f9e53

Artifacts on the right and left, the upper frame of the selection window is not visible.

<img width="708" alt="Screen Shot 2021-10-25 at 22 32 02" src="https://user-images.githubusercontent.com/62497891/138767018-7ac05725-f00b-44c1-8824-95b1adbcf46a.png">

<img width="542" alt="Screen Shot 2021-10-25 at 22 32 43" src="https://user-images.githubusercontent.com/62497891/138767021-166e6cf0-7261-4a21-9efc-0d6f53913c42.png">

**Comment by Oleg-Chashko** [comment]
The same problem:
<img width="838" alt="Screen Shot 2021-10-08 at 13 39 53" src="https://user-images.githubusercontent.com/62497891/136554130-469ec705-ecdd-44e0-88eb-ecb557f410df.png">

**Comment by sweetppro** [comment]
@Oleg-Chashko Ive fixed these issues in https://github.com/transmission/transmission/pull/3205,
however I think the top highlight missing in the first tracker cell seems to be a default macOS bug/feature as iv'e also noticed that also happening in other macOS apps

**Comment by Oleg-Chashko** [comment]
@sweetppro 
Thank you, for your time and for fixes the issues. 👍🏻

**Comment by ckerr** [comment]
Fixed by #3205
