### ISSUE TITLE
[Question] Download folder

### ISSUE THREAD

**Issue by zecaloteiro** [transmission/transmission#194]
Why is always added "C:\" on the folder of new downloads even when in the configuration there's a path like "/share/Multimedia/" ??

![image](https://cloud.githubusercontent.com/assets/7022211/23275177/3a964c94-f9e4-11e6-9869-49f7b52edd88.png)

![image](https://cloud.githubusercontent.com/assets/7022211/23275185/4664b164-f9e4-11e6-8e9b-d5666e210d49.png)

**Comment by mikedld** [comment]
Related to [TRAC-6129](https://trac.transmissionbt.com/ticket/6129). Should be fixed with f6a19f868a12884bffb66018d056cb21d51aa4c9, please try latest [nightly build](https://build.transmissionbt.com/job/trunk-win32/).

**Comment by mikedld** [comment]
Reopen if still valid.
