### ISSUE TITLE
document how users can disable systemd NoNewPrivileges setting on their local installs

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#1951]
Hello,
as reported in Debian at http://bugs.debian.org/996433

```
After upgrading to Debian 11, I found that Transmission stopped sending
me emails about finished torrents. I did a bunch of troubleshooting and
ensured that Transmission is properly executing the completed torrent
script. I also saw that Exim still otherwise works, and can even send
email as the debian-transmission user after su-ing to this user. I even
did a fresh debian install on another machine and did the bare minimum
configuration to get both exim4 and transmission set up on it; I
witnessed the same exact error.

My smaller test script is a simple one-liner:
echo "Torrent Completed: $TR_TORRENT_NAME" | mail -s "Torrent Completed" ADDRESS > /etc/transmission-daemon/mailout 2> /etc/transmission-daemon/mailerr

mailout is empty while mailerr is:
mail: cannot send message: Process exited with a non-zero status
mail: Cannot open file /var/lib/transmission-daemon/dead.letter: Permission denied

It seems that this bug is caused by this change in Transmission: https://github.com/transmission/transmission/pull/795
After changing my
/etc/systemd/system/multi-user.target.wants/transmission-daemon.service
to read "NoNewPrivileges=false" instead of true and reloading the
service and daemon, I find that transmission is properly sending emails
again.
```

Can you look into this? thanks!

**Comment by ckerr** [comment]
Hmm I kind of think `NoNewPrivileges=true` is the right default value.

I'm not an expert on systemd but I do notice there are exceptions to the `NoNewPrivileges` setting:

> Takes a boolean argument. If true, ensures that the service process and all its children can never gain new privileges through execve() (e.g. via setuid or setgid bits, or filesystem capabilities). This is the simplest and most effective way to ensure that a process and its children can never elevate privileges again. Defaults to false, but certain settings override this and ignore the value of this setting. This is the case when DynamicUser=, LockPersonality=, MemoryDenyWriteExecute=, PrivateDevices=, ProtectClock=, ProtectHostname=, ProtectKernelLogs=, ProtectKernelModules=, ProtectKernelTunables=, RestrictAddressFamilies=, RestrictNamespaces=, RestrictRealtime=, RestrictSUIDSGID=, SystemCallArchitectures=, SystemCallFilter=, or SystemCallLog= are specified. Note that even if this setting is overridden by them, systemctl show shows the original value of this setting. In case the service will be run in a new mount namespace anyway and SELinux is disabled, all file systems are mounted with MS_NOSUID flag. Also see No New Privileges Flag.

Maybe one of these exceptions would suffice for this use case?

CC'ing @teknoraver and @darsh13767 who reported cases where this setting breaks their workflow, and @jelly who submitted #795 and likely knows more about systemd settings than I do :smiley:

**Comment by darsh13767** [comment]
> Hmm I kind of think `NoNewPrivileges=true` is the right default value.
Indeed, changing to "NoNewPrivileges=false" in my /lib/systemd/system/transmission-daemon.service has fixed the issue. Thanks!

**Comment by LaserEyess** [comment]
IMO this setting should not be changed, overwriting for specific use cases is better. Allowing transmission to call SUID/SGID binaries is dangerous considering things like #468. This setting removes an attack vector from 99% of people using transmission with systemd.

**Comment by jelly** [comment]
I hope the protection can stay, maybe the transmission documentation should explain how to add a drop-in systemd unit override file.

`cat /etc/systemd/system/transmission.service.d/override.conf`

```
[Service]
NoNewPrivileges=false
```

**Comment by defkev** [comment]
I just ran into this again after upgrading to v4 (4.0.5 from epel)

> Jan 29 11:19:05 transmission.local transmission-daemon[62967]: WARNING: RunAsUser for MSP ignored, check group ids (egid=1000, want=51)
> Jan 29 11:19:05 transmission.local transmission-daemon[62967]: can not chdir(/var/spool/clientmqueue/): Permission denied
> Jan 29 11:19:05 transmission.local sendmail[62967]: NOQUEUE: SYSERR(transmission): can not chdir(/var/spool/clientmqueue/): Permission denied
> Jan 29 11:19:05 transmission.local transmission-daemon[62967]: Program mode requires special privileges, e.g., root or TrustedUser.

Add `MemoryDenyWriteExecute=false` (in addition to `NoNewPrivileges=false`) to `override.conf`

Cheers
