### ISSUE TITLE
Unable to start downloading under win10, prompt “no protocol option”

### ISSUE THREAD

**Issue by freephenix** [transmission/transmission#1952]
在简书看到一篇教程，按照步骤安装之后，正常打开了

但是upnp功能没能生效，且添加的左右种子都会提示“no protocol option”

1、开始怀疑是目录权限问题，修改后依然不能开始下载
<img width="1382" alt="WX20211014-152737@2x" src="https://user-images.githubusercontent.com/15763635/137271243-c0c30a29-e0a1-4ec2-aa8a-77b51f205a0a.png">

**Comment by ckerr** [comment]
I've never seen this error before. Looks like this is an `ENOPROTOOPT` on Windows.

@freephenix that GUI, https://links.jianshu.com/go?to=https%3A%2F%2Fgithub.com%2Fronggang%2Ftransmission-web-control, looks great but is not something I've used before. Could you translate the non-English text that's highlighted red in your screenshot?

**Comment by ckerr** [comment]
Closing due to lack of response.
