### ISSUE TITLE
Transmission event queue is broken on my NAS

### ISSUE THREAD

**Issue by MrJamesT** [transmission/transmission#1957]
So I've been trying to get to the bottom of my issue with https trackers on my NAS.
I'm always getting a `Response code 0 (No response)` from the tracker.

Today, I finally figured out what was causing the issue by setting up my own tracker for testing purposes. I've discovered that **transmission doesn't send any requests** until the event queue is "filled up." It's a bit hard to explain so I'll outline the steps to reproduce the bug on my DS216+II Synology NAS:

1. Start with a freshly booted up instance of transmission
2. Add any torrent with an https tracker -> the torrent won't start downloading and eventually the `Response code 0 (No response)` error will show up
3. Go to torrent details -> Trackers and remove the https tracker
4. I can fix the issue with two different solutions:
- Either put a new tracker url in but don't put /announce at the end but something else
- Or put the url with /announce in and remove it again and repeat this 4-5 times
5. The queue will now release all the requests at once and it will start downloading
(somehow though, when it tries to announce again, it's broken)

---
I have absolutely no idea why this issue is only isolated to my NAS, maybe because of an old kernel?
My setup is currently:

- Docker 20.10.3 - linuxserver/transmission package (latest)
- DSM7
- Synology linux kernel version 3.10.108

If you have any ideas, I'd be grateful.

**Comment by ckerr** [comment]
Is this still happening for you in the 4.0.0 betas?

**Comment by MrJamesT** [comment]
Hey, it's been so long that I forgot how far I went investigating this :) I sadly can't test this anymore since I sold my Synology NAS about half a year ago and built my own with Unraid, where I didn't experience any of these issues. Thanks for checking in on such an old issue though! :)
