### ISSUE TITLE
[2.92 Win 8.1 64-bit daemon] Sending stats on exit/shutdown

### ISSUE THREAD

**Issue by Tharn** [transmission/transmission#196]
Hi,

I've had this issue where I know the daemon has uploaded a certain amount of GB, going by ratios, but the tracker reports a much lower amount.

My hunch would be that stats are reported fine as long as regular tracker updates happen, but sending final stats upon program exit (and with a daemon, program exit is usually Windows shutdown) somehow doesn't happen reliably. If I'm right - can something be done about this? Grace period for services?

**Comment by andreygursky** [comment]
> but sending final stats upon program exit ... somehow doesn't happen reliably.

After some bug "fix" it doesn't happen at all and I reported this in July 2016: [TRAC-6161](https://trac.transmissionbt.com/ticket/6161). Since then I've patched transmission-daemon. It takes 1-4 minutes to shutdown, but it is expected.

**Comment by Tharn** [comment]
So you patched it for yourself? Because with 2.93 we are still seeing no stats being sent upon shutdown, both for system shutdown and regular 'graceful' service stop through services.msc. Would be nice if a patch like this could make it into the client.

**Comment by Shelmor** [comment]
Same here, no stats are sent upon system shutdown or manual stop through services.msc

**Comment by Shelmor** [comment]
Any updates on this? It's been quite a while..

**Comment by tearfur** [comment]
This is already implemented with a 15 seconds timeout in 4.x
