### ISSUE TITLE
The Russian localization does not fit lines of text and etc.

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#1963]
- macOS Big Sur: v.11.6 (20G165)
- Transmission: v.3.00+b0f36a9841

1. (Ни од) -> (Ни одного) - Finish the word completely.
2. (X) -> (None) - Replace (X) with the English word (None).
3. (Нормаль...) -> (Нормальный) - Increase the width of the selection box so that the word fits completely.

<img width="562" alt="Screen Shot 2021-10-15 at none" src="https://user-images.githubusercontent.com/62497891/137514519-35bd5ba4-7634-4933-92c5-25a34ecd13c2.png">

<img width="733" alt="Screen Shot 2021-10-15 at 17 06 02" src="https://user-images.githubusercontent.com/62497891/137514552-42776a87-f255-41a6-9135-38e180e0388e.png">

**Comment by mikedld** [comment]
I would say that some of these issues are related to incomplete transition to AutoLayout. If you want to help with that, see #140.
