### ISSUE TITLE
docs: README.md should have a section for how to submit a PR

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#1977]
specifically, several people have been bit by code-style issues. It's not always obvious how to resolve style conflicts. We should make it more explicit that clang-format version X is used -- or a more futureproof variation, have the readme link to some guest-visible page on https://trtc.mikedld.com/ that shows what version of clang-format is used by CI.

Inspired by https://github.com/transmission/transmission/pull/1748, but there have been other PRs before with the same problem. 1748 helped me to see the pattern.

CC @mikedld who did the CI magic and might intuitively know "ah, yeah http://trtc.mikedld.com/foo is the page you want"

**Comment by mikedld** [comment]
TeamCity doesn't decide which version of clang-format to use, it just runs the [docker-compose](https://github.com/transmission/transmission/blob/master/docker-compose.yml#L4) which uses the [Dockerfile](https://github.com/transmission/transmission/blob/master/docker/code_style/Dockerfile#L1) actually specifying it ("12-debian" tag there means latest 12.x).

**Comment by ckerr** [comment]
Maybe CI could run `clang-tidy --version` before code-style so that we could see the version number in the log?

**Comment by mikedld** [comment]
Not against the idea, but I'd add it to code_style.sh or docker-compose.yml if necessary, so that TeamCity is still ignorant as to what code style container it runs actually does.

**Comment by ckerr** [comment]
I knew we had this conversation but TBH I'd forgotten that we did it in an open issue. This overlaps a lot with #2455 and #2428, so I'm going to close this one to avoid issue duplication. My bad for filing dupes.
