### ISSUE TITLE
"Open folder" functionality with transmission-qt 3.00 in Windows

### ISSUE THREAD

**Issue by tonylambiris** [transmission/transmission#1978]
For some reason this never worked right for me ever since switching to the beta version of 3.0. This happened on an old install with 2.x but also on a recent install of Windows 10 about a few weeks ago.

However, I figured out that if I right click a torrent and go to "Open folder" it won't work, but as soon as I right click the torrent and select "Properties" and THEN try "Open folder" again it works as it should, opening a new explorer window to the file location of the torrent.

Thanks.

**Comment by ckerr** [comment]
I think https://github.com/transmission/transmission/pull/1753 might fix this

**Comment by dylanh724** [comment]
This issue still happens

**Comment by scootergrisen** [comment]
Sometimes selecting open folder will open the users folder (C:\Users\[username]) with Document folder highlighted.
Sometimes nothing happens.
Sometimes the correct folder is opened with the downloaded file.

If nothing happens and you open the properties and then try opening the folder again then a folder is opened with explorer.

Tested with:
Transmission 3.00 (bb6b5a062e)
Windows 7

**Comment by TarasZmyi** [comment]
on Transmission 4.0.0-beta.2 (bceb368f1b) - "Open folder" does not work either, Windows 11 22H2
