### ISSUE TITLE
logging is excessively verbose

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#1992]
The default mode of logging in Transmission is a little prolix. It generates a lot of output and much of it may not be particularly useful. What messages get logged at which verbosity level, especially at the default level, should be reconsidered.

As an aside, tr_log_level has a `TR_LOG_FIREHOSE` mode that appears to be unused and maybe should be removed.

**Comment by ckerr** [comment]
Related: https://github.com/transmission/transmission/issues/1031

**Comment by LaserEyess** [comment]
To add to this: control over what is logged would be nice, not just the levels but also the specific component. I may not care if an announce ever fails, but I may care if a torrent suddenly is corrupted or has a bad piece. Right now, both of those are at the same level (error).

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/2756.

per-component logging should be tracked in a separate issue
