### ISSUE TITLE
[feature request] multiple magnet URI import wizard

### ISSUE THREAD

**Issue by ewtoombs** [transmission/transmission#200]
The idea would be you have a large text pane into which you could paste a whole list of magnet URIs, one per line. After the paste, you hit 'Download' and the metadata gets downloaded. Then you could specify the following options:

- where you want to save the files, renaming files and directories as necessary
- which files within the torrents to download and with what priority
- whether to download the files sequentially or not (handy for video)
- whether they should start paused
- whether to seed only, i.e. whether to download any file that has not already been downloaded

You then hit 'Add', and all of the torrents are added automatically, with all of the options specified in the previous step completed. This would greatly simplify my current process of importing a whole bunch of completed torrents into transmission for seeding.

**Comment by Coeur** [comment]
For macOS, that issue might have been resolved in some way with #3087.
Can you clarify which client you're using: macOS, web, GTK or Qt?

**Comment by ewtoombs** [comment]
I'm using daemon+remote these days. I wrote that a while ago. TBH, I don't even remember writing this feature request lol.
