### ISSUE TITLE
Transmission Mac: Transmission moving files between hard drives freezes the app

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#2011]
This has been the case with Transmission for a long time. Any move operation in Transmission will freeze the app for the entire duration of the move operation. The mouse will spin and the app itself will be completely non-interactive. This is easy to reproduce if the move occurs between two different drives, or ultimately in a scenario where the move operation is long.

Steps to reproduce (either one)
1. Tell Transmit to move an existing file from one hard drive to another.
2. Setup a rule for Transmission to move completed files from an incomplete directory to a complete directory once download is complete. Make sure those two directories are on different hard disks.

This gets to be especially problematic the larger the file considering it will freeze the app for longer.

**Comment by ckerr** [comment]
Topic moved to  https://github.com/transmission/transmission/issues/2462.
