### ISSUE TITLE
Transmission-remote doesn't work and outputs special characters

### ISSUE THREAD

**Issue by txolovinsky** [transmission/transmission#204]
Some days ago the program has stopped working and I do not know what happens:

**# transmission-remote --auth transmission:xxxxxx -l**
Unexpected response: X̛�����1�kA�6��^�`LQ�鎋ka��	Q%ڛ�)��Q��;cd/˵U�1�nY�e~7�yKvΐǠnsm?��]�Iس��=9�Q(��F�Ba�{mګT��_�O� H>��޷�p̼j�"�'\Ϩ�S0��b�iK��B7P����g��:�!�Ih�c$+�Ċ�[�����p�X��e�d�~��}t͋ix�p��Z���OST /transmission/rpc/ HTTP/1.1
User-Agent: transmission-remote/2.84 (14307)
Host: localhost:9091
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 233
Content-Type: application/x-www-form-urlencoded

{"arguments":{"fields":["error","errorString","eta","id","isFinis�

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/).

If you report an issue, be sure to try [latest stable version](https://transmissionbt.com/download/) or latest [nightly build](https://build.transmissionbt.com/) first.

**Comment by txolovinsky** [comment]
I've tried with the latest version and the error continues, but don't worry...
