### ISSUE TITLE
[Feature Request]Unable to get all uploaded traffic.

### ISSUE THREAD

**Issue by kivimango** [transmission/transmission#208]
Please display somewhere on the web gui the uploaded amount of traffic in the current session.
(I would place a counter next to the download/upload speed indicator).

**Comment by fernandog** [comment]
@kivimango accessing from web you can see it:

![image](https://cloud.githubusercontent.com/assets/2620870/23750373/5bfe8e2e-04ab-11e7-88d1-95602faff254.png)

**Comment by kivimango** [comment]
Thank you.
