### ISSUE TITLE
Transmission(QT) constantly force-closes

### ISSUE THREAD

**Issue by jebeld17** [transmission/transmission#210]
Transmission(QT) is constantly force-closing once I start downloading a torrent via a .torrent file in Windows 10 x64 Pro.

I ran the compatibility troubleshooter and the program seems to run a bit more stable when run in backwards-compatibility mode with Windows XP SP3 with disabled scaling on High DPI settings. The program still force-quit one time during a torrent download, but it didn't crash as quickly and didn't crash every time, either.
[TRANSMISSIONQT.pdf](https://github.com/transmission/transmission/files/824938/TRANSMISSIONQT.pdf)

**Comment by mikedld** [comment]
"TransmissionPortable" mentioned in that compatibility troubleshooter report is not a part of official distribution. Please report this issue to people who are involved in its developement. If you wish to try official version, use either the [early preview](https://transmissionbt.com/download/) version or the [nightly build](https://build.transmissionbt.com/job/trunk-win32/).
