### ISSUE TITLE
Debug Assertion Failed for non-english symbols

### ISSUE THREAD

**Issue by depler** [transmission/transmission#2106]
Here is the code under debug:
![image](https://user-images.githubusercontent.com/13541699/140582564-e5f45506-ddcd-4a30-9d00-d77d2846d576.png)

In case if `std::string_view in` contains non-english characters (Russian utf8-encoded in my case) it leads to:
![image](https://user-images.githubusercontent.com/13541699/140581777-5daeac69-7edb-47e6-9850-5fb42b77ec71.png)

Probably `auto` should be changed to `unsigned char`. This is only assertion under debug and not runtime showstopper, but still bad.

**Comment by ckerr** [comment]
Thank you for reporting this!

**Comment by ckerr** [comment]
@depler given your description of the bug & debugger info, I _think_ this fixes it but I don't have a torrent that tickled this bug before so I haven't been able to test.

Could you test this out and confirm this is fixed?

Also, would you be willing to email me a public .torrent file that I could use to test this? My email is my first name @ first last dot com.

**Comment by depler** [comment]
@ckerr this one is fixed. There is another one similar case (probably there are more, not sure if they all need to be fixed):

![image](https://user-images.githubusercontent.com/13541699/150011342-e5eb7b07-ee07-4514-b23e-7a23f43c22df.png)

Here is test torrent file with cyrillic: [cyrillic.zip](https://github.com/transmission/transmission/files/7892088/cyrillic.zip)

**Comment by Leancher** [comment]
Я создаю файл через командную строку.  Появляется такая же ошибка.

<img width="951" height="293" alt="Image" src="https://github.com/user-attachments/assets/85a01bf1-5e77-438c-94f9-eb493cc27b9a" />
