### ISSUE TITLE
Seed idle timeout has different value from config

### ISSUE THREAD

**Issue by fernandog** [transmission/transmission#212]
Build: 14714

Value its limited to 9999 but the transmission setting file is 10080
![image](https://cloud.githubusercontent.com/assets/2620870/23797420/8ca2e34e-057e-11e7-9c68-be61b843a18a.png)

So when i open Transmission-QT, it overrides my torrent and global setting to 9999

Torrent property dialog:
![image](https://cloud.githubusercontent.com/assets/2620870/23797159/35f2547c-057d-11e7-9775-3a36643f2b67.png)

Global setting:
![image](https://cloud.githubusercontent.com/assets/2620870/23797246/b1160a36-057d-11e7-8e35-6ed032620d2d.png)

**Comment by mikedld** [comment]
Limits are not the same across clients: 1..9999 (GTK+ and Qt), 1..99999 (Mac), 0..∞ (web). Transmission core stores the number as `uint16_t` with range of 0..65535.
