### ISSUE TITLE
Crash upon exiting sleep mode

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2122]
- Transmission v.3.00+bbdb488224
- macOS v.12.0.1 (21A559)

Log: [Transmission-2021-11-09-162817.ips.zip](https://github.com/transmission/transmission/files/7506689/Transmission-2021-11-09-162817.ips.zip)

**Comment by ckerr** [comment]
I don't see any PII here, so pasting trace directly

,{"imageOffset":531728,"symbol":"abort","symbolLocation":123,"imageIndex":7},{"imageOffset":886040,"symbol":"tr_assert_report(char const*, int, char const*, ...)","symbolLocation":202,"imageIndex":4},{"imageOffset":735861,"symbol":"tr_peerIoTryWrite(tr_peerIo*, unsigned long)","symbolLocation":498,"imageIndex":4},{"imageOffset":734749,"symbol":"tr_peerIoFlush(tr_peerIo*, tr_direction, unsigned long)","symbolLocation":204,"imageIndex":4},{"imageOffset":834001,"symbol":"Bandwidth::phaseOne(std::__1::vector<tr_peerIo*, std::__1::allocator<tr_peerIo*> >&, tr_direction)","symbolLocation":139,"imageIndex":4},{"imageOffset":834971,"symbol":"Bandwidth::allocate(tr_direction, unsigned int)","symbolLocation":867,"imageIndex":4},{"imageOffset":758494,"symbol":"bandwidthPulse(int, short, void*)","symbolLocation":134,"imageIndex":4},{"imageOffset":1016610,"symbol":"event_process_active_single_queue","symbolLocation":502,"imageIndex":4},{"imageOffset":1004561,"symbol":"event_base_loop","symbolLocation":1130,"imageIndex":4},{"imageOffset":714817,"symbol":"libeventThreadFunc(void*)","symbolLocation":144,"imageIndex":4},{"imageOffset":675281,"symbol":"ThreadFunc(void*)","symbolLocation":28,"imageIndex":4},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":6},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":205165,"frames":[{"imageOffset":21598,"symbol":"kevent","symbolLocation":10,"imageIndex":0},{"imageOffset":535082,"symbol":"-[VDKQueue watcherThread:]","symbolLocation":224,"imageIndex":4},{"imageOffset":365513,"symbol":"__NSThread__start__","symbolLocation":1025,"imageIndex":8},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":6},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":205169,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":0},{"imageOffset":526914,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":520475,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":1},{"imageOffset":517421,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":1},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":3},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":6},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":205171,"frames":[{"imageOffset":13274,"symbol":"__semwait_signal","symbolLocation":10,"imageIndex":0},{"imageOffset":67753,"symbol":"nanosleep","symbolLocation":196,"imageIndex":7},{"imageOffset":546022,"symbol":"tr_wait_msec(long)","symbolLocation":76,"imageIndex":4},{"imageOffset":820775,"symbol":"tr_webThreadFunc(void*)","symbolLocation":1626,"imageIndex":4},{"imageOffset":675281,"symbol":"ThreadFunc(void*)","symbolLocation":28,"imageIndex":4},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":6},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":6}]},{"id":206491,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":206943,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]}]

**Comment by mag01** [comment]
Seems to be the same thing as #1630

**Comment by Oleg-Chashko** [comment]
I did a test: During the download of the file, I turned off and on the Wi-Fi network. The result was a crash.
Log: [Transmission-2021-11-10-074706.ips.zip](https://github.com/transmission/transmission/files/7510484/Transmission-2021-11-10-074706.ips.zip)

If the failure causes, network failures. Please delete this issue, so as not to duplicate with #1630.
