### ISSUE TITLE
Release for OpenSSL 3.0.0?

### ISSUE THREAD

**Issue by limburgher** [transmission/transmission#2126]
I see that #1777 is complete, but it doesn't cleanly apply to 3.00 due to the new submodule. Is there an ETA for a release with that change?

**Comment by mikedld** [comment]
There's no ETA for a release.

I would assume it's not a blocker for you to upgrade to OpenSSL v3 though, API-wise Transmission should be compatible (despite a few deprecation warnings for DH functions) and just work, it's just that RC4 algorithm got moved to a separate provider that's not enabled by default.

According to https://www.openssl.org/docs/man3.0/man7/migration_guide.html,
> ##### Legacy Algorithms
> These legacy EVP algorithms are still available in OpenSSL 3.0 but not by default. If you want to use them then you must load the legacy provider. This can be as simple as a config file change, or can be done programmatically.

Then based on https://www.openssl.org/docs/manmaster/man5/config.html, I would assume that something like this is possible to configure (not tested):
```
openssl_conf = openssl_init

[openssl_init]
providers = providers

[providers]
default = default_provider
legacy = legacy_provider

# https://www.openssl.org/docs/manmaster/man7/OSSL_PROVIDER-default.html
[default_provider]
activate = 1

# https://www.openssl.org/docs/manmaster/man7/OSSL_PROVIDER-legacy.html
[legacy_provider]
activate = 1
```
