### ISSUE TITLE
Documentation example of using addTorrentByUrl of the Web client in order to add a torrent by URL from another tab

### ISSUE THREAD

**Issue by Utopiah** [transmission/transmission#2131]
Hi, I'm wondering how I could integrate transmission with my web based workflow. What I currently do is copy a magnet URL, navigate to the transmission Web client URL then add it. What I would prefer though is register transmission Web client as a protocol handler for magnet. Has this been documented somewhere? Is it feasible as-is and if so how?

PS: tried to post in Discussions but somehow didn't manage to start a new one. Maybe end of the week fatigue but my apologies if this isn't the right place to ask.

**Comment by GScottElshaw** [comment]
When you say web based workflow, do you mean using bittorrent as a client between work and home? I also may be suffering end of week fatigue.

**Comment by Utopiah** [comment]
Even though the browser and client are indeed on different machines I meant not leaving the browser. What I have in mind is that I click on a magnet link and it doesn't open my local transmission client but rather http://tv:9091/transmission/web/ (feasible today) or rather something like http://tv:9091/transmission/web/?addTorrent=magnet://URI that would then add the torrent with that URI.

**Comment by GScottElshaw** [comment]
I love that idea. In some respects it's kind of what utorrent is, i think, working towards. 

I spent many hours in the last week thinking about the same thing but decided I was trying to take a good idea into something fantastical. Maybe just me, but I am constantly in awe how opaque Bittorrent is. I have zero idea why clients connect, stay, or drop-off. I have zero sense of why a client connects or disconnects, or even why my available bandwidth will be used or unused. Sorry, making a lengthy point. It's a terribly uneconomic file sharing platform if being *direct* is what you need.

**Comment by killemov** [comment]
Wow, I've implemented this for https://github.com/killemov/Shift/commit/cc4add2d38c6ea24b6d31ffed4d1283dffe687d5  in 2018. I can click on a magnet or I can drag/drop a torrent link from one tab to Shift. Or simply drop a torrent from the desktop.
> Even though the browser and client are indeed on different machines I meant not leaving the browser. What I have in mind is that I click on a magnet link and it doesn't open my local transmission client but rather http://tv:9091/transmission/web/ (feasible today) or rather something like http://tv:9091/transmission/web/?addTorrent=magnet://URI that would then add the torrent with that URI.

Using these special methods of adding torrents will be phased out. You will, and should, always need the RPC interface for this.

**Comment by GScottElshaw** [comment]
Maybe talking cross-purposes? Regardless of whether it is RPC, browsers can be horrors to configure. I'm currently using [Chromium](https://github.com/Eloston/ungoogled-chromium) and a simple html command for an email address and a subject line seems to be incomprehensible to parse.

**Comment by Utopiah** [comment]
Ok I understand `http://[username]:[password]@[host]:[port]/transmission/rpc` a bit better now which lead me to https://github.com/unrelentingtech/transmitter which does the job. Thanks for the clarifications.
