### ISSUE TITLE
Why it still uses XWayland?

### ISSUE THREAD

**Issue by halturin** [transmission/transmission#2133]
It's not a bug report. Just a question.

I'm not aware of the underhood but just realized, despite using gtk 3.24 it still appears in the xlsclient list. I supposed it should work with Wayland natively.

**Comment by mikedld** [comment]
Building in Fedora 35, can't see it in xlsclients. The only 3 clients there are gsd-xsettings, ibus-x11, and gnome-shell.

**Comment by halturin** [comment]
Oh, I should have mentioned the environment details. I'm using NixOS (unstable). 

It's weird, but after the last update, I don't see transmission-gtk among the xwayland clients (in xlsclient stdout) anymore.
