### ISSUE TITLE
Transmission-qt does not honor system icon theme

### ISSUE THREAD

**Issue by harogaston** [transmission/transmission#216]
In KDE Plasma 5.8 (openSUSE Leap 42.2) Transmission overrides my icon theme, for application and system tray icon.

I don't know why it is. But it is using the hicolor default.

Thank you for any feedback on this.

**Comment by mikedld** [comment]
Which version of Transmission are you using? This should be fixed as of 2.90.

**Comment by harogaston** [comment]
Sorry I didn't mention it. I'm not at home right now, but I'm running 2.8x for sure. So, I'll wait for openSuse to update the repos and I asume it will be fixed.

Thank you for your insigth.

**Comment by sten0** [comment]
Here is what transmission-qt 2.92 (14714) tray icon and menu icon looks like with plasma-desktop-5.8.6 on Debian 9.  Is there supposed to be a more "flat style" icon to fit into the breeze or breeze-dark theme?
![coloured-icon-in-breeze-theme](https://user-images.githubusercontent.com/11372289/28244467-09e4169e-69ba-11e7-9592-a42b6f877471.png)
