### ISSUE TITLE
Nightly build #753 Delete torrent files not working

### ISSUE THREAD

**Issue by nengxu** [transmission/transmission#2206]
Running transmission-3.00+-r1459220b5b-x64.msi, the function (shift-Del) of deleting torrent as well as its files failed. Only the torrent is removed. Its downloaded content is untouched.

**Comment by ckerr** [comment]
Hmm, I'm not seeing that here.

If this is still happening for you, @nengxu, any chance you can walk backwards through some of the nightlies to narrow down where it broke?

**Comment by nengxu** [comment]
Just tried with the latest build #760. The problem still occurred. Either through Shift+Delete, or through right-click menu.

**Comment by nengxu** [comment]
Any news on this issue?

**Comment by nengxu** [comment]
Tried build #823, transmission-3.00+-r4ea2429217-x64.msi. Problem did not occur. Close for now.
