### ISSUE TITLE
[Feature Request] Download a torrent one/some file(s) at a time, automatically

### ISSUE THREAD

**Issue by forteller** [transmission/transmission#2208]
Here's one thing I think a lot of torrent users do, but that I've never seen any client automate:

You get a torrent with a ton of files in it, and you don't want to wait to check out the contents until the whole thing is downloaded. So you set it to download just the first one or couple of files, and then when they're done downloading you go back into the settings for the torrent and set it to download the next one or few files. Rinse and repeat. This is a useful, but just really boring and annoying task to do.

I think Transmission would really set itself apart from other clients in simplicity and a good user experience if you could find a way to automate this process. Let me

1. Select the order the files should download in (hopefully the default order will be by name, ascending, which is probably the most common order, so that most people will not have to reorder the files first and can go straight to step 2, which would then be the only step they need to do)
2. Select the first one or few files to start downloading
3. Automatically continue downloading the next files (same number of files as I selected in step 2, probably) in the list when those first files are done downloading.

This should, of course, be completely optional. It should be just as easy to only download the selected files, and not automatically download the next ones.

That's it. Letting me "set it and forget it" like this, instead of having to open up the torrent client again every time I get a notification that some files are done, just to manually select the next files in the list to download, would be a huge quality of life improvement for a torrent client IMO.

Thanks a lot for your great work!

**Comment by ckerr** [comment]
Hi @forteller, thanks for the suggestion!

A lot of this overlaps with https://github.com/transmission/transmission/issues/597, so I'm going to mark this as a duplicate.

The non-overlapping suggestion, e.g. manually being able to select the file download order, seems a little fringe to me. I think sequential ordering would handle most peoples' needs for this.

**Comment by forteller** [comment]
Thank you for your fast answer, @ckerr! Although I don't see the overlap myself, and it seems to me that the non-overlapping part is my whole point. Either I'm misunderstanding something here or I'm not explaining myself well enough (English is not my first language). Please let me try again, and see if you can tell me if I'm the one misunderstanding you, or if it's the other way around :)

The issue you linked to seems to me to be all about downloading the bits in a single file in order from first to last, so you can start watching a video file before the whole file is downloaded.

That is unimportant to me, and has nothing to do with what I'm trying to request, as far as I can tell (though I'm no technical expert in these things!)

What's important to me is that I can download the full first file in a torrent with many files in it first, then the full second file, etc. (Or the full first X files, then the next, but that's less important). This so that I can listen to the first part of an audioboook where each chapter is an individual file, or watch the first of a series of videos, without having to download the whole torrent first. And I would like to not have to manually go in and select the next file in the series every time the current one is downloaded.

It's very strange to me if this is fringe, I would think a lot of people would prefer to do this, even if they don't do it now because it's too much hassle if the torrent client doesn't automate the process.

This is especially important for people with low download speeds or torrents with relatively few seeders.

I did not see anything about any of this in the linked issue?

Thank you again!

**Comment by forteller** [comment]
I'd like to point to my comment above and ask that this issues is reopened.

**Comment by ckerr** [comment]
To clarify, the reason I marked this as  a duplicate of 597 is that downloading the pieces in sequential order will by definition also download the files in sequential order :smile_cat:
