### ISSUE TITLE
Web UI should use proxy of browser.

### ISSUE THREAD

**Issue by tlc** [transmission/transmission#221]
This is **NOT** about the daemon using a proxy to get out.  This is about the WebUI javascript (remote.js) apparently not using the proxy of the browser it's running in.

When I try to access my transmission server from work, the page elements load and the js load fine, but I always get this dialog.  
```
   Connection Failed
   Could not connect to server. ....
```
My theory is that remote.js isn't using the browser's proxy, but I don't know enough javascript to be sure.
I access other things at home just fine via my SOCKS5 tunnel (polipo/ssh).

**Comment by mikedld** [comment]
I have no idea either so I'll just close this until someone actually has an idea. What I'm usually doing when I need to access remote Transmission web UI is setting up an SSH tunnel.
