### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by Stellarspace** [transmission/transmission#222]
I opened Transmission and this error happened both times: Page Fault In Nonpaged Area

**Comment by mikedld** [comment]
Please you [forums](https://forum.transmissionbt.com) for support, right now it's not at all clear what happened and if Transmission is in fact responsible. You may have more luck on Windows-specific forums though, like the ones helping with BSOD issues on Windows [7](https://www.sevenforums.com/bsod-help-support/), [8](https://www.eightforums.com/bsod-crashes-debugging/), [10](https://www.tenforums.com/bsod-crashes-debugging/) (you didn't specify which Windows version you're running).

Please reopen if/when you have more information.
