### ISSUE TITLE
Downloaded data count decreases while downloading

### ISSUE THREAD

**Issue by RightMakesMight** [transmission/transmission#2231]
When running transmission-remote in a docker container, as downloading progresses for any torrent, the % and total data counts will occasionally decrease, and this becomes more frequent as the download progresses. This occurs for no apparent reason. If this is a result of hashfails/wasted data, then I would suggest that some indicator be added to show where the data is going. Otherwise, is there any other possible cause for the count decrease?

**Comment by ckerr** [comment]
I'd suspect it's due to hashfails. That's why there's also a 'verified' number shown to indicate what data has already passed the test. That number should never decrease.
