### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by kennis942** [transmission/transmission#2235]
i have a 50 TB smb share mounted on the vm that transmission is running on, it is absolutely not out of space on the download location
every torrent looks like this
http://prntscr.com/20xgtly

this is the disk showing it is not full
http://prntscr.com/20xgrrb
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
using SWIZZIN
[transmission.log](https://github.com/transmission/transmission/files/7610922/transmission.log)
.

**Comment by killemov** [comment]
Maybe the user "transmission" does not have access to the download location.
Try:
```console
sudo su -l transmission -s /bin/bash
```
And navigate to the download location.

**Comment by ckerr** [comment]
The logfile is pretty explicit about which filesystem is full:

> Couldn't save temporary file "/home/ken/.config/transmission-daemon/resume/infohash": No space left on device (variant.c:1257)

The path with free space, /mnt/share/media, has nothing to do with it.

**Comment by killemov** [comment]
Mkay, a full home partition ... uhrmaguhrd.
