### ISSUE TITLE
magnet links always pause after they get metainfo

### ISSUE THREAD

**Issue by djcristi** [transmission/transmission#2239]
it pauses after gets metadata instead of downloading.

macbook m1, macos 12 , build 742ae6f

**Comment by ckerr** [comment]
I'm seeing the same behavior in the GTK client builds from master, too

**Comment by djcristi** [comment]
tried now 37a8046 , and it seems fixed.

**Comment by chaseholden** [comment]
preference setting is ignored to “Start torrent when added” so that while checked, all files are added in a paused state regardless in build e0c3a7f3e6 - Transmission 3.0 for Mac on Intel iMac Pro 2017 macOS 12.2 Monterey

**Comment by ckerr** [comment]
Fixed by #2654.

**Comment by chaseholden** [comment]
Just a note about this new build aec1b29e88 - ALL existing torrents now are Paused upon first launch regardless of previous states and so must be resumed manually. 
However, subsequently relaunching the App does remember Status. 
But I verify the "new paused magnet torrent" bug is solved. 
Thanks for all of your hard work. It's really appreciated.

**Comment by JohnGalt1717** [comment]
This appears to be back in the latest docker release.

**Comment by azais-corentin** [comment]
This seems to be fixed by #4856
