### ISSUE TITLE
"Remove and delete data" also deletes same name files from other torrents

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#2240]
Say you are downloading the file FOO from two distinct torrents.
First download completes and you decide to cancel the partial second download with "Remove and delete data": the issue is that it will actually delete the completed download from the first torrent because they share the same filename. The expectation was to only delete the partially downloaded data from the second download.

Transmission 3.00+ (a459e5e11b) on macOS Mojave.

**Comment by killemov** [comment]
This is by design. If you want to make a distinction then rename the file or folder within Transmission.
