### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by fxcoudert** [transmission/transmission#2244]
There is a space missing after “téléversé”:
<img width="391" alt="Capture d’écran 2021-11-28 à 16 39 36" src="https://user-images.githubusercontent.com/1980544/143775199-e0c3c4da-c009-4a72-9529-43e16019ba7b.png">

This is in `transmission/macosx/fr.lproj/Localizable.strings`, https://github.com/transmission/transmission/blob/e2b1c71982a0f050d827fd012f760faedb59d636/macosx/fr.lproj/Localizable.strings#L1132

which should be instead:

```
/* Torrent -> progress string */
"uploaded %@ (Ratio: %@)" = "téléversé %1$@ (ratio : %2$@)";
```

**Comment by ckerr** [comment]
Hi @fxcoudert, thanks for reporting this!

All the translations are done at https://www.transifex.com/transmissionbt/public/ . Transifex is a site that's good for free / open source apps to get crowdsourced translations.

Please submit a change there. Thank you!
