### ISSUE TITLE
crash in nightly build while downloading

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2245]
- Transmission v.3.00+998d4c514b
- macOS v.12.0.1 (21A559)

Crash logs:
[Archive.zip](https://github.com/transmission/transmission/files/7614275/Archive.zip)

**Comment by ckerr** [comment]
998d4c514b is https://github.com/transmission/transmission/pull/2241 and the code is [here](https://github.com/transmission/transmission/blob/998d4c514b57558a993573d78667a126d593bf27/libtransmission/bitfield.cc).

```
    "frames": [
      {
        "imageOffset": 28946,
        "symbol": "__pthread_kill",
        "symbolLocation": 10,
        "imageIndex": 0
      },
      {
        "imageOffset": 25139,
        "symbol": "pthread_kill",
        "symbolLocation": 263,
        "imageIndex": 1
      },
      {
        "imageOffset": 531728,
        "symbol": "abort",
        "symbolLocation": 123,
        "imageIndex": 2
      },
      {
        "imageOffset": 907286,
        "symbol": "tr_assert_report(char const*, int, char const*, ...)",
        "symbolLocation": 202,
        "imageIndex": 3
      },
      {
        "imageOffset": 863562,
        "symbol": "tr_bitfield::countFlags(unsigned long, unsigned long) const",
        "symbolLocation": 330,
        "imageIndex": 3
      },
      {
        "imageOffset": 714440,
        "symbol": "tr_completion::amountDone(float*, unsigned long) const",
        "symbolLocation": 116,
        "imageIndex": 3
      },
      {
        "imageOffset": 261412,
        "symbol": "-[TorrentCell(Private) drawPiecesBar:]",
        "symbolLocation": 319,
        "imageIndex": 3
      },
      {
        "imageOffset": 259057,
        "symbol": "-[TorrentCell(Private) drawBar:]",
        "symbolLocation": 291,
        "imageIndex": 3
      },
      {
        "imageOffset": 253536,
        "symbol": "-[TorrentCell drawInteriorWithFrame:inView:]",
        "symbolLocation": 233,
        "imageIndex": 3
      },
      {
        "imageOffset": 3023673,
        "symbol": "-[NSTableView _drawContentsAtRow:column:withCellFrame:]",
        "symbolLocation": 251,
        "imageIndex": 4
      },
```

**Comment by ckerr** [comment]
My guess it's the new implementation of tr_completion::amountDone() which is only used by the mac client and doesn't have good test coverage. I'll add tests there and see if I can trigger anything.

**Comment by ckerr** [comment]
OK I'm going to leave this open since (a) there may be a second bug and (b) even if there's _not_ a second bug I need to add test coverage for `amountDone()`, but @Oleg-Chashko a build that includes 9516e8a9234e94733fa8eeef8cdd3f23f97e2131 should fix at least _some_ of the oddness. Could you give it a try and let me know?

**Comment by Oleg-Chashko** [comment]
@ckerr 
OK

**Comment by ckerr** [comment]
> A new problem has appeared (Waiting to check existing data...), but the download continues and finishes successfully:


Please open a separate issue for that

**Comment by Oleg-Chashko** [comment]
@ckerr
_Could you give it a try and let me know?_
1. No crash in build v.3.00+9516e8a923
2. But the problem with (#2243) still exists.

**Comment by Oleg-Chashko** [comment]
Closed the issue. Since it may have already been fixed. In the near future, the problem was not noticed.
