### ISSUE TITLE
Nightly build while downloading (Waiting to check existing data...)

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2249]
- Transmission v.3.00+998d4c514b
- macOS v.12.0.1 (21A559)

(Waiting to check existing data...), but the download continues and finishes successfully:

<img width="664" alt="143882040-1fd515b0-4007-43c5-abde-96264b7190cf" src="https://user-images.githubusercontent.com/62497891/143932552-6fe5e8b0-31cc-4631-8b0b-b9e0bba46438.png">

**Comment by ckerr** [comment]
This was introduced sometime in the last 2-4 days. I've seen it here myself once but haven't been able to reproduce it since then.

**Comment by Oleg-Chashko** [comment]
@ckerr,
algorithm to reproduce:
Simultaneous downloading of a large number of torrents.

https://user-images.githubusercontent.com/62497891/144049231-cc86cc6a-94e2-49ca-afbc-9fd3683c969e.mp4

**Comment by imrefazekas** [comment]
Same behaviour here ...

**Comment by Oleg-Chashko** [comment]
Closed the issue. Since it may have already been fixed. In the near future, the problem was not noticed.
