### ISSUE TITLE
[Feature Request] Torrent Done Scripts Directory Option

### ISSUE THREAD

**Issue by berkovskyy** [transmission/transmission#225]
At the moment it is possible to configure only a single script to be executed when torrent is done. This works well for trivial situations but causes an inconvenience for any non-trivial setup. Example of such setup would be presence of two scripts: one script which sends an email and second script which shows a desktop notification. User would have to either combine the scripts manually or write a wrapper script which would call each script individually. Other example of a setup which is not possible with the current transmission is distribution of scripts using package managers.

I propose to add a new configuration option containing location of directory with scripts, default value could point to directory located next to the transmission configuration file (e.g. "script-torrent-done-directory": "/etc/transmission-daemon/scripts.d/"). Current code which runs a single script can be extended to scan the directory for executable files and execute them one after another. As an extra feature it would be good to have a filtering step to skip files with particular names, for example files which end with '~' or start with dot.

**Comment by mikedld** [comment]
I'm for writing "a wrapper script which would call each script individually" in this particular case. Adding scripts directory will only bring more questions to the table, e.g. should Transmission execute next script if previous one failed, in which order should scripts be executed (in case one depends on the results of another), what would be the quick and user-friendly way of disabling some scripts while still allowing other scripts to run... All this is easier to implement (and adjust when needed) in the form of a separate script or program.
