### ISSUE TITLE
Display of first torrent on torrent list in macOS 

### ISSUE THREAD

**Issue by gennaios** [transmission/transmission#2254]
Using the current nightly build, I have noticed such since I started using it a few weeks ago. When adding torrents, the first one in the list is cut off and only partially displayed:

<img width="507" alt="Capture d’écran 2021-11-29 à 17 03 58 " src="https://user-images.githubusercontent.com/12172/144138764-ddd22c90-e0f5-4be7-9610-390dc1703f68.png">

It doesn't happen all the time but it seems most of the time.

**Comment by fxcoudert** [comment]
Do you still see it with a recent build? I've not experienced that issue…

**Comment by gennaios** [comment]
Last build I’ve been using is possibly from a few weeks ago. Will try again soon but if you don’t recall any possible fixes then issue likely still there. 

Monterey Apple Silicon arm64 if that makes any difference.

**Comment by gennaios** [comment]
Newest build. Seems ok so far. Will report back if any issues.

**Comment by gennaios** [comment]
yes it does still occur.

**Comment by Coeur** [comment]
I've never seen that issue. Since there were various UI fixes, like #3315, can you still reproduce in 4.0 beta?

**Comment by Coeur** [comment]
Considering the many intermediate changes that have happened since then, I'll assume it's not reproducible. Feel free to re-open if it happens again.
