### ISSUE TITLE
fatal error: utf8.h: No such file or directory

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#2271]
I don't know what changes took place or where, but cannot build it anymore.

```
/home/stefanos/development/Transmission/transmission/libtransmission/utils.cc:54:10: fatal error: utf8.h: No such file or directory
   54 | #include <utf8.h>
      |          ^~~~~~~~
compilation terminated.
```

I know I have `/usr/include/unicode/` which includes `utf8.h` in there...

Specs

```
OS: GNU / Linux Debian testing 64-bit
Compiler: GCC 11.2.0-12
```

Also this looks weird to me

![image](https://user-images.githubusercontent.com/1777466/144877704-4ff1b6a1-b9b1-4cef-8bdd-e6213c32ae70.png)

as I didn't do anything fancy other than following the update instructions from README

![image](https://user-images.githubusercontent.com/1777466/144877810-85a61679-4ebe-45f1-a5f7-be201af5e2c7.png)

**Comment by stefanos82** [comment]
Based on https://github.com/transmission/transmission/commit/bbe49639d694f2ec346708e7acb9ab365d501a10 a new submodule was introduced and we were not informed.

`git submodule update --init` fixes the problem.

@ckerr and @mikedld, is there a way to inform users that they should execute the aforementioned git command to introduce a new submodule to their existing local forked repos?

Closing the ticket as it was a false alarm.

**Comment by mikedld** [comment]
@stefanos82, I think the command is right there (4th from the top) in the pertinent section, unless I'm missing something?

https://github.com/transmission/transmission/blob/e2be142ad643e583f222e14e5b9203af943468c5/README.md#L56-L65

**Comment by stefanos82** [comment]
`git submodule update` and `git submodule update --init` are not the same thing.

**Comment by mikedld** [comment]
A PR to fix this would be great then, I guess...

**Comment by stefanos82** [comment]
> A PR to fix this would be great then, I guess...

You mean to update README?

**Comment by GScottElshaw** [comment]
That's what I was thinking too. Thanks, by the way.
