### ISSUE TITLE
Please provide an daemon option to explicitly disable IPv6 support.

### ISSUE THREAD

**Issue by enihcam** [transmission/transmission#228]
Sometimes people need IPv6 stack on their server, but not all daemons.
Please provide a run-time option for explicitly disabling IPv6 support.
Thanks!

**Comment by fernandog** [comment]
Did you try this?

https://forum.transmissionbt.com/viewtopic.php?t=11567#p58081

**Comment by enihcam** [comment]
@fernandog, yes I tried. it does not disable IPv6 logics inside transmission.

I think a compile-time option also works.

**Comment by fernandog** [comment]
But if it binds to local, what is the issue? Just asking. No an expert

**Comment by enihcam** [comment]
i disabled ipv6 routes/IPs/etc, but not the ipv6 stack for some reasons. so I cannot bind transmission service to a local IPv6 address.

**Comment by mikedld** [comment]
See #86.

**Comment by Guanglier** [comment]
Hi, 
The ipv6 bind desn't seem to work (Transmission 2.92 (14714) on raspberry pi)

With the address of the VPN (ipv4 and ipv6) configured in "settings.json" the bind only works for ipv4 and not for ipv6 (torrent ip check indicates VPN ipv4, but "original" ipV4 (not the VPN one)

The only way i found was to disable ipv6 from the system.
