### ISSUE TITLE
Pausing new torrents cause metadata to not be downloaded

### ISSUE THREAD

**Issue by diogoeichert** [transmission/transmission#2280]
When adding new torrents in paused state or adding and then immediately pausing them causes the much needed metadata to not being downloaded, until the transfer is unpaused. This prevents being able to select partial downloads in multiple-file transfers before actually starting the transfer.

**Comment by diogoeichert** [comment]
There are no similar issues.

**Comment by killemov** [comment]
> There are no similar issues.

You sure buddy?
https://github.com/transmission/transmission/issues/218
https://github.com/transmission/transmission/pull/1080

**Comment by GScottElshaw** [comment]
Wait, am I misunderstanding? Why would you expect a different state, and not to be cruel, from every other interface for the last 30 years (software and hardware), that pausing a process pauses it?

**Comment by killemov** [comment]
I'm not sure what you mean. This should have been fixed. If it's not then reopen issue #218.

**Comment by diogoeichert** [comment]
@GScottElshaw I'd expect the transfer to be paused, but not the metadata. Sample use case: adding a new transfer which contains several files, but with an option to select which ones before starting. For that to work, the metadata must have been already downloaded.

**Comment by diogoeichert** [comment]
@killemov I stand corrected. I'll check it again on the latest version. Thanks.

**Comment by GScottElshaw** [comment]
You don't have to look too far here to see numerous complaints that upon completion of metadata there is a pause to begin transfer. Personally, I think it's fine, it's a separate process, and a welcome knowledge that you have the metadata to begin your transfer. But, as they say, YMMV.

> @GScottElshaw I'd expect the transfer to be paused, but not the metadata. Sample use case: adding a new transfer which contains several files, but with an option to select which ones before starting. For that to work, the metadata must have been already downloaded.

**Comment by GScottElshaw** [comment]
You need to restart your router? I think that's emblematic about how opaque bittorrent can be, particularly with individual ISP's. Oh, you're the guy I constantly see at 99.x% and i can't directly give you the last 1 - 2%. I often want to be able to select a specific peer and send data their way.

**Comment by killemov** [comment]
> Oh, you're the guy I constantly see at 99.x% and i can't directly give you the last 1 - 2%. I often want to be able to select a specific peer and send data their way.

Ahw, you got me!
