### ISSUE TITLE
remember tab selection in the Torrent Inspector aka Torrent Properties dialog

### ISSUE THREAD

**Issue by forteller** [transmission/transmission#2300]
Every time I double click a torrent in Transmission it's because I want to select which of the files in the torrent I want to download at the moment. But every time it first opens on the Information tab, and I have to click an extra time to get where I need to go. I understand that different people have different needs, but of the information shown in the Information tab almost half is already shown in the main window, and I find it very likely that I'm a quite commons use case.

If the Files tab could be set as default on double click I think that would be appreciated by most. But of course I might be wrong, and in that case how about either an option for which tab to open first (either in the settings or by dragging and dropping the tabs so you can drag your preferred tab to the first spot) or opening on the tab that was used last?

This is my only big issue with Transmission, otherwise I love it, and I thank you for all your work! :)

**Comment by reportxx** [comment]
I think a good way to make it work is if the last opened window tab was remembered by Transmission so that the next time the window is opened, the tab would open automatically.

**Comment by forteller** [comment]
As long as it is universal, and not remembered for each torrent individually that's totally fine for me.

**Comment by killemov** [comment]
+1
I never understood why the files tab isn't the default. For me, it seems highly unlikely that changes would be made on one of the other tabs. (Max speeds, max peers, ...)

**Comment by ckerr** [comment]
I'm not a fan of defaulting to the File tab every time, but I do like the @reportxx suggestion of remembering the previous tab and using that the next time that the properties / inspector dialog is open
