### ISSUE TITLE
Displayed Upload/download global rates are always 0

### ISSUE THREAD

**Issue by Jedikops** [transmission/transmission#2303]
Im running under docker on my nas.
I've been using transmission for over 2 months and what's been bothering since very beggining is that upload and download displayed rates in top right corner always show zero, even tho torrent are downloaded and uploaded correctly.

In addition, displayed upload  rate for each particular torrent is always 0 as well. So to verify how fast im uploading i need to check that on my router or in cli.
Please help

**Comment by ckerr** [comment]
> that upload and download displayed rates in top right corner

What GUI are you using? What version? Are you connecting to a daemon session, or running locally?

**Comment by ckerr** [comment]
Closing due to lack of a response.
