### ISSUE TITLE
Does not delete torrent data when only one file in torrent

### ISSUE THREAD

**Issue by krendll** [transmission/transmission#2325]
If i try to delete torrent with data, and torrent contains only single file error in log occurs, torrent deleted from list, but file remains on device. Tried from web ui and from Transmission-remote GUI app. If torrent contains multiple files all done as needed.
Transmission-daemon version 37a8046, but it happened at previous versions also.
This torrent as example
magnet:?xt=urn:btih:2a364ddf117e2749fd3f6aefbc857d8af4575691

Log, when try to delete (--log-debug)
```
[2021-12-17 08:46:14.121] Couldn't create "/tmp///ISO Workshop Free 10.5.exe/__IpgIdU": Not a directory (/root/Transmission/libtransmission/file-posix.cc:268)
[2021-12-17 08:46:14.121] ISO Workshop Free 10.5.exe Removing torrent (/root/Transmission/libtransmission/torrent.cc:1643)
[2021-12-17 08:46:14.121] ISO Workshop Free 10.5.exe Pausing (/root/Transmission/libtransmission/torrent.cc:1592)
```

**Comment by ckerr** [comment]
@krendll is this still happening int he latest nightlies?

**Comment by krendll** [comment]
@ckerr tested with 6b440af, deleted correctly. But now magnet stopped working :(, even with transmission-remote cli. 
"Error: invalid or corrupt torrent file" when adding magnet.

**Comment by ckerr** [comment]
@krendll Yikes, that's troubling. Please email me the magnet link at my firstname @ first last dot com so that I can test it out.

**Comment by krendll** [comment]
@ckerr pulled and rebuiled lastest version 0166b6e, all is working like a charm. Magnets adding, singlefile torrents deleting.
