### ISSUE TITLE
Seeding time is larger than (now - done_date)

### ISSUE THREAD

**Issue by ProteinPig** [transmission/transmission#2326]
I use Flexget to manage torrents in transmission, and I found that usually the seeding time is larger than the actual time. 

For example, a seed was finished at 0:00, now is 20:00, and the seeding time may be 22 hours.

using transmission in linuxserver.io's docker image.

**Comment by ckerr** [comment]
What version of transmission are you using?

**Comment by ProteinPig** [comment]
It's v3.00 in linuxserver docker image.

**Comment by valcomm** [comment]
Isn't seeding possible (and counted) from the time the full chunk is present and valid?  As opposed to the time when the whole torrent content was downloaded.  Would be a bug if seeding time was longer than (now - startDate), but if it's just longer than (now - doneDate) it's not a bug as I see it.  Am I wrong about it?

**Comment by ProteinPig** [comment]
OK, here is the data I got from transmission. 
FYI

```
now	                    2022/1/24 8:42	+08:00
date_active 	        2022/1/23 17:25	+08:00
date_added  	        2022/1/22 14:54	+08:00
done        	        2022/1/22 14:54	+08:00
started     	        2022/1/23 17:39	+08:00
secondsDownloading  	0
secondsSeeding	        151621


now-date_added          150497
now-done                150497
```

**Comment by valcomm** [comment]
You've got done < started.  I'd assume that you added, started-1, verified the content you already had, stopped after some time, started-2.
And now 'started' is equal to started-2, but between started-1 and stopped you seeded too and that time was counted as a seeding time.
That's my theory without looking at the code.

**Comment by ProteinPig** [comment]
> You've got done < started.  I'd assume that you added, started-1, verified the content you already had, stopped after some time, started-2.
> And now 'started' is equal to started-2, but between started-1 and stopped you seeded too and that time was counted as a seeding time.
> That's my theory without looking at the code.

You are right, the data is already on the disk. 
So, I don't consider the date_start, I suppose it will always change every time you pause & resume the torrent.
