### ISSUE TITLE
Displaced menu on wayland (caused by deprecated gtk_menu_popup () with gtk 3.22)

### ISSUE THREAD

**Issue by IMFTC** [transmission/transmission#233]
Beginning with gtk 3.22 gtk_menu_popup () has been deprecated. To be sure that menus show up at the correct position with Wayland or Mir the gtk documentation suggests using gtk_menu_popup_at_pointer() and variants instead [0]. The only menu I could see the misplacement in transmission-gtk so far is the right-click menu on a torrent row in the main window. Apparently the issue only reveals itself in a Wayland session with 2 monitors, being vertically shifted by some amount: https://bugzilla.gnome.org/show_bug.cgi?id=772096.

I did a quick successful test, replacing all occurrences of gtk_menu_popup () with gtk_menu_popup_at_pointer(). However, there is more work needed since using _at_pointer() requires gtk 3.22 or later, so for older versions falling back to gtk_menu_popup () would be required.

[0] https://developer.gnome.org/gtk3/stable/GtkMenu.html#gtk-menu-popup

**Comment by digitalpenguin** [comment]
This issue is still occurring.

**Comment by ckerr** [comment]
I'm not able to reproduce this, tested on a Wayland session with two monitors as per original description. This may have been fixed as a side-effect of [migrating to gtkmm](https://github.com/transmission/transmission/pull/1969).

If anyone experiences this problem in newer builds, please file a new issue with updated information. Thank you!
