### ISSUE TITLE
daemon crash with key size error

### ISSUE THREAD

**Issue by nitroshift** [transmission/transmission#2333]
When adding a torrent transmission daemon crashes with the following errors:

1.  daemon.err transmission-daemon[4769]: [2021-12-23 08:50:58.380] tr_crypto_utils CyaSSL error: Key size error, either too small or large (crypto-utils-cyassl.c:260)
2.  transmission-daemon[4769]: [2021-12-23 08:50:59.380] tr_crypto_utils CyaSSL error: unknown error number (crypto-utils-cyassl.c:292)

Transmission-daemon version is 3.00-17

**Comment by ckerr** [comment]
Is this still an issue in `main`?

**Comment by nitroshift** [comment]
@ckerr

Haven't tried latest commits, but at the time I opened the issue it was.

nitroshift

**Comment by nitroshift** [comment]
@ckerr 

I've opened (and closed a few days later) an issue in Openwrt packages git (https://github.com/openwrt/packages/issues/17501#issue-1094232130). Traced the issue to ssl libraries (wolfssl specifically) since reverting to openssl / polarssl fixes it.

**Comment by ckerr** [comment]
Sounds good. Closing as an upstream issue.
