### ISSUE TITLE
Nightly build, Crash v.3.00+ (3f8cf63e59)

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#2348]
[Transmission-2021-12-26-190627.ips.zip](https://github.com/transmission/transmission/files/7777365/Transmission-2021-12-26-190627.ips.zip)

**Comment by ckerr** [comment]
looks like an assertion failure in `tr_torrentStat()`.

@Oleg-Chashko is this a one-time crash, or is it recurring?

**Comment by Oleg-Chashko** [comment]
> looks like an assertion failure in `tr_torrentStat()`.
> 
> @Oleg-Chashko is this a one-time crash, or is it recurring?

Yes, at this point in time, it is a one-time failure.

**Comment by Oleg-Chashko** [comment]
Closed the issue. Since it may have already been fixed. In the near future, the problem was not noticed.
