### ISSUE TITLE
commit #2345 broke Magnet links 

### ISSUE THREAD

**Issue by shinra-electric** [transmission/transmission#2357]
All builds since commit #2345 cannot add torrents via Magnet links. 

Edit: 
To be a bit more clear: from the Jenkins builds, 7477 works fine, 7478 onwards cannot add via Magnet links.

**Comment by GScottElshaw** [comment]
Confirmed here too.

**Comment by HexomediaVR** [comment]
Confirmed for me too.

**Comment by ckerr** [comment]
Just checking in -- this is going to take a few days to fix.

**Comment by robd003** [comment]
Is this still broken on current builds? I haven't updated because I need magnets to work for Linux ISOs

**Comment by GScottElshaw** [comment]
Yes.

**Comment by ckerr** [comment]
Just checking in, I haven't forgotten about this one; I've just been afk a lot this week. This is at the top of my Transmission TODO
