### ISSUE TITLE
Torrents stay in incomplete folder (Windows Client, Linux Service)

### ISSUE THREAD

**Issue by ennorehling** [transmission/transmission#236]
I am running the Transmission service on Linux, with the QT client on Windows. The Windows client suggests a default location based on the Linux folder, but prefixes it a C: drive letter.

If I forget to remove the extraneous C: prefix, the torrent still downloads, because my server is set up to download to an incomplete folder, but the data is never moved out of incomplete, because the destination folder doesn't exist. If I manually select "Set Location", and remove the C:, the server then moves the files from incomplete to the actual downloads directory.

Proposed fix: Make the Windows client not modify the destination directory.

**Comment by mikedld** [comment]
Thanks. Already fixed in f6a19f868a12884bffb66018d056cb21d51aa4c9.

**Comment by DanielDC88** [comment]
Downloaded the latest version from the website and this does not seem to be fixed. Where can I go for the version it is?

**Comment by mikedld** [comment]
@DanielDC88 This change has not been released yet. If you're open to using nightly (not necessarily stable) builds, use one from https://build.transmissionbt.com/job/trunk-win32/lastSuccessfulBuild/.

**Comment by carlosrocca** [comment]
Still not working on 2.94.

**Comment by Freeco80** [comment]
Same here, still adding c:\ to start of the location.
Windows 10 1803 with Transmission client 2.94 (d8e60ee44f)
Synology DSM 6.2 with Transmission 2.94-16 (from SynoCommunity.com)

**Comment by diman82** [comment]
Same problem on ubuntu

**Comment by Mardiie** [comment]
This should be such an easy fix. Shame really.
One would say that if this program gets maintained this would be fixed in a second.

**Comment by ennorehling** [comment]
> 
> 
> This should be such an easy fix. Shame really.
> One would say that if this program gets maintained this would be fixed in a second.

At the risk of offending some people: This kind of comment isn't helpful.

As someone not involved in the development, it is easy to underestimate how hard a fix is. We know nothing about how much testing it needs, how many existing tests will break, and in general, how the maintainer handles release management. It's scheduled to be in 3.0, and apparently already in a branch for that release. Cherry-picking it into an earlier release might just be something the maintainers aren't doing as a general rule. It's not a critical bug, so it gets released together with other bugs when there's a bugfix release, not put in with a minor (security-)release.

Software development is hard, and doesn't get easier when people are second-guessing every decision you make. Either help, or kindly shut up.

The beauty of open source, however, is that you can just build your own version of the code, and merge the patch from f6a19f8 if you really cannot wait. You have the source!

**Comment by Mardiie** [comment]
No need to cry. It's a fact that changing a user path is an easy fix. Or the developers just don't have a clue of what they are doing. As for me, do you think I have the time to go over a codebase that huge to find a bug of a program I just started using? Someone who's used to the codebase should be able to take care of this easy. All I'm saying. No need for your whine. I suggest they start looking in the files.h file. Since with my limited coding knowledge, especially in C, and very little time, I'm pretty sure that's were things go wrong after looking for half an hour. I mean it's just as easy to switch over to a new program, you might want to take care of such a application "breaking" bug, that's been in forever. But who am I to not allow you to have your own opinion, how silly it might be.

**Comment by hardhub** [comment]
Why is it closed?

**Comment by mikedld** [comment]
See https://github.com/transmission/transmission/issues/236#issuecomment-343752027, milestone it set to 3.00.

**Comment by hardhub** [comment]
> 
> 
> See [#236 (comment)](https://github.com/transmission/transmission/issues/236#issuecomment-343752027), milestone it set to 3.00.

OK

Can we download preview?

I can found only 2.94 nightly:
https://build.transmissionbt.com/job/trunk-win32/lastBuild/arch=x64,label=pepito-win10/

**Comment by mikedld** [comment]
I believe you have answered your own question. The link points to 2.94+ build which is built from master branch and which 3.00 will eventually be based on.

**Comment by hardhub** [comment]
I am not sure I understand. I do not know the status of 3.0 version.  
So I assumed if issue is closed then somewhere it can be something like 3.0-alpha.  
And that can be built as preview (nightly) version (similar to what we can see in Firefox releases).

**Comment by jrhoffa** [comment]
This really should be a straightforward fix; I'm saying this as a seasoned developer.  This issue should not be "closed" until the actual fix is delivered in some fashion.

**Comment by AngelFalse** [comment]
> Software development is hard, and doesn't get easier when people are second-guessing every decision you make. Either help, or kindly shut up.

Okay, software development is hard.
And, I do fell the need to, at least, reopen this issue again, this bug **IS NOT FIXED, YET**.

**Comment by kapitan-iglu** [comment]
A can also confirm this issue is still present in 2.94, please reopen it!

**Comment by steathy** [comment]
No offense. Just can't believe this issue has been lasting for 2 years and still keeps going

**Comment by LightBringer81** [comment]
Can confirm, QT still adds C: in front of the download location... :/

**Comment by hardhub** [comment]
@LightBringer81 Try to use version 2.94+, not just 2.94. It works for me good.

**Comment by steathy** [comment]
@hardhub 

where is version 2.94+? From their website the newest windows client version is 2.94.
https://transmissionbt.com/download/

**Comment by LightBringer81** [comment]
> @hardhub
> 
> where is version 2.94+? From their website the newest windows client version is 2.94.
> https://transmissionbt.com/download/

https://github.com/transmission/transmission/issues/236#issuecomment-450026977
It works, but I don't count a nightly version as a solution for an issue in a final version. which is there for over a year... 😒

**Comment by hardhub** [comment]
@LightBringer81 

As server I am using Linux and stable 2.94 version.
As client I am using "transmission-2.94+-ra440981571-x64.msi".
So stable server and such client works fine for me (no crashes and so on).

I guess next version will be 3.0. So it is reason why it is not available. But I am not sure.
