### ISSUE TITLE
Corrupt download after running out of disk space and resuming

### ISSUE THREAD

**Issue by JamesC1** [transmission/transmission#2367]
This happened on a fairly recent version of Bionic Puppy, on a computer that I will resume having access to in mid-January.

I started downloading the torrent version of trisquel_9.0.1_amd64 (linked from here: https://trisquel.info/en/download) and ran out of disk space (~= memory in a tmpfs filesystem).  I resolved that issue.  Transmission let me restart the download, which purported to complete.  The iso did not match the checksums.  I downloaded a copy directly from the FSF, which did match the checksums.

I ran both through xxd into a shell script, which compared them.  There is a block of zeros in the bittorent version, which contains more variable data in the fsf version.

Reading the source-code:

tr_sys_file_write_at in libtransmission/file-posix.cc is free to do short writes:
https://github.com/transmission/transmission/blob/02aa2f46d4c4a50b9a61d5ec83dd5022de68d090/libtransmission/file-posix.cc#L858

readOrWriteBytes in libtransmission/inout.cc does not receive notice of short writes:
https://github.com/transmission/transmission/blob/33553c5331ba576e47303c613fab4307a9b78571/libtransmission/inout.cc#L133

so it seems like there was a single short write, some time after testing that the data was received correctly.

I regard this issue as being a cousin to:
https://github.com/transmission/transmission/issues/1835
and as being apparently mutually incompatible with:
https://github.com/transmission/transmission/issues/1001

The file that exhibits the problem is enormous, and so is the output from my analysis procedure.  Attempting to exhibt a sensible sized version of the evidence, here are some excerpts from the analysis output.  They are xxd lines, with labels T for torrent and F for FSF:

$ head -4 merge.txt
T:03f80000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
F:03f80000: fef5 6666 4c56 2d9d 0000 a43a 2ab0 0249  ..ffLV-....:*..I
T:03f80010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
F:03f80010: 0666 5501 720a 615f 0064 10e8 2dc8 1924  .fU.r.a_.d..-..$
$ fgrep 03fbfff0 merge.txt
F:03fbfff0: 23a5 21d2 5220 31c1 0d51 8025 6c2c 5622  #.!.R 1..Q.%l,V"
T:03fbfff0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
$ fgrep -n 03fc00f0 merge.txt
32630:F:03fc00f0: b998 41dc 3364 9962 bfe2 0799 97ca 9096  ..A.3d.b........
32799:T:03fc00f0: b998 41dc 3364 9962 bfe2 0799 97ca 9096  ..A.3d.b........

ps whether writes should be resumed in file-posix.cc or inout.cc depends on what would give the most consistency with Windows.

**Comment by JamesC1** [comment]
ps whether writes should be resumed in file-posix.cc or inout.cc depends on what would give the most consistency with Windows.

**Comment by killemov** [comment]
The testing is in memory. AFAIK the OS/filesystem accepts the write operation and caches it, only to come to the conclusion the write operation can't actually commit to disk. The only proper way to fix this problem is to either use a different, non-cached write operation or to test for a certain amount of free space (>= 64MB?) before writing.

**Comment by ckerr** [comment]
I don't really understand this bug report, e.g. I don't know what "free to do short writes" or "does not receive notice of short writes" means here?

**Comment by JamesC1** [comment]
Hello Killemov and Charles,

This is a standard (mis-)feature of unix.  If you ask to write j bytes to a
device, then writing 0 < k < j bytes is not an error, for the purposes of
setting errno and whether to return -1.

This makes sense in the context of file descriptors being
device-independent.  It could be a tape or network connection with
user-visible record boundaries, or a network file-system with a hiccough.
It is discussed in "Return Value" here:
https://man7.org/linux/man-pages/man2/write.2.html

I dislike your proposed solution, which I read as second-guessing some set
of causes for short writes (k bytes written, strictly less than the j that
were asked for), because the set of causes is open, and could grow in the
future.

I think that, looking away from the code, the correct response is to loop
around the write, possibly interleaved with other things.  I would expect
it to  continue making progress, or return an error, or block.

The corresponding write on Windows is at line 1156 of here:
https://github.com/transmission/transmission/blob/02aa2f46d4c4a50b9a61d5ec83dd5022de68d090/libtransmission/file-win32.cc

It also returns a length.  I don't know whether it does short writes (less
than (DWORD)size) in practice, but it returns the number of bytes written,
which seems to licence it to.

There may be a minimal response, in the file-*.cc.  It is as follows: if
the write is shorter than the number of bytes requested, and the caller is
not asking for the number of bytes written, then fiat that it has failed
entirely and set the system error to your choice of EIO, ENOSPC and
EAGAIN.  When I relieved the lack of space, the client continued writing.
Confirm that, after entirely failing to write a block and resuming, the
existing software retries it.

Regards,
James the pedant.

**Comment by JamesC1** [comment]
Thank you.  This fix makes sense to me.
