### ISSUE TITLE
Buggy behavior with transmission-gtk and debian-11.1.0-amd64-netinst.iso.torrent

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#2369]
When we interrupt the download, close it, and then re-open `transmission-gtk`, it sees the already downloaded folder with files and attempts to re-write the folder / file structure and segfaults.

On another situation, it works with the following error message:

![image](https://user-images.githubusercontent.com/1777466/147817827-176b7c50-a9ec-44cc-99ff-9ed509dfbbf6.png)

To reproduce this behavior, download the Debian torrent file, start it, let it download a couple of megabytes and then right-click on it to delete it; you should see a folder with the name of the torrent file where you chose to save the downloaded file(s); also notice that this behavior does not actually delete the files at all.

Restart `transmision-gtk` and you should get the error message if you get lucky, else it should segfault.

Version: `3.00+ (d8d361e491)`

**Comment by mikedld** [comment]
Caused by refactoring in #2134.

**Comment by stefanos82** [comment]
Good to know. I haven't deleted the generated folder on purpose; will it delete on re-opening the app?

**Comment by mikedld** [comment]
No, it won't, as Transmission doesn't track it.

**Comment by stefanos82** [comment]
Ah I see. I will delete it as soon as merge takes place so I can try it with the fix.

**Comment by stefanos82** [comment]
I can confirm that it works as expected; good job @mikedld :+1:
