### ISSUE TITLE
Support for µTorrent compatible list

### ISSUE THREAD

**Issue by dotnetCarpenter** [transmission/transmission#237]
I just want to second [the suggestion to support *µTorrent compatible list*](https://forum.transmissionbt.com/viewtopic.php?t=7440).

Basically it's a list of URI's with a line feed between them.

Many torrent sites has a link for *µTorrent compatible list* (in no particular order):
+ https://topkickass.net/shortbus-aka-the-sex-film-project-tt4208883.html#technical
+ https://torrentz2.eu/announcelist_2025273041
+ https://torrentproject.se/78b736d16bbd73a4fde6baaa44783c0a42903bd2/

**Comment by stefantalpalaru** [comment]
Implemented by https://github.com/transmission/transmission/pull/229.

**Comment by dotnetCarpenter** [comment]
@stefantalpalaru Looking through your PR, I failed to see how it works. Can I manually add the list or is done under-the-hood?

Could you attach a screen-shot for us poor time-constraint people who won't `clone` -> `pull branch` -> `build`, just to see how it looks?

**Comment by stefantalpalaru** [comment]
![Qt preferences](https://user-images.githubusercontent.com/495550/27131344-8dd2f786-510a-11e7-825e-7b313ea31006.png)

**Comment by dotnetCarpenter** [comment]
@stefantalpalaru Is it possible to edit the list? Similar to how it works now:
![Adding a tracker](https://cloud.githubusercontent.com/assets/2473545/25580709/6e981b2c-2e59-11e7-8fee-f960cda918ed.png)

In general it's valuable to remove non-answering (dead) trackers and add trackers that are not found by `tor->session->defaultTrackers`.

**Comment by stefantalpalaru** [comment]
Of course it's possible. What you see in the Preferences window is an editable text field. It comes empty and you add the default trackers yourself.

The only catch is that the changes only apply for future torrents (or existing torrents after a restart, but only for adding new default trackers).

**Comment by fernandog** [comment]
@stefantalpalaru is it possible show the tracker status (so dead ones can be removed) ? 

also I think that @dotnetCarpenter asked is to use the same interface as in tracker tab in torrent properties. But using that interface won't be possible to copy&page the entire list of trackers, right ?

**Comment by stefantalpalaru** [comment]
You can already see the tracker status in the tracker list of an individual torrent. I don't want to complicate it by copying that functionality in what is better expressed as a simple, editable, text box.

No, it makes no sense to use per tracker input boxes instead of a common text box for the whole list (at least in my intended usage scenario).

**Comment by dotnetCarpenter** [comment]
I'm fine with not using the single torrent tracker list interface. I just wanted to show an image where it is possible to add/remove trackers and the one posted in #257 was readily available.

@stefantalpalaru I didn't get that it was default trackers for all torrents. Got it. This feature is awesome. Don't have enough thumbs up but suffice to say - great work @stefantalpalaru!

Closing this when #229 is merged.

**Comment by stefantalpalaru** [comment]
Thanks.

**Comment by fernandog** [comment]
@stefantalpalaru do you validate the list like If all parses as URL?

**Comment by stefantalpalaru** [comment]
Yes, with ```tr_urlIsValidTracker(url)```.

**Comment by zero77** [comment]
Is this possible in the web-ui or in the settings.json file.

**Comment by slrslr** [comment]
On Windows 10, transmission 2.94 **i am unable to find how to add multiple trackers at once to the torrent**. It also is not in settings.json, in program Settings.

**Comment by lubieowoce** [comment]
@slrslr me neither :( as a workaround, i'm using [transgui](https://github.com/transmission-remote-gui/transgui) which lets you copy-paste a list of trackers per torrent (no default tracker list though).

(in case anyone needs help with setting up transgui: enable Remote Access in Transmission's settings, open transgui, and set the address to `localhost`)

**Comment by Kintawesar** [comment]
@slrslr me too, but on mac os x

**Comment by peerless2012** [comment]
It may be great to support a url to fetch lots of tracks at onece, just like the BitConet on Windows.

**Comment by DJPatron** [comment]
Still impossible. Please, add this feature onto windows version.

**Comment by erhan-** [comment]
Too bad something like this is still not in the GUI after so many years and needs workarounds.

**Comment by ckerr** [comment]
This feature exists now in transmission-gtk and transmission-qt (i.e. the Windows version) as of https://github.com/transmission/transmission/pull/2642.

**Comment by erhan-** [comment]
I want to thank in the name of everyone who was interested into this. Thanks for taking your time!
