### ISSUE TITLE
"Remove Data File" not working under nightly build Build #7495 on M1

### ISSUE THREAD

**Issue by tsegreto** [transmission/transmission#2379]
When I click "Remove Data File" - the torrent is removed from Transmission but the data file is not removed from my downloads folder. Running an M1 Mac. Nightly build #7495

**Comment by ckerr** [comment]
Is this behavior still happening? I'm not able to reproduce it when testing locally.

**Comment by fxcoudert** [comment]
I cannot reproduce that either.

**Comment by gspannu** [comment]
I am getting the same bug as well. Deleting data file does not delete the downloaded file !Running latest version on MacBook Pro M1 Pro

**Comment by Coeur** [comment]
Not reproducing on M1 Mac with either complete downloads or .part downloads, using today's nightly.
Please offer more details if it still happens:
- was it a folder or a file?
- is it systematic or occasional?
- did you happen to have multiple torrents downloading/sharing the same file?

You may reply to this issue and I'll re-open it if above questions are answered together with the precise nightly build being used.
