### ISSUE TITLE
How to override IP to be reported to trackers?

### ISSUE THREAD

**Issue by enihcam** [transmission/transmission#238]
(Simplified version) I have two interface, ppp0 and tun0 (to VPN hosted in cloud).

The transmission service connects to trackers via tun0, so I assume the cloud IP is reported to the trackers.

How can I override it with local IP (the one from ppp0)?

Thanks!

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

**Comment by Mosney** [comment]
@enihcam So, would you find the method to set IP to report to tracker?

**Comment by darkk** [comment]
(A comment for those who land here coming from Google search)

As far as I see, the current `master` branch (v3.00+) does not support this feature.

`announcer-udp.c` unconditionally sets `ip` field to zero (the one [between "event" and "key"](https://libtorrent.org/udp_tracker_protocol.html)):
https://github.com/transmission/transmission/blob/cf9b81eb7d21b57309581e515bab9f753f3fdd76/libtransmission/announcer-udp.c#L336-L349

`announcer-http.c` does not send `ip` field as well:
https://github.com/transmission/transmission/blob/cf9b81eb7d21b57309581e515bab9f753f3fdd76/libtransmission/announcer-http.c#L61-L126

So, if I understand it correctly, transmission does not support seeding from an "local" IP while connecting to the tracker via proxy/VPN. On the other hand, it's unclear to me if _any_ of the trackers actually respects the IP address that is sent in the announce message as this feature may have some abuse potential.

**Comment by abouvier** [comment]
> So, if I understand it correctly, transmission does not support seeding from an "local" IP while connecting to the tracker via proxy/VPN. On the other hand, it's unclear to me if _any_ of the trackers actually respects the IP address that is sent in the announce message as this feature may have some abuse potential.

`hefur` [respects](https://github.com/abique/hefur/blob/master/manual/manual.md#run-the-server) this parameter when the option `-allow-proxy` is used.
