### ISSUE TITLE
Feature request: In "Set Location" dialog, offer 3 or 5  latest folders instead of only 1

### ISSUE THREAD

**Issue by Markus-N** [transmission/transmission#2380]
I'm using multiple downlaod folders for different categories of torrents. This means that I use the "Set Location" dialog a lot.

At least on Linux with XFCE desktop, the dialog offers only one last recently chosen folder in the *torrent location* drop down menu.  
The options look like this:
* home
* Desktop
* File System
* {latest chosen folder}
* Other ...

My life would be easier if there were more *latest chosen folders*. 3 would already help a lot, but 5 would be better. Or maybe the number could be configurable in the settings. However, if this is much more work, a fixed number would do.

**Comment by mikedld** [comment]
Thanks for reporting this, I'll take a look.

Options dialog uses 4: https://github.com/transmission/transmission/blob/a5c61688050aff376b24f58a600f9acbfbf627aa/gtk/OptionsDialog.cc#L34-L78

While relocate dialog saves just one: https://github.com/transmission/transmission/blob/a5c61688050aff376b24f58a600f9acbfbf627aa/gtk/RelocateDialog.cc#L25

**Comment by barn4k** [comment]
bump. Same for Windows. It's quite annoying to choose a folder every time ( for example I've downloaded a set of 10 audio books and I need to specify the path for each of them as my default leads to the tw shows folder)
