### ISSUE TITLE
Allow users to manually select piece size of newly created torrents

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#2416]
Transmission is falling behind by not having features like the ability to manually select a newly created torrent's piece size so we need to have this feature ASAP. This feature has been in pretty much every client since uTorrent and it's about time Transmission also has it. Piece size selection is more important than ever as torrent sizes are bigger than ever, and they are not going to get any smaller. 

If we want Transmission to gain more users and more contributors, we need to be willing to have the same basic features as other popular open-source torrent clients. 

- qBittorrent has piece size selection
- Deluge has piece size selection
- ktorrent has piece size selection
- BiglyBT has piece size selection

Please implement piece size selection! For the good of the project, if nothing else!

**Comment by ckerr** [comment]
FWIW, you can do this right now in the command-line utility `transmission-create`.

I don't find the "falling behind" "more important than ever" and "for the good of the project", since Transmission's GUI apps have never had this feature and I can only remember a few people ever asking for it. So evidence suggests this isn't a feature that most people care about.

That said, I'm not _against_ the feature, it just doesn't seem super important. If someone feels differently and wants to put in a PR, I'd be happy to do code review.

**Comment by Pentaphon** [comment]
> FWIW, you can do this right now in the command-line utility `transmission-create`.

I'm aware of this but I would wager that most users do not torrent via the command line at all. A simple dropdown box with all the available piece sizes and the resulting number of pieces, as found in every other open source client, would make the torrent creator window more useful by giving users manual control of the torrent files they create.

>So evidence suggests this isn't a feature that most people care about.

I would say that this is simply because no matter what torrent client people use, most people do not create torrents at all. Most people just load torrents into their client. However, in order for the torrent community to keep going, somebody has to create more torrents and making sure Transmission has a similar level of functionality as other clients when creating torrents would ensure that power users that create torrents do not dismiss Transmission because it lacks basic functions that other clients have. Therefore, it is important to at least welcome PRs that keep Transmission relevant in the minds of torrent software users, so I'm glad you're open to this feature request. Thanks for that.

**Comment by ckerr** [comment]
If someone wants to write this PR, I'm happy to review it.

**Comment by Pentaphon** [comment]
@ckerr so this is only for the MacOS GUI and NOT the Linux and Windows GUI, correct? Should I open another issue for Linux and Windows? Or does this new PR actually close it for Windows and Linux as well?

**Comment by azy5030** [comment]
It does not. It only added it for MacOS.
