### ISSUE TITLE
Add option to force IPv4, since some trackers do not support IPv6

### ISSUE THREAD

**Issue by Deepcuts** [transmission/transmission#242]
Using Transmission 2.94 (14714) on Windows 10 x64
My network uses Squid 3.5.12 on Ubuntu Server 16.04, intercept proxy for TCP 80.
Proxy runs on router box.
IPv6 disabled on router and client.
Internet connection is PPPoE.
Using 8.8.8.8 and 8.8.4.4 DNS servers on router.
AAAA has precedence on client and I cannot find a way to disable them. My guess, this is where the error originates, but cannot be sure.

```
>nslookup google.com
Server:  router.local
Address:  192.168.100.1

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:400d:806::200e
                 216.58.214.206
```

Some trackers will give the error:  **Tracker gave a warning: Illegal character found in IP address. IPv6 is not supported**
The error is not displayed if intercept proxy is disabled.
Download and upload does not seems to be affected on client machine.

Any way to disable IPv6 in Transmission (Windows)?
Or a hint as to why this error comes up?

Thank you.

**Comment by msg7086** [comment]
Try this [workaround](https://randomtechminutia.wordpress.com/2012/08/13/tweak-registry-to-make-windows-always-prefer-ipv4-over-ipv6/)?

**Comment by tearfur** [comment]
Closing since this is no longer relevant from 85a00625dc9c2e0ab1718340619203219f44212f and onwards.
