### ISSUE TITLE
Cannot connect to https trackers on macOS

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2429]
<sup>Originally posted by **GScottElshaw** January 17, 2022</sup>

An extremely longstanding bug on MacOS since 3.0, and still occurring in the nightlies, the inability to connect with certain trackers, most notably trackers using SSL. There are multiple references to this issue in a number of discussions [here with a user on Monterey](https://github.com/transmission/transmission/discussions/2128#discussioncomment-1702525) and elsewhere. I remember seeing this bug on Catalina, and possibly before, and it exists on Big Sur. 

Essentially, if the tracker has https, forget about connecting to it.

Depending on the number of peers (I'm a former film lecturer and have _extremely_ esoteric taste), I have to use a different client that can connect with these trackers, then open the torrent in Transmission for seeding. I'd love it if I could just use Transmission, and not just because I loathe the other clients.</div>

**Comment by ckerr** [comment]
@GScottElshaw do you have a public https tracker you can suggest that I test with?

**Comment by GScottElshaw** [comment]
https://tpb.tracker.thepiratebay.org/announce

But there are a bunch of other common trackers I can _never_ connect with using Transmission.

udp://coppersurfer.tk:6969/announce
udp://tracker.leechers-paradise.org:6969/announce

**Comment by ckerr** [comment]
(udp is a whole different topic. Maybe open a separate issue for that problem)

**Comment by GScottElshaw** [comment]
> (udp is a whole different topic. Maybe open a separate issue for that problem)

Ironically, it is almost _**exclusively**_  udp servers i _can_ connect to.

**Comment by ckerr** [comment]
> https://tpb.tracker.thepiratebay.org/announce

Does that tracker actually exist?

```sh
$ ping tpb.tracker.thepiratebay.org
ping: tpb.tracker.thepiratebay.org: Name or service not known
```

**Comment by GScottElshaw** [comment]
Usually, but there are plenty more. The point was that all of them fail on varying MacOS's. I wish I could remember what it's called, but the last 2 or 3 iterations of MacOS have been using a different certificate process and it's been an impediment using Transmission. Wiser than I have been discussing this here.  The thread i linked to had another thread with Tockman suggesting using Mozilla's certificate files. I tried the Mozilla certificates.perm. No change for me, but apparently worked for others on earlier OS's.

https://220.162.244.175:53880/announce

https://www.ipmart-forum.com:2710/announce

https://tracker2.istole.it:60500/announce

https://tracker.deluxebits.to:3552/announce

https://tracker.torrentbox.com:2710/announce

https://tracker.hexagon.cc:2710/announce

https://tracker.torrent.to:2710/announce

https://axxo.sladinki007.net:6500/announce

https://www.torrent-downloads.to:2710/announce

**Comment by ckerr** [comment]
I'm not sure that I'm understanding this bug report.

Do you have an example of a tracker announce URL that consistently works outside of Transmission, but consistently fails in Transmission, so that I can test with it?

**Comment by GScottElshaw** [comment]
Charles, can you please send some time looking through the MacOS discussions here, there are multiple users who cannot connect to https trackers. I'm sorry i can't direct you to the conversation from late last year where there was a good discussion about Apple's changes in certificates. It was part of the overhaul in 2020. https://support.apple.com/en-us/HT211025

**Comment by ckerr** [comment]
Does https://github.com/transmission/transmission/issues/1338#issuecomment-653256556 solve the issue you're seeing?

**Comment by GScottElshaw** [comment]
No, i'm afraid not, Charles. There were a bunch of conversations about this late last year, I just wish i could find them to point you to the diagnosis. This was one of the conversations https://github.com/transmission/transmission/issues/1876

**Comment by ckerr** [comment]
> Charles, can you please send some time looking through the MacOS discussions here, there are multiple users who cannot connect to https trackers.

Man, I don't know what to tell you. I don't even run Transmission on MacOS. Maybe @livings124 can do some legwork on this.

I've done nothing but work on Transmission over this long three-day MLK weekend and today I've been getting shit from users for PRs that I didn't merge back in 2018 when I was away from the project. And when I ask a direct question "is there a tracker that consistently works..." and the answer I get back is "please spend some time looking through the MacOS discussions" ... it just makes me feel very tired.

**Comment by Tockman** [comment]
In fact, this problem exists and it's very annoying. I suffer of it every day because I use some torrent tracker for my regular needs. By default its torrent files content https-tracker address only so I have every time to add http-tracker manually which is very uncomfortable (and it's great luck they have one!). Unfortunately, that's a private tracker so you need a private passkey to connect, and I can't give it to you, by clear reasons.
![Bluebird](https://user-images.githubusercontent.com/74548419/149889380-64888dfc-7227-491e-aaa6-5fb482d119fb.png)

**Comment by Tockman** [comment]
> Does [#1338 (comment)](https://github.com/transmission/transmission/issues/1338#issuecomment-653256556) solve the issue you're seeing?

Well, if you would advise where to insert TR_CURL_SSL_NO_VERIFY in macOS. That's solution for Debian, AFAIK.

**Comment by ckerr** [comment]
> > Does [#1338 (comment)](https://github.com/transmission/transmission/issues/1338#issuecomment-653256556) solve the issue you're seeing?
> 
> Well, if you would advise where to insert TR_CURL_SSL_NO_VERIFY in macOS. That's solution for Debian, AFAIK.

The environment variable isn't OS-specific.

TBH it's probably not practical to require every macOS  user to update their pem file.

If I'm reading [this](https://blog.bytesguy.com/resolving-lets-encrypt-issues-with-curl-on-macos) correctly, this affects macOS 10.15 and below, correct? Maybe the code should just unconditionally turn off verification on <= 10.15. That's kind of ugly, but it's better than not working at all.

_If_ that is the case, all we would need is a programmatic way in C of determining what version of macOS we're running on. Probably something like KERN_OSTYPE and KERN_OSRELEASE in sysctl

**Comment by Tockman** [comment]
> TBH it's probably not practical to require every macOS user to update their pem file.
Well, I agree. Moreover, operation of updating .pem file didn't give me any result.

> If I'm reading [this](https://blog.bytesguy.com/resolving-lets-encrypt-issues-with-curl-on-macos) correctly, this affects >macOS 10.15 and below, correct? Maybe the code should just unconditionally turn off verification on <= 10.15. That's kind >of ugly, but it's better than not working at all.
In my case the problem began on Monterey, before macOS 12.1 release.

> sysctl kern.osrelease
> sysctl kern.version
> sysctl kern.osrevision
kern.osrelease: 21.3.0
kern.version: Darwin Kernel Version 21.3.0: Mon Jan  3 23:49:26 PST 2022; root:xnu-8019.80.24~15/RELEASE_X86_64
kern.osrevision: 199506

**Comment by GScottElshaw** [comment]
> it just makes me feel very tired.

I'm truly sorry about that, Charles, i noticed some of those comments too and half expected to hear back in allcaps, "You're all ungrateful swine, and this horse is heading off with Mr Jones off the farm". I'm sorry i've added to the workload, i just noticed you were available later than i usually see you (timezones etc).

**Comment by GScottElshaw** [comment]
> ```shell
> sysctl kern.osrelease
> sysctl kern.version
> sysctl kern.osrevision
> ```

kern.osrelease: 20.6.0
kern.version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
kern.osrevision: 199506

**Comment by ckerr** [comment]
OK so _if_ the environment variable works, then we could check sysctl and, say, turn off ssl verification for <= 199506.

I see from the other thread that there's some ambiguity there about whether or not setting the environment variable works. To remove that ambiguity I'll make a draft PR that unconditionally turns it off. CI will make binaries for that PR and y'all can test running with those built binaries to see if it works. Then I can close the PR (since this was just a test, we wouldn't want to always disable on all OSes) and try it with sysctl.

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/pull/2439

**Comment by ckerr** [comment]
OK CI has made test binaries that just [unconditionally disable ssl verification](https://github.com/transmission/transmission/pull/2439/commits/2ceb7888f3b17cbd8b218b3682dfc983fded9a15).

https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_MacOSX8664xcodebuild/164821?buildTab=artifacts#%2Fbinaries.zip

Could y'all test these and see if it resolves the https tracker connection problem?

**Comment by Tockman** [comment]
@ckerr
It's alright apart from that it requires log in to download ;)

**Comment by ckerr** [comment]
> @ckerr It's alright apart from that it requires log in to download ;)

@Tockman sometimes irony doesn't translate well in text so I'm not sure how to read your answer. Are you saying that you tested it and it works? Or that you didn't click on "Log in as guest" and so haven't tested yet? :smile_cat:

**Comment by Tockman** [comment]
Oh yes, I just found this option.
Sorry for misunderstanding.

**Comment by Tockman** [comment]
Alas, still "could not connect to tracker" with https :(

**Comment by GScottElshaw** [comment]
Afraid not here too Charles. That message from the Transmission info log i posted last year is irrelevant?

2021-12-13 13:54:08 +0000 web.cc:425 [Info] web: will verify tracker certs using envvar CURL_CA_BUNDLE: none
2021-12-13 13:54:08 +0000 web.cc:426 [Info] web: NB: this only works if you built against libcurl with openssl or gnutls, NOT nss
2021-12-13 13:54:08 +0000 web.cc:427 [Info] web: NB: invalid certs will show up as 'Could not connect to tracker' like many other errors

**Comment by ckerr** [comment]
Closing this as a dupe of #1876, since the two tickets are now discussing the same issue.

**Comment by esabol** [comment]
> OK CI has made test binaries that just [unconditionally disable ssl verification](https://github.com/transmission/transmission/pull/2439/commits/2ceb7888f3b17cbd8b218b3682dfc983fded9a15).
> 
> https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_MacOSX8664xcodebuild/164821?buildTab=artifacts#%2Fbinaries.zip
> 
> Could y'all test these and see if it resolves the https tracker connection problem?

Thanks for this. This worked for me on Mac OS High Sierra.

(This version of Transmission seems to have a different problem, fwiw. Switching to different panes of the Torrent Inspector doesn't work, but that's less critical. 😄 )

**Comment by tabanger** [comment]
FYI, as discussed in #1876, the issues raised by @GScottElshaw and @Tockman in this ticket are NOT related to the DST Root CA X3 expiration.

@GScottElshaw, I have tested the list of trackers you listed earlier.  You asked for "a step by step method for users".  Use "curl" for the announce URL.  This is exactly what Transmission does (note, this is only for HTTP/HTTPS trackers).

Here are the test results and an explanation for the failure of each:

**Connection timed out (means there is probably no server at that IP address, or the remote port is silently firewalled):**
$ curl https://220.162.244.175:53880/announce
curl: (7) Failed to connect to 220.162.244.175 port 53880: Operation timed out
$ curl https://www.ipmart-forum.com:2710
curl: (7) Failed to connect to www.ipmart-forum.com port 2710: Operation timed out
$ curl https://tracker.hexagon.cc:2710/announce
curl: (7) Failed to connect to tracker.hexagon.cc port 2710: Operation timed out
$ curl https://axxo.sladinki007.net:6500/announce
curl: (7) Failed to connect to axxo.sladinki007.net port 6500: Operation timed out


**Connection refused (means there is a server there, but it is not accepting connections on that port):**
```
$ curl https://tracker2.istole.it:60500/announce
curl: (7) Failed to connect to tracker2.istole.it port 60500: Connection refused
```

**Could not resolve host (hostname no longer exists in DNS):**
```
$ curl https://tracker.torrentbox.com:2710/announce
curl: (6) Could not resolve host: tracker.torrentbox.com
$ curl https://tracker.deluxebits.to:3552/announce
curl: (6) Could not resolve host: tracker.deluxebits.to
$ curl https://tracker.torrent.to:2710/announce
curl: (6) Could not resolve host: tracker.torrent.to
```

So, @GScottElshaw, that means that all the trackers you listed are all defective or non-operational in one way or another.  It's not a problem with your system or with Transmission.  If you have other trackers you're having problems with, list them here, and we can take a look at them.

**Comment by GScottElshaw** [comment]
Stating the obvious, point me to a non udp http/https tracker i can connect to. This is a list of trackers from late last year that featured in an article about connectivity and live trackers. I cannot connect to any of these.

https://tracker.parrotsec.org:443/announce

https://tracker.moxing.party:6969/announce

https://tracker.ipv6tracker.ru:80/announce

https://tracker.fastdownload.xyz:443/announce

https://gwp2-v19.rinet.ru:80/announce

https://tr.kxmp.cf:80/announce

https://explodie.org:6969/announce

https://tracker.dutchtracking.com:80/announce

https://grifon.info:80/announce

https://182.176.139.129:6969/announce

https://tracker.bt-hash.com:443/announce

https://denis.stalker.h3q.com:6969/announce

**Comment by GScottElshaw** [comment]
I'm including @Tockman in case he has had a similar experience in the past or present.

**Comment by Tockman** [comment]
I had problem lately with only one SSL tracker - it's https://teamhd.org:443/announce. All I succeeded to know from it's owners is they used OpenSSL 1.0 and didn't have in mind any upgrade.

**Comment by GScottElshaw** [comment]
That's really interesting.

**Comment by tabanger** [comment]
> Stating the obvious, point me to a non udp http/https tracker i can connect to.

Sure!  http://opentracker.i2p.rocks:6969/announce is an open tracker (using HTTP) that I just tested and is working right now.  You can first test it with curl, and you should see a response like this:

```
$ curl http://opentracker.i2p.rocks:6969/announce
<title>Invalid Request</title>
```
"<title>Invalid Request</title>" is a response from the HTTP server ("Invalid" because we didn't send a BitTorrent announce), so we know the connection worked.

You should also be able to add that announce URL to any of your public torrents in Transmission, and it should work.

I will look at the new list of trackers you just provided now.

**Comment by GScottElshaw** [comment]
That is the first http tracker i've seen with connectivity. As i said earlier, udp has seemingly been the only choice. I have yet to connect with an https tracker for the last 3 iterations of the OS.

**Comment by tabanger** [comment]
https://tracker.parrotsec.org:443/announce - this one, you should not get a connection error to, but it has Cloudflare DDoS protection in front of it, and there's a gateway timeout to the origin server on the backend.  I'm not sure how that would manifest in Transmission.  

https://tracker.moxing.party:6969/announce - this one has a weird.  It has multiple IP addresses, and doesn't seem to actually offer HTTPS on the designated port:
```
$ host tracker.moxing.party
tracker.moxing.party has address 52.70.94.249
tracker.moxing.party has address 13.234.33.230
tracker.moxing.party has address 54.93.194.194
tracker.moxing.party has IPv6 address 2600:1f18:1555:6211:911c:b425:3ac0:f127

$ ./testssl.sh -p https://tracker.moxing.party:6969/announce

Testing all IPv4 addresses (port 6969): 13.234.33.230 54.93.194.194 52.70.94.249
-----------------------------------------------------
 Start 2022-02-05 01:19:34        -->> 13.234.33.230:6969 (tracker.moxing.party) <<--

 Further IP addresses:   52.70.94.249 54.93.194.194
                         2600:1f18:1555:6211:911c:b425:3ac0:f127 
 rDNS (13.234.33.230):   ec2-13-234-33-230.ap-south-1.compute.amazonaws.com.

 13.234.33.230:6969 doesn't seem to be a TLS/SSL enabled server
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) --> yes
 Service detected:       Couldn't determine what's running on port 6969, assuming no HTTP service => skipping all HTTP checks

 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    not offered
 TLS 1.3    not offered

You should not proceed as no protocol was detected. If you still really really want to, say "YES" --> No
```

**No DNS on these:**
$ curl https://tracker.ipv6tracker.ru:80/announce
curl: (6) Could not resolve host: tracker.ipv6tracker.ru
$ curl https://tracker.fastdownload.xyz:443/announce
curl: (6) Could not resolve host: tracker.fastdownload.xyz
$ curl https://tracker.fastdownload.xyz:443/announce
curl: (6) Could not resolve host: tracker.fastdownload.xyz
$ curl https://tracker.dutchtracking.com:80/announce
curl: (6) Could not resolve host: tracker.dutchtracking.com
$ curl https://denis.stalker.h3q.com:6969/announce
curl: (6) Could not resolve host: denis.stalker.h3q.com

**These have the same issue as the protocol one above:**
$ curl https://grifon.info:80/announce
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
$ curl https://tr.kxmp.cf:80/announce
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Connection timed out:**
$ curl https://explodie.org:6969/announce
curl: (7) Failed to connect to explodie.org port 6969: Operation timed out
$ curl https://gwp2-v19.rinet.ru:80/announce
curl: (7) Failed to connect to gwp2-v19.rinet.ru port 80: Operation timed out

**This is the only one that MIGHT work, but it has a self-signed certificate that you'd have to accept (or ignore) first:**
$ curl https://tracker.bt-hash.com:443/announce
curl: (60) SSL certificate problem: self signed certificate

So, that 2nd list of trackers is basically a bum list too.  Do you need a list of good trackers or something?  Try [this](https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt).  That list is constantly updated with valid, working trackers.  He also maintains a list of [HTTP](https://github.com/ngosang/trackerslist/blob/master/trackers_all_http.txt) and [HTTPS](https://github.com/ngosang/trackerslist/blob/master/trackers_all_https.txt) trackers.

**Comment by GScottElshaw** [comment]
That first one.

https://tracker.parrotsec.org:443/announce "Scrape error: Tracker gave HTTP response code 403 (Forbidden)...."

**Comment by tabanger** [comment]
Yeah, like I said, that's because of the Cloudflare DDoS protection and origin server failure.

Like I said, try the [HTTPS trackers list](https://github.com/ngosang/trackerslist/blob/master/trackers_all_https.txt) I gave you.  It looks like those are all active and working right now.

**Comment by GScottElshaw** [comment]
In Transmission, the response is the same."Scrape error: Tracker gave HTTP response code 403 (Forbidden)...."

In CURL

 Last login: Sat Feb  5 23:23:46 on ttys000
garyelshaw@Oreanui ~ % curl https://tracker.nanoha.org:443/announce
<title>Invalid Request</title>
garyelshaw@Oreanui ~ % 

In transmission the same error, in CURL:

garyelshaw@Oreanui ~ % curl https://tracker.lilithraws.org:443/announce
d14:failure reason31:no info_hash parameter suppliede%

**Comment by tabanger** [comment]
Those curl outputs are good.  Connection is fine.

A scrape error is different from an announce error.  Those trackers may not support scrape.  What does it say in Transmission under the "Last Announce" section?  Or post a screenshot of your tracker tab.

In any case, you're not having connection errors (TCP or TLS).  Those are all valid connections and responses.  Based on the 2 lists you posted earlier, it seems like your problems were just that you had a bunch of invalid/defunct trackers.

**Comment by Tockman** [comment]
@tabanger
```
dmitrytockman@iMac-Dmitrij ~ % curl https://teamhd.org:443/announce            
dmitrytockman@iMac-Dmitrij ~ %
```

**Comment by tabanger** [comment]
So, your curl output is fine with no errors (the same as my tests).  That means the server is fine, their SSL certificate is fine, the remote network is fine, your system's acceptance and validation of the SSL certificate is fine, your local network is most likely fine.  And, it also means that, in general, your system doesn't have a problem because curl can connect.

So, are you getting the announce error that is shown in the screenshot you posted earlier in this thread?  "Could not connect to tracker"

That means that the most likely explanation at this point, is that there is something locally on your computer blocking Transmission specifically.  Do you have any firewall software blocking or filtering outbound connections at the process level on your computer, something like Little Snitch being the most popular example?

I went through your post history in the other ticket, and at one point you said:  "something weird is going on with some of SSL trackers. My Transmission is able to connect to some of them and unable to another ones".  If you could list all the HTTPS trackers you're trying to connect to, including with port, and indicate whether they connect or don't connect, that might help in diagnosing the issue.

**Comment by Tockman** [comment]
> That means the server is fine, their SSL certificate is fine

I doubt this specifically because I have not that problem with any other SSL-trackers.

> So, are you getting the announce error that is shown in the screenshot you posted earlier in this thread? "Could not connect to tracker"

Exactly.

> Do you have any firewall software blocking or filtering outbound connections at the process level on your computer, something like Little Snitch being the most popular example?

No and no.

> If you could list all the HTTPS trackers you're trying to connect to, including with port, and indicate whether they connect or don't connect, that might help in diagnosing the issue.

Now the single one is problematic, and it's noticed on my screen shot: https://teamhd.org:443/announce. As I mentioned before, tracker's owners have told me, on my demand, that they got Open SSL 1.0 installed (for the matters of backward compatibility) and had no any intention to upgrade it (up to the latest 3.0, for example). But I believe that even dealing with such server configuration Transmission might keep an ability to connect tracker by SSL protocol.

**Comment by tabanger** [comment]
> I doubt this specifically because I have not that problem with any other SSL-trackers.
If you know how to read these reports, then you'll recognize that this confirms that their server configuration is fine for HTTPS:
https://www.ssllabs.com/ssltest/analyze.html?d=teamhd.org

If you have not seen this kind of report before, then you'll have to trust me that it means everything is OK on the server side.

> Now the single one is problematic, and it's noticed on my screen shot: https://teamhd.org:443/announce.
So, your Transmission is currently (right now) connecting to other HTTPS trackers successfully?  Can you provide the announce addresses for those also?

**Comment by Tockman** [comment]
> If you know how to read these reports, then you'll recognize that this confirms that their server configuration is fine for HTTPS: https://www.ssllabs.com/ssltest/analyze.html?d=teamhd.org

Thank you, it's very informative. 

> So, your Transmission is currently (right now) connecting to other HTTPS trackers successfully? Can you provide the announce addresses for those also?

https://bluebird-hd.org:443/announce, for example.

**Comment by tabanger** [comment]
It looks like we got the wrong URL for testing for teamhd.org.  Here is the correct announce URL, can you try testing this with curl and provide the output?

https://teamhd.org:443/announce.php

**Comment by Tockman** [comment]
Without  passkey:
```
dmitrytockman@iMac-Dmitrij ~ % curl https://teamhd.org:443/announce.php
d14:failure reason35:Missing required parameter: passkeye%
```

With passkey:
```
dmitrytockman@iMac-Dmitrij ~ % https://teamhd.org:443/announce.php?passkey=xxx
zsh: no matches found: https://teamhd.org:443/announce.php?passkey=xxx
```

**Comment by esabol** [comment]
@Tockman : You need to put single quotes around the URL in the second command.

**Comment by Tockman** [comment]
```
dmitrytockman@iMac-Dmitrij ~ % curl 'https://teamhd.org:443/announce.php?passkey=xxx'
d14:failure reason37:Missing required parameter: info_hashe%
```

**Comment by Tockman** [comment]
I've just updated my macOS up to 12.3 b2, disabled TR_CURL_SSL_NO_VERIFY script, restarted... and now Transmission connects successfully to teamhd.ord:443! Knock wood...

**Comment by tabanger** [comment]
Yeah, so your curl output is still fine.  I just wanted to make sure of that with the correct URL.

So, I'm not sure why there's any difference between calling curl manually, and when Transmission calls curl.  The fact that there's a difference every time you update your OS and restart your computer seems to indicate there's something at a process level affecting something.

In the future, if you have problems, there are some things you can try:

1.  enable curl verbose mode as described by @ckerr [here](https://github.com/transmission/transmission/issues/2546#issuecomment-1025933580).  There may be some clue in the ensuing console logs.
2. Try creating a new user profile on your system and use Transmission on there.  That may eliminate any user-level process issues.
3.  Install a fresh system and try Transmission from there.  This would eliminate any potential system-level issues.  You can test this by booting into Recovery mode (cmd-R at boot) and then install macOS on an external USB drive or create a separate partition on your internal drive.

TR_CURL_SSL_NO_VERIFY is not doing anything for you at this point, because there are no certificate verification issues at play here, either on the server side or your computer's side.
