### ISSUE TITLE
Update from 2.94 leaves immutable torrents

### ISSUE THREAD

**Issue by dbeinder** [transmission/transmission#2430]
In earlier versions, transmission-daemon stored the torrent files with names like "{name}.{truncated_hash}.torrent"
In the current master, it is only {hash}.torrent

When running the current master with an old config directory, this leads to all torrents being re-checked on startup, and even if they are deleted, they re-appear on the next start. Renaming the stored torrent files to {hash}.torrent fixed the problem for me, but this should be done automatically.

**Comment by ckerr** [comment]
What build are you testing with? Specifically what commit or build number?

**Comment by GScottElshaw** [comment]
> What build are you testing with? Specifically what commit or build number?

Possibly related. https://github.com/transmission/transmission/pull/2415#issuecomment-1014888016

**Comment by dbeinder** [comment]
I missed the master->main rename, so I just rebuilt from f415de0626cd88ad9b4cbedba10c53dfad0a24c8 and tested again
Now {hash}.torrent files are created, but the originals are not deleted and re-added after every restart of the daemon.
My 2.94 installations has created torrent files like this: [repro.zip](https://github.com/transmission/transmission/files/7885347/repro.zip)
