### ISSUE TITLE
Information lost upon restart in macOS nightlies

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2434]
A restart of 3.00+ (db23ca4) can wipe out all of the torrents and/or torrent information from the previous session on MacOS Big Sur. The same behaviour is consistent across builds (6b440af) and (bcf5e46). Definitely related to the files in the Application Support folder, looking at the times and dates of the contents in the Resume folder and the Transfers.plist, it looks like end-of-session information isn't being written to these files when quitting.

**Comment by ckerr** [comment]
OK, to be clear you're saying the torrents are still there, just the progress / stats from the previous session is missing, yes?

For the torrents that lost information, do the timestamps in the corresponding `${sha-digest-hash}.resume` files match the time of the application exit? Or are the timestamps older?

**Comment by GScottElshaw** [comment]
I'm looking at the time and date of the contents of the Transmission 'Application Support' directory.

The currently running version 3.00+ (bcf5e4636a). The local time is 7:18 pm.

The file modification dates and times are the most interesting. The client started, again, at 12:44pm

1. The creation and modification time and date for Transfers.plist: 12:44 pm
2. The creation and modification time and date for the majority of files in the Torrents directory? 6:44 pm - yesterday.
3. The creation and modification time and date for stats.json: 6:28 pm today
4. The creation and modification time and date for Resume reflects the Torrents directory
5. The creation and modification time and date for the Transfers.plist is 12:44 pm

QED - no changes written to the Resume, Transfers.plist, and Torrents directory for almost 7 hours.

**Comment by ckerr** [comment]
Thanks for that info. What about the `${sha-digest-hash}.resume` files inside the Resume folder, i.e. `Application Support/Transmission/Resume/${sha-digest-hash}.resume`?

**Comment by GScottElshaw** [comment]
Several hours later, now 12:24 am. All of those Resume folder files are stamped 12:46 pm (yesterday).

Transfers.plist is now 11:07 pm today
Torrent files are currently still dated 6:28 pm (yesterday)
Stats.json 12:16 am (8 minutes ago)

**Comment by GScottElshaw** [comment]
I just restarted and everything was gone with the exception of the three torrents i started today. All that ratio to dust. Ashes to ashes.....

**Comment by ckerr** [comment]
...well crap.

One silver lining, the ratio isn't really dust, of course. The trackers still have the information, so your buffer/ratio on specific trackers is still good.

That's still not great though, obviously. That sucks and I hope we find out what's going on.

**Comment by fxcoudert** [comment]
I'm seeing this intermittently. I open a torrent:

![Capture d’écran 2022-01-18 à 18 33 57](https://user-images.githubusercontent.com/1980544/149988865-0071ca48-0745-486e-860f-7a9b7bcec213.png)

Then quit the app. Reopen, it's still there, same state. Close again, reopen. This time, it's vanished:

![Capture d’écran 2022-01-18 à 18 34 25](https://user-images.githubusercontent.com/1980544/149988930-8f600b36-ee88-4db6-8a3d-b39513b8e769.png)

**Comment by ckerr** [comment]
@fxcoudert in your case it's possibly a side-effect of https://github.com/transmission/transmission/issues/2441 and if so will be fixed by https://github.com/transmission/transmission/pull/2442. My theory there is Transmission is hitting an assert failure before it saves the plist. @GScottElshaw perhaps this is the issue you're seeing too, though from what's been said in this issue I can't tell one way or the other.

(@livings124 is there a reason we still use Transfer.plist at all? The other clients all use `tr_sessionLoadTorrents()` instead and so don't have this issue. It Transfer.plist isn't adding any extra value, it might be slightly nicer for all the clients to use the same API for consistent behavior between platforms)

**Comment by ckerr** [comment]
@fxcoudert #2442 is merged, so as mentioned above that _may_ fix your 2434 problem. @GScottElshaw I'm less sure about your case but please test in case it is the same :slightly_smiling_face:

**Comment by fxcoudert** [comment]
With a build at https://github.com/transmission/transmission/commit/0166b6e6886069cdea5e9fcc94cb5e5d9eeaa024 I don't see the issue anymore.

**Comment by ckerr** [comment]
Closing based on previous comment
