### ISSUE TITLE
Potential regression: gzipped responses from rpc-server on main branch

### ISSUE THREAD

**Issue by jacobmetrick** [transmission/transmission#2454]
Hey all,

Recently switched from using stable 3.00 to a version built from source on commit 0166b6e6886069cdea5e9fcc94cb5e5d9eeaa024 (did this to pick up the change here: **https://github.com/transmission/transmission/pull/1964** as I am running into increasing numbers of hybrid v1/v2 torrent files lately). I'm running/building on linux 5.15 with the command:
```
  cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DENABLE_CLI=ON \
    -DENABLE_GTK=OFF \
    -DENABLE_QT=OFF \
    -DENABLE_WEB=OFF \
    -DINSTALL_LIB=ON \
    -DUSE_SYSTEM_DHT=OFF \
    -DUSE_SYSTEM_B64=ON \
    -DUSE_SYSTEM_NATPMP=ON \
    -DUSE_SYSTEM_UTP=ON
```

This version of transmission works as well or better than the version of 3.00 I was previously on in most respects. However, I use a python script that takes downloaded torrent files, inspects what tracker they are from, and then tells transmission to add these torrent files and put their downloadable contents in specific folders based on their attached tracker. Without having changed my script, the library I used, [transmission-rpc](https://github.com/Trim21/transmission-rpc), was reporting errors decoding the gzipped response to my rpc requests.

I tried a sample request mimicking what my script was doing under the hood and I also ran into issues.
```
curl -v -X POST -H "Accept-Encoding: gzip, deflate" -H "Content-Type: application/json" -H "X-Transmission-Session-Id: 40TlCCDNsnxLSQSS1nQg7Wl1LpzjCW17Uul0ZyKnqvvQjnpB" -d '{"tag": 0, "method": "session-get", "arguments": {}}' http://localhost:9091/transmission/rpc --output /tmp/testfile2.gz
```
The response body I was returned is here: [testfile2.gz](https://github.com/transmission/transmission/files/7897711/testfile2.gz) . I tried using `gunzip` to decode this file but it had no success, either. I also looked briefly into the gzip RFC and it seems like the header identifying data as gzip is not correct, but I admit I am not an expert in gzip.

It's very possible this is something on my end as well, as I may have not built in the proper way. I would also have gotten my hands dirty in the code myself but I'm not sure where to start, and it has been quite a while since I last used C or C++, so I thought I'd get the experts involved first.

edit: I should mention that I was able to get the script working fine if I forced it not to send the Accept-Encoding: gzip header, so that's the workaround I'm using currently.

Thanks!

**Comment by ckerr** [comment]
This is probably related to the change in https://github.com/transmission/transmission/pull/2405 from a couple of days ago. Since you're rolling you're own builds, If you're interest in confirming this theory, the last commit prior to that PR was 6b440af32f94eb011aeab2b8ec7e951137806131

**Comment by jacobmetrick** [comment]
> This is probably related to the change in #2405 from a couple of days ago. Since you're rolling you're own builds, If you're interest in confirming this theory, the last commit prior to that PR was [6b440af](https://github.com/transmission/transmission/commit/6b440af32f94eb011aeab2b8ec7e951137806131)

Gave this a whirl, and building/running the mentioned commit did in fact have the issue go away, as hypothesized. Just for another data point.

**Comment by mikedld** [comment]
Should be as simple as replacing `libdeflate_zlib_compress()` with `libdeflate_gzip_compress()`?..

**Comment by 1100101** [comment]
Considering that `rpcimpl.cc` uses `libdeflate_gzip_decompress()` and `rpc-server.cc` uses `libdeflate_zlip_compress()`, I wonder how this worked in the first place :)
