### ISSUE TITLE
windows version peers list missing

### ISSUE THREAD

**Issue by mayankmetha** [transmission/transmission#246]
http://cdimage.ubuntu.com/ubuntu-gnome/releases/17.04/release/ubuntu-gnome-17.04-desktop-amd64.iso.torrent
This file showed no peers

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. Might also want to refer to [Why Are My Speeds So Slow?](/transmission/transmission/wiki/Why-Are-My-Speeds-So-Slow%3F) wiki page.
