### ISSUE TITLE
Transmission/build/third-party/deflate/src/deflate" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by MrZLeo** [transmission/transmission#2472]
I try to compile new version of transmission in macOS m1, and I got this error message:
```
CMake Error: The source directory "/Users/mrzleo/Transmission/build/third-party/deflate/src/deflate" does not appear to contain CMakeLists.txt.
```
I can compile it correctly previously, so I think it is a bug in new version.

**Comment by GScottElshaw** [comment]
> I can compile it correctly previously, so I think it is a bug in new version.

It was a recent performance [change](https://github.com/transmission/transmission/pull/2405)

**Comment by MrZLeo** [comment]
> > I can compile it correctly previously, so I think it is a bug in new version.
> 
> It was a recent performance [change](https://github.com/transmission/transmission/pull/2405)

Ok, I get it. I just clone the repo again and problem solved.
