### ISSUE TITLE
IP address in announces

### ISSUE THREAD

**Issue by POMATu** [transmission/transmission#2477]
Theres censorshit emerging everywhere in the world so in many countries not possible to connect to tracker directly because its censored

Yes some people use VPN but it only makes sense if whole p2p is illegal at your location. When you use VPN in most cases you get NATed and your torrenting capabilities are stripped, you cant connect to NATed seeds (well sometimes you can with UDP but not always) also you might get stripped speed this way.

So as the outcome of censorshit people have to setup some ways to route tracker requests via some proxies to access tracker. It can possibly be tor or any other way of bypassing censorshit. And hence the tracker receives incorrect announced IP and once again you cant connect to NATed seeds even if you have dedicated IP address

Most trackers support IP address argument &ip=1.1.1.1 in announces maybe there are some other RFC for that like some headers idk. There are settings in other torrent clients like qBittorrent where you can hardcode address. Just those clients are buggy and bad and I want to see such option in transmission so I am requesting that

I am seeding terrabytes of data and if you wanna grab that from my dedicated IP while you being NATed on your VPN I need that option to be implemented cuz censorshit is getting hard

![image](https://user-images.githubusercontent.com/2671462/150642910-ac52b4ae-b432-4955-8658-41cb9c4930d0.png)

Moreover sometimes its the only way for myself to download something, sometimes I am waiting for 20 minutes for other seeds to poll tracker and backconnect to my IP, and after latest regulations of my ISP i probably will have to wait for weeks for some direct uncensored seed to emerge and sync IPs

Thanks

**Comment by vchimishuk** [comment]
@POMATu, does https://github.com/transmission/transmission/pull/3461 addresses your request?

**Comment by POMATu** [comment]
@vchimishuk yes

**Comment by vchimishuk** [comment]
@ckerr , I guess this issue can be closed then.
