### ISSUE TITLE
Progress bar too thin and too long in Qt client

### ISSUE THREAD

**Issue by Advik-B** [transmission/transmission#2478]
The title is self-explanatory

**Comment by Advik-B** [comment]
![image](https://sharex.jrp.best/Advik/m4mug9irh8tq523xfwnf.png)

**Comment by mikedld** [comment]
How is this an issue, for you specifically and for everyone in general? Are there documented guidelines that are violated in current design? What do you propose to do about it?

**Comment by Pentaphon** [comment]
I don't see any issue with the length or width of progress bar on Windows. The outdated, dull button icons on the other hand, should be replaced if there's any nitpicking to be done.

**Comment by ckerr** [comment]
> I don't see any issue with the length or width of progress bar on Windows. The outdated, dull button icons on the other hand, should be replaced if there's any nitpicking to be done.

I think @mikedld has a draft patch for that in  https://github.com/transmission/transmission/pull/2283

**Comment by ckerr** [comment]
> The title is self-explanatory

View > Compact will make the progressbars shorter

**Comment by Advik-B** [comment]
The thing is... I DONT have a compact view turned on
