### ISSUE TITLE
Torrents added via magnet links contain plus signs instead of spaces

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#249]
When the metadata of a torrent added via magnet link is not yet retrieved, the name of the torrent will incorrectly contain plus signs instead of the url-decoded space signs.

**Comment by ckerr** [comment]
This is working correctly now in the [nightly builds](https://transmissionbt.com/download). It was likely fixed as a side-effect of the tr_magnet_metainfo refactor back in January
