### ISSUE TITLE
Setting "Start When Added" fails, adds paused, build e0c3a7f3e6

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#2499]
New bug exists since at least builds e0c3a7f3e6 and 0166b6e688 where the preference setting is ignored to “Start torrent when added” so that while checked, all files are added in a paused state regardless.

**Comment by fxcoudert** [comment]
I think this is https://github.com/transmission/transmission/issues/2239

**Comment by chaseholden** [comment]
confirmed copy of existing known issue
