### ISSUE TITLE
macOS nightlies torrent list renders oddly when sorting by activity

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#2512]
To replicate. Have several torrents running, with them jockeying for position when you have the 'sort transfers by' setting for 'activity'. Open up anything and place it in front of Transmission (in the attached example, System Preferences). Chaos ensues.

https://user-images.githubusercontent.com/69029666/151027707-c7989ab9-6c39-4e0b-97be-2a762cacea5b.mov

**Comment by ckerr** [comment]
I don't think there have been any meaningful changes to the macOS client GUI in awhile. If you can bisect down in the nightlies where this problem was introduced, that might be helpful

**Comment by GScottElshaw** [comment]
It was a really long time ago it began, sorry.

**Comment by ckerr** [comment]
@GaryElshaw is this still happening?

**Comment by GaryElshaw** [comment]
Resolved.
