### ISSUE TITLE
Not able to upload my torrent file due to transmission issue

### ISSUE THREAD

**Issue by venkink** [transmission/transmission#2513]
Hello Team,

I'm using alldebrid for more than 3 years and now I'm facing the issue that torrent was not supporting.
I cross-check with the support team, they replied that please check-in transmission issues by this page.

I have the torrent file where it is working in bit torrent web and not working in alldebrid torrent section.

need your support to fix this issue

**Comment by ckerr** [comment]
What is the issue that you're seeing?

**Comment by Pentaphon** [comment]
I am guessing he means he can't use a v2 torrent because Transmission doesn't support those yet.

**Comment by ckerr** [comment]
OK. Closing as a duplicate of https://github.com/transmission/transmission/issues/458.
