### ISSUE TITLE
Duplicate peers in Inspector panel

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2526]
I haven't seen this before. MacOS Transmission 3.00+ (4fe33496c7).

![Screenshot 2022-01-28 at 2 10 59 AM](https://user-images.githubusercontent.com/69029666/151365963-3fb9ab70-d411-4414-ba39-6bb0d318d739.png)

**Comment by fxcoudert** [comment]
I'm not seeing that with a build at 374c24dde1a7462601a8a1654c0269e94e083eec
Doesn't look like a generic issue.
