### ISSUE TITLE
 transmission-remote missing option: --idle-seeding-limit

### ISSUE THREAD

**Issue by y** [transmission/transmission#253]
needed to set idle-seeding-limit with transmission-remote-gui, but found this old trac ticket reporting the same issue: https://trac.transmissionbt.com/ticket/6016

**Comment by marcelpaulo** [comment]
This option is also missing from command-line **transmission-remote**. It would be really useful to have it.

**Comment by TheOGTonyG** [comment]
I'd go so far to say this is a major feature which is present in the GTK version that renders transmission-remote a lesser option, which means for headless servers one might be better served finding other options. The functionality is clearly there, it's just not implemented in transmission-remote?

**Comment by lajp** [comment]
I'll take a look at this. From what I've gathered it works very similarly to the `seedratio` settings and shouldn't be a very difficult implementation.
