### ISSUE TITLE
Improve feedback "Couldn't connect to server"

### ISSUE THREAD

**Issue by krichter722** [transmission/transmission#254]
The feedback `Couldn't connect to server` of `transmission-remote-gtk` misses any information which can help the user to understand what's going on. The user should be able to fix any connection failure as fast as possible based on the principle "Don't make me think".

experienced with 1.1.1

**Comment by mikedld** [comment]
The program you're referring to is not being developed here, you might want to report the issue elsewhere, e.g. at [transmission-remote-gtk/transmission-remote-gtk](/transmission-remote-gtk/transmission-remote-gtk).

**Comment by krichter722** [comment]
I see. https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/48
