### ISSUE TITLE
regression: segfault in remote.cc when adding a torrent

### ISSUE THREAD

**Issue by LaserEyess** [transmission/transmission#2541]
Discovered while playing with #2539 

Bisected to: 0c16c454baa1e592272d1aa217c3794a88e4eea4

Reproduction steps:
 1. download https://releases.ubuntu.com/21.10/ubuntu-21.10-desktop-amd64.iso.torrent
 2. `transmission-remote -a ubuntu.torrent`
 3. Crash

Some torrents it crashes, some it reports "invalid torrent". In all cases, however, utilities such as `transmission-show` can confirm it is a valid torrent file.

**Comment by LaserEyess** [comment]
I'm tracing though this, and I'm a bit stuck. This crashes in `JsonStringFunc` because the string view of the base64 encoded file returns from `tr_variantGetStrView` with a corrupted memory address for the string data.

**Comment by ckerr** [comment]
<details><summary>valgrind log</summary>
<pre>
==1153297== Memcheck, a memory error detector
==1153297== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1153297== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==1153297== Command: ./utils/transmission-remote localhost:9222 -n underworld:everything -a /tmp/ubuntu-21.10-desktop-amd64.iso.torrent
==1153297== 
==1153297== Invalid read of size 1
==1153297==    at 0x50A8C0: jsonStringFunc(tr_variant const*, void*) (variant-json.cc:536)
==1153297==    by 0x484A2D: tr_variantWalk(tr_variant const*, VariantWalkFuncs const*, void*, bool) (variant.cc:946)
==1153297==    by 0x509C88: tr_variantToBufJson(tr_variant const*, evbuffer*, bool) (variant-json.cc:669)
==1153297==    by 0x485560: tr_variantToBuf(tr_variant const*, tr_variant_fmt) (variant.cc:1195)
==1153297==    by 0x4855AF: tr_variantToStr[abi:cxx11](tr_variant const*, tr_variant_fmt) (variant.cc:1206)
==1153297==    by 0x40D0DE: flush(char const*, tr_variant**) (remote.cc:2147)
==1153297==    by 0x40CA37: processArgs(char const*, int, char const* const*) (remote.cc:2983)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Address 0x6253170 is 0 bytes inside a block of size 491,521 free'd
==1153297==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x40A6C3: processArgs(char const*, int, char const* const*) (remote.cc:2363)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Block was alloc'd at
==1153297==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x515C35D: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x515CB84: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x418976: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator=(char const&) (stl_iterator.h:515)
==1153297==    by 0x416E5B: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::copy_if<char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1>(char*, char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1) (stl_algo.h:751)
==1153297==    by 0x416D0A: tr_base64_encode[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >) (crypto-utils.cc:157)
==1153297==    by 0x40D8D6: getEncodedMetainfo[abi:cxx11](char const*) (remote.cc:550)
==1153297==    by 0x40A5F9: processArgs(char const*, int, char const* const*) (remote.cc:2353)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297== 
==1153297== Invalid read of size 1
==1153297==    at 0x50AAA3: jsonStringFunc(tr_variant const*, void*) (variant-json.cc:574)
==1153297==    by 0x484A2D: tr_variantWalk(tr_variant const*, VariantWalkFuncs const*, void*, bool) (variant.cc:946)
==1153297==    by 0x509C88: tr_variantToBufJson(tr_variant const*, evbuffer*, bool) (variant-json.cc:669)
==1153297==    by 0x485560: tr_variantToBuf(tr_variant const*, tr_variant_fmt) (variant.cc:1195)
==1153297==    by 0x4855AF: tr_variantToStr[abi:cxx11](tr_variant const*, tr_variant_fmt) (variant.cc:1206)
==1153297==    by 0x40D0DE: flush(char const*, tr_variant**) (remote.cc:2147)
==1153297==    by 0x40CA37: processArgs(char const*, int, char const* const*) (remote.cc:2983)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Address 0x6253170 is 0 bytes inside a block of size 491,521 free'd
==1153297==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x40A6C3: processArgs(char const*, int, char const* const*) (remote.cc:2363)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Block was alloc'd at
==1153297==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x515C35D: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x515CB84: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x418976: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator=(char const&) (stl_iterator.h:515)
==1153297==    by 0x416E5B: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::copy_if<char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1>(char*, char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1) (stl_algo.h:751)
==1153297==    by 0x416D0A: tr_base64_encode[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >) (crypto-utils.cc:157)
==1153297==    by 0x40D8D6: getEncodedMetainfo[abi:cxx11](char const*) (remote.cc:550)
==1153297==    by 0x40A5F9: processArgs(char const*, int, char const* const*) (remote.cc:2353)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297== 
==1153297== Invalid read of size 1
==1153297==    at 0x50AABD: jsonStringFunc(tr_variant const*, void*) (variant-json.cc:576)
==1153297==    by 0x484A2D: tr_variantWalk(tr_variant const*, VariantWalkFuncs const*, void*, bool) (variant.cc:946)
==1153297==    by 0x509C88: tr_variantToBufJson(tr_variant const*, evbuffer*, bool) (variant-json.cc:669)
==1153297==    by 0x485560: tr_variantToBuf(tr_variant const*, tr_variant_fmt) (variant.cc:1195)
==1153297==    by 0x4855AF: tr_variantToStr[abi:cxx11](tr_variant const*, tr_variant_fmt) (variant.cc:1206)
==1153297==    by 0x40D0DE: flush(char const*, tr_variant**) (remote.cc:2147)
==1153297==    by 0x40CA37: processArgs(char const*, int, char const* const*) (remote.cc:2983)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Address 0x6253170 is 0 bytes inside a block of size 491,521 free'd
==1153297==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x40A6C3: processArgs(char const*, int, char const* const*) (remote.cc:2363)
==1153297==    by 0x409CDD: main (remote.cc:3102)
==1153297==  Block was alloc'd at
==1153297==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1153297==    by 0x515C35D: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x515CB84: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==1153297==    by 0x418976: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator=(char const&) (stl_iterator.h:515)
==1153297==    by 0x416E5B: std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::copy_if<char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1>(char*, char*, std::back_insert_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, tr_base64_encode(std::basic_string_view<char, std::char_traits<char> >)::$_1) (stl_algo.h:751)
==1153297==    by 0x416D0A: tr_base64_encode[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >) (crypto-utils.cc:157)
==1153297==    by 0x40D8D6: getEncodedMetainfo[abi:cxx11](char const*) (remote.cc:550)
==1153297==    by 0x40A5F9: processArgs(char const*, int, char const* const*) (remote.cc:2353)
==1153297==    by 0x409CDD: main (remote.cc:3102)
</pre>
</details>

**Comment by ckerr** [comment]
@LaserEyess nice triage work. Very actionable. Thanks for the great bug report.
