### ISSUE TITLE
MacOS Build #7591: Tracker icon blinking 

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#2557]
Golly. Alarms?

https://user-images.githubusercontent.com/69029666/151906118-568fbc53-bea3-4359-8b4d-e7725d40144a.mov

**Comment by ckerr** [comment]
Is this still a problem?

**Comment by GaryElshaw** [comment]
I haven't seen that one for a while.

**Comment by nevack** [comment]
I think it was fixed in https://github.com/transmission/transmission/pull/3270

**Comment by GaryElshaw** [comment]
Oh, that was an issue back in February. I haven't seen it do that for a month or two now.

**Comment by nevack** [comment]
Let me know if it's broken again.
