### ISSUE TITLE
Feature request: Add more detail to invalid torrent file message

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#2567]
I've been running across a bunch of `"Torrent" is not a valid torrent file.` error messages lately. The only detail it gives is `The torrent file cannot be opened because it contains invalid data.`. I'd really like to see more information on what went wrong. Bad header? Bad file declaration? Something else? This info would be really useful to take back to the provider to tell them what is wrong with their torrents.

I'm using Transmission 3.0 on macOS 10.15.7.

**Comment by JohnVillalovos** [comment]
The issue with "not a valid torrent file" might be fixed by: https://github.com/transmission/transmission/pull/1964  but there has been no new release since 22-May-2020. So unless you build your own version...

**Comment by ckerr** [comment]
There are also nightly builds available at transmissionbt.com

**Comment by JohnVillalovos** [comment]
> There are also nightly builds available at https://transmissionbt.com/download

Thanks.

I'm assuming that binaries are for Windows and Mac. The provided Linux tarball didn't appear to have binaries in my quick look.

I was looking at: https://build.transmissionbt.com/job/trunk-linux/lastBuild/

**Comment by CyberSkull** [comment]
I checked the nightly build and the underlying error _seems_ to be fixed, insofar as opening the broken torrent file goes.
