### ISSUE TITLE
Transmission 3.00 fails to build since autoconf 2.70, builds fine under autoconf 2.69

### ISSUE THREAD

**Issue by Hexhu** [transmission/transmission#2569]
Distro: Arch Linux
Link to package: https://archlinux.org/packages/extra/x86_64/transmission-cli/
Link to PKGBUILD: https://github.com/archlinux/svntogit-packages/blob/packages/transmission/trunk/PKGBUILD
Steps to reproduce:
1. pacman -Syu
2. git clone https://github.com/archlinux/svntogit-packages.git --branch packages/transmission --single-branch transmission-cli
3. cd transmission-cli/trunk
4. makepkg -s
5. Fails with the below error:
```
==> Extracting sources...
-> Extracting transmission-3.00.tar.xz with bsdtar
==> Starting prepare()...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.
autoreconf: error: intltoolize failed with exit status: 1
==> ERROR: A failure occurred in prepare().
Aborting...
```
6. sudo pacman -U https://archive.archlinux.org/packages/a/autoconf/autoconf-2.69-7-any.pkg.tar.zst
7. makepkg -s
8. Builds just fine

Related upstream (autoconf) bug report:
autoconf-2.71 regression with intltool IT_PROG_INTLTOOL/AC_PROG_INTLTOOL macro
https://bugzilla.redhat.com/show_bug.cgi?id=1944514

**Comment by ckerr** [comment]
3.00 was the last release to support autoconf -- `main` and the nightly builds are CMake only -- so I'm going to close this issue.

Related: https://github.com/transmission/transmission/discussions/2287
