### ISSUE TITLE
[Feature request] Add multiple trackers to a torrent 

### ISSUE THREAD

**Issue by pedrogarcia** [transmission/transmission#257]
I would like to be able to add all the trackers in a list, [for example](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt) at the same time to a torrent, i.e. by pasting the list into a text input field. 

Currently, transmission only allows adding one tracker at a time, and there can be no return character at the end of the line. The example in the screenshot fails to be added to the trackers list.

![screenclip 2](https://cloud.githubusercontent.com/assets/2473545/25580709/6e981b2c-2e59-11e7-8fee-f960cda918ed.png)

**Comment by mikedld** [comment]
See #237.
