### ISSUE TITLE
Minor mistranslation

### ISSUE THREAD

**Issue by pintify** [transmission/transmission#2570]
On Spanish version, there is a minor error as the following is not properly translated:

![imagen](https://user-images.githubusercontent.com/31854894/152378965-0e497cf8-88f8-415c-9294-51c00398c841.png)

As you can see the text should be "_Descargando desde 17 **de** 18 **pares**_" instead of "_Descargando desde 17 of 18 Pares_". The text _of_ seems to be missed in the translation and _Pares_ must not be capitalized as Spanish only capitalizes initial words or proper nouns.

**Comment by ckerr** [comment]
Hi, thank you for reporting this!

Please see https://www.transifex.com/transmissionbt/transmissionbt/ for information on contributing translations; this change can't be handled in the bug tracker.
