### ISSUE TITLE
transmission thinks .torrent file is corrupt

### ISSUE THREAD

**Issue by beren12** [transmission/transmission#2593]
But it works just fine with rtorrent. I tried latest OS X transmission as well as transmission-show on Debian.

http://itorrents.org/torrent/0F4AA208401FA4201B64851B6620030FAC61BCF1.torrent is the link. When I tried to get a magnet version of it, it would keep re-downloading the torrent info and never start.

**Comment by beren12** [comment]
It looks like https://beautifytools.com/torrent-decoder.php can decode it, but https://www.tools4noobs.com says "Bittorrent_Decode::_decode_dict() - Unterminated dictionary." and it seems to have been created by 'go.torrent'

**Comment by ckerr** [comment]
This is fixed by #1964 and works in the [nightly builds](https://transmissionbt.org/download).
