### ISSUE TITLE
assertion in nightly 3.00+ (14714.3.0): t == total_size (block-info.cc:76)

### ISSUE THREAD

**Issue by beren12** [transmission/transmission#2598]
I just updated from January 14, 2020 build, have about 900 torrents seeding.

[Transmission_2022-02-10-092003_Minas-Ithil.crash.txt](https://github.com/transmission/transmission/files/8041777/Transmission_2022-02-10-092003_Minas-Ithil.crash.txt)

**Comment by ckerr** [comment]
I'm not sure how to reproduce this. @beren12 any chance that you were able to determine which torrent was causing this, and is it public?

**Comment by beren12** [comment]
I'm not sure, I can try to narrow it down but oof it's going to be a lot since it's all stored in a single plist...

**Comment by beren12** [comment]
Any way you could roll a debug version to dump each torrent name as it processes it to the log?

**Comment by beren12** [comment]
Nevermind. I found it. It's not public and it's 1.17TB. I was able to remove it with the transmission release and re-add it, it's currently checking existing data, but that will take quite a while.

**Comment by beren12** [comment]
Can I give you the .resume or something?

**Comment by ckerr** [comment]
Might not be necessary. Lemme ponder this a little.
