### ISSUE TITLE
Info Pane not switching tabs

### ISSUE THREAD

**Issue by beren12** [transmission/transmission#2599]
With last night's nightly:
![Screen Shot 2022-02-10 at 10 52 07 AM](https://user-images.githubusercontent.com/455631/153444956-98650f2e-c7ba-4204-b911-34fc73970b05.png)

**Comment by beren12** [comment]
Transmission-663fba71c2

**Comment by ckerr** [comment]
Nobody's been touching the macOS GUI code in quite some time. Is this repeatable, or was it a one-time occurance?

**Comment by GScottElshaw** [comment]
That's not "last night's nightly", that's the 3.0 GUI.

**Comment by beren12** [comment]
Not according to the about box but I can try and copy it again

**Comment by beren12** [comment]
I drug it to the trash and re-copied the binary to double check.
![Screen Shot 2022-02-11 at 1 31 03 PM](https://user-images.githubusercontent.com/455631/153649525-5d76d646-d453-45da-b7ea-f8cee1a11cdd.png)

It's like that after quitting and re-opening. Define repeatable.

**Comment by GScottElshaw** [comment]
The torrent inspector has looked like that since, i think, November or December. This is the current window on MacOS.
![Screenshot 2022-02-12 at 1 00 11 PM](https://user-images.githubusercontent.com/69029666/153696956-892d831f-da81-48a6-a3fe-275f438a58de.png)

**Comment by mangosplat** [comment]
> The torrent inspector hasn't looked like that since, i think, November or December. This is the current window on MacOS. ![Screenshot 2022-02-12 at 1 00 11 PM](https://user-images.githubusercontent.com/69029666/153696956-892d831f-da81-48a6-a3fe-275f438a58de.png)

It depends what version of macOS you are on so you can stop trying to say he's wrong.

~~~

In regards to this issue, it looks like it's known to affect older version of macOS:

- https://forum.transmissionbt.com/viewtopic.php?t=20925&p=80299
- View newer discussion on #2269

**Comment by GScottElshaw** [comment]
Well that's cool. Accusing me of accusing others of being wrong really is your go-to for our interactions isn't it. No need for the ad hominem; I was wrong, sorry about that @beren12. I thought those change were universal across the platform.
