### ISSUE TITLE
Donate link in all clients points to old website

### ISSUE THREAD

**Issue by charlesmims** [transmission/transmission#26]
it's https://transmissionbt.com/donate.php  but should be   https://transmissionbt.com/donate/
as is, it gets a 404.
problem found in osx client,
18:32 < CrazyLemon> its not just osx..its also gtk and qt

**Comment by JohnClay** [comment]
This has been worked around with a website redirect, but all clients should be updated to point to the new address.

@charlesmims Thanks for pointing it out!

**Comment by RobFog** [comment]
#33 should fix this.
