### ISSUE TITLE
.torrent not deleted after it added

### ISSUE THREAD

**Issue by monkeylove** [transmission/transmission#262]
I am using the latest nightly build of the Windows desktop version in Win 8 and a headless NAS.

I configured it to automatically add .torrents from a directory in the PC hard drive and then move them to the trash. The .torrents are added to the queue but they are not deleted from the directory.

It works, though, with the early preview version.

Finally, I am using the nightly build because it correctly sets the download directory of torrents acquired through magnet links in the NAS. The early preview version attempts to create a download directory in drive C: of the desktop.

**Comment by mikedld** [comment]
You're not using latest nightly build, otherwise you would've noticed that I already fixed this in dd538539aae96f43fd4a1c31e643c5b18d059f8c and replied to you on the forum in this regard. Thanks for the book-keeping ticket though ;)
