### ISSUE TITLE
Dialogs not centered properly on GNOME 3.24 Wayland session

### ISSUE THREAD

**Issue by yakubin** [transmission/transmission#263]
I'm using GNOME 3.24 on Arch Linux. On Wayland the dialogs aren't centered properly relative to the main Transmission window. Their positioning seems to be random. Examples:
Wayland:
![screenshot from 2017-05-03 21-29-54](https://cloud.githubusercontent.com/assets/15315211/25678185/27608298-3049-11e7-95a6-553bd21a4c05.png)
![screenshot from 2017-05-03 21-31-34](https://cloud.githubusercontent.com/assets/15315211/25678194/2a57716e-3049-11e7-9e86-94bb342841f1.png)
Xorg:
![screenshot from 2017-05-03 21-32-46](https://cloud.githubusercontent.com/assets/15315211/25678209/36b22314-3049-11e7-992d-da42111148bb.png)
![screenshot from 2017-05-03 21-39-58](https://cloud.githubusercontent.com/assets/15315211/25678210/37f12f40-3049-11e7-8777-387c98456fae.png)

**Comment by diazbastian** [comment]
@yakubin That doesn't seem to be a problem and less is something related to transmission, but it is about how mutter behaves to intelligently align windows in available spaces. By default are the modal dialogs which are attached and centered in the window, for example the "about" dialog.
