### ISSUE TITLE
Feature Request: Dark mode support for Windows 10/11?

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#2636]
We have it for Linux and Mac users so if anybody wants to make it happen for Windows users as well, please by all means make it happen.

**Comment by mikedld** [comment]
I'd say this is blocked by [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028). We can play with QSS themes like other projects do, but I'm not interested in doing it myself.

**Comment by mikedld** [comment]
See #920.

**Comment by GitThisBugOff** [comment]
With the release of 4.00-beta, what's the status on this topic?

**Comment by Pentaphon** [comment]
> With the release of 4.00-beta, what's the status on this topic?

I guess we just have to wait for Qt to fix that bug before we ever see a working dark more for Windows.

**Comment by PaulMEdwards** [comment]
> > With the release of 4.00-beta, what's the status on this topic?
> 
> I guess we just have to wait for Qt to fix that bug before we ever see a working dark mode for Windows.

Run this command for a dark UI on Windows:

`"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2`

You can also append `-style fusion` for a slightly different theme, which I think looks better:

`"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

**Comment by GaryElshaw** [comment]
As part of #4376 there are a reversed set of icons for those who prefer light or dark permanence.

**Comment by Pentaphon** [comment]
> You can also append `-style fusion` for a slightly different theme, which I think looks better:
> 
> `"C:\Program Files\Transmission\transmission-qt.exe" -platform windows:darkmode=2 -style fusion`

Here's what it looks like on Windows 11. Needs a lot of work. 

![dark](https://user-images.githubusercontent.com/49374058/211267690-3d964be7-2ff7-464e-ba2a-1973b4d6f8df.png)

**Comment by PaulMEdwards** [comment]
> Here's what it looks like on Windows 11. Needs a little fine tuning to look good.

Yup, I've been using it that way for the last 3 days. Not perfect, but much better on my eyes since everything else I'm running is dark and this was the only bright white app window glaring at me.
