### ISSUE TITLE
[Feature Request] Check for update for nightly releases

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [transmission/transmission#2637]
Currently you can choose to download stable and beta releases via the app, however when running a nightly build you won't get the option to update the nightly build.

It would be handy to know when a new release comes out via the Transmission app and be able to download it automatically.

**Comment by ckerr** [comment]
This is a good suggestion, but hopefully it won't be needed in the long term. Once 4.0.0 is released, this development frenzy will slow down a bit.
