### ISSUE TITLE
Credentials in url breaks UI

### ISSUE THREAD

**Issue by radioxoma** [transmission/transmission#2638]
If `login:password` are set trough url e.g. `http://login:password@example.com:9091` right mouse click and "Settings menu" won't work at all, "Edit preferences..." shows corrupted window. Simple `http://example.com:9091` with basic authentication form works as expected.

Transmission 3.00 (bb6b5a062e) in Termux. Reproducible on Firefox 97 on Linux, Android default browser etc.

**Comment by ckerr** [comment]
The Web UI has been rewritten since 3.00. If this is still an issue in the [nightly builds](https://transmissionbt.com/download) please file a new issue with updated information. Thank you!
