### ISSUE TITLE
wiki + docs should be moved into transmission repo in new docs/ directory [VOLUNTEERS WANTED]

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2644]
Why:

- Modifying a GitHub-based wiki is frustratingly hard. Crazy as it sounds, I think it's easier for end users to make a pull request on `transmisssion/transmission` than it is to update the wiki. All [of these issues](https://github.com/transmission/transmission/issues?q=is%3Aissue+is%3Aopen+label%3Ascope%3Awiki) could be solved with a user-contributed PR but under the current system that's not possible.
- It's easy for the wiki to fall out-of-sync with the codebase. By unifying them in the same repo, a PR that changes a setting could also update the docs, the same way that RPC changes currently update the rpc-spec document.
- The current documentation is out-of-date due to the reasons above. Migrating the docs would have an added benefit of new eyes that could update the documentation.
- Having a single wiki doesn't always make sense for things that change between versions, e.g. if the values in `settings.json` change, one would want to see the documentation that fits the version of Transmission that they're using.

What:

PRs and volunteers welcomed:

- [x] PR that copies all the info from https://github.com/transmission/transmission.wiki.git into a new directory `docs/` in `transmission/transmission`
- [ ] Ensure all the links in the docs work and link to other docs files rather than to the wiki
- [ ] Fix all the [open `wiki` issues](https://github.com/transmission/transmission/issues?q=is%3Aissue+is%3Aopen+label%3Ascope%3Awiki) by opening new PRs that fix them in `docs/`
- [x] Update `transmisson/transmisson`'s README.md to link to `docs/`
- [x] Move `rpc-spec.md` into `docs/` + fix any links
- [ ] Update the documentation to be up-to-date with modern Transmission. This is probably where the majority of the work will be, e.g. go through the documentation and ensure that all the settings.json fields are covered and are correct.

Maintainer will need to:

- [ ] Shut down the wiki after migration is complete

**Comment by GScottElshaw** [comment]
I'm in. I'll spend some time trying to work all that out a bit later.
