### ISSUE TITLE
Windows 64 bit runs torrents but does not update UI

### ISSUE THREAD

**Issue by pcsanza** [transmission/transmission#2651]
Experienced this issue under Windows 10 Pro Version	10.0.19044 (64 bit) using [transmission-3.00-x64.msi].

I did some searching in the forum and found a few people reporting similar issues - no real help there - the best advice there was to update windows - already up to date.  

I can reproduce this issue for every torrent added to a running client. The torrent is downloading in the background and the UI does not even show that the torrent is added.  If I quit Transmission and restart it, UI shows all active torrents and accurately shows their present status, but UI does not update at all even though download continues in the background.  

On a whim, I uninstalled the 64-bit Transmission and installed the 32-bit client (same version).  It seems to work just fine - I do not experience the issue there.  So as best as I can tell this issue is isolated to the 64-bit version. Please advise if there is additional information you need to know about my environment.

**Comment by ckerr** [comment]
Hi, my first suggestion would be to try updating to a [nightly build](https://transmissionbt.com/download) and see if the problem persists there.

**Comment by pcsanza** [comment]
Ok - thanks for the heads up. I tried the latest nightly build (#1013  transmission-3.00+-r87d9f9b00a-x64.msi) and the problem is gone.  For grins I reinstalled the official release 3.00 x64 again and the problem came back. Whatever the issue is/was it seems that it may have already been addressed. How soon before the next release, which will (presumably) incorporate this fix?

**Comment by ckerr** [comment]
> How soon before the next release, which will (presumably) incorporate this fix?

https://github.com/transmission/transmission/discussions/2287

**Comment by meirdavis** [comment]
I'm still experiencing this issue even though I recently upgraded to Transmission 4.0.4 (24077e3511)

**Comment by nevack** [comment]
> Same issue here. On a Mac though, running Big Sur.

Please open new issue with info about Transmission version and what client (Qt/GTK/Mac native) is being used.

**Comment by x3oo** [comment]
Having the same issue on win 11 pro. had the same issue in the past too.

**Comment by peetezaah** [comment]
Same here on 4.0.6 (38c164933e)

**Comment by TST27** [comment]
Same issue here. 2024-12 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5048685) was installed a few weeks ago, now installing the latest update as of today. Gotta love Windows 11, same pig, different lipstick.

**Comment by rmmoul** [comment]
I'm experiencing this on Windows 11 with version 4.0.6 (38c164933e). I uninstalled and reinstalled and the issue went away for a few days but it's happening again now.

**Comment by megurost** [comment]
Same problem here on Windows 10. Tried the beta version but the problem persisted.
I couldn't find a solution so I temporarily switched to qBitorrent until this is fixed. I love Transmission and its simplicity so I hope this gets fixed sometime!
