### ISSUE TITLE
Blocklist is not loaded

### ISSUE THREAD

**Issue by MagOO33** [transmission/transmission#2655]
Hello,
On MacOS 12, Arm version, the blocklist is never loaded at startup.
I have to load it manually, else UI says it was "never loaded".

**Comment by ckerr** [comment]
Thanks for reporting this.

If you look in About dialog, what build number does it say you're running?

**Comment by MagOO33** [comment]
It say's "3.00+ (376e8b3782)"

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/2272

**Comment by MagOO33** [comment]
Hello, I looked at #2272 and it's not really my case because the blocklist is declared "never loaded" at every start even if the blocklist was loaded the last time I closed Transmission.
I have to load the blocklist manually every time I launch Transmission to have an active blocklist.
It's not about "Automatically update weekly" feature.
