### ISSUE TITLE
Win 8.1 Desktop Accessing NAS: Unable to Add Magnets or Delete Torrents, Client Sometimes Crashes

### ISSUE THREAD

**Issue by monkeylove** [transmission/transmission#266]
Currently using Build No. 42. 

I'm unable to add magnets (whether clicked on in the browser or a pasted link in the client), but it works with another client (Transmission Remote).

The same for completed torrents that I want deleted: it only works if I use another client.

Finally, I am experiencing more crashes for this one than with the previous build, usually involving KERNELBASE.dll or another DLL.

**Comment by mikedld** [comment]
Please open several issues if you have several problems. Current report is not at all useful.

Try being more specific about "Win 8.1 desktop" (is this transmission-qt? is this transmission-remote?), "accessing NAS" (are you using transmission-daemon on NAS? are you using NAS as mounted network share?), "unable to add", "want deleted", "works", "more crashes" (what specific actions do you perform? what happens? what do you expect to happen? what did you do to troubleshoot the issue (including trying to run previous versions to pinpoint the one where it all began, rebooting the system, installing system updates, disabling antivirus, etc.)? do you have logs (including Windows event logs) for any of the involved programs? are you referring specifically to _completed_ torrents for a reason? where are those crash reports for prior and current builds? why are you sure that this is an issue with Transmission itself and not with its configuration or your system?)

**Comment by monkeylove** [comment]
Sorry, please close this thread. I just tested the magnet addition and it now works fine.

FYI, I am using a Transmission-QT client for Windows 2.92 nightly build r10556943e5 in a Win 8.1 64x to access Transmission running in a Buffalo NAS LS-CHLV2.
