### ISSUE TITLE
assertion failed: begin < end (bitfield.cc:83)

### ISSUE THREAD

**Issue by ViRo3** [transmission/transmission#2667]
Nightly build Transmission repeatedly crashing on latest macOS beta
[Transmission-2022-02-21-103139.ips.txt](https://github.com/transmission/transmission/files/8106370/Transmission-2022-02-21-103139.ips.txt)
[Transmission-2022-02-21-103237.ips.txt](https://github.com/transmission/transmission/files/8106371/Transmission-2022-02-21-103237.ips.txt)
[Transmission-2022-02-21-103550.ips.txt](https://github.com/transmission/transmission/files/8106372/Transmission-2022-02-21-103550.ips.txt)

**Comment by ViRo3** [comment]
[[neoHEVC] Magia Record [BD 1080p x265 HEVC AAC] [Dual Audio].torrent.txt](https://github.com/transmission/transmission/files/8107136/neoHEVC.Magia.Record.BD.1080p.x265.HEVC.AAC.Dual.Audio.torrent.txt)
Is the file that causes the crash. This resembles my previously reported issue.

**Comment by ckerr** [comment]
```
  0x0000000100ae41e8 _Z16tr_assert_reportPKciS0_z + 104\n4   Transmission                        
  0x0000000100ae9400 _ZNK11tr_bitfield10countFlagsEmm + 324\n5   Transmission                        
  0x0000000100ab4bd4 _Z18tr_torrentGotBlockP10tr_torrentj + 436\n6   Transmission                        
  0x0000000100ad1018 _ZL16peerCallbackFuncP7tr_peerPK13tr_peer_eventPv + 348\n7   Transmission                        
  0x0000000100ad7e08 _ZL7canReadP9tr_peerIoPvPm + 888\n8   Transmission                        
  0x0000000100acd1a4 _ZL14canReadWrapperP9tr_peerIo + 200\n9   Transmission                        
  0x0000000100acc970 _ZL11utp_on_readPvPKhm + 184\n10  Transmission                        
  0x0000000100b3fefc _Z19UTP_ProcessIncomingP9UTPSocketPKhmb + 2148\n11  Transmission                        
  0x0000000100b40aa4 UTP_IsIncomingUTP + 944\n12  Transmission                        
  0x0000000100af83cc _ZL14event_callbackisPv + 328\n13  Transmission  
```

**Comment by ViRo3** [comment]
Can confirm fix! Thank you very much!
