### ISSUE TITLE
Dead link in project wiki

### ISSUE THREAD

**Issue by kakuhen** [transmission/transmission#2669]
The [RPC protocol specification](https://github.com/transmission/transmission/wiki/RPC-Protocol-Specification) page links to a non-existent file for the current revision of the RPC specification. In short, `rpc-spec.txt` should be renamed to `rpc-spec.md` for the main branch. Since I do not have ability to edit the wiki, I am filing this issue.

**Comment by ckerr** [comment]
Yep, what I'd like to do is shut down the wiki and [migrate it all](https://github.com/transmission/transmission/issues/2644) to here in `transmission/transmission` so that people can make pull requests to fix breakage. 

Thanks for reporting the broken link!

**Comment by ckerr** [comment]
Fixed
