### ISSUE TITLE
Management

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2716]
I'm taking a deep breath, and accepting of consequences.

I'm 51. I've managed, been part of, or led multi-million dollar projects, and done things alone with no money - and far enjoyed the latter more than the former. I've been a primary tester for international open source projects, a contributor to Apple, a designer of an application for hundreds of school children in Cambodia, and a former university lecturer. I helped design and establish my nation's web standards for accessibility after accomplishing the most accessible website in my country. I have three post-graduate degrees and other qualifications.

I'm really pissed off with this project.

I don't understand how only one person leading the project is seemingly the only person who wants to improve it on a - not weekly - but daily basis. How arbitrary or reluctant it is for the other principal contributors to be willing to engage on any level of discussion or development, and yet feel like their best contribution is to review a PR once and a while without contributing anything from themselves insofar as code or improvements are concerned.

The Transmission community is fantastic. I'm glad someone with the correct privileges has seen what is possible. I'd like everyone to give @ckerr a round of applause for actually taking notice; triaging; and just sharing his knowledge about what is an idea, but not necessarily a good one. With reasons.

But i do need to throw some shade. Where are the other principal developers PR's? I am daily testing since October - where are your contributions to Transmission's code base? Largely, from what i read, your answers are no. It's too hard, too difficult, too time-consuming, or should be designated some time, nebulously, in the future.

Earn your name on the lid of the tin.

**Comment by ckerr** [comment]
I like that my recent push to bring Transmission back to active development is having an effect!

One thing though, I think you're looking wrong at the other maintainers. Transmission has been around for a *long* time and we all -- _myself included_ -- have at various times moved on, come back, moved on again. It doesn't make sense to blame people for having other lives or for not staying focused on a project over several years.

IMO the right answer isn't to blame the current maintainers for having lives, it's to grow the number of maintainers.

**Comment by GScottElshaw** [comment]
I don't disagree with your principle, Charles, I'm disappointed with the level of engagement. Not once have the other maintainers engaged with those of us designing the new website. This isn't about historical blame, it's about questioning the last few months where the sole contributor is you. Alone.

I just suggested the new website go live asap for the reason that now is a good time to contribute with an active milestone being seen. I agree. I want more contributors, and there are gaps on the mac side. It's why i think now is a good time to push for more contributors.
