### ISSUE TITLE
Folders names in torrents are ignored when assigning groups by names

### ISSUE THREAD

**Issue by ThomasPzzz** [transmission/transmission#2724]
Hi,

When assigning up groups to new transfers based on name, folders names in torrents are ignored, only the files names are taking in account. At least under MacOS.

Cheers.

**Comment by ckerr** [comment]
Hi @ThomasPzzz, thanks for reporting this. I _think_ this is a duplicate of https://github.com/transmission/transmission/issues/2028 so I'm closing this issue.
