### ISSUE TITLE
Transmission nightly builds should use different file name & identifier from regular

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#2725]
To keep the nightly build of Transmission from accidentally clobbering the main release, it should have a different name and identifier.

For example on macOS, the app should be renamed `Transmission Nightly Build.app` and the Bundle identifier should be changed to something like `org.m0k.transmission-nightly` or `org.m0k.transmission.nightly`.

This will ensure that the app doesn't overwrite the main release in the user's install and preferences set on the main and nightly don't interfere with each other.

**Comment by morbus** [comment]
I'd prefer the app had the same name as the disk image, so that I can more easily track which nightly I'm using.

**Comment by robd003** [comment]
Adding the CI build # to the About window would be useful too. Having only the random commit hash is kind of a pain to look up.
