### ISSUE TITLE
3.00+ (377c335d0f) macOS - not finishing downloading

### ISSUE THREAD

**Issue by sweetppro** [transmission/transmission#2734]
In the latest recent builds, torrents do not finish downloading. Connections are fine, I am connecting to multiple seeds. But downloading will all of a sudden stop at a certain point. no amount of restarting will resume the downloading.
Its as if a completed flag is set for the torrent, not allowing it to finish...

**Comment by ckerr** [comment]
Is this consistent for a lot of torrents, or just a particular swarm?

**Comment by sweetppro** [comment]
you're right, it does seem to be certain swarms
