### ISSUE TITLE
Add clarification of transmission-cli vs transmission-daemon to README.md

### ISSUE THREAD

**Issue by LacrociviousAcrophosist** [transmission/transmission#274]
erdgeist commented in-channel about not having any deprecation information presented when he used transmission-cli for something when instead he would have been better served by transmission-daemon. I propose adding the following section to README.md between sections ## About and ## Building:

## Command Line Interface Notes

Transmission is fully supported in transmission-remote, the preferred cli client.
Three standalone tools to examine, create, and edit .torrent files exist: transmission-show, transmission-create, and transmission-edit, respectively.
Prior to development of transmission-remote, the standalone client transmission-cli was created. Limited to a single torrent at a time, transmission-cli is deprecated and exists primarily to support older hardare dependent upon it. In almost all instances, transmission-remote should be used instead.
Different distributions may choose to package any or all of these tools in one or more separate packages.

**Comment by grrr2** [comment]
hi,

small typo: support older hardare -> support older hardware
