### ISSUE TITLE
move logging to spdlog?

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2741]
Transmission uses a bespoke logging infrastructure. Since libtransmission's logging is getting a refresh to address other issues -- #1992, #295, and the log-first-time-but-not-on-subsequent-similar-failures part of #86 -- this might be a good time to consider moving to [spdlog](https://github.com/gabime/spdlog). It seems well-supported and uses [{fmt}](https://github.com/fmtlib/fmt), which was already under consideration for libtransmission (tracked at #2551, would fix #1353).

Needs investigation:

- does the GTK client still need its logging window? The Qt client doesn't have one.
- what does the macOS client do?
- how to configure verbosity from the command line e.g. with transmission-daemon
- syslog support. spdlog has it, but I haven't looked into how to do it
- if libtransmission uses spdlog, can we use its copy of fmt for non-logging code too, e.g. for faster json / benc serialization in 2551

**Comment by GScottElshaw** [comment]
#4.5
