### ISSUE TITLE
assertion failed: s->leftUntilDone <= s->sizeWhenDone (torrent.cc:1154)

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#2745]
Got this error today upon exiting transmission on macOS: `assertion failed: s->leftUntilDone <= s->sizeWhenDone (/Users/mac-hxuri4iuts/workspace/trunk-mac/libtransmission/torrent.cc:1154)`

**Comment by mrusme** [comment]
Got one as well:

```
assertion failed: s->desiredAvailable <= s->leftUntilDone (/var/tmp/portage/net-p2p/transmission-3.00-r1/work/transmission-3.00/libtransmission/torrent.c:1521)
```

**Comment by ckerr** [comment]
Closing this as a duplicate of https://github.com/transmission/transmission/issues/3354 because although this issue was reported first, the newer issue has a lot more actionable info
