### ISSUE TITLE
MacOS 3.00+ (749bb591fb) crash accessing Message Log

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2760]
[3.00+ (749bb591fb) crash.txt](https://github.com/transmission/transmission/files/8236694/3.00%2B.749bb591fb.crash.txt)

**Comment by ckerr** [comment]
Thanks for the crash report! I think this is a duplicate of #2759 but it's helpful to have the crash report too :+1:

**Comment by GScottElshaw** [comment]
Oh, you saw those are two separate builds, yes?
