### ISSUE TITLE
[enhancement] rpc torrent-get "available" bitfield

### ISSUE THREAD

**Issue by FezVrasta** [transmission/transmission#2768]
On the desktop client there's a toggle to switch between the "available" and "progress" graph, but from the RPC API I can only find the `pieces` bitfield.

<img width="102" alt="CleanShot 2022-03-13 at 10 25 22@2x" src="https://user-images.githubusercontent.com/5382443/158053243-67422b31-2b10-4d1c-9467-6a3a37ec385c.png">

May someone help me understand how are the two charts created starting from a single bitfield?

Thanks.

**Comment by ckerr** [comment]
Progress matches the `pieces` bitfield. I don't think there's currently a way to get the `available` via RPC, but that could be added. @FezVrasta is that what you're looking for?

**Comment by FezVrasta** [comment]
Thanks for the information! Yes that's what I'm looking for. Exposing it would be great.

**Comment by FezVrasta** [comment]
@ckerr may you also help me understand something about the bitfield? I have a 100% downloaded torrent (Big Buck Bunny from webtorrent if it matters), that shows 132 bits set to `true` and the rest set to `false`, this happened only once the download completed, while it was still in progress the number of `true` bits was coherent with the download progress.

**Comment by ckerr** [comment]
@FezVrasta Off the top of my head, I don't know. What version of Transmission is the server running?

**Comment by FezVrasta** [comment]
I'm using Transmission for Mac 3.00+ (1459220b5b), but also 3.00+ (a942c67199) has the same behavior.

This is the base64 bitfield:

```
//////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by killemov** [comment]
Please name the field "piecesAvailable".
