### ISSUE TITLE
Inability to download a magnet link without starting the torrent

### ISSUE THREAD

**Issue by haasn** [transmission/transmission#277]
In clients like rtorrent, you can add a magnet link, and have the torrent client resolve the .torrent file, but keep the torrent itself paused, ideally in its “pre-allocation” stage.

There are a number of reasons I may want to do this:

1. I only want a single file out of a large torrent
2. I get sent a magnet link and want to see its contents before deciding whether or not to download it at all
3. I want to add a magnet link for which I already have the files, but need to make sure the file names match up, to avoid issues like #276 
4. I only want the .torrent file itself, rather than the contents

There are a number of ways I can imagine implementing this:

1. Allow “paused” torrents to resolve via DHT, but remain paused after doing so.
2. Add an option to auto-pause magnet links once the .torrent gets resolved in general
3. Next to the `Open URL` dialog's `Start when added` setting, add a `Pause after resolving` option that is only available when the URL in question is a magnet link.

The third option probably gives the user the most amount of control, but the first option would be the simplest.

**Comment by mikedld** [comment]
See #218.
