### ISSUE TITLE
Tasks added remotely don't start until Transmission window has focus

### ISSUE THREAD

**Issue by jminuscula** [transmission/transmission#28]
It's weird, I know.

I'm adding torrents remotely to a machine in my LAN (OS X 10.11.6, Transmission 2.92 b14714) via Remote Torrent Adder [0], which works great. I can see the torrents added in the web interface, everything is updated just fine.

However, the torrents I add remotely are always stuck in the "retrieving metadata" state, or "downloading from 0/0 clients". If I VNC to the machine I can see that Transmission is in fact *not* downloading anything. As soon as I bring the main window to the foreground, the tasks reactivate and start downloading or retrieving metadata immediately.

I know it sounds quite funny, but I've experienced this behavior consistently for quite some time now.

Let me know if I can do anything to help debugging.

[0] https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci

**Comment by jminuscula** [comment]
didn't see anything on the logs, but here's an extract from before adding the torrents to just when they started downloading

[transmission.log.txt](https://github.com/transmission/transmission/files/483322/transmission.log.txt)

**Comment by jminuscula** [comment]
this seems fixed now

**Comment by mikedld** [comment]
Not sure how as I didn't do anything in regards to this issue... @RobFog's commit mentions wrong GH item it seems.

**Comment by jminuscula** [comment]
hmmm, I can't reproduce it reliably anymore. Will reopen if starts happening consistently again.
