### ISSUE TITLE
Move or Remove Data fails to remove empty directories from Source location

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#2807]
Build 6db3fbfe64 and 783fa500e7 and b94c6796c8 and probably earlier builds

Option to "Move" or "Remove Data" files successfully copies source file(s) and its subdirectories but fails to remove (delete) from source location only its now empty source directories (folders and subfolders) after completion.
*Sometimes, the subtitle text files are actually left behind also*

Example Source BEFORE Move:

     Source / MyVideo.2022 /
                MyVideo (2022).mp4
                Subs / English.srt
                
Example Source AFTER Move:

      Source / MyVideo.2022 /
                      .
                  Subs / .

**Comment by Deathcow** [comment]
"Trash data and remove from list..." Also seems to keep empty folders around in recent versions.

This is probably related and caused by the same bug.

**Comment by chaseholden** [comment]
Awesome!!! build 33cbe33229 does not crash for me. yay! running 1 hour strong.

**Comment by chaseholden** [comment]
Doesn't this bug just mean that somebody missed the "-Recursive " option on the move operations? 
This would be in 3 places:
- option to move data
- option to remove data
- preference setting to "keep incomplete files in [dir]" where files are auto moved when completed

**Comment by ckerr** [comment]
@chaseholden is this still broken after #2919 ?

**Comment by chaseholden** [comment]
Unfortunately, only partially fixed. I just downloaded #7880 build 026174ae51 
Torrents which are moved using "Move Data File To..." continue to leave empty directories from their original location. However, "Remove Data" now does properly delete the source directories after successful copy (move).

**Comment by ckerr** [comment]
@chaseholden OK I'm trying to understand the test case, so you're saying after moving the torrent in the original example, an empty `Subs/` folder is still there in the source directory, but `Subs/english.srt` got moved to the destination directory. Is that correct?

**Comment by chaseholden** [comment]
This appears to have been solved at some point prior to 4.0.2. Closing.
