### ISSUE TITLE
don't announce paused torrents

### ISSUE THREAD

**Issue by gthreepw00d** [transmission/transmission#282]
Transmission should not announce torrents paused by user.
version 2.92

**Comment by diazbastian** [comment]
@gthreepw00d You mean a notification?

**Comment by cfpp2p** [comment]
@gthreepw00d  maybe you mean [Transmission sends a 'stopped' event when pausing a torrent queued (but not running)](https://trac.transmissionbt.com/ticket/5092)

**Comment by gthreepw00d** [comment]
No. It was torrent which was paused (manually, for a long time), i accidentally checked its info and it showed that some peers were found. Very strange.
Cant reproduce reliably.

**Comment by rndusr** [comment]
Clients get the number of peers from scraping, which is different from announcing.

https://en.wikipedia.org/wiki/Tracker_scrape

**Comment by gthreepw00d** [comment]
@rndusr 
Anyway, scraping is also unnecessary for paused torrents.

**Comment by rndusr** [comment]
Well, that's your opnion. Others may want to see the number of peers for paused torrents.

Why don't you want paused torrents to scrape anyway?

**Comment by gthreepw00d** [comment]
Manually paused means (for me) to be inactive.

**Comment by cfpp2p** [comment]
@rndusr @gthreepw00d
Can be chosen

>  scrape-paused-torrents-enabled: Boolean (default = true)

https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#misc
