### ISSUE TITLE
No libraries in 'third-party' directory when downloading source

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#2826]
Downloading the zip source code from transmission/transmission omits the contents of what should be in the 'third-party' folders.

**Comment by ckerr** [comment]
I notice that @mikedld was working on cpack / cmake a few hours ago with c2549c3c774a93df5e1c80570f3696655519f0d0 and 3cd11ee1fbb9783144ab7058eb0c55f5c3190664 -- does this fix the issue?

**Comment by mikedld** [comment]
If you're talking about downloading directly from GitHub via links such as https://github.com/transmission/transmission/archive/refs/heads/main.zip, those archives don't include submodules.

**Comment by mikedld** [comment]
See also dear-github/dear-github#214.

**Comment by GScottElshaw** [comment]
Wow. 

Was that last suggestion in the thread useful? https://github.com/dear-github/dear-github/issues/214#issuecomment-1080042519
