### ISSUE TITLE
NSInternalInconsistencyException build 2996e223dd

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#2834]
NSInternalInconsistencyException build 2996e223dd #7774

Am I reporting crashes correctly? 
There's a whole slew of crashes making Transmission unusable on every single build in the past few weeks that I keep adding to this thread but i'm not sure anyone sees it here:

https://github.com/transmission/transmission/issues/2727#issuecomment-1081218567

**Comment by ckerr** [comment]
Hi @chaseholden, the whole .ips file is useful but the main important part is for the title is the part that begins with `assertion failed:` so yes all the attachments you're putting into #2727 are on-topic for that issue.

Let's continue this conversation there.
