### ISSUE TITLE
UPnP Not working - Transmission 3.00 Windows 64

### ISSUE THREAD

**Issue by MaxiCom** [transmission/transmission#2866]
I have a Netgear router (R6220) which doesn't support nat-pmp but supports UPnP!

When i start Transmission, i see the packets trying to get to the nat-pmp port of my router (which is unreacheable), after that there is a ssdp discovery for upnp devices, my router answer correctly, but after that, nothing, no attempt from transmission to make an UPnP request!

UPnP table from my router (empty as transmission is opened): 
![image](https://user-images.githubusercontent.com/7782302/161385082-0b52b438-a15b-4198-9b66-b81b6e174d93.png)

Packets from NAT-PMP failing and UPnP fallback:
![image](https://user-images.githubusercontent.com/7782302/161385121-6416d5aa-9ad7-427f-a4e9-49d8409def09.png)

The packets capture:
[UPnP.zip](https://github.com/transmission/transmission/files/8402584/UPnP.zip)

I'm not 100% sure that this is a transmission problem so any advice are welcomed!

**Comment by MaxiCom** [comment]
Update: 

There is a SOAP exchange between transmission and the router but it seems to get nowhere about opening a port!

The packet capture:
[UPnP-2.zip](https://github.com/transmission/transmission/files/8402778/UPnP-2.zip)

I tried with a UPnP debugging program and i manage to correctly open a port with it via UPnP so it seems that's indeed a problem with transmission!

**Comment by MaxiCom** [comment]
The port forwarding phase in the logs as it is asked to post it as well!

```
[2022-04-02 18:05:12.350] dbg natpmp.cc:41 initnatpmp succeeded (0) (/home/znkbh/Transmission/libtransmission/natpmp.cc:41)
[2022-04-02 18:05:12.350] dbg natpmp.cc:41 sendpublicaddressrequest succeeded (2) (/home/znkbh/Transmission/libtransmission/natpmp.cc:41)
[2022-04-02 18:05:12.350] inf port-forwarding.cc:111 State changed from 'Not forwarded' to 'Starting (/home/znkbh/Transmission/libtransmission/port-forwarding.cc:111)
```

**Comment by MaxiCom** [comment]
It was just because i was behind 2 routers so my external address (which was still an internal address from the second router) wasn't valid for UPnP!

My bad!

**Comment by girogiacomo** [comment]
Maybe this issue can be re-opened so the devs can fix this behaviour and make it work even behind double nat... I have a netgear RBR20 behind my ISP's router and I have set the local ip of the wan port of the RBR20 in "dmz mode" on the ISP router.
Emule works fine but transmission fails to map the ports on the UPNP table shown in the first message
