### ISSUE TITLE
Crash on open on each nightly build on first run 

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#2877]
build 738431169c

`Crashed Thread:        14  Dispatch queue: NSTextCheckingOperationQueue (QOS: USER_INTERACTIVE)`

`Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY`

`Application Specific Information:

Assertion failed: (temp_fd >= 0), function _open_and_mmap_for_reading, file LanguageIdentifier.c, line 624.
 `
 [738431169c-crash-reports.zip](https://github.com/transmission/transmission/files/8413031/738431169c-crash-reports.zip)

**Comment by chaseholden** [comment]
additional crash log while not verifying anything, just normal unattended operation
[Transmission-2022-04-04-152016.ips.zip](https://github.com/transmission/transmission/files/8413466/Transmission-2022-04-04-152016.ips.zip)

**Comment by chaseholden** [comment]
additional errors:
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
HIToolbox: could not open() theme file
abort() called`

crash log
[Transmission-2022-04-04-153458.ips.zip](https://github.com/transmission/transmission/files/8413519/Transmission-2022-04-04-153458.ips.zip)

taking a break from betas to go back to old stable version

**Comment by ckerr** [comment]
> Transmission-2022-04-04-153458.ips.zip
>
> "tr_clientForId(char*, unsigned long, std::__1::array<char, 20ul>)","symbolLocation":2038,"imageIndex":7}


> Transmission-2022-04-04-152016.ips
>
> "tr_clientForId(char*, unsigned long, std::__1::array<char, 20ul>)","symbolLocation":2038,"imageIndex":7},{"imageOffset":963662,"symbol":"canRead(tr_peerIo*, void*, unsigned long*)","symbolLocation":2007,"imageIndex":7}

These are already tracked in https://github.com/transmission/transmission/issues/2878, so I'm going to minimize that discussion here to avoid crosstalk.

**Comment by ckerr** [comment]
'assertion failed: bytes_read == bytes_written (\/Users\/mac-rwngjfujyy\/workspace\/trunk-mac\/libtransmission\/file-posix.cc:522)'"],"ViewBridge":["ViewBridge hint(s): (","\"bridge key: most-recent-completion\"",")"],"libsystem_c.dylib":["abort() called"]},
  "asiBacktraces" : ["0   CoreFoundation                      0x00007ff81947b1e3 __exceptionPreprocess + 242\n1   libobjc.A.dylib                     0x00007ff8191dbc13 objc_exception_throw + 48\n2   CoreFoundation                      0x00007ff81947b04a +[NSException exceptionWithName:reason:userInfo:] + 0\n3   Transmission                        0x0000000101289b5c _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEEiS3_ + 294\n4   Transmission                        0x0000000101275609 _Z16tr_sys_path_copyPKcS0_PP8tr_error + 447\n5   Transmission                        0x00000001012135c3 _Z11tr_moveFilePKcS0_PP8tr_error + 341\n6   Transmission                        0x000000010124056c _ZL15setLocationImplP12LocationData + 1956\n7   Transmission                        0x000000010125e07a _ZL15onWorkAvailableisPv + 127\n8   Transmission                        0x00000001012e5072 event_process_active_single_queue + 502\n9   Transmission                        0x00000001012e2161 event_base_loop + 1130\n10  Transmission                        0x000000010125dc59 _ZL18libeventThreadFuncP15tr_event_handle + 253\n11  Transmission                        0x000000010125e855 _ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvP15tr_event_handleES8_EEEEEPvSC_ + 40\n12  libsystem_pthread.dylib             0x00007ff8193394e1 _pthread_start + 125\n13  libsystem_pthread.dylib             0x00007ff819334f6b thread_start + 15"],
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "lastExceptionBacktrace" : [{"imageOffset":1028563,"symbol":"__exceptionPreprocess","symbolLocation":226,"imageIndex":6},{"imageOffset":105491,"symbol":"objc_exception_throw","symbolLocation":48,"imageIndex":11},{"imageOffset":1028170,"symbol":"+[NSException exceptionWithName:reason:userInfo:]","symbolLocation":0,"imageIndex":6},{"imageOffset":1137500,"symbol":"tr_assert_report(std::__1::basic_string_view<char, std::__1::char_traits<char> >, int, std::__1::basic_string_view<char, std::__1::char_traits<char> >)","symbolLocation":294,"imageIndex":3},{"imageOffset":1054217,"symbol":"tr_sys_path_copy(char const*, char const*, tr_error**)","symbolLocation":447,"imageIndex":3},{"imageOffset":652739,"symbol":"tr_moveFile(char const*, char const*, tr_error**)","symbolLocation":341,"imageIndex":3},{"imageOffset":836972,"symbol":"setLocationImpl(LocationData*)","symbolLocation":1956,"imageIndex":3},{"imageOffset":958586,"symbol":"onWorkAvailable(int, short, void*)","symbolLocation":127,"imageIndex":3},{"imageOffset":1511538,"symbol":"event_process_active_single_queue","symbolLocation":502,"imageIndex":3},{"imageOffset":1499489,"symbol":"event_base_loop","symbolLocation":1130,"imageIndex":3},{"imageOffset":957529,"symbol":"libeventThreadFunc(tr_event_handle*)","symbolLocation":253,"imageIndex":3},{"imageOffset":960597,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(tr_event_handle*), tr_event_handle*> >(void*)","symbolLocation":40,"imageIndex":3},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":9},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":9}]

**Comment by chaseholden** [comment]
Build 8d11f0bc22
crash #1 immediately after first run 
crash #2 after 7 minutes
running for an hour+ stable thereafter so far...

[8d11f0bc22-crash-reports.zip](https://github.com/transmission/transmission/files/8441184/8d11f0bc22-crash-reports.zip)

**Comment by chaseholden** [comment]
- Build 8d11f0bc22 
- Crash #1 immediately after first run. 
- Crash #2 after 7 minutes.
- Crash #3 after

**Comment by chaseholden** [comment]
All nightlies have been very stable for past few weeks. Fantastic. Thanks developers.
