### ISSUE TITLE
Bulk import trackers to Transmission

### ISSUE THREAD

**Issue by Alkaris** [transmission/transmission#288]
A feature enhancement I would like to see in Transmission is to be able to mass import Trackers from a list and apply them to all current torrents. I was looking at other torrent clients like qBittorrent and they have a tracker import thing where you can import a list of trackers and apply them to every torrent in your download list. People can add and download huge tracker lists like these https://github.com/ngosang/trackerslist but there's no easy way of mass importing them to all current torrents without having to go to each individual torrent in the download list and manually adding them all.

additionally I think if there are dead trackers it should auto remove them after a certain time period of getting no response from them although that may add some complications since some of those trackers servers may have downtime maintenance. Retry a tracker every 1 hour if there's no response, for up to a few days or a week then auto remove or something like that.

**Comment by mikedld** [comment]
See #237.

I'm not sure second part deserves the effort; ping @charlesk.

**Comment by stefantalpalaru** [comment]
Mostly covered by https://github.com/transmission/transmission/pull/229 (without auto-removal).

**Comment by Wolvverine** [comment]
Use Shift:
https://github.com/killemov/Shift

**Comment by Codingale** [comment]
> Use Shift:
> https://github.com/killemov/Shift

I can't get Shift to do much of anything on Windows 10, the GUI works and displays torrents, but I can't bulk add trackers, seems like a dead project too?
