### ISSUE TITLE
Request: Throttle error messages in case of network error

### ISSUE THREAD

**Issue by van-de-bugger** [transmission/transmission#2883]
I run transmission-daemon 3.00-7.fc34.x86_64. message-level (in settings.json) is 1 (error messages only). Usually it works very well.

However, in case of troubles with the internet connection, transmission-daemon logs the messages like these:

    Apr 06 00:56:00 antec transmission-daemon[1178]: [2022-04-06 00:56:00.241] Couldn't connect socket 51 to 62.16.5.209, port 14082 (errno 101 - Network is unreachable) (net.c:339)
    Apr 06 00:56:00 antec transmission-daemon[1178]: [2022-04-06 00:56:00.241] Couldn't connect socket 51 to 109.184.124.160, port 50001 (errno 101 - Network is unreachable) (net.c:339)
    Apr 06 00:56:00 antec transmission-daemon[1178]: [2022-04-06 00:56:00.241] Couldn't connect socket 51 to 109.184.124.160, port 50001 (errno 101 - Network is unreachable) (net.c:339)
    Apr 06 00:56:00 antec transmission-daemon[1178]: [2022-04-06 00:56:00.241] Couldn't connect socket 51 to 79.126.60.131, port 50001 (errno 101 - Network is unreachable) (net.c:339)
    Apr 06 00:56:00 antec transmission-daemon[1178]: [2022-04-06 00:56:00.241] Couldn't connect socket 51 to 79.126.60.131, port 50001 (errno 101 - Network is unreachable) (net.c:339)
    ...

transmission-daemon writes few hundreds errors to the log in a second and flooding the log until the internet connection is restored. 

It would be nice if transmission-daemon throttles the error messages to avoid flooding the log.

**Comment by ckerr** [comment]
Fixed by #2756, which will be in 4.0.0-beta.1. There are also nightly builds at https://transmissionbt.com in the meantime.

**Comment by van-de-bugger** [comment]
Ok, thanks.
