### ISSUE TITLE
Lots of missing resume files in Message Log

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#2885]
@ckerr When looking at the message log it seems like there's a constant stream of errors like this:
`2022-04-06 01:54:06 +0000 utils.cc:306 [Error] utils.cc:306: Couldn't read '/Users/robd003/Library/Application Support/Transmission/Resume/89fa4cb8a4b413c27cb98c3c93584e982443ea6a.resume': No such file or directory (2)`

They seem to appear and vanish intermittently which I found odd. Not sure if this has anything to do with the recent changes.

**Comment by ckerr** [comment]
Looks like this is the same as https://github.com/transmission/transmission/issues/2921 which narrowed the issue down to magnet links
