### ISSUE TITLE
Consider updating 'Third Party' snapshots

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#2894]
I was wondering if @ckerr or the other devs were aware that Miniupnp https://github.com/miniupnp/miniupnp is still being actively worked on even though there hasn't been a release since 2018? I was just wondering if the version currently being used for the upcoming 4.00 beta was the same as 3.0, or some of the later developments might be worth looking into. 

I guess the same could be said for any other third-party libs.

Edit: I had a look at the Miniupnp website and this caught my eye. It might be worth spending some time comparing and contrasting with all of your C++ work Charles:

"For some reasons, it may be not the good solution for you to use the code from the MiniUPnP project directly. As the code is small and simple to understand, it is a good base to take inspiration for your own UPnP implementation. The [KTorrent](https://kde.org/applications/internet/ktorrent/) UPnP plugin in C++ is a good example."

**Comment by Coeur** [comment]
@mikedld @miniupnp

**Comment by GScottElshaw** [comment]
Having a look around.

I'm going to preamble. I am a middle-aged man and have recently been suffering (and probably making others suffer it) a little bit of, 'It seems like it was just yesterday...', and I realise there is very good reason for 'if it ain't broke...', but some of this is bordering a bit negligent that it hasn't received any attention, in one case, for nine years.

1. The version of DHT that Transmission is currently using, according to the change log in src, is from February 2018. The latest commit in the DHT repository is December 2020. https://github.com/jech/dht

2. The current version of Libb64 that is being used is 9 years old. I repeat, it is 9 years old. It deserves cake, a cup of tea and a lie down. In software years, it is Mr Jangles from 'The Green Mile'. It's been forked numerous times after development stopped NINE YEARS AGO; this repository had its last commit in September, 2020. https://github.com/libb64/libb64

3. Libdeflate is, i think, .1 version behind on the latest version of Libdeflate https://github.com/ebiggers/libdeflate

4. I think we're a .11 from the latest Libevent, the latest is 2.1.11 from August 2019. There is something mad going on there, the last attempted commit was two weeks ago, but check out all these commits and crosses for _2 years_. I get using 'release builds', but if i've learned anything on GitHub? Folks often don't have milestones or ideas of when something should be a release. https://github.com/libevent/libevent/commits/master

5. Libnatpmp is from _2012_. I ache. Forked from the original developer, Leah, (https://github.com/getlantern/libnatpmp), this is periodically being worked on by Thomas Bernard (Miniupnp) https://github.com/miniupnp/libnatpmp

6. Libpsl is up to date insofar as release date (2020), but is reasonably active. The last commit was in January. https://github.com/rockdaboot/libpsl

7. Libutp. _12 years old_. May 2018 is surely better than 12 years ago. https://github.com/bittorrent/libutp

8. Utfcpp had a commit in December 2021 https://github.com/nemtrif/utfcpp.

**Comment by ckerr** [comment]
OK, I'm going to hate myself for saying this because I've worked hard to shrink the number of open issues, but... please open separate issues for each of these that you think should be updated. :sob: 

The problem with omnibus issues like this is that we'd have to address all eight of these dependencies before the issue can be closed, making it difficult to track progress.

**Comment by GScottElshaw** [comment]
(Not) happy to, Charles; I love the feeling of more onus and pressure upon those least deserving! I'll do that, but will also do some testing on the later generations of the octogenarians Transmission is currently using.
