### ISSUE TITLE
Small fixes to formatting

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#2901]
I have tiny formatting fixes. How can I contribute them?

**Comment by catadropa** [comment]
diff --git a/libtransmission/port-forwarding.cc b/libtransmission/port-forwarding.cc
index a40e02091..bd58ac5ce 100644
--- a/libtransmission/port-forwarding.cc
+++ b/libtransmission/port-forwarding.cc
@@ -108,7 +108,7 @@ static void natPulse(tr_shared* s, bool do_check)
     if (new_status != old_status)
     {
         tr_logAddInfo(fmt::format(
-            _("State changed from '{old_state}' to '{state}"),
+            _("State changed from '{old_state}' to '{state}'"),
             fmt::arg("old_state", getNatStateStr(old_status)),
             fmt::arg("state", getNatStateStr(new_status))));
     }
diff --git a/libtransmission/upnp.cc b/libtransmission/upnp.cc
index 50948e188..cb2bdad66 100644
--- a/libtransmission/upnp.cc
+++ b/libtransmission/upnp.cc
@@ -277,7 +277,7 @@ tr_port_forwarding tr_upnpPulse(tr_upnp* handle, tr_port port, bool isEnabled, b
             UPNP_IGD_VALID_CONNECTED)
         {
             tr_logAddInfo(fmt::format(_("Found Internet Gateway Device '{url}'"), fmt::arg("url", handle->urls.controlURL)));
-            tr_logAddInfo(fmt::format(_("Local Address is '{address}')"), fmt::arg("address", handle->lanaddr)));
+            tr_logAddInfo(fmt::format(_("Local Address is '{address}'"), fmt::arg("address", handle->lanaddr)));
             handle->state = UpnpState::IDLE;
             handle->hasDiscovered = true;
         }
@@ -341,7 +341,7 @@ tr_port_forwarding tr_upnpPulse(tr_upnp* handle, tr_port port, bool isEnabled, b
             handle->isMapped = err_tcp == 0 || err_udp == 0;
         }
 
-        tr_logAddInfo(fmt::format(
+        tr_logAddDebug(fmt::format(
             _("Port forwarding through '{url}', service '{type}'. (local address: {address}:{port})"),
             fmt::arg("url", handle->urls.controlURL),
             fmt::arg("type", handle->data.first.servicetype),
@@ -350,7 +350,7 @@ tr_port_forwarding tr_upnpPulse(tr_upnp* handle, tr_port port, bool isEnabled, b
 
         if (handle->isMapped)
         {
-            tr_logAddInfo(_("Port forwarding successful!"));
+            tr_logAddInfo(fmt::format(_("Port {port} is forwarded"), fmt::arg("port", port)));
             handle->port = port;
             handle->state = UpnpState::IDLE;
         }

**Comment by catadropa** [comment]
Before:
```Sat Apr  9 08:06:01 2022	Information	port-forwarding.cc:110	State changed from 'Starting' to 'Forwarded
Sat Apr  9 08:06:01 2022	Information	upnp.cc:353	Port forwarding successful!
Sat Apr  9 08:06:01 2022	Information	upnp.cc:344	Port forwarding through 'http://192.168.0.1:49152/soap.cgi?service=WANIPConn1', service 'urn:schemas-upnp-org:service:WANIPConnection:1'. (local address: 192.168.0.100:51413)
Sat Apr  9 08:06:01 2022	Information	upnp.cc:280	Local Address is '192.168.0.100')
Sat Apr  9 08:06:01 2022	Information	upnp.cc:279	Found Internet Gateway Device 'http://192.168.0.1:49152/soap.cgi?service=WANIPConn1'
Sat Apr  9 08:05:59 2022	Information	port-forwarding.cc:110	State changed from 'Not forwarded' to 'Starting
```

**Comment by ckerr** [comment]
Hey, thank you!

Would you mind opening a pull request with these changes?

**Comment by ckerr** [comment]
I had another string fixup PR queued up as #2913, so I've added these diffs to that with you as the commit author and me as the committer.

Thanks for the diff!
