### ISSUE TITLE
`rpc-socket-mode` is set as decimal representation, not octal

### ISSUE THREAD

**Issue by erictapen** [transmission/transmission#2904]
Since https://github.com/transmission/transmission/commit/706735ca88e547dcda2306fb448b694f7f6fb6c0, it is possible to set the mode of the unix domain socket that transmission can listen on. The default mode is `755`, but in `settings.json` it is shown as `493` (the decimal representation of 0o755).

I think it would be more intuitive to make that setting a string, as unix permissions are rarely displayed and configured in decimal? So one could set the value to `"770"`, without looking up the decimal representation first.

**Comment by ckerr** [comment]
Sounds good. If anyone wants to write a PR, I'd be happy to review

**Comment by maxz** [comment]
If we make that setting a string, `umask` should also become a string.
And if that should not be possible due to backwards compatibility reasons, then `rpc-socket-mode` should in my opinion also remain in decimal representation, since having one umask as a string and the other one in decimal representation would be madness.

**Comment by maxz** [comment]
I took a look at what changes would be required.

After a brief look yesterday, I thought that some rather small changes in `session.cc` would suffice.
Now after a better look, is seems that this would need to be changed in `variant-json.cc`, specifically by adding a special case to `action_callback_POP`. My solution right now without better knowledge of the code would be to add a special case to dispatch on the keys `umask` and `rpc-socket-mode` within the `JSONSL_T_STRING` section and then either use `strtol` or something self rolled similar to `decode_hex_string`.
This should then work for decimal integers (which would still use the regular parsing) as well as strings.
Yet it seems rather inelegant to add a special case there.
I did not take a look at the reverse path yet (writing strings with the octal values to the `settings.json`).

What are your thoughts on this, @ckerr?
Does this seem like a valid place for those modifications or can you suggest a better one?

**Comment by erictapen** [comment]
Awesome, thanks!
