### ISSUE TITLE
Issues with webseed torrents

### ISSUE THREAD

**Issue by qu1ck** [transmission/transmission#2909]
There are few issues that I'm observing with webseed torrents ranging from critical bugs to undesired behavior:

Bugs:
1. Downloading torrent never finishes and gets stuck at <100%.
2. Downloading torrent reaches 100% but never finishes.
3. Torrents stuck in downloading state at 100% upon daemon restart switch to seeding with incomplete data (!!)

By incomplete data I mean .part files and files with 0x0 blocks on disk.

I have torrent files I can provide upon request that reliably produce this behavior on current master build. uTorrent downloads these files fine. 

Undesired behavior:

Transmission sends a lot of requests to webseed server. This results in throttling and 429 responses, which may be cause for bug 1)
Ideally there would be a config parameter but as a quick fix it's reasonable to limit parallel requests per webseed to 5-10.

**Comment by robd003** [comment]
I've been having the same errors with regular torrents too. See ticket https://github.com/transmission/transmission/issues/2910

**Comment by qu1ck** [comment]
In my case transmission reports all pieces are downloaded but some of the data is never actually saved on disk.

**Comment by killemov** [comment]
> In my case transmission reports all pieces are downloaded but some of the data is never actually saved on disk.

This has been my experience as well.

**Comment by qu1ck** [comment]
My disk still has ~300gb of space.

**Comment by killemov** [comment]
Ok, yet another layer of weirdness it is.

**Comment by Deathcow** [comment]
I've observed similar issues since the recent webseed rewrites: The download "finishes" (100%), but after triggering a manual verify many files are actually stuck at 99%. Re-Downloading the missing chunks never solves the issue, no matter how many times I seem to verify and re-download. The data is either never downloaded correctly or not written to disk correctly.

**Comment by robd003** [comment]
I'm experiencing the same issue as @Deathcow but with regular torrents, not just webtorrents.

**Comment by GScottElshaw** [comment]
Same here, @robd003. Verifying the data using the nightly proved fruitless, and i fired up 3.0 and discovered half of the data was corrupt. I scrapped it all and started fresh on 3.0 release.

**Comment by Deathcow** [comment]
@ckerr I can confirm that the recent commit seems to fix the issue.

**Comment by qu1ck** [comment]
@ckerr I can confirm that torrents now complete download most of the time but unfortunately if there are a bunch of webseed torrents in the list the daemon becomes unresponsive and I don't have a reliable repro for this. But it happened 2 times.

I am not sure if it's relevant but webseed torrents I download are small (10-50mb), consist of ~100 files 20kb-500kb each and the piece size of the torrent is also small, usually 32kb. Both times I had the daemon lock up I had about 30 of such torrents in the list seeding and 3 downloading (queue limit).

**Comment by AskOldIch** [comment]
Hello!

Can you check the next torrent?
https://archlinux.org/releng/releases/2023.01.01/torrent/
ArchLinux uses webseeds for own iso. And `transmission-gtk 3.00 (bb6b5a062e)` always as if freezes when starting a torrent.
0% progress, but I see incoming traffic through system utility (>50mb/s) and empty download folder. Cannot delete torrent, without hard reset the program (after starting this torrent is stopped and I can to delete and transmission starts to work well (don't freeze)).

This a problem was always when ArchLinux began to distribute own iso through webseeds.

**Comment by ckerr** [comment]
FWIW, https://archlinux.org/releng/releases/2023.01.01/torrent/ works just fine for me using `main`.

There is a recent webseed fix (#4601) that landed after `4.0.0-beta.3` that may be related.
