### ISSUE TITLE
Updated to Transmission 3.00 not connecting to tracker issues

### ISSUE THREAD

**Issue by wrekkbeach** [transmission/transmission#2912]
Hi 
I just upgraded Transmission and it isnt connected to a specific torrent tracker that I have been using for a while. This build is listed on their whitelist so it should be fine. I successfully uploaded something to the tracker and it seeded once from what the ratio info is telling me but stopped after 1.11 ratio and hasnt continued since. Its been weeks. I tried restarting app and system. nothing. also tried reaching out to the exclusive torrent site's staff and they were not very helpful and told me to test with another client. I tried a few tpb torrents and they worked perfectly so its local to this specific sites tracker. Short of downgrading to an ealrier transmission build i dont know what else to do.
any ideas would be appreciated
thank u

**Comment by robd003** [comment]
Which tracker is having the issue?

**Comment by Coeur** [comment]
I suggest contacting the tracker owner?

If you have an error message regarding your connection failure, please post it.

In the mean time, as it's not possible to take action with the information provided, I'll close this issue. I can reopen it if you answer some of the questions. Thank you for your understanding.
