### ISSUE TITLE
Allow Users to Manually Select Piece Size on Linux and Windows Clients

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#2918]
This has already been done for MacOS but not Linux and Windows according to https://github.com/transmission/transmission/issues/2416

Transmission is falling behind by not having features like the ability to manually select a newly created torrent's piece size so we need to have this feature ASAP. This feature has been in pretty much every client since uTorrent and it's about time Transmission also has it. Piece size selection is more important than ever as torrent sizes are bigger than ever, and they are not going to get any smaller.

If we want Transmission to gain more users and more contributors, we need to be willing to have the same basic features as other popular open-source torrent clients.

- qBittorrent has piece size selection
- Deluge has piece size selection
- ktorrent has piece size selection
- BiglyBT has piece size selection

Please implement piece size selection! For the good of the project, if nothing else!

**Comment by ckerr** [comment]
If someone wants to write this PR, I'm happy to review it.
