### ISSUE TITLE
Error in add/resume logic for magnet links

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#2921]
When I add a torrent to transmission from a magnet link, even before I click on Add, an error is emitted in the log like this:
```
Fri Apr 15 15:44:42 2022        Error   utils.cc:260    Couldn't read '/home/username/.config/transmission/resume/50m3h45h50m3h45h.resume': No such file or directory (2)
```
This does NOT happen when adding a .torrent file to transmission. So there seems to be a logic problem where the resume code gets triggered before adding a magnet file.
There don't seem to be any ill effects from this behaviour, other than an error log being emitted for every magnet link added. But perhaps it still warrants a rethink of the logic?

**Comment by ckerr** [comment]
Yeah. It's not causing any harm, but the error messsage isn't really an error so it should be silenced.

**Comment by marcelpaulo** [comment]
I've just built from latest git (185f1f96a520f0f9af23333cf667483a2be7355e) as of 2022-08-27:

```
paulo@monk:~/src/transmission$ transmission-daemon --version
transmission-daemon 3.00+ (185f1f96a5)
```

 and Transmission still complains right after a magnet link is added:

```
ago 28 01:55:26 monk transmission-daemon[6026]: [2022-08-28 01:55:26.024] ERR utils.cc:76 Couldn't read '/home/paulo/.config/transmission-daemon/resume/bd6497576261b2c5e429ac845399b7cfdff2c345.resume': No such file or directory (2)
```
