### ISSUE TITLE
improper accounting of leechers during on_announce_done

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#2932]
Back in the pre-C++ code, a change was made to optimize torrent startup on the assumption that trackers now include the "leechers" scrape info in the announce info. This is often (actually mostly) not true.  I made this patch but it no longer applies to the C++ version, hoping that it gets picked up there.

The result of the change to reset "leechers" regardless of whether it was set in the announce response is that the leecher count is always updated (and zeroed) by announce and only briefly updated by scrapes, and the swarm is never joined.. Note that this fix depends on the response->leechers field being preset to -1 in tr_tracker_http_announce()

```
announcer.c

@@ -1235,7 +1235,12 @@ static void on_announce_done(tr_announce_response const* response, void* vdata)
                 publishPeersPex(tier, seeders, leechers, response->pex6, response->pex6_count);
             }

-            publishPeerCounts(tier, seeders, leechers);
+            /* Only publish leechers if it was actually returned during the announce */
+            if (response->leechers >= 0)
+            {
+                tr_logAddTorDbg(tier->tor, "publishing peer counts: %d seeders %d leechers", seeders, leechers);
+                publishPeerCounts(tier, seeders, leechers);
+            }

             tier->isRunning = data->isRunningOnSuccess;
```

**Comment by ckerr** [comment]
@reardonia any reason you're submitting this as a diff instead of as a pull request? The latter is easier to merge.

**Comment by reardonia** [comment]
apologies

1) It's an old local patch against the pre-C++ codebase. I am not tracking C++ codebase.

2) I'm not setup for pull requests on github.

3) This was just a quick patch. But I think the logic in on_announce_done() is still a little problematic, I think a better fix would:
    not create locals and just push the check into publishPeerCounts()
    publishPeersPex() is not dependent on and should not use seeders & leechers stats
    probably treat scrape_fields as a mask rather than a counter.
    clarify throughout the announcer and scrape code that counts of -1 designate fields not returned in response.
    establish checks for -1 wherever tracker stats are set, probably through a universal setter func.

**Comment by ckerr** [comment]
5164 improved this but PR author @reardonia notes that "it really deserves a more complete refactor":

> A better version of this would redo publishPeerCounts() and publishPeersPex(), make clear that "-1" means "no update", and would add "downloads" to the tr_tracker_event object.

**Comment by tearfur** [comment]
@reardonia What would `downloads` do in `tr_tracker_event`? This struct is used to store arguments to `tr_torrent::on_tracker_response()`, and I don't see where it would be used.
