### ISSUE TITLE
use libpopcnt for bitfield counting

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#2938]
Suggested by @goldsteinn in https://github.com/kimwalisch/libpopcnt.

`std::popcnt` exists in C++20; but in the interim, this header-only library could be used.

**Comment by goldsteinn** [comment]
Hi @ckerr,

I think to add the submodule someone with write access in https://github.com/transmission needs to fork libpopcnt first. Not sure how else this can be accomplished in a PR unless you're okay with using a personal fork/the main repo.

**Comment by ckerr** [comment]
@goldsteinn done @ https://github.com/transmission/libpopcnt, if you're going to PR looks like the latest stable tag is v2.5, so that would be my preference for the submodule.

BTW if you don't have Xcode, it's not _too_ hard to get the macOS project working correctly for third-party header-only libraries. See the three places where `third-party/utfcpp/source/` was added in bbe49639d694f2ec346708e7acb9ab365d501a10; it should probably be the same thing for libpopcnt .

And thanks!

**Comment by goldsteinn** [comment]
> @goldsteinn done @ https://github.com/transmission/libpopcnt, if you're going to PR looks like the latest stable tag is v2.5, so that would be my preference for the submodule.

Was planning to use:
https://github.com/transmission/libpopcnt/pull/1

Since the head version doesn't have a 32-bit API.

Also wasn't planning on using the `popcnt()` API but the underlying `popcnt32`/`popcnt64`. Think `popcnt()` api is only worth it if bitfield size is expected to be very large, otherwise vectorization will incur more overhead than its worth.

What do you think?

> 
> BTW if you don't have Xcode, it's not _too_ hard to get the macOS project working correctly for third-party header-only libraries. See the three places where `third-party/utfcpp/source/` was added in [bbe4963](https://github.com/transmission/transmission/commit/bbe49639d694f2ec346708e7acb9ab365d501a10); it should probably be the same thing for libpopcnt.
> 
> And thanks!

Thanks (on ubuntu but was able to figure it out).

**Comment by goldsteinn** [comment]
Made #2950 which scraps using `libpopcnt` and just makes a new header file.

**Comment by ckerr** [comment]
Closing this ticket as fixed by https://github.com/transmission/transmission/pull/2950 but @goldsteinn I'm happy to review more PRs if you want to speed this up further

**Comment by goldsteinn** [comment]
> Closing this ticket as fixed by #2950 but @goldsteinn I'm happy to review more PRs if you want to speed this up further

Do plan on adding a popcnt that handles large ranges well. When is the next release scheduled for? Ideally would get it done by then.
