### ISSUE TITLE
[Feature request] remote: Select torrents by label

### ISSUE THREAD

**Issue by lajp** [transmission/transmission#2948]
Labels have already been supported in the remote for a while but currently it's only possible to set them and to print them. 
It would be cool to be able to select torrents with their labels similarly to how the `-t` argument works.

My ideal implementation for this would be to merge it to the `-t` argument so that running `transmission-remote -t film -l` would list all the torrents with the `film` label and `transmission-remote -t tv -S` would stop all the torrents with the `tv` label. 
Hopefully you get the idea.

Lastly I'd like to state that I'm willing to start working on an implementation myself once someone has validated my idea.

**Comment by valcomm** [comment]
What's your approach about dealing with labels like '123' or labels that consist of 40 hex digits?

**Comment by lajp** [comment]
That's the main thing I'm unsure of, perhaps there could be some special syntax for selecting labels for example something like `-t [somelabel]`

The other obvious problem is labels containing the `,` character that is used as a separator.

**Comment by lajp** [comment]
Having an entirely separate command for selecting labels is not a bad idea either. For me anything goes as long as something gets implemented and it's even moderately usable.

**Comment by valcomm** [comment]
`[somelabel]` isn't great as square brackets have a special meaning to shells.  And even if it's not that - would be interesting to process correctly one or two square brackets as a part of label.
And you highlighted yourself problems with `,`.

By my opinion setting and printing them is enough.  They're not a some kind of selector.  Just a grouping with limited functionality.  When transmission-remote would be able to output received JSON, it can be filtered (by having a label, or specific label) and translated to required ids.  Right now there's no raw JSON, but that doesn't mean there's a real need for another very rarely used complexity.

**Comment by lajp** [comment]
The main reason behind me wanting this feature is the fact that I personally use the remote for all the management of my torrents and not being able to operate on them based on some logically assigned groups and instead just relying on the ids is getting more and more difficult when I'm adding more torrents.

**Comment by valcomm** [comment]
I understand your situation. I've got a similar one.  Correct way would be having raw received JSON fed to the tool (e.g. `jq`) that would do any required processing and filtering.  As currently there is no way to get a JSON from `transmission-remote`, I had to write a library use it in my pile of scripts.
It's possible to solve it with the third approach that you suggesting.  But as I said it'd be a very rarely used complexity.  Complexity in code, manual and interface with some special cases (separation, special characters, differentiating between id, hash and others).  By my opinion labels processing is better to be done by some external tool.  Transmission already provides enough bricks for you to build a wall

**Comment by lajp** [comment]
I understand and value you're opinions but I disagree with the last part. The main thing why I'm even using transmission is the sheer power of the remote and it's command line arguments. I think the remote is missing out by not being able to filter torrents with their labels which AFAIK is possible on at least some of the GUI interfaces (I haven't tried any of them so I'm not 100% sure).

I think that having to rely on some shell-scripts and 3rd party libraries is not ideal in this case and my opinion is that filtering and selecting by labels in transmission-remote should be possible.

I think I'll go ahead and write this feature for myself regardless of whether It's acceptable to be added to the main build. But thanks for your input and I wish others to also express their thoughts about this.

**Comment by MatanZ** [comment]
I agree that this feature can be quite useful.

I suggest using a separate command line switch, rather then co-opting `-t`:

- This will allow selecting only from some range: `transmission-remote -t 1-50 -select label:abc`
- This feature requires some work, since currently filtering based on the result of torrent-get RPC call is not possible. If the work is done it can be used for more selection criteria, like status (downloading, seeding, etc.), tracker, and many other things.

I already did a bit of work on this, but did not get very far, so I will wait to see your code.

**Comment by MatanZ** [comment]
I checked and saw that my code is in a more advanced state that I remembered, and is actually working, so you can see it in [this branch](https://github.com/MatanZ/transmission/tree/remote_filter) to compare.

**Comment by killemov** [comment]
Related to #1656 .

**Comment by lajp** [comment]
For my needs this was resolved by #3125
