### ISSUE TITLE
transmission 2.92: aggressive disk write i/o load caused by logging subsystem

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#295]
Hello,
this has been reported to Debian as http://bugs.debian.org/858932:

> today i've noticed that my home-server (file storage and sharing machine) blinks "disk i/o" LED frequently - approx. every second. and putting my ear close, i could hear the disk starting to spin and stopping with the same frequency. after stopping some services, i saw that stopping t-d stops that crazy disk i/o.
> 
> installed and ran iotop, i saw t-d at the top line, showing some numbers in "write" column - thus, meaning frequent attempts to write smth on disk. the thing is that on this disc (/dev/sda) there is nothing but a system itself, all the file storage (and seeds) is placed on external drives.
> 
> my first thoughts was that it is writing a lot to logs, but nothing new was appearing neither in syslog/dmesg/etc, nor in /var/log/transmission-daemon, which contained just a few lines (t-d is run with --log-error). but once i changed options in /etc/default/transmission-daemon to "-e /dev/null", this suspicious disc activity stopped right away, leaving my disc in peace.
> 
> i haven't tested other versions (and not sure if they would install on testing), but at least current version from testing suffers from this. please review this issue as soon as possbile, since it causes stress to users' discs and lead them to failure.
> 
> i can provide some strace or whatever or test some patched versions, let me know if any help is needed

**Comment by spooker** [comment]
is this going to be fixed? I have the same issue for a long time with 2.92. This seems to have a great impact on devices with limited resources such as the raspberry pi. This stresses the sd cards on these devices on the long run.

**Comment by sandrotosi** [comment]
the implication is that if explicitly setting `-e /dev/null` causes the issue to go away, there was logging happening, now, the fact that the log file was not updated, could simply mean that something/someone removed it without bouncing the service, which will continue to log to the old file description (the classing `lsof | grep deleted` situation)
