### ISSUE TITLE
Transmission is unusable

### ISSUE THREAD

**Issue by fre123ber** [transmission/transmission#2977]
I always have the same problem where the download speed is intermittent, as you can see in the video below. It doesn't matter which version, it always happens with all the last nightlies since months, I believe.
I must say that the speed gets stable after a reboot or two, or after some time using the same nightly build, but when I update to the last build, Transmission manifests the same problem again.
When the speed gets stable, with Transmission I can reach almost 40 MBps. As a comparison, I tried downloading with qBittorrent and I could reach a speed of 70+ MBps.
As you can understand, this makes Transmission's experience very poor compared to other clients. Usually when Transmission acts up like this, you have to try and open it again, or reboot the computer. Most of the time it doesn't work. Connection to peers is very slow compared to other clients, and I have to wait a long time when adding a magnet link.
Are the developers aware of this problem?

https://user-images.githubusercontent.com/17521141/164982926-2ff7994b-33ee-46e3-9e67-71a8c3efc4e6.mov

After restarting Transmission:

https://user-images.githubusercontent.com/17521141/164982930-625fbcea-bf49-4466-8cf5-4bb889620320.mov

This is a very popular torrent...

**Comment by ckerr** [comment]
From the videos, it looks like the transfer rate keeps periodically dropping to 0. This is a common symptom of #2462; closing this as a duplicate.

On tone -- Also filing a bug report like, "Transmission is unusable"  is just very demoralizing. I've been putting multiple hours per day of work to improve Transmission for the last six months, so to open up the issues to do triage and read a message like "Hey developers, are you aware your app is unusable?" ... was it your intent to send this kind of a message?  What were you hoping to achieve?

On substance though -- despite the many complaints (slow speed, slow magnets, slow to find peers) there is almost no actionable information here. Without the movie showing the speeds dropping to zero I wouldn't know to connect this to 2462 and the whole thing seems more like a rant than a bug report.

Closing as duplicate + user blocked for 30 days
