### ISSUE TITLE
webseeds in torrent properties

### ISSUE THREAD

**Issue by vv01f** [transmission/transmission#298]
would like to easily *read* and **edit** webseeds of a torrent from within the GUI

* [ ] show list of webseeds
* [ ] enable adding webseed
* [ ] make changes available to magnet uri and torrent file without changing info hash

until now we can only copy the magnet uri and see if there is a `ws` parameter and edit it that way manually which is not a nice ux due to e.g. urlencoding

**Comment by Ademord** [comment]
Also **transmission-create** from the CLI doesn't support this either. Anyone who can provide any updates on this?

**Comment by Mlocik97** [comment]
I would really like to have ability to add webseed (at least for creating new torrent)

**Comment by ckerr** [comment]
> I would really like to have ability to add webseed (at least for creating new torrent)

Fixed in #2611

**Comment by killemov** [comment]
Although @vv01f  closed this issue, the fix only implemented adding webseeds for `transmission-create`.

@ckerr Please explain why setting webseeds with `torrent-set` would not be feasible (Even though implementing webseeds_ex made things more complicated.) or reopen this issue.

**Comment by Firefishy** [comment]
FYI: I have a minimal tool for modifying just the torrent seed lists, the seed list can be changed without changing the torrent hash: https://github.com/Firefishy/torrent-edit-webseed

It would be great if transmission could also do it.
