### ISSUE TITLE
tr_sessionSetPeerPortRandom doesn't return a random port

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#2983]
@ckerr 
https://github.com/transmission/transmission/blob/ca13842c8458ee2c84f3a55befae0e36e95eca05/libtransmission/session.cc#L1265-L1271

`setPeerPort(getRandomPort(session));` will change the **public** port.
`return session->private_peer_port.host();` will return the **private** port.

Consequence: the "Randomize" button implementation doesn't work: it always keep the same port.
https://github.com/transmission/transmission/blob/ca13842c8458ee2c84f3a55befae0e36e95eca05/macosx/PrefsController.mm#L413-L416

It might have been an older issue, or it got broken with #2952.

**Comment by ile6695** [comment]
Could this be fixed by using a different, already made, function that changes both ports or does it mess up cases where public and private ports need to be different?
I did not fully test this, because I didn't find "Randomize" button on qt client.
```
-    session->setPeerPort(getRandomPort(session));
+    setPeerPort(session, getRandomPort(session));
```
