### ISSUE TITLE
Transmission's copy of the .torrent and .resume files should include a fragment of the torrent name

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#2988]
For several years, whenever I add a .torrent (from any/all kinds of places, on FreeBSD UNIX and Slackware64 GNU/Linux separately) I have to twice.  First says .torrent file is corrupt, but second time usually works.
        So, I use magnet links.  However then it names files <magnet_hash>.torrent instead of <name>.torrent; there should be option to use real torrent name.  I actually look through .torrent & .resume files (and tried scripts on like transmission-batch-move) so want filenames readable like all my others.  I know most younger people don't understand filesystems (fs) and may not read filenames much, but I'm not and I do.

**Comment by ckerr** [comment]
OK there seem to be two separate problems here -- one, the bug report of having to add a torrent file twice, and the other being a feature request to keep the filenames in the original `${name}.torrent` naming scheme.

We originally used `${name}.torrent` (and `${name}.resume`) for exactly the reason  you describe, but that approach causes edge cases of name collisions and names that are too long for a given filesystem.

For the bug report of Transmission incorrectly thinking a .torrent file is corrupt: would it be possible to try a nightly build from transmissionbt.com and see if the problem persists? I don't know what version you're using, and the nightlies have a _huge_ number of changes queued up. Unitl 4.0.0-beta.1 is released, the nightly builds / tarballs are probably the best way to test against the current codebase.

**Comment by dchmelik** [comment]
Full name .torrent files would be enough; I don't care about .resume as seem mostly/all plain-text so transmission-batch-move works... just with .torrent files often it's mostly/all binary so if I look inside I can't even find out what some are anymore without a real name...
        I currently use  transmission-3.00-x86_64-2_SBo  (and have an older SlackBuilds.org, SBo, transmission-qt) but can try a nightly version... I hope SBo has newer transmission-qt soon...,

**Comment by killemov** [comment]
> Full name .torrent files would be enough; I don't care about .resume as seem mostly/all plain-text so transmission-batch-move works... just with .torrent files often it's mostly/all binary so if I look inside I can't even find out what some are anymore without a real name...

Using the hash for the name is logical and, though inconvenient maybe, prevents easily preventable problems. You should not touch internalized .torrent files anyway. The one thing I don't understand is that renamed payload files in the UI do not get propagated back to these internalized .torrent files. Also these files are not binary, they are bencoded. I use grep sometimes to find some keyword within these .torrent files.

**Comment by ckerr** [comment]
> The one thing I don't understand is that renamed payload files in the UI do not get propagated back to these internalized .torrent files.

Changing the filenames in the .torrent file's info dict would change the info hash, so the original filenames in the .torrent file are left unchanged and the renames are kept in the corresponding .resume file.

**Comment by dchmelik** [comment]
Non-human-understandable filenames are illogical because people share .torrents a lot also: some are hard to find, or on some p2p services, one might tell someone it's faster to get the .torrent then they do.

**Comment by ValZapod** [comment]
> Non-human-understandable filenames are illogical because people share .torrents a

Well, but it is comforatble. You can use https://btdig.com/ to search for that hash. It is very comfortable.

**Comment by dchmelik** [comment]
It's uncomfortable because of another bug from maybe 10+ years ago: if data stops being detected until you update location (typically after a crash) you have to find the .torrent to reopen after removing, so I want my readable config/transmission/torrents/ back.  Every claim you make non-human-understandable filenames are somehow usable/good I'll argue against.  They're not logical, not comfortable, not anything else except a mess.

**Comment by killemov** [comment]
@dchmelik The one thing you seem to skip over is that these torrents are internalized. They might as well be blobs in a database or gzipped, you should not touch them. You have an excellent point when it comes to the bug you mentioned: File not found => remove + readd. This has become such a regular occurrence that I implemented an automated process for it in [Shift](https://github.com/killemov/Shift).

**Comment by dchmelik** [comment]
When I started using computers, you knew what every file on your system is and could count them; I don't consider any file 'internalized:' if they were in a database (not just tarball) they'd be internalized, but they're not. _All_ reasons I described are relevant, including people download & place (into config/transmission/torrents/,) share & search for named .torrent files so want to know those names: not having unreadable filesystem nor useless/unreadable search results in other p2p sevices people  search such files and want to read meaningful names.

**Comment by andreygursky** [comment]
> In event you want to transfer/restore .torrents you'd want to read meaningful names.

Yes, and in case of some issues, I can easily find and check files. Thus I'm looking for the patch to switch back to the long standing ```${name}.${first 16 chars of hash}.torrent/.resume``` scheme. Ideally it would be a configuration option in ```settings.json```.

**Comment by dchmelik** [comment]
Andreygursky's description that name-hash{.torrent|resume} was allowed would be better.

**Comment by dchmelik** [comment]
Sometimes people switch torrent clients which is part _why_ the claim users don't use torrent files is absolute nonsense.

**Comment by dchmelik** [comment]
> Thus I'm looking for the patch to switch back to the long standing `${name}.${first 16 chars of hash}.torrent/.resume` scheme. Ideally it would be a configuration option in `settings.json`.

Did you ever find it?

**Comment by dchmelik** [comment]
@andreygursky
> Thus I'm looking for the patch to switch back to the long standing `${name}.${first 16 chars of hash}.torrent/.resume` scheme. Ideally it would be a configuration option in `settings.json`.

Ddid you ever find it?
