### ISSUE TITLE
consider updating dht to 0.27

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#2998]
@ckerr Transmission currently uses dht 0.25 from February 2018. 0.26 was released in December 2018. The latest commit to the repo was 28 December 2020.

I downloaded the current repo and built Transmission using the 28/12/20 repo with the current cmakefile and everything is running fine.

gh repo clone jech/dht

**Comment by jech** [comment]
Tagged 0.27.  Thanks for the reminder.

**Comment by killemov** [comment]
So change the title to 0.27 as well?
