### ISSUE TITLE
Windows 2.92 build is missing web interface files

### ISSUE THREAD

**Issue by axfelix** [transmission/transmission#300]
Enabling web interface in the newest Transmission for Windows throws a "couldn't find Transmission's web interface files" in the browser -- I assume these were just missing from the build given that it's responding to the HTTP request properly?

This worked in an unofficial Windows build of Transmission-Qt I installed a year ago so I don't think it's a platform limitation.

**Comment by hhrhhr** [comment]
can't confirm.

filename: transmission-2.92-x64.msi
size: 15200256 байтов (14 MB)
SHA256: 8CEE6436E79D48409D76A85BBB1BB506C8C76C8F686551B9E7E13B9A2CA2299D

![clipboard01](https://cloud.githubusercontent.com/assets/966048/26560729/78ef5e72-44c1-11e7-89ac-c1a80cdb0b7d.png)
![clipboard02](https://cloud.githubusercontent.com/assets/966048/26560728/78ee2c00-44c1-11e7-8c7f-3529e6cc97d2.png)
![clipboard03](https://cloud.githubusercontent.com/assets/966048/26560730/78f370b6-44c1-11e7-9dfa-b148224cb1ad.png)

**Comment by axfelix** [comment]
Oh, this is probably a bug with Choco's installer then! Thanks, will mention it there.
