### ISSUE TITLE
Investigate the TeamCity disk space issue

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3007]
>Just a heads-up that TeamCity is down.
> 
> ![SCR-20220428-kyn](https://user-images.githubusercontent.com/69029666/165668919-7366075c-13eb-4ba4-a65b-28bc4dae8766.png)
> 
> _Originally posted by @GScottElshaw in https://github.com/transmission/transmission/pull/3001#discussion_r860434027_

> After some new targets were added to the Xcode project, the size of build artifacts has increased significantly. So much so that all "MacOS/x86_64 (xcodebuild)" build configuration artifacts are now twice as big as those of "Windows/x64"...
> 
> _Originally posted by @mikedld in https://github.com/transmission/transmission/issues/3001#issuecomment-1111711395_

Possibly caused by #2976

**Comment by GScottElshaw** [comment]
It's a TC issue rather than a MacOS TC issue, those binaries should have _always_ been built. I'm hoping TC has the ability to remove iterative builds from cache before storing final pull?

**Comment by ckerr** [comment]
CI has been broken for 3-4 days now; Sanity fails when trying to upload Windows artifacts

**Comment by GScottElshaw** [comment]
I just noticed TC has an [update](https://www.jetbrains.com/teamcity/download/index.html?fromServer) available ¯\_(ツ)_/¯

**Comment by GScottElshaw** [comment]
Madness. [Agents](https://trtc.mikedld.com/agents.html?fromExperimentalUI=true)
16
[Queue](https://trtc.mikedld.com/queue.html)
52

**Comment by Coeur** [comment]
@mikedld can you disable the Windows builds until the issue is resolved?

**Comment by GScottElshaw** [comment]
> @mikedld can you disable the Windows builds until the issue is resolved?

I was wondering if it was necessary to have Windows builds on TC when there are Windows builds being done on Appveyor?

**Comment by ckerr** [comment]
> I just noticed TC has an update available ¯_(ツ)_/¯

:trollface: 

LLOL

**Comment by ckerr** [comment]
> > @mikedld can you disable the Windows builds until the issue is resolved?
> 
> I was wondering if it was necessary to have Windows builds on TC when there are Windows builds being done on Appveyor?

Yes, slightly different builds IIUC

**Comment by GScottElshaw** [comment]
> Yes, slightly different builds IIUC

Crap :-(

**Comment by GScottElshaw** [comment]
I think we may have just killed TC https://trtc.mikedld.com/viewLog.html?buildId=206833&buildTypeId=Transmission_Sanity

**Comment by ckerr** [comment]
Looks like @mikedld got it all going again :green_heart:
