### ISSUE TITLE
Consider updating libdeflate to 1.10

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#3009]
Libdeflate 1.10 was released on 7 February 2022. I've compiled and tested locally using the two current cmakefiles successfully. MacOS Monterey 12.3.1.

**Comment by GaryElshaw** [comment]
Just a heads up...
![SCR-20220508-307](https://user-images.githubusercontent.com/69029666/167257993-695575f2-3f57-4988-9505-ea671acdb58a.png)
