### ISSUE TITLE
Windows 2.92: do not support colon in filenames

### ISSUE THREAD

**Issue by hhrhhr** [transmission/transmission#301]
Can't create directory and files with colon in name. After manually editing the file name some time after the startup, an error occurs: `Unable to save resume file: Unknown error`. In "resume" directory (`%LOCALAPPDATA%\transmission\Resume` in my case) a file is created with a part of the name before the colon.

torrent example (colon in name of directory) — http://mirror.orbiter-radio.co.uk/orbiter/Orbiter2016HiResEarth.torrent
torrent metadata:

| param | value |
| ---: | :--- |
| Directory | Orbiter 2016 High Res: Earth |
| Created On | 08/28/16 20:00:22 |
| Created By | mktorrent 1.0 |

| Filename | File Size |
| ---: | :--- |
| Cloud.tree | 294.29 MB |
| Elev.tree | 16.05 GB |
| Elev_mod.tree | 504.81 KB |
| Mask.tree | 2.11 GB |
| Surf.tree | 14.38 GB |

**Comment by mikedld** [comment]
See #61.
