### ISSUE TITLE
Consider updating utfcpp to 3.2.1

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#3010]
Tested on MacOS Monterey, it compiles within Transmission without change.

Did i mention that all of these recommendations are being made in aggregate? I am not backing out any of these third-party pieces, if they work they stay in this fork.

**Comment by ckerr** [comment]
Can you give a rationale for this?

The diff between the version we're using and 3.2.1 is exactly two commits: https://github.com/nemtrif/utfcpp/commit/a92f85526ba3027f843c6523f1d6ddb7ccf9d223 and https://github.com/nemtrif/utfcpp/commit/d8b92208fddde08d628004563a1a3614a32cf8c8 . Are either of these needed by Transmission?
