### ISSUE TITLE
Consider updating libpsl from current repo

### ISSUE THREAD

**Issue by GScottElshaw** [transmission/transmission#3011]
Although the last release was in July 2020 there have been intermittent commits until February of this year. I download the repo, addded the current cmakefile into the root, and it compiles and runs fine.

gh repo clone rockdaboot/libpsl

**Comment by ckerr** [comment]
Can you give a rationale for this? The diffs between the version Transmission is using and upstream is exactly two commits: https://github.com/rockdaboot/libpsl/commit/9d39483d4216f7b725dfbb590b5138dd15fc1733 and https://github.com/rockdaboot/libpsl/commit/664f3dc85259ec65e30248a61fa1c45b7b0e4c3f

Between this and https://github.com/transmission/transmission/issues/3010, the thinking here seems to be that we should update whenever upstream has a commit, whether or not those commits affect Transmission...? I don't understand what the goal is for this and 3010.

**Comment by GScottElshaw** [comment]
Can you give a rationale for why not? I'm not trying to be obtuse, but if the project has dependencies, shouldn't they be up to date, especially if updating them doesn't create any issues? At all.

Has Transmission changed since its last official release? Yes. Then why should the project's dependencies be treated differently when the dependency projects also continue with commits without official releases? I am not suggesting every commit to anything third party needs an immediate update to the project's library, but i am suggesting someone needs to regularly keep an eye on things. 

As i said earlier [when i first raised this issue](https://github.com/transmission/transmission/issues/2894), if there is a 6 - 12 year gap in oversight, it stretches credulity that 'everything is fine' _if_ these items are a bedrock dependency of a project.

Oh, just saw that you closed this before i could comment. Awesome.

**Comment by ckerr** [comment]
I came here to give a comment like this:

> Update: I don't think I explained this as nicely or as clearly as I should've. Please see https://github.com/transmission/transmission/issues/2997#issuecomment-1112448139 instead for a better description

But you commented in the interim @GScottElshaw; I think we were cross-writing.
