### ISSUE TITLE
Feature Request: support UserNotifications framework for macOS 10.14

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3030]
I've actually done the implementation already:
https://github.com/Coeur/transmission/tree/coeur/UserNotifications
But that implementation is incomplete in regard for one critical point:
- if building from Xcode, then it will work correctly (once #3050 gets merged as well).
- if building from `make`, then it will break all notifications because of incorrect codesign.

Would someone knows how to fix the codesigning identifier when using CMakeLists.txt?
I tried to add the following but it had no impact whatsoever on the resulting signing:
`set(CPACK_BUNDLE_APPLE_CODESIGN_PARAMETER --identifier=org.m0k.transmission --deep -f)`

**Comment by ckerr** [comment]
@mikedld or @livings124 might be able to give more information on how to do this; I haven't touched the code signing procedures
