### ISSUE TITLE
"too many open files" in April 28 nightlies 

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#3032]
according to lsof, there are far more than `tr_open_files::MaxOpenFiles` files of local data open. Looks like there might be a regression in 5dbe1f46690f5dc90cff5eb2755f59949c3dc399 (April 28)

**Comment by Coeur** [comment]
Oh I see. So my previous issue wasn't bogus after all: #3028

**Comment by ckerr** [comment]
Ah, you opened and closed that before I saw it!

Right, not bogus :laughing:

**Comment by robd003** [comment]
Thanks for fixing this @ckerr
