### ISSUE TITLE
Transmission macOS 3.00+ (d498aa1ae1) forgets groups & group criteria entirely

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#3046]
Transmission 3.00+ (d498aa1ae1) on macOS forgets customized groups & group criteria entirely!

My torrents that had started out in a group with criteria are now ungrouped, regardless of which group they were assigned to later (the blank group).

macOS 10.15.7 (19H1824), 64-bit.

Edit: revised based on the fact that I didn't scroll all the way though the list and just assumed this was a regression. 😖

**Comment by CyberSkull** [comment]
Still experiencing it in Transmission 3.00+ (a57d265968).

**Comment by CyberSkull** [comment]
Looking further tonight I noticed that all my existing torrents are in a "blank" torrent group, while my new ones are in what is labeled "No Group".

**Comment by Coeur** [comment]
- Can you screenshot it?
- Can you offer steps on how to reproduce the issue?

I'm using the default groups and they aren't forgotten when closing and reopening the app.
![Capture d’écran 2022-05-04 à 15 00 34](https://user-images.githubusercontent.com/839992/166636079-f1190ca7-2148-4d89-9edd-333d57281b7c.png)

I'm not seeing an option to create new groups, although I see from the code that custom groups can be loaded, as seen by the recent change I made regarding deprecations in #2973.

**Comment by CyberSkull** [comment]
![Screen Shot 2022-05-04 at 4 09 51 AM](https://user-images.githubusercontent.com/201815/166878695-90c5e244-5f55-4904-9ce5-aa8016da2f71.png)
I didn't scroll to the bottom when I initially looked at the problem, so I missed this detail. 😩

It seems that all the custom groups get forgotten, as my default blue and purple groups are still there.

**Comment by CyberSkull** [comment]
![Screen Shot 2022-05-05 at 12 31 13 AM](https://user-images.githubusercontent.com/201815/166879579-0be90610-8015-4a8a-a7e4-fa3b085136e7.png)
As you can see in 3.00+ (d3e1c83c9b), the group criteria are empty now, this one used to have a tracker assigned to it.

**Comment by Coeur** [comment]
Thanks, I didn't know about the criteria feature. I found the bug and it was introduced by me with #2973. I'll make a PR in a few minutes.

**Comment by Coeur** [comment]
Thanks, I didn't know about the criteria feature. I found the bug and it was introduced by me with #2973. I'll make a PR in a few minutes.

**Comment by Coeur** [comment]
Note: the deletion of groups with custom criterias is happening each time you start Transmission. So if you have custom groups and want to persist them, it's best to not close&reopen Transmission until you've updated it to a build with the fix.
