### ISSUE TITLE
Random question about the ratio icon

### ISSUE THREAD

**Issue by anderspitman** [transmission/transmission#3048]
I noticed a while ago that the ratio icon in transmission-qt:

![DeepinScreenshot_select-area_20220502111511](https://user-images.githubusercontent.com/7820200/166293669-7ef3f23a-f25b-44c0-a762-34cbfcabf56d.png)

Is very similar to the Aes Sedai symbol from the Wheel of Time:

![DeepinScreenshot_select-area_20220502111713](https://user-images.githubusercontent.com/7820200/166293853-40aed6e0-d118-44ad-b350-8bb74334699a.png)

Just curious if that was intentional or just a coincidence?

Obviously they're both very similar to the yin yang symbol so maybe it's just a shared resemblance.

**Comment by ckerr** [comment]
I had yin/yang in mind, not Wheel of Time. But that's a fun thought :smile_cat:

**Comment by anderspitman** [comment]
Thanks!
