### ISSUE TITLE
Build #7908 (earlier?) erases all custom group name labels, colors d3e1c83c9b

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#3054]
Build d3e1c83c9b #7908 and probably recent nightly builds completely wipe out all customized group name labels and their colors, while retaining those user created group contents only now nameless.

Some group lables revert back to fresh installed colors and color names regardless 

This requires renaming all groups and reselecting colors although torrents remain separated into now empty groups.

 DEVELOPERS: I humbly request you to include custom groups, colors, group folder locations in your default testing environment please. Thanks for all of your hard work nonetheless. I appreciate you. 

<img width="478" alt="Screen Shot 2022-05-05 at 1 31 06 AM" src="https://user-images.githubusercontent.com/19694741/166887944-f6d35794-6148-4b77-8269-b6bb45256a7e.png">

**Comment by GaryElshaw** [comment]
See https://github.com/transmission/transmission/pull/3053

**Comment by Coeur** [comment]
Sorry about that.
To keep the discussion in one place, see #3046 where I commented about unit tests as well. For the fix, see #3053.
