### ISSUE TITLE
Group colours

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3058]
Something about the colours within 'Group' on MacOS has always annoyed me, i think it's that they all seem so anaemically washed out and kind of un-mac-like in their shape _and_ colour. I'd like to take a shot at it, even if i can just get something a bit better locally. I've had a look around in the code and can't isolate where the parameters for the Group colours are, can someone direct me? @Coeur @DevilDimon

**Comment by Coeur** [comment]
It uses the most native Apple colours available:
https://github.com/transmission/transmission/blob/d3e1c83c9b348c2ee2538498f9938ded16fea1a5/macosx/GroupsController.mm#L69

**Comment by Coeur** [comment]
The gloss and squareness is done programmatically in this single function:
https://github.com/transmission/transmission/blob/d3e1c83c9b348c2ee2538498f9938ded16fea1a5/macosx/GroupsController.mm#L371

With some NSGradient and NSBezierPath.

**Comment by GaryElshaw** [comment]
Thanks Antoine, time to get educated.

**Comment by GaryElshaw** [comment]
Am i on the right path?

`- (NSImage*)imageForGroup:(NSMutableDictionary*)dict
{
    NSImage* image;
    if ((image = dict[@"Icon"]))
    {
        return image;
    }

    @interface MKCircleRenderer : MKOverlayPathRenderer(0.0, 0.0, ICON_WIDTH, ICON_WIDTH);

    NSBezierPath* bp = [NSBezierPath bezierPathWithCircle xRadius:3.0 yRadius:3.0];
    NSImage* icon = [[NSImage alloc] initWithSize:MKCircleRenderer.size];

    NSColor* color = dict[@"Color"];

    [icon lockFocus];`

**Comment by GaryElshaw** [comment]
Sorry Antoine, i'm not a C or C++ coder. I was trying to transform the Group menu items into circles rather than rectangles and hoping that changing it might also remove that gloss.

One of the recent changes i contributed was the colour changes in the Message Log. Those changes are using the MacOS Tag colours, that, to me, are more in keeping with the function and also a move away from what i think of as the old MacOS 'Aqua' styling that has slowly phased out from Snow Leopard --> the present. In other words, i think the current 'Group' styling in the menu, and in the styling of the Main window, are the last vestiges of the old circa 2003 Aqua.

This is a suggested change in two phases. Phase 1 is that menu. Here's a very quick and dirty representation.

![SCR-20220508-l7u](https://user-images.githubusercontent.com/69029666/167280819-2521f8e9-1e20-4429-9431-439f1c29cd32.png)

And, of course, i'd like to change the colour styling of Groups in the main window with a couple of different possibilities. Are the maintainers strongly holding on to the current styling of Group(s)? @ckerr @livings124 @mikedld

**Comment by Coeur** [comment]
Those RGB values in your document are likely missing some alpha value, because in Finder, the colour is different if it's on white or grey background. I'll try to colour pick myself with the native Colour Picker app, and make a PR.
![Capture d’écran 2022-05-08 à 14 55 37](https://user-images.githubusercontent.com/839992/167285467-f97199ff-4d4b-4ab4-b9a0-78e7404c3d91.png)

**Comment by GaryElshaw** [comment]
Thanks Antoine, that sounds great. I'm about to re-do my PR, i haven't been happy with the feel of the images.

**Comment by Coeur** [comment]
I'm doing the shape and color update in #3065.
Not addressing the "dot on folder" suggested style for now.

**Comment by sweetppro** [comment]
I like the idea of a coloured vertical bar down the left hand side, rather than a dot

**Comment by GaryElshaw** [comment]
> Not addressing the "dot on folder" suggested style for now.

Yep, i think that will have _**considerable**_ debate.

**Comment by GaryElshaw** [comment]
> I like the idea of a coloured vertical bar down the left hand side, rather than a dot in the main window

I quite like that too.

![SCR-20220508-tyn](https://user-images.githubusercontent.com/69029666/167290506-77b89d64-c333-4562-9470-09258072a063.png)

**Comment by GaryElshaw** [comment]
Maintainers? Any comments on the design proposals? Another option in the interim could be to try and replace the, i can only describe them as chalky/washed-out colours, for system colours? @ckerr @livings124 @mikedld 

![SCR-20220514-qvv](https://user-images.githubusercontent.com/69029666/168415574-6177c93d-acdd-40d5-b1ed-5e9751e46cf5.png)

**Comment by Coeur** [comment]
We should make different designs to vote.
Here it is how it looks like if I apply the system colours identically to the icons.
![Capture d’écran 2022-05-14 à 21 37 34](https://user-images.githubusercontent.com/839992/168428216-fddc1de7-d489-4139-8cef-3a1b89c9ac50.png) ![Capture d’écran 2022-05-14 à 21 40 25](https://user-images.githubusercontent.com/839992/168428260-7f414222-9e9f-4cf1-98b9-13f5f4796eac.png)

**Comment by sweetppro** [comment]
I was thinking something like this:
<img width="311" alt="groups" src="https://user-images.githubusercontent.com/7323792/168428689-ef5aa335-594c-4745-b341-ae3d6f93400f.png">

**Comment by Coeur** [comment]
@sweetppro thanks. Please also offer a suggestion for the compact view (cmd+T)

**Comment by GaryElshaw** [comment]
Just creating two snapshots...
![SCR-20220515-2u3](https://user-images.githubusercontent.com/69029666/168429138-0f33328f-4290-4004-b994-9938ea929e3d.png)
![SCR-20220515-2ti](https://user-images.githubusercontent.com/69029666/168429145-c6a8b782-c37d-461a-8d77-619ab4d8f86f.png)

**Comment by Coeur** [comment]
What I can do is making three branches, with the three proposals, and let people vote by testing the three branches for themselves.
a. square background
b. lateral bar
c. dot in a corner

**Comment by Coeur** [comment]
Oh, even more neat: I could simply implement all three suggestions, with a settings to choose from.

**Comment by GaryElshaw** [comment]
> Oh, even more neat: I could simply implement all three suggestions, with a settings to choose from.

Ha! I set up a poll in discussions, that should save some work!

**Comment by sweetppro** [comment]
here's a minimal mockup:
<img width="333" alt="groups minimal" src="https://user-images.githubusercontent.com/7323792/168429724-845ecaa6-55d0-496d-9793-ba93746c5939.png">

**Comment by sweetppro** [comment]
I also like Option 4 in the poll - theres no option to select it

**Comment by GaryElshaw** [comment]
> I also like Option 4 in the poll - theres no option to select it

Oops, sorry about that! Fixed.

**Comment by sweetppro** [comment]
I voted for 4... ha

**Comment by GaryElshaw** [comment]
Wow. Really? The competition must have been dreadful.

**Comment by sweetppro** [comment]
option 4 looks most like how the Finder adds tags on Monterey...
and it does look super clean
