### ISSUE TITLE
Download "big" torrents is reduced download speed and slow down transmission (bottleneck to single core of cpu).

### ISSUE THREAD

**Issue by k0ste** [transmission/transmission#306]
Hello.
Today I used torrent with Ultra HD Bluray disk - 86.95Gb Total, with big file is 76.19Gb. Yes, this is 4K, this is 2017 year.
The CPU is Xeon 1230 (LGA1155) with 4Gb RAM. Looks like transmission-daemon can\try use only one core - 25% of CPU or 100% of 400%.

Some netdata screenshots:

![selection_001](https://cloud.githubusercontent.com/assets/7759548/26762547/6b931ac8-496e-11e7-807a-f57d44efde74.png)
![selection_002](https://cloud.githubusercontent.com/assets/7759548/26762548/6bcf7f4a-496e-11e7-8fee-ebe19b0313c7.png)

I try googleed, increase cache size from 128Mb to 384Mb - more memory usage without any effect. I try to disable encryption and uTP - nothing. I'm not found any bottlenecks in my system (cpu & kernel in `performance` mode, no any C-states), I use Linux 4.11.3 with 3x Toshiba X300 4Tb drives -> md_raid5 -> xfs. No any `wa` or `si`, when I use "usual torrents", no any problem - download/upload speed is 100Mbit/s+.

I make another tests:
* One file in torrent (1.82Gb) - no any bottlenecks, download speed is maximum;
* 23 files * 4.3Gb ~= 102Gb torrent - same bottleneck described above.

Transmission from last jenkins build:
```
transmission-daemon 2.92+ (5f7bc801c8)
```
```
  rm -f m4/glib-gettext.m4
  autoreconf -fi
  ./configure --prefix=/usr
  make
```
```
Configuration:

   Source code location:                              .
   Compiler:                                          g++

   Build libtransmission:                             yes
      * optimized for low-resource systems:           no
      * µTP enabled:                                  yes
      * crypto library:                               openssl

   Build Command-Line client:                         no

   Build GTK+ client:                                 yes
      * libappindicator for an Ubuntu-style tray:     no

   Build Daemon:                                      yes

   Build Mac client:                                  no
```
```json
{                                    
    "alt-speed-down": 50,            
    "alt-speed-enabled": false,                                            
    "alt-speed-time-begin": 540,                                   
    "alt-speed-time-day": 127,                  
    "alt-speed-time-enabled": false, 
    "alt-speed-time-end": 1020,      
    "alt-speed-up": 50,                                                                         
    "bind-address-ipv4": "0.0.0.0",                                        
    "bind-address-ipv6": "::",                                             
    "blocklist-enabled": false,                                            
    "blocklist-url": "http://www.example.com/blocklist",                            
    "cache-size-mb": 128,            
    "dht-enabled": true,                        
    "download-dir": "/srv/raid/nas/Serials",                               
    "download-queue-enabled": true,             
    "download-queue-size": 500,      
    "encryption": 1,                 
    "idle-seeding-limit": 30,                                              
    "idle-seeding-limit-enabled": false,        
    "incomplete-dir": "/var/lib/transmission",          
    "incomplete-dir-enabled": false, 
    "lpd-enabled": true,             
    "message-level": 1,                                                                                         
    "peer-congestion-algorithm": "", 
    "peer-id-ttl-hours": 6,                     
    "peer-limit-global": 50000,                 
    "peer-limit-per-torrent": 100,              
    "peer-port": 50789,                         
    "peer-port-random-high": 65535,                                                                                                    
    "peer-port-random-low": 49152,                      
    "peer-port-random-on-start": false,                 
    "peer-socket-tos": "default",                       
    "pex-enabled": true,                                
    "port-forwarding-enabled": false,                   
    "preallocation": 1,                                 
    "prefetch-enabled": true,                           
    "queue-stalled-enabled": true,                      
    "queue-stalled-minutes": 1,                         
    "ratio-limit": 2,                                   
    "ratio-limit-enabled": false,                       
    "rename-partial-files": false,                      
    "rpc-authentication-required": true,                
    "rpc-bind-address": "0.0.0.0",                      
    "rpc-enabled": true,                                
    "rpc-password": "secret",            
    "rpc-port": 9091,                                              
    "rpc-url": "/transmission/",                                   
    "rpc-username": "hoho",                                       
    "rpc-whitelist": "127.0.0.1",                                  
    "rpc-whitelist-enabled": false,                                
    "scrape-paused-torrents-enabled": true,                        
    "script-torrent-done-enabled": false,                                           
    "script-torrent-done-filename": "",                                             
    "seed-queue-enabled": true,                                                     
    "seed-queue-size": 500,                                                         
    "speed-limit-down": 2500,                                                       
    "speed-limit-down-enabled": false,                                              
    "speed-limit-up": 50,                                                           
    "speed-limit-up-enabled": false,                                                
    "start-added-torrents": true,                                                   
    "trash-original-torrent-files": false,                                          
    "umask": 2,                                                                     
    "upload-slots-per-torrent": 14,                                                 
    "utp-enabled": true,                                                            
    "watch-dir-enabled": false                                                      
}                                        
```

**Comment by k0ste** [comment]
The same picture when "verify torrent", no any download. Me seems some hashing (?) function is not optimized and very slow.

![selection_001](https://user-images.githubusercontent.com/7759548/27718701-c203c82c-5d77-11e7-9a33-ae17f1bf3d6a.png)

**Comment by k0ste** [comment]
Trick with reduce download speed is not work with 826Gb (416 files) torrent. Usage of transmission is impossible.
@mikedld, any suggestions?

**Comment by mikedld** [comment]
I'm not sure what the issue is here. It is a slow speed? Is it a high CPU usage? What are the numbers exactly, i.e. what do you consider "normal" values in your environment and what do you actually observe? How many peers are active at the time?

Since you're building from sources, are you sure that you're building an optimized binary? Like, do you see `-O2` or similar flags in compiler command line when running `make V=1` or `make VERBOSE=1` or whatever? I'm asking since configure.ac adds `-O0` to compiler flags if the version being built is not a release ("supported") version, and "2.92+" is not a release version. To get around this, either edit configure.ac (adjust or remove lines ~20-30) or use cmake which allows to specify build type regardless of Transmission version status.

Last but not least, graphs are nice but what about using perf or similar tool to see what is really going on?

**Comment by k0ste** [comment]
> I'm not sure what the issue is here. It is a slow speed? Is it a high CPU usage? What are the numbers exactly, i.e. what do you consider "normal" values in your environment and what do you actually observe? How many peers are active at the time?

This is a limit to one CPU core -> slow work, slow speed.

> Since you're building from sources, are you sure that you're building an optimized binary? Like, do you see -O2 or similar flags in compiler command line when running make V=1 or make VERBOSE=1 or whatever? I'm asking since configure.ac adds -O0 to compiler flags if the version being built is not a release ("supported") version, and "2.92+" is not a release version. To get around this, either edit configure.ac (adjust or remove lines ~20-30) or use cmake which allows to specify build type regardless of Transmission version status.

```diff
diff -Naupr transmission-2.92_orig/configure.ac transmission-2.92/configure.ac
--- transmission-2.92_orig/configure.ac 2017-05-25 03:06:11.373828532 +0700
+++ transmission-2.92/configure.ac      2017-07-20 09:58:17.940976729 +0700
@@ -26,8 +26,8 @@ if test m4_substr(peer_id_prefix,6,1) =
 else
   supported_build=no
   if test "x$GCC" = "xyes" ; then
-    CFLAGS="$CFLAGS -g -O0"
-    CXXFLAGS="$CXXFLAGS -g -O0"
+    CFLAGS="$CFLAGS -g -O2"
+    CXXFLAGS="$CXXFLAGS -g -O2"
   fi
 fi
 AM_CONDITIONAL(TR_UNSTABLE, test "x$supported_build" = "xno")
```

I was apply this patch due you recommendations. I Started watching for changes.

> Last but not least, graphs are nice but what about using perf or similar tool to see what is really going on?

Yep, I was looked to perf. I'm not have many experience with profiling user land applications. If you present "good" command line keys, I try to some `perf record` for you.

**Comment by k0ste** [comment]
Much better. Transmission CPU usage was reduced by ~70%. Transmission came to life, there was a possibility of connecting client, even with simultaneous downloads of 10 Blu-ray discs without any lags/timeouts. 
Thanks.

Just for the record: I started experimenting with the master branch, after the same problems on the release 2.92 (with `-O2` of course).

**Comment by mikedld** [comment]
If the 2.92 binaries were provided by the package in your distro, you may want to report this to the package maintainer. The configure.ac file in release source tarball (transmission-2.92.tar.xz) contains `m4_define([peer_id_prefix],[-TR2920-])` which means that `-O0` is not enforced.

**Comment by k0ste** [comment]
I check distro package, build with `-O2`.
