### ISSUE TITLE
Suggestion on the order to merge the opened Pull Requests

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3060]
Pull requests are starting to pile up a bit. I'm pinging who could merge those?
@ckerr @mikedld @livings124 

Some of them are modifying adjacent or identical lines which will require to resolve merge conflicts (frequent case is when it adds files to the pbxproj), but I'll be quick to solve the conflicts if they are my pull requests. So here is a suggested priority list to merge at the moment:

### blockers

1. https://github.com/transmission/transmission/pull/3050 allow running Transmission when built from Xcode, which is a prerequisite to more debugging/testing contributions on macOS; this will help more devs contributing

### fixes

2. https://github.com/transmission/transmission/pull/3020 third party update, but with complex change to the pbxproj, so it's best to merge early, otherwise merge conflicts will become difficult.

Those don't include Qt or GTK or web changes, as I'm more familiar with macOS-related changes.

Thanks a lot!

[edit: removed the merged ones]

**Comment by GaryElshaw** [comment]
Mitch or Mike, are you able to help Antoine out here? Charles has been notably absent the last few days, is he okay? @livings124 @mikedld

**Comment by Coeur** [comment]
We did get a merge from @ckerr today (#3057), so I'm not worried.
Just Charles might not be fully familiar with macOS, so we can't ask him to review so many macOS changes: multiple of them might need trustable code reviewing from someone else.

**Comment by ckerr** [comment]
> Just Charles might not be fully knowledgable on everything related to macOS, so we can't ask him to review so many macOS changes: multiple of them might need trustable code reviewing from someone else.

This is pretty much right. I'm happy to help with some of the procedural PRs e.g. the .clang-format PR, but have been leaning on other reviewers e.g. @DevilDimon for macOS client code review

**Comment by ckerr** [comment]
Closing this issue since there's only one remaining PR from this list, so the sequencing no longer matters :smile_cat:
