### ISSUE TITLE
Syntax problem on inspector 

### ISSUE THREAD

**Issue by Srevens** [transmission/transmission#3069]
Hello,
I juste came here to report this syntax problem on macOS (I use the French language, I don't know if it happens in other languages)

<img width="498" alt="Capture d’écran 2022-05-09 à 12 50 33" src="https://user-images.githubusercontent.com/105209930/167397082-c52fb66d-8477-4f74-9482-a5edd06c6a48.png">

It only seems to happen with private torrent
Btw thanks to the developers for their work

**Comment by Coeur** [comment]
Merci Srevens.
C'est un bug n'affectant que FR. Désormais corrigé dans Transifex.
La mise à jour dans Transmission se fera par Mike, Charles ou AO. Voir #3073 pour le suivi éventuel.

**Comment by Coeur** [comment]
Fixed with #3318.
