### ISSUE TITLE
Technical Transifex fixes to apply

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3073]
Transifex only allows "suggestions" that are seemingly hard to find.

Here are my bug fixes in need of a reviewer:

https://www.transifex.com/transmissionbt/transmissionbt/translate/#ru/mac-ql/106502643?q=text%3A'%25%40+web+seeds'
=> Need to apply my suggestion for a crash fix

https://www.transifex.com/transmissionbt/transmissionbt/translate/#fr/mac/106502501?q=text%3A'Private+Torrent%2C+non-tracker+peer+discovery+disabled'
=> Need to apply my suggestion for UI fix #3069

Also, I was not able to find the .po strings in Transifex, so I'm not able to port the reversal or this commit to Transifex:
https://github.com/transmission/transmission/commit/9667fc5da53aa74fead291dab68ddd0d1a931767
It would be nice if a Transifex coordinator could fix the twenty languages where OS X needs to be updated to macOS.

Thanks

**Comment by mikedld** [comment]
That's weird, since you're part of a team there you should be able to make corrections (unless the string is in a "reviewed" state I think). Is this happening for all the languages, or only for some of them?

As for .po files, they are in GTK Client group.

**Comment by Coeur** [comment]
For all languages, the submit button is greyed out:
![Capture d’écran 2022-05-10 à 13 16 28](https://user-images.githubusercontent.com/839992/167547476-a3077e43-1189-4a12-936d-56ca68cfd3e8.png)

There are:
- Coordinators who can do most things
- Reviewers who can submit corrections 
- Translators (like me presently) who can only submit "suggestions"

Seems to me that you're the only one, Mike, who can do any change:
![Capture d’écran 2022-05-10 à 13 22 43](https://user-images.githubusercontent.com/839992/167548214-a1bec671-dbc6-4da3-a67f-aab12190cc61.png)

**Comment by Coeur** [comment]
As for the .po strings, even looking at GTK client group, I can't find:
"Transmission is a BitTorrent client with an easy-to-use frontend on top a cross-platform backend. Native frontends are available for OS X and Windows, as well as command line and web frontends."
So I don't know how to apply https://github.com/transmission/transmission/commit/9667fc5da53aa74fead291dab68ddd0d1a931767 in Transifex.

**Comment by mikedld** [comment]
I've made you a reviewer for all the languages, hopefully this will give you more power. But please refrain from actually marking phrases as reviewed (unless they're in your native language I guess) leaving this to actual reviewers for those languages.

`#~` lines in .po files are comments that denote previously active but now unused translations, a kind of limited translation memory: if a phrase is going away but then coming back (in this or slightly different form) — you already have a (some sort of) translation for it. Those comments are used by some translation tools, but given that we're using Transifex which has its own translation memory, I think we ought to just remove them... That is to say, don't worry about fixing those lines.

**Comment by mikedld** [comment]
I still need to sync @ckerr's fmtlib-related changes (now that we're not making too many fixes there), so will have to combine it all somehow...

**Comment by ckerr** [comment]
> I still need to sync @ckerr's fmtlib-related changes (now that we're not making too many fixes there), so will have to combine it all somehow...

Agreed, I think that's mostly done. I have a WIP branch that may  change a couple of libtransmission strings but we shouldn't block the other 99% of the translation update just for a few strings.
