### ISSUE TITLE
High passive memory usage (leak?)

### ISSUE THREAD

**Issue by hasezoey** [transmission/transmission#3077]
since upgrading to ubuntu 22.04 with transmission-daemon 3.0 i have noticed that the memory usage has increased by much, with just ~6 torrents running (each ~2GB on average), it feels like it keeps all the torrents directly in memory in the process itself instead of using streaming or linux's build-in caching:

```txt
$ ps -aux | grep transmission
debian-+    1711  0.8 39.7 10632612 6461816 ?    Ssl  Apr30 133:43 /usr/bin/transmission-daemon -f --log-error
```

![htop_sylvi](https://user-images.githubusercontent.com/10911626/167877936-eee0cff3-b569-447d-b88c-121e971b72b5.png)

```txt
$ apt list --installed "transmission*"
Listing... Done
transmission-cli/jammy,now 3.00-2ubuntu2 amd64 [installed]
transmission-common/jammy,now 3.00-2ubuntu2 all [installed,automatic]
transmission-daemon/jammy,now 3.00-2ubuntu2 amd64 [installed]
```

Also, when i add another torrent (that is about ~2GB), it over the time of the torrent downloading increases by about another GB of memory usage

created a new issue as suggested by https://github.com/transmission/transmission/issues/313#issuecomment-1124817285

**Comment by ckerr** [comment]
Does this problem persist in the nightly builds? 3.00 is over 900 commits ago.

**Comment by ckerr** [comment]
Duplicate of #3055

**Comment by hasezoey** [comment]
> Does this problem persist in the nightly builds?

currently untested, because i run transmission currently only from the ubuntu repos

> 3.00 is over 900 commits ago.

if the leak was know and the version is this old already (guessing from the git tag ~2 years by now), why was there no new version (even if minor) since then and also why did ubuntu then decide to ship this version anyway?

**Comment by wedsa5** [comment]
I also had this issue running the 3.0.0 release after upgrading to 22.04.
Have 4000+ torrents and was not an issue before 22.04.
Upgraded to the latest nightly build (7c014e3256) and confirmed this is no longer an issue.
Memory usage staying in the single digits.

**Comment by Lesiuk** [comment]
I upgraded to current master, and It leaks even more ( c13500240a1b43b84e763a6fde9b16cbe3dc9d02 ). This issue is totally not fixed.
<img width="874" alt="image" src="https://github.com/transmission/transmission/assets/543264/a1e16eaf-07b0-414a-83b1-e13022ee2802">

**Comment by MaartenDeen** [comment]
> I also had this issue running the 3.0.0 release after upgrading to 22.04. Have 4000+ torrents and was not an issue before 22.04. Upgraded to the latest nightly build ([7c014e3](https://github.com/transmission/transmission/commit/7c014e3256499b61e7684f671d99f39155c880a5)) and confirmed this is no longer an issue. Memory usage staying in the single digits.

The issue persists for me. I have switched to 4.0.4 a few days ago and the memory usage grows by 4 GB/day. I am compiling build 11752 now to see what that does.
Ubuntu 22.04.3 and I have about 200 torrents running.

**Comment by guillaumealgis** [comment]
transmission-daemon 3.00 (bb6b5a062e) here, maxing out 8GB of memory after a few days on Ubuntu 22.04.3 LTS.

**Comment by jivanpal** [comment]
@guillaumealgis This is a known issue with 3.00, but I don't think 3.x is receiving any more patches; you'll see that this issue is closed. Version 4.0 was released on 8 Feb 2023, which incorporated a lot of memory leak fixes. There are still known memory issues as of 4.0.4, and I believe the most current GitHub issue tracking this is #6019. See also [this remark](https://github.com/transmission/transmission/issues/5735#issuecomment-1625802255) from the maintainer on 7 July 2023 on issue #5735:

> I'd also be interested in 4.0.3 heaptracks if you feel there's a "huge memory leak" there since we will have at lease one more 4.0.x release.
> 
> I'm less interested in 3.00 bug reports since that is literally 2,000 commits ago. I don't forsee another 3.0x release unless there is some critical security vulnerability or some issue of that magnitude.
