### ISSUE TITLE
macOS unfinished folder never cleared

### ISSUE THREAD

**Issue by sweetppro** [transmission/transmission#3085]
running v3.0+, folders and files in `~/Application Support/Transmission/unfinished/` are never removed. Manually deleting a torrent, or having it automatically removed from transfer list does not delete any associated files.

macOS Monterey 12.3.1

**Comment by Coeur** [comment]
Similar symptoms as with #2379, but not an issue that I'm reproducing: I do see the .part files going into the Trash.

**Comment by sergserg2** [comment]
Have the same on linux arm64, compiled few days ago. Filesystem is on XFS. Empty dirs remains in InProgress after files are moved to Finished dir (main + dirs from torrent structure).

**Comment by ckerr** [comment]
Fixed by #3151.
