### ISSUE TITLE
way to increase the max nofile without recompiling

### ISSUE THREAD

**Issue by sandrotosi** [transmission/transmission#309]
Hello,
if i read

```
$ git grep FD_SETSIZE
CMakeLists.txt:        set(CMAKE_${L}_FLAGS "${CMAKE_${L}_FLAGS} -DFD_SETSIZE=1024")
gtk/tr-prefs.c:  w = new_spin_button (TR_KEY_peer_limit_per_torrent, core, 1, FD_SETSIZE, 5);
gtk/tr-prefs.c:  w = new_spin_button (TR_KEY_peer_limit_global, core, 1, FD_SETSIZE, 5);
libtransmission/fdlimit.c:      /* set the open-file limit to the largest safe size wrt FD_SETSIZE */
libtransmission/fdlimit.c:          const int new_limit = MIN (limit.rlim_max, FD_SETSIZE);
qt/PrefsDialog.cc: #include <winsock2.h> // FD_SETSIZE
qt/PrefsDialog.cc: #include <sys/select.h> // FD_SETSIZE
qt/PrefsDialog.cc:  ui.torrentPeerLimitSpin->setRange (1, FD_SETSIZE);
qt/PrefsDialog.cc:  ui.globalPeerLimitSpin->setRange (1, FD_SETSIZE);
third-party/miniupnp/receivedata.c:    n = select(FD_SETSIZE, &socketSet, NULL, NULL, &timeval);
```

you force the max number of file descriptors to 1024.

now, let's say i have a systems where i could run transmission with more than _just_ 1024 fds, wouldnt it be fantastic if i could specify it either as a configuration option (or using ulimit in the init script)?

is there any reason to hardcode this value at compile time and not make it dynamically changable by the users (unless you want to prevent to have them shot themselves in the foot, but that could happen anyway)

thanks for considering

**Comment by cfpp2p** [comment]
[TRAC-5161](https://trac.transmissionbt.com/ticket/5161#comment:5)
[TRAC-5056](https://trac.transmissionbt.com/ticket/5056#comment:2)
[TRAC-4164](https://trac.transmissionbt.com/ticket/4164)

**Comment by mikedld** [comment]
It would be fantastic for users not to care about this kind of stuff ;) Bumping libcurl requirement might be a nice idea, judging from [TRAC-5898](https://trac.transmissionbt.com/ticket/5898) which I recall taking a shot at some time ago.

**Comment by sio** [comment]
Hello, are there any plans on lifting the 1024 file descriptors limit? It was pretty low even 8 years ago when it [was introduced](https://trac.transmissionbt.com/ticket/4164).

[Dropping support](https://trac.transmissionbt.com/ticket/5898) for libcurl < 7.15.4 does not seem unreasonable, it's more than 12 years old.

Transmission is absolutely amazing torrent client, it's a shame that is does not scale, and for such a small reason...

**Comment by psycholyzern** [comment]
I have "Too many open files" error randomly for months. I read every possible tutorial on how to increase maximum open file for systemd but I keep getting "1024" as the limit. Today I found out that Transmission harcoded the limit. Looks like Transmission daemon is not suitable for hard usage for people like me.
Hopefully we can set higher limit in the future.

**Comment by ckerr** [comment]
@mikedld do we still need to refer to `FD_SETSIZE` directly in our code / CMakeLists? After #893 it looks like we aren't using select() for anything.

**Comment by radonm** [comment]
Hello is that going to be fixed any time soon ?
