### ISSUE TITLE
transmission-qt: very high memory usage

### ISSUE THREAD

**Issue by haasn** [transmission/transmission#311]
Currently sitting at 7493 MB on my machine. Running `transmission-qt 2.92+ (5f7bc801c8)`

Any other information I could provide?

**Comment by mikedld** [comment]
What operating system are you using Qt client on? Where did you get this number from? How many torrents do you have loaded? How many of them are currently active? What size (on disk) are they? How long does it take for Transmission to start using that much memory?

**Comment by haasn** [comment]
1. `Linux xor 4.11.6-gentoo-suse #1 SMP PREEMPT Wed Jun 21 12:39:49 CEST 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel Linux`
2. `htop`'s `RES` column
3. 46 as of right now
4. 1 as of right now
5. 298.8 GB total as of right now
6. Sorry for not clarifying, transmission-qt starts instantly and uses almost no memory after doing so (61 MB). The memory usage just keeps climbing and climbing as I keep the program open.

**Comment by ckerr** [comment]
3.00 had a lot of work for reducing the memory overhead specifically in transmisison-qt. Is this still an issue?

**Comment by haasn** [comment]
I have not been able to reproduce the issue as I no longer keep transmission-qt open for long durations. I won't be of much use debugging this. Feel free to close it.
