### ISSUE TITLE
utp_on_error messages in Debug log

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3110]
Hi Charles, still getting thousands of these in the Debug message log @ckerr.

![SCR-20220519-kkn](https://user-images.githubusercontent.com/69029666/169193821-6eb0d3b9-f701-4193-8135-39c62b770e79.png)

**Comment by ckerr** [comment]
This is coming entirely from libutp; nothing that can be fixed in libtransmission per se other than updating our libutp snapshot.

Closing as a duplicate of https://github.com/transmission/transmission/issues/2996.

**Comment by GaryElshaw** [comment]
Afraid i've got as far as i could with that :-(
