### ISSUE TITLE
InfoOptionsViewController.mm + Icon?

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3112]
The last couple of days i've been trying to change the global settings icon in the footer of the application to something that better reflects the fact that it's a drop-down menu than a preference pane.

After a lot of mucking around, i considered this isn't a separate image file, but something coded? Is it the InfoOptionsViewController.mm file?

In Xcode, the icon looks like this.
![SCR-20220518-r8k](https://user-images.githubusercontent.com/69029666/169225776-6e5136dd-d673-4cbf-932d-90a38cefa7f4.png)

Which to me is more OS contemporary and reflects what this menu item actually does than what is currently there.

![SCR-20220519-peq](https://user-images.githubusercontent.com/69029666/169225931-42d341d7-a81c-4f4a-85f1-ad2172c7202c.png)

Is it possible to have that Xcode default icon enabled?

**Comment by Coeur** [comment]
imagewithsystemsymbolname  is documented as macOS 11.0+:
https://developer.apple.com/documentation/appkit/nsimage/3622472-imagewithsystemsymbolname/

Now, that doesn't mean necessarily that all symbols are available in 11.0. And since we use "gearshape.fill" and "tortoise.fill" for instance, maybe we need to set our minimum to 12.0:
https://developer.apple.com/documentation/swiftui/symbolvariants/fill-swift.property/

I don't have a computer on 11.x to verify at the moment.
Are you on 11.x ?

**Comment by GaryElshaw** [comment]
12.4

**Comment by sweetppro** [comment]
The tortoise icon. Is definitely in macOS 11, I haven’t checked the gear. Buy it likely is.

download SFSymbols to check icon availability

**Comment by sweetppro** [comment]
In fact you could just get rid of the conditional and export the icons from SFSymbols to have consistency across all macOS versions.

i could do this this afyernoon

**Comment by Coeur** [comment]
Note that I wasn't questioning tortoise or gearshape, just the ".fill" part, since in Swift code it's marked for macOS 12+ only:
https://developer.apple.com/documentation/swiftui/symbolvariants/fill-swift.property/

**Comment by GaryElshaw** [comment]
Ellipsis circle in SF Symbols is what i was after. What do others think?

![ellipsis-circle](https://user-images.githubusercontent.com/69029666/169305708-9d55c590-d6e4-49ed-94e6-7d3b83025053.png)


The other images have their png sources or counterparts in /macosx/Images...

**Comment by sweetppro** [comment]
> I love how simple you make that sound. Can we have auto layout this evening? 'World peace in a day? I know someone...'

:) still working on world peace
