### ISSUE TITLE
Zero information in Warn or Info message logs

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3115]
Definitely a change from a recent build, currently using 3.00+ (2e25370cc5)

**Comment by ckerr** [comment]
I haven't changed anything in the logging mechanism lately. @GaryElshaw could you try walking backwards through the recent nightlies and find the last good version and first broken version?

**Comment by GaryElshaw** [comment]
And now it's back ¯\_(ツ)_/¯ . However #3135 :-(

**Comment by GaryElshaw** [comment]
There is a bug, but not in the way i thought. It actually has something to do with how information is retained or discarded in the log file(s) over time.

3.00+ (d6a5f1462c) has been running for around 12 - 16 hours. There is nothing in Warn or Error, and a very recent action from the last 30 minutes in Info.

The Debug log runs in the _**thousands**_ of entries for around the previous three hours, with info such as:

2022-05-26 03:12:27 +0000 peer-io.cc:309 [Debug] [149.57.29.151]:7155: event_read_cb err: res:-1, what:33, errno:54 (Connection reset by peer)

2022-05-26 00:36:40 +0000 announcer-udp.cc:540 [Debug] tracker.openbittorrent.com:6969: Got a new connection ID from tracker: 14859673547237716880

2022-05-26 01:41:58 +0000 tr-dht.cc:613 [Debug] XXXXXXXXXXXXXXXXXXXX Learned 1 IPv4 peers from DHT

**Comment by ckerr** [comment]
To preserve memory, it doesn't queue up log information until you turn on logging and doesn't preserve it between sessions.

As soon as you open the log window and set the logging verbosity, messages should start showing up.

Is this consistent with what you're seeing?

**Comment by GaryElshaw** [comment]
Yes, that is all consistent; it's just that some of the low information records aren't retained during a session. #3139

**Comment by GaryElshaw** [comment]
Okay
