### ISSUE TITLE
'File name too long' with magnet links

### ISSUE THREAD

**Issue by sergserg2** [transmission/transmission#3117]
Every time I add a magnet link an error occurs and the torrent pauses. This happens as soon as a magnet is found. When the torrent is resumed, it downloads normally.

` ERR utils.cc:218 Couldn't read 'magnet:?(here is full magnet link over 255 characters long): File name too long (36) (/home/software/transmission/transmission/libtransmission/utils.cc:218)`

**Comment by ValZapod** [comment]
There are two types of magnet links. One that has small letter and one that has big letter. The first is the usual one found everywhere and the second is jwo it is formated in tixati...

**Comment by sergserg2** [comment]
I guess I was wrong. I think the error has nothing to do with the download pause. I checked on shortest magnet link and in this case the (non-existent) file cannot be read.

`[2022-05-22 00:26:34.833] ERR utils.cc:218 Couldn't read 'magnet:?xt=urn:btih:8ad2239505b8dc16ca9b4018ae8bc59e676443b7&dn=': No such file or directory (2) (/home/software/transmission/transmission/libtransmission/utils.cc:218)`

But after torrent metadata is downloaded, this torrent is also paused, verified and left stopped.

**Comment by ckerr** [comment]
> ERR utils.cc:218 Couldn't read 'magnet:?(here is full magnet link over 255 characters long): File name too long (36) (/home/software/transmission/transmission/libtransmission/utils.cc:218)

Looks like somehow a magnet URL is being passed into `tr_loadFile()` which expects a local filename. @sergserg2 can  you walk me through the exact steps needed to make this happen? I tried adding a magnet link but that worked correctly, so I assume I'm not following the same steps you did & would like a step-by-step :smile_cat:

**Comment by sergserg2** [comment]
I'm using Transmission Remote GUI and click on a magnet link on the rarbg (links are > 255 characters long) and it happens. For example magnet link on this page https://rarbgmirror.org/torrent/lpke62m

```
[2022-05-23 23:17:42.639] ERR utils.cc:218 Couldn't read 'magnet:?xt=urn:btih:d544ada31d05af20aebfe7bd9e4bae5
d1360ef41&dn=A.Fistful.of.Dollars.1964.2160p.BluRay.REMUX.HEVC.SDR.DTS-HD.MA.5.1-FGT&tr=http%3A%2F%2Ftracker.
trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2960&tr=udp%3A%2F%2F9.rarbg.to%3A2720&tr=udp%3A%2F
%2Ftracker.thinelephant.org%3A12750&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14800': File name too long (36)
(/home/software/transmission/transmission/libtransmission/utils.cc:218)
```
There is no debug lines above about magnet processing, only error line.

Then despite this error torrent file from magnet link is downloaded (only torrent file, not movie), verified (60GB of empty file in 0 sec) and leave stoped (paused).

```
[2022-05-23 23:17:50.689] inf A.Fistful.of.Dollars.1964.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT Pausing tor
rent (/home/software/transmission/transmission/libtransmission/torrent.cc:1554)
[2022-05-23 23:17:50.689] dbg A.Fistful.of.Dollars.1964.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT verifying t
orrent... (/home/software/transmission/transmission/libtransmission/verify.cc:48)
[2022-05-23 23:17:51.691] dbg A.Fistful.of.Dollars.1964.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT Verificatio
n is done. It took 0 seconds to verify 65313144215 bytes (65313144215 bytes per second) (/home/software/trans
mission/transmission/libtransmission/verify.cc:145)
```

**Comment by Xist12gh** [comment]
Reverting the change to torrent-magnet.cc of 9c0038ac8e9298b536fa8519117ebf6c0cbd289f fixes the pause after verify. For some reason startAfterVerify is not set to true on the magnet even when "start when added" IS checked. Didn't debug why.

The filename too long part is caused by the change to rpcimpl.cc in 1688 of 96178b1a9fb986b63a956af880a057b0c6aab724
The magnet is now being tried after file failed, previously magnet urls were identified by the magnet string prefix.

Might this behaviour only be triggered when using the rpc api?

Hope that helps, drove me nuts so I attached gdb and registered to comment my findings.
