### ISSUE TITLE
Transmission icon on GitHub is out of date

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3119]
I just noticed this need for a minor cleanup on aisle three?
![SCR-20220522-mjy](https://user-images.githubusercontent.com/69029666/169678334-d4936bfd-ef1f-4bfe-ba55-1efd00f7772e.png)

**Comment by ckerr** [comment]
What's wrong with this icon?

**Comment by GaryElshaw** [comment]
> What's wrong with this icon?

It's the old one.

**Comment by mangosplat** [comment]
> It's the old one.

Are we sure that the Big Sur icon is the new face of transmission? I think the gear shift remains Transmission's branding in general as it's multiplatform. The big sur icon is just for mac and isn't used on any other OS currently

**Comment by ckerr** [comment]
...though, even though there's not One True Icon, I do think the Big Sur version and GNOME version have more in common than either has with the older 45 degree view one. It might be better to update.

**Comment by GaryElshaw** [comment]
[Advising on branding and brand identity is part of my day job]

You're right about the gear shift being the brand. I'm unsure why the Rodger Werner icon wasn't used across all platforms, to me it looks more at home on GNOME than the current icon.

![GNOME-3 32-6](https://user-images.githubusercontent.com/69029666/169940425-56fce7d0-c718-48a6-9149-d1b622ea9d23.png)

**Comment by ckerr** [comment]
github page updated; so I'm going to close this issue.

> You're right about the gear shift being the brand. I'm unsure why the Rodger Werner icon wasn't used across all platforms, to me it looks more at home on GNOME than the current icon.

It's been awhile but IIRC the Transmission icon on GNOME was made by the GNOME designers because for a very long time Transmission shipped by default on several distros. If you want to change that icon, it's probably done on the distro level rather than a change in the `transmission/transmission` repo...? TBH I'm not sure what the first step would be.

**Comment by GaryElshaw** [comment]
I'll take a look, do some work, and leave it up to you and the other maintainers.
