### ISSUE TITLE
transmission-qt 3.00 download percentage bar glitch

### ISSUE THREAD

**Issue by tenplus1** [transmission/transmission#3150]
In transmission-qt 3.00 (bb6b5a062e) supplied with lubuntu 22.10 alpha, the download percentage bar is vertical instead of horizontal and shows a round blob instead of the proper bar.

**Comment by ckerr** [comment]
bb6b5a0 is about 1,060 commits old at this point. @tenplus1 could you try out a nightly build from https://transmissionbt.com/ and see if the problem persists there?

**Comment by tenplus1** [comment]
Unfortunately I'm not able to try the nightly build, so I will wait for transmission-qt to be updated in the 22.10 ubuntu repo's and see if anything changes.

**Comment by ile6695** [comment]
> problem appears when updating the breeze package 5.24.5 -> 5.25 on arch

Someone on IRC had similar issues with the 3.00 release. Ubuntu 22.10 provides breeze 5.25
It's still unknown if the problem persist on latest transmission.

**Comment by ckerr** [comment]
Could someone attach a screenshot of this? I'm not able to reproduce this issue

**Comment by ile6695** [comment]
![image](https://user-images.githubusercontent.com/35461663/175082261-62c80668-bcdf-4430-b0ee-16b62f5cdf5f.png)
This is from lubuntu 22.10 installer in a vm. Tiny grey dot in the middle should be a wide progress bar.

**Comment by tfardet** [comment]
@mikedld is there a plan for a new (at least bugfix) release so that this patch can be made available to users?

**Comment by ile6695** [comment]
@tfardet No, builds that contain this patch are already available as nightlies and next release is supposed to be in 2022.
With 4.0.0, releases should become more regular.
