### ISSUE TITLE
3.00 RPC no longer interprets [] as "all torrents" for torrent-set.

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#3157]
In Shift I have implemented a mass-add-trackers-to-all-torrents function that stopped working because an empty array [] is no longer interpreted as "all torrents" as an argument for torrent-set. Transmission returns a success message but nothing happens. See https://github.com/killemov/Shift/issues/23

**Comment by ckerr** [comment]
I don't believe that this is a bug? I checked the RPC spec back as far as 2.81 and it looks like it's always said that _omtting_ the `ids` argument is treated as "all torrents". It doesn't say that providing an empty array will do that. So I think 2.81 all through main are following the spec.

Am I misunderstanding the bug report?
