### ISSUE TITLE
TeamCity update

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3176]
@mikedld A heads-up there's a new version available.

**Comment by mikedld** [comment]
Thanks but there's no need in raising issues for this. I'm subscrubed to their RSS, and TeamCity itself shows a notification in the header when you login with administrative rights. And again, as with other issues you report, please provide reasoning for why you think it's an issue in the first place.

**Comment by GaryElshaw** [comment]
You actually took the time to add this? Wow. I just thought i might be being helpful. Cool. Thanks for the ad hominem.

![SCR-20220602-qvg](https://user-images.githubusercontent.com/69029666/171575769-1d517ccc-599e-459c-9833-0eae7fe1c17d.png)

**Comment by mikedld** [comment]
It's invalid because it's not an issue with Transmission.

**Comment by GaryElshaw** [comment]
Good to know. Charles, from now on you can just merge and bypass the the TC process altogether @ckerr.

**Comment by ckerr** [comment]
> Good to know. Charles, from now on you can just merge and bypass the TC process altogether @ckerr.

I've given Gary a three-day block for the hostile attitude in https://github.com/transmission/transmission/issues/3176#issuecomment-1144534554 and https://github.com/transmission/transmission/issues/3176#issuecomment-1144613462. Gary, I value your presence and contributions I'm not going to let hostile behavior slide.
