### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tmpfile** [transmission/transmission#318]
Transmission 2.92 was release more than a year ago.
There's been 242 commits since. Lots of improvements and fixes.
It would be great if you could tag a new release.
Thank you.

**Comment by seitzbg** [comment]
Yeah it'd be great to have a new release!

**Comment by Fredrik81** [comment]
Why was this closed? No good comment either..

Latest version 2.92: mikedld released this on Apr 9, 2016

**Comment by buhtz** [comment]
@Fredrik81 I think you missunderstood. This (#318) wasn't closed. It was the referenced Issue (#340) because it was out-dated (still fixed in the git-repo, but not in the release).

**Comment by gerardp** [comment]
Any news on that?

**Comment by DevilDimon** [comment]
I think the only serious thing that needs to be resolved before the next release is #140. Autolayout alone might be worth a release, and there have been so many other improvements as well.

**Comment by rzcat** [comment]
I only use transmission-daemon, therefore the UI doesnt really matter. However there are many torrents with long names that cannot be added to transmission. It seems that this issue has already been fixed in https://github.com/transmission/transmission/commit/bb4741002f832a8f1046196830917462d7063862
I'm looking forward to have the daemon part updated to newer release while others can still play 2.92 with UI

**Comment by enihcam** [comment]
yes, please separate daemon and clients. I only use transmission-daemon too.

**Comment by fcore117** [comment]
i am glad at least that there is a daily builds, yes separation would be good as i only use pure QT client without anything else.

**Comment by rafuse** [comment]
So... has the Autolayout adoption been completed yet?
Can we except an update before the end of the year?

**Comment by gerardp** [comment]
Any news?

**Comment by lnicola** [comment]
A new release would be welcome in the light of the recent CVE.

**Comment by buhtz** [comment]
Can you please first give a concrete number and/or link to the CVE and explain how this would affect the security (or other aspects) while using transmission.

**Comment by lnicola** [comment]
https://github.com/transmission/transmission/pull/468

**Comment by fcore117** [comment]
Ubuntu 18.04 LTS feature freeze comes then 2.92 will stay there.

**Comment by lnicola** [comment]
That security patch can be included by the Ubuntu or Debian maintainers if they choose to.

**Comment by Fredrik81** [comment]
Can we get a 2.93 release?
The latest release is from 2016.
Feels strange there are nothing new.
If your unsure please make a vote here on git.. I'm sure there will be an
overwhelming vote for new version.

sön 21 jan. 2018 kl. 12:55 skrev Laurențiu Nicola <notifications@github.com

**Comment by enihcam** [comment]
i think daemon/cli/gui versions need to be seperated first.

**Comment by gdubicki** [comment]
2.93 was released on 25 Jan, so this can be closed, I believe.

**Comment by slokhorst** [comment]
I think this is more about a feature release (i.e. 3.0). 2.93 just contains a few bugfixes.

**Comment by Enuqt** [comment]
Something happening here? hehe graving for that dark mode

**Comment by Riotous** [comment]
@kevin-hv I think Transmission is having a bit of a lull in development since 2.94 but it's been picking up the last few weeks. I hope everybody from the old Transmission Qt project comes back to build up the Windows port.

**Comment by ellipticaldoor** [comment]
Why it takes so much time to release? Im just curious

**Comment by Riotous** [comment]
@ellipticaldoor Because we don't have enough contributors and the maintainer isn't working on the project as much these days.

**Comment by kevin-hv** [comment]
@Riotous, the latest release is 11 months old, many features have been added, maybe not as much as needed for the 3.0, but something between the current and that would be appreciated

**Comment by Riotous** [comment]
@kevin-hv I agree. There should have been a 2.95 and 2.96 with a focus on getting the Windows port fully stabilized. I hope the devs are planning to make 3.0 a solid release and release 3.01 quickly if there are any major bugs that we can't wait another year to get fixed.

**Comment by Enuqt** [comment]
Looks like we are ready?

**Comment by kevin-hv** [comment]
Sooo, no 3.0 release? Some communication from the devs would be nice.

**Comment by fcore117** [comment]
Even windows nightly builds are failing.

**Comment by someperson** [comment]
I really would like to have #320 on my server, but the change doesn't apply cleanly onto 2.94's web UI, so I'm not sure what to do without a release :(

**Comment by dausruddin** [comment]
I ended up forking and pulling any PR that I think interesting enough and had it built on my server.
Working great, except Web-UI. Even with just forking and not merging any PR, Web-UI broke.
I ended up using 2.94's Web-UI and it has been working really great for now.

**Comment by joechilds90** [comment]
Any news on this?

**Comment by okias** [comment]
Hello, it's been about 2 years since last release.

Since this is the last bug blocking 3.0 release, I'm writing here!
I'm really impressed by all the work your done on the project and by numbers of resolved PRs and bugs.

I'm sure you have a reason to not release it yet, but please consider at least alpha/beta release!

Thank you for your work!

**Comment by XVilka** [comment]
The global pandemic is a perfect opportunity to do so, yes.

**Comment by ttys3** [comment]
Yeah it'd be great to have a new release!

**Comment by okias** [comment]
Release early, release often. Please, do @mikedld

P.S. compiled latest git and it's in pretty great shape.

**Comment by elvey** [comment]
Useful ideas in https://github.com/transmission/transmission/issues/701#issuecomment-611220850 ?

**Comment by PeterDaveHello** [comment]
Looks like v3.0.0 is coming? :tada: 
https://github.com/transmission/transmission/releases/tag/3.00
![image](https://user-images.githubusercontent.com/3691490/79689289-53b7bb80-8286-11ea-9ab2-c66c2fa9bd88.png)

**Comment by Tharn** [comment]
Since this is the last milestone 3.0 issue, should it be closed now?

**Comment by slokhorst** [comment]
@Tharn it hasn't been officially released yet. See https://github.com/transmission/transmission/issues/1223#issuecomment-629385375:

> BLUF: 3.00 is coming soon but it's not finalized and people shouldn't be rolling out downstream packages until the website has formal downoads.

**Comment by ckerr** [comment]
:tada:
