### ISSUE TITLE
consider updating miniupnpc

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3181]
@ckerr Did you know releases of miniupnpc are only acknowledged in the subdirectory of miniupnp/miniupnpc? 

The last version was 20 February of this year.

https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/Changelog.txt

**Comment by GaryElshaw** [comment]
Just a headsup that the latest in repo is finally working properly with cmake again. Just built the latest and installed with no fuss:

mkdir build
cd build
cmake ..

I'll try and figure out a pr....

**Comment by ckerr** [comment]
> Edit: Oh, also, it looks like libevent 2.2 is just around the corner.

Where did you see that? :eyes:

**Comment by GaryElshaw** [comment]
https://github.com/libevent/libevent

**Comment by GaryElshaw** [comment]
Last release of miniupnpc was in November 2022, Transmission version is 2013.
