### ISSUE TITLE
Regression: Missing settings icon on macOS status bar

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3199]
Might have been caused by #3113 (@sweetppro), but I lost some icons in the status bar.
![Capture d’écran 2022-06-05 à 07 35 27](https://user-images.githubusercontent.com/839992/172028881-1bd56e99-51dd-4aff-a644-07b906b95ca0.png)

Notes:
- French interface
- I built for this screenshot with cmake, not Xcode

**Comment by Oleg-Chashko** [comment]
v.3.00+d31254df50
- French interface

<img width="719" alt="Screen Shot 2022-06-05 at 01 49 16" src="https://user-images.githubusercontent.com/62497891/172029307-7cc31b0e-4760-4ecf-8e97-9eea454b2bf5.png">

**Comment by sweetppro** [comment]
I’ll take a look later today
