### ISSUE TITLE
[I18N] Unescaped percent signs

### ISSUE THREAD

**Issue by meskobalazs** [transmission/transmission#3203]
I have an issue with the following strings:
https://github.com/transmission/transmission/blob/9eeb3db89c2a09581298ea481fdaf3e5c92e34ec/gtk/DetailsDialog.cc#L936
https://github.com/transmission/transmission/blob/9eeb3db89c2a09581298ea481fdaf3e5c92e34ec/gtk/DetailsDialog.cc#L944

The `%` signs are not escaped, and this makes translation difficult (read: impossible in Hungarian), as gettext thinks that the following character is a format specifier. The original does not show an error, because o and a are valid format specifiers, but that's just luck.

I think that `%` should always be escaped in C and C++ source files.

**Comment by meskobalazs** [comment]
Also affected:
https://github.com/transmission/transmission/blob/9eeb3db89c2a09581298ea481fdaf3e5c92e34ec/gtk/TorrentCellRenderer.cc#L169
https://github.com/transmission/transmission/blob/9eeb3db89c2a09581298ea481fdaf3e5c92e34ec/gtk/TorrentCellRenderer.cc#L222-L223

**Comment by mikedld** [comment]
IIUC, gettext itself doesn't care for the format specifiers, its purpose is to return you one string based on another string and current locale. Subsequent message formatting is done using fmtlib, not any type of printf-like functions, so escaping `%` doesn't apply. What do you mean whey you say that you "have an issue" with it?

**Comment by meskobalazs** [comment]
I understand that you are not using printf and escaping should not apply, but gettext does not know that, as these are tagged with `#, c-format` in the PO.

I'll give you an example, let's see the first string:
```
{current_size} ({percent_done}% of {percent_available}% available)
```
This would be the following in Hungarian:
```
{current_size} ({percent_done}% / {percent_available}% elérhető)
```
This yields the following gettext error:
> 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 1, the character '/' is not a valid conversion specifier.

If I try to escape it manually in the translation string by using `%%`, then I get this error:
> number of format specifications in 'msgid' and 'msgstr' does not match

**Comment by meskobalazs** [comment]
Oh, this might be an XY problem on my part! Let's see what the gettext docs have to say:

https://www.gnu.org/software/gettext/manual/html_node/c_002dformat-Flag.html

> **xgettext of course could make a wrong decision the other way round, i.e. a string marked as a format string actually is not a format string.** In this case the msgfmt might give too many warnings and would prevent translating the .po file. The method **to prevent this wrong decision is similar to the one used above, only the comment to use must contain the string `xgettext:no-c-format`**.
