### ISSUE TITLE
What's the real type of `rpc-version-semver`?

### ISSUE THREAD

**Issue by Trim21** [transmission/transmission#3204]
According to the doc

Key | Value Type | Description
-- | -- | --
rpc-version-semver | number| the current RPC API version in a semver-compatible string

it says `number` and `string`, what's  the real type?

**Comment by Trim21** [comment]
And a extra question: 


is `rpc-version-semver` missing in this section?

> Request arguments: one or more of 4.1's arguments, except: `blocklist-size`, `config-dir`, `rpc-version`, `rpc-version-minimum`, `version`, and `session-id`

https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#411-mutators

**Comment by killemov** [comment]
> it says `number` and `string`, what's the real type?

It can only be `String`. It think `Semantic` would be a good new native JavaScript type.

**Comment by ckerr** [comment]
> it says number and string, what's the real type?

It's a string. The current value in `main` is `5.3.0`. I'll fix the docs.

> is rpc-version-semver missing in this section?

Yes.
