### ISSUE TITLE
Crash: Transmission-163f6c2544

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3206]
Launching the application is not possible, it crashes immediately.
macOS: Transmission-v.3.00+163f6c2544, Build #7989 (Jun 5, 2022, 1:50:36 PM)
Changes: more FullScreen fixes, and some toolbar animation fixes (#3195)
Log: [Archive.zip](https://github.com/transmission/transmission/files/8840096/Archive.zip)

**Comment by sweetppro** [comment]
yup,
my fault - https://github.com/transmission/transmission/pull/3195 fixed in https://github.com/transmission/transmission/pull/3208
