### ISSUE TITLE
"Couldn't add duplicate torrent" when adding a .torrent file to an existing magnet torrent (or vice versa)

### ISSUE THREAD

**Issue by muelli** [transmission/transmission#321]
I added a magnet URI to my transmission-gtk instance.  It couldn't find the .torrent file in the DHT so I got hold of the torrent file and tried to add it then.  The interface, however, complains about the duplicate torrent.

Similarly, I had a .torrent file without trackers added and then tried to add a magnet URI with tracker URLs. Transmission complained about the duplicate torrent.

I expected transmission to not complain but to complement the state of the to be downloaded content. In the first case I expected transmission to know what data it should download. In the second case I expected transmission to complement its state regarding tracker and webseed URLs.

**Comment by mikedld** [comment]
See #65.
