### ISSUE TITLE
macOS - incorrect behavior at Full Screen

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3215]
https://user-images.githubusercontent.com/62497891/172070023-f042b920-c881-4814-bbf4-db35de52f15d.mp4

**Comment by sweetppro** [comment]
@Oleg-Chashko uggh, fullscreen support really is troublesome. there are so many different scenarios which need to be accounted for. ill take another look tomorrow

**Comment by Oleg-Chashko** [comment]
@sweetppro 
Thanks, for some reason I think that full screen mode is not really needed by this application?

**Comment by sweetppro** [comment]
@Oleg-Chashko yeah it is a weird way to use Transmission, but im sure some probably find it useful...

**Comment by ckerr** [comment]
I hate to make macOS UI suggestions based on other platforms, but FWIW neither the GTK nor Qt apps have full-screen.

I'd be OK with removing it **unless** it's idiomatic for macOS apps to have a full-screen mode

**Comment by GaryElshaw** [comment]
It is 'normal' to have that function.

**Comment by Oleg-Chashko** [comment]
Not all macOS applications use full screen mode. 
The developer uses this mode at his own discretion in his application.
It seems to me that almost no one uses this mode in this application. 
Since this mode was broken a long time ago and maybe never worked correctly. 
And there is no one in the larger community who created this issue before me. 
And I wouldn't have created it this issue because I don't use full screen mode in this app. 

Example:

![Screen](https://user-images.githubusercontent.com/62497891/172118957-19da0869-8862-4a64-94bd-65681a840a48.gif)

**Comment by sweetppro** [comment]
@Oleg-Chashko are you running the latest version? I’ve already done this

**Comment by sweetppro** [comment]
The issue I’m facing right now is showing and hiding the filter/status bar if the toolbar is shown (in full screen mode) - but only if either/both is not showing when full screen is enabled…

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko are you running the latest version? I’ve already done this

v.3.00+8d61f07930

**Comment by sweetppro** [comment]
Which version of macOS?

**Comment by Oleg-Chashko** [comment]
> Which version of macOS?

macOS Monterey v.12.4 (21F79)

**Comment by sweetppro** [comment]
Hmm,
That’s what I’m running.
And the issue you describe is not happening for me. The issue I have is the issue I described above

**Comment by sweetppro** [comment]
See here https://github.com/transmission/transmission/pull/3191/files

**Comment by Oleg-Chashko** [comment]
Fullscreen mode **always worked fine.**
Only it always conflicted with the "Auto Resize" feature that was on.

**Comment by sweetppro** [comment]
> Fullscreen mode **always worked fine.**
> Only it always conflicted with the "Auto Resize" feature that was on.

That’s what I don’t understand, I disabled auto resize in https://github.com/transmission/transmission/pull/3191

**Comment by Oleg-Chashko** [comment]
https://user-images.githubusercontent.com/62497891/172131137-178b67fb-0ab2-4fc0-8b6d-842f5ba5a3be.mp4

**Comment by Oleg-Chashko** [comment]
> > Fullscreen mode **always worked fine.**
> > Only it always conflicted with the "Auto Resize" feature that was on.
> 
> That’s what I don’t understand, I disabled auto resize while in full screen in #3195

Unfortunately, "auto resize" is not disabled in full screen mode.

https://user-images.githubusercontent.com/62497891/172132791-3ff7feb1-2066-4d4c-8bec-8b940e6ea7b3.mp4

**Comment by Coding4Coffee** [comment]
+1 for getting rid of full screen support. I would not say that a torrent client is a primary use day to day, and most users will be multi tasking in the background. The extra screen real estate full screen provides, does not add any real benefit to the user experience imo, apart from a bunch of white space. 

The auto resize function is more than enough for my use case

**Comment by Oleg-Chashko** [comment]
The full screen mode does not work properly.

<img width="1440" alt="Screen Shot 2022-06-13 at 08 14 36" src="https://user-images.githubusercontent.com/62497891/173291467-2e8c5a3a-baba-46de-a761-cfaa62ec17de.png">

**Comment by GaryElshaw** [comment]
See #3278

**Comment by Oleg-Chashko** [comment]
v.3.00+c6b49e99d8 - Fixed.
