### ISSUE TITLE
reduce wasted space in macOS client's Torrent Inspector UI

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3223]
If anyone is planning to do this, please take into account the different lengths in the spelling of words in the different localizations of the application.

Example: Torrent Inspector -> Activity

- Before - Activity
<img width="624" alt="Before - Activity" src="https://user-images.githubusercontent.com/62497891/172204318-1ff68024-b3bf-496f-94bc-ef491f9c9807.png">

- After - Activity
<img width="715" alt="After - Activity" src="https://user-images.githubusercontent.com/62497891/172204389-d2007dd5-8475-41ea-aa17-e5275eed5fe5.png">

---

Example: Torrent Inspector -> Option

- Before - Option
<img width="879" alt="Before - Option" src="https://user-images.githubusercontent.com/62497891/172204625-c66ed3be-0de6-4a06-931f-66d4716911f4.png">

- After - Option
<img width="694" alt="After - Option" src="https://user-images.githubusercontent.com/62497891/172204703-1026f6d6-ca71-4f92-9d0f-97b61f00bdab.png">

**Comment by Coding4Coffee** [comment]
I think this is a good suggestion

**Comment by Oleg-Chashko** [comment]
> I think this is a good suggestion

I would like an adaptive design: when you expand the window, it would change to the one I gave in the example. I ask, this is a change due to the use of IPv6. Since IPv6 addresses are very long and you have to stretch the window horizontally in the Peers tab.

**Comment by Oleg-Chashko** [comment]
If for some reason this change is not possible. 
Please make each tab remember the horizontal size. At the moment, the tabs remember only the vertical size.

**Comment by Oleg-Chashko** [comment]
Added, v.3.00+ffe307ac1b
