### ISSUE TITLE
RPC 4.0: Please do NOT deprecate trackerAdd, trackerRemove and trackerReplace

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#3226]
The methods trackerAdd, trackerRemove and trackerReplace are all good ways for manipulating trackers in batches of torrents. And trackerList manipulation is usually only good for doing that for a single torrent.

In Shift there is a function to add trackers to all torrents. IF I would want to keep that functionality alive after trackerAdd is removed then I'd have to:
- iterate over possibly 10k+ torrents. And for each:
- get the tracker-list
- add the desired trackers
- set the tracker-list

**Comment by killemov** [comment]
I'm revisiting tracker management (`trackerAdd`, `trackerRemove` and `trackerReplace`) in [Shift](https://github.com/killemov/Shift). And looking back, boy do these have bad/useless implementations. In almost all cases all the torrents need to be queried and updated individually anyway. Adding insult to injury, the only response for anything going wrong is just a simple "invalid argument".

- `trackerAdd`. The most straightforward method. Just add a bunch of tracker urls. But that fails when adding even a single duplicate. It should add them and not create duplicates.
- `trackerRemove`. You want `http://dead.tracker.info:80/announce` removed from all torrents? Look up that tracker in each torrent and remove it with the associated tracker id.  It should accept the urls as input and do the look-ups server-side.
- `trackerReplace`. Similar to `trackerRemove`. Use the associated tracker id to update an existing tracker url with a new tracker url. It should accept pairs of urls and update accordingly. [  `http://dead.tracker.info:80/announce`,  `http://alive.tracker.info:80/announce`  ]

My bad for having a knee-jerk reaction to having these methods deprecated instead of realizing/remembering how useless these methods are for global tracker management in the first place. Having said that, I strive to support older versions of transmission AND some batching can be done with `trackerAdd` that cannot be done with trackerList. The other methods require ids that may be unique across torrents, the same tracker url in two torrents is likely to have different ids in each of them. Combining multiple `torrent-set` arguments in a single request would have helped a bit. ( Remove tracker 1 from torrent 3, tracker 2 from torrent 4 and tracker 3 from 5.) I know ... but that is useless from a manipulating a single torrent point of view.

**Comment by ckerr** [comment]
> Oh, and a lot of direct information got lost when rpc-spec.txt was transformed to rpc-spec.md.

Like what?

**Comment by ckerr** [comment]
> My bad for having a knee-jerk reaction to having these methods deprecated instead of realizing/remembering how useless these methods are for global tracker management in the first place.

:neutral_face: 

> Oh, and a lot of direct information got lost when rpc-spec.txt was transformed to rpc-spec.md.

You can't just throw that out and not say what got lost.

Please LMK what got lost so that it can be fixed.

**Comment by killemov** [comment]
No comment on my comment of how things should have worked in the first place? (Maybe still add the string variants to the current implementation?)

From [rpc-spec.txt](https://github.com/transmission/transmission/blob/63fafada16be7f09a890dacc66c48cafc43058fd/extras/rpc-spec.txtl):
![old](https://user-images.githubusercontent.com/932370/216027189-50a28a76-3182-4424-b128-c13db02e6db0.png)

From [rpc-spec.md](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md):
![new](https://user-images.githubusercontent.com/932370/216027195-59d247ee-0429-4048-be3e-19259354d32d.png)

And these are just snippets, just open the two documents side-by-side and see how much has been removed. Documenting the RPC properly does mean not having to glean the code.

**Comment by ckerr** [comment]
> No comment on my comment of how things should have worked in the first place?

For what purpose? They're deprecated.

> Oh, and a lot of direct information got lost when rpc-spec.txt was transformed to rpc-spec.md.
>
> From rpc-spec.txt ... from rpc-spec.md

I'm confused.  Your evidence about info being lost when transforming rpc-spec.txt to rpc-spec.md appears to be changes that were made after you made your claim -- changes that were made _in response_ to your comments, even.

> And these are just snippets, just open the two documents side-by-side and see how much has been removed.

You're the one making the assertion that "and a lot of direct information got lost when rpc-spec.txt was transformed to rpc-spec.md", seems incumbent on you to provide the information?

**Comment by ckerr** [comment]
> No comment on my comment of how things should have worked in the first place?

If you want to have that discussion, please open a new [a discussion thread](https://github.com/transmission/transmission/discussions) for better visibility. Let's not do it in the comments of an issue that was closed seven months ago. I do think there's a productive conversation to be had. In particular I think it would be more straightforward to use announce URLs as keys and remove tracker IDs altogether.

Also, when I read comments like "boy do these have bad/useless implementations" and "how useless these methods are for global tracker management in the first place"... no, of course I don't want to engage with that. Do you talk to your co-workers about their work in that tone too?

> Oh, and a lot of direct information got lost when rpc-spec.txt was transformed to rpc-spec.md.
>
> From rpc-spec.txt ... From rpc-spec.md:

This change came *after* you reported information loss, so it can't be what you were referring to.

> And these are just snippets, just open the two documents side-by-side and see how much has been removed.

Dude, you can't just say "there's a bug in the doc, and I know what it is, but I won't tell you; I want you to go look for it." You realize how that sounds, right?

**Comment by ckerr** [comment]
@killemov can you lmk what direct information  you were referring to, so that it can get fixed?

**Comment by killemov** [comment]
Damn, I can't reproduce it but I was looking at a page where all the array-definitions from torrent-get were missing. (That's why I thought it would be so obvious.)

As for deprecating fields like in the attached screenshots we should keep the definitions/explanations and additionally mark them as deprecated.

Also many fields could use definitions/explanations right there and not refer to code. (Which is more subject to change?)
