### ISSUE TITLE
deprecation warnings in macOS codebase

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3228]
More of a note-to-self, there are *a lot* of warnings here, and i see Apple has started alerting users of deprecations in MacOS 11 *and* 12.

[Controller.mm-warnings.txt](https://github.com/transmission/transmission/files/8857252/Controller.mm-warnings.txt)

**Comment by ckerr** [comment]
I'd welcome deprecation cleanup PRs from you and also from anyone else who wants to do the work :green_heart:

Just clarifying this in case so that the "note-to-self" comment doesn't scare off anyone else who also wants to work on deprecation warnings. There seem to be enough of them for everyone to have a go :slightly_frowning_face:

**Comment by Coeur** [comment]
Settings Milestone to 5.0 since, as seen by my PR, we need some `if (@available(macOS 10.14, *))` for UNNotificationCenter, which makes nevack unhappy about the amount of code, which would be smaller in Transmission 5.0 were we're going to drop macOS 10.13 support.

**Comment by Coeur** [comment]
I would also point out at #3030 tracking the issue already.

**Comment by Coeur** [comment]
Done:
- `NSUserNotification` is deprecated (#3040)
- `NSUnarchiver` is deprecated (#4113)
- `NSURLConnection` is deprecated (#4112)
- `NSFilenamesPboardType` is deprecated (#4221)
- `modalDelegate:` is deprecated (#3950)
- `beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:` is deprecated (#3031)
- `SecKeychain` is deprecated (#4190)

In review:
- `NSURLDownload` is deprecated (#4308)

Not done yet:
- `[NSKeyedArchiver archivedDataWithRootObject:indexSet]` is deprecated (can be replaced with `+archivedDataWithRootObject:requiringSecureCoding:error:`)
- `item.minSize` and `item.maxSize` are deprecated (not urgent, this was only deprecated in macOS 12)

**Comment by Coeur** [comment]
I'll now close this issue, for reasons similar to #4152:
- this is not a user-facing issue (those are just deprecation warnings, only visible to those building from source)
- it's a melting pot of various issues that require multiple distinct pull requests to be addressed (one per warning type)
- (specifically, the attached text file is for Controller.mm but not other files?)
- it's a constantly evolving issue in general: each new Xcode release can add new deprecation warnings (and there are releases roughly every two months: https://xcodereleases.com).
- the list of all remaining warnings is visible in Xcode itself: roughly 34 warnings left for the Transmission target; just pick the warning that you want to fix and attempt to fix it. :)

**Comment by GaryElshaw** [comment]
Building from source, i've loved seeing the warnings reduce. Thanks for your work on this Antoine.
