### ISSUE TITLE
Improve fullscreen support in macOS client

### ISSUE THREAD

**Issue by sweetppro** [transmission/transmission#3231]
Fullscreen support is currently broken
there are a few issues with the current implementation, mostly noted here:
https://github.com/transmission/transmission/pull/3220

**Comment by Oleg-Chashko** [comment]
The full screen mode does not work properly.

<img width="1440" alt="Screen Shot 2022-06-13 at 08 14 36" src="https://user-images.githubusercontent.com/62497891/173291539-cf94f51a-6b3d-4f7a-945f-b58b03ee7f61.png">
