### ISSUE TITLE
macOS - incorrect behavior of the "Quick Look" icon

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3235]
The icon continues to glow blue after closing the Quick Look window. To make the icon go out, you need to click on the application window. I have not noticed this before, maybe it appeared not long ago.

Example:

https://user-images.githubusercontent.com/62497891/172715973-e6b06cc6-5ba0-470f-a19b-e0e11c21af56.mp4

P.S.: Sorry for changing the title of the issue, I'm tired, I'm going to bed.

**Comment by nevack** [comment]
There's even more to do.
I think we need to disable this button when no rows selected.
@ckerr Can you assign to me?
I would like to fix it, as I have already some thoughts about it.

**Comment by Oleg-Chashko** [comment]
> I think we need to disable this button when no rows selected.

I agree with you, that this is the right decision. 👍🏻

**Comment by ckerr** [comment]
@nevack I've assigned you and also invited you as a collaborator
