### ISSUE TITLE
[transmission-daemon] Listen to loopback interface by default

### ISSUE THREAD

**Issue by alive4ever** [transmission/transmission#324]
Currently, `transmission-daemon` will listen to all ipv4 addresses (0.0.0.0). This is not a good security practice, since anyone on the same network will be able to control the daemon.

I suggest changing the default listen address to only loopback interface (127.0.0.1) for best security practice.

**Comment by mikedld** [comment]
Whitelist is enabled by default and contains two addresses: 127.0.0.1 and ::1.
