### ISSUE TITLE
transmission consistently stops responding and no 'make uninstall'

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3242]
On Slackware64 15.1-current GNU/Linux when I start transmission and try to open a new torrent or restart a paused one, transmission stops responding. First it allows me to set location, but as soon as I press a button (open or restart) it stops responding but seems to be neither verifying nor uploading nor downloading.  10 minutes to an hour or two later it still hasn't finished the button press but usually I may not have tested longer than an hour (rather than killing process)... status while it happens is often about at most 10% 5950X CPU resources are used and 32GB or more of 64GB RAM left.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I have 3,106 torrents and have this problem with transmission 3 (stable) and the last few git commits (including d4bc566.)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Since there's no 'make uninstall,' next time I install a stable version after OS (re)install I'll avoid testing git commits anymore...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In recent months I can only run transmission from command-line after first doing 'sudo -i ulimit -n 8192' (maximum) and afterwards setting to normal (which, since some torrents have hundreds files, I suspect now might be part of the non-responsiveness problem by being too low, but probably isn't a problem on *BSD/etc UNIX as can be set higher... perhaps transmission shouldn't open so many files so fast rather than gradually, and not open ones unless they're going to have actual activity?)

**Comment by ckerr** [comment]
@dchmelik if you're building from source, could you try running Transmission in a debugger to see where it's getting stuck?

```sh
$ gdb ./build/path/to/transmission
(gdb) handle SIGPIPE nostop noprint pass
(gdb) run
// wait for transmission to stick...
// ctrl-c
(gdb) thread apply all bt
```

**Comment by dchmelik** [comment]
I stated it happens from transmission 3 (stable, which I didn't compile, but now maybe can't completely revert to) and transmission I compiled from source code (source means the project/people or site one gets that code from.)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I followed your instructions now and am waiting, but how do I know it's not just processing 3,106 torrents with well over 8,192 (maximum ulimit) files and won't take user input until afterwards?  Gdb said many things but I don't know any so far necessarily look critical... how long do you want me to wait?

**Comment by ckerr** [comment]
>  Gdb said many things but I don't know any so far necessarily look critical... how long do you want me to wait?

When you do

```sh
(gdb) run
```

Transmission should start up as normal. So run as normal until it stops responding as you described in the original bug report, then press ctrl-c to get a command prompt back in the debugger. You would use that command prompt to get a backtrace with the `(gdb) thread apply all bt` command and paste that output back into this ticket.

I'm not sure I know what you mean by "how long do you want me to wait" -- however long it's taking Transmission to stop responding as you described? I think we may be talking past each other?

Also FWIW the total number of files in all the torrents isn't subject to a ulimit, since Transmission won't be opening all those files simultaneously, so I don't think that's the issue :smiley_cat:

**Comment by dchmelik** [comment]
Here's a [gist](https://gist.github.com/dchmelik/f3524e5dec00a58093a678d74f5b6eb0).  The thing is transmission doesn't crash so I don't know I should wait longer.  One thing I noticed, despite having already installed the latest commit, it's mentioning paths from the source code directory instead of where those were probably installed.    Another thing is seems some DNS is hard-coded in, most have been down, then it doesn't use /etc/resolv.conf (which I have my ISP and every free DNS I know of as of a few years ago, like an entire page list.) After installing from commits then trying to revert (remove & reinstall) to the available stable package, stable transmission 3 seems to behave more like development/testing/unstable commits (no longer waiting almost half an hour before I can do anything, rather than immediately letting me add torrents and in recent commits, not responding... before a few days ago, but also when I had fewer files, stable & unstable versions would immediately add then start working as normal.)

**Comment by ckerr** [comment]
```
Thread 47 (Thread 0x7fff357fa640 (LWP 7581) "transmission-qt"):
#0  0x00007ffff610aaab in __lll_lock_wait () from /lib64/libc.so.6
#1  0x00007ffff61113ed in pthread_mutex_lock@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x00000000005151e4 in __gthread_mutex_lock (__mutex=0x743760 <tr_session::session_mutex_>) at /usr/include/c++/11.3.0/x86_64-slackware-linux/bits/gthr-default.h:749
#3  __gthread_recursive_mutex_lock (__mutex=0x743760 <tr_session::session_mutex_>) at /usr/include/c++/11.3.0/x86_64-slackware-linux/bits/gthr-default.h:811
#4  std::recursive_mutex::lock (this=0x743760 <tr_session::session_mutex_>) at /usr/include/c++/11.3.0/mutex:108
#5  std::unique_lock<std::recursive_mutex>::lock (this=0x7fff357f8260) at /usr/include/c++/11.3.0/bits/unique_lock.h:139
#6  std::unique_lock<std::recursive_mutex>::unique_lock (__m=..., this=0x7fff357f8260) at /usr/include/c++/11.3.0/bits/unique_lock.h:69
#7  tr_session::unique_lock (this=<optimized out>) at /home/d/math/src/network/transmission/libtransmission/session.h:124
#8  tr_session::WebMediator::clamp (this=0xac3588, torrent_id=2099, byte_count=11424) at /home/d/math/src/network/transmission/libtransmission/session.cc:163
#9  0x0000000000574610 in tr_web::Impl::onDataReceived (data=0x7fff183c5260, size=<optimized out>, nmemb=<optimized out>, vtask=0x7fff240499c0) at /home/d/math/src/network/transmission/libtransmission/web.cc:287
#10 0x00007ffff764decd in ?? () from /usr/lib64/libcurl.so.4
#11 0x00007ffff761f876 in curl_easy_pause () from /usr/lib64/libcurl.so.4
#12 0x0000000000573a3b in tr_web::Impl::resumePausedTasks (this=0x7fff24010310) at /home/d/math/src/network/transmission/libtransmission/web.cc:418
#13 tr_web::Impl::resumePausedTasks (this=0x7fff24010310) at /home/d/math/src/network/transmission/libtransmission/web.cc:402
#14 tr_web::Impl::curlThreadFunc (impl=0x7fff24010310) at /home/d/math/src/network/transmission/libtransmission/web.cc:469
#15 0x00007ffff64573a4 in ?? () from /usr/lib64/libstdc++.so.6
#16 0x00007ffff610e053 in start_thread () from /lib64/libc.so.6
#17 0x00007ffff619abf0 in clone () from /lib64/libc.so.6

Thread 45 (Thread 0x7fff35ffb640 (LWP 7579) "transmission-qt"):
#0  0x00007ffff610aaab in __lll_lock_wait () from /lib64/libc.so.6
#1  0x00007ffff6111392 in pthread_mutex_lock@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x0000000000572ace in __gthread_mutex_lock (__mutex=0x7fff240103a0) at /usr/include/c++/11.3.0/x86_64-slackware-linux/bits/gthr-default.h:749
#3  std::mutex::lock (this=0x7fff240103a0) at /usr/include/c++/11.3.0/bits/std_mutex.h:100
#4  std::unique_lock<std::mutex>::lock (this=0x7fff35ff1820) at /usr/include/c++/11.3.0/bits/unique_lock.h:139
--Type <RET> for more, q to quit, c to continue without paging--
#5  std::unique_lock<std::mutex>::unique_lock (__m=..., this=0x7fff35ff1820) at /usr/include/c++/11.3.0/bits/unique_lock.h:69
#6  tr_web::Impl::fetch (options=..., this=0x7fff24010310) at /home/d/math/src/network/transmission/libtransmission/web.cc:169
#7  tr_web::fetch (this=<optimized out>, options=...) at /home/d/math/src/network/transmission/libtransmission/web.cc:593
#8  0x000000000060cbfb in tr_tracker_http_scrape (session=session@entry=0xac3420, request=request@entry=0x7fff35ff30f0, response_func=response_func@entry=0x587060 <on_scrape_done(tr_scrape_response const*, void*)>, response_func_user_data=response_func_user_data@entry=0xac3420) at /usr/include/c++/11.3.0/bits/unique_ptr.h:173
#9  0x0000000000584bd3 in scrape_request_delegate (announcer=0x7fff2400d0b0, announcer=0x7fff2400d0b0, callback=0x587060 <on_scrape_done(tr_scrape_response const*, void*)>, callback_data=0xac3420, request=0x7fff35ff30f0) at /home/d/math/src/network/transmission/libtransmission/announcer.cc:1433
#10 multiscrape (announcer=0x7fff2400d0b0, tiers=...) at /home/d/math/src/network/transmission/libtransmission/announcer.cc:1500
#11 0x0000000000584e95 in scrapeAndAnnounceMore (announcer=0x7fff2400d0b0) at /home/d/math/src/network/transmission/libtransmission/announcer.cc:1580
#12 0x0000000000585408 in onUpkeepTimer (vannouncer=0x7fff2400d0b0) at /home/d/math/src/network/transmission/libtransmission/announcer.cc:1616
#13 0x00007ffff75cacc8 in ?? () from /usr/lib64/libevent-2.1.so.7
#14 0x00007ffff75cb437 in event_base_loop () from /usr/lib64/libevent-2.1.so.7
#15 0x000000000055422d in libeventThreadFunc (events=0xe1ac00) at /home/d/math/src/network/transmission/libtransmission/trevent.cc:199
#16 0x00007ffff64573a4 in ?? () from /usr/lib64/libstdc++.so.6
#17 0x00007ffff610e053 in start_thread () from /lib64/libc.so.6
#18 0x00007ffff619abf0 in clone () from /lib64/libc.so.6
```

This looks slightly concerning. Might actually be nothing but from first glance this could be a thread deadlock which would be consistent with the freezing you're describing.

@dchmelik I'll take a look into this and report back.
