### ISSUE TITLE
Bug: Recoding needed for folder centre in TorrentCell.mm

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3246]
This is potentially a double-up of an already logged issue i can't find. The current coding centres the ActionHover icon on individual files, but not on a directory/folder. Could some of the Mac coders please take a look? @Coeur @DevilDimon @nevack 

![SCR-20220610-4t4](https://user-images.githubusercontent.com/69029666/172885373-5920089f-9f30-423b-a5a9-edf6d7b84797.png)
![SCR-20220610-4n5](https://user-images.githubusercontent.com/69029666/172885390-d7acbd21-e049-453f-bca9-034d03a7478f.png)
![SCR-20220610-4my](https://user-images.githubusercontent.com/69029666/172885402-0c49c04c-befe-42e9-b728-c0698ea18515.png)
![SCR-20220610-4mr](https://user-images.githubusercontent.com/69029666/172885493-cdf1cbc7-3f95-4b2a-ad92-b6fe901e3913.png)

**Comment by Coeur** [comment]
You mean vertically? It's just the shape of the folder icon that puts its icon center at a different high than the folder cover center.
Nothing we can do.

**Comment by GaryElshaw** [comment]
> You mean vertically? It's just the shape of the folder icon that puts its icon center at a different height than the folder cover center. Nothing we can do.

The icon positioning on the folder can't be brought down on the vertical axis? Crap. Could the folder size be increased?
