### ISSUE TITLE
repetitive DNS logging of nameservers failed / back up

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#3275]
I see this in transmission-daemon's log when I leave it running over time:

```
[msg] All nameservers have failed
[msg] Nameserver 127.0.0.53:53 is back up
[msg] Nameserver 127.0.0.53:53 has failed: request timed out.
[msg] All nameservers have failed
[msg] Nameserver 127.0.0.53:53 is back up
[msg] Nameserver 127.0.0.53:53 has failed: request timed out.
```

I think (but haven't confirmed) this is coming from the libevent DNS lookup for UDP trackers.

It would be better to figure out what's causing this and solve it; otherwise, to try and disable this logging since it's not helpful.

**Comment by ckerr** [comment]
Looks like the logging cycle occurs once per hour. Likely there's a 1hr lifespan somewhere in the evdns code

**Comment by robd003** [comment]
Could it be this? https://github.com/transmission/transmission/blob/0fbfed60b10aa5f1cb454c0a3b3f04ae8531e192/libtransmission/announcer-udp.cc#L474

**Comment by ckerr** [comment]
This is fixed now as a side-effect of the announcer-udp refactor that no longer uses evdns
