### ISSUE TITLE
Visual issues: re-add macOS Fullscreen support #3261

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3277]
Some weird UI behaviours in 3.00+ (dd85cd20bd):

* Truncated main menu (13 of 20 torrents visible with the inability to scroll up).
* No ratio/up/down menu item
* Unchecking Auto Resize and restarting seems to help
* Visually able to see an extra torrent by entering then exiting fullscreen
* The filter bar is, technically, squiffy.

![SCR-20220613-ju5](https://user-images.githubusercontent.com/69029666/173269192-69a3f44a-a160-41b6-9130-bf07fe209b6a.png)

**Comment by sweetppro** [comment]
this is actually related to #3261

**Comment by GaryElshaw** [comment]
Fixed!
