### ISSUE TITLE
French localisation missing in log window

### ISSUE THREAD

**Issue by fxcoudert** [transmission/transmission#3280]
Some levels of logging have an empty string only:

<img width="208" alt="Capture d’écran 2022-06-13 à 09 05 42" src="https://user-images.githubusercontent.com/1980544/173298289-9e8bb950-e66a-492f-ba85-fa1c52f676de.png">

**Comment by nevack** [comment]
Can you provide proper translation for missing labels as native speaker? :)

**Comment by Oleg-Chashko** [comment]
It seems to be on all localizations except English.

<img width="293" alt="Russ" src="https://user-images.githubusercontent.com/62497891/173342118-45b84cc6-72fe-464c-aacf-ddc0275ccf5e.png">
<img width="293" alt="Screen Shot 2022-06-13 at 13 10 27" src="https://user-images.githubusercontent.com/62497891/173342126-419f3ed4-bb63-4b9e-8953-b0ac2169061d.png">
<img width="293" alt="Screen Shot 2022-06-13 at 13 11 12" src="https://user-images.githubusercontent.com/62497891/173342128-782373e8-a6e9-4de9-9ba0-559bbcf674e1.png">

**Comment by fxcoudert** [comment]
For 🇫🇷 :

`Warn` should be `Avertissement`, `Info` should be `Renseignement` (singular), `Trace` should be `Trace`.

**Comment by nevack** [comment]
@mikedld  Hi, Mike! Can you help us here?
I know translations must be made on https://www.transifex.com/transmissionbt/transmissionbt/, but nobody really have access to make any suggestions.

P.S. Maybe migrate to Crowdin? I think it's very popular among open-source projects.

**Comment by fxcoudert** [comment]
<img width="802" alt="Capture d’écran 2022-06-13 à 17 06 34" src="https://user-images.githubusercontent.com/1980544/173384786-2aa7d8ec-71ce-4b87-a469-5a3ed9b560d4.png">

I can't make the suggestion on Transifex, even though I made one in the past, because I was removed from the project.

**Comment by fxcoudert** [comment]
Also, Transifex says all strings are translated in French:

<img width="268" alt="Capture d’écran 2022-06-13 à 18 30 52" src="https://user-images.githubusercontent.com/1980544/173401177-c01c02da-9148-45ce-8c40-4f19826c3579.png">

**Comment by Coeur** [comment]
@mikedld can you re-add fxcoudert?

**Comment by mikedld** [comment]
I didn't remove him to begin with. Was there a conflict with team coordinator? I see he's in the team now, but I wasn't the one who added him either.

**Comment by fxcoudert** [comment]
@mikedld I don't think there was any conflict, I had submitted one minor change (adding a missing space, IIRC). 🤷

**Comment by mikedld** [comment]
I have synced latest translations, is this fixed or still an issue?

**Comment by Oleg-Chashko** [comment]
> I have synced latest translations, is this fixed or still an issue?

3.00+3b9e831eee

- Fr
<img width="280" alt="Fr" src="https://user-images.githubusercontent.com/62497891/174458024-3409f3d4-6716-48a0-9805-4d30b69d7a81.png">

- Tu
<img width="280" alt="Tu" src="https://user-images.githubusercontent.com/62497891/174458048-4ac6c242-5c85-4ce6-b7d3-3db3ded05586.png">

- Ru
<img width="280" alt="Ru" src="https://user-images.githubusercontent.com/62497891/174458056-e6ed41c5-be5d-44aa-9e2f-9f3756ed743d.png">

- Ge
<img width="280" alt="Ge" src="https://user-images.githubusercontent.com/62497891/174458182-40fe6c6a-d0d9-4329-980b-8ea4df924723.png">

**Comment by mikedld** [comment]
Original report is about French, which is now fine. For the rest, need to wait for translators to catch up, nothing I can do about it.

**Comment by fxcoudert** [comment]
@mikedld In this context, `Warn` should be `Avertissement`, because all others are nouns. I've made the suggestion in Transifex.

**Comment by Coeur** [comment]
> I have synced latest translations, is this fixed or still an issue?

There is another regression: we should not add an `s` for the singular form.
![Capture d’écran 2022-06-19 à 19 32 35](https://user-images.githubusercontent.com/839992/174478800-f8c4908b-a17d-4fb5-8db1-c65485da6c90.png)

**Comment by mikedld** [comment]
> @mikedld In this context, `Warn` should be `Avertissement`, because all others are nouns. I've made the suggestion in Transifex.

Maybe we should change the source string to "Warning" so that it's clear? Or add " (noun)" to the context string, although I don't think "warn" could ever be noun in English...

**Comment by Coeur** [comment]
Let's change the English string
