### ISSUE TITLE
macOS - v.3.00+bf1d668f9a - Filter bar doesn't work

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3281]
macOS - Regress, Filter bar doesn't work.
Crash Log: [Transmission-2022-06-13-193913.ips.zip](https://github.com/transmission/transmission/files/8893308/Transmission-2022-06-13-193913.ips.zip)
_Please be careful before merging branches, make sure you haven't made things worse than they were._

![Screen](https://user-images.githubusercontent.com/62497891/173318921-f045ce09-a1e5-486a-bd44-e21ebe493302.gif)

**Comment by Oleg-Chashko** [comment]
v.3.00+c6b49e99d8 - Fixed regression.

**Comment by ckerr** [comment]
@Oleg-Chashko thanks for going back and updating these regression reports :heart:

**Comment by Oleg-Chashko** [comment]
@ckerr
_Thanks for going back_ -> I didn't go anywhere. :)
_Thanks for updating these regression reports_ -> Always happy to help. ❤️
