### ISSUE TITLE
macOS - Improve: A drop-down list box №2

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3293]
@nevack, 
If you have the time and desire, please correct as in this issue: macOS - Improve: A drop-down list box #3263
Thank you.

<img width="729" alt="Screen Shot 2022-06-13 at 21 45 18" src="https://user-images.githubusercontent.com/62497891/173434323-5880c0d9-d8e5-4af0-98c8-ac663d5f6f37.png">

**Comment by nevack** [comment]
@Oleg-Chashko Can you provide more info? I do not see how to reproduce.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko Can you provide more info? I do not see how to reproduce.

https://user-images.githubusercontent.com/62497891/173438194-a1596ede-f88c-465f-9211-c3846595cd4e.mp4

**Comment by nevack** [comment]
Oh, okay, this is another NSPopover.
Okay, I'll take a look into it.

**Comment by Oleg-Chashko** [comment]
> Oh, okay, this is another NSPopover.
> Okay, I'll take a look into it.

Thank you.
