### ISSUE TITLE
Selecting torrents problem - Mac

### ISSUE THREAD

**Issue by Palivec** [transmission/transmission#330]
Hi !
Im having a problem in OSX client. Im downloading 29 torrents divided in 3 groups. I want to pause all of them except a few. So I select them all (cmd+a) and I manually uncheck the few (cmd+click). Then I click "pause selected" (either button, context menu..) and ALL of them get paused, including the unchecked. Its the same with resuming the torrents.

I hope its comprehensible :-)
I use 2.92 , osx 10.11.6 , it happens with the latest git build too.

Maybe the same as #290

**Comment by Coeur** [comment]
It seems to behave as expected nowadays.
There are at least four techniques:
A. From "context menu", you got only one option (pause/resume selection)
B. From "button", you got the two options (pause/resume, all or selections), eventually after customising the toolbar
C. From "app menu", you got the two options (pause/resume, all or selections)
D. From "keyboard", you got the two options (pause/resume, all or selections) with `⌥⌘.`, `⌥⌘/`, `⌘.`, `⌘/`

I've tried it all, it works as expected.
Kindly try with a nightly build eventually.
