### ISSUE TITLE
[macOS] Can't resize torrent window vertically in 3.00+ (d20b77a9ab)

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#3307]
The torrent window can only be resized horizontally in 3.00+ (d20b77a9ab) on macOS. This bug also effects the prior build.

macOS 10.15.7 (19H1922), Intel.

**Comment by GaryElshaw** [comment]
Verified here.

**Comment by CyberSkull** [comment]
Now I can't resize anything in 3.00+ (869741de7c).

**Comment by CyberSkull** [comment]
> Now I can't resize anything in 3.00+ ([869741d](https://github.com/transmission/transmission/commit/869741de7c96cf5398c5f1afe877f4c0922066f0)).

Allow me to correct myself. If I use the horizontal resize on the right hand side it causes the window to slide down the screen.

**Comment by sweetppro** [comment]
this is likely related to #3305

**Comment by CyberSkull** [comment]
Horizontal resizing works in 3.00+ (42198afc5f), but no vertical resizing is offered.

**Comment by CyberSkull** [comment]
Still can't resize vertically in 3.00+ (b983a3ba5c).

**Comment by sweetppro** [comment]
do you have *Automatically size window to fit all transfers* checked?

**Comment by CyberSkull** [comment]
I didn't even know that as an option.

**Comment by CyberSkull** [comment]
I'd prefer an option that would let me snap it to the size of full row.
