### ISSUE TITLE
Cannot set password on windows transmission

### ISSUE THREAD

**Issue by syaifulnizamyahya** [transmission/transmission#331]
Here are my settings.json located in C:\Windows\ServiceProfiles\LocalService\AppData\Local\transmission-daemon

> {
>     "alt-speed-down": 50,
>     "alt-speed-enabled": false,
>     "alt-speed-time-begin": 540,
>     "alt-speed-time-day": 127,
>     "alt-speed-time-enabled": false,
>     "alt-speed-time-end": 1020,
>     "alt-speed-up": 50,
>     "bind-address-ipv4": "0.0.0.0",
>     "bind-address-ipv6": "::",
>     "blocklist-enabled": false,
>     "blocklist-url": "http://www.example.com/blocklist",
>     "cache-size-mb": 4,
>     "dht-enabled": true,
>     "download-dir": "C:/Downloads/Complete/transmission",
>     "download-queue-enabled": true,
>     "download-queue-size": 5,
>     "encryption": 1,
>     "idle-seeding-limit": 30,
>     "idle-seeding-limit-enabled": true,
>     "incomplete-dir": "C:/Downloads/Complete/transmission/temp",
>     "incomplete-dir-enabled": true,
>     "lpd-enabled": false,
>     "message-level": 2,
>     "peer-congestion-algorithm": "",
>     "peer-id-ttl-hours": 6,
>     "peer-limit-global": 200,
>     "peer-limit-per-torrent": 50,
>     "peer-port": 51413,
>     "peer-port-random-high": 65535,
>     "peer-port-random-low": 49152,
>     "peer-port-random-on-start": false,
>     "peer-socket-tos": "default",
>     "pex-enabled": true,
>     "port-forwarding-enabled": true,
>     "preallocation": 1,
>     "prefetch-enabled": true,
>     "queue-stalled-enabled": true,
>     "queue-stalled-minutes": 30,
>     "ratio-limit": 0,
>     "ratio-limit-enabled": true,
>     "rename-partial-files": true,
>     "rpc-authentication-required": false,
>     "rpc-bind-address": "0.0.0.0",
>     "rpc-enabled": true,
>     "rpc-password": "password",
>     "rpc-port": 9091,
>     "rpc-url": "/transmission/",
>     "rpc-username": "user",
>     "rpc-whitelist": "127.0.0.1",
>     "rpc-whitelist-enabled": false,
>     "scrape-paused-torrents-enabled": true,
>     "script-torrent-done-enabled": false,
>     "script-torrent-done-filename": "",
>     "seed-queue-enabled": true,
>     "seed-queue-size": 5,
>     "speed-limit-down": 100,
>     "speed-limit-down-enabled": false,
>     "speed-limit-up": 100,
>     "speed-limit-up-enabled": false,
>     "start-added-torrents": false,
>     "trash-original-torrent-files": false,
>     "umask": 0,
>     "upload-slots-per-torrent": 14,
>     "utp-enabled": true
> }

Unfortunately, I can login remotely without entering password. If I enter password, it doesnt matter if its wrong or right, I can always login.

How do I set transmission daemon password?

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

**Comment by syaifulnizamyahya** [comment]
Will do.

Sorry.
