### ISSUE TITLE
[macOS] Incorrect behavior in full screen mode when "Auto resize" is enabled

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3313]
- macOS Monterey v.12.4 (21F79)
- Transmission v.3.00+06e5767234

Incorrect behavior in full screen mode when "Auto resize" is enabled.
<img width="393" alt="Auto resize" src="https://user-images.githubusercontent.com/62497891/174287838-0f18de27-74e4-4409-95e3-61b83f984f89.png">

Examples:
- 1.View -> Compact View

https://user-images.githubusercontent.com/62497891/174287965-f761039d-2797-4fb7-844a-69d816652b7f.mp4

- 1.2.View -> Compact View

https://user-images.githubusercontent.com/62497891/174288072-96b4871b-d58c-4664-9546-03641047bca5.mp4

---

- 2.View -> Use Groups

https://user-images.githubusercontent.com/62497891/174288153-5ad6526b-023b-451a-9546-a32baf6ea720.mp4

---

- 3.View -> Show Status Bar

https://user-images.githubusercontent.com/62497891/174288227-db935fa6-4309-4fbe-b2e6-c0a7a73d86e0.mp4

---

- 4.View -> Show Filter Bar

https://user-images.githubusercontent.com/62497891/174288344-2381f8e2-0e27-4555-9b4c-829a40cb06eb.mp4

**Comment by Oleg-Chashko** [comment]
@sweetppro 
As a temporary measure, it is to block everything related to "View" in fullscreen mode with "Auto resize" enabled?

**Comment by sweetppro** [comment]
I don’t see any of these behaviours happening on my M1 Air running macOS 12.4?

I’m starting to think this is a losing battle…
Maybe we just s rap full screen mode.

full screen mode + auto size = 💥🤯🤮

**Comment by sweetppro** [comment]
> @sweetppro
> As a temporary measure, it is to block everything related to "View" in fullscreen mode with "Auto resize" enabled?

I’ve already done this…

**Comment by Oleg-Chashko** [comment]
> I don’t see any of these behaviours happening on my M1 Air running macOS 12.4?
> 
> I’m starting to think this is a losing battle… Maybe we just scrap full screen mode.
> 
> full screen mode + auto size = 💥🤯🤮

MacBook Pro (Retina, 13-inch, Early 2015) 🙁

**Comment by Oleg-Chashko** [comment]
_Maybe we just scrap full screen mode?_ 

I'm afraid to even suggest it. The defenders of fullscreen mode will start throwing shoes at me. 😀

**Comment by sweetppro** [comment]
@Oleg-Chashko  Ive uploaded a fix for this issue #3315
and ill keep plugging away at the Hide/Show Toolbar issue
