### ISSUE TITLE
Upload torrent files on mobile devices

### ISSUE THREAD

**Issue by gonstr** [transmission/transmission#332]
Using my iPhone, I want to be able to upload torrent files in the transmission web interface. This is not possible today because the upload file button is hidden on mobile devices through a display: none property in mobile.scss.

I made a pull request for this (https://github.com/transmission/transmission/pull/320). I'm happy to work on it more if it's needed.

**Comment by mikedld** [comment]
Thanks for the PR. There is absolutely no need in opening an issue though.

**Comment by Wheaties466** [comment]
just an fyi to any else that finds this in a google search if you would like to just change the useability to allow mobile uploading edit the mobile.css file on line number 893 in the following commit to get this to work with your existing implementation.

https://github.com/transmission/transmission/pull/320/commits/2624c6b73b97e6729270831c0ce7165e2df936ec
