### ISSUE TITLE
[macOS] Bug with the color and blinking of the background

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3320]
- macOS Monterey v.12.4 (21F79)
- Transmission v.3.00+90f2757448

1. When you switch from window mode to full screen mode, the background changes color.
2. When I stretch the window vertically, the background and header change their color.
2.1 When I resize the window, the application window blinks slightly.

Examples:
<img width="1710" alt="Windowed mode to Fullscreen mode" src="https://user-images.githubusercontent.com/62497891/174453030-fa707db4-65ad-43df-b463-90c55050f70d.png">

https://user-images.githubusercontent.com/62497891/174453034-431b94fc-9f03-4b3a-9f3b-d71c45f66413.mp4

**Comment by GaryElshaw** [comment]
I think this might be part of a long-standing bug #2512.

**Comment by Oleg-Chashko** [comment]
Fixed, v.3.00+ffe307ac1b
