### ISSUE TITLE
arc4 implementation is expensive

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#3325]
While profiling a session today with perf + hotspot, I found arc4 functions are three of the four most expensive functions. Collectively they take up about 46% of the runtime during a download.

function | cycles (self) | cycles (incl.)
---|---|---
arc4_next | 26.2% | 39.8%
arc4_swap | 14% | 15.9%
arc4_process | 9% | 46.8%

This was with `CMAKE_BUILD_TYPE=Debug` so it's possible that a significant part of this could be due to assertions.

*edit:* when built with `RelWithDebInfo` it's more like 20% instead of 46%

**Comment by nevack** [comment]
Wanna note that my Intel MacBook gets significantly hot when there're any active download.
Transmission takes like 5-10% cpu time constantly, greater than 1080p video playing in Chrome.

Can this be related?

**Comment by ckerr** [comment]
Since the algorithm is so small, I tried wrapping it by hand into an hpp file to see if inlining / constexpr / removing pointer indirection would help. Still about 20%, so probably this is just the nature of the beast.

PE/MSE is apparently insecure anyway -- if your ISP wants to shape traffic based on whether you're using BitTorrent or not, they can still do that. IMO the current spec for PE/MSE doesn't serve a lot of use unless your ISP is traffic shaping _and_ is doing a lazy job of it.

Since I'm going to mark the hpp code up as a "failed" experiment (the code works, but it doesn't improve performance), I'm not going to PR it or make a branch for it. The code is @ https://gist.github.com/ckerr/dd72d818a39603fda80b1cc78e5ec45d

I'm going to close this ticket since it doesn't appear that there's anything actionable, short of recoding arc4 in assembly.

**Comment by ckerr** [comment]
> Wanna note that my Intel MacBook gets significantly hot when there're any active download. Transmission takes like 5-10% cpu time constantly, greater than 1080p video playing in Chrome.
>
> Can this be related?

Try turning off encryption and see if it makes a difference?

IDK if there's a mac equivalent to `perf` or not but it would be interesting to see where the macOS client spends its cycles. libtransmission has been profiled pretty aggressively via transmsision-daemon and most of its time now is spent either in (a) rc4, or (b) deciding which blocks to request next. However it's possible that there are inefficiencies in the macOS client simply because nobody's been profiling there.

**Comment by nevack** [comment]
> IDK if there's a mac equivalent to perf
perf is userspace tool for Linux kernel specific sys_calls, so no.

But there's Xcode's `Instruments.app`.

Example 1:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/8330119/174724827-ba10b23f-73e3-4529-afb4-87f990583a4a.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/8330119/174724950-b4dfa2d8-2ad3-4f22-8a62-872c9c7219f7.png">

**Comment by ckerr** [comment]
Most of those at the top probably can't be reduced any further.

- send_to_addr() - probably can't do anything about UTP
- event_callback, arc4_process, tr_sys_file_write_at - these probably cannot be reduced further

But these might be worth a couple minutes' investigation:

- tr_bitfield::countFlags() - might be interesting to expand this and see where that 5.8% is coming from. My first guess is that this will turn out to be assertions in a debug build and can be ignored
- TorrentCell drawInteriorWithFrame:inView: - 4.4% seems high?
- Controller applicationShouldTerminate - 3.2% maybe seems high? The code just loops through the torrents and counts active/stalled. Is this called a _lot_? Or is 3.2% just the time spent with the "Confirm Quit" dialog was visible?
- stringForSpeed - 3.2% for speed string formatting? How?? How is this 85% as expensive as rendering the torrent in drawInteriorWithFrame? Are we calling it a million times? is NSLocalizedString() _that_ expensive?

**Comment by nevack** [comment]
Yeah.
I think I will check this UI and formatting code.
Formatting being bottleneck makes me really unhappy.
