### ISSUE TITLE
Can't download metadata - magnet status: checksum passed 1, metainfo parsed 0

### ISSUE THREAD

**Issue by olegon-ru** [transmission/transmission#3331]
I have some troubles while downloading file. It stalled about 6 hours
Log filled up error messages
magnet status: checksum passed 1, metainfo parsed 0
but can be downloaded by other BT-client...
transmission-3.00-9.fc35.src.rpm
I saw this behaviour periodically, but can't explain it... Many other torrents downloaded very well... 
[https://i.imgur.com/qROLvjs.gif](https://i.imgur.com/qROLvjs.gif)

**Comment by ckerr** [comment]
Hey @olegon-ru, thanks for reporting this.

Transmission 3.00 is pretty old now & we're ramping up for a 4.0.0 beta. If you're comfortable building from source, could you try a nightly tarball and/or building from git to see if the problem persists in the current codebase?

**Comment by olegon-ru** [comment]
@ckerr , I'm not comfortable building with source :) :) but I would like to help developers in making this product, so I spent some hours and can build transmission-daemon from git after instaledl many compilers and libs. I can't test new version of transmission-gtk, where (in old version) I can see this bug. 

So, tested git transmission-daemon with transmission-remote-gtk from Fedora repo. Works well and without any problem.

I installed transmission-daemon from repo mentioned above and error occured again. So, new version without this bug.

I don't know how legal these torrents are, so these links in temporary storage, be careful if you want to test them. But already three links with such a problem. https://pastebin.com/XR6RN3B6

We need a release :) Thank you for your job.

**Comment by ckerr** [comment]
Closing as fixed based on previous comment.
