### ISSUE TITLE
set location doesn't do anything

### ISSUE THREAD

**Issue by zeratax** [transmission/transmission#3337]
I moved a directory with multiple completed torrents to a different drive. of course now transmission can't find them anymore. But using the set location dialog, neither move nor "local data is already there" does anything. In the properties tab the old path is still being shown?

This is on 3.0.0 on windows 11

**Comment by ckerr** [comment]
Would it be possible to try a nightly build from https://transmissionbt.com/ and see how that goes? Transmission 4 has been in development for awhile now and we're finishing up the work before the first beta, so the state of the current code is pretty different from 3.0.0.

**Comment by zeratax** [comment]
I only saw a download for 3.0.0 (bb6b5a062e) on the website?
I did notice that set location does actually work, but it requires a restart until anything happens!
