### ISSUE TITLE
GoogleTest v1.12.0

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3340]
Released [today](https://github.com/google/googletest/releases/tag/release-1.12.0), the notes include:

"This will be the last release to support C++11. Future releases will require at least C++14."

Also noteworthy, they're no longer accepting contributions. "GoogleTest will not accept patches of new features to v1.12.0."

**Comment by nevack** [comment]
They are not accepting contributions for this release.
I think they mean target PRs into master, GoogleTest is more like rolling release library like Abseil from now

**Comment by nevack** [comment]
Have you checked for new features we will get and what will break?

**Comment by GaryElshaw** [comment]
No. I'm just giving a heads-up. I have compiled it locally, and it compiles fine.
