### ISSUE TITLE
Feature request: Run a checksum manually

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#3343]
This actually stems from a bug but I will describe what happened on the latest Mac version.

1. Downloaded torrent to 100% completion (green).
2. Transmission has a rule to move the complete file to a folder, which happens to be a network drive
3. It ended up being green and marked as if it was seeding and working fine
4. This file remained green over multiple app launches and system reboots.

Issue:
1. I ended up trying to play the file and it was very broken. Kind of unexpected and I didn't think transmission was related.
2. I ended up removing the torrent from Transmission, and then re-adding the file back in which forces a checksum. The checksum ran and it ended up going from what was previously 100% down to 70% (!). 

Ultimate issues / requests:
1. I think it was a bug that it thought it was complete but wasn't. I have no idea how that happened or why. Seems very odd to me. 
~2. It would be great if I had a menu option to just re-run the checksum manually in the case that I think it might be worthwhile.~
3. When I removed the torrent and re-added it (and it went to 70%) it just sat there and didn't connect to any peers. It didn't say anything was wrong it just didn't connect to peers or DL anything. I had to restart the entire app and it almost instantly started connecting to peers.

EDIT: I just realized there is a verify local data option but it's from the top menu not the contextual menu.

**Comment by GaryElshaw** [comment]
Although i'm not 100% sure, i'm pretty sure it was a bug that got resolved last week that was really nasty. https://github.com/transmission/transmission/pull/3324

**Comment by nvanfleet** [comment]
> Although i'm not 100% sure, i'm pretty sure it was a bug that got resolved last week that was really nasty. #3324

I'm not sure that's what I am describing. It said that it was fully downloaded fine not stuck at 99%

**Comment by GaryElshaw** [comment]
I also had the same thing you describe, on the surface, the file had seemingly downloaded fine, but sometimes was so irrevocably corrupt it often had to be freshly downloaded. I would definitely recommend to try a new nightly: https://build.transmissionbt.com/job/trunk-mac/

**Comment by mraonea** [comment]
https://github.com/transmission/transmission/pull/3025

**Comment by nvanfleet** [comment]
I tried the nightly but it just kept asking for access to my network drive in a loop until I just had to kill it.

**Comment by ckerr** [comment]
@nvanfleet that's a separate issue; could you open a new ticket for that?

Marking this one as fixed by #3025
