### ISSUE TITLE
[Windows] Icons blurry when display scaled.

### ISSUE THREAD

**Issue by hanekomdirk** [transmission/transmission#3349]
When display scaling is enabled, icons within the app becomes blurry, that is, the gear, the turtle, the plus, the pause and so on. This is on the main app view as well as in the icons within the top menu bar drop down menus.

All other controls and text scale perfectly, incl the tray icon, title bar icon and application shortcut icon.

Conditions:
Transmission 3
Windows 10
Dell 27" 2560x1440 @ 200% scaling (so effectively a 720p screen, but very crisp).
Using integer scaling only, not fractional scaling (so no blurriness from picking the "wrong" scaling factor).

I don't believe it is a problem with my graphics driver or machine, running a stock standard/boring system, most likely a bug or not implemented yet.

**Comment by ckerr** [comment]
I think the problem is that some of the icons that we bundle are older png files and are not scalable.

:+1: that this is a problem, but it probably needs a graphic designer to do some work for the project in order to be solved

**Comment by GaryElshaw** [comment]
Which icon set is Windows using, Charles?

**Comment by ckerr** [comment]
@GaryElshaw this is the icon set that transmission-qt pulls in.

**Comment by GaryElshaw** [comment]
Interesting. This might have something to do with our build settings(?), Faenza includes the full set of icons in svg.

**Comment by GaryElshaw** [comment]
@hanekomdirk Can you please try the latest commit and see if that helps?
