### ISSUE TITLE
Uploading speed is not displayed, always 0 kB/s

### ISSUE THREAD

**Issue by Noobsai** [transmission/transmission#3357]
Version Gnome GTK 3.00+ (eefcbe7cb2)
![Screenshot from 2022-06-26 14-38-57](https://user-images.githubusercontent.com/17625194/175808542-873172b2-c716-4204-8658-981e417523b8.png)

Both view modes are affected.
Downloading speed is ok.
Uploading speed at the Peers tab is ok.
Status bar is ok.

**Comment by ckerr** [comment]
Fixed by #3560
