### ISSUE TITLE
ARC Transition

### ISSUE THREAD

**Issue by DevilDimon** [transmission/transmission#336]
Since the minimum required macOS version has been bumped up, should the project be converted to use ARC? [TRAC-4822](https://trac.transmissionbt.com/ticket/4822) already has the required changes which should be easy to integrate into the current codebase.

**Comment by mikedld** [comment]
I'm cool with this if it still works and doesn't leak afterwards. Not sure if basing your work on the patch from TRAC-4822 is a good idea though; it could certainly be used as a reference in case of issues but I would guess most of the changes there were done using automated migration, i.e. Edit -> Convert -> To Objective-C ARC...
