### ISSUE TITLE
YingYangGroupTemplate.imageset?

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3367]
I mean, i'm totally not adverse to the idea. In fact, how do i make this work?

![SCR-20220628-klf](https://user-images.githubusercontent.com/69029666/176081474-057200b4-4e2d-4472-8518-4183078917ef.png)

**Comment by fxcoudert** [comment]
@GaryElshaw I absolutely do not understand what you write.

> I mean, i'm totally not adverse to the idea.

The idea of what?

> In fact, how do i make this work?

Make what work?

**Comment by GaryElshaw** [comment]
When the changes to the Group icons was occurring, i wondered if someone had put in the YingYang icon as a Group icon somehow. There is already a YingYangTemplate.imageset for the statusbar, why would there be another duplicate imageset?

**Comment by fxcoudert** [comment]
The icons are not identical: the group one is more grey, like other group images.

What is the issue that you think should be fixed? What do you want to “make work”?

**Comment by GaryElshaw** [comment]
I'm happy to be corrected, but so far as i know, that symbol only appears in one place in the ui, and that's in the status bar.

I was actually hopeful this might be an 'easter egg' where it could be used as a group symbol outside of the colour swatches.

**Comment by fxcoudert** [comment]
`YingYangGroupTemplate.imageset` is used there https://github.com/transmission/transmission/blob/3e73913a1dba0f17746d06ad68c8f0e03198828a/macosx/Controller.mm#L3488

**Comment by GaryElshaw** [comment]
I don't see it :-(

**Comment by ckerr** [comment]
I am having trouble reading this bug report but from what I can understand I don't think this is a bug report...?

If that's the case please continue this in  Discussions if needed.
