### ISSUE TITLE
64 bit build causes access violation on Windows 10 professional x64

### ISSUE THREAD

**Issue by jpmikkers** [transmission/transmission#337]
Both the 64 bit official release and nightly build (around 2017-07-15) have the same problem:

    Faulting application name: transmission-qt.exe, version: 2.92.0.0, time stamp: 0x5960dc8f
    Faulting module name: LIBEAY32.dll, version: 1.0.2.7, time stamp: 0x56e30cce
    Exception code: 0xc0000005
    Fault offset: 0x0000000000003863
    Faulting process id: 0x2740
    Faulting application start time: 0x01d2fe538c10a10b
    Faulting application path: C:\Program Files\Transmission\transmission-qt.exe
    Faulting module path: C:\Program Files\Transmission\LIBEAY32.dll
    Report Id: 89e21ba7-bd03-43f0-ae84-d020969adb4c
    Faulting package full name: 
    Faulting package-relative application ID: 

Note that the 32 bit version works fine.

**Comment by LainOTN** [comment]
In my machine changing the libraries LIBEAY32.DLL and SSLEAY32.DLL from the shiped version (1.0.2.7)(1.0.2g) to the version 1.0.2.14 (1.0.2n) did the trick. Maybe an issue on OpenSSL and not Transmission...

**Comment by bonovski** [comment]
```
Faulting application name: transmission-daemon.exe, version: 2.94.0.0, time stamp: 0x5ae8a63c
Faulting module name: LIBEAY32.dll, version: 1.0.2.7, time stamp: 0x5ae88d3a
Exception code: 0xc0000005
Fault offset: 0x0000000000003763
Faulting process id: 0x24c4
Faulting application start time: 0x01d48ce282f3f360
Faulting application path: C:\Program Files\Transmission\transmission-daemon.exe
Faulting module path: C:\Program Files\Transmission\LIBEAY32.dll
Report Id: a5111839-ccc0-4035-9ee8-d3b17871daab
Faulting package full name: 
Faulting package-relative application ID: 
```

This is still a thing with the x64 version. x86 works fine.
Version 2.94

**Comment by youngqqcn** [comment]
错误应用程序名称: Asset_Management_Center(148).exe，版本: 0.0.0.0，时间戳: 0x5e832897
错误模块名称: LIBEAY32.dll，版本: 1.0.1.7，时间戳: 0x5344070e
异常代码: 0xc0000005
错误偏移量: 0x0005c27f
错误进程 ID: 0x3814
错误应用程序启动时间: 0x01d6074fb1036d69
错误应用程序路径: D:\work\AM_WM\Assert_Mng_Center\Asset_Management_Center(148).exe
错误模块路径: D:\work\AM_WM\Assert_Mng_Center\LIBEAY32.dll
报告 ID: 0adbfa91-7383-11ea-a0eb-64006a37fbce

**Comment by youngqqcn** [comment]
this is an issue of  OpeenSSL

**Comment by mikedld** [comment]
Official 3.00 builds use a newer OpenSSL version. Please try it and report back if this is still an issue.
