### ISSUE TITLE
Lots of build warning for dsym generation on macOS

### ISSUE THREAD

**Issue by fxcoudert** [transmission/transmission#3371]
There are many warnings in both Transmission and QuickLookPlugin:

<img width="890" alt="Capture d’écran 2022-06-28 à 22 46 47" src="https://user-images.githubusercontent.com/1980544/176284594-8ec69dd4-d192-4c43-a81f-00f08de1db73.png">

**Comment by nevack** [comment]
I think it's because we use plain libraries targets and not frameworks.

**Comment by Coeur** [comment]
Fixed in #4031
