### ISSUE TITLE
is the tortoise icon clipped horizontally on macOS client?

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3381]
@sweetppro Could you please take a look? I think the nose and tail may have fallen off.

**Comment by sweetppro** [comment]
The TortoiseTemplate image is fine.
It was taken directly from SF Symbols.
It has two tones, but that is fine as it is a template image.
macOS tints the image and displays it correctly.

**Comment by GaryElshaw** [comment]
Oh, i know, i just thought he might need a little padding. I thought he might be a couple of pixels short in the nose and tail?

**Comment by GaryElshaw** [comment]
Often these are project related aspects that i would normally email contributors about, and they would know from those subject lines exactly what i was talking about, but we don't do email or chat here.

**Comment by ckerr** [comment]
Imagine you're searching #3351 a year from now and you can't remember the name "Motuopuhi" but you remember it was an SF icon set for Qt.

I'd probably type in something like "macOS SF icons qt".

So the title for that PR should be a variation of that, something like "Add macOS-based Motuopuhi icons to Qt client"

- it's easier for Future You to find a year from now
- it's easier to understand the issue / PR from reading the title alone, making it more inviting for reviewers / testers
- it's easier to understand when going back and looking at commits / PRs to write release notes

> Often these are project related aspects that i would normally email contributors about, and they would know from those subject lines exactly what i was talking about, but we don't do email or chat here.

I'm missing your point, sorry. What do you mean?

**Comment by GaryElshaw** [comment]
Here's the current version and one i just grabbed from SF Symbols. I think the current one may be missing some pixels.

![SCR-20220701-k8h](https://user-images.githubusercontent.com/69029666/176812692-036029c3-0bc6-4ce3-9571-97b425ee24b5.png)


![SCR-20220701-kaz](https://user-images.githubusercontent.com/69029666/176812712-c5d16acc-2d32-45a1-890e-909ecb3c2891.png)

**Comment by sweetppro** [comment]
As far as I can tell there is no clipping
<img width="475" alt="Screen Shot 2022-07-02 at 6 40 04 am" src="https://user-images.githubusercontent.com/7323792/176986756-ea544983-990e-4a9c-a60b-c68f455c01f7.png">

**Comment by sweetppro** [comment]
> Here's the current version and one i just grabbed from SF Symbols. I think the current one may be missing some pixels.

you're showing two different resolution images, all that extra resolution is not needed at the scale the icon is shown at

**Comment by GaryElshaw** [comment]
I know, i just wanted to see a comparison.

If you think it's good, it's good. Sweet!
