### ISSUE TITLE
macOS distortion in Torrent Inspector (Monterey 12.4) 3.00+ (849a36a30d)

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3393]
I think it's been there for a little while now, but noticed today that the inspector table has some rendering issues. Note how the grey and white parallel lines bleed to white (also tested in dark which looks unaffected) so quickly?

Can anyone else replicate this? @Oleg-Chashko?

![SCR-20220703-ksv](https://user-images.githubusercontent.com/69029666/177023007-5b5877ad-1085-4327-a709-45b029d32a93.png)

**Comment by GaryElshaw** [comment]
I think main might have this too, the grey and white gradient has gone.

![SCR-20220703-l6g](https://user-images.githubusercontent.com/69029666/177023129-c80ccf6c-9155-41a1-b88a-c2e3577a8861.png)

**Comment by GaryElshaw** [comment]
Separate issue. Why do files of the same type lose their application attributed icon while others don't?

**Comment by GaryElshaw** [comment]
cf dark.

![SCR-20220703-npu](https://user-images.githubusercontent.com/69029666/177025688-7971a264-763b-4e38-a88a-163ff546f921.png)

**Comment by ckerr** [comment]
@GaryElshaw is this still broken?

**Comment by GaryElshaw** [comment]
Yes, but it is haphazard. I'm going to close until i can consistently see it reproduced. If someone can point me to where these values are, i'd like to pr an increased contrast of the gradient for the Light theme. @Coeur

**Comment by Coeur** [comment]
Maybe it's native?
If you do `_fTableView.usesAlternatingRowBackgroundColors = NO;`, then the background is plain instead of being with alternative colors.

**Comment by GaryElshaw** [comment]
I bet it's buried in Xcode somewhere....
