### ISSUE TITLE
macOS Application icon attribution

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3394]
There are file types that currently receive the icon for the application they are associated with, and yet some files with the exact same file type are rendered with a blank document icon.
 
![SCR-20220703-l6g](https://user-images.githubusercontent.com/69029666/177023247-15b299d5-252b-4037-a36d-9e9df2673626.png)

**Comment by ckerr** [comment]
Not sure why I didn't notice the description before; sounds more like a bug than a feature disparity.

@GaryElshaw is this still occurring in 4.0.2?

**Comment by GaryElshaw** [comment]
I'm not seeding any single file torrents at the moment. Any of the usual suspects seeing this with 4.0.2? @Coeur @sweetppro @nevack.

**Comment by Coeur** [comment]
`.mkv`, `.avi` and `.mp4` are all white for me in Transmission. It's been like that for an eternity. It may depend on what you have on your system: from your screenshot, you have VLC installed for supporting the media icons.

In Finder, I have:
![Capture d’écran 2023-03-18 à 14 41 33](https://user-images.githubusercontent.com/839992/226089862-b6d04ff0-317c-4912-9ce1-6146165a7a14.png) ![Capture d’écran 2023-03-18 à 14 32 13](https://user-images.githubusercontent.com/839992/226089870-f9bf9133-2346-472b-8e5b-e66461fc2d3e.png)

**Comment by GaryElshaw** [comment]
Out of interest, what's your default media player, @Coeur?

**Comment by sweetppro** [comment]
Looks like iina

**Comment by GaryElshaw** [comment]
Okay, that makes sense. I'm going to close this because i suspect, depending on the default media playback application, it can't attribute the source icon back to Transmission, rather than the other way around.
