### ISSUE TITLE
toolbar buttons and keyboard shortcuts: up/down in qeue

### ISSUE THREAD

**Issue by buhtz** [transmission/transmission#340]
Currently to move an item up or down in the qeue I need to open the context menu of the item. And I have to do this for each position again. One position: 2 clicks. 4 Postions down: 8 clicks.

It would be nice to have toolbar buttons for this and a keyboard shortcut.

Using transmission on Debian GNU/Linux unstable.

**Comment by mikedld** [comment]
Already fixed in #158.

**Comment by buhtz** [comment]
Then I have to point to #318 with some pressure. ;)
Even the version in Debian **unstable** is out-dated.
