### ISSUE TITLE
Ensure Piece Size Selector in torrent creator UI goes up to 32MB (or 64MB if possible) on all platforms (MacOS remaining)

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#3402]
There's been some work on this here: https://github.com/transmission/transmission/pull/3145

However, it only goes up to 16MB on the GUI and I would say this puts Transmission at a disadvantage because other torrent clients like qBittorrent allow up to 32MB pieces, which is very much necessary for very large torrents, which are getting bigger every decade. Some torrent clients can go up to 64MB pieces, which is also welcome since it is the current maximum size for the Bittorrent spec.

If we can allow users on all platforms to set their created torrent piece sizes to at least 32MB (or 64MB if possible) it would bring Transmission to current open source client standards.

**Comment by Lanzaa** [comment]
>  ... up to 64MB pieces, which is ... the current maximum size for the Bittorrent spec

@Pentaphon  Do you have a source for that?

**Comment by ckerr** [comment]
I don't see any limit in https://www.bittorrent.org/beps/bep_0052.html but maybe it's discussed in another bep?

**Comment by mikedld** [comment]
@Pentaphon, @orbital-mango, could this be closed now?

**Comment by Pentaphon** [comment]
@mikedld looks like it. Thanks again to @orbital-mango

**Comment by Pentaphon** [comment]
@mikedld No because I think MacOS users still need this feature.

**Comment by orbital-mango** [comment]
I don't believe there's an upper limit on the MacOS version is there? The
limit is kind of artificial in that it's an upper bound on the slider used
on the GTK and Qt build. The Mac version uses some other UI element without
that restriction. I could be wrong though, maybe a Mac user could verify
this...

**Comment by Coeur** [comment]
The present limit on macOS is 2048 MB. There is a bug above that size, but we could say it's out of the scope of this issue, and I'll close it.
I'll reopen a different issue or PR for avoiding the bug on 4096 MB piece selector on macOS.
