### ISSUE TITLE
PeerSocketTOS: Doesn't set on IPv6 sockets on Mac OS

### ISSUE THREAD

**Issue by nightexcessive** [transmission/transmission#341]
When using the PeerSocketTOS preference on a Mac with IPv6, the TOS field isn't actually set on IPv6 sockets. This is because `tr_netSetTOS` calls `setsockopt(s, IPPROTO_IP, IP_TOS, (void const*)&tos, sizeof(tos))` when it should be calling `setsockopt(s, IPPROTO_IPV6, IPV6_TCLASS, (void const*)&tos, sizeof(tos))`, but only for IPv6 sockets.

**Comment by mikedld** [comment]
See #128.
