### ISSUE TITLE
Failed to set receive buffer UDP in Debian Solution?

### ISSUE THREAD

**Issue by anastiel** [transmission/transmission#342]
Mon Jul 24 01:21:42 2017	     		Transmission 2.84 (14307) started
Mon Jul 24 01:21:42 2017	     	RPC Server	Adding address to whitelist: 127.0.0.1
Mon Jul 24 01:21:42 2017	error	UDP	Failed to set receive buffer: requested 4194304, got 425984
Mon Jul 24 01:21:42 2017	     	UDP	Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf
Mon Jul 24 01:21:42 2017	error	UDP	Failed to set send buffer: requested 1048576, got 425984
Mon Jul 24 01:21:42 2017	     	UDP	Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf
Mon Jul 24 01:21:42 2017	error	UDP	Failed to set receive buffer: requested 4194304, got 425984
Mon Jul 24 01:21:42 2017	     	UDP	Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf
Mon Jul 24 01:21:42 2017	error	UDP	Failed to set send buffer: requested 1048576, got 425984
Mon Jul 24 01:21:42 2017	     	UDP	Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf
Mon Jul 24 01:21:42 2017	     	DHT	Reusing old id
Mon Jul 24 01:21:42 2017	     	DHT	Bootstrapping from 109 IPv4 nodes
Mon Jul 24 01:21:42 2017	     	DHT	Bootstrapping from 55 IPv6 nodes
Mon Jul 24 01:21:42 2017	     	Port Forwarding (NAT-PMP)	initnatpmp succeeded (0)
Mon Jul 24 01:21:42 2017	     	Port Forwarding (NAT-PMP)	sendpublicaddressrequest succeeded (2)
Mon Jul 24 01:21:42 2017	     	Port Forwarding (UPnP)	Found Internet Gateway Device "http://192.168.1.1:2555/upnp/fb8dcf56-ebf8-32f2-bd3a-e63e9031dfd5/WANPPPConn1.ctl"
Mon Jul 24 01:21:42 2017	     	Port Forwarding (UPnP)	Local Address is "192.168.1.37"
Mon Jul 24 01:21:42 2017	     	Port Forwarding (UPnP)	Port forwarding through "http://192.168.1.1:2555/upnp/fb8dcf56-ebf8-32f2-bd3a-e63e9031dfd5/WANPPPConn1.ctl", service "urn:schemas-upnp-org:service:WANPPPConnection:1". (local address: 192.168.1.37:59708)
Mon Jul 24 01:21:42 2017	     	Port Forwarding (UPnP)	Port forwarding successful!

**Comment by mikedld** [comment]
What needs to be done is right there, in the logs:
> Mon Jul 24 01:21:42 2017 UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf
> Mon Jul 24 01:21:42 2017 UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf

Please use [forums](https://forum.transmissionbt.com/) for support.

**Comment by anastiel** [comment]
thanks so much

**Comment by Spintendo** [comment]
My system is unable to add anything to /etc/sysctl.conf

**Comment by shuttingdown** [comment]
Spintendo, did you solve the problem? If not, then you need to use sudo nano or sudo vi or whichever text editor do you like, sudo is needed, unless you change the user to root, then edit the /etc/sysctl.conf using nano or vi, you need to add below lines to the end of the file, after that you need to reload systemctl or restart system, and when your system start you can check that the error disappeared? ( for instruction -> thanks to mikedld ):

"net.core.rmem_max = 4194304"
"net.core.wmem_max = 1048576"

Good luck,
