### ISSUE TITLE
omit pii (e.g. 'creation date', 'created by') from .torrent files

### ISSUE THREAD

**Issue by carandraug** [transmission/transmission#3420]
`transmission-create` sets the torrent creation date from the value of `time` (syscall). I was hoping to be able to set it, either on `transmission-create` or `transmission-edit` but that does not seem to possible. It is possible to do this with something such as [libfaketime](https://github.com/wolfcw/libfaketime):

    LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 \
        FAKETIME="1970-01-01 00:00:01" \
        TZ=UTC \
        transmission-create .... directory

But I think it would be nice if there was a way to do this straight from transmission. I could submit a patch to do this, if there's interest on it (on create or on edit?) Or an option to omit the creation date since I believe that it is an optional field.

**Comment by ckerr** [comment]
I'm slightly against this feature; it seems like letting people specify a fake date on the command line is a minor anti-feature. Also I can't remember anyone else asking for this in the decade or so I've been on Transmission so I'm not sure how many people would use it.

What problem are you trying to solve?
