### ISSUE TITLE
transmission-show does not handle 1970 new year entry

### ISSUE THREAD

**Issue by carandraug** [transmission/transmission#3421]
`transmission-show` does not recognize 1970 new year:

    $ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 \
        FAKETIME="1970-01-01 00:00:00" \
        TZ=UTC \
        transmission-create [...] foo
    $ transmission-show foo.torrent | grep 'Created on'
      Created on: Unknown

But does recognize if date is one second later:

    $ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 \
        FAKETIME="1970-01-01 00:00:01" \
        TZ=UTC \
        transmission-create [...] foo
    $ transmission-show foo.torrent | grep 'Created on'
      Created on: Thu Jan  1 01:00:01 1970

I'm guessing that 1970-01-01 00:00:00 is evaluated as false somewhere.

**Comment by carandraug** [comment]
I had a quick go at it and because `tr_torrent_metainfo` requires a date created field which defaults to zero then zero is always used as having no date. This means it's not possible to distinguish between having no date created information and having that date set to the epoch time without a lot more changes (such as having a pointer to a `time_t` at which point we could distinguish between pointing to a zero or nullptr).

**Comment by ckerr** [comment]
@carandraug Let's take a step back for a second -- what are trying to accomplish here?

**Comment by ckerr** [comment]
`std::optional<time_t>` would be the C++ish way of doing this.

**Comment by carandraug** [comment]
@ckerr wrote:
> @carandraug Let's take a step back for a second -- what are trying to accomplish here?

I guess you mean that there's not much, if any, use case to support here. You're probably right then. It's more a matter of what is correct since `time_t` of zero is a valid date and I like correctness. Also, I thought this was a funny issue. But on a more pragmatic approach, if a time zero is not actually used, then it's fine to use for missing value which also simplifies the code.

Typically, when I handle times zero is to avoid reproducibility issues (which is why it is common to set timestamps in tarballs with `tar ... --mtime="@0" ...` for reproducible builds).

Anyway, I made a PR now and I had my fun. I totally understand if you close this as "won't fix".

**Comment by ckerr** [comment]
Thanks for being understanding about it. I appreciate the anonymization PR and would be happy to review future PRs
