### ISSUE TITLE
Crash when pausing webseed

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3423]
I used the torrent posted by @fxcoudert in [here](https://github.com/transmission/transmission/issues/3285#issuecomment-1178803946): https://download.manjaro.org/kde/21.3.2/manjaro-kde-21.3.2-220704-linux515.iso.torrent

About 5 seconds after starting it, I decided to pause it with the pause button. Transmission crashed.
```
11  Transmission                  	       0x103bc6600 tr_assert_report(std::__1::basic_string_view<char, std::__1::char_traits<char> >, int, std::__1::basic_string_view<char, std::__1::char_traits<char> >) + 2312 (tr-assert.mm:20)
12  Transmission                  	       0x103b78930 (anonymous namespace)::tr_webseed::requestBlocks(tr_block_span_t const*, unsigned long) + 1200 (webseed.cc:275)
```

Full crashlog:
[crash.txt](https://github.com/transmission/transmission/files/9076354/crash.txt)

I believe I was on 9dfb3bf3df6bc06032eff9a84a63d5a8890892a9 (but not 100% sure).

**Comment by Coeur** [comment]
Reproduced on current main: you may try to resume and pause multiple times until it crashes.

**Comment by Oleg-Chashko** [comment]
Assertion failure in 9dfb3bf in onPartialDataFetched() #3415

**Comment by fxcoudert** [comment]
Sorry I thought for a minute the backtrace was different, but it's not. Re-closing.
