### ISSUE TITLE
please report the IPv6 address in which the server is bound to trackers

### ISSUE THREAD

**Issue by habys** [transmission/transmission#3424]
Hello, my server is configured with several static global unicast IPv6 addresses for different services for firewalling reasons.

Transmission is configured as best I can to use a particular address, however a different (but real and configured) IPv6 address is reported back.
I am representing my IPv6 address as `ipv6::last hextet`. If I disable the other addresses, the correct address is reported. I can't keep this workaround though.

`ipv6::87` is desired.
`ipv6::333` is what the tracker receives.

```
$ pacman -Q --info transmission-cli | grep Version
Version         : 3.00-4
```

relevant transmission configuration:

```
$ doas grep ipv6 /var/lib/transmission/.config/transmission-daemon/settings.json
    "bind-address-ipv6": "ipv6::87",
```

the correct IPv6 address is bound:

```
$ doas ss -nalpt | grep transmission
LISTEN 0      128                                 127.0.0.1:9091       0.0.0.0:*    users:(("transmission-da",pid=2443202,fd=14))                
LISTEN 0      128                                 10.0.0.53:15000      0.0.0.0:*    users:(("transmission-da",pid=2443202,fd=15))                
LISTEN 0      128      [ipv6::87]:15000         [::]:*    users:(("transmission-da",pid=2443202,fd=16))           
```

Configuration of the NIC:

```
$ ip -6 addr show dev eno1
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    altname enp0s25
    inet6 ipv6::333/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::171c/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::f70/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::87/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::7a31/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::337/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::17c/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::77/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::9134/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::1311/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::517/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 ipv6::ad10/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::aa50/64 scope link 
       valid_lft forever preferred_lft forever
```

After pouring over many tcpdumps, I believe all the traffic is involving only the correct address. Transmission must only be reporting the erroneous address.

**Comment by vchimishuk** [comment]
> After pouring over many tcpdumps, I believe all the traffic is involving only the correct address. Transmission must only be reporting the erroneous address.

@habys, are you saying that IPv6 **announcement** requests are done using `ipv6::87` source address too? 

In this case the only way when invalid address is reported I can see is `ipv6=` URL parameter. `ipv6=` should be sent withing IPv4 announcement request. On other hand, this is strange, that tracker checks this parameter, since it is kind of outdated. 

> Transmission must only be reporting the erroneous address.

Using tcpdump you can try to catch TCP announce requests and check what is the sent URL. 

If your tracker supports `ip` parameter you can use `announce-ip` configuration property to set IP manually. It is already in `main` (see https://github.com/transmission/transmission/pull/3461), so you can use nightly build to make it available.

**Comment by habys** [comment]
Wow, thanks for the fix. Sorry I missed your question. I will test it out to see if it resolves my issue.

**Comment by vchimishuk** [comment]
> Wow, thanks for the fix. Sorry I missed your question. I will test it out to see if it resolves my issue.

@habys , thanks. It will be great if you can confirm that it works for you.

**Comment by habys** [comment]
I am not sure that I can. I've put in a request but the people who run the tracker are strict about which client are allowed to connect. This being the case I may not know until the next version of transmission is released, then ratified.. Thank you for your work though.

**Comment by habys** [comment]
Everything is upgraded and I'm using
```
$ transmission-cli -v
transmission-cli 3.00 (bb6b5a062e)
```

"bind-address-ipv6" is set to a working address, and indeed accepts incoming connections here. Unfortunately transmission is still sending outgoing connections on a EUI-64 address.. I can't think of a work around here other than to block outgoing traffic from all other IPs execept my intended IP. This will just cause the connections to break though and not solve the problem.

**Comment by habys** [comment]
Not sure why the torrent site continues to get the wrong IPv6 address. I monitored the traffic with `watch 'sudo ss -napt | grep -i transmission'` and can confirm that

1) transmission is listening on the correct specified IP.
2) transmission does not send any traffic from the "wrong" IPv6 address that the tracker reports is "my IPv6 address".

From this I must assume that transmission is "telling" the tracker to use the wrong IPv6 address.

**Comment by habys** [comment]
Sorry, closed by accident.

**Comment by ckerr** [comment]
As of https://github.com/transmission/transmission/pull/4502 Transmission no longer includes ipv4 or ipv6 addresses in announce requests so I _think_ this issue should be closed, but TBH I'm not sure I understand what this issue is requesting, so I thought I'd ask for clarification:

Is this problem resolved by 4502? If not, what specific change is being requested here?

**Comment by habys** [comment]
This appears to be resolved.
The tracker that originally was displaying the incorrect IPv6 address no longer shows any IPv6 at all, which is not a problem. I am monitoring tcp connections and so far all appear to be with my specified IPv6 address.

Thank you!
