### ISSUE TITLE
Corruption of downloaded torrent file

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#3429]
I have had this peculiar issue with torrents I have downloaded. They download completely successfully, and then I try to play them and realize the data is corrupt. I use the tool to verify the data and it can go from anywhere from lost 5% of the file to losing 75% of the file, forcing me to redownload that missing part. I feel like I've even done this several times with the same file multiple times.

Some things about my setup that might be relevant
1. Torrents are often single files (or single main files) that are 10GB or greater in size
2. Mac, most of these downloads happened on the latest release 3.0
3. Files are downloaded to an external hard drive and on completion Transmission moves them to a network drive (possible vector for error?).

Just a few days ago I converted to the nightly build, because I think in another issue someone mentioned there might have been a bug in the 3.0.0 release though it sounded more like a scenario where the torrent never completes and not that it completes but is somehow secretly a fail. 

I haven't had enough examples but running verify on about a half dozen of files using the nightly to verify stuff downloaded using 3.0 is turning up more issues.

**Comment by Petrprogs** [comment]
Maybe the data gets corrupted when it is transferred to a network drive? You may need to check the data before copying to a network drive.

**Comment by amedranogil** [comment]
I have experienced a similar issue. 
My setup: 
- transmission running in docker orchestrated with kubernetes (using Trunas Scale chart)
- transmission incomplete directory is in one partition, complete directory is in another partition

when downloads are completed, I watch the logs stating that the copy is underway, sometimes this takes a while, when this happens transmission is blocked, web UI is inaccessible, RPC is also unresponsive. At some point the pod is killed and restarted mid copy (probably kubernetes detecting the health of the pod is bad, when in reality it is just very busy copying), the copy operation is not resumed after restart and the incomplete directory is purged as if the copy was completed. This causes the completed file to be corrupt and, in the case of folders where multiple files are downloaded, some files are also lost.

I would suggest to handle the copy routine in a non-blocking thread, or in a fork, maybe add a protocol to handle mid-copy interruption (like ensuring all files and the hashes of source and target copy are as they should before purging incomplete dir), this way the copy operation is assured to complete correctly and heavy I/O operations do not compromise the rest of operations of transmission.

**Comment by nvanfleet** [comment]
> I have experienced a similar issue. My setup:
> 
> * transmission running in docker orchestrated with kubernetes (using Trunas Scale chart)
> * transmission incomplete directory is in one partition, complete directory is in another partition
> 
> when downloads are completed, I watch the logs stating that the copy is underway, sometimes this takes a while, when this happens transmission is blocked, web UI is inaccessible, RPC is also unresponsive. At some point the pod is killed and restarted mid copy (probably kubernetes detecting the health of the pod is bad, when in reality it is just very busy copying), the copy operation is not resumed after restart and the incomplete directory is purged as if the copy was completed. This causes the completed file to be corrupt and, in the case of folders where multiple files are downloaded, some files are also lost.
> 
> I would suggest to handle the copy routine in a non-blocking thread, or in a fork, maybe add a protocol to handle mid-copy interruption (like ensuring all files and the hashes of source and target copy are as they should before purging incomplete dir), this way the copy operation is assured to complete correctly and heavy I/O operations do not compromise the rest of operations of transmission.

Yeah I have file a ticket about how moving files blocks everything. I had filed that originally because it locked up the UI which was annoying to manage files, but I wouldn't be surprised if it was also the source of this issue.

**Comment by diligiant** [comment]
I'm having this issue too. My setup is much simpler:
- ubuntu 20.04.5 x64
- various transmission nightly (latest being rad125edea9 from 9/9)
- one directory, file names appended with .part until complete
- 
I now systematically "verify local data" every day and 1 out of 30 torrents misses one piece.

What can I do to help figure this out ?

**Comment by nvanfleet** [comment]
> I'm having this issue too. My setup is much simpler:
> 
> * ubuntu 20.04.5 x64
> * various transmission nightly (latest being rad125edea9 from 9/9)
> * one directory, file names appended with .part until complete
> 
> I now systematically "verify local data" every day and 1 out of 30 torrents misses one piece.
> 
> What can I do to help figure this out ?

I've been updating the nightlies too since it seems like there just won't be a release from TM fixing this. It's slightly better than it was but definitely still occurring. Very frustrating, I am not sure if it's related to the file moving or not but I wish I could at least configure it to verify data on download and move completion or something.

**Comment by diligiant** [comment]
@nvanfleet I'm not moving anything so I guess not.

**Comment by wedsa5** [comment]
I am having a similar issue related to downloading torrents with multipart .rar files. Many of them remain as corrupted .part files after Transmission says that it is 100% done. Re-verifying doesn't seem to fix the issue, and often completely deleting the torrent and re-downloading doesn't solve the problem either.

See comment on other thread:
https://github.com/transmission/transmission/issues/3700#issuecomment-1250354983

**Comment by stevenengler** [comment]
I'm also noticing corrupt torrent downloads with 1bba2a8c6. If I "verify local data", transmission will redownload the correct chunks. My setup is pretty normal: running transmission in docker, writing to an external USB disk (SMART doesn't report any drive errors, and drive is less than a year old). Unlike the original post, I notice it with smaller files as well.

This seems to be a long-standing issue in transmission (ex: #393), so it would be nice if transmission gave us an option to always verify local data when the download completes.

**Comment by GaryElshaw** [comment]
I don't know if it helps, but i stopped seeing this after having more space on the drive i use.

**Comment by stevenengler** [comment]
> I don't know if it helps, but i stopped seeing this after having more space on the drive i use.

I have ~2 TB available (50% of the drive). Maybe your drive has some bad sectors? Does a SMART check show any errors?

Does anyone know if transmission is skipping a chunk, or if it downloaded the wrong chunk? If transmission is downloading the wrong chunk and not verifying it, then it sounds like it would be a security issue.

**Comment by GaryElshaw** [comment]
No, the drive is and was fine, i just found that the larger the empty capacity, the less i would see the corruption issue.

So far as i now, Transmission should *not* be skipping chunks. Are you using one of the latest nightly's Steven?

**Comment by stevenengler** [comment]
> So far as i now, Transmission should not be skipping chunks. Are you using one of the latest nightly's Steven?

I've been building from the main branch, most recently 1bba2a8 (about 20 days old; I should probably re-build again soon).

**Comment by GaryElshaw** [comment]
I really recommend doing that. I think beta is in the next week or so, but i think if you have any concerns, keep any kind of logging of errors you can find and post them as issues.

I have a crash on quit i've posted, this movable feast will continue for a while.

**Comment by stevenengler** [comment]
FWIW, I did a binary diff of some of the corrupted vs original/correct files, and some of the corrupted files had extra header fields included that were not part of the original/correct files. I'm not sure where these header fields came from, and they were also not part of any of the other files in the same torrent. I don't really know much about bittorrent, but my only current guess is that the seeder modified their files locally and added these additional headers, their torrent client continued to seed them without checking them, and then transmission downloaded some of their chunks without checking them, leading to corrupt/unsafe files.

**Comment by ckerr** [comment]
This is a duplicate of https://github.com/transmission/transmission/issues/4621.

Bug report etiquette is to close the newer ones as duplicates of the older ones, but @hauuau had such a great writeup in 4621 for how to repro the issue consistently that I'm leaving that one open and closing this one as the dupe.
