### ISSUE TITLE
[Manjaro Gnome] Transmission 3.0 fails during configure

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3436]
I thought i'd take a look to see how release and nightly builds compare with the change in assets we're now using (png to svg). Unfortunately it seems to break at the configure stage.

```
CMake Error at libtransmission/CMakeLists.txt:312 (add_executable):
  Cannot find source file:

    subprocess-test.cmd

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at libtransmission/CMakeLists.txt:312 (add_executable):
```

**Comment by ckerr** [comment]
Hmm, haven't seen that one before.

```txt
add_custom_command(
    TARGET libtransmission-test
    PRE_BUILD
    COMMAND
        ${CMAKE_COMMAND} -E copy_if_different
            ${CMAKE_CURRENT_SOURCE_DIR}/subprocess-test-script.cmd
            $<TARGET_FILE_DIR:libtransmission-test>/subprocess-test.cmd)
```

looks OK to me... :thinking: 

Could you attach a log of how you checked out transmission and ran cmake?

**Comment by GaryElshaw** [comment]
I downloaded via the website https://github.com/transmission/transmission-releases/raw/master/transmission-3.00.tar.xz

I then just extracted from the archive, cd, and cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

**Comment by ckerr** [comment]
Just to confirm, did you also `mkdir build && cd build`?

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #1138, #1248, #1279, #1408.

**Comment by GaryElshaw** [comment]
Just to confirm, i've filed a duplicate of a configure bug that exists in the release code and hasn't been resolved since 2020?
