### ISSUE TITLE
cmake failure

### ISSUE THREAD

**Issue by Phoveran** [transmission/transmission#3439]
![image](https://user-images.githubusercontent.com/38107945/178554911-f8ae212b-6ebd-4a74-ac7c-41798c46cd4c.png)

transmission version: 3.00
cmake version: 3.13

**Comment by nevack** [comment]
Have you synced git submodules?

**Comment by mikedld** [comment]
In case you downloaded the tarball using GitHub's "Download ZIP" button, that won't work (see #2746). Try with the one in the release: https://github.com/transmission/transmission/releases/download/3.00/transmission-3.00.tar.xz

**Comment by Phoveran** [comment]
I'm using the tarball from release. However when I build from git I succeeded.

> In case you downloaded the tarball using GitHub's "Download ZIP" button, that won't work (see [#2746 (comment)](https://github.com/transmission/transmission/discussions/2746#discussioncomment-2325301)). Try with the one in the release: https://github.com/transmission/transmission/releases/download/3.00/transmission-3.00.tar.xz
