### ISSUE TITLE
transmission 4 can't handle torrents with nonstandard filename encoding.

### ISSUE THREAD

**Issue by InsaneKnight** [transmission/transmission#3442]
The Bittorrent specification says all filename in a torrent file should be encoded in UTF-8, but some old software, especially those running on M$ Windows, might generate torrent files containing filenames encoded in another way, e.g. GB2312 (which is also a superset of ASCII).

Older transmission program (e.g. 3.00) can guess how these nonstandard filenames are encoded, and convert them according to the current locale settings (in $LANG) when storing corresponding files.

However, the main branch of transmission can no longer do this, instead it will store corresponding files directly under names recorded in the torrent as is, regardless they may be neither fit the current locale settings nor standard, leaving gibberish names in the filesystem.

From bad to worse, when running into an existing share created from a torrent file containing nonstandard filename encoding by an old version of transmission, the main branch will consider existing files whose name has been converted upon creation as non-existing, and consider this share as damaged.

For example,  https://dl.dmhy.org/2015/07/11/5fd3691585911a9be4c84e8e08b68ed01752284d.torrent is a torrent file created with BitComet 0.63, containing 11 files, with the last two whose name are encoded in GB2312. `transmission-show` of transmission 3.00 can show the content of this torrent file, with all filename converted according to the current locale settings (note that valid CJKV fonts may be needed to see the correct names), but `transmission-show` from main branch cannot, and the gibberish output can be guessed as GB2312 with the tool `enca`. If a share is created with this nonstandard torrent by the main branch, the last two files will have gibberish names. If a share is created with this nonstandard torrent by transmission 3.00, finished downloading, and then handled with main branch, the last two files will be considered absent within the share, and main branch will say the share is damaged and ask for redownloading.

**Comment by Lanzaa** [comment]
I can confirm what you are seeing, so it is a regression. I took a quick look. It seems that torrent file is rather non-standard.

I will see if I can make a fix.

**Comment by Lanzaa** [comment]
The issue was that support for bitcomet's non-standard path.utf-8 was dropped during the rewrite to speed up torrent file parsing.

I have a pull request open to add back support.

**Comment by InsaneKnight** [comment]
@Lanzaa
I managed to create a torrent file containing non-standard filename encodings with BitComet 0.63 on a virtual machine running win2k, packaged with 3 files to share created out of `/dev/urandom` : [test.tgz](https://github.com/transmission/transmission/files/9125327/test.tgz) , which MAY have the same result as the original one.

This may satisfy @ckerr, and the initial comment of this issue is updated with this new test torrent in the public domain.

**Comment by abubaca4** [comment]
Made some tests
transmission-daemon 88556bd859 in debian 11
With ntfs partition and ntfs3 driver has error Invalid argument as in #4871
When replaced to btrfs partition has no issue with download and save in disk with correct name. But still displayed in web gui as ????
In windows with 4.0.1 download normal but on drive file name incorrect
![изображение](https://user-images.githubusercontent.com/55701175/221414701-5429f5a2-73e2-45c8-856d-e1e4dce1ad21.png)
Tested in this [files](https://github.com/transmission/transmission/files/10833842/test.files.zip)

torrent file from [start of issue](https://github.com/transmission/transmission/issues/3442#issue-1303030566) in debian 11 88556bd859 with btrfs give error Permission denied, not Invalid argument 

I hope #3454 not solve only for GB2312 but for other locales also

**Comment by ckerr** [comment]
User banned due to piracy. I'm leaving the issue open since the banned user was not the person reporting the bug.

**Comment by asacha-ru** [comment]
This regression is a show-stopper for some non-English speaking users.
What can we do to finalize  #3454 and merge it ?

**Comment by ckerr** [comment]
@asacha-ru thanks for bumping this one. Last time I looked at it IIRC it was failing CI on BSD, but that no longer seems to be the case. The code looks reasonable and adds tests.
