### ISSUE TITLE
[macOS] Bug UI

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3445]
- macOS v.12.4 (21F79)
- Transmission v.3.00+39d442b3ee

In order to reproduce this error, a certain sequence of actions is required!

https://user-images.githubusercontent.com/62497891/178988214-6c6692b9-57c0-49b4-947f-325ecac4c7b9.mp4

**Comment by robd003** [comment]
> In order to reproduce this error, a certain sequence of actions is required!

What actions are required to reproduce the UI bug?

**Comment by Oleg-Chashko** [comment]
Bug, Apple SDK, won't fix.

1. Achieved the same bug on another application.
2. It all depends on where the cursor is at the time of the bug.
3. The cursor at the moment of an error must be on the border between switching, stretching the window or moving it. If the circumstances are unfortunate, a bug occurs. The window immediately shifts and stretches, which can be seen in the video recording. We cannot fix this.

I hope you know what I mean.
