### ISSUE TITLE
GTK nightly: Upload rate doesn't appear in main window

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3448]
The below is 3.00+ (2bcab6be7e), but i have noticed the same bug in previous nightlies.

![Screenshot from 2022-07-15 14-41-19](https://user-images.githubusercontent.com/69029666/179137570-47f46399-b723-4ed9-af55-46b81eb612e3.png)

**Comment by mikedld** [comment]
Shows up for me, might be an averaging effect where it's counted as 0 (which hides the label) when there're not enough samples yet.

**Comment by GaryElshaw** [comment]
That zero is static and does not change.
