### ISSUE TITLE
GTK client and Super+3

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3449]
This might be my ignorance, so please feel free to immediately close. But is this modal normal when super+3 are hit? This is 3.00+ (2bcab6be7e).

![Screenshot from 2022-07-15 14-42-47](https://user-images.githubusercontent.com/69029666/179138422-84b5319e-cfc0-4135-9936-abdf6a4be718.png)

**Comment by mikedld** [comment]
There's a built-in search functionality in GTK listboxes and treeviews which results in this popup entry being shown when any printable character is typed when the widget is focused. You can see the same behavior in e.g. Thunar and other apps. It appears to be working and in fact moving selection to the matching torrent.
