### ISSUE TITLE
[3.00] Time remaining becomes negative

### ISSUE THREAD

**Issue by conartist6** [transmission/transmission#3451]
It's a subtle bug -- relatively hard to see because the format of the text is `0 of 3.14 GB (0%) - 22 years remaining` which looks very similar to `0 of 3.14 GB (0%) - -22 years remaining` (negative 22 years remaining). It's hard to capture a screenshot since it tends to toggle back and forth between positive and negative numbers of years, and eventually settles on "remaining time unknown".

Version: 3.00 (f4489c982e) for OSX

**Comment by Coeur** [comment]
Version 3.00 was more than two years ago. Can you reproduce with latest nightly 4.0 build?

**Comment by Coeur** [comment]
Reproduced. Time was at 58 years, then became -48 years, then unknown.
