### ISSUE TITLE
Please add that C# client dll to your wiki

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#3453]
https://www.nuget.org/packages/Transmission.API.RPC

**Comment by ckerr** [comment]
@Petrprogs the wiki's been migrated to the `transmission/transmission` repo in the docs/ directory so that you can make a PR to do this

**Comment by Petrprogs** [comment]
OK, I created a PR

**Comment by ckerr** [comment]
Fixed by #3456
