### ISSUE TITLE
Change default maximum number of upload slots per torrent to something like 4 instead of 14? 

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#3459]
This is related to https://github.com/transmission/transmission/issues/683 where we should expose the maximum number of upload slots per torrent to the user via the GUI instead of just the settings.json

Currently, the default https://github.com/transmission/transmission/blob/main/docs/Editing-Configuration-Files.md uses a number of 

` "upload-slots-per-torrent": 14,`

This is quite excessive for most users and most of them will never know that each torrent they are seeding has exactly 14 upload slots by default until they go check the settings.json file, which most people, to be realistic, will never examine. 

Therefore, it makes sense to keep this number in the single digits at least by default because the less slots, the faster a user's torrent will upload to the swarm. Imagine seeding at say 500 kB/s and your torrent is going to 14 users at 35 kB/s instead of 4 users at 125 kB/s. This makes a massive difference to a big swarm as swarm participants are more likely to get more data (and thus are more likely to get to 100% faster) from Transmission users within a given seeding time.  If you are actively seeding 2 torrents at 500 kB/s, then you are now uploading to 28 users at a measly 17 kB/s under the current default maximum number of slots per torrent. If you ask me, this makes people view Transmission as a "slow seeding" client because most people don't know how to change this setting...

This is up to the community, but I think the default maximum number of upload slots per torrent should be 4 instead of 14. 

I'm not really sure why it is 14 in the first place...

I am currently starting a discussion the community can participate in deciding on better default connection settings for Transmission with today's modern connections here: https://github.com/transmission/transmission/discussions/3460

**Comment by ckerr** [comment]
I don't recall where the 14 number came from. Maybe 8?

**Comment by Pentaphon** [comment]
> I don't recall where the 14 number came from. Maybe 8?

Anything from 4 to 8 would be fine by me. I prefer 4, but if you would be more willing to change the default value to 8, it would still be a massive improvement over the current value of 14.

**Comment by ckerr** [comment]
> Think we can have this change happen before 4.0 beta?

If you want to PR a change to 8 I'd be fine with that :+1:

**Comment by Pentaphon** [comment]
> If you want to PR a change to 8 I'd be fine with that 👍

I don't have the skills to make that happen so please put a "PR welcome" label on my issue, thanks. 

https://github.com/transmission/transmission/issues/3459

**Comment by ckerr** [comment]
It's currently a hardcoded magic number in session.cc. I keep meaning to refactor Settings but for now this is where the change would be made:

`tr_variantDictAddInt(d, TR_KEY_upload_slots_per_torrent, 14);`

**Comment by GaryElshaw** [comment]
*Shakes 14 - 8 magic 8-ball* "Success is assured".

**Comment by Pentaphon** [comment]
Thank you so much for getting this done so quickly, Gary. This will be really help Transmission improve swarm health overall.
