### ISSUE TITLE
[feature-request] Add support for clicking on magnet: links for the Web Interface

### ISSUE THREAD

**Issue by itsnotlupus** [transmission/transmission#346]
I primarily use the web interface to manage my torrents. Right now, that means that whenever I see a torrent I'm interested in, I need to right click on the link, select "Copy Link Address", then open a tab to the Transmission Web Interface, click on the "open" icon, and paste the URL in the dialog that pops up.

That's entire seconds of my life I'm never getting back. Per torrent.

Modern browsers let pages define custom handlers for URIs, which means it's completely possible to have the Web Interface expose a little button somewhere to register a "magnet:" URI handler. The payload itself would look (very roughly) like:
```
    navigator.registerProtocolHandler("magnet", location.protocol+"//"+
        location.host+"/transmission/web/?uri=%s", "Transmission Magnet Handler");
```

Then, all that's missing is some code to parse the query string, open and populate the dialog with the URI if one is present. Something like:

```
    // parse it like I care
    var magnetURL = decodeURIComponent(location.search.substr(5));
    if (magnetURL.startsWith("magnet:")) {
        $('#toolbar-open').click();
        $('#torrent_upload_url').val(magnetURL);
        $('#add-dialog-folder-input').focus();
    }
```
(query string parsing code may benefit from using parseUri() method instead of being super optimistic.)

That's it. With those two pieces of code running, the Web Interface becomes 43% more useful, and clicking on torrent links anywhere on the web will happily bring them into the Web UI, where a delighted user just needs to pick a path and start the transfer.

**Comment by mikedld** [comment]
See #223, you seem to have the same opinion as @grantrules there.

**Comment by itsnotlupus** [comment]
Oh neat. It's already almost a thing!  

Since this hasn't moved much since March, and the code there looks more real than mine (which is really just a tampermonkey script I had just whipped up), would it be okay if I grabbed @hvmp's branch and tweaked it slightly to have the popup show by default, and maybe add a setting to make the popup optional?

**Comment by mikedld** [comment]
Fine by me. Re. setting, I'm thinking saving it as a cookie (i.e. UI-specific) would be better than introducing a core setting.

**Comment by itsnotlupus** [comment]
Ok, I took a stab at it at #349.

Various guesses were made as to the best coding style/patterns to follow.  
Hopefully I'm not too far off, but let me know on the PR and I'll tweak things as needed.
