### ISSUE TITLE
[MacOS 3.00+] Pieces failing checksum

### ISSUE THREAD

**Issue by s12chung** [transmission/transmission#3463]
Been struggling to complete this torrent: magnet:?xt=urn:btih:c84c6ed92d2f7bfd4b04f8aa9348148758fbe7fb&dn=Luck-Key%20%282016%29%20%5B1080p%5D%20%5BBluRay%5D%20%5B5.1%5D%20%5BYTS.MX%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=http%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce

Due to failing checksum. Logs attached here: [logs.txt](https://github.com/transmission/transmission/files/9129136/logs.txt).

Version is from recent commit: https://github.com/transmission/transmission/commit/fe91f0435158640afeb24974062dba92fa2c0516

I updated today from a version from about 3 months ago because it was struggling then too. Didn't look at the logs then.

**Comment by nevack** [comment]
Looks like this torrent content is not in public domain.
CC @ckerr

**Comment by ckerr** [comment]
@s12chung the Transmission project can't provide technical support for non-public-domain torrents.
