### ISSUE TITLE
Transmission AutoAdd

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#3466]
Hello again, can I offer you my creation for transmission :) I recently made a [program ](https://github.com/Petrprogs/transmission_autoadd) to automatically add torrents from the Downloads folder. Please take a look.

**Comment by ckerr** [comment]
Hey, this is kind of cool! Thanks for writing this.

I'm not sure what the goal for this issue is though? If it's just as a heads-up, then :+1: this looks cool.

**Comment by Petrprogs** [comment]
Thank you for your kind words. If you like it, post a link to my repository on your site, please :)
