### ISSUE TITLE
[macOS] UI-Preferences -> Remote, Spanish and Italian localizations, v.3.00+ffe307ac1b

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3476]
<img width="677" alt="SPANISH" src="https://user-images.githubusercontent.com/62497891/179747310-27bf2eee-7f11-4a78-8657-e242200d1f92.png">
<img width="637" alt="ITALIAN" src="https://user-images.githubusercontent.com/62497891/179747326-92b199e4-0344-4a0b-afd9-6e521aa2cc02.png">

**Comment by ckerr** [comment]
Fixed by #3472
