### ISSUE TITLE
[macOS] French localization, There must be a space before the colon

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3477]
French, there must be a space before the colon.

There is always a space before "?" | "!" | ":" | ";"

[La ponctuation et la typographie](https://leconjugueur.lefigaro.fr/frponctuationtypographie.php)

---

<img width="656" alt="FR_1" src="https://user-images.githubusercontent.com/62497891/179753240-997179c8-1868-48b8-8efd-4a9355312837.png">
<img width="674" alt="FR_2" src="https://user-images.githubusercontent.com/62497891/179753252-641ef174-8817-4836-8e20-ec1f979ad8e5.png">
<img width="674" alt="FR_3" src="https://user-images.githubusercontent.com/62497891/179753255-415e20ee-00d9-4f66-ac82-fe6291387665.png">

**Comment by ckerr** [comment]
Is this an issue to be reported here, or should this be handled in Transifex?

In general, i18n shouldon't go in this issue tracker since most issues, e.g. misspellings or incorrect grammar, will be resolved in Transifex and not in `electron/electron`. The exception to this would be if there is something wrong at the code level, e.g. code that makes assumptions about layout / dimensions and those assumptions fail in some translations

**Comment by killemov** [comment]
I don't know if the (semi)colons are part of the translated strings or are added when rendered. In the latter case it could be solved by adding a space at the end. I didn't even know french has this particular rule. It was never taught when I took french in high-school.

**Comment by sweetppro** [comment]
The localised strings are in the <xib>.strings file. It’s very trivial to change

**Comment by ckerr** [comment]
@sweetppro my point is that look at commits like 39d442b3ee6af17d05bb544a1368ecdff910d0bd; these are fixed on Transifex and then all the .strings files here in `transmission/transmission` are overwritten with whatever changes have been added upstream in Transifex. 

So if someone opened a PR here adding the spaces and I or @mikedld merged it, that fix would get overwirtten if the fix wasn't  also in Transifex. Text translation errors need to be fixed there.

**Comment by mikedld** [comment]
While I'm working on it, could someone please go through the base XIBs and make sure they don't contains titles that shouldn't be translated, to reduce questions. I don't want strings like these to be exported/translated:
* https://github.com/transmission/transmission/blob/6900ece01dd2dced3333f9e00e5046f86d2b05ff/macosx/es.lproj/AddMagnetWindow.strings#L2-L3
* https://github.com/transmission/transmission/blob/6900ece01dd2dced3333f9e00e5046f86d2b05ff/macosx/es.lproj/AddMagnetWindow.strings#L26-L27

**Comment by ckerr** [comment]
@transmission/contributors ^ could someone volunteer to do that? :slightly_smiling_face:

**Comment by mikedld** [comment]
Did it myself...

**Comment by mikedld** [comment]
Translations synced in #3519.

**Comment by ckerr** [comment]
OK it does look like this is something that's fixable via Transifex rather than here, so I'm going to close this issue.
