### ISSUE TITLE
Transmission Doesn't Open Ports Correctly Using UPNP - Linux Mint

### ISSUE THREAD

**Issue by RoyiAvital** [transmission/transmission#348]
Hello,
I just installed clean Linux Mint (18.2) and updated all updates (27/07/2017).

I run Transmission and there are issues with port forwarding.  
One could see my post on Ask Ubuntu - [Skype Bypass UFW While Transmission Can't Even Open Port](https://askubuntu.com/questions/940475/skype-bypass-ufw-while-transmission-cant-even-open-port).

I checked with qBitTorrent on the same computer and the port is properly opened.
It seems to be some kind of a bug of the UPNP in Transmission.

Thank You.

**Comment by mikedld** [comment]
I've updated miniupnpc library yesterday. It would be nice if you could build current master and try it out. Instructions for building from source are there in [README.md](/transmission/transmission/blob/master/README.md).

On a side note, Transmission's "test port" functionality isn't particularly reliable, so you might want to use another service like http://canyouseeme.org/ to double-check first.

**Comment by RoyiAvital** [comment]
Hi,
When do you think it will be pushed to Linux Mint's packages?
