### ISSUE TITLE
[v3 to 49b0df8] transmission-qt: always 'invalid or corrupt torrent file'

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3482]
When I Slackware64 15 GNU/Linux (stable & current both up-to-date) transmission 3 & git download .torrents/magnets (for months and updated today) it says 'invalid or corrupt torrent file' even computer science expert ones such as magnet:?xt=urn:btih:8dadac67070daa13cf4c51b38946cf06b33d14b0&dn=FreeBSD-13.1-RELEASE-arm-armv6-RPI-B.img.xz .  Sometimes works to reload .torrent or use magnet to torrent converter but lately often doesn't convert.

**Comment by ckerr** [comment]
I'm having a little trouble reading this bug report. What version of Transmission are you using?

**Comment by dchmelik** [comment]
The type of problem started with v3 and got worse in commits last few days which I use what's current at time of post (you could've checked yesterday): currently 3.00+ (c50da43ae0) has same problem.

**Comment by ckerr** [comment]
> The type of problem started with v3 and got worse last several commits

What exactly does this mean that it got worse? You're seeing the error more often, or what?

Are you saying that when you try to add `magnet:?xt=urn:btih:8dadac67070daa13cf4c51b38946cf06b33d14b0&dn=FreeBSD-13.1-RELEASE-arm-armv6-RPI-B.img.xz` by URl in transmission-qt you see the error message "invalid or corrupt torrent file"?

**Comment by ckerr** [comment]
> you could've checked yesterday

I could've checked _what_ yesterday? I'm trying to understand this bug report but I feel like we're speaking past each other

**Comment by dchmelik** [comment]
>What exactly does this mean that it got worse? You're seeing the error more often, or what?

Used to happen to all .torrents and now also all magnets.

>Are you saying that when you try to add magnet:?xt=urn:btih:8dadac67070daa13cf4c51b38946cf06b33d14b0&dn=FreeBSD-13.1-RELEASE-arm-armv6-RPI-B.img.xz by URl in transmission-qt you see the error message "invalid or corrupt torrent file"?

Yes.  Just transmission-qt though (not GTK).

**Comment by orbital-mango** [comment]
When you open the dialog it's parsing the magnet link and only pasting the the Display Name from the link i.e. FreeBSD-13.1-RELEASE-arm-armv6-RPI-B.img.xz and that results in the invalid or corrupt torrent file error.

If you paste the contents of your clipboard (the whole shebang `magnet:?xt=urn:btih:8dadac67070daa13cf4c51b38946cf06b33d14b0&dn=FreeBSD-13.1-RELEASE-arm-armv6-RPI-B.img.xz`) into the text field over the stripped name then it'll start the torrent correctly.

It seems this was introduced by [this](https://github.com/transmission/transmission/pull/2709) inadvertently treating all magnet links as duplicates and just using the DN.

**Comment by ckerr** [comment]
> It seems this was introduced by this inadvertently treating all magnet links as duplicates and just using the DN.

Maybe I'm misreading this, so I wanted to confirm -- are you saying that if you already have a magnet link that hasn't been converted to a full .torrent yet, you can't add a second magnet link in transmission-qt due to that commit?

**Comment by orbital-mango** [comment]
When you attempt to add a magnet link that hasn't been added ever before whether as a .torrent file or magnet link, the above seems to format the entry pasted (automatically when opening the dialog) into the source textbox using the display name rather than the raw magnet link. This then fails as invalid or corrupt torrent file... Understandbly as there is no torrent file as yet.

I probably am not explaining this too well :)

**Comment by ckerr** [comment]
Fixed by #3787.
