### ISSUE TITLE
transmission-3.00+-rf8b3514c0e does not show icon in start menu on Windows 10 64 bit. 

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#3483]
I did a clean install of the latest nightly transmission-3.00+-rf8b3514c0e on Windows 10 x64 and it seems there's no application icon in the start menu as you can see below. 

![icon](https://user-images.githubusercontent.com/49374058/179910895-512ec6ea-e882-4ba4-9e6c-fecac8666122.png)

It does show up on the control panel's add/remove list, however. 

![control](https://user-images.githubusercontent.com/49374058/179911124-0b39be0b-736e-428d-ac8b-d2caa8bdb246.png)

@mikedld this might make the beta look bad when it comes out. 

@ckerr this might be a good first issue for somebody new to get out of the way before the beta?

**Comment by nevack** [comment]
Maybe packaging issue?

**Comment by Pentaphon** [comment]
> Maybe packaging issue?
> 
> btw, if you run app, is there icon in Taskbar?

This is odd but I just installed the latest nightly with a clean install to verify what you asked and now the icon shows up in the start menu. Not sure what changed, if anything. I guess I'll close this since it works now.
