### ISSUE TITLE
[macOS] UI-Torrent Inspector, Improvement of the Activity tab

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3489]
- At the moment:
<img width="1352" alt="3  At the moment" src="https://user-images.githubusercontent.com/62497891/180010250-578af757-4d70-4a1d-ba8a-0ea4338f4f77.png">

- Example - It is desirable:

<img width="715" alt="3  Example - It is desirable" src="https://user-images.githubusercontent.com/62497891/180010382-79fb69d8-893c-4120-bd6e-3cace9f415aa.png">

- Make the size a little bigger, there is free space for that:

![noname](https://user-images.githubusercontent.com/62497891/180010905-95ae9449-1e74-4ea3-afc5-b3b9ac2c526a.png)

**Comment by sweetppro** [comment]
I don't think it makes sense to have the progress matrix next to the time (Date/TIme elapsed) section

**Comment by Oleg-Chashko** [comment]
> I don't think it makes sense to have the progress matrix next to the time (Date/TIme elapsed) section

Do what you like best. The idea was just to remove the empty space and restore the distance between the buttons and the lines of text.

<img width="1352" alt="180010250-578af757-4d70-4a1d-ba8a-0ea4338f4f77" src="https://user-images.githubusercontent.com/62497891/180717301-7930ac83-b919-4c67-a567-a57b7ef61811.png">

Example:

<img width="1352" alt="180010250-578af757-4d70-4a1d-ba8a-0ea4338f4f77" src="https://user-images.githubusercontent.com/62497891/180718148-28a50402-a1f5-4b13-96c1-ec1ff249017f.png">

**Comment by Oleg-Chashko** [comment]
And if you switch places. Maybe that would suit you better?

Example:

<img width="715" alt="180010382-79fb69d8-893c-4120-bd6e-3cace9f415aa" src="https://user-images.githubusercontent.com/62497891/180720987-56c2c4bc-f51b-4968-b7ca-0391519cc754.png">

**Comment by sweetppro** [comment]
@Oleg-Chashko Ive addresses the margins in the following PR #3522, but im still not sold on rearranging the Activity tab... Personally I think it would look unbalanced when in vertical layout:
<img width="427" alt="activity proposal" src="https://user-images.githubusercontent.com/7323792/180722970-ade6bc46-9866-4f87-bda7-88ae6512e68d.png">

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko Ive addressed the margins in the following PR #3522, but im still not sold on rearranging the Activity tab... Personally I think it would look unbalanced when in vertical layout:
> <img alt="activity proposal" width="427" src="https://user-images.githubusercontent.com/7323792/180722970-ade6bc46-9866-4f87-bda7-88ae6512e68d.png">

Yes, I agree with you! 
Also, I don't understand why vertical mode is needed? 

P.S.: After all, the main application window sprawled horizontally with meaningless empty space.
After that, I don't really care what the final design of the app will be.
