### ISSUE TITLE
macOS toolbar icons are inconsistent sizes

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3498]
It has been like this for a long time, but i was wondering whether we could look at this before beta.

I get the thinking with having different sized icons between what are universal controls and, i guess, 'other', but it also doesn't make much sense to do this in the toolbar when, i think, the correct way to do this would be identical icon sizes, but the universal controls use, as they currently do, the fill icons.

Theoretically we could debate what is a universal control versus localised, but who has time for that, right? Or wrong?

![SCR-20220721-ras](https://user-images.githubusercontent.com/69029666/180158814-ba85209c-8ef3-436c-9671-86ec046c5cf2.png)

**Comment by nevack** [comment]
What is "universal control"?

**Comment by GaryElshaw** [comment]
Any button that effects all of a users torrents.

**Comment by nevack** [comment]
Ah, okay.
Another question: do you mean this circled icons for "pause/resume all" are larger than the ones for other items?
It's not very clear for me just by looking at the provided screenshot, sorry :(

**Comment by GaryElshaw** [comment]
No worries, my eyes aren't good either :-) Yes, we're using fill icons for the 'pause/resume all' functions, which is cool, but the other icons are also smaller. It'd be great if the icons were all the larger size - also helping our eyes.

On that topic of eyes, i'm going to look at this again now that auto-layout changes have opened the possibility. #1676

**Comment by nevack** [comment]
As far as I can tell, this is only the issue with `Icon and Text` toolbar mode.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/8330119/180360345-e86e1b57-a6eb-4c22-b7c9-a2baf071d971.png">

**Comment by GaryElshaw** [comment]
Interesting!
