### ISSUE TITLE
[macOS] Downloaded files extremely slow to delete in nightly

### ISSUE THREAD

**Issue by tozz** [transmission/transmission#3499]
Using macOS 12.4 and 12.5, both M1 and Intel systems with build e9a7ddf7f9 and later (don't know about earlier builds).

I've noticed that downloaded files are very very slow to delete, not moving to trash but emptying it or skipping trash completely. Same thing using `rm` on the CLI. I've seen this behaviour both on internal SSD and an external one. Removing a 3GiB file takes 20 seconds. Opening the file is instant however. If I copy the file to another volume, removing it is instant on that volume.

This behaviour is only exhibited on files downloaded with Transmission, files downloaded in Safari or any other software does not have this issue.

I understand this might not be the best of issues describing how to reproduce it, but I don't know how the gather the relevant data, I've looked in the OS logs for any errors around the file system but it turns up empty.

**Comment by GaryElshaw** [comment]
That's really weird, if i understand correctly? Moving to the trash is instantaneous (normal), but emptying the trash with a file downloaded by Transmission, takes longer (abnormal)?

**Comment by tozz** [comment]
@GaryElshaw That is correct. I first thought it was emptying the trash that had a hiccup but I rebooted and it was just as slow. So then I tried using `rm` and that showed the exact same behaviour.

**Comment by GaryElshaw** [comment]
The only thing i can think of that comes to mind is something to do with how permissions might be being set. Transmission, so far as i know, doesn't treat files in any way differently than regular files. Any chance your Transmission download directory has different parameters than other download directories?

**Comment by ckerr** [comment]
> This behaviour is only exhibited on files downloaded with Transmission, files downloaded in Safari or any other software does not have this issue.

One difference is that BitTorrent downloads its contents opportunistically, e.g. if there are pieces that are scarcer in the swarm (fewer peers have that piece) then Transmission will try to snag that first to improve the health of the swarm. The contents of the file are saved in nearly random order, which can cause fragmentation if you're not preallocating the file. Safari et al (I think) download files in order from beginning to end.

_If_ this is the issue then TBH it's generally best to not worry about it. There's no One Correct Answer to preventing fragmentation and most of the alternatives have other tradeoffs that can cause headaches. If it _really_ bothers you, you can try altering the preallocation settings or turning on APFS defragmentation.
