### ISSUE TITLE
Unable to Change File Locations When Symbolically Linked

### ISSUE THREAD

**Issue by NoSuck** [transmission/transmission#35]
Hello.  I use Transmission 2.92-5 on x86_64 GNU/Linux (4.6.4-1-ARCH).  I have considered other BitTorrent clients, but the simplicity and stability of Transmission leaves little to be desired.  It has all the functionality I need.  Thank you.

If I set a torrent's download location to somewhere within a symbolically linked directory and later try to move the torrent's location to the link's target, Transmission refuses to change the download location.  Stopping the torrent, deleting the link, and then changing the download location to the link's target works around this.

The file system is ZFS, and the symbolic link is relative.

**Comment by mikedld** [comment]
What exactly does "refuses to change the download location" mean? Specifically, are there any errors in the log, or are you getting some GUI dialog with the message, or both? Which flavor of Transmission are you using (GTK+ / Qt / daemon)? How are you executing the actions mentioned (via the native GUI / web UI / transmission-remote)? Where in the path does the symbolic link appear: is it the source or destination directory itself which is a link, or is it some parent directory thereof? Feel free to demonstrate what you're doing with some sample paths ;)

**Comment by mikedld** [comment]
@NoSuck, I believe this is by design. Transmission checks whether source and destinatioin point to the same file or directory and ignore the request. Might still be a good idea to change the internal path Transmission uses to access the data in this case.
