### ISSUE TITLE
[Feature] Limiting upload

### ISSUE THREAD

**Issue by guglovich** [transmission/transmission#3505]
Please put a limit on the number of giveaways you can give away. This feature will help limit people who download too many uploads at once and take up the entire internet channel in one person.

**Comment by ckerr** [comment]
Transmission already lets you set limits on the number of peers and on transfer speed

**Comment by guglovich** [comment]
> Transmission already lets you set limits on the number of peers and on transfer speed

That's a bit off, it doesn't solve the problem against one person downloading all your handouts.

**Comment by guglovich** [comment]
Or you could make a setting with a speed limit per pir/person/IP. This will also solve the problem.
