### ISSUE TITLE
[Transmission 3.00+ (c50da43ae0)] moves all torrent locations to /home/user

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3508]
Changes all torrent data (not .torrent but the data they describe) locations that were /home/user sub-directories/-folders into /home/user .  Over 3,000 locations were lost!  How can I restore those?  Seems data may not have been moved but all torrents started over.

I was invited to try current/development/testing version to solve one minor problem but was replaced with even worse major/critical/total breakage problem: clear it's unstable/experimental/untested in contrast to long-term/stable/user versions.

**Comment by ckerr** [comment]
Hi @dchmelik,

I haven't seen this and there are a lot of nightly build users, so I think there must be some special circumstances that trigger this bug.

- Can you help walk me through the _exact_ steps I should follow to reproduce this issue, e.g. starting from scratch with a public domain torrent?
- Are you using the macOS client, or transmission-qt on Windows, or some other binary?

**Comment by dchmelik** [comment]
On Slackware64 15.1-current (up-to-date) I cleanly exited transmission, and followed your steps 'Building Transmission from Git (first time)' and started transmission: that's all.

**Comment by ckerr** [comment]
OK so I build from the command line all the time and am not seeing this problem, so to help me understand this problem so that I can fix it, once again:

> * Can you help walk me through the exact steps I should follow to reproduce this issue, e.g. starting from scratch with a public domain torrent?

For example if I started from scratch with a fresh install of 3.00 and no torrents, and then upgraded to a nightly build, what steps do I need to do in order to reproduce this issue?

>  (noticeable because used to be set 'sort by age' but everything was sorted by name because all locations had been changed apparently in some name order).

That sounds like a different issue. If sorting is incorrect please open a different issue for that; let's keep this issue on-topic of torrents getting moved.

**Comment by dchmelik** [comment]
I gave steps. Some public domain ones I had were NetBSD 9.2 & FreeBSD 13.1 & OpenBSD 7.1 & DragonFlyBSD 6.2.2. UNIXes & Slackware 15 GNU/Linux (all x86(64)) and many public domain from the Internet Archive (archive.org) I can't find because (already-reported bug) .torrent filenames aren't human-readable anymore.

They were apparently moved in a name order so their new age is name order, which isn't a bug but made clear (to people such as me not normally sorting in name order) _everything_ was moved.

**Comment by ckerr** [comment]
OK let's say I've moved my ~/.config/transmission folder to somewhere else for safekeeping during testing and so I'm starting _absolutely from scratch_. I have both Transmission 3.00 and `main` handy to use. Walk me through **specifically** what I need to do to reproduce this bug?

**Comment by dchmelik** [comment]
Since I always continued my torrents after upgrading, I won't be able to reproduce without restoring locations.  I have some /home/user/.config/transmission/resume-2020-month-day backups from when used transmission-batch-move.  If that's where locations are I'll have to catch up a couple years.

**Comment by ckerr** [comment]
> You could try using a commit from yesterday to 3,100+ torrents then upgrade to todays commit. 

I do that literally every day

```
$ ls -1 ~/.config/transmission/torrents | wc --lines
26345
```

... OK let's take a step back. I am still having a  hard time understanding the behavior that's actually being reported. The bug report title says "moves all torrents" but then the description says "data may not have been moved." What specifically got moved? The `.torrent` files all got moved into your $HOME directory?

**Comment by dchmelik** [comment]
I edited original post to say 'all torrent _locations_' before you replied.

**Comment by ckerr** [comment]
> I edited original post to say 'all torrent locations' before you replied.

What does "all torrent locations" mean? The location of the `.torrent` file? The downloaded .iso files got moved into $HOME? Just answer the question instead of making me hunt for clues, man!

**Comment by dchmelik** [comment]
Changes all torrent locations that were /home/user sub-directories/-folders into /home/user (didn't say .torrents but where the user saves the torrent in their home folder).

**Comment by ckerr** [comment]
@dchmelik are you using transmission-daemon?

**Comment by dchmelik** [comment]
> @dchmelik are you using transmission-daemon?

I use transmission-qt and could use transmission-gtk or other standalone GUI.

**Comment by ckerr** [comment]
> I use transmission-qt and could use transmission-gtk or other standalone GUI.

I don't understand what "other standalone GUI" means.

What were you using when you encountered this in `c50da43` -- transmission-qt _only_, or a combo of (transmission-qt + transmission-daemon), or transmission-gtk?

**Comment by dchmelik** [comment]
> I don't understand what "other standalone GUI" means.
> 
> What were you using when you encountered this in `c50da43` -- transmission-qt _only_, or a combo of (transmission-qt + transmission-daemon), or transmission-gtk?

There are QT, GTK and lately similar standalone GUIs I now checked that one is transgui.  I never use GTK unless QT doesn't work (does since Slakkware 15-stable)..  I forgot what the daemon is--interface only accessible in a web browser?  I tried such a thing years ago but dislike software that must run in web browser (some might be handy for some rare situation but I avoid if at all possible).

**Comment by ckerr** [comment]
WHAT WERE YOU USING WHEN YOU ENCOUNTERED THIS IN `c40da43`

**Comment by dchmelik** [comment]
I USE TRANSMISSION-QT AND COULD USE (I.E., DIDN'T TO TEST THIS YET) OTHERS.

**Comment by ckerr** [comment]
Looks like this bug landed just a few hours ago. @dchmelik thanks for reporting it so quickly.  I think we have a hard time understanding each other here; but regardless, I really appreciate you finding this and reporting it so quickly. :heart:

**Comment by molendus1001** [comment]
Found similar problem on windows, if my computer shuts down from power loss and there was active seeding(when there is actively outbound transfer), then it sometimes tries to redownload that torrent into default download location; or does verification if given file was located in default folder.
I think* it has something to do with writing stats of how much of given torrent has been uploaded - since only torrents that were active(and had some activity) are affected by this.
I'm aware that power loss is not really considered a proper use scenario - but this happens to me often when I put my computer into sleep mode and something was seeding in background.

*From my own testing I see that files inside "%localappdata%\transmission\Resume" do contain BOTH download path AND stats in a single file. Setting them to read only works as a workaround that fixes this problem.
