### ISSUE TITLE
docs/README.md refers to dead irc channel

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#3513]

**Comment by ckerr** [comment]
I don't  understand the question

**Comment by Petrprogs** [comment]
The readme file in the docs folder has the line Visit our [IRC](https://en.wikipedia.org/wiki/IRC ) channel: [#transmission on Libera.Chat](https://irc.libera.chat/transmission ) but the link to lieber .the chat doesn't work. The purpose of the question is, is this chat still alive, if not, does it need a replacement?

**Comment by ckerr** [comment]
No, that chat isn't around anymore. That reference should be removed.

**Comment by LaserEyess** [comment]
That's not true, `#transmission` in irc.libera.chat is indeed around and is registered to the transmission project.

**Comment by Petrprogs** [comment]
> That's not true, `#transmission` in irc.libera.chat is indeed around and is registered to the transmission project.

Yeah. I found direct [link](https://web.libera.chat/transmission)
