### ISSUE TITLE
Translated text not displayed entirely (french)

### ISSUE THREAD

**Issue by nessotrin** [transmission/transmission#352]
The end of the line is missing : "Aucune donnée trouvée ! Assurez-vous que vos disques sont connectés ou utilisez « Définir l'emplacement ». Pour re-té"   ->   "lécharger à nouveau, retirez le torrent et rajoutez-le."
It's cut to the size of the standard window, but extending it or going to the details doesn't update it's length.

I didn't look into it more then that, i'm on the standard Manjaro/Arch package, It says "2.92 (14714)", with the french (FR) language.

**Comment by ckerr** [comment]
This looks like it's out-of-scope for the codebase? Translations can (and should!) be updated by volunteers at Transifex. Anyone interested in improving Transmission's i18n should go there to add better strings.
