### ISSUE TITLE
Option to force-clear resume metadata and redownload

### ISSUE THREAD

**Issue by crumpetcrusher** [transmission/transmission#354]
Error: no data found! Ensure your drives are connected or use "set location"

On Transmission 2.92

Having problems with transmission and this error above.  Requesting an improvement; add option to force clear resume metadata and begin redownloading torrent.  From RPC, or client, wherever.

Oftentimes, data started to download to an incorrect directory, or permissions on the download folder were not correct.  I have a case right now where I'm moving my transmission installation to a new NAS, and torrents started downloading even though the resume information was set to paused from the old install.  Torrents are now stuck in this "no data found!" state because they shouldn't have downloaded in the first place, and what did get downloaded is now deleted.

Cannot set to the folder where the data exists and re-verify -- nothing happens.

Thank you.

**Comment by mikedld** [comment]
> Cannot set to the folder where the data exists and re-verify -- nothing happens.

Maybe we should start with this instead, and not do that other thing you're asking for. Would be nice to get a particular example (steps to reproduce) and maybe even see the logs (with sensitive information stripped).

**Comment by crumpetcrusher** [comment]
Certainly.  It seemed like it was intended behavior so I was coming at it as a feature request -- advanced use-case, wipe resume and bring up the Add Torrent dialog again.

Reproducing on the NAS move scenario is tricky, I ended up recopying all resume/torrent files and ensuring all permissions were correct (they weren't before), which worked for 99% of the torrents.  I was able to just "move data" since the torrent was in a 100% error state and the data was not degraded.  I'll chalk this up to bad NAS move.

Three torrents that were in a Downloading state on the original NAS got moved over to the new. There was no data downloaded as there were no seeders at the time.  Moved over to the new NAS and tried to set the download location to the proper folder.  Torrents locked in a "No data found!" state. 

Since there were only three, I ended up deleting them and, luckily because I had the .torrent files still, was able to re-add them quickly.

This case below, reproducible for me every time:

2. Start to download a torrent, bad permissions on download location.
File is being downloaded but cannot be written anywhere.  Short period where file starts downloading, then download errors with Permission Denied.  

Set location to a folder with proper permissions, and reverify/restart torrent
What I'm seeing: Cannot resume this torrent again - "No data found!" 


In both cases, without having the exact data in the exact configuration the resume file is detailing, it's extremely tough to recover from the error without manually deleting/re-adding.

Please let me know what exactly I can provide in terms of log files, and I'll upload them.

Thank you.

**Comment by pataquets** [comment]
Cross linking to related issue #842

**Comment by jackun** [comment]
It boggles ones mind why this isn't an option
https://trac.transmissionbt.com/ticket/4537#comment:4

**Comment by ckerr** [comment]
I believe this is the same as #83

**Comment by dmak** [comment]
I have the same issue with Transmission v4.0.6.
Steps to reproduce:
* Start download to the directory where Transmission has no write permissions. Torrent is stopped with corresponding error [OK].
* Change target directory to one with write permissions. Torrent changes the status to "No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.". Neither "Verify", nor "Stop" + "Force start" work. Expected: "Verify" checks the target directory and restarts the download.
![image](https://github.com/user-attachments/assets/0dac6cc7-c12a-4704-b4f7-18c8a0a28356)

Hence this comment by @crumpetcrusher is valid and ticket should be re-opened.

> This case below, reproducible for me every time:
> 
>     1. Start to download a torrent, bad permissions on download location.
> 
>     2. File is being downloaded but cannot be written anywhere.  Short period where file starts downloading, then download errors with Permission Denied.
> 
>     3. Set location to a folder with proper permissions, and reverify/restart torrent
>        What I'm seeing: Cannot resume this torrent again - "No data found!"
