### ISSUE TITLE
Unix domain socket support in transmission-remote

### ISSUE THREAD

**Issue by Kobaxidze256** [transmission/transmission#3544]
If the host argument starts with /, ./ or ../ transmission-remote should try connecting to a unix domain socket at that file path. The RPC can already listen on a uds.

**Comment by LaserEyess** [comment]
This would need a new flag/arg in `transmission-remote`. Right now unix sockets implement HTTP, so in addition to a file path for the socket you have a URI. For example, given a socket `/run/var/rpc` (a valid socket filename), how do you know that's the filename when the full URL is `/run/var/rpc/transmission/rpc`? curl handles this by an explicit `--unix-socket` switch and it looks something like this:

```
curl -X POST --unix-socket /run/var/rpc http://localhost/transmission/rpc
```

The domain socket arg would be need to be set and then probably a check for making sure the hostname is localhost. As for supporting the socket itself, it's as easy as setting [this variable](https://curl.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html)

**Comment by mikedld** [comment]
I think one can do it without a new flag in a backward-compatible way by supporting e.g. `unix://` or `unix+http://` scheme alongside `http://`.

**Comment by LaserEyess** [comment]
You could do that, but then you'd have to parse the URL yourself to separate out the URI from the socket path. I think it's much less work to just do what curl does.
