### ISSUE TITLE
Fetching torrents from a web page

### ISSUE THREAD

**Issue by ffries** [transmission/transmission#356]
Dear all,

I am setting-up my local transmission to serve torrents to the Debian and FreeBSD communities. 

Feature request : it would be very nice to be able to serve several torrents or magnets, when they are linled to a single web page.

Examples:
https://wiki.freebsd.org/Torrents
https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/

As regards .torrent files, I wrote a small script relying on wget to explore the page and add any .torrent found. Wget can do the job like that:

wget -nd -r -l1 -P $my_watch -A torrent https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/
where $my_watch is the directory where you save torrents for automatic startup.

Okay, it only took 5 minutes to write a cron job to look for Debian torrents and add them using remote-cli.

Anyhow, it would probably help software developers to be able to add all theirs torrents to Transmission at once using a web page as reference. libcurl can probably do the job.

Kind regards,

**Comment by mikedld** [comment]
I don't think adding HTML parsing (or URLs regex matching) into Transmission is a good idea, and the ease of automation you demonstrated doesn't help it either. External solution like yours gives greater flexibility despite being a little bit less user-friendly.

**Comment by ffries** [comment]
I have another example:
https://www.funkthat.com/~jmg/FreeBSD-11.0-R-magnet.txt.asc

Adding each torrent by hand to support FreeBSD is a curse.
