### ISSUE TITLE
[macOS] Message Log, translations being missing

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3574]
https://user-images.githubusercontent.com/62497891/182584499-7ffba009-b421-4c36-aeb7-3e7374f30109.mp4

- **German**
<img width="717" alt="German" src="https://user-images.githubusercontent.com/62497891/183703394-11090037-0579-4ae8-b79f-442b29b67173.png">

- **Dansk**
<img width="717" alt="Dansk" src="https://user-images.githubusercontent.com/62497891/183703503-34aac9ab-57fa-48ad-9b75-f17a88b81403.png">

- **Italiano**
<img width="717" alt="Italiano" src="https://user-images.githubusercontent.com/62497891/183703586-8b5e53f8-975f-4738-b00d-b4f8aa8e572e.png">

- **Nederlands**
<img width="717" alt="Nederlands" src="https://user-images.githubusercontent.com/62497891/183703675-cd04282f-4e55-4668-8e97-65abba0c9adb.png">

**Comment by Oleg-Chashko** [comment]
- **German**
<img width="717" alt="German" src="https://user-images.githubusercontent.com/62497891/182800167-9b1fd258-da0d-4696-ae8b-223d89bd0f9f.png">

---

- **Dansk**
<img width="717" alt="Dansk" src="https://user-images.githubusercontent.com/62497891/182800288-256550e6-4642-46f6-92ce-8b2f8286671b.png">

---

- **Italiano**
<img width="717" alt="Italiano" src="https://user-images.githubusercontent.com/62497891/182800478-30565b38-741a-4e79-ac47-5049f73f10f4.png">

---

- **Nederlands**
<img width="717" alt="Nederlands" src="https://user-images.githubusercontent.com/62497891/182800642-492499f6-b3de-4af6-b632-b5ade2d2f665.png">

**Comment by GaryElshaw** [comment]
> Message.Log.mp4

That bug has come up before. @Coeur Antoine, do you remember what was causing this?

**Comment by Coeur** [comment]
Simply translations being missing.

**Comment by GaryElshaw** [comment]
> Simply translations being missing.

Thanks Antoine, i couldn't remember!

**Comment by Oleg-Chashko** [comment]
- **German**
<img width="550" alt="German" src="https://user-images.githubusercontent.com/62497891/182888055-d18bec5e-69d3-4aa8-bc16-611bffd9b9f1.png">

---

- **French**
<img width="550" alt="French" src="https://user-images.githubusercontent.com/62497891/182888263-988a3fac-ff10-4491-8109-66768533d0b2.png">

---

- **Russisch**
<img width="550" alt="Russisch" src="https://user-images.githubusercontent.com/62497891/182888381-fb6ca8fc-1d78-41e1-beea-a69fb1967270.png">

**Comment by Oleg-Chashko** [comment]
If for some reason there is no translation, default English must remain. But not the blanks.

**Comment by Coeur** [comment]
We could adopt `NSLocalizedStringWithDefaultValue` instead of `NSLocalizedString` to avoid blanks. But there are 500 occurrences of this in the code.
