### ISSUE TITLE
Duplicate app instances on Windows

### ISSUE THREAD

**Issue by rgaufman** [transmission/transmission#3588]
When I open a torrent, a magnet link or simply double tap on the Transmission app on the desktop, it launches a duplicate instance and corrupts my data. Any way to prevent this?

I'm using the latest nightly build as of 2022-08-05

**Comment by Pentaphon** [comment]
Duplicate of https://github.com/transmission/transmission/issues/255

@mikedld there seems to be a lot of issues like this with the Windows build that have remained since the first test builds. 

@ckerr this might be a blocker for 4.0.0?

**Comment by ckerr** [comment]
Closing as duplicate of #255
