### ISSUE TITLE
Unknown torrent client '-FL1481-'

### ISSUE THREAD

**Issue by stalchuk** [transmission/transmission#359]
Screenshot:
[-FL1481-](https://www.screencast.com/t/Ejbj9IrIV9)

might be Torrent Flux:
[https://sourceforge.net/projects/torrentflux/](https://sourceforge.net/projects/torrentflux/)

**Comment by mikedld** [comment]
[This](/wiperz1789/AtDown/blob/93e09c500447bbd68fbd124bd063ac8b4e1f77a3/src/connect/peermanager/utils/BTPeerIDByteDecoderDefinitions.java#L449) suggests that it could be [Folx](https://mac.eltima.com/torrent-client.html).
