### ISSUE TITLE
[868fc1a to 49b0df8] bad directory permissions

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3594]
On UNIX/GNU/Linux transmisison-gtk, for some weeks (earlier than the partial git commit hash in topi) it's been saving all directories permission 777 which is bad because sometimes users don't want their directories writable by others in their group let alone not in their group (which you're also allowing)... the standard is 755.

**Comment by maxz** [comment]
What is the value of umask in your configuration file (the location is depending on your system but e. g. found at `/var/lib/transmission/config/settings.json`)?
The default umask is 022 which leads to an effective permission of 755.

**Comment by dchmelik** [comment]
> What is the value of umask in your configuration file

I didn't change default but on my PC it's zero (perhaps because of a recent git change).

**Comment by GaryElshaw** [comment]
Transmission does not alter directory permissions. Sometimes, i wish it could.

**Comment by maxz** [comment]
> I didn't change default but on my PC it's zero (perhaps because of a recent git change).

I looked over the last few pages of commits and there is no commit message indicating such a change.

Also is the value in your configuration file `0` (the integer 0) or `"000"` (the string 000)?
In current versions it should not be `0`, unless your configuration file is write protected or something alike.
The related parts of the library are still as they should be.

It could be that something in the GUI sets its own default value, but that would be very strange.

**Comment by GaryElshaw** [comment]
@maxz @dchmelik This is not a Transmission issue, per se, but a user permissions issue. In the first instance, i would also look at sub-directory permissions. Personally, i think for the better, Transmission doesn't ask for permissions, but expects us to find out. Not perfect, but a good default.

**Comment by dchmelik** [comment]
> Also is the value in your configuration file `0` (the integer 0) or `"000"` (the string 000)?
> In current versions it should not be `0`, unless your configuration file is write protected or something alike.

It was one '0' but didn't used to be, and the file isn't write-protected.

> @maxz @dchmelik This is not a Transmission issue, per se

You didn't read closely enough: transmission _saves_ (i.e. torrents') directories with permissions 777.

**Comment by maxz** [comment]
I first tried to reproduce this with `transmission-daemon` and `transmission-qt` which display the normal behaviour that I expected.
So I then also compiled `transmission-gtk` to try and nail this error down, but I cannot reproduce it with `transmission-gtk` either.
All my tests were based on commit `83ffa6bf1b3408bc33f419890442da7898b45c02`. Could you recompile all your Transmission binaries based on that commit or a later commit and see if the error is still there for you?

**Comment by dchmelik** [comment]
When I did 'chmod g+r settings.json'--which _shouldn't_ be required--it stopped happening.

**Comment by maxz** [comment]
It's not required by default. But once your umask setting is messed up this does not come as a surprise. Transmission writes all of its files under the constraints of its umask, therefor also its configuration files.

It would still be very interesting to find out what happened to your settings in the first place, but it seems rather unlikely that we find it out. The best case would be that it was something external that triggered this and that this error has no direct connection to Transmission.
Please keep an eye open for when it happens again.

**Comment by dchmelik** [comment]
> It's not required by default.

That's just semantics; if you set settings.json og-rwx maybe it'll happen!

**Comment by dchmelik** [comment]
I've compiled most/every commit since then. All of transmission daemon, gtk, qt now create all directories with permissions 777.  No other program (including p2p) does this so seems not case was 'somethig external'.
