### ISSUE TITLE
Trying to clear search field using Command + Delete on search field (on macOS) deletes previously selected torrent

### ISSUE THREAD

**Issue by daf121** [transmission/transmission#3599]
1. Use search field to find a few torrents
2. Select One of the torrents (to see some of its metadata for instance)
3. Select the search field to search for a new torrent
4. Press Command + Delete to clear the search field of its content
-> Transmission suggests deleting the torrent, which is a bug as the search field was selected, but for some torrents that are "problematic" (file not available due to disconnected external hard drive for instance), there is no confirmation window, torrent is immediately deleted.

**Comment by Coeur** [comment]
Confirmed.

The shortcut from the main menu is taking precedence:
![Capture d’écran 2022-11-12 à 01 33 21](https://user-images.githubusercontent.com/839992/201396842-d19d9888-c550-44e5-97b7-0301cbcfa7f6.png)

I haven't found how to either disable it or override it when search field is selected.
PR welcome if you know.
