### ISSUE TITLE
Impossible to rename file in case "File name too long"

### ISSUE THREAD

**Issue by sHaggYcaT** [transmission/transmission#362]
Sometimes, a torrent result file has a too long name. In windows this name is OK, in Linux not. And it's architecture limitation in the Linux.

But the problem is - the transmission does not permit to rename this file. In this case transmission does not download all similar torrents anyway.

I use these packages:

transmission-daemon-2.92-1.el7.x86_64
transmission-common-2.92-1.el7.x86_64
transmission-cli-2.92-1.el7.x86_64

**Comment by psycholyzern** [comment]
Currently having this problem. can't download torrent because the file name is too long.

**Comment by vblanton** [comment]
This has also been discussed here: Issue #122 
However, issue 122 was closed even though it wasn't resolved.
Notable: Deluge torrent client for linux does not have this issue. perhaps it automatically truncates the name.

**Comment by ckerr** [comment]
> EDIT: Seems like this was fixed for 3.0

Closing as fixed.
