### ISSUE TITLE
how to limit buff/cache memory

### ISSUE THREAD

**Issue by lcexc** [transmission/transmission#3639]
Recently, I install transmission-daemon on debian 11, when I download file, the buff/cache memory grow up quickly. It takes all most memory, Is this normal situation?

today, i test on alpine, get the same result.

before download
```
alpine:~# free -h
                    total        used        free      shared  buff/cache   available
Mem:           1.9G       60.1M        1.8G      116.0K       65.6M        1.8G
Swap:          3.9G           0        3.9G
```
then, download a 4.6G file,  buff/cache grow up to 1.8G

```
alpine:~# free -h
                      total        used        free      shared  buff/cache   available
Mem:           1.9G       65.9M       95.0M      116.0K        1.8G        1.7G
Swap:          3.9G           0        3.9G
```

if it`s normal, how can limit the max cache size?

**Comment by vchimishuk** [comment]
@lcexc, this is intended and correct behavior of OS, not Transmission. In short: `buf/cache` is a free (not used by programs for its data) RAM which OS uses (why not, it is not in use any way?) for files cache. If any program will ask OS for some memory cache will be freed immediately and that memory goes to the program.
Also, you can see, that before download you had 1.8G `available` (free) memory and after download you have 1.7G. So, only 100Mb has been requested by Transmission for its job.

This is a well-known GNU/Linux gotcha for new users. There is a whole dedicated site -- https://www.linuxatemyram.com/

Hop, this answers your question. If so, please, do not forget to mark issue as closed.

**Comment by lcexc** [comment]
ok, I see. thanks!
