### ISSUE TITLE
use std::ignore instead of (void) to discard return values

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#3667]
Suggested by @nevack in code review. Since there's already pre-existing code that uses the `(void)` idiom I suggested replacing it everywhere in a single batch PR

**Comment by adimalla** [comment]
Came across this while searching for std::ignore vs (void) to suppress unused variable warning, std::ignore is intended to be used with tuples, do you think it is okay to replace with (void) with std::ignore if it isn't a tuple.
From cppreference:|
"An object of unspecified type such that any value can be assigned to it with no effect. Intended for use with [std::tie](https://en.cppreference.com/w/cpp/utility/tuple/tie) when unpacking a [std::tuple](https://en.cppreference.com/w/cpp/utility/tuple), as a placeholder for the arguments that are not used."

**Comment by mikedld** [comment]
Since you're quoting cppreference,
> It can also be used to avoid warnings from unused return values of [[[nodiscard](https://en.cppreference.com/w/cpp/language/attributes/nodiscard)]] functions.

© https://en.cppreference.com/w/cpp/utility/tuple/ignore

**Comment by adimalla** [comment]
Thanks for mentioning, but wouldn't (void) me more performant ?
asm: https://godbolt.org/z/ce41zv63r

![image](https://user-images.githubusercontent.com/22340482/186793262-43326d38-dec0-4e55-a4d1-6329fc589b41.png)

**Comment by ckerr** [comment]
That is quite surprising! 

In truth, we use it so infrequently that I doubt that either option would make much difference in the codebase -- but even so, it's hard to argue with that comparison. Let's use `void` rather than `std::ignore`

**Comment by mikedld** [comment]
@adimalla, @ckerr, that test doesn't have optimizations enabled. I personally don't care about debug builds performance that much.

**Comment by ckerr** [comment]
Sure enough. With `-O` the two are equivalent

**Comment by adimalla** [comment]
Agreed that two are equivalent with optimizations, however from clean code / naming best practice.
std::ignore needs #include <tuple>, someone reviewing the code (in general) may get confused to lack of tuple inits and methods in the current file scope. Wish it were a part of utility, or some lib more generic where its not just associated with tuple.
Having said this, my opinion is just based around code design in general, its always upto the authors to decide what they wish to go with.

**Comment by nevack** [comment]
Maybe worth noting that Chromium moved from void casts to `[[maybe_unused]]` and `std::ignore = ...` this year.
Yup, this needs `#include <tuple>`, but I don't this as a problem.

**Comment by Coeur** [comment]
I'm not seeing warnings when I replace `(void)curl_easy_setopt` with just `curl_easy_setopt`. Shouldn't we only have warnings with functions declared with `[[nodiscard]]`? If that's the case, we don't need either `(void)` or `std::ignore` most of the time.

**Comment by mikedld** [comment]
Could be we're also getting those warnings from static analysis tools like Sonarcube and Coverity (not sure) which may have their own modeling/annotations for popular libraries, even if library authors don't use the attribute.

**Comment by ckerr** [comment]
This has been sitting here in the 'todo' bin for months now because it's `(void)` vs `[[nodiscard]]` is just not very interesting.

I'd welcome a PR for this if someone wants to write it, but am closing this issue as declined.
