### ISSUE TITLE
[git] transmission-qt doesn't resume/open torrents transmission-(daemon|gtk) saved

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3676]
I prefer transmission-qt but have been using transmission-gtk (about 1+ years).  They use same /home/user/.config/transmission and I tried switching back only to find transmission-qt didn't find/resume about a year of torrents.  I switched back to transmission-gtk and those resumed fine.

**Comment by ckerr** [comment]
I don't understand this bug report

**Comment by dchmelik** [comment]
> I don't understand this bug report

Rewrote.

**Comment by dchmelik** [comment]
I believe this is clarified (but since there was a case I stated I use transmission-gtk then you asked me in all capitals what I use, maybe there's more I need to say?)

**Comment by dchmelik** [comment]
Of course I switch from GTK to QT and back to verify it's still happening.

**Comment by ckerr** [comment]
Hi,

I appreciate your answer but am not sure that I understand it. :smile: 

I understand reproducing the bug requires swapping between transmission-gtk and transmission-qt, but am trying to learn both are new builds (e.g. from the same commit hash) or if one is older, e.g. an older git checkout, or transmission 3.00, or whatever.

In other words, I'm trying to understand if there's a possible compatibility issue that comes up when switching between 3.00 and newer builds.

**Comment by dchmelik** [comment]
I updated past post/topic; don't think it can get clearer than this: for each new version, of course I switch from transmission GTK to QT, to verify it's still happening (so far must switch back to GTK).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Once again you assumed I do things I never mentioned and don't know how to do (this time idea of using multiple git versions when the original post was for one this August then checked/updated for each new, and now only mentions one(s) currently tested... if unmentioned, clearly they're untested, which isn't to say might not have the problem, but I'm not testing)

**Comment by dchmelik** [comment]
Doesn't everyone see posts/titles' revisions?  Please check before replying.  From the last 22 to six hours everything already became 100% clarified (recent revision explained).

**Comment by ckerr** [comment]
> I reported this in Summer (in plain/simple English, but seems to have been misread/ignored/deleted) for git transmission: torrents opened in transmission-gtk don't appear/resume in qt nor daemon (other than ones they all already loaded before the bug, in a much older version, perhaps v3, which I no longer use).  I stated I test each application for each same git version (not mixed versions, which I don't know how, nor presumably know any next complicated aspect I'm asked about, i.e., didn't omit).
>
> Steps
> 1. In transmission-gtk (in version weeks/months before original bug report, maybe final stable v3) open many torrents: almost 3,000 to 3,200 (possibly testable with some/many fewer).
>2. Exit, and 'upgrade' to git.
> 3. Exit, and start as gtk, and open some tens more torrents, and remember which because they may not appear later (meaning they'll be invisible in the list).
> 4. Exit, and restart as either qt or daemon, and then check for resume error (the tens new torrents may not appear unless you next exit, and start as gtk, they'll still appear in the gtk), and then exit & restart & check vice-versa (repeat steps two to four over & over, likely with same result).
>
> ### Which application of Transmission?
>
> daemon, gtk, qt
>
> ### Which version of Transmission?
>
> git after v3 to current

**Comment by ckerr** [comment]
> Steps

These steps are confusing to me:

> In transmission-gtk (in version weeks/months before original bug report, maybe final stable v3) open many torrents: almost 3,000 to 3,200 (possibly testable with some/many fewer).

The bug report seems to be about something loading in transmission-gtk but not transmission-qt. Is also changing _versions_ necessary to reproduce the bug? If so, could you clarify what version I need to test here? The words "maybe" and "possibly" don't give me confidence here about which version to test with.

> Exit, and 'upgrade' to git.

Nice little neg there putting the word "upgrade" in quotes.

> Exit, and start as gtk, and open some tens more torrents, and remember which because they may not appear later (meaning they'll be invisible in the list).

What's being exited here? What happened between step 1 and 2?

Does "invisible in the list" mean they are not in the list at all, e.g. the "All" count doesn't count them? Or that they're in the list but are not rendered right, e.g. without a name or something? Is transmission not loading them at all, or is it loading them but not showing them?

> Exit, and restart as either qt or daemon, and then check for resume error (the tens new torrents may not appear unless you next exit, and start as gtk, they'll still appear in the gtk), and then exit & restart & check vice-versa (repeat steps two to four over & over, likely with same result).

Any error messages? What do you mean by "resume error?

**Comment by ckerr** [comment]
@dchmelik can you provide a public-domain `.torrent` and `.resume` file that loads in transmission-gtk but not in transmission-qt?

**Comment by GaryElshaw** [comment]
Deja vu?

**Comment by dchmelik** [comment]
Sorry for duplicate (had trouble finding previous).  Lately I had trouble starting transmission and waiting long enough until I could view/search & modify, but was able to a minute ago and found the bug isn't currently happening, even though it was yesterday, but today I haven't 'upgraded' (not intended as negativity, just cautioning people switching versions from long-term/stable/user to current/development/experimental occasionally brings larger bugs than ones they wanted solved).  All I know is it had been a problem sometime after v3 for weeks/months of git versions, which I didn't get to reporting immediately, so don't know if was immediately after v3 or only more git versions/days/weeks/months later, but you at least had to upgrade from the initial (whether stable or current) version to later ones from git. 'Exit' (not necessary to exit OS) stated again was just for returning from step four to two.

I'm closing this for now as may just work to keep opening in the various applications until finally opens all (may have been result of not saving or opening overloaded/thrashing RAM, until after a few tries starting, enough is finally allocated, which would be a separate bug).
