### ISSUE TITLE
[258faf3 to fa8b6a5] transmission-gtk: almost no right-button menu items

### ISSUE THREAD

**Issue by dchmelik** [transmission/transmission#3697]
Recent transmission-gtk when pressing right pointer button on any torrent, and menu appears, almost all menu items are greyed-out: can't check/edit properties or do almost anything at all (all still work in transmission-qt which has its own problems).

**Comment by ckerr** [comment]
I think ab09718342e0160762d7666bea4f685fd1309b27 _might_ fix this. Are you still seeing this problem?

**Comment by dchmelik** [comment]
> I think [ab09718](https://github.com/transmission/transmission/commit/ab09718342e0160762d7666bea4f685fd1309b27) _might_ fix this. Are you still seeing this problem?

Report's title had been updated about 14 hours ago to include it's happening in ab09718 gtk (not qt).

**Comment by ckerr** [comment]
Looks like a0305a3a1224d9037c86fb079ccb5a986afce27b might've broken this. When I revert it, the menus & actions all start working again. CC @bexnoss
