### ISSUE TITLE
[macOS] Message Log, translations are missing

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3698]
Preferably before the first beta, translations were available everywhere.
[Transmission-258faf3623](https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-258faf3623.dmg)

- **German**
<img width="717" alt="German" src="https://user-images.githubusercontent.com/62497891/186228016-5dbaa875-b1b1-4304-9943-da5e1b7f9abe.png">

- **Dansk**
<img width="717" alt="Dansk" src="https://user-images.githubusercontent.com/62497891/186228081-2f16e076-0469-4f81-b320-60e06d7a4347.png">

- **Italiano**
<img width="717" alt="Italiano" src="https://user-images.githubusercontent.com/62497891/186228244-9f9c997f-4320-409e-aa3e-eaa77aa39b6e.png">

- **Nederlands**
<img width="717" alt="Nederlands" src="https://user-images.githubusercontent.com/62497891/186228306-8d01a97c-4a50-4f2e-85c2-3b249b5858c1.png">

**Comment by ckerr** [comment]
Unless I'm misunderstanding, this isn't a bug tthat can be fixed in the codebase -- it's just missing translations on Transifex. Is that correct?

**Comment by Coeur** [comment]
It's just missing on Transifex, but I could code a fallback to English when translation is missing.

**Comment by mikedld** [comment]
GTK and Qt clients function this way, falling back to the original phrase if no translation is available. Whether you want to do the same for Mac client is up to you, I'm not sure what the usual approach is and how easy it is to change the behavior we have now. I agree that showing the English phrase is generally better from UX perspective than having no phrase at all.
