### ISSUE TITLE
Incomplete .part subtitles files fail to Complete even after Validation #8263

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#3700]
Build ab09718342 #8263 macOS 12.5.1 Monterey Mac mini M1 Ultra

Incomplete .part subtitles files fail to Complete even after Validation

Not all, but for me as many as 15-20% of downloaded files with subtitles show incomplete .part subtitles even after Validation function displays 100% complete. Perhaps there is only a failed rename operation upon completion and upon validation.

screenshot example one of many:
<img width="793" alt="incomplete parts subtitles" src="https://user-images.githubusercontent.com/19694741/186292712-bbaa8f1d-858e-4840-b477-5bc89f7eddfe.png">

**Comment by wedsa5** [comment]
I am also having this issue. Mine is not with subtitles, but with multipart .rar files.
The .r#, .rar, and .sfv files often (not all of them, but up to half) still have the .part extension.

I have tried:
* Re-verifying the torrent
* Deleting the .part files manually then re-verifying allowing them to re-download
* Deleting all the files for the torrent then re-verifying allowing them all to re-download
* Deleting the entire torrent with `-rad` option, then re-adding the torrent
* Deleting the entire torrent, deleting the torrent file, then re-downloading the torrent file and re-adding it

**Comment by ckerr** [comment]
Possibly fixed by 4879, 4880, and 4890 in 4.0.1.

@chaseholden is this still occurring?

**Comment by chaseholden** [comment]
I think this has been solved. I cannot replicate it on 4.0.2.
