### ISSUE TITLE
A potential bug of NPD 

### ISSUE THREAD

**Issue by ash1852** [transmission/transmission#3706]
Hi, I found a potential null pointer dereference bug in the project source code of transmission, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the red arrows represent the call relationships, the file path can be seen in the blue framed section.

![image](https://user-images.githubusercontent.com/87304478/186634843-f4b69e89-c865-407b-9aa5-ce059696045e.png)

would you can help to check if this bug is true?thank you for your effort and patience!

**Comment by ckerr** [comment]
Hi, you're right about the potential problem here; but in practical terms, what can be done about it? If `malloc()` is failing here it'll fail everywhere else too. The application would be nonfunctional. To be honest, it's probably better to crash than to just stop operating.
