### ISSUE TITLE
README on this project page makes no mention of Windows port except on code signing mention at the bottom

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#3707]
Whoever is updating the documentation: please mention that this is a Windows-compatible project so users know it's not just for Linux and Mac anymore. 

Good first issue to anybody who wants to polish up the README.

**Comment by acchang** [comment]
I grabbed this and made the requested change. 
https://github.com/transmission/transmission/pull/3729

It's my first open source contribution! I hope it's ok. I've actually used Transmission too, so this is doubly exciting!
