### ISSUE TITLE
Allow to change the language in UI

### ISSUE THREAD

**Issue by zlodo** [transmission/transmission#372]
Hi,

I found a previously closed issue regarding this (issue 130).

I have installed transmission, on a windows 10, english system. The locale settings are french (for the sake of date format), but the language settings are set to english.

Somehow, that locale setting seems enough for all applications to second guess my english language settings and use french by default, which is not what I want. (french translations are uniformly terrible and I don't like to have to always second guess which well known english technical term is hiding behind a french word that nobody ever actually use in that context)

So usually I can change the language. When there is no option for it, I can delete the unwanted translation files. But transmission is being extra "helpful" and automatically restore those as well.

Automatic language detection never works as intended 100% of the time. Please add an option to override it in the preferences. It is extremely irritating to have your choice of language second guessed incorrectly without a way to change it.

**Comment by mikedld** [comment]
I see what you mean, but please try the [nightly build](https://build.transmissionbt.com/) first to see if the behavior has changed for the better; if it did and the language Transmission uses is in fact what you want, I don't see the point in making it possible to select the language just yet.

**Comment by zlodo** [comment]
I just tried the nightly and it does pick the english language. Thanks!

**Comment by shepelevstas** [comment]
I have the same problem. Will that nightly build be available as a standard stable version for downloading?
