### ISSUE TITLE
[edit] add option to edit source flag

### ISSUE THREAD

**Issue by ilf** [transmission/transmission#3724]
Transmission got support for the "source flag" in some of its tools via #443 and #1991. Thanks!

But while this exists in [create](https://github.com/transmission/transmission/blob/main/utils/create.cc), it's missing in [edit](https://github.com/transmission/transmission/blob/main/utils/edit.cc).

I for one would love this feature in `transmission-edit`. Thanks!

**Comment by ilf** [comment]
I dont know C++, but maybe something for @xavery, as author of #443?

**Comment by ilf** [comment]
Since the feature was merged with https://github.com/transmission/transmission/pull/3760, should this issue be closed?

**Comment by EchoLynx** [comment]
> Since the feature was merged with #3760, should this issue be closed?

I think it should be.

**Comment by ckerr** [comment]
Closing based on previous two comments
