### ISSUE TITLE
consider explicitly add "--force-verify" option

### ISSUE THREAD

**Issue by Dachtire** [transmission/transmission#3777]
#2626 
It's necessary to add "--skip-verify" option. When add unfinish download prealloc files without .part will pass all the conditions and stated as finished. In this case transmission equal to skip verify by default and show the fake finished state of torrent although there is lazy check. Most users know nothing about it, add the option to warn and decide.

**Comment by ckerr** [comment]
Under what conditions will this happen?

**Comment by Dachtire** [comment]
> Under what conditions will this happen?

1. unfinished download task from other bt client move to transmission.
2. transmission unfinish downing without setting .part, due to some error have to remove the task and readd.

**Comment by ckerr** [comment]
This doesn't sound like a scenario that many people would encounter?

If you're manually adding an incomplete task without `.part` files, wouldn't it be just as easy to click "Verify local data" as it would to add a new command-line argument?

**Comment by Dachtire** [comment]
"Verify local data" is what im doing now. But I think "skip verify" is better.

**Comment by Auska** [comment]
I really want this feature, and I often need to publish the same resources to different PT sites, which is important to me.

**Comment by ckerr** [comment]
> I really want this feature, and I often need to publish the same resources to different PT sites, which is important to me.

Could you be more specific about what feature you're requesting? Reseeding torrents to different sites sounds a lot like https://github.com/transmission/transmission/pull/2626 to me. This issue is specifically about an edge case of adding _unfinished_ torrents into Transmission without the `.part` file suffix

**Comment by ckerr** [comment]
> "Verify local data" is what im doing now. But I think "skip verify" is better.

I don't think that I understand this? Transmission is already skipping upfront verify (and instead using on-demand verify) as described in #2626 when the local data passes an initial sniff test. Since it's already skipping the verify, what would `--skip-verify` add?

**Comment by Auska** [comment]
> > I really want this feature, and I often need to publish the same resources to different PT sites, which is important to me.
> 
> Could you be more specific about what feature you're requesting? Reseeding torrents to different sites sounds a lot like #2626 to me. This issue is specifically about an edge case of adding _unfinished_ torrents into Transmission without the `.part` file suffix

Thanks.

**Comment by Dachtire** [comment]
> I don't think that I understand this? 

Sorry, re-edited the original message.

**Comment by ckerr** [comment]
> Click "Verify local data" after manually adding an incomplete task is the solution i am using now. But I think explicitly add the "skip verify" option will be approaching other bt client and user understand it better. As transmission change the default logic from "verify everthing" to "skip verify new add torrent".

I'm sorry but I'm still confused about this request. If you're wanting Transmission 4 to behave the same as Transmission 3, wouldn't `--force-verify` be what we'd want, not `--skip-verify`?

**Comment by Dachtire** [comment]
right, "--force-verify" is better overall.
