### ISSUE TITLE
[3.00] Unable to add .torrent file (transmission-daemon, just command line and web GUI, on Raspian Bullseye 64bit)

### ISSUE THREAD

**Issue by viertelb** [transmission/transmission#3790]
I am trying to add this link: `https://releases.ubuntu.com/22.04/ubuntu-22.04.1-desktop-amd64.iso.torrent`

The message I get is `Error adding "https://releases.ubuntu.com/22.04/ubuntu-22.04.1-desktop-amd64.iso.torrent"  gotMetadataFromURL: http error 0: No Response`

I also get the same message on command line with `transmission-remote -a`. 

At the same time I added torrents successfully as magnetic links on command line. 

However, I get no single peer with the `debug-log` saying: `Pv4 DHT not ready (broken, 0 nodes) (tr-dht.c:743)`.

I am connected via VPN, so no port forwarding. But this setup once worked. I migrated, so not sure if I am doing anything wrong. 

I am running Raspbian Bullseye 64bit and installed `transmission` via `apt`.

```
pi@RPi64:~ $ transmission-daemon -V
transmission-daemon 3.00 (bb6b5a062e)
```

**Comment by ckerr** [comment]
4.0.0-beta.1 should be out sometime in the next couple of weeks. @viertelb, is there any chance you could try a nightly build from transmissionbt.org and/or build from source to see if the current codebase still has this problem?

**Comment by viertelb** [comment]
@ckerr I tested with a second setup and I don't have the issue there. Since this is the exact same version `transmission-remote 3.00 (bb6b5a062e)` I probably have some error in my first setup, which I am currently unable to debug.
