### ISSUE TITLE
Add groups usability

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#38]
Today the only usage I have seen so far for groups is to filter the view of Transmission.
But why not to give those groups some usage ? I am thinking of having some properties linked to the groups like:
- having different destination folder for Torrents
- having different seed ration for those

And possibly having the support for groups with the API, for example when I add a file, I tag in the "seed" group so I know that I will retain this file forever.

**Comment by Taruga** [comment]
Waiting for those features for so long. It was awesome if they come reality one day....

**Comment by Trisooma** [comment]
Something that allows you to set destination folder for completed torrent was commited to trac a while back: https://trac.transmissionbt.com/ticket/5385.
FYI I am the original author of that patch

**Comment by mattia-b89** [comment]
duplicate of #79  ?

**Comment by ckerr** [comment]
Closing as duplicate of #79
