### ISSUE TITLE
Check box in "File-Torrent Inspector" doesn't work

### ISSUE THREAD

**Issue by victorjee** [transmission/transmission#382]
Transmission ver: 2.92
MacOS ver: 10.12.6

After I unchecked some files in one seed, these files still be downloaded.

**Comment by mikedld** [comment]
If the file is a part of a piece which also contains other files which you want to download, this file will be downloaded. That's how torrents work.

Related to [TRAC-532](https://trac.transmissionbt.com/ticket/532) (currently residing in [trac532-collect-unwanted-blocks](/transmission/transmission/commits/trac532-collect-unwanted-blocks) branch).

**Comment by mikedld** [comment]
See #290.

**Comment by KingLucius** [comment]
@mikedld Maybe those files could be hidden and get deleted after downloading finished?
