### ISSUE TITLE
Download only specific files

### ISSUE THREAD

**Issue by WildOrangutan** [transmission/transmission#3830]
Hey, would it be possible to add a feature, to download only specific files?

For example, if I download whole season for TV series, I would only like to download pilot episode.

**Comment by fredo-47** [comment]
This feature is already available.
For example you can use transmission-remote with these options:
```
 -g   --get                    <files>            Mark files for download
 -G   --no-get                 <files>            Mark files for not downloading
```

**Comment by WildOrangutan** [comment]
Also for web interface? Sorry, forgot to mention it in first place.
