### ISSUE TITLE
Display Issue - Google Chrome

### ISSUE THREAD

**Issue by kyleinprogress** [transmission/transmission#384]
I believe it started in Chrome 59 (I'm on version 60 right now), but in either collapsed or normal mode, the row for each torrent is taller than it should be. This is only a problem in Chrome and it appears to the default styling Chrome recently added to unordered lists.

By adding one additional style to the UL, this issue is fixed:

File to be fixed: [web/style/transmission/common.css](https://github.com/transmission/transmission/blob/master/web/style/transmission/common.css)

**Original** 
```css
ul.torrent_list {
  width: 100%;
  margin: 0;
  padding: 0;
  text-align: left;
  cursor: pointer;
```

**Fixed**
```css
ul.torrent_list {
  width: 100%;
  margin: 0;
  padding: 0;
  text-align: left;
  cursor: pointer;
  list-style-type: none;
```

My apologies for not doing this as a pull request. I wasn't sure if the .css or .scss file needed to be updated. So I thought I'd just write this up and let the experts fix it.

**Comment by mikedld** [comment]
Thanks. You usually patch the SCSS file and then compile it into CSS file and commit both.
