### ISSUE TITLE
MacOS crash during quit

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3843]
Quitting time has increased again the last while, but the crash on quit is new.

[Transmission-2022-09-23-101010.txt](https://github.com/transmission/transmission/files/9635692/Transmission-2022-09-23-101010.txt)

3.00+ (cee339e10d) and previous.

**Comment by Coeur** [comment]
Unless I'm reading it incorrectly, your attached file doesn't have a crash log, so it can't be investigated.
On the other hand, there is already a crash report for one happening when quitting the app: #3825
