### ISSUE TITLE
Modify the "Add Tracker" option to take multiple trackers.

### ISSUE THREAD

**Issue by Reelix** [transmission/transmission#3844]
As it stands, the "Add Tracker" option under torrent properties on the Windows client only allows you to add one tracker at a time.

If you want to add a list of trackers, this process can become extremely tedious.

I suggest altering the "Add Tracker" popup dialog to change from a single-line textbox to instead be a multi-line textbox, and parse each line as a new tracker (Trimming out empty lines)

**Comment by ckerr** [comment]
The nightly builds do this. Code last touched in https://github.com/transmission/transmission/pull/3565
