### ISSUE TITLE
Build failed of latest 3.0

### ISSUE THREAD

**Issue by eblanca** [transmission/transmission#3846]
I checked out git revision 1b641b660e1b63cc5d796c364a3fe1bf441cdf56 and the build is failing because of some headers not found:
```
[ 77%] Building CXX object utils/CMakeFiles/transmission-remote.dir/remote.cc.o
In file included from /home/topolinik/svn/transmission/gtk/Application.cc:38:
/home/topolinik/svn/transmission/gtk/FilterBar.h:10:10: fatal error: glibmm/extraclassinit.h: File o directory non esistente
 #include <glibmm/extraclassinit.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Note: this header is missing indeed, but the -dev package shows as installed via synaptic.

My cmake command line was:
```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_GTK=ON -DENABLE_QT=OFF -DENABLE_MAC=OFF ..
```
and the check resulted OK:
```
-- Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.50.1;giomm-2.4>=2.26.0'
--   Found gtkmm-3.0, version 3.24.0
--   Found glibmm-2.4, version 2.58.0
--   Found giomm-2.4, version 2.58.0
```
Any hints?

**Comment by mikedld** [comment]
This file is usually provided by glibmm development package, e.g. I can see it in [libglibmm-2.4-dev](https://packages.debian.org/bullseye/amd64/libglibmm-2.4-dev/filelist) for Debian and [glibmm24-devel](https://packages.fedoraproject.org/pkgs/glibmm24/glibmm24-devel/fedora-37.html#files) for Fedora. Check if you have it properly installed.

**Comment by eblanca** [comment]
Indeed, the header file is missing from the -dev package for amd64.
Submitted bug report to debian guys.
Closing.

**Comment by eblanca** [comment]
A last note after a brief glibmm release check:
extraclassinit.h first appears into release 2.59.1 so should the requisite for cmake be raised accordingly?

**Comment by ckerr** [comment]
> A last note after a brief glibmm release check:
> extraclassinit.h first appears into release 2.59.1 so should the requisite for cmake be raised accordingly?

Sounds reasonable to me.

From looking at https://github.com/GNOME/glibmm/blob/master/NEWS, it looks to me like 2.59.1 is an unstable release, and 2.68.0 is the first stable that came out post-2.59.1. So let's bump the gtkmm dep to 2.68.0
