### ISSUE TITLE
Transmission insists on capitalizing "complete" directory

### ISSUE THREAD

**Issue by ozhound** [transmission/transmission#385]
My Server (Ubuntu 14.04) and Tranmission 2.92 is misbehaving

I recently setup a NAS and forced the GUID and UUID to an existing user on the NAS

Transmission creates and downloads the torrent fine. However when it trys to copy the file to its completed directory (on the same volume just a different subdirectory) it fails with the error

Couldn't create "/media/Downloads": Permission denied (utils.c:424)

The thing is.. /media/Downloads Doesnt exist. it is /media/downloads. 

the settings in the json file reflect this and ive tried unistalling transmission and resetting it backup.

I note that the previous location was Capitalized and was /media/storage/Downloads.

why would it be insisting on using Downloads instead of downloads?

please advise.

**Comment by mikedld** [comment]
Transmission doesn't do that. Please use [forums](https://forum.transmissionbt.com) for support.
