### ISSUE TITLE
[macOS] Crash on start on latest master

### ISSUE THREAD

**Issue by nevack** [transmission/transmission#3851]
```
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'assertion failed: walk6 = std::data(nodes6) + std::size(nodes6) (/Users/nevack/Developer/Projects/transmission/libtransmission/tr-dht.cc:390)'
terminating with uncaught exception of type NSException
```
Something to do with IPv6 support I suppose.

**Comment by mikedld** [comment]
Assignment inside an assertion looks very weird (assertions can't have side-effects, otherwise debug/release builds could have different behavior), should it probably be `==` instead of `=` there?

**Comment by ckerr** [comment]
Thanks for reporting this!

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/3852
