### ISSUE TITLE
macOS GUI issues 3.0.0-dev (cee339e10d)

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3880]
I think it was probably #3871, but a number of new GUI issues are occurring.

- The bar of active torrents remains grey (paused)
- The ability to pause active transfers has gone
- With active transfers working, the client thinks these are paused

![SCR-20221007-meg](https://user-images.githubusercontent.com/69029666/194459810-c15a0f2e-a85d-4184-9f7c-8f34ffef3d73.png)

**Comment by ckerr** [comment]
Well that's disappointing.

Oh well, that's what betas are for. :1st_place_medal:

**Comment by robd003** [comment]
I'm guessing this is the cause: https://github.com/transmission/transmission/pull/3871

**Comment by GaryElshaw** [comment]
Pretty sure...

**Comment by Coeur** [comment]
@Harm133 @ckerr can we revert #3871 for now? I'm not clear what was the goal of the change, but it's causing more issues than not.

**Comment by Harm133** [comment]
I would rather fix than revert. Will publish a fix later :)

**Comment by ckerr** [comment]
> I would rather fix than revert. Will publish a fix later :)

Just now saw this comment after merging @Coeur's PR. :man_shrugging: @Harm133 I'd be happy review another PR if you want to rework the patch

**Comment by Coeur** [comment]
To close the loop, the rework has been done in #3944
