### ISSUE TITLE
4.0.0-beta.1 - Windows 11 Defender False Positive

### ISSUE THREAD

**Issue by smurfhunter** [transmission/transmission#3887]
I can't unpack the .msi file or run it, it looks like it's corrupted.

**Comment by mikedld** [comment]
You don't generally "unpack the .msi file", you let Windows Installer do that for you. What are you trying to do and what error are you getting?

**Comment by mikedld** [comment]
Where did you download it from? Could you try downloading again? Could you confirm that its SHA256 matches [9d7039dc55b0da9518467122ed76ae33a796adf612bfcc932d29b360f47880e2](https://www.virustotal.com/gui/file/9d7039dc55b0da9518467122ed76ae33a796adf612bfcc932d29b360f47880e2)?

**Comment by smurfhunter** [comment]
God I'm tired, forgive my lackluster info. Tested on a Windows 10 machine - works. Tested with compatibility troubleshooter - Windows changes the error to say it has unwanted or harmful files. Tried to open with 7zip again and noticed Windows is treating this as a virus - it's outright deleted.

Disabling Windows Defender realtime protection and cloud-delivered protection resolves the issue.

**Comment by smurfhunter** [comment]
Windows could not start the transmission daemon - error 1503: the service did not respond to the start or control request in a timely fashion. Happens on both the latest nightly and beta, 64 bit.

**Comment by smurfhunter** [comment]
When I don't do a full install (do not install daemon) and just do a regular install, the install finishes successfully with windows defender turned off on both the github beta and nightly.

**Comment by mikedld** [comment]
> Windows could not start the transmission daemon - error 1503: the service did not respond to the start or control request in a timely fashion. Happens on both the latest nightly and beta, 64 bit.

I'd start by (re)moving service configuration directory to see if it helps. Also check out Event Viewer to see if the service exits abnormally.

**Comment by smurfhunter** [comment]
I'm not at home to test this on my personal PC, but I've tested this on three up to date Windows 11 machines that are not mine. They appear to install fine now. I'm unsure if this has been fixed by a Windows update or if it was specific to my machine, but if other members cannot reproduce this, I'm happy to call it closed.

**Comment by ckerr** [comment]
Closing based on previous comment
