### ISSUE TITLE
Doesn't close properly

### ISSUE THREAD

**Issue by WASasquatch** [transmission/transmission#389]
On my Windows 10 Creators Edition Transmission won't close properly. It will appear to be close (gone from windows task bar) but it is still present in the windows task manager processes. If you forget about this, and open Transmission again it will open two copies, one you can interact with, and one in the background. However the one in the background will be doing the actual downloading/uploading, so the window you have doesn't represent what's actually happen (it's info is static from launch, or adding a torrent.). 

For example I just downloaded my server files and I thought it wasn't downloading on the open window with no sources, and I thought that was odd, server was online AND uploading. I realized it was the double process issue. Turns out it was near finished downloading.

**Comment by mikedld** [comment]
See #287.
