### ISSUE TITLE
4.0.0-beta.1 should not list the app name in the window chrome

### ISSUE THREAD

**Issue by TorsteinVin** [transmission/transmission#3891]
Transmission 4.00 beta1 on macOS Monterey displays the name "Transmission" in the top left corner of the window chrome. This is not normal behaviour in any macOS application, and it displaces the tool bar icons towards the right, essentially hiding them unless I resize the window to fit them. 

Remove the name "Transmission" from the window chrome as it serves no purpose (it's obvious it's Transmission, and the user doesn't need to be reminded) and is not normal macOS application behaviour.

**Comment by GaryElshaw** [comment]
@nevack Could you please take a look and see if the status bar appears for you?
