### ISSUE TITLE
4.0.0-beta.1 webui text in preferences is unreadably close to background color

### ISSUE THREAD

**Issue by TorsteinVin** [transmission/transmission#3893]
Text in preferences in webui is almost unreadable as the text is same color as backgorund in Safari 16.0 and Firefox 105.0 in macOS 12.6 Monterey. See photo below.

<img width="569" alt="Skjermbilde 2022-10-07 kl  18 18 02" src="https://user-images.githubusercontent.com/77975542/194600702-11ca94e4-c04a-4a33-a6aa-156984671a18.png">

**Comment by ckerr** [comment]
Related: https://github.com/transmission/transmission/issues/3834

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/3985
