### ISSUE TITLE
4.0.0-beta.1 webui sort order progress does not sort  properly

### ISSUE THREAD

**Issue by TorsteinVin** [transmission/transmission#3894]
Sorting by progress, the sort order gets displayed by progress for some torrents, but others don't get sorted by progress. it seems to be random, and is clearly broken. Toggling reverse order doesn't fix the issue. 

Sorting by name is displayed correctly.

**Comment by dareiff** [comment]
@TorsteinVin I'm curious what the percentages of the specific torrents are. Would you mind sending those over? 

Example: 75% | 45% | 87%.

**Comment by TorsteinVin** [comment]
> @TorsteinVin I'm curious what the percentages of the specific torrents are. Would you mind sending those over?
> 
> Example: 75% | 45% | 87%.
> 
> (So far I haven't been able to dupe, but I don't have many test torrents loaded.)

You know what, I think I just got confused by the new color palette. Since now Recently started seeding, and recently finished downloads, and finished seeding now have almost the same color of gray. I think it could be an idea to visually dinstinguish these different transfer-states more clearer. 

Ie like the 3.00 webui:

Recently started torrent is light gray
Torrent downloading is Light vibrant green filling up light gray space
Finished torrent is fully light vibrant green.
Seeding torrent is darker vibrant green replacing light vibrant green
Finished seeding torrent is dark gray. 

So, I think you can just close this ticket, since it seems to  be sorting correctly. But please consider the suggestions for easier visual communication of torrent-states :)
