### ISSUE TITLE
Update in-app links

### ISSUE THREAD

**Issue by JohnClay** [transmission/transmission#39]
A continuation of the earlier issue w/ the donate link - internal links point to the old site and/or are not HTTPS. Links should be updated to use HTTPS, as well as point to the relevant GitHub page.

**Comment by alimony** [comment]
@JohnClay What is left to be done on this one?

**Comment by JohnClay** [comment]
@alimony I think at this point it's just switching the links over to the [GitHub Wiki](https://github.com/transmission/transmission/wiki) equivalent. I believe @mikedld has migrated the important wiki pages already.

**Comment by alimony** [comment]
@JohnClay These are the only three left according to #57:
https://trac.transmissionbt.com/wiki/Scripts
https://trac.transmissionbt.com/wiki/BuildingTransmissionQtWindows
https://trac.transmissionbt.com/wiki/BuildingTransmissionQtMac
