### ISSUE TITLE
TeamCity build is timing out on NetBSD on PlatformTest.defaultConfigDirXdgConfig

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3900]
One of our CI step is occasionally failing on NetBSD on PlatformTest.defaultConfigDirXdgConfig

https://trtc.mikedld.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=257937&_focus=1892
```
[19:48:39][Step 3/4] 1: [ RUN      ] PlatformTest.defaultConfigDirXdgConfig
[19:58:10][Step 3/4] 1/6 Test #1: libtransmission-test ..........................***Timeout 600.63 sec
```

**Comment by GaryElshaw** [comment]
Also noteworthy, apparently the Transmission TC license is expiring in the next day or two.

**Comment by ckerr** [comment]
@GaryElshaw Mike knows, but thanks :+1:

**Comment by Coeur** [comment]
This issue is old now, so closing it.
