### ISSUE TITLE
4.0.0-beta.1 [macOS] Transmission hangs when attempting to open the Message Log window

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#3908]
Transmission 4.0.0-beta.1 on macOS 10.15.7 hangs when attempting to open the Message Log window.

**Comment by Coeur** [comment]
I do not experience such issue on macOS 13.0 beta 10, with main branch.
In which language is your Transmission interface? Do you reproduce with a nightly build?

**Comment by CyberSkull** [comment]
Everything works fine in 4977c1a02f, the nightly I am using.

**Comment by CyberSkull** [comment]
The message window hangs in bfe6953822.

**Comment by CyberSkull** [comment]
Message window seems to work fine now in cdf817f2e7.
