### ISSUE TITLE
rust rewrite when 👀

### ISSUE THREAD

**Issue by xslvrxslwt** [transmission/transmission#3910]
title

**Comment by Pentaphon** [comment]
@Coeur he wants the project to be rewritten in Rust instead of C++ lol

**Comment by nevack** [comment]
Existence of this issue proves the project is really alive 😄

**Comment by Pentaphon** [comment]
Judging by how Rust has been adopted by projects as big as the Linux kernel itself, it may just be a matter of time before Transmission gets refactored into Rust by a very enthusiastic developer. I wouldn't be surprised to see Transmission 6 or 7 become Rust-based. Hey, as long as Transmission keeps living on and on for decades to come, I wouldn't mind that at all.

**Comment by xslvrxslwt** [comment]
> @Coeur he wants the project to be rewritten in Rust instead of C++ lol

It was a “joke” as everyone's recently (re)writing stuff in rust and everything's “written in rust” so when I've saw it says “rewritten in c++” I felt weird / as if I didn't see cpp in ages as no one's talking about it anymore 😹

**Comment by ckerr** [comment]
Made me smile. 😆 

Even though you were joking I'll give a serious answer since I saw some other people asking this room.

Rust is great, but rewrite would literally be from scratch. The code modernization in 4 was from C to C++, so a lot of the existing code was able to be used as-is

**Comment by Coeur** [comment]
https://twitter.com/slava_pestov/status/1582054532816678919
