### ISSUE TITLE
Listening port check does not work

### ISSUE THREAD

**Issue by escalade** [transmission/transmission#392]
It works fine in 2.92, but when using latest master (0378ee8) it does not.

**Comment by MoBattah** [comment]
Can you provide any more information? 

To get it right, this is in regards to checking port status in the gtk settings panel?

**Comment by escalade** [comment]
Sorry, should have been more specific. I haven't tested the GTK version, this is regarding the port status in the web settings panel. It says closed, but it's correctly forwarded through UPnP.

**Comment by MoBattah** [comment]
Is your IP v4 or v6?

**Comment by escalade** [comment]
It's IPv4, I've also tested with ipv6.disable=1 as kernel option to exclude any IPv6 issue.

**Comment by bunder** [comment]
Do you use proxy or several IP addresses?

**Comment by txVLN** [comment]
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407

**Comment by ckerr** [comment]
Duplicate of #407
