### ISSUE TITLE
[3.00] opening property window sets up crash

### ISSUE THREAD

**Issue by apinunt** [transmission/transmission#3928]
Ubuntu 22.04 Mate desktop, running Transmission 3.00 on Dell G5 and MSI GE75.
Transmission runs fine until you open a property window, which sometimes labels the columns randomly, but just opening the window and closing it seems to set up a crash at some point afterwards.
Numerous people have complained about the issue which sees to have started for me with 22.04.

**Comment by mikedld** [comment]
If it's a crash then having a crash report containing backtraces would be nice.

Also, could you try reproducing this with current `main`? 3.00 was released quite some time ago with a huge amount of changes since, and I'm not sure if we'll be making any 3.x patch releases.

**Comment by trebonius** [comment]
This seems to be related to this issue in Ubuntu's bug tracker: https://bugs.launchpad.net/ubuntu/+source/transmission/+bug/1969315

I will give the 4. beta a try and see if I have the same issue.

**Comment by trebonius** [comment]
So far, I haven't seen this occur in 4.0.0-beta.1
Though as others have discovered, it can come and go.
