### ISSUE TITLE
transmission-3.00 debian 8 recipe for target 'all' failed

### ISSUE THREAD

**Issue by xdostup** [transmission/transmission#3929]
Good day.
transmission-3.00 debian 8
Download from here
https://github.com/transmission/transmission-releases

root@***:/home/*/x/transmission-3.00/build# cmake -DCMAKE_INSTALL_PREFIX=/usr ..    
-- Configuring done  -- Generating done

 make -j2
[ 77%] Building C object libtransmission/CMakeFiles/transmission.dir/wildmat.c.o
Linking CXX static library libtransmission.a
[ 77%] Built target transmission
Makefile:137: recipe for target 'all' failed»
make: *** [all] Error 2
root@***:/home/*/x/transmission-3.00/build# 

/home/xd/x/transmission-3.00/build/libtransmission/Makefile
# The main all target
all: cmake_check_build_system
	cd /home/*/x/transmission-3.00/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/*/x/transmission-3.00/build/CMakeFiles /home/*/x/transmission-3.00/build/libtransmission/CMakeFiles/progress.marks
	cd /home/*/x/transmission-3.00/build && $(MAKE) -f CMakeFiles/Makefile2 libtransmission/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/*/x/transmission-3.00/build/CMakeFiles 0
.PHONY : all

**Comment by mikedld** [comment]
Could you attack a complete build output? It seems that the actual error is located somewhere above the quoted lines.

**Comment by xdostup** [comment]
Good day mikedld. All work.
1 Download gettext 0.19.8.1-1~bpo8+1 from backports
2 CMakeLists.txt
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++1**4**")
 set(CMAKE_CXX_STANDARD 1**4**)

Build OK.
