### ISSUE TITLE
Downloaded files are corrupted

### ISSUE THREAD

**Issue by NikKovIos** [transmission/transmission#393]
I used Transmission to download as games as a movies. And when downloading games, it tells, that file is corrupted. When downloading movies there are damaged frames.

After that i've used uTorrent client and everything downloaded well.

I just wrote this to other users to know that there is such an issue. The problem solved by deleting the Transmission.

**Comment by Allezxandre** [comment]
This is weird. What version of transmission were you using, and on which OS?

**Comment by NikKovIos** [comment]
10.12.3 (16D32)
2.92
Donwload torrents from rutracker.org

**Comment by briskycat** [comment]
**Transmission 2.94 (d8e60ee44f)** running on the latest OpenWrt 18.06-SNAPSHOT r7813-6ee6c97ded on ZyXEL NBG6817.
Still need to run "Verify Local Data" manually on each finished torrent as ~1% usually ends up being corrupt.
Is it time to implement https://trac.transmissionbt.com/ticket/4649 at last?

**Comment by ckerr** [comment]
I haven't been able to reproduce this. If someone seeing this wants to do some detective work and track down the problem, I'd be happy to work on a patch and / or review a PR. But without a way to reproduce the issue I don't know how to move forward on this ticket.

**Comment by ckerr** [comment]
Duplicate of #820.
