### ISSUE TITLE
session-get fields argument ignored

### ISSUE THREAD

**Issue by holomorph** [transmission/transmission#397]
The RPC spec says:
```
4.1.2.  Accessors

   Method name: "session-get"
   Request arguments: an optional "fields" array of keys (see 4.1)
   Response arguments: key/value pairs matching the request's "fields"
       argument if present, or all supported fields (see 4.1) otherwise.
```

However, sending `{"method":"session-get","arguments":{"fields":["alt-speed-enabled"]},"tag":123}"` yields a response containing all the fields.  On `transmission-remote 2.92 (14714)`

**Comment by mikedld** [comment]
Refer to rpc-spec.txt that corresponds to your version (https://github.com/transmission/transmission/blob/2.92/extras/rpc-spec.txt), not the yet-to-be-released version. It says:

```
4.1.2.  Accessors

   Method name: "session-get"
   Request arguments: none
   Response arguments: all of 4.1's arguments
```

**Comment by holomorph** [comment]
Sorry about that. Thanks.
