### ISSUE TITLE
Torrent with unicode in its name does not show in web UI

### ISSUE THREAD

**Issue by micah** [transmission/transmission#3972]
### What is the issue?

I added a torrent that has a unicode character in it (eg. `Björk`) and the webui does not show it at all. If I use `transmission-remote`, I am able to see the torrent without any difficulties.

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 3.00 (bb6b5a062e)

**Comment by killemov** [comment]
In index.html there is `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` so everything should be utf-8. Could you add `<meta charset="UTF-8">` in the head section and report back? It might also be informative to know on which platform you're running transmission-daemon and browser. And also which browser you are using.

**Comment by ckerr** [comment]
If this still exists in 4.0.2, it may possibly be fixed by https://github.com/transmission/transmission/pull/5244

**Comment by killemov** [comment]
FYI, Those must have been some weird Unicode characters because I have had no problems with Unicode. Japanese, emoji, no problem.

**Comment by tearfur** [comment]
`Björk` works now.
