### ISSUE TITLE
TR_TORRENT_BYTES_DOWNLOADED is empty?

### ISSUE THREAD

**Issue by defkev** [transmission/transmission#3978]
### What is the issue?

I am trying to use `$TR_TORRENT_BYTES_DOWNLOADED` in a `script-torrent-done` but the value returned is empty.

https://github.com/transmission/transmission/blob/4a359fd481d9706e55599ffda2e6fa35b16ba40a/libtransmission/torrent.cc#L1738

Am i doing something wrong or is this just not working?

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

v3.0.0

**Comment by mikedld** [comment]
The variable wasn't set in 3.00: https://github.com/transmission/transmission/blob/3.00/libtransmission/torrent.c#L2260-L2266. Those changes were made after 3.00 release and will be included in 4.0.0 (I believe 4.0.0-beta.1 has them already).

**Comment by defkev** [comment]
Guess i'll wait for v4 to hit EPEL then, thanks!
