### ISSUE TITLE
[macOS] UI

### ISSUE THREAD

**Issue by Oleg-Chashko** [transmission/transmission#3979]
### What is the issue?

- Russian
<img width="861" alt="RU" src="https://user-images.githubusercontent.com/62497891/196158342-0c33db1f-7338-404d-9e66-d29b3307c963.png">

- French, button size, do as in all localizations
<img width="640" alt="FR" src="https://user-images.githubusercontent.com/62497891/196159004-8bd3d40d-a267-4c06-ac8b-a69be83979cd.png">

- 1. Length is not justified, take the example of other localizations.
- 2. Transferring the contents of the interface to the right side does not work correctly. Especially noticeable in Russian only in this tab.

<img width="1054" alt="RU_2" src="https://user-images.githubusercontent.com/62497891/196160221-9cf697dc-c555-4539-b84e-703fbe98beeb.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.1

**Comment by Oleg-Chashko** [comment]
- It is better to limit, the possibility of reducing the minimum vertical size.

<img width="594" alt="Screen Shot 2022-10-17 at 15 48 33" src="https://user-images.githubusercontent.com/62497891/196184424-f9026a62-e53e-4334-8aa8-1711d27c597d.png">

**Comment by Oleg-Chashko** [comment]
- Only when the window title is activated, the buttons have a color.

https://user-images.githubusercontent.com/62497891/196185153-11d25335-2a53-459e-859e-e158e9880986.mp4

**Comment by dareiff** [comment]
> * Only when the window title is activated, the buttons have a color.
> 

I _think_, generally, this is ongoing behavior with Inspector-type windows in macOS. (Unsure if intended or not.)

**Comment by ckerr** [comment]
@Oleg-Chashko there's a general rule against omnibus bug reports since it makes bookkeeping difficult, e.g. when a ticket has three bug reports and you fix two bugs, you still can't close the issue.,

So I'm going to close this issue but please do file separate tickets for each of these issues. Thank you!
