### ISSUE TITLE
Issues with Web UI on mobile (4.0.0-beta.1)

### ISSUE THREAD

**Issue by esmorun** [transmission/transmission#3983]
### What is the issue?

1. The menu on the right side is to big, the top part ends up being above the screen, and it also covers some of the buttons on the top row. (A sidebar would probably make more sense on mobile?)
![Screenshot_20221017-205221_Firefox](https://user-images.githubusercontent.com/59760231/196261092-e8c47613-2378-4c83-ba3d-b5cde583d723.jpg)

2. After pressing the info button, you would expect that pressing it again would close the menu again, but it doesn't. And since the menu covers the whole screen on mobile there's no way to close the menu (on desktop I can press an empy space to close it).

3. Text in the info menu appears almost white. I assume this is a dark mode that wasn't properly engaged?
Edit: I see this has already been reported.
![Screenshot_20221017-210623_Firefox](https://user-images.githubusercontent.com/59760231/196263010-8e4f4bad-543e-49d9-9e9a-0d150447ac25.jpg)

Also here are some other thoughts:
- The toolbar on top could be a bit bigger to make the buttons easier to press on a mobile screen. Maybe consider moving it to the bottom on mobile to make one handed operation easier?
- The icons on the top are very low resolution, even on a mobile screen. Maybe replace them with some fresh new ones that would go well with a tasty dark theme? :)

Thank you for your hard work!

### Which application of Transmission?

Web client

### Which version of Transmission?

5.0.0-beta.1

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/3985
