### ISSUE TITLE
Sparkle

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#3988]
### What is the issue?

Now that we're in beta, Sparkle should be reactivated.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.00 beta

![SCR-20221019-qq](https://user-images.githubusercontent.com/69029666/196418421-ffcf7bed-88b9-42be-8aab-204b1f378cbb.png)

**Comment by mikedld** [comment]
Not sure what you mean by "reactivated". Could you please describe what the actual issue is before offering a solution?

**Comment by GaryElshaw** [comment]
A user the other day had been using the 'check for update' function and it hadn't worked. I'm wondering if 3.00 isn't picking up 4.00 beta, and i was wondering if 4.00 betas will pick up later betas?

**Comment by mikedld** [comment]
It's been decided during 4.0.0-beta.1 release preparation that we don't want to offer it for update via Sparkle. I'll let @livings124 comment on further betas.

FYI, [appcast.xml](https://github.com/transmission/transmission.github.io/blob/master/appcast.xml) is the file Sparkle uses for its checks, and as you can see it doesn't contain 4.x info right now.

**Comment by GaryElshaw** [comment]
Cool, thanks Mike.

**Comment by mikedld** [comment]
I also vaguely remember that beta releases support had to be reworked after Sparkle update, and I'm not sure we ever did this.
