### ISSUE TITLE
Downloading torrents have a resume button instead of pause and can't be paused

### ISSUE THREAD

**Issue by federicochiesa** [transmission/transmission#3994]
### What is the issue?

As the title says, the torrents in the screenshot are downloading, but they still show a "resume" button next to the progress bar, and clicking that has no effect, the same problem can be seen in the window bar, there's only a resume button enabled that doesn't do anything.

I noticed that it the button becomes a "pause" button when the torrent starts downloading, but still this isn't right.

![Screen Shot 2022-10-19 at 10 32 05](https://user-images.githubusercontent.com/38504010/196639931-899b24a1-5eb4-49a3-bee4-d79ca10d4f4b.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0 beta 1

**Comment by Coeur** [comment]
Fixed in #3889. You should try a nightly build. :)
