### ISSUE TITLE
Unify settings folder for GUI and CLI versions

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#40]
The GUI and CLI versions of Transmission seem to be using completely different config files and folders. Even the formats are different (`.plist` for the GUI version and `.json` for the CLI.)

Suggest to make this identical for both versions, and if the paths to the config files have to be different because of Homebrew/macOS conventions, a simple symbolic link can unify them.

This way you can use GUI and CLI interchangeably, which I don't see why you shouldn't be able to do. Probably get rid of some surplus code, too.

**Comment by DamienCassou** [comment]
I also don't really the point of having 2 directories.

**Comment by forthrin** [comment]
Evidently, this will never happen due to lack of developer interest.
