### ISSUE TITLE
unchecked files still downloaded.

### ISSUE THREAD

**Issue by azzamsa** [transmission/transmission#400]
the unchecked files still downloaded, even I change the state to low priority.

``` bash
$ transmission-gtk --version
transmission-gtk 2.92 (14714)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
```

please ask me if you need other information.

thanks for this great app, I use this app since the first time I used GNU/Linux at 2013.
thank you so much your contribution to community.

**Comment by mikedld** [comment]
See #290.
