### ISSUE TITLE
Newly-added magnet files get queued for verification if there are torrents being verified

### ISSUE THREAD

**Issue by catadropa** [transmission/transmission#4000]
Newly-added torrents should not get queued behind torrents being verified. But they do, as of recently (nightly builds). They show up as "queued for verification" instead of "downloading metadata...". Unsure if new torrents added with .torrent files get queued the same way.

**Comment by Coeur** [comment]
Can you clarify with which app you're experiencing this?

**Comment by killemov** [comment]
Getting the same behavior in transmission-daemon <=3.00. (I don't have a problem with it, but technically @catadropa is correct.)

**Comment by catadropa** [comment]
This is with transmission-gtk. Also, the magnet will transition to paused instead of downloading, after it gets the magnet data.

**Comment by killemov** [comment]
@Coeur No! This is 'normal' but possibly unwanted behavior for all platforms.

**Comment by ckerr** [comment]
Is this still an issue in 4.0.2?

**Comment by catadropa** [comment]
> Is this still an issue in 4.0.2?

Nope! Finally updated to latest nightly and tested this. No longer a problem!
