### ISSUE TITLE
New Magnets Find No Peers Seed Connections

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#4003]
### What is the issue?

macOS 12.6 M1 Ultra ARM64 

Anyone else on this build find it impossible for newly added magnets to find any peers whatsoever?
I had to quit and open Transmission 3, re-add all new magnets on T3, then quit and open new build 6187cfd67b #8394.

Something weird is going on and I apologize for attempting to explain as a non-dev.

Recipe
1. I open T4, add magnets, magnets appear red with 0 connections or connectivity
2. I open T3, re-add same magnets, magnets very quickly find peers and successfully connect. 
3. If I quit T3, re-open T4 above, any magnets that had not found peers and metadata remain stuck red and peerless
4. If I quit T4 again and re-open T3, those same remaining peerless magnets find peers, connect, and download.

### Which application of Transmission?

macOS app for Monterey

### Which version of Transmission?

build a27c3d18d  #8393

**Comment by sweetppro** [comment]
I am also having issues connecting to trackers and finding peers. Restarting v4 nightly seems to connect. It looks like an issue with connecting to trackers while Transmission has been running for some time, as opposed to connecting on startup

**Comment by chaseholden** [comment]
Restarting T4 doesn't help me at all. 
Only first starting magnets in T3 will allow them to work in T4.

**Comment by arcticfoxwp** [comment]
I have been having this problem on the nightlies for the past 6 months or more, and it still hasn't been fixed. Magnet links are unusable. Peers are found on Transmission startup and then a few mins later the peers drop off, requiring restart to find peers again.

This only happens using Magnet lniks.

**Comment by GaryElshaw** [comment]
A commit made yesterday made a massive difference for me with regards to tracker connectivity.

**Comment by arcticfoxwp** [comment]
I'm on the latest nightly and the problem persists for me.

**Comment by GaryElshaw** [comment]
My only other suggestion is based on behaviour. Transmission is sometimes not very good at reporting corruption if you're downloading, i'd take a close look at doing a 'verify data' on the torrents you are downloading?

**Comment by arcticfoxwp** [comment]
Thanks for the help - I just tried and no problems with the verification. As I mentioned, this is an issue that has been present the whole way through v4 development. I've downloaded the latest nightly once per week and have always had the problem. Exactly the same as the commentors above. The dev team can't replicate this? Is it an issue that only affects ARM Macs? Do they never use Magnet links?

**Comment by sweetppro** [comment]
I have an M2 and exclusively use magnets. The only issue I’m seeing is that while peers connect quickly, it does take some time before data is transmitted.

**Comment by arcticfoxwp** [comment]
Interesting. Let me know how I can help

**Comment by Coeur** [comment]
I'm exclusively using magnets, and no more issues of any sort since 4a80f800a60a52c00ae014074caadaa282666d81.
@arcticfoxwpg @chaseholden kindly try a recent build, thanks.

**Comment by arcticfoxwp** [comment]
@Coeur Tried todays build and problem persits. Very few peers found on Magnet. but the same transfer using the torrent file downloads quickly.

Also, I know it's being worked on, but getting a crash on exit too. Ongoing for me for many months.

**Comment by Coeur** [comment]
@arcticfoxwpg which issue number is it? If there are none, you'd need to create an issue for your crash, with a crash log.

**Comment by arcticfoxwp** [comment]
@Coeur Thanks - crash submitted #4371

Ahything I can do to help with the no magnet peer issue?

**Comment by Coeur** [comment]
I'm afraid I don't know how to help with your magnet issue. Feel free to investigate by looking at the code and your message logs.

**Comment by arcticfoxwp** [comment]
@ckerr @Coeur No longer having this issue - magnets work as they should.
