### ISSUE TITLE
Transmission-QT 4.0.0-beta.1 shows a tons of checksum errors where 3.0.0 works without any.

### ISSUE THREAD

**Issue by blacklion** [transmission/transmission#4007]
### What is the issue?

I have Transmission-QT 3.0.0 and Tansmission-QT 4.0.0-beta.1 installed side-by-side on Windows 10 (x64). Same set of torrents.
3.0.0 downloads reasonably fast and without hash errors.
4.0.0-beta.1 shows 150MB of hash errors per 100MB of successfully downloaded.
When I stop 4.0.0-beta.1 and start 3.0.0, 3.0.0 shows "Piece #xxx corrupt" for ~10% of torrents which were downloaded by 4.0.0-beta.1

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0-beta.1

**Comment by Coeur** [comment]
Any sample torrent that can reproduce this?

**Comment by Kurville** [comment]
Yes, I often have corrupt pieces. I was thinking it could be a good idea to have an option to automatically verify local data once all the pieces have been downloaded or when a corrupt piece is declared while still downloading.

**Comment by stefantalpalaru** [comment]
I have also seen this with 4.0.0-beta.2 on Linux. Some time after the download is completed, a checksum made while seeding fails and an error is shown asking to verify all pieces. It's a rare occurrence - like once or twice a month.

Sure enough, the completion bar goes back to 99% and the bad piece is re-downloaded. Maybe not all pieces are hashed and checked during the initial download? An off-by-one somewhere? Background jobs being cancelled by download completion?

**Comment by ckerr** [comment]
Related: https://github.com/transmission/transmission/discussions/4542

**Comment by ckerr** [comment]
Related: #4890

I think this is fixed now, so I'm going to close this ticket. If this still occurs for you in 4.0.2 or higher please file a new ticket. :bow:
