### ISSUE TITLE
WEB interface FTBFS while trying to locate node modules

### ISSUE THREAD

**Issue by sardanap** [transmission/transmission#4019]
### What is the issue?

Tried with redhat9 and archlinux 6.0.2 both with the same error:

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@primer/stylelint-config > postcss-scss@4.0.5" has unmet peer dependency "postcss@^8.3.3".
warning " > stylelint-config-sass-guidelines@9.0.1" has unmet peer dependency "postcss@^8.3.3".
[4/4] Building fresh packages...
Done in 17.48s.
yarn run v1.22.19
$ /root/Transmission/build/web/node_modules/.bin/webpack --config /root/Transmission/web/webpack.config.js --context /root/Transmission/web
[webpack-cli] Failed to load '/root/Transmission/web/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /root/Transmission/web/webpack.config.js
- /root/Transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js
- /root/Transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js
- /root/Transmission/build/web/node_modules/webpack-cli/bin/cli.js
- /root/Transmission/build/web/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/root/Transmission/web/webpack.config.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Transmission/web/webpack.config.js',
    '/root/Transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js',
    '/root/Transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js',
    '/root/Transmission/build/web/node_modules/webpack-cli/bin/cli.js',
    '/root/Transmission/build/web/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [web/CMakeFiles/trweb.dir/build.make:93: web/CMakeFiles/trweb] Error 2
make[1]: *** [CMakeFiles/Makefile2:1448: web/CMakeFiles/trweb.dir/all] Error 2

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

b32f3e0

**Comment by ckerr** [comment]
Hmm, I wonder if this was an npm hiccup? I just tried this and got:

```
yarn install                                                                                                                                                      127 ↵  2022-10-24 16:00 CDT wk43
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@primer/stylelint-config > postcss-scss@4.0.5" has unmet peer dependency "postcss@^8.3.3".
warning " > stylelint-config-sass-guidelines@9.0.1" has unmet peer dependency "postcss@^8.3.3".
[4/4] Building fresh packages...
Done in 2.41s.
```

Is it still failing for you @sardanap ?

**Comment by floppym** [comment]
I consistently get the same failure on Gentoo.
```
build % make -C web
make: Entering directory '/home/floppym/src/transmission/build/web'
make[1]: Entering directory '/home/floppym/src/transmission/build'
make[2]: Entering directory '/home/floppym/src/transmission/build'
make[2]: Leaving directory '/home/floppym/src/transmission/build'
make[2]: Entering directory '/home/floppym/src/transmission/build'
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@primer/stylelint-config > postcss-scss@4.0.5" has unmet peer dependency "postcss@^8.3.3".
warning " > stylelint-config-sass-guidelines@9.0.1" has unmet peer dependency "postcss@^8.3.3".
[4/4] Building fresh packages...
Done in 5.38s.
yarn run v1.22.19
$ /home/floppym/src/transmission/build/web/node_modules/.bin/webpack --config /home/floppym/src/tran
[webpack-cli] Failed to load '/home/floppym/src/transmission/web/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /home/floppym/src/transmission/web/webpack.config.js
- /home/floppym/src/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js
- /home/floppym/src/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js
- /home/floppym/src/transmission/build/web/node_modules/webpack-cli/bin/cli.js
- /home/floppym/src/transmission/build/web/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/floppym/src/transmission/web/webpack.config.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/floppym/src/transmission/web/webpack.config.js',
    '/home/floppym/src/transmission/build/web/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/floppym/src/transmission/build/web/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/floppym/src/transmission/build/web/node_modules/webpack-cli/bin/cli.js',
    '/home/floppym/src/transmission/build/web/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [web/CMakeFiles/trweb.dir/build.make:93: web/CMakeFiles/trweb] Error 2
make[2]: Leaving directory '/home/floppym/src/transmission/build'
make[1]: *** [CMakeFiles/Makefile2:1550: web/CMakeFiles/trweb.dir/all] Error 2
make[1]: Leaving directory '/home/floppym/src/transmission/build'
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/home/floppym/src/transmission/build/web'
```

**Comment by sardanap** [comment]
This fixed for me:

https://github.com/AndreyPavlenko/transmission/commit/cdc7bd2f15c89fdc58bed2208392dd857cd479d5

**Comment by GaryElshaw** [comment]
No shade, but a fix in May of 2021 might not be relevant to an issue with beta 4 of 2022.

**Comment by t-8ch** [comment]
@GaryElshaw This commit fixes it for me too.
The problem is easily reproducible with out-of-source builds.

It does not look like the best fix because it symlinks the binary dir into the source dir, but it works.

**Comment by GaryElshaw** [comment]
Ouch

**Comment by t-8ch** [comment]
The correct solution would most probably to tell yarn/webpack to pick up node_modules from `${CMAKE_CURRENT_BINARY_DIR}` with an environment variable or CLI switch

**Comment by GaryElshaw** [comment]
@ckerr This sounds appropriate to me. Thoughts?

**Comment by mikedld** [comment]
That's what I did in https://github.com/transmission/transmission/compare/build/remove-transmission-app.js-from-repo...build/remove-transmission-app.js-from-repo-tmp (WIP, based off @ckerr's PR) but I don't like how it looks that much, specifically the need to pass path to node_modules 3 (!) times...

**Comment by t-8ch** [comment]
Would a `.yarnrc` in the binary dir work?

https://www.caxy.com/blog/how-set-custom-location-nodemodules-path-yarn

**Comment by mikedld** [comment]
Not sure, as passing `--modules-folder "${NODE_PATH}"` (alone) to yarn doesn't seem to help when running webpack. I'll certainly try if you think it will.

**Comment by t-8ch** [comment]
Just a guess. I can try to come up with something later'

**Comment by t-8ch** [comment]
Maybe someone could also change the title of the ticket to be more correct?

**Comment by GaryElshaw** [comment]
Best practice is to open a separate issue or pr and reference the issue you're trying to resolve. PIA i know.

**Comment by t-8ch** [comment]
@mikedld I didn't find a way to reduce the number of path specifications...
Instead of passing them as cli parameters they could be done from `webpack.config.js` though.

**Comment by t-8ch** [comment]
This seems also to be the same as #1480

**Comment by ile6695** [comment]
@ckerr Did you accidentally close this with keyword: "Does **not** fix https://github.com/transmission/transmission/issues/4019"?

**Comment by ckerr** [comment]
@ile6695 oop yes I did, but https://github.com/transmission/transmission/pull/4641 fixes it anyway so :man_shrugging:  alg
