### ISSUE TITLE
kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [transmission-gt:6585]

### ISSUE THREAD

**Issue by n3wborn** [transmission/transmission#402]
[paste.txt](https://github.com/transmission/transmission/files/1291876/paste.txt)
Having the **transmission-gtk-2.92-6.fc26.x86_64** on a updated fedora with kernel **4.12.9-300.fc26.x86_64** I have many bugs like the one posted in the title : 
`kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [transmission-gt:6585]`

 This error is also causing a bug on the files that are still in download and even if many parts have been downloaded they are not seen by transmission ~> I explain : 

I start transmission-gtk.
I see a file is downloading
I have the bug shown in the title
transmission seems stuck and can't quit proprely (I have to kill the window as it can't send anything to the trackers)
When I start it again, the same download starts again from the beginning, showing 0% completed)

dmesg shows a warning 
`warning: process `transmission-gt' used the deprecated sysctl system call with 1.40.6.`

**Comment by mikedld** [comment]
Doesn't seem to be our problem. Please report to Fedora people first.
