### ISSUE TITLE
Web Client no longer connecting with "Connection failed" pop-up

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4024]
### What is the issue?

I expose the web client on my main computer to my internal network so I can see what's happening from my laptop by going to http://192.168.1.202:9091/transmission/web/

It seems to be broken in the recent main branch. There are a lot of CORS errors in the inspection console:

![image](https://user-images.githubusercontent.com/396781/197660179-34e4c2c5-6be2-4148-9246-0dd61e3a6363.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

088e146cee4908669abb03e16328f6dbb3fb10d6

**Comment by Deathcow** [comment]
Same here, please don't hardcode localhost as destination.

**Comment by pigsyn** [comment]
> Did someone accidentally force everything to be localhost and hardcode all the values? This isn't the right address OR port that Transmission is running on.
> 
> `POST http://localhost:9091/transmission/rpc net::ERR_CONNECTION_REFUSED`

Yes

```diff
1,3c1,3
<         const P = "speed-limit-down",
<             U = "speed-limit-down-enabled",
<             F = "queue-move-bottom",
---
>         const N = "speed-limit-down",
>             R = "speed-limit-down-enabled",
>             j = "queue-move-bottom",
5,13c5,12
<             R = "queue-move-top",
<             Q = "queue-move-up",
<             O = "../rpc",
<             Y = "alt-speed-down",
<             Z = "alt-speed-enabled",
<             W = "alt-speed-up",
<             J = "speed-limit-up",
<             H = "speed-limit-up-enabled";
<         class V {
---
>             U = "queue-move-top",
>             H = "queue-move-up",
>             W = "alt-speed-down",
>             $ = "alt-speed-enabled",
>             Z = "alt-speed-up",
>             O = "speed-limit-up",
>             Q = "speed-limit-up-enabled";
>         class q {
19c18
<                 r.append("cache-control", "no-cache"), r.append("content-type", "application/json"), r.append("pragma", "no-cache"), this._session_id && r.append(V._SessionHeader, this._session_id);
---
>                 r.append("cache-control", "no-cache"), r.append("content-type", "application/json"), r.append("pragma", "no-cache"), this._session_id && r.append(q._SessionHeader, this._session_id);
21c20
<                 fetch(O, {
---
>                 fetch("http://localhost:9091/transmission/rpc", {
27,28c26,27
<                         const t = new Error(V._SessionHeader);
<                         throw t.header = e.headers.get(V._SessionHeader), t
---
>                         const t = new Error(q._SessionHeader);
>                         throw t.header = e.headers.get(q._SessionHeader), t
34c33
<                     if (r.message === V._SessionHeader) return this._session_id = r.header, void this.sendRequest(e, t, n);
---
>                     if (r.message === q._SessionHeader) return this._session_id = r.header, void this.sendRequest(e, t, n);
```

**Comment by belovachap** [comment]
You're right @pigsyn , localhost starts showing up in 6187cfd67b269bf29644bc068bb840da980f718b . I'm going to try to build the web app on my computer and see what it outputs :crossed_fingers: :four_leaf_clover:

**Comment by GaryElshaw** [comment]
@dareiff Thoughts?

**Comment by dareiff** [comment]
Hey ya'll, this is my fault, for sure, and wasn't supposed to be here! I built using a non-clean checkout (that referenced this hardcoded val.)

I'll have it re-built ASAP!
