### ISSUE TITLE
Possible bug with updating trackers list

### ISSUE THREAD

**Issue by depler** [transmission/transmission#4027]
### What is the issue?

**Steps to reproduce**:
1. Add torrent file with one tracker, start download. For example: https://releases.ubuntu.com/22.04/ubuntu-22.04.1-desktop-amd64.iso.torrent
2. Modify trackers list with several different trackers. For example:

```
udp://tracker.opentrackr.org:1337/announce
udp://9.rarbg.com:2810/announce
udp://tracker.openbittorrent.com:6969/announce
http://tracker.openbittorrent.com:80/announce
https://opentracker.i2p.rocks:443/announce
udp://tracker.torrent.eu.org:451/announce
udp://open.stealth.si:80/announce
udp://exodus.desync.com:6969/announce
udp://tracker1.bt.moack.co.kr:80/announce
udp://tracker.tiny-vps.com:6969/announce
udp://tracker.pomf.se:80/announce
udp://tracker.moeking.me:6969/announce
udp://tracker.dler.org:6969/announce
udp://tracker.0x.tf:6969/announce
udp://tracker-udp.gbitt.info:80/announce
udp://public.tracker.vraphim.com:6969/announce
udp://public.publictracker.xyz:6969/announce
udp://open.demonii.com:1337/announce
udp://mts.tvbit.co:6969/announce
udp://movies.zsw.ca:6969/announce
https://torrent.ubuntu.com/announce
https://ipv6.torrent.ubuntu.com/announce
```

**Expected behavior**: all new trackers should be in use
**Actual behavior**: only one tracker in use

I am using `Trans GUI` (https://github.com/transmission-remote-gui/transgui) to control trackers list in `trackers` tab.

**Step 1 trackers:**
![image](https://user-images.githubusercontent.com/13541699/197751162-09b5d995-9507-4f89-9845-799da137a61e.png)

**Step 2 trackers:**
![image](https://user-images.githubusercontent.com/13541699/197751344-e9b74282-74f1-429e-bb86-6f25fd857277.png)

**After restarting transmission daemon:**
![image](https://user-images.githubusercontent.com/13541699/197752518-6bbda7ab-b955-4cb0-939d-4db5c2f12ff2.png)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

latest

**Comment by depler** [comment]
Yes, one per line, without duplicates. The idea is that added trackers count is more than existing ones.

**Comment by ckerr** [comment]
> Expected behavior: all new trackers should be in use
> Actual behavior: only one tracker in use

> Yes, one per line, without duplicates (not sure if order is important). The idea is that added trackers count is more than existing ones.

OK, I see the problem. Unless you put a blank line between trackers, all the trackers in the same "paragraph" are in the same tier, which is to say only one should be used and the rest in the paragraph are all used as backups iff the others fail.

https://www.bittorrent.org/beps/bep_0012.html has more technical writeup of it, but the tldr for when bulk-adding trackers is that if you want them all to be active, put a blank line between them.
