### ISSUE TITLE
TCP socket closed before it's fully connected to the peer?

### ISSUE THREAD

**Issue by basinilya** [transmission/transmission#4033]
### What is the issue?

There's a peer that only supports TCP. The tracker returns its address, Transmission first tries to connect with UDP, then after some time it sends a TCP SYN packet, but the response SYN,ACK packet is dropped because Transmission has already closed the socket. Is this a misconfiguration or a bug? I'm using version 3.00 on Windows 7.

![image](https://user-images.githubusercontent.com/1749243/197847233-4e3e8b6b-934a-432b-a3f1-d1d6015a79cb.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

3.00

**Comment by ckerr** [comment]
Is this still happening after 8755207dcf63969e1d1c7a35734bef0bf537d1b6 ?
