### ISSUE TITLE
Windows compilation is broken on latest commits 

### ISSUE THREAD

**Issue by depler** [transmission/transmission#4035]
### What is the issue?

Details: https://ci.appveyor.com/project/transmissionbt/transmission/builds/45177525/job/r5c6wuw6g9fn4xp4

Pull request: https://github.com/transmission/transmission/commit/12e564096b9ea8a1ebf834e4e26c520b02c6fc0c

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

latest

**Comment by ckerr** [comment]
Fixed by #4036
