### ISSUE TITLE
Windows QT client add C:\to path

### ISSUE THREAD

**Issue by SignFinder** [transmission/transmission#404]
I have the following path to save torrents in settings - /tmp/mnt/SEAGATE//transmission//download
But When I open torrent file - it changes destination path on torrent dialog to C:/tmp/mnt/SEAGATE/transmission/download 
Transmission 2.92.
It worked fine before Transmission-QT was integrated with transmission-bt.

**Comment by mikedld** [comment]
See #236.

**Comment by SignFinder** [comment]
Bug still exists in 2.93.

**Comment by hardhub** [comment]
> Bug still exists in 2.93.

2.94 is also affected!

Why all of that is closed (incl #236)?

**Comment by kapitan-iglu** [comment]
A can also confirm this issue is still present in 2.94, please reopen it!

**Comment by hardhub** [comment]
> 
> 
> A can also confirm this issue is still present in 2.94, please reopen it!

You need to download version 2.94+

Yeah it is different binaries and it is not obvious of course, but it is how I solved it.
Though it is strange why it is not 2.95 for example.
