### ISSUE TITLE
Withdraw your bonus ⬅️

### ISSUE THREAD

**Issue by Ltr200** [transmission/transmission#4044]
https://sites.google.com/view/btbon30

**Comment by Ltr200** [comment]
Version 4 bytes
0x0488ade4 mainnet
Depth 1 byte
0 Master node
Fingerprint 4 bytes
0x00000000
Child number 4 bytes
0x00000000 Master key
Chain Code 32 bytes
0x9a670e972a210d02209bdea7e5e9bf868a60f79c1332e722798f5c7b13dafdf5

**Comment by sweetppro** [comment]
Spam
