### ISSUE TITLE
Version 4 bytes
0x0488ade4 mainnet
Depth 1 byte
0 Master node
Fingerprint 4 bytes
0x00000000
Child number 4 bytes
0x00000000 Master key
Chain Code 32 bytes
0x9a670e972a210d02209bdea7e5e9bf868a60f79c1332e722798f5c7b13dafdf5

### ISSUE THREAD

**Issue by Ltr200** [transmission/transmission#4045]
Urp+p8P9PiiX3Tz8ulchlsCA4f/7eYc23Nca4bb5gTX19Dajszp5Vr1x2B2LCznX9qtjOFsrlc6KeIfEBxYkcNLfm1/vBD3qmRNQBwNIHlRSWbBkyQCbTJxsZQ9Nv6R6qoPbZOe+NgP1ibUCR2eAOR2tNP32Iz8l/53oR2LhVS+R4qvzwehPMPqbvRWcsjywhSX1Tcm0jHOsnBMNp7rROGN8lxD2qHwrVG9O+OUyrVU6wCgZKNRiY2nRmrv9V9uJOAxS7+Bf3rvLbqdrHASAjJOQ6DIGBwXRizObJEYo2mWOeOvRIjbAOL2rYX0KyoMki/z3knKyVDsCVPCy6TWnII1ZGHXc07/WtNUnYejW419eWmarXrX+VA

**Comment by sweetppro** [comment]
Spam
