### ISSUE TITLE
Transmission doesn't honor the order of torrents as they were added

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#4071]
### What is the issue?

Transmission Mac OS 

Since a while before version 4.0 Transmission starts up with existing torrents in a completely random order. It was the case all the way to the 4.0 beta and the nightly I installed for 4.0 today. 

It's mostly annoying that my in progress torrents get randomly spread amongst the seeding ones but I feel like it should just be honoring the order of the torrents.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0 beta nightly

**Comment by killemov** [comment]
This is a "feature" in ALL versions of Transmission. I even implemented functionality in [Shift](https://github.com/killemov/Shift) to re-queue by date added.

**Comment by GaryElshaw** [comment]
@nvanfleet And when you select View -> Sort transfers by -> Date added?

**Comment by nvanfleet** [comment]
Huh I had no idea. Will check it out thanks
