### ISSUE TITLE
transmission-gtk nightly crash - TR_ASSERT(secret_ != key_bigend_t{}); in peer-mse.h

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4078]
### What is the issue?

Not much information on this one, I'm afraid :(

```
assertion failed: secret_ != key_bigend_t{} (/home/chapman/code/transmission/libtransmission/peer-mse.h:63)
Aborted (core dumped)
```

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

41422c357e

**Comment by mikedld** [comment]
Has been reported before, although as a comment to a commit and not an issue :( https://github.com/transmission/transmission/commit/450f1dcadc43641bd807624c263b1e8a54ba22ec#commitcomment-87402706

**Comment by ckerr** [comment]
Hm, a few people have reported this now; let's raise the priority on it.

Still not sure how to repro it though...
