### ISSUE TITLE
Add enviroment variable for groups

### ISSUE THREAD

**Issue by unknown--** [transmission/transmission#408]
Please consider adding an environment variable for post-processing scripts that passes the torrent's group.
e.g. TR_TORRENT_GROUP

**Comment by mikedld** [comment]
This is not really possible until #137 or similar is implemented inside libtransmission. The core has no idea about Mac client groups.

**Comment by ckerr** [comment]
Core does know about labels, and sets `TR_TORRENT_LABELS` for the scripts to use.
