### ISSUE TITLE
Link support for web interface

### ISSUE THREAD

**Issue by POPSuL** [transmission/transmission#41]
Just screenshot :)

[censored]

(see selected text).

Yes, i know, include raw html in webgui is not secure and etc..., but, maybe possible strip all html and just make links for all `https?://[^s]+`?

**Comment by mikedld** [comment]
Related to [TRAC-5620](https://trac.transmissionbt.com/ticket/5620) and revision 157bbe73f6e6792c21f27c32cb841081ca8a16c1 (released in 2.83).

**Comment by mikedld** [comment]
#180 fixed HTTPS handling. Other than that, I think parsing the comment in search for links is overkill.
