### ISSUE TITLE
Observing for torrents in a folder does not work in Beta 4

### ISSUE THREAD

**Issue by nvanfleet** [transmission/transmission#4100]
### What is the issue?

I tried several times to re-configure observing a specific folder for a new torrent file. So far I have had no luck in getting it working. If I select a folder that contains torrents it will add them, but if I add a torrent after that point it won't detect them at all.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 beta 41422c357e

**Comment by belovachap** [comment]
Hrm, we had a similar problem but in the transmission-gtk app that has been fixed recently: https://github.com/transmission/transmission/issues/4076

**Comment by ckerr** [comment]
@nvanfleet based on the previous comment, looks like this might be fixed. Are you still seeing this problem in 4.0.0-beta.3 or newer?

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/4683
