### ISSUE TITLE
macOS upload/download connectivity is broken?

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4106]
### What is the issue?

I think it's been since #4069, but i'm seeing upload and download issues where nothing is being uploaded to peers, but also nothing being downloaded from peers either.

Peers are clearly visible in the inspector panel, but nothing from the client is coming down or going up.

I thought #4103 might resolve it, but no :-(

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.1.dev (4d8509c180)

**Comment by Coeur** [comment]
At the moment, I need to return to Transmission 3 if I want to download. :(
I do not know why.

**Comment by Coeur** [comment]
Confirmed, by going commit by commit, it's a clear regression from https://github.com/transmission/transmission/pull/4069.
So the last commit where you can download with Transmission 4 is d5cc43355cb56b6838253e5b6aa69090004c3b08

**Comment by GaryElshaw** [comment]
I thought it might just be me, thanks for the confirmation Antoine. I have an earlier build i'm running, but i think this nightly should be okay? https://build.transmissionbt.com/job/trunk-mac/8422/

**Comment by Coeur** [comment]
I found a fix: by reverting the 500 lines of the PR one by one, I figured out which one was causing the issue.
