### ISSUE TITLE
assertion failed: is_shutting_down_

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#4115]
### What is the issue?

sanity failure on 162035a65397fb3977ad67e33e24938a971b2ffe:
>[18:10:51 ](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity/306103?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandchucktcpluginBuild=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=306081_13783_13783&logFilter=debug&logView=flowAware)  [ RUN      ] LpdTest.CanAnnounceAndRead
[18:10:51 ](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity/306103?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandchucktcpluginBuild=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=306081_13784_13784&logFilter=debug&logView=flowAware)  assertion failed: is_shutting_down_ (C:\BuildAgent\work\1f3bff43dd55cfe9\libtransmission\session-thread.cc:248)

https://github.com/transmission/transmission/blob/cb932ddf8dac5ea0d1d00edbe1143708ffdfde51/libtransmission/session-thread.cc#L245-L248

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

162035a65397fb3977ad67e33e24938a971b2ffe

**Comment by ckerr** [comment]
This _might_ be fixed as a side-effect of d61e31c419af336063a90d886525497d86e9177f but I'll keep watching CI for this to show up again

**Comment by ckerr** [comment]
I've seen this happen twice more. It's rare, but it's still out there.

**Comment by ckerr** [comment]
I haven't seen this in two months, so I think all the shutdown work for beta.3 fixed it.

Closing this issue, at least for now.

**Comment by ckerr** [comment]
I am probably missing some clue here but I don't understand the action in this issue in this last hour?

Those LPD test failures don't seem to have any mention of `is_shutting_down_` and should be handled in a separate ticket instead of reopening this one. Are those test failures related in a way that I'm not picking up?

**Comment by ckerr** [comment]
@candrews no worries!

Yes please do open another ticket. It looks to me like the same test is failing for two different reasons :dizzy:

**Comment by candrews** [comment]
> Yes please do open another ticket.

Done: https://github.com/transmission/transmission/issues/4747

Thank you again!
