### ISSUE TITLE
Web client does not showing existing torrents (4.0.0-beta.1.dev)

### ISSUE THREAD

**Issue by madurapa** [transmission/transmission#4120]
### What is the issue?

I have more than 100 torrents on the desktop client, but nothing is visible on the web client, and neither settings nor anything else has loaded.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0-beta.1.dev

**Comment by belovachap** [comment]
Possibly a duplicate of https://github.com/transmission/transmission/issues/4087 ? Can you tell us if there are errors in the web browser's javascript console?

**Comment by madurapa** [comment]
Working again when the daemon killed and start, all good thanks!
