### ISSUE TITLE
Transmission's symbolic icon doesn’t show up in Flatpak

### ISSUE THREAD

**Issue by Obsidien** [transmission/transmission#414]
I installed Transmission from the Flathub flatpak repository, and the symbolic icon is neither showing up when in HighContrast theme (the one for visually impaired people), nor in GNOME Shell’s topbar; the “colored and detailed” icon is used instead. Could that be fixed upstream?

**Comment by mikedld** [comment]
There is no official connection between Transmission project and any kind of Flatpak packages. @wjt or other people in #64 may have a clue.

**Comment by wjt** [comment]
@Obsidien please file issues about the Flathub package here: https://github.com/flathub/com.transmissionbt.Transmission/issues
