### ISSUE TITLE
Ratio is not calculated correctly

### ISSUE THREAD

**Issue by roivanov** [transmission/transmission#416]
<img width="829" alt="trans" src="https://user-images.githubusercontent.com/12698352/31313009-e3df4330-ab89-11e7-9340-33fa55697dd1.png">
5.45+10.96+8.31+4.84 = 29.56
5.81+12.41+9.17+5.27 = 32.66
Ratio shown as 0.97 where is obviously above 1
OS: Macos High Sierra
Transmission 2.92 (14714)

**Comment by onmyouji** [comment]
You can toggle between total ratio (total since the first time you ran the program) or session ratio using the yin-yang circle icon next to the ratio.
 
Perhaps 0.97 is from your total ratio, not your current session, which explain the inaccuracy.

**Comment by roivanov** [comment]
It is total.
Wondering if it might count completed (and so removed) transfters as well.

![untitled](https://user-images.githubusercontent.com/12698352/32416995-37581346-c207-11e7-9e80-3db679478323.png)

**Comment by Nircek** [comment]
I think so too. @roivanov you can go to statistics and then calculate again ratio. On my ubuntu version it's in Help -> Statistics

**Comment by ckerr** [comment]
Fixed by #2424
