### ISSUE TITLE
Compact View unresponsive, no effect up to build fd9c454c45 #8464

### ISSUE THREAD

**Issue by chaseholden** [transmission/transmission#4163]
### What is the issue?

M1 Ultra ARM64 macOS 13.1 Ventura 

Compact View is unresponsive rendering no change or effect
Past view recent dev builds up to build fd9c454c45 #8464

### Which application of Transmission?

macOS app

### Which version of Transmission?

dev build 4. fd9c454c45 #8464

**Comment by ckerr** [comment]
Dupe of #4164

**Comment by chaseholden** [comment]
@ckerr apologies! I have no idea how this got duplicated.

**Comment by ckerr** [comment]
No worries!
