### ISSUE TITLE
Zero size files are not created

### ISSUE THREAD

**Issue by dmp42** [transmission/transmission#417]
Running Transmission 2.92 (14714) on macOS Sierra.

See screenshot: the torrent has finished downloading, and is marked as complete by transmission.
Yet, one file is not there.
The inspector also greyed out the "show in finder" entry for that file.

This is not transient - I re-downloaded this torrent twice.

Not sure what's going on here, or if I'm missing something obvious.
<img width="389" alt="screen shot 2017-10-12 at 12 35 11 am" src="https://user-images.githubusercontent.com/332946/31484489-529baef4-aee5-11e7-9bef-ee317c48de24.png">

Let me know what additional info would be helpful.

**Comment by dmp42** [comment]
So, yeah, the file size is 0.
I guess I would expect the file to still be created.
Is this expected behavior?

**Comment by mikedld** [comment]
Related to [TRAC-5716](https://trac.transmissionbt.com/ticket/5716).

**Comment by dmp42** [comment]
Yep, that's exactly that issue.
Editing bug description - feel free to close as a dupe if trac is the source of truth.

**Comment by mikedld** [comment]
Trac is in read-only (and thus reference-only) mode for a long time now.

**Comment by GitHubIsToxic** [comment]
Is this still an issue in v3.0 ?

We discovered the same bug the (very) hard way in our project! Zero sized files are never created on hard disk, even though Transmission (v2.92) explicitly shows the download complete notification.

![Screenshot from 2021-11-11 01-31-44](https://user-images.githubusercontent.com/6215449/141304136-b5ec5a77-6c04-4dcf-ac37-a03d518a3894.png)

**Comment by kambala-decapitator** [comment]
such files as well as directories containing them are also invisible in the Files tab. SS from macOS version 4.0.3:

![Screenshot 2023-07-22 at 15 01 27](https://github.com/transmission/transmission/assets/1557784/ecc75632-edb0-46d4-8f3f-6a46c9a5468f)

And this is how directory hierarchy looks in reality:

![Screenshot 2023-07-22 at 14 58 58](https://github.com/transmission/transmission/assets/1557784/f4303108-b9bd-4db6-9c1e-9d7241e19919)

This torrent file: https://github.com/qbittorrent/qBittorrent/files/12136323/torrent.zip was created with the same Transmission version, it does contain these 0-byte files (checked inside the file)

**Comment by tearfur** [comment]
Re-open so that this issue can be closed by the PR that actually resolves it.

**Comment by GitHubIsToxic** [comment]
Thanks for fixing, keep up the good work!
