### ISSUE TITLE
Replace jsonsl with nlohmann, rapidjson or simdjson

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#4177]
### What is the issue?

Problem: We presently use https://github.com/mnunberg/jsonsl which isn't enough actively maintained.
Solution: we replace jsonsl.c with [nlohmann](https://github.com/nlohmann/json) or [rapidjson](https://github.com/Tencent/rapidjson) or [simdjson](https://github.com/simdjson/simdjson).

**Comment by ckerr** [comment]
From a quick scan of the three my preference would be rapidjson. Its saxlike API should fit into  our existing code pretty well.

**Comment by tearfur** [comment]
Adding one more reason why we should make the switch: We don't have to deal with Unicode, escaping and whatnot.

> RapidJSON is **Unicode-friendly**. It supports UTF-8, UTF-16, UTF-32 (LE & BE), and their detection, validation and transcoding internally. For example, you can read a UTF-8 file and let RapidJSON transcode the JSON strings into UTF-16 in the DOM. It also supports surrogates and "\u0000" (null character).

**Comment by Coeur** [comment]
For context, we're having to fix json-variant.cc these days (#6005) because of a bug for not relying on modern enough implementation.

**Comment by tearfur** [comment]
Hmm.. I hope I'm not seeing an illusion of rainbows and sunshine.

It looks like we can get rid of `tr_variant` entirely and use `rapidjson::Document` instead. We'd just have to write benc parsers and writers.
