### ISSUE TITLE
Error string too long in italian

### ISSUE THREAD

**Issue by gorghino** [transmission/transmission#418]
The error string "Nessun dato trovato. Verificare che le unità siano connesse oppure usare «Imposta posizione». Per scaricare ripartendo da ze" in italian is too long and it's truncated.
![schermata del 2017-10-13 14 08 46](https://user-images.githubusercontent.com/1898283/31545520-0e38ed58-b020-11e7-96fb-c693d031325e.png)

**Comment by ckerr** [comment]
Yep. This should be a multiline that can wrap as necessary for long errors.
