### ISSUE TITLE
Message log window doesn't restore level selection on first show

### ISSUE THREAD

**Issue by mikedld** [transmission/transmission#4181]
### What is the issue?

To reproduce:
1. Start GTK client
2. Click Help menu -> Message Log item to open the window

Expected result: Level combo contains last selected level.

Actual result: Level combo is in indeterminate state (no item is selected).

Worked correctly in 4.0.0-beta.1.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

134363d83de13d799dacc5465fef871a3083ca6c

**Comment by ckerr** [comment]
This was introduced by #4053

**Comment by mikedld** [comment]
This also happens with encryption mode combo in preferences, and maybe other enum settings (are there any?) that were previously saved as ints and now are strings.

**Comment by ckerr** [comment]
I think what I might do just to get things unstuck is to change the type-to-variant converters (e.g. [this function for tr_log_level](https://github.com/transmission/transmission/blob/main/libtransmission/variant-converters.cc#L166)) and have it save an int again like it did in previous releases.
