### ISSUE TITLE
`nightly` `transmission-gtk` progress bars aren't filling correctly

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4189]
### What is the issue?

My main computer died and I just rebuilt the `main` branch and was surprised to see that the progress bars no longer seem to accurately reflect the percentage of download correctly:

![image](https://user-images.githubusercontent.com/396781/202052620-024a7cfb-bf83-4e64-bb10-77885424315f.png)

The blue-ish downloads should be filling up to match the percentage progress and the green-ish seeds are completed and giving back should be full.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

ac6010557e

**Comment by mikedld** [comment]
Regressed in #4183.

**Comment by belovachap** [comment]
Progress bars are looking good again :100:
