### ISSUE TITLE
Transmission-daemon 2.92 not connecting to udp trackers

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#419]
using version 2.92
None of the udp trackers can be connected in transmission-daemon. 
Transmisison-daemon gives error - Could not connect to tracker
Searched Google and all the results show up for previous versions where the problem is marked solved or closed. Did something change in 2.92 that the daemon cannot connect to udp trackers again?

In other clients likeTixati, the trackers are online and show peers.

**Comment by wrongt** [comment]
hi,
like here #413, try to use a port from this range: 49152-65535 for listening peer.

**Comment by ckerr** [comment]
The UDP announce module has been rewritten for 4.0.0, e.g. in #4002 and #4201, and I can confirm that udp tracker announces & scrapes are working.
