### ISSUE TITLE
`nightly` `web client` "Couldn't find Transmission's web interface files!"

### ISSUE THREAD

**Issue by belovachap** [transmission/transmission#4192]
### What is the issue?

I'm guessing this has something to do with no longer providing the `transmission-app.js`? I see some instructions on the page that hint at what I might do to fix it but I'm still pretty lost (and I'm theoretically "good at computer"). I'm running `tranmission-gtk` from the build directory if that has anything to do with this :thinking: It used to just show me the web client as expected behavior.

![image](https://user-images.githubusercontent.com/396781/202062376-156c09c6-c4b4-42b6-bfc3-d2f1c18404da.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

ac6010557ef507985984bf6388f3fb58763dcb35

**Comment by Coeur** [comment]
transmission-app.js is still there, no? The PR wasn't merged yet: #4061

**Comment by belovachap** [comment]
@Coeur you're right! `transmission-app.js` is still there... so why is it breaking this way now?

**Comment by mikedld** [comment]
I don't think this ever worked the way you expect it to (i.e. automatically using file from source or build directory). If it did, it's probably because you had Transmission package installed so that there're web client files somewhere in /usr/share; or you had them in ~/.local/share; or you were setting `TRANSMISSION_WEB_HOME` environment variable.

**Comment by belovachap** [comment]
@mikedld i did have a version installed globally that it must have been using before! maybe if i run `sudo make install` it will copy over the files i need...

**Comment by belovachap** [comment]
Ah ha! That "fixed" it :) Thanks for knowing about how stuff works @mikedld :clap:
