### ISSUE TITLE
[2.92] Deadslow speeds for Download, please help

### ISSUE THREAD

**Issue by vikaskoppineedi** [transmission/transmission#4203]
### What is the issue?

Hello All, 

I am trying to download Ubuntu torrent using transmissions, I am in the AWS private VPC

{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/var/lib/transmission-daemon/downloads",
    "download-limit": 100,
    "download-limit-enabled": false,
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 0,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/var/lib/transmission-daemon/Downloads",
    "incomplete-dir-enabled": false,
    "lpd-enabled": true,
    "max-peers-global": 100000,
    "message-level": 1,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 10000,
    "peer-limit-per-torrent": 10000,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{8a0f2b7cf26898c19c236d65564027ae805f2f1eR27DS88L",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "transmission",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 1000000,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-limit": 100,
    "upload-limit-enabled": false,
    "upload-slots-per-torrent": 500,
    "utp-enabled": false
}

<img width="321" alt="Screen Shot 2022-11-16 at 5 00 38 PM" src="https://user-images.githubusercontent.com/5601825/202303995-9ee7f8a5-3a67-43de-a81b-52160b70b806.png">

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Transmission 2.92 (14714)

**Comment by vikaskoppineedi** [comment]
transmission is very bad, very hard. I tried downloading using qtorrent and rtorrent and it got downloaded in 2 mins.

**Comment by vikaskoppineedi** [comment]
closing the issue

**Comment by vikaskoppineedi** [comment]
@ckerr thanks for letting me know. I am trying to use transmission-daemon on ubuntu to basically add torrents. is transmission-cli and daemon updated in 4.0.0 beta?

**Comment by Pentaphon** [comment]
>Can you tell me where to download 4.0.0-beta.1 or higher?

https://transmissionbt.com/download look for 4.0.0 links.
