### ISSUE TITLE
Asynchronous DNS Lookup Functionality Breaks Network Connectivity

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [transmission/transmission#4205]
### What is the issue?

Apparently, restoration of asynchronous DNS lookups is the functionality which destroys network connectivity. Late October [23 October approximately] is when it began, and sometime thereafter this month it was fixed. It took much time for me to realise Transmission disconnects all other network traffic. I updated from build 8478 to build 8483 and the problem returned. I believe build 8482 contains the code which makes my internet unusable.

If it matters, I use the latest pre-release build of Private Internet Access VPN on Mac OS 13.1 latest public beta in conjunction with my NextDNS configuration. NextDNS runs as a daemon. To restore connectivity whilst Transmission runs, I must disconnect from the VPN and reconnect to the VPN, but within sixty minutes network connectivity is null.

### Which application of Transmission?

macOS app

### Which version of Transmission?

build 8482

**Comment by ckerr** [comment]
Give `main` a try now; #4201 may have fixed this.

**Comment by Rogue-Git-Dev** [comment]
A minute ago approximately I launched build 8487 and will report feedback regardless.

**Comment by Rogue-Git-Dev** [comment]
Within the past thirty minutes at this moment my internet connexion has become noticeably more latent. I know not if Transmission build 8487 is the culprit but it is abnormal behaviour withal.

**Comment by ckerr** [comment]
Please let me know if this continues in 4.0.2, which will be released later this week.

**Comment by Rogue-Git-Dev** [comment]
Having been writ by Charles Kerr on Monday 13 March 2023 at 23:44:44 -0500 ⬇️

> Please let me know if this continues in 4.0.2, which will be released later this week.
I believe this has not occurred for a while.

-- 
Brother J.

**Comment by ckerr** [comment]
Closing based on previous comment; but if it happens again, please open a new ticket :bowing_man:
