### ISSUE TITLE
WebUI Peer list too narrow

### ISSUE THREAD

**Issue by wsy2220** [transmission/transmission#4209]
### What is the issue?

IPV6 Addresses can overflow.

![2022-11-17-193220_914x583_scrot](https://user-images.githubusercontent.com/7259503/202435720-abc7129f-57dc-4d9d-85e7-e8d7f8d1c887.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

Latest main branch

**Comment by dareiff** [comment]
I think I'd like to take a stab at this. Perhaps an incoming PR today/this week.

**Comment by ckerr** [comment]
If there's not enough horizontal space for everything... I guess clipping IPv6 is probably the way to go.

**Comment by sfan5** [comment]
If you clipped the IPv6 to the /64 (`2001:db8:aa:bb:11:22:33:44` -> `2001:db8:aa:bb::`) that'd still leave it mostly meaningful, but you will have to implement IP parsing in JS and it's a poor workaround IMO. I also haven't seen other clients do this.

At the very least `overflow: hidden; text-overflow: ellipsis;` should be set on the IP field.

**Comment by killemov** [comment]
There is a tiny bit of white space to be taken from the Done percentage. Maybe even take out the %. The combining of Status and Address in a single column is weird and causes problems. If you run out of space you need to make decisions on what to show directly and what indirectly or simply just not. Remember those requests adding a country flag in there? My suggestion would be to lose the Client column and put that data in the title attribute of the Address cell. Also make the Status a separate column or even put that in the title attribute of the Done cell.
