### ISSUE TITLE
hope windows client can be natively supported

### ISSUE THREAD

**Issue by SESProMax** [transmission/transmission#4215]
### What is the issue?

Transmission on windows is really a bad experience. The client and serve always can not work in sync. When I closed the client and reopen it, it 's usually going to start a new one(a new process),and all the settings turns to default. I thought this might be the old process is not completely killed, so a new one is created.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 3.00

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/530
