### ISSUE TITLE
Question - Login with RPC API

### ISSUE THREAD

**Issue by Ryan747800B** [transmission/transmission#424]
Is it possible to login with a POST JSON request? I don't see any login command here https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt but I need a password protected Transmission.

**Comment by cab404** [comment]
It uses HTTP Basic authorization: https://www.httpwatch.com/httpgallery/authentication/

**Comment by mikedld** [comment]
@cab404 is right, just use basic auth. No separate login request is available at this time.
