### ISSUE TITLE
Daemon tries to create whole tree of folders up to download folder

### ISSUE THREAD

**Issue by cab404** [transmission/transmission#426]
I have file structure like this:
```
home
    cab404
        torrents
            .incomplete
```
`torrents` is set as downloads folder, and all permissions are set so debian-transmission has rwx in it. `.incomplete` is set as incomplete folder. When I try to download anything, this error appears:

```
[2017-10-27 14:18:49.888 MSK] Couldn't create "/home/cab404/torrents": Permission denied (utils.c:424)
[2017-10-27 14:18:49.889 MSK] Couldn't create "/home/cab404/torrents/in progress": Permission denied (fdlimit.c:345)
```
Obviously, daemon had no rw permissions in /home/cab404, but they shouldn't be necessary - I think folder existence and access should be first checked with rw test like `'echo something > targetfolder/test && cat test'` or something like that.

**Comment by mikedld** [comment]
Depending on your system, permissions handling may vary. For instance, see https://wiki.debian.org/Permissions (and in particular, "A note on path handling").

Transmission only tries to create directories that don't exist. If Transmission doesn't have permissions to check whether a directory exists or not, you'll get an error.

Feel free to reopen if you're certain this is a valid defect.

**Comment by cab404** [comment]
@mikedld I think it is a valid issue, since folders I specified are readable and writeable, and yes, I know how to handle permissions - I checked with `su debian-transmission -s /bin/sh -c 'echo test > folder/test'` to see if it works. And /home/cab404/torrents definitely existed, but debian-transmission is lacking read, write and execute in /home/cab404/ - thus it may be that your methods of testing whether folder exists or not are lacking.

**Comment by cab404** [comment]
@mikedld and I can't reopen this issue)

**Comment by mikedld** [comment]
The question is then whether the build you're using utilizes the `mkdirp` function or does the intermediate directories creation the hard way. In the former case there's not much we can do as it's a system function; in the latter case though we are in control of the algorithm and could try adjusting it.

Not sure if you could easily (without the debugger) see if the `mkdirp` function is being called, but you could at least check if transmission binary depends on it with something like

    # objdump -T /path/to/transmission-daemon | fgrep mkdirp

**Comment by cab404** [comment]
there are no calls to mkdirp
also, sorry for not specifying version of daemon - it's 2.84 (14307)

**Comment by cab404** [comment]
i can try strace-ing it, if you want

**Comment by mikedld** [comment]
Try grabbing artifacts from binaries.zip archive [here](http://trtc.mikedld.com/viewLog.html?buildId=26805&tab=artifacts&buildTypeId=Transmission_Sanity_GentooX8664autotools) and see if transmission-daemon there works for you. It may not due to build environment difference with your distro, in which case try building from source using the transmission-2.92+.tar.xz archive. Tests have failed on OpenIndiana but that's what I had in mind for the fix (could also be seen in e32ec70981d7f5af2672d456eeb0e216cc8f4449).

**Comment by cab404** [comment]
@mikedld first link doesn't work, prompting me teamcity login and password

**Comment by mikedld** [comment]
There's a "Login a guest" link there as well ;)

**Comment by cab404** [comment]
@mikedld i am not a clever man :D

It looks like it was my stupid mistake after all
thing is - I cd-d to downloads folder before setting o-x on it, thus i can no longer reference it absolutely,  but I may do whatever I want using relative links.
 
here's pretty much what happened:
```
cab404@cab404-pascal:~/Documents/test-daemon
$ mkdir immadork
cab404@cab404-pascal:~/Documents/test-daemon
$ cd immadork/
cab404@cab404-pascal:~/Documents/test-daemon/immadork
$ echo test > immadork
cab404@cab404-pascal:~/Documents/test-daemon/immadork
$ sudo chmod a-x ..
cab404@cab404-pascal:~/Documents/test-daemon/immadork
$ ls
immadork
cab404@cab404-pascal:~/Documents/test-daemon/immadork
$ ls ~/Documents/test-daemon/immadork
ls: cannot access '/home/cab404/Documents/test-daemon/immadork': Permission denied
cab404@cab404-pascal:~/Documents/test-daemon/immadork
$ cd ~/Documents/test-daemon/immadork
bash: cd: /home/cab404/Documents/test-daemon/immadork: Permission denied
```

sorry for the trouble!
