### ISSUE TITLE
Crash after first launch

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#4265]
### What is the issue?

After installation, I opened the transmission, added about 10 torrents, and closed it completely. Next, when I restart, I get a crash

``` 
  Problem Event Name:	APPCRASH
  Application Name:	transmission-qt.exe
  Application Version:	4.0.0.0
  Application Timestamp:	633f8da8
  Fault Module Name:	transmission-qt.exe
  Fault Module Version:	4.0.0.0
  Fault Module Timestamp:	633f8da8
  Exception Code:	c000001d
  Exception Offset:	0000000000100533
  OS Version:	6.1.7601.2.1.0.320.65
  Locale ID:	1049
  Additional Information 1:	bb1d
  Additional Information 2:	bb1d0fe8ea18ff488a3ba69f85c9932a
  Additional Information 3:	d670
  Additional Information 4:	d670cc6a0b897f3558974837191601c1
```

My hardware spec:
Notebook with
Windows 7 Embedded
Pentium Dual-Core
4gb DDR2

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0-beta.1

**Comment by ile6695** [comment]
Exception code `C000001d` means invalid instruction. This might hint towards (unlikely) corrupted binary or that the binary contains new instructions that are not supported by Pentium Dual-Core processor.

If you want to quickly get a working binary, you're likely to get it by building it yourself on the notebook.

**Comment by Petrprogs** [comment]
Ok, thanks!
