### ISSUE TITLE
Sort file list by name as standard

### ISSUE THREAD

**Issue by forteller** [transmission/transmission#430]
Hi. Thanks for a great piece of software I use all the time!

Whenever I double click a torrent in Transmission and go to the Files tab I never understand how the files are sorted. I almost always end up having to click on the Name column header to sort by name and be able to find the files I want to download and the ones I don't. This is unintuitive IMHO, and quite frustrating in the long run. Especially since the file list does not remember any changes I've made to it (sorting, size of columns) when I close the Properties window and open it again.

It would save me much time and frustration if it would be possible to change this behavior. Thank you so much again! :)

**Comment by momoe** [comment]
I thought this was just happening to me, but I too support this.

**Comment by ckerr** [comment]
Which GUI are you using -- gtk, qt, mac, or web?

**Comment by forteller** [comment]
gtk (Ubuntu)

**Comment by forteller** [comment]
This seems to have been fixed now, for me at least. So thank you very much! :)
