### ISSUE TITLE
Upload button is not visible on iphone

### ISSUE THREAD

**Issue by alexweb** [transmission/transmission#431]
Hello
When i go to web ui using safari on iphone 6s, all buttons are not clickable. If i request desktop version, they works. But if i click on the button to add a new torrent - there is no "Upload" button to select file to upload in popup. Only url might be entered. On ipad the Upload button presents. Is it possible to add Upload button on iphone version as well?
See screenshot:
![img_7969](https://user-images.githubusercontent.com/960052/32418746-0f1a0878-c278-11e7-97b8-7796cc71154a.PNG)

**Comment by mikedld** [comment]
See #320.

**Comment by alexweb** [comment]
Ah, ok. Do you know when 3.0.0 will be released?
