### ISSUE TITLE
GTK blocklist update dialog cannot be closed

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4311]
### What is the issue?

The close button on the dialog does not work. Interestingly, you can get around it by closing the main preferences window.

### Which application of Transmission?

GTK+ app on Ubuntu 22.04.1

### Which version of Transmission?

4.0.0-beta.2.dev (0e193a0cb3)

**Comment by ckerr** [comment]
@mikedld could you take a look?
