### ISSUE TITLE
Cannot Connect To HTTPS Trackers Using Cloudflare On Transmission For Windows

### ISSUE THREAD

**Issue by ultimate11** [transmission/transmission#432]
Hi there, I've been using a tracker that uses cloudflare, the tracker is under HTTPS and for some reason I can't seem to get any downloading on the tracker. A friend of mine was suggesting it was related to TLS 1.2, could it be due to that? I run Windows 7, I did try to enable TLS 1.2 on the system using a registry hack, but even doing that didn't work. Hopefully you guys can figure this out.

**Comment by TheAntimist** [comment]
@ultimate11 Seems to be related to #446

**Comment by ckerr** [comment]
Yep agreed, this looks like a dupe of #446.
