### ISSUE TITLE
Qt: Issue with placeholder in german translation

### ISSUE THREAD

**Issue by joshirio** [transmission/transmission#433]
![screenshot_20171108_112236](https://user-images.githubusercontent.com/12795018/32543919-4ca8e92e-c477-11e7-88fb-251d2610dffb.png)

Issue:
`&Ln connected peers`

Transmission-qt 2.92

**Comment by mikedld** [comment]
Thanks. Looks like this has already been fixes on [Transifex](https://www.transifex.com/transmissionbt/transmissionbt/).

**Comment by kelke** [comment]
this is still a thing
