### ISSUE TITLE
assertion failed: io->socket.is_valid()

### ISSUE THREAD

**Issue by Deathcow** [transmission/transmission#4368]
### What is the issue?

Recent builds (tested again with 30d3ce872f45d2e8e49b0a4ba18fba972c9ab619) crash after a short while with

```
assertion failed: io->socket.is_valid() (/var/tmp/portage/net-p2p/transmission-9999/work/transmission-9999/libtransmission/peer-io.cc:816)
[1]    24286 IOT instruction  transmission-daemon --log-level=info --logfile  -f
```

likely culprits
https://github.com/transmission/transmission/commit/9a5d9a0ba2203bee54ec82212c5077210881a6fb
https://github.com/transmission/transmission/commit/22a3a5db25cf990bf9406671d5bd8e1a50d0edc9

older build from 2022-12-03 (0e193a0cb3) is stable.

environment:
Gentoo
linux 6.1.0
arm64

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

30d3ce872f45d2e8e49b0a4ba18fba972c9ab619

**Comment by ckerr** [comment]
Thanks for the report. Is this still happening in https://github.com/transmission/transmission/commit/e6d75a4b7753f1a1228fb2870eb465c81df3a03b or  newer?

**Comment by Deathcow** [comment]
Hi @ckerr : Seems to be running stable with https://github.com/transmission/transmission/commit/e6d75a4b7753f1a1228fb2870eb465c81df3a03b for the last ~2 hours.

**Comment by ckerr** [comment]
@Deathcow I'm going to close this issue for the time being but please do reopen / refile a new issue if anything turns up. Thank you!
