### ISSUE TITLE
Windows client adds "C:" to the start of download location.

### ISSUE THREAD

**Issue by DanielDC88** [transmission/transmission#437]
My settings: https://i.imgur.com/EGIvhqW.png
What comes up when I add a torrent: https://i.imgur.com/3svdfEi.png

As you can see, it has added "C:" to the start. This results in torrents coming up with an error about not being able to find the storage. This didn't used to happen in older versions, but I'm not sure when it was broken.

**Comment by mikedld** [comment]
Please search before creating new issues. See #236, #404.
