### ISSUE TITLE
In Light mode, selected torrents are hard to read because text is "grey on dark blue" [macOS]

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#4375]
### What is the issue?

In Light mode, selected torrents are hard to read because text is "grey on dark blue".
![Capture d’écran 2022-12-16 à 11 09 07](https://user-images.githubusercontent.com/839992/208013441-4a778a26-df89-4854-ac2f-80890a1fb5a0.png)
![Capture d’écran 2022-12-16 à 11 08 56](https://user-images.githubusercontent.com/839992/208013451-b359a303-ad6a-4a7e-bf95-13634f854241.png)

When selected, I can hardly read the Size, Time remaining and other peer stats.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.2.dev (578099bf1c)

**Comment by GaryElshaw** [comment]
I thought it was just me, but this is happening in Dark mode as well. The whiteness of the font contrast has changed when the torrent is highlighted/selected in the data section.

![SCR-20221216-moy](https://user-images.githubusercontent.com/69029666/208014641-30f3049b-93a1-4248-af03-b1cf0f733761.png)

**Comment by GaryElshaw** [comment]
@sweetppro Any ideas?

**Comment by sweetppro** [comment]
@GaryElshaw to be honest I havnt noticed...
I'm using green for my highlight colour.

Its probably not hard to fix.
ill take a look now

**Comment by GaryElshaw** [comment]
Thank you!

**Comment by GaryElshaw** [comment]
By the way, that screenshot of mine is a customisation i've made to increase the main window font size to 10 in my builds. I'd love to know what you both think, but also if you both have your own?
