### ISSUE TITLE
macOS notifications have gone

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4384]
### What is the issue?

I'm currently using cmake to build, i know @Coeur was working on the notifications code for macOS, and don't know if this is related, but i just realised i nolonger get any notifications for completed downloads or completed seeds.

### Which application of Transmission?

macOS app

### Which version of Transmission?

Beta 2

**Comment by Coeur** [comment]
Go to system Settings > Notifications > Transmission and configure it from here.
![Capture d’écran 2022-12-17 à 12 19 57](https://user-images.githubusercontent.com/839992/208224552-3e592056-43a1-49d0-9606-1fe09b5ca629.png)

Notifications are working fine for me when:
- building from Xcode
- building from cmake

So we'll need you to double check your system settings, and the precise way that you got your app built.

Lastly, #3040 was originally meant for Transmission 5 as risky precisely for issues like this... I'm happy that it got merged early, but now signing issues need to be handled perfectly.

**Comment by Coeur** [comment]
![Capture d’écran 2022-12-17 à 12 37 28](https://user-images.githubusercontent.com/839992/208225309-5e709be2-a0cd-48ee-9b08-e3b5b2ee543b.png)

**Comment by GaryElshaw** [comment]
The notifications area had picked up an earlier version that i had renamed 'transmission-stable'. I've removed it and opened the latest build, gone to settings and opened the notification area in system settings, but nothing is appearing :-(

I'll keep an eye on it.

**Comment by Coeur** [comment]
First time, it will probably ask if you allow notifications.
It's by default in "automatic" preview mode, so will show when Transmission is in the background, but not when in the foreground. If you want the notifications even when app is in foreground, then in system settings > notifications > transmission > configure the previews to "always" (penultimate settings)

**Comment by GaryElshaw** [comment]
Oh, i mean it's not appearing in the system settings -> notifications area at all.

**Comment by Coeur** [comment]
Download gimp, wait 2 minutes for it to complete: request to show notifications should popup.

**Comment by Coeur** [comment]
If it doesn't, then possibly an Apple bug with this workaround:
>First, open the Finder app.
Next, click Go and then select Go to Folder.
Now, type the following pathname on the box and click Go:
~/Library/Preferences/com.apple.ncprefs.plist
Look for the file named com.apple.ncprefs.plist and drag it to Trash.
Restart your Mac.
Finally, open the Notification Center again and test it.
Unfortunately you have to re-authorise all the apps one by one as they start to request permission

Source: https://www.reddit.com/r/MacOS/comments/ttudhv/comment/ie5oo05/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by GaryElshaw** [comment]
Sadly, that didn't work either. I'll try an Xcode build.

**Comment by Coeur** [comment]
Video of a build with ninja with zero issues to get the Transmission notifications added to the system settings.

https://user-images.githubusercontent.com/839992/208227530-add0a06d-c839-4a14-9d88-b165bec33100.mov

**Comment by Coeur** [comment]
So I don't think it's a Transmission issue.

1. Make sure you're on latest macOS (13.1 (22C65)).
2. If you can't find Transmission in the Notification settings, then try the Reddit workaround about deleting com.apple.ncprefs.plist and restarting your Mac.
3. If it's still failing, report it to Apple with Feedback Assistant.

**Comment by GaryElshaw** [comment]
Sidenote: After building with ninja, the pop-up asking if i wanted to donate appeared. No notifications queries. Something's up with my setup.

**Comment by Coeur** [comment]
- move the Transmission build folder to Trash
- delete the Xcode Derived Data folder
- verify that all your third-party submodules don't have files modified locally

**Comment by Coeur** [comment]
In Xcode, put a breakpoint on the line after `NSLog(@"UserNotifications not configured: %@", error.localizedDescription);`, and check what is the error (or if no error, check if granted or not).

**Comment by GaryElshaw** [comment]
Thanks Antoine, i'll have another go when i get out of qt purgatory.
