### ISSUE TITLE
Transmission Web UI RPC 409 Error

### ISSUE THREAD

**Issue by ManavSarkar** [transmission/transmission#4385]
### What is the issue?

When I installed Transmission v3.0 in Windows 11, I checked the inspect panel where I found the following error.
![image](https://user-images.githubusercontent.com/42129636/208228204-75aabde7-7cdf-41c5-a0fb-d05e0d383bc5.png)
This error appears always and I tried a number of fixes including changing of the PORT number, refreshing the website, and using LinuxMint for the very same purpose of fixing this error but in vain. Please check and fix this error.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

v3.0

**Comment by ckerr** [comment]
The web client has been rewritten for 4.0.0, so please upgrade to >= 4.0.0-beta.2 and see if the problem persists.

**Comment by ManavSarkar** [comment]
I have upgraded to the beta version but the problem still persists.
![image](https://user-images.githubusercontent.com/42129636/208279116-a66091f2-abe7-458c-8f2a-1c4111f3e51d.png)
And this time it throws the same error 4 times.

**Comment by ManavSarkar** [comment]
Actually when I explored the Network tab, I saw the following, it may help you.

**Comment by killemov** [comment]
AFAIK This error is business as usual. (Maybe not many consecutive times, but still ...) In the 409 response Transmission puts a new "X-Transmission-Session-Id" in the header which the clients needs to use in future requests as some form of security.
