### ISSUE TITLE
Keyboard Shortcut for "Copy Magnet Link to Clipboard" Ctrl+C

### ISSUE THREAD

**Issue by sarvex** [transmission/transmission#439]
It would be nice if we can have a CTRL-C key binding for copy magnet link to keyboard, as it would improve my workflow when torrents are invalidated on disk full state. 

I can also submit a pull request for the same. I am just looking for consensus.

**Comment by mikedld** [comment]
Seems like a nice idea. I'd welcome a PR, as long as it doesn't break input in other text fields (e.g. filter), i.e. only works when torrents list is in focus.

**Comment by RobFog** [comment]
Does the pull request add support for Mac only?
