### ISSUE TITLE
qt crash when pasting blocklist URL

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4396]
### What is the issue?

Immediate crash when pasting a URL into the blocklist field.

[qt-crash.txt](https://github.com/transmission/transmission/files/10253127/qt-crash.txt)

Edit: This appears to be a qt5 bug; working fine when built with qt6.

### Which application of Transmission?

Qt app on macOS

### Which version of Transmission?

Beta 2

**Comment by ckerr** [comment]
I think this is also fixed by the code @Coeur did for #4451.

@GaryElshaw if this is still crashing for you in `main` please file a new issue with an updated crash report :bow:
