### ISSUE TITLE
transmission-qt issues (omnibus version)

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4398]
### What is the issue?

I thought about filing individual issues, but, well, there are quite a few of them, and they're things that i can't fix (you all remember i'm not a coder eh? I just have some half-decent/half-baked deduction skills). The below is notes from my testing on macOS, Manjaro Gnome and Ubuntu LTS using qt@5 on macOS and qt@6 on Linux while messing around with #4376.

1. Preferences are not being saved between sessions on macOS.
2. Crash when pasting blocklist URL (macOS) #4396 
3. In the last 24 hours, accessing settings from the file menu has been intermittent. It's almost as if a background process is at work after start before you can access it.
4. Somewhere, if it hasn't already been, i need to document that qt@6 requires the qt SVG package to build transmission-qt with svg support, correctly. It's not part of core, and qt6 has about 150 odd packages that can be individually installed.
5. There are an array of visual glitches:
    A. Dark themes on Manjaro, Ubuntu, and macOS are a major issue that is going to need attention. My advice would be to tackle this with macOS, Adwaita (and maybe Papirus) on Linux, and whatever the default theme is on Windows. Trying to make these work across all themes and platforms would be an epic nightmare.

    B. The thin blue line: Almost the same colour as when a torrent is highlighted, i'm guessing it's some weird carry-over artefact. Seen at the top of the main window, but also in 'Files' for some reason (screenshot macOS). See more below where you can see the line, blue on blue.

![SCR-20221218-q8b](https://user-images.githubusercontent.com/69029666/208283898-9385857a-ecbf-40d5-95cb-f097765b53da.png)

![SCR-20221218-q9p](https://user-images.githubusercontent.com/69029666/208283904-8607f9ac-1803-48d6-ab4b-97314d39a1b1.png)

    C. Even in Light mode, the contrast between text and background needs work when torrents are inactive.

macOS
![SCR-20221218-m4a](https://user-images.githubusercontent.com/69029666/208284637-1d4de777-8477-4a4d-af0c-585906a7e198.png)

    D. Same goes for the icons in the main menu bar in Ubuntu.

Ubuntu
![ubuntu-qt](https://user-images.githubusercontent.com/69029666/208284768-fdd01dc3-c046-47de-a753-d01334d1a25e.png)

But check out how balanced dark mode can be (Manjaro Gnome w/ Wayland 43.1).

![Screenshot from 2022-12-18 20-48-01](https://user-images.githubusercontent.com/69029666/208288047-fea403e6-3c7d-425d-bc42-9deb3cb27ff3.png)

### The good news

With active torrents (Light), doesn't this look better than what we have had?

![SCR-20221218-mex](https://user-images.githubusercontent.com/69029666/208284921-4e7741ae-a6ba-4836-8d81-d1f5bb734db3.png)

Dark

![SCR-20221218-mel](https://user-images.githubusercontent.com/69029666/208284990-dedb6bfd-1fb4-4b73-8cfc-f649f7271897.png)

Properties (Light and Dark)

![SCR-20221218-mfb](https://user-images.githubusercontent.com/69029666/208285034-3897bfa9-4f75-416a-b78b-93b72bbf19c5.png)

![SCR-20221218-mfn](https://user-images.githubusercontent.com/69029666/208285045-c53eda16-60c5-4071-9658-b08d932ac419.png)

As you can see, I've hit a brick wall getting my icon changes to correctly compile in Ubuntu and Manjaro. 

Things i've tried:

Primarily wrangling with MainWindow.cc and MainWindow.ui (i suspect that if that's not where my problem lies, then it might be qt6 itself since the issue isn't happening on macOS. I noticed in the gui of qt designer the option to hard link the icons. Didn't work there, or by emulating whomever's code via text editing. For example,

`<iconset>
           <normaloff>:/icons/ratio.svg</normaloff>:/icons/ratio.svg</iconset>`

Because Dark mode is my default, i thought i'd reverse the icons. It might be inelegant, but giving qt users the choice of a default light or dark set of icons might be a nice workaround.

![SCR-20221219-7jp](https://user-images.githubusercontent.com/69029666/208308905-5e57866d-2721-46a6-9e58-1b7fbff5f581.png)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

Beta 2

**Comment by ckerr** [comment]
No omnibus tickets please; they are impossible to manage. The issue cannot be closed until every last problem is fixed. And then separating what’s open from what’s closed requires digging through pages of text.
