### ISSUE TITLE
transmission-qt cannot be built on macOS with Homebrew qt@6

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4405]
### What is the issue?

I tried upgrading qt@5 with qt@6 today. Here are the dependencies it installs, anything missing?

==> Dependencies
Build: cmake ✘, ninja ✘, node ✘, pkg-config ✔, python@3.10 ✘, six ✘, vulkan-headers ✘, molten-vk ✘
Required: assimp ✔, brotli ✔, dbus ✔, double-conversion ✔, freetype ✔, glib ✔, hunspell ✔, icu4c ✔, jasper ✔, jpeg-turbo ✔, libb2 ✔, libmng ✔, libpng ✔, libtiff ✔, md4c ✔, openssl@1.1 ✔, pcre2 ✔, sqlite ✔, webp ✔, zstd ✔
==> Requirements
Build: Xcode ✔

Here is the error i got:

In file included from /Users/garyelshaw/Documents/GitHub/transmission-primary/build/qt/transmission-qt_autogen/mocs_compilation.cpp:3:
/Users/garyelshaw/Documents/GitHub/transmission-primary/build/qt/transmission-qt_autogen/EWIEGA46WW/moc_Application.cpp:16:2: error: "This file was generated using the moc from 5.15.7. It"
#error "This file was generated using the moc from 5.15.7. It"
 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [qt/CMakeFiles/transmission-qt.dir/transmission-qt_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [qt/CMakeFiles/transmission-qt.dir/all] Error 2
make: *** [all] Error 2

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

Beta 2

**Comment by ckerr** [comment]
I haven't tried Qt 6 on macOS, but according to #2069, Qt 6 is supported...

> In file included from /Users/garyelshaw/Documents/GitHub/transmission-primary/build/qt/transmission-qt_autogen/mocs_compilation.cpp:3:

This looks like something that might have been generated into your build directory before upgrading to Qt 6, and now it's still laying around & getting picked up by the build. What happens if you delete the `build` directory and then retry so that _all_ the build files get regenerated from scratch when Qt 6 is installed?

**Comment by GaryElshaw** [comment]
Thanks Charles. Yeah, i thought so too, but just tried again with a clean build directory. Here's a more fulsome look at the error output. Thoughts @mikedld?
 
[qt6-build-errors.txt](https://github.com/transmission/transmission/files/10299344/qt6-build-errors.txt)

**Comment by ckerr** [comment]
Just brainstorming here... If you're not using Qt on this box for anything other than Transmission, and if you've got Qt5 and Qt6 both installed, what happens if you uninstall Qt5?

Happy holidays!

**Comment by mikedld** [comment]
Works fine here:
```
brew install qt@5 qt@6
cmake -B obj.qt5 -S src -G Ninja -DENABLE_QT=ON -DUSE_QT_VERSION=5 -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5
cmake --build obj.qt5 --target transmission-qt
cmake -B obj.qt6 -S src -G Ninja -DENABLE_QT=ON -DUSE_QT_VERSION=6 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
cmake --build obj.qt6 --target transmission-qt
```

Maybe your build directory isn't as clean as you think it is after all.

**Comment by GaryElshaw** [comment]
Thanks @mikedld. So, what i've discovered is that building with ninja works, but building with make does not. Yep, no dice with 10.13 as the target.

**Comment by GaryElshaw** [comment]
Wow, something i hadn't noticed before, building with ninja doubles the size of the macOS binary.
