### ISSUE TITLE
[Enhancement] RPC listen on an unix socket 

### ISSUE THREAD

**Issue by 92kz1h** [transmission/transmission#441]
This is a follow up on [Trac#5265](https://trac.transmissionbt.com/ticket/5265) (and the duplicate [Trac#5895](https://trac.transmissionbt.com/ticket/5895)).

The goal is to allow transmission to bind to a Unix Socket Domain (USD) rather than only to a network interface and a port. There are lots of usecases for this, some are discussed in the aforementioned trac issues. I believe this feature helps supports the stance that the RPC should not be public facing.

Since the above tickets were introduced it appears both upstream dependants have been updated to support USD:

* `libcurl` - Added in 7.40.0. Comment with more details in Trac#5895.
* `libevent` - Looks like it was added in 2.1 but I don't know enough about this library to confirm.
  - <https://www.monkey.org/~provos/libevent/doxygen/evhttp_8h.html#7c7adf584dd0c6376212f29bf62738fb>.
  - This ticket and PR appears to suggest partial implementation?: <https://github.com/libevent/libevent/issues/537> and <https://github.com/libevent/libevent/pull/322> (originally <https://github.com/libevent/libevent/pull/320>).

In terms of how to identify a USD - it appears people are copying the [nginx pattern](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) `http://unix:/var/run/transmission/transmission.sock:/path/`. Including the path may or may not be less implementation work - it makes no difference for reverse proxies as they can rewrite URLs but I'm not sure if the path impacts other tools negatively.

**Comment by limakzi** [comment]
@92kz1h Thank you for this request. Is there any progress on this ticket?
The main use-case would be to increase local machine security.

**Comment by lvella** [comment]
Another useful application is to expose RPC outside of a Linux network namespace, which one might use to restrict transmission to a VPN.

**Comment by malte-v** [comment]
Initial attempt here: #1673

**Comment by ju1m** [comment]
> Another useful application is to expose RPC outside of a Linux network namespace, which one might use to restrict transmission to a VPN.

Note that you can also use [systemd-socket-proxyd](https://www.systutorials.com/docs/linux/man/8-systemd-socket-proxyd/#lbAI) to reach an `rpc-bind-address` in a private network namespace.

**Comment by ckerr** [comment]
Fiexd by https://github.com/transmission/transmission/pull/2574
