### ISSUE TITLE
Transmission-Daemon will not access anywhere other than home

### ISSUE THREAD

**Issue by drstee** [transmission/transmission#4429]
### What is the issue?

I am trying to set Transmission-Daemon to download to my **/dev/sda2** EXT4 drive.

It is currently mounted to **/media/user/10tb**

No matter how I set permissions. Transmission-Daemon reports permission denied in the web interface.

I have set the entire directory structure to allow read & write for the user, group and other (777). However, it still won't work.

If I change the download directory back to **/home/user/Downloads/Transmission** it works fine.
Here is the permission for this folder:
drwxrwxr-x  2 user debian-transmission   4096 Dec 21 10:02 Transmission

I have even tried completely duplicating the permission settings from **/home/user/Downloads/Transmission** to **/media/user/Downloads/Transmission** and it still reports permission denied.

Currently the directory has the following permission set:
drwxrwxrwx 2 user debian-transmission 4096 Dec 21 10:58 Transmission

As you can see this is more permissive than my home folder. Yet, I still receive permission denied.

Please help.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00

**Comment by mikedld** [comment]
If you have incomplete directory enabled, its access may need adjustment as well. It seems to be a long-standing issue that Transmissoin isn't clear enough which path it can't access.

**Comment by drstee** [comment]
Incomplete directory is disabled. I have also tried enabling it and setting permissions. Unfortunately, this did not help so, I disabled the feature again

**Comment by mikedld** [comment]
You didn't specify the version you're using. This is important otherwise it wouldn't be in the template, so please amend your original post.

Please also attach a screenshot (with sensitive information redacted) or describe in more detail where exactly you're seeing this error, and what are the actions that lead to it.

**Comment by drstee** [comment]
No problem. Done.

I use the transmission web interface to upload torrents/magnets to transmission-daemon. See below:

![TransmissionOpenDialog](https://user-images.githubusercontent.com/31507258/208938158-40321a21-1a85-4ec6-9b28-bf0c56ac7260.png)

The trouble is, I get the below error when downloading to the following location: **/media/user/10tb/Downloads/Transmission**

![TransmissionDownloadError](https://user-images.githubusercontent.com/31507258/208937052-6973fdc3-d57e-4ad4-bdf9-5a560b09c946.png)

Here are the folder permissions for that directory:

![MediaPermission](https://user-images.githubusercontent.com/31507258/208937329-36223571-1bc1-4874-a3c3-17bfb72a69ec.png)

I do not get the same problem when downloading to my home folder:

![TransmissionDownloadHomeDirectory](https://user-images.githubusercontent.com/31507258/208937511-2862e110-4aa2-4115-93cc-4fec9ff39a69.png)

Here are the folder permissions for my home directory (**/home/user/Downloads/Transmission**):

![HomePermission](https://user-images.githubusercontent.com/31507258/208937638-d3f4c1e7-9a38-4204-8af8-7e39613a006f.png)

As you can see the above permission are identical. Yet transmission-daemon cannot access the media location stored on **/dev/sda2**. See mount point in fstab:

![MediaMountPoint](https://user-images.githubusercontent.com/31507258/208937995-1f8ede10-510a-498b-883f-1f8b80007885.png)

Please let me know if there is anything else I can provide to help.

Thanks

**Comment by drstee** [comment]
Hi,

I have just discovered that mounting disks to the /mnt location instead of /media does not have this issue.

Thanks

**Comment by ckerr** [comment]
Thanks for the followup!
