### ISSUE TITLE
How can we have macOS nightly builds crash logs with debug symbols?

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#4442]
### What is the issue?

@mikedld, see the discussion in #4371: it seems that builds from https://build.transmissionbt.com/job/trunk-mac/ are not symbolicated enough for debugging crashes, which is an issue for investigating regressions during development.

### Which application of Transmission?

macOS app

**Comment by mikedld** [comment]
Not sure what you mean, the symbols are already there: ![imagen](https://user-images.githubusercontent.com/298203/209146511-5b5752cf-55fa-4b38-a77d-51e98148bc08.png)

**Comment by Coeur** [comment]
Ah, separately... I see. So all we have to do is recombine them for each crash log?
Is there an easy way to do it?

**Comment by Coeur** [comment]
I found this on the web:

1. In a folder, put these 3 things:
- the crash report file (a text file)
- YourApp.app.dSYM
- YourApp.app

2. Run the symbolicate.rb script from https://gist.github.com/dceddia/4c2cd2b32a1c9a6029fbc996a05f4a97

**Comment by Coeur** [comment]
Well, can't access old dSyms. Will try again next time there is an unsymbolicated crash report.
