### ISSUE TITLE
2.92 release notes link (inside 2.84)  points to "empty" page

### ISSUE THREAD

**Issue by ProBackup-nl** [transmission/transmission#445]
> 2.9 App Changes
> Improved compatibility with modern OS X
> Several bug fixes
> We're still alive!
> Transmission requires OS X 10.7 Lion or better.
> 
> For a full list of changes, click here.

"click here" points to https://trac.transmissionbt.com/query?milestone=2.92&group=component&order=severity which is "empty".

**Comment by mikedld** [comment]
It is unfortunate that we didn't document the OSX.KeRanger.A "fix" in Trac (which was the only change in 2.92), as could be seen [here](/transmission/transmission/releases/tag/2.92), but the link itself is correct. Let's just leave it as is for now and wait for 3.00.
