### ISSUE TITLE
[macOS] udp bad file descriptor

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4456]
### What is the issue?

Getting lots of these warnings in the Message Log

```
2022-12-23 19:37:20 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to x.x.x.x: 9 (Bad file descriptor)
```

All to different IPs

### Which application of Transmission?

macOS app

### Which version of Transmission?

3cee8bae36

**Comment by GaryElshaw** [comment]
Duplicate of #4406

**Comment by robd003** [comment]
I'm see these with IPv4 addresses too, not just IPv6

**Comment by GaryElshaw** [comment]
Thanks @robd003, it's excellent confirmation it's not just my setup!

**Comment by ckerr** [comment]
Closing as duplicate of #4406
