### ISSUE TITLE
Can't connect to HTTPS tracker.

### ISSUE THREAD

**Issue by NohaTech** [transmission/transmission#446]
Hi,
I'm running Transmission on Windows 10 and Windows server 2016.
And the issue are the same on both machines I can't connect to a tracker that have HTTPS connection after some googling I did find out that I'm not the only one.

This is a big issue, I was forced to go over to Deluge instead but please fix this asap so I can go back to Transmission.

**Comment by Cormak** [comment]
The current 2.92 build isn't actually stable on Windows, which is why it's not on the Transmission homepage. We need the devs to create an actual stable Windows release because your bug has been reported for well over a year now.

**Comment by opicron** [comment]
Tried the latest stable nightly https://build.transmissionbt.com/job/trunk-win32/lastSuccessfulBuild/arch=x64,label=pepito-win10/. If this is the latest 2.92+ stable its not working yet.

**Comment by bhunt89** [comment]
i've the same problem.
i remember some nightlies (i think from before last summer) fixed the issue!
sadly enough we can't download old nightlies anymore on windows, and so far i've not been able to build it myself to check where exactly it broke

**Comment by hatwerk** [comment]
I'm having the same issue as well.
Tested with with 32 and 64 bit client, both latest stable + latest nightly.
Tested on both Windows Server 2016 and Windows 10.

**Comment by NNpranav** [comment]
Windows 10, 2.93 stable release. Still have the same issue. Torrents with HTTPS trackers do not work. It is able to get a list of peers/seeds but does not connect to them, effectively stalling the torrent at 0%.

Same problem with Transmission QT and daemon. The same torrents work fine with my Linux box running an older version of Transmission daemon.

**Comment by FinlayDaG33k** [comment]
- `Ubuntu 16.04.4, 2.84`: Gets peer list, doesn't connect to peers
- `Windows 10, 2.93`: Gets peer list, doesn't connect to peers
- `Windows 10, 2.92`: can't connect to tracker
- `FreeNAS9 jail, 2.93`: can't connect to tracker

all using the same HTTPS tracker (My BitTorrent machines can connect to the tracker perfectly fine and download)

**Comment by Cormak** [comment]
It's amazing that this hasn't been fixed since the 2.93 release.

**Comment by Cormak** [comment]
@NohaTech @opicron @robince @bhunt89 @hatwerk @NNpranav @FinlayDaG33k @mikedld 

This appears to be fixed in 2.94 Windows 64bit.

**Comment by NNpranav** [comment]
Nice, will give it a shot in a couple of hours. Thanks for the update!

**Comment by Scrxtchy** [comment]
bless your face

**Comment by NNpranav** [comment]
No update. Same behavior. Connects to tracker and gets list of peers but does not connect to them. Tried debug logging with transmission-daemon, same behavior.

Here are the relevant bits:

> [2018-05-02 19:36:13.975] [Name_Of_Torrent] Announcing to tracker (C:\Users\vagrant\src\libtransmission\announcer.c:1554)
[2018-05-02 19:36:13.975] [Name_Of_Torrent] Got 13 peers from tracker (C:\Users\vagrant\src\libtransmission\torrent.c:565)
[2018-05-02 19:36:13.975] [Name_Of_Torrent] Announce response contained scrape info; rescheduling next scrape to 1800 seconds from now. (C:\Users\vagrant\src\libtransmission\announcer.c:1152)

No movement on the torrent after that. The 13 peers/seeds it shows is the correct amount as per the tracker's info.

**Comment by Scrxtchy** [comment]
Having no problems 
![image](https://user-images.githubusercontent.com/12771982/39528120-96346478-4e66-11e8-88c8-e837c6420d49.png)

**Comment by NNpranav** [comment]
Interesting. Can you comment on what you used (OS, build, 32 or 64 bit, etc)

The behavior has not changed for me...

**Comment by Scrxtchy** [comment]
Fresh install, pointed the home directory back to the files I used 4-5 month ago
Windows Server 2016, 64 bit

**Comment by NNpranav** [comment]
The 64 bit is the transmission build, I assume?

**Comment by Scrxtchy** [comment]
yes

**Comment by NNpranav** [comment]
Figured it out. Enabling µTP causes the aforementioned issues. The moment µTP was turned off, the daemon was able connect to peers and start downloading. Not sure if that should be logged as another issue or whether we should use this bugreport to discuss that.

As of now, disabling µTP either by manually editing the settings.json or through the QT-based GUI fixes the issue.

**Comment by Cormak** [comment]
@NNpranav very interesting! Glad you found that because I overlooked it since I never enable uTP in the first place.

**Comment by Alhaitham** [comment]
Windows 10 Enterprise 10.0.14393 Build 14393

https

![clipboard02](https://user-images.githubusercontent.com/7531458/50045463-e301fd00-009b-11e9-8224-78f5097fa9a8.png)

http

![clipboard04](https://user-images.githubusercontent.com/7531458/50045464-e6958400-009b-11e9-97bb-16934b743f6c.png)

**Comment by Alhaitham** [comment]
Windows 10 Enterprise 10.0.14393 64bit

Transmission-2.94+-r4671276450-x64 Daemon

Transmission Remote GUI 5.15.4

HTTPS

![clipboard02](https://user-images.githubusercontent.com/7531458/50045463-e301fd00-009b-11e9-8224-78f5097fa9a8.png)

HTTP

![clipboard04](https://user-images.githubusercontent.com/7531458/50045464-e6958400-009b-11e9-97bb-16934b743f6c.png)

**Comment by Alhaitham** [comment]
Same with

Transmission-2.94+-r4a4233feae-x64

![clipboard02](https://user-images.githubusercontent.com/7531458/51051119-80891780-15db-11e9-8edc-67ff81062927.png)

**Comment by javajox** [comment]
"Announce error: Could not connect to tracker"
transmission-2.93-amd64 in FreeNAS jail

**Comment by opicron** [comment]
Some merge went south I guess. In my current version 2.94 (d8e60ee44f) ssl works, but in the new build it does not :(.

**Comment by perHub** [comment]
Hello, I wanted to share my experience on this issue, as others noted it seems that using the pre-built binaries available on Jenkins won't be able to connect to HTTPS trackers, however if curl is built to use the "WinSSL" backend (Schannel) and transmission is built against it, then it will be able to connect to those trackers. On the other hand if curl is built to use OpenSSL as the backend then it will break, at least that's what happened in my case.

**Comment by Alhaitham** [comment]
It would be great if someone can share a build for windows that has this issue fixed

**Comment by perHub** [comment]
I can share mine, however it's x86 because I use it on a 32 bit Windows PC: [https://drive.google.com/open?id=1K1F6NprpWhGh0vIyLdvzY8x-fXSRKXda](url). Also here is a rar with all the libraries it uses, I share it this way because the created msi does not contain all of them (I think that's because I'm building against openssl 1.1): [https://drive.google.com/open?id=1_-9ARPt4JodoLyfFBu-rq58d0yLp4xqF](url)

**Comment by Alhaitham** [comment]
@perHub

Will try it with windows 10 64bit

Thanks

**Comment by Alhaitham** [comment]
@perHub

Installed it and replaced the libs and it's working

![Clipboard03](https://user-images.githubusercontent.com/7531458/55281415-cd5bcf00-533c-11e9-824c-cb604e3d9229.png)

Thanks again

**Comment by perHub** [comment]
I'm glad it works for you too, it's a bit weird this issue doesn't get more attention since it's pretty annoying, I guess HTTPS trackers are not still that popular? dunno ¯\_(ツ)_/¯

**Comment by ryannathans** [comment]
I have the same issue on the latest x64 nightly Transmission 2.94+ (a440981571)

**Comment by markstahler** [comment]
Also looking for a fix. @perHub build did not seem to work for me on Windows Server 2019 as the installer failed on registering the Transmission service. Was previously using the x64 version of 2.94+.

**Comment by perHub** [comment]
I made an up-to-date build with the proper libraries in the installer, it should work now: https://drive.google.com/open?id=1oBBvIfJ95EJ_wlP0mMpXswnPqs5LktvM

As a I said in one of my previous posts this build works because libcurl is built to use the WinSSL backend (the commandline is nmake /f Makefile.vc mode=dll VC=15 WITH_SSL=dll)
@mikedld I assume the curl library being used to build transmission for Windows in jenkins uses openssl as the backend, would it be possible to change this so the official nightlies won't have this issue?

**Comment by mikedld** [comment]
Thanks to everyone involved. If someone is okay with trying the latest master build ([x86](https://trtc.mikedld.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Transmission_WindowsX86&tab=artifacts&guest=1), [x64](https://trtc.mikedld.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Transmission_WindowsX64&tab=artifacts&guest=1)), please do and report back if you notice any issues with the fix.

**Comment by markstahler** [comment]
@mikedld Hi Mike, I just tried the x64 version you posted recently but unfortunately it hasn't worked made any difference on my Windows 2019 Server. Thanks

**Comment by mikedld** [comment]
@markstahler, I'm afraid it's an issue (or rather a feature) of Windows Server itself. If you run `certmgr.msc` you'll notice that the certificate stores there have way less certificates than non-Server Windows edition. Not even switching to WinSSL as cURL backend will help with that; I guess the expectation here is that you'll import the certificates you miss but trust yourself.

**Comment by dmpavlidis** [comment]
Apologies for coming back to this. So there is no solution for running transmission on Windows server 2022?

**Comment by JessieSalgado** [comment]
> Apologies for coming back to this. So there is no solution for running transmission on Windows server 2022?

Look at the Root CA that signed the trackers certificate. Export the root cert from a windows client OS and import it to the Server OS.

That's what I did to solve my connection issue.

**Comment by Dr-PC-Mac-Linux** [comment]
as a solution you can try to change port at every connection, i mean every time you start transmission, it doesn't solve the issue with not connecting trackers but for the trackers that show seeders it helps !-) (it's an option to check in the options (network)
