### ISSUE TITLE
Transmission crash

### ISSUE THREAD

**Issue by sominaik** [transmission/transmission#4479]
### What is the issue?

Hi,

The client suddenly crashes when I add any torrent file, in few seconds

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

Transmission 3.00

**Comment by mikedld** [comment]
Do you have a crash report you can attach? Based on the provided information, it's impossible to know what went wrong.

Could you try with latest beta version (4.0.0-beta.2)?

**Comment by sominaik** [comment]
Hi,

I tried the cli and I can see the error "Segmentation fault (Core dumped)"
when the gui crashes

**Comment by ckerr** [comment]
Please try a 4 beta and see if the problem persists.

**Comment by sominaik** [comment]
Sorry, I cannot upgrade because this is the only approved version by the tracker website I am using. 
I tried the 'strace' commands and got further info as per following;

+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by ckerr** [comment]
All I'm seeing here is literally "it's crashing" and while I'd like to help, there's not a lot that can be done without an actionable crash report or testing on a 4.0.0 beta. 

I'd suggest testing a 4 beta on a public torrent or on a different tracker to see if the problem persists.
