### ISSUE TITLE
RPC Session requests "group-get" and "group-set" cant use.

### ISSUE THREAD

**Issue by confuseder** [transmission/transmission#4486]
### What is the issue?

request:
```json
{
	"method": "group-get",
	"tag": 2131232312313254656
}
```
return:
```json
{
	"arguments": {},
	"result": "method name not recognized",
	"tag": 2131232312313254656
}
```
in transmission 3.0.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.0

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#5-protocol-versions indicates those methods were added in Transmission 4. Transmission 3 isn't going to recognize them 😃
