### ISSUE TITLE
`announce-ip` option corrupt transmission-daemon's download speed

### ISSUE THREAD

**Issue by cwbsw** [transmission/transmission#4497]
### What is the issue?

`announce-ip` option worked as expected, the ip address I set can be passed to tracker correctly.

But if I enabled this option, I can not download torrent anymore, it seems that transmission-daemon can not flush cache to disk until I stopped torrent manually, if I verify torrent again, indeed some data downloaded, but less than `Maximum memory cache size`.

Seeding already completed torrent is not affected, upload speed is as expected.

A strange problem, hope some expert can confirm it.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0-beta.2.dev+rab9e971903

**Comment by ckerr** [comment]
In the codebase, at least, those two parts of the code are not really related at all.

It's possible that there is an indirect connection, e.g. if you're feeding a bad IP address to a tracker, it may be passing that along to other peers and so they no longer know how to connect to you. That has obvious implications for download speeds.
