### ISSUE TITLE
macOS crash adding torrent file

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4498]
### What is the issue?

[crash.txt](https://github.com/transmission/transmission/files/10323573/crash.txt)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.2.dev (192a76b621)

**Comment by mikedld** [comment]
This report is for something called "ReportCrash", not Transmission.

**Comment by ckerr** [comment]
...ReportCrash crashed? :dizzy: 

@GaryElshaw if it's reproducible and you can tease a Transmission crash report please re-file

**Comment by GaryElshaw** [comment]
Thanks Charles, i hope the new year's was grand!
