### ISSUE TITLE
Cannot change/remove/repair Windows Nightly, installed fine (UCRT)

### ISSUE THREAD

**Issue by Scrxtchy** [transmission/transmission#451]
Found this a bit wierd since it installs and runs perfectly
![image](https://user-images.githubusercontent.com/12771982/33811619-c8decad4-de69-11e7-9d9e-206a3026e36c.png)

Related e4ee96c30d569399da4b1ac8f0c3f425a820beeb back in Feb, which makes sense considering I have been using 2.92 up until, but the upgrade didn't fail at all

**Comment by opicron** [comment]
I get this error when trying to install the daemon.

**Comment by Scrxtchy** [comment]
I'm exclusively using the daemon

**Comment by Scrxtchy** [comment]
Managed to uninstall it today without error
was doing some cleanup. Maybe it worked because I stopped the service
