### ISSUE TITLE
Broken transmission icons on Windows

### ISSUE THREAD

**Issue by sherba800** [transmission/transmission#452]
After installing latest stable build 2.92 there is no proper transmission icons on Windows. I tried to install on another machine - same result.
![8e31ff8a59d3](https://user-images.githubusercontent.com/33832299/33937192-9068206e-e013-11e7-8c6f-57110f2e7654.png)
![e15893b9d519](https://user-images.githubusercontent.com/33832299/33937195-91d3d556-e013-11e7-9bb6-f500a43f7332.png)
![screenshot from 2017-12-13 14-31-31](https://user-images.githubusercontent.com/33832299/33937196-933ac558-e013-11e7-8d21-c1f70fe63536.png)

**Comment by Cormak** [comment]
@sherba800 The current 2.92 build isn't actually stable, which is why it's not on the Transmission homepage. We need the devs to create an actual stable release because your bug has been reported for well over a year now.

**Comment by Cormak** [comment]
@mikedld This appears to be fixed in Windows 64bit 2.94

**Comment by SurPaul** [comment]
I still have it. This happened after I changed the default application for images from FastStone Image Viewer to a standard photo through the Settings system application.

Transmission 3.00 (bb6b5a062e), Windows 10 21H1 x64

![image](https://user-images.githubusercontent.com/1708881/135745258-b2cf13cd-8061-43f0-80c2-58ae5d48f00f.png)
![image](https://user-images.githubusercontent.com/1708881/135745405-f5f7a934-da95-418b-8f32-987812bd0594.png)

**Comment by SurPaul** [comment]
I fixed it by manually recreating the icon.

![image](https://user-images.githubusercontent.com/1708881/135745844-d98bc827-fc4f-4180-87ba-1b0db302c891.png)
