### ISSUE TITLE
Nightly build repeatedly asks permission to access folder

### ISSUE THREAD

**Issue by adriaant** [transmission/transmission#4523]
### What is the issue?

Since the beta 2 version has bugs that appear to have been fixed in the current codebase, I tried to download and run the latest nightly build. However, on starting up, the app repeated asks to access the folder it stores the downloads. Clicking allow has no affect as it just pops up the same dialog again. This might be a signing issue, since it's just a nightly build. May I request a new beta build, since quite a lot of changes have been pushed since beta 2?

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0 beta 2

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #3680, #3437, #2171.
