### ISSUE TITLE
[Feature Request] Allow users to add infohashes to "Open URL" function

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#455]
A lot of clients such as qBittorrent have this feature. Basically, the client uses the entered infohash to search the DHT network the same way as adding a magnet link but without the extra characters for making a clickable browser link.

It would be great if Transmission didn't need the entire magnet link, just the infohash, to add a torrent.

**Comment by jay-to-the-dee** [comment]
This would be awesome :)

**Comment by ckerr** [comment]
transmission-gtk and transmission-qt treat raw infohashes as magnet links in 4.0.x.

Note for anyone driving by: real magnet links are faster than a raw infohash, since magnet links usually also include a list of trackers that can give information about where to find peers.
