### ISSUE TITLE
macOS: Transmission crash at torrent download start

### ISSUE THREAD

**Issue by JayBrown** [transmission/transmission#457]
Transmission on macOS tends to crash from time to time (in my case: OS X 10.11.6). This only happens when, after adding a torrent via magnet, Transmission has received 100% info on the torrent, and then in `~/Library/Application\ Support/Transmission` it writes the temp torrent file to a regular torrent file, so it can then start downloading. At some point during this procedure, the crash happens. As soon as Transmission has received the first few bytes/kilobytes of the distributed file, the crash doesn't happen, i.e. it always happens before, as far as I can see. The bug occurs ca. once per week. It's not a critical bug, I assume, but definitely a nuisance. ;) Three crash reports attached.

[3crashReports.zip](https://github.com/transmission/transmission/files/1567343/3crashReports.zip)

**Comment by ckerr** [comment]
Is this bug still present in the nightly builds?

**Comment by JayBrown** [comment]
I'm now on Big Sur, and I haven't seen this bug for a long time. There was at least one update to Transmission since then, and maybe that's the reason why. At any rate, everything has been running smoothly for a long time now.

**Comment by ckerr** [comment]
Closing as fixed based on previous comment
