### ISSUE TITLE
macOS completion notification has missing icon

### ISSUE THREAD

**Issue by mangosplat** [transmission/transmission#4570]
### What is the issue?

Getting a notification upon completion has a 'missing icon' icon on macOS. Not sure if this is supposed to normally have the Transmission app icon or the torrent file icon. For this particular torrent, it was a .iso.

![image](https://user-images.githubusercontent.com/95374372/211428415-b29837c2-0c60-408d-9249-1c3257b53b4c.png)

![image](https://user-images.githubusercontent.com/95374372/211428494-407ea88f-2c61-4a5e-9a57-a4a78618e809.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by Coeur** [comment]
As I recall, it should be specifically the application icon.
Can you check in Finder if the app has an icon? Did you disable Spotlight by any chance?

**Comment by mangosplat** [comment]
> As I recall, it should be specifically the application icon. Can you check in Finder if the Transmission app has an icon? Did you disable Spotlight by any chance? How did you get Transmission: built it yourself, or downloaded from a location?
> 
> Also, I don't have this "pause" icon on my version: it seems that you are on a very old version of macOS possibly?

Yes I do recall it being the application icon previously as well. Spotlight is enabled and this is the beta 3 that I got by downloading it from the Transmission website. I'm on Ventura 13.1. Shouldn't be any weird settings on my system. Are you saying you can't reproduce this issue?

Also I'm not quite sure what you mean by you don't have the 'pause icon'. The one in the main top bar of the app? You should have it, it's even in the (although outdated) screenshot on the transmission website.

**Comment by Coeur** [comment]
Ah, sorry for the "pause" icon: there are two to choose from: I'm using the "pause selection" one, while you're having the "pause all" one, hence I got confused. Never mind about that.

**Comment by ckerr** [comment]
Is this still an issue in Transmission 4.0.1 or higher?

**Comment by Coeur** [comment]
Well, I had at some point the T3 icon, even though I'm sure that I was using T4 when I completed the download:
![Capture d’écran 2023-03-14 à 08 32 23](https://user-images.githubusercontent.com/839992/224862217-a32cd673-8f08-4aa6-9e54-8c98e8e741fb.png)

So I'm suspecting that simply, with multiple installations of the same app (same bundle id "org.m0k.transmission"), the macOS system, when displaying a notification, will pick the icon for one of the install paths in priority (could be `/Applications`, could be `~/Applications`, could be something else).

So it's not a Transmission bug, there is nothing the app can do about it, but you have to make sure to delete the other versions of Transmission installed on your system if you want to get the expected icon. And reboot the mac eventually.

**Comment by ckerr** [comment]
Closing based on previous comment.
