### ISSUE TITLE
Libdeflate 1.16

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4591]
### What is the issue?

New release
https://github.com/ebiggers/libdeflate/releases/tag/v1.16

### Which application of Transmission?

All

### Which version of Transmission?

Beta3

**Comment by ckerr** [comment]
Still not there yet, apparently

**Comment by ebiggers** [comment]
Can you elaborate on what is preventing you from upgrading?

**Comment by nevack** [comment]
> Can you elaborate on what is preventing you from upgrading?

https://github.com/transmission/transmission/pull/4592#issuecomment-1382892569

**Comment by GaryElshaw** [comment]
1.17 is now available, @ckerr https://github.com/ebiggers/libdeflate/releases/tag/v1.17

**Comment by ckerr** [comment]
Fixed by #4596
