### ISSUE TITLE
Warning in my browser with 'XMLHttpRequest '

### ISSUE THREAD

**Issue by zaggash** [transmission/transmission#46]
Hi,

I just add a follow up on this message I get on my browser while going on the webui

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Regards.

**Comment by pedrinho** [comment]
Can we close this issue? Maybe I am missing something, but there is no reference to 'XMLHttpRequest' in the code anymore.

**Comment by zaggash** [comment]
Yeah its been a while since I see this error
