### ISSUE TITLE
[enhancement] RPC needs extensive query capabilities.

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#4603]
### What is the issue?

@ckerr wrote in #4399 :
> I do think there is a scrolling problem in the web client and @killemov if you want to add a virtual scroll to the web client to solve it I would be _very_ happy to review that.

I have been tinkering with delayed fetching in [Shift](https://github.com/killemov/Shift) using placeholder rows and a scroll handler. Using a table makes things easier. Using this in combination with sorting and filtering makes this well ... [NSFW]!

So how DO you sort/filter on sizeWhenDone when you do not have all the data available? You get all the data for that specific column anyway, because you don't know what you don't now. But this negates not having to traverse all the torrent data  server-side and transporting that client-side.

The proper way to do this is to query transmission-daemon. Something like: "Fetch torrents in range [128 ... 255] currently downloading and with sizeWhenDone > 1GB sorted on sizeWhenDone ascending".

So for Shift we can optimize some things to present a first list of torrent data fairly quick. But that is only because the torrents are segmented on status. So you are presented with a possibly limited set of torrents that are actually downloading.

### Which application of Transmission?

Web client

### Which version of Transmission?

All

**Comment by ckerr** [comment]
I think this would be a false savings -- if you're pinging Transmission to ask "give me the 128th through 255th downloading torrents sorted by sizeWhenDone" then do you ping the server each time the scrollbar is dragged? Requiring a round-trip before scrolling sounds painful.

IMO it's better to fetch `sizeWhenDone` once and then periodically update it for torrents which are `recently-active`. For example transmission-qt uses [this list](https://github.com/transmission/transmission/blob/main/qt/Session.cc#L510) to group fields into four categories:

- unchanging fields that the main window needs
- changing fields that the main window needs (loaded once on startup, then periodically updated with `recently-active`)
- unchanging fields that the details dialog needs
- changing fields that the details dialog needs (loaded once when the dialog is opened, then periodically updated with `recently-active`)

This is working out pretty well in transmission-qt, both in terms of CPU and in bandwidth, so my gut feeling is that the query language is not worth the effort & complexity it would take to write. If you feel strongly about it and want to cook up a PR to do it, I'd be happy to collaborate on ideas and to do code review on your PR.

**Comment by valcomm** [comment]
`Something like: "Fetch torrents in range [128 ... 255] currently downloading and with sizeWhenDone > 1GB sorted on sizeWhenDone ascending".` - it is possible now to request a subset of torrents from the daemon.  Further sorting/filtering could be pretty well done on client side.  There is no benefit in adding query complexity in this particular case.

**Comment by killemov** [comment]
@ckerr wrote:
> I think this would be a false savings -- if you're pinging Transmission to ask "give me the 128th through 255th downloading torrents sorted by sizeWhenDone" then do you ping the server each time the scrollbar is dragged? Requiring a round-trip before scrolling sounds painful.

I did some re-coding and testing and ... getting new rows from transmission-daemon on scroll actually works pretty good! But only IF the result is sorted correctly. I tested the scroll using a timeout of 500ms, a viewport with 256 pixels slack and a max fetch limit of 16 torrents at a time. And the result was smooooooth. :sunglasses: Of course this was tested on a local network. Over a VPN the result was not that smooth, but I am certain that some of these parameters could be tweaked for a better experience.

So only adding server-side sorting on torrent field in ascending/descending order should go a long way in creating a smooth scrolling experience whilst also not downloading the entire set of torrents.

@ckerr wrote:
> IMO it's better to fetch `sizeWhenDone` once and then periodically update it for torrents which are `recently-active`. For example transmission-qt uses [this list](https://github.com/transmission/transmission/blob/main/qt/Session.cc#L510) to group fields into four categories:

The field `sizeWhenDone` should be considered semi-static, meaning it only changes when a user changes something, triggering an update. But for fields like `rateDownload` and `rateUpload` you are correct and using `recently-active` is the only logical way.

@valcomm wrote:
> `Something like: "Fetch torrents in range [128 ... 255] currently downloading and with sizeWhenDone > 1GB sorted on sizeWhenDone ascending".` - it is possible now to request a subset of torrents from the daemon.

Without explicitly using ids in the request, how? You only know what torrents have a `sizeWhenDone` > 1GB when you have fetched that data for all torrents already. That is exactly why `recently-active` exists. If not, all dynamic torrentdata would need to be fetched every cycle.

@valcomm wrote:
> Further sorting/filtering could be pretty well done on client side. There is no benefit in adding query complexity in this particular case.

... If you have all the data client-side, sure. But my suggestion for this enhancement is to NOT need to have all the data fetched, but only what is visible. And the tests I have done show it works.

**Comment by valcomm** [comment]
> Without explicitly using ids in the request, how?

What is wrong with explicitly using ids?  Especially when there are two clients with differently sorted lists.  And sorting used by daemon isn't permanent - it changes with restart/torrent removal for example (from any client, btw).  If you pass 128, 129,130,131 instead of 128-131 - I don't think this will break your world.



> You only know what torrents have a `sizeWhenDone` > 1GB when you have fetched that data for all torrents already.

Why all torrents?  I thought you wanted this condition to filter further your range from above.  And again - in any case it's doable on the client side.



> But my suggestion for this enhancement is to NOT need to have all the data fetched, but only what is visible

Fetch all the first time.  Then filter the response and cache resulting ids for the following usage.  What you're asking is doable on the client side and belongs there.

**Comment by killemov** [comment]
> What you're asking is doable on the client side and belongs there.

Again, you probably do not understand what I'm asking.

**Comment by valcomm** [comment]
> you probably do not understand what I'm asking.

I think I do.  You want to shift your wishes (which are totally doable on the client side) on shoulders of daemon developers.  And making RPC specs unnecessary huge and error prone in the process.

**Comment by killemov** [comment]
@valcomm wrote:
> > you probably do not understand what I'm asking.
> 
> I think I do. You want to [shift](https://github.com/killemov/Shift) your wishes (which are totally doable on the client side) on shoulders of daemon developers. And making RPC specs unnecessary huge and error prone in the process.

No. Just, no.

But [I did roll my own Web UI](https://forum.transmissionbt.com/viewtopic.php?f=8&t=12555) in 2011, [used FileReader first](https://trac.transmissionbt.com/ticket/5290#comment:10) and I was requested to look into virtual scrolling by @ckerr. And to do virtual scrolling right, I also took on the additional challenge to minimize data consumption. So not just not render what you can not see but also not fetch what you can not render.  To which I came to the conclusion that can ONLY be done right with extensive query capabilities. But just adding server-side sorting would help a lot. Maybe add two optional fields to the torrent-get arguments: `orderBy`: torrentField and `ascending`: true/false.

**Comment by valcomm** [comment]
> But just adding server-side sorting would help a lot. Maybe add two optional fields to the torrent-get arguments: `orderBy`: torrentField and `ascending`: true/false.

Again: why this sorting cannot happen on the client side?  Could you explain, please?

Right now in my scripts/terminal client I use _client side_ sorting.  With complex conditions and by more than one field.  I see no benefit whatsoever for server side sorting even if I need a sorting by just one field.  But maybe you would be able to explain what great idea/benefit I missed and I'd join you in your request.

**Comment by killemov** [comment]
> > But just adding server-side sorting would help a lot. Maybe add two optional fields to the torrent-get arguments: `orderBy`: torrentField and `ascending`: true/false.
> 
> Again: why this sorting cannot happen on the client side? Could you explain, please?

You CAN do sorting client-side IF you have the complete set client-side. My point is doing the sorting without having the complete set  ... so you can use virtual-scrolling with fetching on demand. Example: You want to scroll through your torrents sorted by name alphabetically. If server-side sorting was implemented you could just fetch the torrents one torrent at a time in order without having to first having to fetch the names of all torrents, sort that and then fetch the torrents from cached ids. Imagine this for 20k+ torrents.

> Right now in my scripts/terminal client I use _client side_ sorting. With complex conditions and by more than one field. I see no benefit whatsoever for server side sorting even if I need a sorting by just one field. But maybe you would be able to explain what great idea/benefit I missed and I'd join you in your request.

The entire point is ... How many torrents in your set?

Another benefit could be that your (or the worlds' ) scripts could become less complex and more efficient.

As an aside, I rolled my own Web UI because the stock one could not (maybe still can't) handle the sheer numbers. If I recall correctly it started to buckle at ~250 torrents and was unusable at ~500.

**Comment by valcomm** [comment]
> The entire point is ... How many torrents in your set?

Over 2K at the moment.

> Another benefit could be that your (or the worlds' ) scripts could become less complex and more efficient.

No, they won't.  Decent clients do the sorting by at least two fields.  Good ones by even more.  And with optional filtering.  
Even "sorting alphabetically" is a complex thing.  How to sort unicode (which collation, unicode form should be used?)?  What about case-sensitivity?
Your request belongs to the client side.  There is no need to make RPC more complex

**Comment by killemov** [comment]
I dislike you asking for explanations and then ignoring them anyway.

We disagree. Period.

Now go manage your 2k torrents with the stock Web UI on your phone.

**Comment by valcomm** [comment]
> I dislike you asking for explanations and then ignoring them anyway.

I did not ignore your explanation.  You turned it into "I want server side sorting", but couldn't provide why this cannot be done on the client side.  In my turn I provided details about "sorting" being not so simple thing.


> Now go manage your 2k torrents with the stock Web UI on your phone.

I picked transmission because of its server/client architecture and used only transmission-remote from the stock set of clients.  Everything is done by my scripts.  If you're observing issues with Web UI, those might be the issues of this particular client, not the server.  And most likely those issues could be fixed in this particular client.

**Comment by ckerr** [comment]
> I was requested to look into virtual scrolling by @ckerr. And to do virtual scrolling right, I also took on the additional challenge to minimize data consumption.

I should be more clear, what I had in mind was something like https://sergimansilla.com/blog/virtual-scrolling/ or https://medium.com/ingeniouslysimple/building-a-virtualized-list-from-scratch-9225e8bec120

**Comment by killemov** [comment]
@ckerr wrote:
> I should be more clear, what I had in mind was something like https://sergimansilla.com/blog/virtual-scrolling/ or https://medium.com/ingeniouslysimple/building-a-virtualized-list-from-scratch-9225e8bec120, how to efficiently handle large list rendering when all the data exists on the client side.

Yes, you were clear enough about that. The tests I have done show the following bottlenecks:

1. Fetching all the data, even only for the visible columns, at start takes a loooong time.
2. Rendering all the data in-DOM all at once (for Shift this means all rows in the table) takes a loooong time with 100% CPU load to boot.

Bottleneck 1 could be mitigated by some form of ['infinite scrolling'](https://infinite-scroll.com/demo/full-page/) with sorting server-side. The server determines the (initial) view in this scenario.
Bottleneck 2 could be mitigated by some form of either 'virtual scrolling', only render what you will see, or pre-rendering out-of-DOM and then optionally show (unhide) the elements just before they come into view. Scrolling through already rendered and visible elements (20k+ rows on Firefox) appears to be no problem at all.

Rendering out-of-DOM saves a lot of time and resources. For Shift I created a dummy TBODY, rendered all the rows in that and then copied the innerHTML to the in-DOM TBODY.

**Comment by killemov** [comment]
Related to #1726.
