### ISSUE TITLE
4.0.0 Beta 3 stops responding after pressing "Adjust tools panel"

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#4604]
### What is the issue?

![Снимок экрана 2023-01-17 в 10 44 33](https://user-images.githubusercontent.com/74548419/212841063-d5a4e965-1184-4079-8ef1-0988c4737f0e.png)
[CrashLog.txt](https://github.com/transmission/transmission/files/10432621/CrashLog.txt)

### Which application of Transmission?

macos

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by Coeur** [comment]
I didn't reproduce the first time, but the second time I saw the hang:
![Capture d’écran 2023-01-24 à 03 04 59](https://user-images.githubusercontent.com/839992/214127502-9aa18526-2782-4e8f-8810-200c3d2db991.png)

**Comment by Coeur** [comment]
Pinging @sweetppro to check if the hang might be UI related.

**Comment by ckerr** [comment]
I'm not able to reproduce this. Are there any other steps needed to trigger this, e.g. making some particular UI change?

**Comment by Tockman** [comment]
> I'm not able to reproduce this. Are there any other steps needed to trigger this, e.g. making some particular UI change?

No any special changes. Just use Ventura 13.2.

**Comment by sweetppro** [comment]
Im also not seeing this happen - M2 MacBook Air Ventura 13.2

**Comment by GaryElshaw** [comment]
I'm not seeing this on 13.2 either.

**Comment by ckerr** [comment]
Still nice-to-have for 4.0.0 but I wouldn't block the release on this

**Comment by nevack** [comment]
Ventura 13.2 (22D49), works for me.

**Comment by nevack** [comment]
Maybe we should test with `ru_RU` locale?

**Comment by Coeur** [comment]
I was reproducing with French locale... but no time to investigate anything at the moment.

**Comment by ckerr** [comment]
> @[Coeur](https://github.com/Coeur) Coeur added this to the [4.0.0](https://github.com/transmission/transmission/milestone/8) milestone [last week](https://github.com/transmission/transmission/issues/4604#event-8337528021)

@Coeur do you have plans to fix this soon? Is this a blocker for 4.0.0?

We'll be doing a release this week and I'm trying to decide what tasks are still outstanding, and whether we need a final beta or whether the code is ready for a stable release.

**Comment by Coeur** [comment]
It's not a blocker for me: that toolbar isn't essential to the usage of Transmission as all options are otherwise already available by selecting torrents and right-clicking for contextual menu.

**Comment by ckerr** [comment]
Removing the `4.0.0` milestone based on previous comment.

**Comment by Coeur** [comment]
It's some sort of infinite loop + memory leak in Apple's framework CoreAutoLayout around NSISEngine/NSISVariable/NSLayoutConstraint.
I couldn't find anything in our code affecting it, so it might be an Apple bug.

![Capture d’écran 2023-02-02 à 13 24 11](https://user-images.githubusercontent.com/839992/216239250-8a73caed-5a30-4539-979a-9dc79112519c.png)

**Comment by Coeur** [comment]
OK, I got a clue: the autolayout hang is happening specifically for `GroupToolbarItem`: when I replace those with `ButtonToolbarItem`, I don't experience any issue.

**Comment by Coeur** [comment]
I still think it's an Apple bug, but we could also:
- consider investigating the implementation approach from this blog: https://christiantietze.de/posts/2018/11/reliable-nssegmentedcontrol-in-toolbar/
- try the macOS 10.15+ method [`+groupWithItemIdentifier:images:selectionMode:labels:target:action:`](https://developer.apple.com/documentation/appkit/nstoolbaritemgroup/3242763-groupwithitemidentifier?language=objc)

**Comment by Coeur** [comment]
I'm seeing that current implementation was done by #3512, aka by @nevack.
