### ISSUE TITLE
"Set location" dialog in transmission-gtk never closes

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#4606]
### What is the issue?

To reproduce: start `transmission-gtk` -> select a torrent -> `Set Location...` -> don't change anything in the dialog -> Apply

The "Moving '{name}'" "This may take a moment..." dialog appears and never closes, causing Transmission's UI to hang forever.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

74c82482 (Jan 17 2023)

**Comment by ckerr** [comment]
I haven't looked into this yet but it sounds kind of like #4391 #4392

**Comment by mikedld** [comment]
Noticed this as well but didn't look into it either [yet]. Going to assign to myself.

**Comment by ckerr** [comment]
Notes: Fixed `4.0.0-beta.1` regression that made the "Set location" dialog hard to dismiss.
