### ISSUE TITLE
Transmission 4 beta 2 does not see beta 3

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#4614]
Transmission 4 beta 2 does not see that beta 3 is available, even though I have "Include beta releases" checked.

![Screen Shot 2023-01-19 at 2 37 22 AM](https://user-images.githubusercontent.com/201815/213420592-1a8e7ea3-1802-45f8-9796-ed1f9a7e5892.png)

**Comment by ckerr** [comment]
Huh this is kind of a good point.


IIRC the rationale was to just not check out betas on the up-to-date check since you don't necessarily want everyone upgrading from stable to beta.

But if you're already _on_ a beta, updating to a newer beta makes sense

**Comment by nevack** [comment]
@ckerr, I didn't mean this is working now!
Let's reopen this for now.
We need to fix this 😄

**Comment by jslawler** [comment]
> Huh this is kind of a good point.
> 
> IIRC the rationale was to just not check out betas on the up-to-date check since you don't necessarily want everyone upgrading from stable to beta.
> 
> But if you're already _on_ a beta, updating to a newer beta makes sense

I get the rationale behind this, but by ticking the box and checking for an update I expected to get updated from v3 to v4, which didn't happen. This made me think the system was broken rather than intentional.

Maybe the option should be hidden for users on stable if it's not desired to have users upgrading from stable to beta?

**Comment by sweetppro** [comment]
I do this in one of my own apps, its not difficult.
I have 2 app casts, one with beta updates, the other for stable updates.

the current stable app cast resolves to:
`https://update.transmissionbt.com/appcast.xml`

we could add another beta app cast here for example:
`https://update.transmissionbt.com/beta_appcast.xml`

we change the appcast url with the `Include beta releases' checkbox.
then I guess the build/release script needs to be updated to publish either the beta or stable app cast, depending on the release version
