### ISSUE TITLE
[3.00] 409 conflict on requesting /transmission/rpc/

### ISSUE THREAD

**Issue by letsintegreat** [transmission/transmission#4615]
### What is the issue?

I am trying to connect Transmission to Flood, so I need to pass /transmission/rpc/ endpoint to flood, but because the connection could not be established on Flood, so I checked that URL on a web browser, and I got 409 Conflict. It used to work fine before.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 3.00 (bb6b5a062e)

**Comment by ckerr** [comment]
409 conflict is a csrf token issue, see https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#231-csrf-protection for documentation. You're not going to be able to view that page with a web browser.
