### ISSUE TITLE
tr_urlParse() fails in libpsl-0.21.2 on macOS brew builds

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#4617]
### What is the issue?

https://github.com/transmission/transmission/actions/runs/3960513272/jobs/6784969451

```
[ RUN      ] WebUtilsTest.urlParse
/Users/runner/work/transmission/transmission/src/tests/libtransmission/web-utils-test.cc:45: Failure
Expected equality of these values:
  "some-tracker"sv
    Which is: "some-tracker"
  parsed->sitename
    Which is: "www"
/Users/runner/work/transmission/transmission/src/tests/libtransmission/web-utils-test.cc:56: Failure
Expected equality of these values:
  "some-tracker"sv
    Which is: "some-tracker"
  parsed->sitename
    Which is: "www"
/Users/runner/work/transmission/transmission/src/tests/libtransmission/web-utils-test.cc:67: Failure
Expected equality of these values:
  "some-tracker"sv
    Which is: "some-tracker"
  parsed->sitename
    Which is: "www"
/Users/runner/work/transmission/transmission/src/tests/libtransmission/web-utils-test.cc:99: Failure
Expected equality of these values:
  "example"sv
    Which is: "example"
  parsed->sitename
    Which is: "www"
```

Not repeatable, but worth at least looking into.

### Which application of Transmission?

None

### Which version of Transmission?

main

**Comment by ckerr** [comment]
Probably not a libpsl bug.

Our fork has this patch:

```diff
diff --git a/src/psl.c b/src/psl.c
index 0f8de1c..5b9f470 100644
--- a/src/psl.c
+++ b/src/psl.c
@@ -166,7 +166,7 @@ struct psl_ctx_st {
 };
 
 /* include the PSL data generated by psl-make-dafsa */
-#if defined(FORCE_BUILTIN_LIST) || defined(BUILTIN_GENERATOR_LIBICU) || defined(BUILTIN_GENERATOR_LIBIDN2) || defined(BUILTIN_GENERATOR_LIBIDN)
+#if defined(BUILTIN_GENERATOR_LIBICU) || defined(BUILTIN_GENERATOR_LIBIDN2) || defined(BUILTIN_GENERATOR_LIBIDN)
 #include "suffixes_dafsa.h"
 #else
 static const unsigned char kDafsa[] = "";
@@ -1366,7 +1366,7 @@ void psl_free(psl_ctx_t *psl)
  */
 const psl_ctx_t *psl_builtin(void)
 {
-#if defined(FORCE_BUILTIN_LIST) || defined(BUILTIN_GENERATOR_LIBICU) || defined(BUILTIN_GENERATOR_LIBIDN2) || defined(BUILTIN_GENERATOR_LIBIDN)
+#if defined(BUILTIN_GENERATOR_LIBICU) || defined(BUILTIN_GENERATOR_LIBIDN2) || defined(BUILTIN_GENERATOR_LIBIDN)
        return &builtin_psl;
 #else
        return NULL;
```

And what's happening in those macOS CI failures is that there's finally a distro in the wild that has a new enough version of libpsl to use the system version instead of our patched version. 

We need to just unconditionally use our patched version until / unless we revisit this and see if we can run with an unpatched version. I don't want to make this change so close to 4.0.0 but we should revisit afterwards.

**Comment by GaryElshaw** [comment]
At the risk of repeating myself (i'm repeating myself), i think it has to do with this bug that was resolved the day after release. https://github.com/rockdaboot/libpsl/commit/c47cf796fcf98641cb34929d17de041b26c54447

**Comment by ckerr** [comment]
> At the risk of repeating myself (i'm repeating myself), i think it has to do with this bug that was resolved the day after release. https://github.com/rockdaboot/libpsl/commit/c47cf796fcf98641cb34929d17de041b26c54447

Thanks for doing the research on that!

I'll give it a try if this other approach doesn't work out but I don't think I don't think that https://github.com/rockdaboot/libpsl/commit/c47cf796fcf98641cb34929d17de041b26c54447 can be it. From the looks of it, that would manifest as a ftbfs on windows, but the symptom here is a runtime error on macOS.

**Comment by ckerr** [comment]
OK https://github.com/transmission/transmission/issues/4617#issuecomment-1397797426 was half right but I jumped to the wrong conclusion about both the cause and possibly what to do about it.

https://github.com/Homebrew/homebrew-core/pull/119028/files disables the default builtin list, specifically the `-Dbuiltin=false` that was added for 0.21.2's formula. Another user noticed the same thing at https://github.com/Homebrew/homebrew-core/pull/119028#issuecomment-1372088438.

This is causing a regression in [libtransmission/web-utils.cc](https://github.com/transmission/transmission/blob/e4c5981545a133d4e7d5b1ee17802572ed8f87c8/libtransmission/web-utils.cc#L261):

```c++
    // is it a registered name?
    if (isAsciiNonUpperCase(host))
    {
        if (char const* const top = psl_registrable_domain(psl_builtin(), std::data(szhost)); top != nullptr)
        {
            host.remove_prefix(top - std::data(szhost));
        }
    }
    else if (char* lower = nullptr; psl_str_to_utf8lower(std::data(szhost), nullptr, nullptr, &lower) == PSL_SUCCESS)
    {
        // www.example.com -> example.com
        if (char const* const top = psl_registrable_domain(psl_builtin(), lower); top != nullptr)
        {
            host.remove_prefix(top - lower);
        }

        psl_free_string(lower);
    }
```

These two `psl_registrable_domain(psl_builtin(), ...)` calls worked fine on brew 0.21.1 but fail with the current brew for 0.21.2.

**Comment by ckerr** [comment]
*whew* Homebrew/homebrew-core doesn't make it easy to submit bug reports that don't quite fit into their templates, but anyway I've reported this upstream at  https://github.com/Homebrew/homebrew-core/issues/121081

**Comment by ckerr** [comment]
I'm going to close this ticket since it's an upstream issue.

IDK how quickly upstream releases, but it's a good sign that there's already a PR that fixes the issue. IMO let's leave CI as-is for awhile, even though it's red, instead of disabling the macOS builds.

**Comment by mikedld** [comment]
If it's possible to build libpsl in a way that doesn't support our use-case, should be maybe handle this on our end either have a fallback or return an configuration error?
