### ISSUE TITLE
 error: ‘CURL_VERSION_BITS’ was not declared

### ISSUE THREAD

**Issue by adrianmihalko** [transmission/transmission#4629]
### What is the issue?

I am unable to compile Transmission 4.0 beta3 on Ubuntu 22.04.1, the error is:

```
[ 32%] Building CXX object libtransmission/CMakeFiles/transmission.dir/announcer-http.cc.o
/home/madrian/tmp/transmission-4.0.0-beta.3+r634b1e8fc1/libtransmission/announcer-http.cc: In function ‘void tr_tracker_http_announce(const tr_session*, const tr_announce_request&, tr_announce_response_func)’:
/home/madrian/tmp/transmission-4.0.0-beta.3+r634b1e8fc1/libtransmission/announcer-http.cc:432:95: error: ‘CURL_VERSION_BITS’ was not declared in this scope; did you mean ‘CURL_VERSION_LIBZ’?
  432 |     static bool const use_curl_workaround = curl_version_info(CURLVERSION_NOW)->version_num < CURL_VERSION_BITS(7, 77, 0);
      |                                                                                               ^~~~~~~~~~~~~~~~~
      |                                                                                               CURL_VERSION_LIBZ
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/build.make:90: libtransmission/CMakeFiles/transmission.dir/announcer-http.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:601: libtransmission/CMakeFiles/transmission.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
(flexget) madrian@ubuntu:~/tmp/transmission-4.0.0-beta.3+r634b1e8fc1/build$ sudo apt-get install  libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.81.0-1ubuntu1.7).
0 upgraded, 0 newly installed, 0 to remove and 179 not upgraded.
```

What can be the problem?

### Which application of Transmission?

transmission-daemon

**Comment by ckerr** [comment]
Hey, @adrianmihalko, that's odd. `CURL_VERSION_BITS` exists in `curlver.h` which is included automatically by `curl.h` which is #included at the top of `announcer-http.cc`. :thinking: 

CI runs using Ubuntu 22.04 and curl 7.81.0 have been building Transmission for months, so my first guess is that there's a configuration issue with either your build or with your curl installation.

You may want to compare your output to, say, [this recent CI run](https://github.com/transmission/transmission/actions/runs/3976115157/jobs/6816396460) to see if there are any differences.

**Comment by adrianmihalko** [comment]
> Hey, @adrianmihalko, that's odd. `CURL_VERSION_BITS` exists in `curlver.h` which is included automatically by `curl.h` which is #included at the top of `announcer-http.cc`. 🤔
> 
> CI runs using Ubuntu 22.04 and curl 7.81.0 have been building Transmission for months, so my first guess is that there's a configuration issue with either your build or with your curl installation.
> 
> You may want to compare your output to, say, [this recent CI run](https://github.com/transmission/transmission/actions/runs/3976115157/jobs/6816396460) to see if there are any differences.

Hi #ckerr,

Here is my cmake output:

https://pastebin.com/raw/Dn2WCEDy

I don't see any special here, the curl library is recognised.

make output:

https://pastebin.com/raw/Atup4LG3

**Comment by ckerr** [comment]
Is it possible that there's a nonstandard / older `curl.h` somewhere in your include path?

What happens if you use cmake with `-DCMAKE_CXX_FLAGS="-E -dI"`

**Comment by adrianmihalko** [comment]
Bingo, you are right.

madrian@ubuntu:~/tmp/transmission-4.0.0-beta.3+r634b1e8fc1/build$ sudo find / -mount -name "curl.h"
```
/var/lib/docker/overlay2/958269692e98ce4b0377dc5e9565542cd168aad1b952cb4537da175cf0895d97/diff/usr/include/x86_64-linux-gnu/curl/curl.h
/var/lib/docker/overlay2/425e5bebcf118af1d1f64783393427a2c89e700d72c7be1fae2c49bb7c82c1d1/diff/usr/include/x86_64-linux-gnu/curl/curl.h
/usr/include/x86_64-linux-gnu/curl/curl.h
/usr/local/include/curl/curl.h
```

I removed the last version and now it compiles without any problem.

p.s.: with `-DCMAKE_CXX_FLAGS="-E -dI"` I had other error.

Thank you again for the fast response.
