### ISSUE TITLE
Opening 'Message Log' in qt client tray doesn't work

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4653]
### What is the issue?

Selecting 'Message Log' from the tray dropdown doesn't display amy information.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-beta.3.dev (b055b98d0f)

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/3773
