### ISSUE TITLE
Beta can't be downloaded due to error 503 backend unavailable

### ISSUE THREAD

**Issue by jslawler** [transmission/transmission#4660]
### What is the issue?

Issue link: https://github.com/transmission/transmission/releases/download/4.0.0-beta.3/Transmission-4.0.0-beta.3+r634b1e8fc1.dmg

<img width="731" alt="Screenshot 2023-01-25 at 6 35 45 pm" src="https://user-images.githubusercontent.com/95468948/214517734-98fd721d-9a3f-4246-9a52-b06a5562be57.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

2

**Comment by ckerr** [comment]
Looks like it was a github hiccup; seems to be working now
