### ISSUE TITLE
Show Client Secret Key for private trackers

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4666]
### What is the issue?

Could we add in the ability to see client secret keys? (usually just a query string appended to the tracker URL)

We use a private tracker to make sure only authorized servers can download database updates and it would be nice to be able to verify which key is being used in a torrent session.

### Which application of Transmission?

macOS app

### Which version of Transmission?

f01191e

**Comment by robd003** [comment]
@GaryElshaw here's the new ticket

**Comment by Pentaphon** [comment]
Honestly, I think the current way Transmission displays announce URLs is superior, as you want to hide that private key as much as possible until you have to edit it. In fact, one of the mistakes I see people make with clients like qBittorrent is that they accidentally show the private key on screenshots or screenshares, forcing them to have to change that key immediately. This is much harder to do with Transmission, as you have to open the edit dialog to show the full URL. Also, your current private key is always shown on the site you're using so its not like you always need to see it on your torrent client. 

I'm going to have to insist this functionality remains the same. Unless the Mac app, which I don't use, doesn't show the full announce URL at all.

**Comment by ckerr** [comment]
@robd003 I think @Pentaphon has a decent point here, displaying it in a prominent way could leak PII. But "the ability to see client secret keys" is a pretty open-ended request -- what did you have in mind?

**Comment by robd003** [comment]
I'd be fine with having a "Show Key" context menu on the trackers so that the key would be hidden by default. Just something so that you can quickly identify if the key being used is correct or if you have to re-download a torrent file.

I did investigate and find that I can select a tracker in the list and use the Edit -> Copy menu to copy the full URL, but then you have to paste it into something else and there's no easy way to visually check within just Transmission.

**Comment by Pentaphon** [comment]
> I'd be fine with having a "Show Key" context menu on the trackers so that the key would be hidden by default.

That seems unnecessary because most people don't use private trackers and the same thing can be achieved by simply hitting the edit button to view it. 

>Just something so that you can quickly identify if the key being used is correct or if you have to re-download a torrent file.

This is where I don't get the use case at all. I personally use private trackers and:

- if the key is "incorrect" it throws out an error and you can't access the tracker
- you rarely have to change your private key or have it changed for you. changing your key is only for an emergency, like when your key is compromised. 
- there's a console on every private tracker that shows you what your key is and it should not change at all, much less often. The only function on that console is an emergency reset function. 

I don't really see what the pressing use case is here. You should never have to constantly check your private keys. I've used private trackers for a 1/3 of my life and I've never had to change them or check them. I don't know any other private tracker user that does this with their keys, either. It seems like a lot of trouble for no reason at all. 

I find Transmission to be better for keeping private keys secret and I really think there's more effort needed here for too little gain in functionality.

**Comment by robd003** [comment]
> > I'd be fine with having a "Show Key" context menu on the trackers so that the key would be hidden by default.
> 
> That seems unnecessary because most people don't use private trackers and the same thing can be achieved by simply hitting the edit button to view it.

On the macOS client there is no edit button. There's no way to edit trackers at all, you can only delete and add new ones.

> 
> > Just something so that you can quickly identify if the key being used is correct or if you have to re-download a torrent file.
> 
> This is where I don't get the use case at all. I personally use private trackers and:
> 
> * if the key is "incorrect" it throws out an error and you can't access the tracker
> * you rarely have to change your private key or have it changed for you. changing your key is only for an emergency, like when your key is compromised.
> * there's a console on every private tracker that shows you what your key is and it should not change at all, much less often. The only function on that console is an emergency reset function.
> 
> I don't really see what the pressing use case is here. You should never have to constantly check your private keys. I've used private trackers for a 1/3 of my life and I've never had to change them or check them. I don't know any other private tracker user that does this with their keys, either. It seems like a lot of trouble for no reason at all.
> 
> I find Transmission to be better than qBittorrent or uTorrent for keeping private keys secret and I really think there's too much effort needed here for too little gain in functionality.

I run a private tracker to distribute code & database updates for our servers. We regularly update keys and it's nice to be able to verify that the correct key is in use.

I'm fine with not having the keys disclosed by default, but really there should be an option to make debugging easier.

**Comment by Pentaphon** [comment]
> On the macOS client there is no edit button. There's no way to edit trackers at all, you can only delete and add new ones.

Wow, ok then. You're totally right then. This is a clear feature parity issue. I'm all for it. You should at least be able to edit URLs like I can with Linux and Windows.

**Comment by ckerr** [comment]
That is tracked already in https://github.com/transmission/transmission/issues/4654

**Comment by Pentaphon** [comment]
> Should this be closed as a duplicate of that ticket?

That's up to you:

1) Is feature parity enough?
2) Or is this special request worth the extra work?

I vote yes for number 1 if that means anything.

**Comment by GaryElshaw** [comment]
I asked Rob to open this as a separate ticket because it struck me that it was a separate feature request.

**Comment by ckerr** [comment]
I also am leaning towards 1
