### ISSUE TITLE
deprecated library warning when building web client

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4668]
### What is the issue?

Just a heads-up about this...

`[100%] Generating public_html/transmission-app.js, public_html/transmission-app.js.map, public_html/transmission-app.js.LICENSE.txt
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility`

### Which application of Transmission?

Web client

### Which version of Transmission?

Beta 4

**Comment by ckerr** [comment]
What's the output when you run `npm --version` and `node --version`?

I'm not seeing this in CI (e.g. https://github.com/transmission/transmission/actions/runs/4009905626/jobs/6885805744)

**Comment by GaryElshaw** [comment]
npm is 9.4.0 and node is 19.5.0 (macOS)

**Comment by ckerr** [comment]
Not a Transmission error. Upstream issue is at https://github.com/cssnano/cssnano/issues/1448 which is fixed in its repo and milestoned for cssnano@6, which is not yet released.

Closing as Not Transmission
