### ISSUE TITLE
Enable hooks for torrents operation

### ISSUE THREAD

**Issue by doronbehar** [transmission/transmission#467]
Will it be possible to add support for hooks other than `script-torrent-done`?

For example, I want to create a hook that will backup all the torrents in my `watch-dir` and when a torrent is removed I want to remove it from the `watch-dir` as well (identifying it should be available using the torrent's hash). I want the hook to update the backup so that the torrent that was deleted from transmission will be deleted from the backup as well.

I'll be happy to hear your thoughts, and thanks for making this great software.

**Comment by ben-ba** [comment]
Why not simply backup the "torrents"-dir?

**Comment by doronbehar** [comment]
While posting this feature request I wasn't aware of the directory `.config/transmission/torrents`. It's a great suggestion and now that I'm aware of this I have set up an [`incron`](https://github.com/ar-/incron) job to do so whenever a file is added or deleted from this directory and it works just fine.

But still I think it could be great to have it as a hook since it will take less system resources (although `incrond` is very lightweight).

**Comment by doronbehar** [comment]
I use syncthing for that now. Closing.
