### ISSUE TITLE
Building RPM Package for CentOS 7 having issues with libcurl-devel 7.29.0

### ISSUE THREAD

**Issue by himabindugit** [transmission/transmission#4671]
### What is the issue?

Opening this issue as part of https://github.com/transmission/transmission/issues/4594 on behalf of @krazak

Building the RPM package for CentOS 7, I get the following error:

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/22843777/214874031-268ab72d-a41d-4733-960f-c7c0d84c2f8c.png">

The problem is that to resolve this issue, version 7.81.0 of curl needs to be installed. When I use 
`yum install libcurl-devel` the curl version that is installed is 7.29.0. 
I have not found a later version than 7.29.0 for CentOS 7. Thanks!

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

https://github.com/transmission/transmission/pull/4643

**Comment by ckerr** [comment]
Introduced in https://github.com/transmission/transmission/pull/1661.

`CURL_VERSION_BITS` is a one-liner macro

```c++
#define CURL_VERSION_BITS(x,y,z) ((x)<<16|(y)<<8|(z))
```

So we can do this by hand

**Comment by krazak** [comment]
@ckerr Thanks for the fix!  There are also these errors that come up as well.

![image](https://user-images.githubusercontent.com/5414213/214905081-4857825b-836e-4b15-a5b1-8a3c394c7713.png)
