### ISSUE TITLE
Files placed in the Auto-add watch folder don't get automatically added until I quit and restart Transmission, or I manually move the files out of there and put them back in

### ISSUE THREAD

**Issue by dburr** [transmission/transmission#4683]
### What is the issue?

M1 Mac mini, macOS Ventura 13.2, Transmission 4.0.0-beta.3 (634b1e8fc1)

I set up the "auto-add: watch for torrent files in..." to watch my `$HOME/Downloads` folder. However, when I download a torrent file, it does not get picked up and auto-added. I can get it to auto-add if I manually move the file out of `$HOME/Downloads` and move it back using Finder, or if I quit and relaunch Transmission.

I have given Transmission "full disk access" btw.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by dburr** [comment]
Additional information: This appears to be specific to the `$HOME/Downloads` folder. I set up a Hazel rule that watches `$HOME/Downloads` and moves all `.torrent` files into a different directory (`$HOME/Torrents`) then changed Transmission to watch that directory. Now when I download torrent files, Hazel moves them to the other directory and Transmission picks them up immediately. (I'm using firefox btw, not sure if that matters or not.)

**Comment by Coeur** [comment]
(note: I don't use that feature)

Unless it's a system or app permission issue specific to `$HOME/Downloads`, then you may want to know that our auto-add detection code is old (potentially deprecated) and unmaintained. I wrote a lengthy comment about the multiple alternative APIs that could maybe (or not) be better than our current code:

https://github.com/transmission/transmission/blob/724a0f48f04075d3bfd23cea654ba22423fe63fd/macosx/VDKQueue/VDKQueue.h#L43-L90

**Comment by shatteredsite** [comment]
For the moment users of certain browsers (such as Brave) can choose to have specific file types open automatically. It is not a fix, but a good alternative for those looking for similar convenience who have the right browser(s).

**Comment by Coeur** [comment]
Someone mentioned a similar issue in #4959 but for Linux/GTK, so maybe that's not an issue with VDKQueue.

**Comment by kowalczt** [comment]
I have noticed, that if I download file with Safari, auto adding torrent file working fine.
When I download torrent file with Firefox, its not getting auto added.

**Comment by ckerr** [comment]
@Coeur could you check and see if there's anything in the macOS client's watchdir code that could be causing this? Also does the macOS client add any logging messages in the watchdir code that could help to triage this?

**Comment by Coeur** [comment]
kowalczt comment is on the spot.
I've added ~/Downloads for auto mode and:
- It works well with Safari 16.4
- It works well with Chrome 110
- It works well with Edge 110
- It works well with Opera 96
- It works well with Brave 1.48
- It works well with Vivaldi 5.7
- **It doesn't work with Firefox** 106-110
- I didn't try [360 Browser](https://browser.360.cn/ee/mac/)

**Comment by Coeur** [comment]
When using Firefox, it seems they aren't doing an atomic download: the downloaded file is first empty, and then they populate it afterward. So our code will fail here:
https://github.com/transmission/transmission/blob/47fd150babf65cde1eb3b197f2e7f860defc3474/macosx/Controller.mm#L3584-L3587

We do have a timer to retry 10 seconds later:
https://github.com/transmission/transmission/blob/47fd150babf65cde1eb3b197f2e7f860defc3474/macosx/Controller.mm#L3517-L3521

But that retry is skipped for identical filenames, so it's a useless retry at the moment. The solution may be to remove the filename from known files when a parsing fails.

**Comment by Coeur** [comment]
OK, removing the filename from known files on parsing error does solve the issue. I'll prepare a PR.

**Comment by nevack** [comment]
@Coeur Interesting find.
I think we can look at extended attributes to check if file is fully downloaded.
https://stackoverflow.com/questions/56531821/reading-com-apple-progress-fractioncompleted-attribute-of-file

Finder displays download progress with this, I think.

**Comment by ckerr** [comment]
> kowalczt comment is on the spot for me. I've added ~/Downloads for auto mode and:
> 
> In Transmission 3.0.0:
> 
> * It works well with Firefox 110 (and other browsers)
> 
> In Transmission 4.0.1:
> 
> * It works well with Safari 16.4
> * It works well with Chrome 110
> * It works well with Edge 110
> * It works well with Opera 96
> * It works well with Brave 1.48
> * It works well with Vivaldi 5.7
> * **It doesn't work with Firefox** 106-110

That is some above & beyond testing. Thank you for doing all that!!

**Comment by shatteredsite** [comment]
@ckerr  Brave v1.48.171 does not work properly on MacOS with this feature on my machine. This needs more testing.

**Comment by Coeur** [comment]
I disagree @shatteredsite : I've tested Brave 1.48.171 and it works perfectly, before and after the patch.
**Please open a new issue if yours is different from the Firefox issue**, but be sure to test various browsers for comparison, explain which version of macOS you have, which build of Transmission you have, and of course verify that your Transmission settings are observing the same folder as the one that your browser is downloading to. Finally, verify that the torrent isn't corrupted when you open it manually. Thanks

**Comment by ckerr** [comment]
Just saying "still doesn't work" isn't super helpful but neither is "it does work."

Trouble is, if it really is not working for @shatteredsite it's difficult to report more information to help us figure out why it's not working. Maybe `macos/Controller.mm` could add debug log messages when skipping a file, e.g. when the file size is zero, so that users can see after-the-fact why a file wasn't added?

**Comment by nevack** [comment]
> @ckerr Brave v1.48.171 does not work properly on MacOS with this feature on my machine. This needs more testing.

What build were you testing it with?

**Comment by Coeur** [comment]
Shatteredsite could also be downloading .magnet files instead of .torrent files as far as we know. Really too few details, and we wouldn't want to mix different problems in the same issue. What has been addressed here was what got detailed by kowalczt, which was a reproducible and distinctive issue.

**Comment by shatteredsite** [comment]
I apologize for the lack of detail. Tested and failed under the following conditions:

- Transmission 4.0.1
- Ventura 13.2.1 on an M1 Macbook Pro
- Safari 16.3
- Brave Version 1.48.171 
- Firefox 110.0 (64-bit)

I only download .torrent files and manually opening .torrent files shows them to function fine with no sign of corruption.
I hope this clears things up.

**Comment by Coeur** [comment]
Since I can't reproduce this issue, can you:
- Please try latest nightly at https://build.transmissionbt.com/job/trunk-mac/
- double-check that in Transmission settings, "Auto add:" is observing the right folder? Put at least one new torrent file in that folder, then uncheck + recheck the option to figure out if that torrent file is opened when you recheck the option.
- System settings > Confidentiality and Security > Are you in "Isolation Mode" (at the bottom of the settings)? (normally, people aren't)
- open a new GitHub issue with that same information (about the three browsers that you've tested, the nightly build number, etc.).

Thanks.

**Comment by shatteredsite** [comment]
@Coeur The installation of the newest build seems to have fixed the issue. It did give me repeated prompts to allow for access to the Downloads folder and allow for incoming connections whenever the app was launched, but a restart fixed that.
