### ISSUE TITLE
Can't donate from russia

### ISSUE THREAD

**Issue by intelegenter** [transmission/transmission#4690]
### What is the issue?

Can't donate from russia :/

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 3.00 (bb6b5a062e)

**Comment by intelegenter** [comment]
you should fix that!

**Comment by robd003** [comment]
I'd donate via crypto if I could. (BTC / ETH / ADA)

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/discussions/4140
