### ISSUE TITLE
Transmission fails to use webseed if any file in the torrent has a colon in its name

### ISSUE THREAD

**Issue by Siguza** [transmission/transmission#4693]
### What is the issue?

For any torrent that contains even one file whose name contains a colon, Transmission seems to be completely unable to download from webseeds.  
Downloading from peers works fine.

Example torrent from archive.org that triggers the issue: https://archive.org/download/install-assistant-12.0-dp-4-pb-3/install-assistant-12.0-dp-4-pb-3_archive.torrent

(Note that on macOS, Finder will show colons in file names as `/` instead.)

### Which application of Transmission?

macOS app

### Which version of Transmission?

3.00 (f4489c982e)

**Comment by tearfur** [comment]
Fixed by #3823.
