### ISSUE TITLE
Googletest warnings

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4697]
### What is the issue?

I've truncated the output, but crazy amount of warnings when building googletest.

[googletest-warnings.txt](https://github.com/transmission/transmission/files/10549841/googletest-warnings.txt)

Latest release was two weeks ago. https://github.com/google/googletest/releases/tag/v1.13.0

Edit: I tried the latest version. It compiles fine, but has about the same number of warnings :-(

### Which application of Transmission?

None

### Which version of Transmission?

Beta 3 on Linux

**Comment by ckerr** [comment]
Please report this upstream to https://github.com/google/googletest/issues. It's not a Transmission issue & is not fixable in `transmission/transmission`.

Though, I am kind of curious why you're seeing these warnings and I'm not. @GaryElshaw how are you building Transmission? e.g. could you attach your `build/CMakeFiles/CMakeOutput.log` file?

**Comment by GaryElshaw** [comment]
Will do. Here's the log.

[CMakeOutput.log](https://github.com/transmission/transmission/files/10560361/CMakeOutput.log)

**Comment by ckerr** [comment]
looks like the difference might be between g++-11 and g++12. :shrug:

**Comment by GaryElshaw** [comment]
What should or could we do?

**Comment by GaryElshaw** [comment]
Reported upstream https://github.com/google/googletest/issues/4141

**Comment by ckerr** [comment]
...shouldn't you tell them what warnings you're seeing? e.g. paste the contents of [googletest-warnings.txt](https://github.com/transmission/transmission/files/10549841/googletest-warnings.txt) into the issue description?

**Comment by GaryElshaw** [comment]
I thought the cmake log would suffice because of where the warnings appear.

**Comment by GaryElshaw** [comment]
I'll do that then.

**Comment by GaryElshaw** [comment]
FYI https://github.com/google/googletest/issues/4141#issuecomment-1414764151
