### ISSUE TITLE
Creating a new torrent - file chooser doesnt let me select directory

### ISSUE THREAD

**Issue by jubalh** [transmission/transmission#4703]
### What is the issue?

I'm unsure whether this is a problem with the gtk file chooser.

Let's say I have a directory structure like:
`files/src/glib` which contains:

```
drwxr-xr-x user user 280 B  Wed Jun 29 15:49:13 2022 docs
drwxr-xr-x user user 1.0 KB Wed Jun 29 15:49:13 2022 fuzzing
drwxr-xr-x user user  18 KB Wed Jun 29 15:49:13 2022 gio
drwxr-xr-x user user 4.9 KB Wed Jun 29 16:05:03 2022 glib
drwxr-xr-x user user 218 B  Wed Jun 29 15:49:13 2022 gmodule
drwxr-xr-x user user 1.4 KB Wed Jun 29 15:49:13 2022 gobject
drwxr-xr-x user user  98 B  Wed Jun 29 15:49:13 2022 gthread
drwxr-xr-x user user 182 B  Wed Jun 29 15:49:13 2022 LICENSES
drwxr-xr-x user user 126 B  Wed Jun 29 15:49:13 2022 m4macros
drwxr-xr-x user user 1.2 KB Wed Jun 29 15:49:14 2022 po
drwxr-xr-x user user 168 B  Wed Jun 29 15:49:14 2022 subprojects
drwxr-xr-x user user 210 B  Wed Jun 29 15:49:14 2022 tests
drwxr-xr-x user user 102 B  Wed Jun 29 15:49:14 2022 tools
.rwxr-xr-x user user 135 B  Wed Jun 29 15:49:13 2022 CODE_OF_CONDUCT.md
.rwxr-xr-x user user  11 KB Wed Jun 29 15:49:13 2022 CONTRIBUTING.md
.rwxr-xr-x user user 5.5 KB Wed Jun 29 15:49:13 2022 glib.doap
.rwxr-xr-x user user 576 B  Wed Jun 29 15:49:13 2022 HACKING
.rwxr-xr-x user user 4.5 KB Wed Jun 29 15:49:13 2022 INSTALL.md
.rwxr-xr-x user user  77 KB Wed Jun 29 15:49:13 2022 meson.build
.rwxr-xr-x user user 3.2 KB Wed Jun 29 15:49:13 2022 meson_options.txt
.rwxr-xr-x user user 2.2 KB Wed Jun 29 15:49:13 2022 msvc_recommended_pragmas.h
.rwxr-xr-x user user 562 KB Wed Jun 29 15:49:13 2022 NEWS
.rwxr-xr-x user user 3.2 KB Wed Jun 29 15:49:13 2022 README.md
.rwxr-xr-x user user 7.4 KB Wed Jun 29 15:49:13 2022 README.win32.md
.rwxr-xr-x user user 3.5 KB Wed Jun 29 15:49:13 2022 SECURITY.md
```

I want to create a torrent with the whole `glib` directory. But the file select always automatically highlights/selects the first entry of the list. So whenever I press `open` it will open into this directory and I have no way of actually sharing the "parent" directory `glib`. In this example it will open `docs`.

![asdf](https://user-images.githubusercontent.com/1658215/216051853-359aae69-0f58-47e7-a92f-7e181f30460b.png)

A workaround would be if I could edit/paste the path in Transmission itself after selecting it via file choose. But that isn't supported.

Am I doing something wrong or would you mind to add a way to edit the filepath manually?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

3.00 (bb6b5a062e)

**Comment by ckerr** [comment]
Hi, thanks for reporting this.

> But the file select always automatically highlights/selects the first entry of the list. 

I'm not able to reproduce this in `main` (latest release from that branch is 4.0.0-beta.3).

When I try to create a new torrent from a folder in transmission-gtk, I get this:

![new-torrent-folder-gtk](https://user-images.githubusercontent.com/70381/216228267-096bab8f-e46d-48e4-b955-6a287893beed.png)

(i.e., when the dialog opens up initially there is no default selection.)

Maybe it's a GTK theming issue? I'm not sure. Does it work for you in 4.0.0-beta.3?


> So whenever I press open it will open into this directory and I have no way of actually sharing the "parent" directory glib. 

You would go up to the parent directory, then select the `glib` folder and hit 'Open"?

**Comment by ckerr** [comment]
I'm unable to duplicate this and it feels like a GTK issue rather than a Transmission one, so I'm going to close this issue as 'not Transmission'.

If anyone thinks this is in error, please file a new bug and let me know how I was wrong. Thank you!

**Comment by jubalh** [comment]
I also have this behaviour with the 4.0.0 release.
I don't use a custom theme. All is set to default Adwaita on openSUSE Tumbleweed with GNOME 43.2.
