### ISSUE TITLE
Third-Party dependencies

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4704]
### What is the issue?

I know i'm totally in the minority, but could @mikedld and @ckerr please take a look at the dependencies before 4.0? I don't mean necessarily updating them, i just mean having a look at changes, generally, and considering whether Transmission would benefit, before 4.0.

### Which application of Transmission?

None

### Which version of Transmission?

4.0

**Comment by ckerr** [comment]
No.

I'm in the middle of deciding whether to go to 4.0.0 stable or to do one final beta because of #4665. Now is not the time to be changing dependencies. 

No dependency bumps pre-4.0.0 unless they address a specific blocker bug or security vulnerability.

**Comment by GaryElshaw** [comment]
You know i can be obstreporous, but isn't it just good governance?

**Comment by GaryElshaw** [comment]
#4665 introduced something different for me, it would be great to have some feedback from @hauuau

**Comment by ckerr** [comment]
> You know i can be obstreporous, but isn't it just good governance?

Good governance is not introducing last-minute changes that can have unknown consequences

**Comment by GaryElshaw** [comment]
Agreed. But reintrodcing "depndencies" that haven't been updated since 2013 strikes me as terrible.

**Comment by GaryElshaw** [comment]
It feels like i'm stuck in this terrible conundrum; i raise the issue that i think the project needs to constantly pay attention to dependencies; and also being told i should have raised this sooner.

**Comment by nevack** [comment]
> It feels like i'm stuck in this terrible conundrum; i raise the issue that i think the project needs to constantly pay attention to dependencies; and also being told i should have raised this sooner.

Thanks for raising attention, but IMO it's not a priority for 4.0 release.
We need a stable ground, not to update everything in the sake of update itself

**Comment by GaryElshaw** [comment]
Then you've missed my point.

**Comment by ckerr** [comment]
Unless there's a specific blocker bug or security vulnerability, no more dependency bumps for 4.0.0.

>  It feels like i'm stuck in this terrible conundrum; i raise the issue that i think the project needs to constantly pay attention to dependencies; and also being told i should have raised this sooner.

There is no catch-22 here: if you suggest a dependency bump when we're not freezing for a stable release, that bump will be given more serious consideration. When you have reported dependency bumps in the past I have considered them on the merits, e.g. #4613, #4476, #3489. 

> Agreed. But reintroducing "depndencies" that haven't been updated since 2013 strikes me as terrible.

The year isn't a reason why.

If you have a specific blocker bug or security vulnerability that's present in a third-party lib that we use and which is fixed in a newer version, please report *that*.

**Comment by GaryElshaw** [comment]
It's obviously a difference of opinion, and i need to give up. As both of us have tried to explain multiple times, we differ how dependencies, by definition, should be treated as such.

"The year isn't a reason why."

I disagree on that, i think the year is a reason why. And that would be fine, but i'm constantly told that no one seems to care about that. And a depndency that has been updated multiple times since 2013 and has not been integrated seems bizarre to me. Where it feels like i'm being gaslit to be told i should have raised something sooner (when i did), and now it's too late before a major release?

**Comment by ckerr** [comment]
I don't know how I can be any clearer about this: If you have a specific blocker bug or security vulnerability that's present in a third-party lib that we use and which is fixed in a newer version, please report that.

**Comment by ckerr** [comment]
> I disagree on that, i think the year is a reason why.

Based on what criteria?

**Comment by ckerr** [comment]
> I disagree on that, i think the year is a reason why.

Based on what criteria?

**Comment by GaryElshaw** [comment]
Because, in that particular case, hardware.

I need to pull back from the project. It's just not how i manage projects, and the focus i want to see is irrelevant. I need to be less around.

**Comment by ckerr** [comment]
@GaryElshaw I see that you're frustrated and I understand that. 

I may have contributed to that with the phrasing of my original reply. It was not my intention to "gaslight" and am not trying to exacerbate any frustration. Let me try again:

> I appreciate the thought, but we're getting really close to a stable 4.0.0 release and all the dependencies in 4.0.0-beta.3 seem to be working okay, so for 4.0.0 let's stick with those dependencies unless there's some specific issue.
>
> If there _is_ a specific issue in the 4.0.0-beta.3 dependencies, let's, let's decide if it rises to the level of "is it a security vulnerability? Is there a critical feature that it breaks?"  

Anyway. If you're still willing to engage, I don't understand your explanation of "the year is a reason why" because "hardware."

**Comment by GaryElshaw** [comment]
The raison detre of the miniupnp project is dealing with contemporary router systems. Being contemporaneous, feels, to me, like it should be a given for Transmission.

**Comment by ckerr** [comment]
What hardware works on newer versions of these libraries but not on the versions shipping in 4.0.0-beta.3?

**Comment by ckerr** [comment]
OK this is the third time you've said you want to step away from the project and I keep this conversation going. Sorry about that; I'll respect your wishes.
