### ISSUE TITLE
upload ratio mismatch in different client

### ISSUE THREAD

**Issue by zero-custom** [transmission/transmission#4708]
### What is the issue?

![20230202183902](https://user-images.githubusercontent.com/22925474/216302559-c04d5b11-bd40-49a5-897f-a3409efab55c.png)

Total Size:4.3G
Downloaded:306M
Uploaded:47G
qt client's progress bar shows upload ratio is 154, but property page shows 10.9
webui shows the same as the property page.

whether i download all files or not, the upload ratio always uploaded / total size, but the progress bar shows upload ratio is uploaded / dowloaded. 
did the calculation changed or something else?

### Which application of Transmission?

None

### Which version of Transmission?

4.0.0-beta.3

**Comment by svkirillov** [comment]
I have the same issue on macOS:
<img width="205" alt="Screenshot 2023-02-27 at 13 16 58" src="https://user-images.githubusercontent.com/33870726/221562172-198a7cdb-2e3b-44a8-920e-1da0dcc6c1a4.png">
