### ISSUE TITLE
How to ban a client ?

### ISSUE THREAD

**Issue by SeAL80s** [transmission/transmission#471]
![screenshot_2018-01-16_19-13-04](https://user-images.githubusercontent.com/12682385/34986209-b0fa3008-faf1-11e7-86b6-e15f2a4c689f.png)
As the screenshot shows ,how to ban client like Xunlei and Thunder ?

**Comment by mikedld** [comment]
There is currently no way of banning clients by name. If you want to ban specific IP addresses you could use [blocklist](/transmission/transmission/wiki/Blocklists) functionality.

**Comment by ArchieMeng** [comment]
You may write a script on your own.
Here is an example I found.
https://zhuanlan.zhihu.com/p/158711236
