### ISSUE TITLE
two event objects leaked during shutdown of transmission-daemon

### ISSUE THREAD

**Issue by icy17** [transmission/transmission#4714]
### What is the issue?

Potential memory leak in [daemon-posix.cc](https://github.com/transmission/transmission/blob/main/daemon/daemon-posix.cc#L73) line 73 Calling event_new() without calling event_free() to free the memory will cause a memory leak.
[Doc](https://libevent.org/doc/event_8h.html#a1f326019b65d319b2221b7e57d56c273) says "Deallocate a struct event * returned by [event_new()](https://libevent.org/doc/event_8h.html#a6cd300e5cd15601c5e4570b221b20397)."
![image](https://user-images.githubusercontent.com/39425646/216762330-c0eff5bc-c586-4ac4-a3ef-469597329e7c.png)

### Which application of Transmission?

transmission-daemon

**Comment by ckerr** [comment]
This is correct and the bug ought to get fixed for cleanliness' sake & to make leak detectors happy -- but FWIW but in practice this is called twice during daemon setup and the allocated events exist for the lifespan of the daemon session, so end users won't see any loss of memory due to this bug.

**Comment by tearfur** [comment]
Fixed by #5695.
