### ISSUE TITLE
Transfers initiated via RPC starting paused (4.0.0-beta.3.dev (fbb98ada4a))

### ISSUE THREAD

**Issue by davidsonb** [transmission/transmission#4715]
### What is the issue?

This is an issue I have noticed ever since the v4 betas were available. Auto downloaders or other tools (Medusa, Chrome ext Remote Transmission ++, etc) that use the RPC to add torrents, for all torrents, the torrents starts paused. It seems to add the torrent started, with peers loading up and meta data loading, but it appears as soon as the meta data is fully loaded, the torrent pauses. Either "stalled, paused" or "paused" depending on if the transfer is stalled option is enabled or not.

No changes to seeding ratio, stop when inactive, or transfer is stalled options, in either Transmission App or clients, seem to affect the results. If I switch back to running Transmission v3 with the same config in transmission and the clients, the problem goes away.

Thanks,

Bradley

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3.dev (fbb98ada4a)

**Comment by gaspoweredflea** [comment]
Same happening here.

**Comment by ckerr** [comment]
This is a subset of https://github.com/transmission/transmission/issues/4740 so I'm going to close this one as a duplicate even though it was filed first.
