### ISSUE TITLE
Transmission window disappears and then reappears on display

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#4717]
### What is the issue?

Beta 3 main window (3 active downloads and 4 uploads) suddenly disappears from display. Icon remains in dock indicating the app is active but there are no active transmissions. Approximately 5 seconds later the window reappears on display - first an empty, then all the transmissions are back, one after one. No any crashlogs. It's behavior I observe for the first time ever since I use TM.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by Coeur** [comment]
I've never experienced that. My guts is that could be some sort of Apple issue in your configuration? (which version of macOS, how many displays, Intel or Apple Silicon?)

**Comment by Tockman** [comment]
Me too, before yesterday. macOS Ventura 13.2, one display, Intel.

**Comment by Coeur** [comment]
Totally speculative, but could be from #4696: you had an exception raised which caused some thread/view to crash but got recreated somehow.

**Comment by ckerr** [comment]
> Totally speculative, but could be from #4696: you had an exception raised which caused some thread/view to crash but got recreated somehow.

That change isn't in 4.0.0-beta.3 though?

**Comment by Coeur** [comment]
Ah right, I thought Tockman was using nightlies. Well, then wrong lead.

**Comment by Tockman** [comment]
> Ah right, I thought Tockman was using nightlies. Well, then wrong lead.

No, I was not.

**Comment by ckerr** [comment]
Is this still an issue in 4.0.1?

**Comment by Tockman** [comment]
No, nothing similar fortunately.
