### ISSUE TITLE
[macOS] Repeated Permissions Request

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4718]
### What is the issue?

After updating to the latest build I'm getting a recurring pop-up requesting access to where all of the torrents are saved.

It's annoying because it appears to be requesting access for each torrent individually.

<img width="272" alt="Screen Shot 2023-02-04 at 8 15 20 PM" src="https://user-images.githubusercontent.com/571328/216796688-6783a683-ecc0-4fa1-8ce4-811761541e8f.png">

Transmission was already granted these permissions:

<img width="662" alt="Screen Shot 2023-02-04 at 8 20 39 PM" src="https://user-images.githubusercontent.com/571328/216796829-f6a1ad4d-ba66-450d-a178-7663d2624b7a.png">

This is on macOS 12.6.3

### Which application of Transmission?

macOS app

### Which version of Transmission?

fbb98ad

**Comment by robd003** [comment]
I've tried granting Transmission "Full Disk Access" but even after that it still sends multiple requests to give permissions to the Documents folder.

**Comment by robd003** [comment]
Tried rolling back to an earlier build, but the same issue persists

**Comment by robd003** [comment]
attempting ```sudo tccutil reset Accessibility``` to see if this will fix it

**Comment by robd003** [comment]
Tried resetting permissions: ```$ sudo tccutil reset All org.m0k.transmission
Password:
tccutil: executable_is_endpoint_security_client failed for path file:///Applications/Transmission.app/Contents/MacOS/Transmission with error: code object is not signed at all```

**Comment by Coeur** [comment]
If it says "code object is not signed at all", then the question may be how did you build it? With `make`, `ninja`, `Xcode` or did you download one of the nightlies?

**Comment by mikedld** [comment]
I don't see how this is different from #2171 and #3680. Closing as duplicate.
