### ISSUE TITLE
ipv6 support for UDP trackers

### ISSUE THREAD

**Issue by L2501** [transmission/transmission#4719]
### What is the issue?

https://www.bittorrent.org/beps/bep_0015.html
IPv6 announces have the same structure as v4 ones, including the used action number except that the stride size of <IP address, TCP port> pairs in the response is 18 bytes instead of 6.

As far as I understand, the current code incorrectly interprets these 18 bytes as 3 pairs of <IPv4 address, TCP port>.
Example:
![wrong_ipv6](https://user-images.githubusercontent.com/1921370/216807535-1a3c925a-b754-443e-81e7-8ec978cf728c.png)

Maybe udp announces should be limited to ipv4 only ? https://github.com/transmission/transmission/blob/fbb98ada4ae8b90f9d76a91fbc0de4ff18662669/libtransmission/announcer-udp.cc#L412

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0-beta.3.dev (fbb98ada4a)

**Comment by ckerr** [comment]
The relevant part of bep 15:

> Which format [ipv4 vs ipv6 addresses] is used is determined by the address family of the underlying UDP packet. I.e. packets from a v4 address use the v4 format, those from a v6 address use the v6 format.

**Comment by ckerr** [comment]
Ideally this should be fixed before 4.0.0 but that is set to come out in a few days. If we wait longer than that the project may miss Debian's freeze.

The proper fix is to support both address types. I'll take a look tonight and see how risky that is as a last-minute change. If the diff is took big then I agree with @L2501 that we could just do announces on ipv4 for 4.0.0, and pick up the rest in a patch release

**Comment by ckerr** [comment]
You know what, I think the last comment answers its own question. 4.0.0 has been in the works for like 18 months now; I shouldn't do anything that could introduce a last-minute bug.

Let's go with the minimal do-no-harm fix for 4.0.0

**Comment by ckerr** [comment]
This issue was auto-closed when #4723 was merged.

I'm re-opening it now for the bigger fix of supporting both ipv4 and ipv6 udp announces

**Comment by ckerr** [comment]
Re-tagging this bug as a feature again now that we're in the "also support udp6 announces" phase

**Comment by Pentaphon** [comment]
> I'm re-opening it now for the bigger fix of supporting both ipv4 and ipv6 udp announces

@L2501 Looks like tearfur might have fully resolved this in time for 4.1.0
