### ISSUE TITLE
Missing documentation for #468

### ISSUE THREAD

**Issue by holomorph** [transmission/transmission#472]
cf7173df9 adds flags that are undocumented.  Apparently now a Host: header is required for RPC, this is also undocumented in the rpc spec.

**Comment by mikedld** [comment]
Thanks for reporting. rpc-spec.txt updated in 2.9x branch, keys info added to [Editing Configuration Files](/transmission/transmission/wiki/Editing-Configuration-Files) wiki page. Will close once merged to master.

**Comment by holomorph** [comment]
Thank you!
