### ISSUE TITLE
Transmission-gtk crash

### ISSUE THREAD

**Issue by legluondunet** [transmission/transmission#4720]
### What is the issue?

When I launch Transmission-gtk et let the window open, when I alt+tab or click on another window, it crashes.
But if I launch it with this command in a terminal:
LANG=C transmission-gtk
it doesn't crash.

I use the same workaround as described on this issue:
https://github.com/transmission/transmission/issues/1353

transmission-gtk version 3.00 (bb6b5a062e), official package from MANJARO

My config:
OS: Manjaro 22.0.2 Sikaris
Kernel: x86_64 Linux 6.1.9-1-MANJARO
CPU: AMD Ryzen 9 5900HX with Radeon Graphics @ 16x 3.3GHz
GPU: AMD Radeon RX 6600M (navi23, LLVM 15.0.7, DRM 3.49, 6.1.9-1-MANJARO)
Video drivers: Mesa 22.3.4

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

3.00 (bb6b5a062e)

**Comment by ckerr** [comment]
Does this happen in 4.0.0-beta.3 for you as well?

**Comment by legluondunet** [comment]
How can I obtain this beta?

**Comment by ckerr** [comment]
https://transmissionbt.com/download

**Comment by legluondunet** [comment]
I just installed transmission-gtk 4.0.0-beta.3 (634b1e8fc1) official package from ARCH.
I close the this issue during my tests. If I will reopen this issue if necessary. Cross fingers.
Thank you for your answers.
