### ISSUE TITLE
macOS client keeps asking for folder permission

### ISSUE THREAD

**Issue by AaronVanGeffen** [transmission/transmission#4727]
### What is the issue?

The macOS client keeps asking for Download folder read/write permission. I've tried resetting the permissions in the 'Security & Privacy' screen, but the permission prompt keeps popping up.

The prompt doesn't just pop up once, either. Once I give permission, another pops up. This happens at least five times.

For what it's worth, the v3 client does not present this issue.

<img width="260" alt="Screenshot 2023-02-06 at 23 18 18" src="https://user-images.githubusercontent.com/604665/217100303-0bdbd9d3-883e-44a9-9ca1-2978077a4b24.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3.dev (3fb1f8bcd7)

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/2171
