### ISSUE TITLE
Magnet links deleted after updating

### ISSUE THREAD

**Issue by AtomicPip** [transmission/transmission#4733]
### What is the issue?

I lost several hundred magnet links when I updated to v4.0 on macOS. Has this been reported before? They were either in a paused or stalled state.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by killemov** [comment]
Please search before you post. Duplicate of #4295.

**Comment by ckerr** [comment]
Closing as duplicate of 4295
