### ISSUE TITLE
4.0.0 won't start on Windows 7: unable to start correctly (0xc0000005)

### ISSUE THREAD

**Issue by hardhub** [transmission/transmission#4734]
### What is the issue?

Application cannot start:

![image](https://user-images.githubusercontent.com/4306334/217476059-2d24348e-2a4b-4e8d-81ad-0641c0209ce9.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0 latest released

**Comment by mikedld** [comment]
Could you please provide information from Event Viewer? Similar to this: 
![image](https://user-images.githubusercontent.com/298203/217640243-a60b8caf-419d-426f-9330-b131f44a62f4.png)

**Comment by hardhub** [comment]
No event in log:

![image](https://user-images.githubusercontent.com/4306334/217658024-9b688298-5f90-4c57-98e7-44c4e737aa4a.png)

It asked for VC++ redist libs, I have installed corresponding ones from Visual Studio 2022.

After that it shows error message on start (0xc0000005), but there is no message about that error in EventLog.

I tested on 2 different PC - result is the same. On 2nd PC VC++ was already there, so it shows error (0xc0000005) without any log events at all.

In information log I can find what is installed as VC++ libs:

```
Product: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.32.31332 -- Installation completed successfully.
Product: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.32.31332 -- Installation completed successfully.

```

P.S. URL in message from event log is not correct.

**Comment by mikedld** [comment]
It's not the program itself but the OS that is showing the error dialog, so I'm not sure why there's no error in the log. Since you seem to have MSVS installed already, debugging it might be the next thing to try. Debug symbols could be found in the release alongside the .msi files: https://github.com/transmission/transmission/releases/tag/4.0.0

> P.S. URL in message from event log is not correct.

I tested it and it is correct. If it's not working for you then something else must be going on on your end.

<details>

```
% curl -LI https://aka.ms/vs/17/release/vc_redist.x64.exe
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Server: Kestrel
Location: https://download.visualstudio.microsoft.com/download/pr/bcb0cef1-f8cb-4311-8a5c-650a5b694eab/2257B3FBE3C7559DE8B31170155A433FAF5B83829E67C589D5674FF086B868B9/VC_redist.x64.exe
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
Expires: Wed, 08 Feb 2023 22:09:39 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 08 Feb 2023 22:09:39 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200 
accept-ranges: bytes
age: 157627
apiversion: Distribute 1.1
cache-control: public, max-age=259200
content-disposition: attachment; filename=VC_redist.x64.exe; filename*=UTF-8''VC_redist.x64.exe
content-type: application/octet-stream
date: Wed, 08 Feb 2023 22:09:40 GMT
etag: "0xCE7FC9A2571CBCCE3C666EB06CD7AE3CD44A1C03E3E15F3C02A6AC26CB91B4E5"
last-modified: Wed, 12 Oct 2022 04:35:37 GMT
server: ECAcc (lis/2E8A)
x-azure-ref: <snip>
x-cache: HIT
content-length: 25466016
```
</details>

**Comment by hardhub** [comment]
> I tested it and it is correct. If it's not working for you then something else must be going on on your end.

I see....

![image](https://user-images.githubusercontent.com/4306334/217665100-5bb12937-402f-4b6c-be05-cfa81b34ade1.png)

but I just tried yesterday, maybe my bad ))

I just tried downloaded version from (https://aka.ms/vs/17/release/vc_redist.x64.exe) on VM and it shows me the same error. But it is not clean machine. Maybe I need to install it from scratch for tests.

And I will try to debug.

**Comment by ckerr** [comment]
@hardhub what version of Windows are you running?

**Comment by dftf-stu** [comment]
@hardhub , @mikedld , @ckerr : Qt 6 does not support Windows 7 or 8, and looking at the "qwindows.dll" file that Transmission 4.0 ships-with reports version 6.4.0.0.

As such Transmission 4.0 will require Windows 10 or later, and you should update the "Downloads" page (https://transmissionbt.com/download) to say "Requires Windows 10 or later", instead of currently advising Windows 7 or later will work.  (I'm going to guess this is a leftover from when version 3.0 was there, and someone has forgot to update it.)

Transmission 3.0 will be the last for Windows 7, and 2.84.9 the last for XP and Vista.  Maybe somewhere it would be worth noting those are the final-versions for those platforms, such as on the "Previous Releases" page?

**Comment by dftf-stu** [comment]
@hardhub: if you need an up-to-date Torrent client for _Windows 7_, [qBittorent](https://www.qbittorrent.org/download.php) still works... just make-sure you download an installer that says "Uses Qt5" next to it.  Similar to _Transmission_, the Qt6 releases will only work on _Windows 10_ or later.

However, **32-bit** _Windows 7_ isn't supported in their latest release: if your PC has that, download 4.4.5 from [here](https://www.fosshub.com/qBittorrent-old.html) or [here](https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.4.5/).

**Comment by ckerr** [comment]
Transmission 4.0.0's minimum Qt version is 5.6, so @mikedld wdyt about doing a similar "Uses Qt5" build?

**Comment by mikedld** [comment]
I'd like to figure out what the actual issue is first. "Is not officially supported" doesn't necessarily mean "won't work", especially since we're building Qt ourselves and not using prebuilt packages provided by the upstream.

**Comment by dftf-stu** [comment]
@mikedld : if there is anything we can do, let us know.  However **Event Viewer** doesn't detail anything other-than the original error-message ("The application was unable to start correctly (0xc0000005). Click OK to close the application.") and all I can confirm is I have the latest-release of the Visual C++ 2015-2022 Redistributable (14.34.31931) installed (both the x86 and x64 installs).

While the error-message was on-screen though, I right-clicked the "transmission-qt.exe" process in _Task Manager_ and did the "Create dump file" option.  Maybe that file, which you can find inside [transmission-qt.zip](https://github.com/transmission/transmission/files/10690984/transmission-qt.zip), might help you?

**Comment by hardhub** [comment]
> @hardhub what version of Windows are you running?

@ckerr Windows 7 (6.1 SP1)

**Comment by hardhub** [comment]
> @hardhub: if you need an up-to-date Torrent client for _Windows 7_, [qBittorent](https://www.qbittorrent.org/download.php) still works... just make-sure you download an installer that says "Uses Qt5" next to it. Similar to _Transmission_, the Qt6 releases will only work on _Windows 10_ or later.
> 
> However, **32-bit** _Windows 7_ isn't supported in their latest release: if your PC has that, download 4.4.5 from [here](https://www.fosshub.com/qBittorrent-old.html) or [here](https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.4.5/).

@dftf-stu 
I use x64 version, but it is better to stick with Transmission, because I also has it on Linux. So single client is much better than multiple.

@ckerr 
Transmission 4.0.0's minimum Qt version is 5.6, so @mikedld wdyt about doing a similar "Uses Qt5" build?

It will be very good if Windows 7 will be supported! I use it even with modern hardware from AMD like 5950x (it is needed to avoid ASRock mobo to get signed drivers). I planned migration to Linux, but it will be not fast and has its own drawbacks.
So if you have the way to support Windows 7 then I will be very appreciated.

**Comment by ckerr** [comment]
> I'd like to figure out what the actual issue is first. "Is not officially supported" doesn't necessarily mean "won't work", especially since we're building Qt ourselves and not using prebuilt packages provided by the upstream.

@mikedld I don't know if it's related to the 0xc0000005 issue, but I'd be hesitant to try and make a Qt6 app run on Windows 7 -- upstream has removed the Windows 7 specific codepaths from their repo: https://bugreports.qt.io/browse/QTBUG-84432

**Comment by hardhub** [comment]
@mikedld 

```
>	ntdll.dll!RtlInitAnsiString()
 	ntdll.dll!string "Enabling heap debug options\n"()
 	ntdll.dll!LdrpSnapIAT()
 	ntdll.dll!LdrpHandleOneOldFormatImportDescriptor()
 	ntdll.dll!LdrpProcessStaticImports()
 	ntdll.dll!LdrpLoadImportModule()
 	ntdll.dll!LdrpHandleOneOldFormatImportDescriptor()
 	ntdll.dll!LdrpProcessStaticImports()
 	ntdll.dll!LdrpLoadImportModule()
 	ntdll.dll!LdrpHandleOneOldFormatImportDescriptor()
 	ntdll.dll!LdrpProcessStaticImports()
 	ntdll.dll!LdrpInitializeProcess()
 	ntdll.dll!string "Enabling heap debug options\n"()
 	ntdll.dll!LdrInitializeThunk()

```
`Exception thrown at 0x0000000077063D04 (ntdll.dll) in transmission-qt.exe: 0xC0000005: Access violation reading location 0x000007FEFC9E1456.`

**Comment by dftf-stu** [comment]
Until it has been decided whether a Qt5 build for Windows 7 and 8 will be offered, can I at-least suggest someone updates the "Downloads" page please to avoid any-further confusion?

There is little-point saying "Windows 7 or later" if we now-know for-sure it isn't working on that OS:
![Screenshot 2023-02-09 091719](https://user-images.githubusercontent.com/83965343/217769792-6d700657-a174-4118-83f2-f965b3d5c340.png)

Leaving it as it is currently will only mean more people try it, get an issue, and then may file duplicate reports on here!

**Comment by andradadad** [comment]
Also having the same problem. I believe it's the windows 7 Ultimate SP1 x64 incompatibility.
No event log. C++ updated on link.
