### ISSUE TITLE
Magnet links are still paused when added (4.0)

### ISSUE THREAD

**Issue by PetersenLars** [transmission/transmission#4740]
### What is the issue?

After having this issue since the first 4.0 beta build and updating to the new release, something is still preventing magnet links to automatically start when added. I tried removing preferences and reinstalling, but unfortunately that didn't help. Any other things I could try?

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0(280ace12f8)

**Comment by CrimsonVex** [comment]
I am also having this issue on windows, Transmission 4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
CC @sweetppro, @Coeur

**Comment by Pentaphon** [comment]
> I am also having this issue on windows, Transmission 4.0.0 ([280ace1](https://github.com/transmission/transmission/commit/280ace12f8a2b99fdf144011cd4f6fed8be876fe))

I am also seeing this behavior on Windows 11. Never really used magnets but I did just now and I was shocked to have it show up as paused after downloading the metadata from X peers.

**Comment by Coeur** [comment]
I noticed this:
- if you kept Transmission open the whole time, then magnet links will start after getting metadata
- if you closed and reopened Transmission, then magnet links will be paused after getting metadata

**Comment by mad-tunes** [comment]
I've just updated to 4.0.0 and see the same. Running as a service on windows server 2022
I've got 'Start added torrents' tikced, but they're starting paused.

**Comment by mad-tunes** [comment]
I've just updated to 4.0.0 (280ace12f8) and see the same. Running as a service on windows server 2022
I've got 'Start added torrents' in preferences ticked & settings.json includes "start-added-torrents": true, but they're left paused.
Same when I have the torrent options dialog show and set torrents to start individually from there.
Unfortunately this breaks the 'workflow' of using it with the *arr apps to automate downloads

**Comment by Pentaphon** [comment]
This should really go in the 4.0.1 milestone. I just confirmed it on my 2nd Windows machine. 

https://github.com/transmission/transmission/milestone/12

**Comment by sweetppro** [comment]
@ckerr the fix I provided was macOS specific. It looks like it also needs to be implemented for other systems.

**Comment by ckerr** [comment]
@sweetppro the person reporting this bug is using the macOS app

**Comment by PetersenLars** [comment]
Yes exactly, I'm on a Mac mini M1 running on Mac OS 13.1.

**Comment by monchote** [comment]
I'm having the exact same issue on Linux.

**Comment by ckerr** [comment]
Yes, I do think it's a problem that exists on multiple platforms :dizzy:

**Comment by ehickox** [comment]
I am on 4.0.0 and still seeing this on Intel macOS 12.6

**Comment by GunbleR** [comment]
> @sweetppro the person reporting this bug is using the macOS app

Had it on [fbb98ad](https://github.com/transmission/transmission/commit/fbb98ada4ae8b90f9d76a91fbc0de4ff18662669). (after https://github.com/transmission/transmission/pull/4528)
Tried on freebsd 13.0 (truenas) jail.
also on ubuntu 22.04.1 vm.

.torent files start correctly.
setting "start-added-torrents": true,

**Comment by pstadler** [comment]
Same happens for me with docker using `linuxserver/transmission:latest` (4.0.0). No problem with the latest 3.x release.

**Comment by ckerr** [comment]
Self-assigning, but I'll probably need an assist on the macOS gui parts.

**Comment by programatix** [comment]
Similar to @pstadler, docker image [linuxserver/transmission:4.0.0](https://registry.hub.docker.com/layers/linuxserver/transmission/4.0.0/images/sha256-a6b7305765c4c44394af0f71bc92599519eba3238efb277b7bf79422f9b16fbd?context=explore) is showing this issue. It's running in my Synology NAS. Was okay before the update from version 3.

As a note, the magnet link did start the download when added, but it will pause after getting the metadata.

So this issue is not platform specific.

**Comment by ckerr** [comment]
> So this issue is not platform specific.

It is and isn't. The macOS client adds torrents into the system in a slightly different workflow than the RPC / Qt / GTK clients so it's kind of two bugs in one :dizzy:

**Comment by zero-custom** [comment]
a temporary solution:
edit settings.json, enable `script-torrent-added-enabled`, add a new script
```
#!/bin/sh

sleep 1
/usr/bin/transmission-remote -t $TR_TORRENT_ID -s
```

**Comment by programatix** [comment]
> a temporary solution: edit settings.json, enable `script-torrent-added-enabled`, add a new script
> 
> ```
> #!/bin/sh
> 
> sleep 1
> /usr/bin/transmission-remote -t $TR_TORRENT_ID -s
> ```

Doesn't seem to work for me. Could it be due to mine being password protected. I tried running it at command line and I get,
```
Unexpected response: <h1>401: Unauthorized</h1>
```

**Comment by subhashay** [comment]
I'm also facing the same issue on linuxserver docker. Thanks for the workaround for now!

**Comment by salvor-hardin** [comment]
The number of peers also doesn't seem to work. It goes up to the default 50 and it ignores everything added to the GUI or even the settings.json file.

Adding the peers to the command does fix it as a temp solution
/usr/bin/transmission-remote -t $TR_TORRENT_ID **--peers 200** -s

**Comment by GaryElshaw** [comment]
> The number of peers also doesn't seem to work. [snip]

@salvor-hardin Please file that as a separate issue, it needs to be examined.

**Comment by ckerr** [comment]
testers needed, please see the Artifacts section of https://github.com/transmission/transmission/actions/runs/4158021347 for test binaries

**Comment by ckerr** [comment]
testers needed, please see the potential fix at https://github.com/transmission/transmission/pull/4856 for links to binaries

**Comment by JulienSambre** [comment]
> a temporary solution: edit settings.json, enable `script-torrent-added-enabled`, add a new script
> 
> ```
> #!/bin/sh
> 
> sleep 1
> /usr/bin/transmission-remote -t $TR_TORRENT_ID -s
> ```

Hi! I probably did something wrong, because magnet torrent are still getting paused when metadata has been downloaded.

I added in the config file this : 
```
    "script-torrent-added-enabled": true,
    "script-torrent-added-filename": "/config/fix_paused.sh",
```

And put this in fix_paused.sh :
```
sleep 1
/usr/bin/transmission-remote -t $TR_TORRENT_ID -s
```

I'm using the linuxserver docker image. Do you know what am i missing?

**Comment by mad-tunes** [comment]
Really not up on the Linux script side of things, so I won't catch anything obvious on that front..
But if you've got a pwd set for transmission, the script might have to include
/usr/bin/transmission-remote --auth user:pass -t $TR_TORRENT_ID -s
(swap user and pass for your user and pass)
..like a few messages back

> > a temporary solution: edit settings.json, enable `script-torrent-added-enabled`, add a new script
> > ```
> > #!/bin/sh
> > 
> > sleep 1
> > /usr/bin/transmission-remote -t $TR_TORRENT_ID -s
> > ```
> 
> Hi! I probably did something wrong, because magnet torrent are still getting paused when metadata has been downloaded.
> 
> I added in the config file this :
> 
> ```
>     "script-torrent-added-enabled": true,
>     "script-torrent-added-filename": "/config/fix_paused.sh",
> ```
> 
> And put this in fix_paused.sh :
> 
> ```
> sleep 1
> /usr/bin/transmission-remote -t $TR_TORRENT_ID -s
> ```
> 
> I'm using the linuxserver docker image. Do you know what am i missing?
> 
> edit : found the mistake : i forgot to add #!/bin/sh at the beginning of the script file => work like a charm now ;).

Really not up on the Linux script side of things, so I won't catch anything obvious on that front..
But if you've got a pwd set for transmission, the script might have to include
/usr/bin/transmission-remote --auth user:pass -t $TR_TORRENT_ID -s
(swap user and pass for your user and pass)
..like a few messages back

**Comment by brandon-daniels** [comment]
Just confirming I have this issue as well. I'm using the linuxserver/transmission docker image. I look forward to the fix! Good work devs

**Comment by drizuid** [comment]
Just a note from us at Linuxserver.io, this upstream fix won't make it into our container until this is a "release" and/or picked up by alpine in their edge repo. That said, the work-around shown above could be made into a persistent docker mod until that time.
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers if someone would like to create a mod to perform the work-around and PR it, i think it'd help a lot of people.

**Comment by SNBogdanov** [comment]
I don't know how it should be in 4.0.1 but in transmission-4.0.0-dev+r9d1a141482-x64.msi from Feb 21, 2023 torrent from magnet link stopped to download info completelly. It behave same way as in v 3.0, went to queue to download info if I checked to start, or paused if not.

**Comment by Coeur** [comment]
@SNBogdanov yes, expected. We had the choice of either a regression for some users, going back to Transmission 3 behavior, or a "many lines change" to address it. We went with the Transmission 3 behavior. The many lines change is in a PR for Transmission 4.1:
#4874

**Comment by maxz** [comment]
> We had the choice of either a regression for some users, going back to Transmission 3 behavior, or a "many lines change" to address it. We went with the Transmission 3 behavior.

But that is not how Transmission 3.0 behaved. The magnet links there were active after adding them.

Hopefully this will be fixed for good in 4.1. I tried mitigating it by starting the torrents after adding them via the RPC interface, but this won't work if the info dict has not been retrieved yet and there is no callback or anything alike to help with determining the right time without polling the state repeatedly.

**Comment by Coeur** [comment]
@ckerr would you want to review https://github.com/transmission/transmission/pull/4874 for an inclusion in 4.0.1 or 4.0.2, to address those concerns?

**Comment by ckerr** [comment]
@Coeur I just tested `transmission-gtk` 3.00 and main, In both:

- Adding a magnet link + clicking "Start when added" adds a magnet, starts downloading metadata + data
- Adding a magnet link + **un**clicking "Start when added" adds a magnet in a paused state.

So it doesn't seem like there's any bug to address?

I also have [other concerns](https://github.com/transmission/transmission/pull/4874#issuecomment-1430272025) about 4874 that never got addressed and probably need consideration before merging, but that's probably more on-topic in the PR conversation than here

**Comment by maxz** [comment]
With the 4.1 release this issue is now fixed for me.
