### ISSUE TITLE
"invalid data" error message when creating new torrent

### ISSUE THREAD

**Issue by whywhyzee** [transmission/transmission#4741]
### What is the issue?

I have had no issues at all with Trans 3.0, but while I can download torrents fine with 4.0, every time I try to create a new torrent file and upload it, I get an error message about the torrent containing "invalid data."  I can't figure out why this is happening.  Any ideas?

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by whywhyzee** [comment]
Sorry for being vague.

I can create the torrent file using T 4.0, but when I upload it to a tracker, I get a message - from Transmission - that says the following:

"[Such and such] is not a valid torrent file.  The torrent file cannot be opened because it contains invalid data."

**Comment by ckerr** [comment]
Depending on what the tracker specializes in, please try creating a new torrent with public domain content, e.g. from archive.org, so that if you get the error message again you can share the torrent file with me to analyze.

**Comment by whywhyzee** [comment]
I really appreciate your help.  Apologies for not knowing how to attach the .torrent file for you --

**Comment by ckerr** [comment]
Yes, if it's a public domain torrent that your tracker has given the "invalid data" error message on, yes I'd like to see it.

If GitHub won't allow you to attach a `.torrent` file to this issue, maybe go to a site like https://base64.guru/converter/encode/file to convert the .torrent file into base64, then paste the plaintext base64 into this ticket.

**Comment by whywhyzee** [comment]
https://we.tl/t-8uArwPkDyD

**Comment by ckerr** [comment]
Why am I not surprised that someone with your username would be making music torrents :smile_cat: 

Huh, that looks like a valid .torrent file to me. ...maybe that tracker has a client whitelist and Transmission's not on it yet because it's new?

Try removing EXACTLY this section:

`10:created by31:Transmission/4.0.0 (280ace12f8)`

so that the post-edit text looks like

...`announce.phpee13:creation datei1675860717e8`...

and see what happens :man_shrugging: 

If this is the problem, then the answer is to wait for the tracker to whitelist Transmission 4. Otherwise we'll keep digging.

**Comment by whywhyzee** [comment]
Yep - remarkably, that was the rub!

Thank you so much for your help.

And I am glad you appreciate classic/prog rock!

Cheers

**Comment by ckerr** [comment]
Also @whywhyzee you might ask in their forums for them to whitelist 4.0.0 :smile_cat:

**Comment by ckerr** [comment]
To be clear, I don't recommend doing little workarounds like this to get pass a tracker whitelist -- I only suggested that change to diagnose whether the problem was a Transmission bug or not.

**Comment by whywhyzee** [comment]
Understood and thanks!

    On Wednesday, February 8, 2023 at 06:25:08 PM EST, Charles Kerr ***@***.***> wrote:  
 
 


To be clear, I don't recommend doing little workarounds like this to get pass a tracker whitelist -- I only suggested that change to diagnose whether the problem was a Transmission bug or not.
