### ISSUE TITLE
Transmission: "when close window minimize to tray" option dissapeared

### ISSUE THREAD

**Issue by legluondunet** [transmission/transmission#4749]
### What is the issue?

Hello, I installed transmission official ARCH package and I can not find "when close window minimize to tray" option.
Is it a known bug?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1)

**Comment by mikedld** [comment]
If Arch package is built against GTK 4, everything works as expected because there're currently no systray implementations that support GTK 4. If you know of one we can use, please let us know.

If it's build against GTK 3, this is not expected and needs to be looked into.

**Comment by legluondunet** [comment]
I'm using XFCE 4.18.

**Comment by legluondunet** [comment]
I will compile latest git myself to verify.

**Comment by ckerr** [comment]
You should be able to check the version with

```sh
$ ldd `which transmission-gtk` | grep gtk
```

**Comment by legluondunet** [comment]
ldd `which transmission-gtk` | grep gtk
	libgtkmm-4.0.so.0 => /usr/lib/libgtkmm-4.0.so.0 (0x00007fbb8fa00000)
	libgtk-4.so.1 => /usr/lib/libgtk-4.so.1 (0x00007fbb8f200000)

**Comment by ckerr** [comment]
Ok, thanks!

> If Arch package is built against GTK 4, everything works as expected because there're currently no systray implementations that support GTK 4. If you know of one we can use, please let us know.

**Comment by legluondunet** [comment]
Thanks to you. But I can still recompile it with GTK3?

**Comment by msangel** [comment]
xfce is affected with exactly the same

**Comment by msangel** [comment]
I don't want to recompile, where I can get right binary?

This is my system (sorry not terminal output, I am not compiling things so command line not needed)
![image](https://github.com/user-attachments/assets/d1ea960a-c2c4-45cd-86da-74b62829f6af)

**Comment by msangel** [comment]
temporary switched to transmission-qt but that looks ugly as not supported nice dark theme with awesome icons on xfce  so I will wait for fix here

**Comment by tmst** [comment]
No "min to tray" option using Xfce 4.20 with GTK 3.24.50.
