### ISSUE TITLE
consider removing the -Werror build flag from libutp

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#4752]
### What is the issue?

Inspired by https://github.com/transmission/transmission/issues/4748

It looks like that option is added by Transmission, but does it ever make sense for Transmission to build a third-party package with -Werror? Those are upstream warnings so maybe we shouldn't fail on them.

CC @mikedld who may have more insight into this one than I do

### Which application of Transmission?

None

**Comment by mikedld** [comment]
Same comment as I made about libb64 before: https://github.com/transmission/transmission/pull/4129#issuecomment-1309339232

IMHO the flag and the option to enable/disable it should stay, but the way we're using the bundled libraries should change.
