### ISSUE TITLE
Consider improving option description for ENABLE_WEB

### ISSUE THREAD

**Issue by jpalus** [transmission/transmission#4755]
### What is the issue?

Looking at `CMakeLists.txt`:
https://github.com/transmission/transmission/blob/6576a2a1db0a1c0fa5255b7fa37b6c97dead1974/CMakeLists.txt#L46-L49

You can see options for toggling GTK/QT/WEB clients. It may appear for all of them that they either disable or enable functionality completely which is not the case for `ENABLE_WEB`. What it really appears to mean is something along `regenerate web artifacts with npm (uses network)`. It's somewhat confusing as even with `-DENABLE_WEB=OFF` web client is installed, just with artifacts shipped with git/release tarball. It would be really good if option name and description could better reflect that.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment]
Yep, this is a leftover from #4658, which has a decent writeup of why transmission-web is built the way it is.

To be clear in case other builders / packagers are reading this -- this isn't a bug in the 4.0.0 cmake with transmission-web, things will still build right.

But @jpalus is right it _is_ very confusing and the terminology should be something like he described above.
