### ISSUE TITLE
Manually reordered transfer list isn't saved after quitting Transmission

### ISSUE THREAD

**Issue by NZ-Vincent** [transmission/transmission#4766]
### What is the issue?

Hi,
After updating to Transmission 4.0.0 (280ace12f8) yesterday, I've realised that my manually reordered list of transfers isn't maintained after I quit Transmission. When I reopen Transmission, I have to manually reorder my list... to no avail, as it goes back to the chronological order after each time I quit the app.

OS : MacOS High Sierra (10.13.6)

I hope that you guys can fix this.
Thanks a lot for your great work!
Vincent

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by naos** [comment]
I have the same issue. Manually ordered queue is not saved when quitting application. In previous 3.x versions it was saved.

version: 4.0.0
OS: macOS Catalina 10.5.7

**Comment by NZ-Vincent** [comment]
Indeed, it looks like the same issue. Sorry for the double post.

**Comment by ckerr** [comment]
No worries!
