### ISSUE TITLE
transmission-daemon: duplicate settings in settings.json

### ISSUE THREAD

**Issue by chantalcoolsma** [transmission/transmission#477]
I have installed transmission-daemon on Fedora Workstation 27 x86. I started it as a service and stopped it. Now I change this lines in settings.json to:

"rpc-whitelist": "*.*.*.*",
"rpc-whitelist-enabled": false,

I start the service again, my changes do not work. When I stop the service and edit settings.json, it looks like:

"rpc-whitelist": "*.*.*.*",
"rpc-whitelist": "127.0.0.1",
"rpc-whitelist-enabled": false,
"rpc-whitelist-enabled": true,

Line 2 and 4 are added. Result, I can only login to the Transmission web client from my Fedora machine and not from any other computer.

Those duplicates appear for all settings starting with "rpc-". Any clues?

**Comment by mikedld** [comment]
See #473.
