### ISSUE TITLE
suggestion: option to seed a torrent only if it's unseeded

### ISSUE THREAD

**Issue by schurlix** [transmission/transmission#4770]
### What is the issue?

Hello, I am using transmission-cli on a very well connected machine and controlling it with the web UI. A perfect setup!

I hereby propose (and wish) a seeding mode that is not controlled by "Ratio" (which is a good thing), but rather by
the availability of a torrent elsewhere. I would like to seed some rare torrents practically forever, but *only if* no other seed is available, making my transmission instance a life saver.

Thank you everybody for this amazing piece of software!

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00

**Comment by ckerr** [comment]
I think I'm going to decline this feature. It has some practical issues we discussed above, but also I'm not sure what problem it really solves and am not sure how many people would use this feature.

If someone really wants this, it would probably be possible to write some script to periodically use `transmission-remote --json` to query which torrents have leechers or not, and then start / stop torrents accordingly.
