### ISSUE TITLE
transmission-create 4.0.0 adds private- and source flag outside of info key

### ISSUE THREAD

**Issue by mahkitah** [transmission/transmission#4771]
When you use transmission-create 4.0.0 with -p and -r option, the 'private' and 'source' keys are added to the main branch of the torrent, not as a child of the info key.

Transmission recognises the private flag outside of 'info' but other clients do not (at least qbittorrent doesn't)
The source outside of 'info' completely defies its purpose, namely to make the infohash unique to the tracker.

(This was found on Windows transmission-create.exe)

**Comment by ckerr** [comment]
Hmm, looks like libtorrent used to do the same thing long ago but no longer does. https://github.com/arvidn/libtorrent/commit/cc5dc24ca1275710fe355ba199a08b697d2a95b5

**Comment by ckerr** [comment]
https://www.bittorrent.org/beps/bep_0027.html

> When generating a metainfo file, users denote a torrent as private by including the key-value pair "private=1" in the "info" dict of the torrent's metainfo file [[1]](https://www.bittorrent.org/beps/bep_0027.html#bep-3).
