### ISSUE TITLE
configuration loading broken

### ISSUE THREAD

**Issue by BrainSlayer** [transmission/transmission#4772]
https://github.com/transmission/transmission/blob/b85f85d3f9c45821edef48699c5055d2c7cc73f9/libtransmission/session.cc#L503

this is broken. tr_sys_path_exists returns 1 on success and not 0. so the check fails and config cannot be loaded

root@raid:/mnt/raid# transmissiond -f --config-dir "/mnt/raid/"
[2023-02-09 14:14:31.407] ERR transmission-daemon Error loading config file -- exiting. (/home/seg/DEV/x86_64/src/router/transmission/daemon/daemon.cc:908)

**Comment by ckerr** [comment]
Hey @BrainSlayer I don't see why line 503 is broken? It's checking to see if the file exists before loading it on 507.

Basically that if ... else ... else block is saying "if there's already a settings file use it. Set success to false only if there was a settings file and we couldn't parse it."

**Comment by BrainSlayer** [comment]
the returncode is wrong used. the function returns 1 if success. but the check is for 0 to return success in th callers function.
if you change it to if (tr_sys_path_exists(filename)) all is working as expected (i tested it)

i call transmissiond as shown. and the settings file is present in that folder as it should be, since its preconfigured. in transmission 3.00 this was working. but in 4.00 it returns an error since this check fails.  but maybe also the following else case is failing for a unknown reason. the file is a standard settings.json which i also used in 3.00

**Comment by BrainSlayer** [comment]
i found the cause. it was a syntax change in settings.json for a integer parameter which is now a string (umask). it seems to belong to all octal based values
before  "umask": 022 was accepted but now it must be  "umask": "022"

**Comment by BrainSlayer** [comment]
personally i think it would be good if transmissions shows config parser error in debugging output. unfortunatly there is no useable error output
