### ISSUE TITLE
4.0 Hangs on Open (mac)

### ISSUE THREAD

**Issue by sararielle** [transmission/transmission#4773]
### What is the issue?

I attempted to update from 3.0.0 to 4.0.0 and the app broke.  Specifically, it hangs as it's opening.  (The app bounces in the dock but doesn't settle, its CPU usage spikes, and the system reports it as "not responding".)  I'm running macos 13.1.

(I have temporarily resolved the issue by downgrading to 3.0.0 but I would like to be able to upgrade to a stable, functional 4.0.0 at some point.)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by allanjackson** [comment]
Mine is doing something similar, but if I just let it bounce in the Dock for about a minute, it finally starts up.

**Comment by sararielle** [comment]
Does it still do it every time? Or is it just an issue the first time?

**Comment by sararielle** [comment]
(I have now given it several minutes. It's stopped bouncing but it's still "not responding" and hasn't properly opened yet.)

**Comment by allanjackson** [comment]
It's every time I start up. I'll get a spinning beachball for at least part of the time, and it'll show up as "not responding" in Activity Monitor. But it has always appeared eventually for me in a bit under a minute.

Details in case they matter:
I'm on an M2 macbook air. 
I have about 15 seeding torrents where the files are stored on a network drive (but it acts the same even if they're all paused).

**Comment by allanjackson** [comment]
And now I restarted my computer for the first time since installing, and it opens instantly...

**Comment by sararielle** [comment]
oh huh.  I'm on an intel. (2019 i9)  Are they *sure* this still runs on the intel macs?  It *says* it's universal but I'm getting suspicious.

**Comment by GaryElshaw** [comment]
> Are they _sure_ this still runs on the intel macs?

Yep!

**Comment by sararielle** [comment]
Ok, well has anyone else had a similar issue on an intel mac? bc even waiting 5 mins leaves it still hung.

**Comment by GaryElshaw** [comment]
@sararielle Is the binary you're using built by yourself or downloaded? As mentioned above, have you restarted?

**Comment by sararielle** [comment]
I haven't had a chance to restart yet.  I first tried with the auto-update and then when it failed I downloaded the binary from the website.  I'll reboot and try fresh tomorrow. Thanks

**Comment by sararielle** [comment]
I have now rebooted and the issue persists.

**Comment by GaryElshaw** [comment]
I think the best move, next, would be to backup up your /Users/YourName/Library/Application Support/Transmission/ directory, and then move it to the desktop. When you relaunch Transmission, it will recreate all of those parameters in there anew.

**Comment by sararielle** [comment]
that seems to have fixed it.  I can't imagine what was causing the issue but it's now opening cleanly so it seems to be resolved. Thank you for all your help.

**Comment by barracuda156** [comment]
I have 4.0.5 totally broken on Catalina now: it freezes itself and kills Finder apps if they try to open a disk which Transmission uses.

**Comment by GaryElshaw** [comment]
Do you have a crash log, @barracuda156?
