### ISSUE TITLE
Automatically size window to fit all transfers hides behind Dock

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#4779]
### What is the issue?

"Automatically size window to fit all transfers" doesn't respect the Dock when it's on the bottom of the screen, so the window goes behind it and you can't see the bottom torrent.

Copied this report from: https://forums.macrumors.com/threads/bittorrent-client-transmission-gains-apple-silicon-support-in-fourth-major-release.2380179/post-31952470

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by asmeurer** [comment]
When the Dock is set to hidden by default, the window resizes to just above where the dock would be, instead of the bottom of the screen. Presumably the logic is just inverted somehow.

**Comment by Artoria2e5** [comment]
https://github.com/transmission/transmission/blob/e10689beeabbf70b54cd0c2df8b4f0008fe05fe2/macosx/Controller.mm#L5286-L5294

```objective-c++
    //make sure we don't go bigger than the screen height
    NSScreen* screen = self.fWindow.screen;
    if (screen)
    {
        NSSize maxSize = screen.frame.size;
        maxSize.height -= self.toolbarHeight;
        maxSize.height -= self.mainWindowComponentHeight;
```

Change `frame` into `visibleframe` here to fix it.
