### ISSUE TITLE
Qt client tracker port shows :80 for HTTPS

### ISSUE THREAD

**Issue by BowlesCR** [transmission/transmission#4782]
Qt client > Torrent Properties > Trackers shows :80 for HTTPS trackers without an explicit port.

It would appear that QUrl.port() is not smart enough to imply 80/443 appropriately based on the scheme.
https://github.com/transmission/transmission/blob/44546674d955c9b2982ec3c2b18d547142b0c9e4/qt/TrackerDelegate.cc#L195

**Comment by ckerr** [comment]
Thanks for finding this!
