### ISSUE TITLE
4.0b3 updater does not see 4.0 release

### ISSUE THREAD

**Issue by CyberSkull** [transmission/transmission#4790]
### What is the issue?

Like in bug #4614, Transmission 4.0b3 does not see there is a new stable release when the "Include beta releases" checkbox is disabled.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0-beta.3 (634b1e8fc1), macOS 13.2, M2

**Comment by CyberSkull** [comment]
<img width="372" alt="Screenshot 2023-02-10 at 1 11 58 AM" src="https://user-images.githubusercontent.com/201815/218051235-529e55c7-558f-47e9-ace8-9c333a9f635b.png">

**Comment by ckerr** [comment]
I'm not sure what can be done for the 4.0.0 betas at this point, since we're not going to release another beta :smile_cat: but we should fix this for next time.

@nevack or @Coeur could you PTAL?

**Comment by arcticfoxwp** [comment]
@ckerr Agree strongly on this issue. The checkbox is to "include" beta releases, not be exlcusive to them.

**Comment by Coeur** [comment]
Whatever you expect regarding this checkbox, it has strictly no effect at the moment since it's implementation is missing.

https://github.com/transmission/transmission/blob/065facc07c72ddb7a096cb97b6680d3f13891ddb/macosx/PrefsController.mm#L411-L414

**Comment by arcticfoxwp** [comment]
So you have peope who wanted to test betas that missed them, and now people who tested the beta waiting for the full release who aren't getting it.

**Comment by ckerr** [comment]
Awesome

**Comment by ckerr** [comment]
Well that is just frustrating beyond words.

Let's put out a call for more macOS devs in the 4.0.1 release notes.

**Comment by ckerr** [comment]
Well that is just frustrating beyond words.

@livings124 @mikedld can we do something about this?

**Comment by livings124** [comment]
`- (void) setAutoUpdateToBeta: (id) sender
{
#ifndef NO_SPARKLE
    [[SUUpdater sharedUpdater] setAllowedTags: SPARKLE_TAG ? [NSSet setWithObject: @"beta"] : nil];
#endif
}`

This is from an old version of the app. Was this lost when this was made an `.mm` file?

**Comment by livings124** [comment]
https://github.com/transmission/transmission/commit/1b36e34d9bcfd8ea28f2c6ff4085a294e4cf0f71

**Comment by livings124** [comment]
Sounds like this change was made because of issues from updating from the old version. I think we can revert this change now that 4.0 is out for going forward.

**Comment by mikedld** [comment]
IIRC that change was made because there was a change in Sparkle API and the old way just wasn't working.

**Comment by ckerr** [comment]
I don't have enough context to understand this discussion, and probably just need it spelled out more plainly ... what should be done about this bug, and can we add something to ensure this doesn't regress in the future?

It's pretty terrible that beta users won't see 4.0.0.

**Comment by Coeur** [comment]
My _guess_ is that "4.0.0-dev" is understood as alphanumerically later than "4.0.0".
If that guess is correct, then simply delivering a "4.0.1" or a "4.0.0-dev2" will be enough for visibility.

**Comment by arcticfoxwp** [comment]
Was this deemed not important enough for 4.0.1? If 4.0.1 has some of the Mac specific problems fixed, maybe this should be more of a priority?

**Comment by ckerr** [comment]
@arcticfoxwpg if you're wanting to set milestones please submit a PR to fix this

**Comment by ckerr** [comment]
@arcticfoxwpg I'd be happy to set a 4.0.1 milestone for this if you have a PR ready to go in before the 4.0.1 deadline

**Comment by ckerr** [comment]
_sigh_

On the one hand yes I would like to see this working and I'm a little frustrated that @livings124 and @mikedld didn't give a clearer answer upthread when I asked what we should be doing about this. I've been fixing issues in the core library and am not a subject expert on how the macOS updates work. So I really would like more clarity on that and I'm sympathetic to what you're saying.

On the other hand, unless you have a PR that's ready to go in time for `4.0.1`, please don't be telling the maintainers what milestones to set. It's really easy to tell maintainers what to work on but harder to actually get it done.

**Comment by arcticfoxwp** [comment]
I hear you. To me it seems like a pretty major issue.

However, I wasn't telling anyone anything. Both my sentences ended in question marks. 450+ open issues, so bumping up some stuff that is completely broken to make sure it doesn't get forgotten about.

**Comment by mikedld** [comment]
I don't think this is a critical issue right now, but it needs to be fixed before we decide to do the next beta. We can't retroactively fix it in 4.0.0 beta releases, so those won't work the way people want. 4.0.1 isn't a beta release so update from 4.0.0 (or 3.00) will work just fine.

Guessing what the actual issue is is not helpful. I'd rather someone go ahead and debug it, and Mac contributors seem capable enough to do this, or so I thought. I can certainly do it myself but where's the fun in that (while we still have time)? :)

**Comment by livings124** [comment]
This is something I will look into fixing in the next week or so, but I can't guarantee it will make it by 4.0.1. But since there likely won't be new beta releases for at least a point release or two, that shouldn't be a huge concern.

**Comment by ckerr** [comment]
related: https://github.com/transmission/transmission/issues/4614

**Comment by livings124** [comment]
If I'm understanding this correctly, there are two issues.

1. The beta checkbox isn't hooked up to anything.
2. The app thinks 4.0 beta 3 is newer than the stable 4.0 release. For this one, do we know if the 4.0 beta 3 suggests updating to 4.0.1 now that that's out?

Am I understanding correctly?

**Comment by Coeur** [comment]
Yes, those are the two issues.
