### ISSUE TITLE
Downgrade from 4.0.0 to 3.0.0 broken

### ISSUE THREAD

**Issue by wumpyr** [transmission/transmission#4798]
### What is the issue?

Upgraded to 4.0.0.  Very much regretting that.  Forced to downgrade on gentoo back to 3.0.0-r5.

Restarted the 3.0.0 daemon (which has been working rock solid for a long time thank you!) and now get:

assertion failed: excess_bit_count >= 0 (/nas/tmp/portage/net-p2p/transmission-3.00-r5/work/transmission-3.00/libtransmission/bitfield.c:378)
Aborted

Upgrade again to 4.0.0 and daemon starts (but is not usable).  How to fix 3.0.0 to get back to sanity?

### Which application of Transmission?

None

### Which version of Transmission?

3.0.0 <-> 4.0.0

**Comment by ckerr** [comment]
> Upgraded to 4.0.0. Very much regretting that. 

Thank you for your descriptive and informative feedback.

> How to fix 3.0.0 to get back to sanity?

Maybe compile in release mode so that assertions are disabled?
