### ISSUE TITLE
Not responding.

### ISSUE THREAD

**Issue by Quantumzzz** [transmission/transmission#480]
After starting a torrent download the client goes not responding. I am using the raspberry pi 3. Usually it would come back to life after 5-10 min, but now that i am downloading a much larger torrent it has been offline for around an hour now. Here is the syslog:

```
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013845] INFO: task transmission-da:536 blocked for more than 120 seconds.
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013857]       Not tainted 4.9.59-v7+ #1047
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013861] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013867] transmission-da D    0   536      1 0x00000000
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013910] [<80715658>] (__schedule) from [<80715b7c>] (schedule+0x50/0xa8)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013927] [<80715b7c>] (schedule) from [<80718dd0>] (schedule_timeout+0x204/0x40c)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013942] [<80718dd0>] (schedule_timeout) from [<807152f8>] (io_schedule_timeout+0xc0/0x138)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013959] [<807152f8>] (io_schedule_timeout) from [<80716488>] (bit_wait_io+0x20/0x6c)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013976] [<80716488>] (bit_wait_io) from [<807160b0>] (__wait_on_bit+0x94/0xd0)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.013993] [<807160b0>] (__wait_on_bit) from [<8020b400>] (wait_on_page_bit+0x98/0xa0)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014010] [<8020b400>] (wait_on_page_bit) from [<8020b4e0>] (__filemap_fdatawait_range+0xd8/0x120)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014025] [<8020b4e0>] (__filemap_fdatawait_range) from [<8020b550>] (filemap_fdatawait_range+0x28/0x44)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014039] [<8020b550>] (filemap_fdatawait_range) from [<8020b5d0>] (filemap_fdatawait+0x64/0x70)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014055] [<8020b5d0>] (filemap_fdatawait) from [<8020d758>] (filemap_write_and_wait+0x5c/0x84)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014204] [<8020d758>] (filemap_write_and_wait) from [<7f41cee4>] (cifs_setattr+0x268/0x5e0 [cifs])
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014342] [<7f41cee4>] (cifs_setattr [cifs]) from [<8028f06c>] (notify_change+0x1cc/0x408)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014360] [<8028f06c>] (notify_change) from [<8026e204>] (do_truncate+0x90/0xc0)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014374] [<8026e204>] (do_truncate) from [<8026e660>] (do_sys_ftruncate+0x128/0x1bc)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014387] [<8026e660>] (do_sys_ftruncate) from [<8026e78c>] (SyS_ftruncate64+0x24/0x2c)
Jan 23 05:46:23 raspberrypi kernel: [ 1964.014403] [<8026e78c>] (SyS_ftruncate64) from [<801080c0>] (ret_fast_syscall+0x0/0x1c)
```

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

It looks like you're storing the files on CIFS which probably doesn't support sparse preallocation. If you want to continue using CIFS as your storage, try changing ["preallocation" in settings.json](/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations) to 0.

**Comment by mtausk** [comment]
Similiar issue here.

    May 17 18:48:11 kernel: [ 6141.921740] INFO: task kworker/u8:0:5 blocked for more than 120 seconds.
    May 17 18:48:11 kernel: [ 6141.921764]       Tainted: G         C      4.14.17-v7+ #1090
    May 17 18:48:11 kernel: [ 6141.921774] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
    May 17 18:48:11 kernel: [ 6141.921785] kworker/u8:0    D    0     5      2 0x00000000
    May 17 18:48:11 kernel: [ 6141.921812] Workqueue: writeback wb_workfn (flush-8:1-fuseblk)
    May 17 18:48:11 kernel: [ 6141.921849] [<807762c0>] (__schedule) from [<80776938>] (schedule+0x50/0xa8)
    May 17 18:48:11 kernel: [ 6141.921868] [<80776938>] (schedule) from [<8014ac8c>] (io_schedule+0x20/0x40)
    May 17 18:48:11 kernel: [ 6141.921887] [<8014ac8c>] (io_schedule) from [<8021c4e4>] (__lock_page+0x100/0x128)
    May 17 18:48:11 kernel: [ 6141.921906] [<8021c4e4>] (__lock_page) from [<8022bb78>] (write_cache_pages+0x30c/0x4d4)
    May 17 18:48:11 kernel: [ 6141.921985] [<8022bb78>] (write_cache_pages) from [<7f4ba618>] (fuse_writepages+0x80/0xe4 [fuse])
    May 17 18:48:11 kernel: [ 6141.922075] [<7f4ba618>] (fuse_writepages [fuse]) from [<8022e284>] (do_writepages+0x30/0x8c)
    May 17 18:48:11 kernel: [ 6141.922094] [<8022e284>] (do_writepages) from [<802ba854>] (__writeback_single_inode+0x44/0x430)
    May 17 18:48:11 kernel: [ 6141.922111] [<802ba854>] (__writeback_single_inode) from [<802bb148>] (writeback_sb_inodes+0x20c/0x4c4)
    May 17 18:48:11 kernel: [ 6141.922126] [<802bb148>] (writeback_sb_inodes) from [<802bb490>] (__writeback_inodes_wb+0x90/0xd0)
    May 17 18:48:11 kernel: [ 6141.922141] [<802bb490>] (__writeback_inodes_wb) from [<802bb714>] (wb_writeback+0x244/0x358)
    May 17 18:48:11 kernel: [ 6141.922155] [<802bb714>] (wb_writeback) from [<802bc2ac>] (wb_workfn+0x36c/0x4d8)
    May 17 18:48:11 kernel: [ 6141.922173] [<802bc2ac>] (wb_workfn) from [<801370d8>] (process_one_work+0x158/0x454)
    May 17 18:48:11 kernel: [ 6141.922192] [<801370d8>] (process_one_work) from [<80137438>] (worker_thread+0x64/0x5b8)
    May 17 18:48:11 kernel: [ 6141.922209] [<80137438>] (worker_thread) from [<8013d4a8>] (kthread+0x13c/0x16c)
    May 17 18:48:11 kernel: [ 6141.922226] [<8013d4a8>] (kthread) from [<8010812c>] (ret_from_fork+0x14/0x28)
    May 17 18:48:11 kernel: [ 6141.922313] INFO: task atop:671 blocked for more than 120 seconds.
    May 17 18:48:11 kernel: [ 6141.922326]       Tainted: G         C      4.14.17-v7+ #1090
    May 17 18:48:11 kernel: [ 6141.922335] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
    May 17 18:48:11 kernel: [ 6141.922344] atop            D    0   671      1 0x00000000
    May 17 18:48:11 kernel: [ 6141.922371] [<807762c0>] (__schedule) from [<80776938>] (schedule+0x50/0xa8)
    May 17 18:48:11 kernel: [ 6141.922389] [<80776938>] (schedule) from [<80779a38>] (rwsem_down_read_failed+0x10c/0x15c)
    May 17 18:48:11 kernel: [ 6141.922404] [<80779a38>] (rwsem_down_read_failed) from [<807790cc>] (down_read+0x5c/0x60)
    May 17 18:48:11 rsyslogd-2007: action 'action 10' suspended, next retry is Thu May 17 18:49:41 2018 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
    May 17 18:48:11 kernel: [ 6141.922421] [<807790cc>] (down_read) from [<802f8468>] (proc_pid_cmdline_read+0xd4/0x4fc)
    May 17 18:48:11 kernel: [ 6141.922441] [<802f8468>] (proc_pid_cmdline_read) from [<80289d74>] (__vfs_read+0x38/0x130)
    May 17 18:48:11 kernel: [ 6141.922458] [<80289d74>] (__vfs_read) from [<80289f08>] (vfs_read+0x9c/0x168)
    May 17 18:48:11 kernel: [ 6141.922473] [<80289f08>] (vfs_read) from [<8028a4b8>] (SyS_read+0x54/0xb0)
    May 17 18:48:11 kernel: [ 6141.922489] [<8028a4b8>] (SyS_read) from [<80108080>] (ret_fast_syscall+0x0/0x28)
    May 17 18:48:11 kernel: [ 6141.922655] INFO: task tmux:5348 blocked for more than 120 seconds.
    May 17 18:48:11 kernel: [ 6141.922667]       Tainted: G         C      4.14.17-v7+ #1090
    May 17 18:48:11 kernel: [ 6141.922676] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
    May 17 18:48:11 kernel: [ 6141.922685] tmux            D    0  5348      1 0x00000000
    May 17 18:48:11 kernel: [ 6141.922711] [<807762c0>] (__schedule) from [<80776938>] (schedule+0x50/0xa8)
    May 17 18:48:11 kernel: [ 6141.922727] [<80776938>] (schedule) from [<80779a38>] (rwsem_down_read_failed+0x10c/0x15c)
    May 17 18:48:11 kernel: [ 6141.922741] [<80779a38>] (rwsem_down_read_failed) from [<807790cc>] (down_read+0x5c/0x60)
    May 17 18:48:11 kernel: [ 6141.922758] [<807790cc>] (down_read) from [<802f8468>] (proc_pid_cmdline_read+0xd4/0x4fc)
    May 17 18:48:11 kernel: [ 6141.922775] [<802f8468>] (proc_pid_cmdline_read) from [<80289d74>] (__vfs_read+0x38/0x130)
    May 17 18:48:11 kernel: [ 6141.922790] [<80289d74>] (__vfs_read) from [<80289f08>] (vfs_read+0x9c/0x168)
    May 17 18:48:11 kernel: [ 6141.922805] [<80289f08>] (vfs_read) from [<8028a4b8>] (SyS_read+0x54/0xb0)
    May 17 18:48:11 kernel: [ 6141.922820] [<8028a4b8>] (SyS_read) from [<80108080>] (ret_fast_syscall+0x0/0x28)
    May 17 18:48:11 kernel: [ 6141.922835] INFO: task rtorrent main:6557 blocked for more than 120 seconds.
    May 17 18:48:11 kernel: [ 6141.922846]       Tainted: G         C      4.14.17-v7+ #1090
    May 17 18:48:11 kernel: [ 6141.922855] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.

**Comment by mtausk** [comment]
Started happening few months ago, not sure which RPI kernel upgrade brought this...
 uname -a
Linux pi 4.14.17-v7+ #1090 SMP Mon Feb 5 21:02:18 GMT 2018 armv7l armv7l armv7l GNU/Linux

Ubuntu 16.04
