### ISSUE TITLE
Please restore the old Dock icon bandwith colours

### ISSUE THREAD

**Issue by juman234** [transmission/transmission#4800]
### What is the issue?

Especially the new upload speed background colour is too light. It makes the speed difficult to read.

Please restore the old colours or choose colours with better contrast. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ddbrierton** [comment]
Agreed. Upload speed in particular is almost impossible to read.

**Comment by ckerr** [comment]
Pinging the usual macOS volunteers for feedback on this idea @Coeur @nevack @sweetppro @GaryElshaw

**Comment by jlhopes** [comment]
I just upgraded to 4.0.0 and agree wholeheartedly with this suggestion. The old dark green and dark blue were much nicer and easier to read. Otherwise, a big thank you for all the work you've done!

**Comment by GaryElshaw** [comment]
@ckerr Happy to take a look!

**Comment by Coeur** [comment]
By curiosity: are you on Dark or Light system colors?

**Comment by jlhopes** [comment]
> By curiosity: are you on Dark or Light system colors?

I am on Light mode

**Comment by Coeur** [comment]
Colors were changed by @livings124 with #1651. So reverting that PR from two years ago might be what you're after.

**Comment by GaryElshaw** [comment]
PR coming shortly...

**Comment by livings124** [comment]
I'm OK changing the color, but would like to keep the new simple styling.

**Comment by sweetppro** [comment]
does someone have any before after screens

**Comment by ckerr** [comment]
Was the color change part of some larger change that we need to think about here -- e.g. are there other places that colors need to be reverted at the same time?

**Comment by GaryElshaw** [comment]
> does someone have any before after screens

I'll make some shortly.

**Comment by ckerr** [comment]
> does someone have any before after screens

https://github.com/transmission/transmission/pull/4813/files/a4bc2e6b74d3b289fb38997860bc82bfb5e773d6..e00fc6e405a9ad70a218e614afc331b5d78508a1 shows the before and after between 4.0.0 and this PR, I think

**Comment by GaryElshaw** [comment]
> are there other places that colors need to be reverted at the same time?

I don't think so. I saw the criticism of the whiteness of the text and icons of the web interface and agree with the comment that was made, it currently excels accessibility-wise and should remain as is unless something between those two values is pr-ed. Come to think of it, just turning down the monitor brightness would probably be just as effective :-)

**Comment by sweetppro** [comment]
how about we just use the apple system colors:
https://developer.apple.com/design/human-interface-guidelines/foundations/color:
<img width="537" alt="green" src="https://user-images.githubusercontent.com/7323792/218233138-e62fea3b-dc9d-4378-8585-5336fd9e384b.png">
<img width="537" alt="blue" src="https://user-images.githubusercontent.com/7323792/218233143-bdf6bb1b-7194-4344-830d-940586432d62.png">

the contrast looks fine in those, in my opinion

**Comment by sweetppro** [comment]
oops... I posted iOS colors.
heres macOS, Green is slightly different:
<img width="571" alt="green" src="https://user-images.githubusercontent.com/7323792/218233350-3f621d2f-da68-44c5-b6e2-2bfe30f8c461.png">
<img width="571" alt="blue" src="https://user-images.githubusercontent.com/7323792/218233360-8b22b143-d419-4980-bd5a-d87537dbef1b.png">

**Comment by ckerr** [comment]
> I saw the criticism of the whiteness of the text and icons of the web interface and agree with the comment that was made, it currently excels accessibility-wise and should remain as is unless something between those two values is pr-ed. Come to think of it, just turning down the monitor brightness would probably be just as effective :-)

Please move this comment to that issue :smile_cat:

**Comment by ckerr** [comment]
> oops... I posted iOS colors. heres macOS, Green is slightly different:

FWIW, this is why I trust other people to do UI review. These look so close to each other that I would never notice the difference in practice. :see_no_evil:

**Comment by GaryElshaw** [comment]
> how about we just use the apple system colors: https://developer.apple.com/design/human-interface-guidelines/foundations/color: {Light Mode color is shown first, then Dark mode) 

I think that would put us almost exactly where we currently are. Never underestimate folks liking what they like.

**Comment by Coeur** [comment]
> does someone have any before after screens

If you mean the change from 2 years ago (Transmission 3 versus Transmission 4), it's in the PR that I linked, just scroll down:
https://github.com/transmission/transmission/pull/1651/files

**Comment by sweetppro** [comment]
The current green is much lighter, blue is basically the same.
Current colors are top, system (Light) colors are bottom.
![Untitled](https://user-images.githubusercontent.com/7323792/218234148-855fd4af-dcd5-4efe-a193-63a8ef13e506.png)

**Comment by GaryElshaw** [comment]
The white on green of the system, i think, is still lacking in contrast but better!

**Comment by GaryElshaw** [comment]
Current

![SCR-20221031-nt8](https://user-images.githubusercontent.com/69029666/198929162-3e46ff0b-85f4-4c78-a439-f1df2d65c6f2.png)

PR

![SCR-20230211-kxg](https://user-images.githubusercontent.com/69029666/218233408-20692589-8a61-42d3-9aa2-aebfab94344a.png)

**Comment by sweetppro** [comment]
how about the Accessible macOS system colors, they have much more contrast:
<img width="571" alt="Screenshot 2023-02-11 at 1 29 25 pm" src="https://user-images.githubusercontent.com/7323792/218234432-6897e71d-8faa-4805-b1ab-3af2e0e67733.png">
<img width="571" alt="Screenshot 2023-02-11 at 1 29 18 pm" src="https://user-images.githubusercontent.com/7323792/218234437-3100c078-dfe8-41be-8028-729023dd2f74.png">

**Comment by GaryElshaw** [comment]
@coeur > Or we could have different colors in Dark mode and Light mode eventually.

Yep, i think that would be great.

**Comment by GaryElshaw** [comment]
@sweetppro That looks much better!

**Comment by sweetppro** [comment]
like this:
![Untitled](https://user-images.githubusercontent.com/7323792/218234500-cc70c682-49a2-458e-ad9f-571d213f934b.png)

**Comment by sweetppro** [comment]
could you try these out @GaryElshaw 

![blue](https://user-images.githubusercontent.com/7323792/218234645-df991c91-1a0c-4b0d-98e6-c4b42937cb0f.png)
![green](https://user-images.githubusercontent.com/7323792/218234650-fe0382a4-ac92-4f87-92ed-afe9f40de9a9.png)
![blue_sm](https://user-images.githubusercontent.com/7323792/218234653-b93061d9-17fa-457b-8bce-aa4da7bec0b7.png)
![green_sm](https://user-images.githubusercontent.com/7323792/218234654-b990e074-51e1-4adb-8bce-79bae31e53f5.png)

**Comment by sweetppro** [comment]
Heres some dark ones also for consistency:
RGB: 28, 28,30
![gray_sm](https://user-images.githubusercontent.com/7323792/218235044-6723c792-9090-42f8-ba61-efd0ddb9e620.png)
![gray](https://user-images.githubusercontent.com/7323792/218235047-d245fd19-952e-4941-bf99-ab687aca3419.png)

**Comment by GaryElshaw** [comment]
I like the idea of those as a Dark variant with dock transparency!

**Comment by GaryElshaw** [comment]
I'm not sure if those who are really just after the old colours will like it, but i think it's a good compromise between 3.0 and 4.0. 

![SCR-20230211-m6t](https://user-images.githubusercontent.com/69029666/218235706-5fc5ce53-a584-47f1-bc71-d51b0efccd75.png)

**Comment by sweetppro** [comment]
its definitely more legible
but, I personally prefer the brighter colors
:)

**Comment by GaryElshaw** [comment]
Me too, i prefer what was already there...

**Comment by Yohmi** [comment]
I prefer the updated style (current one), the brighter colours make it more "pop", it looks fresh and friendly. I don't have issues to read the text (light mode, 2017 retina screen). I see there's a PR for reverting back, I hope we will have a choice there, the older template looks sad and dated…

**Comment by robd003** [comment]
Is there anyway to make this customizable? I'm using the dark theme on macOS and would much prefer the bright colors.

**Comment by ilikepeaches** [comment]
additional vote for the old dark colors or something approximating them
always always a fan of allowing users to customize :-)

**Comment by ckerr** [comment]
If someone wants to make a PR that makes it customizable, that could be added for the next feature release.

For `4.0.1` I'd rather go with the simpler change-the-hardcoded-colors-to-the-compromise option since adding customization isn't a bugfix

**Comment by ckerr** [comment]
If someone wants to make a PR that makes it customizable, that could be added for the next feature release.

For `4.0.1` I'd rather go with the simpler change-the-hardcoded-colors-to-the-compromise option since adding customization isn't a bugfix, but improving contrast arguably is.

**Comment by GaryElshaw** [comment]
PR amended #4813
