### ISSUE TITLE
suggestion: make download link to VCRedist clickable

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#4802]
### What is the issue?

When you open installer on old system like Win7, probably you get this window:
![image](https://user-images.githubusercontent.com/76732207/218187871-03e111ef-882f-480f-92c3-efaf143c81e7.png)

It would be very nice if the download link would be clickable :)

### Which application of Transmission?

None

### Which version of Transmission?

4.0.0

**Comment by mikedld** [comment]
That's not possible with .msi package we currently have. Given that it's not the only thing that's not possible (e.g. supporting dark mode also seems out of the question), we might consider switching to .exe installer in the future.

**Comment by Petrprogs** [comment]
> That's not possible with .msi package we currently have. Given that it's not the only thing that's not possible (e.g. supporting dark mode also seems out of the question), we might consider switching to .exe installer in the future.

Ok. I think that switching to exe installer is good idea too.
