### ISSUE TITLE
There is no visible highlight in groups list while moving with arrow keys

### ISSUE THREAD

**Issue by ziovelvet** [transmission/transmission#4806]
With 'Groups' turned on (View > Use Groups) there's no way to tell which group is selected navigating with arrow keys.

Attached _gif_ shows Transmission v3 on left side - v4 on right side

![Transmission 3 vs 4](https://user-images.githubusercontent.com/42490488/218214168-5fdf42a0-a57d-434c-893e-b4403d9b601a.gif)

Also a better way to highlight groups would be more than welcome. (Need to check if this is related to some Mojave limitations)

### Which application of Transmission?
macOS app (macOS Mojave 10.14.6)

### Which version of Transmission?
4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
CC'ing the macOS army: @Coeur @nevack @sweetppro @GaryElshaw

**Comment by Coeur** [comment]
Not specific to Mojave: also reproduced on macOS Ventura.

**Comment by Coeur** [comment]
Regression might have come from #4333 (@sweetppro).
