### ISSUE TITLE
A potential memory leak

### ISSUE THREAD

**Issue by qingkaishi** [transmission/transmission#481]
Hi, guys

here, it seems there exists a memory leak

https://github.com/transmission/transmission/blob/eb5d1a79cbe1b9bc5b22fdcc598694ecd4d02f43/libtransmission/file-posix.c#L1020-L1059

In the above code, the memory allocated at Line 1033 is not released properly. That is, it is only released at Line 1048 in the condition (ret == NULL). However, if ret != NULL, the memory will not be released

**Comment by mikedld** [comment]
According to the manual (`getcwd(3)`),

> On success, these functions return a pointer to a string containing the pathname of the current working directory. In the case getcwd() and getwd() this is the same value as buf.

Meaning, when the loop ends `ret` has the same value as `tmp` if `getcwd` succeeded, which then gets returned from the function and it's the responsibility of the caller to free it. If `getcwd` didn't succeed, `ret` is `NULL` and `tmp` is freed properly.
