### ISSUE TITLE
De-selecting port forwarding in Qt config window does not take affect

### ISSUE THREAD

**Issue by zhen-huan-hu** [transmission/transmission#4818]
### What is the issue?

De-selecting UPnP or NAT-PMP port forwarding in the Qt client (as a thin client connected to a daemon) does not save the status to `settings.json`. The option is shown as enabled again after relaunching the Qt client.

![Screenshot 2023-02-10 231319](https://user-images.githubusercontent.com/9272721/218241511-2c48b0a6-6f07-4925-8a19-4ef582d00995.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
@zhen-huan-hu thanks for the bug report!
