### ISSUE TITLE
Allow setting Remote Control in thin-client mode

### ISSUE THREAD

**Issue by zhen-huan-hu** [transmission/transmission#4819]
### What is the issue?

Right now the Remote Control configuration panel is disabled in thin-client mode. Users had to change the setting on the remote server which often does not have a GUI. It would be nice if the Remote Control panel allows user change the settings on the server side in thin-client mode.

![Screenshot 2023-02-10 231910](https://user-images.githubusercontent.com/9272721/218241714-49738f30-7079-4798-97d7-a90daaf6b3ea.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
This was intentional so that there is no surface area for an attacker to change authentication and whitelist options.

I agree it's nice-to-have to allow remote configuration of these settings, but I'm suspicious of the risk / reward tradeoff...

**Comment by Pentaphon** [comment]
>This was intentional so that there is no surface area for an attacker to change authentication and whitelist options.

Question: As long as the user enables, and then properly configures their web UI, after opening the 9091 port on their router to access their web UI outside their home, isn't the web UI secure from such attacks? 

I see your point about not having any surface at all is safer than having a surface, but this is true for pretty much every software that can be connected to via the internet. 

I think after so many years of this client being out there, it's probably time to allow the user that functionality, as other clients are allowing it in an increasingly remote-ready world.
