### ISSUE TITLE
two potential memory leaks

### ISSUE THREAD

**Issue by qingkaishi** [transmission/transmission#482]
Hi guys

Here, it seems there are two memory leaks.

https://github.com/transmission/transmission/blob/eb5d1a79cbe1b9bc5b22fdcc598694ecd4d02f43/libtransmission/tr-dht.c#L358-L366

The pointers `nodes` and `nodes6` in the above code point to two newly-allocated memory.

https://github.com/transmission/transmission/blob/eb5d1a79cbe1b9bc5b22fdcc598694ecd4d02f43/libtransmission/tr-dht.c#L395-L398

If `rc < 0` in the above code happens, it will go to the label `fail`, where `nodes` and `nodes6` are not released.

**Comment by mikedld** [comment]
Looks legit, thanks for reporting!
