### ISSUE TITLE
Build gets stuck because of clang-tidy >= 15 stalling

### ISSUE THREAD

**Issue by rsekman** [transmission/transmission#4821]
I've been building transmission from main as an [Arch (AUR) package](https://aur.archlinux.org/packages/transmission-cli-git). The build command looks like this.
```
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DENABLE_CLI=ON \
    -DENABLE_GTK=OFF \
    -DENABLE_QT=OFF \
    -DENABLE_WEB=OFF \
    -DINSTALL_LIB=ON \
    -DUSE_SYSTEM_UTP=OFF \
    -DUSE_SYSTEM_DHT=ON \
    -DUSE_SYSTEM_B64=ON \
    -DUSE_SYSTEM_NATPMP=ON
make
```
The last version I was able to build was 53815e5eb on Jan 23. After this the build started stalling close to completion,  on this step:
```
[ 91%] Building CXX object tests/libtransmission/CMakeFiles/libtransmission-test.dir/web-utils-test.cc.o
```
I've left it overnight only to come back to it still stalled. `top` reveals that `clang-tidy` is using an entire core. If I pass `-DRUN_CLANG_TIDY=OFF` to skip the `clang-tidy` step the build completes without issues.  This issue has not arisen for CI because the Github workflows do precisely this.

However, `web-utils-test.cc` has not been changed since I was last able to build successfully. What *has* changed is that I have upgraded from `clang 14.0.6` to `clang 15.0.7`. And indeed, I cannot build 53815e5eb with this clang! If I downgrade clang to `14.0.6` I can build from main (4a3c21706 currently).

Possibly this is an upstream issue with clang; honestly I'm stumped.

(I think this is the same as https://github.com/transmission/transmission/discussions/4360.)

Version information:
```
% uname -a
Linux naoetsu 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64 GNU/Linux
% gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20230201 (GCC) 
% clang -v
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /sbin
Found candidate GCC installation: /sbin/../lib/gcc/x86_64-pc-linux-gnu/12.2.1
Found candidate GCC installation: /sbin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Selected GCC installation: /sbin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
% clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 15.0.7
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver2
```

**Comment by rsekman** [comment]
Possibly this? https://github.com/llvm/llvm-project/issues/59492

**Comment by ckerr** [comment]
Sounds like an upstream issue, though if it causes a FTBFS maybe we should make the clang-tidy build step an opt-in instead of enabling it when clang-tidy is found on the system.

**Comment by ckerr** [comment]
I'm seeing this too, in clang-tidy-15 but not clang-tidy-14. :man_shrugging:

**Comment by rsekman** [comment]
The problem seems to be with these tests https://github.com/transmission/transmission/blob/05a5c1e410322ef942a00f22a2fc5387fb200dbb/tests/libtransmission/web-utils-test.cc#L27-L38
Here `tr_urlParse` returns an optional and clang-tidy can't tell whether it's non-null in all branches. I think what's going on is that whatever macro expansion/template meta-programming wizardry is going on in gtest hits some regression in clang-tidy. 

In any case I think clang-tidy would be right to emit the `bugprone-unchecked-optional-access` warning here: the `EXPECT_TRUE` should be `ASSERT_TRUE`  to exit early and prevent accessing the fields of  `parsed` if it is in fact null. Cf. #4672.

**Comment by ckerr** [comment]
There are a couple of places in the code where I added `assert(foo)` after `EXPECT(foo)` to get rid of `bugprone-unchecked-optional-access`, e.g. 862abe909cc7162581e4bb17b22e05fb1c2775c1. @rsekman I'd welcome a PR if you want to make a quick fix to add it here

**Comment by rsekman** [comment]
This may have been fixed on main upstream:

https://github.com/llvm/llvm-project/issues/59492#issuecomment-1763510768
https://github.com/llvm/llvm-project/issues/55530#issuecomment-1848988697

Not sure when the fix will make it to releases and distros.
