### ISSUE TITLE
Shift-click often not working

### ISSUE THREAD

**Issue by nengxu** [transmission/transmission#4827]
### What is the issue?

This is a long time issue since V3. I'm using transmission-qt on Windows. Very often,  shift-click trying to multiple select torrents on the UI fail, while Ctrl-click worked. It seems when shift-click, something running in the background was updating the UI which caused the multiple selecting failed and only the one being clicked is selected. 

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

v3 - v4

**Comment by nengxu** [comment]
Any idea about this issue? It is very inconvenient.

**Comment by ckerr** [comment]
No idea, unfortunately. I'm not seeing this behavior :confused:

**Comment by nengxu** [comment]
This issue seems to be fixed after 4.0.1.
