### ISSUE TITLE
alt-i keyboard shortcut for torrent inspector doesn't work

### ISSUE THREAD

**Issue by pleasantone** [transmission/transmission#4829]
### What is the issue?

Browser is MacOS Safari

Keyboard shortcut hint says to use "Alt-I" to open the inspection window.
This would, using a Mac keyboard, usually translate to either Option-I (correct) or Command-I (problematic).
Neither work. Command-I is problematic because the command keys are often in use by the browser (e.g. Command-O opens a dialog box).

Fixes:
- Allow option- versions of the keys through the web interface.
- Better yet, allow straight keys again (just like transmission 3.0), which will work much better on mobile screens!

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0-stable

**Comment by ckerr** [comment]
Confirmed on macOS using both Safari and Chrome.

Works on Linux in Chrome.

Probably just a poor choice of accelerators; let's try some different defaults.

**Comment by tessus** [comment]
> let's try some different defaults.

Does this mean we can change them somehow by hacking a file?

**Comment by ckerr** [comment]
If you're willing to re-webpack the code, yes!

The actions and their shortcuts are in `web/src/action-manager.js`

If you have npm installed, you can rebuild `transmission-app.js` with:

```sh
$ cd web/
$ npm install
$ npm run build
```

And then use that new copy of `transmission-app.js` instead of the old one.

**Comment by tessus** [comment]
Nice, I can play around with this. Cool.

**Comment by tessus** [comment]
I have changed the shortcuts to:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/223439/221380988-52002f2c-88a8-4423-80e8-58576ef042cc.png">

and it works brilliantly. Thanks for the tip how to change them! 👍 

Btw, I've tried to use `Control+Shift+A` for `Deselect all`, but this didn't work. The `Shift` seems to be ignored, thus it just selects all.

**Comment by ckerr** [comment]
@tessus unmodified shortcuts are problematic. If you could add some modifiers on IOPRS that work on both Safari and Chrome then that would be great for a bugfix patch!

**Comment by tessus** [comment]
Ah, ok. In that case I just make the others also use `Control` and send a PR.

It's just that `Pause` and `Preferences` both start with `P` and I have no idea how `U` has anything to do with Pause, except maybe it's the 3rd letter in the word that hasn't been used yet. ;-)

Also, `Control+O` (and I and P) are not easy to do with only one hand on a MacBook, b/c there is no right ctrl key. However, this is just an observation.
