### ISSUE TITLE
Cannot make a .torrent file from a network location

### ISSUE THREAD

**Issue by Bimnomercy** [transmission/transmission#483]
Hello, everytime I try to make a new .torrent file from a network location URI folder like "\\other_computer\folder" or I mount a network disk to this kind of path on Windows 10, Transmission show an error telling "No such file or directory".

In an other side, it is able to share file or save the new .torrent file from a network path.

It's anoying because, I have to copy the file on local drive to make the .torrent file.

Thank you for your work.

**Comment by mikedld** [comment]
Fixed by 3106675261cf0727c608f41c66ae3b94aebb974f.
