### ISSUE TITLE
Suggestion: Dark mode

### ISSUE THREAD

**Issue by harbingerofd00m** [transmission/transmission#4835]
### What is the issue?

I'd really love a dark mode option in Transmission's menu/preferences, since I use light theme on my system (MacOS 13.2) but think certain apps (including this one) would look better dark. I've tried standalone apps that are supposed to be able to do this but haven't had any luck.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by UnderEu** [comment]
You want an app-based setting for enabling #DarkMode on it instead of relying the OS settings, is that the case?
And why are you commiting that crime to your eyes by using the wrong mode (the Retina-burning one), in the 1st place?

**Comment by nevack** [comment]
Personally I don't like this idea.
Many apps had such manual settings before proper dark/light mode was implemented in OS level.
I don't see how having Transmission dark while all of the OS is dark can be useful.

CC @Coeur @sweetppro @GaryElshaw to discuss.
This is not hard to do btw 
https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app

**Comment by harbingerofd00m** [comment]
Thank you both for your input, I completely understand this type of request isn't for everyone. As mentioned though I just think certain apps look better dark; Discord, VLC, Terminal to name a couple, whereas I like my system theme light since I feel Finder windows and pretty much most other apps look better this way. No stress if the feature request doesn't make it into a release, but if it's easy to implement then can't hurt to have the option right?

**Comment by Coeur** [comment]
If it's easy to implement, then wouldn't it be an opportunity to make a participation to code with a pull request for it, @harbingerofd00m ?

We could have such app settings to force an appearance mode, which is infrequent but available in some websites and apps, if someone is willing to have this feature and is willing to code it.

**Comment by harbingerofd00m** [comment]
Sorry if I've given the wrong impression, I wasn't making assumptions, I was just going on what @nevack said in a previous message. I'm fairly new to the site and how it works but I'd be more than happy to help with the request in any way I could.

**Comment by ckerr** [comment]
Even @harbingerofd00m submits a PR for it, there is still the ongoing cost of maintaining another feature. So I think we need to ask if this is something many people would use? Is this something that anyone here is volunteering to fix if there are bugs reported against it?

My _guess_ is that most people will just set a system-wide light or dark mode. It feels to me like per-app dark mode settings are more a leftover from before you could set it for the entire system.

I'm not _completely_ against the feature and could be talked into it -- but don't see much advantage to it and every feature adds more code.

**Comment by sweetppro** [comment]
I agree, I think it’s feature bloat

**Comment by GaryElshaw** [comment]
It's one of those 'nice-to-have' features, but given the project's resources, i think it just *has* to be further down the priority list, sorry @harbingerofd00m.

**Comment by harbingerofd00m** [comment]
@GaryElshaw No that's completely understandable! Thanks nonetheless to you and the others for your consideration
