### ISSUE TITLE
Problems in open web address torrent file

### ISSUE THREAD

**Issue by yoon1982** [transmission/transmission#484]
I used entware-ng on Asus RT-AC86u. Maybe transmission 2.92+git4 version is no problem(except some javascript) but I upgrade to 2.92+git5 version there are some problem on read webaddress.
magnet is no problem, and upload torrent file is no problem. just add url is problem 

![7eb5913a-f5d6-4999-8b23-660cd57e7491](https://user-images.githubusercontent.com/35776362/35347118-75d1bf8c-0177-11e8-8280-36b85572cda5.jpeg)

**Comment by yoon1982** [comment]
Just https has problem...http address is no problem.

**Comment by mikedld** [comment]
Please contact your package maintainer, we're neither preparing nor distributing packages for your platform here.
