### ISSUE TITLE
Website forums registration ReCAPTCHA is broken

### ISSUE THREAD

**Issue by dunxd** [transmission/transmission#4853]
### What is the issue?

When trying to register at https://forum.transmissionbt.com/ucp.php?mode=register, and completing the recaptcha these error messages appear at the top of the page every time making it impossible to register.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/16608541/218311368-a43911c2-346b-4edf-b962-1c011b922b60.png">

### Which application of Transmission?

None

**Comment by ckerr** [comment]
Cc @titer

**Comment by slimandslam** [comment]
I get those error messages when using the latest version of Safari on Mac. On the latest version of Firefox for Mac, when I hit submit, it just resets the form fields and I never get an email (no error messages are displayed tho).

**Comment by sararielle** [comment]
(thank you for catching the dupe!! my apologies for not seeing it myself.)
I can get through the TOS, fill out the page with name/pwd, complete the captcha, but when I hit submit it takes me back to the TOS page.  I'm on chrome for mac.

**Comment by mikedld** [comment]
I've updated the forum and extensions to the latest versions, could you try again?

**Comment by sararielle** [comment]
I went through the process a few hours ago and it did successfully complete but I still haven't received my confirmation/activation email.  (Yes I've checked my spam filter.)

**Comment by mikedld** [comment]
I didn't touch any mail configuration and there're no errors in logs, so not sure.

**Comment by sararielle** [comment]
That's fair.  I just wanted to update you on my attempt.  (I have no idea what happened to my confirmation email)

**Comment by mikedld** [comment]
There's a "Resend activation email" link on the login screen, maybe try that if you haven't.

**Comment by sararielle** [comment]
(attempting that.  I'll let you know what happens)

**Comment by sararielle** [comment]
It's been 3hrs and it still hasn't shown up.  Not sure what's up.

**Comment by dunxd** [comment]
I didn't get a confirmation email, tried registering again where it told me
my email address was already registered, then tried reset password which is
also supposed to generate an email which I did not receive. I suspect the
mail server config is misconfigured.

**Comment by ckerr** [comment]
closing as fixed based on previous comment.
