### ISSUE TITLE
lack of configure.ac / confgure.in during 4.0.0 source code compiling 

### ISSUE THREAD

**Issue by skiiingray** [transmission/transmission#4861]
### What is the issue?

As compiling the latest transmision 4.0.0 by transmission-4.0.0.tar.xz, it seems that I can't autoreconf (autoreconf -i) with the below error message : 

autoreconf: `configure.ac' or `configure.in' is required

just compared it to source code of transmission 3.0.0, there seems to lack of some files for compile and cofig. any take on this?

Thanks.   

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment]
Hi @skiiingray, autotools builds were removed in 2020 by #1465 so you'll need to build with cmake.

**Comment by skiiingray** [comment]
got it and will give it a try by cmake. btw, interestingly i could compile build 3.0.0 by autotools. thanks.

**Comment by skiiingray** [comment]
@ckerr , wondring why the minimum cmake version of CMake required is high a bit, at least 3.12.0? 
Any features of CMake 3.12 that are actually required? 
badly sorry my old NAS device can be upgraded in compiling to CMake 3.2.0 from 2.8.4. As theresult I either stay in Transmission 3.0 or have been trying hard to compile higher version of CMake enviroment first.

Thanks.

**Comment by mikedld** [comment]
@skiiingray, you could try lowering the requirement and seeing for yourself what works and what doesn't, I suppose. CMake 3.2 was released in 2015 while we're using C++17 proper support for which was introduced in GCC 7.1 released in 2017, so my guess is that you'll have more issues building Transmission than just the CMake version.

**Comment by fredo-47** [comment]
@skiiingray , you only need cmake for compiling, but not for running transmission.
Maybe it's possible for you to compile it elsewhere (could be even on a VM or Docker), and then simply copy over the compiled files to your NAS?
