### ISSUE TITLE
[Feature request] Option for speed limit when on battery

### ISSUE THREAD

**Issue by yunruse** [transmission/transmission#4866]
### What is the issue?

Uploading is naturally a bit of a resource-intensive task.

It would be lovely if there was a config setting such that _Speed Limit_ could be enabled when a laptop is on battery, to avoid needless battery degradation & improve performance — it's sort of hard to give a schedule to when I'll be on power or not.

Thank you for the wonderful application! ^^

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment]
Thanks for the suggestion!

Variants of this have come up in the past e.g. #975 and #1327. IMO these are valid ideas but that not many people would use the feature _and_ it's possible to accomplish by writing a script that tells Transmission what speed limits to use when the laptop is plugged in or unplugged, so it's not a feature that is going to go into the core program.
