### ISSUE TITLE
Transmission starts torrent when "Start when added" is unchecked.

### ISSUE THREAD

**Issue by cedarpoolst** [transmission/transmission#4873]
### What is the issue?

Transmission begins to download torrent when "Start when added" is unchecked.  This error began after updating to version 4.0.0.

### Which application of Transmission?

macOS app

### Which version of Transmission?

Version 4.0.0

**Comment by ckerr** [comment]
@cedarpoolst thanks for reporting this!

This is a duplicate off #4856 so I'm going to close this ticket as a dupe.
