### ISSUE TITLE
Stop working (MacOS 10.13.2 (17C205))

### ISSUE THREAD

**Issue by Kholyk** [transmission/transmission#488]
After torrent file has been added to download list try to pause/resume item. It doesn't resume download process, if you'll try to restart app it doesn't start anymore till next reboot.

**Comment by ckerr** [comment]
Closing this issue since it's been untouched for so long and the Transmission version is so old. If this is still happening in a [nightly build](https://transmissionbt.com/downloads) please file a new issue with updated information. Thank you!
