### ISSUE TITLE
slow downloads

### ISSUE THREAD

**Issue by papag1963** [transmission/transmission#4881]
### What is the issue?

slow download 3-4 days since update version 4.0

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0,0

**Comment by peritiSumus** [comment]
Same. Weirdly, I downgraded to 3.0 and still had speed issues. I switched to qBitTorrent to see if my network or machine were the issue, and speeds were as expected (5x faster). 

Ventura 13.1 (22C65)
Transmission 4.0.0

**Comment by Free5ky** [comment]
Same here. After downgrading to 3.0 it's faster but many files are marked as corrupt. (after verifying the DL resumes normally)
MacOS Monterey 12.4
Transmission 4.0.0

**Comment by lukecrownet** [comment]
Similiar for me -- on macOS Ventura. Been using Transmission forever, it's always been rock solid. Upgrade to Transmission 4.0.0 the other day. Worked great for a day or two, then started routinely dropping most peers on downloads. e.g., Add a torrent, it starts adding peers from the swarm like usual, decent speed, then suddenly it slows way down and then drops all or most of the peers, and either stays stuck at 0 peers or only sips from a single peer. 

Sometimes the "too many open files" error appears as well (I'd never run into this until 4.0.0 either), but not as consistently as the above happens.

**Comment by papag1963** [comment]
I never had a problem until the update. I us Folx free for now

**Comment by mishurov** [comment]
Same. Monterey. When I see the progress, it may stay at 15.4% and then go randomly back to 15.2% and forth to 15.43% and alternate back and forth. Downgraded to 3, works as a charm.

**Comment by papag1963** [comment]
How?? Where do I find it

**Comment by arcticfoxwp** [comment]
> Similar for me -- on macOS Ventura. Been using Transmission forever, it's always been rock solid. Upgraded to Transmission 4.0.0 the other day. Worked great for a day or two, then started routinely dropping most peers on downloads.
> 
> e.g., Add a torrent, it starts adding peers from the swarm like usual, decent speed, then suddenly it slows way down and then drops all or most of the peers, and either stays stuck at 0 peers or only sips from a single peer (even though there are tons of peers available).
> 
> Running "Update Tracker" or restarting Transmission will temporarily kick things back into gear, but then most of the peers get dropped again a few minutes later.
> 
> Sometimes the "too many open files" error appears as well (I'd never run into this until 4.0.0 either), but not as consistently as the above happens.
> 
> I haven't changed anything in my Transmission settings since upgrading to 4.0. Port is open like usual. Etc. The problem seems to be getting worse by the day though.

Is this with magnet links? Sounds like #4003

**Comment by lukecrownet** [comment]
Interesting — thanks for the lead! A lot of the comments in #4003 do sound like the problem I’m running into … Except I’m mostly not using magnet links. I’ve just tried a magnet link, and it ran into the same issue (peers initially connect, then drop), but in my case this is also happening with actual torrent file downloads, on private trackers.

**Comment by occamsrazorben** [comment]
I am having the same problem as "lukecrownet" described above - M1 Mini, Ventura 13.2.1. Even on super-popular torrents the number of peers connected drops to low numbers and the speed grinds to a complete halt and I'm seeing a bunch of "corrupt pieces" that require verification. Pretty impossible to finish downloading a torrent. Restarting Transmission seems to speed things up for a few minutes and then the same problem happens.

**Comment by lukecrownet** [comment]
I upgraded to the latest stable nightly and that resolved most of the issues for me. I’m seeing the working-indicator pinwheel more than ever before, but downloading and seeding speeds are strong again, and peers are no longer dropping off en-masse.

**Comment by barrymossel** [comment]
Hmmm, experiencing the same on linuxserver docker container. Guess I'll wait for a new release...

**Comment by tearfur** [comment]
@lukecrownet That may possibly be due to #4890 and a series of other related pull requests.

**Comment by sygibson** [comment]
Similar experience.  I had 4 torrents downloading in 4.0.0 on MacOS Big Sur 11.7.3.  After 1 week of excessively poor performance, I reinstalled 3.0.0.  Within 15 minutes all 4 torrents completed after achieving roughly 15 MB/s overall download speeds with about 225 peers in total.

Performance would be exceptionally sporadic on 4.0.0 - slowing down to zero for long periods of time ...then ramping up to 1 to 2 MB/s top speeds, then petering out again.

**Comment by mecowell** [comment]
This is happening on Ubuntu as well.

**Comment by ckerr** [comment]
FWIW `4.0.1` is scheduled for next Wednesday.

**Comment by Joomsy** [comment]
> This is happening on Ubuntu as well.

Strange. I'm on Pop_OS! 22.04, and I'm not having this problem. Just built the latest commit ([671f835](https://github.com/transmission/transmission/commit/671f835228c3092d75df4923ef8e4cd4835eb053)), and downloads are running at usual speeds. Are you using a pre-built binary? If so, I'm assuming this problem has already been fixed in the master.

**Comment by Coding4Coffee** [comment]
@sygibson @mishurov @papag1963 @peritiSumus @Free5ky and other MacOS users, can you tell me if you enabled "Randomize port on launch"?

**Comment by sygibson** [comment]
I do not have that set....

**Comment by mecowell** [comment]
I do not have that set either

**Comment by Coding4Coffee** [comment]
Do you have uTP on? If so, please compare with the same torrent:

1) Transmission 3.0 uTP on vs Transmission 4.0 uTP on
2) Transmission 3.0 uTP off vs Transmission 4.0 uTP off

I'm suspecting its something in the uTP code, as other clients have had their own fair share of issues with it:

**Comment by mecowell** [comment]
I cannot test with multiple versions but I can say that turning off uTP has allowed Transmission to stay up several hours and it did download a huge file in good time.

**Comment by hamzaelansali** [comment]
I have the same problem, the download is very slow I thought at first it was my connection, but after checking, it was not the case

**Comment by jawkdnaX** [comment]
This was happening to me also... as soon as I upgraded to 4.0, it was unusable. Had to switch to qbittorrent in the mean time. Patiently waiting on a fix as I love Transmission so much more!

**Comment by lsunsi** [comment]
Same here. Low speeds after upgrade and I'm very confused!

**Comment by sararielle** [comment]
I've been having this issue as well. It's very odd. Torrents add and start at a reasonable speed then fairly quickly lose speed (tho not peers).  If I open the inspector the "availability" tab is still quite dark (implying there's plenty of availability).  Weirdly does not appear to be consistent across torrent sites (that torrents are pulled from). (ie certain sites don't seem to have this problem? but the problem *is* consistent since upgrading to 4.0 with other sites.)

**Comment by ylwhatt** [comment]
described to a T whats happening to me... just spent a really long time changing settings around... will come here first from now on... im using the termux version of he daemon on a non rooted android

**Comment by mecowell** [comment]
Is everyone doing what was asked to help troubleshoot the issue? That will
be more helpful than just saying "me too, so I'm off to use a different
application"...

**Comment by sararielle** [comment]
I'd be happy to try the suggested troubleshoot but a) I don't have a great idea as to how to get 3.0 (let alone a nightly of 4.0) and b) I can't seem to figure out how to have 2 versions on my computer at once (even when they're in different places they seem to want to overwrite one another). [If you can provide solutions to these issues I'm happy to take a troubleshoot pass tonight.]

**Comment by Joomsy** [comment]
> I've been having this issue as well. It's very odd. Torrents add and start at a reasonable speed then fairly quickly lose speed (tho not peers). If I open the inspector the "availability" tab is still quite dark (implying there's plenty of availability). Weirdly does not appear to be consistent across torrent sites (that torrents are pulled from). (ie certain sites don't seem to have this problem? but the problem _is_ consistent since upgrading to 4.0 with other sites.)

Here you go. :)
https://github.com/transmission/transmission-releases
https://build.transmissionbt.com/job/trunk-linux/
https://build.transmissionbt.com/job/trunk-win32/
https://build.transmissionbt.com/job/trunk-mac/

**Comment by mecowell** [comment]
> I'd be happy to try the suggested troubleshoot but a) I don't have a great idea as to how to get 3.0 (let alone a nightly of 4.0) and b) I can't seem to figure out how to have 2 versions on my computer at once (even when they're in different places they seem to want to overwrite one another). [If you can provide solutions to these issues I'm happy to take a troubleshoot pass tonight.]

Can you try seeing if the problem exists with uTP on or off?
Is "Randomize port on launch" on or off?

**Comment by lsunsi** [comment]
@mecowell Mine is all default settings, I just reinstalled the system. Just chiming in to maybe be helpful. uTP=on,randomize=off

**Comment by sararielle** [comment]
uTP *is* on. as is randomize. (currently says port check site is down but it usually likes to tell me port is closed. doesn't seem to interfere with dl'ing tho.) disabling uTP doesn't seem to change things tho. (if anything it makes it worse? unclear)

**Comment by ckerr** [comment]
As mentioned above, several of the topics in this ticket have been fixed by  [4.0.1](https://github.com/transmission/transmission/releases/tag/4.0.1).

If slow speeds persist, please file issues with as much detail as possible against 4.0.1. Thanks!

**Comment by sararielle** [comment]
Just wanted to say thank you. 4.0.1 seems to have completely fixed this issue as well as my other main annoyance with 4.0.0, which was the weird new handling of magnets.

**Comment by ckerr** [comment]
@sararielle thank you for the followup!

It gets kind of tiring when I work very hard on a release and then the next day there are hostile comments like https://github.com/transmission/transmission/issues/86#issuecomment-1441218211 and https://github.com/transmission/transmission/issues/5004#issuecomment-1441924610 and wonder if working on this project is worth it. It's *very nice* to hear when something works as well :green_heart:

**Comment by lukecrownet** [comment]
4.0.1 is working great for me so far too -- many thanks for the quick turnaround on that. I've waited much longer for critical patches on paid services before, so it blows my mind some people can get so negative about some hiccups on a volunteer project, especially with how responsive and supportive so many of the folks here are. Bug testing new releases is half the fun ;) Keep up the great work! The engineering going into this is priceless.

**Comment by Genome26** [comment]
qbittorrent seems to be the only solid option, was using  transmission for everything then noticed some torrents would be stuck at 800Kbps even though there were more peers, switched to qbittorrent and speeds skyrocketed
