### ISSUE TITLE
Upload speed Dock badge is difficult to read

### ISSUE THREAD

**Issue by darrenrhs** [transmission/transmission#4899]
### What is the issue?

The upload speed Dock badge is difficult to read due to the colour change in 4.00

### Which application of Transmission?

Transmission for macOS

### Which version of Transmission?

4.00

---

The **old** speed badges looked like this:
<img width="64" alt="Screen Shot 2023-02-15 at 4 24 06 pm" src="https://user-images.githubusercontent.com/7334014/218940464-0034268f-e656-471b-a5eb-ee55b2cc87d1.png">

The **new** speed badges look like this:
<img width="62" alt="Screen Shot 2023-02-15 at 4 25 56 pm" src="https://user-images.githubusercontent.com/7334014/218940619-046ae9a4-30b3-4d42-ab64-29e417ad7981.png">

As you can see, both the upload and download badges have been updated to have lighter backgrounds and flat textures. The impact on the readability of the download badge is minimal. However, the upload badge is now much harder to read. If you focus on it, you can read it. But Dock badges are supposed to be glanced at while you're doing other things. You should not have to take a second to wait for your eyes to resolve the bright text from the bright background.

This is, in my opinion, an accessibility issue.

**Comment by GaryElshaw** [comment]
This has been address with #4813 and is available in the nightly builds. It will also be in the subsequent 4.0.1.

**Comment by darrenrhs** [comment]
> This has been address with #4813 and is available in the nightly builds. It will also be in the subsequent 4.0.1.

Thank you.
