### ISSUE TITLE
MacOS Ventura with v4.0 - every torrent added via web UI and URL is paused by default

### ISSUE THREAD

**Issue by Chopper3** [transmission/transmission#4901]
Every time I add a new URL torrent via the newly-updated web UI downloads the actual torrent file then goes to paused state, needing to be manually resumed.

**Comment by keatre** [comment]
Same issue for me on 4.0.0 from a docker image on Linux.  Downgraded back to version-3.00-r8 and working as expected.

**Comment by sweetppro** [comment]
this is potentially fixed in the latest nightly

**Comment by ckerr** [comment]
@Chopper3, @ekfritz, thanks for the report. I think this is fixed by the same change that fixed magnet links in 4856.

This can be tested out in the nightlies now or by building from source with `main`. Alternately, 4.0.1 should be out next week.
