### ISSUE TITLE
MacOS Ventura 4.0.0 - Segmented rars fail

### ISSUE THREAD

**Issue by kriebe** [transmission/transmission#4902]
### What is the issue?

I wasn't having any noticeable problems until I started downloading any torrents that had rar files that were in segmented parts. I thought that maybe it would just be the creator's fault, but I've tried multiple from different creators since and have the same issue.  I get constant "Failed DL" data.  I currently have a download attempting to download that is a total of 4.76GB.  It has a verified amount of 1.17GB and a Failed DL amount of 3GB.  As with all of these types of downloads, eventually it gets to a point where I never get any new verified data.  I've reverted back to 3.0 to test and everything works perfectly fine.
![Screenshot 2023-02-15 at 2 25 37 AM](https://user-images.githubusercontent.com/12870435/219001831-a33eb63f-e820-4ff2-9ea8-be7ea9fb1c8a.jpg)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
> I get constant "Failed DL" data.

Hey @kriebe thanks for reporting this.

This issue has been fixed by #4880 and #4890. There are nightly builds right now at https://transmissionbt.com/ and 4.0.1 should be out next week.

Thanks again!
