### ISSUE TITLE
build/libutp: Should symbols be checked using check_cxx_symbol_exists?

### ISSUE THREAD

**Issue by bheesham** [transmission/transmission#4910]
### What is the issue?

I was having trouble building with a pre-installed libutp on my system.

Configuring yielded:

      Could NOT find UTP (missing: UTP_LIBRARY UTP_INCLUDE_DIR)
    Call Stack (most recent call first):
      /very/long/path/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
      cmake/FindUTP.cmake:74 (find_package_handle_standard_args)
      cmake/TrMacros.cmake:136 (find_package)
      CMakeLists.txt:503 (tr_add_external_auto_library)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeOutput.log".
    See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeError.log".

The error logs included this bit:

    /very/long/path/bin/ld: /very/long/path/lib/libutp.a(utp_internal.cpp.o): in function `UTP_FreeAll(UTPSocketHT*)':
    (.text+0xc15): undefined reference to `operator delete(void*)'

After changing the check method to use `check_cxx_symbol_exists` instead,
configuring yielded:

    -- Found UTP: /very/long/path/lib/libutp.a

Draft PR created: https://github.com/transmission/transmission/pull/4909

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by bheesham** [comment]
I wonder what y'all are doing to get this working on your machines?

**Comment by ckerr** [comment]
Possibly related: https://github.com/transmission/transmission/pull/4877

**Comment by bheesham** [comment]
Answered here: https://github.com/transmission/transmission/pull/4909#issuecomment-1435351897.
