### ISSUE TITLE
Alternate speed and temp limites no longer working

### ISSUE THREAD

**Issue by Snazzie** [transmission/transmission#4914]
### What is the issue?

after the major update, alternate speed and temp speed feature has stopped working.

turning on temp limits seems to have no effect.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.0

**Comment by ckerr** [comment]
Hi @Snazzie, I think this is a duplicate of #4701 so I'm going to close this as a dupe, but thanks for reporting this!

I'd rather have a bug get duplicate reports than to go unreported :smile_cat:
