### ISSUE TITLE
Config file on Windows

### ISSUE THREAD

**Issue by ExcaliburGO** [transmission/transmission#492]
Hi! I installed transmission on 64 bit Windows 10 pc and can't find config file used when running as a daemon. When I run from console, it's C:\Users\Gateway\AppData\Local\transmission-daemon.
When running graphical version, it's C:\Users\Gateway\AppData\Local\transmission. But I can't find file used when running as a Windows service.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) for support.

[Documentation](/transmission/transmission/wiki/Configuration-Files) describes the location as relative to `%LOCALAPPDATA%`. When daemon is running as a service, it's using LocalService account (by default unless you change it), for which the aforementioned environment variables expands to e.g. "C:\Windows\ServiceProfiles\LocalService\AppData\Local".
