### ISSUE TITLE
libsystemd instead of libsystemd-daemon

### ISSUE THREAD

**Issue by ben-ba** [transmission/transmission#493]
Is it possible to add commit #5921 (from master) to the 2.9x branch? 

https://github.com/transmission/transmission/commit/0862099d0bf5a3ec8b2e9d538458d612897741a2

**Comment by mikedld** [comment]
Next time please add the comment for the commit itself (scroll down to see the comments box) or the corresponding PR (if there is one), no need in opening new issue.

Certainly possible but only if we're going to have 2.94.

**Comment by RSully** [comment]
We had a 2.94 and it wasn't included, any updates here?
