### ISSUE TITLE
GTK app unresponsive

### ISSUE THREAD

**Issue by Daniel6372** [transmission/transmission#4934]
### What is the issue?

Transmission 4.0 on Fedora seems to have issues with closing/minimizing to tray.

Initially, when the program is first installed, the default value for the "Show Transmission icon in the notification area" option is false. In this mode, trying closing the GTK app (either the close window button or File -> Exit) results in a long wait (3-5 minutes) for it to close while it's displaying the "Closing connections... Sending upload/download totals to tracker..." message, even when no torrents have been added yet. Pressing the "Quit Now" button does close it immediately.

However, the a bigger issue arises when the "Show Transmission icon in the notification area" option is enabled. Closing the GTK app does seem to minimize it to the tray normally, but when clicking the tray icon, it (sometimes) still has the checkmark next to the "Show Transmission" option, indicating that the app is still open. Clicking on "Show Transmission" then causes a jump to 100% cpu usage and the app never appears. Transmission's cpu usage then remains at 100% until transmission-gtk is manually killed (e.g. using htop).

Demonstration:
https://user-images.githubusercontent.com/47946277/219822671-2b9628fa-65a0-4c2c-a669-67b02ea05f9c.mp4

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by mikedld** [comment]
For the long shutdown, I believe it's not GTK-specific and there're other tickets that address this.
