### ISSUE TITLE
V4.0 macOS - sort by queue order fails when app is quit

### ISSUE THREAD

**Issue by projeKCtion** [transmission/transmission#4935]
### What is the issue?

In V 4.0 when "Sort Transfers By" is set to queue order and manually ordered, when app is quit the order is forgotten (queue is in random order when re-launched.) The functioned correctly in previous versions.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0

**Comment by ckerr** [comment]
Hi @projeKCtion , thanks for reporting this!

This seems to be a duplicate of #155 so I'm going to close this as a dupe.
