### ISSUE TITLE
version 4.0.0 old issue again - magnet links pause after getting metadata

### ISSUE THREAD

**Issue by xiiviii** [transmission/transmission#4940]
the issue in #2239 seems to be happening again in the most recent build v4.0.0: adding any magnet link and they all pause after they get metadata instead of downloading.

**Comment by FoUStep** [comment]
+1, same issue indeed, after clicking resume right away it'll start the download (which makes it harder to automate)

**Comment by ckerr** [comment]
What does "most recent build v4.0.0" mean -- do you mean literally v4.0.0, or the latest 4.0.0-dev nightly?

**Comment by FoUStep** [comment]
To me, it's the stable build on the main website. Latest stable release (4.0.0 280ace12f8).

**Comment by ckerr** [comment]
Thanks for reporting this.

I think this is a duplicate of #4740, so I'm closing this one as a dupe.

This issue is fixed in the nightly builds and will be in `4.0.1` which is currently scheduled for next Wednesday.
