### ISSUE TITLE
Build error in peer-io

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4944]
### What is the issue?

Not sure exactly what happened in #4897, but peer-io is unhappy during the make process.

```
`[ 21%] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:748:40: error: no member named 'error_code' in 'utp_callback_arguments'
                io->on_utp_error(args->error_code);
                                 ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:761:63: error: no member named 'send' in 'utp_callback_arguments'
                io->bandwidth().notifyBandwidthConsumed(args->send != 0 ? TR_UP : TR_DOWN, args->len, false, tr_time_msec());
                                                        ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:773:47: error: no member named 'state' in 'utp_callback_arguments'
                io->on_utp_state_change(args->state);
                                        ~~~~  ^
3 errors generated.
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o] Error 1`
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0 main

**Comment by ckerr** [comment]
This isn't a 4897 change. Most likely candidate is #4877, _possibly_ 4909. 

@GaryElshaw completely remove the build directory and start a build from scratch. If the build still fails then CC Mike.

**Comment by ckerr** [comment]
This isn't a 4897 change. Most likely candidate is #4877, _possibly_ 4909. 

@GaryElshaw completely remove the build directory and start a build from scratch. If that solves it, go ahead and close this ticket. If that doesn't solve it, CC Mike since he'll probably know better than me what the next step is

**Comment by GaryElshaw** [comment]
Hello @mikedld, can you please advise?

**Comment by mikedld** [comment]
@GaryElshaw, you didn't update the submodules after updating the main repo.

**Comment by GaryElshaw** [comment]
Ugh. Thanks Mike.

**Comment by mikedld** [comment]
Now you need to try what Charles suggested, i.e. a clean build :)

**Comment by GaryElshaw** [comment]
I did, i promise. This is usually where i contemplate getting a fresh clone.

Yep, #4955 will hopefully help a number of issues being filed, i reckon.

**Comment by mikedld** [comment]
> I did, i promise.

Was that before or after updating the submodules? If before then try again, since what is (was) happening is that sources are (were) copied into the build directory, so even if you change them in the source directory (by e.g. updating a submodule) afterwards they aren't (weren't) getting copied again.

**Comment by GaryElshaw** [comment]
It was after updating the submodules. I've just pulled #4955, so will give that a go too.

**Comment by GaryElshaw** [comment]
I thought i'd give ninja a go rather than cmake, pretty much the same result.

`[210/447] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o
FAILED: libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DFMT_EXCEPTIONS=0 -DFMT_HEADER_ONLY=1 -DHAVE_COPYFILE -DHAVE_FLOCK -DHAVE_MKDTEMP -DHAVE_PREAD -DHAVE_PWRITE -DHAVE_SO_REUSEPORT=1 -DHAVE_STATVFS -DHAVE_SYS_STATVFS_H -DHAVE_XLOCALE_H -DMINIUPNP_STATICLIB -DNATPMP_STATICLIB -DPACKAGE_DATA_DIR=\"/usr/local/share\" -DSYSTEM_MINIUPNP -DUSE_SYSTEM_B64 -DWIDE_INTEGER_DISABLE_FLOAT_INTEROP -DWIDE_INTEGER_DISABLE_IOSTREAM -DWITH_KQUEUE -DWITH_UTP -D__TRANSMISSION__ -I/Users/garyelshaw/Documents/GitHub/transmission-primary/build/libtransmission -I/Users/garyelshaw/Documents/GitHub/transmission-primary/third-party/jsonsl -I/Users/garyelshaw/Documents/GitHub/transmission-primary/third-party/wildmat -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/libdeflate.bld/pfx/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/cmake/../third-party/fast_float/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/libpsl.bld/pfx/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/libnatpmp.bld/pfx/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/miniupnpc.bld/pfx/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/dht.bld/pfx/include -isystem /usr/local/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/cmake/../third-party/utfcpp/source -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/cmake/../third-party/wide-integer -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/cmake/../third-party/fmt/include -isystem /Users/garyelshaw/Documents/GitHub/transmission-primary/build/third-party/libevent.bld/pfx/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -W -Wall -Wextra -Wcast-align -Wexit-time-destructors -Wextra-semi -Wextra-semi-stmt -Wextra-tokens -Wfloat-equal -Wgnu -Winit-self -Wint-in-bool-context -Wmissing-format-attribute -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wredundant-move -Wreorder-ctor -Wreturn-std-move -Wself-assign -Wself-move -Wsemicolon-before-method-body -Wsentinel -Wshadow -Wsign-compare -Wsometimes-uninitialized -Wstring-conversion -Wsuggest-destructor-override -Wsuggest-override -Wuninitialized -Wunreachable-code -Wunused -Wunused-const-variable -Wunused-parameter -Wunused-result -Wwrite-strings -Wformat-security -std=gnu++17 -MD -MT libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o -MF libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o.d -o libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o -c /Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:748:40: error: no member named 'error_code' in 'utp_callback_arguments'
                io->on_utp_error(args->error_code);
                                 ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:761:63: error: no member named 'send' in 'utp_callback_arguments'
                io->bandwidth().notifyBandwidthConsumed(args->send != 0 ? TR_UP : TR_DOWN, args->len, false, tr_time_msec());
                                                        ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-io.cc:773:47: error: no member named 'state' in 'utp_callback_arguments'
                io->on_utp_state_change(args->state);
                                        ~~~~  ^
3 errors generated.
[214/447] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-mgr.cc.o
In file included from /Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/peer-mgr.cc:35:
/Users/garyelshaw/Documents/GitHub/transmission-primary/libtransmission/handshake.h:257:24: warning: declaration requires an exit-time destructor [-Wexit-time-destructors]
    static inline auto dh_pool_mutex_ = std::mutex{};
                       ^
1 warning generated.
[215/447] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-msgs.cc.o
ninja: build stopped: subcommand failed.
garyelshaw@Garys-Air build % 
`

**Comment by GaryElshaw** [comment]
Similarly, on Windows 10.

C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
   60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
      |                                        ^
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:326:5: note: in expansion of macro 'TR_ASSERT'
  326 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |     ^~~~~~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc: In static member function 'static void tr_peerIo::event_read_cb(intptr_t, short int, void*)':
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:38: warning: comparison of integer expressions of different signedness: 'tr_socket_t' {aka 'long long unsigned int'} and 'intptr_t' {aka 'long long int'} [-Wsign-compare]
  450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
   60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
      |                                        ^
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:5: note: in expansion of macro 'TR_ASSERT'
  450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |     ^~~~~~~~~
[96/294] Building CXX object libtransm...Files/transmission.dir/peer-mgr.cc.obj
ninja: build stopped: subcommand failed.
PS C:\Users\Gary\Documents\GitHub\transmission\build>

**Comment by ckerr** [comment]
> Similarly, on Windows 10.
> 
> ```
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
>    60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
>       |                                        ^
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:326:5: note: in expansion of macro 'TR_ASSERT'
>   326 |     TR_ASSERT(io->socket_.handle.tcp == fd);
>       |     ^~~~~~~~~
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc: In static member function 'static void tr_peerIo::event_read_cb(intptr_t, short int, void*)':
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:38: warning: comparison of integer expressions of different signedness: 'tr_socket_t' {aka 'long long unsigned int'} and 'intptr_t' {aka 'long long int'} [-Wsign-compare]
>   450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
>       |               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
>    60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
>       |                                        ^
> C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:5: note: in expansion of macro 'TR_ASSERT'
>   450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
>       |     ^~~~~~~~~
> [96/294] Building CXX object libtransm...Files/transmission.dir/peer-mgr.cc.obj
> ninja: build stopped: subcommand failed.
> PS C:\Users\Gary\Documents\GitHub\transmission\build>
> ```

That doesn't look similar at all. Also it doesn't seem to include the build error?

**Comment by GaryElshaw** [comment]
Betterer?

[91/294] Building CXX object libtransm...les/transmission.dir/open-files.cc.obj
FAILED: libtransmission/CMakeFiles/transmission.dir/open-files.cc.obj
C:\msys64\mingw64\bin\g++.exe -DFMT_EXCEPTIONS=0 -DFMT_HEADER_ONLY=1 -DHAVE_GETTEXT -DHAVE_LIBINTL_H -DHAVE_NGETTEXT -DMINIUPNP_STATICLIB -DNATPMP_STATICLIB -DPACKAGE_DATA_DIR="\"C:/Program Files (x86)/transmission/share\"" -DSYSTEM_MINIUPNP -DWIDE_INTEGER_DISABLE_FLOAT_INTEROP -DWIDE_INTEGER_DISABLE_IOSTREAM -DWIN32 -DWITH_UTP -D_FILE_OFFSET_BITS=64 -D__TRANSMISSION__ -IC:/Users/Gary/Documents/GitHub/transmission/build/libtransmission -IC:/Users/Gary/Documents/GitHub/transmission/third-party/libutp/include -IC:/Users/Gary/Documents/GitHub/transmission/third-party/libb64/include -IC:/Users/Gary/Documents/GitHub/transmission/third-party/jsonsl -IC:/Users/Gary/Documents/GitHub/transmission/third-party/wildmat -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/libdeflate.bld/pfx/include -isystem C:/dev/vcpkg/installed/x64-windows/include -isystem C:/Users/Gary/Documents/GitHub/transmission/cmake/../third-party/fast_float/include -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/libpsl.bld/pfx/include -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/libnatpmp.bld/pfx/include -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/miniupnpc.bld/pfx/include -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/dht.bld/pfx/include -isystem C:/Users/Gary/Documents/GitHub/transmission/cmake/../third-party/utfcpp/source -isystem C:/Users/Gary/Documents/GitHub/transmission/cmake/../third-party/wide-integer -isystem C:/Users/Gary/Documents/GitHub/transmission/cmake/../third-party/fmt/include -isystem C:/Users/Gary/Documents/GitHub/transmission/build/third-party/libevent.bld/pfx/include -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__USE_MINGW_ANSI_STDIO=1 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -W -Wall -Wextra -Wcast-align -Wduplicated-cond -Wextra-semi -Wfloat-equal -Winit-self -Wint-in-bool-context -Wlogical-op -Wmissing-format-attribute -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wredundant-move -Wrestrict -Wshadow -Wsign-compare -Wsuggest-override -Wuninitialized -Wunreachable-code -Wunused -Wunused-const-variable -Wunused-parameter -Wunused-result -Wwrite-strings -Wno-format -std=gnu++17 -MD -MT libtransmission/CMakeFiles/transmission.dir/open-files.cc.obj -MF libtransmission\CMakeFiles\transmission.dir\open-files.cc.obj.d -o libtransmission/CMakeFiles/transmission.dir/open-files.cc.obj -c C:/Users/Gary/Documents/GitHub/transmission/libtransmission/open-files.cc
In file included from C:/msys64/mingw64/include/winbase.h:19,
                 from C:/msys64/mingw64/include/windows.h:70,
                 from C:/Users/Gary/Documents/GitHub/transmission/libtransmission/error-types.h:10,
                 from C:/Users/Gary/Documents/GitHub/transmission/libtransmission/open-files.cc:16:
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/open-files.cc: In function 'constexpr auto {anonymous}::isOpen(tr_sys_file_t)':
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/file.h:40:25: error: 'reinterpret_cast' from integer to pointer
   40 | #define TR_BAD_SYS_FILE INVALID_HANDLE_VALUE
      |                         ^~~~~~~~~~~~~~~~~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/open-files.cc:30:18: note: in expansion of macro 'TR_BAD_SYS_FILE'
   30 |     return fd != TR_BAD_SYS_FILE;
      |                  ^~~~~~~~~~~~~~~
[95/294] Building CXX object libtransm...eFiles/transmission.dir/peer-io.cc.obj
In file included from C:/Users/Gary/Documents/GitHub/transmission/libtransmission/transmission.h:23,
                 from C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:20:
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc: In static member function 'static void tr_peerIo::event_write_cb(intptr_t, short int, void*)':
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:326:38: warning: comparison of integer expressions of different signedness: 'tr_socket_t' {aka 'long long unsigned int'} and 'intptr_t' {aka 'long long int'} [-Wsign-compare]
  326 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
   60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
      |                                        ^
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:326:5: note: in expansion of macro 'TR_ASSERT'
  326 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |     ^~~~~~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc: In static member function 'static void tr_peerIo::event_read_cb(intptr_t, short int, void*)':
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:38: warning: comparison of integer expressions of different signedness: 'tr_socket_t' {aka 'long long unsigned int'} and 'intptr_t' {aka 'long long int'} [-Wsign-compare]
  450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/tr-macros.h:60:40: note: in definition of macro 'TR_LIKELY'
   60 | #define TR_LIKELY(x) __builtin_expect((x) ? 1L : 0L, 1L)
      |                                        ^
C:/Users/Gary/Documents/GitHub/transmission/libtransmission/peer-io.cc:450:5: note: in expansion of macro 'TR_ASSERT'
  450 |     TR_ASSERT(io->socket_.handle.tcp == fd);
      |     ^~~~~~~~~
[96/294] Building CXX object libtransm...Files/transmission.dir/peer-mgr.cc.obj
ninja: build stopped: subcommand failed.
PS C:\Users\Gary\Documents\GitHub\transmission\build>

**Comment by mikedld** [comment]
That's unrelated and previously posted at #4893.

**Comment by mikedld** [comment]
> This is usually where i contemplate getting a fresh clone.

Go for it. Fresh clone, fresh build directory, fresh everything.

**Comment by GaryElshaw** [comment]
Yup!

**Comment by GaryElshaw** [comment]
No die :-(

[ 21%] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o
/Users/garyelshaw/Documents/GitHub/transmission/libtransmission/peer-io.cc:748:40: error: no member named 'error_code' in 'utp_callback_arguments'
                io->on_utp_error(args->error_code);
                                 ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission/libtransmission/peer-io.cc:761:63: error: no member named 'send' in 'utp_callback_arguments'
                io->bandwidth().notifyBandwidthConsumed(args->send != 0 ? TR_UP : TR_DOWN, args->len, false, tr_time_msec());
                                                        ~~~~  ^
/Users/garyelshaw/Documents/GitHub/transmission/libtransmission/peer-io.cc:773:47: error: no member named 'state' in 'utp_callback_arguments'
                io->on_utp_state_change(args->state);
                                        ~~~~  ^
3 errors generated.
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o] Error 1
make[1]: *** [libtransmission/CMakeFiles/transmission.dir/all] Error 2
make: *** [all] Error 2

**Comment by mikedld** [comment]
This is simply impossible. Do these 4 commands work?
```
cd /tmp
git clone --recurse-submodules https://github.com/transmission/transmission
cmake -S transmission -B transmission.build
cmake --build transmission.build --target transmission
```

If they don't, what is the output of these commands?

```
grep UTP transmission.build/CMakeCache.txt
head -n119 transmission/third-party/libutp/include/libutp/utp.h | tail -n21
```

Are you sure that "/Users/garyelshaw/Documents/GitHub/transmission" is the directory that you're removing, cloning to, updating submodules in? First half of this thread was using "/Users/garyelshaw/Documents/GitHub/transmission-primary", so I'd like to make sure.

**Comment by GaryElshaw** [comment]
> Do these 4 commands work?

Sadly, no.

[ 62%] Building CXX object libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o
/tmp/transmission/libtransmission/peer-io.cc:748:40: error: no member named 'error_code' in 'utp_callback_arguments'
                io->on_utp_error(args->error_code);
                                 ~~~~  ^
/tmp/transmission/libtransmission/peer-io.cc:761:63: error: no member named 'send' in 'utp_callback_arguments'
                io->bandwidth().notifyBandwidthConsumed(args->send != 0 ? TR_UP : TR_DOWN, args->len, false, tr_time_msec());
                                                        ~~~~  ^
/tmp/transmission/libtransmission/peer-io.cc:773:47: error: no member named 'state' in 'utp_callback_arguments'
                io->on_utp_state_change(args->state);
                                        ~~~~  ^
3 errors generated.
make[3]: *** [libtransmission/CMakeFiles/transmission.dir/peer-io.cc.o] Error 1

Command output from grep UTP transmission.build/CMakeCache.txt:

garyelshaw@Garys-Air /tmp % grep UTP transmission.build/CMakeCache.txt
ENABLE_UTP:BOOL=ON
USE_SYSTEM_UTP:STRING=ON
UTP_INCLUDE_DIR:PATH=/usr/local/include
UTP_LIBRARY:FILEPATH=/usr/local/lib/libutp.a
//Details about finding UTP
FIND_PACKAGE_MESSAGE_DETAILS_UTP:INTERNAL=[/usr/local/lib/libutp.a][/usr/local/include][v()]
HAVE_UTP_CHECK_TIMEOUTS:INTERNAL=1
HAVE_UTP_CLOSE:INTERNAL=1
HAVE_UTP_CONNECT:INTERNAL=1
HAVE_UTP_CONTEXT_GET_USERDATA:INTERNAL=1
HAVE_UTP_CONTEXT_SET_OPTION:INTERNAL=1
HAVE_UTP_CONTEXT_SET_USERDATA:INTERNAL=1
HAVE_UTP_CREATE_SOCKET:INTERNAL=1
HAVE_UTP_DESTROY:INTERNAL=1
HAVE_UTP_GETPEERNAME:INTERNAL=1
HAVE_UTP_GET_USERDATA:INTERNAL=1
HAVE_UTP_INIT:INTERNAL=1
HAVE_UTP_ISSUE_DEFERRED_ACKS:INTERNAL=1
HAVE_UTP_PROCESS_UDP:INTERNAL=1
HAVE_UTP_READ_DRAINED:INTERNAL=1
HAVE_UTP_SET_CALLBACK:INTERNAL=1
HAVE_UTP_SET_USERDATA:INTERNAL=1
HAVE_UTP_WRITE:INTERNAL=1
HAVE_UTP_WRITEV:INTERNAL=1
//STRINGS property for variable: USE_SYSTEM_UTP
USE_SYSTEM_UTP-STRINGS:INTERNAL=AUTO;ON;OFF
//ADVANCED property for variable: UTP_INCLUDE_DIR
UTP_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: UTP_LIBRARY
UTP_LIBRARY-ADVANCED:INTERNAL=1
_UTP_CFLAGS:INTERNAL=
_UTP_CFLAGS_I:INTERNAL=
_UTP_CFLAGS_OTHER:INTERNAL=
_UTP_FOUND:INTERNAL=
_UTP_INCLUDEDIR:INTERNAL=
_UTP_LIBDIR:INTERNAL=
_UTP_LIBS:INTERNAL=
_UTP_LIBS_L:INTERNAL=
_UTP_LIBS_OTHER:INTERNAL=
_UTP_LIBS_PATHS:INTERNAL=
_UTP_MODULE_NAME:INTERNAL=
_UTP_PREFIX:INTERNAL=
_UTP_STATIC_CFLAGS:INTERNAL=
_UTP_STATIC_CFLAGS_I:INTERNAL=
_UTP_STATIC_CFLAGS_OTHER:INTERNAL=
_UTP_STATIC_LIBDIR:INTERNAL=
_UTP_STATIC_LIBS:INTERNAL=
_UTP_STATIC_LIBS_L:INTERNAL=
_UTP_STATIC_LIBS_OTHER:INTERNAL=
_UTP_STATIC_LIBS_PATHS:INTERNAL=
_UTP_VERSION:INTERNAL=
_UTP_libutp_INCLUDEDIR:INTERNAL=
_UTP_libutp_LIBDIR:INTERNAL=
_UTP_libutp_PREFIX:INTERNAL=
_UTP_libutp_VERSION:INTERNAL=
__pkg_config_checked__UTP:INTERNAL=1

Output from head -n119 transmission/third-party/libutp/include/libutp/utp.h | tail -n21:

typedef struct {
	utp_context *context;
	utp_socket *socket;
	size_t len;
	uint32 flags;
	int callback_type;
	const byte *buf;

	union {
		const struct sockaddr *address;
		int send;
		int sample_ms;
		int error_code;
		int state;
	};

	union {
		socklen_t address_len;
		int type;
	};
} utp_callback_arguments;

**Comment by GaryElshaw** [comment]
> Are you sure that "/Users/garyelshaw/Documents/GitHub/transmission" is the directory that you're removing, cloning to, updating submodules in? First half of this thread was using "/Users/garyelshaw/Documents/GitHub/transmission-primary", so I'd like to make sure.

Sure thing. So /GitHub/transmission is the main clone i'm working from, the secondary /GitHub/transmission-primary is where i frequently build from by synching changes to because it contains some customisations or project-related stuff i work on.

**Comment by mikedld** [comment]
Please attach /usr/local/include/libutp/utp.h file here.

**Comment by GaryElshaw** [comment]
I think you just nailed where the problem lies. At some point, i think, ninja has installed libs that shouldn't have been installed.

[utp.h.txt](https://github.com/transmission/transmission/files/10784024/utp.h.txt)

**Comment by mikedld** [comment]
Well, needless to say those files shouldn't be there...

**Comment by mikedld** [comment]
I was just pointing someone to 20 ways to break Linux, I guess it applies to Mac too: https://github.com/transmission/transmission/discussions/4951#discussioncomment-5026541

**Comment by GaryElshaw** [comment]
> Well, needless to say those files shouldn't be there...

Nope, they should not. I'm usually pretty scrupulous, but missed this. Many thanks Mike, i wouldn't have found this without you.
