### ISSUE TITLE
Don't use group markers when using groups is enabled

### ISSUE THREAD

**Issue by svkirillov** [transmission/transmission#4952]
### What is the issue?

Just suggesting not to use group markers when using groups is enabled.

Should look good when scrolling with this suggestion: #4950

Examples:

| Current view | Suggested view |
| - | - |
| <img width="674" alt="Screenshot 2023-02-19 at 14 51 35" src="https://user-images.githubusercontent.com/33870726/219953410-af1d5582-4f5f-4c4c-87b8-c2db752707ea.png"> | <img width="674" alt="Screenshot 2023-02-19 at 14 51 35 2" src="https://user-images.githubusercontent.com/33870726/219953418-7222a619-0325-4629-9cd9-d480ecec5579.png"> |
| <img width="721" alt="Screenshot 2023-02-19 at 16 59 10" src="https://user-images.githubusercontent.com/33870726/219953700-fb9d544f-ef42-4099-aa87-b1600d64a1dd.png"> | <img width="721" alt="Screenshot 2023-02-19 at 16 59 10 2" src="https://user-images.githubusercontent.com/33870726/219953712-dff82c87-475b-4cc2-b534-db2921c69e0f.png"> |

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ilikepeaches** [comment]
Definitely agree with this one.  The dots on every single torrent are busy & duplicative.

**Comment by Coeur** [comment]
This would cause a regression on long lists of torrents.
I believe we should close this issue (#4952) and instead we should focus on #4950 which offers a better alternative.

**Comment by sweetppro** [comment]
Im working on this now, but its quite a large refactor as the TorrentTableView needs to be converted to view based

**Comment by Coeur** [comment]
No rush... if it's a large refactor, it will go with Transmission 5. :P

**Comment by sweetppro** [comment]
so I have this mostly rewritten as a view based table (still need to draw the progress bars), but I can't find a way to draw the group rows without this extra padding...
I've tried subclassing the tableRowView, but thats doesn't work. The tableview seems to magically add in this pacing to each group row which isn't stickied to the top of the tableview.
🤷‍♂️

@Coeur any ideas?
previously in the cell based tableview, I custom drew the group rows. but doing this will lose the ability to float... the whole reason for the rewrite.
<img width="508" alt="Screenshot 2023-03-03 at 9 40 16 pm" src="https://user-images.githubusercontent.com/7323792/222825200-9ffadf8d-b36e-491c-a743-899ec3776b22.png">

**Comment by Coeur** [comment]
Make a draft PR (with the progress bars) and we can look at fixing the padding from there?

**Comment by sweetppro** [comment]
> Make a draft PR (with the progress bars) and we can look at fixing the padding from there?

@Coeur ok so I have everything all working now (I think 😀) with the exception of this top padding for Group Rows...😣
Ill have another look at my code tonight with some fresh eyes, and clean it up some...
then upload a draft PR
