### ISSUE TITLE
Open Folder, queque and priority order not working

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#4957]
### What is the issue?

1- When right-click open a mouse submenu and i click on Open Folder not happens nothing.
2- When I try to set the downloads in order, for example moving to the top of the queue, nothing happens.
3- When using the website with the magnet link to download, a new transmission application opens, why not insert it into the opened app, instead of opening a new transmission?

### Which application of Transmission?

Qt app on Windows 11 (x64)

### Which version of Transmission?

Transmission 4.0.0-dev (c5b1df0daa)

**Comment by ckerr** [comment]
One issue per ticket please. Otherwise it's impossible to so triage or to track which issues are fixed and which aren't.
