### ISSUE TITLE
Priority queue not working

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#4962]
### What is the issue?

When having to move a download up or down nothing happens.
By right clicking > Queue > Move up/down/first/last
Nothing happens

### Which application of Transmission?

Qt app on Windows 11 (x64)
Language: Portuguese

### Which version of Transmission?

Transmission 4.0.0-dev (c5b1df0daa)

**Comment by ckerr** [comment]
Are you sorting by queueing order in `View > Sort by Queue`?

**Comment by celestinoxp** [comment]
no. but it doesn't make sense when I right-click and move up or down the row only if I have to go to View > Sort by Queue first. So it shouldn't appear on the right mouse button > Cupcake up/down.
In my opinion, the ideal thing is for the right mouse button to always work in the row, to move the selected download up or down the row

**Comment by ckerr** [comment]
> In my opinion, the ideal thing is for the right mouse button to always work in the row, to move the selected download up or down the row

I don't understand how that would work in practice. Say for example you're sorting by speed. "move up" can't make the torrent faster :smiley:

**Comment by celestinoxp** [comment]
> > In my opinion, the ideal thing is for the right mouse button to always work in the row, to move the selected download up or down the row
> 
> I don't understand how that would work in practice. Say for example you're sorting by speed. "move up" can't make the torrent faster 😃

when the order is by speed and we click with the right mouse button to make it go up or down, the order would be automatically changed to queue
