### ISSUE TITLE
Update messed up my torrents

### ISSUE THREAD

**Issue by Palivec** [transmission/transmission#497]
Hi ! So I updated from 1.92* to 1.93. Autoupdate failed (extraction error), so I deleted old .app and replaced it with the new version. All my already downloaded torrents (50+) showed as undownloaded, Transmission checked files of about 3 of them and begun to download all the other torrents again. However, all these files still exist completely and can be opened. Transmission just didnt check them and downloads the data somewhere again. Would you now where ? So my torrent list is unusable, but the files are ok. Can I still fix that ?

I run OSX 10.13.3

Thanks !

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
