### ISSUE TITLE
GTK systray icon MIA?

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4972]
### What is the issue?

Just wondering if i'm alone in not seeing the GTK systray icon anymore?

Manjaro w/ Gnome 43

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0-dev (88556bd859)

**Comment by ckerr** [comment]
Hey Gary, I think this is a duplicate of https://github.com/transmission/transmission/issues/4749 so I'm closing this one.

**Comment by GaryElshaw** [comment]
Thanks Charles! It is there when built with GTK 3.
