### ISSUE TITLE
[Feature Request] useful error when unexpected argument

### ISSUE THREAD

**Issue by grantwest** [transmission/transmission#4974]
### What is the issue?

I got stuck for a long time because I had `--peer-port` instead of `--peerport` as an argument. It would be nice if transmission could print an error about an unexpected argument. Right now it just prints the help page. 

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0

**Comment by RoeyFuchs** [comment]
I added a PR for this issue
https://github.com/transmission/transmission/pull/5029

**Comment by ckerr** [comment]
Fixed by #5029.
