### ISSUE TITLE
Not Moving eBooks

### ISSUE THREAD

**Issue by mccorkled** [transmission/transmission#498]
When a download completes, it's supposed to move from downloads/incomplete to /complete. This is working for music, tv, and movies, but not for ebooks which is puzzling me. I am using the Docker version. 

Transmission 2.92 (14714)

I am new to Docker and I am running this on my NAS and do not know much about SSH so I do not how to get the logs. 

Thank you

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

**Comment by mccorkled** [comment]
The forum where hundreds of people view posts but 0 people ever respond?

**Comment by mikedld** [comment]
You are more than welcome to change that, I for one would be greatful if you were to answer others' questions from time to time (and maybe you do, I don't know). Current situation doesn't change the fact that GitHub issues are, as Trac tickets were before that, not the place to expect customer support.

**Comment by mccorkled** [comment]
I would be able to answer people's questions if I knew how to troubleshoot issues but people answering my questions. ;)
