### ISSUE TITLE
Mouse submenu start vs startnow make confusion

### ISSUE THREAD

**Issue by celestinoxp** [transmission/transmission#4982]
### What is the issue?

Mouse right-click has 2 options that are confusing.
Start and Start Now (i don´t know what is the difference). 
In my idiom portuguese start = iniciar, start now = começar agora,

start = paused ?
start now = start download ?

Maybe a translation problem?

![image](https://user-images.githubusercontent.com/41735311/220457412-219ee987-7619-4f35-aeec-b4e2774ae7c6.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.0-dev

**Comment by Yohmi** [comment]
"começar agora" will ignore the queue. If you have set a download limit allowing 3 torrents to be downloaded simultaneously and add 4 torrents, the 4th will be paused until one the former 3 is downloaded (or manually paused). It will wait until a slot becomes available basically. By clicking "começar agora", you will initiate the download of a 4th torrent simultaneously, without changing your queuing rules (so, if you add a 5th torrent, it will wait until 2 torrents are finished). It allows you to bypass for a specific torrent the queuing rules you set.

**Comment by celestinoxp** [comment]
> 
Ok, then (start now  = " começar agora") should be changed to somehting like "start all" = "iniciar todos"
you agree?

**Comment by Yohmi** [comment]
I don't agree because this action really means "start now" (the "now" is key here as it's implying bypassing the queueing rules).
There might be a better wording for it (the french mac version says "_Reprendre la sélection sans attente_", if you like longwinded menu items haha 😛).
I can't comment on the portuguese translation as I don't speak portuguese.
