### ISSUE TITLE
Web UI hover text for torrent options is unreadable on dark mode

### ISSUE THREAD

**Issue by rcunov** [transmission/transmission#4983]
### What is the issue?

After right-clicking on a torrent to view the context menu, the text for items becomes unreadable when hovering over one with dark mode on the web UI. Here is a GIF of the issue:

![transmission-hover](https://user-images.githubusercontent.com/61329286/220487798-1602af9b-9947-4afb-8777-1879b8f333c5.gif)
---
The text is white on dark grey and the highlight color is white, so the white text on white background is invisible. The two options with the "context-menuitem warning" CSS class are fine since they change the foreground text to black and the highlight to red, but the "--color-bg-hover" seems to be wrong for the rest of the items. Changing the background hover color to \#666666 instead of the current value of \#f8f8f8 looks like:

![image](https://user-images.githubusercontent.com/61329286/220489681-7d0ddaa8-7c84-4bbe-8bd7-a1bae23358d0.png)
---
On a minor side note, the text gets bolded when a user hovers over the menu item and for the `Trash data and remove from list` option, the bold text increases the width of the context menu past the set value.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0

**Comment by GaryElshaw** [comment]
What browser and platform are you on @rcunov?

**Comment by rcunov** [comment]
I tried with both Edge and Firefox on both Windows 11 and Ubuntu 22.04 LTS. Running Transmission in Docker from the linuxserver.io image, I'll spin up a fresh VM and install without Docker to see if that's the issue.

**Comment by rcunov** [comment]
Just built from the 4.0.0 release on GitHub and tried it from there, issue still exists.

![image](https://user-images.githubusercontent.com/61329286/220523789-d3a1191a-1e76-40be-8656-8e1837a56ffc.png)

**Comment by GaryElshaw** [comment]
Thanks @rcunov,i've made a [pr](https://github.com/transmission/transmission/pull/4984) and will try to get this in for 4.0.1.
