### ISSUE TITLE
Batch adding tracker url on many torrents no longer possible with 4.

### ISSUE THREAD

**Issue by gpsfa** [transmission/transmission#4985]
### What is the issue?

You can filter torrents per tracker, select all torrents and go to torrent properties,
then select all tracker urls of all selected torrents and delete them, 
and on previous versions using add would add a new tracker url to all those torrents.

that was very useful eg for passkey changes, or easily reverting to http from https in case of issues, or changing tracker url for whatever reason.

Now you can still select all tracker urls from all selected torrents and delete them all at once,
but add only adds the new url to 1 torrent instead of all selected torrents.

And actually if you could implement edit to work on all selected torrents that'd be nice (that was never a thing, edit only worked for 1 torrent.)  Basically what could be done for that is edit function to disregard the old tracker urls, and just replace the whatever old values with the new url(s) added for all selected torrents.

![Screenshot (1876)](https://user-images.githubusercontent.com/62216841/220516926-1128287d-9e97-48e0-8354-57342ab5190f.png)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.0

**Comment by ilikepeaches** [comment]
Also an issue on the MacOS GUI client.

**Comment by killemov** [comment]
Related to #3226

**Comment by ckerr** [comment]
Yeah I agree, that was really handy.

**Comment by killemov** [comment]
@ckerr Maybe re-implement the same methods but with string references only?

**Comment by killemov** [comment]
Related to #642

**Comment by ckerr** [comment]
> @ckerr Maybe re-implement the same methods but with string references only?

That involves new API, so not possible in a patch release

**Comment by killemov** [comment]
That is some very strict thinking. Adding new stuff that does not break anything is OK.

**Comment by ckerr** [comment]
Transmission is following [semver](https://semver.org/#summary) and what you described

> Adding new stuff that does not break anything

is equivalent to semver minor:

> MINOR version when you add functionality in a backwards compatible manner

...so, no, not suitable for a patch release.

**Comment by killemov** [comment]
OK. Any ETA on 4.1.0?

**Comment by ckerr** [comment]
> OK. Any ETA on 4.1.0?

Sometime after 4.0.x :smile_cat:

**Comment by killemov** [comment]
Haha. This means I have to implement ALL variants in [Shift](https://github.com/killemov/Shift) because it supports all versions simultaneously,

**Comment by ckerr** [comment]
> Haha. This means I have to implement ALL variants in [Shift](https://github.com/killemov/Shift) because it supports all versions simultaneously,

I think we may be talking past each other?

No methods were removed from the spec in 4.0.0 so if something isn't working it's a bug and bugfixes are suitable for a bugfix release. What's _not_ suitable for a bugfix release is "re-implement[ing] the same methods but with string references only"

**Comment by killemov** [comment]
The scope is not just QT. AFAIK it's all of 'em.

> What's _not_ suitable for a bugfix release is "re-implement[ing] the same methods but with string references only"

Ah, currently `trackerAdd`, `trackerRemove` and `trackerReplace` are arguments for `set-torrent`, not methods. You could put in the documentation that for `trackerRemove` and `trackerReplace` the use of ids will become deprecated and be replaced with full strings. In code you could check for ids (numbers) first and then for full strings. So you could have them coexist for a while before phasing out the ids completely. Am I correct in that you just merged the non-borking form of adding trackers which doesn't stop when a duplicate is found?

**Comment by uralets** [comment]
Not sure I'm getting this right, but this isn't going to be fixed for GTK even in 4.x.x?
