### ISSUE TITLE
Transmission 4.0.0 interprets Ratio as relative to entire torrent, not just the downloaded part

### ISSUE THREAD

**Issue by robatino** [transmission/transmission#4991]
### What is the issue?

I finished downloading a large torrent where I already had most of it and only had to download a small fraction. When setting Ratio to 2, it's apparently interpreting that to mean relative to the entire torrent, not just what I downloaded. This worked prior to Transmission 4, so it's a regression. I'm using Fedora 37 with transmission-gtk-4.0.0-3.fc37.x86_64.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.0 (280ace12f8)

**Comment by ckerr** [comment]
Hey @robatino,

This is working as intended. The change came from https://github.com/transmission/transmission/pull/2424 to fix https://github.com/transmission/transmission/issues/276.

**Comment by robatino** [comment]
It would be helpful, then, to allow more than 2 decimal places when setting the Ratio. I can calculate the desired ratio relative to the entire torrent, but in my case 2 decimals isn't quite enough precision.

**Comment by killemov** [comment]
No, that would not be nice. Then you or the system has to make that decision for each torrent. The change is especially good for torrents that were "imported", meaning that the displayed ratio won't be insane when you only seed a torrent which you have not internally downloaded.

**Comment by robatino** [comment]
In my situation, I'm downloading a MAME torrent which is updated monthly. The updated part is on the order of 1% of the whole torrent, so it's mostly imported. Seeding to a ratio of 2 relative to the downloaded part means roughly a ratio of 0.02 relative to the entire torrent. It's always worked fine before, but now I have to manually calculate the ratio, and the GUI only allows 2 decimal places which is just barely enough to get roughly the desired ratio. At the very least there needs to be a few more decimals (and potentially an unlimited number depending on the size of the torrent compared to the updated part).

**Comment by killemov** [comment]
AFAIK, you can find bytes downloaded and uploaded somewhere and make your calculation from those values. Just curious, why is the ratio important in this case anyway? For me the metric has always been time uploading instead of bytes uploaded.
