### ISSUE TITLE
Compact rows in Web UI has too little info, too small a progressbar and speed text size, resulting in too much "eye travel" on a desktop browser

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#4994]
### What is the issue?

![compact](https://user-images.githubusercontent.com/49374058/220626072-d9dea74f-38f9-4506-a9c4-0e84155b6cc7.png)
I personally think the Web UI compact mode could scale better for a desktop browser. The current compact mode only really works for a narrow smartphone screen. Perhaps for desktop/tablet browsers, the Web UI compact mode could show more. For example:

1st, As you can see in the screenshot above, the "ETA and speed" text per torrent could be a lot bigger, especially when you compare it to the total speed text above. 

2nd, the progress bar is very tiny considering how much space there is in the row itself. It could be say, 4 times larger and a bit thicker so people can see it better and fill up the row more. 

3rd, there's a lot of "eye travel" that needs to be done when reading info in a compact row on a desktop browser. Look at all that empty yellow space between the title of the torrent and the download info. By making the info text and progress bar bigger, and maybe adding the rest of the info from the "non-compact view" like:

- "seeding to X of X peers"
-  the "total size" of the torrent 
- how much has been uploaded 
- ratio

would be useful and fill up more of that useless, empty space instead of making the user dart their eyes back and forth over all that empty space and instead read a steady line of information. 

Thoughts? I'd especially like to see what @GaryElshaw thinks

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.0-dev 9d1a141482

**Comment by GaryElshaw** [comment]
@Pentaphon I think there's some good, valid, and actionable points here, but also no obvious simple solutions. I'll get to that. Ironically i've spent a bit of time in the web client today, and have quite enjoyed what i think of as it's simple elegance (that kinda matches the aesthetic of what i was trying to do with the Qt client). 

During the day i go back and forth from a linux install on a 22" monitor to a macbook air 13" monitor. The website behaves itself on both platforms and on both monitors, but i do totally get it on the 22" monitor that there's a tendency to move my head from the far left of the screen to the far right in both the normal and compact modes. I ended up opening a separate browser window and resizing to half the screen size on the linux install which worked better for me, personally. 

I've designed web stuff for 'normal' and mobile devices, and the current compromise seems to be excellent, to me, but things can be improved of course. I'll try and find some time in the next few days to if some of your suggestions can be implemented. I think you're right about the up/down text size (for mobile and monitor), and the progress bar could do with an increase too, i think.

**Comment by Pentaphon** [comment]
> I ended up opening a separate browser window and resizing to half the screen size on the linux install which worked better for me, personally.

I was anticipating that and that is certainly somewhat of a solution at the moment, but I think most people these days prefer to have less windows on their screen and having a more readable compact row tab on their existing browser window would work better in general. As a person with at least 20 browser tabs open most of the time, opening another browser window seems...foreign to me. It would make more sense (to me) to install a 3rd party UI like transgui or tremotesf2, but if that can be avoided, I think people will prefer to stick to transmission's native UI. 

>I've designed web stuff for 'normal' and mobile devices, and the current compromise seems to be excellent, to me, but things can be improved of course. I'll try and find some time in the next few days to see if some of your suggestions can be implemented. I think you're right about the up/down text size (for mobile and monitor), and the progress bar could do with an increase too, i think.

Thanks! Whatever makes the current web UI more readable at a glance in the compact mode would be great!

**Comment by GaryElshaw** [comment]
When the old web interface existed, i'd regularly use https://github.com/johman10/flood-for-transmission

**Comment by Pentaphon** [comment]
> When the old web interface existed, i'd regularly use https://github.com/johman10/flood-for-transmission

Yeah, I've seen that before. It just seems a bit too "UI heavy" for my taste. I always preferred the lightweight, simple look of the native webUI (especially 4.0.0) and the 3rd party desktop UIs. 

Honestly, I do see that 3-pane UI coming to Transmission 5.0.0 or later but with a simple, lightweight feel. Especially considering this PR 

https://github.com/transmission/transmission/pull/4267

**Comment by ckerr** [comment]
Usually I close "omnibus" PRs as difficult to triage / manage but these first three items seem all about "how should compact mode look" so I'll leave this one open for some discussion.

To me, these suggestions feel like they're missing the point that compact layout is intended for compact display.  o/c if you stretch the window across a full screen it's going to look weird; making the progressbar thicker isn't going to change that.

So I'm _mostly_ against these items for compact mode but if there's some consensus on improvements I could be talked into it.

Item #4 seems like a different topic to the other three and lgtm. If it were split off into its own ticket I'd mark it `pr welcome` w/o needing any further discussion.

**Comment by Pentaphon** [comment]
> Item #4 seems like a different topic to the other three and lgtm. If it were split off into its own ticket I'd mark it `pr welcome` w/o needing any further discussion.

My apologies, @ckerr, I thought it would be ok to put everything into 1 issue since it's all about the compact mode functionality UI. 

I've split off the 4th item here: https://github.com/transmission/transmission/issues/5000

**Comment by Pentaphon** [comment]
>To me, these suggestions feel like they're missing the point that compact layout is intended for compact display. o/c if you stretch the window across a full screen it's going to look weird; making the progressbar thicker isn't going to change that.

I understand that, but many people use desktop browsers for the WebUI. There should be different display modes for desktop and mobile browsers. Perhaps the compact WebUI elements can automatically adapt to a widescreen desktop display in the following ways:

1) The compact layout is missing info that the original layout has. Just because a layout is compact doesn't mean it should be less useful.
2) The speed/info text in the compact layout could be a tad larger within the existing compact row and thus more readable. 
3) The progressbar could be a tad thicker to be closer to the size of what the speed/info text should be. 
4) The progress bar could be much longer to make the progressbar easier to see completion progress at a glance.
5) All of the above would reduce the vast "eye travel" gap when viewing a torrent in compact mode. Normal mode doesn't have this eye travel issue because all the info is bunched up together in one place in normal mode. 

I have faith that Gary will be able to come up with a very convincing mockup based on my feedback.

**Comment by GaryElshaw** [comment]
Before i pr anything, is this more in line with what you had in mind @Pentaphon? Are these acceptable changes to you, Charles?

![Untitled](https://user-images.githubusercontent.com/69029666/221103549-d7142630-5150-45a1-81e0-2ff6ddead325.png)

**Comment by ckerr** [comment]
I think I'd like to get feedback from the other UI-minded people.

I sort of like the way that the small progressbar in compact mode leaves room for really long torrent names, but maybe I'm in the minority on that.

**Comment by GaryElshaw** [comment]
Ha!Have you seen how much space is still there for titles!

**Comment by Pentaphon** [comment]
> Before i pr anything, is this more in line with what you had in mind @Pentaphon? Are these acceptable changes to you, Charles?

I would say:

1) The progressbar is too long. I would probably cut it in half. 
2) I would add all the info from the non-compact mode between the title and existing speed/status info, so that they are equally informative. 
3) Is there any way to only have this kind of compact mode for browser/tablet/widescreens? Leaving the mobile browser compact mode untouched to keep those people pleased? And just in case it's too big for compact mode on a mobile browser?

And then yeah, that would be pretty much what I had in mind. I thought compact mode just needed a few tweaks is all. I just didn't really like the massive amount of distance your eyes had to travel and I wanted minimize that.  There's no other way to make compact mode like that except to introduce a 3-pane UI

>I think I'd like to get feedback from the other UI-minded people.
>
>I sort of like the way that the small progressbar in compact mode leaves room for really long torrent names, but maybe I'm in the minority on that.

I am all for any kind of scrutiny on this. If other people come in to disagree and put a stop to any UI changes, so be it. 

I just wanted to improve compact mode, because on a desktop browser, it feels like a 2nd class citizen next to normal mode because its not as readable since the status/ratio/speed font was too small, the progressbar was TINY and it forces people to dart their eyes too much instead of a smooth, informative sweep on each column.

**Comment by diamondsw** [comment]
Since there was a call for UI-minded people - columns would work well specifically in compact view. It's kind of "Deluge-y", but a major advantage is the project can define the base set of information that's included (ideal for mobile, for instance) and the user can add what is important to them, resize it, reorder it, etc. It also gives a natural UI anchor for things like sorting, ascending/descending, etc. However, I also know that this is not traditionally how Transmission has worked, and would be a significant endeavor even if desired.

**Comment by Pentaphon** [comment]
> Since there was a call for UI-minded people - columns would work well specifically in compact view.

We could also have a "panel mode" for desktop/tablet browsers so more information can be seen at a glance by simply adding panels of information like torrent info, organizing torrents by tracker/labels/etc.

**Comment by Pentaphon** [comment]
>However, I also know that this is not traditionally how Transmission has worked, and would be a significant endeavor even if desired.

@diamondsw we could just stop using drop-in panels altogether and just always show a 2-panel UI to make the torrent list smaller but always show info/preferences/statistics/shortcuts on a widescreen desktop/laptop, but also keep the same overall UI on a tall phone display by only showing 1 panel at a time. 

@GaryElshaw what do you think about making desktop browsers always show a 2 panel UI? Much like the UI for "Kettu" shown below. 

![screenshot-1](https://github.com/transmission/transmission/assets/49374058/c553d1a3-d697-4980-8cfe-fa4b36bc513c)

**Comment by GaryElshaw** [comment]
I'm 50/50. I like it, but i also like an uncluttered interface.

**Comment by lucianmarin** [comment]
Also, the compact view is messed up on macOS in all 4.0.x versions, but on on 4.0.0.

**Comment by Pentaphon** [comment]
> Also, the compact view is messed up on macOS in all 4.0.x versions, but on on 4.0.0.

I believe there's some PRs that fix that in 4.0.4 or 4.1.0, plus this issue might need more discussion. Compact mode might need to go into a "panel" mode on desktop browsers in order to make it look more sensible than the current stretched out look. I think this is a long term issue that won't get resolved until 5.0.0 when somebody with more of a UI-focused mind redoes the WebUI entirely and hopefully, puts an end to stretched out compact mode in the process.

**Comment by ckerr** [comment]
fixed by ecb58e296674989a006c8eab7d2de8b4db68b104

**Comment by ckerr** [comment]
> 1st, As you can see in the screenshot above, the "ETA and speed" text per torrent could be a lot bigger, especially when you compare it to the total speed text above.
>
> 2nd, the progress bar is very tiny considering how much space there is in the row itself. It could be say, 4 times larger and a bit thicker so people can see it better and fill up the row more.

fixed by #5340
