### ISSUE TITLE
[RPC] Method "free-space" response argument fields differ in spec.

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#4997]
### What is the issue?

In the [RPC-spec](https://github.com/transmission/transmission/blob/a650060f3bcb044a3acb5572c927792cdea38d2e/docs/rpc-spec.md) a field `total_size` is mentioned as a return argument for the method `free-space`. In the protocol version summary a field `total-capacity` is mentioned.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0

**Comment by ckerr** [comment]
Looks like this was just a copyediting error in https://github.com/transmission/transmission/pull/1682. The protocol versions section is in error.
