### ISSUE TITLE
Build failure on Debian Sid

### ISSUE THREAD

**Issue by apexlir** [transmission/transmission#50]
When building master I ran into an issue when launching autogen.sh : 

22:12:10 + ./autogen.sh --prefix=/usr/local/transmission
22:12:10 creating libtransmission/version.h
22:12:12 m4/glib-gettext.m4:39: error: m4_copy: won't overwrite defined macro: glib_DEFUN
22:12:12 m4/glib-gettext.m4:39: the top level
22:12:12 autom4te: /usr/bin/m4 failed with exit status: 1
22:12:12 aclocal: error: echo failed with exit status: 1
22:12:12 autoreconf: aclocal failed with exit status: 1

It's fixed by adding the following line before autoreconf :
 
`rm m4/glib-gettext.m4 || die`

Inspired by https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c13b5e88c6e9c7bd2698d844cb5ed127ed809f7e

**Comment by mikedld** [comment]
Did you try using CMake for the build? I'd very much like to abandon autotools in the future, so you might as well try CMake now and report bugs for it instead (or at least in addition)...

**Comment by apexlir** [comment]
I just followed the README that say to use autogen for nightly build, I'm not familiar with CMAKE can please elaborate on how to use use it to build transmission ?

**Comment by mikedld** [comment]
Yeah, README needs to be updated at some point, but steps are mostly the same for any CMake-based project:

```console
$ git clone https://github.com/transmission/transmission
$ cd transmission
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/transmission -DCMAKE_BUILD_TYPE=Release
$ make install
```

This will try to detect what's possible to build automatically. You could also specify particular options explicitly, e.g. adding `-DENABLE_CLI=ON` (which is OFF by default) to `cmake` invocation. Full list of options is at the top of top-level [CMakeLists.txt](/transmission/transmission/blob/master/CMakeLists.txt) file; those could also be customized by running `ccmake .` (or Qt CMake GUI) in build directory after initial configuration.

**Comment by apexlir** [comment]
Thanks for the commands, it successfully builds with cmake, cool that we can customize with the flags !

cheers
