### ISSUE TITLE
upgrading to 4.0.1 forces verify local data

### ISSUE THREAD

**Issue by alananbari** [transmission/transmission#5004]
Never happened before for a simple upgrade, when _nothing else_ has changed (no new torrents added, just a version update): Every torrent is now **verifying local data**. This is absurd behavior and a massive waste of time! Why would this upgrade force verification? The upgrade to 4.0.0 did not do this. If every future upgrade forces this behavior, I will make sure only to upgrade when I have no or few pending up/downloading torrents. (Most of mine are large seeds currently.)

**Comment by jubalh** [comment]
This didn't happen on my side.

**Comment by bartekuk** [comment]
I've not seen that either but running remote seedboxes so might have not noticed, yet couple of seeding torrents started redownloading despite no change I raised #5007

**Comment by ckerr** [comment]
I haven't seen this happen myself so this is only an educated guess, but I _suspect_ this is the last ripple effect of a 4.0.0 issue that got fixed in 4.0.1.

@alananbari If you wait for the verification to finish, then exit and restart, does it force _another_ verification at that point?

**Comment by rotnemmoc** [comment]
Wow, 4.0.1 is clearly not stable, upon Transmission restarting after install it started undoing my groups and everything was either verifying local data or even worse; redownloading seeding torrents from my own drive. Then it manages to get worse as I'm scrambling to understand as the resume all button paused all downloads and now I need to restart them one by one because obviously resume all just pauses everything and now I've just noticed that on a small batch that I have restarted it's started to download from my old drive again. The UI is broken, the verify local data is broken, what else?

**Comment by Anuskuss** [comment]
I also had to verify most of my torrents. But the worst thing was that half of them were missing their data. I moved the files of one of those torrents with *Set data location*, and while it did move every single file correctly, it still couldn't verify.

**Comment by cybersteel8** [comment]
Wow yeah, this happened to me too. Loads of torrents are considered 0% and need a verify to recognise that they are completed and should be seeding. This is very unusual behaviour.

**Comment by bartekuk** [comment]
> I also had to verify most of my torrents. But the worst thing was that half of them were missing their data. I moved the files of one of those torrents with _Set data location_, and while it did move every single file correctly, it still couldn't verify.

Some of my magnet torrents also "lost" downloaded payload and data. I was able to restore them by downgrading and running verify see #5007

**Comment by alananbari** [comment]
> I also had to verify most of my torrents. But the worst thing was that half of them were missing their data. I moved the files of one of those torrents with _Set data location_, and while it did move every single file correctly, it still couldn't verify.

Same here, tried that too. This seems to be true of magnet links especially, no torrent data re-loads for some, so I can't verify (or do anything with them).

**Comment by maxz** [comment]
I also had to reverify all torrents and the ones added via magnet links had to refetch their metadata first, all when upgrading from 4.0 to 4.1. The active ones now finished their verification but there are still many left in paused state which need to fetch the metadata and verify the local files.

**Comment by maxz** [comment]
Ok, there is something extremely broken with the verification and 4.1. I'm not yet sure what it is. But I just downloaded a 2.31 GB torrent, then it got to 100% was moved to the directory for the completed torrents and when I reverified for good measure it went back to 50% and discarded a few 100 MB due to failed checksums.

Some torrents verify to 100%, others fail and don't even get to 5% although the files seem completely fine when I check them.

Just to throw some things out there. The directory for the incomplete torrents is uncompressed while the one for the complete torrents has filesystem compression enabled. So maybe it is connected to that somehow.
Apart from that I can't think of anything that would be causing this.

**Comment by ckerr** [comment]
Could someone take a look in Transmission's `torrents/` folder and report back whether they see files with the same infohash but a different suffix, e.g. `${infohash}.magnet` and `${infohash}.torrent`?

- on macOS you would look in `~/Library/Application Support/Tranmsission/torrents`
- on Windows you would look in `%USERPROFILE%\AppData\Local\Transmission\torrents` (I think)
- on Linux you could look in `~/.config/transmission/torrents`

**Comment by maxz** [comment]
Yes, such files exists in my `/var/lib/transmission/config/torrents/` which should be the equivalent directory in my configuration. From a quick look it seems like every single `.magnet` has a `.torrent` with the same hash.

**Comment by alananbari** [comment]
Yes, I have those on a Mac. However, after finding no solution to get some torrents to verify, I have downgraded to Transmission 3.0.0, so I can't be sure those files were present when using 4.0.1. Downgrading has allowed me to begin re-verification for the "stuck" magnet links without any further unexpected behavior.

**Comment by maxz** [comment]
I thought I had gotten my Transmission instance back into a sane state after some hangups and problems.

But after everything went through I restarted it and while the situation is not as bad as before, some torrents start their downloads anew unless I manually click verify on them.
I can't see any pattern WHY it is exactly those torrents. I tried to see if they were the ones with magnet links but that is not the case.

**Comment by ckerr** [comment]
I think this is the same as https://github.com/transmission/transmission/issues/5007 so I'm going to close this one.

Please check out that issue, especially [this comment](https://github.com/transmission/transmission/issues/5007#issuecomment-1442846354) which has a link to a test build that may fix this problem. If you give it a try, please LMK in 5007 how it went! :bow:

**Comment by Ramzzz666** [comment]
After the last update, I was very disappointed, having to verify every single one of my torrents, including all that were seeding and finished.

And even after rolling back the update to the before-last edition (Apple Time Machine), this continued to be the case.

Somewhere, a major bug must have been introduced.

**Comment by bartekuk** [comment]
@Ramzzz666 same here quite horrific two releases both gave me different issues so I started contributing to bug trucking which helps developers, I am going to devote some time helping testing future 4.x releases using one of my seedboxes but the main one I fixed at last stable 3.x release

> After the last update, I was very disappointed, having to verify every single one of my torrents, including all that were seeding and finished.
> And even after rolling back the update to the before-last edition (Apple Time Machine), this continued to be the case.
> Somewhere, a major bug must have been introduced.
