### ISSUE TITLE
Alt speed schedule time is not saved by web ui

### ISSUE THREAD

**Issue by bin101** [transmission/transmission#5009]
### What is the issue?

changing the start and end time does nothing currently.

### Which application of Transmission?

Web client

### Which version of Transmission?

bc34f77

**Comment by ckerr** [comment]
Hmm, when I look at it in devtools it looks like it's sending the right request, e.g.

```json
{
  "arguments": {
    "alt-speed-up": 49
  },
  "method": "session-set"
}
```

and gets a reasonable response from the server:

```json
{"arguments":{},"result":"success"}
```

@bin101 can you tell me more about the symptom that you're seeing? E.g. if you're comfortable using devtools, could you try repeating the same test as above? Or if none of that makes sense, then could you describe what symptoms you're seeing that makes  you say changing the alt speed doesn't work?

**Comment by bin101** [comment]
Strange I don't even see the request in devtools... But only for the schedule time settings. I can even disable/enable the schedular.

Do I need a special flag to rebuild the web code? I remember reading sth like this and strangely my first 4 rpc request are failing with a 409 and the https://example.com/transmission/web/transmission-app.js.map request fails with a 404, I cannot find the file either in the web dir.

I am using nginx as proxy but I cannot think of a way this should be a conflict. Nevertheless here my config:

```
server {
	listen 80;
	server_name example.com;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name example.com;

	set $upstream http://192.168.6.210:9091;

	location / {
		proxy_pass $upstream;
	}
}
```

I set my ssl settings inside the http block in the nginx.conf I excluded here the certificate lines.

```
# This file contains important security parameters. If you modify this file
# manually, Certbot will be unable to automatically provide future security
# updates. Instead, Certbot will print and log an error message with a path to
# the up-to-date file that you will need to refer to when manually updating
# this file.

ssl_session_cache shared:le_nginx_SSL:10m;
ssl_session_timeout 1440m;
ssl_session_tickets off;

ssl_protocols TLSv1.3 TLSv1.2;
ssl_prefer_server_ciphers off;

ssl_ciphers "ALL:!AES128:!CAMELLIA128:!CAMELLIA:!ARIA128:!RSA:!SEED:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK:!DHE-RSA-AES256:!ECDHE-RSA-AES256-SHA384:!DHE-RSA-AES256-SHA256:!ECDHE-RSA-AES256-SHA:!DHE-RSA-AES256-SHA:@STRENGTH";

```

**Comment by bin101** [comment]
@ckerr wait you modified the speed setting. I am talking about "alt-speed-time-begin" and "alt-speed-time-end". Speed is working fine for me.

**Comment by bin101** [comment]
My guess:

https://github.com/transmission/transmission/blob/c43ed9a8a15a2c303455fa0a2e081d3968520939/web/src/prefs-dialog.js#L797-L817

This doesn't filter by "select" tagName so the user change for dropdowns is not handled by an event listener but I am not a JS dev...

**Comment by ckerr** [comment]
Yep you're right. Nice catch @bin101 :bowing_man:

**Comment by bin101** [comment]
thanks for the PR ;) And if I am right this bug is already nearly 3 years old xD

**Comment by ckerr** [comment]
> And if I am right this bug is already nearly 3 years old xD

Wellllll people didn't start really using the new web client rewrite until 4.0.0 was released a couple of weeks ago, so depends on how you want to look at it.
