### ISSUE TITLE
Pop-up button of call script is cut at the bottom

### ISSUE THREAD

**Issue by decodism** [transmission/transmission#5010]
### What is the issue?

<img width="752" alt="transmission_1" src="https://user-images.githubusercontent.com/77468771/220936483-a0921fa8-f93d-49d7-a499-5f63a926d064.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
I don't understand what you're saying. Could you provide a screenshot?

What version of Transmission are you using, and which GUI (e.g. macOS, Qt, GTK, web)?

**Comment by nevack** [comment]
> Anyone want to make a patch for this? @GaryElshaw @sweetppro?

I think I can check this.
