### ISSUE TITLE
Color well of groups is cut at the top

### ISSUE THREAD

**Issue by decodism** [transmission/transmission#5011]
### What is the issue?

There is also a gray border on the inside.

<img width="752" alt="transmission_2" src="https://user-images.githubusercontent.com/77468771/220936210-b55a45a4-4a72-41d8-bbd1-a672d3647f56.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by nevack** [comment]
It's how Cocoa UI renders it, I don't see how this can be fixed.

But we can change style to more modern one at least for 13.0+
https://developer.apple.com/videos/play/wwdc2022/10074/?time=441

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/8330119/221018722-6815b9c7-3b9d-4eec-b151-443f0a5a0009.png">

**Comment by nevack** [comment]
> The gray border seems to be due to a bad color space. Maybe use sRGB?

I think this is a wrong guess, we use default colors and do not customise this control, so this should work out of the box.

**Comment by Coeur** [comment]
UI-wise: there is no regression in functionality, as there is a button to access the whole color wheel. So it's good.
