### ISSUE TITLE
"No such file or directory" error when adding magnet link via "transmission-remote -a"

### ISSUE THREAD

**Issue by fab0l1n** [transmission/transmission#5028]
I'm using the latest transmission container from linuxserver.io (lscr.io/linuxserver/transmission:latest, v. 4.0.1) and am getting a "No such file or dir" error when trying to add a magnet link as shown below.
However, the torrent is successfully added anyway. In the past it was not showing any errors.
I recently updated to the new version, but don't know my previous version; probably not older than 6 months.

```
root@cac8442065db:/# transmission-cli -V
transmission-cli 4.0.1 (e1c6e1be43)
root@cac8442065db:/# transmission-remote -V
transmission-remote 4.0.1 (e1c6e1be43)
root@cac8442065db:/# transmission-remote 9091 -a "magnet:?xt=urn:btih:AUewujaLSqvBoQ9OG3OlxXKLVCSsm3ZD0Owj559A&dn=AUewujaLSqvBoQ9OG3OlxXKLVCSsm3ZD0Owj559A&tr=https://ipleak.net/announce.php"
[2023-02-24 13:31:50.210] utils.cc:72: Couldn't read 'magnet:?xt=urn:btih:AUewujaLSqvBoQ9OG3OlxXKLVCSsm3ZD0Owj559A&dn=AUewujaLSqvBoQ9OG3OlxXKLVCSsm3ZD0Owj559A&tr=https://ipleak.net/announce.php': No such file or directory (2)
localhost:9091/transmission/rpc/ responded: success
```

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/commit/5ada8c46d4d9fc53a74a705bf022ae9c3b4d18fc
