### ISSUE TITLE
"Display a window when opening a magnet link" settings checkbox greyed out

### ISSUE THREAD

**Issue by kszumski45** [transmission/transmission#5034]
### What is the issue?

![Screenshot 2023-02-24 at 20 18 46](https://user-images.githubusercontent.com/9089496/221272307-5eb8ed55-485c-4f40-b8d6-3f947bfc03b1.png)

After updating to version 4 I can no longer disable this setting.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by nevack** [comment]
I know this is not intuitive right now, but this checkbox is toggleable only if you have "stable" download location.
Right now you have location set as "Same as torrent file", which is not "stable" location.

**Comment by nevack** [comment]
I don't know, what is better to do here.
1. Hide this checkbox if location is not stable.
2. Add tooltip/help text explaining why it is greyed out.

**Comment by nevack** [comment]
@kszumski45 /offtop but you can screenshot only window, if you press Space after Cmd+Shift+4 and select desired window

**Comment by kszumski45** [comment]
Thanks for help, it resolved my issue but somehow I feel more confused. Did behaviour was different on older version or default location setting changed during update? 
I think tooltip might be helpful or maybe instead of deactivating checkbox force user to select location when checking that option.

**Comment by ckerr** [comment]
> I don't know, what is better to do here.
> 
> 1. Hide this checkbox if location is not stable.
> 2. Add tooltip/help text explaining why it is greyed out.

Arguably tooltip, since that way the feature is more discoverable than if it's hidden?
