### ISSUE TITLE
4.0.0 removed keyboard shortcuts in web client

### ISSUE THREAD

**Issue by tessus** [transmission/transmission#5041]
### What is the issue?

In version 3, when I used remote access via the browser I was able to add a torrent/magent link by pressing `o` in the web UI.

Since v4 this is no longer possible. Now I always have to click on this icon: 
<img width="52" alt="image" src="https://user-images.githubusercontent.com/223439/221333125-ee347a37-d007-43f8-bc76-daef8a8fa499.png">

Any chance that we get that functionality back?

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.0 280ace12f8

**Comment by ckerr** [comment]
The keyboard shortcut values changed, but the shortcuts are still there. See the "Keyboard shortcuts" list in the Info section of the overflow menu.

**Comment by tessus** [comment]
Thanks for the info.

Unfortunately, they don't work either. I am running Transmission on Linux gtk, and I am using a macOS browser to access it remotely.

It shows me these shortvuts:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/223439/221338310-f257a164-6161-4827-8ed6-c97bcd3a257f.png">


I tried all keys `Control`, `Option`, `Command`, nothing worked. So this is no longer working. Previously I pressed `o` and that was it. Now, no matter what I try, it doesn't work.

**Comment by ckerr** [comment]
> and I am using a macOS browser to access it remotely.

This is being tracked in https://github.com/transmission/transmission/issues/4829, so you may want to check out that ticket and/or subscribe to it for updates.

**Comment by tessus** [comment]
Ah, thanks! Will do.

**Comment by ckerr** [comment]
Thanks for reporting it! I'd rather that a bug get too many reports than none :+1:

**Comment by tessus** [comment]
Yep, it was a bit confusing since `alt` usually translates to `option`, but I guess there's some issue with the keycodes.
