### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by jlholt** [transmission/transmission#5042]
I have version 2.94 for macOS (I'm using 13.2.1), saw the 4.0.1 update available and clicked [Install Update]. I then saw a download progress dialog that seems to have reported a successful download. Then I saw a dialog with the text Update Error! and below it the text "An error occurred while extracting the archive. Please try again later." and below that text a [Cancel Update] button. I tried later. Many times with the same result.

I searched here and found no existing issue.

I'm betting that the workaround is to download the image and install it as if it were not already installed.

BTW, I got the same behavior before I upgraded macOS from 13.1 (or thereabouts) to 13.2.1

**Comment by mikedld** [comment]
I believe the existing issue you're looking for is #600, which was fixed in 3.00.

**Comment by jlholt** [comment]
Hmm. I don't use github every day. I sense design-induced pilot error in the searching capabilities.

**Comment by mikedld** [comment]
I'm going to close this as a duplicate then. Manual update, as you figured, is the way to go.
