### ISSUE TITLE
GTK GUI is not created on Ubuntu

### ISSUE THREAD

**Issue by dabagab** [transmission/transmission#5051]
### What is the issue?

I downloaded the latest version 4.0.1. I am using Ubuntu 22.04 (updated)
I followed the install instructions (described in the Readme.md file), which created the following stuffs under the /usr/local/bin

- transmission-create
- transmission-daemon
- transmission-edit
- transmission-remote
- transmission-show

But there is nothing related to GTK GUI, can you please extend the documentation how to build and install the transmission with GTK GUI?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1

**Comment by fredo-47** [comment]
Does this help?
`sudo apt install libgtkmm-3.0-dev`

**Comment by dabagab** [comment]
Thanks it worked, I needed to use the `libgtkmm-4.0-dev `and `gettext` packages.
