### ISSUE TITLE
Version 4.0.1 problem - old torrent files appearing

### ISSUE THREAD

**Issue by smartarts1** [transmission/transmission#5053]
### What is the issue?

when I first installed the update I had about 200 old torrents appear

 - I had to delete them all and most are now gone (including stuff that was half downloaded!!)

but now every time I launch I get the same 7 (red) files - they were successfully downloaded a long time ago

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
@smartarts1 take a look in `/home/Yourname/Library/Application Support/Transmission/torrents`

There should be some torrents whose name is simply `${infohash}.torrent`

And there should be some older ones that are named like `${name}.${infohash.substr(0,16)}.torrent` and these may have older timestamps on them. These are _probably_ the ones that are reappearing.

For the seven that keep reappearing, could you check and see if they have that second naming scheme? And could you check to see what their file permissions are, e.g. are they read-only s.t. Transmission can't delete them?

**NB:** Please only share filenames or infohashes of public domain content.

**Comment by smartarts1** [comment]
ok that worked and the 7 are now gone

am I able to do a restore from time machine to restore the the ones that were downloading?
there were 20 or so that were partially downloaded but I deleted them all when the 100's appeared the first time I opened the new updated version

**Comment by ckerr** [comment]
@smartarts1 I'd like to find the pattern of what kept those 7 coming back. Did you have a chance to look at them to answer those questions above before you deleted them? :smile_cat:

**Comment by ckerr** [comment]
> am I able to do a restore from time machine to restore the the ones that were downloading?

My guess is yes but I have no idea. I only occasionally work on the macOS client.

**Comment by smartarts1** [comment]
<img width="780" alt="Screen Shot 2023-02-26 at 12 18 07 pm" src="https://user-images.githubusercontent.com/126360668/221387094-60d3cddf-6139-4f9a-8337-802b66da9158.png">

**Comment by smartarts1** [comment]
with using Time Machine
I did the restore and about 300 torrent appeared - seems there were lots of unfniished one
I am going to go thru them now and tyry to find the ones I need - thnanks for your help

**Comment by mythrowawayemail18** [comment]
Coming from the dupe...

I had that single file there. My user had read write but "everyone" had no access. The file was not locked. Deleting it resolved the issue.

This was a torrent from 7 years ago haha

**Comment by GaryElshaw** [comment]
@smartarts1 Please delete the image containing your, ahem, unlicensed material.

**Comment by smartarts1** [comment]
doh ! thanks for removing !

_____________________
Kind Regards,
Brett Stephenson

Smart Arts Marketing Pty Ltd
Lennox Head, NSW, Australia
Phone 02 6687 5140

Website Design, Hosting and E-Commerce
http://www.smartarts.com.au <http://www.smartarts.com.au/>

**Comment by gman-villa** [comment]
it crashes. where can I download v 4.0 ?

**Comment by ckerr** [comment]
@gman-villa from https://transmissionbt.com/

**Comment by AeroMaestro** [comment]
> @smartarts1 / @mythrowawayemail18 please take a look in `/home/Yourname/Library/Application Support/Transmission/torrents`
> 
> There should be some torrents whose name is simply `${infohash}.torrent`
> 
> And there should be some older ones that are named like `${name}.${infohash.substr(0,n)}.torrent` and these may have older timestamps on them. These are _probably_ the ones that are reappearing.
> 
> For the ones that keep reappearing:
> 
>     * could you check and see if they have that second naming scheme?
> 
>     * do they all have the same number of infohash characters in their name? (If so, how many?)
> 
>     * could you check to see what their file permissions are, e.g. are they read-only s.t. Transmission can't delete them?
> 
> 
> **NB: Please only share filenames or infohashes of public domain content.**

I started having this problem today on my MacOS Transmission Client.  (Ver. 4.0.1)
Found this thread.  Checked my application data and it's exactly as you describe.  My current (desired) torrents are all named as hashes and all the old files (some as old as 2014!) had filenames.  I deleted all the old ones with file names, quit the application and restarted it.  All good so far.  Thanks.

**Comment by bythewaybtw** [comment]
> @smartarts1 / @mythrowawayemail18 please take a look in `/home/Yourname/Library/Application Support/Transmission/torrents`
> 
> There should be some torrents whose name is simply `${infohash}.torrent`
> 
> And there should be some older ones that are named like `${name}.${infohash.substr(0,n)}.torrent` and these may have older timestamps on them. These are _probably_ the ones that are reappearing.
> 
> For the ones that keep reappearing:
> 
>     * could you check and see if they have that second naming scheme?
> 
>     * do they all have the same number of infohash characters in their name? (If so, how many?)
> 
>     * could you check to see what their file permissions are, e.g. are they read-only s.t. Transmission can't delete them?
> 
> 
> **NB: Please only share filenames or infohashes of public domain content.**

I never had this problem until I finally updated to 4.0.2 and now every time I load Transmission it resurrects the same 7 torrents, which are ones [both the torrent and finished files] I downloaded/cleared/completely deleted at least a year ago.

I did my due diligence and saw this post, so I searched Application Support only to find it devoid of a Transmission folder...

The strangest thing is that despite deleting all trackers from each torrent's list, and -- you know -- _not being able to find a single bit of data anywhere_ on my laptop, I can still hit **Resume** and they...just.._resume_.

**Comment by mythrowawayemail18** [comment]
Did you check your user application support folder or your system one?

**Comment by bythewaybtw** [comment]
The one referenced in @ckerr's instructions, hence why I quoted. Can't even find another Application Support folder, so: also literally the only one I could find.

**Comment by mythrowawayemail18** [comment]
Ignoring the snark..

macOS hides the user library folder by default, so the reason you likely
aren't seeing the Transmission folder is because you're looking in
Macintosh HD/Library instead of Macintosh HD/Users/<username>/Library

The fastest way to get there will be
- open a finder window
- click the go menu on the menu bar
- hold down the option key
- click the library option that now appears
- navigate to Application Support
- now you're in the correct location

**Comment by bythewaybtw** [comment]
If you were reading snark in that first one, that’s on you for projecting
insecurity.

I went — in the very first place — to the only Application Support folder
that either the Find function or Spotlight or manual searching via
Macintosh HD/USERS/USERNAME/Library, as you posted, which again — with
actual snark pointedly-included this time from my end [due to having to
repeat myself after you felt the need to repeat yourself because you
weren’t paying attention] — is the reason my initial reply quoted the exact
instructions…

…and voila: here we are, still.

Does anyone [literate] have any working ideas?

**Comment by mythrowawayemail18** [comment]
yeah I don't think you know what you're doing then lol...

**Comment by bythewaybtw** [comment]
“lol” you just keep digging with that logic, bud.
