### ISSUE TITLE
Qt: Wild discrepancy between upload rate and uploaded rate

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5057]
### What is the issue?

This is pretty wild. The most glaring bits happened before i could capture it. If you keep one eye on the upload rate, you'll notice the uploaded rate differs. At one point the upload rate was 14k/s and the uploaded rate was ticking over at 1m/s.

![Peek 2023-02-26 12-38](https://user-images.githubusercontent.com/69029666/221384567-d53f210b-c379-4e3e-a745-7483b6659e1c.gif)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1-dev (47fd150bab)

**Comment by ckerr** [comment]
@GaryElshaw A for effort but this isn't a great workflow for reporting bugs -- "this is pretty wild" + a 20s animation loop doesn't tell me much; I literally have to sit here and watch it and guess what you're seeing that you think is in error. Also if anyone else experiences this issue (whatever it is :laughing:) won't be able to find it by searching the issue tracker.

Please just describe it in detail in text.
