### ISSUE TITLE
2.92 fails to find 2.93 update?

### ISSUE THREAD

**Issue by gingerbeardman** [transmission/transmission#506]
![screen shot 2018-02-07 at 14 30 18](https://user-images.githubusercontent.com/49612/35921754-77e67258-0c13-11e8-8cb6-efe3fbb983d4.png)

**Comment by core-code** [comment]
very same here

**Comment by core-code** [comment]
the problem is this - the appcast contains this line:

      	sparkle:version="3c5870d4f5"

however this is different version format then previously and the sparkle version comparator sees "3c5870d4f5" as smaller than the previous bundle version "14714"
