### ISSUE TITLE
new version crashes at the start

### ISSUE THREAD

**Issue by gman-villa** [transmission/transmission#5068]
### What is the issue?

new version crashes at the start

where can I download v 4.0 for mac?

### Which application of Transmission?

None

**Comment by ckerr** [comment]
Hi @gman-villa, thanks for reporting this.

Please attach a crash report to this ticket so that we can try & figure out what went wrong.

**Comment by nevack** [comment]
Does it happen with 4.0.1?

> where can I download v 4.0 for mac?

For 4.0.0 - https://github.com/transmission/transmission/releases/download/4.0.0/Transmission-4.0.0.dmg
For 4.0.1 - https://github.com/transmission/transmission/releases/download/4.0.1/Transmission-4.0.1.dmg

**Comment by Coeur** [comment]
This issue isn't informative enough to take any action for it.
I'll reopen it once replied with a crash report.
Thank you for your understanding.

**Comment by ckerr** [comment]
@Coeur completely agree that this ticket is not actionable. OP's original description basically says "some version of Transmission, on some OS, crashes on startup".  :smile_cat: 

Closing an unresponsive issue after three days keeps kinda hasty though.

**Comment by ckerr** [comment]
Possibly related: https://github.com/transmission/transmission/issues/5077

**Comment by ckerr** [comment]
Re-closing (@Coeur :smile_cat:) due to lack of response & lack of actionable info.

If this is still happening for you in the nightlies or in 4.0.2 please open a new issue and include the crash report. Thank you!
