### ISSUE TITLE
Copyright says 2005-2016

### ISSUE THREAD

**Issue by gingerbeardman** [transmission/transmission#507]
![screen shot 2018-02-07 at 14 30 18](https://user-images.githubusercontent.com/49612/35921770-87f1b5cc-0c13-11e8-97dd-d144461fa5a0.png)

**Comment by gitlech** [comment]
Same for version 2.94
Copyright should be 2005-2018

**Comment by ckerr** [comment]
Fixed by df1cca9b573789634b182a5b98a8cc6382314643
