### ISSUE TITLE
macOS Dock Icon's Download and Upload Badges Reversed in Latest Version

### ISSUE THREAD

**Issue by ToniWonKanobi** [transmission/transmission#5071]
### What is the issue?

Is there a reason you guys switched the download and upload rate badges in the latest version? It's been download on the top and upload on the bottom since I started using Transmission in 2009 🤔 

<img width="73" alt="Screen Shot 2023-02-26 at 6 09 35 PM" src="https://user-images.githubusercontent.com/6640340/221455825-c8eef0c3-ba7a-487a-b5d4-597241fa2c02.png">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by GaryElshaw** [comment]
My thinking was that the old was completely illogical #4055

**Comment by ToniWonKanobi** [comment]
Hmm. I have two thoughts. Firstly, I disagree that it was illogical before. What's more important to most users when using Transmission most of the time? I would assume downloading, no? It should therefore be above upload. Second, when something has been a certain way for so long, changing it (even if it's agreeable that it's semantically better this new way) is abrasive and—dare I say—user hostile 😟 

Can we at least have a toggle or something in the preferences 🙏

**Comment by GaryElshaw** [comment]
> Hmm. I have two thoughts. Firstly, I disagree that it was illogical before.

Okay.

> What's more important to most users when using Transmission most of the time? I would assume downloading, no?

I would hope it was both, if they're not leeching.

> changing it (even if it's agreeable that it's semantically better this new way) is abrasive and—dare I say—user hostile

No hostility intended. Personally, i just think the old way was unintuitive and a pecliarity i hadn't seen in other applications that provide metrics like these.

> Can we at least have a toggle or something in the preferences

PR's are always welcome!

**Comment by ToniWonKanobi** [comment]
> PR's are always welcome!

I would do this, but I'm afraid I don't know how :/

**Comment by ckerr** [comment]
>> Can we at least have a toggle or something in the preferences

> PR's are always welcome!

No, not always.

@GaryElshaw if you're interested, give https://ometer.com/preferences.html a read. It _may_ change your point of view. Even if it doesn't, it will give you better insight into how I look at PRs when I decide whether or not to merge them :smile:

**Comment by ckerr** [comment]
IMO it is more sensible to have upload on top and download on bottom; it just semantically makes more sense to me. I don't think the current behavior is broken.

Just to brainstorm though -- maybe it would be clearer if the badge had the same up / down triangles that the Qt / GTK / web clients use? Would that make sense or be out-of-place in a macOS app's badge?

**Comment by GaryElshaw** [comment]
True. That's a good article, by the way. I didn't promise how or if pr's may be merged.

> maybe it would be clearer if the badge had the same up / down triangles

I think that's a good idea, but i'm not sure if it's necessary when placement and colour values indicate which is which.

**Comment by ToniWonKanobi** [comment]
> I don't think the current behavior is broken.

I don't think it's broken either! I just think that it's an abrupt change. And after being the complete opposite way for literally over a decade, it warrants at least a toggle somewhere.

Remember when Apple decided to reverse the scroll direction of their trackpads to better align with the movement of one's finger on iOS devices? ("[Natural scrolling](https://tedium.co/2021/12/29/natural-scrolling-history/).") Yes, it was probably a more "true" UI paradigm, but after having trackpads scroll the opposite way for so long, they allowed users to change it back to the old way via a checkbox in System Preferences.

**Comment by ToniWonKanobi** [comment]
lol okay ✌️

**Comment by ckerr** [comment]
@ToniWonKanobi maybe I was too terse there? I didn't mean to be rude :slightly_smiling_face: 

Basically I don't want to add a preferences checkbox for this for the reasons described in the link above, https://ometer.com/preferences.html. But if it could be made less confusing by adding a non-preference visual queue, I'd be in favor of that

**Comment by ToniWonKanobi** [comment]
No worries. I'm thankful version 3 still works. I'll just use that. (I prefer the the old app icon too.) Thanks for your attention. Have a good night!
