### ISSUE TITLE
feat: add direction arrows for download, upload rows in badge

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#5072]
### What is the issue?

As pointed out in https://github.com/transmission/transmission/issues/5071, users who have looked at the old badge for a decade could easily find the new badge order confusing, despite the color-coding that matches the main window's progressbars.

It would be nice to have another visual cue, using the ▲ and ▼direction arrows that are already used by the GTK / Qt / web clients.

Adding the "needs UI review" label since I'd like a 2nd (and 3rd) opinion on whether this would look right on macOS.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

**Comment by GaryElshaw** [comment]
I've expressed i think it is unnecessary, especially when there has only been one user express concern since 4 was released, and then it turns out that one user isn't using 4 anyway.

**Comment by mangosplat** [comment]
I think this is semi-necessary. Right now, when you are only seeding, the upload badge actually goes to the bottom of the app icon (where the download badge normally is). If you are green-blue colour blind there is no way to know what this badge is indicating (as the only indicator for this value is colour). Also, even if you're not colour-blind, I think it is misleading for a value you peak for can jump in place.

Either a directional arrow, or fixing the badges in place, are good solutions.

**Comment by ckerr** [comment]
> I've expressed i think it is unnecessary, especially when there has only been one user express concern since 4 was released, and then it turns out that one user isn't using 4 anyway.

Hidden as off-topic because I don't think this is a good-faith argument. That one user who expressed concern isn't using 4 *because* they prefer the old badge order.

**Comment by Coeur** [comment]
Since ▲ and ▼ are unicode characters, it's trivial to prepend or append those to the displayed strings.
I'm OK with that suggestion: myself I got confused when there is only a single line: "is it upload or download?". Because I can't always remember which color is for what.

**Comment by Coeur** [comment]
We'd probably want the most discreet arrow possible.
↑↓
▲▼
↾⇂
↿⇃
⇡⇣
⭡⭣
△▽
▴▾

**Comment by ckerr** [comment]
- My first choice is  ▲▼ because I like them and also for consistency with the other UIs

- `↿⇃` and `↑↓` should not be used because the up arrow looks too much like the digit `1`

- `⭡⭣` should not be used due to portability issues; they literally don't render for me. (Ubuntu 22.10,. Chrome 110)

- I'd be OK with any of the others.

**Comment by ckerr** [comment]
- My first choice is  ▲▼ because I like them for their visual clarity, and also because they're already used in the other UIs.  (But if we go with a different option, it's also easy to update the other UIs, so :man_shrugging:)

- `↿⇃` and `↑↓` should not be used because the up arrow looks too much like the digit `1`

- `⭡⭣` should not be used due to portability issues; they literally don't render for me. (Ubuntu 22.10,. Chrome 110)

- I'd be OK with any of the others.

**Comment by mangosplat** [comment]
I think if we align the triangles it could look pretty good

<img width="58" alt="image" src="https://user-images.githubusercontent.com/95374372/221739987-dcdef6ca-4660-44cf-8249-267e9d13ce94.png">

**Comment by Coeur** [comment]
Actually, for the macOS app, we already have a convention for up and down arrows:
![Capture d’écran 2023-03-01 à 03 47 40](https://user-images.githubusercontent.com/839992/221962992-9e62d55a-24e8-4282-837d-7cb37ffa6612.png)

So best to keep them.

**Comment by ckerr** [comment]
> Actually, for the macOS app, we already have a convention for up and down arrows: ![Capture d’écran 2023-03-01 à 03 47 40](https://user-images.githubusercontent.com/839992/221962992-9e62d55a-24e8-4282-837d-7cb37ffa6612.png)
> 
> They are the DownArrowTemplate and UpArrowTemplate images. So best to reuse them for the badge.

Ah good point. Okay, that is better than the triangles that I like then :)

**Comment by GaryElshaw** [comment]
> That one user who expressed concern isn't using 4 _because_ they prefer the old badge order.

...and icon.

1 user. I have no idea, but i hope someone has metrics of how many downloads of 4.0 and 4.0.1 there have been to establish the level of suffering caused.
