### ISSUE TITLE
Couldn't read magnet... FIle name too long (63)

### ISSUE THREAD

**Issue by canine-afficionado** [transmission/transmission#5073]
### What is the issue?

Whilst waiting for [a new Homebrew build](https://github.com/Homebrew/homebrew-core/pull/122688) I built my own transmission-remote on macOS (Monterey/Intel). When I add a magnet link using -a it does work but also gives the following error:
`[2023-02-27 14:16:46.928] utils.cc:76: Couldn't read 'magnet:?xt=urn:btih:[hash redacted]&dn=[name redacted]&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730&tr=udp%3A%2F%2F9.rarbg.to%3A2970&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13730&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790': File name too long (63)`

I didn't have this problem with version 3.

Note also the additional apostrophe before 'magnet' which I presume is a typo.

Thanks for everyone's hard work and reviving this project.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

transmission-remote 4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment]
@canine-afficionado IDK if you're comfortable with debuggers, but since you're doing your own builds it seems likely... could you run in a debugger and add `utils.cc:76` as a breakpoint so that you can get a backtrace  of what's trying to read the magnet link as a file?

**Comment by canine-afficionado** [comment]
Thanks for the quick response @ckerr I'm familiar with debuggers but haven't used C++ for about 20 years . Let me have a go at it and I'll let you know if I can figure it out.

**Comment by ckerr** [comment]
quick refresher:

```sh
$ gdb /path/to/transmission-remote
(gdb) handle SIGPIPE noprint nostop pass
(gdb) break utils.cc:76
(gdb) r
breakpoint 1 utils.cc:76 reached
(gdb) thread apply all bt
````

**Comment by Coeur** [comment]
> Note also the additional apostrophe before 'magnet' which I presume is a typo.

It is not. It's the string delimiter in this log. There is another apostrophe at the end of the magnet string, before "File name too long".

**Comment by canine-afficionado** [comment]
> 

Thanks @Coeur missed that.

Length of name (url encoded) is 78 characters.

**Comment by ckerr** [comment]
@canine-afficionado thank you, that's very helpful!

This was a less complex logic path than I expected:

```
  * frame #0: 0x000000010034f95b transmission-remote`tr_loadFile(filename="magnet:?xt=urn:btih:[hash redacted]&dn=[name redacted]&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2910&tr=udp%3A%2F%2F9.rarbg.to%3A2770&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13760&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14750", contents=size=0, error=0x0000000000000000) at utils.cc:77:28
    frame #1: 0x000000010002fc2c transmission-remote`getEncodedMetainfo(filename="magnet:?xt=urn:btih:[hash redacted]&dn=[name redacted]&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2910&tr=udp%3A%2F%2F9.rarbg.to%3A2770&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13760&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14750") at remote.cc:549:46
    frame #2: 0x0000000100004c53 transmission-remote`processArgs(rpcurl="localhost:9091/transmission/rpc/", argc=3, argv=0x00007ff7bfeff8e8, config=0x00007ff7bfeff5f8) at remote.cc:2501:38
    frame #3: 0x000000010000317f transmission-remote`main(argc=3, argv=0x00007ff7bfeff8e8) at remote.cc:3302:12
    frame #4: 0x00000001010dd52e dyld`start + 462
