### ISSUE TITLE
Tranmission unchokes uninterested peers

### ISSUE THREAD

**Issue by jech** [transmission/transmission#510]
Using a different client, i've noticed that Transmission peers unchoke me even though I'm not interested.  Not a big deal, but possibly wasteful on Transmission's side.

Sorry for not giving extra details, but this is behaviour noticed on remote peers.

**Comment by mikedld** [comment]
https://github.com/transmission/transmission/blob/96926a83373048a63caa75429669aa732f19fd4f/libtransmission/peer-mgr.c#L3302-L3306

**Comment by jech** [comment]
Clear, thanks.
