### ISSUE TITLE
add optional prefix to spinbox

### ISSUE THREAD

**Issue by Kljunas2** [transmission/transmission#5111]
### What is the issue?

In Slovenian, a phrase "n minutes ago" is translated as "pred n minutami". This is usually not a problem when localizing, but there is a spinbox ("Download is inactive if data sharing stopped: [n minute(s) ago]"), which can't be localized as easily. I've coded a [fix](https://github.com/transmission/transmission/commit/9a9e6de0d844b98482df055d1f22685d693a5e70), but I'm not sure whether my code is ok.
There is a problem, since the prefix wouldn't be used in most languages and empty string as original cannot be translated. I have written a hack, in which the original string is just an underscore, and the prefix is not set, if the string isn't changed in specific localization.
The picture below shows the desired look (30 is the spinbox value and acts as expected).
![2023-03-01T18:47:46,161630007+01:00](https://user-images.githubusercontent.com/17785580/222228540-bed215e6-6a02-4ef2-b063-066e8fb208ae.png)

Would I be able to PR? Otherwise I'm asking for some guidelines.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

**Comment by mikedld** [comment]
This was raised in Transifex before, the suggested solution being to move that part of the phrase to the label preceding the spinbox. The most friendly way would probably be to provide a string with a placeholder for translation, e.g. "%0 minute(s) ago", and then split translated phrase on the placeholder to get prefix and suffix for the spinbox ("" and "minute(s) ago" in this case).

**Comment by killemov** [comment]
So something like "${spinbox} minute(s) ago" ?
