### ISSUE TITLE
Transmission 4.0.x does not connect to IPv6 peers

### ISSUE THREAD

**Issue by kubrickfr** [transmission/transmission#5116]
### What is the issue?

Despite having a global unicast address assigned to one of my interfaces, and it being perfectly usable and working very well with previous versions of transmission, this new version just doesn't ever connect to any IPv6 peers.

"Bound to UDP IPv6 address [::]:1234" is the only mention of IPv6 in the logs

### Which application of Transmission?

None

**Comment by robd003** [comment]
Can you test with another client that only has IPv6 connectivity?

**Comment by kubrickfr** [comment]
Can't be bothered, I'm giving up on transmission.
