### ISSUE TITLE
Web UI Dark Mode Selection color is indistinguishable from row color

### ISSUE THREAD

**Issue by abhineetgupta** [transmission/transmission#5127]
### What is the issue?

In the WebUI for Transmission 4.0.1, the color of the row when selecting a torrent is indistinguishable from the color of the row. This makes it difficult to determine if or which rows are selected. 

It will be better to align these colors with other transmission clients, like the macos app.

In the screenshots below, top image shows original (unselected color), while bottom image has the row selected.
- Original row color - unselected
<img width="938" alt="Torrent row unselected" src="https://user-images.githubusercontent.com/15706629/222516340-1adbace2-5390-474a-99d4-622768a11c80.png">

- Row is selected
<img width="883" alt="Torrent row selected" src="https://user-images.githubusercontent.com/15706629/222518416-e50f0cab-a324-456a-9d69-f2a94a94f9cf.png">

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
CC @dareiff who's been tinkering in the neighborhood of this recently

**Comment by dareiff** [comment]
Will happily get this in!

**Comment by ckerr** [comment]
Fixed by #5151.
