### ISSUE TITLE
"Unrecognized colorspace number -1" errors in PiecesBar

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#5128]
### What is the issue?

This issue happens only when downloading is happening and Pieces Bar is enabled.
The logs get filled with:
>Transmission[22416:128333] Unrecognized colorspace number -1
>Transmission[22416:128333] Unknown number of components for colorspace model -1

The culprit seems to be in TorrentCell `drawPiecesBar:`, in our usage of `setColor:`:
https://github.com/transmission/transmission/blob/264437d6d9bba9b5d9b87176543f80135481624e/macosx/TorrentCell.mm#L695

I found three results on the net about that issue: [1](https://stackoverflow.com/questions/69828540/setcolor-on-nsbitmapimagerep-not-working-in-swift), [2](https://ifnotnil.com/t/nscolor-colorspace-etc/2043), [3](https://github.com/kmgrant/macterm/commit/a4a06d6f666ebddc30153c34cc7cf2afb6972d1b).

According to the third one, it can be a source of bad UI performances, although, I only experience about 1 spam log per second, so I'm not sure if the performance impact is huge.

### Which application of Transmission?

macOS app

### Which version of Transmission?

264437d6d9bba9b5d9b87176543f80135481624e

**Comment by ckerr** [comment]
> First, you're right: setColor has been broken at least since Catalina. Apple hasn't fixed it probably because it's so slow and inefficient, and nobody ever used it.

Yikes

**Comment by nevack** [comment]
>  I only experience about 1 spam log per second, so I'm not sure if the performance impact is huge.

AFAIK `updateUI` is called at the same rate.
