### ISSUE TITLE
can't add malformed magnet links to transmission-gtk 4.0.1. (Do we care?)

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#5131]
### What is the issue?

CC @mikedld 

To reproduce: Copy a magnet link, click "Open URL", hit OK.

Expected: The magnet link is added

Actual: It error out.

At [this point](https://github.com/transmission/transmission/blob/main/gtk/OptionsDialog.cc#L409) in the control flow, the magnet link still looks right: `magnet:?xt=urn:btih:...`

But by the time we go through [Session::Impl::add_from_url()](https://github.com/transmission/transmission/blob/main/gtk/Session.cc#L877) to get to [Session::Impl::add_file()](https://github.com/transmission/transmission/blob/main/gtk/Session.cc#L821) and extract the URI from `Glib::RefPtr<Gio::File>` the uri reads `magnet:///?xt=urn:btih:...` note the new slashes. This isn't valid formatting and appears to be added by Gio::File.

Not sure what The Right Thing is here. Seems like we could pass an array of `std::string` or `Glib::ustring` instead of `RefPtr<File>` to `Session::Impl::addFile()` but Mike you probably have a better idea than me if that would cause ripple effects.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
@mikedld do you have time to look at this before 4.0.2?

**Comment by sebastian-65** [comment]
I've downgraded to 3.00-6 now and when I click on magnet, Transmission window gets focused but nothing is added.

**Comment by ckerr** [comment]
> I've downgraded to 3.00-6 now and when I click on magnet, Transmission window gets focused but nothing is added.

3.x and 4.x are such different codebases that it probably doesn't make sense to dedicate bugfix time to 3.x :man_shrugging:

**Comment by ckerr** [comment]
@mikedld looks like a necessary prerequisite is to have an unescaped space in the `&dn=` display name part of the query. When you feed a misformatted magnet link into File > Open URL... this triggers the issue.

I'm not sure whether we should

- treat this as a bug to be fixed in Transmission
- or if it's something to be reported upstream
- or if we just want to close this as a tracker issue for generating invalid magnet links :smile_cat:

**Comment by mikedld** [comment]
If that link with unescaped space is handled by libtransmission when passed through as is, then I might be interested in improving it on GTK client side. Otherwise I don't care that much.
