### ISSUE TITLE
Incorrect display of the IPv6 address in the tracker list

### ISSUE THREAD

**Issue by svkirillov** [transmission/transmission#5148]
### What is the issue?

<img width="368" alt="Screenshot 2023-03-04 at 01 41 09" src="https://user-images.githubusercontent.com/33870726/222964619-8b7c9e87-6cfd-4a76-9782-ba17870a0823.png">

Steps to reproduce:
1. Select any torrent and open Inspector
2. Go to Trackers tab
3. Add new tracker with IPv6 address, e.g. `http://[2001:0db8:11a3:09d7:1f34:8a2e:07a0:765d]:8080/announce` (actually not a tracker, just a random IPv6 address)
4. See the result

The same with any IPv6 address, e.g.

- `http://::1/announce`
- `http://[::1]:8080/announce`
- `http://2001:0db8:11a3:09d7:1f34:8a2e:07a0:765d/announce`

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment]
Looks like this is a bug in the value of `tr_url_parsed_t.host` when `tr_urlParse()` is passed a URL that contains a IPv6 address
