### ISSUE TITLE
Inspector needs better placeholder values until real values have been fetched

### ISSUE THREAD

**Issue by winbatch** [transmission/transmission#5150]
### What is the issue?

![image](https://user-images.githubusercontent.com/2419795/222973275-25b39f4c-88fe-439c-a88a-b9198e9670b2.png)

Then a second later it fixes itself and shows regular numbers.  This happens with multiple files.

![image](https://user-images.githubusercontent.com/2419795/222973488-e8bcceaf-9eff-499f-8b46-eba15b00543b.png)

### Which application of Transmission?

None

### Which version of Transmission?

Transmission 4.0.1 e1c6e1be43

**Comment by killemov** [comment]
It shows some placeholder data before the actual data comes in. The alternative could be showing nothing or not opening the tab before the data is in. Or would you rather have a rotating buffering animation? My personal advice would be to do nothing about this or give it a very low priority.

**Comment by winbatch** [comment]
It reads more like an error than place holder. Place holder would be
‘calculating…’

**Comment by killemov** [comment]
Sure, also nice options.

**Comment by dareiff** [comment]
Feel free to assign to me. Did a first pass that adds 'loading...' or 0% in spots where E2BIG or NaN could be presented. Might change the formatter logic instead, though, if people have opinions.

**Comment by mikedld** [comment]
GTK and Qt clients are using `…` as initial label text before the actual value is loaded. It's short and also marked as not requiring translation which is a tiny bonus.

**Comment by ckerr** [comment]
@dareiff if you PR this I'll put it in 4.0.3

**Comment by GaryElshaw** [comment]
> ..if people have opinions.

Not so much an opinion, but a suggestion of making it '95%' if this is a placeholder that's near to immediately done.

**Comment by dareiff** [comment]
I do have one ready to go, but I'd like to give it another test before I PR — it's been a week since I've looked. (It's pretty darn simple, though.)

**Comment by GaryElshaw** [comment]
Nothing wrong with simple :-)
