### ISSUE TITLE
download interest strategy can make slow swarms much slower

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#5165]
### What is the issue?

1. _(minor)_ The function `rechokeDownloads()` is confusingly named. It doesn't rechoke anything; it decides which peers to be interested in.

2. _(major)_ The function has some well-intended but misdirected code that tries to sniff out whether we're hitting our bandwidth limits by seeing how many cancels we've sent to any peer in the swarm lately. Unfortunately when we are in a swarm with many slow peers this can cause a negative loop: we send out too many cancels because peers are slow, which causes us to reduce how many peers we'll download from, so now instead of downloading from N slow peers we're downloading from N/2 or N/3 slow peers, and things slow to a crawl. After a little while the "cancels" age our of our recent history so the code marks more peers as interested again and the cycle begins again.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by killemov** [comment]
Could this also be related to torrents being 99.9% complete but won't finish? (They need to be removed/re-added/continued or the client needs to be restarted.)

**Disclaimer: I have VERY limited knowledge of the BitTorrent protocol and the request strategy of Transmission.**

I assume "cancel" implies sending cancel requests to all peers to which an earlier request for a single piece was made. I also assume a request for a single piece is sent out to a limited number of peers.
Why send a cancel message at all? Maybe taking the hit of using more bandwidth is worth it.
Obviously the piece size is a factor. So for piece size <= packet size  (64k?) never send cancel requests. And taper off peers with a factor related to piece size.
Are requests distributed round-robin over a limited number of peers? Or are they rather scattered over all connected peers that have said requested piece?

**Comment by ckerr** [comment]
That's a whole lot of interesting discussion that we should have in another thread :)
