### ISSUE TITLE
feat: sequential file download

### ISSUE THREAD

**Issue by OmlineEditor** [transmission/transmission#5169]
### What is the issue?

Please add an option for downloadable torrents for sequential data download.
Now the data is loaded in a random and random way.

Because of this, if there are several video files in the torrent (for example, a series of 10 episodes), you cannot start watching the first series if all 10 episodes are not downloaded, because the first series will be 90% downloaded like all other series.

If you make the download sequentially, the first file from the torrent will be downloaded at 100% first, then the second file will start downloading at 100%, etc. this will reduce the wait before viewing and working with files. This is a very useful feature that is already implemented in other clients.

### Which application of Transmission?

None

### Which version of Transmission?

2.94

**Comment by valcomm** [comment]
Have you tried assigning first episodes a higher priority and last ones a lower priority?
```
 -ph  --priority-high          <files>            Try to download these file(s)
                                                  first
 -pn  --priority-normal        <files>            Try to download these file(s)
                                                  normally
 -pl  --priority-low           <files>            Try to download these file(s)
                                                  last
```

**Comment by OmlineEditor** [comment]
> Have you tried assigning first episodes a higher priority and last ones a lower priority?

This method works provided that there are few files, but if there are a lot of them, it is very inconvenient. In a simple series where 10 episodes need to constantly change priorities and keep track of what is downloaded and what is not. In other programs, this is done simply by specifying the "Download sequentially" parameter

**Comment by OmlineEditor** [comment]
> Unfortunately, logically consecutive files are not guaranteed to be placed consecutively in a torrent. Thus priority based on sorting by filename might be more reliable. Sure, if messing with files order happens rare enough, this may be ignored.

you're right, we need to check and upload in alphabetical order of the file name
