### ISSUE TITLE
Swift rewrite

### ISSUE THREAD

**Issue by DevilDimon** [transmission/transmission#517]
Is there any chance for Transmission to be rewritten in Swift? Now that we have 10.9 as the minimal supported version, any Transmission user can run Swift. Rewriting would certainly force us to finally update some obsolete parts of the code (e.g. ivars), making the codebase more succinct and clear in the process. Swift code is also known to run quicker due to direct dispatch and various smart compiler optimisations.
The syntax of Swift is now pretty stable to use it in a project of this size. If we delay conversion, it can scare off potential contributors who only know Swift from the very beginning. A lot of the larger macOS open-source projects are already in Swift or are in the process of transition (over 35% of native apps in awesome-macOS are in Swift).

**Comment by ckerr** [comment]
Not likely to happen. Swift is great, but Transmission's team does not have enough bandwidth to undertake a full-on rewrite like this.

**Comment by gingerbeardman** [comment]
> Swift code is also known to run quicker due to direct dispatch and various smart compiler optimisations.

I'm interested to see this numbers, can you share any?
