### ISSUE TITLE
Icons not installed with qt enabled and gtk disabled

### ISSUE THREAD

**Issue by floppym** [transmission/transmission#5173]
### What is the issue?

Configuring transmission with `-DENABLE_QT=ON` and `-DENABLE_GTK=OFF` results in transmission.svg not being installed.

This causes the application launcher (transmission-qt.desktop) to show up without an icon.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1

**Comment by GaryElshaw** [comment]
@ckerr This might solve the mystery of why pacman on Arch is doing what it's doing #5142

**Comment by ckerr** [comment]
@mikedld ^

**Comment by ckerr** [comment]
Confirmed.  [Here](https://github.com/transmission/transmission/blob/e1c6e1be43ff7d3bf69a4c6f9468f8c19d6c6c01/gtk/CMakeLists.txt#L211
) is the code that installs icons when the GTK client is enabled. There's nothing similar in [qt/CmakeLists](https://github.com/transmission/transmission/blob/e1c6e1be43ff7d3bf69a4c6f9468f8c19d6c6c01/qt/CMakeLists.txt).

**Comment by floppym** [comment]
Would it make sense to move the icons to a common source directory that can be shared by both the gtk and qt clients? 

Currently the qt directory contains an older set of icons than gtk; gtk had its icons updated in #1141.
