### ISSUE TITLE
zh_TW translation is missing?

### ISSUE THREAD

**Issue by eight04** [transmission/transmission#5189]
### What is the issue?

After installing v4.0.1, the UI language changed from zh_TW to ja. It seems that a translation file is missing:
```
C:\Program Files\Transmission\translations\transmission_zh_TW.qm
```

Currently I use a batch file to make transmission start in en.
```
pushd C:\Program Files\Transmission
set LANG=en
start transmission-qt
```

P.S. When zh_TW is not available, it should be better to fallback to zh_CN instead of ja.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.1 (e1c6e1)

**Comment by ckerr** [comment]
CC @mikedld

**Comment by mikedld** [comment]
I don't see how `zh_TW` could fallback to `ja`, it's more likely that you have Japanese selected somewhere in your system preferences. What was the previous version that you updated from where it worked?

I see that `zh_TW` is not (and never was) listed in `LINGUAS` list in qt/CMakeLists.txt, so I don't think it was ever installed (despite being first exported in 32add75f0e48ca4dd2c4182424ca546ff7001a98 back in 2020).

**Comment by eight04** [comment]
> I don't see how `zh_TW` could fallback to `ja`, it's more likely that you have Japanese selected somewhere in your system preferences.

That makes sense. I do have ja as the second language in Windows 10 setting:
![image](https://user-images.githubusercontent.com/1324510/224365038-5a665a2d-ed5a-467c-8ca3-af32da8bf475.png)
But it is only for IME.

> What was the previous version that you updated from where it worked?

The previous version should be v3.0. However, I'm not really sure if it was displayed in zh_TW. Maybe it was displayed in en?

Should I downgrade to 3.0 to test? Will I lose my download progress?

**Comment by mikedld** [comment]
Japanese was added in d1d27ae35f0d8d7602dbf16b06d653e2d956fa78 so 3.00 already included it, and there were no changes to translations loading logic between 3.00 and 4.0.0, so still not sure. Anyway, I'm going to make sure all translations currently in git are installed, including zh_TW.
