### ISSUE TITLE
Fix didn't migrated to release 2.93

### ISSUE THREAD

**Issue by SignFinder** [transmission/transmission#519]
This bug was fixed in nightly builds, but still exists in release 2.93.
https://github.com/transmission/transmission/issues/236

**Comment by slokhorst** [comment]
As you can see in the issue, the fix is planned for [milestone 3.00](https://github.com/transmission/transmission/milestone/2). So it is intended not to be in 2.93.

**Comment by SignFinder** [comment]
Thanks for the answer. It is a bit strange for me when the fix for bug exists, but future releases are issuing without fix.
