### ISSUE TITLE
Unable to add more than one blocklist anymore on Transmission 4 MacOS

### ISSUE THREAD

**Issue by Javihache** [transmission/transmission#5198]
### What is the issue?

It used to be possible to have several blocklists as .bin files in the Application Support/Transmission/blocklists folder. That doesn't work anymore.

### Which application of Transmission?

MacOS Transmission App

### Which version of Transmission?

4

**Comment by ckerr** [comment]
It's working for me. Can you write up a recipe for me?

How I tested:

```sh
$ cd blockslists/
$ ls -1
blocklist-1.txt
blocklist-2.txt
$ wc --lines *txt
  7 blocklist-1.txt
  4 blocklist-2.txt
 11 total
```

and then after starting Transmission, which says "Blocklist has 11 entries"

```sh
$ ls -1
blocklist-1.txt
blocklist-1.txt.bin
blocklist-2.txt
blocklist-2.txt.bin
```

**Comment by Javihache** [comment]
Sorry, clicked close too fast. It actually works, but previously used to work only with the .bin files. Now the text files are necessary. I also added "blocklist" at the end of the name of each list and it works. Thanks!

**Comment by ckerr** [comment]
@Javihache I'm confused though -- if it works, what remaining action is needed? i.e. why did you re-open the ticket?

**Comment by ckerr** [comment]
Closing due to lack of response and lack of actionable info. If any further action needs to happen, please open a new ticket. Thanks!
