### ISSUE TITLE
"Cannot connect to tracker" after adding a new torrent, propagates to all seeded torrents after a while

### ISSUE THREAD

**Issue by Maxr1998** [transmission/transmission#5199]
### What is the issue?

Since upgrading transmission-daemon to version 4 on Arch Linux, I regularly have the issue that when adding a new torrent, it not only fails connecting to the tracker for that torrent, but also later re-announcements of other torrents (on various trackers) will fail. Restarting transmission-daemon fixes this issue until adding another new torrent. I've successfully reproduced this with a [Fedora Workstation torrent](https://torrent.fedoraproject.org/torrents/Fedora-Workstation-Live-x86_64-37.torrent) as well as a few other ones. Interestingly, one another machine that's also on Arch Linux, I couldn't reproduce this in transmission-gtk, however this was a fresh installation.
For what it's worth, looking at the network traffic with `tcpdump`, I can see the requests to the tracker server and (successful?) responses.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by Maxr1998** [comment]
Apparently, this even happens when adding paused torrents. After adding a new torrent without starting it, all other torrents will fail to announce when they're next due.

**Comment by Maxr1998** [comment]
I further traced this down to only happening when adding a torrent from a URL. It doesn't happen when first downloading the torrent and then adding it through the CLI.

**Comment by rsekman** [comment]
I think I have also had this occur, and indeed also when adding a torrent from an URL. It seemed to only propagate to other torrents on the same tracker. Restarting the daemon resolved it.

**Comment by Maxr1998** [comment]
I wonder how common this issue is and if it is specific to my installation/setup.
The regular daemon restarts have been getting a bit annoying, so I'd love to find out how I could fix and resolve it.

My Transmission instance is running on Arch in a systemd-nspawn container, which could be the cause of these issues. The host OS is Ubuntu 22.04, but that shouldn't have too much impact.
It might, however, be that the slightly complex networking setup makes the HTTP connections fail. It's slightly odd that this didn't happen on Transmission 3.00 though and how it's only provoked by adding torrents from URL.

**Comment by tearfur** [comment]
Can confirm. Used `transmission-remote -a https://torrent.fedoraproject.org/torrents/Fedora-Workstation-Live-x86_64-37.torrent` to add the torrent.

**Comment by tearfur** [comment]
Cannot reproduce with Debian torrent: `transmission-remote -a https://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/debian-12.1.0-amd64-DVD-1.iso.torrent -b`.

This is probably just some sort of anti-DDoS measures at Fedora's tracker. We are sending multiple requests in quick succession to `torrent.fedoraproject.org` after all.

@Maxr1998 @rsekman It'd be great if you can help try the Debian torrents as well.

**Comment by Maxr1998** [comment]
I'm not sure it is an anti-DDoS measure. Fedora was just one public example, I've had this happen with other trackers as well. For those, it didn't happen on Transmission 3, and it started after upgrading to 4. It's very unlikely that those trackers (some of which haven't been updated in years) rolled out anything new at the same time.

I'll try to reproduce with the debian torrent later.

**Comment by tearfur** [comment]
OK, I think I've got a lead on what's happening here.

@Maxr1998 Does your private tracker use the same hostname for hosting the torrent file and tracker? If yes, then this is probably also what happened during your test.

### Hypothesis

There are 2 criteria for this problem to happen (both are true for the Fedora torrent):
1. The torrent download server is on HTTPS, while the tracker is on HTTP.
2. The torrent download server and tracker has the same hostname.

Transmission uses curl both for downloading torrent files and making tracker announcements. What may be happening is:
1. After downloading the torrent file via HTTPS, curl remembers that `torrent.fedoraproject.org` can use HTTPS.
2. curl *mistakenly* tries to announce using HTTPS as well (why? I don't know yet).
3. The tracker does not know what the TLS handshake means, ignores it, then the connection eventually times out.

### Evidence

#### Adding Fedora torrent by URL

Notice after curl sending the TLS handshake, the connection times out 45 seconds later and curl sends a TCP FIN. The annoucement itself was not sent at all.

![image](https://github.com/transmission/transmission/assets/46261767/0d8cf412-2c77-4ccd-84d7-929bfeb1e83f)

#### Adding Fedora torrent by file

curl does not try any TLS handshakes, and the annoucement succeeds.

![image](https://github.com/transmission/transmission/assets/46261767/0f6f1c8a-1966-4195-867b-421e884be233)

P.S. Seems like the Fedora tracker still does not like BEP-7 🤡

**Comment by tearfur** [comment]
Meanwhile for the debian torrent, the web server that hosts the torrent file and the tracker has a different hostname. So both cases works as expected.

#### Adding Debian torrent by URL

![image](https://github.com/transmission/transmission/assets/46261767/3b167587-a595-4edd-a8a7-501d29e6fefd)

#### Adding Debian torrent by file

![image](https://github.com/transmission/transmission/assets/46261767/a1c38c90-e607-4ab8-ba5c-27153961fa29)

**Comment by Maxr1998** [comment]
> There are 2 criteria for this problem to happen (both are true for the Fedora torrent):
> 1. The torrent download server is on HTTPS, while the tracker is on HTTP.
> 2. The torrent download server and tracker has the same hostname.

Both 1. & 2. are fulfilled for the tracker I use.


> Transmission uses curl both for downloading torrent files and making tracker announcements. What may be happening is:
> 1. After downloading the torrent file via HTTPS, curl takes a note to self that `torrent.fedoraproject.org` can use HTTPS.
> 2. curl *mistakenly* tries to announce using HTTPS as well (why? I don't know yet).
> 3. The tracker does not know what the TLS handshake means, ignores it, then the connection eventually times out.

I believe that is correct. When debugging with `mitmproxy` the other day, I struggled with getting the CA to work. So, since I saw that the tracker uses HTTP anyways, and only the HTTPS torrent download was causing issues, I simply added the torrent from a HTTP link instead of the provided HTTPS link.
I was a tad surprised that I didn't see any error message but thought it had to do with mitmproxy, but reading your explanation now everything makes sense.

**Comment by tearfur** [comment]
Found a workaround, but I'm not happy with it:

```patch
diff --git a/libtransmission/web.cc b/libtransmission/web.cc
index 2d8cde154..bccf4d055 100644
--- a/libtransmission/web.cc
+++ b/libtransmission/web.cc
@@ -510,7 +510,6 @@ public:
         TR_ASSERT(std::this_thread::get_id() == curl_thread->get_id());
         auto* const e = task.easy();

-        (void)curl_easy_setopt(e, CURLOPT_SHARE, shared());
         (void)curl_easy_setopt(e, CURLOPT_DNS_CACHE_TIMEOUT, DnsCacheTimeoutSecs);
         (void)curl_easy_setopt(e, CURLOPT_AUTOREFERER, 1L);
         (void)curl_easy_setopt(e, CURLOPT_ACCEPT_ENCODING, "");
```

This does not work, and it is confusing me:

```patch
diff --git a/libtransmission/web.cc b/libtransmission/web.cc
index 2d8cde154..239eacde8 100644
--- a/libtransmission/web.cc
+++ b/libtransmission/web.cc
@@ -781,6 +781,12 @@ public:
                 return;
             }
         }
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_SSL_SESSION);
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_CONNECT);
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_HSTS);
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_COOKIE);
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_DNS);
+        curl_share_setopt(sh, CURLSHOPT_UNSHARE, CURL_LOCK_DATA_PSL);
     }

     std::map<CURL*, uint64_t /*tr_time_msec()*/> paused_easy_handles;
```

**Comment by ckerr** [comment]
The main reason for the curl sharing is https://github.com/transmission/transmission/issues/1815, to prevent excessive DNS lookups.

If @tearfur's idea is correct, maybe we could modify the `shareEverything()` initializer in web.cc to only share `CURL_LOCK_DATA_DNS` and `CURL_LOCK_DATA_PSL` :thinking:

**Comment by tearfur** [comment]
@ckerr The thing is, I've already tried unsharing everything listed in https://curl.se/libcurl/c/CURLSHOPT_UNSHARE.html, and the problem still occurs.

I'm confused.

**Comment by tearfur** [comment]
Well, I just wrote a small program to test libcurl. Seems like having a HTTPS and HTTP server on the same hostname alone does not trigger the bug...

<details>
<summary>Test program</summary>

```cpp
#include <cstddef>
#include <iostream>

#include <curl/curl.h>

constexpr size_t write_data(void* /*buffer*/, size_t size, size_t nmemb, void* /*userp*/)
{
    return size * nmemb;
}

void common_setopt(CURL* const handle, CURLSH* const shared)
{
    curl_easy_setopt(handle, CURLOPT_SHARE, shared);
    curl_easy_setopt(handle, CURLOPT_WRITEFUNCTION, write_data);
    curl_easy_setopt(handle, CURLOPT_TIMEOUT, 45L);
    curl_easy_setopt(handle, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(handle, CURLOPT_SSL_VERIFYPEER, 0L);
}

void perform(CURL* const handle, char const* const str)
{
    auto req_bytes_sent = long{};
    auto status = long{};
    auto content_type = (char*){};
    curl_easy_perform(handle);
    curl_easy_getinfo(handle, CURLINFO_RESPONSE_CODE, &status);
    curl_easy_getinfo(handle, CURLINFO_REQUEST_SIZE, &req_bytes_sent);
    curl_easy_getinfo(handle, CURLINFO_CONTENT_TYPE, &content_type);
    if (status > 0 || req_bytes_sent > 0)
    {
        std::cout << str << " connected (HTTP " << status << ')';
        if (content_type != nullptr)
            std::cout  << "(" << content_type << ')';
        std::cout << std::endl;
    }
    else
        std::cout << str << " did not connect" << std::endl;
}

int main()
{
    CURLSH* const shared = curl_share_init();
    for (long type = CURL_LOCK_DATA_COOKIE;; ++type)
    {
        if (curl_share_setopt(shared, CURLSHOPT_SHARE, type) != CURLSHE_OK)
            break;
    }

    CURL* const handle = curl_easy_init();
    curl_easy_setopt(handle, CURLOPT_URL, "https://captive.apple.com");
    common_setopt(handle, shared);
    perform(handle, "https");

    curl_easy_reset(handle);

    curl_easy_setopt(handle, CURLOPT_URL, "http://captive.apple.com");
    common_setopt(handle, shared);
    perform(handle, "http");

    curl_easy_cleanup(handle);
    curl_share_cleanup(shared);

    return 0;
}
```
</details>

**Comment by rsekman** [comment]
Did you look at the actual packets sent and received? Maybe the Apple server is smarter than the Fedora tracker. The issue seems to be, like you said, that the Fedora tracker doesn't understand the TLS handshake and ignores it. Maybe the Apple server sees it and thinks "I was expecting HTTP, but I know how to speak HTTPS, too, this isn't a problem".

**Comment by Maxr1998** [comment]
Yeah, it must be a server-side issue as well. I just tested @tearfur's program (thanks!) with the URLs from the tracker and got the expected result:

```
https connected (HTTP 200)(text/html)
http did not connect
```

Analyzing the request/response with HTTP Toolkit, I can see that cURL indeed changes the second request to use https, which fails with the following response:
```
The connection failed before a response could be completed with error:

Upstream connection error: write EPROTO 140380004616064:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**Comment by tearfur** [comment]
> Did you look at the actual packets sent and received?

@rsekman Yes I did.

> For the Apple test case, I interestingly see that the first request is marked as HTTPS, the second one is, however, marked as HTTP.

@Maxr1998 Exactly, curl didn't try a TLS handshake with Apple's HTTP server. I haven't been able to figure out why.

**Comment by tearfur** [comment]
> maybe we could modify the `shareEverything()` initializer in web.cc to only share `CURL_LOCK_DATA_DNS` and CURL_LOCK_DATA_PSL`

Well, turns out this was the correct fix all along. I guess it didn't work before since Fedora's tracker temporarily blocked my IP address because I've just been spamming announces.

The reason curl tried the TLS handshake is because of HSTS:

```
https connected (HTTP 200)(application/x-bittorrent)
* Switched from HTTP to HTTPS due to HSTS => https://torrent.fedoraproject.org:6969/announce?info_hash=%5C%D7i%F9%1A%97%23%A1%85l%8F0%F2%A45%A7%16%27%05%98&peer_id=-TR410Z-s5g7fwjzvtel&port=51413&uploaded=0&downloaded=0&left=2099452966&numwant=80&key=5B379F8C&compact=1&supportcrypto=1&event=started
*   Trying 152.19.134.148:6969...
*   Trying 2600:2701:4000:5211:dead:beef:fe:fed8:6969...
* ```

Welp simple fix it is, PR right away.

**Comment by Maxr1998** [comment]
Thank you so much for investigating the cause and providing a fix!

**Comment by tearfur** [comment]
Thank you for participating so actively in the discussion too! It helps a lot.
