### ISSUE TITLE
Wrong torrent progress stripe color

### ISSUE THREAD

**Issue by Raskilas** [transmission/transmission#5207]
### What is the issue?

Good day, since update from 3.x to 4.x version torrent load progress stripe changed color from blue to green and it looks ugly. I've been using Transmission for a decade and there is always was blue load stripe. Other GTK apps in my OS doesn't have such green color. Is there way to tune or turn back blue color?

![Load progress color difference in Transmission](https://user-images.githubusercontent.com/1936631/224549478-41515f21-14f6-413b-9d14-a4f75189f814.png)

Fedora 37, Wayland with GNOME 43.3

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1 (e1c6e1be43)

**Comment by ckerr** [comment]
This was added in https://github.com/transmission/transmission/issues/1998

**Comment by Raskilas** [comment]
So there is no way to return old behaviour?

**Comment by mikedld** [comment]
There's no option for it, no.

"Looks ugly" is subjective. I look at your screenshot and it looks alright to me. I'm planning on making progress colors configurable via CSS when building with GTK 4, but the view needs to be migrated from GtkTreeView to GtkListView first.
