### ISSUE TITLE
Add 2.93 to the PPA?

### ISSUE THREAD

**Issue by forteller** [transmission/transmission#521]
Thanks for a great torrent client!

It seems to me that there are a few important fixes in 2.93, but unfortunately no way to get it in Ubuntu without compiling it from source. I'd appreciate it if you'd add it to your PPA. Thanks! https://launchpad.net/~transmissionbt/+archive/ubuntu/ppa

**Comment by mikedld** [comment]
We're not officially supporting any PPAs, please talk to their maintainers directly.

**Comment by forteller** [comment]
Ok, sorry, didn't know it's not yours. So any other way of getting the 2.93 on the latest Ubuntu?
