### ISSUE TITLE
Transmission (GTK & QT) crash on ArchLinux

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [transmission/transmission#5210]
### What is the issue?

I have updated my distro
I have rebooted it after updates
I have reinstalled GTK and QT

Still crashing after few seconds.

I can provide any info, just tell me what info and how to get it.
Cheers and ty.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1 (Latest)

**Comment by ckerr** [comment]
4.0.2 will be coming out soon; you may want to try with that.

If it's still failing in 4.0.2, please try running transmission in a debugger to get a full backtrace.

Are you building Transmission on your own?

**Comment by 4e576rt8uh9ij9okp** [comment]
Hi, thanks for answering.
I'm just doing `sudo pacman -S transmission-gtk` to install it.

Idk how to build it, as the only way I know is to use `makepkg -si` and there is no makepkg in the linux tar folder.

**Comment by ckerr** [comment]
https://wiki.archlinux.org/title/Debugging/Getting_traces has information on how to get a trace out of apps on Arch. Please remember to install the debug packages; it will help to make the trace be human-readable.

**Comment by ckerr** [comment]
Closing due to lack of response and lack of actionable info.

If the crash persists in 4.0.2 or higher, please provide a backtrace.
