### ISSUE TITLE
Linux - No external storage option for ‘Automatically add torrent files from’ option

### ISSUE THREAD

**Issue by thenosyt** [transmission/transmission#5222]
### What is the issue?

I use a micro sd card for all of my chrome downloads. Transmission will allow me to select it as my target for my Transmission downloads but it won’t for the auto add setting. 

When trying to select it in the Transmission settings,  I look for my external storage when I am in the file browser, I only have access to my internal storage, even when I click on ‘Other Locations’. 

Please help. 

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
Transmission's not doing anything special with the file chooser dialog. Can you see your micro sd card from other GTK applications?

**Comment by ckerr** [comment]
Closing due to lack of response and lack of actionable info.
