### ISSUE TITLE
"Remaining time unknown" while downloading with enough seeders

### ISSUE THREAD

**Issue by gjalsem** [transmission/transmission#523]
In `torrent.c` function `tr_torrentStat()` the ETA of a download is calculated. If the bytes that are still needed to complete the download are not all available, the ETA is set to "unknown":

        if (s->leftUntilDone > s->desiredAvailable && tor->info.webseedCount < 1)
        {
            s->eta = TR_ETA_NOT_AVAIL;
        }

However, I noticed that sometimes, while downloading a file with lots of seeders, the ETA in the GUI jumps to "unknown" shortly. After doing some tests, I have a theory about what's going on.

The `leftUntilDone` value is calculated first, and the `desiredAvailable` after that. If there is at least one seeding peer, `desiredAvailable` is calculated in the same way as `leftUntilDone`, using `tr_torrentGetLeftUntilDone()`. So in theory these values should in those circumstances always be the same. They are not however. My guess is that it's because these two calculations are not in sync. So for example `leftUntilDone` is calculated to be 123456, but when calculating `desiredAvailable`, the same function now returns 123400, since some bytes were downloaded in the meantime.

I'm new to this code base though, so I'd like to hear if I'm on the right track. Also, if this is true, I'm not sure what the best way would be to fix it.

**Comment by andreaskern** [comment]
I think I ran into the same issue reported here #1180

**Comment by andreaskern** [comment]
`desiredAvailable` counts the chunks that have a clear `dnd` (do not dowload) flag (and have a replication count above 0).
`leftUntilDone` seems to be missing the unchecked pieces (but already downloaded).

so adding `s->haveUnchecked` to leftUntilDone should fix this issue.
It seems there are some misconceptions about which values include and which values exclude 'inflight' pieces. 


https://github.com/transmission/transmission/blob/44fc571a6737e98d04c09e479fd6682222abc13d/libtransmission/torrent.c#L1443

**Comment by ckerr** [comment]
This may be fixed by https://github.com/transmission/transmission/pull/4226

**Comment by Pentaphon** [comment]
> This may be fixed by #4226

@andreaskern @gjalsem any followup?
