### ISSUE TITLE
Low-contrast text/graphics on Peers List in WebUI in Light Mode

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#5235]
### What is the issue?

I think the colors on the current Peers List in the WebUI should be improved to make the peers list easier to read on Light Mode. 

See observations below. The whole thing should be overhauled with an emphasis on contrast and legibility in light mode. 

![peers](https://user-images.githubusercontent.com/49374058/225513030-bcd54f4e-e9dd-4326-8dd6-07f52f4c8286.png)

Now compare this to the peers list in dark mode, which is far more legible. The lock symbol and text really pops compared to light mode. 

![dark](https://user-images.githubusercontent.com/49374058/225513118-57120c44-7a3f-4cf3-9f4a-a6174a7b1de7.png)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by sfan5** [comment]
Is it possible to set the WebUI to use dark mode on its own? I assume it just follows the OS/browser setting currently.

**Comment by Pentaphon** [comment]
> Is it possible to set the WebUI to use dark mode on its own? 

no

**Comment by klevain** [comment]
I've just make a [PR that cover this issue](https://github.com/transmission/transmission/pull/5465). Any feedback appreciated.

**Comment by tearfur** [comment]
Fixed in #5470 (?)
