### ISSUE TITLE
Transmission In Confinement Generates Random DBUS Ids and Isnt Static

### ISSUE THREAD

**Issue by CapeCrusader321** [transmission/transmission#5237]
### What is the issue?

Hey there community i am trying to build and maintain a snap package for latest gtk builds of transmission, everything is done but the problem with transmission is that it generates random dbus ids when confined and thus makes my specified any dbus id useless and also prevents a successfully built transmission from running, always gives the following error --:

**_Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.179" is not allowed to own the service "com.transmissionbt.transmission_2051_7733333" due to AppArmor policy_**

First Believing a Issue with snaps discussed with the snapcrafters but they refuse by saying that its a transmission specific problem, the files related to snap build can be checked from-->  https://github.com/CapeCrusader321/Transmission-Snap

How do i fix this, any help will be sincerely appreciated
The aim of snap package is to increase the spread of transmission and also as a better conveyance for Snapd Users.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2

**Comment by ckerr** [comment]
Related:

https://forum.snapcraft.io/t/check-for-d-bus-session-bus-name-is-too-restrictive/8401/4 explains why those numbers are there.

https://github.com/transmission/transmission/pull/847

**Comment by CapeCrusader321** [comment]
> Related:
> 
> https://forum.snapcraft.io/t/check-for-d-bus-session-bus-name-is-too-restrictive/8401/4 explains why those numbers are there.
> 
> #847

Thanks but also can you suggest any fix, i mean what should be the dbus name for the snap..

**Comment by CapeCrusader321** [comment]
> Related:
> 
> https://forum.snapcraft.io/t/check-for-d-bus-session-bus-name-is-too-restrictive/8401/4 explains why those numbers are there.
> 
> #847

The snap has been succesfully built and is live, check it out from these link  --:

<a href="https://snapcraft.io/transmission-community">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>
