### ISSUE TITLE
Unable to compile (error: ‘struct utp_callback_arguments’ has no member named ‘error_code’)

### ISSUE THREAD

**Issue by mikeggh** [transmission/transmission#5247]
### What is the issue?

transmission4/libtransmission/peer-io.cc:757:40: error: ‘struct utp_callback_arguments’ has no member named ‘error_code’
  757 |                 io->on_utp_error(args->error_code);
      |                                        ^~~~~~~~~~
transmission4/libtransmission/peer-io.cc: In lambda function:
transmission4/libtransmission/peer-io.cc:770:63: error: ‘struct utp_callback_arguments’ has no member named ‘send’
  770 |                 io->bandwidth().notifyBandwidthConsumed(args->send != 0 ? TR_UP : TR_DOWN, args->len, false, tr_time_msec());
      |                                                               ^~~~
transmission4/libtransmission/peer-io.cc: In lambda function:
transmission4/libtransmission/peer-io.cc:782:47: error: ‘struct utp_callback_arguments’ has no member named ‘state’
  782 |                 io->on_utp_state_change(args->state);

To compile temporary I used:
10048  git checkout ba679a814fba0f8b861768e2fd9854a4f04d0b4b ../libtransmission/peer-io.cc
10050  git checkout ba679a814fba0f8b861768e2fd9854a4f04d0b4b ../libtransmission/tr-utp.cc
from build dir... 

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

f5a24862db7dbc834506fa16e2ea9046a9ac2a2e

**Comment by mikedld** [comment]
What does `git status` say? I.e. do you maybe need to update submodules?

**Comment by avdzm** [comment]
I had the same issue.
I then remembered seen in the README about updating and recompiling.

i wrote a script for updating in the build folder, with the GTK
make clean    
git pull --rebase --prune    
git submodule update --recursive    
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimized binary.    
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_GTK=ON ..    
make
sudo make install

**Comment by ckerr** [comment]
@mikeggh ^ does this work for you?

**Comment by mikeggh** [comment]
It did work!  I'll have to add an alias for git pull to always update submodules and rebase as well :>  I should have looked further into the issue and recognized the headers were from a submodule.. 
Thanks for the help!

I noticed the updates from the past few months are working great!  whether it's the UTP changes to mitigate the regression, or other changes.. things seem to be functioning much better in general for various torrents.. =)  Thanks for all the effort.
