### ISSUE TITLE
launchpad.net Repository Way Out Of Date

### ISSUE THREAD

**Issue by zero77** [transmission/transmission#526]
The launchpad.net transmission repository listed on the main transmission website under downloads for Ubuntu is way out of date its still on 2.82.

Can you please update this or add another up to date repository.
Thanks

**Comment by mikedld** [comment]
As you could see at https://launchpad.net/ubuntu/+source/transmission, these packages are maintained by "Ubuntu Developers", meaning not us. I've adjusted the link on the site to point to this page (which lists all the recent versions) and not the v2.82 one, but other than that we're not responsible for the content there.
