### ISSUE TITLE
transmission-remote -i does not show field 'Downloaded'

### ISSUE THREAD

**Issue by hoimic** [transmission/transmission#5262]
### What is the issue?

When requesting torrent stats with transmission-remote -i, the field 'Downloaded' is not shown. This info is missing because, in the code requesting this info (utils/remote.cc), the key TR_KEY_downloaded is used. This key does not exist. The correct key name is TR_KEY_downloadedEver. The line I am referring to is https://github.com/transmission/transmission/blob/c60bb5b834f0518a81ca3117a0f2af01fd53850f/utils/remote.cc#L1022

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

4.0.2

**Comment by hoimic** [comment]
I have already fixed the issue in my own checkout of the git repository. How would I go about requesting a pull request for the fix?

**Comment by ckerr** [comment]
@hoimic https://github.com/transmission/transmission/compare should work!
