### ISSUE TITLE
paper over DHT implementation bug that floods DHT network with 1 for the port.

### ISSUE THREAD

**Issue by cfpp2p** [transmission/transmission#527]
DHT versions prior to 0.25 are storing the supplied port number
under the infohash in its store of peer contact information as
port **1** in most cases of `announce_peer`.

refs:

> Exactly the wrong behaviour

https://github.com/jech/dht/issues/29#issuecomment-365762568
http://www.bittorrent.org/beps/bep_0005.html
https://gist.github.com/cfpp2p/59b628987ffbf2a4aa2d9c850d6d6d4a#file-log-stdout-snippet-log

We should have an option to block peers with port **1**
when `tr_peerMgrAddPex()` is adding `TR_PEER_FROM_DHT`.

refs:
https://github.com/ghazel -->  committed Feb 12, 2018 https://github.com/clostra/dcdn/commit/1ba212c7cea6cf1b5ab75f750de890c2df70cad6
https://github.com/cfpp2p/transmission/commit/d0c97a058d1d5f81028d3b91f209d36582cfc756#diff-8c3b89b4f93c549d0e6a76381537e699

Current released transmission version 2.93, and all prior versions,
will continue to flood the DHT network with pollution; DHT peers port **1**.
Transmission needs to account for this, the DHT library is indeterminate for such purposes,
the network is already polluted.

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/5218
