### ISSUE TITLE
Make snap package for ubuntu

### ISSUE THREAD

**Issue by boingo-00** [transmission/transmission#529]
I needed to install the transmission daemon on ubuntu core, where only snap packages are supported. Ready-made packages I have found, to collect myself did not. Would be very grateful for the assembled package for ubuntu

**Comment by simos** [comment]
Here is the (unofficial) snap package for transmission-daemon: *transmission-daemon-simosx*

**Comment by simos** [comment]
Follow this PR for the snap package, https://github.com/transmission/transmission/pull/641

**Comment by ckerr** [comment]
Very very happy that someone is creating unofficial Snap packages. I'm a fan of snappy and use it regularly but don't have the bandwidth to take this on as a supported part of the Transmission project.

As such I'm going to close this issue as `wontfix` but anyone making unofficial snaps has my thanks...

**Comment by ckerr** [comment]
@simos if you want, please open a PR in the `transmission/transmission` [docs](https://github.com/transmission/transmission/blob/main/docs/README.md) linking to your package's page to help users find it!

**Comment by GScottElshaw** [comment]
@ckerr And the renewed Transmission website!
