### ISSUE TITLE
Transmission leaves .added files

### ISSUE THREAD

**Issue by photoenix** [transmission/transmission#5290]
### What is the issue?

Windows 11 QT x64 4.0.0, 4.0.1, 4.0.2

After automatically adding .torrent files from my Downloads folder Transmission leaves .added files in there.

Move the .torrent file to the trash is checked.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.2 (2a57b17031)

**Comment by photoenix** [comment]
Still happening in 4.0.3

**Comment by sounak-kun** [comment]
Can confirm this is happening. For the time being, I have setup Task Scheduler to delete `*.torrent.added` files daily.
`del %USERPROFILE%\Downloads\*.torrent.added`

**Comment by Endlesszombiez** [comment]
This issue is still prevalent in 4.1.0 (0d3b321bac) nightlies.
