### ISSUE TITLE
Transmission 3.00 segfaults shortly after startup

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#5292]
### What is the issue?

Transmission has been running stable up until very recently. I have recompiled it against openssl and there seems to be crashes related to functions in libcrypto.3.dylib, but I'm not sure why.

Here is an example of such stack trace.
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2546]

...

Thread 2 Crashed:
0   libcrypto.3.dylib             	0x000000010ceeaa6c EVP_CIPHER_CTX_set_key_length + 36
1   org.m0k.transmission          	0x000000010cb80f6a 0x10cae2000 + 651114
2   org.m0k.transmission          	0x000000010cb6c4f8 0x10cae2000 + 566520
3   org.m0k.transmission          	0x000000010cb6c58a 0x10cae2000 + 566666
4   org.m0k.transmission          	0x000000010cb6d4f0 0x10cae2000 + 570608
```

It is *always* this exact function crashing. At first I suspected a corrupted app database, but I have weekly backups dating back to November 2022, and the latest three or so backups cause a crash on start somehow. When I start the app from an empty `~/Library/Application Support/Transmission` folder, everything seems normal. I have not attempted torrenting, however. I cannot tell if this is due ABI breakage with OpenSSL or some strange corruption that went unnoticed for a while since I rarely restart the app.

### Which application of Transmission?

macOS app

### Which version of Transmission?

3.00

**Comment by ckerr** [comment]
Does the released version of 3.00 on transmissionbt.com crash? Does 4.0.2?
