### ISSUE TITLE
WebUI: Ctrl+V (Paste) doesn't work anywhere

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5298]
### What is the issue?

In the "Add Torrents" dialog or in any text fields in preferences pressing Ctrl+V just does nothing at all, it is supposed to paste text.
Seen in Firefox on Windows.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by bacongobbler** [comment]
For those looking for a workaround, right-clicking and hitting "Paste" works as normal.

**Comment by tessus** [comment]
Interesting. I understand that it might conflict on Linux and Windows. However, I just wanted to clarify that it worked perfectly fine on macOS. (Which is what I tested with for #5054: transmission running on Linux, using different browsers on macOS to access web frontend)
