### ISSUE TITLE
WebUI: Hamburger menu is not scrollable if window is too small

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5299]
### What is the issue?

![grafik](https://user-images.githubusercontent.com/1042418/227739336-48bf83bf-ade3-43e8-846b-05ed65bfc942.png)
The scrollbar on the right scrolls just a tiny bit. The top 1/3 of the menu contents is basically missing with no means to access it.
Seen in Firefox on Windows

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by killemov** [comment]
If a menu is bigger than the view-port then it should scroll in place. But this looks like you're testing the limits of the UI instead of just using it like you're supposed to. I have seen menus like this turned into tabbed form.

**Comment by Pentaphon** [comment]
@GaryElshaw you might be able to solve this quickly.

**Comment by GaryElshaw** [comment]
Unfortunately this might be a Windows bug, i'm unable to replicate it here :-(

**Comment by Pentaphon** [comment]
> Unfortunately this might be a Windows bug, i'm unable to replicate it here :-(

What is your screen resolution? I find that it only happens on 1366x768 and smaller screens on Firefox.

**Comment by GaryElshaw** [comment]
I'm 1920x1080, i'll take another look.

**Comment by Pentaphon** [comment]
> I'm 1920x1080, i'll take another look.

I posted more info about this here: https://github.com/transmission/transmission/issues/5337

Thanks for looking.

**Comment by GaryElshaw** [comment]
That particular resolution isn't an option for me, i'm afraid.

**Comment by Pentaphon** [comment]
> That particular resolution isn't an option for me, i'm afraid.

That's ok, thanks for trying.

**Comment by GaryElshaw** [comment]
@Pentaphon I've been playing around, but Firefox is rendering the menu in a comletely different way from Chromium. Firefox in foreground, Chromium at the back.

![Screenshot from 2023-07-13 15-14-10](https://github.com/transmission/transmission/assets/69029666/6ab91fe0-dc0d-4053-8045-cfe75de4df78)

**Comment by killemov** [comment]
This is not "and now for something completely different". It's just line-height or spacing that's a little off.

**Comment by GaryElshaw** [comment]
Sure thing, my point was same code, different rendering.

**Comment by killemov** [comment]
My best guess would be to make the line-height and/or spacing (/other property) explicit instead of leaving it for the browser to decide.

**Comment by sfan5** [comment]
No problem replicating this on Linux with Firefox default settings:
![grafik](https://github.com/transmission/transmission/assets/1042418/009ee041-b20f-46be-acda-b45ae48c2517)
My window was 1384x826 in this case.

I also noticed that the hamburger menu does not respond to window resizing at all, but that's a separate bug.

**Comment by Pentaphon** [comment]
@dareiff perhaps you might be able to solve this issue with the webui?

**Comment by dareiff** [comment]
Will be fixed here: https://github.com/transmission/transmission/pull/5820

Not too bad!

**Comment by Pentaphon** [comment]
> Will be fixed here
> 
> Not too bad!

Oh good somebody got it before you looked at it. Thanks for giving it a look!

**Comment by Rukario** [comment]
Unfortunately, it looks like my suggest for changes in another PR are being completely disregarded, I've had to reopen my PR with my suggest for changes accounted for. My PR does not account for secondary scrolling, or "scrollability" as another PR they called it.

**Comment by killemov** [comment]
As an aside. I've mentioned before (Trac maybe?) that eventually there will be too much to display in a menu anyway. So maybe redesign a-la inspector?

**Comment by Rukario** [comment]
I actually thought of murdering some buttons to lighten up list in the menu.

I seem to have sympton with clicking through buttons to find what I'm looking for, some only to open tiny popups so I feel they should be merged...
