### ISSUE TITLE
WebUI: shows nonsense values if torrent info is not loaded yet

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5300]
### What is the issue?

sometimes torrent info takes a bit to load, before that the tab shows nonsense values like E2BIG or NaN:
![grafik](https://user-images.githubusercontent.com/1042418/227739519-809ab265-ebcc-41e7-97e0-053fd9e74b59.png)
It would be better if it just said "Unknown" or left the fields empty.

Seen in Firefox on Windows.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by GaryElshaw** [comment]
#5249 addresses that issue and will be in the next release.

**Comment by sfan5** [comment]
Great, will be closing this then.
