### ISSUE TITLE
WebUI: tracker list should show full domain names

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5301]
### What is the issue?

As far as I can tell the webui looks at the domain name of trackers and tries to extract a meaningful name. This mostly works okay but there are also cases like this:
![grafik](https://user-images.githubusercontent.com/1042418/227740014-1d33cb73-5f3d-43b5-a9f8-0d01813edb79.png)
"tracker"? "torrent"? Entirely meaningless.

It is more practical to just display the entire domain name.
~~_Also_ there's no information whether its an UDP or HTTP tracker, that'd be good to show too.~~

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by ckerr** [comment]
> Also there's no information whether its an UDP or HTTP tracker, that'd be good to show too.

Please open a separate ticket for this -- one issue per ticket, please :smile_cat:  Otherwise triage becomes impossible

**Comment by ckerr** [comment]
> "tracker"? "torrent"? Entirely meaningless.

Hmm :thinking: that sitename comes from trying to sniff out the first part of the part of the address that's not in the public suffix list, e.g.

```
// www.example.com -> example
// www.example.co.uk -> example
// 127.0.0.1 -> 127.0.0.1
```

So at first glance it looks like this should be showing up only if you have announce-urls like `tracker.com` or `torrent.com`.

I don't need to see any torrent info, e.g. info hashes, but could you share the host part of the announce URLs in question, e.g. if the URL is `https://www.example.co.uk/announce/3209834803948390430`, could you share the `www.example.co.uk` part?

**Comment by ckerr** [comment]
Also, if you look at this page in a non-web UI, do you see the same names?

**Comment by ckerr** [comment]
Weird. OK.

Is that web client isn't talking to a macOS homebrew build of Transmission, is it?

I'm pretty sure the answer is "no" since you're using the Qt client, but I'm asking so that I can cross #4617 off the list of suspects.

**Comment by sfan5** [comment]
The daemon is running on Linux (and the Qt client too for that matter).

**Comment by sfan5** [comment]
Looks like #5382 fixed this.
