### ISSUE TITLE
WebUI: Tracker list does not show whether UDP or HTTP tracker

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5307]
### What is the issue?

Example:
![grafik](https://user-images.githubusercontent.com/1042418/228003627-3e1df382-2d7b-4b79-9a63-18f1828ce9d1.png)

Not essential but nice to have IMO. A small text or icon next to it could indicate this.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

**Comment by killemov** [comment]
Was it always like this? I vaguely remember that the raw urls were displayed.

**Comment by sfan5** [comment]
It wasn't, here's Transmission 2.94 web:
![image](https://user-images.githubusercontent.com/1042418/228559242-e81f8352-acda-4fb3-9e4d-f1f98718d79e.png)
