### ISSUE TITLE
aria2 peer ID wrongly identified as ABC

### ISSUE THREAD

**Issue by gdrbyKo1** [transmission/transmission#532]
Tested in version 2.93 (3c5870d4f5).
Transmission wrongly identifies aria2's peer ID as pertaining to the ABC client. For example, for aria2c 1.33.1, the peer ID it uses is `A2-1-33-1-` padded to 20 bytes with random data. When Transmission parses that peer ID, it reports the client as `ABC 2.63.1` instead of `aria2 1.33.1`.
aria2's peer ID format is documented here: https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-peer-id-prefix

**Comment by cfpp2p** [comment]
https://github.com/aria2/aria2/issues/937

**Comment by ckerr** [comment]
Fixed by 1ba64684f908aaeedee2cf0aca6dc6e43ff59fc0
