### ISSUE TITLE
WebUI keyboard shortcuts disabling common keyboard shortcuts when typing into a text input

### ISSUE THREAD

**Issue by anthonyryan1** [transmission/transmission#5326]
### What is the issue?

This is a new regression to the WebUI since the 4.0 release as far as I can tell.

In transmission.js `_keyDown()` we check the keyboard shortcuts from action-amanger.js here:
https://github.com/transmission/transmission/blob/4.0.2/web/src/transmission.js#L473-L480

But we don't define is_input_focused until a few lines later: https://github.com/transmission/transmission/blob/4.0.2/web/src/transmission.js#L490

I think there's merit to not triggering that action when an input is focused.
- One example use case is "Ctrl+A, then backspace" to clear the searchbox at the top of the page.
- Another is Ctrl+V pasting into a search box, where we've accidentally disabled that way to paste

I'm happy to submit a fix for this, but I wanted to confirm the dev team is content with disabling all keyboard shortcuts when a text input is focused.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.x

**Comment by GaryElshaw** [comment]
Having lots of discussion around that area at the moment, i doubt anyone will complain if you fix it! https://github.com/transmission/transmission/pull/5318#issuecomment-1487745181
