### ISSUE TITLE
file size error in TR4

### ISSUE THREAD

**Issue by wishday** [transmission/transmission#5335]
### What is the issue?

the total size of every downloaded torrent shown in TR4 webui will always larger than that in TR3.

acctually the size in TR3 is correct, because that is same with the size announced by PT site.

please correct this error in TR4 asap, we need corrected size info to decide wether the resource is the same in different torrent

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1

**Comment by ckerr** [comment]
Could you be more specific about this? E.g. could you provide screenshots with a public domain torrent?

**Comment by killemov** [comment]
Might this be a (default) unit issue? (1000 vs. 1024?)

**Comment by ckerr** [comment]
Closing due to lack of response + lack of actionable info.

If this problem is still present in the latest version of Transmission, please open a new ticket with the requested information. Thank you!

**Comment by wishday** [comment]
the problem remain the same after updated to tr 4.0.2(deployed in docker)

following screenshot for you info.
3 torrents are the same in tr3 and tr4.

![Screenshot_20230421_211755](https://user-images.githubusercontent.com/124063318/233651372-2451d69b-ef69-43fd-ace7-d5b8ec237f7b.jpg)
![Screenshot_20230421_211548](https://user-images.githubusercontent.com/124063318/233651386-42990b94-6c77-4d36-a316-018fa4230405.jpg)

**Comment by killemov** [comment]
@wishday Replace that image with something open-sourcy NOW. You might get banned otherwise.
