### ISSUE TITLE
Bottom of window is under dock and cannot resize

### ISSUE THREAD

**Issue by hepcat72** [transmission/transmission#5349]
### What is the issue?

I just updated the app, and as you can see from the screenshot, the window dips below the dock.  I cannot grab the bottom edge to resize it (the cursor doesn't change to a resize cursor and trying to resize it anyway just drags the window).

My screen res is set at 720p, if that's helpful.

![Transmission - Screen Shot 2023-04-03 at Apr3 9 44 53 AM](https://user-images.githubusercontent.com/2300532/229529051-5cff54cc-eed9-49d1-a711-2f67db82211a.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.2

**Comment by jslawler** [comment]
I'm also experiencing this with auto resize turned on. With it turned off, it's able to be resized.

macOS: 13.3.1 (22E261)
Transmission: 4.0.3 (6b0e49bbb2)

<img width="517" alt="Screenshot 2023-05-01 at 13 04 50" src="https://user-images.githubusercontent.com/95468948/235395959-f16afb0e-3954-44ee-8ee2-7925ba6ffa37.png">

**Comment by emeritaacuity0u** [comment]
@ckerr @Coeur 
I've confirmed this also on macOS 15.0 Beta (24A5320a) with Transmission 4.0.6 (38c164933e).

The issue only happens (AFAIK) when using the auto resize feature. When using the inbuilt window manager in macOS, or another window manager such as Magnet or Rectangle, the dock position is respected by the Transmission main window.

As soon as auto resize is used and the amount of added torrents exceeds the height of the display, it will underlap approximately 3/4 of the default dock displayed.

<img width="1792" alt="Screenshot 2024-08-14 at 16 23 07" src="https://github.com/user-attachments/assets/94da85f0-d46a-423d-8679-c073f09c8bd0">

**Comment by Coeur** [comment]
Pinging the relevant persons:
- @sweetppro has been maintaining the autoresize feature on macOS.
- The last changes on autoresize were done by #6321 by @Artoria2e5 and reviewed by @nevack and me.

**Comment by Artoria2e5** [comment]
This feels like a relapse of the old bug… I mean, the whole reason that PR existed was to make it not dip into the dock. I will look into it (somewhat during this work week; more during this weekend).

**Comment by hepcat72** [comment]
🎉
