### ISSUE TITLE
rpc-bind-address :: does not allow IPv4

### ISSUE THREAD

**Issue by Sithuk** [transmission/transmission#5350]
### What is the issue?

The rpc-bind-address parameter in the config file does not allow IPv4 connections when set to "::". Transmission does allow ipv6 connections to the webUI with "::". I understand that the "::" parameter is supposed to allow both IPv4 and IPv6 connections for a dual stack environment (see thread linked below)?

https://github.com/transmission/transmission/issues/934

Setting rpc-bind-address to "0.0.0.0,::" doesn't work as transmission deletes the second value when transmission is started. The parameter is therefore only "0.0.0.0". So IPv4 only.
Adding a second rpc-bind-address line below the first doesn't work as transmission deletes the first rpc-bind-address entry.

What is the correct configuration to allow both IPv4 and IPv6 connections to the webUI?

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

3.00

**Comment by Sithuk** [comment]
It could be that the RPC server can only listen on either IPv4 or IPv6 at once. Not both. Does anyone know?
Line 88:
Listen for RPC connections on a specific address. This must be an IPv4 or IPv6 address. Only one RPC listening address is allowed. Default: 0.0.0.0 (All IPv4 addresses)
https://github.com/transmission/transmission/blob/main/daemon/transmission-daemon.1

**Comment by tearfur** [comment]
> It could be that the RPC server can only listen on either IPv4 or IPv6 at once. Not both.

Yes.

**Comment by ciskonc** [comment]
If you are using windows, You can try to use netsh to proxy IPv6 to IPv4 port. linux you can use similar tools to achieve the same effect
`netsh interface portproxy add v6tov4 listenaddress=:: listenport=9091 connectaddress=127.0.0.1 connectport=9091`
