### ISSUE TITLE
[RPC] torrent-add behaviour changed when adding duplicate torrent

### ISSUE THREAD

**Issue by equeim** [transmission/transmission#5355]
### What is the issue?

rpc-spec.md [says](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#34-adding-a-torrent) that:

> When attempting to add a duplicate torrent, a torrent-duplicate object in the same form is returned, but the response's result value is still success.

That was behaviour in transmission 3.0:
```
{"arguments":{"torrent-duplicate":{"hashString":"9f292c93eb0dbdd7ff7a4aa551aaa1ea7cafe004","id":2,"name":"debian-10.9.0-amd64-netinst.iso"}},"result":"success"}
```

However in 4.0.2 transmissions returns `"result": "duplicate torrent"`:
```
{"arguments":{"torrent-duplicate":{"hashString":"9f292c93eb0dbdd7ff7a4aa551aaa1ea7cafe004","id":107,"name":"debian-10.9.0-amd64-netinst.iso"}},"result":"duplicate torrent"}
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.2

**Comment by killemov** [comment]
Good catch. The specification has not changed. The result "success" was always interpreted as "The request is correct.".

**Comment by equeim** [comment]
Digging through source code it seems that "duplicate torrent" result was there even in 3.00:
https://github.com/transmission/transmission/blob/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd/libtransmission/rpcimpl.c#L1747

However it was then reset to NULL due to this condition:
https://github.com/transmission/transmission/blob/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd/libtransmission/rpcimpl.c#L1755

And "success" was sent to client. Then when this code was was refactored it surfaced into actual behaviour.

Digging further:

Original commit that implemented torrent-add returned result: "duplicate torrent" too:
https://github.com/transmission/transmission/commit/2186d852f16e3d2c7ab783022cf67963a54a38c3#diff-7f79ab12eae8a7093418a488e24735bac409b58b050c569649d0a51dd7f1c360R428

It seems that the fact that 3.0 returned success was actually a bug. And the change that added this to spec was added when this bug was already present:
https://github.com/transmission/transmission/commit/bee5c1016a5472066c52d7d475778e7b135bc7ee

**Comment by equeim** [comment]
Here is the change that introduced the original issue:
https://github.com/transmission/transmission/commit/af3481400f13fa196a5cf55e56fb287d10e6c4b6

When result is set to "duplicate torrent", key is also set to TR_KEY_torrent_duplicate. Then we fall into if branch that resets result to NULL.

**Comment by ckerr** [comment]
Yuck.

Since we didn't announce the changes, and since the bee5c1016a5472066c52d7d475778e7b135bc7ee is in the spec, I guess `success` should be returned in 4.x for duplicate torrents. :(

**Comment by killemov** [comment]
If changing the protocol is in the works maybe try to fit with [HTTP codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) or even custom codes instead of text messages. Still not quite sure what to do with 418 though.

**Comment by ckerr** [comment]
> This RPC change affects causes a few minor problems for a few clients that don't do internal duplicate detection (they obviously assume failure means adding the torrent failed). Ideally multiple adds would merge metadata such as trackers when possible, but success should be returned in any case.

There's another ticket tracking that request, https://github.com/transmission/transmission/issues/65

> If changing the protocol is in the works

Not in a semver/patch change, it's not. This change is to revert to the previous behavior to _avoid_ unannounced changes :smile:

**Comment by killemov** [comment]
OK, but it seem that is was and that it just wasn't announced or properly documented. But take it as a suggestion for future reference.
