### ISSUE TITLE
Torrents not seeding after restart

### ISSUE THREAD

**Issue by dnsBlah** [transmission/transmission#536]
Hi all,

I'm trying to solve some issue's on a warehouse here by using Transmission.
It works great and I would like to keep using this.

I have one little issue which came up this morning.
I been playing around with a settings.json so I had to stop/start the daemon a few times.

And I noticed that my 'seeds' have disapeared.
Of course it's because the torrent files are not .torrent anymore, but .torrent.added in my watch-dir
I still would like to keep using Transmission and keep seeding these torrents after a reboot.

Is there something I can do to solve this within Transmission, else I will be using a bash script to rename all the files back to .torrent and then start Transmission daemon.

I have seen a update related to .magnet files on a different fork : https://github.com/cfpp2p/transmission/commit/e06455e3dac1d516591588141b4baccd519f9fd0

Not sure how I can do this as it doesn't want to compile at all from source for me. I installed transmission via homebrew

Any help would be great

p.s. I'm running Mac devices.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
