### ISSUE TITLE
Set Location

### ISSUE THREAD

**Issue by enrique131** [transmission/transmission#5369]
### What is the issue?

Whenever a add a torrent and try to change its location it doesnt work unless i write it down letter by letter. It doesnt accept paste.
Synology DS220+ docker version. 

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

 Transmission 4.0.2 2a57b17031

**Comment by killemov** [comment]
Duplicate of #5326.

**Comment by enrique131** [comment]
Apologies
