### ISSUE TITLE
Update broke transmisson daemon #2

### ISSUE THREAD

**Issue by yuriw** [transmission/transmission#538]
https://ubuntuforums.org/showthread.php?t=2386394

FYI

See #187

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.

**Comment by yuriw** [comment]
@MarcosBL @satter @tzeejay
Thank you for #533 solution !!!

@mikedld  I am not sure why you are not allowing such issues to be added and resolved under this repo?   It is related to the project and is very useful !
