### ISSUE TITLE
key query param in tracker announces should be fixed-length

### ISSUE THREAD

**Issue by pop-dahaka** [transmission/transmission#5393]
### What is the issue?
 transmission-4.0.2-x64.msi  generate wrong key  length (changeable)
sometimes generate 10 numbers and also 9 numbers and also 8 numbers and 7 numbers and 6 numbers 
`&key=3214922509
&key=605129593
&key=83815924
&key=5522375
&key=743475`

but should be fixed length .

### Which application of Transmission?
windows 10 x64

### Which version of Transmission?
Transmission 4.02 (2a57b17031)
 transmission-4.0.2-x64.msi 

please fix the key next version .

**Comment by pop-dahaka** [comment]
the bug is the key length changeable , some trackers blacklist transmission because of that , you can choose one length as you wish maybe 10 or  9 or 8 .

**Comment by ckerr** [comment]
It's just a random 32-bit number.

```
// https://www.bittorrent.org/beps/bep_0007.html
// "The client SHOULD include a key parameter in its announces. The key
// should remain the same for a particular infohash during a torrent
// session. Together with the peer_id this allows trackers to uniquely
// identify clients for the purpose of statistics-keeping when they
// announce from multiple IP.
// The key should be generated so it has at least 32bits worth of entropy."
//
// https://www.bittorrent.org/beps/bep_0015.html
// "Clients that resolve hostnames to v4 and v6 and then announce to both
// should use the same [32-bit integer] key for both so that trackers that
// care about accurate statistics-keeping can match the two announces."
```

How can you have 32 bits worth of entropy with a fixed-length number of digits?

Does the tracker give a rationale for blacklisting based on the width of the key string? This seems insane. Are they requesting that all torrents from that client have the same width key, or what?

**Comment by pop-dahaka** [comment]
they want key length fixed such as :
qbittorrent always send key length fixed = 8 
utorrent always send key length fixed = 8

**Comment by pop-dahaka** [comment]
please count after =
deluge key length fixed = 8
&key=1F777E4B
&key=579D433B
&key=91B4F546

qbittorrent key length fixed = 8
&key=47CEBBB7
&key=F6B45E61
&key=F2A67F4B

transmission key length 10
&key=1458994892
&key=1743210930
&key=4264473821

transmission key length 9
&key=790967735
&key=480189325
&key=854866481

transmission key length 8
&key=55660292
&key=59710114
&key=34491379

**Comment by ckerr** [comment]
Huh, apparently that's true. Both libtransmission and libtorrent are generating a random number, but libtorrent zero-pads it. Looks like this was made in https://github.com/arvidn/libtorrent/commit/7351389ce8aee43059881b36bfd6247f75853db0 where zero-padding was added:

```diff
-                               "&key=%X"
+                               "&key=%08X"
```

I don't see anything in the commit that explains the change, and it doesn't add any entropy, but... if it makes life easier for trackers, sure libtransmission can zero-pad as well.
