### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#541]
A call of the macro “ACX_PTHREAD” is specified in [a build configuration script](https://github.com/transmission/transmission/blob/d86bd614bf23ce97ece8cd872a49d6332b08eeb8/configure.ac#L116 "Update candidate") without parameters. (Determined variables are not applied at other places so far.)
I suggest to update it to [the macro “AX_PTHREAD”](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "Build configuration for POSIX thread API") together with the specification of a parameter like “ACTION-IF-FOUND” (and/or “ACTION-IF-NOT-FOUND”).

**Comment by mikedld** [comment]
CMake is the only build system generator currently supported, closing.
