### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#542]
The function “[g_log](https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-message "Logging a message")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[signal_handler](https://github.com/transmission/transmission/blob/1e3d20422a6ff18a7ffdd2e35a706c81c0eb868a/gtk/main.c#L470 "Update candidate")”.

**Comment by ckerr** [comment]
Looks like this could be replaced with an `fprintf(stderr, ...);`

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "Wait for queued signals")
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Background information for the self-pipe trick")

**Comment by mikedld** [comment]
Fixed in #3967 by switching to `g_unix_signal_add()`.

**Comment by elfring** [comment]
:thought_balloon: I would appreciate further clarification of corresponding software development concerns also for [the safe usage of the programming interface “GLib” in the mentioned area](https://docs.gtk.org/glib/func.unix_signal_add.html "Using g_unix_signal_add()").

**Comment by mikedld** [comment]
`g_unix_signal_add()` is implemented via [`g_unix_signal_source_new()`](https://docs.gtk.org/glib/func.unix_signal_source_new.html) which I believe is well-documented to provide enough information.

**Comment by elfring** [comment]
:thought_balloon: I would find an improved API documentation more appealing also for the discussed use case.

**Comment by mikedld** [comment]
Sorry, I don't understand what you're expecting me to do... This issue does not warrant documentation in Transmission itself. As for Glib documentation, feel free to contribute there if you think it needs clarification.

**Comment by elfring** [comment]
Thanks for your source code adjustments according to the Transmission software.
