### ISSUE TITLE
transmission-cli "no such file or directory" with magnet - similar to PR#5028

### ISSUE THREAD

**Issue by jggimi** [transmission/transmission#5424]
### What is the issue?

Fails in 4.0.2 and 4.0.3. 

`$ transmission-cli "magnet:?xt=urn:btih:ad377e33a5ad91a2291564c96af534e1d87336bb&dn=FreeBSD-13.2-RELEASE-amd64-mini-memstick.img.xz"
[2023-04-20 09:23:18.153] utils.cc:76: Couldn't read 'magnet:?xt=urn:btih:ad377e33a5ad91a2291564c96af534e1d87336bb&dn=FreeBSD-13.2-RELEASE-amd64-mini-memstick.img.xz': No such file or directory (2)`

### Which application of Transmission?

None

### Which version of Transmission?

4.0.3

**Comment by rjc** [comment]
Hello,

I've originally reported this issue[0] to @jggimi as the OpenBSD port maintainer but would like to re-state it here that the two issues look very similar (the same?) as previously reported (and fixed!) issues with `transmission-remote` - #5028 and #5073 - so yes, there's also the `File name too long (63)` issue.

I'm mentioning it here on the off chance that, unlike #5088, a single fix only address this, but not the other, issue.

[0] https://marc.info/?l=openbsd-ports&m=168198982019242&w=2

**Comment by jggimi** [comment]
Backtrace from utils.cc:76:

`#0  tr_loadFile (filename=..., contents=..., error=0x0)
    at /usr/ports/pobj/transmission-4.0.3-no_gtk-no_qt/transmission-4.0.3/libtransmission/utils.cc:77
#1  0x0000033265edbe97 in tr_ctorSetMetainfoFromFile (filename=..., ctor=<optimized out>, error=<optimized out>)
    at /usr/ports/pobj/transmission-4.0.3-no_gtk-no_qt/transmission-4.0.3/libtransmission/torrent-ctor.cc:78
#2  tr_ctorSetMetainfoFromFile (ctor=0x33487cdbc00, filename=<optimized out>, error=0x0)
    at /usr/ports/pobj/transmission-4.0.3-no_gtk-no_qt/transmission-4.0.3/libtransmission/torrent-ctor.cc:90
#3  0x0000033265e0de4d in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/ports/pobj/transmission-4.0.3-no_gtk-no_qt/transmission-4.0.3/cli/cli.cc:260`
