### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#543]
Would you like to add more error handling for return values from functions like the following?
- [bindtextdomain](https://www.gnu.org/software/libc/manual/html_node/Locating-gettext-catalog.html#index-bindtextdomain "How to determine which catalog to be used") ⇒ [main](https://github.com/transmission/transmission/blob/1e3d20422a6ff18a7ffdd2e35a706c81c0eb868a/gtk/main.c#L602)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [on_startup](https://github.com/transmission/transmission/blob/1e3d20422a6ff18a7ffdd2e35a706c81c0eb868a/gtk/main.c#L491)

**Comment by ckerr** [comment]
Sure, a PR would be welcome.
