### ISSUE TITLE
Adjust data structures for dialogue display

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#544]
The class “MainWindow” contains [a few attributes for dialogues](https://github.com/transmission/transmission/blob/dadffa2c0f9ede1f7b2de885d4dd51181523a918/qt/MainWindow.h#L155 "Reconsider attributes in MainWindow"). I find it better to store them in a corresponding member function so that they will be only used if a specific dialogue should really be displayed.

**Comment by ckerr** [comment]
> 💭 I hope that further improvements will become possible also for [Qt software components](https://github.com/transmission/transmission/blob/9280bf347573c4f1f73fdfd85a20d41266a49ecf/qt/MainWindow.h#L157).

You had five years where you could have opened a pull request...! 😸
