### ISSUE TITLE
Complete build specifications for Autoconf

### ISSUE THREAD

**Issue by elfring** [transmission/transmission#545]
I have tried the command “autoreconf” (version 2.69) out after I cloned the Git repository for this software.
Unfortunately, this approach failed because of questionable build dependencies.

```
configure.ac:20: error: required file './compile' not found
configure.ac:20:   'automake --add-missing' can install 'compile'
…
configure.ac:651: error: required file 'third-party/…/Makefile.in' not found
…
```

**Comment by elfring** [comment]
The command “`autoreconf -i`” works a bit better. But it failed still for the directory “third-party”.

**Comment by mikedld** [comment]
CMake is the only build system generator currently supported, closing.
