### ISSUE TITLE
announce url in inspector tier list is null

### ISSUE THREAD

**Issue by S-Aarab** [transmission/transmission#5459]
### What is the issue?

this bug caused by this commit #5382
when the announce url use protocol `udp` the url origin is `null`.
tested on firefox console:
```
console.log(new URL('udp://example.com:80').origin);
null
```
<img src="https://user-images.githubusercontent.com/32977495/234720117-3ba3edf8-1700-4215-801b-15273f0d59fd.png" width="50%" />

### Which application of Transmission?
Web client

### Which version of Transmission?
Transmission 4.0.3 6b0e49bbb2

### Which Browser?
Firefox 112.0.2

**Comment by ckerr** [comment]
Thanks for reporting this.

Looks like the `udp` scheme is confusing `new URL()` for whatever reason.

```term
> new URL('udp://example.com:80').origin
'null'
> new URL('http://example.com:80').origin
'http://example.com'
```
