### ISSUE TITLE
stats.json writed only if upload/download size changed

### ISSUE THREAD

**Issue by kmikita** [transmission/transmission#5476]
Uptime between sessions are lost if no data transmit (upload/download stats not changed -> file stats.json not written). Please, add periodical sync stats.json and flush stats on exit transmission-daemon.

transmission-daemon 4.0.3

**Comment by kmikita** [comment]
Now stats syncing every 6 minutes (session.cc: SaveIntervalSecs = 360s) and when closing session.

**Comment by jibwf** [comment]
@kmikita  Is it hard code or configurable? I would like to adjust it to dayly sync up to reduce disk spin up.

**Comment by kmikita** [comment]
@jibwf , not configurable.
You can play with **SaveIntervalSecs** and custom build or place configure files on virtual fs (overlayfs, tmpfs, ramfs for example) and sync to suit your needs (better choice).
