### ISSUE TITLE
How to tell the availability of a torrent

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#548]
Some times a transfer will never finish because there is one or more file piece that no-one has got.

What I currently do to check for this is press "Available" in the Torrent Inspector, and if there are some white pieces in the matrix chart, that means the file will most likely never reach 100%. (However, this can be quite hard to tell, because the colour for "available" and "unavailable" is almost identical!)

Where can I find Availability clearly stated in the GUI, eg. "Availability: 100%", "Availability: 98.7%"?

**Comment by forthrin** [comment]
Anyone? It's been a year since the issue was opened.

**Comment by forthrin** [comment]
Evidently, no-one is reading these issues.

**Comment by hughlilly** [comment]
I would also like to see an "Availability: _x_ %" item to the left of the availability chart. I can't imagine it would be too much work to add, unless the software doesn't currently calculate availability.

**Comment by danger89** [comment]
me2
