### ISSUE TITLE
Qt UI's compact view doesn't show torrent name

### ISSUE THREAD

**Issue by tunedal** [transmission/transmission#5483]
### What is the issue?

For torrents added via magnet links, before the torrent starts downloading, the Qt UI only displays "Magnetized transfer - retrieving metadata" and no filename, which makes it difficult to identify torrents.

The default view (non-compact) displays both the filename and this message. The GTK UI displays the filename in both compact and default views.

![transmission-qt-compact](https://user-images.githubusercontent.com/556423/235373124-3cc9a2f6-2e56-4f24-bddf-43f3a3c5ae10.png)

The GTK UI and the default view in the Qt UI work as expected:

![transmission-qt](https://user-images.githubusercontent.com/556423/235373125-2c07daf8-92e5-4217-a3c4-4b3e2ff4915c.png)
![transmission-gtk-compact](https://user-images.githubusercontent.com/556423/235373122-5ec4fb37-f875-409d-ace9-e79cc9db1f36.png)
![transmission-gtk](https://user-images.githubusercontent.com/556423/235373123-44817a14-6e5c-46cf-b261-151544c8a885.png)

This applies to any magnet link, but here is the one I tested with: `magnet:?xt=urn:btih:1485b3032e9ff79cfd499beeccd970da4d13e230&dn=FreeBSD-13.2-RELEASE-amd64-disc1.iso`

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by Pentaphon** [comment]
Looks like your theme is causing the issue and you should update to 4.0.3

**Comment by tunedal** [comment]
> There's only 1 line of info in compact mode (but the magnetizing info could be shortened)

The GTK UI also displays only 1 line, but it uses that line to display the filename. See the third screenshot. 

I would like the Qt UI to behave the same way as the GTK UI in this case, because a list of filenames is more useful than a list of identical "Magnetized transfer ..." messages.

> and you should update to 4.0.3 '

Yes, I realized that after submitting the issue, but 4.0.3 does not change this behavior.
