### ISSUE TITLE
Selecting two torrent transfers and clicking pause causes all transfers to stop

### ISSUE THREAD

**Issue by markrankin** [transmission/transmission#5485]
### What is the issue?

Hi,

I'm using an old Intel Macbook Air (see attached) with Transmission 4.0.3. When I have 3 transfers downloading, if I select 2 and click the pause button, all 3 transfers stop. Why?

### How would I fix this?

Update your "Resume all transfers" button to work only on selected transfers if one or more transfers are selected.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by markrankin** [comment]
![Screen Shot 2023-05-02 at 6 14 09 AM](https://user-images.githubusercontent.com/2543657/235677656-0bf8e113-f4c2-4914-a74f-bb7b6e5e496a.png)
![Screen Shot 2023-05-02 at 6 14 45 AM](https://user-images.githubusercontent.com/2543657/235677664-d57beddb-c1f6-4957-b918-2cfda29eedf3.png)

**Comment by nevack** [comment]
Are you sure you use "Pause / Resume Selected"?

By default there's only "Pause / Resume All" controls in Toolbar.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8330119/236632458-7984d1f2-753d-4ee3-a051-b5f1c3b4e6df.png">

**Comment by markrankin** [comment]
Hi Dzmitry,

Thanks for making that clear. I was using the default buttons.

Feel free to close this issue.

Thanks,

Mark
