### ISSUE TITLE
Trasmission Mac hang when moving files

### ISSUE THREAD

**Issue by WoodpeckerBaby** [transmission/transmission#5486]
### What is the issue?

When a torrent is downloaded, and then you use UI to move the torrent to a new location, after selecting the location, and the shift starts, the UI will hang untill the transfer is complete, which can take 45 min or more if it's a large file. 

I can't check version number because it's hanging right now. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/2462
