### ISSUE TITLE
Add wireguard to transmission for macos

### ISSUE THREAD

**Issue by cellulosa** [transmission/transmission#5487]
### What is the issue?

hi there, I found [this (official) WireGuard implementation for iOS and macOS](https://github.com/WireGuard/wireguard-apple) and was looking to implement it to transmission.
Any hint on where it would make more sense to start looking at to implement it? On `libtransmission`?
Thanks

### Which application of Transmission?

macOS app

### Which version of Transmission?

master branch

**Comment by nevack** [comment]
Seems a bit odd to me to have any VPN protocol implementation inside Torrent client.
It is possible to use standalone VPN solution and AFAIK everybody just uses it like that.

**Comment by cellulosa** [comment]
My use-case is that by doing so a user would be sure to bind Transmission to a secure connection. This whilst keeping browsing on a non-VPN connection with other apps.
