### ISSUE TITLE
Settings don't save after restarting client 

### ISSUE THREAD

**Issue by AK220011** [transmission/transmission#5492]
### What is the issue?

When settings are set and the client is restarted they go back to default. Workaround is going into user folder into appdata and changing the .json setting folder manually using notepad. Using windows 11 up to date.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.3 (6b0e49bbb2)

**Comment by mikedld** [comment]
This looks a lot like #5302.

**Comment by Radha-Mohan** [comment]
I am unable to understand what you are saying!

> ### What is the issue?
> When settings are set and the client is restarted they go back to default. Workaround is going into user folder into appdata and changing the .json setting folder manually using notepad. Using windows 11 up to date.
> 
> ### Which application of Transmission?
> Qt app on Windows
> 
> ### Which version of Transmission?
> Transmission 4.0.3 ([6b0e49b](https://github.com/transmission/transmission/commit/6b0e49bbb296f1c84785275b8a8f18b4210180af))

**Comment by Radha-Mohan** [comment]
> ### What is the issue?
> When settings are set and the client is restarted they go back to default. Workaround is going into user folder into appdata and changing the .json setting folder manually using notepad. Using windows 11 up to date.
> 
> ### Which application of Transmission?
> Qt app on Windows
> 
> ### Which version of Transmission?
> Transmission 4.0.3 ([6b0e49b](https://github.com/transmission/transmission/commit/6b0e49bbb296f1c84785275b8a8f18b4210180af))

@transmission-bot this is unethical, my query was deleted before it was answered!

**Comment by mikedld** [comment]
@Radha-Mohan, your comment made no sense and didn't add anything valuable to the discussion (neither does the new one) and honestly looked like spam. This ticket was closed more than a year ago as a duplicate, there's no point in commenting in it unless you want to get banned.

**Comment by Radha-Mohan** [comment]
> @Radha-Mohan, your comment made no sense and didn't add anything valuable to the discussion (neither does the new one) and honestly looked like spam. This ticket was closed more than a year ago as a duplicate, there's no point in commenting in it unless you want to get banned.

I just want to know about the settings comment, i.e. what changes to be made so that transmission qt saves the settings...
