### ISSUE TITLE
When closing client it does not close every time instead it's still active in background

### ISSUE THREAD

**Issue by AK220011** [transmission/transmission#5494]
### What is the issue?

When closing client it sometimes ends process, sometimes it takes 30 seconds for it to close itself and sometimes I have to "end task" otherwise it doesn't close. Using windows 11 up to date.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 4.0.3 (6b0e49bbb2)

**Comment by mikedld** [comment]
Looks like a duplicate of #287.
