### ISSUE TITLE
"Port is closed" is incorrectly shown

### ISSUE THREAD

**Issue by dreua** [transmission/transmission#5496]
### What is the issue?

Edit -> Preferences -> Network -> Test Port:

It always results in "Port is closed" no matter what I do. https://www.canyouseeme.org/ however shows "success" for the same port, therefore I believe Transmission is doing something wrong in the port check. (Maybe it looks for the wrong IP address or the API changed, idk. Can I enable verbose/debugging output for the port check specifically?)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3 (6b0e49bbb2) [On Fedora 38]

**Comment by Jack20947** [comment]
Same behaviour in Mac.
Transmission 4.0.3 and MacOS 10.13.6

**Comment by dreua** [comment]
Just found this in the portcheck repo: https://github.com/transmission/portcheck/issues/7

**Comment by theirongiant82** [comment]
This is still broken in Transmission 4.0.4 on macOS 12.6.8 (Monterey).  My ISP does not assign IPv6 addresses, and my router does not support IPv6 port mapping as far as I'm aware.  Other applications with statically mapped or UPnP ports continue to work: namely, Plex Media Server, Air Video Server HD, and my Synology NAS.  Only Transmission has a problem.

**Comment by bradtchapman** [comment]
Hello @ckerr .  Would this enhancement / bug fix for the port detection issue also resolve #6363, including the 8 other issues I referenced in the body of the post?

Thanks in advance.
