### ISSUE TITLE
Request upgrade to higher version of "BitComet"

### ISSUE THREAD

**Issue by DeckerCHAN** [transmission/transmission#55]
When I uploaded torrent file and start download, there always some "padding file" with file name "_____padding_file_0_if_you_saw_this file，please_upgrade_to_BitComet_v0.85_or_higher____"

**Comment by JohnClay** [comment]
This is an issue with your tracker, not an issue with Transmission.

**Comment by kirbyzhou** [comment]
This is not an issue with tracker, it is feature of BitComet.
BitComet will insert dummy padding files with zero-filled content into its torrent files.
This files are useless, and its filename starts with "_____padding_file_".

**Comment by Skaronator** [comment]
#579

**Comment by fjqingyou** [comment]
hope add a global ignore file, 

be similar to .gitignore

user can config it
