### ISSUE TITLE
[request] libadwaita support

### ISSUE THREAD

**Issue by gmankab** [transmission/transmission#5500]
libadwaita is amazing

**Comment by CapeCrusader321** [comment]
> libadwaita is amazing

Its amazing no doubt but its a library centred  around gnome, libadwaita is preferred by apps wishing to become part of gnome circle, Other than gnome no other Gtk DE currently supports it.
**Personal views

**Comment by gmankab** [comment]
@CapeCrusader321, libadwaita apps are not depends on gnome, they work on every de, every disto, and also on windows

**Comment by CapeCrusader321** [comment]
> @CapeCrusader321, libadwaita apps are not depends on gnome, they work on every de, every disto, and also on windows

@gmankab 
What i meant is its gnome centric, and may work in other DEs like Xfce,Mate etc. but it cant be themed with mate preference centre or xfce settings etc, one need to use _**gnome tools like gsettings**_ to switch dark and light mode for libadwaita apps, i dont understand why should gtk projects targetting non-gnome DEs should even use libadwaita, libadwaita was built by gnome for Gnome DE even if it works for other DEs, i think gtk 4 is enough, if transmission isnt try to be gnome exclusive ??

**Comment by gmankab** [comment]
ok i undersood

**Comment by joao-arthur** [comment]
I personally use gnome with a dark theme, and it is quite unpleasing that almost all the apps that I use respect the dark mode of the system. I understand that Transmission is generic, not a gnome app, but doesn't a dark theme make sense?

**Comment by tragivictoria** [comment]
>    The GTK interface has been carefully written to follow the GNOME Human Interface Guidelines and features. 

Copied from Transmission website.
