### ISSUE TITLE
I can not see the loading and unloading icons

### ISSUE THREAD

**Issue by arodu** [transmission/transmission#551]
![captura de pantalla_2018-03-12_18-04-14](https://user-images.githubusercontent.com/12447690/37312084-0a7d9012-2620-11e8-9ced-51f3dad105ff.png)

transmission-gtk 2.93
OS: Manjaro 17.1.6 Hakoila
DE: Xfce4
WM: Xfwm4

**Comment by mikedld** [comment]
@arodu, there have been some changes since 2.93. Might be the font you're using is missing the needed glyphs, but could you still check with current `main`?
