### ISSUE TITLE
Consider updating FMT to 10.0.0

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5511]
https://github.com/fmtlib/fmt/releases/tag/10.0.0

### Which application of Transmission?

All

### Which version of Transmission?

4.1

**Comment by GaryElshaw** [comment]
Output during make.

[fmt-10.txt](https://github.com/transmission/transmission/files/11468516/fmt-10.txt)

**Comment by GaryElshaw** [comment]
Just a heads up on something i saw being added to the fmt readme.

`clang-tidy <https://clang.llvm.org/extra/clang-tidy/>`_ v17 (not yet
released) provides the `modernize-use-std-print
<https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-std-print.html>`_
check that is capable of converting occurrences of ``printf`` and
``fprintf`` to ``fmt::print`` if configured to do so. (By default it
converts to ``std::print``.)

**Comment by ckerr** [comment]
@GaryElshaw we won't be hitting that for years, most likely. Transmission is still targeting C++17; `std::print` is in C++23 :smile_cat:
