### ISSUE TITLE
Qt: Awful contrast/theme colors

### ISSUE THREAD

**Issue by sfan5** [transmission/transmission#5512]
### What is the issue?

![grafik](https://github.com/transmission/transmission/assets/1042418/252a0010-78ac-42f5-99fb-8143a79d35ab)

This was tested on a freshly installed Arch Linux VM with Xfce left 100% at its default settings. The system theme is Adwaita.
This doesn't change based on which Qt style you set.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

Transmission 4.0.3 (6b0e49bbb2)

**Comment by GaryElshaw** [comment]
Out of curiosity, looking at the toolbar, is qt-svg installed?

**Comment by sfan5** [comment]
Yes, qt6-svg was installed.

**Comment by CapeCrusader321** [comment]
> Yes, qt6-svg was installed.

What is the packaging format ??

**Comment by CapeCrusader321** [comment]
> > Yes, qt6-svg was installed.
> 
> What is the packaging format of transmission ??

**Comment by sfan5** [comment]
https://archlinux.org/packages/extra/x86_64/qt6-svg/
https://archlinux.org/packages/extra/x86_64/transmission-qt/

**Comment by likeaross** [comment]
Adding to this, the qt6 dark theme the wonky colors are more pronounced:

![Screenshot from 2023-06-12 10-53-34](https://github.com/transmission/transmission/assets/483960/be871950-5b83-447c-b3e6-c78462648191)
![Screenshot from 2023-06-12 10-53-20](https://github.com/transmission/transmission/assets/483960/ee1ea53f-5179-43e2-b492-8a9c2867ab77)

**Comment by ekce** [comment]
> With the qt6 dark theme, the wonky colors are more pronounced:
> 
> ![Screenshot from 2023-06-12 10-53-34](https://user-images.githubusercontent.com/483960/245227613-be871950-5b83-447c-b3e6-c78462648191.png) ![Screenshot from 2023-06-12 10-53-20](https://user-images.githubusercontent.com/483960/245227619-ee1ea53f-5179-43e2-b492-8a9c2867ab77.png)

I fixed this on my end by using kvantum and setting the theme in qt6ct (I use the materia-dark theme in kvantum, if that matters at all).

**Comment by likeaross** [comment]
Great advice @ekce. I was missing the environment variable `QT_QPA_PLATFORMTHEME=qt6ct`.
I stuck with the fusion theme in qt6ct, cloned the darker theme and tweaked it to be [closer to the libadwaita dark colors](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/named-colors.html).

![Screenshot from 2023-08-06 02-55-17](https://github.com/transmission/transmission/assets/483960/3623aec8-d5aa-4085-89fc-045b7da8cde3)

**Comment by mikedld** [comment]
We're not modifying palette ourselves in any way (and aren't planning on it). This should be solved either in the theme/style you're using or in Qt.

**Comment by sfan5** [comment]
I find that hard to believe given no other Qt application had the same issue.
But doesn't matter as it this doesn't happen on my system anymore. Perhaps been fixed in 4.0.4 or 4.0.5?

**Comment by mikedld** [comment]
> I find that hard to believe given no other Qt application had the same issue. But doesn't matter as it this doesn't happen on my system anymore. Perhaps been fixed in 4.0.4 or 4.0.5?

You don't have to believe me, the source code is available and you're free to try and find proof. If/when you do find it, I'll be more than glad to hear about it. I'm not aware of any changes in 4.0.4 or 4.0.5 that would affect this.
