### ISSUE TITLE
i can't download anymore from 4.0.3

### ISSUE THREAD

**Issue by malcolve** [transmission/transmission#5544]
### What is the issue?

so i updated my transmission from v3 to v4.0.3 and now, i can't download anything.

![screenshot](https://github.com/transmission/transmission/assets/134119870/6b6c30a1-20ff-4f3c-a15c-05e24184196e)

please help

thanks

:)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

**Comment by malcolve** [comment]
and, i didn't do anything on my settings. i just leave it to default

**Comment by ckerr** [comment]
Closed + user banned as per [issue template instructions](https://github.com/transmission/transmission/blob/main/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml). 

> **YOU WILL BE BANNED** if you include information about pirated torrents.
