### ISSUE TITLE
Multiple daemon instances

### ISSUE THREAD

**Issue by leewdch** [transmission/transmission#555]
Sorry if this has been asked already but I prefer asking here directly instead of trusting random blog posts on the internet.. Right now I'm running a transmission daemon in, let's say, `.config/transmission1-daemon`. This daemon is started with a systemd service like this one:

```
[Unit]
Description=Transmission BitTorrent Daemon
After=network.target

[Service]
User=mynick
Type=notify
ExecStart=/usr/bin/transmission-daemon -f --log-error
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

How am I supposed to run another daemon? I just copied the config folder making a new one named `.config/transmission2-daemon` and changed all the ports inside adding +1 to the already existing ports.. is that ok? Can I use the same systemd service to run multiple transmission daemons at once? or maybe I'm supposed to use a service specific for each daemon? something like `/usr/bin/transmission-daemon -g /home/mynick/.config/transmission2-daemon -f --log-error` maybe?

Final systemd service:

```
[Unit]
Description=Transmission BitTorrent Daemon
After=network.target

[Service]
User=mynick
Type=oneshot
ExecStart=/usr/bin/transmission-daemon -f --log-error
ExecStart=/usr/bin/transmission-daemon -g /home/mynick/.config/transmission2-daemon -f --log-error
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by 8549** [comment]
Systemd supports specifiers in unit files, so you can modify your service like this:
```
[Unit]
Description=Transmission BitTorrent Daemon (%i instance)
After=network.target

[Service]
User=mynick
Type=notify
ExecStart=/usr/bin/transmission-daemon -f --log-error -g /home/mynick/.config/%i
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
```
If you service file is called, for example, `transmission@.service` you can then launch multiple instances of the daemon like this:
`systemctl start transmission@foo`
`systemctl start transmission@bar`
transmission-daemon will use /home/mynick/.config/foo and /home/mynick/.config/bar as config folders, respectively.
The `@` in the service name is needed for the specifiers, don't forget it!

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
