### ISSUE TITLE
Transmission lets you rename one of a torrent's files to match another of the torrent's files

### ISSUE THREAD

**Issue by basilefff** [transmission/transmission#5555]
### What is the issue?

I have encountered a bug. If you rename a file to have exact same filename as another file in the same torrent it will let you. And if you then close and reopen properties, it will contain only one file with that name.

I believe this bug to be in libtorrent itself. [This issue](https://github.com/transmission/transmission/issues/909#issue-444983198) clearly references the same bug in Qt version of the application.

When I look at the documentation, tr_torrentRenamePath function is supposed to return EINVAL when attempting to rename to existing filename, but it doesn't do that, and there are no tests checking that.

I can try to fix this bug myself, if needed.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.1.0-dev (87472672a6)

**Comment by basilefff** [comment]
> Same thing as `mv` in Linux. Transmission assumes you know what you are doing. Why would you ever do that?!? So no stupid user protection included.

It is an incorrect state, in which transmission shows one less file, than torrent actually has. The problem isn't files being overwritten, it is incorrect state of the torrent. Also, usually GUI applications have protections against these sort of things.

**Comment by killemov** [comment]
Ah, I missed that one. Same answer as here though. And yeah, still no answer as to why. The filenames are actually part of the torrent hash calculation. Renaming files is a convenience Transmission is offering so don't abuse it.

And congratulations on your issue being [Interstella](https://www.imdb.com/title/tt0368667)!

**Comment by basilefff** [comment]
> And congratulations on your issue being [Interstella](https://www.imdb.com/title/tt0368667)!
Thanks!

>  And yeah, still no answer as to why.
I am very sorry, can you explain what you mean here? You mean why I want this change or why the bug is happening?

**Comment by killemov** [comment]
> If you rename a file to have exact same filename as another file in the same torrent

This. So don't. You are willfully breaking stuff ... and Transmission lets you. So like `mv` in the sense that it lets you overwrite stuff without complaining.

**Comment by nevack** [comment]
BTW

> I believe this bug to be in libtorrent itself.

Do you mean `libtransmission` here? As Transmission is not based on `libtorrent`.

> I can try to fix this bug myself, if needed.

You're welcome.
But what really do you wanna fix here?
Like, make it present some user-visible error or something else?

**Comment by basilefff** [comment]
> Do you mean `libtransmission` here? As Transmission is not based on `libtorrent`.

Yes, I meant libtransmission.


> But what really do you wanna fix here?
> Like, make it present some user-visible error or something else?

Well, GUI already presents user-visible error if you try to rename to `.`, `..`  or name including path separator, like `foo/bar`

```
 *   If oldpath can't be found in files[*].name, or if newname is already
 *   in files[*].name, or contains a directory separator, or is nullptr, "",
 *   ".", or "..", the error argument will be EINVAL.
```

This is what documentation in libtransmission/transmission.h says tr_torrentRenamePath should be doing, and that's just not what it does. If tr_torrentRenamePath actually returned EINVAL in case of renaming collision, GUI would just show already existing error

**Comment by ckerr** [comment]
I do feel like this is kind of a "doctor, it hurts when I hit myself" kind of a ticket and probably am not going to prioritize this on my personal TODO list, but if someone wants to dig into `libtransmisson/torrent.cc`'s `namespace rename_helpers` functions and add error-checking for this I'd be happy to do code review.

**Comment by basilefff** [comment]
> I do feel like this is kind of a "doctor, it hurts when I hit myself" kind of a ticket and probably am not going to prioritize this on my personal TODO list, but if someone wants to dig into `libtransmisson/torrent.cc`'s `namespace rename_helpers` functions and add error-checking for this I'd be happy to do code review.

I tried to resolve it this in [this PR](https://github.com/transmission/transmission/pull/5563), can you review it?

**Comment by ckerr** [comment]
@basilefff sure! Thanks for the link. I should've seen that PR but didn't.
