### ISSUE TITLE
Is BEP0053 supported for hybrid and v2 torrents?

### ISSUE THREAD

**Issue by kovalensky** [transmission/transmission#5558]
### What is the issue?

File indices for v2/hybrid torrents are miscalculated, Transmission will fail to set them correspondingly.

Adding f.e. &so=0,5,7 to the magnet link, won't set downloading of those files corresponding to `file tree` metadata or `files` list (indices for padding files discarded of course), it will set downloading for all of them.

Currently I'm in the process of making of the tool to get rid of duplicates before downloading via magnet links for v2/hybrid .torrent files, to my regret I can't use this feature as thought.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by killemov** [comment]
Related to #5582

**Comment by kovalensky** [comment]
I assume that the developers are not eager to answer issues, my other issue also remained unanswered.

> Related to #5582

**Comment by kovalensky** [comment]
> Related to #5582

I assume that the developers are not eager to answer issues, my other issue also remained unanswered.
