### ISSUE TITLE
How to make Transmission finish individual files as fast as possible

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#556]
Picture the following situation:

- I'm downloading X (eg. 5) torrents simultaneously
- These torrents each have Y (eg. 3) individual files
- Each of the X*Y (15) files can be used by the user independently of the other files
- Some of the torrents are fast, others are slow

Obviously I would like to maximise my bandwidth its use to download torrents as quickly as possible. But, let's say I have the additional goal:

I want _as many individual files to finish as quickly as possible_, rather than having all the torrents competing equally for the total available bandwidth, thus making individual files finish equally slow.

How do I set up Transmission to intelligently do this? My current and rather tedious workaround is:

1. Start all the torrents
1. Order torrents by completeness
1. In each torrent, put one file as "High" priority, one as "Normal" and the rest as "Low".
1. Pause some torrents so that the few fastest ones use all the available bandwidth.
1. Leave slow torrents be, because they eat little bandwidth, and just need time to finish.
1. Repeat 3-5 periodically

This is a lot of fiddling, and I'm thinking this sort of thing ought to be solvable by computer logic. Does Transmission have smart functionality for this, or can we discuss how it could be implemented?

**Comment by forthrin** [comment]
Anyone? It's been a year since the issue was opened.

**Comment by ymte** [comment]
Wouldn't this harm the bittorrent network?

**Comment by forthrin** [comment]
Someone asked: "Wouldn't this harm the bittorrent network?" Possibly, if everyone did it. However, if it's not a default, most people won't do it, at least not at the same time. Some people might have other priorities to how they want their downloads to be prioritised. Given, I don't know the torrent protocol in detail, so I don't know how vulnerable it is to interfering with the order in which pieces are shared.

**Comment by forthrin** [comment]
Evidently, no-one is reading these issues.
