### ISSUE TITLE
Wrong tooltip color

### ISSUE THREAD

**Issue by emperor06** [transmission/transmission#5561]
### What is the issue?

Possibly related to #5140 

I'm using Transmission-gtk and Cinnamon with Mint-Y-Dark-Teal theme.
With this theme, tooltips are supposed to be dark-grey on yellow background but since 4.0.1 (or was it 4.0.2?), Transmission displays the tooltips with white color on yellow background.

![5e8514f3c917f1638dfee60b74c23e223e816e43](https://github.com/transmission/transmission/assets/9116243/a46ca1fa-0591-4b68-b7f3-23e9f5a409bc)

Here's the tooltip definition in /usr/share/themes/.../gtk-4.0/gtk.css
```
tooltip {
  color: #4a4a4a;
  border-radius: 2px;
  border: 1px solid #d0d0d0; }
  tooltip.background {
    background-color: #fbeaa0;
    background-clip: padding-box; }
    tooltip.background label {
      padding: 4px; }
```

If I change the tooltip.background's color to dark grey, the tooltips are ok in Transmission (white on dark grey). Note that the tooltip's color does not matter. It seems like Transmission is not using it at all (it stays white no matter what).

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3

**Comment by ckerr** [comment]
The button is just a GtkToggleButton with an embedded GtkImage. I don't see anything in the .ui file about that tooltip, so I don't think this is a Transmission issue.

My *guess* is that it's some kind of conflict between your theme and GTK4. 

If I'm wrong and there is something to address in Transmission, please let me know.
