### ISSUE TITLE
Transmission Web Interface not working

### ISSUE THREAD

**Issue by Infallibleman** [transmission/transmission#5566]
web interface is not working.  says "safari cant open the page"

Version: 4.0.3 (6b0e49bbb2)

**Comment by Petrprogs** [comment]
Did you [visit](https://github.com/transmission/transmission/blob/main/docs/Web-Interface.md) this link for docs about Transmission WE?

**Comment by Infallibleman** [comment]
yes.  it was working before.  does not work now.

**Comment by ckerr** [comment]
@Infallibleman what version of Safari are you using?
