### ISSUE TITLE
transmission-remote only lists every other label

### ISSUE THREAD

**Issue by rsekman** [transmission/transmission#5571]
In the loop where `transmission-remote` lists labels of torrents, the index is increased both in the for loop itself and when reading the label to print.

https://github.com/transmission/transmission/blob/61679e1adc680c210c553aa62898c12d8035af00/utils/remote.cc#L952-L954

The result is that only the zeroth, second, fourth, ... labels are printed
The fix is obvious; remove the increment operator inside the loop (and adjust the conditional for the formatting).

**Comment by killemov** [comment]
Weird bug to be introduced in the first place. Does this code not get scanned by a linter or something similar? It would have pointed out changing the loop variable within the loop.
