### ISSUE TITLE
Language auto-select is a misfeature

### ISSUE THREAD

**Issue by me-dog** [transmission/transmission#5576]
I'd like to request that language pack is *not* auto-selected. I don't want a half-completed, sometimes incomprehensible UI with strings I can't google. Please allow me to control what language my software speaks to me.

**Comment by killemov** [comment]
For web the language header should be followed with an optional configuration setting that takes precedence.

**Comment by ckerr** [comment]
duplicate of https://github.com/transmission/transmission/issues/1152, I think
