### ISSUE TITLE
59 PR's

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5577]
### What is the issue?

Hi guys, @mikedld and @livings124 i've noticed the project has lulled in Charles' absence and hope Charles is okay. In his absence, could one of you please take a look at the backlog of PR's, or designate a contributor (not me) to be able to merge them?

**Comment by killemov** [comment]
I have noticed his absence as well and hope he's okay as well. In the old Trac days month would go by without any news and even the forum has been quite quiet for longer periods. It is probably currently such a period meaning that actual life takes priority. So ... No-news-summer?

Or ... it is time to strategize next steps.

**Comment by ckerr** [comment]
ffs I'm not dead I'm just busy with dayjob.

**Comment by ckerr** [comment]
![giphy-3275798878](https://github.com/transmission/transmission/assets/70381/925cc2a7-aaf9-4e77-a6b1-275a1f69e56c)

**Comment by ckerr** [comment]
@shivanshu3 tentatively Aug 8
