### ISSUE TITLE
torrent files become *.part

### ISSUE THREAD

**Issue by arthackrc** [transmission/transmission#5579]
### What is the issue?

as the title said. all torrent files become *.part. I used renamer to change it all, but when I do check the hash it's a mismatch.

### Which application of Transmission?

Qt app on Windows

**Comment by valcomm** [comment]
Not fully downloaded files get ".part" suffix.  When the file is complete, it gets renamed to the proper name.
You changed the name of incomplete file and hence hash if it is different from what's expected.  You shouldn't have done that
