### ISSUE TITLE
option to disable appending the ".added" suffix to added torrents

### ISSUE THREAD

**Issue by bananakid** [transmission/transmission#5581]
### What is the issue?

Transmission lacks UI/CLI toggle to turn off adding `.added` suffix to filename extension when `.torrent` file is added to Transmission 4.0.0-4.0.3 in Windows 10, i.e. `Torrent.torrent` gets renamed to `Torrent.torrent.added` when added to Transmission using drag-n-drop or double-click from File Explorer. Changing filename of original torrent file should not be mandatory. AFAIK this is regression from 2.94 and 3.0.0 first introduced in 4.0.0. Current behavior may be considered as a bug.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
Ok. Then copy the original torrent to the watch dir and remove it when it has the suffix.

**Comment by bananakid** [comment]
> Ok. Then copy the original torrent to the watch dir and remove it when it has the suffix.

Thanks, I can also use batch script for opening .torrent file (by altering Windows Registry entry) to change filename back. But to me it appears to be incorrect way to handle usability for average Joe.

**Comment by killemov** [comment]
IF we are not talking about the watch dir but about manually adding a torrent (drag+drop or from file selector) then I would characterize this as a bug. But if we are talking about the watch dir then this is by design.

**Comment by killemov** [comment]
> But it may become a feature if UI toggle is implemented.

DON'T make your bug your feature this time. Manually added torrents should never have the filename changed.

**Comment by ckerr** [comment]
Looks like this is only happening in the Qt client.

The GTK client specifically only renames files that have been added via the watchdir. The Qt client should do the same.

**Comment by Spleeen** [comment]
please stop this it's really annoying to have to do it manually

**Comment by ckerr** [comment]
I think #5705 should fix this, if anyone wants to give it a test

**Comment by roryyamm** [comment]
I'd still prefer a dedicated option to disable it entirely. I generate torrents automatically, and liked that in previous versions I could both have them be added automatically AND use them again in other applications without manually renaming them. The .added 'feature' is very annoying, as now I have to manually rename every torrent file that gets added.

**Comment by ckerr** [comment]
@roryyamm how do you add those generated torrents?

**Comment by roryyamm** [comment]
I have it automatically add torrents from a directory, but in the past, the torrent options dialog would prevent .added from being… well, added. That doesn't seem to work now.
