### ISSUE TITLE
Torrent list with ETAs greater than 999 days gets misaligned

### ISSUE THREAD

**Issue by lvd2** [transmission/transmission#5583]
### What is the issue?

The torrents with ETA that is greater than 999 days have misaligned columns in the output of `transmission-remote -t`.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

Any, up to 61679e1

**Comment by killemov** [comment]
Do we need both the issue and the pull request?

**Comment by lvd2** [comment]
What's wrong with having both the issue and the corresponding pull request fixing it?

**Comment by ckerr** [comment]
I'm not sure but this might be the first issue to get the `scope:remote` and `type:ui` labels. Achievement unlocked, @lvd2!
