### ISSUE TITLE
showing ? where download size should be, not starting download

### ISSUE THREAD

**Issue by ttobmister** [transmission/transmission#5592]
### What is the issue?

so my problem is, alot of the torrents i try and download definitly have seeders but transmission is just showing a ? where the size should be and not starting the download. why?
![image](https://github.com/transmission/transmission/assets/41894984/62b1757e-036f-437e-851d-895f01f4ce1c)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Transmission 3.00

**Comment by killemov** [comment]
I suspect those torrents are magnets and the metadata (including size) hasn't downloading yet.
Related to #5150?

**Comment by ttobmister** [comment]
they where added to transmission by sonarr and they didnt download the metadata after about 3 hours of sitting there.

**Comment by killemov** [comment]
So the issue is actually 'Metadata is not fetched within a reasonable amount of time (3 hrs).'.

**Comment by Daniel6372** [comment]
Is the port transmission is using open in your firewalls? For two peers to be able to connect to each other, at least one of them has to have their port open, otherwise neither of them can connect to the other.

**Comment by ckerr** [comment]
Please upgrade to Transmission 4.0.x and file a new report if the problem persists.
