### ISSUE TITLE
refactor: consider a semantically-appropriate container for torrent labels

### ISSUE THREAD

**Issue by rsekman** [transmission/transmission#5598]
Currently the labels of a torrent have type `labels_t = std::vector<tr_quark>`. But there should be no duplicates, so it would be more semantic to let `labels_t = std::set<tr_quark>` .
This would let the standard library take care of  duplicate checking:
https://github.com/transmission/transmission/blob/0ef58c2a20019096aed0ab639f2207b8e1c1b248/libtransmission/torrent.cc#L1962
In fact, it can be propagated up the call stack to https://github.com/transmission/transmission/blob/0ef58c2a20019096aed0ab639f2207b8e1c1b248/libtransmission/rpcimpl.cc#L971-L973
such that a `set` is constructed to begin with, and `setLabels` becomes just a setter.

Duplicate checking has log asymptotic complexity for `set` but linear for vector. On the other hand there are usually few labels. On the third hand this function is probably not called all that often. On the fourth hand there is some memory overhead to using a `set`, but again, the number of labels is usually small. So the code would be cleaner but the performance implications are unclear.

In any case, the functions in this call stack should probably all use `labels_t`  to be more semantic.

**Comment by xavery** [comment]
`tr_quark` is a `size_t` so the overhead of using `std::set` would be quite significant.

`std::unordered_set` might be more fitting here but perhaps the easiest way to do this would be to sort the labels vector when created, as this makes it possible to use `std::unique` to search for/eliminate duplicates, and `std::binary_search` for lookups.

**Comment by ckerr** [comment]
Y'all are both right about the semantics.

The reason I chose a `std::vector<tr_quark>` is just for memory overhead and locality. Both `std::set` and `std::unordered_set` use a tree implementation that is total overkill for holding data that, when all is said and done, is going to be a small handful of `size_t`s.

Something like [Chromium's base::flat_set](https://chromium.googlesource.com/chromium/src/+/HEAD/base/containers/flat_set.h) would be perfect here, with the semantics of a set and the small footprint of a vector.

I have been working on a refactor that adds https://github.com/alandefreitas/small as a third-party dependency. Maybe `small::set` would be the Right Thing to use here...

**Comment by ckerr** [comment]
As @Coeur correctly pointed out in https://github.com/transmission/transmission/pull/5612#pullrequestreview-1475683468, the ordering of these labels should be picked by the user (e.g. store them in the order added) rather than alphabetically or by tr_quark value. There's not  a good `set` container that does that, so `std::vector` is probably as good a container as we're going to get for this use case. :man_shrugging: 

I appreciate the good feedback and hope that y'all keep filing issues & doing reviews, but I think this small piece of the code is probably best off as-is.
