### ISSUE TITLE
Memory leaks found with AddressSanitizer

### ISSUE THREAD

**Issue by milloni** [transmission/transmission#56]
Running tests on AddressSanitizer (ASan)-enabled build of Transmission results in several of those tests failing.

Steps to reproduce:
- Build from master and run the tests

``` bash
$ git clone https://github.com/milloni/transmission.git
$ cd transmission
$ ./autogen.sh CFLAGS=-fsanitize=address CXXFLAGS=-fsanitize=address
$ make
$ make check 
```

This gives the following result (libtransmission/test-suite.log):
https://gist.github.com/milloni/b027e4e91b1ef1c15c5db56aab395a26

Platform info:
Fedora 24
Linux 4.7.5-200.fc24.x86_64
gcc 6.2.1
glibc 2.23

**Comment by mikedld** [comment]
Thanks, I'll take a look when I have time. In the meantime, PRs are welcome.

**Comment by cfpp2p** [comment]
> ==29778==ERROR: LeakSanitizer: detected memory leaks
> Direct leak of 448 byte(s) in 1 object(s) allocated from:
>` #0` 0x7fde657cb210 in realloc (/lib64/libasan.so.3+0xc7210)
> `#1` 0x446ac2 in tr_realloc /home/milloni/Code/transmission/libtransmission/utils.c:133
> `#2` 0x44e636 in containerReserve /home/milloni/Code/transmission/libtransmission/variant.c:526


**variant.c:526**
`v->val.l.vals = tr_renew (tr_variant, v->val.l.vals, n);`

The way _LeakSanitizer_ sees it,
if I am visualizing that correctly, if realloc
( via tr_renew() --> tr_realloc() )
fails then original `v->val.l.vals` is orphaned
and hence memory leak.

**Comment by mikedld** [comment]
@cfpp2p, `tr_realloc` is modelled after BSD `reallocf` which frees old memory if reallocation fails ;)
