### ISSUE TITLE
remote authentication

### ISSUE THREAD

**Issue by raako71** [transmission/transmission#560]
Is remote authentication just done with a plain text password? Is the connection secured with encryption? Can't seem to find an answer to this

**Comment by LaserEyess** [comment]
Any acces to RPC is, by default, unencrypted. That includes all clients, such as the QT client and transmission-remote. If you want to encrypt it you can reverse proxy transmission behind something like nginx, but otherwise transmission has no way of encrypting http traffic by itself.

**Comment by ckerr** [comment]
Closing duplicate of https://github.com/transmission/transmission/issues/1294
