### ISSUE TITLE
Possible Regression - Accessing Moved URLs

### ISSUE THREAD

**Issue by teeks99** [transmission/transmission#5603]
### What is the issue?

When running the latest commit on main today (0ef58c2a20019096aed0ab639f2207b8e1c1b248), I got an error when attempting to open a URL to a torrent that actually pointed to a redirecting link. 

```
transmission-remote {host} --auth {user}:{password} --add https://download.kiwix.org/zim/wikispecies_en_all_maxi.zim.t
orrent --download-dir {path}
Error: Couldn't fetch torrent: No Response (0)
```

I believe this is a current regression on main, as going over to the 4.0.x branch caused the issue to go away.

```
transmission-remote {host} --auth {user}:{password} --add https://download.kiwix.org/zim/wikispecies_en_all_maxi.zim.t
orrent --download-dir {path}
{host}:9091/transmission/rpc/ responded: "success"
```

The other factor that I have a strong feeling is relevant is that, tn this case, that URL is a 301 redirect to another URL:

```
$ curl -v https://download.kiwix.org/zim/wikispecies_en_all_maxi.zim.torrent 
*   Trying 51.159.108.60:443...
* Connected to download.kiwix.org (51.159.108.60) port 443 (#0)
<snip TLS stuff>
> GET /zim/wikispecies_en_all_maxi.zim.torrent HTTP/2
> Host: download.kiwix.org
> user-agent: curl/7.81.0
> accept: */*
> 
<snip TLS stuff>
< HTTP/2 301 
< date: Sun, 11 Jun 2023 02:25:47 GMT
< content-type: text/html; charset=iso-8859-1
< content-length: 287
< location: https://download.kiwix.org/zim/other/wikispecies_en_all_maxi_2023-05.zim.torrent
< cache-control: no-store, no-cache, must-revalidate
< strict-transport-security: max-age=15724800; includeSubDomains
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://download.kiwix.org/zim/other/wikispecies_en_all_maxi_2023-05.zim.torrent">here</a>.</p>
</body></html>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host download.kiwix.org left intact
```

I feel like this type of redirect is pretty common on open source mirror systems, so I wanted to raise this up before it gets too far along.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

main branch commit: 0ef58c2a20019096aed0ab639f2207b8e1c1b248

**Comment by killemov** [comment]
Maybe change the title to "Possible Regression - Accessing Moved URLs (HTTP 301)"

**Comment by tearfur** [comment]
@teeks99 Do you mind running `git bisect` and find out which commit caused it?

**Comment by teeks99** [comment]
I just went to try and bisect it, but it seems that something has fixed it on the mainline. I'll re-open if I ever see it again.

**Comment by Helyos96** [comment]
I am hitting this on main (ac5c9e082da257e102eb4ff18f2e433976a585d1): `Couldn't fetch torrent: No Response (0)`.

Unsure if this is because the URL is a redirect, or because it reports an unspecified length (`Length: unspecified [application/x-bittorrent]`). I get the same error with your link `https://download.kiwix.org/zim/wikispecies_en_all_maxi.zim.torrent`. wget and curl are able to fetch the file properly.

Also, while your link has a `301 Moved Permanently`, mine doesn't.

Some logs:

`trc rpcimpl.cc:1324 torrentAdd: HTTP response code was 0 (No Response); response length was 0 bytes (rpcimpl.cc:1324)`

```
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * Host download.kiwix.org:443 was resolved.
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * IPv6: (none)
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * IPv4: 51.159.101.162
Apr 21 17:05:00 ks2 transmission-daemon[21965]: *   Trying 51.159.101.162:443...
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * Hostname in DNS cache doesn't have needed family, zapped
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * Name '2001:<>::1' family 2 resolved to '2001:<>::1' family 10
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * Failed to connect to download.kiwix.org port 443 after 205 ms: Couldn't connect to server
Apr 21 17:05:00 ks2 transmission-daemon[21965]: * Closing connection
```

edit: fixed by setting my IP in `bind-address-ipv4`. Seems related to https://github.com/transmission/transmission/issues/7229.
