### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by clem9669** [transmission/transmission#561]
Hi all 😸 ,

My issue is Error: Permission Denied💀 
Indeed, my output folder is /mnt/hdd/torrent, i think this is the problem. So I tried to give all permissions to anyone and I change the owner from root to $user but not successful yet... 🤔 

Do you have an idea about it ? Would i tried to assign "transmission" as user ?

Cheers 🖥

**Comment by scriptzteam** [comment]
If i good remember try this ;)

**chown transmission-debian:transmission-debian /mnt/hdd/torrent/**

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
