### ISSUE TITLE
Wrong macOS interface image uploaded during .png compression

### ISSUE THREAD

**Issue by gw859060** [transmission/transmission#5621]
### What is the issue?

Commit #5586, which losslessly compressed a few dozen .png files, seems to have accidentally replaced [ActionHover@2x.png](https://github.com/transmission/transmission/blob/main/macosx/Images/Images.xcassets/ActionHover.imageset/ActionHover%402x.png) for macOS with an unrelated image ([link to comparison](https://github.com/transmission/transmission/commit/0ef58c2a20019096aed0ab639f2207b8e1c1b248#diff-14cc84016bc2131675d0dc4d325870c3ebb7cd1c92dfbdb49fee0844966f61ec)). It should be a down arrow inside a circle, like ActionHover.png, but is instead currently a screenshot of Transmission's dropdown menu with "Settings..." highlighted.

<img width="1118" alt="SCR-20230614-pnwa" src="https://github.com/transmission/transmission/assets/70682725/b610ba13-8821-4959-9846-027a169ecb26">

Apologies if this report isn't formatted correctly - I am new to contributing on GitHub.

### Which application of Transmission?

macOS app

**Comment by mikedld** [comment]
Not the only case, e.g. https://github.com/transmission/transmission/commit/0ef58c2a20019096aed0ab639f2207b8e1c1b248#diff-ec4091398a2633b0ccc37e4255d1f5698f31321405cf8863a62521cd59a48956 is wrong as well. Need to verify all images.

**Comment by GaryElshaw** [comment]
PR on its way.

**Comment by ckerr** [comment]
WTF. I'm not sure how this happened but obviously my mistake.

Sorry all for the regression & thanks for the PR @GaryElshaw

**Comment by ckerr** [comment]
- docs/resources/QT-Enable-Web-Win-3.png
- macosx/Images/Images.xcassets/ActionHover.imageset/ActionHover@2x.png

Looking at the [diffs](https://github.com/transmission/transmission/commit/0ef58c2a20019096aed0ab639f2207b8e1c1b248), these are the two that I see regressions in.
