### ISSUE TITLE
Feature Request: Implement OS Cache

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#5622]
### What is the issue?

As per discussion here: https://github.com/transmission/transmission/discussions/5183

Related libtorrent documentation here: 

>enable_os_cache
    Files are opened normally, with the OS caching reads and writes.
disable_os_cache
    This opens all files in no-cache mode. This corresponds to the OS not letting blocks for the files linger in the cache. This makes sense in order to avoid the bittorrent client to potentially evict all other processes' cache by simply handling high throughput and large files. If libtorrent's read cache is disabled, enabling this may reduce performance.
https://www.libtorrent.org/reference-Settings.html

Something that libtransmission needs to perform reliably on modern OS's. 

### Which application of Transmission?

None

### Which version of Transmission?

N/A

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/5668.

**Comment by Pentaphon** [comment]
> the equivalent of `disable_os_cache` is accomplished in 5668

@ckerr this feature request is about implementing an OS cache, though, not disabling it. 

The libtorrent documentation says: 

>disable_os_cache
This opens all files in no-cache mode. This corresponds to the OS not letting blocks for the files linger in the cache. This makes sense in order to avoid the bittorrent client to potentially evict all other processes' cache by simply handling high throughput and large files. If libtorrent's read cache is disabled, enabling this may reduce performance.

If the equivalent of `disable_os_cache` is accomplished in 5668 and enabling that "may reduce performance" then how is that helpful? 

Or am I reading this wrong and does bypassing the disk write cache when cache-size-mb is zero achieve the same as letting the OS do the caching? Also, if the OS is now doing the caching when cache-size-mb is zero, why not enable this setting by default for all users?

**Comment by ckerr** [comment]
@Pentaphon I think we may be talking past each other. What does "implementing an OS cache" mean to you; what specifically are you requesting?

**Comment by Pentaphon** [comment]
> What does "implementing an OS cache" mean to you; what specifically are you requesting?

Using the operating system's file cache, as in

>Enable OS cache — (default: enabled) Paraphrased from the libtorrent docs: enable for better performance, disable if you also disabled libtorrent's read cache, or to help preventing the operating system from growing its file cache indefinitely, or if you want to prevent qbittorrent from potentially evicting all other processes' cache (which may result in lower perceived system responsiveness).

https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent#user-content-libtorrentspecific_configuration

**Comment by tearfur** [comment]
@ckerr libtorrent's "OS cache" is acutally `mmap` behind the scenes.
@Pentaphon Just so you know, this is a big mess of a topic. This is already an long long on-going thread discussing solutions to the problems you want to fix at #2462.

https://github.com/arvidn/libtorrent/issues/6667#issuecomment-1040874903
https://github.com/arvidn/libtorrent/wiki/memory-mapped-I-O

**Comment by Pentaphon** [comment]
@tearfur I will just ask you directly: does Transmission currently have an "OS cache" as libtorrent has? If not, then I don't think this issue should have been closed. I could be wrong though. I am just asking people who are clearly more knowledgeable than I am.

**Comment by ckerr** [comment]
@Pentaphon I'll ask again, can you describe in your own words, without copy-pasting libtorrent's docs, what behavior libtorrent's OS cache has and which  libtransmission's caching does not, that is needed in order for "libtransmission needs to perform reliably on modern OS's"?

I feel like this feature request is very vague at the moment & that you're just saying "whatever libtorrent has, that's what we ought to have."

TBH the vagueness makes this request hard to even respond to.

**Comment by ckerr** [comment]
@Pentaphon I'll ask again, can you describe in your own words, without copy-pasting libtorrent's docs, what behavior libtorrent's OS cache has and which  libtransmission's caching does not, that is needed in order for "libtransmission needs to perform reliably on modern OS's"?

I feel like this feature request is very vague at the moment & that you're just saying "whatever libtorrent does, that's what libtransmission needs in order to perform reliably on modern OS's." without any details about the features nor any way of verifying any difference in disk performance.

I really don't know how to proceed with this request unless / until there are more details about what *specifically* is being requested and how *specifically* this will benefit disk performance.

**Comment by Pentaphon** [comment]
> Pentaphon I'll ask again, can you describe in your own words, without copy-pasting libtorrent's docs, what behavior libtorrent's OS cache has and which libtransmission's caching does not, that is needed in order for "libtransmission needs to perform reliably on modern OS's"?

Tearfur named `mmap` as what libtorrent does behind the scenes to improve efficiency of memory usage. Obviously, you are much more knowledgeable than I am, so I will just ask,: would ` mmap`or a similar solution benefit Transmission or not? If `mmap` or a similar solution would benefit Transmission, then that's what I am requesting.
