### ISSUE TITLE
transmission 2.84 Error: Unable to save resume file: No such file or directory

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#563]
Error: Unable to save resume file: No such file or directory
![1](https://user-images.githubusercontent.com/6442439/38025763-1beb40c6-32bc-11e8-8f0c-09470ad201d9.jpg)

**Comment by leewdch** [comment]
Do you have a `resume` folder in your transmission path? You can find your transmission path here https://github.com/transmission/transmission/wiki/Configuration-Files
