### ISSUE TITLE
make fails to compile third-party/googletest/googletest/src/gtest-all.cc.o on Ubuntu 22.04

### ISSUE THREAD

**Issue by holta** [transmission/transmission#5634]
### What is the issue?

Transmission doesn't compile at the moment, on Ubuntu 22.04

A week ago this worked:

```
apt install build-essential cmake libcurl4-openssl-dev libssl-dev libsystemd-dev
git clone https://github.com/transmission/transmission
cd transmission
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make
```

At the moment this fails (repeatedly) with error:

```
[ 30%] Building CXX object tests/gtest/CMakeFiles/gtestall.dir/__/__/third-party/googletest/googletest/src/gtest-all.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [tests/gtest/CMakeFiles/gtestall.dir/build.make:76: tests/gtest/CMakeFiles/gtestall.dir/__/__/third-party/googletest/googletest/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:624: tests/gtest/CMakeFiles/gtestall.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Which application of Transmission?

Trying to compile the "core 5" i.e.
{transmission-daemon, transmission-remote, transmission-create, transmission-edit, transmission-show}

### Which version of Transmission?

Branch [main](https://github.com/transmission/transmission), Commit 0fd7989 (from 1 hour ago)

### Background

- #5585
- #5362
- PR iiab/iiab#3599

**Comment by ckerr** [comment]
Transmission pulls Google Test directly from https://github.com/google/googletest.git to "live at head" in their repo as [suggested in their README](https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-live-at-head-and-how-do-i-do-it).

@holta could you try cloning a copy of https://github.com/google/googletest locally and building it to see if that works, without any Transmission in the mix?

**Comment by holta** [comment]
@ckerr your suspicion was correct.

Running the following...

```
git clone https://github.com/google/googletest
cd googletest
mkdir build
cd build
cmake ..
make
```

...failed with the exact same error:

```
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [googletest/CMakeFiles/gtest.dir/build.make:76: googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by ckerr** [comment]
@holta thanks for the confirmation. Please report this upstream to https://github.com/google/googletest/issues so the GTest maintainers will know about it and can fix it :smile_cat:

**Comment by holta** [comment]
Compiling [googletest](https://github.com/google/googletest) must be dependent on some kind of "hidden" online/upstream dependency:

- 3 identical Ubuntu VM's failed to compile googletest yesterday, in the exact same way — freezing (hanging) for about 5 minutes, before returning to the prompt, with the [error message](https://github.com/transmission/transmission/issues/5634#issuecomment-1596274639) pasted in above.
- Now about 24h later, 3 additional fully equivalent VM's work (Ubuntu 22.04, 2GB RAM) compile googletest successfully, in about 8 seconds each.

One hopes the googletest community understands (or is interested in solving) its own fragility here:

- google/googletest#4284

In any case, if only to document the mystery:

- googletest very mysteriously failed to compile (in the exact same way) on 3 different VM's yesterday.
- Today googletest compiles without problem on 3 new/equivalent VM's.
