### ISSUE TITLE
libfmt 10.0.0 warnings

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5637]
### What is the issue?

More of a headsup than anything. Transmission compiles, but fmt issues a warning for almost every single piece of code along the way.

Manjaro linux 
[fmt.txt](https://github.com/transmission/transmission/files/11783257/fmt.txt)

All of Transmission on Linux.

### Which version of Transmission?

4.1

**Comment by ckerr** [comment]
Please report this upstream to fmtlib; we're not modifying that code in any way so this is probably better handled upstream.

Closing this ticket since it's not fixable in `transmission/transmission` except maybe by reverting to fmt 9?

**Comment by GaryElshaw** [comment]
If i understand correctly, it's a gcc bug. https://github.com/fmtlib/fmt/issues/3497#issuecomment-1596526522
