### ISSUE TITLE
CLI should download to current directory by default

### ISSUE THREAD

**Issue by lmamane** [transmission/transmission#5638]
### What is the issue?

It is customary, and expected by users, that by default command-line "download programs" download to the current directory; when downloading multiple files it is useful to do it in a newly created subdirectory of the current directory.

That's how curl, wget, lftp, and countless others do it.

By contrast, out of the box transmission-remote/transmission-cli seems to create a directory in the user's home directory instead. This leads the poor user to wonder where the **** the downloaded files went, until days (if ever...) later (s)he stumbles on them by looking at hir home directory.

Please consider changing the default to (newly created subdirectory) of current directory.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

4.0.2

**Comment by valcomm** [comment]
This is not an application, but a server/client architecture.  Server download directory is defined in its config file.
You request has no sense.  Just imagine two or more logged in users ask server to download the same torrent.

**Comment by ckerr** [comment]
If there was some kind of a "trget" app I would definitely expect it to download into cwd just as wget, curl, etc. do.  And @lmamane's is right that many people do use transmission-cli as a "trget".

So both the argument and counterargument make sense to me. So what is the Right Thing to do here?

Since people have been using transmission-cli for over a decade now I'm going to vote for keeping the current default. Changign that would likely confuse _more_ people who are used to the old behavior.

**Comment by lmamane** [comment]
> Just imagine two or more logged in users ask server to download the same torrent.

Well, if two users (or even the same user doing two requests) ask for different things to happen, then technically there is nothing keeping the server from fulfilling these two different requests, even if they are about putting the same data in two different places. The same that would happen now if the two instances of transmission-cli are launched with different "-w" command-line options.

If you want to go into "just imagine" scenarios, we can talk about "what if the user running tranmission-cli doesn't have read access to the server's download directory", and "what if the server doesn't have write access to the directory requested by the user" (although in the latter case, in theory it could send the data to the client, and the client writes to disk?)

> Since people have been using transmission-cli for over a decade now I'm going to vote for keeping the current default.

That makes sense.

**Comment by valcomm** [comment]
> > Just imagine two or more logged in users ask server to download the same torrent.
> 
> Well, if two users (or even the same user doing two requests) ask for different things to happen, then technically there is nothing keeping the server from fulfilling these two different requests, even if they are about putting the same data in two different places. The same that would happen now if the two instances of transmission-cli are launched with different "-w" command-line options.

Nope, that's incorrect.  Only one torrent with one unique hashset could be downloaded at the same time.  Unless you're thinking about one specific case, where torrent data is being downloaded fast and another cli starts its download after the previous one is downloaded and removed from the daemon.
At the same time it looks like you're familiar with "-w" option - why not to specify it?  Lazy to do it every time?  Create an alias.
Of course daemon has to have rights to write to this directory.


> 
> If you want to go into "just imagine" scenarios, we can talk about "what if the user running tranmission-cli doesn't have read access to the server's download directory", and "what if the server doesn't have write access to the directory requested by the user" (although in the latter case, in theory it could send the data to the client, and the client writes to disk?)

The former case is covered by "--move" option.  Not a problem.
The latter case is confusing.  Client doesn't receive any torrent data from the daemon.  It only passes information about it.
Not sure how writing it to disks helps your case.

**Comment by lmamane** [comment]
> Nope, that's incorrect. Only one torrent with one unique hashset could be downloaded at the same time.

I wasn't aware that transmission can do only one download at a time, I'm surprised. Anyway, there is no fundamental reason that this single download cannot be written to two places, either as full copies or by hard links (each having their own advantages, disadvantages and limitations). Whether that is worth the effort to implement is another question altogether.

> At the same time it looks like you're familiar with "-w" option - why not to specify it? Lazy to do it every time?

Well, when transmission-cli didn't do what I expected, I read the man page. So *now* I now about it, but as a first-time user the first time I used it I got bitten by what I perceived as a weird unusual default. I was trying to suggest being more "first time user" friendly, ckerr explained that historical reasons prevail... OK, that's a valid choice, so this issue is closed.

The availability of an option to do "the thing a user expects" and/or possibility to create an alias for that is besides the point when the suggestion was not about "make something possible for users after they have read the documentation thoroughly", but "be more first-time-user friendly".

> The former case is covered by "--move" option.

Not documented, not in the man page and not in the "transmission-cli --help" output.

> The latter case is confusing. Client doesn't receive any torrent data from the daemon. It only passes information about it.

In theory, it could be possible to work around the daemon not having write access to the destination by having the server send "torrent data" to the client so that the client writes it do disk, not the server. However, that would be an architectural change in the client/server protocol, and may not be worth it and/or not the use case that transmission has in mind. And this has nothing to do with the (first) subject of this issue, it was going into a tangent of other "image if" scenarios.

> Not sure how writing it to disks helps your case.

My understanding of the whole purpose of transmission is to get data over the network and write it to disk storage, and share that data back over the network to other requesters of it. I don't think that keeping the data only in RAM would be the best choice.

**Comment by lmamane** [comment]
> > Not documented, not in the man page and not in the "transmission-cli --help" output.
> 
> ```
> transmission-remote --help
> transmission-remote 4.0.3 (6b0e49bbb2)
> A fast and easy BitTorrent client
> https://transmissionbt.com/
> ...
>       --move                           <path>            Move current torrent's
>                                                          data to a new folder
> ...
> ```

That's transmission-remote, not transmission-cli, which is/was the subject of discussion here.

```
user@host:~$ transmission-cli --help | grep move
userr@host:~$ 
```

> Transmission doesn't keep much data in RAM.

We seem to agree on that, but to misunderstand each other's messages. My understanding of the discussion is:
- You wrote you didn't understand how writing data to disk helps my use case
- I wrote writing data to disk is the whole point, and essential to pretty much any use case; I couldn't imagine any other place for data than in RAM, so given your suggestion of not writing it to disk, the alternative seemed to keep in it RAM and in RAM only, and I expressed that this did not seem a good idea.
- You write that transmission does not keep data in RAM, confirming it behaves as I expect it to.

I think we are veering quite far away from the original subject of this issue, and should maybe leave it at that?

**Comment by valcomm** [comment]
> > > Not documented, not in the man page and not in the "transmission-cli --help" output.
> > 
> > 
> > ```
> > transmission-remote --help
> > transmission-remote 4.0.3 (6b0e49bbb2)
> > A fast and easy BitTorrent client
> > https://transmissionbt.com/
> > ...
> >       --move                           <path>            Move current torrent's
> >                                                          data to a new folder
> > ...
> > ```
> 
> That's transmission-remote, not transmission-cli, which is/was the subject of discussion here.

Few points here.
In the very first post in this topic you wrote
`By contrast, out of the box transmission-remote/transmission-cli`
but now you're saying that subject was only about transmission-cli.  That's confusing.

Frankly speaking I wasn't aware about transmission-cli.  Its purpose for existing is puzzling me.  Was it a limited version before `transmission-remote` was created or is it just a simple demo of something?  I think this might be a good question to developers how is it different from `transmission-remote` and what's the benefit of having both of them at the same time.

> > Transmission doesn't keep much data in RAM.
> 
> We seem to agree on that, but to misunderstand each other's messages. My understanding of the discussion is:
> 
>     * You wrote you didn't understand how writing data to disk helps my use case

You probably skipped reading some parts of what I wrote.  I wrote that transmission server doesn't send torrent files content to the client.  It sends only information about it.  And that I'm not sure how writing this information about torrent files to disk by client would help your case.


> I think we are veering quite far away from the original subject of this issue, and should maybe leave it at that?

Well, I don't consider this as arguing.  It is more like educational.  At least for me.  I learned about existence of `transmission-cli` for example.  I hope you learned something too here.  But if you wish to end this, I'm totally fine with it.
