### ISSUE TITLE
Limit input width in Add dialog of Web

### ISSUE THREAD

**Issue by ai** [transmission/transmission#5639]
### What is the issue?

1. Open Transmission Web
2. Click `Add` icon to show new torrent dialog
3. Set `.torrent` file with long name

Actual result:

`<input>` field became longer than dialog width. UI looks broken.

Expected result:

`<input>` field is limited. You can’t see all file name but UI doesn’t look broken.

![Captura desde 2023-06-19 14-06-08](https://github.com/transmission/transmission/assets/19343/abebe2cc-bbd8-4c3a-a484-53c3f05a0464)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3

**Comment by dareiff** [comment]
Looks like this happens in Firefox. Investigating!

**Comment by killemov** [comment]
The inputs probably have an absolute positioning, so remove that or fix the dialog width and or input widths/positions. (Cancel add Buttons are aligned how?)
