### ISSUE TITLE
"make uninstall" doesn't remove /usr/local/share/transmission

### ISSUE THREAD

**Issue by marcelpaulo** [transmission/transmission#565]
I've just built transmission from source (96926a83373048a63caa75429669aa732f19fd4f) on Xubuntu 17.10, and because of #564, I decided to temporarily uninstall it and replace it with the Ubuntu package, but `sudo make uninstall` left these files/directories behind:

```
paulo@monk:~/src/Transmission$ sudo updatedb
paulo@monk:~/src/Transmission$ locate transmission | grep ^/usr/local
/usr/local/share/transmission
/usr/local/share/transmission/web
/usr/local/share/transmission/web/images
/usr/local/share/transmission/web/javascript
/usr/local/share/transmission/web/style
/usr/local/share/transmission/web/javascript/jquery
/usr/local/share/transmission/web/style/jqueryui
/usr/local/share/transmission/web/style/transmission
/usr/local/share/transmission/web/style/jqueryui/images
/usr/local/share/transmission/web/style/transmission/images
/usr/local/share/transmission/web/style/transmission/images/buttons
```

**Comment by mikedld** [comment]
This is the standard behavior automake implements. Although possible, I'm not going to add more logic to it. Take this as a lesson and learn how to use your package manager to create (and install) packages from source tarballs so that the system knows whether some directory is owned by the particular package or not.

**Comment by mikedld** [comment]
We're not explicitly doing anything ourselves to create those directories, hence we shouldn't be doing anything to remove them IMHO. If you want the behavior to change you could try discussing this with automake developers.

As for installing software using packages, that is something that is implied by your distribution being Debian-based (or DEB-packages based). Once you step outside of accepted way of installing software on your system you're on your own.
