### ISSUE TITLE
disk read rate too high

### ISSUE THREAD

**Issue by yasezbk** [transmission/transmission#5664]
### What is the issue?

I noticed that Transmission usually has an unexpected read rate from disk (~ 5 MB/s) while downloading torrents (~ 10 MB/s). I limited the seed rate to 10 KB/s, but that didn't seem to affect the read rate.

Is this WAI?

If needed, I'd be happy to run a build with local patches to help debug this.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3

**Comment by dantearmok** [comment]
Does this occur in the current nightly build?

These r/w rates - are they from the app or Activity Monitor or ?

Please describe your configuration... which Mac, to where is the i/o going? If an external drive(s), how is it connected?

**Comment by yasezbk** [comment]
> Does this occur in the current nightly build?

It does. I reproduced this in #11474.

> are they from the app or Activity Monitor

They are coming from the Activity Monitor. The app doesn't show similar read rates.

> Please describe your configuration... which Mac

Mac Mini M2 Pro / Mac OS 13.4 (22F66)

> to where is the i/o going? If an external drive(s), how is it connected?

I'm able to reproduce this on both the local SSD device and on external HD(WD Elements, LaCie Mobile) connected via USB C.

**Comment by dantearmok** [comment]
What else is running, that's doing long-term'ish disk i/o?

When Activity Monitor is showing such read rates, what is Transmission saying?

**Comment by richliu** [comment]
I got the same issue, APP version is Tranmission 2.94 (d8e60ee44f)

torrent is a special private torrent which file size is 655GB, 
when get several peers, read rate is normal . 
but if massive peers (over 30) connnected to tranmission, it can reach over 50Mbit read rate and upload speed only under 1Mbit. 

suppose some special peers caused this issue
