### ISSUE TITLE
libtransmission `Cache` class may be slowing performance a lot

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#5667]
### What is the issue?

@ckerr I think I am spotting multiple problems in the `Cache` class of libtransmission. Would appreciate your input about this, whether you think these are valid observations.

1. Minus some edge cases such as `iter == end`, `Cache::find_contiguous()` *always* returns `std::pair{ iter, iter + 1 }`. The implication is that Tranmission is requesting OS writes block by block, thus making lots of system calls and performing a lot of disjoint writes.

   Is it supposed find the biggest chunk of adjacent blocks surrounding `iter`?

   https://github.com/transmission/transmission/blob/ed02f9801441c7203c210b9edee6bc6ca6b7d90b/libtransmission/cache.cc#L32-L71
3. Using `std::vector` for `Cache.blocks_` might be inefficient, especially because Transmission calls `blocks_.erase()` very frequently, triggering lots of copy/move operations.

   https://github.com/transmission/transmission/blob/ed02f9801441c7203c210b9edee6bc6ca6b7d90b/libtransmission/cache.cc#L218
   
   https://github.com/transmission/transmission/blob/ed02f9801441c7203c210b9edee6bc6ca6b7d90b/libtransmission/cache.cc#L262

   I think chasing cache locality here is actually *harming* performance, so we need a non-contiguous container. And since we are sorting `blocks_` by `Cache::Key`, we might as well make it a `std::map`. (side note, if we use `std::map`, then it may enable us to raise the default cache size in order to reduce calls to OS write)

### Which application of Transmission?

None

### Which version of Transmission?

ed02f9801441c7203c210b9edee6bc6ca6b7d90b

**Comment by tearfur** [comment]
This theory is based on https://github.com/transmission/transmission/issues/5261#issuecomment-1606171673

**Comment by blind-oracle** [comment]
Btw is there a defined way of disabling/bypassing Transmission's cache? I've tried setting it to -1/0 but not sure that works.

By reading the `Cache` class - it seems even setting it to 0 won't help as it will still write to a cache and then call `cache_trim()` to immediately flush everything to disk.

**Comment by tearfur** [comment]
> Btw is there a defined way of disabling/bypassing Transmission's cache?

I don't see anything like that in the code either.

> I have a ZFS backend with sync=disabled and ARC/L2ARC so probably having a cache layer in Transmission only hurts the performance.

I have no idea what all these are. It sounds like you are implying that the system already has a cache layer, and thus this `Cache` class is delaying writes to the physical disk without much benefit?

**Comment by blind-oracle** [comment]
> I have no idea what all these are. It sounds like you are implying that the system already has a cache layer, and thus this Cache class is delaying writes to the physical disk without much benefit?

Yes, the filesystem already has multilayer read cache and even `fsync()` to a torrent volume currently are set to be no-op. So the caching layer in Transmission, especially if it has performance issues, is making things worse, not better.

I wonder how hard it would be to add an on/off knob to a Cache. Removing it directly probably would be harder than some flag in the cache similar to filesystem's `O_DIRECT` that would just make `write_block()` and `read_block()` call `tr_ioRead` and `tr_ioWrite` directly. Maybe I'll look into that

**Comment by tearfur** [comment]
> I wonder how hard it would be to add an on/off knob to a Cache. Removing it directly probably would be harder than some flag in the cache similar to filesystem's `O_DIRECT` that would just make `write_block()` and `read_block()` call `tr_ioRead` and `tr_ioWrite` directly. Maybe I'll look into that

As far as I can see, Transmission only has a write cache, and it only uses the cache for reading if a block it wants happens to be in the write cache.

I think I already have an implementation for disabling the write cache ready at #5668. If `"cache-size-mb": 0`, my code should bypass the cache entirely and write directly to disk. Especially when your filesystem has its own cache, it would be interesting to see if this helps with the performance. Code reviews also very welcome.

**Comment by blind-oracle** [comment]
Thanks, will try to test today

**Comment by ckerr** [comment]
- @tearfur yes, I think that `Cache::find_contiguous()` is misimplemented. It should be returning the span of continguous blocks that include `iter` but isn't. If there is a standalone PR for fixing just that, I'd consider it for both 4.1.0 and 4.0.x.

- Plausible that a map could be a better container here but moving a `CacheBlock` is pretty cheap and there will be less erase() noise when `find_contiguous()` is fixed so ideally we'd have A/B numbers on that before making that change.

- As for disabling the cache altogether... I really appreciate both @tearfur's PR and @blind-oracle's testing but IMO it's a faulty comparison to perf test this change against the current implementation where `find_contiguous()` is broken. It would be better to fix that first and then do the comparision.

**Comment by blind-oracle** [comment]
@ckerr I'd anyway would merge the possibility to disable the cache by setting it to <=0 - it might benefit people like me who don't need this cache at all.

The change is quite small and it will make cache's semantics clearer: currently it allows to set it to zero (or even less), but still it would work in a bit useless manner.

**Comment by Tharn** [comment]
Seeing how setting cache to 0 is a peculiar choice and no one would do it who didn't *want* to disable the cache, I think it would make sense to have that setting disable it. For clarity and also for people running stuff on ZFS, bcachefs, and other modern solutions.

Unless I'm mistaken, even a better implementation will mean caching stuff twice for these certain filesystems.

**Comment by tearfur** [comment]
@blind-oracle Never set it to a negative number, you will just end up with a very very big cache because of integer overflow 😓

**Comment by ckerr** [comment]
I have a PR up in #5671 to fix the `find_contiguous()` bug that @tearfur mentioned in this ticket. It's separate to the vector-vs-map question and the can-I-disable-cache question which are still both valid issues IMO.

The goal of 5671 is to maximize the contiguous size of data being written from the cache to disk. I'd be very interested in A/B testing of how much time is spend in disk writes.
