### ISSUE TITLE
transmission-da triggered out of memory codition (oom killer not called)

### ISSUE THREAD

**Issue by Revell1on** [transmission/transmission#5673]
### What is the issue?

I have asus-wrt router with installed transmission
After updating from transmission 3 to transmission 4 I'm starting to get crashes when adding a torrent file (some time can pass after adding) with the error transmission-da triggered out of memory codition (oom killer not called)
[transmission_crash.txt](https://github.com/transmission/transmission/files/11878503/transmission_crash.txt)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Transmission 4.0.3 6b0e49bbb2

**Comment by ckerr** [comment]
I don't know how to reproduce this; there's nothing in the crash report that refers to transmission afaict.

If there's a memory issue in Transmission I'm happy to try and address it, but I'm not sure how to move forward on this report as-is.
