### ISSUE TITLE
Can we update README build instructions for "Building Transmission from Git (updating)"?

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#5674]
Whenever you add a new `third-party` submodule, we cannot compile successfully because we need to `--init` first and then proceed to build.

I was bitten by `small`'s addition to `third-party`; it could not find it and would not let me build the code.

My question is, would it hurt to update `git submodule update --recursive` to `git submodule update --init --recursive`?

Of course you know better how to rearrange the instructions to make it less confusing.

Feedback please?

**Comment by fredo-47** [comment]
Yeah, I also encountered that error. 
I helped myseld by deleting the complete folder and restarting with the "Building...first time" instructions. 
But more elegant solutions would be appreciated 😄

**Comment by stefanos82** [comment]
A simply minor tweak would fix the whole building process.

For example, from this:

```
$ cd Transmission/build
$ make clean
$ git submodule foreach --recursive git clean -xfd
$ git pull --rebase --prune
$ git submodule update --recursive
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimzed binary with debug information. (preferred)
# Use -DCMAKE_BUILD_TYPE=Release to build full optimized binary.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make
$ sudo make install
```

to this:

```
$ cd Transmission/build
$ make clean
$ git submodule foreach --recursive git clean -xfd
$ git pull --rebase --prune
$ git submodule update --init --recursive
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimzed binary with debug information. (preferred)
# Use -DCMAKE_BUILD_TYPE=Release to build full optimized binary.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make
$ sudo make install
```

That's it, really!

**Comment by dantearmok** [comment]
Using --init works.  I can now build in Xcode again.  Getting 76 warnings, tho.  Is that normal?

**Comment by stefanos82** [comment]
I get warnings as well, even though I'm using GNU / Debian.

I would say the future code improvement or possible refactoring will eliminate these warnings, eventually!

**Comment by stefanos82** [comment]
@ckerr see #5688 and let me know whether it's alright or not.

**Comment by nevack** [comment]
> Getting 76 warnings, tho. Is that normal?

Yes, it's ok.

**Comment by stefanos82** [comment]
Should I close it or should I wait first to get PR approved and then close the ticket?
