### ISSUE TITLE
Done script is not always executed

### ISSUE THREAD

**Issue by jonudewux** [transmission/transmission#569]
Even in log daemon say that script is calling, it is not ran.
Most often when torrent file is in separated directory.
settings.json
```json
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/opt/my/cfg/transmission-daemon/hass_notify",
```
log
```
Mar 31 19:55:02 daemon.info transmission-daemon[1184]: [censored] State changed from "Incomplete" to "Complete" (torrent.c:2218)
Mar 31 19:55:02 daemon.info transmission-daemon[1184]: [censored] Calling script "/opt/my/cfg/transmission-daemon/hass_notify" (torrent.c:2118)
```
script permissions
```
-rwxrwxrwx    1 root     root           179 Mar 31 19:56 /opt/my/cfg/transmission-daemon/hass_notify
```
transmission-daemon 2.92 (14714)

**Comment by mikedld** [comment]
How do you define "not ran"? If it doesn't perform the action you expect it to, maybe you need to fix the script and not Transmission. For ideas on how to see what's really going on and further support please search/use [forums](https://forum.transmissionbt.com/).

**Comment by jonudewux** [comment]
Script is working fine from bash, also on some other torrent again its work.
Script is very simple:
#!/bin/sh
/bin/date > ./tmp

So I my point is that, something else not work.
