### ISSUE TITLE
assertion failure in tr_global_ip_cache, 0fbafc9 Build #9141

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#5707]
### What is the issue?

Updated Transmission nightly to the latest.  Launched it.  Went to get coffee.  Came back to this crash.

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS 10.15 Catalina, PeakHour, PIA, and Xcode 12.3 (all fully updated).

Running Transmission-0fbafc9e18 Build #9141 (Jun 30, 2023, 11:05:10 PM)

Process:               Transmission [58937]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            Transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Transmission [58937]
User ID:               502

Date/Time:             2023-06-30 21:35:32.983 -0400
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 280000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'assertion failed: std::all_of( std::begin(is_updating_), std::end(is_updating_), [](is_updating_t const& v) { return v == is_updating_t::ABORT; }) (/Users/mac-dyu4mtleuz/workspace/trunk-mac/libtransmission/global-ip-cache.cc:168)'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff35586a17 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff6e0eba9e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff35586875 +[NSException raise:format:] + 181
3   Transmission                        0x0000000100ca5638 _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEElS3_ + 280
4   Transmission                        0x0000000100c24272 _ZN18tr_global_ip_cacheD2Ev + 386
5   Transmission                        0x0000000100c3a483 _ZNSt3__110unique_ptrI18tr_global_ip_cacheNS_14default_deleteIS1_EEED1Ev + 29
6   Transmission                        0x0000000100c3abbb _ZN10tr_sessionD2Ev + 303
7   Transmission                        0x0000000100c36eba _Z15tr_sessionCloseP10tr_sessionm + 620
8   Transmission                        0x0000000100b70d6e -[Controller applicationWillTerminate:] + 1220
9   CoreFoundation                      0x00007fff35500549 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
10  CoreFoundation                      0x00007fff355004dd ___CFXRegistrationPost1_block_invoke + 63
11  CoreFoundation                      0x00007fff35500452 _CFXRegistrationPost1 + 372
12  CoreFoundation                      0x00007fff355000be ___CFXNotificationPost_block_invoke + 80
13  CoreFoundation                      0x00007fff354d026c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1745
14  CoreFoundation                      0x00007fff354cf635 _CFXNotificationPost + 1586
15  Foundation                          0x00007fff37b75096 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
16  AppKit                              0x00007fff32a3a528 -[NSApplication terminate:] + 1385
17  AppKit                              0x00007fff329af9f7 -[NSApplication(NSResponder) sendAction:to:from:] + 299
18  AppKit                              0x00007fff32abf48e -[NSMenuItem _corePerformAction] + 312
19  AppKit                              0x00007fff32abf20a -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 106
20  AppKit                              0x00007fff32abe107 -[NSMenu performKeyEquivalent:] + 412
21  AppKit                              0x00007fff32ef424b routeKeyEquivalent + 521
22  AppKit                              0x00007fff32910b1d -[NSApplication(NSEvent) sendEvent:] + 1161
23  AppKit                              0x00007fff3275d94f -[NSApplication run] + 707
24  AppKit                              0x00007fff3272f706 NSApplicationMain + 777
25  libdyld.dylib                       0x00007fff6f28bcc9 start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6f3d332a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6f493e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6f35a808 abort + 120
3   libc++abi.dylib               	0x00007fff6c5bf458 abort_message + 231
4   libc++abi.dylib               	0x00007fff6c5b08bf demangling_terminate_handler() + 262
5   libobjc.A.dylib               	0x00007fff6e0eda57 _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff6c5be887 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff6c5be829 std::terminate() + 41
8   org.m0k.transmission          	0x0000000100c3a483 std::__1::unique_ptr<tr_global_ip_cache, std::__1::default_delete<tr_global_ip_cache> >::~unique_ptr() + 29 (unique_ptr.h:272)
9   org.m0k.transmission          	0x0000000100c3abbb tr_session::~tr_session() + 303 (session.h:83)
10  org.m0k.transmission          	0x0000000100c36eba tr_sessionClose(tr_session*, unsigned long) + 620 (session.cc:1349)
11  org.m0k.transmission          	0x0000000100b70d6e -[Controller applicationWillTerminate:] + 1220
12  com.apple.CoreFoundation      	0x00007fff35500549 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
13  com.apple.CoreFoundation      	0x00007fff355004dd ___CFXRegistrationPost1_block_invoke + 63
14  com.apple.CoreFoundation      	0x00007fff35500452 _CFXRegistrationPost1 + 372
15  com.apple.CoreFoundation      	0x00007fff355000be ___CFXNotificationPost_block_invoke + 80
16  com.apple.CoreFoundation      	0x00007fff354d026c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1745
17  com.apple.CoreFoundation      	0x00007fff354cf635 _CFXNotificationPost + 1586
18  com.apple.Foundation          	0x00007fff37b75096 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
19  com.apple.AppKit              	0x00007fff32a3a528 -[NSApplication terminate:] + 1385
20  com.apple.AppKit              	0x00007fff329af9f7 -[NSApplication(NSResponder) sendAction:to:from:] + 299
21  com.apple.AppKit              	0x00007fff32abf48e -[NSMenuItem _corePerformAction] + 312
22  com.apple.AppKit              	0x00007fff32abf20a -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 106
23  com.apple.AppKit              	0x00007fff32abe107 -[NSMenu performKeyEquivalent:] + 412
24  com.apple.AppKit              	0x00007fff32ef424b routeKeyEquivalent + 521
25  com.apple.AppKit              	0x00007fff32910b1d -[NSApplication(NSEvent) sendEvent:] + 1161
26  com.apple.AppKit              	0x00007fff3275d94f -[NSApplication run] + 707
27  com.apple.AppKit              	0x00007fff3272f706 NSApplicationMain + 777
28  libdyld.dylib                 	0x00007fff6f28bcc9 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6f3d1756 kevent + 10
1   org.m0k.transmission          	0x0000000100d16007 kq_dispatch + 571 (kqueue.c:315)
2   org.m0k.transmission          	0x0000000100d076ac event_base_loop + 735 (event.c:1994)
3   org.m0k.transmission          	0x0000000100c658e5 tr_session_thread_impl::sessionThreadFunc(event_base*) + 87 (session-thread.cc:250)
4   org.m0k.transmission          	0x0000000100c65cd7 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) + 63 (thread:300)
5   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6f3d1756 kevent + 10
1   org.m0k.transmission          	0x0000000100c1108c -[VDKQueue watcherThread:] + 203 (VDKQueue.mm:190)
2   com.apple.Foundation          	0x00007fff37bc4222 __NSThread__start__ + 1064
3   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6f3ccdea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6f3cd160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3550ad07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff355097c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff35508c33 CFRunLoopRunSpecific + 466
5   com.apple.AppKit              	0x00007fff3290ebf4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 4:: com.apple.coreaudio.AQClient
0   libsystem_kernel.dylib        	0x00007fff6f3ccdea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6f3cd160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3550ad07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff355097c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff35508c33 CFRunLoopRunSpecific + 466
5   com.apple.audio.toolbox.AudioToolbox	0x00007fff3387ff60 GenericRunLoopThread::Entry(void*) + 166
6   libAudioToolboxUtility.dylib  	0x00007fff6bc13611 CAPThread::Entry(CAPThread*) + 77
7   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff6f3cce26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68dcfb16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68dcf9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68dcf7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68dcf1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 6:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6f3cce26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68dcfb16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68dcf9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68dcf7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68dcf1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f494109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f48fb8b thread_start + 15

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6f48fb68 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6f48fb68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6f48fb68 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000010c1a6dc0  rcx: 0x00007ffeef096f98  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffeef096fc0  rsp: 0x00007ffeef096f98
   r8: 0x00007ffeef096e60   r9: 0x00007ffeef097030  r10: 0x000000010c1a6dc0  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff6f3d332a  rfl: 0x0000000000000246  cr2: 0x00007fff95c3cfb0
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1-dev  0fbafc9e18 Build #9141 (Jun 30, 2023, 11:05:10 PM)

**Comment by ckerr** [comment]
CC @tearfur

**Comment by tearfur** [comment]
@ckerr I'll be getting to this once I have free time, please assign me to it.
