### ISSUE TITLE
tr_peerMgr::makeNewPeerConnections() should use less CPU

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#5714]
Discussed [here](https://github.com/transmission/transmission/issues/5261) and in particular here:

![50308023-58e73062-54de-4b55-ba03-888d02042b1b](https://github.com/transmission/transmission/assets/70381/eae422b4-0447-4a8d-a427-3d1ae08aa890)

But since 5261 is pretty wide-reaching, I'm culling this out into a standlone ticket.

**Comment by tearfur** [comment]
@ckerr Brainstorming here.

I think the biggest culprit here is that `tr_swarm.pool` can only grow, and never shrink. Given that Transmission maintains the peer limit per swarm (`max`) by sorting peers (`tr_swarm.peers`) using `ComparePeerByActivity`, we can probably do the same with `pool`, but with a slightly (how much?) bigger limit than `max` without impacting transfer performance too much.

**Comment by tearfur** [comment]
This is less important that my previous comment and frankly very hard to judge, but I'm also wondering if 500ms is too frequent for `reconnectPulse()`.

Do we really get new peers that quickly?

**Comment by blind-oracle** [comment]
@tearfur I'm currently testing a change that cleans up the `pool` based on simple rules:
1. Peer was added >10 min ago to let it have some retries (i've added a `time_added` field to `peer_atom`)
2. Last successful connection (`lastConnectionAt`) was >10min ago

It's a first attempt, let's see if that helps keeping the peer count at bay, most probably gonna have to tune the logic and timeouts.

My pool size after 3 days was 1.6M so I need this very much :)

**Comment by tearfur** [comment]
@blind-oracle This idea sounds a bit like `closeBadPeers()` but with different numbers. 🤔

**Comment by blind-oracle** [comment]
@tearfur well just removing atoms from `pool` seems to be problematic since they're referenced in the network code and really not supposed to be removed :) At least it would take some effort to implement... gonna look for other ways

**Comment by ckerr** [comment]
My concern about pruning the pool is that peers could feed us bad peers again and since we've thrown away the info that a peer isn't connectable, we'd have to try it all over again. But I do think 1.5m atoms is _insane_ and maybe we should rethink whether we could use some data structure that would be more efficient at scale.

5734 tries caching the short-term candidate list for a few seconds which would cut the CPU use by 75% but I still like the idea of reducing the footprint of `pool` and `peer_atom` since 1.5m instances of a struct is probably expensive

**Comment by blind-oracle** [comment]
Tried latest master -> transmission at `5.5GB` of RAM so I guess there's a leak somewhere in this cache.

**Comment by tearfur** [comment]
@ckerr I think I spot another issue with `pool`. It shoud only store the *listening socket address* of the known peers.

It now stores every socket address that Transmission ever connected to, and the majority of these will be temporary sockets with ephemeral ports, which will only exist throughout the duration of its corresponding connection.

What ends up happening is that these temporary sockets will all be marked "unreachable" and sit there wasting memory space and time filtering through them.

**Comment by ckerr** [comment]
What is the right fix for that, though?

**Comment by tearfur** [comment]
I had an idea for storing `peer_atom` via `std::shared_ptr` instead of directly storing the object in `pool`. Then, we would only insert the `peer_atom` pointer into `pool` in PEX, and not on handshake done.

But now that you have #5773 up, I am still re-evaluating if something along this line can still work. 🤔

**Comment by tearfur** [comment]
Oh boy, I am excited about fixing this one, it is going to be an important fix. 😁 

#5756 also noticibly improved seeding performance when I was comparing `std::map` and `std::unordered_map`. So I'm quite looking forward to the feedback on `4.1.0` release.

**Comment by ckerr** [comment]
> I was planning to refactor `tr_peerMsgs` to store its own `peer_atom` struct or something along those lines. But now that you have #5773 up, I am still re-evaluating the situation.

After 5773 I'll move on to another part of the code so that I won't step on any of your work.

`peer_atom` was still generally behaving like a C struct going back to its time before the C -> C++ migration, and its data hiding came from the fact that only peer-mgr.cc could see it. The `info` struct is still filling the same needs as `peer_atom` but with private fields in a C++ class.

**Comment by tearfur** [comment]
Cool, I am look at the code in 5773 now. semantically, it does look like nothing much has changed. Might as well do a code review along the way if I see anything odd.

**Comment by ckerr** [comment]
There was some oddness in `peer_atom` of "do we *know* peer X is reachable or not, or did another peer *say* that they're connectable, or do we just have no idea" that was handled in multiple related bools, and have now have a tristate via `std::optional<bool>`.

I do see another wart, that sometimes with an incoming peer we don't know their open port until they advertise it in the handshake. That's what `tr_peer_event::Type::ClientGotPort` is for. And we *do* modify the atom/info port, but we don't modify the `pool` map key. ...and on top of that, modifying the key is tricky because we really don't want to invalidate that atom/info object that we've passed a raw pointer to in `tr_peerMsgs`' constructor. :dizzy:

**Comment by tearfur** [comment]
> And we *do* modify the atom/info port, but we don't modify the `pool` map key.

Oh boy... 💫 But nice catch. It is nice to have 2 pairs of eyes.

Actually. if we make `tr_peerMsgs` own the `tr_peer_info` object it uses (like I suggested earlier), then I think we can sort this out.
Now, when it receives a `tr_peer_event::Type::ClientGotPort`, it just needs make a copy of its own `tr_peer_info` object, change the port to the listening port, then insert into `pool`.

I know what I have in mind is probably not very clear to you now, I'll just have to cough up a PR for this.

**Comment by ckerr** [comment]
> > After 5773 I'll move on to another part of the code so that I won't step on any of your work.
> 
> @ckerr I'll be less active for a while on here. So if you want to move your attention back onto peer communications, by all means.

Alright. Your code's been great; come back soon :green_heart:
