### ISSUE TITLE
MacOS torrent selection with Sort by activity is broken

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5717]
### What is the issue?

Probably related to #5147. When a torrent is selected in the main window and the user is using 'Sort transfers by -> Activity', and there are torrents jockeying during seeding, the highlight will stay in place with torrents moving in and out of the highlight, rather than the highlighted torrent moving within the table.

cc @sweetppro 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (4c282bdbb4)

**Comment by Coeur** [comment]
Ah, actually same underlying issue as #5838, but #5838 had easier steps to reproduce the selection problem.
