### ISSUE TITLE
Building from git error

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5727]
### What is the issue?

Latest pull after #5721.

`/home/gary/Documents/GitHub/transmission-primary/third-party/small/include/small/detail/exception/scope_guard.hpp:14:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   13 | #include <iostream>
  +++ |+#include <cstdint>
   14 | #include <utility>
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/build.make:300: libtransmission/CMakeFiles/transmission.dir/file-piece-map.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:571: libtransmission/CMakeFiles/transmission.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

### Which application of Transmission?

None

### Which version of Transmission?

Linux

**Comment by tearfur** [comment]
`git bisect` yielded #5720. I guess `<vector>` does not include `<cstdint>` at all in some STL versions.

Anyway this looks like a third party bug to me.

**Comment by candrews** [comment]
I can confirm that this PR fixes the problem on my system.
