### ISSUE TITLE
Transmission web interface freezes occasionally when doing anything besides just downloading

### ISSUE THREAD

**Issue by Ivar418** [transmission/transmission#5732]
### What is the issue?

I have about 70+ torrents that have been added. About 10 of them are allowed to download at the same time.
They are downloaded to a samba share.

The web interface is freezing a lot. It happens when torrents are being added, checked, moved or if any other program uses the disk that is being used for the downloads.

I have tried to not use a samba share for my uncompleted folder, but it still freezes.
I have tried other torrent clients and those work fine. I dont like the other clients so I wanna keep using transmission but it would be great if it were to not freeze all the time. 

There is no information in the log nor anything visual that Ii can show via screenshot. I am using the Flud web interface, but ive tried all the interfaces that are known to me including the default one but it happens with all of them

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3

**Comment by Ivar418** [comment]
It does seem like #2462 
I will follow that thread to see if that is solved my problems go away too

**Comment by ckerr** [comment]
Closing as duplicate
