### ISSUE TITLE
Buggy behavior with transmission-gtk in latest commit 2a9c30a61

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#5733]
I've just compiled 2a9c30a61 and on resizing `transmission-gtk` window, I get the following behavior:

![image](https://github.com/transmission/transmission/assets/1777466/320aec25-f678-48c0-84f7-d6ba32809dca)

Please note that it becomes unresponsive and cannot tell whether any download has finished or not; I need to kill it and reopen it to resume.

`transmission-qt` behaves as expected.

**Comment by stefanos82** [comment]
@tearfur Seems like I have managed to reproduce this peculiar behavior.

This buggy behavior is part of GTK4 I'm afraid.

You can reproduce it with `gtk4-demo --run=gltransition`; try to resize it as fast as possible and see it freezing...to stop it, just press `Ctrl+C` from your terminal and will exit.

https://github.com/transmission/transmission/assets/1777466/1ccbf526-e9dc-4e48-b68f-e46535cfc44f

**Comment by tearfur** [comment]
Shall I close this as an upstream bug?
