### ISSUE TITLE
Context menu not completely visible

### ISSUE THREAD

**Issue by madebr** [transmission/transmission#574]
When right-clicking on an item at the bottom of the list, only the top portion of the context menu is shown.
The bottom part is cut off by the bottom of the screen.

How to reproduce:
1. Launch `transmission-gtk`
2. Add an item to the download list
3. Unmaximize the window and move it to the bottom of the screen
4. Right click on an item

Expected behavior:
The context menu is completely visible

Actual result:
The context is _not_ completely visible

os: Fedora 26
version: transmission-gtk 2.92 (as shipped by Fedora)

**Comment by mikedld** [comment]
@madebr, is this still an issue? I'd expect context menu to open to the top (not the bottom) from the cursor in this case, which then sounds like a GTK issue.

**Comment by madebr** [comment]
No, I cannot reproduce it anymore. 
As you said, this has probably something to do with gtk/wayland/...
I'll close this one.

Thanks for checking this old issue.
