### ISSUE TITLE
Missing keyboard shortcut for "Edit Labels..."

### ISSUE THREAD

**Issue by luaneko** [transmission/transmission#5752]
### What is the issue?

There is no keyboard shortcut for the "Edit Labels..." action in the web client.

Perhaps an unused key combo like `Control + K` could be mapped to this action.

![image](https://github.com/transmission/transmission/assets/27663662/51fdcfdd-e2e8-4d6d-89a8-8d120acfa4da)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
Sure "K" for Labels ... Also, this would activate self-destruct on your commander.
