### ISSUE TITLE
Dark Mode: Colours make descriptive texts impossible to read

### ISSUE THREAD

**Issue by HoboCop85** [transmission/transmission#5757]
### What is the issue?

In dark mode when hovering over the top menu buttons, the descriptive text completely disappears and is unreadable. This happens with all the buttons at the top menu (Not dropdown menues).

![Skärmbild från 2023-07-09 10-01-51](https://github.com/transmission/transmission/assets/138284359/f84ceee0-b629-41fe-bb18-d4b22726abe2)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
This appears to be related to your other post: #5758.

**Comment by mikedld** [comment]
We're not modifying palette ourselves in any way (and aren't planning on it). This should be solved either in the theme/style you're using or in Qt.
