### ISSUE TITLE
Dark mode: Blurry text

### ISSUE THREAD

**Issue by HoboCop85** [transmission/transmission#5758]
### What is the issue?

When hitting "Torrent" or "Edit" (Running the swedish language but it's the dropdown to the left of torrent) shows all text as blurry text. It's readable but definately improveable. Attached screenshot
![Skärmbild från 2023-07-09 10-02-17](https://github.com/transmission/transmission/assets/138284359/3632e354-37db-4790-93b6-9439438665f5)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3

**Comment by mikedld** [comment]
We're not modifying palette ourselves in any way (and aren't planning on it). This should be solved either in the theme/style you're using or in Qt.

P.S. The text is rendered this way because the menu items are disabled since you don't have any torrents selected.
