### ISSUE TITLE
Crash at vtable for __cxxabiv1::__class_type_info + 16

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#5765]
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS 10.15 Catalina, PeakHour, PIA, and Xcode 12.3 (all fully updated).

Running Transmission-8169d524ea Build #9181 (Jul 8, 2023, 7:28:46 PM)

Process:               Transmission [45514]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            Transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Transmission [45514]
User ID:               502

Date/Time:             2023-07-11 06:29:57.042 -0400
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 280000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fff8d59e9f0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [45514]

VM Regions Near 0x7fff8d59e9f0:
    __DATA                 00007fff8d594000-00007fff8d59b8f0 [   30K] rw-/rwx SM=COW  /usr/lib/libc++.1.dylib
--> __DATA                 00007fff8d59b8f0-00007fff8d59ef38 [   14K] rw-/rwx SM=COW  /usr/lib/libc++abi.dylib
    __DATA                 00007fff8d59ef38-00007fff8d59f001 [   201] rw-/rwx SM=COW  /usr/lib/libcharset.1.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x00007fff8d59e9f0 vtable for __cxxabiv1::__class_type_info + 16
1   org.m0k.transmission          	0x000000010ad385b1 auto tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_6::operator()<tr_peerMsgs>(tr_peerMsgs const*) const + 49 (peer-mgr.cc:1676)
2   org.m0k.transmission          	0x000000010acd5fde tr_peer_stat* std::__1::transform<std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_6>(std::__1::__wrap_iter<tr_peerMsgs* const*>, std::__1::__wrap_iter<tr_peerMsgs* const*>, tr_peer_stat*, tr_peerMgrPeerStats(tr_torrent const*, unsigned long*)::$_6) + 126 (algorithm:1948)
3   org.m0k.transmission          	0x000000010acd5ed0 tr_peerMgrPeerStats(tr_torrent const*, unsigned long*) + 496 (peer-mgr.cc:1672)
4   org.m0k.transmission          	0x000000010abe84f9 tr_torrentPeers(tr_torrent const*, unsigned long*) + 121 (torrent.cc:1695)
5   org.m0k.transmission          	0x000000010aa19823 -[Torrent peers] + 51 (Torrent.mm:943)
6   org.m0k.transmission          	0x000000010aac210b -[InfoPeersViewController updateInfo] + 1803 (InfoPeersViewController.mm:154)
7   org.m0k.transmission          	0x000000010aa3cdc7 -[InfoWindowController updateInfoStats] + 71 (InfoWindowController.mm:470)
8   org.m0k.transmission          	0x000000010a9adf90 -[Controller updateUI] + 1536 (Controller.mm:2317)
9   com.apple.Foundation          	0x00007fff2fa3fd6a __NSFireTimer + 67
10  com.apple.CoreFoundation      	0x00007fff2d33a718 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
11  com.apple.CoreFoundation      	0x00007fff2d33a27e __CFRunLoopDoTimer + 872
12  com.apple.CoreFoundation      	0x00007fff2d339d69 __CFRunLoopDoTimers + 322
13  com.apple.CoreFoundation      	0x00007fff2d31e9ed __CFRunLoopRun + 1885
14  com.apple.CoreFoundation      	0x00007fff2d31dc33 CFRunLoopRunSpecific + 466
15  com.apple.HIToolbox           	0x00007fff2bf39aad RunCurrentEventLoopInMode + 292
16  com.apple.HIToolbox           	0x00007fff2bf397c5 ReceiveNextEventCommon + 584
17  com.apple.HIToolbox           	0x00007fff2bf39569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
18  com.apple.AppKit              	0x00007fff2a5823c9 _DPSNextEvent + 883
19  com.apple.AppKit              	0x00007fff2a580c10 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
20  com.apple.AppKit              	0x00007fff2a57291e -[NSApplication run] + 658
21  com.apple.AppKit              	0x00007fff2a544706 NSApplicationMain + 777
22  org.m0k.transmission          	0x000000010a98c077 main + 55 (main.mm:17)
23  libdyld.dylib                 	0x00007fff670a0cc9 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff671e1d36 _kernelrpc_mach_vm_map_trap + 10
1   libsystem_kernel.dylib        	0x00007fff671e1c65 mach_vm_map + 80
2   libsystem_malloc.dylib        	0x00007fff67265f43 mvm_allocate_pages + 246
3   libsystem_malloc.dylib        	0x00007fff6726658a large_malloc + 159
4   libsystem_malloc.dylib        	0x00007fff6725c16f szone_malloc_should_clear + 235
5   libsystem_malloc.dylib        	0x00007fff6725ad7a malloc_zone_malloc + 104
6   libsystem_malloc.dylib        	0x00007fff6725acf5 malloc + 21
7   libc++abi.dylib               	0x00007fff643d5dea operator new(unsigned long) + 26
8   org.m0k.transmission          	0x000000010acdd99d std::__1::__libcpp_allocate(unsigned long, unsigned long) + 77 (new:253)
9   org.m0k.transmission          	0x000000010ad270f0 std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>::allocate(unsigned long, void const*) + 80 (memory:1869)
10  org.m0k.transmission          	0x000000010ad26f81 std::__1::allocator_traits<std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate> >::allocate(std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>&, unsigned long) + 33 (memory:1586)
11  org.m0k.transmission          	0x000000010ad26ed2 std::__1::__split_buffer<(anonymous namespace)::connect_helpers::peer_candidate, std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>&) + 98 (__split_buffer:318)
12  org.m0k.transmission          	0x000000010ad26c7d std::__1::__split_buffer<(anonymous namespace)::connect_helpers::peer_candidate, std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate>&) + 45 (__split_buffer:321)
13  org.m0k.transmission          	0x000000010ad2612e std::__1::vector<(anonymous namespace)::connect_helpers::peer_candidate, std::__1::allocator<(anonymous namespace)::connect_helpers::peer_candidate> >::reserve(unsigned long) + 110 (vector:1586)
14  org.m0k.transmission          	0x000000010acd7ea2 (anonymous namespace)::connect_helpers::get_peer_candidates(tr_session*) + 290 (peer-mgr.cc:2398)
15  org.m0k.transmission          	0x000000010acd7560 tr_peerMgr::make_new_peer_connections() + 128 (peer-mgr.cc:2526)
16  org.m0k.transmission          	0x000000010acd6da1 tr_peerMgr::reconnectPulse() + 481 (peer-mgr.cc:2177)
17  org.m0k.transmission          	0x000000010acd7995 tr_peerMgr::bandwidthPulse() + 293 (peer-mgr.cc:2242)
18  org.m0k.transmission          	0x000000010acde598 tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()::operator()() const + 24 (peer-mgr.cc:828)
19  org.m0k.transmission          	0x000000010acde55d decltype(std::__1::forward<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(fp)()) std::__1::__invoke<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) + 29 (type_traits:3545)
20  org.m0k.transmission          	0x000000010acde50d void std::__1::__invoke_void_return_wrapper<void>::__call<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) + 29 (__functional_base:349)
21  org.m0k.transmission          	0x000000010acde4dd std::__1::__function::__alloc_func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()() + 29 (functional:1546)
22  org.m0k.transmission          	0x000000010acdd13e std::__1::__function::__func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()() + 30 (functional:1720)
23  org.m0k.transmission          	0x000000010abcf1f5 std::__1::__function::__value_func<void ()>::operator()() const + 53 (functional:1873)
24  org.m0k.transmission          	0x000000010abcefe5 std::__1::function<void ()>::operator()() const + 21 (functional:2548)
25  org.m0k.transmission          	0x000000010af179f4 libtransmission::EvTimer::handleTimer() + 148 (timer-ev.cc:152)
26  org.m0k.transmission          	0x000000010af1751f libtransmission::EvTimer::onTimer(int, short, void*) + 31 (timer-ev.cc:144)
27  org.m0k.transmission          	0x000000010af6f765 event_persist_closure + 773 (event.c:1624)
28  org.m0k.transmission          	0x000000010af6ed98 event_process_active_single_queue + 824 (event.c:1683)
29  org.m0k.transmission          	0x000000010af695c4 event_process_active + 324 (event.c:1783)
30  org.m0k.transmission          	0x000000010af6848b event_base_loop + 795 (event.c:2006)
31  org.m0k.transmission          	0x000000010ac9f102 tr_session_thread_impl::sessionThreadFunc(event_base*) + 242 (session-thread.cc:239)
32  org.m0k.transmission          	0x000000010aca13bf decltype(*(std::__1::forward<tr_session_thread_impl*>(fp0)).*fp(std::__1::forward<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 143 (type_traits:3486)
33  org.m0k.transmission          	0x000000010aca12b7 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 87 (thread:274)
34  org.m0k.transmission          	0x000000010aca0a06 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) + 118 (thread:284)
35  libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
36  libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff671e4746 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff67167eea nanosleep + 196
2   libc++.1.dylib                	0x00007fff643b06da std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   org.m0k.transmission          	0x000000010ad911ce void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) + 190 (thread:387)
4   org.m0k.transmission          	0x000000010adb943f tr_web::Impl::curlThreadFunc() + 1055 (web.cc:713)
5   org.m0k.transmission          	0x000000010adbc697 decltype(*(std::__1::forward<tr_web::Impl*>(fp0)).*fp()) std::__1::__invoke<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 119 (type_traits:3486)
6   org.m0k.transmission          	0x000000010adbc59e void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 62 (thread:274)
7   org.m0k.transmission          	0x000000010adbbd86 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*> >(void*) + 118 (thread:284)
8   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
9   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff671e6756 kevent + 10
1   org.m0k.transmission          	0x000000010aaebd6c -[VDKQueue watcherThread:] + 188 (VDKQueue.mm:189)
2   com.apple.Foundation          	0x00007fff2f9d9222 __NSThread__start__ + 1064
3   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff671e1dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff671e2160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2d31fd07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff2d31e7c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff2d31dc33 CFRunLoopRunSpecific + 466
5   com.apple.AppKit              	0x00007fff2a723bf4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 5:: com.apple.coreaudio.AQClient
0   libsystem_kernel.dylib        	0x00007fff671e1dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff671e2160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2d31fd07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff2d31e7c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff2d31dc33 CFRunLoopRunSpecific + 466
5   com.apple.audio.toolbox.AudioToolbox	0x00007fff2b694f60 GenericRunLoopThread::Entry(void*) + 166
6   libAudioToolboxUtility.dylib  	0x00007fff63a28611 CAPThread::Entry(CAPThread*) + 77
7   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff671e1e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff60be4b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff60be49b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff60be47c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff60be41e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 7:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff671e1e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff60be4b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff60be49b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff60be47c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff60be41e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff672a9109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff672a4b8b thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff672a4b68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff672a4b68 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff672a4b68 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	0x00007fff672a4b68 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	0x00007fff672a4b68 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fa03978a000  rbx: 0x00007fa03741a4a0  rcx: 0x000000010b0726a8  rdx: 0xffffffffffffffd8
  rdi: 0x00007ffee5276418  rsi: 0x00007fa03978a000  rbp: 0x00007ffee5276450  rsp: 0x00007ffee52763a8
   r8: 0x0000000000000000   r9: 0x00007ffee5276000  r10: 0x00007fa03f8a3a00  r11: 0xffffffa153e72158
  r12: 0x00007fa038011050  r13: 0x00007fff65ef3d10  r14: 0x0000600003833240  r15: 0x00007fff71a7f040
  rip: 0x00007fff8d59e9f0  rfl: 0x0000000000010287  cr2: 0x00007fff8d59e9f0
  
Logical CPU:     1
Error Code:      0x00000015 (invalid protections for user instruction read)
Trap Number:     14

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-8169d524ea Build #9181 (Jul 8, 2023, 7:28:46 PM)

**Comment by tearfur** [comment]
This looks awfully similar to #5524.

**Comment by tearfur** [comment]
Supersceded by #5853.
