### ISSUE TITLE
[macOS] Task doesn't start until Transmission window is on foreground

### ISSUE THREAD

**Issue by jminuscula** [transmission/transmission#577]
I always add magnet links to Transmission via the remote interface on my local network. I don't have any auth set up or IP restrictions. To add the torrents I use the [Remote Torrent Adder](https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci) extension.

When I add a magnet link, the task appears in Transmission without any issues. However, even though I have it configured to start tasks right away, I see in the web interface it stays fetching metadata (magnet/red state).

It's only when I VNC into my download server (a mac mini running macOs 10.13.2 and Transmission 2.92/14714) and bring the Transmission window to the foreground, it starts downloading.

In the attached logs you can see how the task was added at 18:15, but did not start until 19:12.

Please let me know if there's anything I can do to help debug this.
Thanks!

[transmission.txt](https://github.com/transmission/transmission/files/1891456/transmission.txt)

**Comment by andycarver101** [comment]
Me too.

**Comment by wiz78** [comment]
I've submitted a PR to fix this (https://github.com/transmission/transmission/pull/755)

**Comment by andycarver101** [comment]
I don’t have power nap enabled and the application itself cannot be disabled. 
My server never sleeps.

**Comment by wiz78** [comment]
PowerNap and AppNap are two different things. Since 10.9 (AFAIR), you can’t disable App Nap via the Finder inspector as in previous releases. If you close Transmission’s window, leaving it in the dock, you’ll see it napping using Activity Monitor (toggle the App Nap column in the table, if it’s not visible)

**Comment by andycarver101** [comment]
I’m running 10.12.6. Apps that suppprt it can be prevented. One example is Sonarr, (however it’s not disabled)

**Comment by wiz78** [comment]
All apps support AppNap (
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html).

The checkbox to disable it appears only for apps linked to older SDKs, newer apps need to handle it themselves, like my patch does, disabling AppNap entirely for Transmission. If you can compile Transmission from sources, check it out

**Comment by wiz78** [comment]
No idea, I’ve only contributed a patch, but I’m not the maintainer of this project 😃

**Comment by andycarver101** [comment]
That’s cool. Hope it won’t be too long. This app rarely gets updates.

**Comment by sxflynn** [comment]
I am still experiencing this issue on Transmission 3.00. I don’t believe this issue has been fixed.

**Comment by wiz78** [comment]
the fix has been merged for a future release (4.0.0, AFAIK)
