### ISSUE TITLE
Transmission should retry with clear connection if MSE handshake failed

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#5779]
### What is the issue?

Currently, even when Transmission is set to *prefer* encryption and not *require* encryption, it will only try to initiate encrypted outgoing conections. There are also no mechanism to retry with clear connection when the MSE handshake failed.

### Which application of Transmission?

None

### Which version of Transmission?

2ec19e6

**Comment by GaryElshaw** [comment]
> There are also no mechanism to retry with clear connection when the MSE handshake failed.

The macOS client has a _require_ encryption option. Isn't that it a good thing that there isn't a retry with a clear conection? I'm wondering if it's the labelling that needs to change where the word _prefer_ should be _require_?

**Comment by tearfur** [comment]
Of course I am referring to when the option is set to *prefer* encryption.

**Comment by GaryElshaw** [comment]
Ahhh, my mistake, please disregard what i said, i see something has changed or i had forgtten over time. I thought at one point there were only two choices in the linux clients of prefer or allow.

**Comment by tearfur** [comment]
Looked at the code again, Transmission *does* change to unencrypted mode if the reply it got from sending out `Ya` was a plain BT handshake. But is this guaranteed? What if the client simply ignored `Ya` and never sent replies?

**Comment by GaryElshaw** [comment]
It would also be great if the connection failure was more meaningfully for users. Rather than connection failed, it should be 'peer/tracker is unencrypted'.

**Comment by tearfur** [comment]
It does log that info, albiet hidden in the lowest logging level. If you are referring to something like a GUI pop-up, then I'm afraid I cannot be much help atm.

https://github.com/transmission/transmission/blob/2ec19e694d0ac9226808ac04305e3e90b2b7f1ce/libtransmission/handshake.cc#L343-L350

**Comment by GaryElshaw** [comment]
I was thinking it could appear in the trackers view, where 'Connection Failed' could be more meaningful.

**Comment by tearfur** [comment]
This issue is related to peer communication, rather than tracker communication.

And I just found the code that retries with clear connection, jumped the gun too quickly on this one. 😅 

https://github.com/transmission/transmission/blob/2ec19e694d0ac9226808ac04305e3e90b2b7f1ce/libtransmission/handshake.cc#L800-L810

**Comment by tearfur** [comment]
> I'm still wondering about those choices though. Allow encryption Prefer encryption Require encryption
> 
> Couldn't complexity be removed by just having Require and Allow. I either want to encrypt the connection or not. allow and prefer, to me, seem to more or less be the same thing.

Is this a GUI bug? 🤔 That's not the options I see in daemon.

**Comment by GaryElshaw** [comment]
> This issue is related to peer communication, rather than tracker communication.

The logical place would be here:

![Screenshot from 2023-07-14 16-36-20](https://github.com/transmission/transmission/assets/69029666/44444b28-2df8-42ee-9ca1-219988cd7844)

**Comment by GaryElshaw** [comment]
> Is this a GUI bug?  That's not the options I see in daemon and libtransmission.

Options in the preferences of the GTK client.

![image](https://github.com/transmission/transmission/assets/69029666/aee432be-e368-4c4a-985d-8faf07e77d68)

**Comment by tearfur** [comment]
Ah my memory didn't serve me right again... This *is* consistent with the daemon and libtransmisson.

"Allow encryption" means Transmission won't actively initiate encrypted connections, but if a peer requested an encrypted connection, it will oblige.

Perhaps a better wording would be something along the lines of "Prefer no encryption".

**Comment by GaryElshaw** [comment]
I might be alone in my thinking, but it mystifies me why someone might be reluctant to connect with an encrypted peer, as opposed to me seeing how their might be some good security reasoning why you might not want to engage with an uncrypted peer.

My point being shouldn't these options be from the standpoint of the user requiring or not requiring encryption? That _preference_ doesn't really come into it?

**Comment by tearfur** [comment]
People with CPU-limited devices often prefer to avoid encryption whenever possible.

Encryption is generally quite expensive in terms of CPU usage. This applies as well in Transmission, as it is one of the biggest CPU eaters among all calculations.
