### ISSUE TITLE
Transmission should separately store the pool of listening sockets and temporary sockets

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#5780]
### What is the issue?

Dedicated issue to track the discussion that started at https://github.com/transmission/transmission/issues/5714#issuecomment-1632320957.

### Which application of Transmission?

None

### Which version of Transmission?

2ec19e6

**Comment by tearfur** [comment]
@ckerr I'd to like to self-assign this issue, but I have no permission to do it.

**Comment by tearfur** [comment]
Note to self: Keep https://github.com/transmission/transmission/pull/5773#discussion_r1262719640 in mind when writing this.

**Comment by ckerr** [comment]
@tearfur I think you should be able to self-assign now; but I'm not positive, so please @ me if you need anything

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/issues/5714#issuecomment-1633499835 is a related pre-existing bug in the peer pool code that should be fixed either as part of this work or on its own.
