### ISSUE TITLE
the track server returned an error : Tracker HTTP response 500 (internal server error)

### ISSUE THREAD

**Issue by nemomen76** [transmission/transmission#5782]
### What is the issue?

Is one day that more files downloading is stopped with this icon on the file 

<img width="60" alt="Schermata 2023-07-14 alle 10 18 53" src="https://github.com/transmission/transmission/assets/138798349/7ab6b909-4005-4e10-9192-10b87b6e9acd">
 and this message "the track server returned an error : Tracker HTTP response 500 (internal server error)"  . .Anyone know whats mean? thanks.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3

**Comment by tearfur** [comment]
Most likely you had a temporary connection problem to the tracker. Most likely it is ok now, yes?

**Comment by Pentaphon** [comment]
Sounds like a server issue, not a Transmission issue.
