### ISSUE TITLE
Crash when download dir is a nfs mount point

### ISSUE THREAD

**Issue by M95D** [transmission/transmission#5796]
### What is the issue?

transmission-daemon 4.0.3, running on OpenWrt snapshot r22977, 64bit, on a Raspberry Pi 3B+

The temporary download directory is a local ordinary dir. The download dir (where the finished files should be moved) is nfs mountpoint stored on another machine.
When a torrent finishes downloading, transmission daemon crashes. There is no error saved in the log file.
It crashes very frequently, but this is so far the only crash that I can reproduce.

Thanks.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
This servercide might be caused by having TM copy the files to any other partition, not just nfs-based. This causes TM to use all available resources for that copy operation, breaking in the process. Using network-mounted partitions only aggravates things. Better script the copy-operation AND then relocate-without-moving-operation.

**Comment by ckerr** [comment]
If you can provide a backtrace from a debug build, that would be great.

Instructions on building Transmission are in the README on github.com/transmission/transmission. After building, run the debugger this way:

```sh
$ gdb transmission-daemon
$ handle SIGPIPE nostop noprint pass
$ run --foreground
... wait until crash ...
$ thread apply all bt
```

**Comment by M95D** [comment]
OK, [I fixed it](https://github.com/openwrt/packages/pull/21584).

While trying to get a crash log, I noticed there were some audit logs created when these crashes happened. It was a seccomp issue with the OpenWrt package. It seems that it fixed a lot of crashes, not just the nfs mountpoint issue.

Thank you.

**Comment by ckerr** [comment]
@M95D thank you for the followup, for finding the bug, and for submitting a PR! :green_heart:
