### ISSUE TITLE
Needed update for the app icon in Mac OS

### ISSUE THREAD

**Issue by Zeebrah** [transmission/transmission#580]
It has been several years since the updated design guidelines from Apple and current skeuomorphic icon look kind of weird and dated in Dock. It would be really be appreciated to be at least able to choose between icons in preferences. It's just a pity that otherwise perfect torrent client is not ideal design-wise

**Comment by 1lias** [comment]
This becomes a bigger and bigger issue with most apps having an updated design and transition sticking out like a sore thumb.

**Comment by Zeebrah** [comment]
> This becomes a bigger and bigger issue with most apps having an updated design and transition sticking out like a sore thumb.

Indeed it is. And the worst part is that I started this thread over a year ago and NOTHING changed. I'm starting to suspect that Transmission is slowly dying

**Comment by 1lias** [comment]
> > This becomes a bigger and bigger issue with most apps having an updated design and transition sticking out like a sore thumb.
> 
> Indeed it is. And the worst part is that I started this thread over a year ago and NOTHING changed. I'm starting to suspect that Transmission is slowly dying

How could we push this issue to higher importance? Transmission is an incredible fast and clean torrent client, we need to keep it up to date for the sake of giving an exaple to all the other clients (who usually bloat and use information of users).

**Comment by 1lias** [comment]
> I started sketching out an icon that matches the new macOS icon layout/perspective. It's sort of plain so far (I think the dark-grey base plate could use some more detail, like the ul/dl cutout in the original icon), but I'm not sure what to add... Maybe the entire base could be a double-arrow shape? If anyone knows what Hugo's original icon is meant to be referencing (is there a specific shifter that uses a red handle like this?) that would be helpful inspiration.
> 
> ![transmission](https://user-images.githubusercontent.com/8733615/52224834-de68f200-285d-11e9-9480-d5bd3677daaa.png)

I like your design, though it needs a few changes. Would you like to try and complete it together so we have something ready to show to the others?
