### ISSUE TITLE
Tracker URL cannot be changed if base URL stays the same

### ISSUE THREAD

**Issue by drws** [transmission/transmission#5802]
### What is the issue?

A tracker's URL cannot be changed when the base URL stays the same. For example, an URL `http://tracker.tld` cannot be changed into `http://tracker.tld?pass=1337`. Workarounds by deleting the entry or temporary changing the base URL work, but it is still an unnecessary restriction.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3

**Comment by Pentaphon** [comment]
Interesting! I didn't think this was true but I can confirm it. This does seem unnecessary.
