### ISSUE TITLE
Message's Portuguese translation missing space

### ISSUE THREAD

**Issue by jrom99** [transmission/transmission#5809]
### What is the issue?

Both download and upload messages in the main UI are missing a space between the number and the word "peers".

![image](https://github.com/transmission/transmission/assets/47498278/9f0b156b-bd27-4f76-8cd0-1371a2a8e675)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by mikedld** [comment]
Fixed on Transifex for pt_BR, will apply on next translations sync.

**Comment by jrom99** [comment]
I'm not sure if I should also report this here, but in pt_BR we also use "pares" instead of "peers" (singular being "par")

**Comment by mikedld** [comment]
I'm going to close this as solved by #6453. Unfortunately, it targets 4.1 and not 4.0, I apologize.
