### ISSUE TITLE
transmission-remote unauthorized for rpc-authentication-required daemon

### ISSUE THREAD

**Issue by cybersteel8** [transmission/transmission#581]
I have enabled rpc-authentication-required and set a username and password. I have also disabled the rpc-whitelist and in a browser, I am able to access the transmission web gui as it prompts me to type in the username and password.

However, transmission-remote is now disallowed from accessing transmission-daemon. I often SSH into my machine and use transmission-remote.

Is there a step I have missed in getting transmission-remote to authenticate with transmission-daemon? Or is there a deeper issue occurring?

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. It is usually a good idea to read the [documentation](https://www.mankier.com/1/transmission-remote#-n) first...

**Comment by cybersteel8** [comment]
I'm sorry, I went through the manual twenty times and every time I missed the -n parameter. I feel blind. Thanks for highlighting it for me!
