### ISSUE TITLE
relocating an installation

### ISSUE THREAD

**Issue by backstube** [transmission/transmission#582]
Hi,
a transmission installation needs to be moved to a different disk. In this migration, path names change a bit. The goal is to have the daemon keep all of its settings as if no change would've occured (torrent dates/time stamps, ratios, renames, dl states, etc.).

In order to reach this goal, all `.torrent` files, all files in download directory, all daemon's settings have been rsync'ed to the new location. User permissions and ownerships are typically cared of by rsync and have been checked afterwards.

In `.config/transmission-daemon/settings.json` the directory settings have been adjusted accordingly before restart. 
Inside torrent's resume files, the old file system locations seem to be hard coded between two colons. They all have been sed'd to match the new location. By the looks of it they seem just fine for the new setup.

Once daemon gets fired up again, it completely ignores the *.resumes, starting off from scratch with each torrent there is, ignores former completed torrents and starts at 0%. Also renames, stats are gone.

What's wrong? What's missing? Can anyone please shine a light on this? Thanks in advance.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
