### ISSUE TITLE
Download stoped | MAC 

### ISSUE THREAD

**Issue by Qarnabite** [transmission/transmission#5823]
### What is the issue?

So I was downloading multiple files and some files just stop downloading for no reason someone stop at 92% some more some less. It is like this for two days 
<img width="1355" alt="Screenshot 2023-07-26 at 12 42 48 copy" src="https://github.com/transmission/transmission/assets/61066350/46b054e3-21c1-4b2a-a39d-08b65b0055b1">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by Pentaphon** [comment]
>for no reason

you have no peers
