### ISSUE TITLE
[Feature request] transmission-show to display sizes in bytes

### ISSUE THREAD

**Issue by superbonaci** [transmission/transmission#5824]
### What is the issue?

Option to display sizes in bytes:
```
$ transmission-show -B nz.torrent
  Total Size: 1337968919
$ transmission-show --bytes nz.torrent
  Total Size: 1337968919
```

Instead of default, which is auto:
```
$ transmission-show m.torrent
  Total Size: 1.34 GB
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

2.93

**Comment by Pentaphon** [comment]
This doesn't seem practical to torrent users.

**Comment by tearfur** [comment]
I suppose this shouldn't be very hard to implement.

Although I can see it being useful for scripts, you may find using the RPC API directly to be more flexible and straight-forward.

**Comment by superbonaci** [comment]
> I suppose this shouldn't be very hard to implement.
> 
> Although I can see it being useful for scripts, you may find using the RPC API directly to be more flexible and straight-forward.

Sample command line?

**Comment by superbonaci** [comment]
`aria2` and `dumptorrent` can do it now that I've checked, so can close the issue if not needed.

**Comment by tearfur** [comment]
You can find all the details at https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md.

Assuming you are writing shell scripts, you would probably want to use curl. Something along the lines of:

```
curl -H 'X-Transmission-Session-Id: <your CSID>' --data '{"arguments": {"fields": ["totalSize"]}, "method": "torrent-get", "tag": <arbitrary number>}'
```

Disclaimer: Didn't actually try the command.

**Comment by tearfur** [comment]
> `aria2` and `dumptorrent` can do it now that I've checked, so can close the issue if not needed.

Sure thing.
