### ISSUE TITLE
MacOS torrent priority chevron no longer visible 

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5826]
### What is the issue?

I just noticed the up or down chevron that denotes torrent priority is no longer visible in the macOS client.

An assumption, given that it was the last major change to the macOS client, but possibly related to #5147. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (22da17f13f)

**Comment by Coeur** [comment]
Confirmed.
Hover the middle of the icon of a torrent, open that menu, change the priority to High or Low: there are no longer any UI indication of that priority.
