### ISSUE TITLE
uTP is barely working/not working at all

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#5829]
### What is the issue?

Quite literally what the title says. The handshake's fine, but no data can be transferred using uTP at all.

If you've been seeing a lot of `setting {} do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error` logs, this is probably what's causing them.

I'll be posting some test results to prove my point.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.1-dev (22da17f)

**Comment by GaryElshaw** [comment]
That's been an issue for a loooong time.

**Comment by tearfur** [comment]
Is there an existing issue for it? Do you know that the cause is uTP, or are you just seeing the log spam?

**Comment by tearfur** [comment]
So far I can find https://github.com/transmission/transmission/issues/590#issuecomment-1448742341 that is pointing out the log spam.

**Comment by GaryElshaw** [comment]
I've raised the log spam previously; i'm wondering if you might have finally hit where some of the big network issues are though.

**Comment by tearfur** [comment]
To prove that the logs are caused by uTP, I have made the small patch below and collected some Transmission logs.

```patch
diff --git a/libtransmission/peer-mgr.cc b/libtransmission/peer-mgr.cc
index d9f38cef5..6dc3e41e1 100644
--- a/libtransmission/peer-mgr.cc
+++ b/libtransmission/peer-mgr.cc
@@ -432,11 +432,22 @@ public:
             {
                 /* some protocol error from the peer */
                 peer->do_purge = true;
-                tr_logAddDebugSwarm(
-                    s,
-                    fmt::format(
-                        "setting {} do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error",
-                        peer->display_name()));
+               if (auto msgs = dynamic_cast<tr_peerMsgs*>(peer); msgs != nullptr)
+                {
+                    tr_logAddDebugSwarm(
+                        s,
+                        fmt::format(
+                            "setting {} do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error ({})",
+                            peer->display_name(), msgs->is_utp_connection() ? "uTP" : "TCP"));
+                }
+                else
+                {
+                    tr_logAddDebugSwarm(
+                        s,
+                        fmt::format(
+                            "setting {} do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error",
+                            peer->display_name()));
+                }
             }
             else
             {
```
[log.txt](https://github.com/transmission/transmission/files/12191157/log.txt)

```bash
$ wc -l log.txt
1311 log.txt
$ grep -F 'peer-mgr.cc:441' log.txt | wc -l
1062
$ awk '/peer-mgr.cc:441/ && /uTP/' log.txt | wc -l
1059
```

You can see that among 1311 lines of logs, 1062 lines are the `do_purge` logs, and among them `1059` are caused by uTP, while the remaining ones are caused by TCP (no webseeds since I was seeding only).

*Side note: The triple duplicate `do_purge` logs mentioned in #5287 are all caused by TCP as far as I can see.*

**Comment by tearfur** [comment]
> The handshake's fine, but no data can be transferred using uTP at all.

I've yet to prove this part, I will get to it tonight.

**Comment by Pentaphon** [comment]
Yep, people have been saying this for a long time and that's why I turn uTP off entirely for non-testing, personal use. I turn it off for every client but especially Transmission.

**Comment by tearfur** [comment]
> Yep, people have been saying this for a long time and that's why I turn uTP off entirely for non-testing, personal use. I turn it off for every client but especially Transmission.

Welp, I'm quite new here so I didn't notice those discussions. Could you point me to them?

**Comment by GaryElshaw** [comment]
This has been a catch-all regarding everything network-related. It mostly consists of [complaints and conjecture](https://github.com/transmission/transmission/issues/5261).

**Comment by tearfur** [comment]
I'm well-aware of it, even read through it all. Didn't see anything related to this issue.

**Comment by GaryElshaw** [comment]
That's because the primary respondents do not code. They can see the issue, but can't diagnose it.

**Comment by Pentaphon** [comment]
> Welp, I'm quite new here so I didn't notice those discussions. Could you point me to them?

https://forum.transmissionbt.com/viewtopic.php?t=17357

There's other discussions but they are buried under other complaints about connection quality

**Comment by tearfur** [comment]
Well damn, I can't reproduce the problem now. Will close the issue if I can't figure it out.
