### ISSUE TITLE
Transmission Daemon crash when listing torrents

### ISSUE THREAD

**Issue by rootkwok** [transmission/transmission#5834]
### What is the issue?

Seems [this commit]( https://github.com/transmission/transmission/commit/31f2c7aa29996b154eef49816df49bf983574c80) introduced the problem, as now m->piece_count is being accessed before the return short circuiting when !m:

-  auto const* const m = tor->incompleteMetadata;
-  return m == nullptr || m->piece_count == 0 ? 0.0 : (m->piece_count - std::size(m->pieces_needed)) / (double)m->piece_count;
 + auto const& m = tor->incomplete_metadata;
 + auto const& n = m->piece_count;
 + return !m || n == 0 ? 0.0 : (n - std::size(m->pieces_needed)) / static_cast<double>(n);`

BT:
#0  0x00007f621fb2502b pthread_kill (libc.so.6 + 0x9902b)
#1  0x00007f621faca5e8 raise (libc.so.6 + 0x3e5e8)
#2  0x00007f621faae4f8 abort (libc.so.6 + 0x224f8)
#3  0x00007f621fe933b2 std::__glibcxx_assert_fail(char const*, int, char const*, char const*) (libstdc++.so.6 + 0xdd3b2)
#4  0x000055c7323e7f34 std::_Optional_base_impl<tr_incomplete_metadata, std::_Optional_base<tr_incomplete_metadata, false, false> >::_M_get() const (transmission-daemon + 0x1baf34)
#5  0x000055c7322c3761 tr_torrentStat(tr_torrent*) (transmission-daemon + 0x96761)
#6  0x000055c7323cfdfa addTorrentInfo (transmission-daemon + 0x1a2dfa)
#7  0x000055c7323c98f3 tr_rpc_request_exec_json(tr_session*, tr_variant const*, void (*)(tr_session*, tr_variant*, void*), void*) (transmission-daemon + 0x19c8f3)
#8  0x000055c7323c54d4 handle_rpc_from_json (transmission-daemon + 0x1984d4)
#9  0x00007f6220730b95 n/a (libevent-2.1.so.7 + 0x2cb95)
#10 0x00007f62207186cc bufferevent_run_readcb_ (libevent-2.1.so.7 + 0x146cc)
#11 0x00007f622071b620 n/a (libevent-2.1.so.7 + 0x17620)
#12 0x00007f6220726c45 n/a (libevent-2.1.so.7 + 0x22c45)
#13 0x00007f62207283af event_base_loop (libevent-2.1.so.7 + 0x243af)
#14 0x000055c7323db73d tr_session_thread_impl::sessionThreadFunc(event_base*) (transmission-daemon + 0x1ae73d)
#15 0x00007f621fe97943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
#16 0x00007f621fb230af n/a (libc.so.6 + 0x970af)
#17 0x00007f621fbb59f0 n/a (libc.so.6 + 0x1299f0)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

master

**Comment by tearfur** [comment]
Oops.
