### ISSUE TITLE
Question about commit version in GTK/Qt

### ISSUE THREAD

**Issue by stefanos82** [transmission/transmission#5841]
I have just pulled the latest changes and HEAD is ec0567e09, but both GTK and Qt clients show d7473f22ed.

![image](https://github.com/transmission/transmission/assets/1777466/40788d05-d0a1-4ef7-b0b5-870ecd06fc95)

Is this an expected behavior?

**Comment by nevack** [comment]
Have you rebuilt apps?

**Comment by stefanos82** [comment]
I follow the `Building Transmission from Git (updating)`:

```sh
$ cd Transmission/build
$ make clean
$ git submodule foreach --recursive git clean -xfd
$ git pull --rebase --prune
$ git submodule update --init --recursive
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimzed binary with debug information. (preferred)
# Use -DCMAKE_BUILD_TYPE=Release to build full optimized binary.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make
$ sudo make install
```

but instead of using `make`, I use `ninja`:

```sh
cd "$HOME/repositories/transmission/build/"
ninja clean
git submodule foreach --recursive git clean -xfd
git pull --rebase --prune
git submodule update --init --recursive
cmake -G Ninja \
    -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" \
    -DRUN_CLANG_TIDY=OFF \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
ninja
```

So far, it worked just fine; this is the first time I've got such a behavior.

I always run both my GUI clients and check their version.

**Comment by nevack** [comment]
Thanks, I can see this too with `transmission-daemon`

Version is taken from `libtransmission/version.h`
This file is generated on `cmake`.

@mikedld I think cmake somehow skips `libtransmission/version.h` regeneration if REVISION is not changes.

**Comment by tearfur** [comment]
This is my workflow, it seems to work as expected (if there are no new submodules):

```bash
$ cd Transmission/build
$ git pull -p --recurse-submodules
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ cmake --build .
```

**Comment by stefanos82** [comment]
> ~This is my workflow, it seems to work as expected (if there are no new submodules):~
> 
> Edit: Nope it doesn't, I goofed.
> 
> ```shell
> $ cd Transmission/build
> $ git pull -p --recurse-submodules
> $ cmake --build .
> ```

Can you try my way I build `transmission`? I have shared it above.

**Comment by tearfur** [comment]
I don't have to try it to know it doesn't. 😓 

I do have an idea to use [add_custom_target](https://cmake.org/cmake/help/latest/command/add_custom_target.html) to fix this though.
