### ISSUE TITLE
 Secure https announce links not reaching tracker (v4.xx) [Mojave 10.14.6]

### ISSUE THREAD

**Issue by agoodseed** [transmission/transmission#5842]
### What is the issue?

When using v4.00 and above my secure (https) announce links cannot reach the tracker. Only unsecured (http) announce links are able to reach the tracker which isn't ideal. Im not aware if Mojave is or isn't supported but I assume it is as I am able to install it. I am running macOS Mojave 10.14.6.

For anymore information or questions please don't hesitate to ask. 
Thank you for your time and consideration.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.00 - 4.03

**Comment by tearfur** [comment]
It is a bit of a far-fetched guess, but I think #5702 may fix this.

Could you test with the latest Nightlies at https://build.transmissionbt.com/job/trunk-mac/?

**Comment by tearfur** [comment]
Also may be fixed by #5969. Please re-open if you see this bug again.
