### ISSUE TITLE
Feature Request: handling shortlinks to magnet links when copy-pasting

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#5847]
### What is the issue?

When copy-pasting a shortlink (aka, from an URL shortener) of a magnet link, the macOS app says it can't support that format.
Other clients like qBittorrent are supporting it.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0

**Comment by killemov** [comment]
Interesting ... Does the protocol still begin with `magnet:` ? If so, is referral part of the spec?

**Comment by nevack** [comment]
> Interesting ... Does the protocol still begin with `magnet:` ? If so, is referral part of the spec?

I think it does not.
You need to make connection, check for status code to be 301/302/303 and then get magnet from  `Location` header.

**Comment by nevack** [comment]
> Be VERY specific about what does what not. Is it a `magnet:`? Then HTTP status 301/... have nothing to do with this.

Location header can point to any protocol.
You can have some http link, resolving which redirects you to magnet link

Example:
1. magnet: ArchLinux latest iso - 
`magnet:?xt=urn:btih:7a9c4a72e79fcf5f65f091e462b60e589af3f865&dn=archlinux-2023.08.01-x86_64.iso`
2. I shorten it via https://tormag.ezpz.work/
3. Shortened url - https://tormag.ezpz.work/31qcrs7t46
4. If I open the link in Chrome, default app associated with magnet scheme opens.

<img width="1222" alt="image" src="https://github.com/transmission/transmission/assets/8330119/1fe80823-e97e-4239-80dd-29c5ceac47a8">

**Comment by killemov** [comment]
Nice that it works with Chrome, now test it with curl. (Does the macOS app use curl also?)

**Comment by nevack** [comment]
> Nice that it works with Chrome, now test it with curl. (Does the macOS app use curl also?)

```bash
$ curl -s -I -X GET https://tormag.ezpz.work/31qcrs7t46
HTTP/2 302
server: nginx/1.10.3 (Ubuntu)
date: Wed, 02 Aug 2023 08:07:06 GMT
content-type: text/html; charset=UTF-8
location: magnet:?xt=urn:btih:7a9c4a72e79fcf5f65f091e462b60e589af3f865&dn=archlinux-2023.08.01-x86_64.iso
```

macOS naturally uses NSURLRequest/NSURLSession.
You can make a connection for provided URL and check if location header points to magnet link.
