### ISSUE TITLE
[RPC] Document session.session-id

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#5861]
### What is the issue?

In the [RPC](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#41-session-arguments) the entry for `session-id` is missing. Please document thoroughly and include when/why it changes and if it is related to [X-Transmission-Session-Id](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#231-csrf-protection).

### Which application of Transmission?

None

### Which version of Transmission?

3.00+

**Comment by valcomm** [comment]
Is it really an issue?
`X-Transmission-Session-Id` is a header for any HTTP request.
Link to the `Session requests` points to one running daemon (session).  
Those are two separate entities.

**Comment by tearfur** [comment]
Thanks for pointing that out. Not sure why users and downstream developers should be concerned with when and why it changes though.
