### ISSUE TITLE
feature requests: HTTPS support for connecting remote sesseion on the Qt App

### ISSUE THREAD

**Issue by uprprc777** [transmission/transmission#5887]
### What is the issue?

I setup my transmission deamon behind a nginx reverse proxy server with HTTPS enabled.
I cannot connect without HTTPS support.
I can't find any option about HTTPS though I can set the port to 443 but the app can only connect via HTTP

### Which application of Transmission?

Qt app on Windows / Linux

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by killemov** [comment]
TM does not support this.
Do the same thing on your client machine and make another proxy to tunnel http requests over https. OR make the entire tunnel end-to-end over ssl.

**Comment by uprprc777** [comment]
> TM does not support this. Do the same thing on your client machine and make another proxy to tunnel http requests over https. OR make the entire tunnel end-to-end over ssl.

I am sorry. What is `TM`?

**Comment by killemov** [comment]
Ah, TM => TransMission.

**Comment by tearfur** [comment]
Related: #13
