### ISSUE TITLE
Third-Party: Bump fmt to 10.1.1

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#5894]
### What is the issue?

fmt 10.1.1 is out today. The good news is that all of the console warnings when compiling with gcc and debuginfo have been fixed with this version. The downside, on this machine at least, compile time seems to have increased.

https://github.com/fmtlib/fmt/releases/tag/10.1.1

### Which application of Transmission?

All

### Which version of Transmission?

4.0.x - 4.1.x

**Comment by rafe-s** [comment]
I can upon a separate issue for this, but it would be nice if, coincidental to the version bump, cmake could search the system for fmt, googletest, and fast float.

**Comment by ckerr** [comment]
Thank you  @GaryElshaw :+1:
