### ISSUE TITLE
Improve timestamp granularity info window

### ISSUE THREAD

**Issue by bbsixzz** [transmission/transmission#5917]
### What is the issue?

Running time shows time in segments like 1 minute, 1 hour, 1 day etc.

Please keep counting minutes and seconds e.g. 1 day, 3 hours and 20 seconds

Date added shows only year month day, please add exact time as well.

<img width="480" alt="Screenshot 2023-08-19 at 03 31 20" src="https://github.com/transmission/transmission/assets/47334163/9906ae7e-aa81-4ae3-ba76-9e9567ac0fdb">

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3

**Comment by killemov** [comment]
The data is present, just rendered too coarsely.
