### ISSUE TITLE
[WebUI] Menu bar buttons aren't greying out in dark mode

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#5919]
### What is the issue?

As the title suggests, the buttons in the menu bar are not greying out as intended in the WebUI on dark mode, high contrast or not.

![image](https://github.com/transmission/transmission/assets/46261767/0a9f182a-5868-4ad5-ac72-5918b739aad4)

### Which application of Transmission?

Web client

### Which version of Transmission?

`main` (eea7d4d8866232ef0740aa6bf1e3e127a9d7e40e)

**Comment by tearfur** [comment]
`git bisect` revealed #5470 to be the point it broke.

**Comment by Rukario** [comment]
This was going to be covered in #5897 but would it be better to split into own PR? (I haven't taken contrast into account)

**Comment by tearfur** [comment]
If you are willing to, yes please. Otherwise, just edit the PR description to fix this issue.

**Comment by Rukario** [comment]
It's just one line of code so making a PR for it might be an overkill but I'll be happy to let it have it. I think it'll depend on if that PR will make it to 4.1.0 or not.

**Comment by tearfur** [comment]
The number of lines is not important, what it fixes is. I think this is a must-have for `4.1.0`.

If anything, it being just 1 line of code makes it very easy to be accepted.

**Comment by Rukario** [comment]
~~Not that it's really about PR tagging shenanigans~~

**Comment by LAfricain** [comment]
I have the same issue with but not with the web version, with the desktop version, all the menu bar is greyed out, impossible to use the tools inside the menu

![Image](https://github.com/user-attachments/assets/5c991486-925f-4325-a829-c68d6aa6b497)

**Comment by tearfur** [comment]
This looks to be a completely different problem, please create a new issue.
