### ISSUE TITLE
set peer ID

### ISSUE THREAD

**Issue by qqdaiyu55** [transmission/transmission#592]
Any idea how to set peer ID to let the private tracker identify/filter the peer? (For example, there's a private tracker only allow users in allowed peer ID list to connect to itself) 
Thanks!

**Comment by ckerr** [comment]
Transmission intentionally won't be adding this as a feature. This would be horribly irresponsible to expose as a general use feature.

However, I will say that I haven't been above tweaking `version.h` by hand before compiling when testing a development build on trackers that disallow development builds...
