### ISSUE TITLE
Donation in Bitcoin

### ISSUE THREAD

**Issue by NCrashed** [transmission/transmission#5922]
### What is the issue?

Hello,

I really love the software and want to support it. I caught myself several times that I went to donation page and cannot make the donation as only PayPal and credit cards are supported. Unfortunatelly, I don't have access to the enlisted tools. Could you please add more permissionless way to donate you, please?

### Which application of Transmission?

None

**Comment by Pentaphon** [comment]
Discussed here: https://github.com/transmission/transmission/discussions/4140
plz close

**Comment by NCrashed** [comment]
No problem. Although, I don't agree with the carbon footprint take as banks and states make much more carbon footprint than Bitcoin. But, the owner have right to not accept it. Closing.
