### ISSUE TITLE
Crash NSInternalInconsistencyException', reason: 'assertion failed: Invalid type (./libtransmission/net.h:421)'

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#5926]
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS 10.15 Catalina, PeakHour, PIA, and Xcode 12.3 (all fully updated).

Running Transmission-bb386cf17f Build #9243 (Aug 18, 2023, 8:58:17 PM)

Process:               Transmission [1546]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            Transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Transmission [1546]
User ID:               502

Date/Time:             2023-08-20 22:28:07.683 -0400
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 50000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'assertion failed: Invalid type (./libtransmission/net.h:421)'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff356e1a17 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff6e246a9e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff356e1875 +[NSException raise:format:] + 181
3   Transmission                        0x0000000100e43118 _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEElS3_ + 280
4   Transmission                        0x0000000100e14201 _ZNSt3__14hashI17tr_socket_addressE7ip_hashERK10tr_address + 85
5   Transmission                        0x0000000100e1b027 _ZNSt3__112__hash_tableINS_17__hash_value_typeI17tr_socket_address12tr_handshakeEENS_22__unordered_map_hasherIS2_S4_NS_4hashIS2_EENS_8equal_toIS2_EELb1EEENS_21__unordered_map_equalIS2_S4_S9_S7_Lb1EEENS_9allocatorIS4_EEE4findIS2_EENS_15__hash_iteratorIPNS_11__hash_nodeIS4_PvEEEERKT_ + 31
6   Transmission                        0x0000000100e1afd7 _ZNSt3__112__hash_tableINS_17__hash_value_typeI17tr_socket_address12tr_peer_infoEENS_22__unordered_map_hasherIS2_S4_NS_4hashIS2_EENS_8equal_toIS2_EELb1EEENS_21__unordered_map_equalIS2_S4_S9_S7_Lb1EEENS_9allocatorIS4_EEE14__erase_uniqueIS2_EEmRKT_ + 19
7   Transmission                        0x0000000100e1af47 _ZN8tr_swarm11remove_peerEP11tr_peerMsgs + 287
8   Transmission                        0x0000000100e100c1 _ZN10tr_peerMgr14reconnectPulseEv + 2109
9   Transmission                        0x0000000100e11c32 _ZN10tr_peerMgr14bandwidthPulseEv + 214
10  Transmission                        0x0000000100ea910b event_process_active_single_queue + 1121
11  Transmission                        0x0000000100ea5fab event_base_loop + 1134
12  Transmission                        0x0000000100dfe2f5 _ZN22tr_session_thread_impl17sessionThreadFuncEP10event_base + 87
13  Transmission                        0x0000000100dfe6e7 _ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM22tr_session_thread_implFvP10event_baseEPS7_S9_EEEEEPvSE_ + 63
14  libsystem_pthread.dylib             0x00007fff6f5ef109 _pthread_start + 148
15  libsystem_pthread.dylib             0x00007fff6f5eab8b thread_start + 15

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreGraphics        	0x00007fff35a89ac0 ripc_GetColor + 272
1   com.apple.CoreGraphics        	0x00007fff35abdac7 render_glyph_list + 291
2   com.apple.CoreGraphics        	0x00007fff35ab3fc5 render_glyphs + 380
3   com.apple.CoreGraphics        	0x00007fff35ab36c9 draw_glyph_bitmaps + 1728
4   com.apple.CoreGraphics        	0x00007fff35ab2f57 ripc_DrawGlyphs + 1799
5   com.apple.CoreGraphics        	0x00007fff35ab2494 CGContextDelegateDrawGlyphs + 963
6   com.apple.CoreGraphics        	0x00007fff35e1bf8c draw_glyphs + 1021
7   com.apple.CoreGraphics        	0x00007fff35ab2012 CGContextShowGlyphsWithAdvances + 512
8   com.apple.CoreText            	0x00007fff374aa8a9 CTFontDrawGlyphsWithAdvancesInternal + 2923
9   com.apple.UIFoundation        	0x00007fff665a6744 -[NSCoreTypesetter _NSFastDrawString:length:attributes:paragraphStyle:typesetterBehavior:lineBreakMode:rect:padding:graphicsContext:baselineRendering:usesFontLeading:usesScreenFont:scrollable:syncAlignment:mirrored:boundingRectPointer:baselineOffsetPointer:wantsTextLineFragments:drawingContext:] + 3157
10  com.apple.UIFoundation        	0x00007fff665a17d8 -[NSCoreTypesetter _stringDrawingCoreTextEngineWithOriginalString:rect:padding:graphicsContext:forceClipping:attributes:stringDrawingOptions:drawingContext:wantsTextLineFragments:validatedAttributedString:firstNonRenderedCharacterIndex:foundSoftHyphenAtEOL:enginePathUsed:] + 1221
11  com.apple.UIFoundation        	0x00007fff6659f03c __NSStringDrawingEngine + 5948
12  com.apple.UIFoundation        	0x00007fff665d6b07 _NSStringDrawingCore + 173
13  com.apple.AppKit              	0x00007fff32a4c07d _NSDrawTextCell + 3724
14  com.apple.AppKit              	0x00007fff32af5283 -[NSTextFieldCell drawInteriorWithFrame:inView:] + 798
15  com.apple.AppKit              	0x00007fff32c86693 -[NSTableHeaderCell drawInteriorWithFrame:inView:] + 1019
16  com.apple.AppKit              	0x00007fff32c85d2e -[NSTableHeaderCell _drawThemeContents:highlighted:inView:] + 522
17  com.apple.AppKit              	0x00007fff32c872b0 -[NSTableHeaderView _drawHeaderOfColumn:] + 218
18  com.apple.AppKit              	0x00007fff32c871a9 -[NSTableHeaderView _drawColumnHeaderWithIndexes:] + 205
19  com.apple.AppKit              	0x00007fff32c86d58 -[NSTableHeaderView drawRect:] + 340
20  com.apple.AppKit              	0x00007fff32a5391f _NSViewDrawRect + 139
21  com.apple.AppKit              	0x00007fff32a52c2e -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2170
22  com.apple.AppKit              	0x00007fff32a5202a -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 1271
23  com.apple.QuartzCore          	0x00007fff40fb672d CABackingStoreUpdate_ + 595
24  com.apple.QuartzCore          	0x00007fff410163a1 invocation function for block in CA::Layer::display_() + 53
25  com.apple.QuartzCore          	0x00007fff40fb5c2a -[CALayer _display] + 2103
26  com.apple.AppKit              	0x00007fff32a51a1a -[_NSBackingLayer display] + 537
27  com.apple.AppKit              	0x00007fff329b3507 -[_NSViewBackingLayer display] + 800
28  com.apple.QuartzCore          	0x00007fff40fb4cad CA::Layer::display_if_needed(CA::Transaction*) + 757
29  com.apple.QuartzCore          	0x00007fff40f92fca CA::Context::commit_transaction(CA::Transaction*, double) + 334
30  com.apple.QuartzCore          	0x00007fff40f91bb4 CA::Transaction::commit() + 644
31  com.apple.AppKit              	0x00007fff32a68041 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 266
32  com.apple.AppKit              	0x00007fff33186920 ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
33  com.apple.CoreFoundation      	0x00007fff3566513c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
34  com.apple.CoreFoundation      	0x00007fff3566506c __CFRunLoopDoObservers + 457
35  com.apple.CoreFoundation      	0x00007fff35664604 __CFRunLoopRun + 884
36  com.apple.CoreFoundation      	0x00007fff35663c33 CFRunLoopRunSpecific + 466
37  com.apple.HIToolbox           	0x00007fff3427faad RunCurrentEventLoopInMode + 292
38  com.apple.HIToolbox           	0x00007fff3427f7c5 ReceiveNextEventCommon + 584
39  com.apple.HIToolbox           	0x00007fff3427f569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
40  com.apple.AppKit              	0x00007fff328c83c9 _DPSNextEvent + 883
41  com.apple.AppKit              	0x00007fff328c6c10 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
42  com.apple.AppKit              	0x00007fff328b891e -[NSApplication run] + 658
43  com.apple.AppKit              	0x00007fff3288a706 NSApplicationMain + 777
44  org.m0k.transmission          	0x0000000100d028b2 main + 47
45  libdyld.dylib                 	0x00007fff6f3e6cc9 start + 1

Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x00007fff6f52e32a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6f5eee60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6f4b5808 abort + 120
3   libc++abi.dylib               	0x00007fff6c71a458 abort_message + 231
4   libc++abi.dylib               	0x00007fff6c70b8bf demangling_terminate_handler() + 262
5   libobjc.A.dylib               	0x00007fff6e248a57 _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff6c719887 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff6c719829 std::terminate() + 41
8   org.m0k.transmission          	0x0000000100e1b027 std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::__unordered_map_hasher<tr_socket_address, std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::hash<tr_socket_address>, std::__1::equal_to<tr_socket_address>, true>, std::__1::__unordered_map_equal<tr_socket_address, std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::equal_to<tr_socket_address>, std::__1::hash<tr_socket_address>, true>, std::__1::allocator<std::__1::__hash_value_type<tr_socket_address, tr_peer_info> > >::find<tr_socket_address>(tr_socket_address const&) + 31 (__hash_table:2390)
9   org.m0k.transmission          	0x0000000100e1afd7 unsigned long std::__1::__hash_table<std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::__unordered_map_hasher<tr_socket_address, std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::hash<tr_socket_address>, std::__1::equal_to<tr_socket_address>, true>, std::__1::__unordered_map_equal<tr_socket_address, std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, std::__1::equal_to<tr_socket_address>, std::__1::hash<tr_socket_address>, true>, std::__1::allocator<std::__1::__hash_value_type<tr_socket_address, tr_peer_info> > >::__erase_unique<tr_socket_address>(tr_socket_address const&) + 19 (__hash_table:2534)
10  org.m0k.transmission          	0x0000000100e1af47 tr_swarm::remove_peer(tr_peerMsgs*) + 287
11  org.m0k.transmission          	0x0000000100e100c1 tr_peerMgr::reconnectPulse() + 2109 (peer-mgr.cc:2074)
12  org.m0k.transmission          	0x0000000100e11c32 tr_peerMgr::bandwidthPulse() + 214 (peer-mgr.cc:2157)
13  org.m0k.transmission          	0x0000000100ea910b event_process_active_single_queue + 1121
14  org.m0k.transmission          	0x0000000100ea5fab event_base_loop + 1134 (event.c:2006)
15  org.m0k.transmission          	0x0000000100dfe2f5 tr_session_thread_impl::sessionThreadFunc(event_base*) + 87 (session-thread.cc:244)
16  org.m0k.transmission          	0x0000000100dfe6e7 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) + 63 (thread:300)
17  libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
18  libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6f52a746 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6f4adeea nanosleep + 196
2   libc++.1.dylib                	0x00007fff6c6f66da std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   org.m0k.transmission          	0x0000000100e3ed0a tr_web::Impl::curlThreadFunc() + 448
4   org.m0k.transmission          	0x0000000100e3ef81 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_web::Impl::*)(), tr_web::Impl*> >(void*) + 59 (thread:300)
5   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff6f52c756 kevent + 10
1   org.m0k.transmission          	0x0000000100daa53c -[VDKQueue watcherThread:] + 203 (VDKQueue.mm:190)
2   com.apple.Foundation          	0x00007fff37d1f222 __NSThread__start__ + 1064
3   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6f527dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6f528160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff35665d07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff356647c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff35663c33 CFRunLoopRunSpecific + 466
5   com.apple.AppKit              	0x00007fff32a69bf4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 5:: com.apple.coreaudio.AQClient
0   libsystem_kernel.dylib        	0x00007fff6f527dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6f528160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff35665d07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff356647c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff35663c33 CFRunLoopRunSpecific + 466
5   com.apple.audio.toolbox.AudioToolbox	0x00007fff339daf60 GenericRunLoopThread::Entry(void*) + 166
6   libAudioToolboxUtility.dylib  	0x00007fff6bd6e611 CAPThread::Entry(CAPThread*) + 77
7   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff6f527e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68f2ab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68f2a9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68f2a7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68f2a1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 7:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6f527e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68f2ab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68f2a9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68f2a7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68f2a1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6f5eab68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6f5eab68 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6f5eab68 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	0x00007fff6f5eab68 start_wqthread + 0

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff6f527e3e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff6f38db6b _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff6f38df97 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff6f39b795 _dispatch_worker_thread + 284
4   libsystem_pthread.dylib       	0x00007fff6f5ef109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6f5eab8b thread_start + 15

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000a326000  rcx: 0x000070000a3243a8  rdx: 0x0000000000000000
  rdi: 0x000000000000a30b  rsi: 0x0000000000000006  rbp: 0x000070000a3243d0  rsp: 0x000070000a3243a8
   r8: 0x000070000a324270   r9: 0x000070000a324440  r10: 0x000070000a326000  r11: 0x0000000000000246
  r12: 0x000000000000a30b  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff6f52e32a  rfl: 0x0000000000000246  cr2: 0x00007fff95d99c58
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-bb386cf17f Build #9243 (Aug 18, 2023, 8:58:17 PM)

**Comment by tearfur** [comment]
@dantearmok Any more this type of crashes after using the test build I gave you in #5881?

**Comment by dantearmok** [comment]
Your build has been rock solid for 2 days now.  No crashes at all.
