### ISSUE TITLE
magnet stuck at 50% metadata

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#5943]
### What is the issue?

For an unknown reason, while working fine for other magnets, one popular magnet (830 seeds, 1 leecher) has been stuck at 50% metadata for one day.
<img width="659" alt="Capture d’écran 2023-08-26 à 00 36 14" src="https://github.com/transmission/transmission/assets/839992/3cc11841-b9a3-4aa2-8551-c2e9ee5b8a72">

Being stuck in that situation seems to say that we potentially have some problems at properly requesting the magnet metadata in some circumstances.

- Pausing+Unpausing the magnet did not resolve the situation.
- Closing+Restarting Transmission resolved the situation immediately.

Issue is reproducible for me when I download many magnets, many are permanently stuck until I restart the app:
<img width="644" alt="Capture d’écran 2023-08-27 à 00 39 15" src="https://github.com/transmission/transmission/assets/839992/420cf564-36bf-40f1-95d6-880498fac4fd">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (cb2462aacd)

**Comment by Coeur** [comment]
Chronologically, might have been a regression from #5903 (@ckerr) or #5889 (@tearfur) or it's an older bug that I didn't notice before.

**Comment by tearfur** [comment]
Can't reproduce on daemon. Since you can reproduce it, mind if you `git bisect` to find out which commit it was?

**Comment by Coding4Coffee** [comment]
I have this same issue, also on MacOS, latest trunk 

`4.1.0-dev (3be0d728dd)`

Before restart, 60 peers and message log with recurring logs of the below:

```
2023-09-12 xx:27:57 +0000 peer-mgr.cc:662 [Debug] xxx: setting [xxx]:xxx do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
2023-09-12 xx:28:19 +0000 torrent-magnet.cc:380 [Debug]xxx: next piece to request: 1
```

After restart, immediately fixes itself and see this in the log:

```
2023-09-12 xx:29:22 +0000 torrent-magnet.cc:69 [Debug] xxx: metadata is 29254 bytes in 2 pieces
2023-09-12 xx:29:22 +0000 torrent-magnet.cc:380 [Debug] xxx: next piece to request: 0
2023-09-12 xx:29:22 +0000 torrent-magnet.cc:380 [Debug] xxx: next piece to request: 1
2023-09-12 xx:29:23 +0000 torrent-magnet.cc:319 [Debug] xxx: got metadata piece 0 of 16384 bytes
2023-09-12 xx:29:23 +0000 torrent-magnet.cc:355 [Debug] xxx: saving metainfo piece 0... 1 remain
2023-09-12 xx:29:23 +0000 torrent-magnet.cc:319 [Debug] xxx: got metadata piece 1 of 12870 bytes
2023-09-12 xx:29:23 +0000 torrent-magnet.cc:355 [Debug] xxx: saving metainfo piece 1... 0 remain
2023-09-12 xx:29:23 +0000 torrent-magnet.cc:307 [Debug] xxx: we now have all the metainfo!
```

How can I help debug @tearfur ?

**Comment by tearfur** [comment]
@Coding4Coffee Are you able to build yourself?

If you do, then please use `git bisect` to find the commit that introduced the bug.

**Comment by tearfur** [comment]
@Coding4Coffee @Coeur Maybe #5791 has something to do with this. Maybe you can try a build before this PR.

**Comment by Coeur** [comment]
Took me some hours to reproduce, but yes, I managed to reproduce on #5791 (31f2c7aa29) from July 15. Doesn't strictly mean that this is the faulty commit: I would also need to compare with a previous build to confirm.
But it does seem that we're not requesting the correct packet, especially in second screenshot: we want part 3 but we keep receiving part 1 or 2.
<img width="1133" alt="Capture d’écran 2023-09-17 à 01 58 13" src="https://github.com/transmission/transmission/assets/839992/69802195-2a99-44ca-b4f3-fdfe27f91a40">
<img width="1133" alt="Capture d’écran 2023-09-17 à 02 05 45" src="https://github.com/transmission/transmission/assets/839992/34c602f1-35f7-45dc-a428-facd72f3e18e">

**Comment by Coeur** [comment]
Oh, another detail: those are pure DHT or PEX peers: there are no trackers in the magnet link.

**Comment by Coeur** [comment]
And I got multiple times this error in my Xcode console:
```
2023-09-17 02:31:40.860817+0200 Transmission[22720:329463] [Framework] SHKSandbox: No read access to file with url: file:///Users/User/Library/Application%20Support/Transmission/Torrents/f3the-hash-of-the-magnet42.torrent
```

**Comment by tearfur** [comment]
Do you mean Transmission might be trying to access the wrong file?

**Comment by Coeur** [comment]
The SHKSandbox issue is an attempt to access the wrong file, yes. I don't know if it's expected.

**Comment by Coeur** [comment]
Still happening on Today's main. Stuck at 50% metadata for one hour, despite it being a popular torrent with hundreds of seeds.
<img width="414" alt="Capture d’écran 2023-10-08 à 21 39 43" src="https://github.com/transmission/transmission/assets/839992/1dc42dd1-d4ad-4537-860f-135409e5d991">

**Comment by tearfur** [comment]
So checking out a commit before #5791 did not fix this?

**Comment by Coeur** [comment]
I'll try it in November rain.

**Comment by Coeur** [comment]
So annoying when it happens: thousands of seeds, hundreds of connected peers, but metadata stuck forever.
<img width="391" alt="Capture d’écran 2023-11-20 à 01 49 26" src="https://github.com/transmission/transmission/assets/839992/a078e9de-59f3-4ce4-aebc-085ec7c59623">

I'm just flooded with thousands of such logs:
2023-11-20 00:54:20 +0000 torrent-magnet.cc:368 [Débogage] [...].mkv: next piece to request: 0
2023-11-20 00:54:20 +0000 peer-mgr.cc:781 [Débogage] [...].mkv: setting [89.149.17.8]:34569 do_purge flag because we got [(57) Socket is not connected]

But hard to pinpoint which commit made the regression, since a restart of Transmission will almost always fix it.

**Comment by arcticfoxwp** [comment]
I've been having this problem as well for a long time on v4.. Now on 4.05, I notice I am also getting metadata stuck at 33.33% and 66.66%.

**Comment by Xist12gh** [comment]
for those who don't come across it: 
in @Coeur PR, after going on a wild goose chase because I got my `||` messed up, I traced a similar issue with stuck metadata at https://github.com/transmission/transmission/pull/6272#issuecomment-1848599934

@arcticfoxwpg if you can, try compile from source with this patch on current master
```
diff --git a/libtransmission/torrent-magnet.cc b/libtransmission/torrent-magnet.cc
index 73318895b..639580281 100644
--- a/libtransmission/torrent-magnet.cc
+++ b/libtransmission/torrent-magnet.cc
@@ -68,7 +68,7 @@ bool tr_torrentSetMetadataSizeHint(tr_torrent* tor, int64_t size)
 
     if (tor->incomplete_metadata)
     {
-        return false;
+        return tor->incomplete_metadata->metadata.size() == (uint64_t)size;
     }
 
     int const n = (size <= 0 || size > INT_MAX) ? -1 : div_ceil(size, MetadataPieceSize);
```

It's the workaround I'm currently running, tried it several times with the magnet set from the PR. 
I suspect the base issue (missing metadata piece from first peer) lies somewhere else, it might not be safe (do we trust a single metadata piece received from a different peer), it's ugly (what's up with the cast), I have no idea if I broke anything else (at least its not obvious) and neither am I sure that you got the same Issue, but it just might help you out till someone who knows his stuff can take a look at it.

**Comment by arcticfoxwp** [comment]
@Xist12gh Sorry, I can't.

**Comment by Xist12gh** [comment]
took a git dive:
the restriction to `msgs->metadata_size_hint` was first introduced by https://github.com/transmission/transmission/commit/bfbf81cea12a2319c6a00f8e6544db3cf6b267b5
There must have been metadata trouble in the past when fetching data from different peers. The commit reworks the incomplete_metadata handling to what we see today. The guard around metadata_size_hint looks kind of like an addition.
Probably from the same thought that crossed my mind: how to guard against peers with incorrect metadata. Well at least we could check the size.
In fact I dug around a bit more and the metadata pieces are quite well guarded in `parseUtMetadata`, and the subsequent incomplete_metadata handling in `torrent-magnet.cc` is also mentioning checksums. Did not bother to verify though.

It seems kind of logical to allow other peers to provide metadata, I can also understand reasons not to.
But it's still strange, why a piece of metadata just gets lost in translation so often, even if its valid peer behaviour.
If we re-allow other peers to provide meta, we kind of hide the underlying issue.

While researching the history of magnet metadata I'm now more confident that we are talking about the same issue regarding stuck magnet meta.
For some reason the unique_ptr in incomplete_metadata just make it appear more often. This is kind of a scary on another level.
Maybe some side effect with peer connection or message code?

Also I'm kind of unhappy with my haphazzard size check. Someone knowing a better solution?
I still think it's a sledgehammer solution. Let me know, if I should open a PR.

Btw the 33% Metadata arcticfoxpwg mentioned is intriguing as I only ever had one piece missing. I'd really like confirmation if it is _only_ metadata_size_hint at play here

**Comment by tearfur** [comment]
@Xist12gh Superb analysis on the cause of this bug! Sounds completely reasonable to me.
I need more time to consider the options we have to go about fixing this though.

> It seems kind of logical to allow other peers to provide metadata, I can also understand reasons not to.

It's kind of embarrassing, but the guard around `metadata_size_hint` in `parseUtMetadata()` was added by me not long ago in ca4cb1a675fb951f6ca975e8bb3d4de1ae25ad57 without much thought. My intention was just to harden the guard, but I was not expecting it to forbid peers other than the first to provide metadata.

**Comment by Xist12gh** [comment]
@tearfur oh that is much cleaner. I can test your patch in about 8h... 

I didn't come across any misbehaving peer with my previous patch yet, so being aggressive is _probably_ fine here.

Redoing the incomplete_metadata was also an idea I was pondering but wasn't sure how to do it cleanly.
If it is ok to re-run the code after the `if` then it should be fine to guard against those corner cases and still be pretty smooth. 

I'll see if I can hack a little testcode into peer-msgs to try to force such a situation when I get around.

**Comment by tearfur** [comment]
I'm coughing up a PR that improves on my initial idea, you may want to wait for that instead.
