### ISSUE TITLE
Release for 4.0.4 tag

### ISSUE THREAD

**Issue by nebulade** [transmission/transmission#5944]
### What is the issue?

While preparing the update for a Cloudron transmission package, I was wondering why there is no release in github for the v4.0.4 tag? Is some pipeline to build assets not working or was something not triggered?

### Which application of Transmission?

None

### Which version of Transmission?

4.0.4

**Comment by GaryElshaw** [comment]
Not ready yet, but soon.

**Comment by mikedld** [comment]
Sorry for the delay, should be good now!

**Comment by nebulade** [comment]
Great thanks! We've updated our package with it as well and works well.

**Comment by ckerr** [comment]
> While preparing the update for a Cloudron transmission package, I was wondering why there is no release in github for the v4.0.4 tag? 

So you're saying 4.0.4. was ... not found?

**Comment by ckerr** [comment]
> While preparing the update for a Cloudron transmission package, I was wondering why there is no release in github for the v4.0.4 tag?

So you got a 4.0.4 not found error?
