### ISSUE TITLE
Nightly Build Web Page Offline

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [transmission/transmission#5946]
### What is the issue?

For I know not how many weeks now the [Mac web page for Transmission Nightly builds](https://build.transmissionbt.com/job/trunk-mac/) has been inaccessible. The error code is 504 gateway time-out. I know not where to get the Mac client of updated nightly builds. I am using an old build from June 2023 but I am sure it has updated since then. It was approximately the time when I created the issue about improved accessibility using the other table view in Mac OS.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0

**Comment by mikedld** [comment]
Says last successful build was 5 days ago but it was indeed unresponsive (not sure for how long). Should be fixed now, thanks for reporting.
