### ISSUE TITLE
download/upload speed info wraps

### ISSUE THREAD

**Issue by tessus** [transmission/transmission#5951]
### What is the issue?

After I updated to transmission-daemon 4.0.4, the download/upload speed info wraps when checking the status via the web client:

<img width="248" alt="image" src="https://github.com/transmission/transmission/assets/223439/190c1f52-cdac-4c48-9879-bf611979f0d8">

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.4

**Comment by tearfur** [comment]
I think this is supposed to be fixed by #5828.

**Comment by tessus** [comment]
Haha, it worked in 4.0.3, so the "fix" actually did the opposite.

**Comment by tearfur** [comment]
Ah, what I meant was, this broke from 4.0.3 -> 4.0.4 and the PR I just mentioned will fix this in a future release if it is accepted.

**Comment by tessus** [comment]
Thanks for the clarification. 

But I am not using a narrow viewport. The browser takes up my full screen (2880 x 1800).
Anyway, the only problem is that I now have to wait another 1 or 2 months before this is fixed. It's not really important, just annoying.

**Comment by tessus** [comment]
If this is already addressed, you can close this issue of you wish

**Comment by GaryElshaw** [comment]
This is occurring in the 4.0.x and 4.1.x branches.

**Comment by killemov** [comment]
Somebody forgot/removed a `white-space: nowrap;`?
@tessus You could hotfix this yourself now by finding the element/class with the built-in developer tools (Chrome/Firefox/...) and adding the above.

**Comment by tessus** [comment]
> You could hotfix this yourself now by finding the element/class with the built-in developer tools (Chrome/Firefox/...) and adding the above.

@killemov that alone does not do it. the width of 70px is too narrow. it should be 90 or 100px. But hot-fixing seems like an option. Thanks.
