### ISSUE TITLE
[Feature] Support handling/creation of up to 256 MiB piece size .torrent files

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#5955]
[qBittorrent 5.0 is on track to support the handling AND creation of up to 256 MB piece size .torrent files](https://github.com/qbittorrent/qBittorrent/pull/19535)

Apparently,  1GB is the maximum piece size that libtorrent-rasterbar (used in qBittorrent and Deluge) can support but **the devs are going to go up to creating 256 MB .torrent files for resource and libtorrent limitation reasons** so it would be good to keep up with these popular open source torrent clients, which now quite possibly the majority of torrent clients used in the wild. 

It would be a good long term goal for **Transmission 5.0** to support the handling and creation of up to 256 MB piece size torrent files so that we are ready for these torrent files when they become more widely used. 

**Edit: https://github.com/qbittorrent/qBittorrent/pull/21295 rolled back to 128MB so that might be a better safe goal.**

**Comment by Coeur** [comment]
If I recall correctly, it's already possible with the macOS client, so I'll tag it "feature disparity". And there may be a previous issue or pull request about the same thing.

**Comment by Coeur** [comment]
@orbital-mango would you like to handle this request?

**Comment by Pentaphon** [comment]
> Note that it's already possible with the macOS client (tested with pieces of 2 GB each), so I'll tag this as "**feature disparity**". And for reference the previous issue on the topic was about raising the limit to 64 MB

Yes, that a late-ish issue just in the hopes that 4.x.x kept up with the qBittorrent 4.x.x series but now that qBittorrent 5.x (which is probably coming out late next year) is going to go up to 256MB, I thought it would be prudent to have an issue in place so somebody out there has plenty of time to tackle it in time for Transmission 5.x.

**Comment by Pentaphon** [comment]
qBittorrent rolled back to 128MB piece sizes so we may also consider that a safe goal. https://github.com/qbittorrent/qBittorrent/pull/21295

**Comment by Coeur** [comment]
For macOS: it was already up to 2 GB at the creation time of your issue.
For Qt, to was increased from 64 MB to 256 MB in #6211.
For GTK, I made #7251.

**Comment by Pentaphon** [comment]
> For macOS: it was already up to 2 GB at the creation time of your issue.
> For Qt, to was increased from 64 MB to 256 MB in #6211.
> For GTK, I made #7251.

Understood. I was just offering this information in case 256MB becomes an issue.

**Comment by rayman3003** [comment]
Desperately waiting for this feature. Recently found so many torrent files that have 256 MiB piece sizes, that qBittorrent can't open them.

**Comment by Coeur** [comment]
Transmission can already open them. It just can't create them with the GTK client. I made a PR three weeks ago.
