### ISSUE TITLE
[Windows] Invalid characters in file name or path crashes Transmission

### ISSUE THREAD

**Issue by kissglay** [transmission/transmission#596]
If the pathname or filename was named (deliberately inserted in "Save as", "Destination folder" or contained in the filename in torrent file itself) with some invalid characters reserved by windows(i.e. *?<> etc), transmission crashed after a while.

For details, plz refer to https://forum.transmissionbt.com/viewtopic.php?f=16&t=17539&start=60#p73289

**Comment by Tharn** [comment]
See #61 also.

**Comment by ckerr** [comment]
I think this was fixed by https://github.com/transmission/transmission/commit/99033b067da01c646a3e12a13f8bbcd43a9dd056. If this issue is still affecting you in a [nightly build](https://transmissionbt.com/download), please file a new issue with information from the new version. Thank you!
