### ISSUE TITLE
Transmission cannot process some Unicode names

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#5967]
### What is the issue?

For example text "Дыскаграфія" cannot be displayed correctly. In Qt client and in browser it is displayed as "Ды�?каг�?афі�?".

In JSON it looks like `Ð\u0094Ñ\u008bÑ?ÐºÐ°Ð³Ñ?Ð°Ñ\u0084Ñ\u0096Ñ?`

Client: Linux 4.0.3, Windows 4.0.4, Browser (Any)
Server: Windows 7 (4.0.4)

**Comment by killemov** [comment]
I suspect the used font has no glyph for these specific codes. (Maybe try to replace the font in the style-sheet to confirm this is the case.)

**Comment by hardhub** [comment]
> I suspect the used font has no glyph for these specific codes. (Maybe try to replace the font in the style-sheet to confirm this is the case.)

If I open Dev Tools in browser and paste text from clipboard to HTML - it is displayed correctly.

And it is displayed bad on Windows where most likely all fonts are present.

I initially also thought it is fonts issue but no.

I guess issue is introduced between 4.0.0 and 4.0.4 but I need to investigated more to be sure, it will force me to reinstall server part to resr.

**Comment by hardhub** [comment]
@killemov,  yes transmission-4.0.3-qt5-x64.msi does not have this issue.

**Comment by tearfur** [comment]
Can't reproduce on English Windows 10. I suppose your OS language is not English?

![image](https://github.com/transmission/transmission/assets/46261767/6941fbba-8de9-46e3-bdf7-e0bd63d4c0f5)
![image](https://github.com/transmission/transmission/assets/46261767/8f7872e7-b126-4b88-a1ce-a8a31c251166)

**Comment by tearfur** [comment]
Can't reproduce on English Windows 10. I suppose your OS language is not English? Also is this still a problem in the latest nightly builds https://build.transmissionbt.com/job/trunk-win32/?

![image](https://github.com/transmission/transmission/assets/46261767/6941fbba-8de9-46e3-bdf7-e0bd63d4c0f5)
![image](https://github.com/transmission/transmission/assets/46261767/8f7872e7-b126-4b88-a1ce-a8a31c251166)

**Comment by hardhub** [comment]
It is not QT5 build. I cannot test it on Windows 7 x64.

P.S. I am using English version but it does not matter (you can install MUI which does not affect anything).

**Comment by tearfur** [comment]
> It is not QT5 build. I cannot test it on Windows 7 x64.

What do you mean? If it is on Windows, then it is most likely QT5.

Can you maybe give the filename of the installer you are using?

**Comment by hardhub** [comment]
Nightly builds do not provide QT5 version. It provides QT6 version only which is not compatible with Windows 7.

If you look at releases you will find the difference:

```
Transmission-4.0.4-dsym.zip
transmission-4.0.4-qt5-x64-pdb.7z
transmission-4.0.4-qt5-x64.msi
transmission-4.0.4-qt5-x86-pdb.7z
transmission-4.0.4-qt5-x86.msi
transmission-4.0.4-x64-pdb.7z
transmission-4.0.4-x64.msi
transmission-4.0.4-x86-pdb.7z
transmission-4.0.4-x86.msi
Transmission-4.0.4.dmg
transmission-4.0.4.tar.xz

```
QT6: transmission-4.0.4-x64.msi
QT5: transmission-4.0.4-qt5-x64.msi

**Comment by tearfur** [comment]
I've tried both `transmission-4.0.4-x64.msi` and `transmission-4.0.4-qt5-x64.msi`, I can see the Unicode characters normally. 🤔

**Comment by hardhub** [comment]
> I've tried both `transmission-4.0.4-x64.msi` and `transmission-4.0.4-qt5-x64.msi`, I can see the Unicode characters normally. 🤔

It looks strange. I have made a lot of additional tests including different VM machines. And cannot reproduce it anywhere except one physical machine. The only thing which I know for now 4.0.3 works fine there.

Something is updated in 4.0.4 which works wrong exactly on that PC. And I even cannot understand what can be a reason in theory, which components it rely on in the system.

**Comment by hardhub** [comment]
Can that be the reason in some way?

```
void tr_locale_set_global(char const* locale_name) noexcept
{
    try
    {
        std::ignore = std::locale::global(std::locale{ locale_name });

        std::ignore = std::cout.imbue(std::locale{});
        std::ignore = std::cerr.imbue(std::locale{});
    }
    catch (std::exception const&)
    {
        // Ignore.
    }
}
```
which is now called in daemon.cc?

**Comment by tearfur** [comment]
That is also my suspicion, but then I cannot reproduce problem on my machine, so I have no way to be sure of it.

I'm afraid you'd have to do all the hard work of getting to the bottom of this.

**Comment by streengcheeze** [comment]
I am also experiencing this issue. Had no issues in 4.0.3 and started seeing the issue right when I upgraded to 4.0.4. Downgraded back to 4.0.3 and issue went away.

In 4.0.4, running a Local Session doesn't seem to have the issue but running it in Remote Session mode with the daemon running, the issue exists.

OS: 
Windows 11

Installed packages:
transmission-4.0.3-x64.msi (no character display issues)
transmission-4.0.4-x64.msi (character display issues exist)

**Comment by streengcheeze** [comment]
Freshly spun up Windows 11 VM also experiencing same issue with 4.0.4, only when running in remote session/daemon mode and not local session.

**Comment by tearfur** [comment]
Got it, I can reproduce myself now.

So the bug only happens for Transmission RPC interface hosted on Windows.

**Comment by tearfur** [comment]
Normal (before #6005):

![linux](https://github.com/transmission/transmission/assets/46261767/8deea836-313c-468c-af99-521c4c9a37f3)

Bugged:

![windows](https://github.com/transmission/transmission/assets/46261767/e3b13ad8-f6d8-4af8-a3fd-fa2a4e527f05)

**Comment by Hackerpcs** [comment]
I don't get how this wasn't a showstopper for the 4.0.4 on Windows, especially since the msi installer doesn't allow downgrades for some reason and an uninstall/reinstall is needed. 4.0.4 shouldn't be available on Windows until this is fixed, this is a major bug
