### ISSUE TITLE
Renaming a file pauses transfer with web seeds

### ISSUE THREAD

**Issue by differenceclouds** [transmission/transmission#5968]
### What is the issue?

Using the context menu Rename File function usually works, but seems to pause the transfer indefinitely when only web seeds are present (often found when downloading from Archive.org). Unsure if when the seeders are mixed between normal and web only the normal ones work.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by killemov** [comment]
Sounds very logical to me. How else could a resource be identified if not by its url? Rename the file back until completed.

**Comment by differenceclouds** [comment]
fair enough
