### ISSUE TITLE
Segmentation fault (core dumped) above 4.0.3 with non root user

### ISSUE THREAD

**Issue by gduckHUN** [transmission/transmission#5971]
### What is the issue?

Hi!

I build Transmission4 on old Zyxel NAS hardware (armv5), with cmake 3.26.5, gcc 12.3.0. There were no problems until version 4.0.3.

But now (with 4.0.4  or 4.1.x beta) segmentation fault (core dumped) error if I run transmission-daemon with non root user. With root user, transmission-daemon start without any error message.

Do you have any idea/recommendation?

Thanks,
  Csaba

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4 and 4.1.x

**Comment by ckerr** [comment]
Hey @gduckHUN, could you please try running transmission-daemon -- preferably a build from `main` -- in the foreground inside a debugger to get a backtrace of the crash that you're seeing?

**Comment by gduckHUN** [comment]
Hi [ckerr](https://github.com/ckerr), thank you for your help, I think, I found the problem source!

`Reading symbols from transmission-daemon...
(gdb) r
Starting program: /e-data/b853c50d-a73d-42e9-8b57-1e0e8d6b563c/ffproot/ffp/bin/transmission-daemon

Program received signal SIGSEGV, Segmentation fault.
0x4042be60 in __sync_fetch_and_add_4 () from /ffp/lib/libstdc++.so.6
(gdb) c
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)q`

My "developer" NAS libstdc++.so.6 vesion is different than others: 
developer: /ffp/lib/libstdc++.so.6 -> libstdc++.so.6.0.32
others: /ffp/lib/libstdc++.so.6 -> libstdc++.so.6.0.24

Thank you and sorry, this is not a bug, this is my fault :(

Best regards:
   Csaba

**Comment by ckerr** [comment]
@gduckHUN thanks for the followup!
