### ISSUE TITLE
The main window does not show up

### ISSUE THREAD

**Issue by Major-Mike** [transmission/transmission#5982]
### What is the issue?

I installed this program (Transmission 4.0.4 x64) and I was really looking forward to using it.

![image](https://github.com/transmission/transmission/assets/55165479/3c26e9e1-c556-4a0e-a369-2cd7c960b477)

On Windows 11 Pro machine. Initially after the install I opened it up, so far so good and then shut it down. Now each time I open it, get a quick white square and then nothing, the systray icon is there, the icon on the taskbar is there but no window shows no matter what you do (hence no screenshots) but this is what shows up in the systray

![image](https://github.com/transmission/transmission/assets/55165479/7d68efa8-905b-4c58-a63f-d32c85a6a835)

if I click on the checkmark for "Main Window" the taskbar icon disappears, checking it again bring that taskbar icon but still no window shows, no matter what I do.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by tearfur** [comment]
Weird. Maybe try maximising it by pressing Windows+Up.

**Comment by Major-Mike** [comment]
@tearfur Well the Windows+Up did the trick but that is so bizarre, never had this issue with any program, might be a Qt thing but I have used other Qt apps before, so not sure why but at least it works, so thank you.

**Comment by dftf-stu** [comment]
Two things I'd suggest:

1. Make-sure to download "transmission-4.0.6-x64.msi" and not "transmission-4.0.6-qt5-x64.msi".  The "qt5" version is mostly just there now for Windows 7 and 8 users, as qt6 doesn't support any Windows before 10.  Qt5 was [only tested](https://doc.qt.io/archives/qt-5.15/supported-platforms.html) up-to the 22H2 version of Windows 11, but not on 23H2 or 24H2, so will likely have issues.

2. Try the latest beta version: "transmission-4.1.0-beta.2-x64.msi" from [here](https://transmissionbt.com/download)
