### ISSUE TITLE
macOS: 2.93 -> 2.94 Update: Sparkle Error: An error occurred while extracting the archive.

### ISSUE THREAD

**Issue by bgeet** [transmission/transmission#600]
Transmission.app 2.93:
`Check for Update...`
`Install Update`
>Downloading Update...
Extracting update...
Update Error! An error occurred while extracting the archive. Please try again later.

*system.log* shows
>Transmission[3281]: Sparkle Error: An error occurred while extracting the archive. Please try again later.

**Comment by mikedld** [comment]
You're on High Sierra (or another new and fancy version). As I noticed, Sparkle tries to mount the DMG under /Volumes and doesn't have permissions to do so. Download and install 2.94 manually or, if you're feeling lucky, do `sudo chmod a+w /Volumes` and try updating once more.

Hope to fix this in 3.x with new Sparkle version (still have to check whether it solves the issue though).

**Comment by bgeet** [comment]
>You're on High Sierra (or another new and fancy version).

Yes, sorry forgot to include.

`sw_vers `
>ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

**Comment by bgeet** [comment]
> Please post a download link for the manual install. The website only has the daily compiles, not 2.94.

Not true.
https://transmissionbt.com/download/ links to 
https://github.com/transmission/transmission-releases/raw/master/Transmission-2.94.dmg
which is the correct d8e60ee44f build that is *2.94*.

**Comment by Logseman** [comment]
Mac OS High Sierra 10.13.4 user here.

1. I reproduced the error
2. I ran `sudo chmod a+w /Volumes` as instructed by Mike.
3. Afterwards the installer got through.

**Comment by DavidMunch** [comment]
Just want to mention that I also see the issue under macOS Sierra (10.12.6), so a wider number of users may be affected by the problem other than those on the most recent version of macOS.

**Comment by DJBabyBuster** [comment]
On high sierra as well and was seeing the same problem.  Manual install took care of it, thanks!

**Comment by digital-discuss** [comment]
I can confirm this error in macOS 10.12.6 Sierra. I'm not going to modify my Volumes folder. No need to update. Nevertheless thanks for moving forward dear developers! This is still the best torrent app I think.

**Comment by mikedld** [comment]
Checked new Sparkle version and it does indeed fix the issue. Bad thing is we'll have another manual update before things get back to normal.

**Comment by bradtchapman** [comment]
> You're on High Sierra (or another new and fancy version). As I noticed, Sparkle tries to mount the DMG under /Volumes and doesn't have permissions to do so. Download and install 2.94 manually or, if you're feeling lucky, do `sudo chmod a+w /Volumes` and try updating once more.
> 
> Hope to fix this in 3.x with new Sparkle version (still have to check whether it solves the issue though).

Ron Howard: "It doesn't."

**Comment by livings124** [comment]
@bradtchapman this should be fixed, but there hasn’t been an update last 3.0 yet. What failure are you seeing?
