### ISSUE TITLE
Tracker favicons not downloading to favicons folder on Windows version of 2.94

### ISSUE THREAD

**Issue by ghost** [transmission/transmission#601]
This is from a clean install of the 64 bit version of 2.94 running on Windows 10.

Tracker favicons are not being displayed, because they are not downloaded to the "favicons" folders at all.

**Comment by Riotous** [comment]
@mikedld You may want to look into this for the 3.0 release because its still there in your nightly and it's one of the first things Windows users will notice when filtering by tracker. Favicons don't seem to download at all.

**Comment by ckerr** [comment]
Fixed by https://github.com/transmission/transmission/pull/2575
