### ISSUE TITLE
Hamburger menu is not fully accessible

### ISSUE THREAD

**Issue by markbaaijens** [transmission/transmission#6010]
### What is the issue?

The hamburger menu on the right of the web/ui, is not showing completely on small screens. It starts from the bottom (see screenshot) and then several options on the top are not accessible when running out of space. Right now, the only way to access these functions is to (temporarily) change the resolution or scale factor of the screen. 

![image](https://github.com/transmission/transmission/assets/3878546/237bd7c9-3c09-40c1-99c1-7bccbbc12842)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3 6b0e49bbb2

**Comment by tearfur** [comment]
Already fixed by #5827 in `main`

**Comment by markbaaijens** [comment]
Tnx for letting me know.

Apparantly, my docker instance is not updated with the latest version in which this particular problem is solved, i,e, 4.0.4 so I'm still at 4.0.3. I'll just wait for that updated version to come by.
