### ISSUE TITLE
Bump libdeflate to 1.19

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#6013]
### What is the issue?

Libdeflate 1.19 out today https://github.com/ebiggers/libdeflate/releases/tag/v1.19

### Which application of Transmission?

All

### Which version of Transmission?

All

**Comment by Pentaphon** [comment]
This project should start using dependabot to get all the libs up to date. 

https://github.com/dependabot

**Comment by GaryElshaw** [comment]
Yep. I would pr these third-party bumps, but are mystified by how git handles them.

**Comment by ckerr** [comment]
@Pentaphon PRs welcomed

**Comment by ckerr** [comment]
> Slightly improved compression performance at levels 1-9.
>
> Improved the compression ratio of very short inputs.

These two items look like they'd benefit us

**Comment by Coeur** [comment]
Done with #6709
