### ISSUE TITLE
[To-do] Refactor MSE handshake

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6022]
### What is the issue?

The more I look into it, the more issues I find in the MSE handshake code. It has lots of repeated code, and numerous subtle bugs that probably stemmed from losing track of the code.

I will first fix whatever I can find in the current code, then start the refactor with that as reference.

### Which application of Transmission?

None

**Comment by killemov** [comment]
Maybe first deduplicate what you can and then fix the remaining issues or you might fix duplicate issues and then have to deduplicate them (the fixes) after all.

**Comment by tearfur** [comment]
Too much code conflict to fix them one by one... I just lumped them in one PR.
