### ISSUE TITLE
transmission-2.94/libtransmission/clients.c:265: duplicate if then elses

### ISSUE THREAD

**Issue by dcb314** [transmission/transmission#603]
[transmission-2.94/libtransmission/clients.c:265]: (style) Expression is always false because 'else if' condition matches previous condition at line 205.
[transmission-2.94/libtransmission/clients.c:284]: (style) Expression is always false because 'else if' condition matches previous condition at line 209.
[transmission-2.94/libtransmission/clients.c:219]: (style) Expression is always false because 'else if' condition matches previous condition at line 215.
[transmission-2.94/libtransmission/clients.c:273]: (style) Expression is always false because 'else if' condition matches previous condition at line 253.

**Comment by mikedld** [comment]
See #442.
