### ISSUE TITLE
The Transmission application does not open for me

### ISSUE THREAD

**Issue by Cristo095** [transmission/transmission#6033]
### What is the issue?

The Transmission application does not open for me, the executed program appears even in task management but I cannot open and use it as I want.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.4 Stable

**Comment by Daniel6372** [comment]
duplicate of https://github.com/transmission/transmission/issues/5982

**Comment by tearfur** [comment]
@Cristo095 If your issue is not yet solved then please re-open.
