### ISSUE TITLE
Torrent creation is broken for directories

### ISSUE THREAD

**Issue by lvella** [transmission/transmission#6056]
### What is the issue?

Torrent creation for directories is broken in main, creates corrupted torrent file. Tested with QT and `transmission-create` command line.

Steps to reproduce:
```
$ mkdir asdf
$ dd if=/dev/urandom of=asdf/file bs=1M count=50
$ ../build/utils/transmission-create asdf
```
then load the created asdf.torrent on any torrent client.

Transmission QT says: "invalid or corrupt torrent file"
qBittorrent says: "Error: invalid length of torrent"

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

6f59d340d6bea32c40b45e671efdffddf25ab5ed

**Comment by tearfur** [comment]
@ckerr Can confirm, 55da783e8f13bab242a41469c74f6587b09093b8 broke it.
