### ISSUE TITLE
Stale peer ID docs

### ISSUE THREAD

**Issue by si14** [transmission/transmission#6076]
### What is the issue?

According to https://github.com/transmission/transmission/blob/6cee75547cfec3810bf4b649b42acae63af3f538/docs/Peer-ID-and-User-Agent.md, Transmission is supposed to use one digit for the major version and two digits for the minor version (presumably, decimal) in its peer ID. However, since at least 3.00 Transmission seems to use triple hex (?) format, so 4.0.4 clients use `-TR4040-` and, according to https://github.com/transmission/transmission/issues/3901, version 3 was sending `A` for 10 (which implies non-base10 version number).

Am I missing something, or is it indeed stale documentation? I'm happy to submit a PR fixing the docs if that's the case.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.4

**Comment by ckerr** [comment]
Hi @si14, yes, thanks for the question!

https://github.com/transmission/transmission/blob/main/CMakeLists.txt#L122 is how the peer-ids are being generated for every release after 3.00:

```sh
# derived from above: peer-id prefix. https://www.bittorrent.org/beps/bep_0020.html
# chars 4, 5, 6 are major, minor, patch in https://en.wikipedia.org/wiki/Base62
# char 7 is '0' for a stable release, 'B' for a beta release, or 'Z' for a dev build
# '-TR400B-' (4.0.0 Beta)
# '-TR400Z-' (4.0.0 Dev)
# '-TR4000-' (4.0.0)
```

As per the old docs, Transmission used to use 'X' in the peer-id to denote beta releases. (IIRC this was back in the Transmission 2 days). IIRC other clients were using 'B' for this, so we changed to follow the to use that for consistency with other apps.

**Comment by ckerr** [comment]
Yes, a PR to update those docs would be very nice. Thank you for offering!
