### ISSUE TITLE
Not enough space on Groups list

### ISSUE THREAD

**Issue by Tockman** [transmission/transmission#6098]
### What is the issue?

There’s no space enough to indicate groups’ names in full.
And no possibilities to make list space any wider.
![Снимок экрана 2023-10-11 в 15 24 56](https://github.com/transmission/transmission/assets/74548419/11ca0e8f-8c14-4804-b0f0-9f142ef13bb6)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by nevack** [comment]
Making it horizontally scrollable will fix this for you?
I don't see any other way to fix it right now, as Preferences window is not resizable, so we cannot make this list any wider.

**Comment by Tockman** [comment]
At least, to have them scrollable is much better than see ugly stumps of respectable names ;)

**Comment by Coeur** [comment]
Why is there an horizontal gap on the right in Russian? I don't have such gap in French.
/Users/coeur/Desktop/Capture d’écran 2023-10-13 à 17.45.29.png

**Comment by Tockman** [comment]
> Why is there an horizontal gap on the right in Russian? I don't have such gap in French. <img alt="Capture d’écran 2023-10-13 à 17 45 29" width="768" src="https://user-images.githubusercontent.com/839992/274949896-afd8a5d3-424b-4241-9417-6bed3e1fb31b.png">

Exactly.
