### ISSUE TITLE
sometimes i have to restart the app for some torrents that have seeds to download.

### ISSUE THREAD

**Issue by rezad1393** [transmission/transmission#6115]
### What is the issue?

sorry if this is vague.
I have the latest version installed on arm/archlinux.

I run the app in terminal 24/7 so that rare torrents and torrents downloaded from torrent website that are not private but may have low seeds get downloaded.

but recently sometimes when I restart the app  then I see some torrents start downloading.
I noticed that they are torrents that are public torrents so maybe this issue doesnt happen with private torrent (not sure as my private torrents have a lot of seeds and usually download fast). 

I dont means torrent are not at all downloaded before restart.

for example when I woke up today I saw a torrent that last night didn't have seeds ,was downloaded and done but when I restarted the app I see a lot of other torrents start to get downloaded.
I investigated the torrents and some of them had a many seeds on their website and after restart they peers are there but not before it.

like somehow before restart of app  they get stuck and don't see any peers.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

**Comment by ExceptionalError** [comment]
I've observed the same behavior. Transmission sits for hours with no downloads (0 kB/s) and upon restart it immediately starts downloading.

**Comment by rezad1393** [comment]
wow.
I thought I had to explain it more but it seems others see it too.

right now I have gone over to qbittorrent app even though it doesn't have native remote support (non-webui) just for this.
and some of the long stuck torrents at 93% and more that had no seed and the peers would just sometimes appear annd then disappear have been completed.

**Comment by tearfur** [comment]
#5801 and #6111 will hopefully fix this. Please ask us to re-open if the issue persists in `4.1.0`.

**Comment by rezad1393** [comment]
> #5801 and #6111 will hopefully fix this. Please ask us to re-open if the issue persists in `4.1.0`.

do these directly fix this?

are you sure this is the issue causing this? I am not disputing this , just checking.

**Comment by tearfur** [comment]
> are you sure this is the issue causing this?

Not 100%, I can never be sure if a patch will solve a specific case related to BT peers, since there are just too many factors.
But I am reasonably confident that they address some of the underlying causes that people with similar issues are facing.

Actually, instead of waiting for `4.1.0`, would you be interested to test with our nightly releases?

**Comment by rezad1393** [comment]
right now I have moved my no-seeds torrents to qbittorrent.
and use transmission just for popular torrents.

**Comment by rezad1393** [comment]
also my torrent client is on arm arch so right now I can't use nightly builds.

**Comment by nevack** [comment]
> also my torrent client is on arm arch so right now I can't use nightly builds.

TBH, it's really straightforward to build it yourself on Arch.
If you are interested, I could provide instructions.

**Comment by rezad1393** [comment]
> > also my torrent client is on arm arch so right now I can't use nightly builds.
> 
> TBH, it's really straightforward to build it yourself on Arch. If you are interested, I could provide instructions.

maybe a simple pkgbuild?

**Comment by rezad1393** [comment]
it these two commits are in 4.0.5 release?
