### ISSUE TITLE
Can't replace string in transmission script?

### ISSUE THREAD

**Issue by iknowzxc** [transmission/transmission#6116]
### What is the issue?
Here is my cmd script which will be executed after torrent download finish.
```
@echo off
chcp 65001
setlocal enabledelayedexpansion

set SRC=D:\PT_Download\
set DST=D:\PT_Hardlink\
@REM set TR_TORRENT_NAME=地火明夷.azw3
set SRC_FILE=%SRC%%TR_TORRENT_NAME%
echo %TR_TORRENT_NAME% > D:\scripts\log.txt
echo %SRC_FILE% >> D:\scripts\log.txt


if exist "%SRC_FILE%" (
    echo Exist >> D:\scripts\log.txt
    dir /b "%SRC_FILE%" | find "." >nul
    if errorlevel 1 (
        echo Foler >> D:\scripts\log.txt
    ) else (
        echo File >> D:\scripts\log.txt
        @REM set OLD_FILE=!SRC_FILE!
        set NEW_FILE=!SRC_FILE:Download=Hardlink!
        echo !SRC_FILE! >> D:\scripts\log.txt
        echo !NEW_FILE! >> D:\scripts\log.txt
        @REM if defined NEW_FILE (
        @REM     echo !NEW_FILE! >> D:\scripts\log.txt
        @REM     echo mklink /H !NEW_FILE! !OLD_FILE! >> D:\scripts\log.txt
        @REM ) else (
        @REM     echo NEW_FILE undef >> D:\scripts\log.txt
        @REM )

    )
) else (
    echo Dont exist >> D:\scripts\log.txt
)


echo finish >>  D:\scripts\log.txt
```

Here is my log
```
爱尔兰咖啡.epub 
D:\PT_Download\爱尔兰咖啡.epub 
Exist 
File 
D:\PT_Download\爱尔兰咖啡.epub 
ECHO is off.
finish 
```

It seems that string replacement didn't succeed in  execution?Futhermore, if i define `TR_TORRENT_NAME` directly in script and call this script it can successfully execute and print correct log. I tried to comment out `chcp 65001` and download an English torrent,the error is same. So what will the error be?

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Transmission 版本：4.0.4 (24077e3511), RPC: 17, WEB Control: 1.6.1(20200913)

**Comment by iknowzxc** [comment]
I found the reason. If `echo %TR_TORRENT_NAME%`  is directly in *.bat then it's okay. If `echo %TR_TORRENT_NAME%` is in `if-else` it dumps nothing. It seems that can execute `if-else` in finish script?

**Comment by mikedld** [comment]
Any valid script should work. It could be that the log file you're writing to is created in unexpected place when Transmission executes the script, compared to when you run it manually. Could you try using an absolute path there, e.g. "C:\Windows\Temp\log.txt" instead of just "log.txt", so that you're sure you're looking at the right file?

**Comment by iknowzxc** [comment]
> Any valid script should work. It could be that the log file you're writing to is created in unexpected place when Transmission executes the script, compared to when you run it manually. Could you try using an absolute path there, e.g. "C:\Windows\Temp\log.txt" instead of just "log.txt", so that you're sure you're looking at the right file?

You are right. I changed my script to absolute path. I post my log above. It still has some error

**Comment by mikedld** [comment]
Here is how your script is being executed: https://github.com/transmission/transmission/blob/c70c49e87bf29828045920b7cd2ac2741107daf6/libtransmission/subprocess-win32.cc#L226-L231

This means that command extensions and delayed expansion are initially disabled. You're already enabling delayed expansion, same needs to be done for command extensions I suppose, i.e. adding the following may help:

```bat
setlocal enableextensions
```

**Comment by iknowzxc** [comment]
> Here is how your script is being executed:
> 
> https://github.com/transmission/transmission/blob/c70c49e87bf29828045920b7cd2ac2741107daf6/libtransmission/subprocess-win32.cc#L226-L231
> 
> This means that command extensions and delayed expansion are initially disabled. You're already enabling delayed expansion, same needs to be done for command extensions I suppose, i.e. adding the following may help:
> 
> ```batchfile
> setlocal enableextensions
> ```

Problem solved. Thank youuuu very much. I have been struggling with this script for 3 days
