### ISSUE TITLE
UDP Announce IP address is not in network byte order

### ISSUE THREAD

**Issue by capicy** [transmission/transmission#6125]
### What is the issue?

I was using transmission to test UDP tracker I programmed and so I had to set `"announce-ip": "1.2.3.4"` in `settings.json`, then my tracker logged that IP `127.0.0.1` had announced itself as `4.3.2.1`...

I double checked documentation of `inet(3)` and `inet_ntoa` which I used to log the IP addresses with bytes directly read from a data packet and it says:

> The inet_ntoa() function converts the Internet host address in, given in ***network byte order***, to a string in IPv4 dotted-decimal notation.

Emphasis mine.

I'm not very familiar with libtransmission, but quick peek at [announcer-udp.cc#L588](https://github.com/transmission/transmission/blob/d273e0f90ec5dff09b4c82d1ab20a9fe7018d26c/libtransmission/announcer-udp.cc#L588) and [announcer-udp.cc#L190](https://github.com/transmission/transmission/blob/d273e0f90ec5dff09b4c82d1ab20a9fe7018d26c/libtransmission/announcer-udp.cc#L190) makes me think that an already network byte ordered address is byteswapped once more when building the UDP announce packet.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

transmission-daemon 4.0.4 (24077e3511)

**Comment by tearfur** [comment]
Hmm, yes. This is a bug that was there from the very beginning #3461 and was never caught.

Nice catch!
