### ISSUE TITLE
Can't build latest release in Alpine linux

### ISSUE THREAD

**Issue by lexfrei** [transmission/transmission#613]
I'm trying to make a docker image with transmission.
Probably related to #66 (same failed line in comments)
This line [fails](https://gist.github.com/lexfrei/72bdcdf291263b222b295be3dd7a1397#file-gistfile1-txt-L3004) on build: `Linking C executable transmission-test-watchdir_generic`
Dockerfile can be found [here](https://github.com/lexfrei/transmission/blob/e410a88195b50f9f9061f2aedb8c1bffb229910c/Dockerfile). Run `docker build Dockerfile` to reproduce.

**Comment by mikedld** [comment]
See #191. If there will be 2.95, I'll cherry-pick the fix there.
