### ISSUE TITLE
segfault upon trying to open .torrent files from the "recent" list

### ISSUE THREAD

**Issue by magicalskye** [transmission/transmission#6130]
### What is the issue?

I am using an up-to-date archlinux and transmission-gtk 4.0.4. I do not have a desktop environment installed, which I mention because it’s perfectly possible that there is a problem with missing dependencies (pacman seems to do this a lot), but a segfault is concerning behaviour in every case.

When I try to open a .torrent file through the regular integrated file browser (i.e. I ctrl + o, navigate to my torrents folder, and click the .torrent), it works fine. If I instead use the integrated list of recent files because I am lazy, transmission-gtk instantly crashes with a segmentation fault. I tried this with a bunch of live iso torrents from different sources, it does not depend on the file, only on the way through which i access it within transmission-gtk. If i right-click the file inside the “recent” list and tell it to copy the path to the file, I get the correct path, so clearly, the list works as expected, only actually using it leads transmission-gtk to try something that the memory manager does not appreciate.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4

**Comment by nevack** [comment]
Hi!
1. By integrated file browser you mean GTK File Chooser? Can you attach screenshot?
2. Can you attach stacktrace? Relevant [ArchLinux wiki page](https://wiki.archlinux.org/title/Debugging/Getting_traces)

FYI @mikedld

**Comment by mikedld** [comment]
Worth running transmission-gtk from terminal to see the log messages it's printing (e.g. GTK warnings / errors / criticals).

**Comment by magicalskye** [comment]
simply running it from the terminal gives no output until the segfault, unfortunately. i tried staring at the strace output first but ultimately i just have no experience debugging misbehaving software so i gave up and came here.

i attached a screenshot of the file selection - the “recent” tab is the one that causes issues, the one that’s active in the screenshot. it shows me the last couple of .torrent files i downloaded and if i pick any of them i get the crash. if i access the exact same files by going to “home” or “downloads” first and navigating through the folders, i can open them just fine.

also attached the gdb trace, i hope i did this correctly

![Screenshot_2023-10-20_01-13-46](https://github.com/transmission/transmission/assets/28151473/98f21cfa-5cb5-4779-b353-4bd4cec0594b)
[transmission-stk-segfault.log](https://github.com/transmission/transmission/files/13048425/transmission-stk-segfault.log)

**Comment by nevack** [comment]
@mikedld I think it fails to dereference nullptr here
https://github.com/transmission/transmission/blob/main/gtk/OptionsDialog.cc#L338

https://docs.gtk.org/gtk3/method.FileChooser.get_current_folder.html
