### ISSUE TITLE
Mistranslation of literal "Ratio" in Spanish

### ISSUE THREAD

**Issue by simonbcn** [transmission/transmission#6135]
### What is the issue?

Screenshot of the Spanish menu `Viewing` > `Sort tasks by`:
![Captura de pantalla 2023-10-20 a las 11 42 50](https://github.com/transmission/transmission/assets/428231/e2d94e82-59f3-4384-91a9-76021ca5353c)

There are 2 items with the same name. The first one (_Tamaño_) is correct: `Size` but the second one `Size` is really `Ratio`.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by mikedld** [comment]
Judging by Transifex, it's actually "State" and "Size" that have the same translation: https://app.transifex.com/transmissionbt/transmissionbt/translate/#es/mac-MainMenu/433168408. Feel free to join and fix it yourself; otherwise, I've created an issue there for someone to hopefully take a look.

**Comment by ckerr** [comment]
I'm going to close this `transmission/transmission` repo ticket since it seems to be a translation issue rather than a code one.

If there is an issue in the code, e.g. if the code's translatable string is incorrect, please do reopen this ticket or open a new one here. Thank you!

**Comment by simonbcn** [comment]
> Judging by Transifex, it's actually "State" and "Size" that have the same translation: https://app.transifex.com/transmissionbt/transmissionbt/translate/#es/mac-MainMenu/433168408. Feel free to join and fix it yourself; otherwise, I've created an issue there for someone to hopefully take a look.

ok, I have applied to join the project at Transifex. 
In any case, `State` doesn't work for me because it is sorting by `Ratio`.
