### ISSUE TITLE
Download-property screen will not close as expected

### ISSUE THREAD

**Issue by markbaaijens** [transmission/transmission#6137]
### What is the issue?

When you double-click on a torrent-entry, a property screen at the right is opened, which is OK. But, this screen can only be closed when clicking *outside* the entry on a blank/empty area. Also not on another entry b/c then the properties for that entry will be shown. If the display has no empty area (below the torrent entries), the only way to close that screen is to click on the main bar. Both feel very unnatural.

What is expected is that clicking on the entry it self (single click), will lead to the closing of the property-screen b/c it is the reverse of what you must to open that screen.

Another option would be some button (cross-icon?) to close that screen.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3 6b0e49bbb2

**Comment by tearfur** [comment]
I think #5947 already implemented what you want.

**Comment by GaryElshaw** [comment]
I'm unsure if that made it to the 4.0 ranch.

**Comment by markbaaijens** [comment]
> I think #5947 already implemented what you want.

From the issue: 'Less dismissable Inspector: Clicking outside will not close it out of the blue (e.g. if you want to play/pause a torrent), only new popup or new X button can dismiss it.'
I cannot see which solution is chosen, but nevertheless, anything else is better than how this (closing of the property inspector) now works.

**Comment by tearfur** [comment]
> Another option would be some button (cross-icon?) to close that screen.

You suggested this, isn't this it?

**Comment by markbaaijens** [comment]
I gave several suggestions for closing the property-screen (click on the entry or close-button) which are all reflected in the linked issue (see my quoted text above), and none of them has really my preference. 

The point is that there is a commit (already merged?), but I'm not able to see what particular solution is chosen, that's all.

**Comment by tearfur** [comment]
It looks like this now in `main`.

![image](https://github.com/transmission/transmission/assets/46261767/96d64ead-6a08-485e-9300-46f8d14d5e4d)

**Comment by markbaaijens** [comment]
Ok, so the solution Is a close button, which is fine for me
