### ISSUE TITLE
download speed slow than other BT client

### ISSUE THREAD

**Issue by huoyan1231** [transmission/transmission#6152]
### What is the issue?

Same BT, trackers
other client ~20MiB 
transmission ~5mb

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.4

**Comment by tearfur** [comment]
If you had set a low upload bandwidth limit (somewhere around 50kB/s), then you are probably seeing #5952. I will close this issue as duplicate if that is the case.

**Comment by huoyan1231** [comment]
> If you had set a low upload bandwidth limit (somewhere around 50kB/s), then you are probably seeing #5952. I will close this issue as duplicate if that is the case.

not setting any bandwidth

**Comment by tearfur** [comment]
Then there has been a long on-going discussion over at #5261.
