### ISSUE TITLE
Cannot (de)select files below depth 1 in a torrent file

### ISSUE THREAD

**Issue by rharish101** [transmission/transmission#6167]
### What is the issue?

Consider a torrent file for the following directory structure:

```
lots-of-numbers/
├── big numbers
│   ├── 10.txt
│   ├── 11.txt
│   └── 12.txt
└── small numbers
    ├── 1.txt
    ├── 2.txt
    └── 3.txt
```

When I open a torrent file with such a directory structure in Transmission, I can only select whether I want to download the directories `big numbers` or `small numbers`. I can neither see nor select/deselect the .txt files.

Here's an example torrent file: https://github.com/webtorrent/webtorrent-fixtures/blob/master/fixtures/lots-of-numbers.torrent

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by simplepad** [comment]
Cannot reproduce on 4.0.4

![image](https://github.com/transmission/transmission/assets/35456194/0cd8f81d-d2ee-4e72-a8f8-a5eeb254d7cc)

**Comment by rharish101** [comment]
My bad, it's caused by my GTK-theme (Canta-dark). I'll close this issue and open it there.
