### ISSUE TITLE
Crash at launch in build #9370

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#6168]
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS Ventura 13.6.1 (w/OCLP 1.1.0), PeakHour 4.1.14, PIA 3.3.1, and Xcode 15.0.
Pipe is 450 Mbps wifi to Comcast coax 100/25 Mbps, with PIA beaming me thru to Toronto CA.
Transmission uses a FW Drobo (long-term seeding) and three USB hard drives.

Running Transmission-72d2823851 Build #9370 (Oct 25, 2023, 8:38:11 PM)

Upon launching Transmission, it bounces a few times in the dock, displays the main and info windows, then crashes.  Note that the dialog asking for permission to access the remote/usb volumes never appears.  This crash is 100% repeatable.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [18946]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-10-25 21:07:30.3038 -0400
OS Version:            macOS 13.6.1 (22G311)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 93000 seconds

System Integrity Protection: enabled

Crashed Thread:        2

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Transmission [18946]

Application Specific Information:
abort() called

Application Specific Backtrace 0:
0   CoreFoundation                      0x00007ff8156dab72 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007ff81520241c objc_exception_throw + 48
2   CoreFoundation                      0x00007ff8156da9d8 +[NSException raise:format:] + 206
3   Transmission                        0x0000000104690f78 _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEElS3_ + 280
4   Transmission                        0x0000000104671bb1 _ZN12_GLOBAL__N_17canReadEP9tr_peerIoPvPm + 1773
5   Transmission                        0x0000000104655405 _ZN9tr_peerIo16can_read_wrapperEv + 171
6   Transmission                        0x00000001046556e6 _ZN9tr_peerIo8try_readEm + 340
7   Transmission                        0x00000001046547d9 _ZN9tr_peerIo13event_read_cbEisPv + 231
8   Transmission                        0x00000001046f6cd8 event_process_active_single_queue + 502
9   Transmission                        0x00000001046f3de3 event_base_loop + 1134
10  Transmission                        0x0000000104645f25 _ZN22tr_session_thread_impl17sessionThreadFuncEP10event_base + 87
11  Transmission                        0x00000001046462f7 _ZNSt3__1L14__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM22tr_session_thread_implFvP10event_baseEPS7_S9_EEEEEPvSE_ + 63
12  libsystem_pthread.dylib             0x00007ff8155891d3 _pthread_start + 125
13  libsystem_pthread.dylib             0x00007ff815584bd3 thread_start + 15

Thread 0::  Dispatch queue: com.apple.main-thread
0   CoreFoundation                	    0x7ff8155f25fc CFEqual + 832
1   CoreServicesInternal          	    0x7ff81848b7a2 GetBookmarkResourcePropertyToInfo(__CFString const*, BookmarkResourcePropertyKeyToInfoStructItem*) + 73
2   CoreServicesInternal          	    0x7ff81848b6c7 BookmarkCopyPropertyFromBookmarkData(BookmarkData&, __CFString const*, unsigned long) + 73
3   CoreServicesInternal          	    0x7ff81848b33c _CFURLCreateResourcePropertiesForKeysFromBookmarkData + 240
4   CoreFoundation                	    0x7ff81564e79e +[NSURL resourceValuesForKeys:fromBookmarkData:] + 25
5   LaunchServices                	    0x7ff815a9d99f +[FSNode(BookmarkData) getName:fileIdentifier:creationDate:forBookmarkData:error:] + 209
6   LaunchServices                	    0x7ff815a9d176 _LSAliasCompareToNode + 347
7   LaunchServices                	    0x7ff815b53360 _LSAliasAndInodeOnContainerMatchesNode + 175
8   LaunchServices                	    0x7ff815a9ce60 _LSBundleMatchesNode(_LSDatabase*, unsigned int, LSBundleData const*, FSNode*, unsigned long long) + 94
9   LaunchServices                	    0x7ff815a9cdfd ___LSBundleFindWithNode_block_invoke + 33
10  LaunchServices                	    0x7ff815a9cc40 LaunchServices::BindingEvaluation::isBindingOK(LaunchServices::BindingEvaluation::State&, LaunchServices::BindingEvaluation::ExtendedBinding const&) + 165
11  LaunchServices                	    0x7ff815a9928b LaunchServices::BindingEvaluation::addAndEvaluate(LaunchServices::BindingEvaluation::State&, void (*)(LaunchServices::BindingEvaluation::State&), std::__1::vector<LaunchServices::BindingEvaluation::ExtendedBinding, std::__1::allocator<LaunchServices::BindingEvaluation::ExtendedBinding>>&) + 435
12  LaunchServices                	    0x7ff815a988dd LaunchServices::BindingEvaluation::runEvaluator(LaunchServices::BindingEvaluation::State&, NSError* __autoreleasing*) + 1009
13  LaunchServices                	    0x7ff815b245dc LaunchServices::BindingEvaluator::getBestBinding(LSContext*, UTTypeRecord* __strong*, NSError* __autoreleasing*) const + 138
14  LaunchServices                	    0x7ff815a97f91 LaunchServices::BindingEvaluator::getBestBinding(LSContext*, NSError* __autoreleasing*) const + 19
15  LaunchServices                	    0x7ff815a97686 _LSBundleFindWithNode + 571
16  LaunchServices                	    0x7ff815a96b82 _LSFindOrRegisterBundleNode + 242
17  LaunchServices                	    0x7ff815c3b1c2 LaunchServices::URLPropertyProvider::capabilityEffectiveNodeForNode(LaunchServices::Database::Context&, FSNode*) + 314
18  LaunchServices                	    0x7ff815c39e5f LaunchServices::URLPropertyProvider::prepareApplicationCapabilityValue(LaunchServices::Database::Context&, FSNode*, __FileCache*, __CFString const*, LaunchServices::URLPropertyProvider::State*, NSError* __autoreleasing*) + 190
19  LaunchServices                	    0x7ff815a92b56 LaunchServices::URLPropertyProvider::prepareValues(__CFURL const*, __FileCache*, __CFString const* const*, void const**, long, void const*, __CFError**) + 587
20  CoreServicesInternal          	    0x7ff81848749f prepareValuesForBitmap(__CFURL const*, __FileCache*, _FilePropertyBitmap*, __CFError**) + 394
21  CoreServicesInternal          	    0x7ff818483d2a _FSURLCopyResourcePropertyForKeyInternal(__CFURL const*, __CFString const*, void*, void*, __CFError**, unsigned char) + 277
22  CoreFoundation                	    0x7ff81563b91c CFURLCopyResourcePropertyForKey + 96
23  IOSurface                     	    0x7ff81f0db744 _iosConnectInitalize + 3541
24  libsystem_pthread.dylib       	    0x7ff815585946 __pthread_once_handler + 65
25  libsystem_platform.dylib      	    0x7ff8155b3f86 _os_once_callout + 18
26  libsystem_pthread.dylib       	    0x7ff8155858f4 pthread_once + 74
27  IOSurface                     	    0x7ff81f0df71b IOSurfaceClientCreateChild + 116
28  IOSurface                     	    0x7ff81f0dbe6e -[IOSurface initWithProperties:] + 89
29  IOSurface                     	    0x7ff81f0dbe01 IOSurfaceCreate + 50
30  CoreUI                        	    0x7ff81d7cd0e2 __csiCompressImageProviderCopyIOSurfaceWithOptions + 1274
31  QuartzCore                    	    0x7ff81d3faac3 CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 2042
32  QuartzCore                    	    0x7ff81d3fa3d6 CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 269
33  QuartzCore                    	    0x7ff81d3fa2a7 CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) + 20
34  QuartzCore                    	    0x7ff81d3f9fe2 CA::Layer::prepare_commit(CA::Transaction*) + 544
35  QuartzCore                    	    0x7ff81d57bcbe CA::Context::commit_transaction(CA::Transaction*, double, double*) + 664
36  QuartzCore                    	    0x7ff81d3d5963 CA::Transaction::commit() + 713
37  AppKit                        	    0x7ff8187bcc3f __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285
38  AppKit                        	    0x7ff818fcfc8c ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
39  CoreFoundation                	    0x7ff815663dc7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
40  CoreFoundation                	    0x7ff815663ce6 __CFRunLoopDoObservers + 482
41  CoreFoundation                	    0x7ff815663271 __CFRunLoopRun + 859
42  CoreFoundation                	    0x7ff8156628bc CFRunLoopRunSpecific + 560
43  HIToolbox                     	    0x7ff81f5adf3d RunCurrentEventLoopInMode + 292
44  HIToolbox                     	    0x7ff81f5adb84 ReceiveNextEventCommon + 199
45  HIToolbox                     	    0x7ff81f5adaa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
46  AppKit                        	    0x7ff81865e25c _DPSNextEvent + 858
47  AppKit                        	    0x7ff81865d106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
48  AppKit                        	    0x7ff81864f788 -[NSApplication run] + 586
49  AppKit                        	    0x7ff8186239a1 NSApplicationMain + 817
50  Transmission                  	       0x1045443ac main + 73 (main.mm:17)
51  dyld                          	    0x7ff81522f41f start + 1903

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 2 Crashed:
0   libsystem_kernel.dylib        	    0x7ff8155511e2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff815588ee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8154afb45 abort + 123
3   libc++abi.dylib               	    0x7ff815543282 abort_message + 241
4   libc++abi.dylib               	    0x7ff8155353fb demangling_terminate_handler() + 267
5   libobjc.A.dylib               	    0x7ff815209a67 _objc_terminate() + 96
6   libc++abi.dylib               	    0x7ff8155426db std::__terminate(void (*)()) + 6
7   libc++abi.dylib               	    0x7ff815544fa7 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	    0x7ff815544f6e __cxa_throw + 116
9   libobjc.A.dylib               	    0x7ff81520251a objc_exception_throw + 302
10  CoreFoundation                	    0x7ff8156da9d8 +[NSException raise:format:] + 206
11  Transmission                  	       0x104690f78 tr_assert_report(std::__1::basic_string_view<char, std::__1::char_traits<char>>, long, std::__1::basic_string_view<char, std::__1::char_traits<char>>) + 280 (tr-assert.mm:22)
12  Transmission                  	       0x104671bb1 (anonymous namespace)::canRead(tr_peerIo*, void*, unsigned long*) + 1773 (peer-msgs.cc:1747)
13  Transmission                  	       0x104655405 tr_peerIo::can_read_wrapper() + 171 (peer-io.cc:390)
14  Transmission                  	       0x1046556e6 tr_peerIo::try_read(unsigned long) + 340 (peer-io.cc:469)
15  Transmission                  	       0x1046547d9 tr_peerIo::event_read_cb(int, short, void*) + 231 (peer-io.cc:490)
16  Transmission                  	       0x1046f6cd8 event_process_active_single_queue + 502 (event.c:1691)
17  Transmission                  	       0x1046f3de3 event_process_active + 220 [inlined]
18  Transmission                  	       0x1046f3de3 event_base_loop + 1134 (event.c:2006)
19  Transmission                  	       0x104645f25 tr_session_thread_impl::sessionThreadFunc(event_base*) + 87 (session-thread.cc:239)
20  Transmission                  	       0x1046462f7 decltype(*static_cast<tr_session_thread_impl*>(fp0).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 30 (type_traits:3859) [inlined]
21  Transmission                  	       0x1046462f7 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 30 (thread:287) [inlined]
22  Transmission                  	       0x1046462f7 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) + 63 (thread:298)
23  libsystem_pthread.dylib       	    0x7ff8155891d3 _pthread_start + 125
24  libsystem_pthread.dylib       	    0x7ff815584bd3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff815553272 __select + 10
1   libcurl.4.dylib               	    0x7ff82ca1f29e Curl_poll + 495
2   libcurl.4.dylib               	    0x7ff82ca17751 multi_wait + 728
3   libcurl.4.dylib               	    0x7ff82ca17473 curl_multi_wait + 23
4   Transmission                  	       0x10468c9ca tr_web::Impl::curlThreadFunc() + 414 (web.cc:707)
5   Transmission                  	       0x10468cc61 decltype(*static_cast<tr_web::Impl*>(fp0).*fp()) std::__1::__invoke<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 26 (type_traits:3859) [inlined]
6   Transmission                  	       0x10468cc61 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 26 (thread:287) [inlined]
7   Transmission                  	       0x10468cc61 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) + 59 (thread:298)
8   libsystem_pthread.dylib       	    0x7ff8155891d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff815584bd3 thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	    0x7ff81554f1de kevent + 10
1   Transmission                  	       0x1045ec0dc -[VDKQueue watcherThread:] + 203 (VDKQueue.mm:189)
2   Foundation                    	    0x7ff8164475d3 __NSThread__start__ + 1009
3   libsystem_pthread.dylib       	    0x7ff8155891d3 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff815584bd3 thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 26:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 27:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 28:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 29:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 30:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 31:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 32:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 33:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 34:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 35:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 36:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 37:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 38:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 39:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 40:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 41:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 42:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 43:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 44:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 45:
0   libsystem_pthread.dylib       	    0x7ff815584bb0 start_wqthread + 0

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007000078e9000  rcx: 0x00007000078e7228  rdx: 0x0000000000000000
  rdi: 0x0000000000007503  rsi: 0x0000000000000006  rbp: 0x00007000078e7250  rsp: 0x00007000078e7228
   r8: 0x00007000078e70f0   r9: 0x00007ff815546729  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000007503  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff8155511e2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

Binary Images:
       0x104541000 -        0x104798fff org.m0k.transmission (4.1.0-dev) <c31467ec-3d83-33c6-87c9-014d638aa389> /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
       0x104bf0000 -        0x104c3bfff org.sparkle-project.Sparkle (1.27.1) <37b3b035-3c83-3a37-a235-cbe17e25f29e> /Users/USER/*/Transmission.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1051bb000 -        0x10539afff com.apple.Metal (306.7.5) <6581cd53-8583-38d1-b4b9-773f1dc3f551> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
       0x1056d3000 -        0x10571afff libllvm-flatbuffers.dylib (*) <d5ce0002-b92a-3d76-9549-1fb7bc428091> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/libllvm-flatbuffers.dylib
       0x17f177000 -        0x17f17afff libGPUCompilerUtils.dylib (*) <d5ce0002-b778-37c5-917b-186e88376470> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/libGPUCompilerUtils.dylib
       0x1f8c17000 -        0x1f8df2fff com.apple.mlcompiler.runtime (*) <6aa382dd-e176-37e7-ae0e-133ba273d6a4> /System/Library/PrivateFrameworks/MLCompilerRuntime.framework/Versions/A/MLCompilerRuntime
       0x104f49000 -        0x104f58fff libobjc-trampolines.dylib (*) <229fe663-a456-31c6-8977-42546bcb07d1> /usr/lib/libobjc-trampolines.dylib
    0x7ff8155e8000 -     0x7ff815a82fff com.apple.CoreFoundation (6.9) <cb4808c4-3518-3ba4-99ab-20517dbee56c> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff818483000 -     0x7ff8184c2fff com.apple.CoreServicesInternal (484) <c7f70854-a514-3d73-9395-6a5c9a3e2656> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7ff815a83000 -     0x7ff815d00ff6 com.apple.LaunchServices (1141.1) <b13a7e69-46f0-3e7a-8f4b-57af15d7533c> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7ff81f0d9000 -     0x7ff81f0eefff com.apple.IOSurface (336.60.1) <887ad259-4e00-31e6-a819-c413233b86c3> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7ff815583000 -     0x7ff81558efff libsystem_pthread.dylib (*) <3a3fa85c-f1fe-336c-bf68-924fc947ade3> /usr/lib/system/libsystem_pthread.dylib
    0x7ff8155b3000 -     0x7ff8155bcfef libsystem_platform.dylib (*) <f1798256-c6b5-335c-bbb5-7978acf41deb> /usr/lib/system/libsystem_platform.dylib
    0x7ff81d786000 -     0x7ff81d8deff9 com.apple.coreui (2.1) <5891c84e-6983-370a-9f69-669f22b1973a> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7ff81d3d3000 -     0x7ff81d739fff com.apple.QuartzCore (1.11) <84ad6e1f-aba1-3bab-aff2-2bbf1d2d76ff> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7ff818620000 -     0x7ff819627fff com.apple.AppKit (6.9) <c5499c27-03c5-3194-815e-94cf6e6b68db> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff81f57f000 -     0x7ff81f876ff9 com.apple.HIToolbox (2.1.1) <bbbf9caf-5b24-3c4c-b275-e85d272258c9> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff815229000 -     0x7ff8152c15ef dyld (*) <3df96f32-b9c9-3566-a6b7-4daebc6d6563> /usr/lib/dyld
    0x7ff815549000 -     0x7ff815582fff libsystem_kernel.dylib (*) <3f11f30e-7216-3a5a-8f7d-504e349b672b> /usr/lib/system/libsystem_kernel.dylib
    0x7ff815430000 -     0x7ff8154b7ff7 libsystem_c.dylib (*) <a720129c-c1cf-3e62-9d76-aa6fa0d31333> /usr/lib/system/libsystem_c.dylib
    0x7ff815534000 -     0x7ff815548ff3 libc++abi.dylib (*) <4dbd2a8f-9459-3d65-a0fc-b86e399b9475> /usr/lib/libc++abi.dylib
    0x7ff8151ee000 -     0x7ff815228fc0 libobjc.A.dylib (*) <5363ad4e-ff0f-3d5e-9499-c3fba7c4a0d8> /usr/lib/libobjc.A.dylib
    0x7ff82c9e3000 -     0x7ff82ca5afff libcurl.4.dylib (*) <9023008d-7bb8-383b-870a-55bff4691ad0> /usr/lib/libcurl.4.dylib
    0x7ff8163ef000 -     0x7ff816d77ff1 com.apple.Foundation (6.9) <b7674982-bc75-3c0e-a6de-ae0b4bc8896c> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=781.1M resident=0K(0%) swapped_out_or_unallocated=781.1M(100%)
Writable regions: Total=4.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=4.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                  640K        4 
CG image                            92K       18 
ColorSync                          240K       26 
CoreAnimation                     2388K       97 
CoreUI image data                 1140K       19 
Foundation                          84K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           216.1M      199 
MALLOC guard page                   32K        8 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.2M       46 
Stack                             30.9M       46 
VM_ALLOCATE                         44K       11 
VM_ALLOCATE (reserved)             3.8G        5         reserved VM address space (unallocated)
__CTF                               824        1 
__DATA                            30.6M      546 
__DATA_CONST                      36.4M      347 
__DATA_DIRTY                      1708K      207 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       176.7M        7 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2011K        2 
__TEXT                           604.3M      568 
dyld private memory                260K        2 
mapped file                      209.8M       38 
shared memory                     1300K       18 
===========                     =======  ======= 
TOTAL                              5.6G     2224 
TOTAL, minus reserved VM space     1.4G     2224 

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-72d2823851 Build #9370

**Comment by nevack** [comment]
@tearfur FYI
I think it's related to https://github.com/transmission/transmission/commit/6e7fdef7211c8fd4397a672e091546ed23935d5b

**Comment by tearfur** [comment]
Yet another issue that immediately got caught by others despite me running multiple tests that lasted for days... 🤡
