### ISSUE TITLE
4.04 --> 4.1.0-dev upgrade issue

### ISSUE THREAD

**Issue by carried-away** [transmission/transmission#6173]
### What is the issue?

I apologize in advance but I'm beyond stuck.

I built 4.04 from source a few days ago. Everything seemed ok, but I noticed that downloads would cap out one or two cores of my cpu to 100% and degrades webui performance/responsiveness. 

I saw that transmission-4.1.0-dev patched a performance issue related to downloading. So I built that from source without issue. But the daemon is still running the binary for 4.0.4

I assumed since I built the software the same way, it would just overwrite the existing binaries. I'm trying to go through the cmake cache, but I'm way too stupid to understand what I'm looking at. How do I properly upgrade when building from source?

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

transmission-4.1.0-dev

**Comment by GaryElshaw** [comment]
Totally safe would be to empty the build directory, otherwise, if you're using make, i'd try deleting the libtransmission directory, and 'make'.

**Comment by carried-away** [comment]
Thanks for looking at this issue. I used these instructions to install

```bash
$ tar xf transmission-4.1.0-dev+rd224985ef8.tar.xz
$ cd transmission-4.1.0-dev+rd224985ef8.tar.xz
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimized binary with debug information. (preferred)
# Use -DCMAKE_BUILD_TYPE=Release to build full optimized binary.
$ cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ cd build
$ cmake --build .
$ sudo cmake --install .
```

so I should delete the contents from `transmission-4.1.0-dev+rd224985ef8/build`? 

I only see a cmake folder in `transmission-4.1.0-dev+rd224985ef8`.

Or are you saying I should remove the binaries from /usr/local/bin/ prior to building a new version?

I know you didn't mention anything about the binaries themselves, i'm just trying to figure out what you mean.

**Comment by GaryElshaw** [comment]
How did you install 4.0.4 @carried-away?

**Comment by carried-away** [comment]
The same way I did with 4.1.4, with cmake

```bash
$ tar xf transmission-4.0.4.tar.xz
$ cd transmission-4.0.4
# Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimized binary with debug information. (preferred)
# Use -DCMAKE_BUILD_TYPE=Release to build full optimized binary.
$ cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ cd build
$ cmake --build .
$ sudo cmake --install .
```

**Comment by GaryElshaw** [comment]
Okay, cool. I'd delete transmission-daemon from /usr/local/bin and just follow the build instructions you're following. Keep the /usr/local/bin directory open just to double-check the timestamps of the binaries.

**Comment by carried-away** [comment]
@GaryElshaw I can't thank you enough. That worked.

4.1.4 gave me issues, I couldn't start the daemon, it errors with `Main process exited, code=killed, status=11/SEGV`

So I removed the binaries again from /usr/local/bin and built `4.0.3` instead. Not only did that fix the daemon startup error, but it also resolved my download speed/cpu usage issue. Thank you so much!
