### ISSUE TITLE
The event thread is blocked for a long time

### ISSUE THREAD

**Issue by AndreyPavlenko** [transmission/transmission#619]
After investigation I've found out that the event thread is blocked here:

```c
preallocate_file_sparse() {
...
        /* fallback: the old-style seek-and-write */
        if (tr_sys_file_write_at(fd, &zero, 1, length - 1, NULL, &my_error) && tr_sys_file_truncate(fd, length, &my_error))
...
```

If the system or the file system does not support fallocate, the above code is performed in the event thread and, as the result, the event thread could be blocked for a few minutes.

**Comment by mikedld** [comment]
See #108.
