### ISSUE TITLE
script-torrent-done not working

### ISSUE THREAD

**Issue by hansyulian** [transmission/transmission#6191]
### What is the issue?

the script for torrent done not executed
```
    "script-torrent-done-enabled": true,
    "script-torrent-done-filename": "/usr/bin/delete-completed-transmission",
```

file permission:
```
-rwxr-xr-x  1 root root        1894 Aug 17 08:51 delete-completed-transmission
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

When running on bash, the script work just fine

**Comment by mikedld** [comment]
Closing as duplicate of #4885. Please review the discussion there and see if you can provide more details.
