### ISSUE TITLE
Check for malicious single file torrent is too restrictive

### ISSUE THREAD

**Issue by tiennou** [transmission/transmission#62]
I'm looking at a single-file torrent that has it's `name` info key set to something like `torrent/data` which fails the `path_component_is_suspicious` check.

Given that the spec says

```
The name key maps to a UTF-8 encoded string which is the suggested name to
save the file (or directory) as. It is purely advisory.
```

would relaxing that check be appropriate ?

**Comment by mikedld** [comment]
Fixed in terms #294 (99033b067da01c646a3e12a13f8bbcd43a9dd056).
