### ISSUE TITLE
Please update translations

### ISSUE THREAD

**Issue by jony0008** [transmission/transmission#620]
I have updated the Swedish translation in Transifex, please merge it.

**Comment by jony0008** [comment]
@mikedld Please update all translations for 3.00 release

**Comment by mikedld** [comment]
That's the plan. Last update was on March 6, 2019, are you saying it doesn't include your changes?

**Comment by jony0008** [comment]
Sure, but why not update again after 5 months.

**Comment by jony0008** [comment]
I found some bugs in the Swedish translation, please update again. Thank you.

**Comment by ckerr** [comment]
Closing old issue. @mikedld has updated the translations in preparation of the upcoming 3.0.0 release.
