### ISSUE TITLE
Error after installing it. Doesn´t open.

### ISSUE THREAD

**Issue by rafamuz** [transmission/transmission#6202]
### What is the issue?

There were error on trying opening it. 
PS: the Latest Version.
![erro](https://github.com/transmission/transmission/assets/74082832/182116c2-78cf-43e0-8d9c-63e50af78e0e)

### Which application of Transmission?

None

**Comment by rafamuz** [comment]
I did reinstalled it, but same error appears.

**Comment by ckerr** [comment]
I'm not sure that this is a bug in Transmission.

Have you tried the suggestions at https://answers.microsoft.com/en-us/windows/forum/all/this-application-failed-to-start-because-no-qt/e5b31106-84a1-4196-92f3-a1ee633f68b0?
