### ISSUE TITLE
[RPC] Document "torrent-verify-force"

### ISSUE THREAD

**Issue by killemov** [transmission/transmission#6204]
### What is the issue?

A new method `torrent-verify-force` was added to the protocol. It is documented as in, this method exists, but what does it do? What is the difference with normal `torrent-verify`?
Also [searching for tr_torrentVerifyForce](https://github.com/search?q=repo%3Atransmission%2Ftransmission%20tr_torrentVerifyForce&type=code) yields only the RPC spec.

### Which application of Transmission?

transmission-daemon

**Comment by ckerr** [comment]
@killemov you're right, we probably do need to document this better.

FWIW in the short term, there's some background discussion at #5981 and the tldr is to force a file verify even if the torrent thinks that one or more files has disappeared, e.g. the "No data found!" error.

**Comment by killemov** [comment]
... aaaaaaand it's gone again? https://github.com/transmission/transmission/commit/7af71d96950ee33d12473ab50060f15fe4445cf4

Maybe add something in the RPC-spec to mark if a change is (very) experimental? Or only document stuff that will be in the upcoming release?

**Comment by tearfur** [comment]
Please don't expect anything not yet released to be stable.

**Comment by killemov** [comment]
Ack
