### ISSUE TITLE
Client name is garbled for some peers in list of peers (transmission-remote --info-peers/-ip)

### ISSUE THREAD

**Issue by marcelpaulo** [transmission/transmission#621]
The client name is garbled for some peers in the peers list for a torrent I've just checked. Here's a sample of the output:

```
+paulo:~/tmp$ transmission-remote -t 46 -ip | tee log
Address                                   Flags         Done  Down    Up      Client
2402:3a80:d76:b5ab:4883:7084:db6a:afb3    uEI           5.4      0.0     0.0  µTorrent 4.0.2
2405:204:5681:af9d::131e:78b0             UEX           2.0      0.0     0.0  µTorrent 4.0.2
2405:204:d303:9f58::ed9:88a4              uEX           0.0      0.0     0.0  µTorrent 4.0.2
2405:205:c883:66c5:76bb:505b:4f98:54e2    uEX           59.2     0.0     0.0  µTorrent 4.8.1
2409:4054:211e:c9cf::9a5:68ac             uEX           10.0     0.0     0.0  µTorrent 4.8.1
5.36.209.250                              TuEX          33.3     0.0     0.0  µTorrent 4.0.2
8.40.194.55                               TEX           0.0      0.0     0.0  µTorrent 4.0.3
23.241.149.84                             TuEX          5.8      0.0     0.0  %169;|i%FF%FF8
23.242.197.28                             TUEX          63.9     0.0    32.0  %FF&%FFh%07%FF%0A%FF
24.169.13.190                             uEX           2.9      0.0     0.0  libtorrent (Rasterbar) 1.1.0
24.175.72.152                             TuEH          5.1      0.0     0.0  %FFR~E%FF%FFNC
24.186.60.25                              TEX           0.0      0.0     0.0  %FF%FF%FF%FF&z%FF%13
24.194.148.213                            TEX           0.0      0.0     0.0  LAx%FF%FF%FFW;
24.207.231.17                             TEX           0.0      0.0     0.0  %FF|CB%FF%FF8%FF
24.215.65.195                             TUEX          95.7     0.0    16.0  %FF%FFDC%FF%FFS%FF
24.226.96.65                              TEX           0.0      0.0     0.0  %FFQ"%0C%FF%FF%FF%FF
24.247.94.81                              TUEX          98.9     0.0     0.0  .%FF%0C%FF%12%FF%FFn
```

I've pasted the full otput [here](https://paste.ee/p/HqhiX) in case it may be useful.

I'm running transmission-daemon c11f2870fd18ff781ca06ce84b6d43541f3293dd on Xubuntu 18.04.

**Comment by marcelpaulo** [comment]
In case it helps, here's the torrent whose peers list had some client names garbled:
[torrent-garbled-peer-client.zip](https://github.com/transmission/transmission/files/1998094/torrent-garbled-peer-client.zip)

**Comment by marcelpaulo** [comment]
I suppose this shouldn't influence the issue, but in any case, here's my locale:

```
+paulo:~/tmp$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=
```

**Comment by marcelpaulo** [comment]
I rebuilt transmission from c89cce792d907e4c94ef0d83c1e570701e33857a but the issue is still there, so it must have crept in with an earlier commit. I can't remember when I last checked the peer list and the client name wasn't garbled.

**Comment by marcelpaulo** [comment]
I ran `transmission-remote` with debugging (`-b`), and [here](https://paste.ee/p/Ww8Uy)'s the output. I can see that `transmission-daemon` is sending the garbled client names to `transmission-remote`.

**Comment by marcelpaulo** [comment]
I tried the following:

1. Wiped all torrents, so that there was no logging related to other torrents
1. Restarted transmission-daemon with `--log-debug`
1. Readded the torrent (that led me to open this issue)
1. Waited for it to start downloading, ensured that transmission-remote showed garbled client names
1. Stopped transmission-daemon
1. [Here](https://paste.ee/p/elhkm)'s all transmission-daemon's logging from _/var/log/syslog_

**Comment by Pietu1998** [comment]
This issue also occurs in (at least) the Windows Qt version and the Debian `transmission-gtk` package, both version 2.94. I recall seeing it in earlier versions too.

Example on Windows:

![example of torrent details with garbled client names](https://user-images.githubusercontent.com/8439661/40587779-92a7e026-61dc-11e8-8926-8bf37b4bfd69.png)

**Comment by ckerr** [comment]
Fixed by 1ba64684f908aaeedee2cf0aca6dc6e43ff59fc0

**Comment by GScottElshaw** [comment]
There are some random ones still around.... :-(

3.00+ (5efec26a3b)
![Screenshot 2022-01-24 at 8 44 35 PM](https://user-images.githubusercontent.com/69029666/150742042-6011c406-c3c8-4856-aa3b-7d68a419637d.png)

**Comment by ckerr** [comment]
@GScottElshaw please file a new issue for each one! :bow:
