### ISSUE TITLE
announces to torrent.ubuntu.com are worse after 42198afc5f 

### ISSUE THREAD

**Issue by ckerr** [transmission/transmission#6216]
Prior to that commit, announces to torrent.ubuntu.com usually yielded somewhere between 15 and 30 peers.

Starting in 42198afc5feb1c017f6a9c54bef5c854980d201d, only one peer is found.

Very repeatable. The problematic commit was found with `git bisect`. Found while investigating [this test](https://github.com/transmission/transmission/issues/5261#issuecomment-1793599776) by @ziovelvet.

Ubuntu 22.04.3 test torrent @ https://releases.ubuntu.com/22.04/ubuntu-22.04.3-desktop-amd64.iso.torrent

**Comment by ckerr** [comment]
removing this line from web.cc "fixes" the issue insofar as we get a good announce response from torrent.ubuntu.com.

```diff
diff --git a/libtransmission/web.cc b/libtransmission/web.cc
index 8e9504dd9..5c73a29c5 100644
--- a/libtransmission/web.cc
+++ b/libtransmission/web.cc
@@ -518,7 +518,7 @@ public:
         (void)curl_easy_setopt(e, CURLOPT_MAXREDIRS, -1L);
         (void)curl_easy_setopt(e, CURLOPT_NOSIGNAL, 1L);
         (void)curl_easy_setopt(e, CURLOPT_PRIVATE, &task);
-        (void)curl_easy_setopt(e, CURLOPT_IPRESOLVE, task.ipProtocol());
+        // (void)curl_easy_setopt(e, CURLOPT_IPRESOLVE, task.ipProtocol());
 
 #ifdef USE_LIBCURL_SOCKOPT
         (void)curl_easy_setopt(e, CURLOPT_SOCKOPTFUNCTION, onSocketCreated);
```

But I'd like to look into this and figure out if this breaks anything else.

CC @tearfur for IPv6 brains

**Comment by ckerr** [comment]
(tested with curl 7.81.0)

**Comment by ckerr** [comment]
(tested with curl 7.81.0)

also CC @lvella who might have an idea on what's going on here

**Comment by tearfur** [comment]
Never seen this, it has always been find on my end. (curl 8.0.1)

![image](https://github.com/transmission/transmission/assets/46261767/0a6b7727-f9ae-457f-b4c3-beb6f5eee1d7)

**Comment by tearfur** [comment]
Maybe try to see what curl is doing under the hood using [CURLOPT_VERBOSE](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html)?

If you are going this far back in commits, then maybe you are seeing #5206.

**Comment by lvella** [comment]
My guess is this: many (most?) trackers are not prepared to handle the current version of BEP-7.

In old versions of BEP-7, the client would send one announce request with HTTP GET parameters `ipv4=...&ipv6=...`. In the current version, the client makes 2 requests, one via each IP protocol, and it is the server's job to identify they are from the same client by matching a unique identifier.

Either it has a buggy implementation of the barely used new BEP-7, or it doesn't know about it at all and gets confused by getting two successive announce requests by the same client (one possibility is that the IPv4 requests arrives first, sets the address, then the IPv6 request arrives, replaces the IPv4 with the IPv6, and the other peers never get the IPv4 that was overwritten).

I have seen a different issue with new BEP-7 in another tracker, that I was never connecting to IPv6 peers. I patched my local transmission a few weeks ago to use the old BEP-7 behavior (i.e., to send `ipv4=...&ipv6=...` in the request) and the problem was gone.

**Comment by ckerr** [comment]
> Never seen this, it has always been fine on my end. (curl 8.0.1) (5d56e90)

@tearfur the thing to do is click on 'more info' in the tracker tab and look at the announce results: scrape says there are thousands of seeders, but announce only gives us one peer address back, every time starting with 4219afc5f. Before that commit, announce returns back a list of 25-50 peers.

**Comment by ckerr** [comment]
announce response in the commit before 42198:

```
---

* Connection 6 seems to be dead!
* Closing connection 6
* Connection 8 seems to be dead!
* Closing connection 8
* Connection 9 seems to be dead!
* Closing connection 9
* Connection 7 seems to be dead!
* Closing connection 7
* Hostname torrent.ubuntu.com was found in DNS cache
*   Trying 2620:2d:4000:1::42:443...
* Hostname ipv6.torrent.ubuntu.com was found in DNS cache
*   Trying 2620:2d:4000:1::42:443...
* Connected to torrent.ubuntu.com (2620:2d:4000:1::42) port 443 (#10)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL re-using session ID
* Connected to ipv6.torrent.ubuntu.com (2620:2d:4000:1::42) port 443 (#11)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL re-using session ID
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*   server certificate verification OK
*   server certificate status verification SKIPPED
*   common name: torrent.ubuntu.com (matched)
*   server certificate expiration date OK
*   server certificate activation date OK
*   certificate public key: RSA
*   certificate version: #3
*   subject: CN=torrent.ubuntu.com
*   start date: Sun, 01 Oct 2023 16:13:23 GMT
*   expire date: Sat, 30 Dec 2023 16:13:22 GMT
*   issuer: C=US,O=Let's Encrypt,CN=R3
* ALPN, server accepted to use http/1.1
> GET /announce?info_hash=uC%9d%5d%e3C%99%9a%b3w%c6%17%c2%c6G%90%29V%e2%82&peer_id=-TR300Z-1zcu0dcnuxah&port=51413&uploaded=0&downloaded=0&left=5033426944&numwant=80&key=746061239&compact=1&supportcrypto=1&event=started&ipv6=2600%3A1700%3A6843%3Aa30%3A8826%3A542b%3Aae38%3Acb5a HTTP/1.1
Host: torrent.ubuntu.com
User-Agent: Transmission/3.00+
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd

* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*   server certificate verification OK
*   server certificate status verification SKIPPED
*   common name: torrent.ubuntu.com (matched)
*   server certificate expiration date OK
*   server certificate activation date OK
*   certificate public key: RSA
*   certificate version: #3
*   subject: CN=torrent.ubuntu.com
*   start date: Sun, 01 Oct 2023 16:13:23 GMT
*   expire date: Sat, 30 Dec 2023 16:13:22 GMT
*   issuer: C=US,O=Let's Encrypt,CN=R3
* ALPN, server accepted to use http/1.1
> GET /announce?info_hash=uC%9d%5d%e3C%99%9a%b3w%c6%17%c2%c6G%90%29V%e2%82&peer_id=-TR300Z-1zcu0dcnuxah&port=51413&uploaded=0&downloaded=0&left=5033426944&numwant=80&key=746061239&compact=1&supportcrypto=1&event=started&ipv6=2600%3A1700%3A6843%3Aa30%3A8826%3A542b%3Aae38%3Acb5a HTTP/1.1
Host: ipv6.torrent.ubuntu.com
User-Agent: Transmission/3.00+
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 06 Nov 2023 14:26:23 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 1180
< Content-Type: text/plain
< Pragma: no-cache
< Content-Encoding: gzip
< 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 06 Nov 2023 14:26:23 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 1191
< Content-Type: text/plain
< Pragma: no-cache
< Content-Encoding: gzip
< 
* Connection #10 to host torrent.ubuntu.com left intact
* Connection #11 to host ipv6.torrent.ubuntu.com left intact
Announce response:
[raw]<< d8:completei1756e10:incompletei46e8:intervali1800e5:peersld2:ip26:2001:1af8:4700:b0d0:d000::7:peer id20:-TR4030-9s4c37ghgh2d4:porti42929eed2:ip21:2a01:7e03:e002:300::27:peer id20:-lt0D80-\xca\xe4\xc6\xaa\x8bFJ\xee\xd9@\xd5\xf54:porti57070eed2:ip22:2a02:c206:3008:6973::17:peer id20:-TR3000-qun5j2altd6w4:porti51413eed2:ip19:2001:41d0:a:6816::17:peer id20:-TR3000-5bmucjcejqug4:porti51413eed2:ip19:2607:5300:60:623::17:peer id20:-TR2940-hr0d9z2kuefy4:porti51413eed2:ip21:2a01:4f8:c010:8a61::17:peer id20:-TR4040-6ll79o3so26t4:porti51413eed2:ip19:2001:41d0:8:d92e::17:peer id20:-TR2920-c3ra4kr6ylf14:porti51413eed2:ip35:2603:c020:3:eaf:9a85:1e93:888f:cd387:peer id20:-lt0D80-\x09L\xc0\xa0\xf6\xec\x7fnu\x07\xd2\xcd4:porti6882eed2:ip39:2a02:1210:4831:9700:ba27:ebff:fe91:60cd7:peer id20:-TR2940-nlviini8qkug4:porti51316eed2:ip35:2001:470:7a83:6f74:0:7069:7261:74657:peer id20:-TR4040-tvgqdh0gvjwm4:porti6979eed2:ip37:2409:8a62:575:c0d0:8647:9ff:fe13:41f67:peer id20:-TR2940-mgqyi29iydcc4:porti51413eed2:ip20:2a01:4f8:141:5330::17:peer id20:-TR3000-me5f37rrsrsd4:porti51413eed2:ip35:2a02:85f:fcd4:e800:21e:6ff:fe37:d697:peer id20:-TR4020-1u2u109qux2g4:porti50031eed2:ip22:2620:1d5:ffd:1702::2137:peer id20:-TR3000-d01q8y5idujd4:porti51413eed2:ip39:2607:fea8:fdf0:80f1:4228:4e05:41f4:85207:peer id20:-TR2940-o1gmnia7lbp24:porti51413eed2:ip38:2a01:c22:ad03:5600:9209:d0ff:fe2f:886f7:peer id20:-TR2930-e6njf86u5odh4:porti16881eed2:ip18:2001:41d0:e:907::17:peer id20:-lt0D80-\xdak\xd8u\xc9~S\x1c\xa6\x8e\xcc@4:porti12280eed2:ip20:2a02:85f:fc60:a00::17:peer id20:-TR4030-ljfyq90v2jmi4:porti54454eed2:ip19:2001:41d0:a:6785::17:peer id20:-lt0D80-@C\x0d\xfa\xb5\x90\xaa w\xbe\xb1\x024:porti6818eed2:ip24:2409:8a5c:8e33:b454::ebd7:peer id20:-TR3000-3iqsoq9dy14u4:porti51413eed2:ip23:240e:361:ba03:ff01::c477:peer id20:-TR3000-0xnhcc48p3y94:porti51413eed2:ip14:185.125.190.597:peer id20:T03I--01azasgkwISuvf4:porti6935eed2:ip37:2001:9e8:f101:1600:211:32ff:fe97:ebfe7:peer id20:-TR2930-wvhpz8r4ma7y4:porti16881eed2:ip38:2001:448a:3050:9b88:b33b:bc3:2e45:56f37:peer id20:-TR4020-ft7ah7e28exo4:porti51413eed2:ip39:2001:b011:4008:1e88:264b:feff:fe83:63f77:peer id20:-TR3000-xaq4e3omvl5n4:porti51417eed2:ip20:2001:bc8:1640:530::17:peer id20:-TR3000-0zme05qpmxhh4:porti13000eed2:ip38:2601:402:4581:84c0:10c8:686b:2f15:25617:peer id20:-TR4040-0mcdirayxlec4:porti51413eed2:ip17:2001:470:dc0b::107:peer id20:-TR3000-f0m2k9e82ix14:porti51413eed2:ip18:2a10:e780:11:1::6d7:peer id20:-TR410Z-qkfp8qk7lvps4:porti51413eed2:ip37:2a01:e0a:3c4:6c10:3d95:9c25:921b:2e8e7:peer id20:-TR3000-b8y2il4nr8cc4:porti51413eed2:ip39:2a02:214a:840e:a700:132c:9858:2670:7d147:peer id20:-TR3000-04cfb7yajpte4:porti51413eed2:ip39:2607:fea8:fdf0:80f1:4228:4e05:41f4:85207:peer id20:-TR2940-3h2lkfvta1kb4:porti51413eed2:ip35:2a01:e0a:27e:1920:5054:ff:fe69:99387:peer id20:-TR3000-s4m03bnw59074:porti51413eeee

```

**Comment by Pentaphon** [comment]
> Prior to that commit, announces to torrent.ubuntu.com usually yielded somewhere between 15 and 30 peers.

It was even worse when I made https://github.com/transmission/transmission/discussions/4916 but people kept saying it was fine which is why I didn't initially open an issue but clearly something is different about that tracker. 

I couldn't get a single peer for minutes at a time when I made that thread and yes I just checked it again just now and only 1 peer seems to connect as you describe.

**Comment by ckerr** [comment]
and in 42198afc:

```
* Hostname torrent.ubuntu.com was found in DNS cache
*   Trying 185.125.190.59:443...
* Found bundle for host torrent.ubuntu.com: 0x7fbb40002350 [serially]
* Server doesn't support multiplex (yet)
* Hostname torrent.ubuntu.com was found in DNS cache
*   Trying 2620:2d:4000:1::42:443...
* Found bundle for host ipv6.torrent.ubuntu.com: 0x558a94d41df0 [serially]
* Server doesn't support multiplex (yet)
* Connected to torrent.ubuntu.com (185.125.190.59) port 443 (#4)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
* Connected to torrent.ubuntu.com (2620:2d:4000:1::42) port 443 (#5)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
*   Trying 185.125.190.59:443...
* Hostname 'ipv6.torrent.ubuntu.com' was found in DNS cache
*   Trying 2620:2d:4000:1::42:443...
* Connected to ipv6.torrent.ubuntu.com (185.125.190.59) port 443 (#6)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
* Connected to ipv6.torrent.ubuntu.com (2620:2d:4000:1::42) port 443 (#7)
* found 415 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*   server certificate verification OK
*   server certificate status verification SKIPPED
*   common name: torrent.ubuntu.com (matched)
*   server certificate expiration date OK
*   server certificate activation date OK
*   certificate public key: RSA
*   certificate version: #3
*   subject: CN=torrent.ubuntu.com
*   start date: Sun, 01 Oct 2023 16:13:23 GMT
*   expire date: Sat, 30 Dec 2023 16:13:22 GMT
*   issuer: C=US,O=Let's Encrypt,CN=R3
* ALPN, server accepted to use http/1.1
> GET /announce?info_hash=uC%9d%5d%e3C%99%9a%b3w%c6%17%c2%c6G%90%29V%e2%82&peer_id=-TR300Z-z7fryf386jon&port=51413&uploaded=0&downloaded=0&left=5033426944&numwant=80&key=576820569&compact=1&supportcrypto=1&event=started&ipv6=**REMOVED** HTTP/1.1
Host: torrent.ubuntu.com
User-Agent: Transmission/3.00+
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd

* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*   server certificate verification OK
*   server certificate status verification SKIPPED
*   common name: torrent.ubuntu.com (matched)
*   server certificate expiration date OK
*   server certificate activation date OK
*   certificate public key: RSA
*   certificate version: #3
*   subject: CN=torrent.ubuntu.com
*   start date: Sun, 01 Oct 2023 16:13:23 GMT
*   expire date: Sat, 30 Dec 2023 16:13:22 GMT
*   issuer: C=US,O=Let's Encrypt,CN=R3
* ALPN, server accepted to use http/1.1
> GET /announce?info_hash=uC%9d%5d%e3C%99%9a%b3w%c6%17%c2%c6G%90%29V%e2%82&peer_id=-TR300Z-z7fryf386jon&port=51413&uploaded=0&downloaded=0&left=5033426944&numwant=80&key=576820569&compact=1&supportcrypto=1&event=started HTTP/1.1
Host: torrent.ubuntu.com
User-Agent: Transmission/3.00+
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 06 Nov 2023 15:23:20 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 99
< Content-Type: text/plain
< Pragma: no-cache
< Content-Encoding: gzip
< 
* Connection #4 to host torrent.ubuntu.com left intact
Announce response:
[raw]<< d8:completei1787e12:crypto_flags31:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0010:incompletei48e8:intervali1800e5:peers6:\xb9}\xbe;\x1b\x17e
```

**Comment by tearfur** [comment]
> and in [42198af](https://github.com/transmission/transmission/commit/42198afc5feb1c017f6a9c54bef5c854980d201d):

@ckerr I tried this a few times in `main` myself. I do see the 1 peer compact `peers6` responses that you are seeing, but I *sometimes* also see a normal benc response containing many peers right before the compact response with 1 peer.

So maybe that's why you are seeing only 1 peer from the previous announce response.

**Comment by tearfur** [comment]
> Another possibility is that two requests are sent but just one is parsed. Maybe the peers were in the request discarded when this else is reached: [42198af#diff-cb6beb7a0dfabaaade7372527594e6ca1eee0863a46a9a57b335c6406c20542aR379-R382](https://github.com/transmission/transmission/commit/42198afc5feb1c017f6a9c54bef5c854980d201d#diff-cb6beb7a0dfabaaade7372527594e6ca1eee0863a46a9a57b335c6406c20542aR379-R382)

I added a line of log in that `if` branch, I've never seen any of them so far.

**Comment by tearfur** [comment]
> Another possibility is that two requests are sent but just one is parsed. Maybe the peers were in the request discarded when this else is reached: [42198af#diff-cb6beb7a0dfabaaade7372527594e6ca1eee0863a46a9a57b335c6406c20542aR379-R382](https://github.com/transmission/transmission/commit/42198afc5feb1c017f6a9c54bef5c854980d201d#diff-cb6beb7a0dfabaaade7372527594e6ca1eee0863a46a9a57b335c6406c20542aR379-R382)

Can confirm, when the normal benc responses weren't getting parsed by us, they are being discarded in this `if` branch.

Weirdly enough, ubuntu's trackers seems to consistently return the (faulty?) compact responses containing only 1 peer when I announce only with IPv4 by setting `d->requests_sent_count = 1` and commenting out

https://github.com/transmission/transmission/blob/65755dca33cd4e24525fa147adfac0af7ab63529/libtransmission/announcer-http.cc#L315

On the other hand, I consistently get the normal benc responses containing many peers if I announce only in IPv6 by commenting out

https://github.com/transmission/transmission/blob/65755dca33cd4e24525fa147adfac0af7ab63529/libtransmission/announcer-http.cc#L311

P.S. So that's why I get so little peers on an IPv6 only machine...!! I've been wondering why that is for a while.

**Comment by tearfur** [comment]
To sum up, to fix this issue:
1. ubuntu has to fix their IPv4 tracker.
2. We need to stop discarding announces to account for cases where the tracker return different responses for different requests.

**Comment by Pentaphon** [comment]
> 1. ubuntu has to fix their IPv4 tracker.

I'm sure its just a matter of contacting their webmaster and asking them to update their tracker software to the latest version because I've never seen another tracker do this. It is puzzling how this is still happening considering how many Ubuntu users have Transmission installed by default. You'd think they'd get lots of complaints about it.

**Comment by Pentaphon** [comment]
@ckerr @tearfur I'm afraid the problem has actually gotten worse on Transmission 4.1.0-dev (bcbd9b77af). Port is open on a machine with an SSD and i5 processor. 

Now I connect to 1 single peer, it downloads a bit... then I lose that peer...and then regain it over and over and over again. Here's a screen recording to show that I see.

https://github.com/transmission/transmission/assets/49374058/d911528e-6fb8-41d0-a8a4-49191ab59fb3

**Comment by tearfur** [comment]
I should have tested on an IPv4 only machine before submitting the PR... I'll see if I can reproduce this.

**Comment by tearfur** [comment]
@Pentaphon I'm not convinced #6223 is going to be any better/worse for IPv4 only users, Transmission's behaviour should be exactly the same.

What I do notice is that the QT app is not getting DHT peers at all, while `transmission-daemon` is, and it didn't seem to depend on OS. @ckerr

**Comment by tearfur** [comment]
> What I do notice is that the QT app is not getting DHT peers at all, while `transmission-daemon` is, and it didn't seem to depend on OS.

Hmm, actually, it seems to be just a matter of not having enough peers to bootstrap the DHT process in a fresh Transmission installation.

After deleting all resume files in `transmission-daemon`'s config folder, it too didn't get any DHT peers.

@Pentaphon If you go download a bunch of other Linux torrents on the Transmission installation that you were testing on, keep those torrents running, then go back to the Ubuntu torrent, you should get much more peers than you are getting now.

I'm afraid that's just how it's gonna be if Ubuntu don't fix their IPv4 tracker.

**Comment by Pentaphon** [comment]
> If you go download a bunch of other Linux torrents on the Transmission installation that you were testing on, keep those torrents running, then go back to the Ubuntu torrent, you should get much more peers than you are getting now.

Oh I know that is the case. I would do whenever I tested Transmission in other issues because I knew something was going on with the Ubuntu tracker. Usually I try 5 of the different major non-Ubuntu torrents from https://distrowatch.com/dwres.php?resource=bittorrent to avoid using it. I just stuck to Ubuntu this time for the purposes of this triage.

**Comment by Pentaphon** [comment]
@flowerey I've reported Ubuntu's torrent tracker issue to their issue page https://github.com/canonical/ubuntu.com/issues/15735 and have directed them to this issue.

**Comment by flowerey** [comment]
> [@flowerey](https://github.com/flowerey) I've reported Ubuntu's torrent tracker issue to their issue page [canonical/ubuntu.com#15735](https://github.com/canonical/ubuntu.com/issues/15735) and have directed them to this issue.

Thanks :D
