### ISSUE TITLE
Wont begin to download

### ISSUE THREAD

**Issue by ximikas** [transmission/transmission#622]
Hi ,i have following problem .Transmission 2.94 on ubuntu 18.04 ,previously on 17.10 ,older version of transmission 2.91 (ubuntu default installed) ,the same problem. After program left running for a few hours , adding a new torrent to download don't begin to download ,just stays on the list with "downloading" with no error messages . When clicking properties on that torrent ,then tracker tab ,there is only two lines " Queued to ask for peer count" and "Queued to ask for peers ".
This message can stay for hours ,sometimes it begin to download ,but not always .Restarting application helps .When i see there "Queued" ,there is no time specified .If i rightclick on torrent "Ask tracker for more peers" ,nothing changes .If server would busy ,then program restart would not help. Torrent count is not high ,300-400 .They are sucesfully seeding ,some connected to same tracker.
I have increased connections limit to 100 from default 50 , also increased memory buffer size to reduce hdd trashing . Please help resolve this .

**Comment by antikan** [comment]
same as issue #616 .
