### ISSUE TITLE
Files are completing, then are being removed immediately

### ISSUE THREAD

**Issue by wesleigh** [transmission/transmission#6222]
### What is the issue?

Hi there,

Whenever I attempt to torrent **anything**, the torrent completes as expected, and as soon as it completes, the file gets automatically removed.

I have included a screenshot of a test torrent I from webtorrent.io:
<img width="1437" alt="image" src="https://github.com/transmission/transmission/assets/15859357/742e5b39-7cc3-4d36-be57-45c834cf2cc5">

As you can see in the penultimate line, as **soon** as the Torrent finishes, it immediately removes it. This is a completely fresh install of Transmission, with zero changes to any source files anywhere.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.4

**Comment by ckerr** [comment]
> This is a completely fresh install of Transmission, with zero changes to any source files anywhere.

Well, `torrentDone.js` doesn't ship with Transmission, so there is at least some config change going on there. What's are the contents of that script?

**Comment by killemov** [comment]
@wesleigh Could this be related to [Torrents are removed from Transmission upon completion](https://forum.cloudron.io/topic/5811/torrents-are-removed-from-transmission-upon-completion) ?

**Comment by ckerr** [comment]
Where is this `torrentDone.js` script even coming from?

**Comment by wesleigh** [comment]
> @wesleigh Could this be related to [Torrents are removed from Transmission upon completion](https://forum.cloudron.io/topic/5811/torrents-are-removed-from-transmission-upon-completion) ? (The solution is also there.) I wrote a script a long time ago that does something similar: [Unrar and cleanup](https://forum.transmissionbt.com/viewtopic.php?t=10364).

Ahh, I see. the `torrentDone.js` file must be something added in by Cloudron, which I use to host my dockerized Transmission WebUI instance. I've clearly been dense and not realised that - and ended up opening a thread in the wrong place. Apologies @ckerr!

Thanks @killemov for providing that super helpful link. Any further issues, I'll raise with them!

**Comment by killemov** [comment]
@ckerr wrote:
> Where is this `torrentDone.js` script even coming from?

Clickdalink ... Cloudron!
