### ISSUE TITLE
Nightly died in on_got_port_duplicate_connection

### ISSUE THREAD

**Issue by dantearmok** [transmission/transmission#6239]
### What is the issue?

Mac mini (late 2012, 2.5-GHz 4-Core i5), 16GB RAM, plus an assortment of USB & FW HDs.
macOS Ventura 13.6.1 (w/OCLP 1.1.0), PeakHour 4.1.16, PIA 3.5.1, and Xcode 15.0.1.

Running Transmission-36f33c0d30 Build #9418 (Nov 10, 2023, 1:14:46 AM)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Transmission [3455]
Path:                  /Users/USER/*/Transmission.app/Contents/MacOS/Transmission
Identifier:            org.m0k.transmission
Version:               4.1.0-dev (14714.4.1.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-10 15:35:35.4991 -0500
OS Version:            macOS 13.6.1 (22G313)
Report Version:        12
Anonymous UUID:        9D83084F-22F2-20FB-B0D2-056E94905F2F

Time Awake Since Boot: 9200 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Transmission [3455]

Application Specific Information:
abort() called

Application Specific Backtrace 0:
0   CoreFoundation                      0x00007ff8151a5b72 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007ff814ccd41c objc_exception_throw + 48
2   CoreFoundation                      0x00007ff8151a59d8 +[NSException raise:format:] + 206
3   Transmission                        0x0000000102e0f95e _Z16tr_assert_reportNSt3__117basic_string_viewIcNS_11char_traitsIcEEEElS3_ + 542
4   Transmission                        0x0000000102d33f90 _ZN12tr_peer_info5mergeERS_ + 192
5   Transmission                        0x0000000102d8ca58 _ZN8tr_swarm32on_got_port_duplicate_connectionEP11tr_peerMsgsRNSt3__119__hash_map_iteratorINS2_15__hash_iteratorIPNS2_11__hash_nodeINS2_17__hash_value_typeI17tr_socket_address12tr_peer_infoEEPvEEEEEEb + 696
6   Transmission                        0x0000000102d8c246 _ZN8tr_swarm11on_got_portEP11tr_peerMsgsRK13tr_peer_eventb + 950
7   Transmission                        0x0000000102d8bcfd _ZN8tr_swarm16peer_callback_btEP11tr_peerMsgsRK13tr_peer_eventPv + 685
8   Transmission                        0x0000000102dbafae _ZN12_GLOBAL__N_115tr_peerMsgsImpl7publishERK13tr_peer_event + 62
9   Transmission                        0x0000000102dcec47 _ZN12_GLOBAL__N_118parseLtepHandshakeEPNS_15tr_peerMsgsImplERN15libtransmission12BufferReaderISt4byteEE + 6599
10  Transmission                        0x0000000102dbd440 _ZN12_GLOBAL__N_19parseLtepEPNS_15tr_peerMsgsImplERN15libtransmission12BufferReaderISt4byteEE + 992
11  Transmission                        0x0000000102db9f80 _ZN12_GLOBAL__N_120process_peer_messageEPNS_15tr_peerMsgsImplEhRN15libtransmission12BufferReaderISt4byteEE + 18624
12  Transmission                        0x0000000102daa9fe _ZN12_GLOBAL__N_17canReadEP9tr_peerIoPvPm + 2814
13  Transmission                        0x0000000102d22a30 _ZN9tr_peerIo16can_read_wrapperEv + 224
14  Transmission                        0x0000000102d2317a _ZN9tr_peerIo8try_readEm + 1338
15  Transmission                        0x0000000102d2329e _ZN9tr_peerIo5flushE12tr_directionm + 142
16  Transmission                        0x0000000102e11623 _ZN12tr_bandwidth9phase_oneERNSt3__16vectorIP9tr_peerIoNS0_9allocatorIS3_EEEE12tr_direction + 995
17  Transmission                        0x0000000102e11d2b _ZN12tr_bandwidth8allocateEy + 779
18  Transmission                        0x0000000102d3a253 _ZN10tr_peerMgr15bandwidth_pulseEv + 67
19  Transmission                        0x0000000102d3fb38 _ZZN10tr_peerMgrC1EP10tr_sessionRN15libtransmission10TimerMakerER11tr_torrentsRNS2_10BlocklistsEENKUlvE_clEv + 24
20  Transmission                        0x0000000102d3fb15 _ZNSt3__18__invokeB7v160006IRZN10tr_peerMgrC1EP10tr_sessionRN15libtransmission10TimerMakerER11tr_torrentsRNS4_10BlocklistsEEUlvE_JEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOSD_DpOSE_ + 21
21  Transmission                        0x0000000102d3fad5 _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callIJRZN10tr_peerMgrC1EP10tr_sessionRN15libtransmission10TimerMakerER11tr_torrentsRNS6_10BlocklistsEEUlvE_EEEvDpOT_ + 21
22  Transmission                        0x0000000102d3faad _ZNSt3__110__function12__alloc_funcIZN10tr_peerMgrC1EP10tr_sessionRN15libtransmission10TimerMakerER11tr_torrentsRNS5_10BlocklistsEEUlvE_NS_9allocatorISC_EEFvvEEclB7v160006Ev + 29
23  Transmission                        0x0000000102d3eac9 _ZNSt3__110__function6__funcIZN10tr_peerMgrC1EP10tr_sessionRN15libtransmission10TimerMakerER11tr_torrentsRNS5_10BlocklistsEEUlvE_NS_9allocatorISC_EEFvvEEclEv + 25
24  Transmission                        0x0000000102cf68f2 _ZNKSt3__110__function12__value_funcIFvvEEclB7v160006Ev + 50
25  Transmission                        0x0000000102cf6495 _ZNKSt3__18functionIFvvEEclEv + 21
26  Transmission                        0x0000000102f01e76 _ZN15libtransmission7EvTimer11handleTimerEv + 134
27  Transmission                        0x0000000102f01abf _ZN15libtransmission7EvTimer7onTimerEisPv + 31
28  Transmission                        0x0000000102f52ad0 event_persist_closure + 736
29  Transmission                        0x0000000102f52142 event_process_active_single_queue + 786
30  Transmission                        0x0000000102f4cb61 event_process_active + 321
31  Transmission                        0x0000000102f4ba7b event_base_loop + 795
32  Transmission                        0x0000000102cf5d3a _ZN22tr_session_thread_impl17sessionThreadFuncEP10event_base + 218
33  Transmission                        0x0000000102cf73b4 _ZNSt3__18__invokeB7v160006IM22tr_session_thread_implFvP10event_baseEPS1_JS3_EvEEDTcldsdeclsr3stdE7declvalIT0_EEclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT1_EEEEOS8_OS7_DpOS9_ + 116
34  Transmission                        0x0000000102cf732f _ZNSt3__116__thread_executeB7v160006INS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEM22tr_session_thread_implFvP10event_baseEJPS6_S8_EJLm2ELm3EEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE + 63
35  Transmission                        0x0000000102cf6fd2 _ZNSt3__114__thread_proxyB7v160006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM22tr_session_thread_implFvP10event_baseEPS7_S9_EEEEEPvSE_ + 98
36  libsystem_pthread.dylib             0x00007ff8150541d3 _pthread_start + 125
37  libsystem_pthread.dylib             0x00007ff81504fbd3 thread_start + 15

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff8150155a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81502371d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff81501c5d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff81501588a mach_msg + 19
4   CoreFoundation                	    0x7ff81512f9e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff81512e46b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff81512d8bc CFRunLoopRunSpecific + 560
7   HIToolbox                     	    0x7ff81f078f3d RunCurrentEventLoopInMode + 292
8   HIToolbox                     	    0x7ff81f078d4e ReceiveNextEventCommon + 657
9   HIToolbox                     	    0x7ff81f078aa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
10  AppKit                        	    0x7ff81812925c _DPSNextEvent + 858
11  AppKit                        	    0x7ff818128106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
12  AppKit                        	    0x7ff81811a788 -[NSApplication run] + 586
13  AppKit                        	    0x7ff8180ee9a1 NSApplicationMain + 817
14  Transmission                  	       0x102a29518 main + 72 (main.mm:17)
15  dyld                          	    0x7ff814cfa41f start + 1903

Thread 1 Crashed:
0   libsystem_kernel.dylib        	    0x7ff81501c1e2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff815053ee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff814f7ab45 abort + 123
3   libc++abi.dylib               	    0x7ff81500e282 abort_message + 241
4   libc++abi.dylib               	    0x7ff8150003fb demangling_terminate_handler() + 267
5   libobjc.A.dylib               	    0x7ff814cd4a67 _objc_terminate() + 96
6   libc++abi.dylib               	    0x7ff81500d6db std::__terminate(void (*)()) + 6
7   libc++abi.dylib               	    0x7ff81500d696 std::terminate() + 54
8   Transmission                  	       0x102d8ca58 tr_swarm::on_got_port_duplicate_connection(tr_peerMsgs*, std::__1::__hash_map_iterator<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<tr_socket_address, tr_peer_info>, void*>*>>&, bool) + 696 (peer-mgr.cc:876)
9   Transmission                  	       0x102d8c246 tr_swarm::on_got_port(tr_peerMsgs*, tr_peer_event const&, bool) + 950 (peer-mgr.cc:819)
10  Transmission                  	       0x102d8bcfd tr_swarm::peer_callback_bt(tr_peerMsgs*, tr_peer_event const&, void*) + 685 (peer-mgr.cc:523)
11  Transmission                  	       0x102dbafae (anonymous namespace)::tr_peerMsgsImpl::publish(tr_peer_event const&) + 62 (peer-msgs.cc:547)
12  Transmission                  	       0x102dcec47 (anonymous namespace)::parseLtepHandshake((anonymous namespace)::tr_peerMsgsImpl*, libtransmission::BufferReader<std::byte>&) + 6599 (peer-msgs.cc:1103)
13  Transmission                  	       0x102dbd440 (anonymous namespace)::parseLtep((anonymous namespace)::tr_peerMsgsImpl*, libtransmission::BufferReader<std::byte>&) + 992 (peer-msgs.cc:1237)
14  Transmission                  	       0x102db9f80 (anonymous namespace)::process_peer_message((anonymous namespace)::tr_peerMsgsImpl*, unsigned char, libtransmission::BufferReader<std::byte>&) + 18624 (peer-msgs.cc:1619)
15  Transmission                  	       0x102daa9fe (anonymous namespace)::canRead(tr_peerIo*, void*, unsigned long*) + 2814 (peer-msgs.cc:1762)
16  Transmission                  	       0x102d22a30 tr_peerIo::can_read_wrapper() + 224 (peer-io.cc:388)
17  Transmission                  	       0x102d2317a tr_peerIo::try_read(unsigned long) + 1338 (peer-io.cc:465)
18  Transmission                  	       0x102d2329e tr_peerIo::flush(tr_direction, unsigned long) + 142 (peer-io.cc:575)
19  Transmission                  	       0x102e11623 tr_bandwidth::phase_one(std::__1::vector<tr_peerIo*, std::__1::allocator<tr_peerIo*>>&, tr_direction) + 995 (bandwidth.cc:189)
20  Transmission                  	       0x102e11d2b tr_bandwidth::allocate(unsigned long long) + 779 (bandwidth.cc:247)
21  Transmission                  	       0x102d3a253 tr_peerMgr::bandwidth_pulse() + 67 (peer-mgr.cc:2252)
22  Transmission                  	       0x102d3fb38 tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()::operator()() const + 24 (peer-mgr.cc:945)
23  Transmission                  	       0x102d3fb15 decltype(std::declval<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()&>()()) std::__1::__invoke[abi:v160006]<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()&) + 21 (invoke.h:394)
24  Transmission                  	       0x102d3fad5 void std::__1::__invoke_void_return_wrapper<void, true>::__call<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()&) + 21 (invoke.h:487)
25  Transmission                  	       0x102d3faad std::__1::__function::__alloc_func<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()>, void ()>::operator()[abi:v160006]() + 29 (function.h:185)
26  Transmission                  	       0x102d3eac9 std::__1::__function::__func<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*, libtransmission::TimerMaker&, tr_torrents&, libtransmission::Blocklists&)::'lambda'()>, void ()>::operator()() + 25 (function.h:356)
27  Transmission                  	       0x102cf68f2 std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const + 50 (function.h:510)
28  Transmission                  	       0x102cf6495 std::__1::function<void ()>::operator()() const + 21 (function.h:1156)
29  Transmission                  	       0x102f01e76 libtransmission::EvTimer::handleTimer() + 134 (timer-ev.cc:151)
30  Transmission                  	       0x102f01abf libtransmission::EvTimer::onTimer(int, short, void*) + 31 (timer-ev.cc:143)
31  Transmission                  	       0x102f52ad0 event_persist_closure + 736 (event.c:1623)
32  Transmission                  	       0x102f52142 event_process_active_single_queue + 786 (event.c:1682)
33  Transmission                  	       0x102f4cb61 event_process_active + 321 (event.c:1783)
34  Transmission                  	       0x102f4ba7b event_base_loop + 795 (event.c:2006)
35  Transmission                  	       0x102cf5d3a tr_session_thread_impl::sessionThreadFunc(event_base*) + 218 (session-thread.cc:239)
36  Transmission                  	       0x102cf73b4 decltype(*std::declval<tr_session_thread_impl*>().*std::declval<void (tr_session_thread_impl::*)(event_base*)>()(std::declval<event_base*>())) std::__1::__invoke[abi:v160006]<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) + 116 (invoke.h:359)
37  Transmission                  	       0x102cf732f void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) + 63 (thread:288)
38  Transmission                  	       0x102cf6fd2 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) + 98 (thread:299)
39  libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
40  libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff81501e272 __select + 10
1   libcurl.4.dylib               	    0x7ff82c4ea29e Curl_poll + 495
2   libcurl.4.dylib               	    0x7ff82c4e2751 multi_wait + 728
3   libcurl.4.dylib               	    0x7ff82c4e2473 curl_multi_wait + 23
4   Transmission                  	       0x102dfb608 tr_web::Impl::curlThreadFunc() + 952 (web.cc:707)
5   Transmission                  	       0x102dfca49 decltype(*std::declval<tr_web::Impl*>().*std::declval<void (tr_web::Impl::*)()>()()) std::__1::__invoke[abi:v160006]<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) + 105 (invoke.h:359)
6   Transmission                  	       0x102dfc9ce void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) + 46 (thread:288)
7   Transmission                  	       0x102dfc6b2 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) + 98 (thread:299)
8   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff81501a1de kevent + 10
1   Transmission                  	       0x102b70b1d -[VDKQueue watcherThread:] + 189 (VDKQueue.mm:189)
2   Foundation                    	    0x7ff815f125d3 __NSThread__start__ + 1009
3   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff8150155a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81502371d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff81501c5d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff81501588a mach_msg + 19
4   CoreFoundation                	    0x7ff81512f9e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff81512e46b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff81512d8bc CFRunLoopRunSpecific + 560
7   AppKit                        	    0x7ff8182893f5 _NSEventThread + 132
8   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 5:: com.apple.coreaudio.AQClient
0   libsystem_kernel.dylib        	    0x7ff8150155a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81502371d mach_msg2_internal + 78
2   libsystem_kernel.dylib        	    0x7ff81501c5d4 mach_msg_overwrite + 692
3   libsystem_kernel.dylib        	    0x7ff81501588a mach_msg + 19
4   CoreFoundation                	    0x7ff81512f9e0 __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff81512e46b __CFRunLoopRun + 1365
6   CoreFoundation                	    0x7ff81512d8bc CFRunLoopRunSpecific + 560
7   AudioToolbox                  	    0x7ff825415b0b CADeprecated::GenericRunLoopThread::Entry(void*) + 157
8   libAudioToolboxUtility.dylib  	    0x7ff8242123ab CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 77
9   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 6:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	    0x7ff81501551e semaphore_wait_trap + 10
1   caulk                         	    0x7ff81edaf07e caulk::semaphore::timed_wait(double) + 150
2   caulk                         	    0x7ff81edaef9c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff81edaecb0 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 7:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	    0x7ff81501551e semaphore_wait_trap + 10
1   caulk                         	    0x7ff81edaf07e caulk::semaphore::timed_wait(double) + 150
2   caulk                         	    0x7ff81edaef9c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff81edaecb0 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff8150541d3 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81504fbd3 thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff81504fbb0 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff81504fbb0 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff81504fbb0 start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	    0x7ff81504fbb0 start_wqthread + 0

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000f08f000  rcx: 0x000070000f089678  rdx: 0x0000000000000000
  rdi: 0x0000000000007003  rsi: 0x0000000000000006  rbp: 0x000070000f0896a0  rsp: 0x000070000f089678
   r8: 0x000070000f089540   r9: 0x00007ff815011729  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000007003  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff81501c1e2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

### Which application of Transmission?

macOS app

### Which version of Transmission?

Transmission-36f33c0d30 Build #9418 (Nov 10, 2023, 1:14:46 AM)

**Comment by tearfur** [comment]
Aww man this part of code waay too fragile...
