### ISSUE TITLE
A possible null pointer dereference issue

### ISSUE THREAD

**Issue by qingkaishi** [transmission/transmission#624]
https://github.com/transmission/transmission/blob/c11f2870fd18ff781ca06ce84b6d43541f3293dd/libtransmission/utils.c#L401-L426

In the above code, the branch statement at Line 418 means that the variable `out` may be null. It is then returned to the caller function (e.g., Line 163 in the following code) through Line 425 and Line 403.

https://github.com/transmission/transmission/blob/c11f2870fd18ff781ca06ce84b6d43541f3293dd/libtransmission/file-posix.c#L160-L171

Unfortunately, the pointer `p`, which may be null as explained before, is dereferenced directly at Line 168 without any checks.

**Comment by mikedld** [comment]
Handling OOM each and every time we (re-)allocate memory would be cumbersome, and handling it "properly" is too much work. Thus the [inconsistent] handling of it in `tr_strndup` and not the lack of handling in `create_path` is the issue. I very much agree with [Hans Passant's opinion](https://stackoverflow.com/a/7462498/583456) in this case and would rather add an exit/abort into `tr_malloc` and such. All in all, I'd better spend more time on errors we have greater chances to recover from.
