### ISSUE TITLE
Bump fastfloat to 5.3.0

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#6252]
### What is the issue?

New version of fastfloat out today https://github.com/fastfloat/fast_float/releases/tag/v5.3.0

### Which application of Transmission?

All

### Which version of Transmission?

All

**Comment by Coeur** [comment]
Pull request creation failed. Validation failed: must be a collaborator
https://github.com/transmission/fast_float/compare/transmission:main...fastfloat:main

**Comment by nevack** [comment]
> Oh, nice contributions in this release. ;)

<details>
<summary> 🏅 </summary>

<img src="https://github.com/transmission/transmission/assets/8330119/c42ae47c-2f94-46e7-89ce-8054989d993d" width="128" />

</details>
