### ISSUE TITLE
Allow binding multiple interfaces with bind-address-ipvx

### ISSUE THREAD

**Issue by Magissia** [transmission/transmission#626]
Greetings, would be useful to be able to bind to multiple addresses using bind-address-ipv{4,6}, syntax could be the same as rpc-whitelist.

**Comment by luoqi-git** [comment]
I was cleaning my github account today and closed some unresolved PRs including this one, https://github.com/transmission/transmission/pull/518, then I noticed your feature request -- it was precisely what the PR was for. Unfortunately I also deleted the fork that the PR was generated from, but the changelist is still accessible from the closed PR, you're welcome to give it a try or even take it over, as I have zero time dealing with such issues.

**Comment by ckerr** [comment]
This is a duplicate of https://github.com/transmission/transmission/issues/338
