### ISSUE TITLE
Connection to Trackers With Port Number in Announce Address Not Possible

### ISSUE THREAD

**Issue by Devillegi** [transmission/transmission#6265]
### What is the issue?

When a tracker URL has the port number in it, I cannot establish a connection when using the [SynoCommunity Transmission build](https://synocommunity.com/package/transmission). This issue does not happen when I download the (Windows desktop) build directly from Transmission. Therefore [I've reported it there first](https://github.com/SynoCommunity/spksrc/issues/5928), but was told I should report it here instead. So here we go :) :

I have noticed that with Transmission 4.0.4 (possibly 4.x) I seem to be unable to connect to trackers that have a port number in their announce URL. Specifically in my case using the 4.0.4-24 SynoCommunity build.

e.g. with "http://something.sometracker.net:2710/" I always get "Could not connect to tracker."
It works fine with trackers without a port number on the same machine/same Transmission instance.
Trackers with port numbers work fine with TR3.00 on another machine and used to work fine with TR3.00 on the machine now having issues.

Any chance there's a relation to https://github.com/transmission/transmission/issues/2510 ?
Can anyone reproduce this?

I'm aware the error message is very unspecific, but I'm not sure how/where I could get more logs.
I don't know how the behaviour is like on other Linux-flavours.
(I'm also aware that nowadays Transmission in a container is recommended, but I don't see myself migrating all my content just yet, tbh.)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

**Comment by tearfur** [comment]
If anything, this sounds like an issue with curl. When announcing to HTTP trackers, Transmission delegates all of the hard lifting to curl, all it does is specifying the curl options (destination URL, IP protocol, shared data, etc.).

Can you try running Transmission with the environment variable `TR_CURL_VERBOSE` set? Transmission and curl will emit some additional debug logs, and hopefully those will tell us what's happening.

**Comment by Devillegi** [comment]
This one was user error. Or rather fixed itself after shutting down Transmission and rebooting the machine its on.
I couldn't reproduce the issue on another near identical machine, which finally gave me the idea to try a reboot. My bad.

Still no idea what actually was the issue with curl there, I suspect it started after upgrading from Transmission 3.x to 4.x.

**Comment by Devillegi** [comment]
This one was user error. Or rather fixed itself after shutting down Transmission and rebooting the machine its on.
I couldn't reproduce the issue on another near identical machine, which finally gave me the idea to try a reboot. My bad.

Thanks for the information about curl doing the work. Still no idea what actually was the issue with curl there, I suspect it started after upgrading from Transmission 3.x to 4.x.
