### ISSUE TITLE
The Transmission 4.0.4 stable application does not open for me

### ISSUE THREAD

**Issue by caiiiycuk** [transmission/transmission#6266]
### What is the issue?

Hi. I've been using Transmission for a while, but now it's not showing the main window. I attempted to reinstall the latest version, but the issue remains. When the app launches, it displays the icon in the taskbar, yet the main window fails to appear. Pressing **Win+Up** doesn't have any effect. I can generate multiple main windows, but they all stay hidden or unresponsive. I just installed the latest Windows update **Windows 11, version 23H2**.  Could this update have caused the problem?

https://github.com/transmission/transmission/assets/1727152/cb2672cd-dd9c-48b1-9c9b-56af6d6c370c

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.4-x64

**Comment by mikedld** [comment]
Sounds pretty similar to #5341, does trying to move the window into view (mentioned there) help?

**Comment by caiiiycuk** [comment]
Moving does not help. Furthermore, in the window preview, I don't see any UI. However, connecting a second monitor helps. It seems that the transmission somehow remembers where it was last run, and when I detach the monitor, it creates a window on a non-existent screen. Nonetheless, as I mentioned, it's impossible to move it to any screen.

**Comment by tearfur** [comment]
How about #5982, does the solution there help?

**Comment by caiiiycuk** [comment]
Windows + Up also isn't working. However, it's not reproducing the issue anymore, so I'll close it for now.
