### ISSUE TITLE
What happened to Tray Icon?

### ISSUE THREAD

**Issue by alkaris2** [transmission/transmission#6269]
### What is the issue?

I remember Transmission having a tray icon where you could close the app to the system tray without fully closing Transmission, but that option seems to no longer exist, why is it removed?

![image](https://github.com/transmission/transmission/assets/73155407/2ad322b4-c1aa-4dbf-9851-4fee2561e545)

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.3 (6b0e49bbb2)

**Comment by GaryElshaw** [comment]
You have to build with GTK3. GTK4 doesn't support the tray.

**Comment by alkaris2** [comment]
AppIndicator and KStatusNotifierItem exist, why not use these?

**Comment by GaryElshaw** [comment]
More info here: https://github.com/transmission/transmission/issues/5670
