### ISSUE TITLE
Transmission downloaded invisible files that cannot be found anywhere on the disks

### ISSUE THREAD

**Issue by trancephorm** [transmission/transmission#6278]
### What is the issue?

![image](https://github.com/transmission/transmission/assets/5833909/bed63a33-75f7-47b9-ba51-95bfed36c119)
![image](https://github.com/transmission/transmission/assets/5833909/1b2c4039-24b8-4d54-994f-531714c1956b)

I've never seen anything this weird, Transmission shows files are downloaded, but only jpegs are actually there, no flacs. I have the same case with some other torrents from Redacted, not from other trackers. I searched for files on the disk - no luck, they are just ghosts in Transmission interface.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4

**Comment by ckerr** [comment]
Issue closed + user banned as per the issue template:

> For specific issues, attach a torrent or provide a magnet, with public domain content only. **YOU WILL BE BANNED** if you include information about pirated torrents.
