### ISSUE TITLE
Add Chinese support on Mac

### ISSUE THREAD

**Issue by SESProMax** [transmission/transmission#6284]
### What is the issue?

I'm using V4.0.4, can I change its language? Or maybe I can add Chinese support.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.4

**Comment by nevack** [comment]
Hi!

What is your system language?

By the way, you can change app language with system settings.

[Apple Support](https://support.apple.com/en-by/guide/mac-help/mh26684/mac)

![image](https://github.com/transmission/transmission/assets/8330119/42ab6e0a-2fee-42ee-9c3d-cb03e3795e0f)

**Comment by SESProMax** [comment]
There is no Chinese option.
***@***.***

**Comment by nevack** [comment]
To summarize:

> Dose transmission on mac only support English？

No, Transmission macOS client supports several languages.

> There is no Chinese option.

Yes, you are right, there's no Chinese translation provided.

**Comment by SESProMax** [comment]
I have checked this translation project. Chinese is already completed. But why does it have no Chinese option on Mac?

**Comment by Coeur** [comment]
@ckerr @mikedld @SESProMax Can one of you edit the title of this issue to mention explicitly about adding Chinese support? Thanks

**Comment by Settledust** [comment]
Hello, maybe i can help with the macOS Chinese translation? I have already made a zh_CN.lproj myself, can i upload it here? It adapts to ver 4.0.5

**Comment by SESProMax** [comment]
> Hello, maybe i can help with the macOS Chinese translation? I have already made a zh_CN.lproj myself, can i upload it here? It adapts to ver 4.0.5

要不你试试直接在项目里提交

**Comment by Coeur** [comment]
I'll mark this as "PR Welcome".
I believe that QT and GTK already have zh_CN, so I'll mark this as "scope: Mac".

Here is the process:
1. Read https://github.com/transmission/transmission/blob/main/docs/Translating.md
2. Go to https://app.transifex.com/transmissionbt/transmissionbt/language/zh_CN/ and download the resources for MAC
3. Make a pull requests adding the resources to the **main** branch for Transmission, and modifying a few configuration files:
- transmission.xcodeproj will need to have `zh-Hans` added to localizations
- macosx/CMakeLists.txt will need to have `zh-Hans` added to LINGUAS
<img width="1021" alt="Capture d’écran 2023-12-16 à 11 42 49" src="https://github.com/transmission/transmission/assets/839992/34669adb-9551-41d0-9cbb-7605a9bde5d3">

**Comment by SESProMax** [comment]
> Hello, maybe i can help with the macOS Chinese translation? I have already made a zh_CN.lproj myself, can i upload it here? It adapts to ver 4.0.5


Have you sent this pr request? If not you can set your trans file to me, I will pr. I have sent a request to this translation project, but it has not yet been granted.

**Comment by Settledust** [comment]
> > Hello, maybe i can help with the macOS Chinese translation? I have already made a zh_CN.lproj myself, can i upload it here? It adapts to ver 4.0.5
> 
> Have you sent this pr request? If not you can set your trans file to me, I will pr. I have sent a request to this translation project, but it has not yet been granted.

[zh_CN.lproj.zip](https://github.com/transmission/transmission/files/13767637/zh_CN.lproj.zip)
不好意思，这段时间比较忙没有留意消息，这是我做的语言包，已经使用了一段时间并根据实际情况润色了几遍，麻烦你了

**Comment by mikedld** [comment]
For my understanding, what is "zh-Hans" in #6437? In my /Applications folder,

```
% cat a.txt
$ find /Applications -name 'zh*.lproj' | egrep -o '[^/]+$' | tr A-Z a-z | tr _ - | sort | uniq -c | sort -nr
 186 zh-tw.lproj
 183 zh-cn.lproj
  48 zh-hk.lproj
  47 zh-hant.lproj
  47 zh-hans.lproj
  18 zh-hant-tw.lproj
   1 zh-hant-hk.lproj
```

At the same time on Transifex we have
* zh_CN — Chinese (China)
* zh_TW — Chinese (Taiwan)
* zh_HK — Chinese (Hong Kong)

And the archive attached above is for zh_CN (not zh_Hans). So my plan was to import the first 2 as they are now complete.

P.S. I can guess that "hans" is for "simplified" variant and "hant" for "tranditional", but I can't say if what's on Transifex under zh_CN right now is one or the other, and if importing zh_CN will do what you wanted to do with #6437 or if we'll need to map one to the other somehow (supposedly by extending configuration in .tx/config file).

**Comment by SESProMax** [comment]
Hans is the simplified version of Chinese, and Hant is the traditional version. Language I have uploaded is this friend(#6284) given to me. And it's polished, we think this maybe a better version. And this week I'm a little busy, maybe next week I will handle the problem in #6437.
________________________________
发件人: Mike Gelfand ***@***.***>
发送时间: 2023年12月27日 6:42
收件人: transmission/transmission ***@***.***>
抄送: watchout ***@***.***>; Mention ***@***.***>
主题: Re: [transmission/transmission] Add Chinese support on Mac (Issue #6284)


For my understanding, what is "zh-Hans" in #6437<https://github.com/transmission/transmission/pull/6437>? In my /Applications folder,

% cat a.txt
$ find /Applications -name 'zh*.lproj' | egrep -o '[^/]+$' | tr A-Z a-z | tr _ - | sort | uniq -c | sort -nr
 186 zh-tw.lproj
 183 zh-cn.lproj
  48 zh-hk.lproj
  47 zh-hant.lproj
  47 zh-hans.lproj
  18 zh-hant-tw.lproj
   1 zh-hant-hk.lproj


At the same time on Transifex we have

  *   zh_CN ― Chinese (China)
  *   zh_TW ― Chinese (Taiwan)
  *   zh_HK ― Chinese (Hong Kong)

And the archive attached above is for zh_CN (not zh_Hans). So my plan was to import the first 2 as they are now complete.

P.S. I can guess that "hans" is for "simplified" variant and "hant" for "tranditional", but I can't say if what's on Transifex under zh_CN right now is one or the other, and if importing zh_CN will do what you wanted to do with #6437<https://github.com/transmission/transmission/pull/6437> or if we'll need to map one to the other somehow (supposedly by extending configuration in .tx/config file).

―

**Comment by Coeur** [comment]
@mikedld please read my message from two weeks ago: for the macOS app, zh_CN needs to be renamed zh-Hans in the macosx folder.

**Comment by mikedld** [comment]
> @mikedld please read my message from two weeks ago: for the macOS app, zh_CN needs to be renamed zh-Hans in the macosx folder.

Why? From my previous message, I see that lots of other apps don't rename it and it (supposedly) works... It may be obvious to you, but I don't speak Chinese so I have no clue.

**Comment by Coeur** [comment]
Ah, maybe both work.

**Comment by Coeur** [comment]
Ah, I found it, it was under "More Languages" at the end of the list. So yes, it's valid.
<img width="513" alt="Capture d’écran 2023-12-29 à 12 40 52" src="https://github.com/transmission/transmission/assets/839992/092ee37c-61c5-4c29-8008-fb3fb5cd5cc2">

**Comment by stokito** [comment]
The zh_CN should be renamed to zh_Hans (e.g. Han Simplified).
Same the zh_HK and zh_TW should be renamed to zh_Hant (e.g. Han Traditional).

The zh_HK has less translations than the zh_TW so yoiu can simply remove it.

Here is a short description
https://mzikmund.dev/blog/supporting-chinese-localization-in-uwp-apps

**Comment by stokito** [comment]
BTW the en_GB, en_CA and en_AU doesn't have any difference and even they haven't any difference with en_US.
So you can drop them all

**Comment by Coeur** [comment]
@stokito can you open a new issue for zh_Hans?

en_GB/en_CA/en_AU aren't in Transmission.

**Comment by stokito** [comment]
Ok, created.

> en_GB/en_CA/en_AU aren't in Transmission.

I don't get it. They are in the `po` folder and looks like used.

**Comment by Coeur** [comment]
> I don't get it. They are in the `po` folder and looks like used.

The po folder isn't for the Mac app, it's for the GTK client on Linux.
