### ISSUE TITLE
auto updating 2.92 -> 2.94 failed

### ISSUE THREAD

**Issue by axet** [transmission/transmission#629]
Unable to update from 2.92 to 2.94 usint in app update. Also I do not see transmission-2.94.dmg files on github release page. Just in case if it is another security issue. Or just a bug.

**Update Error!**

An error occurred while extracting the archive. Please try again later.

<img width="469" alt="screen shot 2018-05-19 at 12 32 45" src="https://user-images.githubusercontent.com/298672/40267175-e2e3ba7e-5b60-11e8-9e33-7123a52c0970.png">

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #600.
