### ISSUE TITLE
transmission-2.94-x64 installation issue

### ISSUE THREAD

**Issue by vinothvkr** [transmission/transmission#630]
Hi Team,

I tired to install 2.94 version x64 on windows 10, but installation was prevented by windows defender smartscreen. Attached the screenshot of it, please help to fix the issue. Thanks in advance.
![transmission-2 94-x64](https://user-images.githubusercontent.com/9390245/40639257-9fc5931e-632d-11e8-8551-7d11998a1017.JPG)

**Comment by vinothvkr** [comment]
![image](https://user-images.githubusercontent.com/9390245/40898664-7146dee6-67e0-11e8-817d-344c4f918cb3.png)
SS with more info has been attached.

**Comment by vinothvkr** [comment]
Bump.

**Comment by Smithy3** [comment]
SmartScreen by default blocks anything that it deems as unrecognized (i.e. very few installs).
It’s not something that can really be fixed.
