### ISSUE TITLE
Choosing LPD interface

### ISSUE THREAD

**Issue by shreyanshk** [transmission/transmission#631]
I'm trying to use Transmission as a part of another project.
I want to use transmission to seed a bunch of files (private) present on the local computer so that other computers on the same network can download them (other computers already have the corresponding '.torrent' file).
Ideally, I want to use LPD so that client computers can easily discover the seed computer without being dependent on a Tracker.
FYI, the seed computer has multiple network interfaces.

What is happening (I think) right now?
Transmission starts LPD on only 1 interface (which is, unfortunately, it's own choice of interface).
I identified this by starting LPD on local transmission process and then using wireshark to see if any LDP membership join requests were being broadcasted on the interface.

What should ideally happen? (Either one of this is sufficient)
* Transmission should start LPD on all present interfaces 
* Transmission should give the user means to select an interface

Is it possible to accommodate this? I really hope so.

Any help you can do will be much appreciated.
Please let me know if I'm missing something.

Thank you.
--
Software: Arch Linux (updated 29/05/18, rolling release), Transmission 2.94 (d8e60ee44f)

**Comment by shreyanshk** [comment]
Update (30/5/18):
The interface is chosen based on where 224.0.0.0/3 is routed. This seems to be a hard coded value.

**Comment by imz** [comment]
I've also hit this problem that the local peers on a second interface were not discovered with transmission-daemon-2.94, until I did a strange thing on both sides:

```
ip route add 224.0.0.0/4 dev tap0
```

Maybe improvements to the code to loop through all interfaces would fix/workaround this problem -- in the spitit of **UPDATES** notes in [Use ip route add to add multicast routes to multiple interfaces](https://serverfault.com/q/814259/68972) (the discussion there also explains why adding a route with `ip route` is a strange wrong thing):

>  I realized the error was in our code. We were not setting the interface to use for multicasting with `IP_MULTICAST_IF`. Once I added the `setsockopt` call to set `IP_MULTICAST_IF`, I no longer needed to add the routing tables.
>
>    struct in_addr multicastInterface = {};
>    multicastInterface.s_addr = interfaceAddressNetworkOrder;
>    
>    // Set which outgoing interface to use
>    int result = setsockopt(m_socket, IPPROTO_IP, IP_MULTICAST_IF, (char*)&multicastInterface, sizeof(struct in_addr));

I haven't looked into the source code of transmission-daemon to check how this is done now; nor haven't I tried to patch it along this lines and see whether setting this option would enable the communication through the additional interface.

**Comment by imz** [comment]
<https://forum.transmissionbt.com/viewtopic.php?p=68500&sid=cab4c31801758a28f60761990cc90ca0#p68500> discusses related issues:

>  The seed server does have multiple interfaces/addresses, and I can see that causing potential problems. I tried setting bind-address-ipv4 to the LAN IP the clients are on but it still didn't help.
