### ISSUE TITLE
Transmission on Android keeps stopping as soon as exiting active window.

### ISSUE THREAD

**Issue by swoondrones** [transmission/transmission#6310]
### What is the issue?

I can't figure this out. For some reason as soon as I put the transmission window in the background, it stops automatically. It will only work if the window is showing. And even then I'm not sure if it's downloading anything. This is only happen recently and I have no idea why it began. 

Can someone help me with this and fix it? It's really frustrating. Is there a absolute limit of how many tolerance I can have going even though most of them are paused because they've fully downloaded? But I use it as a library of what I've downloaded to then play. I really need some help with this. 

Thanks.

### Which application of Transmission?

None

### Which version of Transmission?

The latest Android one.

**Comment by mikedld** [comment]
We're not making any official Android releases. Your issue is with a 3rd-party app (not one of the official apps we maintain here), please contact its authors instead.
