### ISSUE TITLE
Flatpak version always uses light mode, not system dark theme

### ISSUE THREAD

**Issue by RichardJECooke** [transmission/transmission#6312]
### What is the issue?

Ubuntu 22.04 on X.org.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by mikedld** [comment]
We're not making any official Flatpak releases. Your issue is with a 3rd-party package (not one of the official packages we maintain here), please contact its authors instead.
