### ISSUE TITLE
[macOS] Confirmation window cannot be turned off.

### ISSUE THREAD

**Issue by emxjay** [transmission/transmission#632]
Unchecking the option `Display a window when opening a magnet file` has not effect.

Thanks.

**N.B.** Transmission 2.94 (d8e60ee44f) on macOS High Sierra (10.13.4).

**Comment by mikedld** [comment]
Set download location to a specific directory instead of "Same as torrent file". Magnet links are not files and thus don't have a location on disk, hence the download location cannot be deduced. Functions as designed.

**Comment by emxjay** [comment]
For the record, it was already set to a specific directory. Now, setting it to `Same as torrent file`, then back to a directory did the trick.
