### ISSUE TITLE
Doesn't respect GNOME dark|light theming

### ISSUE THREAD

**Issue by pchmykh** [transmission/transmission#6327]
### What is the issue?

Doesn't respect dark / light GNOME settings.
Flatpak, Fedora 39, GNOME 45.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #6312, #5275, #5140.
