### ISSUE TITLE
macOS Nightly Builds failing to download torrents with subdirectories

### ISSUE THREAD

**Issue by robd003** [transmission/transmission#6339]
### What is the issue?

Getting a lot of "No such file found" on the last few nightly builds for any torrent that has subdirectories.

### Which application of Transmission?

macOS app

### Which version of Transmission?

3cd66899fe

Specific error: ```Error: Couldn't get 'features_EN/postgres/data/base/1/PG_VERSION`: No such file or directory (2)```

I've only seen this error when selecting a few files in a torrent rather than downloading the entire thing. Also the error of not being able to find a file seems to be for files that haven't been selected to be downloaded.

**Comment by robd003** [comment]
@Coeur / @tearfur I wonder if this has to do with the zero byte changes recently merged in

Any advice on debugging this further?

**Comment by tearfur** [comment]
I'm afraid there's no other way than tracing the code. I think I know what the cause is though, PR soon.
