### ISSUE TITLE
Webclient does not show correct download directory for torrents that have been moved

### ISSUE THREAD

**Issue by MaartenDeen** [transmission/transmission#6352]
### What is the issue?

I think this bug has similar origins as https://github.com/transmission/transmission/issues/6330 .

Expected behaviour:
When using Set Location... in the webclient, the torrent is moved to another location. After all the files have been moved, when you open that dialog again, you should see the new location.

Observed behaviour:
After all the files have been moved and opening the dialog again, you still see the old location. The location is updated when you refresh the webclient.

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.1.0-dev bcc81f61c0

**Comment by MaartenDeen** [comment]
No, i disagree. I know the old location stays until the files are completely moved, but I just tested one, the files were moved within seconds but the location is not updated, even after 15 minutes.

**Comment by tearfur** [comment]
Huh, but I test in Firefox too. Could it be your cache?

**Comment by MaartenDeen** [comment]
Well, a sure way to clear the cache is reload the page, and sure, it's gone then but it returns for the next one.

**Comment by tearfur** [comment]
Ahh, I think I have an idea for what's causing this.

Transmission's WebUI tries to optimise the process of updating torrent status by retrieving info for "recently active" torrents only. It does so by setting `"ids": "recently-active"` in the `torrent-get` RPC call.

Setting location does not count as being "active" in this context.

Perhaps your torrent has not been "active" in those 15 minutes you waited, so it was never updated and WebUI never got its new location.

**Comment by MaartenDeen** [comment]
That's very likely. I first though it was with idle incompleted torrents only (I have some of those), but then I also saw this for others. I tried with an active torrent and there the location did get updated.

**Comment by killemov** [comment]
@tearfur Slightly related ... Why does changing the queuePosition count as being active? Maybe what qualifies as `recently-active` should be limited to actual torrent upload/download and status changes.

**Comment by killemov** [comment]
> @killemov Queue positions are one of the return values of `torrent-get` after all.

True, but changing `queue-position` is also user-driven, just like changing the location. So think about not counting user-driven changes as recently active.

**Comment by tearfur** [comment]
User-driven or not, a change in a torrent's status needs to be counted as recently active, for multiple reasons. I'll use queue position for my example here.

1. The RPC request to update the queue position is not guaranteed to succeed, so the client cannot assume the queue position has been updated until it receives a status update from the daemon, which is done using the `recently-active` parameter in our official WebUI.
2. Even if there is a smart trick that allows the client to assume the updated queue position, other clients that are connected to the same daemon will not receive the updated queue position if it is not counted as recently active.

**Comment by killemov** [comment]
@tearfur First off, thank you for answering even though the issue was closed.

> The RPC request to update the queue position is not guaranteed to succeed.

This is both extremely disturbing news and also not very likely. I do a request to transmission-daemon and it MUST respond with either a resulting success or an error message. See [2.2 Responses](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#22-responses).

> Even if there is a smart trick that allows the client to assume the updated queue position, other clients that are connected to the same daemon will not receive the updated queue position if it is not counted as recently active.

For years I always assumed that consuming the RPC was meant for, but not limited to, single use. And I still believe it is so. The use-case for multiple consumers is extremely niche. Do cached outgoing messages have consumer counters, so you know all consumers got the outgoing message?
