### ISSUE TITLE
wip/gtk-3.14: correct icon path

### ISSUE THREAD

**Issue by pavreh** [transmission/transmission#636]
Icon path is:
/usr/share/icons/hicolor/16x16/apps/transmission.png/transmission.png
It should be:
/usr/share/icons/hicolor/16x16/apps/transmission.png

It is valid for every hicolor icon (not only 16x16) on wip/gtk-3.14 branch.

**Comment by ckerr** [comment]
Fixed by 91b4e5c3c440434fa5d52973e855507c5ff66b58
