### ISSUE TITLE
Transmission 4.0.5 (a6fe2a64aa) ignores speed limit and bandwidth settings

### ISSUE THREAD

**Issue by miklosUX** [transmission/transmission#6361]
### What is the issue?

It seems my settings for speed limit and general bandwidth are completely ignored in this version. I have my global bandwidth limit set at 1800 KB/s, my speed limit at 900 KB/s and the download rate just hit 3 MB/s and this is with speed limit ON.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by tearfur** [comment]
I see, the code I removed in #6134 was actually a way to roughly compensate for whatever reason the code below is not enough to limit transfer speeds for uTP peers.

https://github.com/transmission/transmission/blob/4037726150b4e508d099a676440a99869b15c6a8/libtransmission/peer-io.cc#L732-L751

I'll look into it.

**Comment by su1736** [comment]
I have Transmission 4.0.5-26 on Synology NAS.

Seems like Transmission during its start doesn't read settings.json or ignores alternate speed limit setting.

If I connect to Transmission through its web-interface or Transmission Remote GUI on Windows, I see the setting "use limit" unchecked. I set it check and this setting starting to work. But after restarting Transmission service, it became unchecked again and speed limit doesn't work.
But in settings.json this setting is always in "true"!

![image](https://github.com/transmission/transmission/assets/3241647/5879fdf3-e9cc-4079-99ea-d2baf742e092)

![image](https://github.com/transmission/transmission/assets/3241647/27cc7285-a532-4399-b22e-3762f73a8ef8)

![image](https://github.com/transmission/transmission/assets/3241647/deb02616-5dcf-436b-b60d-7570d0c1acc4)

**Comment by jbarlov** [comment]
Was there any new info on if it's been added to be fixed?

**Comment by jbarlov** [comment]
No?

**Comment by jbarlov** [comment]
Echo?

**Comment by tearfur** [comment]
As you can see from the status of this issue, this has already been fixed in `main`.

I've also created a PR to backport the change to `4.0.x` #6551.

**Comment by tessus** [comment]
@tearfur please see #6736 

This is really a serious issue. I don't understand why a hotfix hasn't been released. It practically does not allow you to use Transmission unless you have a separate Internet connection for it. I am pretty sure that almost nobody has.

**Comment by tearfur** [comment]
See my replies at #6736. It's probably not what you want to hear so I won't repeat it here, but it's what it is.
