### ISSUE TITLE
missing torrent icons in 4.0.5 webui

### ISSUE THREAD

**Issue by Daniel6372** [transmission/transmission#6362]
### What is the issue?

The torrent icons that indicate the type of file(s) within them are missing from the webui after updating to 4.0.5.
The pause/resume icons normally to the right of the progress bars are also missing.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by tearfur** [comment]
Can confirm this happens on my end too.

**Comment by tearfur** [comment]
@ckerr Looks like purely a mistake in the build process, running `npm run build` again compiles a normal WebUI.

**Comment by pankaj-2503** [comment]
I can work on this issue assign this to me.

**Comment by tearfur** [comment]
Feel free to open a PR any time :)

**Comment by pankaj-2503** [comment]
can you help me how to look forward toward this issue

**Comment by tearfur** [comment]
What help do you need?

**Comment by tearfur** [comment]
I think this is actually a Firefox bug, seems like it cannot render the svg content encoded in a data url stored in a custom property.
On Chrome, everything is normal.

![image](https://github.com/transmission/transmission/assets/46261767/b32ac554-adb7-418a-ac92-e7907eb2fe33)

**Comment by GaryElshaw** [comment]
Possibly related, the play/pause icons from the webui are also MIA.

![image](https://github.com/transmission/transmission/assets/69029666/f772c638-c98c-4793-916a-b29a3423432e)

**Comment by Daniel6372** [comment]
> I think this is actually a Firefox bug, seems like it cannot render the svg content encoded in a data url stored in a custom property. On Chrome, everything is normal.

Are you sure? I tried Chrome too, then on a Windows machine Bing and Chrome, and finally the Windows version of the daemon as well. None of the combinations had the icons present.

A few days ago I still had 4.0.4 running on a machine for immediate comparison and the icons were still present there.

**Comment by GaryElshaw** [comment]
Sorry, i should have said, ungoogled-chromium 120.0.6099.109 (Official Build, ungoogled-chromium) (64-bit) on Linux.

**Comment by tearfur** [comment]
> Are you sure?

Hmm, tried again and this time they are gone on Chrome too... I even made sure to try in Incognito mode...

Anyway, I think I know what's wrong, fixing right away.

**Comment by GaryElshaw** [comment]
What do you think @tearfur? It's obviously SVG related.
