### ISSUE TITLE
sequentialDownload does not work in torrent-get

### ISSUE THREAD

**Issue by qu1ck** [transmission/transmission#6365]
### What is the issue?

I have latest transmission version from main branch, 4.1.0-dev (4037726150)

The `sequentialDownload` field can not be fetched from rpc:

```
curl 'http://127.0.0.1:9091/transmission/rpc' \
  -H 'Authorization: Basic <redacted>' \
  -H 'X-Transmission-Session-Id: <redacted>' \
  --data-raw '{"method":"torrent-get","arguments":{"fields":["name","sequentialDownload"],"ids":[316]}}' 
```
Response has only name:
```
{"arguments":{"torrents":[{"name":"random data"}]},"result":"success"}
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1.0-dev (4037726150)

**Comment by tearfur** [comment]
@qu1ck Are you willing to submit a PR for this? I think you've got to the bottom of it.
