### ISSUE TITLE
"Show transmission icon in the notification area" is missed even with Ayatana Indicators installed

### ISSUE THREAD

**Issue by N0rbert** [transmission/transmission#6385]
### What is the issue?

Current version of Transmission GTK lacks the very useful Tray Icon. Please provide it.
In previous versions it was configurable from *Preferences → Desktop → Show transmission icon in the notification area*.
In 4.x versions this functionality is missed. I see no icon in default `task-mate-desktop` installation and no icon with Ayatana Indicators enabled (`sudo apt-get install ayatana-indicator-* ayatana-settings` and Indicator Applet Complete added to MATE Panel).

### Which application of Transmission?

transmission-gtk

### Which version of Transmission?

4.0.2 on Debian trixie + sid

**Comment by GaryElshaw** [comment]
Are you building from source, @N0rbert?

**Comment by N0rbert** [comment]
At first attempt I tried the most straightforward method - I have installed Debian 13 with binary [transmission-gtk from sid](https://packages.debian.org/sid/transmission-gtk).
It is built with GTK-4 - see

```
$ transmission-gtk --version
transmission-gtk 4.0.2 (2a57b17031)
$ ldd /usr/bin/transmission-gtk | grep gtk
	libgtkmm-4.0.so.0 => /lib/x86_64-linux-gnu/libgtkmm-4.0.so.0 (0x00007f2e57c00000)
	libgtk-4.so.1 => /lib/x86_64-linux-gnu/libgtk-4.so.1 (0x00007f2e57200000)
```

but I do not see any linkage with indicators

```
$ ldd /usr/bin/transmission-gtk | grep indicator
```

On the previous Debian 11 I see the linkage with GTK-3 and Ayatana Indicators:

```
$ transmission-gtk --version
transmission-gtk 3.00 (bb6b5a062e)
$ ldd /usr/bin/transmission-gtk | grep -iE "gtk|indicator"
	libayatana-appindicator3.so.1 => /lib/x86_64-linux-gnu/libayatana-appindicator3.so.1 (0x00007fc00997b000)
	libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fc009000000)
	libayatana-indicator3.so.7 => /lib/x86_64-linux-gnu/libayatana-indicator3.so.7 (0x00007fc0084d1000)
	libdbusmenu-gtk3.so.4 => /lib/x86_64-linux-gnu/libdbusmenu-gtk3.so.4 (0x00007fc0084ba000)
```

To get more reproducible results I tried Ubuntu MATE 23.10 with the same Transmission 4.0.2 (2a57b17031).  
Here the situation is the same. Rebuilding from deb-src with `-DUSE_GTK_VERSION=3` is not possible because of the compilation error.
The latest 4.0.5 version from `ppa:ubuntuhandbook1/transmission` does not show tray icon too.

Have you ever tested Transmission 4.x with Ayatana Indicators? On which distro?

**Comment by GaryElshaw** [comment]
Because of changes in GTK4, unfortunately having a tray icon isn't possible right now. GTK3 is absolutely fine. I have a PR down the track, but i need consensus from project maintainers for Ayatana to be a project requirement.

It's a simple change to Transmission/GTK/SystemTrayIcon.cc

Line 58 of that file needs to be changed from `"transmission-tray-icon"` `"transmission-symbolic"`

![Screenshot from 2023-12-17 10-51-31](https://github.com/transmission/transmission/assets/69029666/7041bc6c-cd72-4418-8f97-8f497c839c90)

ninja or make and it should be fine, and theme compliant.

**Comment by rharish101** [comment]
Hi, does this mean that if I build Transmission with GTK4, even if I have ayatana indicators available during compilation, it won't have systray support? This comment implies that you can have GTK4 and ayatana indicators at the same time: https://github.com/transmission/transmission/issues/5670#issuecomment-1614974850.
