### ISSUE TITLE
Allow changing data location of torrent when multiple torrents download to the same directory.

### ISSUE THREAD

**Issue by zwimer** [transmission/transmission#6388]
### What is the issue?

Say I have 2 torrents, `T1` and `T2` saves to my `/downloads/A` directory.
`T1` is for the file `D/T1.txt` and `T2` is for `D/T2.txt`.

If I move `T1` to `/downloads/B` it will move the entire directory `D` including `D/T2.txt`, leaving `T2` without any data.

If nothing else, there should be a warning about this though ideally moving `T1` would only move the files `T1` is responsible for, not the entire directory. If transmission considers `T1` to own the directory `D` then I think transmission should either prevent `T2` from being added with the same name (`D`) in the same directory (`/downloads/A`) as `T1` or at least should warn the user beforehand.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
No. Transmission does not know about "bridging" torrents. The only sensible use case is to complete the SAME incomplete content with multiple torrents. In your example your torrent top-level name would be "D", which is okay if you only have one of those. If you can't change multiple but equal top-level names at the source YOU should be very careful when deleting/moving that content. If the top-level name is different but the content is the same you would use hard links on the filesystem.

**Comment by zwimer** [comment]
I am unfamiliar with the term "bridging torrents". One example of when the issue above arises is when downloading something like 2 torrents `MySeries` in different seasons. Like:

`Torrent 1`: `MySeries` which contains:
`MySeries/Season 01/Episode 1.mkv`
`MySeries/Season 01/Episode 2.mkv`
`MySeries/Season 01/Episode 3.mkv`

`Torrent 2`: `MySeries` which contains:
`MySeries/Season 02/Episode 1.mkv`
`MySeries/Season 02/Episode 2.mkv`
`MySeries/Season 02/Episode 3.mkv`

Here both would download to the same directory.

The issue listed above would allow me to, for example, have transmission move `Torrent 1` from `/downloads/ForWife` to `/downloads/ForWife` without also silently moving the data of `Torrent 2`.

**Comment by zwimer** [comment]
More to the point, the issue above would have transmission only move the files the torrent owns. A torrent should only claim ownership of what it downloads, so moving or deleting a torrent should only remove those files and nothing else. Minimally a warning that there are unexpected files before moving them would be beneficial- the onus should not be on the user to check every torrent they have doesn't conflict with any other before every move of a torrent.

That's generally the feature this issue is about.

**Comment by tearfur** [comment]
Since you are using the daemon, I assume you are using the RPC `torrent-set-location` API to move the files? But that wouldn't make sense, because the code does move each and every file one by one:

https://github.com/transmission/transmission/blob/d467fa1f7f6b9b2cf8e4d6feaea45b344e302cd6/libtransmission/torrent-files.cc#L183-L206

My test results also confirms this. I created 2 test torrents `D_1.torrent` and `D_2.torrent`, then tried to move `D_1.torrent`, and the files for `D_1.torrent` stayed in place. Attaching test files used.

[tr_6388.zip](https://github.com/transmission/transmission/files/15466278/tr_6388.zip)

**Comment by zwimer** [comment]
On the version I have now, I can no longer replicate this issue so I'm marking it as closed. Thanks!

**Comment by edgan** [comment]
#251
