### ISSUE TITLE
Web UI shows "Connection Failed" when a XHR POST fails and it does dissappear when it succeeds

### ISSUE THREAD

**Issue by gdubicki** [transmission/transmission#6396]
### What is the issue?

Hi,

I installed transmission-daemon 3.00 (bb6b5a062e) on my old Raspberry Pi Zero W v1.1 with Raspbian / Raspberry OS bullseye.

I think that because it's a very slow device, sometimes the XHR POST requests to refresh the UI fails (times out?), and when this happens, an "Connection Failed", "Could not connect to the server. You may need to reload the page to reconnect." error message is shown.

One problem is that I don't really care that the UI failed to update one or two times, so I would prefer this message to be shown as a non-modal. But I supposed that this would be a feature request.

But the second problem is a bug in my opinion - when the next POST request succeeds, the error message should disappear and the UI should be updated, but it does not happen.

<img width="1918" alt="Screenshot 2023-12-17 at 11 30 32" src="https://github.com/transmission/transmission/assets/566632/11b853b0-5530-4fea-92bb-58e62f561857">

### Which application of Transmission?

Transmission daemon

### Which version of Transmission?

3.00 (bb6b5a062e)

**Comment by killemov** [comment]
A configuration setting to suppress this dialog completely would be nice. Maybe a connection status indicator in toolbar or, even better, the menu bar would suffice.

**Comment by hluup** [comment]
> But the second problem is a bug in my opinion - when the next POST request succeeds, the error message should disappear and the UI should be updated, but it does not happen.

Created a PR for this - https://github.com/transmission/transmission/pull/6657

Though I kind of agree that maybe it shouldn't be a popup at all, but instead should be an some sort of indicator on the toolbar.
