### ISSUE TITLE
Allow renaming files externally

### ISSUE THREAD

**Issue by haansn08** [transmission/transmission#6397]
### What is the issue?

I didn't like the file names of the torrent I downloaded so I renamed them using my file manager. After doing so, Transmission cannot find the files anymore. Would it be possible that the "Set Location..." option calculates the checksum of the files contained in the selected folder and matches them with the files in the torrent?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.4 (24077e3511)

**Comment by LaserEyess** [comment]
What you're looking for is [RPC](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#37-renaming-a-torrents-path).

**Comment by haansn08** [comment]
@LaserEyess You mean I should use it to make a script to do this?

**Comment by LaserEyess** [comment]
Yes, if "Set Location" doesn't do what you need, then you'll need to use RPC directly to fix it.

**Comment by dvingerh** [comment]
I made my own program a while back that allows bulk renaming of files downloaded with transmission, it may be useful to you: https://github.com/dvingerh/transmission-renamer

**Comment by tearfur** [comment]
Closing this since it is simply not possible to implement in an efficient way.
