### ISSUE TITLE
Does not save the set columns settings

### ISSUE THREAD

**Issue by cry0xen** [transmission/transmission#640]
transmission 2.94/remote gui v5.15.4
os win7

Transmission remote gui Does not save the set columns settings. Each time the programme restarts, it goes back to default settings. I have to reorganize my columns, add or remove  them and sort them to my customization. doing this every time when client restarts is very irritating.

**Comment by mikedld** [comment]
Wrong repository, please refer to [transmission-remote-gui/transgui](/transmission-remote-gui/transgui).
