### ISSUE TITLE
torrent-stop does not trigger 'recently-active'

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6403]
### What is the issue?

Similar to #5996, start/stop no longer sets torrent to "recently-active"

If torrent is currently stopped, and has been stopped since Tr4 initialized, then on torrent-start the status is properly set to recently-active.  However, torrent-stop will not set to recently-active, and a sequence of stop/start will not change status.

Have only tested @a494da4f , not sure if this has always been true of Tr4 or only recent.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4

**Comment by tearfur** [comment]
The cause was exactly the same as [#5996](https://github.com/transmission/transmission/issues/5996#issuecomment-1829390230) too.
