### ISSUE TITLE
simple ldap auth for webui

### ISSUE THREAD

**Issue by cyberb** [transmission/transmission#6412]
### What is the issue?

I would like to add transmission to Syncloud self-hosting project (https://github.com/syncloud/platform) app store and I need basic ldap support to be able to authenticate against running locally openldap server so users can manage their credentials in one place.

I am only interested in webui + daemon (no desktop) as Syncloud is a web device.

I can try adding it myself (not a lot of c++ experience) if it has a chance of being merged.

### Which application of Transmission?

None

**Comment by killemov** [comment]
You could do that NOW with a reverse proxy. Just put an LDAP-enabled web-server in front of it.

**Comment by cyberb** [comment]
Ok I guess transmission does not need to know or have any user info so I can be done outside, I will try something like https://www.authelia.com

**Comment by nevack** [comment]
> Ok I guess transmission does not need to know or have any user info so I can be done outside, I will try something like [authelia.com](https://www.authelia.com)

If you are successful with this, you can always write some guide in our Docs/ how to set it up.

**Comment by cyberb** [comment]
am I right that transmission daemon is not a multi user tool and if I authenticate different users it will still show the same list of torrents to all of them or is there a way to make it keep state per "user"?

> If you are successful with this, you can always write some guide in our Docs/ how to set it up.

at least I will post some results here

**Comment by killemov** [comment]
"not a multi user tool " => "single user tool" And yes it is a single user tool.

Usually Transmission runs under user "transmission" or similar. If you use web you can only set credentials for a single user. Running per-user instances is possible but a hassle to configure. If you must you can store data in a cookie or maybe you can do something more with the reverse proxy than just reverse proxying. I'm the creator of [Shift](https://github.com/killemov/Shift) which uses a cookie to store per device settings.

**Comment by cyberb** [comment]
ok, authelia (ldap auth mode) + transmission seems to work, here is the config for reference: https://github.com/syncloud/transmission/blob/master/config/nginx.conf
