### ISSUE TITLE
4.0.5 build error 

### ISSUE THREAD

**Issue by cyberb** [transmission/transmission#6415]
### What is the issue?

building under debian:buster-slim docker image.

```
apt -y install build-essential cmake wget libcurl4-openssl-dev libssl-dev
wget --progress dot:giga https://github.com/transmission/transmission/releases/download/4.0.5/transmission-4.0.5 .tar.xz
tar xf transmission-4.0.5 .tar.xz
cd transmission-4.0.5 
cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_QT=OFF -DENABLE_MAC=OFF -DENABLE_GTK=OFF
cd build
cmake --build .
```

Error:
```
CMake Error at libtransmission/CMakeLists.txt:13 (add_compile_options):
Error evaluating generator expression:
$<CXX_COMPILER_ID:AppleClang,Clang>
$<CXX_COMPILER_ID> expression requires one or zero parameters.
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by cyberb** [comment]
Ok, using debian:bookworm-slim helped

**Comment by nevack** [comment]
> Ok, using debian:bookworm-slim helped

@mikedld @Coeur I suppose we incorrectly state minimum supported cmake version

`cmake --version` inside `debian:buster-slim` docker:
```
cmake version 3.13.4
```

**Comment by Coeur** [comment]
So, I added this syntax in #5632. According to doc, it's supported since cmake **3.15**.
I'll update the minimal required version
