### ISSUE TITLE
Add easy GUI to search and replace in tracker lists (announce URLs) of all torrents

### ISSUE THREAD

**Issue by Harvie** [transmission/transmission#642]
I know there's `transmission-edit -r ...` but that needs me to get torrent files, edit all of them, remove torrents from transmission and load new edited torrents. That's not very user friendly and i had to do that several times until i got it right.

Thing is that my tracker key changed and i had to figure all of this out. I would rather have some easier way of changing tracker key globaly directly using web UI.

Do you think it would be possible?

**Comment by ckerr** [comment]
Closing as a subset of https://github.com/transmission/transmission/issues/5234
