### ISSUE TITLE
When I select to see files in download location program opens VS Code instead of Nemo.

### ISSUE THREAD

**Issue by ConwayPhelps** [transmission/transmission#6429]
### What is the issue?

Transmission 3.0, Ubuntu 22.04 (Jammy), Cinnamon 5.2.7, Visual Code 1.85.1
When I select to see the files within the download location from within Transmission (/Downloads), rather than opening Nemo to browse the directory, it opens Visual Code to browse the files in the directory instead. I have been through all the settings and I don't see any way to change which program works as the file browser. This is confusing me because I don't remember this happening before. 

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

3.0

**Comment by nevack** [comment]
This is not related to Transmission

https://askubuntu.com/questions/235660/how-do-i-change-the-default-file-manager-back-to-nautilus

I also had VSCode set itself as default file manager some time ago

**Comment by ConwayPhelps** [comment]
The default is Nemo, not VS Code. Transmission is the only application that opens Code instead of the default, Nemo. Every other program that does a call to open the default opens Nemo, not Code.

**Comment by ConwayPhelps** [comment]
It was you suggested, somehow Code had established itself as the default away from Nemo. Thank you.
