### ISSUE TITLE
Transmission QT Client has stopped working

### ISSUE THREAD

**Issue by S1ngS1ng** [transmission/transmission#643]
After I open Transmission for 30 sec ~ 1 min, it stopped working every single time :(

I am on Windows 10 Home X64

Transmission QT version: 2.94 (d8e60ee4f) (x64)

![image](https://user-images.githubusercontent.com/13592559/41496926-d2cca2d6-7118-11e8-9c12-442713aba6c2.png)

**Comment by ckerr** [comment]
Given the age of this ticket and the lack of actionable information, I'm going to close this ticket. Transmission was not as well-maintained in 2018 and this issue did not get enough followup at the time.

If this is still happening in the Transmission 4 series, please open a new bug report. Thanks!
