### ISSUE TITLE
Transmission does not support Dark Mode on macOS Mojave

### ISSUE THREAD

**Issue by pshirshov** [transmission/transmission#644]
Transmission ignores Dark Mode on most recent macOS and draws all-white UI.

I guess this should be fixed.

**Comment by Sombre-Osmoze** [comment]
You just have to build Transmission with Xcode-beta 10

Here a build from **current** master down here : 
[Transmission.app.zip](https://github.com/transmission/transmission/files/2312536/Transmission.app.zip)

**Comment by diver-down** [comment]
Agreed, it would be nice to have the installation (as-downloaded from [https://transmissionbt.com/download/](https://transmissionbt.com/download/) ) support dark mode "out of the box"...

That being said, thanks Sombre-Osmoze for the fix! :)

**Comment by Sombre-Osmoze** [comment]
You're welcome, then I think the issue can be closed

**Comment by slimnickyy** [comment]
not really as gatekeeper is unhappy with the unsigned file and even if I run it anyhow macOS firewall asks to allow incoming connections each time I open this version. also little snitch is upset that the code doesn’t match. an official release would be grateful

**Comment by Sombre-Osmoze** [comment]
My bad, I forgot to signed the app with a distribution certificate
But anyway a official release is better, I juste share my version of "Transmission" for who that can't wait

**Comment by williamluke** [comment]
>My bad, I forgot to signed the app with a distribution certificate ...

@Sombre-Osmoze Did you update the colors to change semantically? I have the source files that fix these issues for both light and dark mode but I haven't got around to fixing the progress bars yet (minor issue). I should also submit a pull request one I fix once I have the progress bars fixed.

**Comment by williamluke** [comment]
Mac OS 10.14 support: [https://github.com/williamluke/transmission-1/releases](url)  
In Xcode 10 edit: **File...** > **Project Settings...** >  **Per-User Project Settings:** > **Build System** to **Legacy Build System** to build from source

**Comment by slimnickyy** [comment]
thanks, but again notwithstanding gatekeeper, which can be overruled, the Mac firewall complains each time that build is opened as does little snitch in relation to a signed code mismatch. hopefully it can be officially signed.

**Comment by williamluke** [comment]
Yes, I agree, there needs to be an official release but no need to we wait for the developers to sign. This does work in the meantime until they do something to push another official release. I'll be looking to contribute whatever I can in the future.

**Comment by williamluke** [comment]
> I’ve done that. it doesn’t change firewall from asking every time the app is opened. likewise little snitch complains too unless I tell it to ignore the signature.
Sorry, I didn’t test the unsigned version against the native firewall but there was an issue that prevented signing.
The signed version is now up: [link](
https://github.com/williamluke/transmission-1/releases)

**Comment by slimnickyy** [comment]
@williamluke  thank you that’s excellent 👍

**Comment by nucleare2** [comment]
@williamluke what's the difference between v2.94 and v2.94+ on your releases? strange one seems newer than other but older one seems vertically out of order....

**Comment by MartinZubek** [comment]
Hi guys, is there anything new on the official dark theme for Transmission?
I am almost beginning to think that we'll might never get it at all. :-(

**Comment by MartinZubek** [comment]
Any update folks?

**Comment by mikedld** [comment]
Closed by #757, pending release 3.00. This should've been linked and updated earlier, sorry.

**Comment by mikedld** [comment]
If there're some outstanding issues in current nightlies, feel free to create a separate issue.

**Comment by alanhogan** [comment]
For those eagerly awaiting this: Just download and install the latest mac build here https://build.transmissionbt.com/view/all/job/trunk-mac/lastBuild/

Note that you may need to adjust your security settings and/or right-click → Open this app to get it to run, as it is an unsigned executable.

**Comment by MartinZubek** [comment]
Hi guys, is there any time schedule on releasing a new stable version with dark-mode included?
The wait for this feature feels like eternity.

**Comment by jasonefmonk** [comment]
macOS 10.15 (Catalina) will support automatic (sunrise-sunset) or scheduled light/dark changes. I would also like to see this feature in a release.

**Comment by jdlien** [comment]
I just tried the unsigned version that has been recompiled with a later version of XCode. It looks beautiful in dark mode on Mojave. It would be very very nice to have an update just for this feature alone.

**Comment by MartinZubek** [comment]
It would be really nice, but to be honest I have already abandoned any hopes that we will ever get hands on new release with dark mode support. It's been almost year and half since last release and nothing suggests that there is any plan to get new release any soon. It's a sad story.

**Comment by v7rzlhb3xg** [comment]
So when's dark mode gonna make it to release?

**Comment by ourcore** [comment]
Running @williamluke's signed build for now. It's nice because it supports the system-level dark mode and it only prompts for access on the first run, but the white and blue in the progress bars still stand out too much (too bright) for a dark mode design.

**Comment by ldexterldesign** [comment]
This issue should be reopened, the OP isn't solved

Regards
