### ISSUE TITLE
Transmission 4.0.5 ignores alternative speed limits setting during startup

### ISSUE THREAD

**Issue by su1736** [transmission/transmission#6449]
### What is the issue?

I have Transmission 4.0.5-26 on Synology NAS (OS version is 7.1.1).

Seems like Transmission during its start ignores alternate speed limit setting ( "alt-speed-enabled") in settings.json.
(transmission user has all permissions on settings.json)

If I connect to Transmission through its web-interface or Transmission Remote GUI on Windows, I see the setting "use limit" unchecked. I set it check and this setting starting to work at runtime. But after restarting Transmission service, it became unchecked again and speed limit doesn't work. But in settings.json this setting ("alt-speed-enabled") is always in "true"!
It also doesn't change to "false" if uncheck "use limit" box in control interface and restart the Transmission service.

Looks like Transmission just ignores read and set "alt-speed-enabled" in settings.json.

web-interface on 9091 port:
![image](https://github.com/transmission/transmission/assets/3241647/5879fdf3-e9cc-4079-99ea-d2baf742e092)

Transmission Remote GUI client on Windows:
![image](https://github.com/transmission/transmission/assets/3241647/27cc7285-a532-4399-b22e-3762f73a8ef8)

settings.json in Transmission working directory /volume1/@appdata/transmission
![image](https://github.com/transmission/transmission/assets/3241647/deb02616-5dcf-436b-b60d-7570d0c1acc4)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment]
Thanks for reporting. A bit surprised this wasn't caught until now.
