### ISSUE TITLE
Transmission-daemon crashes

### ISSUE THREAD

**Issue by dyd0u** [transmission/transmission#645]
Hi,
I installed transmission-daemon on my VPS (Debian Jessie) a few years ago, and I have been very satisfied with it. However, a few months ago, it suddenly stopped working.

When I try to start the service, it stops ~10s later, and then starts again.
I tried to run it directly from the command-line, the daemon starts, and stops ~10s later too.
I also tried to reinstall it, but it didn't solve the problem. I've tried both `2.84` and `2.92`.
I tried to run it with a completly new config folder, it doesn't work either.
There is no information about the crash in the log file (see below, crash at 21:49:42).
I don't want to reinstall the VPS, because there are other important things installed on it.

The only change I noticed when it started crashing is an update of curl and libcurl3 packages. Before the crashes, I was running `7.38.0-4+deb8u8` and Transmission has been buggy since version `7.38.0-4+deb8u9`.
I have a friend that saw his transmission-daemon starting to crash approximately at the same time as mine, and he seems to have installed this update too, so maybe this update is in cause.

I've been trying to fix this for months now, I tried everything, but I can't fix it by myself, so I'm asking for your help.

Thanks.

> [2018-06-18 21:49:40.726 CEST] Transmission 2.84 (14307) started (session.c:738)
> [2018-06-18 21:49:40.726 CEST] Couldn't read "/home/seedbox/.config/transmission-daemon/stats.json": No such file or directory (utils.c:233)
> [2018-06-18 21:49:40.726 CEST] Couldn't read "/home/seedbox/.config/transmission-daemon/stats.benc": No such file or directory (utils.c:233)
> [2018-06-18 21:49:40.726 CEST] Cache Maximum cache size set to 4.00 MiB (256 blocks) (cache.c:261)
> [2018-06-18 21:49:40.726 CEST] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:881)
> [2018-06-18 21:49:40.726 CEST] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/ (rpc-server.c:1132)
> [2018-06-18 21:49:40.726 CEST] RPC Server Whitelist enabled (rpc-server.c:1136)
> [2018-06-18 21:49:40.726 CEST] Bound socket 16 to port 51413 on 0.0.0.0 (net.c:379)
> [2018-06-18 21:49:40.726 CEST] Bound socket 17 to port 51413 on :: (net.c:379)
> [2018-06-18 21:49:40.726 CEST] Port Forwarding Stopped (port-forwarding.c:180)
> [2018-06-18 21:49:40.726 CEST] UDP Failed to set receive buffer: requested 4194304, got 266240 (tr-udp.c:78)
> [2018-06-18 21:49:40.726 CEST] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:83)
> [2018-06-18 21:49:40.726 CEST] UDP Failed to set send buffer: requested 1048576, got 266240 (tr-udp.c:89)
> [2018-06-18 21:49:40.726 CEST] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:94)
> [2018-06-18 21:49:40.726 CEST] Using settings from "/home/seedbox/.config/transmission-daemon" (daemon.c:557)
> [2018-06-18 21:49:40.726 CEST] Saved "/home/seedbox/.config/transmission-daemon/settings.json" (variant.c:1214)
> [2018-06-18 21:49:52.237 CEST] Transmission 2.84 (14307) started (session.c:738)
> [2018-06-18 21:49:52.237 CEST] Couldn't read "/home/seedbox/.config/transmission-daemon/stats.json": No such file or directory (utils.c:233)
> [2018-06-18 21:49:52.237 CEST] Couldn't read "/home/seedbox/.config/transmission-daemon/stats.benc": No such file or directory (utils.c:233)
> [2018-06-18 21:49:52.237 CEST] Cache Maximum cache size set to 4.00 MiB (256 blocks) (cache.c:261)
> [2018-06-18 21:49:52.237 CEST] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:881)
> [2018-06-18 21:49:52.237 CEST] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/ (rpc-server.c:1132)
> [2018-06-18 21:49:52.237 CEST] RPC Server Whitelist enabled (rpc-server.c:1136)
> [2018-06-18 21:49:52.237 CEST] Bound socket 16 to port 51413 on 0.0.0.0 (net.c:379)
> [2018-06-18 21:49:52.237 CEST] Bound socket 17 to port 51413 on :: (net.c:379)
> [2018-06-18 21:49:52.237 CEST] Port Forwarding Stopped (port-forwarding.c:180)
> [2018-06-18 21:49:52.237 CEST] UDP Failed to set receive buffer: requested 4194304, got 266240 (tr-udp.c:78)
> [2018-06-18 21:49:52.237 CEST] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:83)
> [2018-06-18 21:49:52.237 CEST] UDP Failed to set send buffer: requested 1048576, got 266240 (tr-udp.c:89)
> [2018-06-18 21:49:52.237 CEST] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:94)
> [2018-06-18 21:49:52.237 CEST] Using settings from "/home/seedbox/.config/transmission-daemon" (daemon.c:557)
> [2018-06-18 21:49:52.237 CEST] Saved "/home/seedbox/.config/transmission-daemon/settings.json" (variant.c:1214)

**Comment by sergey-s-betke** [comment]
Transmission crashed when `preallocation` is set to non-zero. Disable `preallocation` (set to zero)...

**Comment by dyd0u** [comment]
I finally reinstalled Transmission on a new system, thanks.
