### ISSUE TITLE
Pull request creation failed. Validation failed: must be a collaborator [https://github.com/transmission/miniupnp]

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#6458]
### What is the issue?

Like most Transmission dependencies, our forks are not open to pull requests. :/
Can I either be collaborator for all forks (including in particular https://github.com/transmission/miniupnp), or can we open them for pull requests to non-collaborators?

Thanks

### Which application of Transmission?

None

**Comment by ckerr** [comment]
Invite sent.
