### ISSUE TITLE
configure: error: Your intltool is too old.  You need intltool 0.35.0 or later.

### ISSUE THREAD

**Issue by ky0ncheng** [transmission/transmission#647]
https://trac.transmissionbt.com/ticket/4744
It doesn't work.

I try
```
./autogen.sh
intltoolize
./configure
make
```

then

```
checking for xfs/xfs.h... no
checking for SYSTEMD_DAEMON... no
checking for clock_gettime in -lrt... yes
checking µTP... yes
checking system miniupnpc library... none
checking whether NLS is requested... yes
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/local/bin/intltool-update line 986.
checking for intltool >= 0.35.0...  found
configure: error: Your intltool is too old.  You need intltool 0.35.0 or later.
➜  transmission-2.94
```

```
apt install intltool -y
transmission-2.94 apt-get install intltool
Reading package lists... Done
Building dependency tree
Reading state information... Done
intltool is already the newest version (0.51.0-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

intltool has been updated.

**Comment by ky0ncheng** [comment]
edit configure.ac to delete about intltool version

**Comment by barzan-hayati** [comment]
`sudo apt-get install intltool`

**Comment by yangchengjun** [comment]
I find ：Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?([A-Z_]+)}?(.*)$/ at /usr/local/bin/intltool-update line 1065.
if we use Perl 5.26 or later, should edit the "SubstituteVariable" in /usr/local/bin/intltool-update line 1065:
`sub SubstituteVariable
{
    my ($str) = @_;

    # always need to rewind file whenever it has been accessed
    seek (CONF, 0, 0);

    # cache each variable. varhash is global to we can add
    # variables elsewhere.
    while (<CONF>)
    {
        if (/^(\w+)=(.*)$/)
        {
            ($varhash{$1} = $2) =~ s/^["'](.*)["']$/$1/;
        }
    }

    if ($str =~ /^(.*)\$\{([A-Z_]+)}?(.*)$/)
    {
        my $rest = $3;
        my $untouched = $1;
        my $sub = "";
        # Ignore recursive definitions of variables
        $sub = $varhash{$2} if defined $varhash{$2} and $varhash{$2} !~ /\$\{$2\}/;

        return SubstituteVariable ("$untouched$sub$rest");
    }

    # We're using Perl backticks ` and "echo -n" here in order to
    # expand any shell escapes (such as backticks themselves) in every variable
    return echo_n ($str);
}`

**Comment by yangchengjun** [comment]
I find ：Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.)${ <-- HERE ?([A-Z_]+)}?(.)$/ at /usr/local/bin/intltool-update line 1065.
if we use Perl 5.26 or later, should edit the "SubstituteVariable" in /usr/local/bin/intltool-update line 1065:
`
sub SubstituteVariable
{
    my ($str) = @_;

    # always need to rewind file whenever it has been accessed
    seek (CONF, 0, 0);

    # cache each variable. varhash is global to we can add
    # variables elsewhere.
    while (<CONF>)
    {
        if (/^(\w+)=(.*)$/)
        {
            ($varhash{$1} = $2) =~ s/^["'](.*)["']$/$1/;
        }
    }

    if ($str =~ /^(.*)\$\{([A-Z_]+)}?(.*)$/)
    {
        my $rest = $3;
        my $untouched = $1;
        my $sub = "";
        # Ignore recursive definitions of variables
        $sub = $varhash{$2} if defined $varhash{$2} and $varhash{$2} !~ /\$\{$2\}/;

        return SubstituteVariable ("$untouched$sub$rest");
    }

    # We're using Perl backticks ` and "echo -n" here in order to
    # expand any shell escapes (such as backticks themselves) in every variable
    return echo_n ($str);
}

`

**Comment by yangchengjun** [comment]
I encountered the same issue, with the following error: 
```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.)${ <-- HERE ?([A-Z_]+)}?(.)$/ at /usr/local/bin/intltool-update line 1065.
```
This error is due to stricter regex requirements in Perl 5.26 and later versions. We need to find and modify line 1065 in the SubstituteVariable function in the /usr/local/bin/intltool-update file to the following code:
````
sub SubstituteVariable
{
    my ($str) = @_;

    # always need to rewind file whenever it has been accessed
    seek (CONF, 0, 0);

    # cache each variable. varhash is global to we can add
    # variables elsewhere.
    while (<CONF>)
    {
        if (/^(\w+)=(.*)$/)
        {
            ($varhash{$1} = $2) =~ s/^["'](.*)["']$/$1/;
        }
    }

    if ($str =~ /^(.*)\$\{([A-Z_]+)}?(.*)$/)
    {
        my $rest = $3;
        my $untouched = $1;
        my $sub = "";
        # Ignore recursive definitions of variables
        $sub = $varhash{$2} if defined $varhash{$2} and $varhash{$2} !~ /\$\{$2\}/;

        return SubstituteVariable ("$untouched$sub$rest");
    }

    # We're using Perl backticks ` and "echo -n" here in order to
    # expand any shell escapes (such as backticks themselves) in every variable
    return echo_n ($str);
}
```
