### ISSUE TITLE
Chinease language codes are incorrect

### ISSUE THREAD

**Issue by stokito** [transmission/transmission#6474]
### What is the issue?

The zh_CN should be renamed to zh_Hans (e.g. Han Simplified).
Same the zh_HK and zh_TW should be renamed to zh_Hant (e.g. Han Traditional).

The zh_HK has less translations than the zh_TW so yoiu can simply remove it.

Here is a short description what are correct lang codes:
https://mzikmund.dev/blog/supporting-chinese-localization-in-uwp-apps

Related to #6284

### Which application of Transmission?

None

**Comment by mikedld** [comment]
Your link is pointing to an article about UWP (so, Windows) while you seem to be talking about files inside the "po" subdirectory (used by GTK client for which we don't provide Windows builds). Moreover, it's not even about the platform but the library/toolkit that handles those files. Do you have any gettext-related articles that prove your point? Do you have an example of a *NIX system that names .po files the way you suggest?

**Comment by Yohmi** [comment]
zh_HK and zh_TW aren't culturally neutral and aren't supposed to be. 
zh_Hans and zh_Hant are culturally neutral, so they wouldn't describe the vocabulary used, while you can be sure that Taiwanese mandarin and Hongkongese cantonese not only vary in pronunciation.

**Comment by Coeur** [comment]
I believe that @stokito is referring to the Mac client, because otherwise they wouldn't have participated to #6284.

So, specifically for Mac, on Transmission 4.1.0-dev nightly builds, here is what we support **natively**:
<img width="375" alt="Capture d’écran 2024-01-01 à 17 23 45" src="https://github.com/transmission/transmission/assets/839992/2628f54b-b5d8-4f69-ad02-8577e017c48d">

And if I explicitly set the app in "Chinese (China mainland)", I see:
<img width="654" alt="Capture d’écran 2024-01-01 à 17 25 56" src="https://github.com/transmission/transmission/assets/839992/4221eea2-7d4d-456d-8351-79a645f60f0e">

And if I explicitly set the app in "Chinese, Simplified", I see the same thing!

So kindly try the Transmission nightly build and tell us if it works or not:
https://build.transmissionbt.com/job/trunk-mac/

**Comment by mikedld** [comment]
My interest isn't in theoretical correctness, rather practical applicability. Could you answer the two posed questions?

**Comment by Coeur** [comment]
I think I agree with @Yohmi on cultural neutrality (aka adopting Hans/Hant instead of CN/TW).
Just in practice, I believe that both setups give presently the same results, according to my quick tests on macOS Sonoma 14.3.

**Comment by mikedld** [comment]
My impression is that this issue is initially about "po" files, so has nothing to do with Mac. Let's wait for OP's response and not mix things up.

**Comment by stokito** [comment]
> Your link is pointing to an article about UWP

The article is about a correct lang codes. Just a shortest one that I quickly googled.

The Chinease has two written form Traditional and Simplified. And they are officially used in many countries. But prononciation differs (e.g. Cantonese, Mandarin etc.).
![Chinease language usage](https://github.com/transmission/transmission/assets/415502/eb51c00e-f6e1-4068-9103-2a68a0efd51d)

You can use a Bing Translator to check Cantonese https://www.bing.com/translator

The both zh_TW.po and zh_HK.po are recognized as Traditional. The zh_TW.po is more complete and newer so you can drop the zh_HK.po

The issue is applied to all clients were the po files are used e.g. macOS or GTK.

**Comment by mikedld** [comment]
> The issue is applied to all clients were the po files are used e.g. macOS or GTK.

Only GTK client uses .po files (which we don't officially support on Mac, let alone Windows). Moreover, even if built for Mac, gettext/libintl there will canonicalize zh-Hans and zh-Hant into zh_CN and zh_TW, and won't do such thing on e.g. Linux, meaning it expects to find specifically the latter forms, not the former ones. Proof is in [gnulib](https://github.com/coreutils/gnulib/blob/5b92dd0a45c8d27f13a21076b57095ea5e220870/lib/localename.c#L1364-L1367) sources:

```c
    /* Mac OS X has "zh-Hans", "zh-Hant".
       Country codes are used to distinguish these on Unix.  */
    { "zh-Hans", "zh_CN" },
    { "zh-Hant", "zh_TW" }
```

Still waiting for answers to the two questions.

**Comment by Artoria2e5** [comment]
The Chinese language codes are alright. In the sense that zh_CN means different things from zh_Hans, and zh_HK has distinct wording and syntax from zh_🌚.

**Comment by stokito** [comment]
Thank you for the clarification. I randomly checked translations from the zh_HK and zh_TW and they were same or translated similarly but just seems outdated.
But if zh_HK.po has own wording then for sure we should leave it as is.

Many projects that I saw switched from the zh_Hans and zh_Hant and that seems enough.
