### ISSUE TITLE
QT GUI is not showing some torrents.

### ISSUE THREAD

**Issue by lvella** [transmission/transmission#6482]
### What is the issue?

I tried using the QT interface to create a torrent file for a directory, and then added this new torrent. The torrent list was empty and it remained empty after adding it. I know the torrent was correctly added because after I closed the QT GUI and opened the GTK GUI, the torrent I created/added was there. I then quit the GTK GUI and opened the QT GUI again, but the torrent was still missing.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

dce0d37130ec6feb4af2f6791b4b87bd4fd44c29

**Comment by tearfur** [comment]
@ckerr Regression from 10d047005aabd8a96c7ff5d29ff76ca00a6ba8ff
