### ISSUE TITLE
typo in update-version-h.sh?

### ISSUE THREAD

**Issue by xukl** [transmission/transmission#6485]
https://github.com/transmission/transmission/blob/4cfd9f0c9e6ef17e55b31e66a61b289fb0a27284/update-version-h.sh#L50

This `{A..A}` should be `{A..Z}`, I think🤔

**Comment by Coeur** [comment]
Could have been an opportunity for an easy pull request. :D
Thank you @xukl , I proposed the change in https://github.com/transmission/transmission/pull/6486
