### ISSUE TITLE
[Windows daemon 2.94 x64] settings.json garbled

### ISSUE THREAD

**Issue by Tharn** [transmission/transmission#650]
Got an unusual one for you here:

Earlier today, I ran into some hardware trouble. A cable came loose, and as I troubleshooted the problem, I turned the PSU off rather than shutting down Windows. Later, I booted Windows and once again turned the PSU off before the OS loaded fully.

Then later, once I had the hardware stuff sorted out, I noticed that transmission-daemon would not start anymore. It gave me 1053 errors, 'can't start in a timely fashion' after a milisecond of trying to load. It took me a while to hunt down the problem: The settings.json file had been overwritten by a paragraph of garbled `NUL` data.

I don't know how feasible it is, but it would be nice if Transmission wasn't able to brick itself after power loss during a particularly bad time in its startup. Out of the whole OS, this seems to be the only file where it happened.

**Comment by kevin01523** [comment]
i think it got corrupted so you should reinstall it or rather do an windows inplace upgrade then reinstall your transmission

**Comment by Tharn** [comment]
I had a backup, so fixing the file was easy.

Also it's possible that a loose cable contributed to this whole mess, so unless the dev says that Transmission is capable of garbling its own settings file when it initializes, I think now that it's safer to assume it was hardware.
