### ISSUE TITLE
FindDHT doesn't find OpenDHT

### ISSUE THREAD

**Issue by eyalroz** [transmission/transmission#6509]
### What is the issue?

The find module for the DHT library looks for a file named `dht.h` - but it requires that file to be present within as `dht/dht.h`. In OpenDHT, which is the DHT library available on Debian and I assume is what you're looking for, we find: `opendht/dht.h`.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment]
We bundle libdht as a git submodule, our release tarball has it too. Please refer to our build instructions at the bottom of the README for details.
