### ISSUE TITLE
Make the green (and gray) progress bars more muted

### ISSUE THREAD

**Issue by eyalroz** [transmission/transmission#6511]
### What is the issue?

I like the color choice of the progress bar for ongoing torrents in the transmission-gtk UI. However, coming from v3.0.0, I noticed completed torrents now have a very _strong_ full green progress bar. It's too strong! Please make it more muted/faded. I've attached an example with something like -15 saturation and +15 lightness.
![suggestion](https://github.com/transmission/transmission/assets/8672255/25df1750-6dda-499c-964f-0e1930e8c484)
at the top is the existing green bar, at the bottom is a possible choice of different hue of green.

About the same point I would make for the strong gray bar of faulty torrents

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5

**Comment by mikedld** [comment]
Work done by @GaryElshaw in #5648, I'll close this in favor of that other ticket, feel free to comment there.
