### ISSUE TITLE
Transmission 4.0.5 does not open on Mac OS 14.2.1 Sonoma

### ISSUE THREAD

**Issue by julianirwin** [transmission/transmission#6522]
### What is the issue?

I recently upgraded to Sonoma 14.2.1. I noticed Transmission was no longer working so I downloaded the 4.0.5 version from Github thinking an update would solve the problem. This version also does not work. I unpack the dmg, drag the .app to my Applications folder, and then run the app. The icon appears in my dock but no Transmission window appears. I also tried nightly build #9498 from January 12th with no success.

I did just successfully (I think) build Transmission from the latest source locally and got the same problem. If someone can tell me how to enable some sort of debugging output when I build, I could try that to be able to provide more information about what is hanging/crashing.

<img width="338" alt="image" src="https://github.com/transmission/transmission/assets/10728285/e5dbb773-8dc2-4551-970d-c401f5cdcb1d">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5

**Comment by nevack** [comment]
Please see https://github.com/transmission/transmission/issues/6359

**Comment by Coeur** [comment]
The report from @julianirwin : https://github.com/transmission/transmission/files/13923360/Transmission.Hang.Report.txt

**Comment by Coeur** [comment]
I'm also seeing:
>Dispatch Thread Soft Limit Reached:   64  (too many dispatch threads blocked in synchronous operations)

And also 198 threads named `DispatchQueue "updateTimeMachineExclude"` when normally there should be only few of them. So that hints to a lock caused by too many calls to:
https://github.com/transmission/transmission/blob/1de6e93fec61b88c9422d4fdc011b7ae2dc59130/macosx/Torrent.mm#L1829

**Comment by Coeur** [comment]
I shouldn't have done a git blame... well, so the regression was caused by #4208

**Comment by Coeur** [comment]
@julianirwin please try my fix attempt at #6523. You can either get it from my fork, or manually apply the 7 modified lines. Thanks.
For others who want to try the fix without building from source, you may attempt the instructions from https://github.com/transmission/transmission/blob/main/docs/Testing-Transmission.md

**Comment by julianirwin** [comment]
@Coeur I copied Torrent.mm from your PR into a clone of the latest origin/main, then rebuilt with cmake. Running Transmission.app from the build/ folder still hangs the system.

[Transmission Hang Report Coeur Fork Build.txt](https://github.com/transmission/transmission/files/13928572/Transmission.Hang.Report.Coeur.Fork.Build.txt)

**Comment by Coeur** [comment]
Thank you. There are 64 occurrences of CSBackupSetItemExcluded in your new logs. I'd try to make the thread SERIAL instead of PARALLEL.

**Comment by julianirwin** [comment]
Still hanging for me.

[Transmission hang report 3.txt](https://github.com/transmission/transmission/files/13939946/Transmission.hang.report.3.txt)

**Comment by mikedld** [comment]
@julianirwin, I'm not sure how this is possible. Could you double-check that new changes are in place? Maybe do a clean build?

**Comment by julianirwin** [comment]
@mikedld Apologies, I was trying to use the "play" button in xcode to build. It said "build succeeded" but I don't think it was actually rebuilding. I'm not an xcode user so I probably did something wrong.

Anyways, I just rebuilt on the command line with cmake and no hang! Transmision opened!

**Comment by nevack** [comment]
Cmake build can be different from Xcode build in options to compile used AFAIK

**Comment by Coeur** [comment]
The third logs can't be coming from the latest version of the code, in my opinion, because it shows parallel executions of what is marked in code to run serially. Glad that the cmake rebuild fixed the issue.
