### ISSUE TITLE
Transmission 4.0.x breaks complete download handling in Sonarr

### ISSUE THREAD

**Issue by bbsixzz** [transmission/transmission#6528]
### What is the issue?

I've tested everything with linuxserver/transmission docker images.

Sonarr removes torrent from Transmission 3.0 once seeding finishes after 1 minute (settings for demonstrative purposes).

![1](https://github.com/transmission/transmission/assets/47334163/6be5f1f8-4d39-4bfe-be23-94051bc9a374)
![Screenshot 2024-01-14 at 20 47 24](https://github.com/transmission/transmission/assets/47334163/a5ff8606-79c5-458e-bc24-0b1e4d431135)

**With Transmission 4.0.0 torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 49 53](https://github.com/transmission/transmission/assets/47334163/e15ba5d5-db94-4d1b-98e2-4668d5b98d1f)

**With Transmission 4.0.1 torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 51 09](https://github.com/transmission/transmission/assets/47334163/a0fb8066-5320-4663-a7fa-abafa2d0e50f)

**With Transmission 4.0.2 and forward torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 51 47](https://github.com/transmission/transmission/assets/47334163/ab239b29-fa97-4dfe-81d1-d493d02c66b8)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.x

**Comment by bbsixzz** [comment]
These options were disabled in all versions of Transmission while testing.

![Screenshot 2024-01-14 at 20 59 28](https://github.com/transmission/transmission/assets/47334163/c36e8e14-856d-49d8-be7c-1b51dd57ca37)

**Comment by bbsixzz** [comment]
You should spend more time reading and less time attacking and being rude, it's not a good look; I clearly stated "settings for demonstrative purposes".

If I set seed time to 8 weeks the torrent will behave the same, this is a quick way to test the issue.

Transmission 3 clearly works and respects Sonarr Seed time and removes the torrent after the set time passes.

Transmission 4 does not.

**Comment by bakerboy448** [comment]
Transmission should not be removing anything.

sonarr tells transmission to remove the torrent once the goals are met

**Comment by bbsixzz** [comment]
Well it does, and your feedback is worthless.

**Comment by bakerboy448** [comment]
So you believe transmission - not sonarr - removes the clients? The  why open any bug up with sonarr's

Also you're 100% wrong and don't understand how sonarr works.

https://wiki.servarr.com/sonarr/quick-start-guide#download-clients
> If the "Completed Download Handling - Remove" option is enabled in Sonarr's settings, Sonarr will delete the torrent from your client and ask the client to remove the torrent data, but only if the client reports that seeding is complete and torrent is stopped (paused on completion).

Sonarr logic for whether to remove or not: it would seem a breaking v4 transmission change occurred so this no longer functions.
 
https://github.com/Sonarr/Sonarr/blob/0685896ed8263ef6d05a933acaf584e6f4aa9f92/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L131-L169

Sonarr method to tell transmission to remove it:

https://github.com/Sonarr/Sonarr/blob/0685896ed8263ef6d05a933acaf584e6f4aa9f92/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs#L125

**Comment by bbsixzz** [comment]
> it would seem a breaking v4 transmission change occurred so this no longer functions.

I agree, thanks for the constructive feedback.

I can't provide any logs as I'm away for a while, but hopefully someone else can look into this issue now that it's been identified.

Cheers

**Comment by carlflash** [comment]
I'm also having this problem ever since updating to Transmission 4, please have a look at this @ckerr

**Comment by bbsixzz** [comment]
I received this reply from Sonarr dev:

> I've also verified the behaviour with just a time limit and Transmission appears to be retting `secondsSeeding` when stopping seeding (either when manually stopped or automatically stopped when reaching it's idle timeout), which means for torrents that aren't actively seeding it's going to be very difficult for Sonarr to check that it's finished seeding and get it removed (and impossible with a seed time of 1 minute for testing).
> 
> According to https://github.com/transmission/transmission/blob/340d0d496639364524642917cefe07f402459962/libtransmission/transmission.h#L1529-L1530 (which is where the API docs point you to), this value should not reset when stopped. If this is an intentional change on the Transmission side we might be able to handle the scenario better, but for now we're leaving it as-is.

Can you please fix the value to not reset?

**Comment by carlflash** [comment]
Can we please have some clarification of the intent @ckerr?

Sonarr team is apparently not making any changes yet because they're unsure if it's a regression waiting to be fixed or actual intended change in Transmission.

**Comment by yeejonathan** [comment]
Coming across this issue as well. Based on what I've read it looks like Sonarr will not be making any changes until we get clarification on the intent of the resetting behavior in Transmission to avoid further confusion. Can anyone clarify the intent?

**Comment by tearfur** [comment]
I agree that this is a regression, and put up a fix at #6844.

Let's see if it gets accepted.
