### ISSUE TITLE
Bump lbpsl to 0.21.5

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#6529]
### What is the issue?

Released a couple days back https://github.com/rockdaboot/libpsl/releases/tag/0.21.5

### Which application of Transmission?

All

### Which version of Transmission?

All

**Comment by Pentaphon** [comment]
@ckerr have you considered using something like https://github.com/marketplace/renovate to keep up with all these dependencies for the project? This kind of automation will make life easier for everybody involved.
