### ISSUE TITLE
Web Interface does not load, times out.

### ISSUE THREAD

**Issue by Infallibleman** [transmission/transmission#6531]
### What is the issue?

When I click on "Launch Web Interface", it opens up the browser to http://localhost:9091 but it times out after a while. Used to work.  not working anymore.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5 stable as well as the latest nightly

**Comment by nevack** [comment]
What web browser and its version?
Are there any messages in browser's console log?

**Comment by killemov** [comment]
Check settings.json for `"rpc-port": 9091,`. macFirewall acting up?

**Comment by tearfur** [comment]
Closing as stale.
