### ISSUE TITLE
Always zero entries in my blocklist

### ISSUE THREAD

**Issue by binarykitchen** [transmission/transmission#6532]
### What is the issue?

Short: under Settings > Privacy > Blocklist always shows "Blocklist has 0 entries"

Screenshot:
![zero](https://github.com/transmission/transmission/assets/177641/17ca3b34-b562-47a4-9336-0a2580d8dcfe)

I've purchased it from I-BlockList, chose the `cidr` and uncompressed format, see second screenshot:
![list](https://github.com/transmission/transmission/assets/177641/457c9990-979f-4026-96e3-9b7588504ba3)

Happy to share the private link over a secure channel. But here is the link to the full blocklist, hosted on S3:
http://s3.amazonaws.com/hn62xeffkz4xd8g3qnq8/files/8nyb624es6rbfqro0x1e/njynbykqzurmkfbpwqtf.txt

No denying it's large and has numerous entries, not zero.

I'm on latest Ubuntu and here is the snapshot from the "About" window with the version number which is 4.0.2:
![image](https://github.com/transmission/transmission/assets/177641/4caa4fcd-ffd9-4d9d-8923-5099f27cae12)

Support from support@iblocklist.com believes it's not a bug on their side; therefore I'm raising it here.

Any advice? How can I, from a fellow developer to another developer, help find out what the problem is, whether it's a bug or something else?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2

**Comment by GaryElshaw** [comment]
Have you tried a .gz option?

**Comment by binarykitchen** [comment]
Yes, the gz option didn't help either.

**Comment by GaryElshaw** [comment]
In the interim, until someone else can help, this will work: https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz

**Comment by tearfur** [comment]
@binarykitchen I got "Access denied" when trying your S3 link, maybe you can upload it here as an attachment.

**Comment by binarykitchen** [comment]
@tearfur They banned me because I've published it here for reproduction :(
