### ISSUE TITLE
Performance regression from `3.00` to `4.x` when generating pieces to request

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6535]
### What is the issue?

This issue is about optimising the process of calcuating the list of pieces to be sent out in a BT request message to other peers, and it is next on my to-do list.

In `3.00`, when downloading torrents, Transmission has a cache (namely `tr_swarm::pieces`) storing the list of pieces that

1. are part of a file that is selected for download, and
2. we don't have a complete copy of.

This is a sensible optimisation. Without it, calculating if a piece satisfies these conditions requires sifting through 2 bitfields, and that is expensive. OTOH, these 2 conditions don't change very often, so a caching the results has a large benefit.

However, this optimisation was dropped in 073c6af1d6b5eae29010654150ee269108da719e when converting the code to C++, and this produces flame graphs like this, where `tr_peerMgrGetNextRequests()` is taking up up to half of the CPU time:

![flame-4-deb-btf](https://github.com/transmission/transmission/assets/46261767/a5fcdb8e-07e4-42a3-8f57-2796cbfea03d)

Compared with a `3.00` flamegraph, the difference is very obvious:

![flame-3-deb](https://github.com/transmission/transmission/assets/46261767/ceb03d9e-d9f5-4a8b-b2d8-86a706be410a)

I'm already working to add back this optimisation, just writing this issue here for the record. If anyone have any ideas for new optimisations, please also raise them here.

### Which application of Transmission?

None

### Which version of Transmission?

0ce4adf07ce4b6cfabf81e2d027f96197bb9a305

**Comment by tearfur** [comment]
CC @ckerr

**Comment by killemov** [comment]
> * are wanted by us, and
> 
> * we don't have a complete copy of.

Logically these are the same, but I believe there is a difference in timing and one is a subset of another. So "don't have" is a fact and "want" is based on a decision and the subset of the former. I'm missing something about the rarity of a piece here.

> requires sifting through 2 bit-fields, and that is expensive.

Bit-fields are storage savers so the tradeoff here is MEM vs CPU. My guess is that these bit-fields are used to find the next candidate piece(s) to request so `candidate = dont_have and not wanted`. [Shift](https://github.com/killemov/Shift) uses the `pieces` bit-field in the RPC for display purposes and now I'm wandering how expensive that might be.

My advice would be to only keep the "don't have" bit-field and lose the "wanted" bit-field in favor of the cached list with a configurable maximum size. So determine the next set of pieces from "don't have", "not cached", "rarity" and/or "sequential" to be cached and requested.

**Comment by killemov** [comment]
Ah, of course, but that only changes the algorithm to: determine the next set of pieces from "don't have", "part_of_file wanted", "not cached", "rarity" and/or "sequential" to be cached and requested.

**Comment by andreygursky** [comment]
> don't change very often, so a caching the results has a large benefit.

Perhaps, prioritizing of rarest pieces requests (removed by #2021, requested again by https://github.com/transmission/transmission/discussions/6084#discussioncomment-7406480) could be brought back by caching.

**Comment by killemov** [comment]
Concerning #2021: Weird that priority of rarity of pieces was removed as it is one of the base principles of the Bittorrent protocol. Does this have anything to do with sequential downloading? If the number of seeders are high enough this should not be a problem though. So switching to the rarity strategy below X (=16?) seeders should comprise the best of both worlds.

**Comment by tearfur** [comment]
I'm wondering why rarest pieces was remove too.

In any case, AFAICT this has nothing to do with caching or sequential download. They can be implemented individually without affecting each other.

**Comment by killemov** [comment]
To be clear, not caching vs sequential, but rarity vs sequential are conflicting strategies. But when there are enough seeders it doesn't really matter much.

**Comment by Pentaphon** [comment]
This is the kind of stuff I was expecting people to find in https://github.com/transmission/transmission/issues/5261. Nice work, tearfur. I suspect this is not the only one you will find. 

My question is: how did this get "lost in translation" during the refactor?

**Comment by reardonia** [comment]
Just wanted to thank you @tearfur for this deep analysis and rewrite. the swarm cache was among the thorniest parts of Tr3 and glad to see it back.
