### ISSUE TITLE
Blinking connection to a peer

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#6539]
### What is the issue?

See the screen recording, it keeps connecting and disconnecting to a peer. It has been like that for minutes/hours?

https://github.com/transmission/transmission/assets/839992/29e8e74b-ae0d-4906-b167-596592541c29

The peer is identified as being on Transmission 2.21 (why do people stay on so old versions?)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (0ce4adf07c)

**Comment by GaryElshaw** [comment]
I'm still seeing this too #5816
