### ISSUE TITLE
Pressing Enter does not submit add torrents form in transmission 4

### ISSUE THREAD

**Issue by Huy-Ngo** [transmission/transmission#6553]
### What is the issue?

After updating transmission to version 4, I can no longer use Enter key to submit the add torrents popup form by pressing enter like I could with version 3. Because I often use keyboard to input magnet url and subpath for categorizing downloads, having to switch to mouse adds friction to the workflow.

### Which application of Transmission?

Web client

### Which version of Transmission?

Transmission 4.0.5 (a6fe2a64aa)

**Comment by bheesham** [comment]
Submitted a fix for this. I feel like it's a bit of a hack though.

In the mean time, you should be able to get away with pressing `TAB` a couple more times. A little annoying, but hey, It Works :tm:.

**Comment by Huy-Ngo** [comment]
Thanks

**Comment by Huy-Ngo** [comment]
>I feel like it's a bit of a hack though

FWIW, I think setting it as form is a perfectly valid and semantic way to do it
