### ISSUE TITLE
Black border around the context menu

### ISSUE THREAD

**Issue by Petrprogs** [transmission/transmission#6555]
### What is the issue?

![img](https://github.com/transmission/transmission/assets/76732207/171b0bee-9c2e-43c5-8ee2-a96b48498345)

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5

**Comment by Pentaphon** [comment]
Which theme/distro do you see this on?

**Comment by Petrprogs** [comment]
> Which theme/distro do you see this on?

Debian 12 with Adwaita Dark

**Comment by mikedld** [comment]
To me it looks like you're using a theme that makes use of transparency for popup shadows, and you're not running a compositor to actually support it. If Transmission is the only program which exhibits this, it may still not be the one to blame here if e.g. all you other programs are using GTK 3 (and so one variant of the theme) and Transmission is using GTK 4 (and so another variant of the same theme).
