### ISSUE TITLE
transmission interface does not open

### ISSUE THREAD

**Issue by nonotrop** [transmission/transmission#6576]
### What is the issue?

# Francais : 
Bonjour, je viens vers vous pour vous dire que l'interface de transmission ne fonctionne plus. Quand je lance un téléchargement il ce lance bien mais je ne vois pas l'avancer de ce fichier.
je suis sous windows 10 x64 msi j'ai télécharger la bonne version. 
j'ai déja télécharger transmission sur mon pc avant et il marchait tres bien, mais j'ai du le desinstaller et le réinstaller pour une résons et de puis je ne vois plus l'interface.
j'aimerais avoir de l'aide 
merci a vous 
bonne soirée 
cordialement 

# Anglais : 
Hello, I come to you to tell you that the transmission interface no longer works. When I launch a download it launches fine but I do not see the progress of this file.
I am on Windows 10 x64 msi
I downloaded the correct version.
I already downloaded transmission on my PC before and it worked very well, but I had to uninstall it and reinstall it for a while and then I no longer see the interface.
I would like some help
thank you
Have a good evening
Sincerely
![Capture d’écran 2024-02-05 184044](https://github.com/transmission/transmission/assets/159057496/59d3d41e-e25b-4e6a-943c-3a0b6cbe8b90)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Windows 10 x64 msi

**Comment by Daniel6372** [comment]
Similar issues: #5341, #5982, #6033, #6266
