### ISSUE TITLE
"Last activity" field in web interface

### ISSUE THREAD

**Issue by klntsky** [transmission/transmission#658]
![preview](https://user-images.githubusercontent.com/18447310/42127068-b58b2110-7c9a-11e8-9d8e-2aa741c9d82d.png)

> Last Activity: 17712 days ago

Please change to something like "Never" for zero timestamps.

**Comment by Rafostar** [comment]
I made PR #1390 that should solve this.

**Comment by belovachap** [comment]
Is this issue still open? It reads like it might have been fixed during the "web client refresh": https://github.com/transmission/transmission/pull/1390#issuecomment-1038174420

**Comment by ckerr** [comment]
I think @belovachap is right; closing as fixed
