### ISSUE TITLE
transmission RPC and HTTP headears

### ISSUE THREAD

**Issue by janemba** [transmission/transmission#6582]
### What is the issue?

Hello,

Is it possible to transmit or add HTTP headers to transmission using RPC ?

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

1.6.0

**Comment by tearfur** [comment]
Hi, just so you know, you've raised this issue in Transmission's main repo. We don't have release version `1.6.0`.

Did you meant to create this issue for a third-party Transmission GUI?

**Comment by janemba** [comment]
My bad, yes `1.6.0` is my `transmission-remote-gtk` but my question is not related to it. It's more related to `transmission-remote` which use the following version `transmission-remote 3.00 (bb6b5a062e)`.

I'm using RPC protocol from transmission to add torrents. The `torrent-add` method allow adding a cookie so transmission can use that cookie to download a torrent.

Now, I would like to know if there is a way to also add an header with `torrent-add` method in case the cookie alone is not enough for transmission to download a torrent file.

**Comment by tearfur** [comment]
No, we don't have that at the moment.
