### ISSUE TITLE
BEP-7 compatible problem

### ISSUE THREAD

**Issue by kotori2** [transmission/transmission#659]
In parameters of BEP-7, there is a parameter named "ipv4" which will announce an IPv4 address to tracker if you access tracker by IPv6 network.

> In case the client contacts the tracker on an IPv6 interface, it may add an &ipv4= parameter with its IPv4 address or endpoint.

I checked "libtransmission/announcer-http.c", there is only ipv6 parameter, which will only announce one ipv6 address to tracker.

**Comment by ckerr** [comment]
Mooted by https://github.com/transmission/transmission/pull/4502
