### ISSUE TITLE
Question: Have distinct local and remote listening peer ports

### ISSUE THREAD

**Issue by loutr** [transmission/transmission#6593]
### What is the issue?

Hello,

My current setup has a transmission server behind a VPN with a port forwarding capability. The VPN remote port is typically provided at random at each new session. On the other hand, I can ask for a static local port (e.g. the default 51413). Keeping it that way would be handy, as it would prevent me from updating my server firewall every time (as opposed to the setup where both local and remote ports are identical).

Currently, if I'm correct, the "listening port" that can be provided in the settings corresponds to both ports. So, is there any way to tell transmission to listen locally on a given port, but announce the remote port as the listening port to the public? I couldn't find this information anywhere else. I apologise if this question is irrelevant and/or has already been asked.

Thanks a lot for your efforts in this project!

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4

**Comment by tearfur** [comment]
No, we don't have anything like that at the moment.

I'm not sure how we can go about adding something that will cater to your case. Having 2 separate options for listening port and announce port is not an option, since that's just a *really* convenient way for malicious actors to fill tractors with bogus peers.

**Comment by loutr** [comment]
I understand. I think scripting the opening of the correct ports in the firewall is the only good solution for now. Thanks!
