### ISSUE TITLE
Handle broken UTF-8

### ISSUE THREAD

**Issue by Anuskuss** [transmission/transmission#6595]
Characters in file names of torrents which contain invalid UTF-8 should be replaced with `0xEF 0xBF 0xBD` (`U+FFFD`, �).

I won't post the hash here but it's probably okay to post the filename for educational purposes:
```
4D 6F 6E 73 74 65 72 73 2E 42 61 6C 6C 2E D3 B5  Monsters.Ball...
B1 A7 D1 DE D1 F4 CC EC 2E D6 D0 CE C4 D7 D6 C4  ................
BB 2E 48 52 2D 48 44 54 56 2E 41 43 33 2E 39 36  ..HR-HDTV.AC3.96
30 58 35 32 38 2E 78 32 36 34 2D C8 CB C8 CB D3  0X528.x264-.....
B0 CA D3 D6 C6 D7 F7 2E 61 76 69                 ........avi
```

Or in it's corrected form:
```
Monsters.Ball.ӵ��������.������Ļ.HR-HDTV.AC3.960X528.x264-����Ӱ������.avi
```

Additionally, for this particular torrent, I can see (I don't really know how torrents store their data but just looking in an hex editor) that there's a `pathl75` with the broken name followed by a `path.utf-8l90` with the correct name:
```
Monsters.Ball.拥抱艳阳天.中文字幕.HR-HDTV.AC3.960X528.x264-人人影视制作.avi
```

I don't think this happens all too often but it's still concerning (it broke one of my scripts and could lead to crashes in applications which are not prepared for this).

**Comment by Coeur** [comment]
- Kindly specify which app (macOS, QT, GTK, ...).
- Kindly specify which version.
- Kindly try a nightly build (or to build from sources), which I believe already solves UTF8 issues.

**Comment by mikedld** [comment]
Although I think there're still some cases where libtransmission doesn't handle Unicode well internally (leading to e.g. #5914), a couple of related fixes have made it into 4.0.2, in particular #3454. So yeah, please confirm which version you're using.

**Comment by Anuskuss** [comment]
@Coeur I assumed it would be expected to be on the latest stable (v4.0.5) but you're right, I should've specified. Also assumed that it would affect the backend so I didn't clarify that I'm using `transmission-daemon`. My bad.

@mikedld I should've done more research because I'm pretty sure this is a duplicate of #3442 (the filename seems to be GB2312). I must've downloaded that torrent a long time ago (<= v3) and just noticed this now (after a script of mine broke). I don't think it makes sense to retroactively fix torrents/filenames so I guess I'll close this for now.

**Comment by Coeur** [comment]
> Also assumed that it would affect the backend so I didn't clarify that I'm using `transmission-daemon`.

Well, yes, maybe. Just the macOS app had an extra layer and was immune to invalid unicode a bit earlier (since #4144, Transmission 4.0.0).
