### ISSUE TITLE
Feature request: Labels

### ISSUE THREAD

**Issue by zsugabubus** [transmission/transmission#660]
As the number of torrents increase, the harder it is to find something and keep things organized. It would be a nice feature if I could assign one or more labels (maybe colors too) to torrents. Filtering by label could happen in another panel and/or in the search bar.

**Comment by yangjz1125** [comment]
It's a good idea.I like labels, too.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #79.
