### ISSUE TITLE
[Feature request] Transfer rate in Kbit/s option

### ISSUE THREAD

**Issue by cetinajero** [transmission/transmission#662]
It would be really appreciated an option to switch speed units between Bytes/s and Bits/s on network-related measures (not storage-related) a.k.a transfer rate.

Some users prefer bits/s because mostly all networks and Internet connections are also measured in bits/s, therefore it would be really helpful to see how saturated the Internet connection is... otherwise you have to recalculate Bytes/s back to Bits/s manually.

- Internet lines are sold in Mbits
- Network switches, routers, WiFi are all rated in Mbits
- Internet speed tests return Mbits

I know the storage units are Bytes by default and all hard drives / OS's / files are measured in Bytes and I can see why transmission is currently using Bytes.

Maybe the default should follows the OS (as currently) but offer an option to toggle the unit measure on network-related metrics to bits it would be helpful.

**Comment by mikedld** [comment]
See #198.

**Comment by cetinajero** [comment]
Hi @mikedld,

Issue #198 is about using the right [_Giga_ prefix measure](https://en.wikipedia.org/wiki/Metric_prefix) (i.e. using 1000 bytes or 1024 bytes as the base to calculate the size of a file).

This issue is a feature request to have an option to transform Bytes to Bits, this will be convenience to know how much bandwidth your current connections are taking up and I hardly think is a duplicate from #198.

As an example... with the current transmission we would get some thing like this:

![screen shot 2018-09-03 at 5 30 57 pm](https://user-images.githubusercontent.com/24572406/45003417-9e949a80-af9f-11e8-98b9-9d0a0930c976.png)

If someone has an Internet connection with 50Mbps/10Mbps (Downlink/Uplink) and wants to know how much bandwidth is consuming transmission... it would have to multiplicate the current value to bits (e.g. **1.44MBps** * 8 = **11.52Mbps**), thats why an option to toggle the unit measure on network-related metrics to bits it would be helpful.

**Comment by gingerbeardman** [comment]
I would also like to work in Kilobits rather than Kilobytes

**Comment by cetinajero** [comment]
Any comments on this @mikedld?

**Comment by ITwrx** [comment]
I think the default should be Mb, but I guess a setting might be nice if enough people, or devs, actually want anything other than Mb. I guess in the future we may need Gb? I have no idea why it is shown in K/MB. IDK what storage units have to do with the transfer rate.
