### ISSUE TITLE
Feature: Pass argument(s) in script-torrent-*-filename

### ISSUE THREAD

**Issue by defkev** [transmission/transmission#6627]
### What is the issue?

I am assuming the behavior outlined here:

https://forum.transmissionbt.com/viewtopic.php?t=15730

has not changed since 2014?

Note this is about commandline arguments ($1 in bash or sys.argv[0] in python) and NOT environment variables!

The idea is simply to reuse my script-torrent-done script in script-torrent-done-seeding instead of having to maintain two almost identical scripts, e.g.:

```json
{
  "script-torrent-done-enabled": true,
  "script-torrent-done-filename": "/path/to/my/superduper-script.sh",
  "script-torrent-done-seeding-enabled": true,
  "script-torrent-done-seeding-filename": "/path/to/my/superduper-script.sh foo"
}
```

and the imaginary superduper-script.sh
``` bash
if [ "$1" ]; then
  echo $1
else
  echo bar
fi
```

Which causes script-torrent-done-filename (bar) to run as per usual on completition and script-torrent-done-seeding-filename to not run at all after hitting the seed ratio.
Using a seperate script in script-torrent-done-seeding-filename (without an argument) works.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5 (a6fe2a64aa)

**Comment by killemov** [comment]
Yes, this could be useful. Also see [Script Variables](https://github.com/transmission/transmission/blob/main/docs/Scripts.md) where an additional TR_TORRENT_STATUS could be added.

**Comment by ILoveGoulash** [comment]
You could just use symlinks and inspect `$0`.

**Comment by killemov** [comment]
@ILoveGoulash That would be an elaborate option, but please elaborate.

**Comment by ILoveGoulash** [comment]
```
{
  "script-torrent-done-enabled": true,
  "script-torrent-done-filename": "/path/to/my/tr-script-done.sh",
  "script-torrent-done-seeding-enabled": true,
  "script-torrent-done-seeding-filename": "/path/to/my/tr-script-done-seeding.sh"
}
```
and
```
$ cd /path/to/my/
$ cat tr-script-impl.sh
case "${0##*/}" in
    tr-script-done.sh)               ... ;;
    tr-script-done-seeding.sh) ... ;;
esac
$ ln -s tr-script-impl.sh tr-script-done.sh
$ ln -s tr-script-impl.sh tr-script-done-seeding.sh
```
A bit like busybox's single binary dispatch thing.

**Comment by killemov** [comment]
Yup, that would work.

**Comment by tearfur** [comment]
Can't you just write a wrapper script for your superscript? There are multiple ways to get around this.

If we start allowing passing arguments to the scripts, then sooner or later we are going to find ourselves having deal with escaping, or get around quirks related to each shell's argument parsing mechanisms. I don't think it is a good idea for us to get ourselves into that mess.

**Comment by defkev** [comment]
I am currently using 2 almost identical scripts, hence the future request.
@ILoveGoulash's approach would certainly work but is complicated, especially for something this trivial.

If you are concerned about compatibility consider adding an additional environment variable [1] exposing what called the script, e.g.

* `TR_TORRENT_CALLER` - `done` or `done-seeding` etc...

Which would suit me as well.

[1] https://github.com/transmission/transmission/blob/main/docs/Scripts.md

**Comment by tearfur** [comment]
What I mean is, can't you just do something like this?

```bash
# script-torrent-done-filename.sh
. superduper-script.sh

# script-torrent-done-seeding-filename.sh
. superduper-script.sh foo
```

```json
{
  "script-torrent-done-enabled": true,
  "script-torrent-done-filename": "/path/to/my/script-torrent-done-filename.sh",
  "script-torrent-done-seeding-enabled": true,
  "script-torrent-done-seeding-filename": "/path/to/my/script-torrent-done-seeding-filename.sh"
}
```

**Comment by killemov** [comment]
@tearfur Sort of like symbolic linking, but in script form. If your filesystem supports it, that would be the cleaner option.

**Comment by tearfur** [comment]
Nothing like symbolic linking, just 3 scripts, 2 of which are one-liner wrapper scripts, the remaining one is the actual implementation.

**Comment by defkev** [comment]
I can absolutely follow:
3 scripts instead of 2 symlinks and 1 script
Still an overly complicated solution for a very simple problem...

If you don't want to add it that's fine by me, no hard feelings.
It was a suggestion, not an obligation.

Cheers
