### ISSUE TITLE
Multiple transfers with the same title fight for the same destination.

### ISSUE THREAD

**Issue by yarnichat** [transmission/transmission#663]
When two (or more) transfers are are downloading two files (or two folders) that happen to have the exact same name, they write in the same location, walking over each other's data. Transmission doesn't seem to know this conflict is happening.

For now, a workaround is to make a duplicate of the downloaded file, Move Data File To a separate location, and then Verify Local Data, for each transfer with the same title.

Transmission ought to recognize when two transfers are trying to download files with the same name, and make separate folders to contain them in.

Transmission 2.94 for Mac

**Comment by bittaurus** [comment]
I don't know of a torrent client that doesn't have this issue.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #649.

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/251
