### ISSUE TITLE
Broken web interface  after yesterday nightly build 

### ISSUE THREAD

**Issue by ase7en34** [transmission/transmission#6632]
### What is the issue?

Hello, 

yesterday I decided to build latest nightly build since I have issues when adding magnet torrents  - some times its suck on gathering sources and nothing happen until daemon restart. Yes, despite of 100+ seeders.

So if you can take a look at the attached file you will see broken UI 

Compiling did not produced any error at all. And I checked on 3 mostly common browsers - Firefox, Chrome and Microsoft Edge

![2024-02-20 16_16_24-Transmission Web Interface](https://github.com/transmission/transmission/assets/65528374/5dafc99e-479f-4b12-9f71-8bdeb7e0c944)

### Which application of Transmission?

Web client

### Which version of Transmission?

4.1.0 DEV

**Comment by nevack** [comment]
Are there any errors in DevTools console? Opens with F12 by default.

**Comment by ase7en34** [comment]
Yes, there are some errors but they are not meaningful for me :)

![2024-02-20 16_58_18-](https://github.com/transmission/transmission/assets/65528374/4a2e0744-7820-4692-a995-a8adc641e8ab)

**Comment by killemov** [comment]
@ase7en34 The 409 error is documented here: https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#231-csrf-protection

**Comment by tearfur** [comment]
It actually has been "broken" for a more than a month (since 61ed621f55f6b4c8f5414260159c18129f304899).

#6540 will fix this, but I have no idea why it has not been merged for a whole month. 🤓

**Comment by tearfur** [comment]
Finally fixed by #6857.
