### ISSUE TITLE
Bump `small` submodule to latest commit

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6639]
### What is the issue?

@ckerr Please sync https://github.com/transmission/small with upstream.

I've just landed some major fixes that make the types in `map.hpp` much more usable, and I want to use them in #6614.

### Which application of Transmission?

None

**Comment by Coeur** [comment]
I believe that Charles should grant write access to those third-parties repositories to you and me, so that we could maintain them more easily.

Related: I have a similar request for miniupnp but it's unnoticed: https://github.com/transmission/miniupnp/pull/1

**Comment by ckerr** [comment]
Done

**Comment by tearfur** [comment]
@ckerr Please bump again, just got another important fix merged https://github.com/alandefreitas/small/pull/43.
