### ISSUE TITLE
Suggestion: Web Login, send the hash and not the clear password

### ISSUE THREAD

**Issue by infopz** [transmission/transmission#664]
I want to improve this program.
You can change the web login sending the hash of the password using the same algorithm in which the password is hashed on the server-side, so the program had only to do a simply control on the hash received.
I think this is really better than sending the password without any type of safety.
(sorry for my bad english)

**Comment by xavery** [comment]
What would this achieve? If somebody sniffs the traffic between the client and the server, they can use the hash just as well as the plaintext password.

**Comment by infopz** [comment]
Lol, you're right.
