### ISSUE TITLE
torrent-set-location (rpc) fails to move?

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6646]
### What is the issue?

Not sure when this behavior started but it's happening @ 7f029ac .  Can see that rpcimpl has gone thru a lot of refactoring.

when the following json is sent, the 'move' flag seems to be getting ignored.

`
{"method": "torrent-set-location", 
"arguments": 
{
"ids": ["9a4be9d9817b549e89f37498274f997a31096287"], 
"location":"/home/user/Download", 
"move": "true"
}
}
`

I was able to fix this by changing the quoted "true" value to True, unquoted, in python.  But the string value should work as it always has. There was a previous case where 0/1 and true/false where not interchangeably allowed. Strongly recommend maintaining rpc compat with Tr3.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1

**Comment by killemov** [comment]
As mentioned, similar to #6630. "true" is truthy as in every non-empty string is truthy so "false" is also truthy. For reference see https://developer.mozilla.org/en-US/docs/Glossary/Falsy .

It has been established that the used JSON-parser is not lenient about truthy/falsy values. I also would prefer it was, making it a bit easier for non-JavaScript client libraries. So either reconfigure it to be lenient or integrate another JSON-parser.

**Comment by reardonia** [comment]
I see now, this is just dupe of #6630
