### ISSUE TITLE
reverse proxy access despair

### ISSUE THREAD

**Issue by ctx83** [transmission/transmission#665]
Hi guys, please help me on this... I have literally spent days. My transmission web UI will work fine on port 9091, but when behind an apache2 reverse proxy with ssl it loads and immediately throws "Connection Failed // Could not connect to the server. You may need to reload the page to reconnect." Sadly a reload does nothing.
Here's my apache config (FQDN=my server's public address):

`<IfModule mod_ssl.c>`
`<VirtualHost FQDN:443>`
 
 `ProxyPass               /transmission   http://127.0.0.1:9091/transmission`
`ProxyPassReverse        /transmission   http://127.0.0.1:9091/transmission`
`ProxyTimeout    30`
`ProxyErrorOverride      On`
`ProxyVia                On`

 
`#<Proxy http://127.0.0.1:9091/transmission>`
`<Proxy *>`
        ` Require all granted`
       ` Options none`
 `</Proxy>`
 
 `SSLEngine On`
` SSLProxyEngine On`
` SSLCertificateFile /etc/letsencrypt/live/FQDN/fullchain.pem`
`SSLCertificateKeyFile /etc/letsencrypt/live/FQDN/privkey.pem`
` Include /etc/letsencrypt/options-ssl-apache.conf`
` KeepAliveTimeout 99`
 
`</VirtualHost>`
`</IfModule>`

my transmission's settings json includes these lines:

`    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "FQDN",
    "rpc-host-whitelist-enabled": true,
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-whitelist": "*",
    "rpc-whitelist-enabled": true,`

PLEASE help!! :-)

Cheers, Chris

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
