### ISSUE TITLE
Web UI missing icons / file priority images

### ISSUE THREAD

**Issue by stevenengler** [transmission/transmission#6653]
### What is the issue?

When running the web UI, some of the images are missing. For example the images in the torrent list and the up/down chevron in the file list.

![1709238996_grim](https://github.com/transmission/transmission/assets/3708797/79b15c65-c0a1-4d4b-a9b3-eda1ec5741c5)

```bash
# can also use docker instead
podman run --rm -it -p 9091:9091 ubuntu:23.04

apt-get update
apt-get install -y \
    git \
    cmake \
    clang \
    libcurl4-openssl-dev \
    libssl-dev

mkdir /tmp/install/

cd /tmp/
git clone --branch 4.0.5 --depth 1 --recurse-submodules https://github.com/transmission/transmission
mkdir transmission/build/
cd transmission/build/
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TESTS=OFF -DENABLE_GTK=OFF -DENABLE_QT=OFF -DINSTALL_DOC=OFF ..
cmake --build . --parallel "$(nproc)" 
cmake --install . --prefix /tmp/install/

export TRANSMISSION_WEB_HOME=/tmp/install/share/transmission/public_html/
/tmp/install/bin/transmission-daemon --foreground --allowed '*' --config-dir /tmp/config
```

Then go to `http://localhost:9091/transmission/web/` in the browser.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.5

**Comment by stevenengler** [comment]
I can confirm that it worked properly in 4.0.4, so it was broken somewhere between 4.0.4 and 4.0.5. The web UI on the current HEAD 1855cdb is very broken (see #6632).

**Comment by killemov** [comment]
The 409 status codes are normal, see: https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#231-csrf-protection

**Comment by stevenengler** [comment]
> @stevenengler Did you not read #6632 completely?

Yes I did read it completely. Why, is there something I'm missing?

**Comment by killemov** [comment]
Yes, the explanation about 409 status codes ...

**Comment by stevenengler** [comment]
> Yes, the explanation about 409 status codes ...

I'm aware of how CSRF protections work. I just added that as additional information since someone asked about console errors in #6632. I figured I might as well preemptively provide that information here about any console errors as well.

**Comment by tearfur** [comment]
This has nothing to do with #6632. Closing as duplicate of #6362.
