### ISSUE TITLE
Transmission 4.0.5 statically link on alpine linux fails with "undefined reference to xxxxx"

### ISSUE THREAD

**Issue by deamen** [transmission/transmission#6661]
### What is the issue?

I am trying to build a statically linked transmission-daemon on alpine linux, but fails at the link stage:.

I have added dependencies in this command:
`apk update && apk --no-cache add \
    build-base pkgconfig curl-static curl-dev linux-headers vim \
    brotli-static brotli-dev nghttp2-static zlib-static cmake \
    openssl-libs-static libevent-static libevent-dev gettext-dev xz ninja`
I use the following command to configure the project:
`cmake \
        -S transmission-4.0.5 \
        -B transmission-4.0.5-obj \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DENABLE_DAEMON=ON \
        -DENABLE_CLI=OFF \
        -DENABLE_GTK=OFF \
        -DENABLE_QT=OFF \
        -DENABLE_UTILS=OFF \
        -DENABLE_TESTS=OFF \
        -DBUILD_SHARED_LIBS=OFF \
        -DENABLE_NLS=OFF \
        -DCMAKE_EXE_LINKER_FLAGS=-static \
        -DCURL_LIBRARY_RELEASE=/usr/lib/libcurl.a \
        -DEVENT2_LIBRARY=/usr/lib/libevent.a \
        -DOPENSSL_USE_STATIC_LIBS=TRUE `
I then build with this command:
`cmake --build transmission-4.0.5-obj --config RelWithDebInfo`

I get a bunch of link errors:

> [131/132] Linking CXX static library libtransmission/libtransmission.a                                                                  
[132/132] Linking CXX executable daemon/transmission-daemon                                                                             
ninja: job failed: : && /usr/bin/c++ -O2 -g -DNDEBUG -static daemon/CMakeFiles/transmission-daemon.dir/daemon.cc.o daemon/CMakeFiles/transmission-daemon.dir/daemon-posix.cc.o -o daemon/transmission-daemon libtransmission/libtransmission.a  /usr/lib/libevent.a  third-party/libdeflate.bld/pfx/lib/libdeflate.a  /usr/lib/libssl.a  /usr/lib/libcrypto.a  -ldl  /usr/lib/libcurl.a  third-party/libpsl.bld/pfx/lib/libpsl.a  third-party/libnatpmp.bld/pfx/lib/libnatpmp.a third-party/miniupnpc.bld/pfx/lib/libminiupnpc.a  third-party/dht.bld/pfx/lib/libdht.a  third-party/libutp.bld/libutp.a  third-party/libb64.bld/src/libb64.a  -lm  third-party/jsonsl/libjsonsl.a  third-party/wildmat/libwildmat.a && :                                                                                                                      
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libcurl.a(libcurl_la-version.o): in function 'brotli_version':                                                                                                               
/home/buildozer/aports/main/curl/src/curl-8.5.0/lib/version.c:91:(.text+0x1a): undefined reference to 'BrotliDecoderVersion'            
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libcurl.a(libcurl_la-version.o): in function 'curl_version':                                                                                                                 
/home/buildozer/aports/main/curl/src/curl-8.5.0/lib/version.c:189:(.text+0xf1): undefined reference to 'zlibVersion'                    
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/buildozer/aports/main/curl/src/curl-8.5.0/lib/version.c:201:(.text+0x13f): undefined reference to 'ares_version'                                                                
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/buildozer/aports/main/curl/src/curl-8.5.0/lib/version.c:206:(.text+0x16e): undefined reference to 'idn2_check_version'                                                          
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libcurl.a(libcurl_la-version.o): in function `curl_version_info':       
removed for brevity 

I think it fails because the other static libs that libcurl.a requires is not included. How can I add those libs?
                           

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by GaryElshaw** [comment]
I don't know anything about alpine, but you're probably needing to install libcurl-dev via whatever package manager you have available.

**Comment by deamen** [comment]
> I don't know anything about alpine, but you're probably needing to install libcurl-dev via whatever package manager you have available.

Yeah, curl-static curl-dev are installed and all static libraries are installed.

I can compile dynamically linked transmission-daemon without issues. It only occurs when I am building statically linked version. 

But looks like in cmake, I need to manually add the libraries dependencies, but that means I need to patch CMakelist.txt to do it. I would like to know if there is better/official way to do it?

**Comment by GaryElshaw** [comment]
Maybe have a look at the alpine CI for dependencies? https://github.com/transmission/transmission/actions/runs/8041768826/job/22184879939?pr=6647

**Comment by deamen** [comment]
> Maybe have a look at the alpine CI for dependencies? https://github.com/transmission/transmission/actions/runs/8041768826/job/22184879939?pr=6647

Yeah, I started from the CI workflow, but unfortunately it doesn't build statically linked binaries unless I missed?

**Comment by GaryElshaw** [comment]
If you scroll to the bottom of the page.... https://github.com/transmission/transmission/actions/runs/8041768826?pr=6647

**Comment by deamen** [comment]
> If you scroll to the bottom of the page.... https://github.com/transmission/transmission/actions/runs/8041768826?pr=6647

Yes, we have CI to build transmission suite on alpine linux with musl, but it is not statically linked, this is the ldd result of the transmission-daemon from the CI:

> ldd transmission-daemon 
ldd: warning: you do not have execution permission for `./transmission-daemon'
        linux-vdso.so.1 (0x00007ffd787fc000)
        libevent-2.1.so.7 => /lib64/libevent-2.1.so.7 (0x00007fa1fa785000)
        libssl.so.3 => /lib64/libssl.so.3 (0x00007fa1fa6e2000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fa1f9e00000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007fa1fa34c000)
        libminiupnpc.so.17 => not found
        libintl.so.8 => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fa1f9a00000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa1fa328000)
        libc.musl-x86_64.so.1 => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007fa1f981e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fa1fa30e000)
        libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007fa1fa2e3000)
        libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fa1f9dde000)
        libssh.so.4 => /lib64/libssh.so.4 (0x00007fa1f9d6b000)
        libpsl.so.5 => /lib64/libpsl.so.5 (0x00007fa1fa6ca000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fa1f9d15000)
        libldap.so.2 => /lib64/libldap.so.2 (0x00007fa1f9cb0000)
        liblber.so.2 => /lib64/liblber.so.2 (0x00007fa1f9c9e000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007fa1f9c90000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa1f973d000)
        /lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007fa1fa7e9000)
        libunistring.so.5 => /lib64/libunistring.so.5 (0x00007fa1f958d000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fa1f94b4000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fa1f9c78000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fa1fa2da000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fa1f9c68000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fa1f9c61000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fa1f94a3000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fa1f9484000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007fa1f9461000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fa1f9434000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007fa1f93fb000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fa1f9360000)

I think we have a misunderstanding here:

I don't have problems building dynamically linked transmission-daemon 4.0.5 on alpine linux, I am having trouble building statically linked transmission-daemon.

**Comment by mikedld** [comment]
Judging from the posted build log, the undefined references are coming from libcurl.a, so those are transitive dependencies we don't know (and don't want to know) anything about. I'd say you need to look at the files CMake is using to figure out those dependencies, which depending on how CURL is build will be either CMake package configuration files or pkg-config .pc files.

As to your question on how to add them (manually), I'd try e.g. passing them to CMake via [`CMAKE_EXE_LINKER_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXE_LINKER_FLAGS.html) when configuring the project.

**Comment by deamen** [comment]
Thanks, I have tried adding the libraries to CMAKE_EXE_LINKER_FLAGS, like `-DCMAKE_EXE_LINKER_FLAGS="-static /usr/lib/libnghttp2.a /usr/lib/libbrotlidec.a"`. But I am getting warning:
> CMake Warning:
 > Ignoring extra path from command line: /usr/lib/libbrotlidec.a

I ended up patching the daemon/CMakeLists.txt, added the libraries via the **find_library** command, and added them into **target_link_libraries()** under **PUBLIC**

I wonder if I did something wrong with the **CMAKE_EXE_LINKER_FLAGS**? This seems to be a better way than patching the CMakeLists.txt

**Comment by deamen** [comment]
I am able to build transmission-daemon for x86_64 and amr64 by patching the CMakelist.txt file, the scripts are in this [repo](https://github.com/deamen/transmission-builder)

**Comment by deamen** [comment]
I think we can close this.
