### ISSUE TITLE
write permission

### ISSUE THREAD

**Issue by gamesmann** [transmission/transmission#668]
i get a problem with my transmission 2.94 on Ubuntu 16.04 LTS server.

i tried different dir on my disks and all give me same problem. i tried reinstall and that didn't help.

i used this guide to install Transmission 
[https://help.ubuntu.com/community/TransmissionHowTo](url)

tried editing "sudo nano /etc/transmission-daemon/settings.json"  with no help and working on user groups.

on this cmd is this correct ?
"sudo usermod -a -G debian-transmission myuser"

now i dont know what to do 

![2018-07-19](https://user-images.githubusercontent.com/18055903/42938261-f90305aa-8b51-11e8-899f-ce5f328769ff.png)

****************

i did edit the path after the picture was taken.

Permission denied (/home/thomas/media/hdd2/ubuntu-16.04.4-server-amd64.iso)

still same problem

******************

When connected to smb and download with utorrent on windows to ubuntu path it is successful

**Comment by gamesmann** [comment]
i did edit the path after the picture was taken.

Permission denied (/home/thomas/media/hdd2/ubuntu-16.04.4-server-amd64.iso)

still same problem

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) for support.
