### ISSUE TITLE
How can I copy a torrent file to some dir when torrent is completed and using script which on "script-torrent-done-filename"

### ISSUE THREAD

**Issue by UnicornUnderMoon** [transmission/transmission#6684]
### What is the issue?

ubuntu 22.04
transmission-daemon 4.0.5 (a6fe2a64aa)
I write a script. set  "script-torrent-done-filename"=`/path/myscript.sh`. The script can work, but when I try to copy torrent file `/var/lib/transmission-daemon/.config/transmission-daemon/torrents/${TR_TORRENT_HASH}.torrent` to another dir, it doesn't work.
e.g `cp '/var/lib/transmission-daemon/.config/transmission-daemon/torrents/${TR_TORRENT_HASH}.torrent' '/media/Download/torrent/reseed/${TR_TORRENT_NAME}.torrent'`, return "No such file or directory".
I find the torrents are in `/var/lib/transmission-daemon/.config/transmission-daemon/torrents/` and user,grooup 'debian-transmission:debian-transmission', and mod 600.
When I copy the command, run it with sudo , it work , file is copied to the new dir. I know it should be some privilege promblem. But don't know how to do.
Some suggestions?
Thanks 

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
> When I copy the command, run it with sudo , it work , file is copied to the new dir. I know it should be some privilege promblem.

Then su yourself to transmission-daemon and try again. The complete path must be accessible to your script not just the last directory in it.

**Comment by UnicornUnderMoon** [comment]
> > When I copy the command, run it with sudo , it work , file is copied to the new dir. I know it should be some privilege promblem.
> 
> Then su yourself to transmission-daemon and try again. The complete path must be accessible to your script not just the last directory in it.
> 
> Or, for testing purposes only!, run Transmission as root.

Thank for your reply. @killemov 
I mount ntfs on  `/media/Download/`. 
`drwxr-xr-x  11 root root  4096  4月 20  2023 media/`
`drwxrwxrwx   1 root root             348160  3月 13 13:04 Download/`
`drwxrwxrwx  1 root root      20480  2月 29 14:14 torrent/`
`drwxrwxrwx 1 root root  24576  3月 12 11:18 reseed/`
The transmission-daemon run as systemd service. That's what in `/lib/systemd/system/transmission-daemon.service`.
```
[Unit]
Description=Transmission BitTorrent Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=debian-transmission
Type=notify
Environment=TRANSMISSION_WEB_HOME="/etc/transmission-daemon/web"
ExecStart=/usr/bin/transmission-daemon -f --log-level=info --logfile /var/log/transmission.log
ExecReload=/bin/kill -s HUP $MAINPID
NoNewPrivileges=true
MemoryDenyWriteExecute=true
ProtectSystem=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
I googled for solution.Tried to comment “NoNewPrivileges”，“MemoryDenyWriteExecute”，“ProtectSystem”，"PrivateTmp", and set `PrivateTmp=false`. It not work. 
I change the user just now.
```
[Unit]
Description=Transmission BitTorrent Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
#User=debian-transmission
Type=notify
Environment=TRANSMISSION_WEB_HOME="/etc/transmission-daemon/web"
ExecStart=/usr/bin/transmission-daemon -f --log-level=info --logfile /var/log/transmission.log
#ExecStart=/usr/bin/transmission-daemon -f --log-level=error
ExecReload=/bin/kill -s HUP $MAINPID
#NoNewPrivileges=true
#MemoryDenyWriteExecute=true
#ProtectSystem=true
#PrivateTmp=true
NoNewPrivileges=false

[Install]
WantedBy=multi-user.target

```
Then I even can't connect the web ui. Response is "403: Forbidden". 
what's in `/var/log/transmission.log`:
```
[2024-03-14 09:32:24.593] inf session.cc:1328 Transmission version 4.0.5 (a6fe2a64aa) shutting down (session.cc:1328)
[2024-03-14 09:32:24.593] inf rpc-server.cc:740 Stopped listening for RPC and Web requests on '0.0.0.0:9091' (rpc-server.cc:740)
[2024-03-14 09:32:25.861] inf session.cc:646 Transmission version 4.0.5 (a6fe2a64aa) starting (session.cc:646)
[2024-03-14 09:32:25.861] inf session.cc:404 Listening to incoming peer connections on [0.0.0.0]:51413 (session.cc:404)
[2024-03-14 09:32:25.861] inf session.cc:404 Listening to incoming peer connections on [::]:51413 (session.cc:404)
[2024-03-14 09:32:25.861] inf port-forwarding.cc:215 State changed from 'Not forwarded' to 'Starting' (port-forwarding.cc:215)
[2024-03-14 09:32:25.861] inf tr-udp.cc:168 Bound UDP IPv4 address [0.0.0.0]:51413 (tr-udp.cc:168)
[2024-03-14 09:32:25.861] inf tr-udp.cc:202 Bound UDP IPv6 address [::]:51413 (tr-udp.cc:202)
[2024-03-14 09:32:25.861] inf rpc-server.cc:763 Added '127.0.0.1' to host whitelist (rpc-server.cc:763)
[2024-03-14 09:32:25.861] inf rpc-server.cc:763 Added '::1' to host whitelist (rpc-server.cc:763)
[2024-03-14 09:32:25.861] inf rpc-server.cc:907 Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (rpc-server.cc:907)
[2024-03-14 09:32:25.861] inf rpc-server.cc:713 Listening for RPC and Web requests on '0.0.0.0:9091' (rpc-server.cc:713)
[2024-03-14 09:32:25.861] inf rpc-server.cc:912 Whitelist enabled (rpc-server.cc:912)
[2024-03-14 09:32:25.861] inf rpc-server.cc:923 Serving RPC and Web requests from '/etc/transmission-daemon/web' (rpc-server.cc:923)
[2024-03-14 09:32:25.861] inf daemon.cc:715 Loading settings from '/root/.config/transmission-daemon' (daemon.cc:715)
[2024-03-14 09:32:32.902] inf port-forwarding.cc:215 State changed from 'Starting' to '???' (port-forwarding.cc:215)
```

**Comment by killemov** [comment]
This all looks normal. Are you accessing the web-UI with localhost? (Whitelist problem?) Is /var/lib/transmission-daemon/.config/transmission-daemon/torrents a symlink to /media/torrent? If so, getting permission might be a problem on NTFS. You might even need to mount /media/Downloads with transmission-daemon as user option. (-o uid=XXXX)

I haven't run transmission as root for a very long time AND I still mainly run 3.0, but maybe something else is preventing you to run TM as root. Whatever that is, is not logged here. However, I don't particularly like the last log line going from Starting to ??? (unknown?) .

**Comment by UnicornUnderMoon** [comment]
> This all looks normal. Are you accessing the web-UI with localhost? (Whitelist problem?) Is /var/lib/transmission-daemon/.config/transmission-daemon/torrents a symlink to /media/torrent? If so, getting permission might be a problem on NTFS. You might even need to mount /media/Downloads with transmission-daemon as user option. (-o uid=XXXX)

You are right. I run transmission-daemon on my server,  and  accessing the web-UI with WAN.  After log on server , I can access the transmission with localhost. 
I add `set -x -v; exec &> /tmp/script.log` in the script. Run transmission-daemon as root with systemd service again. The log show the same.
`+ 'cp '\''/var/lib/transmission-daemon/.config/transmission-daemon/torrents/20dba03d923138d4160e9fa448e0442d20858aa9.torrent'\'' '\''/media/Download/torrent/reseed/***.azw3.torrent'\'''
/etc/transmission-daemon/after-torrent-done.sh: row 39: cp '/var/lib/transmission-daemon/.config/transmission-daemon/torrents/20dba03d923138d4160e9fa448e0442d20858aa9.torrent' '/media/Download/torrent/reseed/****.azw3.torrent': No such file or directory`
torrent directory:
```
(base) unicorn@Nas-Station:~$ sudo ls -l /var/lib/transmission-daemon/.config/transmission-daemon/
总计 164
-rw------- 1 debian-transmission debian-transmission     4  3月 15 08:39 bandwidth-groups.json
drwxr-xr-x 2 debian-transmission debian-transmission  4096  1月 26 13:27 blocklists
-rw------- 1 debian-transmission debian-transmission  6054  1月 26 15:00 dht.dat
drwxr-xr-x 2 debian-transmission debian-transmission 69632  3月 15 08:39 resume
lrwxrwxrwx 1 root                root                   38  5月  6  2023 settings.json -> /etc/transmission-daemon/settings.json
-rw------- 1 debian-transmission debian-transmission   162  3月 15 08:40 stats.json
drwxr-xr-x 2 debian-transmission debian-transmission 69632  3月 14 10:18 torrents
```
what's in /etc/fstab:
`UUID=3F210BE358E698D9                     /media/Download ntfs    defaults       0       2`

**Comment by UnicornUnderMoon** [comment]
I get it. It's all my fault. First, `sudo -u debian-transmission bash` can run commad as user "debian-transmission". Then torrent file can be copied to the new directory. So I check the script.
Finally, I find I made a mistake. put the cp commad under double quote. 
Thank you for the help @killemov

**Comment by killemov** [comment]
@UnicornUnderMoon DOH! And you're welcome but please close this issue.
