### ISSUE TITLE
After the saved directory is changed, files that have been downloaded in other directories cannot be uploaded anymore!

### ISSUE THREAD

**Issue by sxwangws** [transmission/transmission#6686]
### What is the issue?

Hello everyone, I use Transmission under the openwrt system to download. The download directory is the mounted external USB hard disk. I have created two folders, 'Movies' and 'Tvs', under the hard disk. The default download path set by Transmission is the 'Movies' folder. For example, when I download a file, there is no problem in saving it to the 'Movies' directory, but when I want to save it to the 'Tvs' directory, I cannot download the file when I manually modify download path to the Tvs directory. Why ? I have started the program with the root account

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3

**Comment by nevack** [comment]
@sxwangws Please remove/edit screenshots with copyrighted content.

**Comment by sxwangws** [comment]
> @sxwangws Please remove/edit screenshots with copyrighted content.

OK，sorry for that

**Comment by sxwangws** [comment]
Does anyone know?

**Comment by ckerr** [comment]
Issue closed & user banned [as advertised](https://github.com/transmission/transmission/commit/13ae244eed007cd6e94b15de5f2d97a7131cbb870).
