### ISSUE TITLE
"Move the .torrent file to the trash" does not work

### ISSUE THREAD

**Issue by Real3L0** [transmission/transmission#6692]
### What is the issue?

1.
Preferences -> Downloading
"Move the .torrent file to the trash" - ON
But the file is not deleted.
2.
Open Torrent from URL or Magnet Link
"Move the .torrent file to the trash" - ON
But the file is not deleted.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Client: 4.0.5, Server: 3.00

**Comment by mrbass21** [comment]
Duplicate of https://github.com/transmission/transmission/issues/5647 ?

**Comment by Real3L0** [comment]
Hmm, but sometimes it deletes
