### ISSUE TITLE
transmission 4.0.5 crashes with plasma 6 

### ISSUE THREAD

**Issue by asteri0** [transmission/transmission#6694]
### What is the issue?

Since I upgraded my desktop to KDE Plasma 6 (6.0.1), transmission-qt (4.0.5-1) fails to start when I double click on its icon.(?)
I am running on a Lenovo Thinkpad P1 with Intel Xeon E-2176M (12) @ 4.400GHz
OS: Arch Linux x86_64 
kernel: 6.7.9-arch1-1

>>>> I am sorry I made a gross mistake. It seems the offending link is the executable in "/usr/bin/transgui" not the app 

Everything worked fine, just before upgrading my DE. All other apps I use have worked seamlessly in the new desktop. 

Searching joutnalctl, I saw this: 

Mar 14 11:52:52 thor systemd[1093]: Started Transmission Remote GUI - TransGUI.
Mar 14 11:52:52 thor plasmashell[42041]: [FORMS.PP] ExceptionOccurred
Mar 14 11:52:52 thor plasmashell[42041]:   Sender=EAccessViolation
Mar 14 11:52:52 thor plasmashell[42041]:   Exception=Access violation
Mar 14 11:52:52 thor plasmashell[42041]:   Stack trace:
Mar 14 11:52:52 thor plasmashell[42041]:   $00000000005B29D3
Mar 14 11:52:52 thor plasmashell[42041]:   $0000000000591829
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000071C038
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000071B9CA
Mar 14 11:52:52 thor plasmashell[42041]:   $00000000007175DC
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000061FA19
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000061F91B
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000044D65A
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000044C4D3
Mar 14 11:52:52 thor plasmashell[42041]:   $000000000043A15C
Mar 14 11:52:52 thor plasmashell[42041]: [FORMS.PP] ExceptionOccurred

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5-1

**Comment by mrbass21** [comment]
Interesting. I have a similar setup and I haven't had any issues with Transmission. Posting software specs just for comparison:

Transmission: 4.0.5 (a6fe2a64aa)
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
QT Version: 6.6.2
Kernel Version: 6.7.9-arch1-1 (64-bit)
Graphics Platform: Wayland

**Comment by asteri0** [comment]
I am sorry; I made this post by mistake!

The issue I had was unrelated to transmission-qt per se, it was with
transmission-remote-gui / transgui and my new desktop.

I have now reinstalled transgui and everything works.


Best Regards,

Pablo Klein Bernard

**Comment by GaryElshaw** [comment]
@asteri0 Please close this issue if things are resolved.

**Comment by asteri0** [comment]
I close this issue as I opened it by mistake.
