### ISSUE TITLE
[feature request] Add an automatic prioritizer for files

### ISSUE THREAD

**Issue by bofh69** [transmission/transmission#67]
When downloading a torrent with multiple files, I most often want to be able to access the "first" file before the rest, so I increase its priority and often lower the third and further files priorities. It would be awesome if that could be selected to happen automatically.

I'm sure it is possible to find some heuristic to figure out the order of the files since they often follow one of a few naming schemes, the most common being that many files have the same filename, except one or two digits that are increased.

**Comment by mikedld** [comment]
This sounds like overkill. I found myself doing download order targeted priority management a few times some years ago as well, but cannot imagine a 1) wide audience for the feature, and 2) simple ordering algorithm that will satisfy everyone. Not to mention there are lots of digits other than [western] arabic ones out there ;)
