### ISSUE TITLE
Add torrrent when dragging torrent to window in web ui

### ISSUE THREAD

**Issue by tiagoboldt** [transmission/transmission#670]
Currently, if I drag a torrent to the Web UI, the browser considers it a link and shows the file content. It would be a better behavior to enable the user to drag a torrent to the browser window for a quick torrent add.

**Comment by killemov** [comment]
This is a very important and convenient feature. It was one of the first features I implemented in [Shift](https://github.com/killemov/Shift/blob/2be00e864af80589f7fb79a9ad676e12ab8b2215/shift.js#L1909) in 2011. <- This link points to the actual entry-point in the code where "drops" are handled.

**Comment by dareiff** [comment]
In implementing this, should drag-and-drop bring up the dialog with the file pre-filled, or should it just upload to transmission?

**Comment by ckerr** [comment]
In the other GUIs there is a preferences flag (default value: `true`) to let the user decide whether or not to pop up a dialog before adding. If you're inclined to add Prefs + PrefsDialog code for that too, then copying that feature in the web client would be the preferred way to do it.

**Comment by bbsixzz** [comment]
Has this regressed? 

Not working for me in Safari 17.5 (19618.2.12.11.6) on macOS Sonoma 14.5 with Transmission 4.0.6
