### ISSUE TITLE
download speed caps at ~10 MB/s

### ISSUE THREAD

**Issue by Aivars27** [transmission/transmission#672]
Hello,

I am running Transmission on my NETGEAR NAS (Readynas 104) device. Every time I download anything in Transmission, the download speed never exceeds ~10 MB/s (not Mb/s). If I connect from my PC to the NAS file system and download/upload data, the transfer speeds are in excess of 30+ MB/s. My fibre broadband speed is 370 Mbps and I can downoad torrents, steam games, other files from the internet with a constant speed of around 50+ MB/s (again, not Mb/s). All this indicates that there is something to do with the Transmission app on my NAS, something is capping download speeds to not exceed 10 MB/s. My upload is 20 Mbps, but in 2-3 years I have been running Transmission on the NAS, the downlaod never exceeded 10 MB/s. The port forwarding is working poperly and Transmission reports the port as Open. The Transmission version running is "Transmission 2.82 (14160)".

Any help or advice would be much appreciated.

**Comment by OliverLew** [comment]
I have the same problem on my laptop.

Tested by same torrents from the same tracker with enough peers, download speed in transmission stays under ~11MiB/s, in qbittorrent it can get to 70MiB/s.

The version is transmission 2.9.4

**Comment by ckerr** [comment]
Whatever this issue was at the time, it's definitely not the case in Transmission 4.

I don't have the best bandwidth in the world and am able to get sustained 60MB/s in Transmission 4.0.0-beta.2.
