### ISSUE TITLE
GUI interface MacOS

### ISSUE THREAD

**Issue by listingpro** [transmission/transmission#6724]
### What is the issue?

Transmission 4.0.5
Sonoma 14.4

New machine, new transmission install. Didn't want to retype Group criteria list, so  I copied org.m0k.transmission.plist from a previous back up and overwrote existing .plist file. No, problem, Transmission loaded with my previous settings. :)
However, now ANY settings changes in GUI don't write to org.m0k.transmission.plist. Make a settings change, quit transmission, restart transmission, open settings GUI, see old settings with no changes made.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.5

**Comment by nevack** [comment]
@listingpro

I suppose permissions on that file could be messed up
Can you show Finder's `Get Info` on that file?

<details>
<summary>Example:</summary>

<img width="377" alt="image" src="https://github.com/transmission/transmission/assets/8330119/4c20af37-2470-4807-841f-de848dea36b6">

</details>

Also, are there any errors for Transmission in Console?
<img width="1020" alt="image" src="https://github.com/transmission/transmission/assets/8330119/2b05c211-d457-4d9a-93aa-013848198292">

**Comment by listingpro** [comment]
Checked Get Info. Found a duplicate permission entry for Everyone listed as "Custom". The other Everyone entry was Read Write.
Changed the custom entry to Read Write as well.
Reopening get info showed permissions changed Everyone to no access and my user to Read Write.
Restarted Transmission Made settings changes in the GUI and they saved correctly.
