### ISSUE TITLE
[linux] cannot cross compile qt6 translations

### ISSUE THREAD

**Issue by dkwo** [transmission/transmission#6732]
### What is the issue?

At https://github.com/void-linux/void-packages/pull/49505 I'm trying to switch transmission from qt5 to qt6.
The native linux builds look fine, but cross compiling fails at the translations step:
```
[287/379] Automatic MOC and UIC for target transmission-qt
[288/379] Generating transmission_af.qm
FAILED: qt/transmission_af.qm /builddir/transmission-4.0.5/build/qt/transmission_af.qm 
cd /builddir/transmission-4.0.5/build/qt && /usr/aarch64-linux-gnu/usr/lib64/qt6/bin/lrelease -silent /builddir/transmission-4.0.5/qt/translations/transmission_af.ts -qm /builddir/transmission-4.0.5/build/qt/transmission_af.qm
/bin/sh: line 1: /usr/aarch64-linux-gnu/usr/lib64/qt6/bin/lrelease: cannot execute binary file: Exec format error
```
It may be that our cmake cross toolchain lacks something, or that something is not setup correctly in transmission-qt.
Can anyone cross compile it fine? is it supposed to use the host or target `lrelease` at this step?
Thanks.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5

**Comment by dkwo** [comment]
fixed on my end.

**Comment by nevack** [comment]
> fixed on my end.

Do not hesitate to post a fix here for anybody struggling with this in the future :smile:
