### ISSUE TITLE
Pre-allocate option missing on Ubuntu: unable to restart encrypted server

### ISSUE THREAD

**Issue by binarykitchen** [transmission/transmission#6740]
### What is the issue?

Good evening,

In short: while torrenting last night on my encrypted Ubuntu server, disk space ran out. No warning.

Longer version: is there some UI option to activate pre-allocating disk space before torrenting? If you look at this UI screenshot, there is none:
![image](https://github.com/transmission/transmission/assets/177641/4144e8e7-f55e-43be-bd80-5872380c4351)

I had a fun time today decrypting my server with manual commands. I think an option to pre-allocate disk space is vital.
There are no documents out there, nor found any bug reports, and found none about this matter.

Thanks for any feedback,
M.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.2 (2a57b17031)

**Comment by tearfur** [comment]
I think your issue is a variant of #6554.
