### ISSUE TITLE
[remote] `-w` should set download location when adding torrent instead of `--find`

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#6741]
### What is the issue?

I'm wondering how disruptive it would be to fix this:

As the title suggests. I'd expect this command to allow me to set the download location:

```console
$ transmission-remote -a my.torrent -w /path/to/download/my/torrent
```

Quoting `-w`'s description:

> When used in conjunction with --add, set the new torrent's download folder.

But no! This is what actually works:

```console
$ transmission-remote -a my.torrent --find /path/to/download/my/torrent
```

P.S. `transmission-remote`'s argument parsing code is a pain in the ass to look at and work with...

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

2ff3ae07d1ac0ae9bfa48229b8e5d0bce1446fde

**Comment by tearfur** [comment]
Hmm, looks like this functionality was adding at 61e2493d0003a6e3e9c927fe5fdf7d22811c842b, and it was already mismatching back then.

**Comment by tearfur** [comment]
Well, I'm not sure what went wrong with my tests before, `transmission-remote -a my.torrent -w /path/to/download/my/torrent` works now. I could have sworn I've tried in multiple occasions to swap the positions of `-a` and `-w` to no avail...

Closing as invalid.

**Comment by valcomm** [comment]
I've seen transmission not working properly with `-w` option too.
When adding magnet, sometimes `-w` was ignored.  Might be somehow linked how metadata (.torrent) is gathered (some magnets get their metadata after few weeks or even months).
Another issue that I remember is that `-w` changed working/downloading directory for the following added magnets.
Just sharing what I remember as proper testing requires a lot of time

**Comment by tearfur** [comment]
If you have any findings, please post it here, and I'll consider re-opening the issue.
