### ISSUE TITLE
Magnetized transfer - torrent metadata needed

### ISSUE THREAD

**Issue by lelekGH** [transmission/transmission#6757]
How to fix this problem:
Magnetized transfer - torrent metadata needed

2024-03-29 15:59:02 +0000 torrent-metainfo.cc:650 [Error] torrent-metainfo.cc:650: no bencoded data to parse (92)
2024-03-29 15:59:41 +0000 torrent-metainfo.cc:650 [Error] torrent-metainfo.cc:650: no bencoded data to parse (92)

Mac OS Catalina 10.15.7
Transmissmission ver. 4.0.5 (a6fe2a64aa)
 
thx
leSheQ

**Comment by killemov** [comment]
Weird. If I read this correctly it tries to parse a magnet as a torrent. I guess there is a difference for how you add a torrent or a magnet and you chose the wrong one?

**Comment by tearfur** [comment]
You probably got wrong metadata size from a peer, and Transmission stuck with it.

If I guessed correctly, the problem won't go away unless you restart Transmission. This is fixed in #6364.
