### ISSUE TITLE
Suggested order of merging ready-to-merge Pull Requests

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#6760]
### What is the issue?

There are many pull requests which have been reviewed and approved and are ready to merge, but sometimes it takes a long time to see them effectively merged, or the code starts to conflict with newer refactoring which slows down their integration even further.
https://github.com/transmission/transmission/pulls?q=is%3Aopen+is%3Apr+draft%3Afalse+assignee%3Ackerr

So here is a personal suggestion order of merges to be performed, by my perceived priority/low-risk, and hopefully they all get merged quickly in a matter of days. In other words, please consider merging all those now before refactors.

### blockers (build failures or broken app that should be addressed before anything else)

- none anymore, thanks

### 4.0.x (production fixes that could be addressed and released without delay)

- #6753 - Fixes queue order between sessions (may need a second PR for 4.0.x branch)

### pipelines testing and warnings (benefits all the other pull requests)

- none anymore, thanks

### docs and safe changes

- #6713 - Chore: update generated transmission-web files

### fixes

- #6672 - Blocker for fixing port-forwarding
- #6055 - Fixes data-removal
- #6721 - Third-Parties fixes

(and there are more PR fixes opened, but not yet reviewed)

### features (oldest ready-to-merge PR first)

- #4178 - macOS prevents corrupted downloads
- #5102 - macOS random port on first launch
- #6548 - Windows dual stack support
- #6573 - Qt UI improvement
- #6599 - Qt RPC improvement
- #6610 - macOS UI improvement

### refactor (best done last, to avoid potential conflicts with higher importance ready-to-merge pull requests)

- #6708 - core api changed to C++ interface

**Comment by killemov** [comment]
They need to be merged ASAP before any change makes them unmergeable. Maybe block new PR's for a while, until most merging is done, and explain why.

**Comment by ckerr** [comment]
> There are many pull requests which have been reviewed and approved and are ready to merge, but sometimes it takes a long time to see them effectively merged, or the code starts to conflict with newer refactoring which slows down their integration even further.
>
> https://github.com/transmission/transmission/pulls?q=is%3Aopen+is%3Apr+draft%3Afalse+assignee%3Ackerr

As always, I appreciate your work @Coeur at marshalling these lists :bowing_man: 

But the "assignee=ckerr" filter is because _you've_ assigned me, even when there are reviews pending from other maintainers. Did you assign any to @mikedld?

**Comment by killemov** [comment]
@ckerr Is it the usual way here to merge PR's in batches? My earlier, disliked, comment expressed my worries of PRs getting out of sync so much that they have to be refitted to be accepted again. Some of the oldest remaining open PRs are from 2018 so they probably need to be triaged for conflicts. Some of those are probably conflicting with the big C++ refactoring and need to be redone completely. Some of those probably have developers that don't want or can't redo their work which either leads to more work for the TM devs or the PR just gets lost over time.

**Comment by Coeur** [comment]
> But the "assignee=ckerr" filter is because _you've_ assigned me, even when there are reviews pending from other maintainers. Did you assign any to @mikedld?

Coincidentally, newspapers are warning today open source projects of code-merge pressures:
https://www.404media.co/xz-backdoor-bullying-in-open-source-software-is-a-massive-security-vulnerability/

I think I did try long ago to assign some PR to Mike, but gave up with time. I wrote an email explaining why on 23rd of March 2024 to each of you (including @livings124), but didn't get a reply. If you're using Mail.app on macOS, you may be able to directly find it pasting `message:<83498228-F47C-4384-A805-D34A52557C90@gmx.fr>` in your browser.

Thank you for the merges last weekend, Charles.
To keep the project healthy in the long term, it could be nice to meet. Let me know if you travel to Europe one day (I have, unfortunately, no plans to visit America at the moment).
