### ISSUE TITLE
Request: Add ability to gtk to remove torrent from verification queue.

### ISSUE THREAD

**Issue by bittaurus** [transmission/transmission#677]
I can't find any way in the gtk ui to remove a torrent from the verifying queue, waiting for other torrents to verify hash. Intuitively, I would think the "pause" option would do it.  Sometimes if I change location of the torrent, with the "already there" option, it will set it to paused.  Also, if I restart the client completely it will set it to paused.

This is probably a fairly easy fix.

**Comment by pyrovski** [comment]
Surprisingly, this was not implemented in any UI; torrents queued for verification are not considered active, so they aren't stopped when you stop them. This is fixed in my fork: https://github.com/pyrovski/transmission/blob/d8263a7e623f4203905a7173d4c4b8a637655f55/libtransmission/rpcimpl.c#L311.

**Comment by pyrovski** [comment]
Duplicate of #199.
