### ISSUE TITLE
Cant download any bittorrent

### ISSUE THREAD

**Issue by huoyan1231** [transmission/transmission#6772]
### What is the issue?

![image](https://github.com/transmission/transmission/assets/53113734/98627838-1e6e-49ef-b4bb-aaaa6d5387b8)
stuck here

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
Are you sure this is not a network issue? Have you tried an older version of Transmission or even other BitTorrent clients?

**Comment by huoyan1231** [comment]
not network issue
qbitorrent working fine

于 2024年4月8日 GMT+08:00 00:41:57, killemov ***@***.***> 写到:

**Comment by CamiloPSEVEN** [comment]
You could fix it? I have the same problem

**Comment by Coeur** [comment]
I have no idea if it's the same issue, because you're on Windows, but on macOS when it happens, I restart the computer and torrents start connecting to peers afterward.

**Comment by tearfur** [comment]
You are probably seeing #6216, and you probably have a lot more other torrents in qB than Tr, so you can get peers in qB for the Ubuntu torrent via DHT easier.

**Comment by huoyan1231** [comment]
> You are probably seeing #6216, and you probably have a lot more other torrents in qB than Tr, so you can get peers in qB for the Ubuntu torrent via DHT easier.

![image](https://github.com/transmission/transmission/assets/53113734/bf7de422-7f09-4e9f-bd17-587aadbe311f)
same trackers

**Comment by huoyan1231** [comment]
![image](https://github.com/transmission/transmission/assets/53113734/b535ac12-9392-4b6b-b33f-edbab979bfb0)
Another torrent (ArchLinux)

**Comment by tearfur** [comment]
As I've said in #6216, Ubuntu's trackers are bugged and works very poorly for IPv4 only peers.

That's why you'd have to rely on DHT (which aren't reliant on trackers) to get peers. And for that to work, you'd have to have some other torrents that are being seeded by peers that also have the Ubuntu torrent.

It's not our problem.

**Comment by huoyan1231** [comment]
in other side, transmission need more time to start download more than qbittorrent
