### ISSUE TITLE
[FEATURE] Show download progress in taskbar on windows

### ISSUE THREAD

**Issue by Wrestor** [transmission/transmission#6775]
### What is the issue?

Use [this class in QT](https://doc.qt.io/qt-5/qwintaskbarprogress.html) to add download progression to the taskbar on windows.

Examples(Google Chrome):
![1](https://github.com/transmission/transmission/assets/54822494/9598fece-d419-45c3-aaf0-43b03d5311b7)  ![2](https://github.com/transmission/transmission/assets/54822494/bbd8d916-89f9-4b2c-87d3-f16276b1d0d1)  ![3](https://github.com/transmission/transmission/assets/54822494/16894c9a-a352-435d-ac43-4e14b436fb15)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

Future version

**Comment by killemov** [comment]
... And that progression indicator would indicate what progression exactly? The average of all currently downloading torrents?

**Comment by nevack** [comment]
Also it is not available with Qt6
https://forum.qt.io/topic/131934/is-there-an-alternative-to-qwintaskbarbutton-in-qt-6/3

**Comment by Pentaphon** [comment]
This is more for media playback progress than download progress. Not useful. We only need a notification when a download is done.
