### ISSUE TITLE
File size representation inconsistent under Windows, KDE

### ISSUE THREAD

**Issue by arschficken** [transmission/transmission#678]
Windows, KDE (configurably), and other environments use IEC (i.e. base-2) units for sizes, while MacOS, Gnome, and other environments use base-10. Additionally, some users on one environment prefer the other representation.

Transmission seems to use base-10 everywhere. Previously, it used base-2 everywhere. Neither of these is correct.

Transmission should by default match the environment it's running on, and allow the user to configure the units.

**Comment by mikedld** [comment]
Please search for existing issues before creating new ones. See #198.
