### ISSUE TITLE
Use .app bundle instead of .dmg file for macOS distribution

### ISSUE THREAD

**Issue by jslawler-gh** [transmission/transmission#6783]
### What is the issue?

There's not really any advantage I can see to using a .dmg file instead of an .app bundle for macOS, as it's just a single app in a folder. Other apps that currently use this method as an example would be iStat Menus, Plex Media Server, Telegram, etc.
#4062 exists to simplify the installation process within the .dmg file, however I think it can be done away with all together as its not needed.

The usual pros of using a .dmg file over an .app bundle aren't present with Transmission, being:

- Showing a custom background
- Adding license agreements
- Organising files within the .dmg
- File compression (Transmission isn't large by any means)
- Release nots

Switching to an .app bundle will allow an easier installation process of simply: 
1. Downloading the .app bundle,
2. Open the folder in which it was downloaded to, and 
3. Dragging it to the Applications folder.

The current method requires you to: 
1. Download the .dmg file, 
2. Open the folder in which it was downloaded to,
3. Mount the .dmg file, 
4. Open a second folder or toggle on the Sidebar (Transmission's .plist isn't following system settings and has it turned off by default)
5. Drag the .app bundle to the Applications folder, 
6. Eject the mounted .dmg file, and
7. Bin the downloaded .dmg file.

### Which application of Transmission?

macOS app

**Comment by Coeur** [comment]
To my understanding, .app isn't one file, it's one folder. So we can't download one unless it's archived (.tgz, .zip, or .dmg).

**Comment by Coeur** [comment]
I see. So, in a sense, you suggest .zip instead of .dmg for distribution.

**Comment by nevack** [comment]
AFAIK, zip cannot be signed.
Also, this is Safari only behaviour I disable always 😄

**Comment by nevack** [comment]
> .dmg needs signing capabilities because it's a program itself

I think this is not true.
.dmg is not a program.
It is a disk image, you can inspect it with `hdiutil imageinfo ...`, it can contain even several partitions and has a defined filesystem inside.
Signing is for verifying this disk image was not altered in any way.
Comparing hashes of the whole blob can be used as another altering check technique, but they are not the same.

> I still favor that .dmg guidance for beginner users.

Me too, and I do really often see any other formats of distribution of macOS software.

**Comment by Coeur** [comment]
So, thank you for the feedback @jslawler-gh, but we won't be implementing .zip releases for macOS.
