### ISSUE TITLE
[BUG] All announces are "event=stopped" after initial start

### ISSUE THREAD

**Issue by anthonyraymond** [transmission/transmission#679]
Whenever you resume or pause a torrent, the "event" url parameter sent to the tracker is "stopped"

**Steps to reproduce:**
- Start Transmission (windows x64 desktop app)
- Add a torrent and start downloading it (at this point the event will be "started", which is good)
- Pause the torrent, and event "stopped" is sent, which is good as well.
- Resume the download. A "stopped" event will be send once more instead of a "started"

![image](https://user-images.githubusercontent.com/7503585/43545022-05932e02-95d5-11e8-9103-51a47a1d9964.png)

Version: 2.94 windows x64.

**Comment by cfpp2p** [comment]
This might get you banned on some private trackers. Sending assorted erroneous messages like this is bad.
[TRAC 5092](https://trac.transmissionbt.com/ticket/5092)

**Comment by anthonyraymond** [comment]
It has been a think for 6 years :o
It should have been on top of the todolist

**Comment by xavery** [comment]
I couldn't reproduce this while running Transmission locally - the Trac ticket (down at the moment, fortunately web.archive has a snapshot) mentions that this occurs only over RPC. Can you confirm?

**Comment by anthonyraymond** [comment]
If the Windows desktop app is talking to the core over RPC then yes.

I'm 100% sure that it happens in the windows app.

**Comment by ckerr** [comment]
I'm not able to reproduce this issue. If this is still happening in the [nightly builds](https://transmissionbt.com/download) please update this ticket with more information. The `TR_CURL_VERBOSE` environment variable may be helpful for testing this.
