### ISSUE TITLE
directing *.torrent files to a user-defined directory

### ISSUE THREAD

**Issue by stephenboston** [transmission/transmission#6792]
### What is the issue?

Looking through `settings.json` I see how I can specify the `download-dir` but no way of setting a directory for torrent files . I want to change that  from the default  `.config/torrents `  to some other directory. 

Preferred behavior is that when  I 'add' a torrent link, the torrent file goes into the torrent directory and the associated download goes into the `download-dir`.

How can I do this? 

### Which application of Transmission?

transmission-remote

**Comment by killemov** [comment]
This is the internalized database of torrent files, so it is logical there is no configuration for this. But you can use a symbolic link if your filesystem supports it.

**Comment by stephenboston** [comment]
All good then. Thanks for the comments.

I have a bit of a quibble with dynamic data in a configuration directory but maybe that's just me.
