### ISSUE TITLE
torrent filename to reflect content

### ISSUE THREAD

**Issue by stephenboston** [transmission/transmission#6793]
### What is the issue?

Currently the torrent files are named by some random? hex UID. I would like those torrent files to reflect the file they are associated with. 

For example if I am downloading "war.and.peace.epub" I want the torrent file to be "war.and.peace.torrent". 

### Which application of Transmission?

None

### Which version of Transmission?

transmission-cli 4.0.5-1

**Comment by killemov** [comment]
Before Transmission 3.00 the internalized database of torrents used the torrent name as part of the file name. The current scheme uses the torrent hash instead, which is less error prone.

**Comment by stephenboston** [comment]
I see. Thanks.
