### ISSUE TITLE
transmission rhash qbittorrent generate different magnet link with one file?

### ISSUE THREAD

**Issue by baoliaogeming2020** [transmission/transmission#6797]
### What is the issue?

I use transmission rhash qbittorrent generate magnet link or torrent with one file, and use transmission-show to generate magnet with torrent. I get three different btih.
>transmission-create -p -o aa.torrent -t udp://tracker.openbittorrent.com:80 -t udp://tracker.opentrackr.org:1337 046.mp4
>transmission-show -m aa.torrent
magnet:?xt=urn:btih:36a4a07d80e2bcad51bacf77ba64ec92194658bd
>transmission-show -m cc.torrent # cc created by qbittorrent
magnet:?xt=urn:btih:75ee718b8cfe22adffa11b66d25fa9fdb5119137
>rhash --btih 046.mp4
49a57e42dac83ae264f3a91881cd028f70b686f1  046.mp4

49a57e42dac83ae264f3a91881cd028f70b686f1---rhash
75ee718b8cfe22adffa11b66d25fa9fdb5119137---qbittorrent
36a4a07d80e2bcad51bacf77ba64ec92194658bd---transmission-create
6EC8B648497A81DC16630C002E2175C4A96CAE5E---this is dowload from web

### Which application of Transmission?

macOS app

### Which version of Transmission?

transmission-show 4.0.5 (a6fe2a64aa)

**Comment by tearfur** [comment]
It's completely normal. The info hash is generated from the info dictionary, and different torrent generators might generate it differently.

**Comment by baoliaogeming2020** [comment]
Recently, it was discovered that the HASH value is affected by the file name. The same BT software generates different HASH values ​​for the same file after modifying the file name.
