### ISSUE TITLE
Files with forbidden characters can't be downloaded

### ISSUE THREAD

**Issue by koberulz** [transmission/transmission#6799]
### What is the issue?

If a torrent contains a file with a forbidden character in the filename, it throws an error and fails to download the torrent. Other clients will substitute forbidden characters with, say, underscores.

For example, "Chapter One: Introduction.pdf" is valid in Linux, and a torrent could be created for this file. But downloaded in Transmission for Windows, it will simply create a file named "Chapter One" with no file extension, then say the file cannot be downloaded due to a file system limitation. Other clients will instead download the file, successfully, as "Chapter One_ Introduction.pdf".

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
For completeness: [Naming Files, Paths, and Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

AFAIK Windows has the most restrictions on file names. Still kind of weird that these are still OS-based instead of filesystem-based.

**Comment by Coeur** [comment]
I recall I fixed it in #6187. (Transmission 4.1.0 dev/nightlies)

**Comment by Coeur** [comment]
> Any such limitations for macOS?

macOS was my predilection system for investigation. No, macOS on APFS or HFS+ is not affected and behaves as a Unix-like system. But having an external disk/partition on NTFS with [macFUSE + NTFS-3G](https://apple.stackexchange.com/a/213575/62697) and asking Transmission download on it is unsupported.

**Comment by Coeur** [comment]
Will close as resolved in https://github.com/transmission/transmission/pull/6187.

**Comment by Coeur** [comment]
According to #6801, it happens in Transmission 4.1.0 too. Reopening.
I don't have a Windows computer, so I can't analysis this further myself.

**Comment by tearfur** [comment]
This is not an OS-specific bug, PR already up for the fix.
