### ISSUE TITLE
curl in OS X binary is outdated, and does not work with TLS trackers

### ISSUE THREAD

**Issue by 2600box** [transmission/transmission#68]
I could not find an open issue for this, but it seemed to be such a major issue I expected it would be fixed quickly. https / ssl trackers are becoming the norm.

This forum thread explains in detail, including how to force Transmission to load a recent very version for curl. https://forum.transmissionbt.com/viewtopic.php?t=17886&start=15

Can you make the native binary work with TLS tracker communications please? thank you

**Comment by huronking** [comment]
I would also like to see this issue addressed.

**Comment by MarsArtis** [comment]
any chanche to make something for supported osx? from Lion up, I mean

**Comment by tearfur** [comment]
Fixed by #1542.
