### ISSUE TITLE
`Too many open files` blocks transmission from responding 

### ISSUE THREAD

**Issue by Willian-Zhang** [transmission/transmission#6803]
### What is the issue?

transmission not responding to remote API or web interface.
from strace I can see fsync blocked by a repetition of reading of as specific fd, which turn out to be:
```
sudo cat /proc/$PID/fd/3
ERR variant.cc:1102 Couldn't save '/volume1/@appdata/transmission/resume/xxxxxxxxx.resume':
```

FTR the transmission always hit open file limit on my system, they are not good but still can be managed with manually tweeting with system limit or pausing some excessive task, however not being able to access the management interface means it has no chance to recover.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment]
Can you check the list of open files to see if the RPC listening port is still open? Maybe it got closed by the OS because there are too many open files.

**Comment by Willian-Zhang** [comment]
will try next time it occurs

> Can you check the list of open files to see if the RPC listening port is still open? Maybe it got closed by the OS because there are too many open files.

**Comment by tearfur** [comment]
If there are no further news, I'll be closing this issue for now.
