### ISSUE TITLE
frequent json rpc errors

### ISSUE THREAD

**Issue by robot468** [transmission/transmission#6806]
### What is the issue?

Macos transgui 5.18.0
transmission-daemon-4.0.5_1 freebsd
i have more than 1000 torrents in daemon. transgui shows json parsing error frequently (see screenshots).
Is there a way to fix this? Or at least log rpc answers from daemon?

Problem is **not stably** reproduced. It happens 10 to 20 times a day.

![2024-04-22_17-19-23](https://github.com/transmission/transmission/assets/130483126/fe1dd5ac-2c14-4e90-9d39-4b9ad7b03122)
![2024-04-22_14-03-18](https://github.com/transmission/transmission/assets/130483126/27872010-26a4-4b76-a2e8-98230e57523c)
![2024-04-22_11-51-58](https://github.com/transmission/transmission/assets/130483126/9b71b97f-94a0-4a3c-ad0b-cda38c990532)
![2024-04-21_23-23-10](https://github.com/transmission/transmission/assets/130483126/9587173f-6634-4cc5-b298-5615728146c8)
![2024-04-20_11-26-51](https://github.com/transmission/transmission/assets/130483126/3d17e212-f8c4-4a90-ad57-2b6efecf362e)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by killemov** [comment]
My first thought was "unescaped content". A tracker with a " in the name for example. But then I saw "falqe" which is only one bit apart from "false".

So does this happen more often when you turn on your microwave? (Suspecting weird network interference here.)

@ckerr Is it possible to have more response types use the table format? (trackerStats in this context for example.)

**Comment by robot468** [comment]
> My first thought was "unescaped content". A tracker with a " in the name for example. But then I saw "falqe" which is only one bit apart from "false".

That's an interesting observation. Thank you.

> 
> So does this happen more often when you turn on your microwave? (Suspecting weird network interference here.)

Doesn't the tcp protocol protect against such things? At least at this frequency.

This error is present on two of my macbooks, so it's definitely not them. That's why I want to somehow log the server responses to rpc requests.

**Comment by killemov** [comment]
> Doesn't the tcp protocol protect against such things? At least at this frequency.

Yes it should, but these errors are that weird. And transgui is a direct client of the RPC protocol, so no proxy on the server side, correct?

**Comment by robot468** [comment]
> Yes it should, but these errors are that weird. And transgui is a direct client of the RPC protocol, so no proxy on the server side, correct?

Looks like I disturbed you for nothing :)
I read the news about the broken memory in Voyager 1 and decided to check it out :)
My second macbook is exactly the same model. I guess their memory degrades over time.

![IMG_5889](https://github.com/transmission/transmission/assets/130483126/46069f15-1aec-4c0c-93f2-8e86d8f7da6e)

**Comment by killemov** [comment]
Ha! Even weirder. In the past I had some BSOD pop up sometimes on a Windows NT 4.0 machine and it turned out I had bad ELCOs on my MOBO. After replacing them it ran fine again.

**Comment by robot468** [comment]
Of course, thank you)

**Comment by killemov** [comment]
> My second macbook is exactly the same model.

As the Voyager 1 system? Wow! :joy:
