### ISSUE TITLE
Wiki pull request on "config files" section

### ISSUE THREAD

**Issue by pantryk** [transmission/transmission#681]
Sory, i am noob and can't find how pull requests on wiki. This file with comment about config files for daemon on windows. I spent more time for find where config really present and think, this information will be useful on wiki.

[Configuration-Files.md.txt](https://github.com/transmission/transmission/files/2265961/Configuration-Files.md.txt)

**Comment by Sylvain303** [comment]
also related to https://github.com/transmission/transmission/issues/435

**Comment by ckerr** [comment]
@pantryk I recently moved the documentation into the docs/ directory here in `electron/electron` for this very reason, to make it easier for people to submit PRs. Could you make a PR for this change?
