### ISSUE TITLE
Transmission-remote SegFault

### ISSUE THREAD

**Issue by simplepad** [transmission/transmission#6816]
### What is the issue?

Transmission-remote (main branch) segfaults when running it with `-l`.

```gdb
1462	            if (tr_variantDictFindInt(d, TR_KEY_id, nullptr))
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
0x000055555565e04e in (anonymous namespace)::value_if<long> (setme=0x0, var=<optimized out>) at /transmission/libtransmission/variant.cc:60
60	            *setme = *val;
```

Here is the offending line:
https://github.com/transmission/transmission/blob/821a6816ef70fb074eac2b6c920562a2fd496418/utils/remote.cc#L1462

Added by https://github.com/transmission/transmission/pull/5608

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

transmission-remote 4.1.0-dev (821a6816ef)

**Comment by lvd2** [comment]
https://github.com/transmission/transmission/pull/6819#issuecomment-2088710004
