### ISSUE TITLE
Allow disabling of dbus in `qt/qt.pro` as in `qt/CMakeLists.txt`

### ISSUE THREAD

**Issue by q3cpma** [transmission/transmission#682]
Hello,

title is pretty explicit. It looks like Dbus is optional, but the logic isn't implemented in qt.pro (which looks like the preferred way to build transmission-qt).

**Comment by mikedld** [comment]
Qt.pro, as well as autoconf-based builds, is deprecated and will be removed at some point in the future. Building all of Transmission with CMake is the preferred way.
