### ISSUE TITLE
rpc spec error?

### ISSUE THREAD

**Issue by trim21** [transmission/transmission#6837]
### What is the issue?

I just test a old transmission version and I find that there are some torrent argument avaiable in 3.00 (bb6b5a062e) but it's documented as "added in Transmission 4.0.0, rpc 17". for example ['file-count', 'group', 'percentComplete', 'primary-mime-type', 'trackerList'].

Is document wrong?

### Which application of Transmission?

Web client

**Comment by killemov** [comment]
I checked the code at the commit you mentioned: https://github.com/transmission/transmission/blob/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd/libtransmission/rpcimpl.c#L818

And none of the fields you mentioned are present. AFAICT the documentation of the RPC-spec has the correct versions on this. Somebody might have used an old commit id on a newer version.

**Comment by trim21** [comment]
thanks
