### ISSUE TITLE
Handling filenames with diacritics and SMB

### ISSUE THREAD

**Issue by metaclam** [transmission/transmission#6884]
### What is the issue?

Encountering all sorts of issues with filenames that contain diacritics.  Torrents with such filenames saved cannot be searched for, do not integrate with MacOS Finder, cannot be verified by the client WebUI, etc.

here are some examples of torrents that cannot be verified:

Northern Cree - Nîtisânak - Brothers and Sister
Cheikh Lô - Né La Thiass
Hüsker Dü - Makes No Sense At All
Urban Tunélls Klezmerband - Zemer Atik

running transmission-daemon in a docker container ([haugene](https://github.com/haugene/docker-transmission-openvpn)).  Synology NAS.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment]
Related to #6704.
