### ISSUE TITLE
Feature Request: Option to Download first and last pieces first 

### ISSUE THREAD

**Issue by Pentaphon** [transmission/transmission#6888]
### What is the issue?

This downloads the header and footer of the file first and makes single files partially readable (making it playable) on file systems at an incomplete stage and is a long-time feature on clients like qBittorrent. I'm sure many people will find it useful in conjunction with the upcoming sequential download feature. 

### Which application of Transmission?

Web, Qt, GTK, Mac, core

### Which version of Transmission?

N/A

**Comment by Rukario** [comment]
This is quite very important feature for sequential downloading. This and sequential feature are closely conjoined I think it's fine to implement this as behind the scenes feature becoming part of Transmission's new sequential feature.
