### ISSUE TITLE
miscalculated downloading-time-seconds vs seeding-time-seconds on new, existing torrents

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6899]
### What is the issue?

in Tr4 mainline:

Something changed in the logic handling seeding-time and downloading-time, likely with 7e8eca0.

If I (re)add a torrent for which the file(s) exist already, the done-date is set to zero. The torrent is never "done" because it never begins downloading.  It remains in a state where donwloading-time-seconds increases forever, but seeding-time-seconds remains at zero.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr4 mainline

**Comment by killemov** [comment]
I just ran a test with [Shift](https://github.com/killemov/Shift) + 4.0.5 (a6fe2a64aa) and I can't reproduce the described behavior. After re-adding it starts seeding after checking. `doneDate` has data and `secondsSeeding` is counting.

**Comment by reardonia** [comment]
> I just ran a test with [Shift](https://github.com/killemov/Shift) + 4.0.5 ([a6fe2a6](https://github.com/transmission/transmission/commit/a6fe2a64aa7eca089f96006cf082a12f0cde937f)) and I can't reproduce the described behavior. After re-adding it starts seeding after checking. `doneDate` has data and `secondsSeeding` is counting.

*mainline* not 4.0.x

**Comment by tearfur** [comment]
I couldn't reproduce on d42d0f3f3f50c01cda1d9f7180d1f4a3ef8aba63 either...

**Comment by tearfur** [comment]
Closing for now due to lack of response.

**Comment by reardonia** [comment]
could you please reopen this.  just have a lot of issues&bugs that I'm slowly working through.  This one is still a priority as its still happening on my systems. I'm trying to find the cause or at least a crisp repro.

**Comment by reardonia** [comment]
@tearfur thanks for reopening.  I found a simple repro.

1) download torrent file.  Add *paused*.  Make sure that the torrent data is NOT at the default download location.
2) because of (1), the torrent is added at 0% complete.
3) torrent-set-location so that the torrent is now pointing at the torrent data.
4) verify.  torrent now 100% complete.
5) start.

The torrent is stuck "downloading", even though it is at 100%. It stays stuck in this 100%-but-still-downloading state thru app restarts, torrent stop/start.

Output from transmission-remote:

```
NAME
  Id: 1237
  Name: ...
  Hash: ########################################
  Magnet: ...
  Labels:

TRANSFER
  State: Idle
  Location: /home/...
  Sequential Download: No
  Percent Done: 100%
  ETA: 0 seconds (0 seconds)
  Download Speed: 0 B/s
  Upload Speed: 0 B/s
  Have: 68.63 GB (68.63 GB verified)
  Availability: 100%
  Total size: 68.63 GB (68.63 GB wanted)
  Downloaded: None
  Uploaded: None
  Ratio: 0.00
  Peers: connected to 1, uploading to 0, downloading from 0

HISTORY
  Date added:       Sat Jun 29 19:30:33 2024
  Date started:     Sat Jun 29 19:34:51 2024
  Downloading Time: 9 seconds (9 seconds)

ORIGINS
  Date created: Wed May 08 15:37:55 2024
  Public torrent: No
  Comment: ...
  Creator: mktorrent 1.1
  Source: ...
  Piece Count: 4091
  Piece Size: 16 MiB

LIMITS & BANDWIDTH
  Download Limit: Unlimited
  Upload Limit: Unlimited
  Ratio Limit: Default
  Idle Limit: Default
  Honors Session Limits: Yes
  Peer limit: 25
  Bandwidth Priority: Normal
```

Conversely, if you added the torrent (not paused) pointed at it's data, the lazy verifier takes over, sets it to 100% complete, and everything is ok.

**Comment by tearfur** [comment]
I think the culprit is here:

https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/libtransmission/torrent.cc#L1825-L1832

I don't know why `recent_change` is needed.

**Comment by tearfur** [comment]
Oh, it was to prevent overriding the `date_done_` value set in these locations:

https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/libtransmission/torrent.cc#L907-L908

https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/libtransmission/torrent.cc#L2270-L2271

**Comment by tearfur** [comment]
Why the ratio calculation was changed from `3.00` to `4.0.0`:
- #2424
- #2770

**Comment by tearfur** [comment]
But then I don't get it, why was this wrapped in an `if` as well?

https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/libtransmission/torrent.cc#L1812-L1820

**Comment by reardonia** [comment]
> But then I don't get it, why was this wrapped in an `if` as well?
> 
> https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/libtransmission/torrent.cc#L1812-L1820

I'm not entirely sure what needs to be fixed here?

**Comment by tearfur** [comment]
Not that wrapping the log statement in the `if` causes a major issue, I was trying to figure out what `recent_change` was intended for.

Usually these seemingly redundant code are leftovers from when they served a purpose.

**Comment by reardonia** [comment]
Yeah, I tried to blame thru to an understanding but failed.

**Comment by tearfur** [comment]
I looked into it again, I think I get it now.

`recent_change` first came from https://trac.transmissionbt.com/changeset/2423, which was then squashed into 1 commit in `main` (then `trunk`), shown here (line 1119 to be exact):

https://github.com/transmission/transmission/blob/76da1185ca2dd15dd5a406cdcd2ff2b1b4ae4686/libtransmission/torrent.c#L1107-L1126

`recent_change` was supposed to be for ensuring that Tr will only announce a `completed` tracker event to trackers if the data was freshly downloaded. Quoting BEP-3:

> An announcement using `started` is sent when a download first begins, and one using `completed` is sent when the download is complete. ***No `completed` is sent if the file was complete when started***.

Everything up to this point makes sense to me. If a torrent was completed by other means, then updated by verifying the torrent, the `started` tracker event sent when restarting the torrent will notify the trackers that we have the full torrent instead.

I see 3 problems so far:

1. `date_done_ = tr_time()` should be moved out of `if (recent_change)`, this is the culprit of this bug:

   https://github.com/transmission/transmission/blob/7f79cb16ee194d58ce665f9319524bc5e6e4f91d/libtransmission/torrent.cc#L1834

2. `mark_changed()` should also be moved out of `if (recent_change)`.

   https://github.com/transmission/transmission/blob/7f79cb16ee194d58ce665f9319524bc5e6e4f91d/libtransmission/torrent.cc#L1833

4. The intention of wrapping the log statement in `if (recent_change)` was probably to prevent a bunch of trace log saying the torrent state changed from `TR_LEECH` to `TR_SEED`/`TR_PARTIAL_SEED` everytime the client started. However, it doesn't consider the case where the state changed from verifying the torrent (and a bunch of other edge cases). I don't have a perfect solution to this, so I'm inclined to just remove the `if`.
