### ISSUE TITLE
macOS gui leaks memory when "sort transfer by activity" is selected

### ISSUE THREAD

**Issue by trendsetting** [transmission/transmission#69]
If you set Transmission (2.92) to sort by activity, there seems to be a memory leak as my system shut it down. 

The work around seems to be to sort by any other method.

Should note, I've seen this issue before in an old version of transmission but it was fixed and this didn't seem to happen in Mac OS 10.11.x with 2.92, but I can't be sure as I usually run the latest version of transmission, but I don't know when I updated to 2.92 (I just upgraded Mac OS to 10.12.x two days ago and it started crashing regularly, all memory overruns).

**Comment by mistakster** [comment]
Hi there!

I can confirm this issue. Also, I found that the application immediately releases all “leaked” memory if I close application window (the app is still running in Dock). Once I open the window, it's continue leaking.

Such leaks happen only if “Sort Transfers by Activity” selected.

**Comment by pouriaalmassi** [comment]
I ran the Leaks Instrument to check for this. After nearly 10 minutes of running the app the instrument detected no leaks. That said, running the static analyzer yielded several possible instances where the project could be leaking memory. I have some changes (unfortunately only made on a clone of the svn repo as it was the only one that made available 2.92) that begin the process of moving to ARC. This could help in squashing some of these leaks. Ping me if the 2.92 branch is mirrored to GitHub, I'll submit a pull request.

**Comment by SwimTommy** [comment]
Thanks for the tip guys! I was frustrated that the memory usage was constantly increasing, eventually exhausting all available memory if left unattended, requiring a reboot of my old Mac Mini server. Switching the sort to date added and closing and reopening the main window immediately fixed the problem, and memory consumption has been constant ever since!

**Comment by mikedld** [comment]
@pouriaalmassi, I don't think ARC will solve the issue. Anyway, in case you didn't see it, there is [TRAC-4822](https://trac.transmissionbt.com/ticket/4822) (we dropped 32-bit support in 2.9x along with OS X 10.6 support). [Tag for 2.92](https://github.com/transmission/transmission/releases/tag/2.92) is certainly here on GitHub, but please base your work on master instead.

Related to [svn14501](https://trac.transmissionbt.com/changeset/14501), [svn14632](https://trac.transmissionbt.com/changeset/14632), [Transmission freezing after Yosemite upgrade](https://forum.transmissionbt.com/viewtopic.php?f=4&t=16519) forum thread.

**Comment by Coeur** [comment]
The last one reporting a reproduction of this issue was on 15 Jan 2017, that's more than 5 years ago.
Today I did not reproduce any leak on macOS 10.14.6 with Transmission master branch when sorting by activity.

I recommend closing this issue.

**Comment by Harm133** [comment]
Ran the latest build via xcode, with the stated settings. Saw allocations an de-allocations as expected:

![image](https://user-images.githubusercontent.com/1971429/194405801-9ec2ef84-5f6a-4f5d-820b-8b8f071b671d.png)

As Coeur said, probably good to close :) @ckerr

**Comment by ckerr** [comment]
@Harm133 thanks for benchmarking!
