### ISSUE TITLE
Transmission-qt freezes on completion of bash script

### ISSUE THREAD

**Issue by jrr45** [transmission/transmission#691]
Calling a bash script on download completion will cause the program UI to freeze indefinitely. This happens even with a empty script or script that just echos some text. The script finishes according to my log file and transmission will continue to download files but the UI must be closed and reopened to be used.  Transmission 2.92 on Kubuntu 18.04.

**Comment by ckerr** [comment]
I'm not able to reproduce this issue in the [nightly builds](https://transmissionbt.com/download). If anyone else is still experiencing this in newer versions of Transmission, please file a new bug with updated information. Thank you!
