### ISSUE TITLE
Transmission-daemon no connectivity over wireguard

### ISSUE THREAD

**Issue by waltmck** [transmission/transmission#6916]
### What is the issue?

I've been having some strange issues with connectivity when I run `transmission-daemon` inside of a network namespace over a wireguard interface. I am using the following setup:
- Transmission runs inside of a systemd network namespace that only has access to a wireguard device `wg0` (as well as a local loopback device). I can verify that only these are the only interfaces visible by running `ifconfig -a`.
- For RPC, I am using `systemd-socket-proxyd` to forward `0.0.0.0:9091` outside of the `netns` to `127.0.0.1:9091` inside of the `netns`. This works fine and I am able to connect to the daemon successfully.
- I changed routing rules so that all traffic originating within the `netns ` is routed through the `wg0` interface, as well as setting `resolv.conf` for the network namespace to make DNS work. I verified that both outgoing traffic routing and DNS are working successfully with  `dig` and `curl google.com` from within the `netns`.
- My VPN service provides a public IP address, so all ports are forwarded to `wg0`. I can verify that this is working correctly by stopping the transmission service, running `nc -l 0.0.0.0 51413` within the `netns`, and then connecting with `nc -v <VPN public ipv4> 51413` (this works for any other port too).

Unfortunately, when I try to actually torrent one of my beloved Linux ISOs, Transmission fails as if it has no internet connection whatsoever (see [logs](https://github.com/user-attachments/files/15809717/logs.txt)). I tried opening port `51413` and running Transmission outside of the wireguard network namespace and was able to torrent successfully, so I have narrowed the problem down to the wireguard interface. Since I am using Nix, I am able to share my entire config reproducibly: [here](https://github.com/waltmck/dotfiles/blob/c25c602abdadde39b41bbe3c3404a0d54cb20ffb/services/cloud/transmission.nix) is the config that works without using a wireguard VPN while [here](https://github.com/waltmck/dotfiles/blob/504c17bbd817f5d3c9d2bbd311b336044e86b09b/services/cloud/transmission.nix) is the config that fails to connect.

I don't have much networking experience, but I'm really puzzled as to why Transmission would fail when as far as I can tell packets are being routed correctly. Could anyone help identify the problem here, or is it a bug?

Thank you!

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

transmission-daemon 3.00

**Comment by kiwixz** [comment]
Logs basically says you can't establish connections, DNS is failing and it can't connect to the trackers.
You probably cant ping/curl or anything from the netns ?  or maybe it is because of the address you bind the socket to ?

**Comment by tearfur** [comment]
You can run Transmission with the environment variable `TR_CURL_VERBOSE` set, then you will see curl debug logs alongside the Transmission logs. Maybe that will tell you what's wrong.

**Comment by waltmck** [comment]
This strangely seems to have started working again without me changing my configuration. Since I

**Comment by SysAdminSmith** [comment]
Hate to resurrect this from the dead but I am experiencing the exact same issue and haven't had the luck for it to fix itself.  Any suggestions?
