### ISSUE TITLE
Probable bugs in QoS/ToS

### ISSUE THREAD

**Issue by neomerx** [transmission/transmission#692]
Hi,

I've been experimenting with [ToS](https://en.wikipedia.org/wiki/Type_of_service) `peer-socket-tos` setting parameter and noticed that it probably sets [DSCP](https://en.wikipedia.org/wiki/Differentiated_services) IP packet parameter incorrectly. I've also noticed that only a fraction of packets has DSCP set.

This [line](https://github.com/transmission/transmission/blob/6410a460ea3acc83a3573f70acf6687d12879d76/libtransmission/net.c#L185) should set `CS1` (0x08 or 0x0a or 0x0c or 0x0e) but sets 0x20 which is `CS4`.

PS As you stick to using ToS values and actually [accept raw values in config](https://github.com/transmission/transmission/blob/eb5d1a79cbe1b9bc5b22fdcc598694ecd4d02f43/libtransmission/session.c#L291) why not just allow setting any DSCP value with it as described [here](https://en.wikipedia.org/wiki/Type_of_service#DSCP_and_ECN)?

**Comment by Artoria2e5** [comment]
The line you cited is pretty new and not included in any of the releases yet. I do agree with your point though -- now that even the old IPv4 values are depreacted and replaced by DSCP/ECN, the wisest way to go is probably just getting rid of the old values and allowing DSCP entry instead.

**Comment by Artoria2e5** [comment]
The values used here are in fact legit, since there are two ECN bits after DSCP bits, requring the whole thing to be shifted by two bits. Confusing, I know, but that's how...
