### ISSUE TITLE
378

### ISSUE THREAD

**Issue by MO77799** [transmission/transmission#6926]
### What is the issue?

<html>
<body>

./run: line 21: 373 Aborted (core dumped) s6-setuidgid abc /usr/bin/transmission-daemon -g /config -c /watch -f | stdout
-- | --
2024-06-17 02:53 | assertion failed: excess_bit_count >= 0 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/bitfield.c:378)

</body>
</html>

### Which application of Transmission?

None

**Comment by tearfur** [comment]
We're not supporting `3.xx` anymore.

**Comment by MO77799** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
