### ISSUE TITLE
Change 403 error info

### ISSUE THREAD

**Issue by x-Felix** [transmission/transmission#693]
I know if I enable rpc-whitelist and access transmission remote gui through a non-whitelist IP, I will get a 403 unauthorized IP error page before authentication. 

Is it possible to totally disable this 403 error page or customize it to a less information page? My concern is, someone scans the open port and tries to connect and get a detail error page tells him this IP:port is serving transmission rpc. If there's any known vulnerabilities relate to transmission, the attacker can pick up the code and initiate the attack directly. 

Maybe I am too cautious about this. Or maybe transmission RPC has been tested secure enough to expose to Internet. Or maybe there's a better way to secure transmission setup I am not aware of. Anyway, I am just thinking if it is possible to give user option to hide 403 error page after setup and configuration is fully completed (similar as syslog message logging levels) . Thanks.

**Comment by ckerr** [comment]
The 403 messages are at https://github.com/transmission/transmission/blob/main/libtransmission/rpc-server.cc#L429  and I agree with the idea of reducing the amount of identifying information that the server leaks. What would be the ideal 403 error message?

**Comment by x-Felix** [comment]
> 

I think as simple as 403 error - forbidden. You don’t have permission to access. That’s all.
