### ISSUE TITLE
Accept-Encoding problematic in scrapes

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6932]
### What is the issue?

I've run into one private tracker that returns a compressed response to a scrape without setting Content-Encoding.

This raises the question of whether Accept-Encoding should be set or not on announces & scrapes.  Given that the hash and compact-peer are incompressible it seems like it may not be worth setting the various compression schemes, and should be `Accept-Encoding: identity` in every case.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr4 mainline, possibly 4.0.x

**Comment by tearfur** [comment]
I don't think we should worry about bugs from other people's software, as long as we stay in-line ourselves.

From RFC 9910, the `Content-Encoding` field is mandatory if the payload is encoded in any way.

> If one or more encodings have been applied to a representation, the sender that applied the encodings **MUST** generate a Content-Encoding header field that lists the content codings in the order in which they were applied.

**Comment by tearfur** [comment]
> Given that the hash and compact-peer are incompressible it seems like it may not be worth setting the various compression schemes, and should be `Accept-Encoding: identity` in every case.

As for this, I don't see a reason to write extra code to differentiate announces/scrapes from other HTTP requests unless there's a significant performance loss from the compression algorithm.
