### ISSUE TITLE
peer-id is discarded from response to tracker announce, not checked during handshake

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6943]
### What is the issue?

Perhaps this was litigated long ago, just want to create record of decision.

[BEP-3](http://bittorrent.org/beps/bep_0003.html) says clearly that the peer-id discovered during handshake should match what the client expects, and "If the receiving side's peer id doesn't match the one the initiating side expects, it severs the connection." This would only apply during outbound handshakes. The one situation where we expect to know a peer-id before handshake is when the peer was sourced from announce, aka TR_PEER_FROM_TRACKER. For some reason, which I cannot find in changelog, Transmission throws away peer-id info from announces. See `tr_announcerParseHttpAnnounceResponse` :

```
            else if (key == "peer id")
            {
                // unused
            }
```

Retaining the peer-id in `tr_pex` would eat up another 20 bytes per peer, basically doubling the size of tr_pex.

For private trackers in particular it may be important to do this check during handshake.

It is noted that BEP-23 says that peer-id is not strictly required.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr2.9+

**Comment by tearfur** [comment]
From BEP-23:

> The peer id does not appear in the compact format. The format has been in use for years and the lack of a peer id has posed no problems.

I guess this is why. I'm not the one who wrote the original code, but I'd be too lazy to write this check too.
