### ISSUE TITLE
[Feature request] Import/export

### ISSUE THREAD

**Issue by pawel-jurczyk** [transmission/transmission#695]
I couldn't find an option to export all the torrent files. I would like to have this option when I'm reinstalling my system or moving to another PC. I can move the folders with the data, but then I need to manually add the torrents to the program. 
There is an option to change the name of the directories, if I'm using it, then it prevents me from having this process painless.

**Comment by xavery** [comment]
How's that different from just moving/copying your entire Transmission config directory? All the torrents currently loaded into Transmission are there in the `torrents` directory, while any alterations are stored as resume data in the `resume` directory.
If you want to port the current state of the torrents into another client, this is an entirely different issue.

**Comment by pawel-jurczyk** [comment]
Right, but this could be supported by the client itself, currently the user would have to go find the config directory and copy/paste the files to the new config dir.
And I've noticed that the destination path in these `resume` files is absolute, meaning, if you've changed your username when migrating to another operating system or PC, it won't be able to track it, unless you go and manually modify these files. So maybe an export feature with the added relative path would solve this issue?

**Comment by ckerr** [comment]
This probably makes more sense as a 3rd-party script than as something built into Transmission itself. It sounds very useful but only in very very specific circumstances.
