### ISSUE TITLE
Pieces bar in dark mode is still white

### ISSUE THREAD

**Issue by Osx2ooo** [transmission/transmission#6958]
### What is the issue?

Can the pieces bar be darkened in the dark UI? It makes perfect sense in light mode, but it's just blinding in dark mode.

<img width="1110" alt="image" src="https://github.com/transmission/transmission/assets/174082784/3fe54f4e-c7a8-4b6b-b182-745b40d1a0da">

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

**Comment by Pentaphon** [comment]
Not a Mac user but that seems like a huge oversight. It should be a very light grey. 

@Coeur thoughts?

**Comment by Coeur** [comment]
If I'm not mistaken, it's just about increasing this value:
https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/macosx/ProgressGradients.mm#L10-L15

**Comment by nevack** [comment]
> If I'm not mistaken, it's just about increasing this value:
> 
> https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/macosx/ProgressGradients.mm#L10-L15

Actually, more like here:

https://github.com/transmission/transmission/blob/ec5296c8dc15c0d51014d67ef93658e5569f354c/macosx/ProgressBarView.mm#L186

Regular progress bars are already fully supported in dark mode, only pieces bar behaves like this, so no need bothering to change gradients.

**Comment by Osx2ooo** [comment]
That looks great, thanks! Looking forward to the update.
