### ISSUE TITLE
download location

### ISSUE THREAD

**Issue by workinganimal** [transmission/transmission#696]
My transmission is running in zyxel nsa 325v2. Everything worked fine till i installed the latest windows version 2.94. Everytime i open a torrent the download location is wrong and the zyxel crashes because of that. The addrss is like this: c:/i-data/md0/download/ . Why the hell is c: in front of that. In options it isn´t there. I have to delete it everytime and so i hope you will fix this soon.

**Comment by mikedld** [comment]
Please search before creating new issues. See #236, #404, #437.
