### ISSUE TITLE
Unable to open Transmission on Arch Linux: Undefined symbol vkCreateXlibSurfaceKHR

### ISSUE THREAD

**Issue by binarykitchen** [transmission/transmission#6967]
### What is the issue?

When clicking on a magnet link on Google Chrome, `journalctl -f` displays this error right away:

```
/usr/bin/transmission-gtk: symbol lookup error: /usr/lib/libgtk-4.so.1: undefined symbol: vkCreateXlibSurfaceKHR
```

Nothing happens but Chrome flickers.

The `paman -QS "gtk"` command shows:
```
local/transmission-gtk 4.0.6-2
    Fast, easy, and free BitTorrent client (GTK+ GUI)
```

I'm on 6.9.7-arch1-1, installed via EndeavourOS.

Not sure that the problem is with libgkt-4, any advice welcome. Or is it a bug, some dependencies are missing?

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.6-2

**Comment by tearfur** [comment]
Doesn't look like Transmission's problems. The error indicated an error within libgtk, and this also seems to be happening to other packages on Arch: https://www.reddit.com/r/mpv/comments/ry9sgi/i_keep_getting_this_error_when_opening_mpv_on/
