### ISSUE TITLE
using on headless server?

### ISSUE THREAD

**Issue by chovy** [transmission/transmission#697]
I am not sure how to override the default config settings for cli and daemon.

I have the files inj $HOME/.config/* . but they seem to be ignored. I want to customize the download, watch and incomplete directories based on the user level.

**Comment by chovy** [comment]
Ubuntu

**Comment by TheLifeGamingYT** [comment]
Try to edit the json located in `/etc/transmission-daemon/settings.json` and tell me the result

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
