### ISSUE TITLE
candidate peers should reset state on stop/start torrent

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6971]
### What is the issue?

(directing this to @tearfur given all the other PEX and peer_info issues we've been chewing on)

Currently, when a peer is designated `is_connectable=false` , the only way (I can see) that causes that peer to become connectable again is for it to connect back to us incoming.  Otherwise, the peer lies there unconnectable forever, and we won't generate outgoing connections to that peer; eg tracker announces will not cause that state to reset, and it will never be probed again. So, if there is a transient network dropout after the beginning of a handshake, the peer will never be retried.  The only event that will cause a retry is to shutdown Transmission and restart.

Recommend one of the following:
(1) allow user to override this behavior by stopping & starting torrents.  That should reset the retained state of all candidate peer_info, at a minimum the is_connectable flag
(2) put a timer on `is_connectable==false` that resets?  i thought this was why the reconnect_interval logic exists but apparently not?
(3) tether the reset of is_connectable (and possible other peer_info state) to a forced tracker re-announce

Ironically (?), within peerMgr, the `connectable_pool` actually contains peers with `is_connectable==false`.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr4.1 mainline

**Comment by tearfur** [comment]
> i thought this was why the reconnect_interval logic exists but apparently not?

No, I agree that having the `reconnect_interval` logic should be enough. The check inside `is_peer_candidate()` for unreachable peer should go.
