### ISSUE TITLE
Transmission freezes for a long time on close, even when no torrents are in the queue.

### ISSUE THREAD

**Issue by 11plustwo** [transmission/transmission#6972]
### What is the issue?

Freezes every time I close it, even when there are no torrents in the queue. It stops responding and I get the beach ball immediately. It will close on its own, eventually, but it takes like 45 seconds for some reason. Have had this issue for quite a while. 

I am on the latest version of Transmission, 4.0.6

I'm on MacOS 13.6.7.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

**Comment by reardonia** [comment]
If you have a LOT of torrents active, it takes quite some time to announce to trackers that your torrents are stopping.

**Comment by Pentaphon** [comment]
> If you have a LOT of torrents active, it takes quite some time to announce to trackers that your torrents are stopping.

He did say that this happens even when there's no torrents in the queue.

@11plustwo got any screen recording of this happening? M series or Intel?

**Comment by 11plustwo** [comment]
I have an intel based mac, but I can't seem to reproduce the issue without any torrents in the queue now, so maybe I'm just dumb. Feel free to close this ticket. If it happens again, and I can record it, I'll open a new issue. Thanks
