### ISSUE TITLE
Character witch make crash transmission

### ISSUE THREAD

**Issue by Mister158** [transmission/transmission#698]
hi guys,

I had a lot of crash, every 3 minutes, dues to a french spécial character in a title.

this caracter is î

Thanks

**Comment by ckerr** [comment]
I think this was fixed by https://github.com/transmission/transmission/commit/99033b067da01c646a3e12a13f8bbcd43a9dd056. If this is still happening for you in a [nightly build](https://transmissionbt.com/download), please open a new issue with bug report information from that new version. Thank you!
