### ISSUE TITLE
Bug in download directory over remote session

### ISSUE THREAD

**Issue by mscho527** [transmission/transmission#699]
In Transmission (Windows) Client connected to a remote daemon on Linux server, there is a bug in download directory:

When the default is set in remote daemon as:
/parent/child

Transmission (Windows) Client changes it as if it was a Windows folder, as:
c:/parent/child

Tested in:
Windows Client 2.94
Linux (Ubuntu) Daemon 2.92

**Comment by mikedld** [comment]
Please search before creating new issues. See #236, #404, #437, #696.
