### ISSUE TITLE
transmission-daemon fails to notify systemd of correct start

### ISSUE THREAD

**Issue by MechMK1** [transmission/transmission#6991]
### What is the issue?

I'm running Ubuntu 24.04 with transmission 4.0.5-1build5. When installing transmission-daemon, it gets stuck at

    Created symlink /etc/systemd/system/multi-user.target.wants/transmission-daemon.service → /usr/lib/systemd/system/transmission-daemon.service.

What happens is that systemd tries (and succeeds) to start transmission-daemon and it successfully responds to queries by transmission-remote. However, after 90 seconds, transmission-daemon is killed again by systemd, stating that it supposedly "timed out".

Here is the full status log:

```
mechmk1@server:~$ systemctl status transmission-daemon.service
× transmission-daemon.service - Transmission BitTorrent Daemon
     Loaded: loaded (/usr/lib/systemd/system/transmission-daemon.service; enabled; preset: enabled)
     Active: failed (Result: timeout) since Fri 2024-07-12 12:14:34 CEST; 11s ago
    Process: 2832 ExecStart=/usr/bin/transmission-daemon -f --log-level=error (code=exited, status=0/SUCCESS)
   Main PID: 2832 (code=exited, status=0/SUCCESS)
        CPU: 154ms

Jul 12 12:13:04 server systemd[1]: Starting transmission-daemon.service - Transmission BitTorrent Daemon...
Jul 12 12:14:34 server systemd[1]: transmission-daemon.service: start operation timed out. Terminating.
Jul 12 12:14:34 server transmission-daemon[2832]: Closing transmission session... done.
Jul 12 12:14:34 server systemd[1]: transmission-daemon.service: Failed with result 'timeout'.
Jul 12 12:14:34 server systemd[1]: Failed to start transmission-daemon.service - Transmission BitTorrent Daemon.
```

Restarting transmission-daemon results in the restart command hanging for 90 seconds, transmission-daemon being available for 90 seconds, and then systemd killing transmission-daemon, thinking that it's failed to start

When I use `sudo -u debian-transmission transmission-daemon -f`, the application runs fine. I believe somehow transmission-daemon fails to notify systemd that it has started correctly

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5-1build5

**Comment by mapelo** [comment]
Change in /etc/systemd/system/multi-user.target.wants/transmission-daemon.service

Type=notify
to
Type=simple

**Comment by MechMK1** [comment]
> Change in /etc/systemd/system/multi-user.target.wants/transmission-daemon.service
> 
> Type=notify to Type=simple

While this is indeed a workaround, it still doesn't fix the underlying bug of no notification being sent. I'm trying to find out if this is a problem with transmission itself or ubuntu's packaged version of transmission

**Comment by tearfur** [comment]
Most likely the Ubuntu package maintainer didn't build with `-DWITH_SYSTEMD=ON`. systemd notification has always been working fine for me.

**Comment by almightiest** [comment]
Could `apparmor` be blocking it?  What does `sudo dmesg | grep transmission` show?

You could also, at your own risk, try transmission 4.0.6 from [here](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/transmission)

**Comment by uhertlein** [comment]
FYI:  
I've got the same issue (Kubuntu 24.04, transmission 4.0.5-1build5).

There are no indications in `dmesg` that anything transmission-related is denied/blocked by apparmor.

**Comment by alyssonnaide** [comment]
I get the same problem, but the daemon stop working after some dependency update, i believe it is the dependency libsystemd0.

**Comment by MechMK1** [comment]
> FYI:
> 
>     * I've got the same issue (Kubuntu 24.04, transmission 4.0.5-1build5)
> 
>     * the `Type=simple` work-around works for me
> 
>     * there are no indications in `dmesg` that anything transmission-related is denied/blocked by apparmor
> 
>     * 4.0.6 from "ppa:ubuntuhandbook1/transmission" has the same behaviour, i.e. it blocks for 90s and then fails; work-around works

Interestingly, if I compile transmission-daemon 4.0.6 with `libsystemd-dev` installed, it works as normal. `ldd` reveals that both my self-compiled binary and the one installed via apt link against `libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0`

In short: I have no idea why the packaged version doesn't work correctly

**Comment by magecu** [comment]
I'm having the same issue.
Like wise Type=simple seams to solve it.
Before the change to simple I could see apparmor lines in syslog with "w" denied on run/systemd/notify

**Comment by alyssonnaide** [comment]
> I'm having the same issue. Like wise Type=simple seams to solve it. Before the change to simple I could see apparmor lines in syslog with "w" denied on run/systemd/notify



> Change in /etc/systemd/system/multi-user.target.wants/transmission-daemon.service
> 
> Type=notify to Type=simple

I made that change, after that i update the system and de transmission-daemon run normally so far.

**Comment by innovara** [comment]
I changed `Type=notify `to `Type=simple` and it works but I'd recommend to use `systemctl edit --full transmission-daemon.service` to edit the service file

**Comment by neoteknic** [comment]
same bug, updated to 40.6 have handbook1 ppa , ubuntu server 24.04, bug happened about 1 week ago. fix by changing to type=simple 
ubuntu update broke something ?

**Comment by DanyChrys** [comment]
yeah work again with this simple modification "type=simple" - use this command to modify:
sudo nano /lib/systemd/system/transmission-daemon.service
in this location "/etc/systemd/system/multi-user.target.wants/transmission-daemon.service" is the shortcut

**Comment by ElizarovEugene** [comment]
Today after updating the system I encountered the same problem on 4.0.6.
But "type=simple" doesn't help

**Comment by Speederer** [comment]
Have you rebooted the system or at least reload the systemd configs?
`systemctl daemon-reload`

**Comment by olimexsmart** [comment]
Just upgraded to 24.04.1 from 22.04.something, and got this error. The installed version after the LTS upgrade is `4.0.5-1build5`.

Fix in second comment works fine. Thanks.

**Comment by whiteonred** [comment]
Thanks a lot! 
1. `Type=notify` to `Type=simple` and it works but I'd recommend to use `systemctl edit --full transmission-daemon.service` to edit the service file
2. `systemctl daemon-reload`
3. `service transmission-daemon start`

**Comment by JoseVegaclic** [comment]
Thank you very much, solved

**Comment by damienbutt** [comment]
Just noticed the same problem today. Updating the systemd unit file to `Type=simple` works for me too.

**Comment by thonixx** [comment]
I have a lot of apparmor lines in syslog:

```
[395201.414562] audit: type=1400 audit(1727277774.392:573): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395202.414715] audit: type=1400 audit(1727277775.392:574): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395203.414885] audit: type=1400 audit(1727277776.392:575): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395204.415035] audit: type=1400 audit(1727277777.392:576): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395205.415212] audit: type=1400 audit(1727277778.392:577): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395206.415363] audit: type=1400 audit(1727277779.393:578): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395207.414491] audit: type=1400 audit(1727277780.392:579): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395207.847269] audit: type=1400 audit(1727277780.824:580): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
[395207.898943] audit: type=1400 audit(1727277780.876:581): apparmor="ALLOWED" operation="sendmsg" class="file" info="Failed name lookup - disconnected path" error=-13 profile="transmission-daemon" name="run/systemd/notify" pid=193060 comm="transmission-da" requested_mask="w" denied_mask="w" fsuid=114 ouid=0
```

As I only see apparmor="ALLOWED" I am not sure if it's related or not. Any ideas?

**Comment by tearfur** [comment]
Hi everyone, just a heads up that someone seems to have gotten to the bottom of this, and have posted a more robust workaround than `Type=simple`.

Please see https://github.com/transmission/transmission/issues/7133#issuecomment-2376246078.

I'm going to close this issue since there is nothing Transmission can do about it.

**Comment by jduartedj** [comment]
I am still experiencing this issue, even after I updated the whole system to newest version Ubuntu 24.10, transmission 4.0.6 and curl 8.9.1-2. Nothing worked. I saw this thread and tried this workaround, and it works!

BTW Transmission can be a "nice guy" and poke the fellows at Ubuntu that this is broken.

**Comment by LucaZeta** [comment]
> `systemctl edit --full transmission-daemon.service` to edit the service file

Best practice from Ubuntu states to use 'systemctl edit transmission-daemon.service'.
It's only needed to learn how override works with services. It's quite simple.

**Comment by ledlamp** [comment]
I'm having problem like this on Ubuntu 26.04, sometimes it works eventually but sometimes it times out. It seems that transmission is just taking a really long time to start up for some reason. When it starts up it uses 100% cpu for a while, until it's ready. If it's soon enough it tells systemd it's running but if it takes too long it times out and systemd stops it. So I change to `Type=exec` to avoid this, but I still wonder why is transmission-daemon taking so long to start up using 100% cpu core? The package version is 4.1.1+dfsg-1ubuntu1
