### ISSUE TITLE
cannot restart single-file torrent with "lost" local data

### ISSUE THREAD

**Issue by reardonia** [transmission/transmission#6994]
### What is the issue?

(Tr4.1 mainline)

Note: this is specific to single-file torrents, ie torrents without a 'files' key. Multi-file torrents recover as expected.

When a torrent's data file is missing, Transmission sets the following error: 
```
No data found! Ensure your drives are connected or use "Set Location". To re-download, use "Verify Local Data" and start the torrent afterwards.
```

However, this recommendation does not work. If some form of the original file (even a zero-byte file) is not found, the torrent is stuck in a forever unstartable state.  After `torrent-verify`, `torrent-set-location`, or both, the torrent remains unstartable and keeps reporting the same error.

If any file with the matching name is found (after torrent location is changed, or if filename subsequently appears in expected location and then verified) then things proceed as expected, even if that file has incorrect length. "As expected" means, eg, that the previously completed torrent is reset ("have none", in the bitfield sense) and downloaded anew.

There may be multiple issues here:
1) Was a bit surprised that the validity-checker doesn't care about length of file.  If the file exists then the torrent is validated and can be started. Perhaps length-of-file should be checked against the length expected?  or is this too complicated with partially downloaded torrents?
2) On daemon startup, only the *first* file in a multi-file torrent is checked for validity.  If all the other files are deleted, the torrent is treated as valid (ie can be started&stopped without incident).

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr4 mainline

**Comment by killemov** [comment]
No! Files should just be there and the verification process checks the content, including length of files. Maybe not check for "validity" at all. There is something to be said for users being able to remove files/folders and just have Transmission recreate them ... with a warning maybe.

**Comment by reardonia** [comment]
> No! Files should just be there and the verification process checks the content, including length of files. Maybe not check for "validity" at all. There is something to be said for users being able to remove files/folders and just have Transmission recreate them ... with a warning maybe. In TM < 4 the error message was: "No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it." I got that so often that it became annoying and I built a `recycle` option in Shift.

But you agree that the existing "frozen" torrent behavior is unacceptable, right?

**Comment by killemov** [comment]
> But you agree that the existing "frozen" torrent behavior is unacceptable, right?

Sure, if it does not work with verify + start.

**Comment by tearfur** [comment]
Cannot reproduce, my steps:

1. Download Ubuntu 24.04 Desktop by torrent. https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso.torrent
2. Move the .iso file elsewhere using `mv`.
3. Pause and start the torrent to trigger the error.
4. Verify the torrent.
5. Start the torrent. The error clears, and the torrent starts downloading again.

**Comment by tearfur** [comment]
Same with "Set Location":

1. Move the .iso file elsewhere using `mv`.
2. Pause and start the torrent to trigger the error.
3. Use `torrent-set-location` to set to the location where the file is.
4. Start the torrent. The error clears, and the torrent starts seeding again.

**Comment by reardonia** [comment]
Hmm, now I cannot repro. I checked this ten different ways before filing issue, so need to track down what changed.  Any chance that you are testing with #6992 in place?

**Comment by tearfur** [comment]
> Any chance that you are testing with #6992 in place?

I did, but I don't think that will have any effect on this issue.

**Comment by reardonia** [comment]
@tearfur are you able to repro with 4.0.6 ?

**Comment by tearfur** [comment]
This behaviour is not in any released version, so it's normal that you cannot reproduce in 4.0.6.

See #83 for some history.

**Comment by reardonia** [comment]
> This behaviour is not in any released version, so it's normal that you "can easily reproduce" in 4.0.6.
> 
> See #83 for some history.

er, I don't follow what you are saying here.  Which "behaviour" is not in any released version?

**Comment by tearfur** [comment]
Starting a torrent from error state after `torrent-verify` is currently only possible in Tr mainline.

`torrent-set-location` should work though.

What are your exact repo steps?

**Comment by SNBogdanov** [comment]
1. Add torrent https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso.torrent
2. Start it
3. Wait for .part file to appear
4. Stop torrent
5. Delete part file
6. Start torrent. You get the error
7. Verify torrent
8. Start torrent. Torrent remains in error state
