### ISSUE TITLE
27inch iMac (2009) running 10.13.6; Can't kill Transmission

### ISSUE THREAD

**Issue by misterhtmlcss** [transmission/transmission#700]
Hi Guys,

I go to turn off Transmission because it randomly stopped downloading; not an issue it happens and when I did for the second time now it's appeared to turn off, but I still find it when I try to relaunch the app. Then I try 'Command+Option+Esc' and it doesn't acknowledge killing the app and it's still present. It's been an hour and it's still sitting in my "Force Quit Applications" box after multiple tries to kill the app. I am unable to find a command line way to kill it and it looks like I'll need to reboot the app.

Let me know if you need anything else.

FYI. I can't open the app right now, so I can't see the version, but I should be current since I'm the guy that always accepts software updates immediately.

Is this a bug? Is this being addressed? Is there a way for me to avoid constantly rebooting?

**Comment by Coeur** [comment]
Well, at this age, kindly adopt Transmission 4 on a recent macOS version (like macOS 13 Ventura).
I'm really not experiencing anything like what you've described.
If it happens in latest versions of Transmission and macOS, you may want to "spindump" the process (you can do so from Activity Monitor) and attach the resulting file in a new issue.
