### ISSUE TITLE
Feature request: Suspend all transfers for torrent maintenance

### ISSUE THREAD

**Issue by Rukario** [transmission/transmission#7022]
### What is the issue?

I thought it might be good idea to have a way to stop and resume all transfers, similar to start all and pause all but doesn't change torrents status, they are preserved. In effect it can be similar to user having closed their Transmission, whether should it shut connections to peers down gracefully or not I don't care, but more importantly Transmission will remain open for the user. It allows turning Transmission into "under maintenance" to manage the torrent list before connecting to peers again.

### Which application of Transmission?

None

### Which version of Transmission?

4.0.6 (38c164933e)

**Comment by tearfur** [comment]
I'm failing to see how this can be useful... On the contrary, I can only see this being confusing to users.

**Comment by BowlesCR** [comment]
Does this materially differ from setting bandwidth limits to 0?

**Comment by tearfur** [comment]
> Does this materially differ from setting bandwidth limits to 0?

Yes, that'll work.

**Comment by Rukario** [comment]
That's something I was thinking could be invoked with, but it takes effect very slowly. Discoverability sucks too.
