### ISSUE TITLE
Historic TRAC system is down

### ISSUE THREAD

**Issue by cfpp2p** [transmission/transmission#703]
Historic [TRAC](https://trac.transmissionbt.com/) system down now for several days.

@tiagoboldt
as https://github.com/transmission/transmission/issues/701

**Comment by bestouff** [comment]
Is there a way to get at the archive ?

**Comment by cfpp2p** [comment]
I have made an archive utilizing https://github.com/hartator/wayback-machine-downloader
 [TRAC](http://transmissionbt.net/trac.zip)

**Comment by mikedld** [comment]
Thanks. Should be up now.
