### ISSUE TITLE
Various configuration directives discrepancies (config & doc)

### ISSUE THREAD

**Issue by Berbe** [transmission/transmission#7038]
### What is the issue?

This is a follow-up to #4822

Missing directives with default value in generated `settings.json`:
* `pidfile`
* `rpc-socket-mode`
* `watch-dir`
* `watch-dir-enabled`

Documentation of default value not matching default value in generated `settings.json`:
* `message-level` (doc: `2`, default: `4`)
* `peer-socket-tos` (doc: `default`, default: `le`)
* `rename-partial-files` (doc: `true`, default: `false`)

Missing documentation about some legacy configuration directives:
* `lazy-bitfield-enabled`
* `peer-id-ttl-hours`
* `proxy-auth-enabled`
* `proxy-auth-password`
* `proxy-auth-username`
* `proxy-enabled`

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6

**Comment by tearfur** [comment]
> Missing directives with default value in generated `settings.json`:
> 
> * `pidfile`
> 
> * `rpc-socket-mode`
> 
> * `watch-dir`
> 
> * `watch-dir-enabled`

These was already in #6499, I've mentioned it to you around the beginning of this year https://github.com/transmission/transmission/issues/4822#issuecomment-1879923432.

> * `message-level` (doc: `2`, default: `4`)
> 
> * `peer-socket-tos` (doc: `default`, default: `le`)

Good call, these does need updating.

> * `rename-partial-files` (doc: `true`, default: `false`)

The default *was* `true` before #4053. It looks to me it was changed by accident.

> Missing documentation about some legacy configuration directives:

Are you suggesting that we should document configuration directives that no longer exists? If so, why?

**Comment by Berbe** [comment]
> > Missing directives with default value in generated `settings.json`:
> > 
> > * `pidfile`
> > * `rpc-socket-mode`
> > * `watch-dir`
> > * `watch-dir-enabled`
> 
> These were already added in #6499, I've mentioned it to you around the beginning of this year [#4822 (comment)](https://github.com/transmission/transmission/issues/4822#issuecomment-1879923432).

I have been looking at the output of a fresh `4.0.6` `settings.json` configuration file (empty initial configuration directory) generated with `transmission-daemon`, as I mentioned in the original message.
If those have been fixed meanwhile: all good!

> > Missing documentation about some legacy configuration directives:
> 
> Are you suggesting that we should document configuration directives that no longer exists? If so, why?

I was not proceeding from personal opinion, but rather from observation of the existing efforts: I noticed [the current documentation](../../transmission/blob/4.0.6/docs/Editing-Configuration-Files.md#legacy-options) is already doing that through a `Legacy Options` section.

I think that might prove helpful for users migrating old `settings.json` (as I did) understanding why some directives are not generated anymore, and maybe what new ones to set, whenever conversion is not done automatically.

If you now decide maintaining this is a burden, then removing this section would clarify your position.

The choice is collectively yours!

**Comment by tearfur** [comment]
> I noticed [the current documentation](../../transmission/blob/4.0.6/docs/Editing-Configuration-Files.md#legacy-options) is already doing that through a `Legacy Options` section.

This section is written before I joined a project, so I might not have the best idea about it. But AFAICT, it does not contain options that were removed, it only contains options that are replaced by other newer options.
