### ISSUE TITLE
Cannot remove torrents from list

### ISSUE THREAD

**Issue by iamwally** [transmission/transmission#704]
Cannot seem to remove anything from my list even after it is fully downloaded and or seeded.  Running on windows 10 64bit.

Thanks

**Comment by ckerr** [comment]
Hey, I'm not able to reproduce this issue and, since it's been years since this issue was filed, the first step would be to try a [nightly build](https://transmissionbt.com/download) and try it out since so much has changed in the interim.

Is this behavior still happening for you in a more recent build?

**Comment by perdomon** [comment]
I'm having what I think is an identical (at least similar) issue:

<img width="1020" height="213" alt="Image" src="https://github.com/user-attachments/assets/26aff435-cd5d-4dbf-8d68-84dca93cce8f" />

This download is finished, but the button to remove or cancel doesn't appear. Here's an example of a different torrent that's also in my library but isn't experiencing the same issue with the disappearing alert options:

<img width="1010" height="180" alt="Image" src="https://github.com/user-attachments/assets/32316aea-e07f-4b1c-8788-5379b03ffcb6" />

Whether I select the trash can or right-click and select "Remove from list," the outcome is the same. Here's my app info:

From the CasaOS dashboard:
linuxserver/transmission
4.0.4

From the web app itself:
Transmission
4.0.4
24077e3511
A fast and easy bitTorrent client
Copyright © The Transmission Project

**Comment by perdomon** [comment]
I paused the file in Transmission, transferred it to a different directory, and restarted the container. After that, I was able to kind of see a "Remove" option to select. The way the alert rendered makes me think it's a browser issue, but I have no way to know. 

<img width="1188" height="195" alt="Image" src="https://github.com/user-attachments/assets/eca22a8b-2fc5-404e-a51a-6c1131eafc9e" />
