### ISSUE TITLE
Transmission daemon log time

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#7046]
### What is the issue?

For transmission-daemon running as service with LOCAL_SERVICE account log contains time in UTC not in local time specified in system.
For daemon running on NAS system time is correct.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1.0-dev

**Comment by killemov** [comment]
Wasn't there a ticket in the old Trac system requesting UTC for all logging? (Can't look it up, Trac is down/unreachable.) It would be better to use UTC anyway if you want to compare logs from different systems.

**Comment by SNBogdanov** [comment]
Using UTC for comparing logs on different systems is less common case then just looking in log file on your local computer to see what happens. So instead of looking for local time (you should know it, right?) you need to convert it to UTC and find recoreds according to converted time. It is not convinient.
