### ISSUE TITLE
[Web GUI] Compact mode - Torrent info panel over torrent list

### ISSUE THREAD

**Issue by Berbe** [transmission/transmission#7050]
### What is the issue?

Since the Web GUI revamp, the torrent info panel is displayed on top of the torrents list, rather than on its side, as before.

One consequence of using the `Compact rows` option is this panel ends up hiding torrents current status (displayed on the right end side of each torrents' line)

### Which application of Transmission?

Web client

### Which version of Transmission?

3e9f5f614a

**Comment by Berbe** [comment]
Tried that though [my main branch](https://github.com/Berbe/transmission/commits/main/) ([complete list](https://github.com/Berbe/transmission/blob/main/CHANGELOG.md) of what has been added to upstream's `main`).

It does not work: the panel still shows on top of torrents, not on their side.

**Comment by Rukario** [comment]
@Berbe

What's the reported viewport width of your browser? The commit set it to be at least 950px for column mode.

**Comment by Berbe** [comment]
Width is 1920px

**Comment by Berbe** [comment]
Damn I thought I was reporting on your PR.
It would be better to continue there, rather than here?

**Comment by Rukario** [comment]
As the context isn't lost I wouldn't mind.

I pulled in your forked repo and it worked fine on Firefox on my main PC and zoomed out Safari on my iPhone 12 Mini. I don't know what else can go wrong on your end.

**Comment by Berbe** [comment]
I am not running the code directly, but connection to a remote daemon.

I do not see the new CSS features into the minimised CSS code:
```CSS
#mainwin-workarea{display:flex;flex:1;flex-direction:row;overflow:auto}
```

**Comment by Rukario** [comment]
See if `@media (width >= 950px){#mainwin-workarea .contract{min-width:570px}}` also present in your minified CSS. I think this will be a good indicator if your setup rebuilt the website correctly.

**Comment by Berbe** [comment]
No sign of `950px`, which was the initial canary I was looking for.

[Building](https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md#building-transmission-from-git-first-time) went through with tests

**Comment by Rukario** [comment]
I'm on Windows so I couldn't verify the doc written for Unix.

The doc for Windows is incomplete, so I'm basically shooting in the dark, I've had to write my own script for convenience.

If you were able to build and run Transmission on your computer then only left for website stuff is to use `npm`, I've had to take `public_html\transmission-app.js`, `public_html\transmission-app.css`, and `public_html\index.html` from elsewhere to where Transmission will serve the website (which is done by my script anyway).

**Comment by Berbe** [comment]
I can confirm the `transmission-app.css` web asset installed server-side does not contain the `950px` canary either.

**Comment by Berbe** [comment]
I am noticing you updated `web/assets/css/transmission-app.scss`, but not `web/public_html/transmission-app.css`.
Is this intentional?

**Comment by Berbe** [comment]
Oh there is [an interesting CMake line](https://github.com/transmission/transmission/blob/main/CMakeLists.txt#L63):
```
tr_auto_option(REBUILD_WEB "Rebuild the web client's generated assets. Requires Node.js and network access." OFF)
```

**Comment by Berbe** [comment]
It worked!
Now I can see you modifications working :)

Since/When the window is on the side, I notice it still disappears when you right-click on a torrent.
It felt logical when the windows was "pop-out", even if annoying.

Now, it feels strange: is it an enhancement to de correlate from your proposal, or could that fit in, as part of the change of behaviour, do you reckon?

**Comment by Berbe** [comment]
Another thing: the global download/upload rates are not being shown anymore, instead of the expected behaviour of being moved left of the new side window

**Comment by Berbe** [comment]
FWIW @Rukario I added specifics for Web assets to my documentation improvements proposal: #7077

**Comment by Rukario** [comment]
@Berbe I'm happy you got it working, I remember trying to enable rebuild web in CMake but could never get it working, I studied and understood that CMake is going to do with NPM for building web, eventually sprung off into standalone setup ready to rebuild web only and not the rest.

You have some other questions and I think you have already found your answer, the CSS is compiled at build, you can also see buildbot circulating this repo doing the CSS generation for us (e.g. 7075).

Thank you for doing documentation improvement, there has never been a good time to update and complete with our findings.

I see that you tested my commit and have some critique to share, your new dev setup really paid off.

**Comment by Berbe** [comment]
It is not a dev setup it's a production build (aka compiled with production flag), and used for my own actually deployed instances.

Driving CMake though flags is actually very easy once the base compilation is set up, and that part was already documented enough.
It's too bad the most difficult part has been done by the developers, providing a way to (de)activate feature through CMake options, but the documentation is missing them out. It really is the last mile to the user which is missing!

There are other flags not being documented, by I am being opportunistic in my process, improving the documentation of what I actually ended up using.

---
To give you a little more details, I am producing my own container images, allowing me to have a deterministic build environment: repeatable and clean (by design).
Using this image, popping a test/ephemeral environment is relatively straighforward.
And once a new recipe has been cooked, rolling over the actual useful instances is done without trouble (and even reverting in case everything falls apart, if that ever happens).
