### ISSUE TITLE
tail: invalid PID: ‘’

### ISSUE THREAD

**Issue by kiritoxjf** [transmission/transmission#7052]
### What is the issue?

A few days ago, after upgrading the Docker container to version 4.0.6, I noticed that it would frequently and sporadically kill the main process and then restart, causing all my seeding tasks to reset to their initial state at startup. This led to my trackers showing duplicate seedings. 
After discovering that others had the same experience with version 4.0.6, I tried downgrading to 4.0.5 and 4.0.4 but found that the issue was not resolved. I am unsure what is causing this problem. 
I run four containers, three of which are relatively high-load, either with over 6000 seeds or with a seeding volume exceeding 60TB. These three containers experienced the issue, while the remaining low-load container did not restart. I want to know if this issue can be avoided through certain configurations or if it is a bug that needs to be fixed.
![Docker Logs](https://github.com/user-attachments/assets/c95cbebc-5b93-4703-bd87-6734cfc5b50d)

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.4 & 4.0.5 & 4.0.6

**Comment by fetzu** [comment]
Hey @kiritoxjf 

The issue you are experiencing is probably due to a change in cURL/libcurl (see #7035). The docker image you are using is probably on cURL 8.9.1. If you are using linuxserver/docker-transmission (for example), try pulling the latest version of the image or revert back to a previous tag (some trackers have outright banned Transmission 4.0.6, so I would suggest using the ":4.0.5-r3-ls240" tag).

Hope this helps.

**Comment by kiritoxjf** [comment]
Hi @fetzu 
Yesterday, I tried switching the image to the latest linuxserver/transmission:4.0.6-r0-ls251 or the 4.0.5-r3-ls240 that you mentioned, but the issue still persists. Based on the Docker logs and the status of the torrents, it continues to self-kill and restart. I'm even beginning to suspect that this situation might be caused by my hardware not being robust enough.
Still, I appreciate your kindness.

**Comment by ivanjx** [comment]
i am using their latest library and i no longer see the crashes. make sure you are using `latest` tag.

**Comment by fetzu** [comment]
@kiritoxjf are you running the 3 containers on the same machine? What happens if you only start a single of the "heavy-load" containers at a time? Does it also crash?

**Comment by kiritoxjf** [comment]
@fetzu 
Yes, I'm running four Docker containers on the same machine. After testing over the past two days, even when I run only one of the 'heavy' containers, crashes still occur, though the frequency has significantly decreased. I suspect it might indeed be due to insufficient hardware performance. I might need to reconsider my seeding strategy.

**Comment by kiritoxjf** [comment]
Over the course of a few days of testing, I was able to roughly pinpoint what might be causing the error. Before, I set the maximum number of connections for my container to 10000, probably due to too many connections, causing the container to crash. After I changed it to 10, I found that there were almost no crashes.
