### ISSUE TITLE
Icon does not show up. 

### ISSUE THREAD

**Issue by CowGivesMilk** [transmission/transmission#7063]
### What is the issue?

OS: Arch Linux 
DE: KDE Plasma 6.1.4
WM: KWin (Wayland)

The icon of transmission-qt does not how. In start button's search typical file icon is placed and when I open it there was no icon in panel (empty space was highlighted) other things worked as expected. 

I can't include screenshots because I added icon myself form application property and now I have a Icon. 

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.6-2

**Comment by tearfur** [comment]
Potentially related to #5173.
