### ISSUE TITLE
v4.0.6 windows speed limit dont work

### ISSUE THREAD

**Issue by devopg** [transmission/transmission#7067]
### What is the issue?

![image](https://github.com/user-attachments/assets/fe796b1a-6b32-4404-9bc7-434491c4eb3b)

![image](https://github.com/user-attachments/assets/bd0ae8c7-7e88-4148-9951-6eea88be131f)

![image](https://github.com/user-attachments/assets/6111467e-432e-4124-a0e2-b224ca44d290)

![image](https://github.com/user-attachments/assets/23458f67-faec-45e7-a2de-eebde82cff4a)

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.6

**Comment by Pentaphon** [comment]
Known issue that was not quite fixed by https://github.com/transmission/transmission/pull/5086

**Comment by tearfur** [comment]
I think this is already fixed by #6937, you saw this after enabling turtle mode and restarting Transmission, right?

Tested on 3e5a77d17603dd6548add3c5b233a4e87d38c577:

![test](https://github.com/user-attachments/assets/7af358f7-22b0-4005-8283-dbff316d3371)

**Comment by burner1024** [comment]
I have Linux with web ui. Set all limits to 0. Turtle or no turtle, download still goes through.
Although doesn't appear to happen without an available webseed.

**Comment by ckerr** [comment]
Use banned + issue closed for [rule violations](https://github.com/transmission/transmission/blob/main/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yml).

> YOU WILL BE BANNED if you include information about pirated torrents.
