### ISSUE TITLE
10x read amplification probably caused by TR_SYS_FILE_SEQUENTIAL

### ISSUE THREAD

**Issue by tkittich** [transmission/transmission#7081]
### What is the issue?

I am having a trouble seeding only 200+ torrents. The seeding speed is around 10-20 MB/s but somehow transmission is reading from ZFS raidz2 disks at around 100++ MB/s. There seems to be around 10x read amplification that should not occur. I've already turned off prefetch `"prefetch-enabled": false` in settings.json .

Probably the cause is using TR_SYS_FILE_SEQUENTIAL where data is not and should not be read sequentially such as in [tr_open_files::get](https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/open-files.cc#L187) , [create_empty_files](https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/torrent.cc#L1834) .

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6, 3.00 running debian 12

**Comment by killemov** [comment]
This is not great. But why are you reporting two versions? Isn't this related to the sequential downloading feature added in 4+?

**Comment by tkittich** [comment]
> This is not great. But why are you reporting two versions? Isn't this related to the sequential downloading feature added in 4+?

The default transmission in debian 12 is 3.00. I've also tried version 4.0.6 from debian testing. Both versions have similar 10x read amplification. So this shouldn't be related to sequential downloading.

**Comment by dechamps** [comment]
I don't think this has anything to do with `TR_SYS_FILE_SEQUENTIAL`. Looking at the code, it looks like `TR_SYS_FILE_SEQUENTIAL` actually does nothing on Linux:

https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/file-posix.cc#L570

`O_SEQUENTIAL` is not a thing on Linux, so it is default to 0 (i.e. no-op):

https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/file-posix.cc#L70

Maybe you're seeing the default behavior of the ZFS prefetcher? Maybe there's a way to disable the prefetcher for these particular reads only?

**Comment by ILoveGoulash** [comment]
Yeah, but fadvise is called when this flag is provided, it seems to me:
https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/file-posix.cc#L587
https://github.com/transmission/transmission/blob/5260331732772d4f11b2b43e080ef7aafccdee88/libtransmission/file-posix.cc#L117

**Comment by dechamps** [comment]
Right, I missed that line indeed. My bad.

**Comment by tearfur** [comment]
I think it makes sense that file descriptors for torrent files should not be opened with `TR_SYS_FILE_SEQUENTIAL`, since by the nature of BT (excluding cases like sequential download), the files will be randomly accessed.

**Comment by killemov** [comment]
> file descriptors for torrent files

Did you mean payload?

**Comment by tearfur** [comment]
This issue hasn't been resolved yet, but I'd just like to say the conversations had in this thread has been some of the most healthy and productive ones I've seen in a while.

We have multiple people studying and discussing the code, then quickly reached a consensus in a cordial fashion.

Good job to every participants here.
