### ISSUE TITLE
Tracker returned error

### ISSUE THREAD

**Issue by tburton2000** [transmission/transmission#7082]
### What is the issue?

Many trackers returned error 522
![Screenshot 2024-08-27 at 12 15 46](https://github.com/user-attachments/assets/25d830de-c803-4225-967f-be4dc33ba13b)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6 (38c164933e)

**Comment by Pentaphon** [comment]
Which trackers? Link to torrents?

**Comment by tburton2000** [comment]
yes, if I verify local data, it helps for 1 minute, then again same error.

**Comment by tburton2000** [comment]
Sorry, 
I don't understand technical terms, 

half of my torrents are displayed with an exclamation mark, they don't distribute, 
although everything worked before. Error 522 appears. 

If you need other information, I can make screenshots. Thanks


￼

**Comment by Stanzilla** [comment]
many trackers banned transmission 4.0.6, you need to downgrade to .5

**Comment by tburton2000** [comment]
Thank you!
 It helped!

S.

**Comment by ryliejamesthomas** [comment]
See #7078.

**Comment by tburton2000** [comment]
Thanks a lot!

**Comment by tearfur** [comment]
Duplicate of #7078
