### ISSUE TITLE
Transmission 4.0.6 is now banned due to bugs in this version. Please either downgrade to 4.0.5 ,please fix next release .

### ISSUE THREAD

**Issue by mmmmm-sbi** [transmission/transmission#7083]
Transmission 4.0.6 is now banned due to bugs in this version. Please either downgrade to 4.0.5 or change to a different client.

please fix next release .

**Comment by killemov** [comment]
Duplicate of #7082, but clear description.

**Comment by ryliejamesthomas** [comment]
It's because of #7078.

**Comment by tearfur** [comment]
Duplicate of #7078
