### ISSUE TITLE
Transmission hardcoded to link against libcrypto 0.9.8 makes build not work with newer openssl

### ISSUE THREAD

**Issue by karypid** [transmission/transmission#71]
This is a follow-up issue, discussed on the forum in: https://forum.transmissionbt.com/viewtopic.php?f=4&t=18178

Transmission's build files seem to have hard-codded the use of libcrypto 0.9.8 som time around version 2.90. As a result, when bulding, it fails to link on newer versions of macports. This is discussed in https://trac.macports.org/ticket/52749#comment:4

Older versions (specifically 2.84) compile and work fine even with the latest version of openssl. Could you please review and hopefully undo the commits discussed in the comment linked above in macports? It seems like the version was pinned intentionally, but this does not seem to be the best option anymore.

**Comment by favadi** [comment]
We should restore the ability to build with newer versions openssl as it usually takes Apple some time to patch the builtin version.

**Comment by mikedld** [comment]
FYI, I've committed CMake files for Mac client recently. Using CMake instead of xcodebuild should resolve the issue as well.
