### ISSUE TITLE
Support for arm64?

### ISSUE THREAD

**Issue by Hozzu** [transmission/transmission#7105]
### What is the issue?

Hello.
Is there any plan for supporting arm64?
Windows on arm becomes more available now.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.6

**Comment by Pentaphon** [comment]
Duplicate of https://github.com/transmission/transmission/issues/4735

**Comment by tearfur** [comment]
Duplicate of #4735
