### ISSUE TITLE
Quitting Transmission on macOS is slow

### ISSUE THREAD

**Issue by plasmacel** [transmission/transmission#7121]
As the title says, quitting Transmission 4.0.6 on Apple Silicon M3 Max, macOS Sonoma 14.6.1 is slow, takes multiple (even 10) seconds.

**Comment by wally-crunk** [comment]
This is a dupe of https://github.com/transmission/transmission/issues/7065

[Dear OP — there is not enough information in the OP to triage the issue.  If there are thousands of torrents in queue, this is normal.  If there are less than 5 torrents in queue, this is not normal.]

**Comment by nevack** [comment]
Yep, duplicate of https://github.com/transmission/transmission/issues/7065
Taking some time to quit is expected, app being unresponsive during that is not.
