### ISSUE TITLE
Assert in tr-lpd.cc

### ISSUE THREAD

**Issue by cronyx643** [transmission/transmission#7125]
### What is the issue?

App quits in ~ minute after launch with
assertion failed: std::size(announce) <= MaxDatagramLength (libtransmission/tr-lpd.cc:643)

Looks like commit [d6f5e60](https://github.com/transmission/transmission/commit/d6f5e60a355a1866f2c0ee5635fd8f64b65de1ac) / pull [6700](https://github.com/transmission/transmission/pull/6700) broke correct size calculation of one infohash line in LPD announcement.

Before commit it was std::size of formatted string fmt::format("Infohash: {:s}\r\n", tr_strupper(info_hash)) with 1 info_hash calculated like diff between announcement with 1 hash and empty announcement.

Now it is just std::size of info_hash_str.

Seems same [6953](https://github.com/transmission/transmission/issues/6953).

Should affect any client wishing to announce > 25 hashes.

### Which application of Transmission?

Qt app on Linux, BSD, etc.

### Which version of Transmission?

4.0.6 [f6e1bb2](https://github.com/transmission/transmission/commit/f6e1bb2d700750266365da1fcc31b1af26bb18cd)

**Comment by tearfur** [comment]
Thanks for the analysis, it's straight to the point.
