### ISSUE TITLE
Disable IPv4

### ISSUE THREAD

**Issue by bernardgut** [transmission/transmission#7129]
### What is the issue?

Is there a way to disable IPv4 and use IPv6 only ? 

Assuming you have full connectivity with IPv6 but IPv4 does not (no NAT). What is the best config? Port shows "closed" eventhough online IPv6 scanners show open. 

How can I disable IPv4 entirely ?

Thanks

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.5

**Comment by tearfur** [comment]
As long as IPv6 scanners can see your port you're fine, no need to disable IPv4 since it is still useful for outgoing connections.

**Comment by Roy-Orbison** [comment]
Isn't binding to an IPv4 address to listen for incoming connections completely separate from making outgoing connections? If you know you can't accept IPv4 incoming then why listen for them? And won't that produce incorrect responses when you tell trackers/peers your listening addresses, and any IPv4 within that message will be guaranteed to be wrong?
