### ISSUE TITLE
Cannot add trackers to a torrent. "Error: error setting announce list"

### ISSUE THREAD

**Issue by RetroViking** [transmission/transmission#7134]
### What is the issue?

If I do something like:
```
transmission-remote -t 1 -td "http://some.tracker.url:80/announce"
```
or
```
transmission-remote --torrent all -td "http://some.tracker.url:80/announce"
```
the command almost always returns "Error: error setting announce list"

On seemingly random occasions, the command succeeds, but most of the time I get this error.

### Which application of Transmission?

transmission-remote

### Which version of Transmission?

4.0.6

**Comment by tearfur** [comment]
If the tracker list didn't change after the command (e.g. if the tracker already exists when you added it), then this error will be returned.

**Comment by RetroViking** [comment]
> If the tracker list didn't change after the command (e.g. if the tracker already exists when you added it), then this error will be returned.

Thank you! Based on this, I was able to find the problem. If I do
```
transmission-remote --torrent all -td "http://some.tracker.url:80/announce"
```
and the first torrent in the list already has that tracker, the rest of the torrents will be skipped even if they don't have that tracker. Can this behavior be modified so that no torrents are skipped?

**Comment by killemov** [comment]
Please read #3226 and some other related issues. The `trackerAdd`, `trackerRemove` and `trackerReplace` fields in the `torrent-set` method of the RPC-spec were also borked from the beginning and they have been deprecated.

**Comment by tearfur** [comment]
I'm afraid we don't have a new command line option in `transmission-remote` that caters to the new API `trackerList` that replaces the deprecated APIs. But that is outside of the scope of this thread.

Do you mind if we close this issue and I create a new issue referencing this thread?

**Comment by RetroViking** [comment]
> Do you mind if we close this issue and I create a new issue referencing this thread?

Fine with me, thanks.
