### ISSUE TITLE
Add file blocklist

### ISSUE THREAD

**Issue by csm10495** [transmission/transmission#7146]
### What is the issue?

Can there be a feature to disable downloading certain files?  I would use it to block certain extensions, though it could be regex based to be more flexible.

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.6

**Comment by killemov** [comment]
You can run a script when a torrent is added when you enable the `script-torrent-done-enabled` and `script-torrent-added-filename` settings.

**Comment by csm10495** [comment]
Is there some other setting that needs to be enabled for that to get run? I have 

```   
    "script-torrent-added-enabled": true,
    "script-torrent-added-filename": "Z:/pathto/script.bat",
```

**Comment by csm10495** [comment]
It sort of looks like https://trac.transmissionbt.com/ticket/5586 wasn't merged? Does this config actually work in current Transmission?

**Comment by csm10495** [comment]
Ok so there was a merge: https://github.com/transmission/transmission/pull/1896/files .. but it looks like a bunch of that stuff no longer exists.. so the feature doesn't work at this point.

**Comment by csm10495** [comment]
My bad. It works, but is just a bit confusing at first. I was trying a torrent that wouldn't fully resolve/start. It seems like metadata has to load THEN this action gets called. That actually makes sense. Anyways I tried with one that works and its all good. Closing out. Thanks.

For people looking at this later: If you want to block certain files, use script-torrent-added and then use rpcs to remove the files you don't like.

**Comment by stevemk14ebr** [comment]
@csm10495 care to share your script?

**Comment by csm10495** [comment]
Unfortunately it isn't really easy to share just that part since its part of a bigger ecosystem of non-public spaghetti code. The gist is, use the `TR_TORRENT_ID` environment variable to figure out which torrent was added, then fetch the files in the torrent via the api, (I use the clutch library for python). Then mark files you don't want to fetch as `files-unwanted`. 

I do it via a regex of files I just don't want to ever download.
