### ISSUE TITLE
Tracker returned error: Passkey not found

### ISSUE THREAD

**Issue by xiataojiaxuan** [transmission/transmission#7148]
### What is the issue?

Does any one know what's wrong with this? How can I fix it?

### Which application of Transmission?

macOS app

### Which version of Transmission?
4.0.5

**Comment by killemov** [comment]
Please remove references to copyrighted material or risk a ban.

**Comment by xiataojiaxuan** [comment]
> Please remove references to copyrighted material or risk a ban.

sorry what you mean?

**Comment by nevack** [comment]
> > Please remove references to copyrighted material or risk a ban.
> 
> sorry what you mean?

Kindly remove screenshot from the issue description

**Comment by xiataojiaxuan** [comment]
> > > Please remove references to copyrighted material or risk a ban.
> > 
> > 
> > sorry what you mean?
> 
> Kindly remove screenshot from the issue description

right, thanks

**Comment by Roardom** [comment]
The error is pretty self-explanatory. Your passkey was not found. So, change your passkey to one that *is* found. If you don't know how to do this, ask your tracker, not Transmission. This is a tracker error, not a client error.

**Comment by xiataojiaxuan** [comment]
> The error is pretty self-explanatory. Your passkey was not found. So, change your passkey to one that _is_ found. If you don't know how to do this, ask your tracker, not Transmission. This is a tracker error, not a client error.

Sorry I really don't know how
