### ISSUE TITLE
RSS downloader

### ISSUE THREAD

**Issue by kburman** [transmission/transmission#718]
Is there any plan for having RSS downloader as other torrent clients offer?

**Comment by williamluke** [comment]
It's possible but development has slowed down here... This feature would definitely keep this project alive for a long time. I looked into ages ago but I didn't have the time or resources to put into it implementing such a feature. This isn't an issue but a feature request, btw. If you have a start on this or an example of it used in another open-source application that would be helpful.

**Comment by b7398564** [comment]
I believe it's the most requested feature on transmission.
Also, why not just take that from qbitorrent system? It just works @williamluke

**Comment by mikedld** [comment]
Not going to happen. Already solved by tools like [FlexGet](https://flexget.com/).
