### ISSUE TITLE
Not Seeding on ASUSTOR NAS

### ISSUE THREAD

**Issue by canufrank** [transmission/transmission#7180]
### What is the issue?

I have 1000s of torrents seeding on my NAS. Recently, about 80% of them disappeared from transmission. The files/downloads are still present on the device (and served on DLNA/Plex), but they are no longer being shared. (ASUSTOR uses a transmission wrapper app called 'Download Center' which updated to v1.1.5.r1323 recently, which indicates it is using 'Transmission 3' but no minor version number.) What is the method to reseed previously downloaded torrents/magnets? 

### Which application of Transmission?

Web client

### Which version of Transmission?

3

**Comment by killemov** [comment]
It looks like the resume and torrent files were removed. Add the torrents again. Point them to the correct location. Verify.

**Comment by canufrank** [comment]
> It looks like the resume and torrent files were removed. Add the torrents again. Point them to the correct location. Verify.

thanks @killemov . where are resume files located? note that i mostly use magnets, not torrent files, and was hoping there was some sort of backup instead of adding the specific torrents again.

**Comment by killemov** [comment]
Magnets are resolved to torrents and that is what is stored. There are no backups of these unless you have manually created them. On Debian the resume folder is located in `/var/lib/transmission-daemon/info`, but it is very possible your version was customized and uses a different location.
