### ISSUE TITLE
transmission (and all bittorrent clients) need outgoing to be opened

### ISSUE THREAD

**Issue by oupala** [transmission/transmission#721]
I struggled with transmission a few days before understanding that I need to set the default policy to open on my ufw firewall.

For ufw, I need to enter the following command:

```bash
sudo ufw default allow outgoing
```

This should be the same for all other bittorrent clients, but this should be clearly mentioned in the documentation.

**Comment by ckerr** [comment]
This probably shouldn't be documented like this, as it's likely to confuse more people than it helps. By default, UFW is set to allow all outgoing connections
