### ISSUE TITLE
Download speed is doubled in main UI when using webseed

### ISSUE THREAD

**Issue by rgaudin** [transmission/transmission#7221]
### What is the issue?

As visible in the screenshot, in a webseed download, the actual download speed is properly reported in the Info/Peers pane but in the main window, the speed displayed is twice the actual one.

<img width="933" alt="Screenshot 2024-10-29 at 09 23 41" src="https://github.com/user-attachments/assets/10e6de62-4e3f-4f30-9e86-7f52702c036b">

I noticed it because my Internet connection is maxed is not capable of such speeds.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6

**Comment by Pentaphon** [comment]
@Coeur @nevack is this actually happening?

**Comment by Coeur** [comment]
To attempt to reproduce:
https://library.kiwix.org/#lang=eng&q=noted
and get the **torrent**, not the magnet.

But for now, the webseed is not sending anything to me, so I don't know.

**Comment by Coeur** [comment]
The incorrect value is from:
https://github.com/transmission/transmission/blob/73f960032676a52084e1a23c3a7e6f87de90c00f/macosx/Torrent.mm#L1430

Where fStat is updated every seconds with:
https://github.com/transmission/transmission/blob/73f960032676a52084e1a23c3a7e6f87de90c00f/macosx/Torrent.mm#L248

The maths for the value is:
https://github.com/transmission/transmission/blob/73f960032676a52084e1a23c3a7e6f87de90c00f/libtransmission/torrent.cc#L1374-L1375

But that bandwidth seems populated twice:
- once from somewhere I don't know
- once from:
https://github.com/transmission/transmission/blob/73f960032676a52084e1a23c3a7e6f87de90c00f/libtransmission/webseed.cc#L266

If I remove that line in webseed.cc, then the total bandwidth is now correct, but the individual speed of each webseed is displayed as zero.
So we need to keep that line (for individual webseeds) and figure out where is the extraneous `notify_bandwidth_consumed` coming from.

**Comment by Coeur** [comment]
@rgaudin can you edit your issue title to clarify it's specific to webseeds?

**Comment by rgaudin** [comment]
@Coeur done 👍

**Comment by Coeur** [comment]
> But that bandwidth seems populated twice:
> 
> * once from somewhere I don't know

Ah, @tearfur found the culprit one, it was in web.cc.
