### ISSUE TITLE
Release notes for 4.0.5 and above missing from `main` branch

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#7222]
### Which application of Transmission?

None

**Comment by jggimi** [comment]
@tearfur - what scope did you intend?

- `README.md` refers to 4.0.4 in an example and that's an easy patch to update.  
- If you meant `docs/Release-Notes.md`, that hasn't been updated with new release information since 2016 -- 2.92.

**Comment by tearfur** [comment]
I meant the `news/` directory. Updating `README.md` would be nice too.

I'm guessing `docs/Release-Notes.md` is a relic from the past that didn't get cleaned up? It has some formatting issues while the release notes in `news/` don't.
