### ISSUE TITLE
Getting windows path for downloads when remoting

### ISSUE THREAD

**Issue by Palku** [transmission/transmission#723]
Connected to remote server(Freenas).
In Preferences -> Downloads
![image](https://user-images.githubusercontent.com/10268487/46256145-0064f900-c4a7-11e8-80be-4eb68a7b7921.png)

When adding .torrent i get this instead.
![image](https://user-images.githubusercontent.com/10268487/46256156-18d51380-c4a7-11e8-8d29-88cb7083eecb.png)

Must change it everytime.
Using Transmission 2.94 for windows.

**Comment by mikedld** [comment]
Please search before creating new issues. See #236, #404, #437, #696, #699.
