### ISSUE TITLE
Missing start at login option, App starts automatically at login

### ISSUE THREAD

**Issue by szl1973** [transmission/transmission#7237]
### What is the issue?

The app starts automatically, and there is no option in the latest version to disable it.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.6 (38c164933e)

**Comment by nevack** [comment]
Transmission itself never enables starting at login by itself.

Are you sure this option is not enabled by you?

<img width="720" alt="image" src="https://github.com/user-attachments/assets/593d988d-eff7-4a4f-b78f-f558219cb653">

Another place to check is "System Settings" > "Login Items & Extensions" > "Open at Login"

<img width="720" alt="image" src="https://github.com/user-attachments/assets/8e497f4d-0bf6-42c6-9027-b48a21e95921">

**Comment by szl1973** [comment]
Hi,

I have only the „Keep in Dock” activated, and the app isn’t listed at the „Open at Login” section.

**Comment by szl1973** [comment]
Hi,After complete uninstall and reinstall the issue disappeared.Feladó: ***@***.***átum: 2024. november 7. 15:13:16 CETCímzett: transmission/transmission ***@***.***>Tárgy: Válasz: [transmission/transmission] Missing start at login option, App starts automatically at login (Issue #7237)﻿Hi,I have only the „Keep in Dock” activated, and the app isn’t listed at the „Open at Login” section.2024. nov. 7. dátummal, 13:38 időpontban Dzmitry Neviadomski ***@***.***> írta:Transmission itself never enables starting at login by itself.Are you sure this option is not enabled by you?
image.png (view on web)Another place to check is "System Settings" > "Login Items & Extensions" > "Open at Login"
image.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
