### ISSUE TITLE
macOS 12 CI needs updating

### ISSUE THREAD

**Issue by tearfur** [transmission/transmission#7274]
### What is the issue?

macOS 12 runner images are unsupported starting from 2024-12-03. Ref: https://github.com/actions/runner-images/issues/10721

I would raise a PR myself, but I don't know if there's any specific Xcode version that we should be using or whatnot.

CC @Coeur @nevack 

### Which application of Transmission?

None

**Comment by Coeur** [comment]
We should use the oldest Xcode version supported by the macOS 13 image on GitHub Actions.
