### ISSUE TITLE
Transmission GUI and daemon not sharing settings on Ubuntu 24.04

### ISSUE THREAD

**Issue by rapperskull** [transmission/transmission#7303]
### What is the issue?

Today I updated from Ubuntu 22.04 to 24.04 and I was having issues with Transmission.

First of all, transmission-daemon was not installed by default, so I had to install it. Then it was not starting, so I fixed it by changing the apparmor profile with the info from here: https://discourse.ubuntu.com/t/systemctl-start-transmission-daemon-timeout/51136

Now the daemon starts, but it looks like the settings are not aligned between it and the GTK/QT GUI. From the GUI I set up transmission remote to use a specific username and password, allowing connections from all IPs.

Instead, I can only connect to the web GUI from the same machine, and it doesn't ask for username and password.

After connecting though, I see none of my torrents. The issue here I think is that the GUI and the daemon are not sharing settings.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Transmission 4.0.5 (a6fe2a64aa)

**Comment by killemov** [comment]
That is because TM only reads the config on startup and writes on shutdown. I assume you pointed both clients to the same config.

**Comment by rapperskull** [comment]
Nevermind, looks like I don't need transmission-daemon at all. Even if I uninstall it, Transmission automatically starts on boot.

The only difference with Ubuntu 22.04 is that there's no icon in the task bar until I manually start the GUI.
