### ISSUE TITLE
4.1.0-beta.1 appears in Sparkle appcast.xml feed

### ISSUE THREAD

**Issue by PeetMcK** [transmission/transmission#7308]
### What is the issue?

Transmission version 4.1.0-beta.1 appears in Sparkle appcast.xml feed. I'm not sure if this was accidental or intended, but there are no other beta versions in the Sparkle feed.

The primary autopkg recipe for this project pulls from the Sparkle feed, so it's now grabbing 4.1.0-beta.1, and not the most recent release.

It does seem as though the Sparkle feed has been and should remain production releases only. Any chance someone could speak to this. 

(As an aside, thank you for all your good work on this super useful project.)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-beta.1

**Comment by tearfur** [comment]
CC @Coeur

**Comment by livings124** [comment]
This was intentional. The beta should only appear when "Include beta releases" in checked in preferences.

**Comment by tearfur** [comment]
There's a report #7312 saying the app prompted for an update despite unchecking "Include Beta Releases".

**Comment by livings124** [comment]
Unfortunately releases before 4.0.6 won't differentiate beta and release. It's a tradeoff for the small subset of users that didn't autoupdate since that release but are seeing an autoupdate prompt during the beta period.

**Comment by PeetMcK** [comment]
@livings124 It appears that the built in ["Channels" feature of Sparkle 2](https://sparkle-project.org/documentation/publishing/#channels) wasn't used for the beta vs stable updates. Is there a requirement that forced "Transmission.app" to use something custom?  
Regardless, even if Transmission is not using the `<sparkle:channel>` functionality would it be possible to add `<sparkle:channel>beta</sparkle:channel>` and `<sparkle:channel>release</sparkle:channel>` to [https://transmissionbt.com/appcast.xml](https://transmissionbt.com/appcast.xml)?
I can see how that might be a big ask, please disregard if it is. Since the releases are differentated on github creating an autopkg recipie from https://github.com/transmission/transmission/releases is less of a lift, but if it fits in your project, it may be best in the long run to use Sparkle's channel functionality.

**Comment by Coeur** [comment]
@PeetMcK Transmission didn't update to Sparkle 2. It's still at Sparkle 1. Feel free to make a PR if you want to update it.
