### ISSUE TITLE
Use a color code  to differentiate between seeding and downloading torrents.

### ISSUE THREAD

**Issue by pkrauss2022** [transmission/transmission#7333]
### What is the issue?

On the GUI both downloading and seeding torrents show in the same color.  It would help if either the progress bar (orange) or the font were different colors for the two.

### Which application of Transmission?

Web client

### Which version of Transmission?

2.92

**Comment by pkrauss2022** [comment]
As soon as the download completed the progress bar could be turned light blue or some other color.  It would make it easier to track progress.

**Comment by Rukario** [comment]
2.92 is old version, would you please try the latest/beta version and report back if you're still having a problem with it? Is there something that is stopping you from running the latest version of Transmission?

**Comment by killemov** [comment]
For an extended discussion see #5648.
