### ISSUE TITLE
Why does Transmission want access to Photos on macOS Mojave?

### ISSUE THREAD

**Issue by ftclausen** [transmission/transmission#734]
I was surprised to see this pop up on macOS Mojave - why would Transmission need access to Photos?

**Comment by ftclausen** [comment]
After some research it looks like this might be due to Mojave's new [app sandboxing requirements](https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave) but confirmation would be appreciated.

**Comment by wiz78** [comment]
That dialog appears the first time an application tries to access a file in _~/Pictures/Photos Library.photoslibrary_ (or something similar, the exact name of the photoslibrary directory depends on the locale)

Could it be that you've configured Transmission to share/save files there or in _~/Pictures/_ and subfolders?

**Comment by mikedld** [comment]
Transmission only stores data in either locations that aren't restricted (e.g. ~/Library/Preferences) or are specified by the user. Please use [forums](https://forum.transmissionbt.com) for support.
