### ISSUE TITLE
Feature request: client-based blocking

### ISSUE THREAD

**Issue by Artoria2e5** [transmission/transmission#735]
Transmission should introduce a feature to disconnect or unprioritize (UL speed, no PEX, you name it) clients based on their software names. The “leechlist” format can be as simple as a plaintext file with one regexp per line. (This is basically #471 with more context)

[Xunlei](https://en.wikipedia.org/wiki/Xunlei) (aka Thunder) is a well-known leecher in much of the P2P world. As a download-only tool, it supports both eMule and BitTorrent protocols, but more frequently does the seeding with a proprietary protocol among its own clients. To facilitate leeching it frequently reports a zero completion % despite, say, having taken a lot of data. It also has a pay-to-access "offline download" functionality, which has its servers leech the files for *you* so the client can just get it through plain HTTP. And of course the servers don't seed back a lot, if any. Many similar "offlining" services are found in China, with e.g. BaiduYun, QQDownload, and many others.

It would be an awful idea to ban Xunlei users based on IP ranges, as it is found all over China and banning the entirity of Chinese IPs is just adding to the Iron Curtain *(cough)* &ndash; the technical complications for P2P (carrier-level NAT, low international bandwidth, generic GFW things) &ndash; for well-behaved users.

* * *

The eMule-side solution to Xunlei and other Leeching clients is DLP (Dynamic Leecher Protection, [source code](https://sourceforge.net/projects/emulextreme/files/DLP/AntiLeech44/)). Transmission probably won't want something that involves loading an entire dynamic library, so let's hope name-based regexp blocklists will do for now. After all, the entire point of making it a C++ module is to match both client names and usernames (which BT doesn't have).

**Comment by yellowbigbird** [comment]
totally agree.
suggest add option, could input some client name user want to block.

**Comment by Auska** [comment]
totally agree.

**Comment by aliyuchang33** [comment]
Agree

**Comment by aliyuchang33** [comment]
Not hard to implement, [sample code](https://blog.zscself.com/posts/66b00f02/)

**Comment by Artoria2e5** [comment]
I am looking at how to do this *right*; it appears that I will need to mimic the way the whole blocklist thing is implemented and probably do a lot of code duplication with it. Is everyone okay with me just putting the extra stuff in blocklist.{c,h} and call it something like a clientblocklist?

**Comment by aliyuchang33** [comment]
That would be easy. I'm happy with existing blocklist mechanism.

**Comment by Hexhu** [comment]
Looks promising and elegant, any updates?

**Comment by GrandArth** [comment]
Before our friend here finishing his/her contribution, remember you can still block most of xunlei client by a proper ip filter.
As implemented here:
https://blog.zscself.com/download/ipfilter.txt
This filter block xunlei/baidu service ip and all chinese ip, you can manually delete those line with CN mark to preclude xunlei/baidu client exclusively.

**Comment by GrandArth** [comment]
Well, again for temp usage, I give my answer with limited zsh/bash experience here.

```bash
    #!/bin/zsh
    Username=yourwebuiaccount
    #transmission webgui的用户名
    Password=yourwebuipassword
    #transmission webgui的密码
    ClientList=(Xunlei Thunder "\-XL0012\-")
    #list of clients you want to block
    ListAddress="/var/www/html/blocklist.txt"
    #blocklist in your apache/nginx directory

    for CertainClient ($ClientList){
    transmission-remote --auth $Username:$Password  -t all -ip |grep $CertainClient |awk '{print $1}' | xargs -L1 -I {ip} echo "{ip}" >> "templist.txt"
    }
    Temp=("${(@f)$(< templist.txt)}")
    #a temp file which will be deleted later
    for EachIp in $Temp
    do
            if [ $(grep $EachIp $ListAddress) ]
                    then
                            echo "$EachIp exist, not adding"
            else
                    echo "$EachIp didn't exist, adding"
                    echo "$EachIp - $EachIp , 0 , Autogen" >> $ListAddress
            fi
    done

    transmission-remote --auth $Username:$Password --blocklist-update
    echo "clocklist updated"
    transmission-remote --auth $Username:$Password  -t all --stop
    echo "current session stopped, starting after 2 seconds"
    sleep 2s
    transmission-remote --auth $Username:$Password  -t all --start
    echo "session started"
    rm "templist.txt"
```

Create a crontab for this script (mine is 10 mins), remember to clean the list once a whlie since most of people have dynamic ip address.

**Comment by OdinVex** [comment]
> Not hard to implement, [sample code]

The post referenced uses a poorly blurred image of IP addresses and should not be posted. The less publicity, the better, considering what that torrent is.

**Comment by ckerr** [comment]
IIRC --  and it's been over a decade since I read the Grokster / MGM findings, so this is fuzzy -- there is legal risk to a software project that has _policy_ on what peers to allow and block. It's very intentional that the Transmission project doesn't recommend any blocklists or have any control about the IP ranges inside the blocklists. For similar reasons, we won't & can't block based on peer-ids.

If third parties want to build together a blocklist of known bad peers, that is your own business and outside the scope of this project.

**Comment by OdinVex** [comment]
> IIRC -- and it's been over a decade since I read the Grokster / MGM findings, so this is fuzzy -- there is legal risk to a software project that has _policy_ on what peers to allow and block. It's very intentional that the Transmission project doesn't recommend any blocklists or have any control about the IP ranges inside the blocklists. For similar reasons, we won't & can't block based on peer-ids.
> 
> If third parties want to build together a blocklist of known bad peers, that is your own business and outside the scope of this project.

"legal risk to a software project that has _policy_ on what peers to allow and block" ...Yeah, no, that's just complete made-up balogni. The option is no different from someone being allowed to require encryption or not. Transmission doesn't have to recommend anything, that wasn't being requested. The *option* for the user to block whoever, based on a list they provide, was. I've seen a number of clients used in ways that mis-report uploads/downloads and even a few that end up forcing trackers to call into question other clients, mostly due to bugs. Some trackers have gone to lengths to ban specific clients because of it. Would prefer the same to prevent wasting bandwidth, but whatever.
