### ISSUE TITLE
Umask Linux permissions are discarded

### ISSUE THREAD

**Issue by godot999** [transmission/transmission#739]
Everytime Transmission creates a file, it doesn't use the access permissions filter (_umask_) set by the user.
Linux users may change the file _~/.profile_ and set the umask with:
`umask XXX`
where XXX is the desired permission flag.
When creating a new file, and when software create new files, that permission should be used.
It is annoying because I have to manually change the permissions of my downloaded files everytime.

**Comment by mikedld** [comment]
You can set `umask` parameter in settings.json to whatever you desire. See [Editing Configuration Files](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations) for more information.
