### ISSUE TITLE
use GtkFileChooserNative in the GTK client

### ISSUE THREAD

**Issue by snaggen** [transmission/transmission#745]
To allow Transmission to run in a tighter sandbox, it should be made to use GtkFileChooserNative.

**Comment by Arxcis** [comment]
**Update**

We did some testing of this over at the flathub-repo https://github.com/flathub/com.transmissionbt.Transmission/issues/31 . It seems like we are half-way there.

**Comment by ckerr** [comment]
If there is any progress on this anywhere, I'd be happy to upstream patches into `transmission/transmisson`

**Comment by mikedld** [comment]
@Arxcis, could you test with current `main` to see if it makes things better? There's been a change in #3916 that switches from custom widget API (which requires access to the window, which native dialogs don't provide) to choice API for the dialog shown when "Open [file]" is triggered.

**Comment by Arxcis** [comment]
Hi @mikedld ! :) Thank you for working on this :clap: 

How do you test `main` inside a Flatpak? Do you have a step-by-step guide somewhere? If not, I will figure it out and post my step-by-step here :wink:

**Comment by mikedld** [comment]
I was under the impression that you know this already :) We're not maintaining Flatpak packages, so I have no idea.

**Comment by Arxcis** [comment]
> I was under the impression that you know this already :) We're not maintaining Flatpak packages, so I have no idea.

I understand :) I have some Flatpak experience. I should be able to figure it out. I just need some help with building and running transmission from source.

This is what I have done so far:
```sh
git clone git@github.com:transmission/transmission.git
cd transmission
git checkout c75c6bf5c815611595079ea3f85e604a28d90ffb  # See: https://github.com/transmission/transmission/commit/c75c6bf5c815611595079ea3f85e604a28d90ffb
git submodule update --init --recursive

mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
sudo apt install libcurl4-openssl-dev libssl-dev            # install missing deps
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..  # try again - success!
make
...
```

I expected to find a `transmission` gtk-executeable after building, but I cannot find it: 
```sh
$ find ./build/ -name "transmission*"
./build/utils/transmission-show
./build/utils/transmission-create
./build/utils/transmission-remote
./build/utils/transmission-edit
./build/daemon/transmission-daemon
...
```

I followed [these steps](https://github.com/transmission/transmission#building-transmission-from-git-first-time) in the README.md. Am I on the right track here @mikedld ? What step am I missing ?

**Comment by mikedld** [comment]
See https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md#debian-11--bullseye for recently updated steps. CI configuration may also be of help: https://github.com/transmission/transmission/blob/48e42ac71e8a9532016d2884bee8cf7568ddd88a/.github/workflows/actions.yml#L409-L431

**Comment by bbhtt** [comment]
> @Arxcis, could you test with current main to see if it makes things better?

4.0.1 (built against GTK4, GNOME 44 beta) is using non-portaled FileChooser everywhere

If it was using portaled Filechooser there would be a "Handling openfile" message in `/usr/lib/xdg-desktop-portal --replace --verbose` once the chooser is opened. but there isn't.

I cannot see the two 'different' FileChoosers as explained here https://github.com/flathub/com.transmissionbt.Transmission/issues/31#issuecomment-734502552
