### ISSUE TITLE
"Insuficient disk space" from wrong disk

### ISSUE THREAD

**Issue by lcvass** [transmission/transmission#747]
I can't resume a torrent while the free space in the partition where Transmission is installed is lower than ~1GB, even if downloading to a different disk. Transmission-gtk for GNU/Linux.

**Comment by mikedld** [comment]
You most probably have incomplete directory enabled, which is where there's insufficient space. The fact that Transmission includes wrong (download-dir instead of incomplete-dir) path in error message is probably the real issue here.
