### ISSUE TITLE
Issue downloading gzip compressed data with webseeds

### ISSUE THREAD

**Issue by ieee8023** [transmission/transmission#753]
Hello,

I think there is an issue when downloading gzip files as webseeds. For example for this file:

$ file iaprtc12.tgz
iaprtc12.tgz: gzip compressed data

When it is downloaded using this torrent:

http://academictorrents.com/details/cf870b196222cf961a01c13999be9e4b7760cef1

I get all these errors and no pieces are correct:

2018-11-04 21:48:22 +0000 torrent.c:3327 [Error] iaprtc12.tgz: Piece 4, which was just downloaded, failed its checksum test
2018-11-04 21:48:28 +0000 torrent.c:3327 [Error] iaprtc12.tgz: Piece 5, which was just downloaded, failed its checksum test
2018-11-04 21:49:22 +0000 torrent.c:3327 [Error] iaprtc12.tgz: Piece 0, which was just downloaded, failed its checksum test
2018-11-04 21:49:22 +0000 torrent.c:3327 [Error] iaprtc12.tgz: Piece 1, which was just downloaded, failed its checksum test
2018-11-04 21:49:22 +0000 torrent.c:3327 [Error] iaprtc12.tgz: Piece 2, which was just downloaded, failed its checksum test

But if I download using wget the pieces are verified as correct.

**Comment by cfpp2p** [comment]
Related to [TRAC](https://trac.transmissionbt.com/ticket/4666)
Accounting for bad content encoding is needed in addition to the corrupt piece strike count of the trac5923-webseed-issues branch --> https://github.com/transmission/transmission/tree/trac5923-webseed-issues

**Comment by cfpp2p** [comment]
Related to [TRAC 4666](https://trac.transmissionbt.com/ticket/4666)
Accounting for bad content encoding is needed in addition to the corrupt piece strike count of the trac5923-webseed-issues branch --> https://github.com/transmission/transmission/tree/trac5923-webseed-issues

**Comment by cfpp2p** [comment]
Transmission asks for the content to be uncompressed:
Accept-Encoding: identity

cf870b196222cf961a01c13999be9e4b7760cef1.torrent
However, the www-i6.informatik.rwth-aachen.de server returns transmission that it will be sending compressed content (even though asked not to by transmission):
Content-Encoding: x-gzip

The content is then un-encoded by libcurl and correctly assuming that the www-i6.informatik.rwth-aachen.de server actually did send encoded content (which it didn't). The www-i6.informatik.rwth-aachen.de server should not send the "Content-Encoding: x-gzip" message if it is not actually encoding the data itself.

ed8a16ebb346e14119a03371665306609e485f13.torrent
Another academictorrent behaves correctly and correctly does not relay transmission a Content-Encoding message when it isn't.

iaprtc99.tgz.torrent
It's not .tgz files that gives transmission the problem and this is demonstrated in this torrent snippet .tgz iaprtc99.tgz.torrent and depicted final log file informational below.

The www-i6.informatik.rwth-aachen.de server should not send the "Content-Encoding: x-gzip" message if it is not actually encoding the data itself. Transmission can't assume and by doing so would break correctly messaged and encoded webseeds.


[test torrents here](http://transmissionbt.net/torrent-samples-753.zip)


LOG FILE extracts for cf870b196222cf961a01c13999be9e4b7760cef1.torrent

* About to connect() to www-i6.informatik.rwth-aachen.de port 80 (#0)
*   Trying 137.226.36.140...
* Found bundle for host www-i6.informatik.rwth-aachen.de: 0x20046f90

* Connected to www-i6.informatik.rwth-aachen.de (137.226.36.140) port 80 (#0)
> GET /imageclef/resources/iaprtc12.tgz HTTP/1.1
Range: bytes=12570624-16760831
User-Agent: Transmission/2.77
Host: www-i6.informatik.rwth-aachen.de
Accept: */*
Accept-Encoding: identity

< HTTP/1.1 206 Partial Content
< Date: Wed, 07 Nov 2018 16:12:06 GMT
< Server: Apache/2.4
< Last-Modified: Thu, 18 Dec 2008 11:28:16 GMT
< ETag: "693333bb-45e507d189400"
< Accept-Ranges: bytes
< Content-Length: 4190208
< Content-Range: bytes 12570624-16760831/1764963259
< Content-Type: application/x-tar
< Content-Encoding: x-gzip
< 
* Error while processing content unencoding: invalid block type
* Closing connection 0
< HTTP/1.1 206 Partial Content
< Date: Wed, 07 Nov 2018 16:12:06 GMT
< Server: Apache/2.4
< Last-Modified: Thu, 18 Dec 2008 11:28:16 GMT
< ETag: "693333bb-45e507d189400"
< Accept-Ranges: bytes
< Content-Length: 4190208
< Content-Range: bytes 8380416-12570623/1764963259
< Content-Type: application/x-tar
< Content-Encoding: x-gzip
< 
* Error while processing content unencoding: invalid distance too far back
* Closing connection 1

< HTTP/1.1 206 Partial Content
< Date: Wed, 07 Nov 2018 16:12:06 GMT
< Server: Apache/2.4
< Last-Modified: Thu, 18 Dec 2008 11:28:16 GMT
< ETag: "693333bb-45e507d189400"
< Accept-Ranges: bytes
< Content-Length: 4190208
< Content-Range: bytes 4190208-8380415/1764963259
< Content-Type: application/x-tar
< Content-Encoding: x-gzip
< 
* Error while processing content unencoding: invalid stored block lengths
* Closing connection 2



LOG FILE extracts for ed8a16ebb346e14119a03371665306609e485f13.torrent

* About to connect() to academictorrents.cloud.seedboxes.cc port 443 (#0)
*   Trying 185.149.90.114...
* Found bundle for host academictorrents.cloud.seedboxes.cc: 0x201810c0

* Connected to academictorrents.cloud.seedboxes.cc (185.149.90.114) port 443 (#0)
* Connected to academictorrents.cloud.seedboxes.cc (185.149.90.114) port 443 (#1)
* Connected to academictorrents.cloud.seedboxes.cc (185.149.90.114) port 443 (#2)
* Connected to academictorrents.cloud.seedboxes.cc (185.149.90.114) port 443 (#3)
* Connected to host1.academictorrents.com (85.17.75.141) port 80 (#4)
> GET /share/cs231n-spring2017/Lecture%201%20%5F%20Introduction%20to%20Convolutional%20Neural%20Networks%20for%20Visual%20Recognition-vT1JzLTH4G4.mp4 HTTP/1.1
Range: bytes=29331456-33521663
User-Agent: Transmission/2.77
Host: host1.academictorrents.com
Accept: */*
Accept-Encoding: identity

< HTTP/1.1 206 Partial Content
< Date: Wed, 07 Nov 2018 16:42:50 GMT
< Server: Apache
< Last-Modified: Fri, 21 Sep 2018 03:53:29 GMT
< ETag: "919c82e-5765995168040"
< Accept-Ranges: bytes
< Content-Length: 4190208
< Content-Range: bytes 29331456-33521663/152684590
< Content-Type: video/mp4


LOG FILE extracts for iaprtc99.tgz.torrent

* About to connect() to transmissionbt.net port 80 (#0)
*   Trying 45.40.165.30...
* Found bundle for host transmissionbt.net: 0x20151398

* Connected to transmissionbt.net (45.40.165.30) port 80 (#0)
> GET /iaprtc99.tgz HTTP/1.1
Range: bytes=49152-65535
User-Agent: Transmission/2.77
Host: transmissionbt.net
Accept: */*
Accept-Encoding: identity

< HTTP/1.1 206 Partial Content
< Content-Type: application/x-compressed
< Last-Modified: Tue, 06 Nov 2018 06:39:02 GMT
< Accept-Ranges: bytes
< ETag: "364926689b75d41:0"
< Server: Microsoft-IIS/7.5
< X-Powered-By: ASP.NET
< Date: Wed, 07 Nov 2018 16:55:17 GMT
< Content-Length: 16384
< Content-Range: bytes 49152-65535/4052720

**Comment by ieee8023** [comment]
> The www-i6.informatik.rwth-aachen.de server should not send the "Content-Encoding: x-gzip" message if it is not actually encoding the data itself. Transmission can't assume and by doing so would break correctly messaged and encoded webseeds.

I see the issue. There are many occasions where webseeds will do this and we end up putting the data somewhere else. I would prefer if Transmission would accommodate these "broken" servers because even though they are not following the standard they are free bandwidth for our data! These webservers running in CS departments are probably not going to upgraded anytime soon.

What if after a failure of the webseed an attempt was made to ignore the content encoding and try again? This shouldn't impact correct webseeds. Maybe the code logic can go: If webseed fails for code 998 then add it again with "forced content-type mode" where you force curl to ignore the stated content response and assume it is identity.

**Comment by cfpp2p** [comment]
@ieee8023

**CURLOPT_HTTP_CONTENT_DECODING, 0L**

Turning off content decoding does indeed work for the exampled torrent.

The trac5923-webseed-issues branch --> https://github.com/transmission/transmission/tree/trac5923-webseed-issues
will need quite some work to function as in my fork's webseed reimplementation.

By the way, the magnets at http://academictorrents.com/browse.php should have an `&ws=`
i.e. `&ws=http%3A%2F%2Fserver.webseed.org%2Fpath%2Fto%2Ffile`

**Comment by cfpp2p** [comment]
The most important thing to bring some stability for webseeds at  transmission here, is to make some changes to `web.c` `writeFunc()` when such cURL errors result. Stability exampled for the gzip tgz encoding https://github.com/cfpp2p/transmission/compare/2.77plus14734-14-2...svn/trunk

**Comment by cfpp2p** [comment]
The most important thing to bring some stability for webseeds at transmission here, is to make some changes to `web.c` `writeFunc()` when such cURL errors result. Stability exampled for the gzip tgz encoding https://github.com/cfpp2p/transmission/compare/2.77plus14734-14-2...2.77plus14734-15-2

**Comment by ckerr** [comment]
@cfpp2p do you want to make a PR for this for `main`?
