### ISSUE TITLE
howto run info add to readme

### ISSUE THREAD

**Issue by xenpac** [transmission/transmission#756]

**Comment by xenpac** [comment]
can you add some info on how to run transmission together with i2pd in the readme.
howto enable Qt interface...

**Comment by mikedld** [comment]
It's not something we currently officially support, so there's nothing to add. You need to turn to either [l-n-s/transmission-i2p](https://github.com/l-n-s/transmission-i2p/) maintainers (?) or [forums](https://forum.transmissionbt.com/) for clarification.
