### ISSUE TITLE
Provide transmission-cli with Homebrew formula

### ISSUE THREAD

**Issue by mcandre** [transmission/transmission#759]
Could we add transmission-cli to the Homebrew formula for transmission? So that we can use the standard CLI for transmission on macOS :)

**Comment by mikedld** [comment]
If you're talking about transmission-cli binary, it's deprecated. If you're referring to the transmission-remote binary (and other CLI tools) that is part of "transmission-cli" package in some Linux distributions, the request is misdirected since we don't manage the Homebrew formula ourselves.
