### ISSUE TITLE
Plays sound even if disabled in System Preferences

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#761]
When a transfer is finished, a sound effect is played even though "Play sound for notifications" is disabled in System Preferences > Notifications.

Transmission 2.94 (d8e60ee44f)

**Comment by mikedld** [comment]
Transmission has its own settings for that.

![image](https://user-images.githubusercontent.com/298203/48432328-1f80c700-e785-11e8-80ae-5d4df35325ec.png)
