### ISSUE TITLE
Extend Web-Interface

### ISSUE THREAD

**Issue by JustMyGithub** [transmission/transmission#763]
I love transmission for its low footprint, but there are some features I really miss from utorrent 2.x:
- show "added on" and "completed on" (what is age? creation of torrent? added on?)
- tracker-category "none" or at least "sort-by-tracker
- Web-UI: status-categories verify and error (qt gui has these view filters, but webui not)
- Web-UI: show numbers next to the view filter in the dropdown-menus

Maybe I just don't find these features or there are other tickets about those that I have not found - if so, let me know :)

**Comment by chchia** [comment]
I am using Transmission Remote GUI, you should give it a try.

**Comment by chchia** [comment]
and i also recommend you to use
https://github.com/ronggang/transmission-web-control

to replace the internal webui.

**Comment by elboletaire** [comment]
I also would love to see updates on the web gui, but I'm not really sure about what transmission developers have planed for it, as there are some PR related to the web gui which are not being accepted (like #490, #752, #559, #515, #349... there are many).

So... I'd like to take this opportunity to ask if there are any plans, at all, for the web UI? It makes sense for me to leave transmission only with the RPC protocol, and split the web ui into a different project (doing so, would be easier for others to collaborate).

**Comment by Danielperalta07** [comment]
> [](https://github.com/ronggang/transmission-web-control)
> 
> to replace the internal webui.

Definitely, you should check out this project!
![capture](https://user-images.githubusercontent.com/40923874/48640367-a02a0800-e9bd-11e8-9281-1a098f593dcc.PNG)

**Comment by elboletaire** [comment]
Stop spamming that. Doing it once was enough.
