### ISSUE TITLE
[ISSUE] [BUFFER] [SYSCTL.D] Kernel not applying SYSCTL.D !

### ISSUE THREAD

**Issue by Danielperalta07** [transmission/transmission#764]
Hello, I'm having the following issue:

**Packages:** 
[transmission-daemon-openssl - 2.94-2]
[transmission-web - 2.94-2]

**Machine/System**
[Router-MIPS] / [Linux version 3.4.113 (padavan)] -> [Entware]

**Error:**
[UDP Failed to set receive buffer: requested 4194304, got 1966080 (tr-udp.c:84)]

**Solution:**

1 - [editing /opt/etc/sysctl.d/20-transmission.conf]

modifying the values to:

`net.core.rmem_max = 16777216 `
`net.core.wmem_max = 4194304`

2 - applying changes:

 sysctl -p /opt/etc/sysctl.d/

3 - restarting the transmission's daemon

works fine!!

[**NEW PROBLEM**]

This manual process, steps 2-3, are necessary on every reboot because kernel isn't applying `/opt/etc/sysctl.d/` automatically on boot. Also I cannot create a `/etc/sysctl.d/*.conf` because system automatically deletes( don't know why =/ ) created files on this directory.

SO THE MAIN PROBLEM HERE ( i think ) IS `/opt/etc/sysctl.d/` NOT BEING AUTOMATICALLY APPLIED ON BOOT.

Tried some solutions found on web but, since entware is a different system didn't have success.

Thanks in advance for the time to read and support!

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. This is not an issue with Transmission itself.
