### ISSUE TITLE
transmission AND i2p

### ISSUE THREAD

**Issue by xenpac** [transmission/transmission#768]
It seems transmission is a normal Bittorrent.
how can you configure it to run over i2p only.
thanks

**Comment by xenpac** [comment]
It seems transmission is a normal Bittorrent.
how can you configure it to run over i2p only.
thanks

**Comment by mikedld** [comment]
I see you're already familar with [l-n-s/transmission-i2p](https://github.com/l-n-s/transmission-i2p). There's nothing else to my knowledge. If you have any further questions, please use [forums](https://forum.transmissionbt.com/).
