### ISSUE TITLE
Transmission daemon - variable download speed

### ISSUE THREAD

**Issue by su30** [transmission/transmission#778]
Variable download speed while downloading a popular torrent (over 200 seeds).

Daemon on router:
CPU MT7621A 880 MHz, 2 core
RAM 256 MB DDR3

ISP speed 50 Mbit/s.

Screen from webUI of my router

<img width="515" alt="2018-12-10 13 35 39" src="https://user-images.githubusercontent.com/9026538/49728570-30d5ca00-fc84-11e8-97ba-df76e99bf1fb.png">

Downloading with rtorrent client 

<img width="579" alt="rtorrent" src="https://user-images.githubusercontent.com/9026538/49728840-e56feb80-fc84-11e8-983b-81be4ed770ca.png">

Screen from console with `top` command

<img width="1088" alt="2018-12-10 13 39 14" src="https://user-images.githubusercontent.com/9026538/49728635-5cf14b00-fc84-11e8-9db5-dc04cb32f0a3.png">

**Comment by ckerr** [comment]
Topic moved to #2462.
