### ISSUE TITLE
dht-0.26 is out

### ISSUE THREAD

**Issue by jech** [transmission/transmission#782]
Dht-0.26 is out, and it fixes a rather important bug.  Please update.

**Comment by sandrotosi** [comment]
@mikedld do you think this can be included in a (possibly soon) new release of transmission? Debian is about to freeze for the upcoming stable release, so it'd be great to have a new transmission to pick up recent changes. thanks!

**Comment by sandrotosi** [comment]
JFYI i'm about to update dht.c in Debian to have `if (want <= 0)`

**Comment by jech** [comment]
> Out of curiosity, what is the bug?

We don't send nodes in response to get_peers or find_node unless there's
an explicit want parameter.  The result is that we prevent other nodes
from finding their targets, which might endanger the integrity of the DHT.

This is particularly worrying for the IPv6 DHT, where we are the majority
of the nodes (BEP-32 is only implemented by us, Tixati and Vuze).

**Comment by cfpp2p** [comment]
@sandrotosi 
https://github.com/jech/dht/commit/190517533c10db9da16b9ed2bfaceb80a4f872b6 incorrectly changed `parse_message()` returned want value when the message did not contain `want`.
This change took place **after** the stable release of 0.25 https://github.com/jech/dht/commits/master?before=190517533c10db9da16b9ed2bfaceb80a4f872b6+35
Be sure of what dht revision before changing just `send_closest_nodes()` `if (want <= 0)` 
ref: https://github.com/cfpp2p/transmission/blob/aaadaf0561b741d0c394e158fbac5271ab27447f/third-party/dht/README-0.26-DHT.txt

**Comment by jech** [comment]
This is correct -- the bug was introduced after 0.25, and does not appear to be in any stable release.

My apologies, it looks like I panicked uselessly.
