### ISSUE TITLE
How to set seeder in my vps for the created torrent? 

### ISSUE THREAD

**Issue by gitsnippet** [transmission/transmission#785]
I want to create a torrent for a file on vps and download the target file from local pc  with torrent created.    
In my vps.    
The target file located in `/tmp/fly.mp3`.      
1.Prepare transmission and mktorrent.

    yum install epel-release
    yum install transmission-daemon
    yum install transmission-*
    yum install  mktorrent

2.Create torrent with mktorrent.

    mktorrent                                        \
    -a  http://share.camoe.cn:8080/announce          \
    -a  udp://tracker.torrent.eu.org:451/announce    \
    -a  http://t.nyaatracker.com:80/announce         \
    -o  /tmp/test.torrent  fly.mp3

It doesn't matter that i  omit many `-a http://url:announce` in the command posted here,really there are as many as 50 tracker servers added in mktorrent command.   

3.Open firewall for port 9091.

    sudo firewall-cmd --zone=public --add-port=9091/tcp --permanent
    success
    sudo firewall-cmd --reload
    success

4.Start transmission-daemon.

    systemctl start transmission-daemon   

In local pc.

    scp  root@vps_ip:/tmp/test.torrent   /tmp

I got the torrent file in vps from local pc,then to open the transmission on local pc ,load the torrent file ,start to download the target file `/tmp/fly.mp3` in vps.

[https://i.stack.imgur.com/iSZXh.png](url)

It shows that 

    Tier 3
    http://t.nyaatracker.com:80
    Last Announce: Today 06:55:58 PM (got 1 peer)
    Next announce in 12 minutes
    Last Scrape: Today 06:55:58 PM
    Seeders:	0
    Leechers:	2
    Downloads:	N/A

I have done all things.

    1.Start transmission-daemon on vps 
    2.Firewall is open on vps
    3.Target file is in the `/tmp/fly.mp3` on vps.

How can i set seeders on vps then?

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support.
