### ISSUE TITLE
Use the latest translations

### ISSUE THREAD

**Issue by scootergrisen** [transmission/transmission#786]
I was trying to figure out why the Transmission translation was not fully translated on https://translations.launchpad.net/ubuntu/ when it have been fully translated on Transifex for a while.

It says Transmission 2.94 was released 1 May (2018 i guess) on:
https://github.com/transmission/transmission/releases/tag/2.94

In the .po files it says 2012.
POT-Creation-Date: 2012-02-03 15:22-0600

So it seems strange if there have been no change in translations for between 2012 and 2018 so could someone check to see if there are problems?

**Comment by mikedld** [comment]
Transifex and Lauchpad are two independent systems, not sure what you mean by citing the latter. Sometime during preparations for the next major release, translations will be exported from Transifex and committed here; Launchpad is no longer used for translations and thus will not be affected by these actions.

**Comment by scootergrisen** [comment]
I just checked Ubuntu translations and wondered why Transmission was not fully translated there.
So have the translations from Transifex not been used at all yet?

**Comment by mikedld** [comment]
Again, despite there being a Transmission project on Launchpad, it's not being used for translations and so it's not a good idea to check translations state there. Not now, not ever in the future.

Translations from Transifex have not been a part of any release yet but were already imported a few times. If you check the files in master you'll see headers contain

> POT-Creation-Date: 2017-05-19 22:53+0300
