### ISSUE TITLE
If torrent is added during retrieving magnetized metadata, retrieve the metadata from the torrent

### ISSUE THREAD

**Issue by Mikaela** [transmission/transmission#787]
Currently when I first add a magnet link that doesn't start downloading or retrieving the metadata, I have to remove it from Transmission before I can try adding the .torrent file, because Transmission either says that the torrent is already downloading or only renames the torrent as `.torrent.added`.

* transmission-daemon 2.94 (d8e60ee44f)
* Debian GNU/Linux buster/sid

**Comment by ckerr** [comment]
This is a good idea and implementing it  would be a little easier now with the `tr_magnet_metainfo` refactor that landed a month ago. If anyone wants to PR this, it would just need new code in `tr_torrentNew()` that checks iff `duplicate_of` exists _and_ it has no metainfo _and_ the new torrent being added does, the copy the metainfo over with `setMetainfo()` before returning

**Comment by ckerr** [comment]
Duplicate of https://github.com/transmission/transmission/issues/65
