### ISSUE TITLE
Dark-Mode Support

### ISSUE THREAD

**Issue by z1tr0t3c** [transmission/transmission#788]
Dear Transmission-Team,

Is it possible to add support for Mojaves Dark-Mode?

Best regrads,
Falk Rismansanj

**Comment by mikedld** [comment]
It certanly is, and it did already happen. See #757.

**Comment by ellipticaldoor** [comment]
When it will be released?

**Comment by 1343starscream** [comment]
possible date of release?

**Comment by ldexterldesign** [comment]
👋 https://github.com/transmission/transmission/issues/644#issuecomment-601979132
