### ISSUE TITLE
Add support for reading X-Forwarded-For header for "rpc-whitelist"

### ISSUE THREAD

**Issue by driesmp** [transmission/transmission#792]
Transmission does not support reading the X-Forwarded-For header for RPC-whitelist addresses.
To identify the original IP address I add the header X-Forwarded-For altough I noticed that transmission does not use this header to determine "friendly whitelisted IP addresses". This because following settings result in unauthorized. 

"rpc-whitelist": "10.0.0.*"
"rpc-whitelist-enable: yes"

10.0.0.* are my LAN IP addresses that are using the proxy to reach transmission.

**Comment by ckerr** [comment]
Seems like this would invalidate the whitelist feature? It's easy to forge an `X-Forwarded-For` header this would be a significant security hole.
