### ISSUE TITLE
arm7h: Timeout only when authentication is enabled and other weird behaviours

### ISSUE THREAD

**Issue by doronbehar** [transmission/transmission#793]
I'm experiencing very weird and inconsistent behaviour when using `transmission-daemon` and `transmission-remote` on a Raspberry-pi 3 with arm7h, it's running headless.

The packages (without GUI) were installed from the official repositories of Arch Linux for ARM - https://archlinuxarm.org/packages. Here is the build script - https://archlinuxarm.org/packages/armv7h/transmission-cli/files/PKGBUILD. No special flags were used in `./configure` besides `--prefix=/usr`.

The main problem is that the `transmission-daemon` process sometimes doesn't exit when it gets `^C` or `SIGQUIT` from systemd, resulting in the need to kill it with `SIGKILL`.

Additionally, another problem is that when RPC authentication is required, right after the `transmission-daemon` process has started, the client can connect to it once but when trying to connect to it another time, it reaches timeout and it seems that **because of this** `transmission-daemon` can't quit gracefully - as if because it didn't finish to serve the last client which tried to reach it.

Even more weirdly, if I turn off RPC authentication, I don't get a timeout from `transmission-remote` when running it for a 2nd time! **But**, it still won't quit when it gets `SIGQUIT` after it had 1 connection  or more.

I tried to run `transmission-daemon` in a console with `--log-debug` but no mention of clients' connections was there so I couldn't find any clues myself.

BTW I'm running Transmission on a x86_64 machine with Arch Linux as well and I don't experience the same issues as with the ARM version.

Thanks.

**Comment by ckerr** [comment]
Much of the RPC code was rewritten for Transmission 4.

Is this still happening in 4.0.0-beta.1 or newer?

**Comment by doronbehar** [comment]
> Much of the RPC code was rewritten for Transmission 4.
> 
> Is this still happening in 4.0.0-beta.1 or newer?

Thanks for the update, I don't have that Raspberry Pi I tested transmission with back then so I can't test this now.
