### ISSUE TITLE
Could not connect to https tracker

### ISSUE THREAD

**Issue by Alhaitham** [transmission/transmission#806]
Windows 10 Enterprise 10.0.14393 64bit

Transmission-2.94+-r4671276450-x64 Daemon

Transmission Remote GUI 5.15.4

HTTPS

![clipboard02](https://user-images.githubusercontent.com/7531458/50045463-e301fd00-009b-11e9-8224-78f5097fa9a8.png)

HTTP

![clipboard04](https://user-images.githubusercontent.com/7531458/50045464-e6958400-009b-11e9-97bb-16934b743f6c.png)

_Originally posted by @Alhaitham in https://github.com/transmission/transmission/issues/446#issuecomment-447586292_

**Comment by Alhaitham** [comment]
Same with

Transmission-2.94+-r4a4233feae-x64

![clipboard02](https://user-images.githubusercontent.com/7531458/51051119-80891780-15db-11e9-8edc-67ff81062927.png)

**Comment by mikedld** [comment]
No need in knowingly (!) creating duplicates.

**Comment by Alhaitham** [comment]
Thanks.
