### ISSUE TITLE
What does recently-active means?

### ISSUE THREAD

**Issue by prehawk1999** [transmission/transmission#809]
In rpc-spec, I see there is a "recently-active" option to set in torrent-get.
How exactly does it behave? If I have 100 download tasks and 15 of them is added two days ago with non-zero-progress, no-speed, what is the return?

**Comment by xavery** [comment]
`recently-active` is controlled by the compile-time define `RECENTLY_ACTIVE_SECONDS`, which is currently set to 60. Sadly, it doesn't look like there's any way to change it at runtime.
The code for this lives in [rpcimpl.c, lines 153-165](https://github.com/transmission/transmission/blob/master/libtransmission/rpcimpl.c#L153).

**Comment by ckerr** [comment]
Closing as answered

**Comment by maicWorkGithub** [comment]
As version 3.0.0 add `label` field, should `recently-active` return task which label updated?

**Comment by mikabytes** [comment]
This is currently controlled by [`RecentlyActiveSeconds`](https://github.com/transmission/transmission/blob/main/libtransmission/rpcimpl.cc#L52), the value remains at 60 seconds.

**Comment by onlyJinx** [comment]
> As version 3.0.0 add `label` field, should `recently-active` return task which label updated?

This issue still hasn’t been addressed in TR 4.x  @ckerr , do you have any update plans for this issue?
