### ISSUE TITLE
transmission2.92 have not speed on arm platform

### ISSUE THREAD

**Issue by jalin107** [transmission/transmission#813]
transmission2.92 have not speed on arm platform

![1](https://user-images.githubusercontent.com/17920700/51103219-e7494380-181c-11e9-86ad-9269e209c35d.png)
![2](https://user-images.githubusercontent.com/17920700/51103220-e7e1da00-181c-11e9-8122-3163340a594c.png)

The first picture is from the arm platform
The second picture is from the intel platform

**Comment by ImMrMa** [comment]
大兄弟，我也是arm的，咋就你没有网速呢？？？

**Comment by PeterDaveHello** [comment]
I don't think it's about arm platform, I've been using Raspberry Pi to seed Linux distributions for years.

Maybe it's about the configuration?

**Comment by jalin107** [comment]
> 大兄弟，我也是arm的，咋就你没有网速呢？？？

你的sysctl有做特殊配置吗？

**Comment by ImMrMa** [comment]
> > 大兄弟，我也是arm的，咋就你没有网速呢？？？
> 
> 你的sysctl有做特殊配置吗？

我是nanopi m4,正常apt-get 的transmission ,我这里下载ipv6 的bt一切正常，不过，不知道是网卡还是transmission的原因，我一开始bt下载网络就直接崩溃，只有用usb网卡才没有这个问题。。不知道为什么

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support, and respect others by using English.

**Comment by jalin107** [comment]
> Please use [forums](https://forum.transmissionbt.com/) for support, and respect others by using English.

OK, Thank you for your reminder
