### ISSUE TITLE
cache-size-mb只涉及到内存写入缓存，不能设置读取缓存？所有上传经过硬盘导致io高负载

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#818]
cache-size-mb只涉及到内存写入缓存，不能设置读取缓存？所有上传经过硬盘导致io高负载
我查看了配置文件，都没有详细说明读取缓存
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

![1](https://user-images.githubusercontent.com/6442439/51334863-ae7aca00-1abb-11e9-833a-565760f39141.png)
![2](https://user-images.githubusercontent.com/6442439/51334864-af136080-1abb-11e9-99d1-b61d1beeba3a.png)
![3](https://user-images.githubusercontent.com/6442439/51334865-af136080-1abb-11e9-99db-79b1cdade682.png)
![4](https://user-images.githubusercontent.com/6442439/51334866-afabf700-1abb-11e9-913d-c33f1d3df938.png)

**Comment by 1265578519** [comment]
版本 2.84

**Comment by xavery** [comment]
Nice torrents you're torrentin' there.

**Comment by mc256** [comment]
Translate:
**cache-size-mb** can merely set the writing buffer but make no controls on reading buffer, which makes seeding a problem.

The user @1265578519  wants to configure the reading buffer so that the program can load the entire file to memory for seeding purpose.

**Comment by mc256** [comment]
> 版本 2.84

发英文比较好

**Comment by xavery** [comment]
`cache-size-mb` is only used for (re-)calculating the hashes. It is not used for I/O during peer messages at all. If you grep through the code, the only references to tr_cache{Read,Prefetch}Block that you're going to find come from functions which are used for calculating hashes for the torrent's pieces.
The only form of caching used during I/O is POSIX's `fadvise` call. Transmission does not appear to use any form of internal caching for I/O with peers.

**Comment by 1265578519** [comment]
@xavery 我认为，他是确实有写入缓存的，因为你尝试修改值，然后进行下载操作，你会发现，在设置的值内，不会写入硬盘，都存在内存中。
如果达到内存值满了，才会进行一次硬盘的写入操作。

**Comment by xavery** [comment]
@1265578519 You're welcome to open the code and prove me wrong. I'm just sharing my own experiences, since I've looked into this before.

**Comment by mc256** [comment]
I would suggest closing this issue. This is not a programming issue. 
The wiki page might need to be updated.

**Comment by Shados** [comment]
> `cache-size-mb` is only used for (re-)calculating the hashes. It is not used for I/O during peer messages at all. If you grep through the code, the only references to `tr_cache{Read,Prefetch}Block` that you're going to find come from functions which are used for calculating hashes for the torrent's pieces. The cache is filled while the pieces are received from peers (presumably for recalculating the hash when the torrent is completed, though I haven't checked that in depth), but isn't used at all when sending data to them. The only form of caching used while sending data to peers is POSIX's `fadvise` call. Transmission does not appear to use any form of internal caching in this case. It seems like the meaning of this configuration key is very widely misunderstood. I wish there was a wiki page or something that users can be pointed to in order to familiarise themselves with what `cache-size-mb` actually does, or, more importantly, what it _doesn't_ do.

For anyone looking into `cache-size-mb` behaviour: the quoted comment was incorrect at the time of writing, and still is. I'm not sure how the OP missed it, but the cache was and is used for both prefetching and reading blocks in response to peer messages, since right back from [its initial implementation in 2010](https://github.com/transmission/transmission/commit/e70bebf930d14e28da27491dfe96bdef8e588e77#) (look at the diff for `libtransmission/peer-msgs.c`).
