### ISSUE TITLE
Download won't start on Windows

### ISSUE THREAD

**Issue by softshape** [transmission/transmission#82]
Version 2.92, Windows 10 64bit. Both 64bit and 32bit Transmission get peers list, but after that torrent download won't start, freezing on 0%.

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. Check out [this wiki page](https://github.com/transmission/transmission/wiki/Why-Are-My-Speeds-So-Slow%3F) as well.
