### ISSUE TITLE
Transmission 2.94 Keeps Quitting (Win 10)

### ISSUE THREAD

**Issue by Demasterpl** [transmission/transmission#821]
Transmission seems to be quitting unexpectidly without any warning. Here's what the event logs show:

> Faulting application name: transmission-qt.exe, version: 2.94.0.0, time stamp: 0x5ae8a6b1
> Faulting module name: transmission-qt.exe, version: 2.94.0.0, time stamp: 0x5ae8a6b1
> Exception code: 0xc0000005
> Fault offset: 0x00000000000a5686
> Faulting process id: 0xa2c
> Faulting application start time: 0x01d4b1037028bbf9
> Faulting application path: C:\Program Files\Transmission\transmission-qt.exe
> Faulting module path: C:\Program Files\Transmission\transmission-qt.exe
> Report Id: 068317f7-b8fb-49a9-8b8a-2913bb2327ea
> Faulting package full name: 
> Faulting package-relative application ID: 
> 

Using Windows 10 x64 and Transmission 2.94 (d8e60ee44f). I can't tell what's causing this to happen, honestly. My Transmission window disappears without any warning or popup. Doesn't appear in my task manager either after it crashes. Let me know how I can submit a memory dump if needed or if there's anything I can try to remedy the issue.

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/51622559-ce096b00-1f71-11e9-9a5b-ede1940f25d3.png)
你试试查找系统日志？我看起来拟提供的信息是一个内存地址偏移错误。

**Comment by anthonypants** [comment]
I just started seeing this issue a couple of times recently, and even on the same fault offset. I went through some of the torrents I just added, and one of them has a file with a question mark in it, which is (normally) illegal in Windows. Could that be causing this error?

**Comment by ckerr** [comment]
One thing to try -- Transmission's codebase has changed a _lot_ since this issue was filed, so you may want to continue testing with [nightly bulds](https://transmissionbt.com/download/) instead. If the behavior continues there, please update this issue. Thank you!

**Comment by ckerr** [comment]
Closing due to lack of response + lack of actionable info.

If anyone is still seeing this crash, please open a new issue. Thank you!
