### ISSUE TITLE
Download speed max 3.5MB/s on ARMv5 with 2.94+ versions

### ISSUE THREAD

**Issue by tonyk79** [transmission/transmission#829]
The 2.94+ versions (etc: 4671276450, r0cbf62411b, r4a4233feae) on ARMv5 NASes have speed issue. When the download reaches the ~3.5MB/s, it is stabilizing in this speed. If I changed back to 2.94 (d8e60ee44f), this speed limitation disappears, everything is working fine, in my case the speed is ~ 11MB/s.  Many of 2.94+ version have been tried, with the same result. This issue was confirmed by other users in our community (with Zyxel 310, 320, 325 ). With the + versions, CPU usage is high, around 99.8%!

**Comment by xavery** [comment]
Make sure you're not compiling the debug version with assertions enabled and stuff.

**Comment by tonyk79** [comment]
Sorry, would you be so kind to tell me how can I do it?

**Comment by xavery** [comment]
Stripping only takes care of removing information from the binary that can be used to debug a program. However, if the program itself was compiled in debug mode (i.e. no optimizations and assertions enabled, among other things), there is no way for you to turn it into release mode after the fact.

Compiling in release mode depends on the build system that you're using :
- With CMake, just pass `-DCMAKE_BUILD_TYPE=Release` to the cmake commandline, and then compile normally. Remember to create a new build directory for the release build.
- With autotools, apply [this patch](http://paste.debian.net/1065173/), clean the build directory by running `make distclean`, and start from scratch by doing `./autogen.sh && make`.

**Comment by tonyk79** [comment]
Thank you for your quick help! Manually replaced the affected lines in configure.ac from the patch. After compiling it looks good at first sight!
Thank you very much!
