### ISSUE TITLE
automake failing

### ISSUE THREAD

**Issue by vitorhugomattos** [transmission/transmission#832]
When I try to build with
```
./autogen.sh --disable-gtk --enable-daemon --disable-cli --enable-libnotify --disable-nls --disable-mac --disable-wx --disable-beos
```
I get `autoreconf: automake failed with exit status: 1`. You can see it here:
[![asciicast](https://asciinema.org/a/H1yudHoehb6HwwCJLrEKzcSPp.svg)](https://asciinema.org/a/H1yudHoehb6HwwCJLrEKzcSPp)
(yes, it's slow, is an Atom N270 netbook)

I'm on Void Linux, trying to build againt commit a89f33d7dcf5ca0ee700bd85bad61a5ce97fc207 (the current HEAD of branch 'master').

**Comment by mikedld** [comment]
If you're clonning this git repository, README.md mentions running `git submodule update --init` before building anything.
