### ISSUE TITLE
How password hash is computed ?

### ISSUE THREAD

**Issue by vincentdieltiens** [transmission/transmission#839]
Hi,

I read that transmission-daemon uses sha1 to encrypt the password but when I compare my sha1-hashed password with the one generated by transmission-daemon, it does not match.

Thanks

**Comment by mikedld** [comment]
It's "SSHA1" (salted SHA1) that is being used for password hashes: https://github.com/transmission/transmission/blob/master/libtransmission/crypto-utils.c#L128-L162. The salt is 8 random characters from a predefined alphabet which are appended to plain-text password before calculating SHA1 and then again appended to hex-formatted SHA1 after it's calculated to be able to recalculate it with that same salt when validating the password.

**Comment by vincentdieltiens** [comment]
Thank, works like a charm :)

**Comment by jooola** [comment]
Hello, I'm trying to update my transmission daemon password but I keep hitting a 401 every time I try to reconnect with the new password.

Here is what I did:

Stop transmission
```sh
sudo systemctl stop transmission-daemon.service
```
Generate a new password
```sh
#/bin/bash

salt=$(openssl rand -hex 4)
password=$(openssl rand -hex 8)

hashed=$(echo -n "${password}${salt}" | sha1sum | awk '{print $1}')

echo "Password: $password"
echo "Hashed password + salt: ${hashed}${salt}"
```
Change the password in `settings.json`

Restart transmission-daemon:
```sh
sudo systemctl start transmission-daemon.service
```

Still I cannot authenticate using the password generated by my script.

Could someone help me out with this ?

**Comment by tomwijnroks** [comment]
If anyone needs to create the rpc-password string: https://github.com/tomwijnroks/transmission-pwgen
