### ISSUE TITLE
web gui returns empty list on newer browsers

### ISSUE THREAD

**Issue by mote0230** [transmission/transmission#84]
In recent browsers like firefox dev edition and nightly, and chrome nightly, the web gui has been broken for some months. The gui loads, but the list of torrents remains empty. This is the console output in chrome:

jquery.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Failed to load resource: the server responded with a status of 409 (Conflict)

**Comment by mikedld** [comment]
I'm using Firefox on nightly update channel (currently 52.0a1) every day and web UI loads just fine, with all the torrents. Just tried Google Chrome Canary (56.0.2914.0) and torrent list loads there as well. Both tested with Transmission 2.92. Unless you provide more details (I don't believe quoted console output is relevant) I'm considering this a non-issue.

For further support, please consider using [forums](https://forum.transmissionbt.com/).
