### ISSUE TITLE
Feature request: 'torrent added' notification could include 'start' button

### ISSUE THREAD

**Issue by mgorny** [transmission/transmission#846]
I've set transmission not to 'start added torrents'. I would therefore find it convenient if the 'torrent added' notifications included a 'start torrent' button to quickly start specific torrents I've added.

**Comment by xavery** [comment]
Submitted #848 : very initial stage, but you're welcome to merge it into your own build, as the functionality works okay.

**Comment by mgorny** [comment]
Thanks but I'm using GTK+ client ;-).

**Comment by xavery** [comment]
Oh snap. Well here's #849 for you, then. :)

**Comment by mgorny** [comment]
Thank you and sorry for not mentioning that at first. It's impressive how fast you've solved it, in two different GUI toolkits ;-).

**Comment by ckerr** [comment]
Both those PRs are merged, so I'm closing this issue as fixed
