### ISSUE TITLE
"Display a Window" checkbox doesn't work?

### ISSUE THREAD

**Issue by xavdid** [transmission/transmission#85]
Hey gang, love the app. 

v2.9.2, macOS 10.11.6

Having an issue where when I click magnet links in Safari, the "add" window always pops up asking me where to store the file (despite having the "display a window when opening magnet links" button unchecked. 

Happy to provide any logs or anything you need!

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com/) for support. In particular, check that your "Default location" preference isn't set to "Same as torrent file" (as in [this forum thread](https://forum.transmissionbt.com/viewtopic.php?f=4&t=17705)).

**Comment by xavdid** [comment]
Ah, that did it.

Thanks a bunch!

~DavidB
[davidbrownman.com]
c: 303.819.0850

On November 12, 2016 at 12:51:56 AM, Mike Gelfand (notifications@github.com)
wrote:

Please use forums <https://forum.transmissionbt.com/> for support. In
particular, check that your "Default location" preference isn't set to
"Same as torrent file" (as in this forum thread
<https://forum.transmissionbt.com/viewtopic.php?f=4&t=17705>).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/transmission/transmission/issues/85#issuecomment-260110285>,
or mute the thread
