### ISSUE TITLE
The easier way to set individual file priorities doesn't work

### ISSUE THREAD

**Issue by dabraham02124** [transmission/transmission#853]
This appears to be a UI issue.

When looking at the individual files contained in a torrent with the Inspector file tab, I have a column with priority.  When I mouseover that column in a row, I get the "down arrow|dot|up arrow" widget.  When I click up or down, nothing happens.  When I double click up or down, I get taken to the .part file in finder.

I _can_ adjust priority by right clicking, going to "Priority", then "High", "Normal", or "Low".  The priority column is even adjusted appropriately, and high priority files finish downloading first.  This is why I think that this is a UI issue.

I've googled around and I I've only found [one link](https://forum.transmissionbt.com/viewtopic.php?t=17708&p=73308) that appears to describe this issue.  That _might_ be when I first noticed it.  I don't see an active bug report on this in this bug tracker.  Am I missing something?  Is there any other information that could help?  Is there anything I should try?

Thank you very much.

**Comment by Coeur** [comment]
Working fine for me in Transmission 4 on macOS Ventura:
![Capture d’écran 2022-11-13 à 02 55 15](https://user-images.githubusercontent.com/839992/201490269-c26d8d9b-0fc2-4ac7-900a-ca9d1fc41afb.png)

Likely resolved long time ago? Feel free to comment or reopen an issue with a screen recording and your version of macOS if it happens again with latest Transmission.
