### ISSUE TITLE
How to disable pre-allocation on Nvidia Shield android TV?

### ISSUE THREAD

**Issue by Remcodh** [transmission/transmission#856]
Hey guys,

At the moment i'm using Aria2 for torrenting on my Nvidia Shield because the ziahamza webui has the option of disabling pre-allocation and even when pre-allocating the webui continues to work. In Transmission pre-allocation makes the shield hang for quite some time and the webui becomes unresponsive. This is annoying because I can't add any other torrents and also can't see the progress of other torrents (if they continue downloading at all).  So I would like to know how I can find the config file for Transmission so that I can change the pre-allocation and compare Aria2 and Transmissions performance. I tried to find the file using X-plore but I just can't find it anywhere. Maybe it is hidden in a folder that can only be accessed when rooted?

Edit: in transmission the path to config file is: /data/user/0/com.ap.transmission.btc/Config. I can't find it in X-plore, so I think I just can't access it?

Thanks in advance!

**Comment by xavery** [comment]
You can set the `preallocation` key to `0` in config.json, as [documented here](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations).

**Comment by Remcodh** [comment]
Hey,

Thanks for the reply! I know how to do it but I just can’t find the config file on my Nvidia Shield. Do you have any idea on how to find it? I think the map is hidden on unrooted shield as I can’t find config files for other apps too.

Greetings,

Remco

Verstuurd vanaf mijn iPhone

Op 7 mrt. 2019 om 22:24 heeft Daniel Kamil Kozar <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


You can set the preallocation key to 0 in config.json, as documented here<https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#files-and-locations>.

**Comment by xavery** [comment]
Sorry, I was going to rewrite the comment, and you replied in the meantime. ;-)
Anyway, I wanted to say this is not really a Transmission issue, but it's rather related to the system where you're running it. Therefore, you might not be able to get help unless somebody running the same setup also has a similar problem.

**Comment by Remcodh** [comment]
Yeah all the torrent clients on the shield do this unfortunately. But it is all related to pre-allocating files I think. So that’s why i’m trying to find a way of disabling pre-allocation just like it is done on other systems. I just need to find a way to get to the config file 😄 I hope someone comes along with the same setup and that managed to do this. Thanks!

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) for support.
