### ISSUE TITLE
Transmission tries to connect IPv6 instances even ipv6 addresses are disabled.

### ISSUE THREAD

**Issue by enihcam** [transmission/transmission#86]
Transmission tries to connect IPv6 instances even ipv6 addresses are disabled.

sysctl.conf:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.br0.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.enp3s0.disable_ipv6 = 1
net.ipv6.conf.enp4s0.disable_ipv6 = 1
net.ipv6.conf.enp5s0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

systool:
```
Module = "ipv6"
  Parameters:
    autoconf            = "1"
    disable             = "0"
    disable_ipv6        = "1"
```

Note: I am not going to disable the whole IPv6 stack, because some apps have dependency on it. I'm only asking Transmission team to add an option to disable listening to IPv6.

My journal log is flooded with these (and more):

```
-- Logs begin at Wed 2016-11-16 08:25:35 CST, end at Thu 2016-11-17 05:59:39 CST. --
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2a02:a445:49ed:0:f030:ce43:92b3:eef0, port 50321 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:5ef5:79fb:3819:217e:920d:700e, port 37514 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6ab8:3c4b:1c82:a52d:66a2, port 64677 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6abd:85d:3dd7:cd55:9536, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:01 archnet transmission-daemon[313]: [2016-11-17 03:40:01.967] Couldn't connect socket 90 to 2001:0:9d38:6ab8:1c31:251b:d166:32cf, port 57438 (errno 99 - Cannot assign requested address)
Nov 17 03:40:03 archnet transmission-daemon[313]: [2016-11-17 03:40:03.967] Couldn't connect socket 45 to 2001:0:5ef5:79fb:3c58:1275:fa92:c6a8, port 59851 (errno 99 - Cannot assign requested address)
Nov 17 03:40:03 archnet transmission-daemon[313]: [2016-11-17 03:40:03.967] Couldn't connect socket 45 to 2001:0:5ef5:79fb:3c58:1275:fa92:c6a8, port 59851 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 45 to 2001:0:9d38:6ab8:3c86:1959:a13f:f5be, port 49450 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 45 to a7c2:0:5ef5:79fd:34bc:993:b3b8:ee95, port 56112 (errno 99 - Cannot assign requested address)
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 63 to 2a02:c7f:600:af00:b034:3267:417b:1d5f, port 51413 (errno 99 - Cannot assign requested address
Nov 17 03:40:04 archnet transmission-daemon[313]: [2016-11-17 03:40:04.967] Couldn't connect socket 63 to 2a02:c7f:600:af00:b034:3267:417b:1d5f, port 51413 (errno 99 - Cannot assign requested address
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fb:189c:397d:ac02:4538, port 12346 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:87d:1ba4:a152:dd82, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:34bc:993:b3b8:ee95, port 42946 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:84:32e3:b218:5789, port 35576 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:383f:2490:44c5:e4, port 45682 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:90d7:2c36:36d9:a500:f02c, port 10603 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:3ce2:278b:adb5:7944, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:5ef5:79fd:3ce2:278b:adb5:7944, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:30e3:ad0:e73d:2893, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:06 archnet transmission-daemon[313]: [2016-11-17 03:40:06.967] Couldn't connect socket 92 to 2001:0:9d38:6abd:30e3:ad0:e73d:2893, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:08 archnet transmission-daemon[313]: [2016-11-17 03:40:08.967] Couldn't connect socket 38 to 2601:85:4501:61aa:e0f9:dd4c:d654:a3cd, port 30793 (errno 99 - Cannot assign requested address
Nov 17 03:40:08 archnet transmission-daemon[313]: [2016-11-17 03:40:08.967] Couldn't connect socket 38 to 2601:85:4501:61aa:e0f9:dd4c:d654:a3cd, port 30793 (errno 99 - Cannot assign requested address
Nov 17 03:40:09 archnet transmission-daemon[313]: [2016-11-17 03:40:09.968] Couldn't connect socket 48 to 2a02:1810:9d17:fc00:a558:e1f2:6c46:d63a, port 41897 (errno 99 - Cannot assign requested addre
Nov 17 03:40:09 archnet transmission-daemon[313]: [2016-11-17 03:40:09.968] Couldn't connect socket 48 to 2a02:1810:9d17:fc00:a558:e1f2:6c46:d63a, port 41897 (errno 99 - Cannot assign requested addre
Nov 17 03:40:11 archnet transmission-daemon[313]: [2016-11-17 03:40:11.967] Couldn't connect socket 48 to 2001:0:9d38:6ab8:24d7:368b:743d:bc26, port 14844 (errno 99 - Cannot assign requested address)
Nov 17 03:40:23 archnet transmission-daemon[313]: [2016-11-17 03:40:23.967] Couldn't connect socket 36 to 2001:0:9d38:90d7:2407:1849:a9ea:f5a9, port 40414 (errno 99 - Cannot assign requested address)
Nov 17 03:40:23 archnet transmission-daemon[313]: [2016-11-17 03:40:23.967] Couldn't connect socket 36 to 2001:0:9d38:90d7:2867:9a9b:b0be:8881, port 11337 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:86b:211c:a128:34f1, port 40501 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:88e:1654:d198:d941, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6ab8:34ad:eca:a1ba:d6af, port 40501 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:5ef5:79fb:1c53:3643:4006:8239, port 8999 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:34c7:3068:2b8f:67af, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:28 archnet transmission-daemon[313]: [2016-11-17 03:40:28.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:e0:2dd3:af2b:4755, port 40500 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:2825:20cc:937c:cb3c, port 64232 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:1c53:9e5e:4387:6b5a, port 40500 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:6abd:24d8:d7a:2d44:7c2, port 40500 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2001:0:9d38:90d7:1833:3fe6:bf90:d5b3, port 58908 (errno 99 - Cannot assign requested address)
Nov 17 03:40:29 archnet transmission-daemon[313]: [2016-11-17 03:40:29.967] Couldn't connect socket 51 to 2405:204:2087:67bc:fb08:e5cb:5ecc:ace, port 6881 (errno 99 - Cannot assign requested address)
Nov 17 03:40:31 archnet transmission-daemon[313]: [2016-11-17 03:40:31.967] Couldn't connect socket 48 to 2001:0:9d38:6ab8:108d:3fce:a0a2:5b88, port 6881 (errno 99 - Cannot assign requested address)
Nov 17 03:40:32 archnet transmission-daemon[313]: [2016-11-17 03:40:32.967] Couldn't connect socket 48 to 2001:0:5ef5:79fd:10a1:381e:a777:714c, port 63302 (errno 99 - Cannot assign requested address)
Nov 17 03:40:33 archnet transmission-daemon[313]: [2016-11-17 03:40:33.967] Couldn't connect socket 51 to 2602:306:3b37:6a70:ed51:80a0:8abd:cb96, port 50001 (errno 99 - Cannot assign requested addres
Nov 17 03:40:33 archnet transmission-daemon[313]: [2016-11-17 03:40:33.967] Couldn't connect socket 51 to 2602:306:3b37:6a70:ed51:80a0:8abd:cb96, port 50001 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:306:8b10:33c0:d1d0:40e1:e538:9824, port 51930 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:306:8b10:33c0:d1d0:40e1:e538:9824, port 51930 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2601:601:8a02:dc0:2dca:d74a:f030:e279, port 40500 (errno 99 - Cannot assign requested address
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2602:30a:2c65:c200:b1e3:470c:f6ae:ccaa, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:35 archnet transmission-daemon[313]: [2016-11-17 03:40:35.967] Couldn't connect socket 51 to 2a02:2149:8237:a200:354a:8b7:d001:b20a, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:39 archnet transmission-daemon[313]: [2016-11-17 03:40:39.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:381f:1e95:b85c:1fe9, port 25163 (errno 99 - Cannot assign requested address)
Nov 17 03:40:39 archnet transmission-daemon[313]: [2016-11-17 03:40:39.967] Couldn't connect socket 51 to 2001:0:5ef5:79fd:381f:1e95:b85c:1fe9, port 25163 (errno 99 - Cannot assign requested address)
Nov 17 03:40:44 archnet transmission-daemon[313]: [2016-11-17 03:40:44.967] Couldn't connect socket 51 to 2001:0:9d38:90d7:4f:3180:d8d1:1d3f, port 30238 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2001:0:5ef5:79fd:2047:d9fc:b69f:8ee2, port 53787 (errno 99 - Cannot assign requested address)
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2a02:2149:8154:c00:f0f2:3b09:7bd8:a7a7, port 40500 (errno 99 - Cannot assign requested addres
Nov 17 03:40:49 archnet transmission-daemon[313]: [2016-11-17 03:40:49.967] Couldn't connect socket 56 to 2001:0:5ef5:79fd:24bc:38b2:203b:a5a6, port 64611 (errno 99 - Cannot assign requested address)
Nov 17 03:40:50 archnet transmission-daemon[313]: [2016-11-17 03:40:50.967] Couldn't connect socket 56 to 2001:0:9d38:6ab8:3cd6:6a6:fae1:ec0e, port 8999 (errno 99 - Cannot assign requested address) (
Nov 17 03:40:50 archnet transmission-daemon[313]: [2016-11-17 03:40:50.967] Couldn't connect socket 56 to 2001:0:9d38:6abd:2cef:3bca:b275:ce38, port 40507 (errno 99 - Cannot assign requested address)
```

**Comment by enihcam** [comment]
The only way to remove the spam from the log is to completly disable log (message_log = 0) ( the error appear when message-log = 1 so only way to remove it is toput message-log = 0 , so completly disable log.)

This should not be conssidered an error, and should at least appear once at the start of the program and not all the time. By the way not having ipv6 activated should not be an issue.

**Comment by enihcam** [comment]
Please add an option in Transmission for disabling IPv6, so I don't have to disable ipv6 from system level.

Thanks!

**Comment by damajor** [comment]
Logging with useless data is pretty annoying.
If there is no IPv6 then these logs should be dropped by the program itself silently not by the user!
Debug log level should bypass silent drop and show them but not in common usage.

**Comment by enihcam** [comment]
@damajor agreed! not only drop the logs, but please also drop the requests.

**Comment by matrunchyk** [comment]
> This should not be conssidered an error, and should at least appear once at the start of the program and not all the time.

It happens all the time. Proof:
```
Aug  4 11:40:35 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:35.941] Couldn't set source address fe80:: on 21: Invalid argument (net.c:272)
Aug  4 11:40:35 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:35.941] Couldn't set source address fe80:: on 21: Invalid argument (net.c:272)
Aug  4 11:40:38 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:38.942] Couldn't set source address fe80:: on 32: Invalid argument (net.c:272)
Aug  4 11:40:38 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:38.942] Couldn't set source address fe80:: on 32: Invalid argument (net.c:272)
Aug  4 11:40:43 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:43.942] Couldn't set source address fe80:: on 21: Invalid argument (net.c:272)
Aug  4 11:40:43 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:43.942] Couldn't set source address fe80:: on 21: Invalid argument (net.c:272)
Aug  4 11:40:47 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:47.942] Couldn't set source address fe80:: on 23: Invalid argument (net.c:272)
Aug  4 11:40:47 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:47.942] Couldn't set source address fe80:: on 23: Invalid argument (net.c:272)
Aug  4 11:40:49 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:49.942] Couldn't set source address fe80:: on 27: Invalid argument (net.c:272)
Aug  4 11:40:49 raspberrypi transmission-daemon[21061]: [2019-08-04 11:40:49.942] Couldn't set source address fe80:: on 27: Invalid argument (net.c:272)
```

**Comment by damajor** [comment]
This issue is not about stop logging. Please don't close it with such reason.

**Comment by val-kulkov** [comment]
transmission-daemon may be incorrectly binding to IPv6 interfaces. Spamming of syslog no longer happens as soon as the bind_address_ipv6 option is explicitly set to a public IPv6 address.

This is the port listening status I observe when "bind-address-ipv6" is set to "::". With this configuration, syslog is spammed with messsages like "Couldn't connect socket 34 to fd01::a1de:16d:450e:e2f9, port 29200 (errno 13 - Permission denied) (net.c:290)":
```
root@OpenWrt:/etc/config# netstat -plaunt | grep 51413
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      9806/transmission-d
tcp        0      0 :::51413                :::*                    LISTEN      9806/transmission-d
udp        0      0 0.0.0.0:51413           0.0.0.0:*                           9806/transmission-d
udp        0      0 2607:deaf:deaf:deaf::1:51413 :::*                                9806/transmission-d
```

And this is the port listening status I observe when "bind-address-ipv6" is set to "2607:deaf:deaf:deaf::1" (the real address has been obfuscated). With this configuration, syslog is no longer being spammed:
```
root@OpenWrt:/etc/config# netstat -plaunt | grep 51413
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      11090/transmission-
tcp        0      0 2607:deaf:deaf:deaf::1:51413 :::*                    LISTEN      11090/transmission-
udp        0      0 0.0.0.0:51413           0.0.0.0:*                           11090/transmission-
udp        0      0 2607:deaf:deaf:deaf::1:51413 :::*                                11090/transmission-
```

**Comment by diamondsw** [comment]
Over three years without any attention. Might as well "CLOSED: WONTFIX" it.

**Comment by onedr0p** [comment]
#wontfix

**Comment by Brent-Frere** [comment]
Ok.
# apt purge transmission transmission-cli transmission-common transmission-daemon transmission-gtk

**Comment by onedr0p** [comment]
Yes, I have moved to qBittorrent.

**Comment by Brent-Frere** [comment]
Ok. I'll try it.

**Comment by Brent-Frere** [comment]
It rocks !

**Comment by roquemore92** [comment]
Does Transmission 3.0 fix this or is it still a problem there too?

**Comment by ikwyl6** [comment]
I've tried the "fe80::" option in the ```settings.json``` file as per [forum.transmissionbt.com](https://forum.transmissionbt.com/viewtopic.php?f=2&t=11567&p=78907&hilit=fe80#p78907) but it crashes my transmission:

version: ```transmission-daemon 3.00 (bb6b5a062e)```

line with core dump:
```
Aug 10 02:07:04 user systemd-coredump[21386]: Process 21305 (transmission-da) of user 1000 dumped core.
Stack trace of thread 21333:
#0 0x00000000b69c7758 raise (libc.so.6 + 0x31758)
```

**Comment by jfeilbach** [comment]
Transmission 3.00 does not fix this issue. It is now 2021 and the issue persists.

**Comment by politas** [comment]
My system doesn't have an ipv6 address configured on any of its interfaces, and is connected via an ipv4-only tunnel to the Internet, yet transmission-daemon is still listening to ipv6 and reporting ipv6 connection errors.

**Comment by elisimpson** [comment]
My transmission docker container ate up 3gb of ram logging zillions of bogus IPv6 connection errors. Please please please fix this!

**Comment by Goro2030** [comment]
> My transmission docker container ate up 3gb of ram logging zillions of bogus IPv6 connection errors. Please please please fix this!

Yes, please, I second that! An option to not even try to use IPv6 would be great!

**Comment by Korrd** [comment]
Same happens here. Using latest as of the date of this message. It seems it logs a forever amount of stuff, which causes it to crash eventually. Issue goes away if I manually delete its logfile, but only for a time.

**Comment by onedr0p** [comment]
Probably better to just close this issue or unsubscribe, the maintainers obviously don't care about fixing this.

**Comment by Pentaphon** [comment]
@ckerr any thoughts on this?

**Comment by KaranTrivedi** [comment]
2022 now lol.

**Comment by ckerr** [comment]
There seems to be two separate but related issues here

- There should be an option for disabling IPv6 connections. This is an option that most people will probably not use so it won't be in the GUI, but it could be made available to users by editing the settings file.

- Separate from that, the default behavior of logging  is so high-volume that the volume itself becomes an issue. That should be handled in a separate issue, https://github.com/transmission/transmission/issues/1992

**Comment by ckerr** [comment]
Breadcrumb: looks like one way to test in code for IPv6 being enabled / disabled is to make an AF_INET6 socket and look for a return code of EAFNOSUPPORT. If this happens, Transmission could log a warning the first time this happens, then not log the rest / avoid initiating IPv6 for the rest of the session.

**Comment by vstarodubtsev** [comment]
https://github.com/keenetic/transmission/commit/1995141a2e547a96da400a12887abaec652eae29

**Comment by ckerr** [comment]
> [keenetic/transmission@1995141](https://github.com/keenetic/transmission/commit/1995141a2e547a96da400a12887abaec652eae29)

```c++
f = fopen("/proc/sys/net/ipv6/conf/default/disable_ipv6", "r");
```

Just a guess but I don't think that's going to work on Windows :smile:

**Comment by KaranTrivedi** [comment]
This is not a logging issue. My instance just stopped downloading all together.

**Comment by vuanhson** [comment]
Mine still can download but I had to disable transmission logging. 
Even if this issue have a PR to fix, from the time between releases of transmission history, I think it will take forever to be released. Last released is 2 years from now. Transmission should switch to something like monthly release or stable/nightly release.

**Comment by cdonovan** [comment]
Hey @ckerr, putting aside the logging issues (i.e if logging isn't important - setting the level to 0 until the next release that contains the verbosity fixes), are there any performance concerns directly related to the actual attempts to establish invalid ipv6 connections?

I recently switched from running transmission directly on my host to using docker-compose (hence the issues w/ lack of ipv6 connectivity) and wasn't sure if the frequent dropped connections would cause any discernible issues. It seems from a small time sample, when I had logging enabled I would see roughly 5-10 "Couldn't connect socket N" errors every few seconds.

**Comment by breakthestatic** [comment]
Hey @ckerr, putting aside the logging concerns (either via disabling logging altogether or the incoming logging verbosity fixes), are there any performance concerns with the actual failed attempts to open ipv6 sockets?  From a small time sample when I had logging enabled, it seems the ipv6 socket error was occurring 5-10x every few seconds (with about 800-900 torrents in the client.)

(also sorry, this is a paraphrase of a question i asked yesterday while accidentally signed in to my work account.)

**Comment by merc4derp** [comment]
It's still next to impossible to get a working ipv6 setup in docker. Why are the devs being blind to this request? For a lot of users the problem isn't not wanting to provide ipv6, but literally not being able to. Transmission keeps spamming logs with nonsense. 

Please fix this.

**Comment by kissgaby** [comment]
Please fix this.

**Comment by eblanakusok** [comment]
"message-level": 0 ?

**Comment by damajor** [comment]
> "message-level": 0 ?

Please refer to https://github.com/transmission/transmission/issues/86#issuecomment-517993152

**Comment by eblanakusok** [comment]
> > "уровень сообщения": 0 ?
> 
> Пожалуйста, обратитесь к [# 86 (комментарий)](https://github.com/transmission/transmission/issues/86#issuecomment-517993152)

How can I determine which address to set in my case?

**Comment by iliv** [comment]
> I've tried the "fe80::" option in the `settings.json` file as per [forum.transmissionbt.com](https://forum.transmissionbt.com/viewtopic.php?f=2&t=11567&p=78907&hilit=fe80#p78907) but it crashes my transmission:
> 
> version: `transmission-daemon 3.00 (bb6b5a062e)`
> 

FWIW, I run older transmission-daemon 2.84 (14307) and it doesn't crash but it still complains excessively about not being able to set "fe80::" as a source address. IPv6 is disabled on my host.

> transmission-daemon[22367]: [2022-06-24 12:30:21.828 EEST] Couldn't set source address fe80:: on 256: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:24.828 EEST] Couldn't set source address fe80:: on 190: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:27.828 EEST] Couldn't set source address fe80:: on 177: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:29.833 EEST] Couldn't set source address fe80:: on 237: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:31.828 EEST] Couldn't set source address fe80:: on 258: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:38.827 EEST] Couldn't set source address fe80:: on 95: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:39.829 EEST] Couldn't set source address fe80:: on 93: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:39.829 EEST] Couldn't set source address fe80:: on 279: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:41.828 EEST] Couldn't set source address fe80:: on 111: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:46.828 EEST] Couldn't set source address fe80:: on 138: Invalid argument (net.c:270)
> transmission-daemon[22367]: [2022-06-24 12:30:54.827 EEST] Couldn't set source address fe80:: on 189: Invalid argument (net.c:270)

**Comment by shudack** [comment]
Does anyone have a solution? I have the same problem in transmission-daemon 3.00 (bb6b5a062e)

**Comment by elisimpson** [comment]
I was trying to solve this issue recently and discovered something interesting: in my transmission Docker container I changed the network type from the default "bridged" network to "host" and the constant ipv6 errors stopped. There's something in the bridged network in Docker that fouls up the connections.

Using host networking isn't optimal, but it's at least a workaround that can prevent the huge bloating of log files in the meantime

**Comment by politas** [comment]
It's bridging in general, not docker, in that case, as my Transmission daemon is running in a VM, not a docker container.

**Comment by elisimpson** [comment]
Good info to have. I wonder if someone running transmission completely natively has this issue. With a combination of use cases we might be able to see what the common thread is.

**Comment by eternal-sorrow** [comment]
I'm running transmission completely natively and I'm having this issue. I have IPv6 disabled by sysctl.

**Comment by dafmdev** [comment]
I'm using docker and everything stopped downloading

**Comment by UnconditionalLoop** [comment]
Can someone explain why after 7 years, we still can't get this fixed? Either Transmission will attempt to use bogus inaccessible ipv6 addresses when it is not enabled, (the real problem that should be fixed), or we have to use this dumb setting, that doesn't even do anything. Either way, we still get bullshit in our logs, because the dumb program keeps trying to use ipv6, when it's been disabled system wide.

**Comment by hechtoid** [comment]
> Can someone explain why after 7 years, we still can't get this fixed? Either Transmission will attempt to use bogus inaccessible ipv6 addresses when it is not enabled, (the real problem that should be fixed), or we have to use this dumb setting, that doesn't even do anything. Either way, we still get bullshit in our logs, because the dumb program keeps trying to use ipv6, when it's been disabled system wide.

computer engineering is non-linear. especially on volunteer-run projects such as this one.

**Comment by ckerr** [comment]
> Can someone explain why after 7 years, we still can't get this fixed? Either Transmission will attempt to use bogus inaccessible ipv6 addresses when it is not enabled, (the real problem that should be fixed), or we have to use this dumb setting, that doesn't even do anything. Either way, we still get bullshit in our logs, because the dumb program keeps trying to use ipv6, when it's been disabled system wide.

Can someone explain why I put up the `pr welcome` label a year ago and you still haven't submitted a patch?

**Comment by alexfornuto** [comment]
> Can someone explain why I put up the `pr welcome` label a year ago and you still haven't submitted a patch?

I can only speak for myself when I answer. In my case it's because I'm a user of this software, but not a developer with the expertise required to resolve the issue. I've also been burned enough when I attempt to contribute to OSS projects by abrasive maintainers who lambasted my attempts to provide fixes than I'm afraid to try again. I'm left hoping that the amount of user-interaction on the issue is enough for the maintainer to prioritize the work required to resolve it.

**Comment by ckerr** [comment]
> I've also been burned enough when I attempt to contribute to OSS projects by abrasive maintainers who lambasted my attempts to provide fixes than I'm afraid to try again. 

That's understandable. FWIW, here are six PRs from six different contributors that were all merged into `main` within the last week, so you can judge whether people are being lambasted here.

* https://github.com/transmission/transmission/pull/5083

* https://github.com/transmission/transmission/pull/5055

* https://github.com/transmission/transmission/pull/5054

* https://github.com/transmission/transmission/pull/5035

* https://github.com/transmission/transmission/pull/5006

* https://github.com/transmission/transmission/pull/4975

**Comment by sentriz** [comment]
yahhooooo!!

**Comment by OcBuddy** [comment]
Still an issue in 2026, how to disable ipv6?

[**2026**-03-26T20:07:48.666+0100] dbg ip-cache.cc:303 Couldn't obtain source IPv6 address: Network is unreachable (101) (ip-cache.cc:303)
