### ISSUE TITLE
Skip specific file.

### ISSUE THREAD

**Issue by procobain** [transmission/transmission#862]
Hello, I have the transmission installed on an Arch Linux, even using the community version or AUR (git). I also use the Transmission Remote Gui 5.16.0, and sometimes the transmission webui itself. This problem happens in all:

I can not skip a specific torrent file, for example, I'm going to download a movie where the main file is LionKing.mkv, I want to cancel / skip jpg image files, zip files, subtitles and any other files that are not of interest to me.
Even removing the selection of these files, it lowers everything, and this is annoying.

Is it something in the configuration file or what?

Thank you

(Google translator)

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) for support.

**Comment by procobain** [comment]
220/5000
I had already searched in the forum and also in google, however I did not find this information, just a few talking topics which is a bug.

https://forum.transmissionbt.com/viewtopic.php?f=2&t=9813&p=46196&hilit=skipping#p46196
