### ISSUE TITLE
Elementary OS. Window size is different when started from magnet links.

### ISSUE THREAD

**Issue by Blast-City** [transmission/transmission#864]
elementary OS Loki (Ubuntu 16.04):

1- Start Transmission and set a window size. Close the application.
2- Open Firefox and go to a torrent site that have magnet links. Click on a magnet link.
3- Transmission is started, but the window size is a lot bigger than what it was when you saved in point 1.

The window size is back to what it was on point 1 after closing transmission and open it again using the application icon.

Anyone have a clue if this is a bug on transmission or on elementary's window manager?
What could be causing this?

**Comment by Blast-City** [comment]
Closing it because it seems to be fixed on Juno (Ubuntu 18.04).

**Comment by y** [comment]
Same thing happens on MacOS 10.14 with latest nightly: 2.94+ (eef4799388)
