### ISSUE TITLE
Missleading windows Daemon config file location listed in Wiki

### ISSUE THREAD

**Issue by boazarad** [transmission/transmission#865]
While the wiki correctly lists "%LOCALAPPDATA%/transmission-daemon" as  the config file location, "%LOCALAPPDATA%" will resolve to "C:\Users\[username]\AppData\Local" under a user context, rather than the expected "C:\Windows\ServiceProfiles\LocalService\AppData\Local" under a service context.

I suggest this should be noted on the wiki page to prevent confusion.

See issue #492, as well as numerous forum posts online from users having trouble finding the config file.

**Comment by strikepredator** [comment]
Thank you very much!

**Comment by Okesik** [comment]
This is still very much the case on GitHub Wiki :-/
