### ISSUE TITLE
FreeBSD Transmission service is stopping randomly

### ISSUE THREAD

**Issue by tommeh1337** [transmission/transmission#867]
I installed Transmission in an FreeBSD 11.2 iocage jail on my server. However, the Transmission service stops running once every few days. The jail is still up and running and I am able to start the Transmission service again without any problems. I tried rebooting the jail and the server itself without any luck. 

I can't find any errors in /var/log/messages other than normal Tranmission logging about torrents. 

How can I check why the Transmission service has stopped running?

**Comment by rehito** [comment]
When I encountered this problem, it was due to my system not having enough ram available. ZFS was eating it all up but creating a swap partition seemed to fix it for me.

**Comment by tommeh1337** [comment]
> When I encountered this problem, it was due to my system not having enough ram available. ZFS was eating it all up but creating a swap partition seemed to fix it for me.

Hi rehito, thanks for your reply. I don't think this is causing the issue for me. I am running FreeNAS 11.2-u3 with a total of 6 jails, only Transmission is stopping randomly. Never had any problems with the other jails. 

I have 16 GB of RAM, this is what it looks like:
![image](https://user-images.githubusercontent.com/38126487/55459197-441ff300-55ef-11e9-85ef-c70744287da7.png)

**Comment by ckerr** [comment]
Is this still an issue in the 4.0.0 betas or newer?

**Comment by rafe-s** [comment]
This no longer appears to be a live issue. FreeBSD ports contains 4.04, which I have run stably inside a jail for months now.

There may, however, be a separate bug report filed in the [future](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274818) related to transmission entering a stopped / zombie state.
