### ISSUE TITLE
[transmission-cli] missing mime integration for torrents and magnets 

### ISSUE THREAD

**Issue by Boruch-Baum** [transmission/transmission#87]
Ref: https://bugs.archlinux.org/task/51842#comment152795

The package transmission-cli does not associate MimeType=application/x-bittorrent;x-scheme-handler/magnet; with the binary "transmission-remote -add". This was observed when trying to open a magnet from within firefox.

The fix would be to add the mime-type association
x-scheme-handler/magnet=transmission-remote.desktop

And to create/install a file /usr/share/applications/transmission-remote.desktop

[DesktopEntry]
Encoding=UTF-8
Version=1.0
Type=Application
Exec=transmission-remote --add %u
Name=transmission-remote
Comment=Custom definition for transmission-remote
MimeType=application/x-bittorrent;x-scheme-handler/magnet;

EDIT: When I tested this for torrent files, it seemed that the exec line needed the %f macro instead of %u, so it might be necessary to have separate desktop files (eg. transmission-remote-magnet, transmission-remote-torrent). It's not sufficient to name the desktop files uniquely, the name definition in the desktop file also needs to match the unique name.

**Comment by ckerr** [comment]
transmission-cli is deprecated. It won't be removed, but it's only getting critical fixes at this point.

transmission-daemon + transmission-remote is the preferred replacement.
