### ISSUE TITLE
'seed time' not saved between sessions

### ISSUE THREAD

**Issue by Jorman** [transmission/transmission#870]
Hi, I just noticed that the seed time that transmission show to me is totally wrong.

For example I've one torrent that I know for sure that is in seed for 1W and 4D but transmission show to me that the seed time is about 1D, that is the day I restart the transmission service.
Transmission don't save the seed time during the reboot?
I'm on the last 2.94+, actually ...101a, maybe is for that?

J

**Comment by firesalp** [comment]
Hello Jorman,

I have the same issue here.
Do you have any update to share on this case?

Regards

**Comment by Jorman** [comment]
@firesalp 
No sorry, I had to switch to another client because I need to be "precise" with seeding time

**Comment by Pentaphon** [comment]
I'm actually surprised that Transmission doesn't show you the total seed time per torrent.

**Comment by edgeman16** [comment]
This is still an issue on 4.0.4_4 (version as per FreeBSD ports tree install). A reboot or restart of the transmission daemon wipes the seed time for some (but not all) torrents.

**Comment by edgeman16** [comment]
Just a note to mention this still occurs on 4.0.6. I have had a little bit of luck if I pause/stop all torrents prior to shutting down, but it's not consistent (and sometimes there are shutdowns/restarts where the torrents are not all paused/stopped gracefully anyways).

I'd like the "Total Seed Time" data to be accurate(ish... within a day or two at least) as I use external scripts + the API to clean up certain torrents in certain directories after they have been seeding for a certain time (length of time kept seeding varies by directory).

**Comment by kvanbiesen** [comment]
Should be fairly easy to implement. 

The download_done date is been set in the resume file. If the clients reads the time from there, like it does with last_activity .

Seems like it even get read in resume.cc line 688 :DoneDate but nothing be done with it.
