### ISSUE TITLE
linux  too many open files

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#871]
ulimit -n 1048576
修改了，并且重启transmission，还是出现too many open files错误。

**Comment by kslr** [comment]
一个是全局，一个是systemd

**Comment by 1265578519** [comment]
@kslr 搜索的解决方案，，我认为他并不适合，https://github.com/cfpp2p/transmission/issues/11
竟然说是限制peer连接数量来解决，，这个明显不靠谱啊。大佬有什么解决方案吗，还是说这是BUG没办法弄

**Comment by kslr** [comment]
从你的标题错误信息上来看，可以先检查系统和进程现值是多少

**Comment by psycholyzern** [comment]
Hi. Transmission has 1024 max open files hardcoded in the code. Took me so long to know that.
I ended up decreasing value for peers.

**Comment by mikedld** [comment]
See #309. Please use English when communicating here.

**Comment by ckerr** [comment]
Appears to be a duplicate of #633
