### ISSUE TITLE
Disable CSRF protection

### ISSUE THREAD

**Issue by psycholyzern** [transmission/transmission#872]
Hi. I wanted to disable CSRF protection. What I have to do to get it disabled?
I made a search and found [this line](https://github.com/transmission/transmission/blob/750589101aee6705a325f4ef09290b520b72add4/libtransmission/rpc-server.c#L44). 
Should I delete that line and recompile?

Thanks.

**Comment by mikedld** [comment]
Commenting out or deleting this line will disable the check, yes. I'm not sure why you'd want to do this though, could you describe your use case?

**Comment by psycholyzern** [comment]
Thanks. I am using transmission for my bot. Since public can't access my transmission directly, it is useless to have that protection. having CSRF protection turned on will cost me additional HTTP request.

Thanks :)

**Comment by somenewaccountthen** [comment]
My use case is i am doing X referenced request from a shared front end.
I need it to be disabled. There are x site calls.
