### ISSUE TITLE
Bug when adding new torrent from Qt management interface for Windows to a remote Linux machine.

### ISSUE THREAD

**Issue by AngelFalse** [transmission/transmission#877]
![image](https://user-images.githubusercontent.com/28922095/55695578-c8a5b380-59eb-11e9-87a1-37a7412a410c.png)
![image](https://user-images.githubusercontent.com/28922095/55695743-934d9580-59ec-11e9-966d-c93d2167c1ec.png)

When adding torrent(s) (whenever from a torrent file or a link) to a remote linux machine from local qt interface (for windows), the path of the "Target Folder" gives a value with a part of windows-styled path(C:) and linux-styled path(/media/sda2/Downloads).

**Comment by mikedld** [comment]
See #236.

**Comment by jrhoffa** [comment]
Bug #236 is also NOT FIXED.
