### ISSUE TITLE
Several new peer id, though I can not recognize.

### ISSUE THREAD

**Issue by AngelFalse** [transmission/transmission#878]
Downloading a video torrent, and found several strange peer id.
在下载一个视频种子，发现了多个奇怪的peer id。
I did some digging into the issue list and got two possible software for two on the list, the rest remained unclear.
查了一下issue列表，找到了两个可能的对应软件，但另外两个还是不清楚.
![image](https://user-images.githubusercontent.com/28922095/55769771-872d0b00-5ab4-11e9-8ec8-447433db36ef.png)
FDM(Strangely, the last 4 byte is changed with no clear pattern~~, does that mean the last 4 byte is generated randomly?~~**updated, see below for the newest message**):https://github.com/transmission/transmission/issues/335
看起来像FDM，但很奇怪：最后四位变了，且是由“R%FF”变成了“]%C7”，完全找不到规律。~~这是否意味着这个peer id的后四位是随机生成的？~~**已更新，见以下更新的内容**
XFplay(5000, also very strange, 5.0.0 maybe? Have seen this peer if before already, while downloading other video torrent.):https://github.com/transmission/transmission/issues/252
XFplay 也很奇怪，为什么是5000？5.0.0吗？之前下载视频种子的时候也见过这个peer id。

@msg7086
Any idea, if possible?

------
Update:
More peer id starting with FD51 found, with very different tails.
发现了更多以FD51开头，不同的字符结尾的peer id。
![image](https://user-images.githubusercontent.com/28922095/55770385-ab89e700-5ab6-11e9-8ada-6cc69cb944da.png)
Sounds like we can call it a fact that FDM generate the last 2/4 byte by random.
看起来FDM随机在peer id尾部生成随机字符已经是一个不争的事实了。

**Comment by msg7086** [comment]
https://github.com/transmission/transmission/blob/master/libtransmission/clients.c#L53

FDM有自己的版本号方式。

XF是Xfplay。剩下两个不清楚。

**Comment by ckerr** [comment]
These four clients highlighted are all supported in `main` now as of #1907
