### ISSUE TITLE
[Feature] Add 'Error' to filter bar

### ISSUE THREAD

**Issue by unknown--** [transmission/transmission#880]
It would be handy if you could filter the view so that erroneous torrents can be fixed rather than searching for each one. An example would be when a tracker de-registers torrents and you'd like to remove them.
![Screen Shot 2019-04-14 at 11 45 54 AM](https://user-images.githubusercontent.com/7199527/56087485-cf32a000-5eaf-11e9-9417-6361048e70cf.png)

**Comment by mikedld** [comment]
See #19.
