### ISSUE TITLE
transmission服务器有/29 ip，使用客户端连接服务器，只能工作一个ip。

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#887]
transmission服务器有/29 一共5个ip地址，使用客户端连接服务器，只能工作一个ip。
其他ip会处于seen状态，是transmission不支持一个peer多连接端口请求？
transmission估计检测到是客户端来路只有一个ip导致的问题？
我是在客户端上手动添加了transmission服务器的ip和端口。。
这样没办法多个服务器ip多线程同时工作提高客户端下载速度。。

**Comment by 1265578519** [comment]
utorrent中有bt.allow_same_ip设置，可以开启，qbit也有相关设置可以解决，transmission配置文件中没看到，是不支持修改吗？

**Comment by mikedld** [comment]
Please use [forums](https://forum.transmissionbt.com) (ane English) for support. It's quite hard to understand what you're trying to ask, and this place is generally for reporting real issues or requesting features, not asking questions...

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/63786203-31061a80-c924-11e9-9592-105c08bd33db.png)
网上这些人客户端是怎么搞的，看他们的是2.93版本，可以同时连接多个IP地址
