### ISSUE TITLE
Magnet Torrents Disappear

### ISSUE THREAD

**Issue by cfpp2p** [transmission/transmission#89]
Magnet Torrents Disappear

NOT **in**valid
https://trac.transmissionbt.com/ticket/5981
https://forum.transmissionbt.com/viewtopic.php?f=2&t=17298

In `tr_torrentSetMetadataPiece()` if `checksumPassed` is true and `tr_variantFromBenc()` returns without error  `tr_variantFromFile()` loads the initial (without 'info' dictionary) torrent file. This original torrent file is then removed ( `tr_sys_path_remove (path, NULL)` ). Removal is preparation for creating new finalized completed torrent file. However, if `tr_metainfoParse` or block size fails `success` will be false and finalized torrent file will NOT be saved, rendering no longer a torrent file of the initial magnet information.

Without `success` the `/* drat. */` block is processed to try again but there can never be success again because
`if (tr_variantFromFile (&newMetainfo, TR_VARIANT_FMT_BENC, path, NULL))`
will interminably fail. A permanently stalled magnet results.

Once there is a valid checksum there is no reason to ever try again the metadata acquisition. If checksum fails incompleteMetadataFree() might want to be called so that a new (perhaps valid) peer's  parseLtepHandshake could then be used to of ` tr_torrentSetMetadataSizeHint` and try again.

**Comment by ckerr** [comment]
I think this is resolved as a side-effect of the `tr_torrent_metainfo` refactor as torrent-magnet.cc no longer uses `tr_variantFromFile()`.

**Comment by ckerr** [comment]
Closing this one as fixed because I agree with the original report but don't see a codepath to this endless fail loop anymore, but if I've missed it please do open a new issue and maybe it can get fixed in 2029 or so :smile:
