### ISSUE TITLE
tracker不工作，提示Tracker will be used as a backup

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#890]
tracker不工作，提示Tracker will be used as a backup

**Comment by yellowbigbird** [comment]
并没有生命说开发者是中国的, 就不要用中文吧.

**Comment by AngelFalse** [comment]
Translate:
Some trackers on the tracker list given by the torrent is inactive, and status is shown as "Tracker will be used as a backup".

**Comment by ckerr** [comment]
This is as intended -- they _are_ backup trackers in a tier.

https://www.bittorrent.org/beps/bep_0012.html

> The tiers of announces will be processed sequentially; all URLs in each tier must be checked before the client goes on to the next tier. URLs within each tier will be processed in a randomly chosen order; in other words, the list will be shuffled when first read, and then parsed in order. In addition, if a connection with a tracker is successful, it will be moved to the front of the tier.

**Comment by trim21** [comment]
> This is as intended -- they _are_ backup trackers in a tier.
> 
> https://www.bittorrent.org/beps/bep_0012.html
> 
> > The tiers of announces will be processed sequentially; all URLs in each tier must be checked before the client goes on to the next tier. URLs within each tier will be processed in a randomly chosen order; in other words, the list will be shuffled when first read, and then parsed in order. In addition, if a connection with a tracker is successful, it will be moved to the front of the tier.

It looks like transmission didn't fully respect bep12?

> On each announce, first try tracker1, then if that cannot be reached, try backup1 and backup2 respectively. On the next announce, repeat in the same order. This is meant for when the trackers are standard and can not share information.

So it mean, if any announce to tier 0 trackers success, transmission should not announce to tier 1 trackers.

But what I have observes, it announce to tier 1 trackers even tier 0 announcement success.

**Comment by ckerr** [comment]
https://github.com/bittorrent/bittorrent.org/issues/82
