### ISSUE TITLE
服务器没有负载压力，在持续跑高宽带超过1Gbps情况，web  gui长时间Pending

### ISSUE THREAD

**Issue by 1265578519** [transmission/transmission#894]
服务器没有负载压力，在持续跑高宽带超过1Gbps情况，web  gui长时间Pending
![1](https://user-images.githubusercontent.com/6442439/56853528-d5b72200-695b-11e9-9d6b-8f0e3bc13bd7.png)
![2](https://user-images.githubusercontent.com/6442439/56853529-dcde3000-695b-11e9-9c16-70cc1e86ddca.png)
![image](https://user-images.githubusercontent.com/6442439/56853535-e798c500-695b-11e9-9a32-c326741a03ef.png)

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/56853565-6c83de80-695c-11e9-8af8-a83ea6d60737.png)

**Comment by xavery** [comment]
no spoko fajne skrinszoty porobiłeś ale co z tego?

**Comment by 1265578519** [comment]
https://github.com/transmission/transmission/issues/888
基本上大家都是这种问题，希望能修复，毕竟现在服务器都是10Gbps甚至是40Gbps宽带

**Comment by ckerr** [comment]
This appears to be the same issue as https://github.com/transmission/transmission/issues/1829.
