### ISSUE TITLE
option to strip parent folder for single file

### ISSUE THREAD

**Issue by linetwo** [transmission/transmission#896]
Sometimes torrents contain only a single file.
Sometimes torrents contain only a single file, but in a parent folder.

BEP 3 strongly implies that the latter case shouldn't exist. Also, it's annoying in the file system.

I found that I can't just rewrite the torrent info dict to convert the latter into the former, before adding the torrent to transmission, because the info_hash will change. Private trackers require this info_hash to match that of the original torrent file.

Please add an option to transmission to ignore the parent folder for the single-file-in-a-single-folder case. I guess this setting would be stored as a key in the resume file.

**Comment by linetwo** [comment]
I figured out a W/A.

In the resume file, the full path to the dest file is determined by the keys `destination/file[0]`, where `file[0]` is a partial path that includes the parent folder. On Mac, the GUI crashes if you remove the parent folder from `file[0]`, but you can simply replace it with `.`.

The inspector does not expose the entire [partial] path, it only shows and allows editing of the basename. I did not test what happens if you later 'rename file' in the inspector. I suspect the `.` will be lost and the parent folder name will be restored, and then transmission will think the file is lost.

**Comment by ckerr** [comment]
This isn't something that very many people will use and there is a workaround.
