### ISSUE TITLE
Prioritising torrents doesn't work as expected

### ISSUE THREAD

**Issue by forthrin** [transmission/transmission#900]
This happens often:

I've got some weak torrents that take weeks to finish. Then I add some healthy torrents that go fast.

Problem:

The fast torrents hog bandwidth from the slow ones. Setting the slow ones to "High" priority and the fast ones to "Low" changes nothing how bandwidth is distributed between the torrents.

Solution:

Make sure that "High" priority makes the torrent get all the bandwidth it needs, while the "Low" ones only gets what's left after "High" (and "Normal") have taken all the bandwidth they want.

**Comment by ckerr** [comment]
High priority torrents already get all the bandwidth they need. If there are no peers in the slow swarm to use that bandwidth, it winds up getting hogged by low priority torrents anyway. But high-priority torrents are first in line when bandwidth is allocated.

**Comment by forthrin** [comment]
Thanks for your response after only almost three years. However, your response does not match up with my real life experience at all. Either that, or I'm having the wrong idea about how this function is supposed to work.

Let's say I have 10M total download capacity.

1. Add torrent A which tops at 4M download speed.
2. Pause torrent A and add torrent B which uses the full bandwidth (10M)
3. Start A. The bandwidth may now either be shared between A and B, or B may take the full 10M again.
4. Set A to "High bandwidth priority". I now expect A to take 4M and B to take what's left (6M).
5. However, nothing happens. The capacity is shared exactly like before I change the priority.

Is this the intended behavior? If so, please explain the function's usefulness with a simple, practical example.

**Comment by GScottElshaw** [comment]
It's taken me a long time to realise that using a torrent client is a horrible experience regardless of the individual application. Everything feels completely opaque. My bandwidth has zero determination with what peers appear to be able to receive. It's exhausting to seed with a 10mb/s upload speed and it appears you can only upload a 10k/s. The more i have dug into how everything works, the more i realise there are so many variables involved that it will always be this way.

Charles is doing his best.

**Comment by forthrin** [comment]
My workaround is to throttle less important torrents manually, to free up capacity for those more important, which requires some lame brain capacity, but works instantly as expected. Though this feels unnecessary as this is the sort of thing you expect the software to provide smartness for, but is doable as long as you don't get obsessive about it.

The neurotic/adventurous programmer would write a script wrapper that does some sort of incremental tuning by looking at the numbers, do some throttling, look at the numbers again, etc. until some desired optimum is achieved. I haven't been bothered to do this yet, as like I said I feel it's a core feature that would belong in the software itself.

Prioritizing particular files is sometimes also desired, though I know some find this to be sacrilegious to the swarm. Maybe we should all just get gigabit fiber and go meditate while the bits find their way to our computers in no particular order.

**Comment by GScottElshaw** [comment]
I wasn't aware we were discussing our mental health :-)
