### ISSUE TITLE
No TCP connections when UTP enabled (Win 10)

### ISSUE THREAD

**Issue by ryannathans** [transmission/transmission#907]
Transmission 2.94+ (750589101a) x86 

Win 10 1809

1. Enable uTP (UDP)
2. Restart Transmission
3. Observe no peers connected via TCP
4. Disable uTP (UDP)
5. Restart Transmission
6. Observe peers connected via TCP

Expected behavior: When uTP is enabled, TCP is not disabled. Most other clients allow both to be used simultaneously, otherwise, if there are TCP peers but no uTP peers the torrent will never download.

**Comment by ckerr** [comment]
TCP is not disabled when uTP is enabled. This may have been a sampling issue.
