### ISSUE TITLE
transmission-qt: File rename to existing file breaks the torrent

### ISSUE THREAD

**Issue by kroppt** [transmission/transmission#909]
I am using transmission-qt on Windows to hook into my remote server (running on the same machine). I just tested it on local session, which encounters the same issue.

Easy to test... get a torrent with multiple files, download it, rename one file to the same name as another file. Then, the names should be linked together (change one, and the other is the same). Close out properties and re-open, you should see this garbled mess:
![image](https://user-images.githubusercontent.com/14015672/57859699-77929780-77c1-11e9-8159-c18527cd7dcf.png)
![image](https://user-images.githubusercontent.com/14015672/57859602-431edb80-77c1-11e9-8b3e-b86d0fe311de.png)

One of the files is missing, and the other is just wrong.

Then, I verified the torrent, and resumed. The missing file did not return, and the size of the torrent kept increasing, and it just kept downloading. Nothing was showing up on the file system.

The first time this happened to me, it actually crashed the client. After all of this, the file you wanted to rename is now no longer downloadable. I had to restart the torrent and verify the local files (after renaming them on the torrent of course).

**Comment by Pentaphon** [comment]
@mikedld this looks like a pretty big issue that needs your specific eyes.

**Comment by kroppt** [comment]
This was fixed in https://github.com/transmission/transmission/pull/5563 and I tested that it was fixed in version 4.0.4.
