### ISSUE TITLE
[Feature Request] Auto-download updated torrent from forum

### ISSUE THREAD

**Issue by SakhJack** [transmission/transmission#911]
It's very common for forum-like trackers to update their releases (and torrents) for new version of software or new episode of TV series

So upon torrent expiration (or on set schedule) check either:
1. manually "subscribed" threads by providing a URL/RSS in settings (authentication required for private trackers)
2. comment section of torrent where people usually put reference to the thread

**Comment by xavery** [comment]
Such functionality is best implemented via external scripts/programs (usually triggered via a cronjob or similar scheduling facilities) which communicate with Transmission via `transmission-remote`.
