### ISSUE TITLE
Transmission Flatpak package is not translated on my french system

### ISSUE THREAD

**Issue by antistress** [transmission/transmission#919]
Hi,

I just tried Transmission Flatpak package on my Debian Sid 64 bits and it's not translated in french, unlike the deb package provided by my distribution.

Maybe this bug should be linked with Flatpak package #64 ?

Or maybe should I report the bug against the Flathub package here: https://github.com/flathub/com.transmissionbt.Transmission/issues as mentioned in Transmission's symbolic icon doesn’t show up in Flatpak #414 ?

Thanks

**Comment by antistress** [comment]
To be more precise :
Transmission Flatpak package is not translated on my french system if I install it via GNOME Software GUI from dl.flathub.org
But if I manually install it with .Locale as ending to the name :
flatpak install flathub com.transmissionbt.Transmission.Locale
Then it's alright

**Comment by antistress** [comment]
Here is the corresponding bug at https://github.com/flathub/com.transmissionbt.Transmission/issues/22

**Comment by wjt** [comment]
Please close this – as described on the Flathub ticket this was an issue with gnome software
