### ISSUE TITLE
Notification: I have built an AppImage for Transmission

### ISSUE THREAD

**Issue by fusion809** [transmission/transmission#92]
Hi,

Not sure if this is where I should say this but I have built an [AppImage](https://appimage.org) for Transmission 2.92. I have tested it on Fedora 24 and Ubuntu 16.04 and it seems fine (any bug reports should be made at https://github.com/fusion809/AppImages/issues). AppImages for those of you that do not know are a type of cross-distribution packaging format (like flatpak or snaps) that do not need to be installed in order to be run. They merely need to be marked executable (with `chmod +x`) and run. This AppImage of mine can be found [here](https://bintray.com/fusion809/AppImages/Transmission-GTK#files) and is a mere 11.7 MB download. This AppImage was built in a CentOS 7 Docker container so it should be able to run on any Linux distribution with FUSE setup that is of equal age or newer than CentOS 7. So this means the following major distributions are supported:

* Arch Linux
* CentOS 7
* Debian 8
* Fedora &geq;20
* Gentoo Linux
* Linux Mint &geq;17
* Mageia 5
* Manjaro Linux
* openSUSE &geq;42.1
* Sabayon Linux
* Ubuntu &geq;14.04

Thanks for your time,
Brenton

**Comment by ckerr** [comment]
I'm going to close this issue since there's not really anything actionable here -- but I do want to thank you for taking the time to do this! The Transmission team has pretty limited time and I don't think it's likely that we'll be taking on maintaining any new binary images on our own.

**Comment by Mhowser** [comment]
@fusion809 Can you update the appimage build to the version 3 please?

**Comment by Axa-Ru** [comment]
for version 4?

**Comment by Samueru-sama** [comment]
https://github.com/pkgforge-dev/transmission-qt-AppImage/

Works on ubuntu 14.04 (and likely older unless Transmission depends on new kernel features) as well as on Alpine linux: 

![Image](https://github.com/user-attachments/assets/15bc8633-8383-4d0e-8155-2b115a728706)
