### ISSUE TITLE
Incorrect when parsing blocklist entries

### ISSUE THREAD

**Issue by artiomn** [transmission/transmission#928]
```
transmission_1  | [2019-06-16 13:10:03.561] RPC Server Adding address to whitelist: download-torrent.nas.org (And it has a '+' or '-'!  Are you using an old ACL by mistake?) (rpc-server.c:969)
```

rpcserver finds '+' or '-' symbols anywhere in the string. Domain names with '-' symbol cause warning.

**Comment by mikedld** [comment]
Whitelists should contain IP addresses, not domain names.

**Comment by ckerr** [comment]
Introduced in 2008: https://github.com/transmission/transmission/commit/32ebb868e7465c081e0ba6dd02ecee808afe569d
