### ISSUE TITLE
Something (Web UI?) removes user settings from settings.json

### ISSUE THREAD

**Issue by artiomn** [transmission/transmission#929]
I have following string in the my `settings.json`:

```
    "rpc-host-whitelist": "download-torrent.nas.org",
```

When I use standard Web UI, value of this parameter becomes "" and interface doesn't work.
With alternative UIs, everything works fine.

**Comment by ckerr** [comment]
This appears to be the same issue as https://github.com/transmission/transmission/issues/1490
