### ISSUE TITLE
BUG:Transmission WEB can't be visited via IPV6

### ISSUE THREAD

**Issue by samondlee** [transmission/transmission#934]
"rpc-bind-address": "0.0.0.0",

i can reach web gui 9091 via IPV4

but in ipv6 enviroment ,i can't visit 9091 port.

does it havent listened ipv6 port?

how to configure it?

(i am confirmed both clients and server have ipv6 address)

**Comment by lps-rocks** [comment]
You'll need to configure rpc-bind-address to be 

``` "rpc-bind-address": "::" ```

**Comment by samondlee** [comment]
> "rpc-bind-address": "::"

Oh,thanks!

can they IPV4 IPV6 address appear at same time？

such as  i input 

"rpc-bind-address": "::"
"rpc-bind-address": "0.0.0.0"

in the conf file？ will it get crashed :(

**Comment by lps-rocks** [comment]
No, you can only have one. but if you use "::" it will listen on the IPV4 equivalent too. (Dual stack Linux FTW)

**Comment by samondlee** [comment]
> No, you can only have one. but if you use "::" it will listen on the IPV4 equivalent too. (Dual stack Linux FTW)
i change the conf,

but it still cant be visited...

192.168.1.81:9091 is fine

but http://[2409:8a62:628:4c70:7834:3bd7:9fa:3eb4]:9091/  still cant be visited...

i am confirmed my router's IPV6 firewall has been turned off

`{
    "DHT-block-this-port": 1,
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "blocklist-webseeds": false,
    "cache-size-mb": 2,
    "cheat-mode-default": 0,
    "clean-json-utf-enabled": false,
    "client-version-bep10": "",
    "concurrent-announces-maximum": 48,
    "dht-dat-ipv6-forced": false,
    "dht-enabled": true,
    "download-dir": "/mnt/16gusb/opt/wwwroot/default/download",
    "download-group-default": "movies",
    "download-groups": [
        "Movies",
        "Music",
        "Software"
    ],
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "drop-interrupted-webseeds": true,
    "encryption": 0,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/mnt/16gusb/opt/wwwroot/default/download/cache",
    "incomplete-dir-enabled": false,
    "ipv6-enabled": true,
    "ipv6-listen": true,
    "lpd-enabled": false,
    "magnet-bad-piece-max": 25,
    "message-level": 2,
    "multiscrape-maximum": 64,
    "peer-congestion-algorithm": "",
    "peer-id-prefix": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 240,
    "peer-limit-per-torrent": 60,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "piece-temp-dir": "/mnt/16gusb/opt/wwwroot/default/download/cache",
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": false,
    "prefetch-magnets-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "redirect-maximum": 16,
    "rename-partial-files": true,
    "reverify-torrents-tries": 0,
    "rpc-authentication-required": true,
    "rpc-bind-address": "::",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{**********************",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "admin",
    "rpc-whitelist": "::",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-added-enabled": false,
    "script-torrent-added-filename": "",
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "stream-mode-default": 0,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-slots-per-torrent": 14,
    "user-agent": "",
    "utp-enabled": true,
    "watch-dir": "",
    "watch-dir-enabled": false,
    "webseed-max-connect-fails": 5,
    "webseed-timeout-seconds": 20,
    "webseeders-maximum": 4
}
`

**Comment by samondlee** [comment]
> No, you can only have one. but if you use "::" it will listen on the IPV4 equivalent too. (Dual stack Linux FTW)

OMG it lose form....

u can get file here

http://n1.likeqi.cn:8888/settings.json

or ipV4 visit http://index.likeqi.cn/settings.json

**Comment by Alpherie** [comment]
> You'll need to configure rpc-bind-address to be
> 
> `"rpc-bind-address": "::"`

I have a similar problem. When I set this in config, I get an error:

`RPC Server :: is not an IPv4 address. RPC listeners must be IPv4 (rpc-server.c:1202)`

How do I fix my config to avoid it?

**Comment by treysis** [comment]
Seems like you can't. Unfortunately, currently transmission doesn't seem to support IPv6 for rpc. It even needs an IPv4 configured on the ethernet interface. When I start transmission with only localhost "lo" configured with IPv4, it won't even listen on 127.0.0.1:9091.

I've heard rumors this is working with transmission 3.0.

**Comment by slokhorst** [comment]
This is fixed in transmission 3.00.

1. Stop transmission
2. Edit `settings.json` to read `"rpc-bind-address": "::"`
3. Start transmission

**Comment by samondlee** [comment]
> This is fixed in transmission 3.00.
> 
> 1. Stop transmission
> 2. Edit `settings.json` to read `"rpc-bind-address": "::"`
> 3. Start transmission
Thanks!!!and!!!
Could transmission offer Arm64 \arm release.......

**Comment by samondlee** [comment]
transmission 3.0.0 support ipv6 remote login

**Comment by samondlee** [comment]
transmission 3.0.0 support ipv6 remote login

**Comment by treysis** [comment]
Would be nice if this setting was the default, or at least be configurable from the GUI.
