### ISSUE TITLE
transmission-headless

### ISSUE THREAD

**Issue by Hordeking** [transmission/transmission#939]
Provide a "transmission-headless" that operates in much the same way as transmission-gtk, but doesn't provide a graphical interface. It can run as the user, and could be accessed via transmission-remote.

I'm aware that this functionality is more or less available using transmission-gtk while minimized, and transmission-daemon is more for running a torrent distribution server.

It would be really nice to just have a per-user headless torrent client that if one added torrents using -gtk and closed it, then they could run -headless and have it continue the job.

**Comment by sio** [comment]
I think you've described exactly what transmission-daemon is. Why is it not suitable for you? What would be the differences between -daemon and -headless?

**Comment by Hordeking** [comment]
-daemon uses /var/lib/transmission, a -headless would just be accessed via transmission-remote and only have access to the user's home directory tree. Perhaps a system has multiple users who for whatever reason should not have access to each others' torrents, and who should not have to ask an admin/have root access to move their files out of /var/lib/transmission.

Or maybe the daemon takes care of this with a sticky bit? The docs aren't always super clear about what goes on under the hood, at least that I could tell.

**Comment by sio** [comment]
You can specify any config directory for daemon with `--config-dir` parameter. You can also start the daemon under your user account, or any number of daemons under any number of user accounts.

**Comment by Hordeking** [comment]
I guess that would work. Usually I think of a daemon running as a system account, and a headless as a user account, and so on. But if I can just run it as a user and leave the system daemon in-tact for other purposes, I think that would work for me.

**Comment by sio** [comment]
@Hordeking, if you have no further questions please close the issue.
