### ISSUE TITLE
Torrent file make freeze transmission-daemon

### ISSUE THREAD

**Issue by azlux** [transmission/transmission#943]
Hi,
If you try to download the Parrot ISO from torrent on [Parrot website](https://www.parrotsec.org/download-security.php), transmission-daemon become unresponsive right at the start of the download (RPC server is also unresponsive)

On IRC, some people said it looks like an issue with the daemon because it's works fine with GTK client.

I've compress the torrent file in case Parrot modify the file on their website.
[Parrot-security-4.6_amd64.iso.torrent.zip](https://github.com/transmission/transmission/files/3386814/Parrot-security-4.6_amd64.iso.torrent.zip)

Best regards,
Azlux

**Comment by mikedld** [comment]
Please search for existing issues before opening new ones. See #553.

**Comment by ckerr** [comment]
https://github.com/transmission/transmission/issues/1829
