### ISSUE TITLE
a session config overwrties the other session config

### ISSUE THREAD

**Issue by rezad1393** [transmission/transmission#947]
I use transmission-daemon on openwrt and transmission-qt on my laptop.
when I change the session from the remote openwrt one it seems to overwrite my setting.json on my laptop with the remote one on my openwrt.
for example my download directory folder changes on my laptop instance to the path from openwrt one.
the only way to change it back is to open the local session one again and set it in transmission setting and then (this needs to be done it seems) close the transmission client.
this way the setting that I changed get written to the local setting.

the other way around doesn't happen. if I open the transmission and switch to the remote one and open the setting it shows the correct path and everything it seems.

P.S.
switching between two remote running transmission doesnt seem to have this issue.
(they both show their speed limit and path correctly)
but the setting are not saved back to the remove setting file if I change them in transmission.
so transmission cant change the remote setting file?

**Comment by ckerr** [comment]
This is the same issue as https://github.com/transmission/transmission/issues/1490.
