### ISSUE TITLE
ios upload button not visible

### ISSUE THREAD

**Issue by laouache** [transmission/transmission#956]
Hi,

I have Transmission 2.94 (d8e60ee44f) and on ios the button upload torrent is not visible on webui (on chrome and safari as well). It seems the same as this issue : https://github.com/transmission/transmission/issues/431 but it is not resolved.

Thanks,

**Comment by mikedld** [comment]
The #431 you've mentioned has been fixed in terms of #320 where milestone is set to 3.00. The fix is not in 2.94.
