### ISSUE TITLE
'Verify Local Data' not running when computer locked

### ISSUE THREAD

**Issue by wb6vpm** [transmission/transmission#97]
When running 2.92 (14714) on Mac OS X 10.11.6, and doing a Verify Local Data command and my computer locks the screen, all processing stops until the system is unlocked again. I do not know if it happening to downloads/seeds yet, as I am in the process of importing my existing torrents into Transmission from uTorrent.

**Comment by wb6vpm** [comment]
Also, I do have the keep computer awake checkbox checked.

**Comment by wb6vpm** [comment]
Apparently, restarting Transmission for the 4th time seems to have done the trick...

**Comment by samirfor** [comment]
This issue affects me as well. There is some fix for it?
