### ISSUE TITLE
Port stays closed

### ISSUE THREAD

**Issue by fluffyears** [transmission/transmission#971]
Hi , My peer listening port is closed and I cannot get it to reopen. I have toggled automatic map port with no change. My message log reads as below. what do I need to do to reopen?

Thank you.

Now sorted, back open.

**Comment by libertyx82** [comment]
How you have solved it?

I have the same Problem, transmission says "Port closed" but it is open.

**Comment by txVLN** [comment]
Looks like there's several copies of this issue. Here's the one with the most activity: https://github.com/transmission/transmission/issues/407
