### ISSUE TITLE
listening UDP port wouldn't change

### ISSUE THREAD

**Issue by kristapsdin** [transmission/transmission#973]
after executing "transmission-remote -p PORT" or changing port from web gui, listening TCP port changes but not UDP
checked with "netstat -ltup"
Linux QWE 4.14.133-1-ARCH #1 SMP PREEMPT Tue Jul 16 01:54:40 UTC 2019 armv7l GNU/Linux

**Comment by kaaposts** [comment]
editing peer-port in settings.json and executing "/bin/kill -s HUP $MAINPID" also changes only TCP listening port.

**Comment by mstargard** [comment]
Turns out this is important for anyone dynamically reconfiguring their running transmission with the port from VPN port forwarding.

**Comment by ckerr** [comment]
This should be working now in 4.0.0-beta.2 as a side-effect of #4053
