### ISSUE TITLE
Program hangs for some seconds when start

### ISSUE THREAD

**Issue by k79e** [transmission/transmission#974]
It only happen when I uncheck minimum to tray icon when start.

When it hangs it just become blank!!! (Of course it always blank on start)
![image](https://user-images.githubusercontent.com/6483602/62946147-c1b40500-be12-11e9-9ff9-3fbef9e3b686.png)
When it stucks it need 10-11s to back to normal. i.e It need 10-11s to start.
But if I check that box which make it don't show gui and go to tray icon on start 
Then program will start immediately. If I click tray icon after it appeared I found that gui don't blank. And everything is normal.

I'm using v2.94 x64 on win7x64

**Comment by ckerr** [comment]
Is this still happening in the nightly builds?

**Comment by k79e** [comment]
Tried on 3.00 and it's fine now
