### ISSUE TITLE
Feature Request: Pause Transfers On Battery Power

### ISSUE THREAD

**Issue by pqhf5kd** [transmission/transmission#975]
It would be great to have an option to pause all transfers when disconnecting the power cable from a label and then resuming all transfer when plugging back in.

**Comment by sio** [comment]
Have you considered using scripts (via transmission-remote or JSON RPC) for this purpose?

**Comment by ckerr** [comment]
Transmission tries to KISS as much as possible. IMO this would be better done with third-party tools as suggested by @sio
