### ISSUE TITLE
Cant use devilspie with Transmission since last versions

### ISSUE THREAD

**Issue by gverrey** [transmission/transmission#98]
Transmission doesn't appear for use with Devilspie to classify the desktop windows.

guillaume@whois:~$ devilspie 
Window Title: 'Local Folders - Mozilla Thunderbird'; Application Name: 'Thunderbird'; Class: 'Thunderbird'; Geometry: 1366x741+0+27
Window Title: 'Clementine'; Application Name: 'Clementine'; Class: 'Clementine'; Geometry: 1366x741+0+27
match
Window Title: 'Google - Mozilla Firefox'; Application Name: 'Firefox'; Class: 'Firefox'; Geometry: 1366x768+0+0
match
Window Title: 'guillaume@whois: ~'; Application Name: 'terminator'; Class: 'Terminator'; Geometry: 1366x768+0+0

**Comment by mikedld** [comment]
Any more clarification? What does "last versions" mean? Which client are you running (GTK+, Qt)? I seriously doubt that the issue is with Transmission itself right now...

**Comment by mikedld** [comment]
Please reopen if still relevant.

**Comment by gverrey** [comment]
so old, so young
