### ISSUE TITLE
file-allocation add falloc and trunc?

### ISSUE THREAD

**Issue by kai456789** [transmission/transmission#981]
file-allocation add falloc and trunc?

falloc for ntfs

trunc for ext3

**Comment by xavery** [comment]
Transmission already uses a number of methods for pre-allocating files, if that's what you mean. The relevant function is called [tr_sys_file_preallocate](https://github.com/transmission/transmission/blob/develop/libtransmission/file-posix.c#L845).

**Comment by sedlund** [comment]
Do you know why it fully allocates even though preallocate set to 0 (NONE) on an armhf system with ext4 filesystem on an SD card?

I've tested with magnets and torrent files with the same outcome. 

I then tried qBittorrent on the same system and it correctly allocates only the chunks it is downloading as it is downloading.

**Comment by andreygursky** [comment]
@sedlund, please, make sure in ```/etc/transmission-daemon/settings.json``` (standard location on Debian) the value is set according to your wish (if not, exit the transmission/daemon first, adjust the value and start again):
```
    "preallocation": 0,
```

**Comment by sedlund** [comment]
> @sedlund, please, make sure in `/etc/transmission-daemon/settings.json` (standard location on Debian) the value is set according to your wish (if not, exit the transmission/daemon first, adjust the value and start again):
> 
> ```
>     "preallocation": 0,
> ```

@andreygursky yes it is.  This is an ancient bug from many many years that no one has figured out yet.

```
/data/transmission-home # grep preallocation settings.json
    "preallocation": 0,
```

**Comment by andreygursky** [comment]
Are you sure the data is really preallocated? Perhaps the file is sparse and only 1 or 2 bittorrent pieces are allocated. ```ls``` shows the whole file size (not necessary the file occupies all this space). But it is possible to see the real size on disk.

E. g. for a 999 MB sparse file, where only 3 MB are really allocated:
```
$ ls -h -gG some_file
total 3M
-rw-rw-r-- 1 999M Apr  1  2020 some_file
```

You can see "3M" already. Alternatively you can add ```-s``` parameter:

```
$ ls -h -gG -s some_file
total 3M
3M -rw-rw-r-- 1 999M Apr  1  2020 some_file
```

**Comment by sedlund** [comment]
Yes, it shows the file as fully allocated when using transmission.  It's actually quite difficult to get the output of ls after starting a large torrent in transmission armhf as it completely blocks the system.  I can see the disk LED on solid (raspberry pi) as soon as it starts and the whole system is locked while it is allocating.  This also occurs on android.  I suggest trying it for yourself.  You can start transmission in a docker container with --device-write-bps=/dev/sda:10mb simulating an SDcard  speed.

In comparison with qBittorrent I can run ls -s on the file and see the file growing in the torrent chunk size as the chunks are downloaded.

**Comment by sedlund** [comment]
I found that the full allocation of the sparse file on this system was due to using eCryptFS.  It has to encrypt all the zero's before writing to disk, so sparse files are not possible.  I've since switched it to Luks.

**Comment by queeup** [comment]
> It's actually quite difficult to get the output of ls after starting a large torrent in transmission armhf as it completely blocks the system. 
@sedlund, my atom based system also blocking while downloading torrent from docker transmission. I played almost all settings but no solution.

**Comment by sedlund** [comment]
> @sedlund, my atom based system also blocking while downloading torrent from docker transmission. I played almost all settings but no solution.

Transmission doesn't have asynchronous disk IO.  Everything is single-threaded, so if the disk on the system is slow it will block the webserver.  I've switched to using qBittorrent and made this https://github.com/sedlund/piaqbittorrent .  qBT has asynchronous IO.  Granted you will want to limit the download speed to be lower than your bandwidth if you have slow disk.
