### ISSUE TITLE
reset torrents after HDD failure without re-downloading

### ISSUE THREAD

**Issue by sibero80** [transmission/transmission#984]
My HDD failed and died.  I had around 45 torrents downloading, now they all show error because of the missing data.

Is there a way to reset the torrent metadata so it could start downloading from 0% without having to re-add the 45 torrents? 

Thank you

**Comment by sio** [comment]
Did you try "Force recheck" from the menu?

**Comment by sibero80** [comment]
> Did you try "Force recheck" from the menu?

Yes, bare in mind that the drive with the download data died, so there is no folder containing the incomplete download data. (Transmission shows: No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.)

What I need is to restart the download (and thus re-creating the file and folder structure) the torrent, but without having to browse and re-add each torrent again.

**Comment by kilobyte** [comment]
You don't need to obtain the .torrent files again — as long as you didn't remove them from Transmission's list, they are available in `~/.config/transmission/torrents`; on Windows and Mac I assume they're in a similar directory in your profile.

**Comment by jordanade** [comment]
This happens to me with magnet torrents when the disk fills up. No way to recover gracefully, or there is a way but the UX around it is broken.

**Comment by ckerr** [comment]
This is a variant of #83
