### ISSUE TITLE
[Torrent Properties] Problem with Limit upload speed set to 0 kB/s

### ISSUE THREAD

**Issue by kevvood** [transmission/transmission#987]
If I set the _Limit upload speed_ to _0 kB/s_ on a torrent, its download stops!
Observed on Transmission 2.94+ c11f2870fd Windows 8.1
Cheers

PS
If that behavior was by design, there should be a UI indication. BTW, it's not that I don't want to share the torrent. I was just testing my own JSON CLI.

**Comment by Nikita11790** [comment]
seeds likely are blacklisting you because you're not uploading. or trackers can too

**Comment by ckerr** [comment]
What would be the right way to indicate that downloads won't happen if the upload speed is set to 0?

**Comment by ckerr** [comment]
Duplicate of #127.
