### ISSUE TITLE
block size constraints

### ISSUE THREAD

**Issue by cfpp2p** [transmission/transmission#99]
When a torrent's info dictionary `pieceSize` is less than 16384 {`MAX_BLOCK_SIZE = (1024 * 16)`} the result is block size equal to piece size. Without warning, any block size down to even a block size of 1 is accepted. Overhead is 13 bytes, so this is a situation far from ideal. `metainfo.c` provides no constraints on piece length other than it can't be less than 1.

> Due to smaller requests resulting in higher overhead due to tracking a greater number of requests, implementers are advised against going below 2^14(16KB)

 https://wiki.theory.org/BitTorrentSpecification#request:_.3Clen.3D0013.3E.3Cid.3D6.3E.3Cindex.3E.3Cbegin.3E.3Clength.3E

**torrent.c**

```
uint32_t
tr_getBlockSize (uint32_t pieceSize)
{
  uint32_t b = pieceSize;

  while (b > MAX_BLOCK_SIZE)
    b /= 2u;

  if (!b || (pieceSize % b)) /* not cleanly divisible */
    return 0;

  return b;
}

```
**metainfo.c**

```
  /* piece length */
  if (!isMagnet)
    {
      if (!tr_variantDictFindInt (infoDict, TR_KEY_piece_length, &i) || (i < 1))
        return "piece length";
      inf->pieceSize = i;
    }
```

**Comment by ckerr** [comment]
OK, so we're advised _against_ going below 16 KB, and also everyone closes connections that request more than 16 KB... seems like our range is limited :smile: 

https://www.bittorrent.org/beps/bep_0003.html

> 'request' messages contain an index, begin, and length. The last two are byte offsets. Length is generally a power of two unless it gets truncated by the end of the file. All current implementations use 2^14 (16 kiB), and close connections which request an amount greater than that.

**Comment by ckerr** [comment]
the8472 [also points out](https://stackoverflow.com/a/65299426) "the incentive to use 16KiB-sized blocks [in BitTorrent 2.0] is much stronger now because that is also the leaf hash size."
