### ISSUE TITLE
Nightly not building for Mac 

### ISSUE THREAD

**Issue by JonoHaysom** [transmission/transmission#992]
Hi team, Im not sure if https://build.transmissionbt.com/job/trunk-mac/ is managed by anyone here but its listed in the documents.. its been dead for 6 months now. can it be started again?

**Comment by JonoHaysom** [comment]
Thanks @mikedld :) I see its fixed now

**Comment by JonoHaysom** [comment]
The builds came up for a while but are now dead again for Mac, can it be started again?

**Comment by BenSokol** [comment]
Could Github Actions be setup to build for all platforms and release?
