### ISSUE TITLE
To continue the further revamping of this great software

### ISSUE THREAD

**Issue by TomHsiung** [transmission/transmission#999]
Dear, sir / madam

I like the software of transmission as my default torrent download. I hope the development would continue. And I hope the Mac client could have dark skin mode. Thank you.

Tom

**Comment by Palivec** [comment]
Mac client has dark skin mode, try downloading this version : https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-a440981571.dmg

**Comment by JonoHaysom** [comment]
> Mac client has dark skin mode, try downloading this version : https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-a440981571.dmg

why hasn't the machine been building the latest nightlies?

**Comment by TomHsiung** [comment]
@JonoHaysom Hello, Jono. It is a nice 404 page.

**Comment by ldexterldesign** [comment]
👋 https://github.com/transmission/transmission/issues/644#issuecomment-601979132
